### ISSUE TITLE
Second Dynamics Session

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#10]
Lead = Swap

**Comment by lzim** [comment]
Hi Swap,

This is the "Facilitation Guide" Project Tracking part of GitHub that we can use as we iterate on our PSD facilitation materials.  I've assed the "First Modeling Session," which we discussed this morning, to you.

This "issue" will track the project and we can discuss it here - it will push the updates to Basecamp automatically, so we can track progress there.

I created two "milestones" for this item a "see.Rmd" file and a "say.Rmd" file. We can discuss it here, but I should also see it any updates in my "feed."

Last, if you have questions about specific code, etc.  You can assign this issue to me (or another collaborator from our team) to "review."

Thanks!

Lindsey

**Comment by swapmush** [comment]
Hey Lindsey, 

Thanks for creating this and showing me this function of Github. 
Sounds good, I should have this up by tomorrow evening or Wednesday morning.  

Swap
