### ISSUE TITLE
Co-planning Meeting

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1017]
potential dates for the first two weeks of March (3/2-3/13)

**Travel/OOO Notices:**
Jay: DC in March 4-5 and on AL Feb 27 and March 10
Gayle: Feb 25-27
Jane: Feb 24-25 and March 5-8.
Claire: Travel on the week of 2/24 - 2/28.
Theresa: OOO 25-27
Matt: 3/2-3/3, 3/9-3/13, 3/30-3/31
Claire, Theresa, and Gayle: On travel for part or all of the week of 3/9 - 3/13

Jay Cohen:
608GC Somersworth VA Clinic
Leadership
-	VISN 1 CMHO – David Schafer, PsyD (calendar could not be updated) 
-	Chief/MH Alicia Semiatin, PhD 

Dates (in Team Time’s zone):
1.	Mon 3/9 @1pm Eastern 
2.	Thurs 3/12 @11am Eastern 
3.	Thurs 3/12 @1pm Eastern 

--------------------------------------------------------------------------------------------------------------

John Klocek:
*Note, some of John’s times are in Eastern and some in Central based on the Team’s time zones.
652GA Fredericksburg VA Clinic
Leadership
-	VISN 6 CMHO – David Buyck,, PhD
-	Richmond ACOS - Cheryl Jones, M.D. (need additional contact for Dr. Jones due to health challenges)

Dates (in Team’s Time Zone):
1.	Tues 3/10 @2pm Eastern (11am Pacific)
2.	Fri 3/13 @1pm Eastern (10am Pacific) (This is during our usual MTL Facilitate Friday meeting time)
3.	Fri 3/13 @12Noon Eastern (9am Pacific)  (This is during our usual MTL Facilitate Friday meeting time) 

--------------------------------------------------------------------------------------------------------------
John Klocek:
565GE Robeson County VA Clinic
Leadership
-	VISN 6 CMHO – David Buyck,, PhD 
-	Fayetteville Acting ACOS MH - Ricanthony Ashley, M.D 
-	Fayetteville Acting ACOS MH (as of 1/13/19) - Elizabeth Sullivan, Ph.D 

Dates (in Team Time’s zone):
1.	Mon 3/9 @12Noon Eastern (9am Pacific)  (This is during our usual #Manuscript Monday meeting time)
2.	Wed 3/11 @3pm Eastern (12pm Pacific)
3.	Thurs 3/12 @10am Eastern (7am Pacific)

-----------------------------------------------------------------------------------------------------------------------------------

John Klocek:
580GH Tomball VA Clinic
Leadership
-	VISN 16 CMHO - Irving Kuo, M.D 
-	Houston ACOS MH - Laura Marsh, M.D
-	Houston Deputy ACOS MH - Kaki York, Ph.D 
-	Houston ACOS Ambulatory Care (At Houston, CBOCs under Ambu Care & report to ACOS AC. - Aruna Gottumukkala, M.D.

Dates (in Team Time’s zone):
1.	Wed 3/11 @1pm Central (11am Pacific)  (This is during our usual MTL Facilitate Wednesday meeting time)
2.	Weds 3/11 @3pm Central (1pm Pacific)
3.	Thurs 3/12 @3pm Central (1pm Pacific)

--------------------------------------------------------------------------------------------------------------
Theresa Schmitz:
546GC Homestead VA Clinic
Leadership
-	VISN 8 CMHO – Carri-Ann Gibson
ACOS/MH & BH Miami – Spencer Eth 

Dates (in Team Time’s zone):
1.	Fri 3/6 @12:30pm Eastern (9:30am Pacific) (This is during our usual MTL Facilitate Friday meeting time)
2.	Fri 3/6 @1:30pm Eastern (10:30am Pacific)
3.	Fri 3/6 @2:30pm Eastern (11:30am Pacific)

--------------------------------------------------------------------------------------------------------------
Marcia Hunt:
529 Abie Abraham VA Clinic
Leadership
-	VISN 4 CMHO - Angela Keen, PhD 
-	ACOS/MH - Amy Capretto

Dates (in Team Time’s zone):
1.	Fri 3/6 @4pm Eastern (1pm Pacific)
2.	Mon 3/9 @2pm Eastern (11a Pacific) 
3.	Tues 3/10 @11am Eastern (8am Pacific)

**Comment by lijenn** [comment]
@staceypark Hi Stacey 😄

Format is a bit off, I can fix this later tonight. 

This is for the local co-planning meeting 1 where they meet with the local leaderships and figure out which teams to work with. They would then meet with the team sometime in March. 

However, it was decided that anything through the 21st was too soon so the meetings need to be rescheduled either for next week (2/24 - 2/28) or first two weeks of March (3/2-3/13).

**Comment by lzim** [comment]
Thanks @lijenn!

We have a team convention not to put any emails on GitHub. Would you keep the dates, location, & QIIC, but scrub the emails?

@staceypark

**Comment by lijenn** [comment]
@lzim @staceypark Right, thank you for reminding me! Removed them just now.

**Comment by staceypark** [comment]
Dates have been set.
@lijenn will create the issues for the next steps.
