### ISSUE TITLE
02/20 MTL Video AGG: Do QIICS have AGG Data?

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#1018]
Hi @branscombj 

What did you find? Do we need to upload AGG data for the MTL video reviewers?

Thanks!

Lindsey

**Comment by branscombj** [comment]
@lzim oops the chat was hoppin today; guess my note got buried. The Team Data table and model variables were populated for Agg in Team 2 team world, and I ran a bc with reasonable results.

**Comment by lzim** [comment]
Thanks @branscombj !!
