### ISSUE TITLE
MTL Demo home page needs review and edits

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#1020]
**1. Add description:** 
This page
https://forio.com/app/va/va-psd-demo/mtl_demo.html
![image](https://user-images.githubusercontent.com/29778290/75146538-556f6380-56c9-11ea-83d2-b4ae249723af.png)

1. Has some broken links - test all.
2. The MTL Live icon and line should probably be removed since now you go to How to get either Red or Blue, not just "the Live 12-session plan". 
>Click the icon to see the guides for the Modeling to Learn Live 12-session plan.
3. Also, above that it says "There are 4 versions of Modeling to Learn." Is this confusing as there are 2 versions of MTL Live?
<img width="787" alt="Screen Shot 2020-03-03 at 9 13 16 AM" src="https://user-images.githubusercontent.com/59668647/75801316-c77e2300-5d2f-11ea-90fd-e11863289235.png">

**Comment by staceypark** [comment]
@branscombj @jamesmrollins @ritahitching @lijenn 
We will cover this as part of MTL DEMO Training next Friday March 6.

**Comment by lijenn** [comment]
@lzim Hi Lindsey, Jane brought up excellent thought-provoking suggestions here for the Demo page. 

I wanted to ask if the audience that is brought to mtl.how/demo (people who have the codes from conferences, email interest, possibly MTL for All too (?), etc.) is aware of Red and Blue? 

Asking this because if they are not aware of Red and Blue, would items 2 and 3 remain the same?

**Comment by lijenn** [comment]
From Support WG 3/4/20:
Can update this after other high priority go-live tasks are completed.

**Comment by lzim** [comment]
@lijenn @staceypark @lijenn 

This and #1070 is definitely priority epic! We will definitely be telling people to check this out on Tuesday.
At a minimum, I do think it makes sense to get the MTL Red and MTL Blue icons on mtl.how/demo. 
Cross-ref #1065 - I can't tell what has and has not been done on this?

**Comment by lijenn** [comment]
@lzim Where would the MTL Red and Blue icons go exactly?

1) I was going to follow Jane's suggestion (see number 2 at the top post), but removing the MTL Live icon and replacing it with hyperlinked MTL Red and Blue icons to their corresponding guide would make it hard for people to find mtl.how

2) Keeping the MTL Live icon and also adding the hyperlinked MTL Red and Blue icons may seem a bit redundant (but maybe necessary?) since the MTL Live icon/mtl.how's front page already has hyperlinked images to the Red and Blue guides.

If going with option 2, I just planned to change the description for MTL Live from
>Click the icon to see the guides for the Modeling to Learn Live 12-session plan.

to

> Click the icon to see the guides for Modeling to Learn Red and Blue.

**Comment by lzim** [comment]
> @lzim Where would the MTL Red and Blue icons go exactly?

These would go in the section where it says "There are four versions of _MTL_"
It should now read:

"There are five versions of _MTL_. Are you are at _MTL Demo_" [Note these need to be italicized"
- Then, there should be 5 icons, with _MTL Red_ and _MTL Blue_ replacing _MTL Live_. Make sense?

> 1. I was going to follow Jane's suggestion (see number 2 at the top post), but removing the MTL Live icon and replacing it with hyperlinked MTL Red and Blue icons to their corresponding guide would make it hard for people to find mtl.how
- I think you're misunderstanding @branscombj 
- Please see my instructions above.
- Note these icons are not hyperlinked at all 😸

**Comment by branscombj** [comment]
@lzim is right about my 3 point above, @lijenn and I like her solution.

My point 2 above is regarding the Run Your Test section (screenshot below). The line with the MTL Live icon says "Click the icon to see the guides for the Modeling to Learn Live 12-session plan." I don't know if you want to change which icon goes there (@lzim ?), but it should probably link to mtl.how/blue, if not to blue S05 or blue S05 learner see md directly.

![image](https://user-images.githubusercontent.com/29778290/76252058-8b126180-621e-11ea-8c00-a746f6d07999.png)

Then, the next line has the mtl.how icon and says "Click the icon to review the simulation cheatsheet. All Modeling to Learn resources are available at mtl.how." I don't think an icon should link to a different place than it normally does, so I would not link THAT icon to the cheatsheet. Perhaps just link it to mtl.how as it says, reverse the order of the 2 sentences, and had a "here" link directly to the sim UI cheatsheet once it is finished and located in the main mtl.how repo. In other words:

[mtl.how icon, live link]           All *Modeling to Learn* resources are available at mtl.how. Click [here ](https://github.com/lzim/teampsd/blob/master/resources/cheatsheets/mtl_how_sim_cheatsheet.pdf)to review the simulation cheatsheet.

**Comment by jamesmrollins** [comment]
@branscombj @lijenn @lzim   Regarding Jane's suggestion, 

[mtl.how icon, live link] All Modeling to Learn resources are available at mtl.how. Click [here ](url)to review the simulation cheatsheet.

We cannot provide hyperlinked text in the section of web page.  Only the graphic can be linked.

**Comment by lzim** [comment]
> @branscombj @lijenn @lzim Regarding Jane's suggestion,


Great! for the Icons only:
1. @jamesmrollins can you help with my guidance above about the "5 Versions" of _MTL?_ and swap out the "MTL Live" logo with the two "MTL Red" and "MTL Blue" logos.

Down below where the icons link to the following links @lijenn will do 2 and 3 below:

2. The current "MTL Live" logo will still point to mtl.how, so use the mtl.how logo instead https://github.com/lzim/teampsd/blob/master/resources/logos/mtl_how.png

3. Then for the current "mtl.how" logo that points to the Sim UI cheatsheet in Blue Session 5, continue to link there (@staceypark will upload a cheatsheet there today), but use the mtl.how/sim logo: https://github.com/lzim/teampsd/blob/master/resources/logos/mtl_how_sim.png

**Comment by jamesmrollins** [comment]
@branscombj @lijenn @lzim  Yes, I will document and swap the mtl Live logo with mtl Red and mtl Blue logos. This should be done by Wednesday morning.  BTW, who has the Illustrator files for mtl blue and red?  I need .svg files for the website.   Since svg is vector graphic format, it does much better with responsive design.

**Comment by jamesmrollins** [comment]
@branscombj @lijenn @lzim  Will change as shown below. 

@hirenp-waferwire  Please change mtl.how/DEMO as shown below. Use these .svg files for logos
  - mtl_how_video.svg
  - mtl_how_blue.svg
  - mtl_how_demo.svg
  - mtl_how_facilitate.svg
  - mtl_how_red.svg

Logos are available here [https://github.com/lzim/teampsd/tree/master/resources/logos](url)

![image](https://user-images.githubusercontent.com/30132017/76260496-27376b00-6215-11ea-9db8-55292940a54c.png)

**Comment by lzim** [comment]
> @branscombj @lijenn @lzim Yes, I will document and swap the mtl Live logo with mtl Red and mtl Blue logos. This should be done by Wednesday morning. BTW, who has the Illustrator files for mtl blue and red? I need .svg files for the website. Since svg is vector graphic format, it does much better with responsive design.
> **NEVERMIND - FOUND an AI that will work.**

I have AI for these files if you still need them @jamesmrollins just let me know.
Thanks!

**Comment by lzim** [comment]
@jamesmrollins @lijenn @ritahitching @lrollins33 

Hello Everyone, I wanted to alert you all that in anticipation of **go_live** tomorrow I updated the lead paragraph for _both_ MTL Demo and MTL Team.
- I understand that you have an assignment to make TEST consistent with PROD for Demo.
- Please use this language that is already in PROD.

Thanks! 💥 

**MTL Demo now reads:**
Modeling to Learn is a national quality improvement initiative in the Veterans Health Administration (VA). Funded by the National Institutes of Health (NIH) and VA Health Services Research and Development (HSRD), scientific study of Modeling to Learn is underway to determine its effectiveness increasing delivery of evidence-based addiction and mental health care (NIDA R01DA046651 and R21DA042198 ; HSRD I01HX002521; PI: Zimmerman ). Modeling to Learn supports multidisciplinary teams of frontline psychiatrists, psychologists, social workers, nurses and certified peer support specialists in VA. This demonstration website supports the research effort by providing a simulation demonstration to implementation science and quality improvement researchers, and to patient, provider and policy-maker stakeholders across VA, or other integrated addiction and mental health care systems.

**MTL Team now reads:**
Modeling to Learn is a national quality improvement initiative in the Veterans Health Administration (VA). Funded by the National Institutes of Health (NIH) and VA Health Services Research and Development (HSRD), scientific study of Modeling to Learn is underway to determine its effectiveness increasing delivery of evidence-based addiction and mental health care (NIDA R01DA046651 and R21DA042198 ; HSRD I01HX002521; PI: Zimmerman ). Modeling to Learn supports multidisciplinary teams of frontline psychiatrists, psychologists, social workers, nurses and certified peer support specialists in VA. Modeling to Learn was developed by a multidisciplinary team of scientists and partners known as Team Participatory System Dynamics or Team PSD. Read below to learn more about who we are and what we do.

**Comment by lijenn** [comment]
@ritahitching @lrollins33 

Also wanted to let you both know to make the following changes within your Demo instances as well. These changes are also reflected in Prod already (see my screenshot)

1) The current "MTL Live" logo will still point to mtl.how. Change the MTL Live logo to the mtl.how logo instead (can be found here https://github.com/lzim/teampsd/blob/master/resources/logos/mtl_how.png)

2) For the current "mtl.how" logo that points to the Sim UI cheatsheet in Blue Session 5, continue to link there (@staceypark will upload a cheatsheet there), but use the mtl.how/sim logo (can be found here)https://github.com/lzim/teampsd/blob/master/resources/logos/mtl_how_sim.png

<img width="1083" alt="Screen Shot 2020-03-10 at 7 31 21 AM" src="https://user-images.githubusercontent.com/59668647/76323242-b0947f00-62a1-11ea-9650-c3075dac4155.png">

**Comment by lrollins33** [comment]
@lijenn  @ritahitching  @jamesmrollins  I have made all updates to mtl demo (dev). It appears to be working with Stacey's cheatsheet and red/blue guides.

**Comment by branscombj** [comment]
Hi @lrollins33 ! Nice to meet you!!

**Comment by lrollins33** [comment]
Hi @branscombj , Nice to meet you too. I am slowly getting the hang of things on GitHub and Epicenter.

**Comment by lijenn** [comment]
@jamesmrollins Seems like the changes have been reflected onto MTL Demo. Thank you for getting that to us so fast :) !!

@ritahitching Were you able to make the changes to your instance? If so, I believe this card can be closed.

**Comment by ritahitching** [comment]
@jamesmrollins  @lijenn 
Yes, I believe it's ready to close. I was waiting on @jamesmrollins james to confirm all is well.
thanks,

**Comment by staceypark** [comment]
@jamesmrollins has said this can be closed.
