### ISSUE TITLE
wave1_teams Task: Ordering Cameras & Monitors

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#1021]
Order cameras and monitors for Facilitators 
List of requirements in issue #890
Shipping documentation can in TeamPSD folder.

**Comment by ritahitching** [comment]
Cross reference #890 - list of requirements and shipping documentation can be found there.

**Comment by ritahitching** [comment]
Discuss at HQ meeting Thursday Feb 27 and at MTL Facilitate Launch Friday 2/28.
Waiting on budgetary confirmation from Lindsey.
Purchases to likely be made via Amazon.

**Comment by ritahitching** [comment]
@lzim do you have an update on the budget allocation, so that I can move forward with this issue.
thanks, Rita

**Comment by lzim** [comment]
@ritahitching please provide an estimate tomorrow, thanks!

**Comment by ritahitching** [comment]
> @ritahitching please provide an estimate tomorrow, thanks!

Is is estimated as 2 points.

**Comment by lzim** [comment]
@ritahitching as we clarified at the meeting 

Next week, please email  me the inventory of items to be ordered and the total cost ($). Thanks !

**Comment by ritahitching** [comment]
@lzim I just sent you an email with an estimated cost for the purchase of cameras and monitors.
thanks

**Comment by ritahitching** [comment]
Confirm we have home shipping details for all facilitators

**Comment by ritahitching** [comment]
Decision from HQ meeting (March 3/19) to table this issue for now.

**Comment by staceypark** [comment]
@ritahitching for #1021 and #1022, if these have been tabled in a meeting, please make sure to move them to the appropriate epic so we have accurate data.

**Comment by ritahitching** [comment]
@staceypark from what I recall at our HQ meeting 3/19, we decide to place a hold on purchasing equipment for now, but no instructions was given to move the issues to teams_sim, and as such as did not move the issues over. In light of this morning meeting perhaps it makes sense to move #1021 and #1022 now to teams_sim. I'll move them now.
thanks

**Comment by staceypark** [comment]
@ritahitching I'm not sure what the specific guidance is for this task in terms of ordering, but if we don't have the equipment even ordered, at the very least #1022, which is for shipping, wouldn't be feasible by friday.

**Comment by ritahitching** [comment]
@ritahitching update
David L. has provided guidance on his preferred type of monitor - TeamPSD file is shared drive requisitions_qiics_cameras_documents updated

**Comment by ritahitching** [comment]
@lijenn the list of requests for additional IT equipment is on the shared drive with postal address details for each QIIC.
I recommend keeping this issue open.

**Comment by lzim** [comment]
@ritahitching 

Where is this purchase list in the Team PSD folder?

FYI @staceypark  and @lijenn

**Comment by ritahitching** [comment]
File is called **requisitions_qiics_cameras_monitor** under **pavir_expenses** folder

**Comment by lijenn** [comment]
Closing as orders have been approved and are being shipped out. Will re-open if any issues occur.
