### ISSUE TITLE
wave1_teams Task: Shipping Cameras and Monitors Facilitators

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#1022]
Shipping of monitors and cameras to Facilitators - addresses in TeamPSD drive
Cross reference #890 list of requirements
Cross reference #1021 ordering status

**Comment by ritahitching** [comment]
Waiting on response from Debbie - all other Facilitators have responded.

**Comment by staceypark** [comment]
@ritahitching I notice that this issue # #1021 are in the "go_live" milestone, but the "team_data" epic. Given that for now, we decided that epics = milestones, I'm not sure why these are inconsistent.

Also I see both of these issues are in the "bug_tracker", but as we discussed before when getting oriented to ZenHub, we can have issue cards that are not applicable to any of the four trackers (a lot of HQ items are like this! 😅 ). Bugs = existing features that are broken, which are not applicable for #1021 and #1022.

**Comment by ritahitching** [comment]
@staceypark thanks for the instructions.
I updated issue #1021 and #1022 accordingly.

**Comment by ritahitching** [comment]
Decision from HQ meeting (March 3/19) to table this issue for now. Moved to wave1_teams epic for May 2020.

**Comment by dlounsbu** [comment]
From: Hitching, Rita M. <Rita.Hitching@va.gov> 
Sent: Friday, June 05, 2020 6:06 PM
To: david lounsbury <david.lounsbury@einsteinmed.org>
Subject: RE: Emailing: Copy of revise Healing Communities Study budget 8 22 19.xlsx

Hi David,
Thank you for letting me know.
I’ll keep a record of the computer monitor you want, and I’ll order & ship it to you when we place the order for the equipment needed by all the facilitators via PAVIR.
Please let me know if you have an questions or need any additional assistance.
best,
Rita


From: david lounsbury <david.lounsbury@einsteinmed.org> 
Sent: Friday, June 5, 2020 11:19 AM
To: Hitching, Rita M. <Rita.Hitching@va.gov>
Subject: [EXTERNAL] FW: Emailing: Copy of revise Healing Communities Study budget 8 22 19.xlsx


Hi Rita:

I decided to go ahead and order the laptop. 

Let me know if ordering a 2nd monitor and expensing it to Einstein’s next subk invoice is okay. 

Or would you prefer order and ship to me? I can provide the campus address to ship to, if this is the preferred way.

DL

**Comment by ritahitching** [comment]
@ritahitching update
@lijenn FYI
David L. has provided guidance on his preferred type of monitor - TeamPSD file is shared drive requisitions_qiics_cameras_documents updated

**Comment by ritahitching** [comment]
@lijenn the list of requests for additional IT equipment is on the shared drive with postal address details for each QIIC. It is associated with #1021
I recommend keeping this issue open.

**Comment by lijenn** [comment]
David and Debbie's monitors are on the way, expected to arrive by tomorrow or Monday 10/5 at the latest. Closing issue unless shipping error occurs.

**Comment by dlounsbu** [comment]
Hi @lijenn 

The second monitor was delivered to my office on 10/1/2020. I will scan the packing slip. Should I attached the scanned image here? 

Thanks so much, David

**Comment by lijenn** [comment]
Hi @dlounsbu!
Great to hear you got the monitor! Don't upload the scanned image here, feel free to email it to me or just it to me on Teams please :)
