### ISSUE TITLE
wk4 Task: Co-planning Scheduling Sites

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1024]
- [x] Matt - 5 sites
- [ ] Marcia - 4 sites
- Reached out to Marica, no response yet.
- [ ] Theresa - 2 Sites
Dates have been sent, email tbd??
- [ ] Claire - 1 site

**Comment by lzim** [comment]
@lijenn 
Cross-ref my comment on #1025 - thanks! 
🏂

**Comment by lijenn** [comment]
Closing for Nov Epic, remaining sites needed to be scheduled and tracked in Dec. epic card:
- Marcia: 3/4 Sites
- Theresa: 2/2 sites
- Claire: Hold off unless we need an additional Red site.
