### ISSUE TITLE
5/1 Co-Planning Scheduling Sites (Rita)

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1025]
**Rita Scheduling**
652 - ~John~ Matt
No contact made as yet

**Rita Scheduling**
580 - ~John~ Gayle 
No contact made as yet

**Rita Scheduling**
506 - Matt
~**Thurs 3/19 at 8AM Pacific**~
Cancelled due to COVID-19

**Rita Scheduling**
583 - Matt
~**Thurs 3/19 at 9am Pacific**~
Cancelled due to COVID-19

**Rita Scheduling**
VISN 8 - Theresa
**Fri 3/13 at 6:30am Pacific**
Call went ahead

**Comment by ritahitching** [comment]
#1017

**Comment by ritahitching** [comment]
1. Confirm that co-planning calls are in Lindsey's calendar
2. Changes to LucidMeeting Calendar

**Comment by lijenn** [comment]
Updates @ritahitching 
- Matt has been scheduled for Ann Arbor.
- Theresa's dates have been updated.

**Comment by ritahitching** [comment]
Matt   Moore | HQ: Rita
-- | --
Site | 506 Ann Arbor   VA Medical Center
Leadership | VISN   10 CMHO – Jesse Burgard, PhD
  | ACOS/MH –   Charles Surber, MD
Dates   | **Thurs 3/19 @11am Eastern (8am   Pacific)**


Theresa   Schmitz | HQ: Rita
-- | --
Site | 546BC Homestead**   VA Clinic
Leadership | VISN   8 CMHO - Carri-Ann Gibson
  | ACOS/MH   & BH Miami - Spencer Eth
Dates |  **Fri 3/13 @9:30am Eastern (6:30am Pacific)**

**Further discussions taking place

Estimate - 2 hours for calendar issues

**Comment by lzim** [comment]
@lijenn and @ritahitching 

Can we please edit these posts to make them less identifiable? 
There is no need to post this much information here.

An example of all you need is:
**Rita Scheduling
506 - Matt
Thurs 3/19 at 8AM Pacific**

I will be deleting any information not removed by our huddle.
Thanks!

**Comment by lijenn** [comment]
@ritahitching I just scheduled
583 - Matt
For: Thurs 3/19 at 9am Pacific

Will need to remove the tentative hold outs for the following in Lindsey's calendar:
Wed 3/11 at 6:30am Pacific
Fri 3/20 10am Pacific

Thanks!

**Comment by ritahitching** [comment]
Done, thanks!

**Comment by lzim** [comment]
@ritahitching edited your comment to be consistent with the SOP! Please be sure to always post through GH, not email. Thanks!

**Comment by ritahitching** [comment]
@lijenn FYI VISN details

**Comment by ritahitching** [comment]
@lijenn you already know the status of our efforts to reach out to the VISNs and the bandwidth of each QIIC..  
I recommend consolidating this issue with yours #1024 or keeping it open.

**Comment by lijenn** [comment]
closing to merge with 1024 to keep it all in 1 place.
