### ISSUE TITLE
Review See and Say Guides for Partner Phase S1 - S4

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#1029]
**Review See and Say Guides for Partner Phase** 

S1 and S2
S3 and S4

1. data_ui and team_data_table
2. A2 box information
3. History of clinics
4. Clinic stepped care
5. Clinic selection
6. Hidden control tab (remove from guide)
7. Use of Chrome (use disclaimer in forio/epicenter)
8. Power pivot and CPT codes

**Comment by ritahitching** [comment]
Review guides for changes attributed to MTL 2.0, including

Session S1 and S2 & S3 and S4

1. Requests - team world & team folder - **data_ui** and **team_data_table** 
2. A2 box information
3. History of clinics
4. Clinic stepped care
5. Clinic selection
6. Hidden control tab (remove from guide)
7. Use of Chrome (use disclaimer in forio/epicenter)
8. Power pivot and CPT codes
 
Gifts
Add disclaimer under all gifts that they refer to MTL 2.0 and may differ from videos

**Comment by ritahitching** [comment]
@lzim 
I'm comparing the videos to the See guides for the partner phase. There is no instruction in the See Guide on how to find/access the guides themselves - which is mentioned in the videos.  

1. Should we need to add a line to the See Guides to provide directions for learners on where/how to find all the Session Guides? 

Something like:
**"Open any Internet browser window and go to mtl.how - where you'll find all the Session Guides for _MTL_.  For today's session select Session 1."**

2. Should we add the message above to every session guide?

thanks!

**Comment by staceypark** [comment]
@ritahitching @lijenn 
I'm not sure why the ask here sounds like Rita is universally adding a disclaimer to all the gifs, if 1) Gifs are on Jenn's plate and 2) as such only Jenn would know where to add the disclaimer.

> ## **Session S1 and S2 & S3 and S4**
> **Images**
> 
> 1. Add disclaimer under all gifts that they refer to MTL 2.0 and may differ from videos
> 2. For all 12 sessions, use the title slides logo found here
>    **Reminder:** These logos should remain "unclickable".
>    **Only update** the logo link within the brackets and leave the text in the parentheses that ensure these are unclickable.
> 
> ```
> [<img src = "https://github.com/lzim/teampsd/blob/master/resources/logos/mtl_live_sq_sm.png"
>      height = "175" width = "290">](#DontLink)
> ```

**Comment by staceypark** [comment]
My stab at this question would be:
1. The learners are taught how to get to the guides in Session 01.
2. If they don't know how to get there anyways, I'm not sure how putting it in the See Guides would help them? They would already need to know how to get to the Guide to see this message you're proposing. If they do need that instruction, it would need to be elsewhere.
3. Remember, most platforms (including Internet Explorer) DO NOT support GitHub anymore. So we **never** want to be directing them to open up GitHub in Internet Explorer.


> @lzim
> I'm comparing the videos to the See guides for the partner phase. There is no instruction in the See Guide on how to find/access the guides themselves - which is mentioned in the videos.
> 
> 1. Should we need to add a line to the See Guides to provide directions for learners on where/how to find all the Session Guides?
> 
> Something like:
> **"Open any Internet browser window and go to mtl.how - where you'll find all the Session Guides for _MTL_. For today's session select Session 1."**
> 
> 1. Should we add the message above to every session guide?
> 
> thanks!
