### ISSUE TITLE
Update logos in MTL Red & Blue SEE & SAY guides

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1032]
Update logos in MTL Red & Blue for both SEE & SAY guides according to the below:

1. R01 & IIR comparator arm RED SEE & SAY guides - 
- [ ] Part 1 will have the logo: "mtl part 1 over data UI" (Dependency on Lindsey to create the logo)
- [ ] Part 2 will have the logo: "mtl part 2 over team data" (Dependency on Lindsey to create the logo)

2. BLUE SEE & SAY guides 
- [ ] for all 12 sessions, use the title slides logo found [here](https://github.com/lzim/teampsd/tree/master/resources/title_slides)

### Reminder: These logos should remain "unclickable". 
Typically, for an image we use the brackets [ ] to indicate the image source link and the parentheses ( ) to indicate what link the image should point to. 

Anthony & Ash worked on all of the SEE & SAY guides to ensure none of the top logos (not icons) pointed anywhere by putting in text in the parentheses portion. Notice in the example below, it uses "(#DontLink).

```
[<img src = "https://github.com/lzim/teampsd/blob/master/resources/logos/mtl_live_sq_sm.png"
     height = "175" width = "290">](#DontLink)
```

**DECISION**: Only update the logo link within the brackets and leave the text in the parentheses that ensure these are unclickable.

**Comment by staceypark** [comment]
@ritahitching @lijenn let's divvy the work as:
Rita: Blue SEE Sessions 1-12 
Jenn: Blue SAY Sessions 1-12

**Comment by ritahitching** [comment]
@staceypark @lijenn 

logo to be fixed no link from the title slides for each session  (https://github.com/lzim/teampsd/tree/master/resources/title_slides)

Rita: Blue SEE Sessions 1-12

Jenn: Blue SAY Sessions 1-12

**Comment by staceypark** [comment]
I'm not sure what you mean by this comment. Is there a specific ask here?

> @staceypark @lijenn
> 
> logo to be fixed no link from the title slides for each session (https://github.com/lzim/teampsd/tree/master/resources/title_slides)
> 
> Rita: Blue SEE Sessions 1-12
> 
> Jenn: Blue SAY Sessions 1-12

**Comment by staceypark** [comment]
@ritahitching @lijenn It looks like you guys broke down this task further, since I see Rita made a card specific to working on Blue sessions 1-12 See and Say.

Jenn, if you're working on the rest, please make a new card for that and close this. As it stands right now, Rita has both this card and the Blue Sessions 1-12 SEE/SAY card in the "In Progress" column which is confusing.

**Comment by staceypark** [comment]
@lijenn @ritahitching 
I've assigned the Red to @anthonycpichardo on #1059.
Since the Blue is tracked on #1050 , I am closing this issue.
