### ISSUE TITLE
Second Wifi Hotspot

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1034]
**Ask PAVIR if we can get a second free wifi hotspot**

**Comment by ritahitching** [comment]
@lzim 
I spoke with Mary at PAVIR and she will give us a second WiFi Hotspot. It should be available to pick up within the next 2 weeks, if not sooner. Mary will email me to let me know when the Hotspot is available for pick up. I'll go by PAVIR to pick it up as soon as I hear from Mary.
thanks,
Rita

**Comment by lzim** [comment]
@ritahitching Great News, thanks!

**Comment by ritahitching** [comment]
@lzim what are you thoughts on moving thus issue to the ice box until our remote working situation changes? thanks

**Comment by ritahitching** [comment]
@lzim in light of the current remote working set up, I'll move this issue to the next Epic teams_sim, please let me know if this is not appropriate. thanks

**Comment by ritahitching** [comment]
@lijenn FIY 
I'll forward you the email of the person I have leased with to get the previous hotspot and add it to the thread on Teams.

**Comment by lzim** [comment]
Hi @ritahitching @lijenn @staceypark!

Rita, please add this issue # and details to the hq thread on the hq_workgroup channel.

Also, please keep Stacey and I in the loop, we don’t want the sole responsibility to fall to one person. We’ll want to support this transition as a team. Thanks! ⛹🏻‍♀️

**Comment by ritahitching** [comment]
@lijenn there is no current need for an additional WiFi but if the need returns I provided you with the contact details for Mary Thornton at Pavir.

**Comment by lzim** [comment]
@lijenn With COVID19 I think this can either be closed or out in the icebox for some time when we return to the office.
