### ISSUE TITLE
DUE 2/28/20 - MTL Facilitate Workgroup - mtl.how Front Page Edits + Additions

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1035]
From the Wed. Feb. 26th MTL Facilitate Launch 2020 Meeting:

1) Currently, TMS MTL Video disclaimer say that the videos reflect the MTL 1.7 release and should still be really helpful (and they are accredited). But there are new & exciting features available now in MTL 2.0, which are reflected in the guides at mtl.how!

- [ ] Disclaimer needs to be at the top and reflect MTL 2.0
- [x] Can we also include screenshot in TMS so that folks are not surprised when they navigate mtl.how? 

YES - BUT ONLY if we take screenshots and put them in a **word document or PDF**, TMS can add the updated announcement as a handout in the courses.

- [ ] If so, we want to include a MTL 1.7 Screenshot and a MTL 2.0 Screenshot - that explains what to expect and what they should do.

2) - [ ] Add roadmap to help better orient Red and Blue users (complete roadmap on Friday training)

3) - [ ] Create Press Kit

4) - [ ] 1.7 Videos

**Comment by lzim** [comment]
@lijenn 

I could use your help with this. But, I will take the lead on the edits!
I'm going to assign myself.

Lindsey

**Comment by lzim** [comment]
@lijenn 

I could use your help with this. But, I will take the lead on the edits!
I'm going to assign myself.

Would you please create a separate issue for the "map," also assign it to me for 5 points?

Thanks!

Lindsey

**Comment by lzim** [comment]
Done and published
