### ISSUE TITLE
Triage Data Connection Refresh

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1036]
Would like to remove the data refresh button from the splash page (mtl.how/data).

Goal is to prevent users from seeing the error if they happen to click the data refresh.

 Need to triage on splash page if this is possible

**Comment by anazariz** [comment]
This issue should be closed. Data Refresh in the SplashMothership workbook is now performed via code attached to the Refresh button on the Control sheet.  

Please close @anthonycpichardo

**Comment by anthonycpichardo** [comment]
Misunderstanding Ash, This issue is to research and find out if we can remove the data refresh button from the splash page so that the users cannot click it. @anazariz

**Comment by anthonycpichardo** [comment]
@lzim @staceypark @anazariz 

For this, we can update the page to show the Data refresh button, but it needs to be done individually per SplashChart, it is also being set from the SplashMothership, I can make the updates by hand this time, but we will need to modify the code for the future or it will be reintroduced

**Comment by lzim** [comment]
> @lzim @staceypark @anazariz
> 
> For this, we can update the page to show the Data refresh button, but it needs to be done individually per SplashChart, it is also being set from the SplashMothership, I can make the updates by hand this time, but we will need to modify the code for the future or it will be reintroduced

Okay, thanks @anthonycpichardo 

Let's make sure this is on #626 and put in the **teams_sim** epic for when we propagate the splashpage next!

**Comment by anthonycpichardo** [comment]
Sounds good, I will take screen shots of the process to make changes to the web app.

**Comment by anthonycpichardo** [comment]
Manually Updated The Splash Pages to address the data refresh issue. Also outlined sites that are too large to be loaded into the sharepoint. Closing this  and moving any relevant details to #626
