### ISSUE TITLE
mtl.how/data folder creation/management for "MTL all

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1040]
Create workflow for managing world creation requests by "MTL for all" teams

**Comment by staceypark** [comment]
@lzim I've been mulling about this and #1039 (sim folder management).
Until we fix the LSV issue for the teams_data epic, even if we provide folders for folks, they won't be able to query their own data. If they can't query their own data, then they have nothing to put into the sim.

Option 1:
Stacey creates folders at mtl.how/data, asks for grids list, and creates both data_ui and team_data_table files, and put it in the sim

Option 2: 
We present the setup as:
Send us your information needed to create team folders by Friday 3/13.
You will have everything you need by Friday 3/20? (team_data launch date, by which both the LSV issue should be resolved and Jenn/Rita will be trained to manage the data folders)

**Comment by lzim** [comment]
@staceypark 

These dates are way too short. 

I’m thinking something like “We will begin creating Team Folders in April.”

**Comment by anthonycpichardo** [comment]
This has been completed.

**Comment by lzim** [comment]
> This has been completed.

@anthonycpichardo 
Will you put "We will begin creating team folder in April 2020."

Thanks!

**Comment by anthonycpichardo** [comment]
@lzim  happily! 

Updating both "New Team Folder" and "Team Membership Change" and closing this issue =).
