### ISSUE TITLE
BACKLOG MTL Videos YouTube & Public Affairs

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1041]
@AnnHier we have a new function in our Simulation User-Interface called the "Tutor" function, for helping user walk through the platform. One piece of the "Tutor" function is a "video icon" that we want to link directly to the MTL Videos for learners to watch the video walkthrough.

In order to link the videos, we would need to post them to YouTube. Can we confirm that this is okay?

**Comment by AnnHier** [comment]
@staceypark, I think that would be okay - but we need to check really quickly with Elizabeth Bowling.  Would you like EES to give you the video files for posting, or would you like us to post them for you?  Just let us know.

**Comment by lijenn** [comment]
@lzim is currently reviewing the requirements and guidelines for getting YouTube videos up through the VA.

**Comment by lijenn** [comment]
8AM WG Leads 8/10:
- Have an HQ member keep an eye on this (I can do it since I was in previous contact with Public Affairs)
- Send Lindsey the video requirements to get MTL videos up on VA YouTube

**Comment by lzim** [comment]
moved to backlog
