### ISSUE TITLE
DUE 2/28/20 - MTL Facilitate Workgroup - mtl.how Map

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1042]
From the Wed. Feb. 26th MTL Facilitate Launch 2020 Meeting:

- [ ] Need to create and add a "map" to help better orient Red and Blue users onto mtl.how front page.

Requirements:

Will appear in the middle of the page

- Landing Page Map to tell people where they get the guides.

- Map would answer this question Visually and with Links:

Is your clinical care team participating in MTL LIVE with a facilitator?

- Yes, and I am in a red team.

- Yes, and I am in a blue team.

- No, I am learning on my own using the videos.

**Comment by lzim** [comment]
Done and published

**Comment by branscombj** [comment]
Hi @lijenn @lzim I love the map! It's very helpful and easy to read. I'm just wondering about the I am learning with MTL Video/No --> Go to mtl.how/red. Might we want people who are just curious and want to look at guides to see the Blue ones?

**Comment by lzim** [comment]
> Hi @lijenn @lzim I love the map! It's very helpful and easy to read. I'm just wondering about the I am learning with MTL Video/No --> Go to mtl.how/red. Might we want people who are just curious and want to look at guides to see the Blue ones?

@branscombj good question. I’m glad you like it 😸 

It’s not my first priority to address the “just curious” crowd outside of what we offer at mtl.how/demo - which is essentially everything except the ability to upload your own local VA team data table.

But, we could add to this line to the main mtl.how README.md page:
**“Just curious about _Modeling to Learn_? Check out [mtl.how/demo](https://mtl.how/demo).”**

**Comment by lijenn** [comment]
I can add that COB today, thanks all!
