### ISSUE TITLE
4/24: Quick Tip Loading Screen

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1044]
Replace the current loading screen "..." with a quick tip for users to improve their experience on the platform.
 

Note: This may move into the icebox

**Comment by lzim** [comment]
@jamesmrollins @dlkibbe 

At today's Workgroup Leads meeting Debbie will connect James with the "quick tips" used as pop-ups in _MTL Video_
[Insert: 🐦 Inside joke about "birds" 🤣 ]
Thanks!

**Comment by jamesmrollins** [comment]
Here is an example from Lucid Charts.

![image](https://user-images.githubusercontent.com/30132017/77936179-629ee580-7267-11ea-9346-3a3e1f9d92f4.png)

**Comment by jamesmrollins** [comment]
**Team PSD**
Here is the RVTM for this issue:
[#1044 Quick Tip Loading Screen rtvm.xlsx](https://github.com/lzim/teampsd/files/4417218/1044.Quick.Tip.Loading.Screen.rtvm.xlsx)

Here is the wireframe for this issue:
[1044-Quick Tip Loading Screen.pdf](https://github.com/lzim/teampsd/files/4417221/1044-Quick.Tip.Loading.Screen.pdf)

Please let me know your feedback.

**Comment by dlkibbe** [comment]
@jamesmrollins would it be easiest if I inserted potential tips into sheet 2 of this excel file by session number?

**Comment by lzim** [comment]
@jamesmrollins @staceypark 
Reviewed at 4/1/2020 Support Workgroups Leads Meeting
1. Admin panel is great. 
2. Go with all white on grey, no color
3. Use existing _MTL_ iconography for the tips.
4. Reduce the "Loading" indicator to either the existing dots or something smaller & white to compete less (visually) with the tip.

**Comment by jamesmrollins** [comment]
@dlkibbe You don't have to use the spreadsheet to list out quicktips.  That is the RTVM and it just governs the requirements of the design.  We will have an admin panel to put in the quick tips, so you can give it to me in any text form, or just wait for the admin panel to be put into test.  We plan to combine the quick tips with our existing iconography in the Sim UI.

**Comment by jamesmrollins** [comment]
@lzim it looks like I was off by 4 hours.  DEV will need 20 hours to implement this design. ~James

**Comment by staceypark** [comment]
From 4/1/32020 Workgroups Leads Meeting
1. James will provide instructions for Jane & Debbie to test quick tips loading screen and populate tips in the admin panel by end of week
2. Once tips are populated, James will create & add logos for each tip

**Comment by branscombj** [comment]
> From 4/1/32020 Workgroups Leads Meeting
> 
> 1. James will provide instructions for Jane & Debbie to test quick tips loading screen and populate tips in the admin panel by end of week
> 2. Once tips are populated, James will create & add logos for each tip

Hi @jamesmrollins , Do we have these directions or could you clarify for me where we are with this? Thanks! Jane and @dlkibbe

**Comment by jamesmrollins** [comment]
@branscombj @dlkibbe I will write up the instruction sheet this morning and get you a link. Its pretty simple, shouldn't take long. ~James

**Comment by jamesmrollins** [comment]
@branscombj @dlkibbe addendum - looks like I have found a bug while writing up instructions!  Will resolve and let's try again tomorrow. Sorry for any inconvenience ~ James

**Comment by jamesmrollins** [comment]
**PLEASE DO NOT USE - THIS IS A WORK IN PROCESS**

### Testing and Validation Document

Test/validate assignee: 
Test case document available here: 

Please check off these requirements as they are validated.  

- [ ]  1.  Devise a loading screen design that directs user attention to a helpful tip or feature in the Sim UI.
   - [ ] 1.1 The number of tips that can be authored are unlimited.
   - [ ] 1.2 The tips are presented between:
      - [ ] 1.2.1 Home page and Play page.
      - [ ] 1.2.2 When the simulation is run.
      - [ ] 1.2.3 When the simulation is reset.
   - [ ] 1.3 When all tips are presented in the sequence, the tips recycle from highest number to lowest number.
- [ ]  2.  Devise an administration panel where a user may create, in a numerical sequence.
   - [ ] 2.1 Provide a text field to accommodate up to 250 characters to narrate the tip or helpful hint.
   - [ ] 2.2 Provide a field to accommodate the filename of the graphic used in the tip.
   - [ ] 2.3 Provide an editable sequence number to govern the order of appearance of the tips.

**Comment by dlkibbe** [comment]
[QuickTips v2.docx](https://github.com/lzim/teampsd/files/4504633/QuickTips.v2.docx)

@jamesmrollins attached is the next version of the Quick Tips file first developed by @branscombj 
This file was also sent via email. Let us know if you have questions.

**Comment by lzim** [comment]
> Thank you @dlkibbe ! I will get back to you if I have questions and otherwise upload these tomorrow.

- Thanks, @branscombj and y'all! 😸

**Comment by branscombj** [comment]
@jamesmrollins All the tips for those listed are uploaded. I checked everything off above, although I believe we altered a couple of the requirements about cycling-through pattern. 
I think this can be closed.

**Comment by jamesmrollins** [comment]
Thanks @branscombj !!
