### ISSUE TITLE
Session 02 , 03 , 05 Discrepancies

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1045]
Session 02 and Part 1 Discrepancies
Update see and say guides to reflect the following:

1. Data - Refresh Connections" button needs to be taken out. All of that has been changed in terms of the data refresh workflow and but we are removing this from the Splashpage and guides, because they can no longer do that.

 

2. We no longer show an Excel sheet in the Splashpage. Interaction is through the grey buttons and the View dropdown, not through the tabs in the Excel.

 

3. What can and cannot be shown in the videos? Different parts of the data UI seem to be greyed out in the GIF vs. in the data UI 

- In the data UI, everything from "Default Provider" and on are greyed out.

- In the gif, everything from "Clinic Name" and on are greyed out.

 

4. Patient SSID is no longer asterisked out in the Splashpage. Has been completely removed.

 

5. No longer need to select station from control tab because there will be station specific data UI for every facility.

**Comment by staceypark** [comment]
Closing this with merged #1086
