### ISSUE TITLE
Blue SEE Guides S1-4 and Red SEE Guides Part 1 & 2:  GIF and Links

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1049]
Nevermore 
- A2 language
- Create Team Data button
- Get clinic list - Ash fixing function right now (Splash page issue)
1. Pull up old history of clinics (419?)
2. model_params tab
3. check if SP tabs is described in guides
3. power pivot drill down fidgets? (new feature not in guide or gifs)
4. Clinic tab --> 2 gray buttons
5. control tab will be hidden of we propagate all their data ui to their splashpages (blocked by LSV)
6. Patient Data & team data:
- 2 drop downs
   - which data will you pull
     - SP, CC, MM, etc.
         - will put out a 0 whenever you don't pull -> new feature

From SIM for Blue:
- include gif of mtl.how/sim showing the red notice saying to use IE vs Chrome

Blue See Guides
S1:
- [x] data_ui_login.gif
- [x] session2_data_ui_2.gif

S2:
- [x] data_ui_login.gif
- [x] session2_data_ui_2.gif
- [x] data_ui_login.gif
- [x] data_ui_splashpage.gif
- [x] session2_data_ui_2.gif
- [x] session2_data_ui_4_viz_diag.gif
- [x] session2_data_ui_2.gif
- [x] session2_data_ui_4_viz_diag.gif

S3:
- [x] session2_data_ui_4_viz_diag.gif
- [x] session3_data_ui_params.gif
- [x] session3_data_ui_params.gif
- [x] session3_data_ui_params.gif
- [x] mtl_menu.gif

S4:
- [x] mtl_menu.gif
- [x] mtl_menu.gif
- [x] mtl_menu.gif
- [x] sim_ui_1.gif

Red See Guides
Part 1:
- [x] data_ui_login.gif 
- [x] session2_data_ui_2.gif

- [x] data_ui_login.gif
- [x] data_ui_splashpage.gif
- [x] session2_data_ui_1.gif
- [x] session2_data_ui_2.gif
- [x] session2_data_ui_4_viz_diag.gif

- [x] session2_data_ui_2.gif
- [x] session2_data_ui_4_viz_diag.gif

Part 2:
- [x] session2_data_ui_4_viz_diag.gif
- [x] session 3_data_ui_params.gif

- [x] session 3_data_ui_params.gif

- [x] session 3_data_ui_params.gif
- [x] mtl_menu.gif

**Comment by staceypark** [comment]
@lijenn I'm not sure what your task is based on your comment above?

> SEE Guides
> 
> * Red Part 1:
>   GIF: 'Your team data folder'
>   Link:
> * All images are currently linked
> * GIFS are linked as well
> * Red Part 2:
>   Link:
> * All images are currently linked
> * GIFS are linked as well
> 
> SAY Guides

**Comment by staceypark** [comment]
@lijenn I've also added a dependency for you. Your gifs as you discussed with Anthony yesterday cannot be fixed until they make all the changes in the Splashpage first.
