### ISSUE TITLE
Update logos in MTL Blue SEE & SAY guides S1 - S12

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#1050]
**Update logos in MTL Blue SEE & SAY guides :** 

**Images**
1. Add disclaimer under all gifts that they refer to MTL 2.0 and may differ from videos (#1048)
2. For all 12 sessions, use the title slides logo found [here](https://github.com/lzim/teampsd/tree/master/resources/title_slides)
**Reminder:** These logos should remain "unclickable".
**Only update** the logo link within the brackets and leave the text in the parentheses that ensure these are unclickable.
3. Log size 270 *590
```
[<img src = "https://github.com/lzim/teampsd/blob/master/resources/logos/mtl_live_sq_sm.png"
     height = "175" width = "290">](#DontLink)
```
 **Branch** https://github.com/lzim/teampsd/blob/rita_2020_03_02_issue_1050/

**Comment by ritahitching** [comment]
Sessions 1 and 2 done

**Comment by staceypark** [comment]
This task looks like it is for updating only the first logo in each guide that was previously "MTL Live". I'm not sure why this criterion is in here "Add disclaimer under all gifts that they refer to MTL 2.0 and may differ from videos" for this task as it is not applicable.

I believe that is a separate review? I thought gifs were on @lijenn plate?
> **Update logos in MTL Blue SEE & SAY guides :**
> 
> **Images**
> 
> 1. Add disclaimer under all gifts that they refer to MTL 2.0 and may differ from videos
> 2. For all 12 sessions, use the title slides logo found here
>    **Reminder:** These logos should remain "unclickable".
>    **Only update** the logo link within the brackets and leave the text in the parentheses that ensure these are unclickable.
> 
> ```
> [<img src = "https://github.com/lzim/teampsd/blob/master/resources/logos/mtl_live_sq_sm.png"
>      height = "175" width = "290">](#DontLink)
> ```

**Comment by ritahitching** [comment]
@staceypark you divided #1032 Update logos in MTL Red & Blue SEE & SAY guides into 

Rita: Blue SEE Sessions 1-12
Jenn: Blue SAY Sessions 1-12

Jenn asked me to add the disclaimer under every screen shot of the MTL Blue SEE Guides to demonstrate that they referred to MTL 2.0. and would differ from the video, while I was updating the main logo.

Please let me know if I should be stop adding the disclaimer to the photos but continue to update the main logo. 
thanks

**Comment by ritahitching** [comment]
Update Status 

Session | Blue SEE Guides | Disclaimer Added | Main Logo Updated
-- | -- | -- | --
1 |   |   | Yes
2 |   |   | Yes
3 |   |   | Yes
4 |   |   | Yes
5 |   |   | Yes
6 |   |   | Yes
7 |   |   | Yes
8 |   |   | Yes
9 |   |   |  
10 |   |   |  
11 |   |   |  
12 |   |   |  
  |   |   |  


Session | Blue SAY Guides | Disclaimer Added | Main Logo Updated
-- | -- | -- | --
1 |   |   |  
2 |   |   |  
3 |   |   |  
4 |   |   |  
5 |   |   |  
6 |   |   |  
7 |   |   |  
8 |   |   |  
9 |   |   |  
10 |   |   |  
11 |   |   |  
12 |   |   |  



Session | Blue SAY Guides | Disclaimer Added | Main Logo Updated
-- | -- | -- | --
1 |   |   |  
2 |   |   |  
3 |   |   |  
4 |   |   |  
5 |   |   |  
6 |   |   |  
7 |   |   |  
8 |   |   |  
9 |   |   |  
10 |   |   |  
11 |   |   |  
12 |   |   |

**Comment by ritahitching** [comment]
@staceypark pull request made.
thanks,

**Comment by ritahitching** [comment]
updating logo size to 175*420

**Comment by ritahitching** [comment]
Pull request made and accepted. 
I'll close this issue.
