### ISSUE TITLE
Compare SEE and SAY Guides S1 - S12 within and across sessions for continuity and consistency

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#1053]
**Review See Say Guides **

Review SEE & SAY S1- S12 for consistent wording and number formatting across SEE & SAY guides

(merged details #1047)

**Comment by ritahitching** [comment]
**Todo**

1. Compare** S1 - S12 for MTL 2.0 and MTL 1.7 
2. Compare titles and numbering match.
3. Differences should match 1.7 and create a new branch / pull request.

**Comment by ritahitching** [comment]
@staceypark I have made a pull request for this issue.
thanks,

**Comment by staceypark** [comment]
@ritahitching great thanks! I merged the pull request for aligning the SEE guides.
Next, can you make sure the main numbered instructions match between the SEE and SAY guides? If they do not, the SAY should be edited to match the SEE.

**Comment by ritahitching** [comment]
**branch** rita_2020_03_03_issue_1053_numbering

**Comment by ritahitching** [comment]
To do:
1. Remove sub-numbering (lettering) in the SAY guides if not present in the SEE Guides.
2. Replace lettering with a bullet point.
3. Check formatting

**Comment by staceypark** [comment]
Closing this issue with pull request #1087
