### ISSUE TITLE
Purchase LucidCharts Account

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1054]
Acquire a Premium Account for Lucid Charts--requires filling out a req logic request.

Annual pricing option is cheapest

**Comment by lzim** [comment]
@ritahitching 

I can email you the account information tomorrow. I created the account and we need to set it up with PAVIR in ReqLogic to close this issue. Thanks!

**Comment by ritahitching** [comment]
@lzim please email me your account log in details for Lucidchart (email and password).  I can order through my own Reqlogic account.

**Comment by ritahitching** [comment]
@lzim ReqLogic order placed.

**Comment by lzim** [comment]
Great thanks @ritahitching
