### ISSUE TITLE
3/12 Zenhub Map Document

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1055]
Map out our Zenhub workflow on LucidCharts and disseminate to the team.

**Comment by anthonycpichardo** [comment]
@staceypark Can you review the zenhub map on Lucid and provide feedback. 😀

**Comment by staceypark** [comment]
@anthonycpichardo some comments:
1. I believe we want to follow the template in that certain shapes should be certain colors.
2. Please include instructions for going to specific links. i.e. ask people to go to mtl.how/zenhub as a step
3. Write out the 9 clicks in step 3
4. "Per the latest huddle is my current issue the highest priority?" - Clarify this isn't the "high priority" pin, but rather **individual** priority
5. "Come to the next HQ huddle prepared to answer questions about your current capacity and issues" - this links to #4's diamond but I'm not sure why?
6. Add dark red node to the Pull Request step that links to the documentation_map workflow and explains how that system works.

**Comment by anthonycpichardo** [comment]
Updated following your feedback. 

For number 5, it links because essentially that flow should be a continuous loop until we have no work left.
