### ISSUE TITLE
2/28 Revise Goals 2020 to complete PAVIR review 

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#1058]
**Revise Goals for 2020:** 

1. Revise 2020 goals using recommendations from Lindsey's email.
2. Send to Lindsey for review.
3. Finish by COB Friday 2/28

**Comment by ritahitching** [comment]
@lzim the ReqLogic purchase order has been approved by PAVIR and submitted to Lucidchart.
Please confirm I can close this ticket.
thanks

**Comment by lzim** [comment]
@ritahitching 

This is the revision to your PeopleGoal for PAVIR. The other issue about ReqLogic for Lucid Chart I closed earlier today.

Please see your email tomorrow to wrap up the PeopleGoal task.

Thanks!

**Comment by ritahitching** [comment]
@lzim 
I just sent you updated goals for 2020. thanks

**Comment by ritahitching** [comment]
@lzim I submitted the goals through the portal, thanks for your help.
