### ISSUE TITLE
Disable Links from MTL Part 1 and 2 see guides; update header logo in Red SEE & SAY guides

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1059]
- Disable the links on images in the MTL Red Part 1 and 2 see guides
- Update main "MTL Live" logo at the top of each guide to Part 1/Part 2 specific logos for SEE & SAY guides and checklists

**Comment by staceypark** [comment]
@anthonycpichardo I added one extra piece to this task, which is updating the logos
