### ISSUE TITLE
Blue SEE Guides S5-12: Gifs and Links 

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1060]
Update incorrect gifs of sim UI for sessions 5-12, and ensure they don't link out 
- [x] YAML S1-12 from 1.8 to 2.0
- [x] Disclaimer below gif: MTL 2.0. For MTL 1.7, click here. (here will hyperlink to 1.7 guide)
- [x] Add 2.0 function gifs/pngs (Session 5)
   - [x] community_button.gif
      - [x] drag_drop_community.gif
      - [x] snip_tool_community.gif
      - [x] upload_files_community.gif [issue]
   - [x] report_bug.gif (has upload files function in it already)
      - [x] drag_drop_bug.gif
      - [x] snip_tool_bug.gif
   - [x] News Function
      - [x] sim_ui_andon_alert.png
      - [x] sim_ui_news_notification.gif

S5: [need to add tutor, additional 2.0 features]
done/do
- [x] sim_ui_1.gif
- [x] sim_ui_sections.gif
----------
- [x] sim_ui_home.gif
- [x] sim_ui_team_data_menu_maint
- [x] learning_mode.gif
- [x] sim_ui_sections.gif
----------
done/do
- [x] **session2_data_ui_2.gif** [this part is confusing to me, doesn't go with the flow of s5 which is mainly sim?]
- [x] sim_ui_pop_ups.gif

s6:
- [x] sim_ui_pop_ups.gif
- [x] sim_ui_reveals.gif
----------
- [x] sim_ui_reveals.gif
----------
- [x] sim_ui_reveals.gif
- [x] sim_ui_text_fields.gif

s7:
- [x] sim_ui_text_fields.gif
- [x] sim_ui_outputs_text_section.gif
----------
- [x] sim_ui_1.gif
- [x] sim_ui_sections.gif
- [x] sim_ui_bc_qh.gif
----------
- [x] sim_ui_bc_qh.gif
- [x] sim_ui_outputs_text_section.gif

s8:
- [x] sim_ui_outputs_text_section.gif
- [x] sim_ui_results_dash.gif
----------
- [x] sim_ui_1.gif.gif
- [x] sim_ui_previous_exp.gif
- [x] sim_ui_adjust_sliders.gif 
- [x] sim_ui_save_exp.gif
- [x] sim_ui_results_dash.gif 
----------
- [x] sim_ui_results_dash.gif 
- [x] sim_ui_text_fields.gif

s9:
- [x] sim_ui_text_fields.gif
----------
- [x] sim_ui_1.gif [was gonna use screenshot but will need to update it all over]
- [x] sim_ui_compare_alt.gif
- [x] sim_ui_adjust_sliders.gif
- [x] sim_ui_save_exp.gif
- [x] sim_ui_results_dash.gif
----------
- [x] sim_ui_results_dash.gif

s10:
- [x] sim_ui_1.gif
- [x] sim_ui_compare_alt.gif
- [x] sim_ui_results_dash.gif

s11:
- [x] sim_ui_results_dash.gif

**Comment by staceypark** [comment]
@ritahitching I believe @lijenn is working on this issue. Did you guys reassign the workload?

**Comment by ritahitching** [comment]
@staceypark 
@lijenn and I decided that I'd do the main logos and disclaimers for MTL 2.0 and MTL 1.8 at the top of each guide S1 - S12 for Blue SEE and SAY Guides, and @lijenn would do the images and links for the remainder of the guides.

**Comment by lijenn** [comment]
#1070 
Update these in Prod Demo
- [ ] **.gifs on DEMO slider** (check #1060)
    - [ ] demo_reveals_gif_1.gif
    - [ ] demo_text_inputs_gif_2.gif
    - [ ] demo_experiments_gif_3.gif [NEED EXP FILE]
    - [ ] demo_alternatives_gif_4.gif [NEED EXP FILE]
    - [ ] Demo_graphic.jpg
