### ISSUE TITLE
Due 3/4 Epicenter Training Homework - Review MTL Test

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#1065]
**Epicenter Training Homework** 

1.  Review MTL Test prior to next training session with James
2.  Login in https://forio.com/app/va/va-psd-test-demo/login.html
3. Make changes directly to MTL Test (will show up on: https://forio.com/app/va/va-psd-test-demo/mtl_demo.html)
4. Email James when done

Estimate 1 hour

**Comment by ritahitching** [comment]
Review mtl.how/demo (https://forio.com/app/va/va-psd-test-demo/mtl_demo.html)

I'm thinking of the "MTL for all" users primarily 

**Introduction**
1: Add link to HSRD I01HX002521 (https://www.hsrd.research.va.gov/research/) ?
2. Sliders move too fast IMHO

**Modeling to Learn Section**
1. Icons don't link to mtl.how/live mtl.how/video mtl.how/facilitate or mtl.how/demo
2. There's only 2 versions mlt.how/red or mtl.how/blue not 4 versions -remove and replace 


**Run Your Test** (Is this the right title? Should we explain what this section refers to?
1. Form to get an account - font very small - hard to read. Is it worth saying that "You need to follow the confirmation email to activate your account"? or is this not needed? Is the icon "Run" a good choice to sign up?
2. mtl.how/demo offers the option to login to modelling to learn. Should it remind folks to create an account if they have't got one yet, and accidental selected mtl.how.demo before run?   
3. mtl.how/live - do you need a GitHub account to access the content? If so, should we offer a link or remind people to sign up for a GitHub account?
4. mtl.how link to resources and cheatsheet is broken


**Videos** (Should we explain what this section refers to?) [ALL NEED UPDATING]
1. VAPOR - link goes back tp mtl.how/demo
2. mtl.how/live - link goes back tp mtl.how/demo
3. mtl.how/video - - link goes back tp mtl.how/demO

**Slides**
1. Link works fine - should we offer a download option directly to the document - rather than the link to a second link within the connference homepage

**Papers** 
1. Link works great - download easy 

Funding

**Comment by jamesmrollins** [comment]
Crossref with #1070 

Hi @ritahitching.  Thank you for the very comprehensive review of your assigned web page!  I think this is thorough and I am going to share it with @lijenn and @lrollins33 , so they can coordinate their efforts as well.  Yes, I would like for you to collaborate with @lijenn and @staceypark determine the correct links and input them on the admin page.  Be sure to answer either here or in #1070 so @lrollins33 can replicate in her assignment.  ~James

**Comment by lijenn** [comment]
@jamesmrollins @ritahitching Currently, all the links on Prod and mtl.how/demo as of right now should be correct with the exception of the MTL Live hyperlinked icon and issues Jane addressed in #1020. I am waiting on a decision from Lindsey that is tracked in that thread.

Please refer to #1070 for all the changes I have already made/currently still need to make. Thank you!

**Comment by staceypark** [comment]
thanks @lijenn 
@lrollins33 and @ritahitching is that enough for you two to go off of?

**Comment by ritahitching** [comment]
@staceypark @lijenn @jamesmrollins @lrollins33 

Yes, thank you - this is enough for me to continue with. 

**I have updated the links for gifs to:**
1. mtl_demo
2. mtl_live
3.  mtl_how 

**and the links to the videos for**
1. vapor
2. mtl_live
3. mtl s1 - 4

**I will wait on the decision to #1020 on:**
1. Removing MTL Live icon and line  to be replaced with MTL Red and MTL Blue
Click the icon to see the guides for the Modeling to Learn Live 12-session plan.
2. Removing there are 4 versions of Modeling to Learn. 

I will do this last portion until next week, once all our tasks for MTL GoLive are done.
thanks, Rita

**Comment by lijenn** [comment]
@ritahitching @lrollins33 I have updated the gifs on the slider at Prod for mtl.how/demo.
Please be sure to update that in your respective Demo version. 

- Issue: Outdated gifs on the Demo Slider (also referenced in #1070)
Solution: Jennifer needs to recreate and upload the updated gif files in MTL Demo Prod's Slider's folder on Epicenter
For Rita and Lucy: Please download the updated gif files (see the gif file names below) and reupload the gif files into your Demo version's slider folder in Epicenter. Then go onto the Admin panel and update the slider name files to reflect the new updated gif files.

- demo_gif1.gif (now called updated_gif_1_demo.gif from Prod's Slider's folder)
- demo_gif2.gif (now called updated_gif_2_demo.gif from Prod's Slider's folder)
- demo_gif3.gif (now called updated_gif_3_demo.gif from Prod's Slider's folder)
- demo_gif4.gif (now called updated_gif_4_demo.gif from Prod's Slider's folder)

**Comment by ritahitching** [comment]
@lijenn  thanks for the information 
@jamesmrollins Uploaded the new files to Test Demo Slider and updated the files names for the sliders in the Admin panel. Please review and then I'll close this issue.

**Comment by lzim** [comment]
> @lijenn thanks for the information
> @jamesmrollins Uploaded the new files to Test Demo Slider and updated the files names for the sliders in the Admin panel. Please review and then I'll close this issue.

@ritahitching I see that this is in the **"Review/AQ"** Pipeline, which is great!
But, was not assigned for review.

I've assigned @jamesmrollins and affixed the label for **Sim** if this is on his plate now to wrap up.

Thanks!

**Comment by ritahitching** [comment]
@jamesmrollins are you OK with closing this issue?
thanks! Rita
