### ISSUE TITLE
Research Analytic Option for Sharepoint Splash Page

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1066]
Explore what options are available to monitor traffic and usage on our splash page. Determine work required to implement

**Comment by anthonycpichardo** [comment]
hey @lzim , when you have a moment can you check if you have "Site Usage" option in the settings gear on the Sharepoint site? Looks like you might need to be Site Owner to view this.

To view usage data, click the settings gear and click site usage.

**Comment by anthonycpichardo** [comment]
@lzim . As we saw today, with the activation of the Reporting we can now view usage via "Popularity Trends" and "Popularity and Search Reports" (Only you have access to this it seems).

There is additional data on the sharepoint page if you go to the "Most Popular Items" on the library toolbar.

If we want something a little more detailed we may need to do some research on what other webapps we can setup and build a dashboard with.

Recommending we close this for now.

**Comment by lzim** [comment]
Hmm I don't see this:

> There is additional data on the sharepoint page if you go to the "Most Popular Items" on the library toolbar.

I think it's okay to keep this open, but move to the icebox until we figure out what more we should do.

**Comment by anthonycpichardo** [comment]
Okay sounds good! @lzim 

If you're interested, I can show you the spot the internet says it should be in for the additional thing.

**Comment by lzim** [comment]
> Okay sounds good! @lzim
> 
> If you're interested, I can show you the spot the internet says it should be in for the additional thing.

@anthonycpichardo maybe on Friday if we want to review progress on our data after the kickoff calls.

Otherwise, just pop this in the icebox 🍨 if you don't mind!
