### ISSUE TITLE
wk2 may_epic DUE COB 5/3 TEST QA: Review SAY checklists all sessions for Fidelity to Theory of Change

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1074]
**Discussed at hq_workgroup 4/4/21**
@staceypark 
@lijenn 
@lzim  

_Need a working meeting Mon 5/3 PM:_
- [x] Align all 12 sessions s1-12 Red and Blue at mtl.how
- [ ] Standardize their abbreviated versions in the team_tracker.
- [ ] Slot into the session chapters of the _MTL Facilitator and Technical Manual_.

Note: Blue Sessions 2 & 3 and Red Part 1 & 2 should essentially have the same checklists, since they are the same session content

Lindsey to check Sessions 1-6 say checklists here for feb_epic
- [x] S1: https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/facilitator_say/mtl_session01_say_checklist.md
- [x] S2: https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/facilitator_say/mtl_session02_say_checklist.md
- [x] S3: https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/facilitator_say/mtl_session03_say_checklist.md
- [x] S4: https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/facilitator_say/mtl_session04_say_checklist.md
- [x] S5: https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/facilitator_say/mtl_session05_say_checklist.md

**Comment by branscombj** [comment]
@staceypark - @dlkibbe  is back in the office. She is first going to attend to the Post-tests for sessions 11 and 12 that Elizabeth did not have, so the pilot testers can complete their work. Then she will turn to the Checklists for Red 1 & 2 and Blue 3,4,5. I am doing the Community of Practice Q&As.

**Comment by branscombj** [comment]
@staceypark @dlkibbe In addition, before we start any teams we will need to address feedback on the post-tests that warrants changes that we've gotten from pilot testers. Debbie is compiling that feedback from the pilot forms Elizabeth forwards.

**Comment by staceypark** [comment]
@dlkibbe how are these coming?

**Comment by dlkibbe** [comment]
Working on them...

**Comment by dlkibbe** [comment]
I will have these done by tomorrow. I'm also noting other edits that may be required in Say guides so when I do the pull request you will see not only the addition of remaining checklists but also some edits to a few other documents.

**Comment by staceypark** [comment]
@dlkibbe that's for taking the first stab at these. I've merged your pull requests.

As we discussed, this will now be handed off to @lzim to make sure the checklists are made consistent across the sessions to ensure fidelity with the theory of change.

**Comment by lzim** [comment]
@lijenn  and @staceypark 

Can we clarify what dependencies there are for this at today's **hq_workgroup** meeting.

**Comment by lzim** [comment]
Discussed at **hq_workgroup** on 2/18/21

Split into two cards - links to the SAY Checklists 
Lindsey believe the best versions of these are in team_tracker
- [ ]  sessions 1-6 for feb_epic

- [ ] sessions 7-12 for a later epic based on the GANTT chart.

**Comment by staceypark** [comment]
5/3 meeting: 

1. Intersession checklist: goes before partner, build, apply checklists as the intro: https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/checklists/fidelity_training_checklist.md
2. partner: https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/checklists/partner_fidelity_training_checklist.md
3. build: https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/checklists/build_fidelity_training_checklist.md
4. apply: https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/checklists/apply_fidelity_training_checklist.md
5. PRE checklist: teampsd/pre_meeting_checklist.md at master · lzim/teampsd (github.com)
6. POST checklist: teampsd/post_meeting_checklist.md at master · lzim/teampsd (github.com)
7. session1_debrief as examples on how/what to track: https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/checklists/session1_debrief.md

**Comment by staceypark** [comment]
@lzim some questions as I've started to edit the checklists:

1. What should we call the non "live-lead"? I've seen "fidelity facilitator" and "pre/post lead / notetaker." I'm leaning toward the former.
2. For Red - we are thinking of editing the intersession checklist and the partner fidelity checklist to be tailored to red language.
3. The sessions were divided into 5-10 and 11-12, since we stop running experiments by session 11. This is an issue for the time stamps see here: https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/checklists/inter_session_checklist.md
