### ISSUE TITLE
Review Blue Session 1-12 SAY & SAY Checklist

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1076]
Make sure the SAY checklist matches in content for SAY guides for Sessions 6-12

**Comment by ritahitching** [comment]
1. New branch rita_2020_03_02_issues_1076
2. Compare S6 to S12  - each session with it's respective checklist.

**Comment by staceypark** [comment]
I am closing this issue, as there is a lot more work to be done than just cross-checking the checklist to the SAY guides and we need a different issue card for this.

**Comment by lzim** [comment]
Thanks @staceypark can you add a cross-ref for the relevant new issue so they are linked?
