### ISSUE TITLE
Examine Sessions 5-10 SEE, SAY, & SAY checklist for updated team data maintenance language

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1084]
In every instance that says "Team Data Menu Maintenance", we will now use **"Team Data Dropdown Maintenance"**
cross ref #339

**Comment by ritahitching** [comment]
@staceypark 
pull request made for replacing "Team Data Menu Maintenance" with "Team Data Dropdown Maintenance" in S5 to S10 SEE, SAY, SAY Checklist.
thanks.
