### ISSUE TITLE
First Dynamics Session

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#11]
Lead = Myra

**Comment by lzim** [comment]
Hi Myra,

Once you accept the invitation to collaboration, this is the "Facilitation Guide" Project Tracking part of GitHub that we can use as we iterate on our PSD facilitation materials.  I've assed the "First Modeling Session," which we discussed this morning, to you.

This "issue" will track the project and we can discuss it here - it will push the updates to Basecamp automatically, so we can track progress there.

I created two "milestones" for this item a "see.Rmd" file and a "say.Rmd" file. We can discuss it here, but I should also see it any updates in my "feed."

Last, if you have questions about specific code, etc.  You can assign this issue to me (or another collaborator from our team) to "review."

Thanks!

Lindsey

**Comment by myraaltman** [comment]
Hi Lindsey, 

I have the "see" and "say" files created for this session but since I cannot access r from the VA, they exist in code in word format only! I will copy them to r markdown and post them on here once I get home and can access r.

Thanks,
Myra

**Comment by lzim** [comment]
Thanks Myra!

**Comment by lzim** [comment]
Myra,

You can use R and R Studio in the VA.  If you'd like to use R on a VA machine, you open a work order and OIT will install it on your machine.

There are instructions in the D&T useful info OneNote in the Team PSD Orientation folder. Let me know if you need help!

Lindsey

**Comment by myraaltman** [comment]
I just put in the work order - thanks Lindsey!

**Comment by lzim** [comment]
Great!
