### ISSUE TITLE
Makes Copies of MTL Red and SEE Guides S1-S12 files to MTL 2.0

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#1115]
**Copy MTL Red and S1-S12 SEE Guides & Create New Files in teampsd MTL 2.0:** 

1. Create new branch : Rita 2020 03  06 mtl20 copy files
2. Copy files for
- MTL Red part 1
- MTL Red part 2
- S1-S12 for SEE Guides
3. Create new .md files in TeamPSD MTL 2.0
4. Update the Edited by to say March 2020
5. Make pull request 
6. Estimate 1 hour & due by 3/6

**Comment by ritahitching** [comment]
@staceypark 
I completed this issue #1115 and created a pull request issue #116

**Comment by staceypark** [comment]
closed and done
