### ISSUE TITLE
Makes Copies of MTL Red and SAY Guides S1-S12 files to MTL 2.0

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#1118]
**Copy MTL Red and S1-S12 SAY Guides & Create New Files in teampsd MTL 2.0:** 

1. Create new branch: rita_2020_03_06_mtl20_say_copy_files 
2. Copy files for
- MTL Red part 1
- MTL Red part 2
- S1-S12 for SAY Guides
- Donot include Checklist
3. Create new .md files in TeamPSD MTL 2.0
4. Update the Edited by to say March 2020
5. Make pull request 
6. Estimate 1 hour & due by 3/6

**Comment by ritahitching** [comment]
@staceypark 
Please accept a pull request for this issue tracked in #1119

**Comment by staceypark** [comment]
pull request merged and closed.
