### ISSUE TITLE
Due 3/12 MTL Blue Replace Header logo  for S1 - S12 for Pre and Post Email  

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#1120]
** MTL Blue Replace Header logo for S1 - S12 for Pre and Post Email**

Larger overall tasks currently tracked in #987  among other tasks - break down of work cross referenced in  #983 #870

**To do:**
1. S1 - S12 for MTL Blue replace all 24 emails header logo
- 12 pre
- 12 post
2. Title slides logo found [here](https://github.com/lzim/teampsd/tree/master/resources/title_slides)
3. Add MTL Blue to pre email files
4.Add MTL  Blue to post email files
files can be found [here]  https://github.com/lzim/teampsd/tree/master/mtl_facilitate_workgroup/pre_post_emails
5. Create new branch: rita_2020_03_10_pre_post_email_headerlogo
6. Make pull request

Estimate 1 hour

**Comment by ritahitching** [comment]
@staceypark @lijenn 
I updated the pre and post emails for MTL Blue S1 - S12 with the new header logos.
I made a pull request #1146 
branch: Rita 2020 03 10 pre post email headerlogo

**Comment by lzim** [comment]
@ritahitching please clean up all your old branches on GitHub 🧹

**Comment by ritahitching** [comment]
> @ritahitching please clean up all your old branches on GitHub 🧹

@lzim will do.
@staceypark other than the current open branch **rita_2020_03_10_pre_post_email_headerlogo** are you ok with me deleting all the others? 
thanks,

**Comment by staceypark** [comment]
I don't know what your other branches have? If you don't have any current work on other branches that needs to be merged, then please delete them.

> > @ritahitching please clean up all your old branches on GitHub 🧹
> 
> @lzim will do.
> @staceypark other than the current open branch **rita_2020_03_10_pre_post_email_headerlogo** are you ok with me deleting all the others?
> thanks,

**Comment by ritahitching** [comment]
> I don't know what your other branches have? If you don't have any current work on other branches that needs to be merged, then please delete them.
> 
> > > @ritahitching please clean up all your old branches on GitHub 🧹
> > 
> > 
> > @lzim will do.
> > @staceypark other than the current open branch **rita_2020_03_10_pre_post_email_headerlogo** are you ok with me deleting all the others?
> > thanks,

thanks, I'll delete the old ones.

**Comment by ritahitching** [comment]
@staceypark did the issue of the logos being are clickable get discussed yesterday at the huddle?
thanks, 

@ritahitching it looks like all of these logos are clickable to their image source.
Following our decision rules we used when working on the guides, we would also not want images or links to go to unwanted places in the pre/post emails as well.

I'm thinking it should either go to the session directly or be made unclickable.
You should ask for the team's ideas on that at a hqhuddle.

**Comment by ritahitching** [comment]
Decision made for header logo to go to the respective session.

**Comment by ritahitching** [comment]
@staceypark I made a pull request made for this ticket (#1203) in branch rita_2020_03_16_issue_1120
thanks,

**Comment by staceypark** [comment]
@ritahitching Following the Documentation Map here and our training last Friday:
https://github.com/lzim/teampsd/blob/master/resources/maps/documentation_map.pdf

This issue card stays assigned to you, the owner of the task, instead of me during Review/QA, since the pull request  is assigned to me.

When the pull request is in Review/QA, the issue card goes back to the "Priority Epic" pipeline instead of Review/QA since the pull request is already there.

I've unassigned myself and moved the pipeline according to the SOP. Let's stay close to the SOP so we have accurate data for our epics and good self-assessments of our own work! 😅

**Comment by ritahitching** [comment]
@staceypark I see you merge my pull request for this issue, thank you. 
Are you OK with me closing this issue?
thanks,

**Comment by staceypark** [comment]
@ritahitching 
Yes, again following the map [here](https://github.com/lzim/teampsd/blob/master/resources/maps/documentation_map.pdf), please close the task card when the pull request has been accepted. 

No need to ask me next time. I am going to close to make sure we have accurate data.
