### ISSUE TITLE
4/23 TASK Splashpage User Guide Development

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1124]
on the mtl.how/data left hand side, there is a user guide for SplashPages.

Need to investigate and clean up as necessary

**Comment by staceypark** [comment]
@anthonycpichardo I'm plating this to you. Tap me if you have questions though

**Comment by anthonycpichardo** [comment]
Tapping you.

Do you want me to update this doc and make it useful or remove it from the sharepoint?

**Comment by lzim** [comment]
> Tapping you.
> 
> Do you want me to update this doc and make it useful or remove it from the sharepoint?

@anthonycpichardo Tapping who? 🤣 
Don't forget to mention someone.

I think you should work on the edits for a user guide, leaving the current guide at mtl.how/data.

Do you agree @staceypark ?

**Comment by anthonycpichardo** [comment]
@lzim  woopsies. @staceypark and I spoke offline. We're all in agreement

**Comment by anthonycpichardo** [comment]
I've updated the User Guide section to link to an updated guide.

@staceypark @lzim please review and provide any feedback.

**Comment by anthonycpichardo** [comment]
@anthonycpichardo add Splash Page controls to User Guide

**Comment by lzim** [comment]
@anthonycpichardo I edited to reflect the _MTL_ resource in the title.

**Comment by anthonycpichardo** [comment]
Updated the Splashpage User Guide available at mtl.how/data to include the splashpage controls.

Let me know what you think @staceypark. Ready to close if you approve
