### ISSUE TITLE
3/9 Deadline Guidance on TeamPSD Move 

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#1136]
**TeamPSD Move** 

1. TeamPSD move Friday March 13.
2. Collate emails from Craig Rose, Mary Kwan and Steve Woodward on instruction for labeling moving boxes, instructions for computing equipment etc.
3. Provide guidance by mid-day huddle 3/9 

Estimate 1 hour

**Comment by ritahitching** [comment]
Email Steve / Mary and confirm that the desk/tower details in the move spreadsheet is sufficient for the moving labels as to where computers and boxes should be moved to.

**Comment by ritahitching** [comment]
@lzim @staceypark @lijenn @anthonycpichardo @anazariz 
Please use the moving sheet to find your 'room number' for the Standard Moving Labels.

**Example:**
Division: MPD
From Bldg: 334
Room: C-127
To Bldg: 334
To Room: B239B-WS5
Contact: Rita Hitching / Lindsey Zimmerman

**Comment by ritahitching** [comment]
@lzim @staceypark @lijenn @anthonycpichardo @anazariz 
Good morning all. In preparation for our move please let me know:
1. how many boxes you have packed
2. other items you would like moved
3. any assistance you need

There is a moving spreadsheet on our shared drive where all the details will be recorded - look for folder labelled **move**.  
thanks,
Rita

**Comment by staceypark** [comment]
Can't believe we are really moving 😱 🎆 
Thanks @ritahitching for taking point on this.

For the "Contact" name, I believe we should be putting our **own names (first & last)**, followed by the PI's initials and sequential numbers* after (i.e. LZ1, LZ2, LZ3, etc.) based on Craig's email.

*We should probably wait to number the boxes until we have everything packed.

> @lzim @staceypark @lijenn @anthonycpichardo @anazariz
> Please use the moving sheet to find your 'room number' for the Standard Moving Labels.
> 
> **Example:**
> Division: MPD
> From Bldg: 334
> Room: C-127
> To Bldg: 334
> To Room: B239B-WS5
> Contact: Rita Hitching / Lindsey Zimmerman

**Comment by staceypark** [comment]
we are done packing! I believe we can close this
