### ISSUE TITLE
Sim UI label fix

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#1137]
@jamesmrollins We should remove the fixed word "Quarters" from next to the "Advance" drop-down menu in the Experiment Timeline section. We we have units next to each of the dropdown menu options (and one is not Qtrs). 

It would (imo) also be nice to change the dropdown option "End" to read "2 Years" for consistency, and to put it at the bottom of the list even though it is the default - or list all the options in decreasing order.

![image](https://user-images.githubusercontent.com/29778290/76250744-3968d780-621c-11ea-964c-3803d617e9cd.png)

**Comment by jamesmrollins** [comment]
@branscombj I hear make the changes as shown below.  Note: Default must be at top.

![image](https://user-images.githubusercontent.com/30132017/76263585-82209080-621c-11ea-9242-d1d2fb8e1b73.png)

**Comment by branscombj** [comment]
@jamesmrollins great, except don’t add st (1st) etc.

**Comment by jamesmrollins** [comment]
@branscombj WILCO

![image](https://user-images.githubusercontent.com/30132017/76336333-16d5cd80-62b3-11ea-9c26-ca6dfb446687.png)

**Comment by staceypark** [comment]
confirmed in PROD and ready to close
