### ISSUE TITLE
Sim UI model diagram section header

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#1138]
I tried to submit a bug report from the sim in Test but ran into 2 problems I can discuss in a different issue. The one here is that when I log in to the sim (my individual world in the Test environment, here), if I click a radio button by a module under "Start a new session" and then go back to "Join Current Session", the data file name does not appear in the main sim UI page diagram section header. The correct module name does show up, but not the data file name. The sim opens, so I assume everything is still as Ileft it in the session (data loaded; any runs saved, etc.). There's just a glitch about the filename not getting brought into the blue bar.

![image](https://user-images.githubusercontent.com/29778290/76254851-88fed180-6223-11ea-83d8-50d63991996a.png)

**Comment by jamesmrollins** [comment]
@hirenp-waferwire when we do the following use case, the model parameters file gets substituted, when it shouldn't.  Please investigate.

1.  User has a current session loaded with a given model parameters file.

![image](https://user-images.githubusercontent.com/30132017/76365347-4fda6600-62e4-11ea-9b43-730cb4224d93.png)

2.  User selects a new session and new model parameters file.

![image](https://user-images.githubusercontent.com/30132017/76365078-a4c9ac80-62e3-11ea-81b9-b9760325a2df.png)

3.  However, **user changes mind** and selects Join Current Session instead.  Note the model parameters filename.

![image](https://user-images.githubusercontent.com/30132017/76365161-d8a4d200-62e3-11ea-8f2e-a38fc4221e39.png)

4. When session loads, the model parameters file reflected in the header bar of the Main Diagram is the model parameters file selected from the new session dropdown.

![image](https://user-images.githubusercontent.com/30132017/76365314-39cca580-62e4-11ea-84ec-19173efd7093.png)

**Comment by branscombj** [comment]
@jamesmrollins My use case was slightly different; see images below, using Chrome/VA Sim UI PROD. *Note that this same sequence in Chrome/VA Sim UI TEST - Slow produced CORRECT behavior for me.*

![image](https://user-images.githubusercontent.com/29778290/76428128-a5b21b00-6383-11ea-9962-1dde717bc8a5.png)

![image](https://user-images.githubusercontent.com/29778290/76428153-aba7fc00-6383-11ea-9991-9ce0318c0735.png)

**Comment by branscombj** [comment]
Complete.
