### ISSUE TITLE
3/9 Template LucidChart TeamPSD Colors & Fonts

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#1139]
** Template LucidChart TeamPSD Colors * 

1. Login Lindsey account
2. Create Lucidchart template include
(i) full set of TeamPSD colors
(ii) myriad pro font.
3. Color located in shared drive in VHA style guide

Estimate 1 hour

**Comment by lzim** [comment]
@ritahitching 

Thanks for working on this!
Unfortunately, no, I don't see the template in Lucid Charts 😕

**Comment by ritahitching** [comment]
@lzim 
I sent you a link to the Lucidchart template via your gmail account. 
Follow the link to add the template to your account.
When you create a new document, it should offer you option to use a template. I'm happy to show you how if it's not clear in Lucidchart.
I'll close this ticket once I know you have been able to access the template.
thanks,
Rita

@staceypark @anthonycpichardo I sent you both a link to the template via your gmail account.

**Comment by ritahitching** [comment]
@lzim please check your account one more time. It should be in there.
thanks,
Rita

**Comment by lzim** [comment]
@ritahitching 

Great, thanks it is there!
Later this week (no need for overtime) will you please update to include the Extended color palette we discussed in the huddle?
https://github.com/lzim/teampsd/blob/teampsd_style/colors.md

I've copied the list of Secondary Colors below.

VA Blue Green - #115E67; RGB 17, 95, 103

VA Evergreen - # 154734; RGB 22, 71, 52

VA Green - #598527; RGB 89, 133, 39

VA Vibrant Green - #78BE20, RGB 120, 190, 32

VA Vibrant Light Blue (312PC) - #00A9CE; RGB 0, 169, 206

VA Vibrant Purple (2725PC) - #685BC7 ; RGB 104, 91, 199

VA Gray (7544PC) - #768692; 118, 134, 146

Thanks!

**Comment by ritahitching** [comment]
@lzim sure, happy to.

**Comment by ritahitching** [comment]
@lzim 
I updated the color template on Lucidchart to reflect all 11 colors.
I'm closing this issue.
thanks,
