### ISSUE TITLE
4/17  TASK + Sharepoint Community

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1140]
Think through what we want to do with the Sharepoint community functionality and how it should be setup/moderated.

**Comment by anthonycpichardo** [comment]
@lzim @staceypark  created an issue for us to discuss what should be done with regards to handling the Community on Sharepoint.

FYI: When we added this, the sharepoint home page was changed. Just something to be mindful of as we explore the additional functionality that is offered to us.  I've corrected it back to the previous landing page.

**Comment by lzim** [comment]
@anthonycpichardo and @staceypark 

I made minor edits to the "Community" menu on the left hand side.

Are they published? What do you think?

**Comment by anthonycpichardo** [comment]
They are published and look good =). Excited to get smarter and help others.

**Comment by lzim** [comment]
@anthonycpichardo 

Not a priority tonight, but would be aweseome to figure out how to get an MTL Logo on there...
I couldn't figure it out.

**Comment by lzim** [comment]
Also...

Probably would be great to have at least the HQ team join the Community at mtl.how/data
@staceypark @anthonycpichardo @staceypark @lijenn 

So, it doesn't look so lonely on there.

**Comment by anthonycpichardo** [comment]
@lzim  I think we can likely add a webpart for the image.

Yeah, I'll go ahead and join =). I imagine we can label ourselves for when we post as well.

Note: I'm quickly becoming a sharepoint wizard.

**Comment by lzim** [comment]
🚀 sweet

**Comment by anthonycpichardo** [comment]
Will follow the COP guidelines and add them to the sharepoint doc

**Comment by anthonycpichardo** [comment]
Updated the Sharepoint Community with our COP guidelines. Changes have been published.

Closing this issue.
