### ISSUE TITLE
3/10 + COP Lead Issue Card: Clean up the history on the card & Lock

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#1145]
@staceypark 

Tomorrow AM, would you be able to perhaps delete, re-post, re-pin, and re-lock this issue card on mtl.how? Like BEFORE THE NATIONAL KICK-OFF CALL, please 🙏 

I could see all your edit history, which will be confusing to new GitHub users.
Then, I tried to unlock & edit, but made it worse 🤣 

Thank you!

https://github.com/lzim/mtl/issues/47

**Comment by lzim** [comment]
@staceypark to be clearer.

The card itself with the community of practice guidelines looks great as is, it's just the edit history that I'd like to remove by re-creating the card.

Thanks!

**Comment by staceypark** [comment]
@lzim recreated, repinned, and relocked the new issue. unfortunately can't delete the old one, it's just in "closed". it's no longer pinned though so I think we should be fine
