### ISSUE TITLE
3/19 + Change folder path for team_data_table

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1147]
When "Create Team Data Table" is selected, make the generated file automatically drop into the "team_data_table" folder for each team, instead of the data_ui folder

**Comment by anthonycpichardo** [comment]
@lijenn testing

**Comment by anthonycpichardo** [comment]
@anazariz this is ready for review. Sent you an email with the file for review.

@staceypark after Ash reviews the changes you can test as well.

**Comment by anthonycpichardo** [comment]
@staceypark @anazariz code has been reviewed and pushed to master.
