### ISSUE TITLE
SIM UI: Mixed Cases for File Names

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1152]
Does the SIM only take file names that are lower case? 

If not, should we add to the notice here to warn user's that it is case-sensitive?
<img width="480" alt="Screen Shot 2020-03-10 at 4 09 22 PM" src="https://user-images.githubusercontent.com/59668647/76367200-9c747000-62e9-11ea-939e-e87f20a24930.png">

FYI @staceypark

**Comment by jamesmrollins** [comment]
@lijenn The sim is NOT case sensitive. Case sensitivity is our convention, not a limitation of the software. It does, however, need to match the filename exactly!

**Comment by lijenn** [comment]
Got it, that answered our question. Will close the issue!
