### ISSUE TITLE
3/13 tt_report week commencing 3/16

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#1157]
**tt_report** 

1. Updates from workgroup leads
2. Changes to Lucidcalendar
3. Weekly announcement

**Comment by ritahitching** [comment]
@staceypark @anthonycpichardo @lijenn @lzim 
Hi All, Please let me know:

1. if there are any updates from your workgroups for the tt_report. (I already have feedback from @jamesmrollins) 
2. Any specific update to the Lucidcalendar
3. Weekly announcement

A working draft of the tt_report is ready in the shared team_psd drive.
thanks,
Rita

**Comment by staceypark** [comment]
@lijenn please make sure the next upcoming 2 weeks has the most updated coplanning meetings, following Lindsey's guidance from our huddle

@ritahitching did you ping Jessilyn to ask about qual?

**Comment by lijenn** [comment]
@ritahitching 

Hi Rita, no updates from the EES, VAPOR, or Facilitate WG. 

I'll update Lucid to reflect all co-planning meetings for next week as I'm currently scheduling a meeting right now. Should be updated no later than noon, thanks!

**Comment by ritahitching** [comment]
@lijenn thank you.
I'll add the tt_report to our HQ huddle once you are done

**Comment by ritahitching** [comment]
@staceypark I have sent Jessilyn a message, no response as yet.

**Comment by ritahitching** [comment]
> @staceypark I have sent Jessilyn a message, no response as yet.

No updates from Jessilyn.

**Comment by ritahitching** [comment]
tt_report sent.
