### ISSUE TITLE
Sept. Task - Assess and detail document_team column by session

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1158]
#602 has many documentation needs compiled that relate both to HQ training and for facilitators.

Each session needs to be thought through for documentation needs for both audiences and outlined with:
1. What needs to be documented for each session
2. When documentation will be worked on and done
3. When we will train

**Comment by staceypark** [comment]
Will focus on Session 2 & 3 for teams_data and re-assess the rest at teams_sim

**Comment by lzim** [comment]
@staceypark @anthonycpichardo Can we get an updated Due Date for this issue in the Title?

**Comment by staceypark** [comment]
documentation needs already assessed and being worked on
