### ISSUE TITLE
wk2: Setup accounts for VA REDCap

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1162]
Make sure everyone who needs a VA RedCap account has one including:
1. Jenn & Rita
2. Ash & Anthony
3. All facilitators, including Lindsey
4. Jenn to keep track of David N. when he gets VA badge

Look at when Facilitators are next meeting and slot in a time to quickly alert folks that this is happening. See if I can do it for people.

**Comment by lzim** [comment]
@lijenn 

Please set up the following accounts:
- Rita, Jenn, David, Ash, Anthony, Debbie, Jane, Stacey, Lindsey
- We will wait to set up the QIICs

**Comment by lzim** [comment]
> @lijenn
> 
> Please set up the following accounts:
> 
> * Rita, Jenn, David, Ash, Anthony, Debbie, Jane, Stacey, Lindsey
> * We will wait to set up the QIICs

How is this coming? I'm really hoping to wrap up all things RedCap ASAP, since the training occurred a while back. 😸 
- BTW: Just to check, do the QIICs have to be involved to be added now?
- If they don't need to be involved, then why not add everyone now?

- If they do need to be involved...
I recommend that once the first group is all in VA RedCap, then we split this in to two stories and close #1162. 
- The second story would be the points just for adding the QIICs.
- Make sense?

FYI: @staceypark @ritahitching

**Comment by lijenn** [comment]
@lzim That makes sense! We won't be involving QIICS for now since they will get an email from REDCap if we make accounts for them right now, I will split this into the second story as it only involves QIICS. 

For the others, this will be done COB today! Thank you!

**Comment by lijenn** [comment]
Already have Accounts:
- [x] Stacey
- [x] Rita
- [x] Jenn

Need accounts and need to try signing in:
- [ ] David
- [ ] Ash
- [ ] Anthony
- [ ] Debbie
- [ ] Jane
- [ ] Lindsey

**Comment by lijenn** [comment]
@lzim @anazariz @anthonycpichardo It seems like you all have REDCap accounts already. Would you all mind trying logging in? 

I will be sending out email to you all with the link to the REDCap website (only accessible through the VA server) and your usernames. You may need to request a password change if you do not remember your password. 

Thanks!

**Comment by lijenn** [comment]
@branscombj @dlkibbe @dlounsbu Hi All! 

Please check your VA emails for 2 emails from the VA REDCap (their website is only accessible from the VA Server). You should receive one that says your account has been made and the other email with your login username details and instructions to set up your password on the website.

Please let me know/private message me if you are able to successfully log-in or need further assistance! Thank you!

**Comment by branscombj** [comment]
@lijenn I was able to log in to RedCap this morning. Thanks!

**Comment by lijenn** [comment]
@lzim @dlkibbe @dlounsbu 

Reminder to please check your VA emails and follow the instructions in the email with the subject line '**REDCap access granted**'.

For those having issues with getting on the server, Jane has suggested to try going on during off-peak hours as it may help relieve some tension off the bandwidth. Thanks all!

**Comment by dlkibbe** [comment]
@lijenn @branscombj 
I've completed this action

**Comment by lijenn** [comment]
@lzim Reminder to check if you can access your account, remember to use your VHA alias as the username :star:

**Comment by lzim** [comment]
> @lzim Reminder to check if you can access your account, remember to use your VHA alias as the username ⭐

Thanks @lijenn I will!
