### ISSUE TITLE
post *MTL 1.6* Vensim Model (.mdl) files

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#117]
Hi @TomRust and @staceypark,

We want to get the August release (and standardized) *MTL 1.6* .mdl files posted here over the weekend: https://github.com/lzim/teampsd/tree/master/model_workgroup/models

This is the last piece of the 1.6 standardization effort, with the exception of reviewing the sim UI dynamic "i" in formation.
I will also plan to make the models the first files we add in prime time to mtl.how 👍 

Stacey said she didn't see them in her email, which is fine. 
We can just upload them to the file above.
Tom, let Stacey and I know if you need any help uploading the tested files to Master.

**Comment by TomRust** [comment]
Done!  All model files on the master are current -- as of Sept 4th, 2018.

**Comment by lzim** [comment]
@TomRust AWESOME!!!
