### ISSUE TITLE
redundant team questions

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#118]
HI @staceypark 

Are the files here outdated and redundant with the files in coded team meetings?
https://github.com/lzim/teampsd/tree/master/qual_workgroup/team_questions

If so, can we delete this folder?

Thanks!

Lindsey

**Comment by staceypark** [comment]
@lzim This is from when I was trying to make the Q, H, F, D more easily visible.  But the system isn't necessary anymore, with our debrief/prep system and they should always be in the sim following the mtl fidelity. deleted the folder!
