### ISSUE TITLE
June TASK GitHub Documentation Checklist for Team PSD Manual

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#1191]
For next week - i.e., not the weekend...🍹
I’m just catching up.

@anthonycpichardo & @staceypark 

Anthony is working on the ZenHub map.
- We GitHub Checklist, **cheatsheet or map for all TeamPSD folks who create an issue or comment**.

For example in **issues**
- by & large, half of the folks at #hq are still creating issues without following the template title 
- OR- 
- the leave all the details for the 9 clicks, rather than delete & provide a succinct description for the issue.

In **comments**
- We really need all team members trained ASAP in **responding on the GH platform not via email.**

Maybe there are other things?

I’m thinking that this is more of a checklist or cheatsheet type of documentation. Not a guide or a map.

**Comment by staceypark** [comment]
@lzim - is this not supposed to be in the icebox?? Looks like there is a assignee, label, and milestone.

**Comment by lzim** [comment]
Cross-ref #1192 and #1218 

- We need to continue to prioritize resources for training, onboarding and orientation.

**Comment by lzim** [comment]
Hmm...this is also running late, would be great to get an updated Due Date in the Title:

@anthonycpichardo @staceypark Cross-ref: #921 and #1192

**Comment by ritahitching** [comment]
@ritahitching 
- Create a check list
- For features and issues
- Headers for each section
- Example for **features** and **issue cards**
- Include 9 clicks
- Issue title and due date 
- Is it a task card ?
- Is the current epic and upcoming epic

**Comment by ritahitching** [comment]
Hi All,
- [ ] I have a draft template for the [GitHub Documentation Checklist for Team PSD Manual](https://github.com/lzim/teampsd/blob/rita_2020_04_23_issue_1191/resources/training_guides/github/documentation_checklist_teampsd_manual.md) and I'd welcome your feedback.
thanks
@lzim @anthonycpichardo @staceypark @lijenn

**Comment by ritahitching** [comment]
@ritahitching Moved issue to May Epic.

**Comment by ritahitching** [comment]
@lijenn this is issue is blocked by the #1192 and the MVP process.
I recommend we keep this issue open.

**Comment by lijenn** [comment]
Closed due to outdated work.
