### ISSUE TITLE
DEC - Data sessions (S2 & 3) document_team 

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1194]

**Comment by staceypark** [comment]
Facilitators & HQ
1. Add all teams to mtl.how/data with correct permissions and add new team members
2. Explain how PIV engages with the SharePoint for permissions
3. Creating two folders and explain how data gets saved into the folders 
4. Use the master data UI to add a new data UI to a team's folder
5. Use master data UI to look up facility number for each team
6. Explain how data is pulled for the Splashpages and how to drill down to specific views (grey button)
7. Explaining errors of fuzzy clinics or weird scribbles or unclickable grey buttons or refresh pivot data error 
8. Explain how to do the get patient-level data pull and where the data comes from
9. Explain power pivot tools and order of operations for drilling
10. Explain how to the create team data table pull for each module (including what the zeroes mean) and where that data comes from
11. Explain the colors and types of explanations in the Params tabs
12. How the data works with the SIM
13. mtl.how/data community

90% of this is communicated across the cheatsheets, SEE guides and SAY guides. However, we understand we want it in one place. Do we want a map per topic? i.e.:
- Admin
- Splashpage
- Data UI
- Community

**Comment by anthonycpichardo** [comment]
Hey @staceypark,

How do you want to divvy up the items you've outlined above?

**Comment by staceypark** [comment]
I do think a lot of this is already documented. However, until all the Splashpage and data UI issues, we can't really move forward on this without creating rework.

**Comment by lzim** [comment]
@staceypark 
@anthonycpichardo 

Not sure if the dependency was completed so that this can move forward without rework?

**Comment by staceypark** [comment]
@lzim @anthonycpichardo @lijenn 
Yes, actually we can finish up documentation for this now.

Anthony - I updated #626 documentation card to say facility_data_check instead of splashpage_check. Not sure if you've updated the document itself yet.

Jenn - We need to spend a few minutes reviewing the status on these docs and what needs to be updated  & divvied.

**Comment by anthonycpichardo** [comment]
I have not, I can make those changes.

Do we want to replace all references of splashpage to facility?

**Comment by lzim** [comment]
> Do we want to replace all references of splashpage to facility?

Good question @anthonycpichardo 
How deep would those edits go, @lijenn (e.g., EES/TMS, plus all the SEE and SAY guides, etc.)?

FYI: @staceypark

**Comment by lijenn** [comment]
@lzim 
I believe @staceypark and I got those splashpage to facility edits (tms/ees, see/say guides, data ui checklist, mtl.how/data) already back in week 1 for data ui review.

**Comment by lzim** [comment]
So...it sounds like the answer to @anthonycpichardo's question for **document_team** is "yes."
