### ISSUE TITLE
Jane's Lucid action items

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#1195]
- [x] (1) Output charts: We need to identify all of the output charts that are not in the model diagram but show up in the output charts for each model for the guides

**See below for attachment with list of all output charts.**

- [x] (2) Check to make sure in master crosswalk table that Psychotherapy has the 4 cohorts (AUD, DEP, OUD, PTSD) and no Other category.

**See below; this has been checked.**

- [x] (3) Please use the .md files and the .xlsx files for reviewing the "i" information: https://github.com/lzim/teampsd/tree/master/resources/master_crosswalk/info Check all unit abbreviations in Master Crosswalk to be sure we're using the ones decided. (See table on CC worksheet) Revise all "I" text descriptions in the Team Data Table worksheet of the Master Crosswalk to repeat the variable name...

**I would like to do a thorough comb-through again unless HQ thinks it's not needed?**

- [x] (4) Make sure people can see the links** between the DataUI tabs - these data tabs feed these visuals, these feed those. 

**Does this need to be addressed in Facilitator Say/Checklist or other resources?**

- [x] (5) S05 when join current session or select new model explain to learner that model is running/initializing 

**After speaking with James, we decided the models are initializing fast enough now (in most cases) that we don't need to make a point of saying this.**

- [x] (6) Worksheets? text for Team Data Table Intro Paragraph (for all modules CC, MM, Psy & Agg): Need to correct in all worksheets. This model uses team data from the VA’s Corporate Data Warehouse (CDW), which are generated by staff during routine clinical care (e.g., a provider selecting CPT codes in CPRS).  The team data table is built using the Modeling to Learn data user interface based on clinic/grid selections.  More detail about data sources and estimation is available in the data user interface.  

**The i info for Team Data Table (in Test-Slow/CC at least) is different from this text and I think more complicated than the above. Should/how do we change it?**

- [x] (7) For the MTL Facilitate Guide: Draft a set of question that prompt the desired "dynamic hypotheses" that are higher-level (1-4 systems thinking) - see the qual_workgroup folder items 1) systems thinking codebook, and 2) coded meeting notes to see what questions were used to help the teams develop hypotheses during team meetings 

**Is this subsumed in the (relatively new) Session Checklist documents? Do we need to review checklists to make sure we provide this for Partner, Build, Apply and CFBT?**

**Comment by branscombj** [comment]
RE: (1) above: I pulled all the Chart Variables from the master_crosswalk_table dated 2019-10-07 and put them in a spreadsheet. And the winner is...........AGG, with 211 output variables to choose from! This version of the MCT did not have a Chart Label column for the PSY module.
There are 2 tabs: one listing all variables alphabetically; the other with them alpha-numeric meaning the 6 default charts are identified by a leading numeral at the top of the list.
[ChartLabels.xlsx](https://github.com/lzim/teampsd/files/4340156/ChartLabels.xlsx)

**Comment by branscombj** [comment]
RE: (2) above: I verified in the sim UI (TEST-Slow) that there is no "Other" showing up in the Team Data Table in PSY.

**Comment by branscombj** [comment]
RE: (3) above: Is this a priority task to do? If so, how can we coordinate that with James to make sure he knows which "i" text needs to be revised? Or - can this wait until we can handle this in a more automatic way like we do with world-team mapping now?

**Comment by staceypark** [comment]
@branscombj 
I notice this is in the “Icebox” pipeline of ZenHub and the “awaiting triage” section of the “document tracker”. Also, no one has been pingged within this thread. 

I happened to stumble on this while looking at the master issue list - otherwise this would have stayed invisible in the workflows unless you brought it up in a meeting 😅 

Items assigned to the document_tracker won’t show up in the columns unless assigned. And the cards that do make it in should represent a document and tracks its status (ie Session 05 See guide) rather than a task (ie update all SEE guide gifs to MTL 2.0).

This doesn’t apply to any of the trackers so I will remove the project assignment. And I’m changing the pipeline to “Priority Epic” until we decide otherwise.

**Comment by lzim** [comment]
Whoa! 

I just stumbled upon this issue @staceypark and @branscombj 🤣 

I think there are items above that are moving forward in other issues.
And, as always, you’ve found important items - thanks for reviewing Lucid 👍 

For example, I know that @jamesmrollins and Ash met about the Master Crosswalk today, and I know James has “i” information issue cards open.

Could we get these broken off into the respective GitHub resource cards they reference?

**Comment by lijenn** [comment]
@branscombj Hi Jane! Any updates on the remaining unchecked issues? We could bring the remaining items up in the Monday WG morning.

Let's try to get a due date in the title as well. So far, our epic is ending on 4/24, but we may extend it.

**Comment by lzim** [comment]
@branscombj and @lijenn 

I think this has cross-ref to #1220 and #784 

> 3) Please use the .md files and the .xlsx files for reviewing the "i" information: https://github.com/lzim/teampsd/tree/master/resources/master_crosswalk/info Check all unit abbreviations in Master Crosswalk to be sure we're using the ones decided. (See table on CC worksheet) Revise all "I" text descriptions in the Team Data Table worksheet of the Master Crosswalk to repeat the variable name...

**Comment by branscombj** [comment]
> @branscombj and @lijenn
> 
> I think this has cross-ref to #1220 and #784
> 
So I think it can be checked off here and subsumed there? I'm checking it off!

**Comment by branscombj** [comment]
@lzim @lijenn @staceypark It looks to me like the pieces of this that are not completed within this issue are covered in other issues, so I'm going to go ahead and close this.

I do want to call attention to this file I created of all the output chart variables. I'm not sure where it needs to be stored, or when we might want to call on it, but we had wanted it at one point. I know that @dlkibbe and I thought it would be helpful to have a reference to all the variables, since their abbreviations are sort of cryptic in the UI and the lists are long to scroll through in their drop-downs. This lets you look at them all and home in on what is most meaningful to the team's question. 
Does it go in the More Info page #886 ?

[ChartLabels.xlsx ](https://github.com/lzim/teampsd/files/4340156/ChartLabels.xlsx)
> From the master_crosswalk_table dated 2019-10-07. Note that this version of the MCT did not have a Chart Label column for the PSY module.
There are 2 tabs: one listing all variables alphabetically; the other with them alpha-numeric meaning the 6 default charts are identified by a leading numeral at the top of the list.
