### ISSUE TITLE
4/27 TeamPSD & Facilitators to MTL Help and MTL Info Inboxes

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1201]
MTL Help - all facilitators and HQ
MTL Info - all HQ

**Comment by staceypark** [comment]
@lzim 
YourIT requests have been submitted and in TeamPSD.
Reached out to Frank Behrens who helped us with this last time - he has picked the tickets up and aims to get the changes made by tonight.
The owner for both mailboxes will also be changed from Erica to you, Lindsey.

Also FYI, we could use the calendar on the MTL Help inbox as our shared calendar across facilitators? Just an idea - Apparently this is a thing people do.

FYI @anazariz (#1208) @anthonycpichardo (#1209) @lijenn (#1210) @ritahitching (#1211) You all should have access by the AM tomorrow. I've created GH tickets for you to test the inboxes. If I hear anything to the contrary from Frank tomorrow, I'll update you all.

**Comment by staceypark** [comment]
@ritahitching responding to your email here, in case other folks have the same question - 
As I mentioned in my comment above and in each person's specific issue card, the access will come in by AM (morning) **tomorrow**.

Please do not do this task until **tomorrow** morning at the earliest!

**Comment by ritahitching** [comment]
@staceypark no problem, but FYI the mailboxes are now visible on outlook. thanks

**Comment by lzim** [comment]
@staceypark 
- Wait to re-assess this with any QIICs who didn't already confirm their access.

@dlounsbu @jamesmrollins 
- Will you please confirm on this issue whether you can see the MTL Help inbox in your VA Outlook?
Thanks!

We'll close once we've confirmed with James and David. 😎

**Comment by lijenn** [comment]
From 4/2 HQ WG Meeting:
David has access.
@staceypark @jamesmrollins Does not see the MTL Help inbox. Moved this issue from teams_data to April.

**Comment by staceypark** [comment]
@lijenn thanks I'll reach out to the contact from last time to get this fixed.
I've found he's most reachable if I can catch him on Skype, so may take a few days (and he's our fastest option instead of a HelpDesk ticket).

**Comment by lijenn** [comment]
@staceypark 
I believe @jamesmrollins still does not have access to the inbox yet. Let me know if I could help!

**Comment by staceypark** [comment]
@lijenn We need to catch Frank Behrens on Skype to move this forward. Already created ticket on IT but it won't move forward anytime soon probably especially with COVID related pressures.

Ticket # is REQ2148924.

Please ask him to do the below for the MTL INFO inbox:
1. **Add** James Rollins (using James's VA email address, which you can find in the GAL). Make note to him that James' email address has a number in it.

2. **Fix** or double check Marcia Hunt (look for her email on the GAL as well). Make note that her email **also** has a number in it.

**Comment by staceypark** [comment]
@lijenn No need to reach out to Frank. IT has reached out to me that they are working on it.

**Comment by staceypark** [comment]
@jamesmrollins can you check your VA email account again? You should see the MTL Help inbox now.

**Comment by staceypark** [comment]
James confirmed MTL Help.

**Comment by hnorthcraft** [comment]
#adjudicate_memo update vs
