### ISSUE TITLE
3/17 Watch Telework Training 

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#1204]
**Watch Telework Training:** 

1. TMS Training on remote working #VA 1367006
2. Estimate 1 1/2 hours

**Comment by ritahitching** [comment]
@lzim I completed the teleworking training and added the certificate to our shard drive.
Are you OK with me closing out this issue? thanks,

**Comment by staceypark** [comment]
@ritahitching looks like you finished this and put it in the folder already.
I'm closing this because the work has been done. Please go ahead and close your own issues in the future that do not need review.

**Comment by hnorthcraft** [comment]
#adjudicate_memo update vs
