### ISSUE TITLE
3/20 tt_report 

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#1214]
**tt_report ** 

1. tt_report week commencing March 23 2020
2. Updates from workgroup leads
3. Calendar changes
4. Weekly announcement

**Comment by ritahitching** [comment]
Hi @staceypark @anthonycpichardo @lijenn @jamesmrollins do you have any updates or changes to the calendar from your workgroups that you'd like to be added to the tt_report for week commencing March 23? thanks!  :pray:

**Comment by jamesmrollins** [comment]
None - thank you.

James Rollins, Col (Ret), MS, MEd
Principal
PRAXIS ANALYTIX
________________________________

**Comment by staceypark** [comment]
@jamesmrollins 
As a reminder, please do not respond to these from your email as it puts everyone's email information in here. THanks!
> None - thank you.

**Comment by ritahitching** [comment]
1. Confirm with Jenn calendar is up to date 
No meetings to be cancelled
Meeting to discuss CRM between Jane, Debbie, Lindsey, Stacey and Ash needs to be added to the calendar.
2. Announcement
Draw attention to upcoming "Co-planning" meetings, "All Hands" and VAPOR meetings.
3. Confirm LucidMeeting calendar with Lindsey prior to sending tt_report.

**Comment by ritahitching** [comment]
@lijenn let me know if I can help with getting LucidMeetings is up to date, so that I can add it to the tt_report.
thanks!

**Comment by ritahitching** [comment]
Update screen shots
Draw attention to using mtl.how/teams rather mtl.how/live 
Add the additional times of the meetings on LucidMeetings
Email Lindsey

**Comment by ritahitching** [comment]
@lzim sent you an email draft of tt_report.
thanks

**Comment by hnorthcraft** [comment]
#adjudicate_memo update vs
