### ISSUE TITLE
TBD + COVID 19 Updates

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1217]
Update our research & operations data with the latest COVID data from their respective warehouses.

Research and operations use different data sets so they will not have the same changes.

This issue will be broken down further when we have more details.

**Comment by anthonycpichardo** [comment]
CPT Codes and ICD Codes require a sql change if we want to include them for the update.

Moving to "April"

**Comment by lzim** [comment]
@anthonycpichardo Can this be closed? 

I’m not sure how it is distinguished from #1241 and #1242

**Comment by anthonycpichardo** [comment]
@lzim I think its a bit redundant at this point. Closing.
