### ISSUE TITLE
4/17 MTL Red Replace Header logo for Pre/Post Emails

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1219]
1. MTL Red Logos have been uploaded
2. Need to delegate/triage MTL Red Emails w/ Rita

**Comment by lijenn** [comment]
@ritahitching Thanks for catching this! I haven't had the time to work on this, could you please pick it up if you have bandwidth and it seems to also be a part of the work for #1293? 

We do not want to use the general MTL Red Logos. 
Here is the location of the logos that go by session since the pre/post emails go out by session:
https://github.com/lzim/teampsd/tree/master/resources/red_sessions

Thanks!

**Comment by ritahitching** [comment]
@lijenn thanks for confirming - looks like you assigned me already 😄

**Comment by hnorthcraft** [comment]
#adjudicate_memo adding operations label
