### ISSUE TITLE
3/23 Microsoft Teams Options

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#1223]
**Microsoft Teams** 

1. Discuss requirements for MS Teams for TeamPSD.
2. Requirements for CRM 
3. Phone-line purchase

**Comment by ritahitching** [comment]
1. Phone call with @anazariz to discuss prior contact and efforts with IT and installation of MS Teams. Prior correspondence, hurdles and decisions forwarded.
2. Purchase of any phone line - needs to happen outside of Reqlogic
3. Discussion of needs for team on email for help@ and info@

**Comment by ritahitching** [comment]
Place order for single license MS Team through Reqlogic for Lindsey - use gmail account details. due by COB 3/20

**Comment by ritahitching** [comment]
@lzim @anazariz I placed an order for single license for MST through Reqlogic thanks

**Comment by hnorthcraft** [comment]
#adjudicate_memo update vs
