### ISSUE TITLE
wk2 Possible Changes to Splash Page For Team Folder Requests

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#1224]
**Possible Changes to Splash Page For Team Folder Requests** 
Add the following features the Splash page: Team Folder Requests

1. A second confirmation (pop up) before accepting or rejecting a request for a Team Folder to prevent errors e.g. "Do you want to [ACCEPT] or [REJECT] this request?
2. Templates within the Splash page for messages sent out to users of Team Folder requests to include:
(i) request accepted
(i) request denied and why
(iii) you already have an existing folder - details

**Comment by anthonycpichardo** [comment]
@ritahitching @staceypark @lijenn I can take a look and see if thats something we can add

**Comment by lzim** [comment]
@anthonycpichardo 
- I edited this issue title to "wave1" to reflect that it's in **wave1_teams** and no longer due (or late) for March. 📆

**Comment by anazariz** [comment]
The form the is on the SharePoint is an InfoPath form. In order to understand how the form is processing the button click, I tried to start InfoPath 2013, which is on my VA computer, to try to reverse engineer the form and therefore add the requested feature. When I click on the InfoPath link on my VA computer, the program goes through a first time use configuration and ask you to reboot your machine at the end of it. After reboot, a click on the InfoPath 2013 will send you through the exact same configuration. If you skip the reconfiguration,  the program will ask you to validate your license on internet or via phone. This is where I stopped. Although InfoPath is a component of the Office 2013 software, it seems like I do not have a proper setup. I'll need to find out how to proceed.

**Comment by anazariz** [comment]
I managed to resolve the InfoPath Licensing issue. I looked on our site to find the InfoPath form(s) that need to be worked on.   The InfoPath Forms on our SharePoint have the extension .xsn. I did find the forms that are currently displaying under the names Review_Publishing*.xsn. When I tried to open the forms using InfoPath, I recived the following warning. I will do some more research to understand what this message means. 
![image](https://user-images.githubusercontent.com/39805164/96023254-ff416300-0e06-11eb-8fec-5029c1901914.png)

**Comment by anazariz** [comment]
Update: the forms listed above, are not the forms displayed on the site.

**Comment by staceypark** [comment]
@anazariz @anthonycpichardo 
FYI @lijenn 
Regarding Team folder requests I think we need to changes:
**1) We probably need to clarify how to "Enter Team Members." I got to the screenshot below by clicking on Request New Team Folder.** 

![Screen Shot 2020-10-14 at 3 16 16 PM](https://user-images.githubusercontent.com/31089501/96051992-80155480-0e31-11eb-9eaa-3f88e0409039.png)

Specifically, if they don't click on the address book icon, they need to add email addresses separated by a semicolon i.e. test@gmail.com; test2@hotmail.com.
Perhaps we can edit the instruction to:
```
Enter Team Members by Email
e.g. example@va.gov; example2@va.gov
```
**2) Currently there is no way to send additional information regarding a team folder request (whether approved or denied)** I got to this screenshot by clicking on "administrative" on SharePoint > choose a "not started" workflow task > edit item.
![Screen Shot 2020-10-14 at 3 23 42 PM](https://user-images.githubusercontent.com/31089501/96051983-7db2fa80-0e31-11eb-9f3f-6ab87631d9d7.png)

In the form above, if you hit "Approved" or "Rejected" an email is autogenerated to the requester with only the info below.

![Screen Shot 2020-10-14 at 3 33 00 PM](https://user-images.githubusercontent.com/31089501/96052498-8e17a500-0e32-11eb-920a-bdd055a5c3cf.png)

It would be great to add an additional field in that form to include information about how to get to the team folder or why a request was rejected etc. in replacement of the current generic message. That way we don't need to send out two emails for one task.

**Comment by anazariz** [comment]
I'll be looking for the 2 xml configuration files for the forms (listed above) hosted on our SharePoint site on 10/15. If I find them, I maybe able to change the forms' behavior and complete Stacey's request. Will provide additional progress update by EOD 10/15.

**Comment by anazariz** [comment]
@Stacey, 

**Part 1 of your ask - Changing adding a ";"**
We now have access to our SharePoint's two forms ("Request Team Folder" and "Request Team Member Change"). 
However, when I open the forms in InfoPath, which is the software used for creating/editing these forms, I get the message shown : 

![image](https://user-images.githubusercontent.com/39805164/96296736-9e4f9180-0fa4-11eb-9b47-d6d368865d8d.png)

As this is a production site and I don't know what new fields have been added to the forms, I answer no. At which point I still get access to the form and can change the text of the form labels. So I can complete your first ask. Would the change below be OK?

Or should it say:     

Enter Team Members by Email
e.g. example@va.gov; example2@va.gov
  
![image](https://user-images.githubusercontent.com/39805164/96297112-3b122f00-0fa5-11eb-8742-95547e23a9d2.png). 

Also, I can see the workflow actions. But so far I can only activate or deactivate existing ones (e.g. send or not send email, etc.). 
I'll see if I can add new actions and let you know.

**Comment by staceypark** [comment]
Hey @anazariz I’m a little confused by the screenshots here. Are you asking to change the dialogue on both the buttons?

**Comment by anazariz** [comment]
@staceypark  No just the text that's highlighted in red (both forms - you see only one of them here). 
Should it say **List the team members to add or remove - Separated by a ";"**        or  
Should it say **Enter Team Members by Email e.g. example@va.gov; example2@va.gov**

**Comment by staceypark** [comment]
I think on both the forms, we can say maybe a combination of those two:
**Enter team members by email, separated by a ";"** 

> @staceypark No just the text that's highlighted in red (both forms - you see only one of them here).
> Should it say **List the team members to add or remove - Separated by a ";"** or
> Should it say **Enter Team Members by Email e.g. [example@va.gov](mailto:example@va.gov); [example2@va.gov](mailto:example2@va.gov)**

**Comment by anazariz** [comment]
@staceypark  OK. Thx

**Comment by staceypark** [comment]
Thanks for the update @anazariz. To make sure I'm getting it - do you mean that SharePoint changed the structure of the form since we've last worked with it?

> fyi, I get the following alert for the "Status" field when I try to publish my changes. Looks like the field (structure) was changed since the form was last updated. To prevent overwrite, I'll have to investigate this before I publish any changes.
> 
> ![image](https://user-images.githubusercontent.com/39805164/96309486-3441e700-0fba-11eb-9f20-d52f65043efe.png)

**Comment by anazariz** [comment]
When I opened the form for edit in InfoPath, it asked me if I wanted to overwrite the existing list fields in the form with updates, which appreately was the the "Status" field. Initially, I answered no because I didn't know what the field change would do to the form or the workflow. That's where I stopped (the message above). But then I reopened the form and this time I agreed to have the field update to be added to the form. My intention was to not save/publish the form if there was going to be a change to the structure of the form. There didn't seem to be a change. So I made the label change and published the form. Everything seemed to go well. But somehow, I'm not seeing the change in the live form. Maybe there's a time lag between publishing and displaying. I'll figure it out. Will keep you posted.

**Comment by anazariz** [comment]
@staceypark, both forms have been updated to show the ";".

![image](https://user-images.githubusercontent.com/39805164/96491389-0695b180-11f7-11eb-88d6-35996d581899.png)

![image](https://user-images.githubusercontent.com/39805164/96491457-21682600-11f7-11eb-8905-5ae8337d94e6.png)

**Comment by anthonycpichardo** [comment]
@staceypark Part 1 of the change is complete. For part 2, I think thats something we can consider once we move to power automate but may not be worth the development time for the current version. Let me know what you think.

**Comment by staceypark** [comment]
@anthonycpichardo I think it makes sense not to spend energies on this for an intermediary version but to start thinking about how we will use it with the Power platforms. I made a new issue and put it in Epic Backlog so we can track the idea #1546 
> @staceypark Part 1 of the change is complete. For part 2, I think thats something we can consider once we move to power automate but may not be worth the development time for the current version. Let me know what you think.
> 
> This can be closed with your approval
