### ISSUE TITLE
List of TeamPSD Usernames 

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#1231]
**List of TeamPSD Usernames**

1. List of TeamPSD usernames (coordinate with Steve / Stacey)
2. List of permissions granted
3. Save in Team PSD Orientation

**Comment by ritahitching** [comment]
@staceypark please let me know where I can find details of the usernames for TeamPSD members. thanks

**Comment by staceypark** [comment]
@ritahitching I'm not sure what you mean by usernames? for what platform?
Do you mean VA usernames/alias?

**Comment by ritahitching** [comment]
@staceypark please see email from @lzim dated 3/24 and the need for a list of Team PSD usernames for LSV permissions. thanks

**Comment by staceypark** [comment]
Just pingged you back

**Comment by staceypark** [comment]
@ritahitching you mentioned you needed further help on this yesterday, what was the question you had?

**Comment by ritahitching** [comment]
@staceypark thanks not sure what you meant by **GAL** in your email

**Comment by ritahitching** [comment]
@staceypark a list of 43 TeamPSD Usernames is ready to review in out shared drive in the teampsd_orientation folder.
thanks.

**Comment by staceypark** [comment]
@ritahitching 
1. Please make sure all of the text is formatted consistently. I notice a mix of cases throughout the usernames that are not the same. It's probably easiest to do all caps for the usernames to easily distinguish between 
2. I notice you're missing several people from the workgroups you included, such as Joe Bloomquist from EES for example.
3. Ilse's last name is spelled wrong and her VISN should be two digits (everyone's VISN should be formatted as two digits).
4. If you read my initial email with the starting list, you are missing the number at the end for Lindsey's username.
5. Anthony & Ash's usernames are missing.
6. Ren's username is incorrect.

Please double check the list! Btw, the tt report list of recipients is probably a good comprehensive list to use for our team members.

**Comment by ritahitching** [comment]
@staceypark thank you for the feedback. 
I have revised the list following your feedback.   I only included current TeamPSD members. Please let me know if I missed anyone and if the next step is to send to Steve for mapping. thanks

**Comment by staceypark** [comment]
Ok I will review and let you know

**Comment by ritahitching** [comment]
Following HQ meeting March 30, we decide to move this issue to the ice-box until contact with QIICs resumes.

**Comment by staceypark** [comment]
@ritahitching Since this is going in the "Icebox" pipeline, please remove the epics and milestones consistent with the SOP. We will get incorrect data for this epic and milestone if we have issue tasks still assigned to it in the IceBox!

**Comment by ritahitching** [comment]
@lijenn FYI
Current list is in the shared drive in file teampsd_orientation.

**Comment by ritahitching** [comment]
@lijenn I recommend keeping this issue open as more usernames will need to be added in future.
