### ISSUE TITLE
Due 3/27 tt_report week commencing March 30

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#1233]
**tt_report**

1. Possible information for TeamPSD members 
(a) accessing and orienting to 
ZenHub
MS Teams - channels

2. Contact workgroup leads for updates

**Comment by ritahitching** [comment]
Hi all, any updates for the tt_report for the week commencing March 30?
@jamesmrollins @anthonycpichardo @lijenn @staceypark @swapmush

**Comment by jamesmrollins** [comment]
No updates – thank you.

James Rollins, Col - USA (Ret), MEd, MSS
PRAXIS ANALYTIX
(425)919-5153

**Comment by anthonycpichardo** [comment]
Hi @jamesmrollins be mindful of replying to emails from github it posts your email addresses for the world to see

**Comment by lijenn** [comment]
@ritahitching All facilitate meetings are cancelled. Changes are already reflected on Lucid, thanks!

**Comment by ritahitching** [comment]
No updates from quant and other groups group.
Weekly message

**Comment by ritahitching** [comment]
draft tt_report week commencing March 30 
[tt_report_061.docx](https://github.com/lzim/teampsd/files/4395676/tt_report_061.docx)

**Comment by ritahitching** [comment]
@lzim the revised tt_report is ready for review in our shared drive thanks and in MS  Teams

**Comment by ritahitching** [comment]
closing this issue as new tt_report has been sent.
