### ISSUE TITLE
4/10 Acquire 365 Excel License

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1235]
Need access to 365 Excel for our VA accounts in order to store our mailing list for mapping teams to facilitators.

Validation: Will know this is done if both Ash and I have access to Excel Online

**Comment by anthonycpichardo** [comment]
Need to submit a YourIT request for an excel license

**Comment by lzim** [comment]
**MTL Help - #1201 - Cross-ref - #1023, #1167 & #1235 NEEDS to be submitted OIT TODAY!**

- Help emails are produced by Epicenter are showing up in mtl.help@va.gov "sent." 

- When the learner replies, it will reply to mtl.help@va.gov

- List of incoming emails - list of support people for that account - email sent to them that the message is there in the mtl.help@va.gov inbox.

- If the email comes in and there is no one assigned, the flag would show that the support person is missing.

- You would then assign a support person to that email address in the spreadsheet.

- There is a Team PSD member role for monitoring the HELP and INFO emails.

- A-D below make use of the email "category" field:

a) "Processed" and an email pinged assigned support people.

b) If cannot find a support person it will be flagged as "missing."

c) "Export" flag means the email is included in the Excel report.

d) Excel report will say who responded with a "on behalf of..." message in the email.

**Comment by anazariz** [comment]
@lzim @anthonycpichardo 
Created a YourIT ticket: RITM1938737
Requested access to 365 (on-line) access to Excel and Power Automate.

**Comment by lzim** [comment]
> @lzim @anthonycpichardo
> Created a YourIT ticket: RITM1938737, REQ2046875
> Requested access to Excel 365 (on-line) and Power Automate.

@anazariz 

There is a folder in Team PSD where we keep all HelpDesk Tickets (NSD help desk) so that another team member can follow-up, if necessary.

If you need help finding this NSD help desk folder, let us know during Monday’s #hqhuddle

**Comment by anthonycpichardo** [comment]
@anazariz @lzim Closing this issue as our requests were not fulfilled and the ticket has been closed.

Per the latest CRM design we will not be using Excel 365 as a data store and this is no longer needed.
