### ISSUE TITLE
4/16 Add explanation of data_ui vs. team_data_table folders in guides

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1237]
Add an explanation at the top of Blue Session 03 and Red Part 02, outlining the difference between the data_ui and team_data_table folders.

Double check both SEE and SAY guides in both arms.

@branscombj @dlkibbe I've assigned it to both of you for now, because I'm not sure who has the bandwidth to pick this up.

**Comment by lijenn** [comment]
From Mon. 3/30 WG Leads meeting:
- Follow up/Need to create a Pull Request
- Stacey or Jenn needs to update cheatsheet

**Comment by staceypark** [comment]
done!

**Comment by hnorthcraft** [comment]
#adjudicate_memo adding operations label
