### ISSUE TITLE
WAVE1 BUG Data UI Removal or Escape of Special Characters from Clinic List

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1238]
Need to escape any special characters from the clinic names or any other variables that would impede the sql queries.

Review: Code review from Ash that will check the parsing of special characters in the sql queries.

**Comment by anazariz** [comment]
Added a function called removeSpecialChar. This function is used in the getData sub and is configurable. Please see VBA code for additional information.

**Comment by lzim** [comment]
Hi @anazariz This looks ready to be closed. Is it? 😃

**Comment by anthonycpichardo** [comment]
i believe it is. Closing.
