### ISSUE TITLE
wave1 Data UI Double Click Functionality for SPReferrals

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1239]
The Double Click a Clinic to select does not work for SPRefferals. Need to address that

**Comment by lzim** [comment]
@anthonycpichardo Updated Issue Card Due Date to reflect **wave1_teams**

**Comment by anthonycpichardo** [comment]
@anazariz I've completed this, in ash_workarea, lets add this bundle all of the data_ui bug fixes together for review.
