### ISSUE TITLE
SEP task: Operations Script Validation and Documentation

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1240]
Review and annotate the code carefully (splashpage first, then Data UI, then Team Data Table)
Review the annotated code carefully against the MTL and Team PSD documentation.

Parse SQL code on mtl_code into the 3 major production tasks
- [X] go_live - mtl.how/data (splashpage)
- [ ] MAY - Data UI
- [ ] MAY - Team data table (flat file for Sim UI)

**Comment by lzim** [comment]
@anazariz and @anthonycpichardo 

- Can you please clarify using a checklist and specific dates how you will verify what this card describes?
For example, **who** by **when** will produce **what** for advance circulation and **verification** at which **existing workgroup meeting?**

**Comment by lzim** [comment]
### Discussed at #hqhuddle 4/17/2020

**Cross-ref **mtl.how/bugs** (bug_tracker)**
#1238 
#1153 

**Cross-ref **mtl.how/documents** (documents_tracker)** 
- **document_teams** - #531, #626, #627 (change to **may_epic**)
- **disseminate_scientists_va** - #544, #546 

Goal would be to close the relevant bugs and documents associated with this take card.
