### ISSUE TITLE
 data UI changes for COVID-19

### ISSUE THREAD

**Issue by anazariz** [lzim/teampsd#1242]
**Covid-19 - data integration Research**
Based on the results of #1241 Integrate the COVID data to our data ui and splash pages.

Review: Code review from Anthony and Quality review from Lindsey/Stacey to ensure that we are inline with the expectations.

Requirements need to be further defined for this once we have more information.

**Comment by jamesmrollins** [comment]
@anazariz and @dkngenda to review with @lzim to review in the next Quant WG meeting.
