### ISSUE TITLE
Due 3/30 FY Q2 PCSPD Dashboard

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#1244]
**End of Fiscal Year PCSPD Dashboards**

1. Due 3/30/2020

2. Anything with a **RED** dot on dashboard needs to be **verified/updated**

3. Ensure **ALL** entries on every tab of your dashboard are **GREEN**

4. Entries are in **APA** style

5. **Include** any: 
(i) newly submitted grants
(ii) newly submitted publications
(iii) verify/Update the status for any Grants, Publications, Programs, Products, and Positions that rolled over from FY19
(iv) for grants, update funding status as appropriate
(v) for publications, update from “in press” to “published” as appropriate
(vi) new presentations (ISTSS, etc) - specify workshop/poster/presentation with just the conference name, do not include 34th annual etc. Only include NATIONAL/INTERNATIONAL presentations (e.g., at national/international conferences, national/international webinars). 
 
6. Updates to **shared drive**

**Comment by staceypark** [comment]
@lijenn @ritahitching I'm going to check with Lindsey on this issue at the huddle, and then let's spend 30-45minutes just doing it together. And you guys can write something up as we do it.

**Comment by ritahitching** [comment]
@staceypark
thanks for your help, no problem @lijenn and I can do the write up

**Comment by ritahitching** [comment]
@ritahitching update the documentation on shared drive once Lindsey send updated resume to include details from January through March 2020.

**Comment by lzim** [comment]
Hi @ritahitching 
Note this is just the end of FY Q2 not end of fiscal. I edited the title accordingly.
I updated the database and I'm closing this issue.
