### ISSUE TITLE
4/23 TASK R21 Data Review

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1248]
Go through the Pcharts generated for the R21 and validate that the data is including the correct dataset which should be the Union of ICD9 and ICD10 codes over a 5 year period. 

Review Process: Provide Lindsey/Stacey with a report of what the data set consists of so they can review and validate it.

**Comment by anthonycpichardo** [comment]
Andrew will send the final file that was used to generate the data.

**Comment by anazariz** [comment]
At the Monday WG Meeting, team thought that this ticket should be in the bug_tracker. 
So I'm updating it from feature_tracker to bug_tracker.

**Comment by anthonycpichardo** [comment]
Closing this issue as we have completed the primary analysis and reviewed during the 4/30 Quant wg meeting

R21 ORD research will be continued in mtl_code#9.

**Comment by lzim** [comment]
Morning @anthonycpichardo 

I see that this is now on **mtl_code#9** but I’m confused by this comment, as I haven’t seen any updates on all the next steps identified during the 4/30 **quant_workgroup** meeting.

- Can we be sure to include all the next steps as a checklist of requirements to **mtl_code#9** so nothing falls through the cracks?

> Closing this issue as we have completed the primary analysis and reviewed during the 4/30 Quant wg meeting
> 
> R21 ORD research will be continued in mtl_code#9.
