### ISSUE TITLE
wave1  Check DB User Authorization + 3 

### ISSUE THREAD

**Issue by anazariz** [lzim/teampsd#1249]
Checking Clinician's DB connectives:

1-Check their DB Account Privs using the link that Andrew provided. See email for details.   
Correlate the results.
2-Check their LSV access using the Data UI method
3-Check their LSV access using the connectivity Excel method

These users will provide insight into how Local and National DB privileges are impacting the Data UI.

Test will consist of having the users go through Ash's permission test and then clicking the two buttons on the Data UI

A positive result will have the users able to generate a team data file and able to get patient level data.

Goal is to determine what permissions are required based on the LSV access a user has.

Relates to Issue mtl_code#6

**Comment by anazariz** [comment]
We may be able to check LSV permissions with Jenn and Rita only. 
May not need Dexter and Steve for this. 

Checking with clinicians should be if all other methods fail. 

Reordering the process:
1-Check users' their DB Account Privs using the link that Andrew provided - find local users.
2-Check users' LSV access using the connectivity Excel method
3-Check users' LSV access using the Data UI method
Correlate the results.

Relates to Issue mtl_code#6

**Comment by lzim** [comment]
@anazariz and @anthonycpichardo 

I edited the title to reflect **wave1_teams**
