### ISSUE TITLE
Team Data question

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#125]
NEVERMIND: I FIGURED OUT WHY THIS IS A DUMB QUESTION!
I'm running v1.6 Test in Chrome, World 7. I've looked at 2 data parameter files and for both of them, the New Patient Start Rate in the Team Data Table is 0 for all services except Review. Am I missing something or shouldn't some of the other services be non-zero?

Data files:
640a0_mpd_green_18jul2018.xlsx 
640ha_stc_23jul2018.xlsx

screen shot:
(https://github.com/lzim/teampsd/files/2342644/2018_09_01_teamdataquestion.pptx)

**Comment by lzim** [comment]
Hi @branscombj 

Good question!  Thanks for brining this to everyone's attention. @dlkibbe @dlounsbu @staceypark 

There are two key answers to your question:

**ANSWER PART 1: Those data files are not STANDARDIZED to the MTL 1.6, please do not use them.**
This refers to the Team Data Table component of your question. The clue that they are non-standard is that they don't have the new standardized file name (look at the date, which should be yyyy_mm_dd).

Until I get more ready - something I'll be doing soon - the only file available this morning that will work is named **'640_a0_blue_2018_08_30.xlsx'**. 

This file is available in Epicenter, but if you don't have it loaded in your world 7, you'll need to add it by typing it in exactly in the Team Data Maintenance box at log-in.

**ANSWER PART 2:  This isn't in the team data table, but is related. Note that in the patient section of AGG model diagram in the main tile, there is a difference between the upper patient flow and the bottom. When you toggle to display patient services, if you select "review," then everything down stream goes to zero. And, if you select any other service besides "review," then review goes to service.

QUESTION for @TomRust and @jamesmrollins: **Can you look into a potential discrepancy between the Team Data Table in AGG says "New Patient Start Rate" and the "Review Rate" variable in the main tile and the experiment tile slider?** In the ModelParameters.xlsx file tab AggParams cell A6, and in "Master_Crosswalk_Table_v10_30AUG2018.xlsx" AGG Tab row four we show a standard variable name of "New Patient Start Rate."

Perhaps I'm missing something, but what is the "bc" value for the Review Rate slider, if it is not the "New Patient Start Rate."

Thanks!

Lindsey

**Comment by lzim** [comment]
Re-opening this issue. Please see my answer above to @branscombj and alerting all about what data to use for now @dlkibbe @staceypark and @dlounsbu 

 Please also see my question for @TomRust and @jamesmrollins 

Thanks!

**Comment by TomRust** [comment]
@lzim @jamesmrollins 

I double checked the data connections, and the right variables are being read into both the Team Data table and the UI from the Vensim. The details are below.

In checking on these across the data, Vensim, and UI, I think there is a legacy name under the "Display Patient Services" radio button selections.    I think we should change the label "Review" to instead say "Intake," to be more consistent with the Model Diagram. 


    Appt. Supply (median) (Intake) = ModelParameters.xlsx, AggParams, B2

     Review Rate = is calculated in the model, based off of the team's data on "New Patient Start Rate" (which is B6 in ModelParameters, and Row 4 in CrossWalk) and "Appropriate Patient Start Rate for Supply[Intake]"  Specifically, the Review Rate is the remainder of the "New Patient Start Rate" after we pull out all the appointments they completed with an intake/eval CPT code.  Review Rate = New Patient Start Rate (mean)[Intake] - Appropriate Patient Start Rate for Supply[Intake]  This allows us to separate out the two types of "new to a service" starts -- those that were preceded by an intake/eval CPT coded visit, and those that weren't.

If you want to show the base-case number for the "Review Rate," just link to the variable "Data on Review Rate" in Vensim.

     Intake Evaluation Rate = Vensim variables "Appropriate Patient Start Rate for Supply[Intake]" AND "Appropriate Intake Evaluations for Supply" AND "Intake Evaluation Rate"  They are all the same value.

**Comment by jamesmrollins** [comment]
@lzim @TomRust 

So you want me to change the label below from "Review" to "Intake?"

![image](https://user-images.githubusercontent.com/30132017/45069701-ae38df80-b082-11e8-9859-7886a4f7a288.png)

**Comment by TomRust** [comment]
Ahh!!! Everything is connected!!! Thanks for thinking this through farther than I did, James.  

Since it would be such a pain to change, I will defer the decision to Lindsey.  To me, the current labeling is confusing, as the "Review" radio button allows you to see the rates and stock related to "Intake Evaluations."  The value for "Review Rate" (line 132 in the Master Crosswalk) isn't visible in the UI, anyway.  

Perhaps we should add "BC" buttons to both the "Review Rate" and the "Intake Evaluation Rate"...or add those values to the Team Data table...or both!


--TOM

**Comment by jamesmrollins** [comment]
@lzim @TomRust 
I can change "Review" to "Intake" pretty easily for Ver 1.6.  I would like to issue that change no later than tomorrow.  However, the addition of base case to other variables will have to wait for Ver 1.7.  And I agree, I would like to hear from Lindsey before making the changes, not because I disagree, but just in case there is something neither of us thought about.

**Comment by jamesmrollins** [comment]
![image](https://user-images.githubusercontent.com/30132017/45135929-aa768d00-b156-11e8-9756-1ef7fd439650.png)

How about this for gender neutral?

**Comment by lzim** [comment]
@jamesmrollins and @TomRust 

James and I decided to:

1. Change the "Review" radio to "Intake" for Display Patient Services
2. This change will also be in the prefix for the results dashboard.
3. At least for tomorrow, we're going to use the MTL 1.6 feature of dynamic "i" information to add this detail you described to the "Review Rate" "i" in the experiment slider (even though it mixes where the data come from with what you're changing - we feel this is a more minor breach of protocol, then not having them have a way to look up review rate in the team data table for a red slider - we can resist this later).

"Review Rate is calculated in the model team's data for "New Patient Start Rate,” which is B6 in AggParams, and “Appropriate Patient Start Rate for Supply[Intake].” The Review Rate is the remainder of the "New Patient Start Rate" after we pull out all the appointments they completed with an intake/eval CPT code. 
User can set a new number of patients per week who start a new service without an intake appointment, regardless of whether or not the team has enough supply for the patient demand (default value is "-1" which uses the ideal start rate)."

James is also going to:
1. Fix the image icon to gender neural (see above)
2. Change the chat tile headers to "Chat with your facilitator" and "Chat with your team."

Thanks!

**Comment by jamesmrollins** [comment]
Items noted above have corrected.
