### ISSUE TITLE
WAVE1 + DATA UI - Validate VBA joins - 3 

### ISSUE THREAD

**Issue by anazariz** [lzim/teampsd#1250]
**1. Add description:** 

LSV - DATA UI - Validate VBA joins 

Check joins in the Data UI VBA to see if non-LSV connection are used.  
User are supposed to get LSV (local to their VISN) authenticated based on Their AD accounts. Unless one of the queries is joining them to other servers and databases tha they do not have access to. This needs validation and potentially remediation if that is happening.

**Comment by lzim** [comment]
Thanks @anazariz 🔥

**Comment by anazariz** [comment]
@lzim @anthonycpichardo 
A single SQL query can join tables from different servers and databases. Our Master Data UI workbook runs such queries to extract and combine data from 2 servers with LSV and non-LSV databases. While this does not throw an exception at the Master Level (for those with national-level access), after workbook propagation, the queries should not contain joins between LSV and non-LSV databases. The objective of this inspection is to detect such joins and if found, remove (thru redesign) the dependencies.
