### ISSUE TITLE
wk1 NDS Check - 8

### ISSUE THREAD

**Issue by anazariz** [lzim/teampsd#1251]
**1. Add description:** 

Tickets #1249 and #1250 deal with potential reasons for Data UI's getting access issues. Should those tickets not produce results, we have to check with the NDS team (Per Andrew) for additional triage to see why a user who should have access to the LSV views may not. This ticket may have to be close should there be no need to do this level of triage. Need to NDS resources (involved in the Active Directory Provisioning) to understand the mechanisms and rules involved.  

Relates to mtl_code#6

**Comment by lzim** [comment]
@anazariz 

- I'm not sure this accurately captures what NDS can and cannot tell us. 
- We'll double-check on this, but for now, I'm change the title from due 4/10 to reflect **wave1_teams**
