### ISSUE TITLE
4/24: RedCAP project for R01 measures - 6 Months

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1255]
- Baseline for Blue and Red have been done and reviewed (#814)
- Do the same for the 6 Months 
- [x] MTL Blue & Red Logos are correct
- [x] Use MTL Language (refer to appendix file)
- [x] Double check measures (refer to appendix file)

**Comment by ritahitching** [comment]
@staceypark @lijenn @ritahitching 
Please clarify the following:
1. The VA RedCap project and instruments for the R01 baseline measures has been done and verified by @lijenn - already have access to this RedCap project.
2. Has the project and instruments for the R01 6 month follow measures already been coded?
3. Confirm where is the where is the survey for R01 6 month follow up submitted to IRB can be found to compare it to the coded RedCap project OR can be used to code a new project.
4. If 6 month follow measures instrument has not already been coded, should it have its own project or live within the same project as the baseline R01 measures.

Once this specs are clear either @ritahitching or @lijenn will be assigned the task.

**Comment by lijenn** [comment]
@staceypark Hi Stacey, I'm seeing Participatory Measures (i.e Context, Partnership Structural Values, Synergy, etc.) in the instruments for the R01 project. However, these measures are not in the R01 appendix document. 

Should the Participatory Measures be removed from the R01 project or added onto the R01 appendix document?

**Comment by staceypark** [comment]
@lijenn those should only be in the IIR and not R01. You can take them out I believe.

> @staceypark Hi Stacey, I'm seeing Participatory Measures (i.e Context, Partnership Structural Values, Synergy, etc.) in the instruments for the R01 project. However, these measures are not in the R01 appendix document.
> 
> Should the Participatory Measures be removed from the R01 project or added onto the R01 appendix document?
