### ISSUE TITLE
VAPOR Week 3 Video Selection and Upload

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1256]
Cross ref: https://github.com/lzim/teampsd/issues/315#issuecomment-601787269

 - [x] Identify new content for session 2 VAPOR video (02:36-'2:59 | D.C. - Take 2)

- [x] Editing is needed and then upload onto YouTube

**Comment by lijenn** [comment]
@lzim I made this card so the task doesn't get lost back in issue 315 which is a closed card. Thanks!

**Comment by lzim** [comment]
> @lzim I made this card so the task doesn't get lost back in issue 315 which is a closed card. Thanks!

Thanks @lijenn I think we will be able to finish this over the weekend 😺
