### ISSUE TITLE
Due 4/1 Chrome bug when displaying mtl.how/team

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#1273]
**1. Chrome bug when displaying mtl.how/team:** 

@jamesmrollins I came across some display issues for mtl.how/team in chrome. 
Please see screenshots below. I types mtl.how/team in my chrome browser
I found consistent displays in Edge and Safari.
Thanks,

## Chrome Browser mtl.how/team
![chrome_error](https://user-images.githubusercontent.com/54862187/78076668-b8ed5080-735b-11ea-923f-d6d6dd6b0578.jpg)

## Safari & Edge Browser mtl.how/team
![edge_safari_no_error](https://user-images.githubusercontent.com/54862187/78076746-d7ebe280-735b-11ea-92ab-3788835c95cb.png)

**Comment by jamesmrollins** [comment]
Hi @ritahitching I checked this out with my browser with no issues.  Did you by chance run the "Inspect" routine and capture the "console" error messages?  I should cover that procedure with all of you, as it is essential to determine the origin of the problem.  Normally, these things are caused by a server unavailable issue.  Can you try to access via Chrome again and see if the issue is still there?  If so, perhaps we should share a screen so I can take a look.  Let me know . . .  James

**Comment by ritahitching** [comment]
@jamesmrollins 
Please screen shot of the element, I'm sorry I did not think to include it earlier. 
No need to cover the process for me, but it's worth adding to the training manual.
Please let me know if you need anything else.
thanks,

![Screen Shot 2020-04-01 at 7 39 58 AM](https://user-images.githubusercontent.com/54862187/78150606-5e500500-73ec-11ea-944b-7ec18a3f94bb.png)

**Comment by ritahitching** [comment]
@jamesmrollins thanks for the call this morning. I'm sorry we were not able to fix the bug.  I'm adding the console screens shots here for reference. Happy to help if you need me.
thanks, 

![image.png](https://images.zenhubusercontent.com/5e4c144d178a4973ff70f372/287ac6bc-c8ae-4657-a3e8-7c8af52692aa)

![image.png](https://images.zenhubusercontent.com/5e4c144d178a4973ff70f372/dd1af19e-2520-48f1-bbc5-5543c7f38976)

**Comment by lijenn** [comment]
@jamesmrollins @ritahitching 

I can see **mtl.how/team** fine in Chrome.

However, I believe I'm starting to see the same issue as well, but for **mtl.how/demo** in Chrome (Mac). Similarly, I can see the page fine in other browsers or incognito on Chrome. I have also heard back from Window users that they can see it fine on Chrome.

![image](https://user-images.githubusercontent.com/59668647/78797085-15f49200-796c-11ea-883b-8706c21f86c2.png)
![image](https://user-images.githubusercontent.com/59668647/78797396-7edc0a00-796c-11ea-80cb-2fbabc6b2691.png)

Please do keep me in the loop and let me know what you decide to proceed with as I recall trying something regarding cookies.

**Comment by jamesmrollins** [comment]
@hirenp-waferwire there is an interesting issue arising with the Team PSD website on Chrome.  I have tried the following:

1.  If we open the web page in "incognito mode", the page works. This would indicate a cookie problem.  But,
2.  When we go into browser settings and delete the cookies, the page still does not load.  

Will you check it out please.  Let us know if we should run further tests.

FYI @ritahitching @lijenn

**Comment by jamesmrollins** [comment]
Engaged in troubleshooting with @lijenn and @ritahitching to determine cause of problem. 

1.  Suspect cookies were preventing proper loading of screens in Edge and Chrome, pages load properly in Incognito mode.
2.  Cleared cookies and web elements from cache from the Chrome/Edge setting screens.
3.  CLOSED ALL BROWSER TABS and then opened a new tab.  Pages loaded properly. Suspect cookies do not clear from open browser tabs.
4.  Also, users must ensure that cookies are cleared all the way back to their Chrome account to prevent reload. 

ISSUE RESOLVED....

**Comment by ritahitching** [comment]
@jamesmrollins @lijenn thank you for working to resolve this bug. I'm closing this issue. thanks
