### ISSUE TITLE
MTL Video - TMS Supplementary Documents 

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1275]
Goal: identify most crucial changes that may affect learning and increase confusion from the 1.7 videos for mtl 2.0

Requirements/Task:
- [x] 4/22-23 - Check 1.7 & 2.0 differences from guides & videos 
- [x] 4/22 - Deadline for a Final Template
- [x] Look at pop-up edits (#748) and depend_products as this may help address the need to provide only crucial changes, double check the version since some are 1.8
- [x] 4/30 or 5/1: Send Joe the documents in .pdf to upload on TMS

Other notices/concerns:
- [x] References in "More Info" on SIM UI listing all the links to the Learner SEE Files are broken [Will depend on whether or not the New "More Info" is in Prod by 4/24]
- [x] Guide edits: change mtl.info email into mtl.help
- [x] Guide edits: change "Disclaimer" language into "Note:"
- [x] Incorporate Debbie's from the word doc edits
- [x] #1359 edits

**Comment by lijenn** [comment]
@branscombj @dlkibbe Hi Jane and Debbie! Sorry for the delay in this. The video buffering makes it so slow to review things quickly!

I had some questions while scoping out essential and crucial changes that should be addressed in these additional documents (I have all of the information and sessions compiled into 1 document for convenience for now, will need to separate them into separate documents based on session and come up with a template afterwards). 
[mtl_video_supplementary_info.docx](https://github.com/lzim/teampsd/files/4483282/mtl_video_supplementary_info.docx)

1. Should I include timestamps of when they should refer to the points mentioned?

2. Would it be helpful to link the Learner See guides in the supplementary document as a shortcut? 

I only included a disclaimer of referring to the guides for new and exciting changes in 2.0. I also tried to limit the amount of new features that needed to be mentioned as I believe the guides should be referred to for that purpose. I only provided/reminded first hand discrepancies mentioned in the videos that may seem confusing or make to learners worried in that moment.

3. I noticed mtl.help@va.gov is mentioned in the videos (although I did not catch all the mentions. 

From discussing the CRM on Monday, it was my understanding that MTL Help is to be used by the teams since this email is based on co-facilitation and MTL Info is for more of a general audience and general questions (please correct me if I'm wrong). 

However, since we also now have MTL All, I was wondering if this would be confusing? I could make a disclaimer that MTL Help is only used for MTL Blue/Facilitated sessions and for MTL All to use MTL Info email instead?

**Comment by branscombj** [comment]
> it was my understanding that MTL Help is to be used by the teams since this email is based on co-facilitation and MTL Info is for more of a general audience and general questions 

Hmm. Good question. Since we can't change the audio or pop-ups in the videos now, I think we're going to have to live with any emails from non-participants that come to MTL Help. We can try to reply to them from MTL All where appropriate. I don't think a "disclaimer" type message would be good (one that parses what the video says); but we should just use the MTL All email address and link to it where we would want that to be used. 

That's my thought, but I might have to look at how we're providing this update info. Others' thoughts? @staceypark @dlkibbe @lzim 

This does raise the point that we need to ID **where to file emails from non-participant addresses** (@anazariz ). And we should also consider the case in which the **"from" address of an email from a participant doesn't match the one we have on file** - e.g. if their mail client is set up to default send from a non-VA address.

**Comment by lzim** [comment]
@branscombj @lijenn @staceypark @dlkibbe 

I think we can get all the emails from ESS for any TMS registered _MTL Video_ leaders and that could be included in a sub folder that we assign to folks from **hq_workgroup.**

We still may end up with some completely "_MTL_ for all" folks, but it should help with workflow and tracking support.

**Comment by lijenn** [comment]
Guides that mentioned mtl.info and have been edited to mtl.help:
2.0
- [ ] Session 1
- [ ] Session 2

1.7
- [ ] Session 1 - update Lindsey and Stacey's email to mtl.help

**Comment by lzim** [comment]
Discussed the creation of a standard template for the _MTL Video_ documents at today's #hqhuddle:

- @lijenn plans to draft a template by COB Fri 4/17 Pacific.
- @branscombj and @dlkibbe Jenn is hoping to quickly review this template at the Monday morning 8AM Workgroup Leads meeting, hopefully you can take a peak on Monday morning before the meeting.

Happy Friday 🌴

**Comment by lijenn** [comment]
@branscombj @dlkibbe Here is a working draft of the template, let me know what you guys think! Have a great weekend!
[supplementary_draft_temp.pdf](https://github.com/lzim/teampsd/files/4495678/supplementary_draft_temp.pdf)

**Comment by branscombj** [comment]
Morning @dlkibbe  and @lijenn ! I like it! 

Comments:

> New! Data User Interface Updates: 

- What about a tag line that makes more clear what this Video Supplement document is, like "A quick guide to updates and improvements you may notice since *MTL* Video was recorded" - Then you could have a generic (see next comment) sub-statement that says "For all of the new features, please refer to the Learner See guide for this session at mtl.how/blue." 

This also makes the template require less tailoring for each session, and for the learner lends comforting familiarity/continuity.

> Please go to https://mtl.how to the MTL Blue Session 2 See Guide to review all the 
new MTL 2.0 updates and features added on the BISL SharePoint splash page and 
data_ui file. 

- There are so many clicks (5) to get to the document referenced, and not all of them are apparent from this instruction. (Type mtl.how. Click Blue. Click session02. Click s02_learner. Click mtl_session02_see.md.) Can we provide more of that path, if we keep it specific to each session in the template, or maybe a more general instruction e.g. "Go to the Learner resources for this session at mtl.how/blue."

Formatting: Allow more space below the header - it should stand on its own as a header. I recommend reducing the font sizes and the line spacing to make the sheet look shorter/more compact. I might suggest a horizontal line between updates, and top-justifying the text on the left with the image on the right.

Do we need to provide the email address in addition to the embedded link?

**Other note re: the See guides:**

> Disclaimer: If you are a self-directed learner, then some of the details in the guides may not apply to you. These guides were developed for facilitated Modeling to Learn Live team meetings.

I would caution against using "Disclaimer" for this - I would suggest "Note:". "Disclaimer" suggests denial, repudiation - not taking responsibility for what happens. It makes sense for us to use the term internally, but I worry about how it might land on others at the top of our guides.

**Comment by lijenn** [comment]
Thank you @branscombj for this incredibly thoughtful and easy to follow feedback. 

> Formatting: Allow more space below the header - it should stand on its own as a header. I recommend reducing the font sizes and the line spacing to make the sheet look shorter/more compact. I might suggest a horizontal line between updates, and top-justifying the text on the left with the image on the right.

I've incorporated:
- [x] document tag-line
- [x] generic guide sub-statement
- [x] format it the best to my abilities
I tried to include existing TeamPSD MTL style by using the red arrows, but if that looks too distracting, I can just use a plain horizontal line.

> There are so many clicks (5) to get to the document referenced, and not all of them are apparent from this instruction. (Type mtl.how. Click Blue. Click session02. Click s02_learner. Click mtl_session02_see.md.) Can we provide more of that path, if we keep it specific to each session in the template, or maybe a more general instruction e.g. "Go to the Learner resources for this session at mtl.how/blue."

In addition to getting to the referenced See Guide, I was thinking of having Session 2 (and beyond) to just have the general direction of going to mtl.blue. 
I was going to provide a more detailed instruction in Session 1 since that would be the first time Learners are going to mtl.how and will most likely need the detailed 5 clicks as you described. What do you think about that in regards to also lending Learners familiarity and continuity?

I also had the same question about whether or not to provide the email address explicitly and embedded in the image as well. I've included both this version as it may be helpful for either learners who prefer the image shortcut or want to keep the email on hand for reference. 

In regards to the other See guides, I can make the edits for the word "Disclaimer" into "Note:". Thank you for mentioning that, I don't think we ever thought about it that way!

[supplementary_draft_temp_V2.pdf](https://github.com/lzim/teampsd/files/4510612/supplementary_draft_temp_V2.pdf)

**Comment by branscombj** [comment]
@lijenn NICE! 

I like the arrows as separators but I agree the bright red is a little distracting. If it would not be straying too far from *MTL* style to keep them as arrows but make them a fairly light gray, that might work? Or just gray bars.

The *MTL* logo at the top is a bit pixelated.

I think in print you can leave off the https:// of the mtl/how address (but include it in the hyperlink) - easier for folks to see how simple the address is to remember.

**Comment by lzim** [comment]
Great work on this @lijenn !!!

I really like what you've done. 🏅 
- [ ] If this will be a .pdf, can we please use Myriad Pro, so that it is 100% consistent with our VA style guide? As long as you create the file on a non VA machine with Myriad Pro uploaded, it will be reflected in the .pdf.

- I agree with @branscombj about a) fixing the pixelation, although I see it more in the screenshots, not the logo. And b) leave off the visible https:// (but retain in the actual link).

- I like how the red arrows are consistent with our _MTL_ and Team PSD red arrow. And, find the mixed fonts more distracting than having the clear separate sections. 👀

**Comment by staceypark** [comment]
@lijenn 
- I agree with @lzim and @branscombj that the screenshots are blurry. Is it possible also to make them brighter? They're quite grey for me, which I imagine will make it harder to read for some folks.
- Since these are session specific, I would even recommend linking directly to the session guide instead of just mtl.how/blue,

**Comment by lijenn** [comment]
@staceypark @branscombj @lzim 
Thank you for all the feedback on the template! Will try my best to reduce blurriness in the logos and screenshots and already have Myriad Pro installed.

- I was also thinking of directly linking Learners to the session guide instead of mtl.how/blue. However, the videos go through that process of getting to the exact guide. Only difference is that there is the blue and red folder now. 
- I also don't want to make it look like Learners should depend on these supplementary docs on getting to the guides directly as there won't be a supplementary doc for each session. 

Maybe others can chime in on this?

- With that said, I have also attached a word doc of all the information I plan to put in these supplementary docs.

Could folks take a quick look and see how they feel about it?
[mtl_video_supplementary_info.docx](https://github.com/lzim/teampsd/files/4523397/mtl_video_supplementary_info.docx)

I have also included the differences mentioned in the 2.0 guides and have highlighted parts from that to indicate that they are also mentioned/discussed in the video and have added that update in the supplementary docs (particularly for Sessions 2, 3, 5 since it deals with the Data and Sim). 

Thanks everyone!

**Comment by dlkibbe** [comment]
Hi @lijenn - made a few comments in the WORD file. Agree that a direct link to session SEE guide is more efficient. There is one item in the word file about CC and MM and the learning mode that language needs to be corrected. I inserted a comment and a screenshot.
[mtl_video_supplementary_info dk.docx](https://github.com/lzim/teampsd/files/4523755/mtl_video_supplementary_info.dk.docx)

**Comment by lijenn** [comment]
@dlkibbe All of these edits are awesome and super helpful, thank you for the feedback!!

**Comment by branscombj** [comment]
@lijenn 
> I was also thinking of directly linking Learners to the session guide instead of mtl.how/blue. However, the videos go through that process of getting to the exact guide. Only difference is that **there is the blue and red folder now**.
> I also don't want to make it look like Learners should depend on these supplementary docs on getting to the guides directly as **there won't be a supplementary doc for each session**. 

I think these are good points, and mtl red will be confusing to people doing mtl video without a facilitator. I suggest not sending them (from this document) to mtl.how, and also not linking to specific sessions. Two ideas:

![image](https://user-images.githubusercontent.com/29778290/80145218-d76ef200-857d-11ea-8233-445f4c77598a.png)
or
![image](https://user-images.githubusercontent.com/29778290/80145651-81e71500-857e-11ea-9992-87c90131fec0.png)

**Comment by branscombj** [comment]
@lijenn I also think the supplement for blue 01 needs to say (as the first update under the header above)

New! *MTL* update @ xx:xx (first mention of mtl.how): A second version of *Modeling to Learn* has been created, called *MTL* Red. *MTL* Video follows the 12-session plan, *MTL* Blue.

**Comment by lzim** [comment]
@lijenn 

Cross-ref: #1365 about orienting to the exciting _MTL 2.0_ release first.
- I wonder if this is consistent with @branscombj’s comment:
> New! MTL update @ xx:xx (first mention of mtl.how): A second version of Modeling to Learn has been created, called MTL Red. MTL Video follows the original 12-session plan, now designated MTL Blue.

- I agree that the general confusion about Blue/Red is best avoiding for a typical _MTL Video_ learner.
- However, I do think it’s nice to go straight to the _MTL Blue_ session guide, unless I’m misunderstanding Jane’s recommendation.

**Comment by lijenn** [comment]
@lzim @branscombj 

> New! MTL update @ xx:xx (first mention of mtl.how): A second version of Modeling to Learn has been created, called MTL Red. MTL Video follows the original 12-session plan, now designated MTL Blue.

I think including the new features in MTL 2.0 mentioned in #1365 in Session 1 after this update statement would be a sufficient orientation and mention.

> However, I do think it’s nice to go straight to the **MTL Blue session guide**, unless I’m misunderstanding Jane’s recommendation.

Just to make sure, by "MTL Blue session guide", we are talking about mtl.how/blue and not the actual specific SEE guide based by session right?

**Comment by lijenn** [comment]
HQ Huddle 4/24 decisions:
- Include directions to mtl.how/blue
- Include directions specific sessions since feedback from pilot reviews indicated trouble finding the see guides (all sessions will have a supplementary doc)
- Mention all the new 2.0 features in all of the docs for each session 

FYI: @lzim

**Comment by lijenn** [comment]
Thank you to everyone that helped with this, I have attached the .pdfs of the final version for all sessions.
[s1_final.pdf](https://github.com/lzim/teampsd/files/4560595/s1_final.pdf)
[s2_final.pdf](https://github.com/lzim/teampsd/files/4560596/s2_final.pdf)
[s3_final.pdf](https://github.com/lzim/teampsd/files/4560597/s3_final.pdf)
[s4_final.pdf](https://github.com/lzim/teampsd/files/4560598/s4_final.pdf)
[s5_agg_final.pdf](https://github.com/lzim/teampsd/files/4560600/s5_agg_final.pdf)
[s5_cc_final .pdf](https://github.com/lzim/teampsd/files/4560603/s5_cc_final.pdf)
[s5_mm_final .pdf](https://github.com/lzim/teampsd/files/4560606/s5_mm_final.pdf)
[s5_psy_final.pdf](https://github.com/lzim/teampsd/files/4560610/s5_psy_final.pdf)
[s5_sp_final.pdf](https://github.com/lzim/teampsd/files/4560611/s5_sp_final.pdf)
[s6_final.pdf](https://github.com/lzim/teampsd/files/4560613/s6_final.pdf)
[s7_final.pdf](https://github.com/lzim/teampsd/files/4560614/s7_final.pdf)
[s8_final.pdf](https://github.com/lzim/teampsd/files/4560615/s8_final.pdf)
[s9_final.pdf](https://github.com/lzim/teampsd/files/4560617/s9_final.pdf)
[s10_final.pdf](https://github.com/lzim/teampsd/files/4560619/s10_final.pdf)
[s11_final.pdf](https://github.com/lzim/teampsd/files/4560620/s11_final.pdf)
[s12_final.pdf](https://github.com/lzim/teampsd/files/4560622/s12_final.pdf)

**Comment by lijenn** [comment]
Updated TMS documents based on BISL/Data UI changes:
[s2_final_2020_10.pdf](https://github.com/lzim/teampsd/files/5330979/s2_final_2020_10.pdf)
[s3_final_2020_10.pdf](https://github.com/lzim/teampsd/files/5330980/s3_final_2020_10.pdf)
[s5_agg_final_2020_10.pdf](https://github.com/lzim/teampsd/files/5330981/s5_agg_final_2020_10.pdf)
[s5_cc_final_2020_10.pdf](https://github.com/lzim/teampsd/files/5330982/s5_cc_final_2020_10.pdf)
[s5_mm_final_2020_10.pdf](https://github.com/lzim/teampsd/files/5330983/s5_mm_final_2020_10.pdf)
[s5_psy_final_2020_10.pdf](https://github.com/lzim/teampsd/files/5330984/s5_psy_final_2020_10.pdf)
[s5_sp_final_2020_10.pdf](https://github.com/lzim/teampsd/files/5330985/s5_sp_final_2020_10.pdf)

**Comment by lijenn** [comment]
Need to update S2 & S3 Supplementary Documents to incorporate PBI Updates, then email Joe at EES to upload updated files.
@mnallajerla @lijenn

**Comment by dlkibbe** [comment]
@lijenn @lzim @mnallajerla 
John K. and I and @branscombj and I had discussions last week after Red, Part 1, session 1 with Durham. Topics of discussion: 
1) a part 1 say guide that breaks down the content for each session, e.g. sessions 1-3 focus on what is this variable or that variable or that spreadsheet? How do we find specific data or information?, and sessions 3-6 could explore trends in the data. 
2) a part 2 say guide that breaks down the content for each session with 7-9 focused on understanding the team data and 10-12 focused on using the data UI and team data table to inform decisions. This would be especially helpful as we all learn to navigate Power BI.
The say guides could include: a) question prompts to engage the team; b) variables to review & discuss each session; c) could apply a QHFD framework to the data UI discussions - what do we think the team trend has been and discuss why actual is different than hypothesis. 
Question - will we pull new data sets during part 1 and part 2 or use only one data set for all 12 sessions?

**Comment by lijenn** [comment]
Clearing 9-clicks since this is a document card.
