### ISSUE TITLE
Dec. Epic: Setup QIICS for VA REDCap 

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1277]
Look for the next Facilitators meeting and slot in a time to quickly alert folks that this is happening (anticipate an email for REDCap account and log-in instructions).
- Set up REDCap for QIICS

**Comment by ritahitching** [comment]
@staceypark @lzim @lijenn @ritahitching 

- This issue is in the Epic Backlog as we don't want to send the QIICS  any email invitations to RedCap
- This task can be closed quickly when we decide to reconvene with the Teams.

**Comment by lijenn** [comment]
8AM WG Leads 8/10:
- Don't discuss with QIICS yet until maybe September depending on where MTL Fidelity will live (maybe team_tracker repo #841)

**Comment by lijenn** [comment]
Closing as we do not want Facilitators to learn a new platform just to show results (Session 4 MTL Menu).

**Comment by hnorthcraft** [comment]
#adjuducate_memo @lijenn
looks like there was some work, can we update the SP
