### ISSUE TITLE
4/3 Replace Broken Links in Do and Done Logos in Pre and Post Emails

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#1278]
**Replace Broken Links in Do and Done Logos in Pre and Post Emails**
 
cross reference #1176 

1. Create new branch rita_2020_04_02_logos_pre_post_emails
2. Replace the links in the logos for the **do** and **done** pre_session email S1-S12 [here](https://github.com/lzim/teampsd/tree/master/mtl_facilitate_workgroup/pre_post_emails/pre_emails)
3. Replace the links in the logos for the **do** and **done** pre_session email S1-S12 [here](https://github.com/lzim/teampsd/tree/master/mtl_facilitate_workgroup/pre_post_emails/post_emails)
4.  Ensure correct logos are used for **Done** and **Do** - The **Done** is the one with the check mark and the **Do** is the one with the arrows. 
5. Do not change any other aspects of the template
6. Make a pull request

**Comment by ritahitching** [comment]
@staceypark 
For session 12 of the post session email - where should the **do** icon link to? thanks

**Comment by staceypark** [comment]
@ritahitching I think it could link back to the general mtl.how page

**Comment by ritahitching** [comment]
> @ritahitching I think it could link back to the general mtl.how page

@staceypark thanks 
I will insert the link https://mtl.how for S12 post email
Please see the upcoming pull request for this issue in #1280

**Comment by ritahitching** [comment]
@staceypark 
-  Where it was needed I updated the [**done check  logos**](https://raw.githubusercontent.com/lzim/teampsd/master/resources/icons/done.png) and the [**done arrow  logos**](https://raw.githubusercontent.com/lzim/teampsd/master/resources/icons/do.png).
- Session S10 and S11 pre email has an extra mtl.how/sim icon - I deleted them.
- I remade a pull request in the same branch rita_2020_04_02_logos_pre_post_emails #1284

**Comment by ritahitching** [comment]
I am closing this issue as github repo has been updated and pull request merged.
