### ISSUE TITLE
wk3 apr_epic story_1 - R21 days to EBP completion

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1281]
### Check off requirements to verify progress through feature_tracker.
- [ ] 1. **DEFINE in work_breakdown**
  - [ ] a. **what & why** - **written definitions of requirements** in a **numbered checklist**
    - [x] 1. There shall exist a crosswalk between Aim 1a and Aim 1b rule definitions and the R21 data scripts to better facilitate the relationship between what is documented and where it lives in the code.
    - [x] 2. There shall be validation and if needed correction of the data used for the R21  P charts
    - [ ] 3. There shall be an xbar-S chart generated from the final comparator file for the R21
    - [x] 4. Research related R and SQL code shall be hosted on mtl_code Github to allow for more effective source control as well as a more efficient way to document resources
  
  - [ ] b. **date & who** -  **Verified** requirement definitions an **existing team meeting.** 
---
- [ ] 2. **DESIGN** in **operations_to_do** and **research_to_do**
  - [ ] a. **what & why** - **_MVP_ of design** of requirements in a **algorithm map, wireframes or design** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** design **asynchronously** or an **existing team meeting.** 
---
- [ ] 3. **DEVELOP** in **under_development** - "frozen"
---
- [ ] 4. **TEST in functional_test**
  - [ ] a. **what & why** - **TEST requirements** using **testing_checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** via TEST **asynchronously** or an **existing team meeting.** 
---
- [ ] 5. **PROD in done**
  - [ ] a. **what & why** - **_DOCUMENT_ feature** using **document_tracker** for the **5 D's.** 
  - [ ] b. **date & who** -  **DELEGATE**
    - [ ] **describe_learners** [Jenn & Rita]
    - [ ] **detail_facilitators** [Jane & Debbie]
    - [ ] **document_team** [Anthony]
    - [ ] **disseminate_scientists_va** [Anthony]
    - [ ] **depend_products** [hq & ees]
---
- [ ] 6. **closed** - fully documented, trained and ready for the next release.

**Comment by anthonycpichardo** [comment]
Key Notes and Action Items from 4/09/20 Quant Workgroup Meeting:
Next Steps for Pivoting to more Research due to COVID-19

r21_r01_iir_procedures documentation on OSF 

*Still needed: Better crosswalk between OSF and Team PSD Folder.

1. **GitHub mtl_code is okay for our NIH/VA "Research"

 Action Item: Bring ALL of our .r and .sql code from the Team PSD folder on to the private mtl_code repo where code reviews can be done using standard pull re

 

*DART: Data Access Research Tracker Request

**To do: Need to identify which .sql queries were used for the R21, and need to make sure that they go through B2 and the R21 ORD project, and not through A01 and our Operations permissions.

**To do:  We will need a DART and a ORD for the R01 and a separate one for the IIR.

**After approved:  VINCI will help us set this up and create a patient cohort according to our IRB approvals at Stanford.

Will Update The Master Card with applicable details.

@anazariz @anthonycpichardo

**Comment by lzim** [comment]
@anthonycpichardo @anazariz 

Do we think the title of this card could better reflect what this is?
It is hard to discern with the vagueness of the title.
When combined with the wide-array of the details in the issues, I cannot define what this is clearly.

**Comment by anthonycpichardo** [comment]
@lzim @staceypark  can we verify the requirements piece outlined above? Thanks! =)

**Comment by lzim** [comment]
> @lzim @staceypark can we verify the requirements piece outlined above? Thanks! =)

Yes, I think that the requirements at the top comment are accurate, but may not be fully complete.

I believe another task is to review the DART and ORD for the R21 to make sure that is all working properly too. Let's discuss at tomorrow's **quant_workgroup.**

@anthonycpichardo  Will you please add #1281 to the agenda tomorrow?

FYI: @anazariz

**Comment by anthonycpichardo** [comment]
> > @lzim @staceypark can we verify the requirements piece outlined above? Thanks! =)
> 
> Yes, I think that the requirements at the top comment are accurate, but may not be fully complete.
> 
> I believe another task is to review the DART and ORD for the R21 to make sure that is all working properly too. Let's discuss at tomorrow's **quant_workgroup.**
> 
> @anthonycpichardo Will you please add #1281 to the agenda tomorrow?
> 
> FYI: @anazariz

@lzim  Sounds good, I will add it to the agenda

**Comment by staceypark** [comment]
@anthonycpichardo reminder - We don't want milestone & epic data in master Feature cards or master Document cards, as these will create fake inflation in the ZenHub reports. I took it off for this one. Could you do the same for #1192.

**Comment by lzim** [comment]
**quant_workgroup:**
@anazariz @anthonycpichardo @dkngenda @staceypark @lijenn 

Let's keep track of who exactly is doing what across what appear to be MANY related issue tasks:
- Can we come on Monday with updated **due_date** that follow our **Team PSD week 3 MVP user testing schedule?**
- Can we be sure that the **dependencies** are tracked accordingly?
- Can we make sure that right **MVP assignees** (i.e., owners of that feature) and that the right **MVP reviewers** (i.e., users who need to test the MVPs asynchronously or at existing meetings) are identified using the **9 clicks** on the right for ZenHub tracking?

#1439  STTM 
#1422 lzim/research 
#1440 .r, .md, .sql Style Guides
#1429 Split Pipeline Data Lineage
#1401 GH actions w/Markdown Lint


_See **quant_workgroup** later today:_ 
We'll meet on Teams to pick up in the the same discussion context. 
- I'd like to start with spending no more than 5 minutes reviewing the slides we covered of the STMM prototype with the documentation in Teams. I can do this.
- Then, I'd like Ash to keep going for ~20 minutes for that video.
- I'd really like to try to get through 2 videos during the hour we've scheduled.

We'll need to use Zoom to record. There an integration hurdle:
- Zoom will automatically output the notes we take in the chat.
- But, this will pull the conversation out of context, which we can track on Teams for the sprint.

Recommendations?

**Comment by lzim** [comment]
Discussed today re: #1441 #1442 #1443

**Comment by anthonycpichardo** [comment]
Remaining item to generate xbar charts

@dkngenda

**Comment by lzim** [comment]
@staceypark 
@anthonycpichardo 
@anazariz 
@dkngenda 

I’m having a hard time tracking how this issue #1281 fits w/ #674 #675 
&
research#22
research#25
research#29

Can you all help? 👩🏻‍💻
I’m hoping we can get these all clearly aligned today to get over the hump on these.

**Comment by lzim** [comment]
@anthonycpichardo 
@dkngenda 
@anazariz 
@staceypark 

Let's discuss this at **8AM Workgroup Leads** on Monday.
I've indicated this as a **blocker** for **R21 Tests of Aims and Findings** due **wk4 feb_epic** since I've identified an easy alternative to what we did before that meets the objectives of the grant.

- [ ] **R21 Need SQL calculation of a column for number of days from EBP initiation encounter to EBP completion encounter during 
- [ ] 12-month pre observation
- [ ] 12-month post observation
- [ ] What about during the modeling intervention period David? What makes the most sense here?

#### Background
- We previously looked to see if an **Intake** to **EBP** could be defined based on how the R21 protocol was written in which we hoped we could link **CPT coded Intake encounters** to our **EBPs.** 
- We found we could not validly identify cases that way as we'd hoped.

However, it would be valuable to adjust and simply consider **days from EBP initiation to completion.**
This is likely the next best estimate that could be validly calculated for **Aim 2.**

#### Proposed Solution
Therefore the **R21 Notebook** and **R21 Findings** would be able to describe these two outcomes:
- **Aim 1b Dose** would be pre and post EBP completers/ EBP initiators (a % or proportion of those who initiation who complete) 
- **Aim 2** would be # **of days from EBP initiation to EBP completion**.

#### Impact
This gets at the **timeliness in days** that we wanted to test in Aim 2.
**It's foundational to two interrelated ideas:**
a) quality care means getting a **_timely_ therapeutic course of an EBP** (i.e., through a full course when you start).
b) **participatory system dynamics modeling helps stakeholders improve EBP course** or continuity, and improving EBP throughput for EBPs known to lead to recovery is key to many feedbacks in  our models.

**Comment by anthonycpichardo** [comment]
Discussed at 1pm Team Time 2/23/21

- EBPsy works because you can easily days between EBPsy initiation and EBPsy completion.
- EBPharm also work for "course/continuity" if we look at days between "issued" scripts.
- Issue - Initial dose was issued.
- Release Date Released to the patient.

But, we want to count # of days between the issued prescriptions by the provider.

CDW/SQL handling of the fact that for a stable patient you may be issued a new prescription without a subsequent.

EBPharm - standard of care - Have encounter with prescriber who evaluates you for a therapeutic response to the mediation.


EBPharm
- # of days between issued meds.

And also # of days between issued meds that can be linked to a visit with a prescriber (psychiatrist, MD) evaluating for therapeutic response.

**Comment by anazariz** [comment]
I have completed the coding on this, run it and delivered the results to the quant research team. Closing this ticket.
