### ISSUE TITLE
COVID Data Project Requirements Card

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1282]
TO BE POPULATED

### Check off requirements to verify progress through feature_tracker.
- [ ] 1. **DEFINE in work_breakdown**
  - [ ] a. **what & why** - **written definitions of requirements** in a **numbered checklist**
    - [ ] 1. 
  
  - [ ] b. **date & who** -  **Verified** requirement definitions an **existing team meeting.** 
---
- [ ] 2. **DESIGN** in **operations_to_do** and **research_to_do**
  - [ ] a. **what & why** - **_MVP_ of design** of requirements in a **algorithm map, wireframes or design** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** design **asynchronously** or an **existing team meeting.** 
---
- [ ] 3. **DEVELOP** in **under_development** - "frozen"
---
- [ ] 4. **TEST in functional_test**
  - [ ] a. **what & why** - **TEST requirements** using **testing_checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** via TEST **asynchronously** or an **existing team meeting.** 
---
- [ ] 5. **PROD in done**
  - [ ] a. **what & why** - **_DOCUMENT_ feature** using **document_tracker** for the **5 D's.** 
  - [ ] b. **date & who** -  **DELEGATE**
    - [ ] **describe_learners** [Jenn & Rita]
    - [ ] **detail_facilitators** [Jane & Debbie]
    - [ ] **document_team** [Anthony]
    - [ ] **disseminate_scientists_va** [Anthony]
    - [ ] **depend_products** [hq & ees]
---
- [ ] 6. **closed** - fully documented, trained and ready for the next release.

**Comment by lzim** [comment]
@anthonycpichardo @anazariz @staceypark 

Before tomorrow's **quant_workgroup** meeting, let's try to get this 
1. over to **mtl_code** repo
2. using a (hopefully) final standardized **master feature card** (cross-ref: #921)
3. bring in the updated information about COVID-19 in CDW

**Comment by jamesmrollins** [comment]
@anazariz and @dkngenda will review this card with @lzim during the Quant WG meeting to determine if this is an active requirement, if it can be closed, or if it needs more work.
