### ISSUE TITLE
wk3: Move all VA RedCap projects from development to production

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#1290]
**Move all VA RedCap projects from development to production**

- [ ] Move all RedCap projects from development to production once edits are finalized. 
- [x] We need to factor time for VA RedCap to review and accept the project.  @lijenn will contact VA RedCap and get an estimate on their turnaround time.
- [x] Priority projects include:
 - IIR Team Red Baseline
 - IIR Team Blue Baseline
- IIR Team Red Follow-up
- IIR Team Blue Follow-up
- MTL Menu (MTL Live)

cross ref #483

**Comment by ritahitching** [comment]
@lzim @staceypark 

- [ ] @lijenn and I finalizing the review of the VA RedCap projects below and believe they are consistent with the grant.
1. IIR Team Blue Baseline
2. IIR Team Red Follow-up
3. IIR Team Blue Follow-up
4. MTL Menu (MTL Live)

- [ ] The projects need to be moved to production prior to being used, with assurances of that data integrity, loss prevention, and any needed server backup is supported by RedCap. Changes can always be made once the project is production, without resubmitting to VA RedCap.  
- [ ] The review process by RedCap can take a couple of weeks and during the process project cannot be accessed / used. 
- [ ] I recommend moving the projects to production to factor in the response time from VA so that we can be ready ahead of schedule.

**Comment by ritahitching** [comment]
@staceypark and @lijenn 
Shall I move the RedCap projects to production and close this issue? We can always make edits once it's in production.
thanks,

**Comment by staceypark** [comment]
@ritahitching @lijenn 
No need to move them into production yet. We have some additional things to add right before we work with teams. I'm putting this into wave1_teams.

**Comment by ritahitching** [comment]
@lijenn this is issue is blocked by the #1192 and the MVP process.
I recommend we keep this issue open.

**Comment by lijenn** [comment]
RedCap projects have been updated to be in production, shortlink is still needed #1353 and PACT measure awaiting updates.
