### ISSUE TITLE
wave1 Create  pre and post email template for MTL Red to be consistent with MTL Blue 

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#1293]
**Create pre and post email template for MTL Red **

- [ ] Create pre and post email template for MTL Red 
- [ ] Template to live [here](https://github.com/lzim/teampsd/tree/master/mtl_facilitate_workgroup/pre_post_emails)
- [ ] Need to create a folder for MTL Red  
- [ ] Ensure consistency with MTL Blue #1176 
- [ ] Use  MTL Red logos for each session [here](https://github.com/lzim/teampsd/tree/master/resources/red_sessions)
- [x] Cross ref #987

**Comment by ritahitching** [comment]
Track #1298 pull request

**Comment by ritahitching** [comment]
@lijenn this is issue is blocked by the #1192 and the MVP process.
If you read the thread you will find inks to the most current drafts of the email templates.
I recommend we keep this issue open.

**Comment by lijenn** [comment]
Pre/post emails have been created already, closing the issue.
