### ISSUE TITLE
August Task: COVID-19 grants fund - Submit modifications for R01 & IIR IRB and contracts

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1294]
Once one or both the additional grants for COVID-19 fund, we need to submit modifications for the R01 & IIR IRB's and any open contracts on the additional monies and scope

**Comment by lzim** [comment]
@staceypark @ritahitching and @lijenn 

For the R01, we can go ahead and 
- [ ] submit the NCPTSD 10-item Coronavirus Stress measure as a IRB modification for the Baseline and 6-month online provider survey
- [ ] make sure this is programmed in RedCap (Cross-ref: #1255 - 6 months, and #814...see *NOTE):

*NOTE: _There are MANY RedCap Issues on GitHub..._
But, I don't see **master document cards** where I would expect them in the **disseminate_scientists_va** column of **mtl.how/documents**
- _According to the SOP, shouldn't there be a card for each assessment, that closes when fully programmed, and opens where there is a modification like this one?_

I would expect these all need to be created for tracking these **research** (disseminate) documentation:
- [ ] R01 Baseline
- [ ] R01 6-month
- [ ] IIR Baseline 
- [ ] IIR 6-month
- [ ] R21 Post-evaluation

**Comment by ritahitching** [comment]
@lzim @staceypark @lijenn 
I believe there is no master card for RedCap.  
I had asked @lijenn about it and neither of us is aware of one.  
@staceypark will you please confirm that we don't already have a master card for RedCap? As soon as I get confirmation there isn't a prior card, I'll create the master card and cross reference with this issue.

**Comment by ritahitching** [comment]
Decisions from HQ meeting 4/15
- [ ] @lijenn to work on biosketches details located in TeamPSD folder
- [ ] @ritahitching to work on code RedCap using the NCPTSD 10-item Coronavirus Stress measure 

FYI @lzim  @staceypark

**Comment by lzim** [comment]
> @lzim @staceypark @lijenn
> I believe there is no master card for RedCap.
> I had asked @lijenn about it and neither of us is aware of one.
> @staceypark will you please confirm that we don't already have a master card for RedCap? As soon as I get confirmation there isn't a prior card, I'll create the master card and cross reference with this issue.

@ritahitching Please review my checklist above yours from yesterday's #hqhuddle. It clarifies the next steps required for making progress, which were all discussed during the huddle.

**Comment by lijenn** [comment]
From 8/3 8am WG Leads, identified work was done. Closing the card.
