### ISSUE TITLE
Team PSD CRM

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1296]
**1. Feature Description: What is the goal of this feature and why are we working on it?** 
------------

**Creation of a CRM that can be used by Team PSD to handle support messaging in order to provide timely assists to our users in the field** 
 
**2. Requirements, Design, and Test Cases: Outline of the necessary requirements, design, and test steps**  
<details>
<summary> Requirement Helper </summary>
 1. Requirement Definition (What & Why)
 </br></br>
2. Verification Method (How)

<strong>Documentation of requirements</strong> - Review of definition of the requirements.  

<strong>Analysis</strong> - Code, data, model reviewed. 

<strong>Test</strong> - Procedures must be well documented.  

<strong>Inspect</strong> - Purpose, methods and procedures must be well documented so result can be duplicated using the same inspection procedures. May include inspection of design or an algorthm (aka process map of process).

<strong>Demonstrate</strong> - A comprehensive demonstration and/or application of the functions and features of the system or its components.  

<strong>Infer</strong> - from “Why”/purpose of requirement definition.  
</br></br>
3. Reviewer (Who)

Within Workgroup Member  

Verify across workgroups  

Required or Optional?  
</br> </br>
4. Location in Tracker
</details>

-------------

- [ ] Requirement 1 Met
<details open=true>
<summary>Requirement 1</summary>

  1. Step 1 Requirement Definition (What & Why)   
  Example:  
  **Community Button links out of Sim UI to the GitHub Community of Practice.**  
  2. Verification Method (How)   
  Example:  
  - [X] Documentation of requirements - Reviewed definition of the requirements at **sim_UI_workgroup** on 4/07/2020.  
  3. Reviewer (Who & When)  
  Example:  
  - [x] Verified design with Lindsey & Stacey at **sim_UI_workgroup** on 04/07/2020.
  4. Location in Tracker  
  *Upon Approval Card can move to operations/research_to_do*

  ---
  1. Step 2 Design Definition (What & Why)  
   Example:  
  **Create Community Button that links out of Sim UI to the GitHub Community of Practice through a new "I have a question" ["Community   Button" > "I have a question" Button > GitHub "Community of Practice"].**
  2. Verification Method (How)  
   Example:  
  - [ ] Design document of the 3 buttons within the Button - Review this design at **sim_UI_workgroup** on 4/14/2020.
  3. Reviewer (Who & When)  
   Example:    
  - [ ] Verified design prototype with Lindsey & Stacey at **sim_UI_workgroup** on 04/14/2020.
  4. Location in Tracker  
  _After approval card can move to under_development once work has begun._

  ---
  1. Step 3 Build/Test Definition (What & Why)  
  Example:  
  **Implement the new buttons on the SIM UI** 
  2. Verification Method (How)  
  Example:  
  - [X] Analysis - Code tested by Anthony on 04/18/2020.  
  - [ ] Demonstration of the new design/functionality on the platform - Review this demo at **sim_UI_workgroup** on 4/21/2020.  
  3. Reviewer (Who & When)    
   Example:  
  - [X] Anthony ran test scripts outlined in Design Document on 04/18/2020.
  - [ ] Verified demo with Lindsey & Stacey at **sim_UI_workgroup** on 04/21/2020.
  4. Location in Tracker  
  _Once Review has begun Card should either move to functional_testing or measurement based on the test being done._
</details>

<button type=button onclick=print(Content) > Add a requirement button </button>

**3. Review**: 
----------------

**Comment by anthonycpichardo** [comment]
Replaced with 1299. Closing this card

**Comment by hnorthcraft** [comment]
#adjudicate_memo per above comment, efforts tracked on different card. Assigning dup label.
