### ISSUE TITLE
Update NCPTSD TeamPSD Phone Listing

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1327]
Purpose: Update the phone listing excel sheet to reflect new changes made on the team

- [x] Update the excel sheet to reflect new members and remove old members and the move upstairs
- [x] Double check with @lzim @ritahitching 
- [x] Email back to Eric once finalized 
- [x] Put it in shared drive

**Comment by ritahitching** [comment]
@lijenn I sent you my edits in the email you sent me with the spreadsheet.
thanks

**Comment by lzim** [comment]
@lijenn @ritahitching I didn't see this come back through to Eric is this done and can this be closed?
