### ISSUE TITLE
Do/Done Day 2, 3 & 4 - Drawing from Debbie's Draft Agenda

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#133]
Hi @dlkibbe and @branscombj !

I wanted to return to these great ideas from Debbie's draft agenda.
To reinforce the *MTL Live* 12-session format, we propose to start and end each *MTL Facilitate Pilot* day with 15 min Done/Do. The exercises below from our earlier draft agenda would be great ways to facilitate the "Done" piece in an open-ended way that would give us rich "pilot" information.

I'd like to propose that we spend nearly all of the 15 minutes on this, reflecting what they share, with just a couple minutes at the end introducing what we will do next. Ideally, linking our next activities to the needs they relay in the afternoon session. The afternoon Team PSD debrief will benefit from wrapping each day with *Empty Your Cup*. Whereas the morning *What's Sticky?* will help us to assess where the learners are with the prior day's content as we kick off our day.

**Day 1 (Tues) - Afternoon - Done/Do**
- *Empty Your Cup* - “In order to teach others I need more help understanding…”

**Day 2 (Wed) - Morning - Done/Do**
- *What’s “Sticky?* - " I remember best…"

**Day 2 (Wed) - Afternoon - Done/Do**
- *Empty Your Cup* - “In order to teach others I need more help understanding…”

**Day 3 (Thurs) - Morning - Done/Do**
- *What’s “Sticky?* - " I remember best…"

**Day 3 (Thurs) - Afternoon - Done/Do**
- *Empty Your Cup* - “In order to teach others I need more help understanding…”

**Day 4 (Fri) - Morning Done/Do**
- “I can teach others….” 
- “I need more information to facilitate this…”

If this sounds okay, I'll put it in the schedule.

Lindsey

@staceypark @TomRust @dlounsbu

**Comment by dlkibbe** [comment]
I agree with this proposal @lzim  -- these segments could provide great feedback/input and help us potential improve the next day's experience. I'm happy to facilitate these discussions if you'd like.

**Comment by branscombj** [comment]
I like this too. Suggest using "In order to" instead of "Before I" in the Empty Your Cup question. Correct the typo "teacher".
