### ISSUE TITLE
ICEBOX Develop Reporting Capabilities for CRM Phase I

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1330]
Requirement 6 of #1299

Design a reporting tool that will monitor the response status of incoming messages, sender/recipient, and elapsed time for responses.

This will be done using Excel

**Comment by lijenn** [comment]
This is an outdated and manual task work related to the CRM which is now being automated and implemented in #1299. Closing this card.

**Comment by hnorthcraft** [comment]
#adjudicate_memo per above comment, efforts tracked on different card. Assigning dup label.
