### ISSUE TITLE
4/16 Move .R and .SQL to github

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1332]
Copy the .R and .SQL research related files to mtl_code GitHub from TeamPSD  folder

Part of #1281

**Comment by anthonycpichardo** [comment]
@lzim For this task I will need to email these files to my PAVIR/personal email before uploading due to the upload restrictions (and would continue needing to do so every time we wanted to push new changes). Is that okay with you or should we consider using the enterprise account to avoid this?

**Comment by lzim** [comment]
@anthonycpichardo 

Good question! Just to check:
- Is there something new? 
- In the past, I never had an upload issue for files of this type. 
- It was just adding files (like screenshots of bugs) to **Comments** that VA decided to block. 

Generally though, yes, it will make sense to keep our a) R and SQL code,
b) code review procedures, and
c) _related discussions (like this one)_

In one of these:
1. OSF (on our R21, R01, IIR registrations),
2. **mtl_code** (part of our secure TeamPSD pro account), or
3. We can learn more about VA enterprise integration of GitHub for both Research and Operations.

FYI: @staceypark @anazariz

**Comment by anthonycpichardo** [comment]
Closing this issue to continue this discussion on MTL_Code. I've removed the estimate to not double count points. 
I've tagged you all on the new issue.
@lzim @staceypark  @anazariz
