### ISSUE TITLE
Jane test

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#1334]
Regretfully, I do not have enough background to use this tool. ☹️ Is it designed for HQ? If so, it may be great. If co-facs will be using it, we will need quite a bit of training. I would not expect others beyond co-facs to know where to start, unless maybe they're coders. I have put some questions/reactions to specific parts in italics below. But some of them seem to be hidden in Preview so may only show up when the issue is opened in edit??

The biggest challenge for me is understanding the meta-ness of the content in the form: what is instruction for how to use it; what is descriptive of the content I should input; what is instruction for use post-creation - that kind of thing. Also the fact that the formatting code is only code when you're actually working in the form (in Write mode) makes it more confusing and distracting than helpful. It should not be necessary to switch back and forth between Preview and Write to get that something is a header or something is in italics. 

Depending on how broad the audience is for using this, I'd recommend using no formatting at all; just putting headers for the content that someone should type (Rationale for the feature); or put those in question form (What is the rationale for this feature?) or in instruction format (Enter below the rationale for the feature.) But stick with whichever form is chosen throughout._

Notes:

_I am not sure what I'm supposed to do with these 3 notes?_

1. **Markdown** language to be used, include:
- [ ] **BOLD**
- [ ] _Italic_
- [ ] Use **Numbering**  or **Bullets** 

2.  **HTML** 
- [ ] Text contained within the <> tags remains unchanged - this is a fixed section header.
- [ ] Description is to be inserted within after the <> arrows for each section of the Feature template
- [ ] To add another requirement, copy and paste the helper (Including the \<details>\</details> tags) and paste below the relevant section.

3. **Kanban**  
- [ ] For a **Feature** to progress across the Kanban columns the entire list of requirements within the **Master Card** needs to be checked first
- [ ] If a **Feature** requirement has tasks associated with it cross reference the issue # at the appropriate step.

**Guidance for 6 Sidebar Clicks - Delete this text after completing the 6 clicks** 

_I do not know what this means or how to use it._

i. **Pipeline** - Open Features (Will stay here until card is closed)   
ii. **Label**- assign workgroup (lead) responsible for tracking the task  
iii. **Projects** - Feature Tracker (work_breakdown)  
iv. **Milestones** - select monthly sprint milestone within the workgroup   
v. **Epics** - assign to team-wide epic and TeamPSD master plan project  
vi. **Releases** - assign to key team release grouped with other relevant issues  

**1. Feature Description** 
------------
- [ ] Insert brief description answering the following question:  **What is the goal of this feature and why are we working on it?** 

_If this is to be like a template, just put the content needed - not instructions to insert it._

Example:

**Want to create a Community of Practice for the users of the SIM UI to access in order to have a forum for discussion and to ask/answer questions** 
 
<details>
<summary> Requirement Helper </summary>

_What does this mean? Am I supposed to click between the <> and type in my details and summary? What does Requirement Helper mean?_
 
 1. Requirement Definition (What & Why)
 </br>
 
_Keep in mind that when one is working in the issue, we see only the md code. If we could work in the Preview mode, the formatting would be helpful; but in Write mode it does not help the user visualize aspects of the "form". So for example I don't know what the <_/_ br_> means. And bizarrely, I can't even see this note I'm typing in the Preview mode: where did it go? _ 

 - [ ] -Insert Requirement-
 
 </br>
2. Verification Method (How)

#### Applicable for Requirements Phase:

- [ ] **Documentation of requirements** - Review of definition of the requirements.  

#### Applicable for Design Phase

- [ ] **Analysis** - Code, data, model reviewed. 
- [ ] **Infer** - from “Why”/purpose of requirement definition.   
- [ ] **Inspect** - Purpose, methods and procedures must be well documented so result can be duplicated using the same inspection procedures. May include inspection of design or an algorthm (aka process map of process).  

#### Applicable for Build/Test Phase

- [ ] **Demonstrate** - A comprehensive demonstration and/or application of the functions and features of the system or its components. 
- [ ] **Test** - Procedures must be well documented. 
- [ ] **Analysis** - Code, data, model reviewed. 

</br></br>
3. Reviewer (Who)

Within Workgroup Member  

Verify across workgroups  

Required or Optional?  
</details>

**2. Requirements, Design, and Test Cases: Outline of the necessary requirements, design, and test steps**  
-------------

- [ ] Requirement 1 Met
<details >
<summary>Requirement 1 -Rename to "What" of this requirement</summary>
<div>
 
  1. **Requirement Definition (What & Why)** - Must be complete before moving to Operations/Research_To_do     
  Example:  
  - [X] Community Button links out of Sim UI to the GitHub Community of Practice. 
  2. **Verification Method (How)**   
  Example:  
  - [X] Documentation of requirements - Reviewed definition of the requirements at **sim_UI_workgroup** on 4/07/2020.  
  3. **Reviewer (Who & When)**  
  Example:  
  - [x] Verified design with Lindsey & Stacey at **sim_UI_workgroup** on 04/07/2020.

  ---
  1. **Design Definition (What & Why)**  - Must be complete before card moves to under_development
   Example:  
  - [X] Create Community Button that links out of Sim UI to the GitHub Community of Practice through a new "I have a question" ["Community   Button" > "I have a question" Button > GitHub "Community of Practice"].
  2. **Verification Method** (How)  
   Example:  
  - [ ] Design document of the 3 buttons within the Button - Review this design at **sim_UI_workgroup** on 4/14/2020.
  3. **Reviewer** (Who & When)  
   Example:    
  - [ ] Verified design prototype with Lindsey & Stacey at **sim_UI_workgroup** on 04/14/2020.
  

  ---
  1. **Build/Test** (What & Why)  
  Example:  
  - [X] Implement the new buttons on the SIM UI
  2. **Verification Method** (How)  - Once build is complete card can move to functional_testing or measurement
  Example:  
  - [X] Analysis - Code tested by Anthony on 04/18/2020.  
  - [ ] Demonstration of the new design/functionality on the platform - Review this demo at **sim_UI_workgroup** on 4/21/2020.  
  3. **Reviewer** (Who & When)    
   Example:  
  - [X] Anthony ran test scripts outlined in Design Document on 04/18/2020.
  - [ ] Verified demo with Lindsey & Stacey at **sim_UI_workgroup** on 04/21/2020.
 </div>
</details>

*Note: To add another requirement copy and paste the helper above (Including the \<details>\</details> tags) and paste below.*

**3. Review**: 
----------------

**Comment by anthonycpichardo** [comment]
This is really great feedback @branscombj, thank you for taking the time to try and work through it. 

I will make the instructions much more explicit as well as consistent and clear out any unnecessary formatting pieces to try and make this look as approachable as can be.

I too wish that GitHub would render markdown on the Write screen instead of having to switch to Preview.
