### ISSUE TITLE
4/17 Team PSD tt_report 064

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#1335]
**Team PSD tt_repor 064** 

- [x] tt_report 064 using new template
- [x] weekly announcement
- [x] subject line 
- [x] Lucidmeeting updates
- [x] Contact Workgroup Leads for updates
- [x] Add to agenda for review at Thursday's 4/16 HQ Meeting
- [x] Test formatting of email
- [x] To be in Team PSD members' inbox Monday April 20 by 8:00am to be used at Workgroup Leads meeting for

**Comment by ritahitching** [comment]
@anthonycpichardo @jamesmrollins @staceypark @lijenn @jessfroe 

Hi all,
Do you have any updates for the tt_report week commencing April 20 from your respective workgroups or anticipated calendar changes? 
thanks,

**Comment by staceypark** [comment]
@ritahitching  none from me

**Comment by ritahitching** [comment]
Decisions from HQ 4/16 meeting
- **Keep** Lucidcalendar as it & new screen shot needed
- **Add**
- **Subj:** [tt064] Finalize HSRD & NIDA Grants for Submission
- **Announcement:**  Team PSD "All Hands" Meeting is scheduled for next week the 5th Tuesday 4/28.
- **Change Epic:** April epic ends Friday 4/24.

**Comment by lzim** [comment]
@ritahitching you are missing the second announcement from our **hq_workgroup** thanks!

Subj: [tt064] Finalize HSRD & NIDA COVID-19 Grants for Submission

Announcement: 

- Team PSD "All Hands" Meeting is scheduled for next week the 5th Tuesday 4/28.

- #559 The r01_protocol_impsci is being reviewed by co-Is on OSF https://osf.io/8pzxu/ 

Epic: April epic ends Friday 4/24.

**Comment by ritahitching** [comment]
Closing this issue tt_report 064 ready to be sent.
