### ISSUE TITLE
wk1 task: Register OSF Project - R21 Grant

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1337]
Goal: We need to fill out the OSF Project template as a team for the R21, R01 and IIR. 
We will be done with a) compliance on IIR JIT, and b) COVID-19 grants soon and it would be great to get this done!

Largely they will be consistent with our ClinicalTrials.gov and IRB protocols.

Follow the OSF Project Registration guide here: https://github.com/lzim/teampsd/blob/master/resources/training_guides/mtl_how_osf/osf_project_registration.md

FYI: @lzim @staceypark @ritahitching @anazariz @anthonycpichardo

**Comment by lijenn** [comment]
Hi @lzim I think you need to give me admin privileges in order to see/edit any project registrations. Will need to have the same permissions for R01 (#1336) and IIR (#1338).

**Comment by staceypark** [comment]
@lijenn I've made you admin on R01 (#1336) and IIR (#1338).
But yes, for the R21, I don't have admin either so @lzim will need to do that.

**Comment by lzim** [comment]
@staceypark & @lijenn I made you both admin in the R21 project registration. Thanks!
