### ISSUE TITLE
ASAP: NIDA Administrative Supplement (PAR-18-591)

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#1339]
**NIDA Supplement**
https://www.drugabuse.gov/funding/contracts-small-businesses/administrative-supplements-to-grants-cooperative-agreements

- [ ] **Cover Sheet** - Lindsey & Co-Is
---
**Research Strategy (6 pages)** - Must include summary or abstract of funded parent award. Also include these docs if they are being changed by the supplement: 
1) Aims, 2) Resource Sharing Plan, 3) Consortium/Contracts
- [x] **Aims** - Lindsey & Co-Is
- [x] Aims Reviewed by NIDA
- [x] Aims Reviewed by Craig
- [x] Aims Reviewed by Shannon
- [ ] Aims Reviewed by Rachel
---
- [x] **Plan** - Lindsey & Co-Is - Parent Award Abstract goes in the Plan
- [x] Reviewed by Craig 4/15/2020
- [ ]  Reviewed by Shannon
- [ ]  Reviewed by Rachel
- [ ] Reviewed by Nasim 
- [ ] Reviewed by Tom
- [x] References checked
---
- [ ] **Budget** - Lindsey & PAVIR
- [X] CUNY Estimate Received 4/14/2020
- [x] Lindsey review w/Marisela
- [x] Lindsey review w/Margaret
- [x] PAVIR approves
---
- [ ] **Budget Justification** - Lindsey & PAVIR
- [X] CUNY Subaward Received 4/14/2020
- [x] Full Budget Justification Completed
---
- [ ] **Science Docs** - HQ & Margaret
- [x] Facilities & Other Resources - Margaret
- [x] Project Summary - Lindsey
- [ ] Project Narrative - Lindsey
- [x] Equipment - Margaret
---
- [ ] **Human Subjects** Will the use of an additional existing dataset or resource be proposed in the supplement application? If so, then a new Inclusion Enrollment Report will need to be created as well as an Inclusion of Women, Minorities, and Children document.
- [x] patients (facility)
- [ ] providers (facility MH)
---
- [ ] **Biosketches** - HQ & Margaret
- [x] **Existing Biosketches** (confirm the NIDA R01 list) - No need to do this piece @lijenn. Confirmed with Margaret that we only need biosketches for new key personnel in the supplement.
- [x] **Added Biosketches**: Matt B, David N, Nasim S.)
---
- [ ] **LOS**: 
- [x] Nasim S. 
- [ ] Matt B.

**Comment by staceypark** [comment]
@lzim  I've updated the above against Margaret's checklist.

Does the Human Subjects question apply to us? Maybe it does because of the COVID-related data? Does that count as "existing" since its evolving?

> **Human Subjects**: Will the use of an additional existing dataset or resource be proposed in the supplement application? If so, then a new Inclusion Enrollment Report will need to be created as well as an Inclusion of Women, Minorities, and Children document.

**Comment by lzim** [comment]
@staceypark @anazariz @anthonycpichardo - Discussed at #hqhuddle 4/17/2020

In our COVID-19 adaptations we propose that the new _MTL_ Covid-19 module will be at the facilite or st3n Level.
- So, to update the Human Subjections **patients** and **provider** enrollment tables for Exploratory Aim and priority D. Simulate, Measure, Analyze

1.  **R01 24 facility st3ns** outpatient **patient** denominator and **provider denominator** (Excel file that calculates the racial, ethnic and gender)
2.

**Comment by lzim** [comment]
propo

**Comment by anthonycpichardo** [comment]
> @staceypark @anazariz @anthonycpichardo - Discussed at #hqhuddle 4/17/2020
> 
> In our COVID-19 adaptations we propose that the new _MTL_ Covid-19 module will be at the facility or st3n Level.
> 
> * So, to update the Human Subjections **patients** and **provider** **enrollment tables** for **_Exploratory Aim a and b_** to integrate "Patient Need" and "Provider Need"
> 
> 1. **R01 24 facility st3ns** outpatient **patient** denominator and **provider denominator** (Excel file that calculates the racial, ethnic and gender proportion).
> 2. **IIR 24 facility st3ns** outpatient **patient** denominator and **provider denominator** (Excel file that calculates the racial, ethnic and gender proportion).
> 
> **Step 1** get the list of facility sta3ns
> **Step 2** is find the outpatient patient (use splashpage) and outpatient provider ("FTE_total_current" column H) denominators
> **Step 3** is estimate the proportions using our Human Subjects Excel tool (keep this in Team PSD > Grants > enrollment_calculator)

@lzim For the "outpatient patient" are we looking for the average # of encounters over the length of the data at a given site?

@staceypark tagging for visibility.

**Comment by lzim** [comment]
HI @anthonycpichardo and @staceypark 

I apologize, I did not see this question come through, but this is quite time-sensitive as we need to finalize this submission ASAP this week.

Anthony, I pinged you on Teams in case a quick chat would help us resolve this faster. I'm not 100% that I understanding your question, but I believe the answer is, yes.

**Comment by lzim** [comment]
From our Team chat on 4/22/20 - @anthonycpichardo and @staceypark 

- The actual chart review will reflect total patients served by the facility between March and Sept 2020 (6 months of acute COVID-19 phase); this is the value needed for enrollment table.
- This would initialize a new basecase in the COVID-19 module that accounts for crisis standards of care for our 48 unique st3n (across both trials).

**Comment by lzim** [comment]
#hqhuddle 

Final steps to get these back to Margaret for upload this week.
GOAL: Elaine submits on Monday.

@staceypark 
- [ ] Boden LOS
- [ ] Facilities
- [ ] Budget Justification
- [ ] Enrollment

@lzim 
- [ ] aims
- [ ] plan
- [ ] references

**Comment by staceypark** [comment]
@lzim 
I've done the Human Subjects table for the patients. But the enrollment calculator for the providers one does not add up correctly. Wasn't able to find one that added up correctly within our folders. 

Is there a copy on your computer you were using and/or when can I go look for this? I did some quick Google searching for VA HS enrollment calculator but didnt find one

**Comment by lzim** [comment]
> @lzim
> I've done the Human Subjects table for the patients. But the enrollment calculator for the providers one does not add up correctly. Wasn't able to find one that added up correctly within our folders.
> 
> Is there a copy on your computer you were using and/or when can I go look for this? I did some quick Google searching for VA HS enrollment calculator but didnt find one

@staceypark I made a comment about this on Teams. Let’s touch base tomorrow AM if you still need help.

**Comment by lzim** [comment]
This was submitted on 7/1 to NIDA!
