### ISSUE TITLE
4/15 Microsoft Teams vs. Slack for TeamPSD 

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1340]
@lzim 

**Microsoft Teams**
Pros:
- Free version we are using seems to serve our team's needs fine
- Ability to record calls (once VA integrates) 
- Seamlessly use VA MS Teams once the merge happens
- Integrates with all the other Microsoft apps we use as part of VA

Cons:
- Supports less app integrations than Stanford

**Stanford Enterprise Slack**
Pros:
- 800+ app integrations based on pricing tiers (Teams only has 180+ apps), but both support GitHub, and neither support Lucid Meetings
- Higher tier account than Teams so has higher storage capacity (but we don't put files here)

Cons:
- Needs SUNetID; most of the team needs to be sponsored by NCPTSD Admin for this
- Cannot record call/meetings no matter what pricing tier. Need to use an integration for it.

I would recommend we just stick with Teams, it doesn't seem worth switching. We can use Zapier with both to integrate 1) with more than what is supported on the platforms or 2) integrate with different commands

**Comment by lzim** [comment]
@staceypark 

Thanks for looking in to this and summarizing your findings.
I looked at it a bit before pinging you, and basically came to the same conclusion.

_I really appreciate how you documented this work. 🙌 Can we show the team as an example?_
