### ISSUE TITLE
wk3 jun_epic Document - IIR DART Submission

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1349]
IIR_dart_submission

## 1. Link to the document and add relevant team members to the card.
- [ ] Add the link the current draft of the documentation for the issue:

## 2. Link to issues that must be edited in the document in the **issue_tracker** and **feature_tracker.** _(use the # for the link to the issue)_
- [ ] Issue lzim/mtl_code#7
- [ ] Issue #
- [ ] Issue # 

# Dart Request - 5 Page Submission Guide

### All of the information below can be found with a combination of 4 documents/platforms:
*- complete grant application PDF in TeamPSD > Grants*
*- Clinical Trials registration at clinialtrials.gov*
*- IRB protocol application & approval letters in TeamPSD > IRB*
*- RDIS (Research & Development Information System) at rdispaloalto.net*

## Page 1 Information
- [x] Short Name for Study : 
  ***- Grant application (use own discretion to shorten)***
- [ ] Does our project have an IRB or other project number? 
***Each of our projects has 3 numbers:***
  ***- federal Identifier # from the funding agency: under Grants in TeamPSD***
  ***- clinicaltrials.gov identifier #: search for project on the clinical trials website***
  ***- IRB protocol #: under protocol application in IRB in TeamPSD***
- [ ] Approval Expiration Date?
  ***- IRB Approval letter***
- [ ] Study Start Date : 
  ***- Clinicaltrials.gov registration; note: don't use the dates in the Grants application as they may have updated***
- [ ] Anticipated Study Close Date : 
  ***- Clinicaltrials.gov registration; don't use the dates in the Grants application as they may have updated***
- [ ] Has our study been determined to be an exempt human subjects study? 
  ***- IRB protocol application***
- [ ] If no, informed consent required orally or in writing? HIPPA authorization in writing? IRB Approval for waiver of informed consent?
  ***- IRB protocol application***
- [ ] Does the study have IRB or Privacy Board approval for a waiver of HIPPA authorization? If not, is the waiver only for recruiting/eligibility or for the entire study?
  ***- IRB protocol application***

## Page 2 Participant List
- [ ] List of team members and their requirement needs (Notifications, Data Access or CAPRI/JLV Access)

## Page 3 Data Sources
- [ ] Determine Data Storage Location (VINCI or On Premise Server [Need Location Details])
***Keep consistent to what was specified on RDIS. Tap an HQ member for RDIS info if needed.***
- [ ] Data Access Systems: Would we like to use the SAS Grid in VINCI?
- [ ] Are we sending any data external to VHA? Need location details if so. Company/Agency Name and address and we will need to fill out a DUA 
***Keep consistent to what was specified on RDIS. Tap an HQ member for RDIS info if needed.***
- [ ] What identification level do we need? Real SSN, Scrambled SSN, or Identifiable data but no real/scrambled SSN
***Keep consistent to what was specified on RDIS. Tap an HQ member for RDIS info if needed.***
- [ ] Required Data Sources : Do we need anything other than CDW Production?
- [ ] NDS Approval for CDW access

## Page 4 Documents
- [ ] Required Documents to be uploaded - vary based on our selections made above.

## Page 5 Submission
- [ ] Submit request - missing documents or items will be displayed here.

### Research Request Memo
-  Blank form found [here](http://vaww.vhadataportal.med.va.gov/DataAccess/DARTRequestProcess.aspx#DocumentsAndForms)

### Research Study Institutional Review Board (IRB) Approval Letter
- Located in TeamPSD > IRB, but originally downloaded from Stanford IRB website eprotocol.stanford.edu under Actions >  Download Approval Letter
- From CIRB, local VAMC, or University Affiliate
- IRB letters are needed from each site
- Key Items needed:
  - PI Name
  - Study Name 
  - Approval Date
  - Expiration Date
  - Signed by the Chair of the IRB

### Research and Development RD Committee Approval Letter
- Located in TeamPSD > rdis, but originally downloaded from RDIS website at rdispaloalto.net under Initial Approval Letter

### IRB Approval of Waiver of HIPAA-Compliant Authorization
- Should include
  - VA Facility Name
  - Title of Study
  - PI Name
  - Brief description of PHI used for IRB
  - Must have Chair of IRB Signature

### Research Protocol
- Should include:
  - Introductory paragraph
  - Statement of the Problem
  - Purpose
  - Significance of the Study
  - Research Questions and/or Hypotheses and/or Null Hypotheses
  - Background
  - Methodology
  - Procedure and time frame
  - Analysis plan 
  - Scope and limitations
  - Use the most up to date Protocol

### CDW-Domain Checklist
-  Blank form found [here](http://vaww.vhadataportal.med.va.gov/DataAccess/DARTRequestProcess.aspx#DocumentsAndForms)

**Comment by lzim** [comment]
@anthonycpichardo @staceypark @dkngenda 
See email dated 1/15/21 from me re: this open compliance issue on VA grant.
Thanks!

**Comment by lzim** [comment]
Discussed the SSN form that needs to route through IRB and ORD before being re-uploaded to DART.

@anthonycpichardo  I see above that this is linked to lzim/research/9 
Anything else we need to do on this?

@staceypark and Anthony, we will track this here and via emails with these partners:
- [ ] IRB chair
- [ ] ACOS-R
- [ ] DART Upload

**Comment by lzim** [comment]
@anthonycpichardo 
@staceypark 

Based on the emails with Ashima what are the next steps?
Please provide an 0 pt estimate (rather than leave unestimated), if it is a **document_card** with work estimated elsewhere.
Thanks!

**Comment by lzim** [comment]
@staceypark  

I believe this can be completed per the emails from Kaur and Ashima.
Please report back to the team and have @dkngenda check to ensure that he can see all 3 ORD projects. 

Thanks!
