### ISSUE TITLE
July - Task: Renew NounPro via ReqLogic

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1352]
Noun Project (NounPro) is used to generate new icons when needed.
Lindsey's yearly annual subscription of $39.99 renews next week (Next payment is this Friday April 24th)

Task: Renew this on via ReqLogic - Edited by "lz" 4/22/20 to remove account information.
Also show Jen how this is done so she could pick up ReqLogic tasks if needed

**Comment by ritahitching** [comment]
FYI @lijenn 
- [ ] ReqLogic purchase order made for Noun Project $39.99 made.
- [ ] Requisition #84950.
- [ ] Request to expedite purchase order made as current subsscription ends 4/24/2020.
- [ ] Email sent to PAVIR informing them of time sensitive nature of requisition.
- [ ] Will provide update once a response is received.

**Comment by ritahitching** [comment]
FYI @lijenn 
- [ ] Response from Luanne  below
- [ ] Ask for decision at HQ Huddle

"_They are a new vendor for us and we will require paperwork to get them approved as our vendor.  It would be quicker if you can please pay for the order and get a reimbursement.  If you are in a hurry, you should do this. Each vendor differs.   Some are quick and some take a week, 2 weeks, longer…Shelter in place may make it longer…."

**Comment by ritahitching** [comment]
@ritahitching 
FYI @lijenn 
- [ ] Decision from HQ meeting 4/23 to let let renewal occur with current credit card and consider ReqLogic at a later time.
- [ ] Email Luanne to let her know.

**Comment by ritahitching** [comment]
@lijenn the decision to move the  NounProject subscription via ReqLogic was delayed until 2021 due to Covid.  
It makes sense to keep a note that the purchase does need to be made through ReqLogic but this issue can likely be closed.

**Comment by lijenn** [comment]
Closing as next 2021 payment cycle will be reimbursed via check request or get paperwork to Luanne earlier. Jenn will add a reminder in Outlook calendar.
