### ISSUE TITLE
4/27 Task: Comb through Blue Session 5-11 guides for use of the words "Patients"

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1359]
Comb through and edit the MTL Blue Sessions 5-11 Learner & Facilitator guides for use of the word "Patients". This word should always be **plural, with no apostrophes (Patients)** instead of singular/with an apostrophe. 

Since our models are of aggregate numbers, our stock & flow variables should all be plural.

Note: Cross-ref #1044 (Debbie identified the inconsistent use of "Patient's" versus "Patients'" within the SIM UI, Psy Model).

Note:
- Red guides do not need to be combed through since they will not use the sim.
- None of the cheatsheets need to be combed through because specific variables are not mentioned in these.
- James is combing through the Sim to correct this issue as well.

@lijenn or @ritahitching Can one of you pick up this task based on bandwidth and add a date in the header for when you can complete it? This shouldn't take very long as we don't mention specific variables very often in the guides.

**Comment by lijenn** [comment]
@staceypark @ritahitching  I can do this as I have edits that need to be made in the guides already in #1275, thanks!
