### ISSUE TITLE
4/24 Task: tt_report 065 week commencing April 27

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#1361]
**Team PSD tt_repor 065** 

- [x] tt_report 065 using new template
- [x] weekly announcement
- [x] subject line 
- [x] Lucidmeeting updates
- [x] Contact Workgroup Leads for updates
- [x]  Add to agenda for review at Thursday's 4/23 HQ Meeting
- [x] Test formatting of email
- [x] To be in Team PSD members' inbox Monday April 27 by 8:00am to be used at Workgroup Leads meeting for

**Comment by ritahitching** [comment]
@ritahitching Decision from HQ 4/23
- [ ] Announcement: Reminder of meetings Tuesday April 28
- All Hands 
- Vapor 
- [ ] No Lucidmeeting calendar changes expected

**Comment by lzim** [comment]
@ritahitching @lijenn and @staceypark

- Generally, **hq_workgroup** will be able to provide more effective feedback on this if you type out the **tt_template** (Cross-ref #1228) information for review _before or during_ the **#hqhuddle** 
- It would be preferred if you could make recommendations in advance on GitHub🏆 
- For example, with a little more time to consider it, I realized that posting _MTL Video_ on TMS is a huge accomplishment that we should celebrate! 🎊 

@lijenn and @staceypark

1. **subject line:** “_MTL_ Video is on TMS; All Hands Meeting Tues 4/28 at 9AM Pacific”
2. **announcements:**
- “_MTL Video_ is available for free psychiatry, psychology, social work and nursing licensure credits on TMS - thanks to all the video “stars” and reviewers.”
- “Team PSD All Hands Meeting Tues 4/28 at 9AM Pacific - Celebrate **april_epic**accomplishments.”
- “VAPOR Meeting Tuesday 4/28 at 3PM Pacific” - Review the VAPOR videos at mtl.how/videos”
3. **priority epic:** “**may_epic** begins Thurs 5/1”

Thanks!

**Comment by ritahitching** [comment]
@ritahitching @lzim 

- [ ] I updated the tt_065 to reflect
- subject line: **MTL Video is on TMS; All Hands Meeting Tues 4/28 at 9AM Pacific**
- announcements:  1. **MTL Video is available for free psychiatry, psychology, social work and nursing licensure credits on TMS - thanks to all the video “stars” and reviewers.** 2. **Team PSD All Hands Meeting Tues 4/28 at 9AM Pacific - Celebrate april_epicaccomplishments.** and 3. **VAPOR Meeting Tuesday 4/28 at 3PM Pacific” - Review the VAPOR videos at mtl.how/videos**.
- priority epic: **may_epic begins Thurs 5/1**
- [ ] In future I will make suggestions in GitHub prior to the HQ meeting on Thursdays regarding:   
- subject line:
- announcements:  
- [ ] I will continue to have the tt_report ready for review at the HQ meeting on Thursdays
- [ ] I am closing this issue as the report is ready to send and a test email has been sent and confirmed by @lijenn 


FYI @staceypark
