### ISSUE TITLE
August - TASK Review Splashpage User Guide

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1363]
Review the user guide hosted on mtl.how/data for clarity and helpfulness.

The user guide should explain:
- [ ] Splash Page Controls
- [ ] How to Find Their Teams
- [ ] How to Access the community
- [ ] Overall navigation of the sharepoint site.

cross-ref #1124

**Comment by lzim** [comment]
Great job creating this card @anthonycpichardo 👏

**Comment by lzim** [comment]
Re-assigning to @ritahitching. Thanks!

**Comment by ritahitching** [comment]
@lzim please confirm I can move this issue to the May milestone &  Epic?
thanks

**Comment by lzim** [comment]
> @lzim please confirm I can move this issue to the May milestone & Epic?
> thanks

@ritahitching Right, consistent with my “order of operations” instruction above, which we reviewed in the **hq_workgroup** meeting, #1364 is first priority. Then, once finalized, all the dependent issue cards can proceed according to the standardization rules.

**Comment by ritahitching** [comment]
@lijenn @anthonycpichardo 
I have not reviewed the Splashpage User Guide; it was blocked by #1192 but its @anthonycpichardo issue and not for me to decide if it should be closed.

**Comment by anthonycpichardo** [comment]
@anazariz This document just needs to be reviewed at mtl.how/data

**Comment by staceypark** [comment]
@anthonycpichardo Rather than myself or Jenn, @branscombj @dlkibbe @dlounsbu would be better users to review this. Perhaps during the top of one of the Wed co-I meetings?
