### ISSUE TITLE
4/27 Task: Review MTL Video Supplementary Document Info.

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1365]
Cross Ref #1275 
@lzim @staceypark 

Task: I have attached a word doc containing all the information I plan to put in these supplementary docs that will go by session. Please review to see if the content is clear or if there is anything you'd change or remove.

I have also included the differences mentioned in the 2.0 guides and have highlighted parts from that to indicate that they are also mentioned/discussed in the video and have added that update in the supplementary docs (particularly for Sessions 2, 3, 5 since it deals with the Data and Sim).

I have attached a word doc version with Debbie's edits as it can help reduce the amount of workload for review. 

[mtl_video_supplementary_info.dk.docx](https://github.com/lzim/teampsd/files/4525654/mtl_video_supplementary_info.dk.docx)

**Comment by lzim** [comment]
Thanks @lijenn 

This is all looking really good!

I’m actually wondering if before the session by session part, we should talk about the major features in _MTL 2.0_ that are cross-cuttin
- [ ] tutor
- [ ] COP
- [ ] News
- [ ] More Info
- [ ] avatar

That sort of thing. It’s really helpful to know that those are there.
And, it makes this document more exciting.
What do you think, Jenn?

I’m going to walk through this with Tom at tomorow’s talk with the WPI System Dynamics club, if you’d like to sit in 😸 - it’s at 11AM Pacific.

FYI: @staceypark
