### ISSUE TITLE
6/29 TASK Create SQL Style Guide

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1367]
Produce a markdown document detailing the SQL style guide that all Team PSD members will follow.

**Comment by lzim** [comment]
@anthonycpichardo  @anazariz 

As we have clarified through the **july_epic:** 
We will use OMHSP and VA SQL Style Guides to integrate with existing standards for SQL style.

**Comment by anthonycpichardo** [comment]
This no longer needs to be created as we are using the OMHSP Style guide.

closing
