### ISSUE TITLE
4/27 Task: Team PSD Schedule - PAVIR timecards

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1373]
- [ ] Add the PAVIR timecard due dates for Team PSD PAVIR employees (only) Outlook Calendar
   - Employees complete the time card first
   - Lindsey then approves - get an alert for 24 hrs before it's due at both VA and Gmail emails

**Comment by ritahitching** [comment]
@lijenn confirming the task: Using the timecard calendar that Payroll has set for 2020 
- [ ] PAVIR calendar located in TeamPSD drive.
- [ ] Create calendar reminders for TeamPSD PAVIR  employees to submit their time cards 2 days prior due date.
- [ ]  Calendar reminder for Lindsey to approve the timecards based on PAVIR payroll.

**Comment by lijenn** [comment]
@ritahitching I think that sounds right. Lindsey also wants her reminders at least 24 hours prior in advance as well. 

I've also forwarded you the email that has the task and PAVIR calendar as well.

**Comment by ritahitching** [comment]
@lijenn  I've completed this task, and will close the issue.
thanks,

**Comment by lzim** [comment]
Hurray!!! Thanks @ritahitching  👏
