### ISSUE TITLE
5/20 Task: r21_vapor_ajcp - Cite Keys

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1375]
Use cite keys from Zotero to the .md manuscript file​

Cross ref: #697

**Comment by lzim** [comment]
Thanks @lijenn 

I will send this to you ASAP!
I'm still working on it 🌻

**Comment by lijenn** [comment]
@lzim No problem! I believe I don't have access to the OSF for this paper either and I have requested access to it as well, thank you!

**Comment by lijenn** [comment]
from hq huddle 5/1:
- @lzim Will upload word doc. in OSF
- Jenn will check in/out the doc to add in cite keys via Zotero extension

**Comment by lijenn** [comment]
Closing as cite keys were added. If there ends up being additional citations, I will re-open. Thank you!
