### ISSUE TITLE
wk3: R01 Literature & Publishings Review

### ISSUE THREAD

**Issue by dlkibbe** [lzim/teampsd#1376]
R01 Manuscript - Literature and Publishing Review
Issue #559

1. Review for consistency with exemplar cluster randomized trial (CRT) (Look for the three PDF articles under Files)
2. Review Implementation Science guidelines on which sections need to be include and provide recommendations on what can be cut from our protocol based on this

**Comment by dlkibbe** [comment]
@staceypark what is the product that will help the authors best edit the journal manuscript? Do you want a word file with 2 sections: 1) recommendations to meet the journal guidance; 2) recommendations based on a review of the published journal articles?

**Comment by lzim** [comment]
> @staceypark what is the product that will help the authors best edit the journal manuscript? Do you want a word file with 2 sections: 1) recommendations to meet the journal guidance; 2) recommendations based on a review of the published journal articles?

Thanks @dlkibbe 

- The two sections sound very helpful.
- I'm not sure what will be most digestible for co-Is (e.g., Word file, etc), but I do note we have to do this again, immediately after this one, for the VA IIR grant. 🤣

**Comment by lijenn** [comment]
Hi @dlkibbe! Wanted to check-in with you to see how the paper is going since we last met up on Monday.
Should @lzim or @staceypark expect anything to review next week since next Mon. #MM is a holiday and you will be out through Tues.?

Otherwise, enjoy the weekend and have a safe drive 🚗!

**Comment by dlkibbe** [comment]
@lzim @dlounsbu @staceypark @branscombj 
Version 4 of the R01 manuscript has been uploaded to OSF. Two titles are proposed in a comment on page 1. There are a few questions/sections where I noted additional editing could be done to the paper. Body of the paper is currently 8,736 words. 
@dlounsbu The Abstract sections -- Methods/Design and Discussion -- still need to drafted if you can help with this task. You're a better writer than I am!! Thanks and apologies to all for the delayed review and editing of this document.

**Comment by dlounsbu** [comment]
Hi @dlkibbe 👍 

Thanks for this update. I will look for your updated versions on OSF and I will review/edit as you requested. You are the best!

**Comment by lzim** [comment]
@dlounsbu 

@staceypark and I are doing working meetings this afternoon to submit as many manuscripts as possible by the end of the week. I'd like to submit this one this week.

**Comment by dlkibbe** [comment]
@staceypark are we doing manuscript (MS) monday today or are you and @lzim focusing that time on MS finalization?
@branscombj @dlounsbu

**Comment by lzim** [comment]
@dlkibbe 

We are only doing a working meeting this afternoon. So, I would head to the VA!

FYI: @staceypark and @branscombj

**Comment by dlkibbe** [comment]
Thanks @lzim

**Comment by lzim** [comment]
Good luck @dlkibbe 🤞

**Comment by staceypark** [comment]
@lzim @dlkibbe @dlounsbu Closing this card for Debbie & David's work on this in October. 
Created new review card for Lindsey - #1567
