### ISSUE TITLE
r21_vapor_ajcp - Review and Add VAPOR context

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1377]
Lindsey will add a little more context of VAPOR and Modeling to Learn now & link to the videos.
Finish review and edits & hand off.

Cross Ref: #697

**Comment by lzim** [comment]
@staceypark 
Submission of this manuscript needs to come after the R01 Protocol manuscript.
I'm going to put back in the Priority Pipeline and remove from In progress

**Comment by staceypark** [comment]
@lzim where are we with this? And whats the appropriate place to slot it in relation to our Story 1 plan?
putting in June for now since we are focusing on GMB, then R01
