### ISSUE TITLE
wk1/2: r01_protocol_impsci - Review & Upload Supplementary materials

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1379]
Cross ref: #559 

**Direct link to the additional_files.docx in OSF:  https://osf.io/cp65q/**

- [x] Explain in supplementary materials that we are using MTL Red (AF) vs. MTL Blue (PSD) language for the field, but keep to the "PSD vs. AF" language as is in the main protocol
- [x] Upload co-planning file templates to OSF with TeamPSD logos & branding (Myraid Pro, VA & MTL logos, etc.) 
1. document mtl_123_sitename_local_coplanning_agenda_meeting1.docx
2. presentation mtl_123_sitename_local_coplanning_stakeholder_map_meeting1.pptx
3. document visnnumber_123_sitename_notes.docx
4. local co-planning 2 process
- [x] Add all the measures in .docx form to OSF ready for upload.
1. Describe RedCap. Look for RedCap citation guidance to include for publishing.
- [x] Review all the supplementary material uploads for use of** _MTL 2.0 _video, guides, models, link to RedCap MTL Menu demo.*

**Comment by staceypark** [comment]
Consider anything someone else will need to be able to run our program including research, coplanning, guides, measures, etc.
***Re-read what are allowable supplementary materials and the format for them.

**Comment by lijenn** [comment]
Note to self for supplementary docs requirements (known as 'additional files' for imp sci and imp sci comm):
- imp sci: https://implementationscience.biomedcentral.com/submission-guidelines/preparing-your-manuscript#preparing+additional+files
- imp sci comm: https://implementationsciencecomms.biomedcentral.com/submission-guidelines/preparing-your-manuscript#preparing+additional+files
- requirements for additional files: https://www.biomedcentral.com/getpublished/writing-resources/additional-files
