### ISSUE TITLE
Number Dropdown Scales in Experiment Variables and Save Dialogue Not Sufficient

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#1382]
**1. Add description:** 
The number scale in the Number dropdown, in certain Experiment Variables (such as Appointment Supply and Engagement Duration) and in the Save dialogue, in various modules, are not adequate to cover the possible range of values for the variable.  Currently, the number scale maximum in the Save Dialogue is 100.  The range of possible experimental values are from 0 to 200.  Some values provided by team data for this variable exceed this amount.

 ![image](https://user-images.githubusercontent.com/31182258/80542784-aa568100-897b-11ea-9264-cd6c7afe07b3.png)
 
**2. Possible Dependencies.** Modeling and Facilitation may need to specify a better range of values to code into the simulation.

FYI @dlkibbe

**Comment by dlkibbe** [comment]
@jamesmrollins here is another example of this in Aggregate module. The appointment supply range from 0 to 200 does not encapsulate the Appointment Supply numbers in the team data table (i.e., Adj 207, MM 226 and Psy 560). 
![image](https://user-images.githubusercontent.com/31182258/80621779-cb6bb000-8a15-11ea-9890-bb341b188ac8.png)

**Comment by jamesmrollins** [comment]
Hi @dlkibbe .  Would quote the Team Data filename in this thread so I can look it up?  Thanks, James

**Comment by dlkibbe** [comment]
@jamesmrollins  -- sorry its the only file I have in test! 
583ge_wl_bhip_2019_04_14.xlsx

**Comment by jamesmrollins** [comment]
No worries @dlkibbe !  I'm glad we are discovering these issues now, versus after release 😁

**Comment by lzim** [comment]
@jamesmrollins 

Reviewing the** bug_tracker** I saw this issue, looks like it hasn't been closed yet.
What's the status? 
Thanks!

**Comment by jamesmrollins** [comment]
@lzim I am going to see if there is away to dynamically adjust these ranges, since it may be impossible to guess what maximum values may turn out to be.  

FYI @hirenp-waferwire

**Comment by jamesmrollins** [comment]
@lzim and @dkibbe, the most straightforward way to address this may be to **allow free text.**  We can limit what is hand entered to accept only whole numbers.  This would also provide better performance.  For example in the SP model, we have a dropdown that has to build a number list from -8000 to +8000 and is difficult to use. What are your thoughts?

**Comment by jamesmrollins** [comment]
@lzim and @dlkibbe - re-pinging this issue.  Do you accept the recommendation?

**Comment by dlkibbe** [comment]
@lzim @jamesmrollins allowing a user to hand enter whole numbers makes sense to me especially given the variation in the ranges across variables.
