### ISSUE TITLE
AUG Task : Review R Style Guide

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1385]
Review #1366 for clarity and completeness of the R Style Guide

- [ ] Style guide covers common use cases
- [ ] Style guide will create standard code if followed
- [ ] Style guide is easy to follow and understand

**Comment by lzim** [comment]
Following-up on dependencies across #1220, #1192, #1366, #1367, which we discussed at Support Workgroup Leads on 4/29/20

@anazariz and @anthonycpichardo 
- The would need to be covered in our **Team PSD Manual** #1192 to train and support Team PSD members.
- Needs to consider our **Master Crosswalk Process Goal:** “...standards are developed and every instance of a Team PSD or MTL variable instance, data definition, code base (e.g., interdependent .Rmd, data and .R; SQL joins etc.) in a way that is consistent across Team PSD workgroups.

**Comment by anazariz** [comment]
@anthonycpichardo I completed reviewing #1366 (R Style Guide) for clarity and completeness and did not find any issues with the content.
