### ISSUE TITLE
August - Due Review draft Form for WRJ on TeamPSD COVID-19 associated research - HSRD grant & NIDA Supplement 

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#1391]
**1. Review draft Form for WRJ on TeamPSD COVID-19 associated research - HSRD grant & NIDA Supplement** 

@lzim Please review the draft form for WRJ on TeamPSD COVID-19 associated research - HSRD grant & NIDA Supplement available on shared TeamPSD folder
thanks, 

Cross reference issue #1360

**Comment by lzim** [comment]
> **1. Review draft Form for WRJ on TeamPSD COVID-19 associated research - HSRD grant & NIDA Supplement**
> 
> @lzim Please review the draft form for WRJ on TeamPSD COVID-19 associated research - HSRD grant & NIDA Supplement available on shared TeamPSD folder
> thanks,
> 
> Cross reference issue #1360

@ritahitching Whoa! thanks for assigning a review card, without it #1360 was invisible to me. 😅 
- Within Team PSD is this in the grants folder? [Note: Chat me the location on Teams, if needed].
