### ISSUE TITLE
wk2 Task Create Data_ui_check 

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1395]
Referencing #627

Create a checklist for the data_ui that will allow teammates to know how to use and troubleshoot any issues.

**Comment by anthonycpichardo** [comment]
@staceypark  @lijenn 

Document is available under data_ui/documents/data_ui_check on mtl_operations and is ready for review.

Let me know what feedback you have! =)

**Comment by lzim** [comment]
@staceypark  Are you able to review this?

**Comment by staceypark** [comment]
@anthonycpichardo I made a few changes to make it readable as a markdown file.
I read the doc and it doesn't explain how to run the propagation or where to go for the instructions.
I'm not sure what to do with the list of code and buttons without further context.

**Comment by anthonycpichardo** [comment]
I will add the propagation instructions

**Comment by anthonycpichardo** [comment]
added the propagation instructions.
