### ISSUE TITLE
First Modeling Session

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#14]
Lead = Melissa

**Comment by lzim** [comment]
Hi Melissa,

This is the "Facilitation Guide" Project Tracking part of GitHub that we can use as we iterate on our PSD facilitation materials.  I've assed the "First Modeling Session," which we discussed this morning, to you.

This "issue" will track the project and we can discuss it here - it will push the updates to Basecamp automatically, so we can track progress there.

I created two "milestones" for this item a "see.Rmd" file and a "say.Rmd" file. We can discuss it here, but I should also see it any updates in my "feed."

Last, if you have questions about specific code, etc.  You can assign this issue to me (or another collaborator from our team) to "review."

Thanks!

Lindsey

**Comment by mjlondon** [comment]
Hi Lindsey,

I've updated the files, but we are in need of those two images that you suggested- one being either a bathtub or a sink of some sort and one to represent the model.

Citations are still missing from the SAY file and I will do my best to add those in the next week.

Best,
Melissa
