### ISSUE TITLE
6/5Task: tt_report 071 week commencing June 8

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#1419]
**Team PSD tt_report 071** 

@lzim 
Hi All:
I made some suggestions for the tt_071 report for week commencing June 8.  I'd welcome your
feedback.

**Any updates for next week's tt_report (6/8)** @jamesmrollins @anthonycpichardo @jessfroe  @staceypark @lijenn? 

- [x] tt_report 071 using new [template](https://github.com/lzim/teampsd/blob/master/resources/training_guides/emails_outlook/tt_teampsd.md)
- [x] Suggested Subject, Announcement & Epic

**Subject Line** 
[tt_071] Week 2 of Continuous Integration & Prototyping for TeamPSD

**Announcement** 
**1. Team PSD has fully incorporated last month's 2.0 design process for our monthly sprints/epics:**
- Week 1 - user-centered hypotheses
- Week 2 - clarifying assumptions with an user-centered MVP hypothesis test
- Week 3 - review of the results of user persona testing of your MVPs (with concurrent video and retrospective verbal think aloud)
- Week 4 - review the user-persona artifacts mindfully and empathically to discover new understandings you might have missed or still need to learn

**2 . Current Prototypes in Progress**
- R & SQL Integrations to improve R21 data visibility 
- TeamPSD Bookdown Manual & Markdown Linter via GitHub Actions continuous integration of all Team PSD documentation  
- LucidCharts & GitHub continuous integration to support real time visual workflow guides  for all Team PSD workgroups
- Vensim Model & Forio Epicenter and GitHub & Forio Epicenter continuous integration across all platforms 
- Video Library for all Team PSD members to use and contribute to for shared learning

**Epic**
June_Epic continues & ends 6/30

- [x] Check for LucidMeeting updates
- [x] Contact Workgroup Leads for updates
- [x] Test formatting of email
- [x] To be in Team PSD members' inbox MondayJune 8 by 8:00am to be used at Workgroup Leads meeting

**Comment by lzim** [comment]
@ritahitching @staceypark @lijenn 

**First**, I'd like to help with coaching consistent with **_all Team PSD email subject lines._** Make people want to open the email within <30 characters (often we use _"We decided...")._ To open it, they need to see something that calls to them that they should open it.

This original Subject Line will be 100% uninterpretable among 80% of the recipients of the message (all our senior Co-Is, Stanford partners, the QIICs, etc.):
[tt_071] Week 2 of Continuous Integration & Prototyping for TeamPSD

Consider instead something like (based on the questions I ask workgroup leads below):
[tt_071] teampsd 2.0 - Co-I review Tues 6/9 10AM & QIIC meeting Fri 6/12 at 10AM

- Perhaps there are other suggestions, but we really need to engage these two groups (see below).

**Second**, I'd like to help with coaching consistent with what we using in **_all instructional guides_** (e.g., SEE and SAY guides), etc. We use **Bloom learning verbs** across Team PSD and _MTL_ style.

VERBs are used in parallel across all sentences. By parallel, we mean in the same tense, lead the sentence and all unnecessary adjectives (e.g., "fully") are removed.
For example, in _Modeling to Learn_ the learning objectives are standardized as 
- Describe
- Test
- Apply

So, for example you would edit to this:

**1. Team PSD 2.0 Workflow for All MontEpic:**
Week 1 - Refine user-centered hypotheses.
Week 2 - Test key assumptions with user-centered MVPs/prototypes.
Week 3 - Synthesize MVP user testing results from concurrent video and retrospective verbal think aloud protocols.
Week 4 - Integrate prototype into Team PSD workflow; Conduct "second story" review for continuous learning.

**2. June Epic Priorities by Workgroup
- **quant_workgroup** Improve R21 data visibility
- **hq_workgroup** a) Develop Team PSD GitHub Actions, 2) Finalize LucidCharts <> GitHub integrated workflow.
- **sim_workgroup.** Refine Team PSD continuous integration, inclusive of Vensim & Forio Epicenter.

**June Epic 6/1/2020-6/30/2020**

Questions for @lijenn @ritahitching and @staceypark 
1. **When is the follow-up meeting with the QIICS?** 
- We said last Friday it would be M/W/F. In my view Wed or Friday is preferred. We'll want to make sure it's a) finalized with the QIICs, and b) on the Lucid Calendar screenshot that goes out Monday morning.
- What about the co-I meeting on Tuesday? Will **quant_workgroup** be ready to review a prototype with these users on Tuesday? @anthonycpichardo and @anazariz 
2. **The priorities above don't capture all workgroups:** Can you help @ritahitching @lijenn @staceypark @jessfroe for at least **facilitate** **co-I** and **qual?**

**Comment by lijenn** [comment]
@ritahitching 
For **2. June Epic Priorities by Workgroup**
- **facilitate_workgroup** 1) EES & QIIC Personas, 2) Test & review MVPs/prototypes

The **follow-up with the QIICS** will either be next Wednesday 6/10 or the following Wednesday after next week 6/17 as schedules may shift some QIICS. I will touch base when when this is finalized and in Lucid.

**Comment by ritahitching** [comment]
@lijenn please let me know once a date with the QIICs is finalized. thank you

**Comment by ritahitching** [comment]
@ritahitching closing this issue as tt_report sent
