### ISSUE TITLE
July Task: TeamPSD 2.0 Organization Flow Map

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1423]
See Team PSD 2.0 organization flow map here:
https://app.lucidchart.com/documents/edit/d2399f12-a16c-439d-9d3d-7e7410633ea5/0_0

**Assumptions/Hypothesis:**
Repos are organized to  
a) reduce total number of repos
 b) based on whether they share a CI workflow
c) account for compliance issues d) integrate w/ZenHub

 Final List of 7 Repositories: 
1. lzim/teampsd (Public)  #1436 
2. lzim/mtl (Public)  #1422
3. "va/mtl" (GH Enterprise) (operations pipeline) 
4. lzim/research (formerly lzim/mtl_code) (Private)  #1424 
5. "va/research" (GH_Enterprise) (research pipeline) 
6. lzim/team_tracker (Private)   [August_epic]
7. lzim/sim #1430 
-----------------------------------------------------
What environment variables and folder structure will we use?
**Proposed Environment Variables & Folders**
1. readme.md - will be main page you see on the repo explaining what the repo has and how they work
2. .gitignore - for temp files you want to ignore
3. license.md - outlines what can and cannot be done with our code (there are different license templates on GitHub that help you figure out what kind you want)
4. code-of-conduct.md - similar to what James created for the lzim/mtl repo CoC under wiki (outlines how interaction should be conducted i.e. no trolling etc.)
5. fonts folder - for teampsd look and feel
6. css folder - for teampsd colors
7. images folder- for teampsd logos
8. .yml config file - sets parameters and initial settings in environment for running an app
9. docs folder - explains how actions work?
10. tests folder - folder of test scripts within the scripts folder
11. scripts folder - tools
12. packages folder - multiple tools brought together (scripts build the package)
13. vignettes - as a subset nested under packages
14. .github folder - configure issue and pull request templates. have example of “good first issue”
15. .workflow folder - needed for GH actions 
16. secrets - encrypted environment variables using a libsodium sealed box to that it is encrypted before reaching GitHub - note for a repository secret, only the repository owner can create this
17. gh-pages branch - GH Actions for Bookdown Manuals 
18. api
19. web - probably only for mtl.how repo

**Comment by lijenn** [comment]
Currently editing lists here:

**Comment by dlounsbu** [comment]
What is my LucidChart ID? How will I use LucidChart, as co-faciliator and a co-I on the Qual workgroup?

**Comment by lijenn** [comment]
@dlounsbu David, the team has made the inclusion of needing a platform to be able to create flow maps and charts as these help visualize processes that may otherwise be "unseen" within the team. We have a team account and I can forward you & @branscombj the details!

We have begun to use LucidCharts for its ability to create these intricate processes as it includes a lot of functions like custom templates, ability to work on a map or chart with other people at the same time (similar to google docs), etc. 

If you ever need/want to visually show a process that might be verbally hard to describe, you can use LucidCharts to create a TeamPSD style flow map or chart. 

We are in still in the process of the TeamPSD template for this and the overall file structure of where maps should go in LucidChart.

**Comment by anthonycpichardo** [comment]
My vote is for List 1 for the same reasons that James documented on Teams where prototype 1 seems to match our functional alignments most closely.

**Comment by branscombj** [comment]
Here is my mental model for _Modeling to Learn_:

**Human Resources** 
- Support staff - hiring, onboarding, management
- Facilitators - selection, training, supervision
- Interns - selection, training, mentorship
- Partners - engagement, relationship management (other than teams currently participating in _MTL_)
	
**Financial Resources**
- Grant writing/development
- Grants management and reporting
- Contracting and subcontracting
- Accounting and financial reporting

**Program Development**
- _MTL_ data pipeline
- Data UI
- Model design
- Sim UI
- Facilitation design
- Facilitation resources/materials
- Accreditation and 508 compliance

**Program Implementation**
- Site identification
- Team engagement and onboarding
- Co-facilitation
- Supervision
- Delivery platforms/technology
- Communications
	
**Research**
- Advisory
- Research design
- Compliance
- Data pipeline design
- Data collection and storage
- Data analysis

**Dissemination**
- Manuscripts
- Conferences/meetings
- Social/web
- TMS
- Media/gray literature

**Comment by branscombj** [comment]
I'm shakier on who's meant by these categories of people and their responsibilities, but here's a stab at cross-walking them with the above:

**Human   Resources** | HQ | Qual | Quant | Sim | Facilitate | Co-I
---| -- | -- | -- | -- | -- | --
Support staff   - hiring, onboarding, management | X |   |   |   |   |  
Facilitators -   selection, training, supervision |   |   |   |   | X |  
Interns -   selection, training, mentorship |   |   |   |   |   | X
Partners -   engagement, relationship management | X |   |   |   |   |  
**Financial   Resources** |   |   |   |   |   |  
Grant   writing/development | X |   |   |   |   | X
Grants   management and reporting | X |   |   |   |   |  
Contracting   and subcontracting | X |   |   |   |   |  
Accounting and   financial reporting | X |   |   |   |   |  
**Program   Development** |   |   |   |   |   |  
MTL data pipeline |   |   | X |   |   |  
Data UI |   |   | X | X | X |  
Model design |   |   |   | X |   |  
Sim UI |   |   |   | X | X |  
Facilitation   design |   |   |   |   | X |  
Facilitation   resources/materials | X |   |   |   | X |  
Accreditation   and 508 compliance | X |   |   |   | X |  
**Program   Implementation** |   |   |   |   |   |  
Site   identification | X |   |   |   | X |  
Team   engagement and onboarding | X |   |   |   | X |  
Co-facilitation |   |   |   |   | X |  
Supervision | X |   |   |   | X |  
Delivery   platforms/technology | X |   |   |   | X |  
Communications | X |   |   |   | X |  
**Research** |   |   |   |   |   |  
Advisory |   |   |   |   |   |  
Research   design |   | X | X |   |   | X
Compliance | X |   |   |   |   | X
Data pipeline   design |   | X | X |   |   | X
Data   collection and storage | X | X | X |   |   |  
Data analysis |   | X | X |   |   | X
**Dissemination** |   |   |   |   |   |  
Manuscripts | X | X | X | X | X | X
Conferences/meetings |   | X | X | X | X | X
Social/web | X |   |   |   |   | X
TMS | X |   |   |   | X |  
Media/gray   literature | X |   |   |   |   | X

**Comment by jamesmrollins** [comment]
As a result of our 7/6 meeting we decided:

_We will use as few repositories as is possible, to reduce the aperture for mistakes and complexity and promote scalability.  Repositories are defined by workflow, not workgroup, to promote standardization of testing and CI/CD actions._

**Comment by staceypark** [comment]
@jamesmrollins btw for the url you added, for the hyperlink to actually work, the address needs to be within the parentheses as well - [text displayed](actual url to the site)

> We reduced the number of repositories from 5 repositories to 4. One will reside inside the VA domain, the remaining 3 on public GitHub. See https://app.lucidchart.com/documents/edit/d2399f12-a16c-439d-9d3d-7e7410633ea5/0_0 for a diagram.

**Comment by anthonycpichardo** [comment]
> @jamesmrollins btw for the url you added, for the hyperlink to actually work, the address needs to be within the parentheses as well - [text displayed](actual url to the site)
> 
> > We reduced the number of repositories from 5 repositories to 4. One will reside inside the VA domain, the remaining 3 on public GitHub. See https://app.lucidchart.com/documents/edit/d2399f12-a16c-439d-9d3d-7e7410633ea5/0_0 for a diagram.

Also, I thought the final decision was the 6 repos outlined on the lucidchart?

Sorry, if I misunderstood something there.

**Comment by staceypark** [comment]
> > @jamesmrollins btw for the url you added, for the hyperlink to actually work, the address needs to be within the parentheses as well - [text displayed](actual url to the site)
> > > We reduced the number of repositories from 5 repositories to 4. One will reside inside the VA domain, the remaining 3 on public GitHub. See https://app.lucidchart.com/documents/edit/d2399f12-a16c-439d-9d3d-7e7410633ea5/0_0 for a diagram.
> 
> Also, I thought the final decision was the 6 repos outlined on the lucidchart?
> 
> Sorry, if I misunderstood something there.

Good question... @jamesmrollins where did you get 4?

**Comment by jamesmrollins** [comment]
@staceypark @anthonycpichardo  I was gisting notes, so likely something I heard.  I didn't reconcile the notes with the diagram. 

I see the following repositories in the diagram:
1.  VA/Team Data
2. lzim/mtl (to contain the SIM UI and Model resources)
3. lzim/teampsd
4. lzim/mtl_code (to be renamed)

I see the following trackers in the diagram:
1.  team_tracker (in lzim/teampsd)
2.  manuscript_tracker (in lzim/teampsd)
3.  bug_tracker (in lzim/teampsd) (not shown in the diagram)
4.  feature_tracker (lzim/teampsd) (not shown in the diagram)

**Comment by lijenn** [comment]
Closing as flow map was created and repos/purposes were finalized.
