### ISSUE TITLE
July Task: lzim/research Repo Design (formerly lzim/mtl_code)

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1424]
From Team Time 6/9:

Task: Think early and often about potential dependencies and delegation, raise awareness early while working on the redesign of the following repo's structures:
 **lzim/mtl_code (Anthony)**

**Week 2 "root" MVPs** 
- (#1423) Team PSD 2.0 org chart map (HQ)
- (#1422 & # #1424) Repo design map (HQ mtl & teampsd (); Quant mtl_code...VA Enterprise vs. non-VA GH; Research vs. Operations)
- (#1425) R Studio IDE or GH Desktop & Git workflow map (Quant would be helpful HQ)
	
**Platforms to think about:**
- GitHub (All)** Natively on GH.
- OSF (All)
- Lucid Chart (All)
- R Studio IDE (cuts across workgroups)**project for each repo that sets up my Git.
- SQL Server (quant; maybe co-Is)

**Comment by anthonycpichardo** [comment]
Related to #1425. Adding blocking dependency

**Comment by dkngenda** [comment]
I found [this](https://learn-the-web.algonquindesign.ca/courses/web-dev-6/github-project-setup/) link quite informative on best practices for setting up team git repos.

**Comment by dkngenda** [comment]
@anthonycpichardo, below are my GitHub use cases I can think of now. I'll update the list if I think of something else

-	Access research data and related metadata.
-	Review code (with documentation) used for production of research data.
-	Document analyses I am working on, pull requests and store results.
-	Share prototypes (including R code) I am working and track/respond to comments from reviewers. 
-	Track issues that I am tagged on.
-	 Store research articles/tutorials of interest.

**Comment by anazariz** [comment]
**Use Case (Data Engineer):** 

 1. Repo will be used for version control of:
     1. Script Source Code
     2. Table and View Definitions
     3. Stored Procedures and Functions
2. Repo will be used for meta data management: 
Field:
    1. Name 
    2. Description 
    3. History
3. Repo will be used for StTM (Source to Target Mapping) 4 columns: 
    1. Source Table/Field
    2. Transformation
    3. Target Table/Field
    4. Optional Comments
4. Repo will be used to store ERD (Entity Relation Diagrams)

**Comment by anthonycpichardo** [comment]
Needs (Data Analyst)
1. Central platform for:
  1. R & SQL Code
  2. Technical Specs
  3. Analysis and Documentation
2. Repo will handle version control
3. Repo will run test cases
4. Repo will support issue and bug triage
5. Repo will facilitate requirement documents and project proposals

**Comment by anthonycpichardo** [comment]
Automation Tests:
R Linter for style guide
Style Conformation for manuscripts

**Comment by lzim** [comment]
@anazariz @anthonycpichardo @dkngenda @lijenn @staceypark 

Decisions made during the **july_epic:**
1. Renamed to lzim/research
2. Will use Tidyverse Style guide for R.

- Anthony has prototypes, what are the issue dependencies?
- Let's track those carefully for **week 3 8AM Monday Workgroup Leads meeting** next week

#1281 R21 Data Model for Tests of Specific Aims
#1439 STTM
#1422 lzim/research
#1440 .r, .md, .sql Style Guides
#1429 Split Pipeline Data Lineage
#1401 GH actions w/Markdown Lint

**Comment by anthonycpichardo** [comment]
Repo has been renamed and branches cleaned up--ready to follow new process. Manual for lzim/research will be tracked using : https://github.com/lzim/research/issues/24
