### ISSUE TITLE
wk1 Task: MS Teams workflow + Citrix Guide 

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1426]
**Hypotheses:** 
- All of Team PSD and partners need better orientation to our main communication platform, MS Teams, as a part of #1192 TeamPSD 2.0 Manual Bookdown.
- Concerns: Need to list out issues and dependencies related to TeamPSD using the MS Teams Free ver. which has some different features from VA Teams which our VA partners use to develop Whys & How for the guide.
- VA Teams Timeline:
Phase 2 Island Mode: Begins Wednesday July 22nd till August.
Phase 3 Teams Mode only: 

--------------------------
Current MVP: https://lijenn.github.io/teampsdprototype/_book/4-ms-teams.html
- Using Microsoft's General Quick Start Guide: https://www.chorus.co/media/2989/quickstart-guide-to-teams-chorus.pdf
This guide covers the majority Communication functions that applies for both VA and Free Teams Version, but **lacks use cases based on our Teams needs.**
- Covers some of Team PSD/VA specific conventions and features not explicitly mentioned in the quick start guide:
   - Switch Organizations
   - Meet in a Channel
   - Edit Message/Reply
   - Use Markdown
   - Start a Call in a Thread
   - “React” to a Comment
   - Link a Comment/Discussion/File

**To do: Will need help to flush needs and functions based on each Team member's pain points with navigating Teams before we fully phase out Lucid.**

**Comment by lijenn** [comment]
@lzim @staceypark @jamesmrollins @anthonycpichardo @anazariz @dkngenda 

Hi Team! Last Friday, we discussed of trying to access our VA teams by trying to add our VA Teams Account to our Free teampsd_vha Teams Organization to link up these 2 accounts and see how that would work. This morning, we discovered features and bugs related to the Meeting Notes function. 

I will need help collecting any **issues that you may be having with additional functions that you may find useful or are thinking of adding on onto Teams** and/or **concerns related to linking up our VA and Free accounts (think of personal computer or Citrix limitations that we may not be aware of)** to better develop the Whys and Hows as we migrate to Teams. 

**Tips that make the experience easier are appreciated!**

In addition, please do try the [Quick Start Guide](https://www.chorus.co/media/2989/quickstart-guide-to-teams-chorus.pdf) made by Microsoft. **What is missing here that we could add into our guide?**

Here are some documented concerns/tips at the moment:
- How to switch organizations.
- How to add members into Organizations. 
- How to share screen on dual monitors.
- How to show peoples' webcams/faces when sharing screen. 
- Citrix has a Desktop MS Teams App, but impossible/hard to sign in at the moment. 
- Teams WebApp version in Citrix has no audio.
- How do we connect our Free Version Accounts to the VA Teams Organization? 
(We can only connect our VA emails to the Free Version at the moment)
- Meeting Notes 'locks' when a user is clicked into it.
   - Possible solution: Try adding a different section so multiple members can edit their section.
- Meeting Notes only refreshes when you are viewing it when fully clicked out of the meeting (does not update in compact version during a meeting call).
- How to add members into Organizations.

**Comment by staceypark** [comment]
@lijenn I believe this is done

**Comment by lijenn** [comment]
re-opening due to edits and incorporation of signing into citrix.
