### ISSUE TITLE
Task: Link Vensim Experiment Variable Min/Max Values to Sim UI Experiment Sliders

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#1433]
### Check off requirements to verify progress through feature_tracker.
- [ ] 1. **DEFINE in work_breakdown**
  - [ ] a. The current min/max values that limit the slider range in the Experiments Section are hard-coded.  If a range of values needs to be changed, it must be done at the code level.  This modification sets min/max values within the .mdl file, and the Sim UI code will auto-update.  What this means:  If a range of values has been found to be incorrect, all the user would have to do is update the min/max values in the Vensim model, and the process would automatically update the slider ranges in the Sim UI Experiments section.
  - [ ] b. **date & who** -  **Verified** requirement definitions an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 2. **DESIGN** in **operations_to_do** and **research_to_do**
  - [ ] a. **what & why** - **_MVP_ of design** of requirements in a **algorithm map, wireframes or design** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** design **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 3. **DEVELOP** in **under_development** - "frozen"

  Task Cards:
  #
---
- [ ] 4. **TEST in functional_test**
  - [ ] a. **what & why** - **TEST requirements** using **testing_checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** via TEST **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 5. **PROD in done**
  - [ ] a. **what & why** - **_DOCUMENT_ feature** using **document_tracker** for the **5 D's.** 
  - [ ] b. **date & who** -  **DELEGATE**
    - [ ] **describe_learners** [Jenn & Rita]
    - [ ] **detail_facilitators** [Jane & Debbie]
    - [ ] **document_team** [Anthony]
    - [ ] **disseminate_scientists_va** [Anthony]
    - [ ] **depend_products** [hq & ees]
  
  Task Cards:
  #
---
- [ ] 6. **closed** - fully documented, trained and ready for the next release.

**Comment by jamesmrollins** [comment]
@lzim and @staceypark.  We could do this in the NOV epic. It would entail changing the code to read the min/max values provided by the Vensim model (this is now supported by Epicenter).  While we are in there, we should also look at hooking up the "i" information from the model file tool, as this too is now supported by Epicenter.  The model files have been all updated with the latest "i" information (Lucy did that back in August).

**Comment by jamesmrollins** [comment]
After capacity planning with the DEV team, we placed this issue in reserve to free up time for issues still in current epic.

**Comment by staceypark** [comment]
thanks for the update @jamesmrollins.
I agree we definitely have more pressing items in the current november epic. I've moved the milestone & epic to december and changed the pipeline to upcoming.

**Comment by jamesmrollins** [comment]
This coding is completed and testing is being managed under issue #1637
