### ISSUE TITLE
Install SmartLook User Analysis Cookies on MTL Web Pages

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#1434]
### Check off requirements to verify progress through feature_tracker.
- [x] 1. **DEFINE in work_breakdown**
  - [x] a. We need analytics that help us understand how the users are interacting with our various web pages.  Google analytics tells us which pages are being used, but do not provide sufficient details in how the moves around the page and clicks on object on the page.  We intend to set up user recording using the SmartLook service, see [https://www.smartlook.com/](url)
  - [ ] b. **date & who** -  **Verified** requirement definitions an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 2. **DESIGN** in **operations_to_do** and **research_to_do**
  - [ ] a. **what & why** - **_MVP_ of design** of requirements in a **algorithm map, wireframes or design** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** design **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 3. **DEVELOP** in **under_development** - "frozen"

  Task Cards:
  #
---
- [ ] 4. **TEST in functional_test**
  - [ ] a. **what & why** - **TEST requirements** using **testing_checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** via TEST **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 5. **PROD in done**
  - [ ] a. **what & why** - **_DOCUMENT_ feature** using **document_tracker** for the **5 D's.** 
  - [ ] b. **date & who** -  **DELEGATE**
    - [ ] **describe_learners** [Jenn & Rita]
    - [ ] **detail_facilitators** [Jane & Debbie]
    - [ ] **document_team** [Anthony]
    - [ ] **disseminate_scientists_va** [Anthony]
    - [ ] **depend_products** [hq & ees]
  
  Task Cards:
  #
---
- [ ] 6. **closed** - fully documented, trained and ready for the next release.

**Comment by staceypark** [comment]
@jamesmrollins will present on this at the 9/17 HQ workgroup.

**Comment by lzim** [comment]
@jamesmrollins Just cleaning up issues, is this done?

**Comment by jamesmrollins** [comment]
@lzim Yes - would you like me to close it?

**Comment by lzim** [comment]
For sure, you can have the honors @jamesmrollins 

Whoo hoo! 🎊
