### ISSUE TITLE
Develop Team Data CD - Epicenter Sim UI Drop Down Update Action

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#1435]
### Check off requirements to verify progress through feature_tracker.
- [X] 1. Hypothesis: 

  1. This Action will automate the process of adding a team data file to Epicenter and updating the drop down menu in on the Home page of the Sim UI. The file adding process will be managed from the SharePoint end by the end user with no touch points needed by admin from back end Epicenter (see #2 below).
  2. The Action will reduce user touch points from learning three platforms (SharePoint, Epicenter and the Sim UI) to just one (SharePoint).
  3. The Action will mistake-proof the Team Data update process.

Linked to:

Task Cards:
  #
---
- [ ] 2. **DESIGN** in **operations_to_do** and **research_to_do**
  - [ ] a. **what & why** - **_MVP_ of design** of requirements in a **algorithm map, wireframes or design** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** design **asynchronously** or an **existing team meeting.**

  Task Cards:
  #
---
- [ ] 3. **DEVELOP** in **under_development** - "frozen"

  Task Cards:
  #
---
- [ ] 4. **TEST in functional_test**
  - [ ] a. **what & why** - **TEST requirements** using **testing_checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** via TEST **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 5. **PROD in done**
  - [ ] a. **what & why** - **_DOCUMENT_ feature** using **document_tracker** for the **5 D's.** 
  - [ ] b. **date & who** -  **DELEGATE**
    - [ ] **describe_learners** [Jenn & Rita]
    - [ ] **detail_facilitators** [Jane & Debbie]
    - [ ] **document_team** [Anthony]
    - [ ] **disseminate_scientists_va** [Anthony]
    - [ ] **depend_products** [hq & ees]
  
  Task Cards:
  #
---
- [ ] 6. **closed** - fully documented, trained and ready for the next release.

**Comment by staceypark** [comment]
Two things to add to the above:
1. The file adding process will ideally be managed from the SharePoint end by the end user with no touch points needed by admin from back end Epicenter.
2. In case of any possible corruption or errors, I think there should still be some backend way to "fix" things either by way of SharePoint or Epicenter. Whichever makes more sense for possible bugs that could pop up.

**Comment by jamesmrollins** [comment]
Hi @staceypark - Thank you for the feedback.  I will add in your number 1 above.

Regarding the quote bellow- Can you go into a little more detail please?  What do you mean by a "Backend way to "Fix" things?
> 2\. In case of any possible corruption or errors, I think there should still be some backend way to "fix" things either by way of SharePoint or Epicenter. Whichever makes more sense for possible bugs that could pop up

**Comment by lzim** [comment]
FYI: @jamesmrollins  and @staceypark 

We may need something other than Icebox, which implies "nice to have" but doesn't include it in a specific new release.

**Comment by staceypark** [comment]
@lzim @jamesmrollins 
Open Features >  Feature tracker at mtl.how/features >  future_release?

**Comment by lzim** [comment]
That sounds good @staceypark

**Comment by jamesmrollins** [comment]
This card is an original that was in the icebox.  It was duplicated in a later feature release, that included the feature requested above.  The hours for this card were removed to not duplicate story points and was closed.
