### ISSUE TITLE
WK 1 : 2/17 qual - authorship app prior_work categories input into app

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1437]
@lzim I kept the categories from the meeting yesterday and reviewed the ones we previously had on OSF. The additional ones are "checkboxes" instead of "bullets". 

Could you review and just check off the boxes of any additional we should keep? Then, I'll ping WG leads on this issue as well for them to work on this in their meetings next week.

Here are the links.
ICJME: http://www.icmje.org/recommendations/browse/roles-and-responsibilities/defining-the-role-of-authors-and-contributors.html

APA: https://www.apa.org/science/leadership/students/authorship-determination-scorecard.pdf

## HQ
-- Graphs
-- Tables
-- Literature Review
-- Stakeholder Relationships

- [ ] Pre-post emails
- [ ] mtl learner & facilitator cheatsheets
- [ ] redcap mtl menu programming 

## Research/Co-Is
- R21
-- Literature Review
-- Aims
-- Design
-- Measures
-- Analyses
- R01
-- Literature Review
-- Aims
-- Design
-- Measures
-- Analyses
- IIR
-- Literature Review
-- Aims
-- Design
-- Measures
-- Analyses

- [ ] DART
- [ ] clinical trials

 
## Qualitative
-- Systems Thinking Codebook
-- MTL Fidelity Codebook
-- CFIR Codebook

- [ ] codebook developer
- [ ] coder
- [ ] programmer rqda
- [ ] qualitative/design procedures

** We could do these 4 tasks by codebook? Or is that overkill

 
## Quantitative
-- Data UI/Splashpage
-- R Analyses and Workflow
-- CRM 
-- tt_reports
 
## Models
-- GMB
-- Vensim
-- Sim UI

same concepts as above but in more detail
- [ ] model conceptualization & stakeholder input 
- [ ] model development in Vensim 
- [ ] model data input/structure for model 
- [ ] model validation - tests of formulation mathematically (unit checking, etc.) 
- [ ] model validation - stakeholder review, variable names, etc. 
- [ ] model interface with sim UI 

 
## Facilitate
-- See Guides
-- Say Guides
-- Theory of Change/Fidelity
 
## EES
-- MTL Live
-- MTL Video
-- MTL Facilitate
-- Accreditation
-- Videos

- [ ] MTL Live & Video learning objectives & pre/post test
- [ ] MTL Live & Video EES documentation
- [ ] MTL Video facilitation, review, annotation
- [ ] MTL Video recording, editing
- [ ] MTL Facilitate LO, pre/post, EES documentation
 
## VAPOR
- Videos
- Measures & Designs

**Comment by dkngenda** [comment]
@lzim @staceypark I have now uploaded the updated app which can be found [here](https://dkn18.shinyapps.io/authorship_app-3/). Looking forward to testing this with users and getting more user feedback this week!

**Comment by lzim** [comment]
Discussed at **hq_workgroup**

- "Elemental" - "substantive contribution to the science" - "authorship"
- "Support" - "acknowledgement"

- Contributions are evaluated based on their function in the progress of the team's science (i.e., tests of specific aims).
e.g., Stakeholders to come up with the problem definitions address in the models. The primary scientific approach that was funded.
- Some contributions move the work along, but typically would not be the scientific contribution, unless written about and situated scientifically.

e.g., Manuscript focus: "The future of participatory collaboration at scale online during COVID19. Dynamic CRM is key to maintaining stakeholder engagement over time."

**Comment by staceypark** [comment]
Dicussed at **vapor_workgroup meeting** 7/28
Combining user feedback from Ren and SWS, we are considering creating an 
- "Advisory board" authorship category to include our Co-I's and current/past VAPOR board members for their scientific contributions and support in grant writing and analysis

**Comment by staceypark** [comment]
**Facilitate & EES** - @branscombj @dlkibbe 
**Qual** - @teampsdkathryn @dlounsbu @jessfroe @swapmush 

Following @branscombj's user feedback, @dkngenda has updated the [authorship_app](https://mtl.how/authorship) to be able to cue up previously assigned contributions by manuscript by contributor. To use this function effectively, we'd like for each workgroup to fill out prior contribution details for their workgroup contributions:

1. Review the sub categories above in the first comment of the thread under your workgroup headings.
2. If there are any scientific/research contributions that you feel are missing, add them. *For questions on what constitutes a scientific or research contribution, please refer to the ICJME link at the top.*
3. List out all the team members who have contributed to each of the contribution categories.
4. Assign a weight or number of points to each sub-category. *See the APA links for examples on categories and points*.

**Comment by staceypark** [comment]
8/3 #mm meeting w/ @branscombj @dlkibbe @dlounsbu 
1. Debbie & Jane will post a draft of the Facilitate & EES weights by the end of week.
2. David will bring the authorship_app to the qual workgroup meeting on Wed 8am Pacific / 11am Eastern.

**Comment by dlounsbu** [comment]
Qualitative
-- Systems Thinking Codebook
-- MTL Fidelity Codebook
-- CFIR Codebook

 codebook developer
 coder
 programmer rqda
 qualitative/design procedures
** We could do these 4 tasks by codebook? Or is that overkill

**Comment by teampsdkathryn** [comment]
David, I am fine with sub-dividing these tasks by codebook especially since some codebooks require input from multiple staff while others may come from one person. Best Regards, Kathryn

**Comment by dlkibbe** [comment]
@branscombj @staceypark @lijenn 
Instructions:
-Review the sub categories above in the first comment of the thread under your workgroup headings.
-If there are any scientific/research contributions that you feel are missing, add them. For questions on what constitutes a scientific or research contribution, please refer to the ICJME link at the top.
-List out all the team members who have contributed to each of the contribution categories.
-Assign a weight or number of points to each sub-category.  

**MTL Facilitate** (Training the Trainers)

Accreditation (does this count as scientific contribution?)
- branscombj 50%
- lzim 50%

Training Content - Contributors
- lzim 
- dlounsbu 
- TomRust 
- branscombj 
- dlkibbe 
- QIIC - input into final product

**Comment by dlkibbe** [comment]
**MTL Live**
-- Learning Objectives
-- See Guides
-- Say Guides
-- Say Checklists
-- Pre- & Post-Checklists (meeting prep & debrief)
-- Email communication between meetings
-- Fidelity Checklists 
-- Theory of Change (_does this belong here_?)

**MTL Video**
-- Accreditation
-- Creation/Recording of Videos
-- Pop-up message editing
-- Integration of VAPOR video content 

MTL Live & Video learning objectives & pre/post test
MTL Live & Video EES documentation
MTL Video facilitation, review, annotation
MTL Video recording, editing
MTL Facilitate LO, pre/post, EES documentation

**Comment by dlkibbe** [comment]
**MTL Video**
-- Accreditation
-- Creation/Recording of Videos
-- Pop-up message editing
-- Integration of VAPOR video content 

MTL Live & Video learning objectives & pre/post test
MTL Live & Video EES documentation
MTL Video facilitation, review, annotation
MTL Video recording, editing
MTL Facilitate LO, pre/post, EES documentation

**Comment by staceypark** [comment]
@dlounsbu @teampsdkathryn @jessfroe @swapmush 
Are there any further updates from the qual workgroup on the authorship app? I'm happy to join the qual meeting next week if need be.

**Comment by dlounsbu** [comment]
https://github.com/lzim/teampsd/issues/1437#issuecomment-669261512

Link above shows where Katheryn and I ended our discussion of this matter. 

To simplify qualitative workgroup EFFORT CATEGORIES for any QUALITATIVE MANUSCRIPT, I am proposing:

EFFORT CATEGORIES (for any qual manuscript):
- (20%) qualitative/design procedures (includes code book development, RQDA setup/management)
- (20%) qualitative coding (includes adjudication)  
- (40%) qualitative data synthesis (data pulls, merges, best quotes, summaries) 
- (20%) team coordination/convening/qual wg session minutes

QUAL WORKGROUP MEMBERS/CONTRIBUTORS inlcude:
- Katheryn
- David
- Lindsey
- Swap
- Jesslyn
- Stacy
- Others?? (Who am I forgetting?)

I hope this is helpful!

**Comment by staceypark** [comment]
@dlounsbu @teampsdkathryn @jessfroe @swapmush Let's try to get the qual categories wrapped up soon so we can get the authorship app updates finalized and close this issue!

**Comment by teampsdkathryn** [comment]
Hello Stacey,

I thought this was already wrapped up. Specifically, what remains for us to tackle? Thank you, Kathryn

**Comment by lijenn** [comment]
@dlounsbu @teampsdkathryn  @jessfroe  @swapmush 
@staceypark asks to please assign each qual wg member and their %'s within each of the Effort Categories mentioned from this [post](https://github.com/lzim/teampsd/issues/1437#issuecomment-674537520). Let's try to get this done before the end of the week!

**Example following the post by David:**
EFFORT CATEGORIES (for any qual manuscript):
- (20%) qualitative/design procedures (includes code book development, RQDA setup/management)
   - Kathryn 10%
   - David 15%
   - Lindsey 30%
   - Swap 45%
These %s would all add up to 100% based on the number of people and their contributions to that Effort Category.

**Comment by teampsdkathryn** [comment]
Hello Jennifer,

On what basis are we going to determine these percentages? They will change depending on the manuscript, how long one has been on the project and maybe the weight assigned to the category. To be accurate, one would have to keep a log which most team members have not done. It is even hard to guess the percentages.  Sincerely, Kathryn

**Comment by lzim** [comment]
Hi @teampsdkathryn 

This is my understanding of what the goals are, as developed by consensus across all Team PSD workgroups:

1. The **prior_work** categories are specifically designed to track work done over the time on the project, so that prior work can always be credited in the authorship. 
2. The weight assigned to the category will vary depending on the scope of the manuscript. Some manuscripts, depending on their topic, will include more or less **"prior_work"** of the kind described in #1.
3. Therefore, prior_work is not meant to capture the specific work on a given manuscript. That work is captured by **write_analyze_edit**

- The major advantages of this approach are:
a. We can honor all the prior contributions that Team PSD members and partners contribution all throughout our iterative, participatory way of working.
b. When selecting manuscripts to contribute to, for any given manuscript project started in OSF, potential co-authors can see potential papers for which they may already be the "team expert" based on prior work, and they can help get those out the door.
c. It also helps during the **write_analyze_edit** phase, for co-authors to determine how much specific writing for the manuscript they want to do, for any given co-authorship position.

- Other workgroups simply assigned percentages based on how they contributed to the specific **prior_work** categories recognized by ICJME & APA as "substantive scientific and intellectual contributions."
- And the workgroups decided what those major categories of work actually were.

This aligning with our process across all workgroups over the last 18 months or so of app development, right @staceypark and @dkngenda ?

**Comment by staceypark** [comment]
Yes, thanks that's right @lzim. 
FYI also @teampsdkathryn Jenn and I have been deleting the email addresses from your GItHub posts. But, please make sure to respond from GitHub instead of your email in the future so that other people's information does not get posted.

**Comment by lzim** [comment]
@dlounsbu's proposal basically makes sense to me, I've built on it below with my recommendations specific to **qual_workgroup.**

I've narrowed down to 3 **prior_work** categories. These categories of contributions are not about the **write and edit** part of **write_analyze_edit.**

**prior_work** - Work done on the team that will be reflected in authorship on that codebook [**yes, this should be broken up by codebook for qual**]. Most of the **qual_workgroup** primarily contributed to one of these categories _regardless of specific **write_analyze_edit** tasks a co-author takes on for a particular manuscript:
> * (30%) **Qualitative Design and Conceptualization** of qualitative/design procedures (includes framing of research questions, initial code book priorities and codebook development, and qualitative workgroup development).
> * (30%) **Qualitative Data Collection** includes organizing data collection activities (team meetings, note takers or interviewers, data cleaning and import, RQDA code setup and management for the team).
> * (30%) **Qualitative Coding and Code Operational Definitions** (includes application of codes to qualitative data, refinement of coding decision rules according to theory model via adjudication).

Then, this category fits in the **write_analyze_edit** section
> **Qualitative analysis or synthesis** (includes analysis/synthesis of coding according to research design, selection of exemplars to address research questions related to the theory model or framework)

> QUAL WORKGROUP MEMBERS/CONTRIBUTORS include:
> 
> * Kathryn
> * David
> * Lindsey
> * Swap
> * Jessilyn
> * Stacey

Yes, I believe this is our complete **qual_workgroup** to date.

**Comment by staceypark** [comment]
@lzim I'm wondering if we can finish the qual portions of this during the workgroup meeting tomorrow?
We still need your input on the most of the other categories however - i.e. co-i, vapor, models, etc.

**Comment by lzim** [comment]
@staceypark What’s the easiest way for me to get you what is needed?

**Comment by staceypark** [comment]
@lzim probably just editing my first comment on here directly to add in the people + weights

**Comment by lzim** [comment]
@staceypark 

I think we need a better way to do this, because we’re going to have to do this over and over, right?

**Comment by staceypark** [comment]
@lzim @dkngenda 
David and I discussed that we would need a new underlying system for the app so data can be created and stored through the app which David will look into. 

One thing we realized is that every category under a workgroup should be able to be weighted according to the paper written. Currently you can only weight the overall workgroup and whatever proportions you gave for the categories against each other within a workgroup cannot be adjusted, but the paper may not be written that way.

We believe this will definitely make the concept of the weight calculations easier too for folks since there will only be two weighting points instead of three: prior work vs. current writing and how much each category weighs in that prior work.

**Comment by staceypark** [comment]
@lzim 
@dkngenda and I met and clarified the updated logic we needed for the authorship app to make sure we had the same mental model. He is working on making those updates.

I am working on updating the Excel sheet for feeding the prior_work weights into the app based on this thread, before I hand it to you. **While we ultimately want a function in the app to be able to add new prior work items, we decided to triage that to a 2.0 version as the scope/time will not allow for our Wednesday deadline.**

We also hope to incorporate any user feedback on ease of use in the 2.0 version.
For now, we're trying to ensure the app is usable for assessing authorship accurately for our urgent papers.

**Comment by lzim** [comment]
Sounds good! Thanks @staceypark and @dkngenda

**Comment by staceypark** [comment]
@lzim updated CSV file here: https://osf.io/f5kh6/
I marked in red text the items that I need your help filling out or that I made some guesses on. 
You'll notice that we changed all the subcategories to have 100 points "possible", and the score is how much of that "100" pie is split between everyone who contributed to that subcategory.

@dkngenda is updating the app itself for folks to be able to weigh the subcategories for how much it will account for the prior_work. We realized this portion can't be part of the predetermined input, since we **do** know how much work folks did per item, but we **don't** know which and how much of the subcategories we will be talking about in any given paper.

**Comment by staceypark** [comment]
@dkngenda can you add an update on the development time based on the list two comments above that I added of the features we want in the 1.0 version

**Comment by dkngenda** [comment]
@staceypark This is my estimated time for for the new features of  1.0 version
Feature | Dev time | QA-dev time | QA -test time | Total required time
-- | -- | -- | -- | --
Add New subcategories | 4 | 2 | 1 | 7
Pie 1 | 2 | 1 | 1 | 4
Pie 2 | 2 | 1 | 1 | 4

**Comment by staceypark** [comment]
@dkngenda thanks for the updated estimates. Looks like it'll be ~15 hours total. Based on your other workflows, do you think it can be done by this by 2/10 or 2/17 (next two qual meetings)?

**Comment by dkngenda** [comment]
2/17 seams reasonable. Given that R01 might consume better part of my next two working days
