### ISSUE TITLE
Task Create R Linter

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1441]
**1. Description:** 
Create R Linter action to ensure that style guide #1440 is being followed.

**Comment by jamesmrollins** [comment]
@dkngenda here is a copy of our discussion notes from this afternoon:

In the absence of a user-persona, I asked David questions regarding him as an "R code" user:
 
1.  How would you characterize your comfort level, learning new things on a computer? Depending on the software - feels very comfortable picking up new things on the computer. Technically oriented.  Like to have instruction with new things, such as a link to training.
2.  Are you a MAC or PC user (or both)?  MAC user - able to use both.    
3. How familiar are you with GitHub? (Advanced, intermediate, basic)  Feels he is an intermediate user.  Though, would appreciate orientation to help find his way through new learning.
4. How would you characterize your expertise regarding R code?  Tidyverse? Feels he is an advanced user of R Code.  Very familiar with Tidyverse.   Tidyverse is a consolidated set of packages that provide a standard for R Code in terms of creating data frames and passing data through pipes. There are some packages other than Tidyverse, available on GitHub or CRAN that are more geared towards modeling and other statistical tasks   
5. Do you have any preferences with regard to R Linters? Likes to use LintR which supports TidyVerse standards.
6. What code editing tools do you like to use (i.e., Atom, RStudio IDE, Visual Studio)? He uses RStudio to edit code.  He points LintR to his code and tests "on-the-fly."
7. With whom would you collaborate regarding R coding and related development activities?  Are there other R users?  Would need to collaborate with Anthony, who either knows or is learning R.  The Qual and Quant workgroups will be interacting regarding R coding and SQL data issues. 
8. Do you clone your repository to your client?  Yes.  He makes changes on local computer then merges with upstream repositories using GitHub functions through the command line.  Can create branches through R Studio and pull updates. 

**Pain Points:**
1.  Would appreciate automation to handle branch creation, and merge, reviewer notifications and lintr and code testing.
2. If there is a way we can do the linter checks supported by Jim Hester LINTR program in a GitHub action - that would be a boon!

**Comment by jamesmrollins** [comment]
### Hypothesis

1.  A feature that provide an action to automatically create a feature branch for a code update, automatically open the pull request, and notify reviewers.

**Comment by anthonycpichardo** [comment]
@jamesmrollins these all look good. I would add that for Assumption 1, I wouldn't only use the command line. Both Github Desktop and Rstudio have git support through GUIs that I would use in some cases.

**Comment by jamesmrollins** [comment]
Thanks for staying up to review this @anthonycpichardo.  I will adjust the assumption to incorporate your feedback.  When we implement the action, it will take it cue from the commit.  So it really doesn't matter from what client or web based platform you use.

**Comment by dkngenda** [comment]
@jamesmrollins These look good to me also!

**Comment by lzim** [comment]
@jamesmrollins 

Cross-ref:
#1441
#1442
#1443

**FYI:**
@anthonycpichardo 
@anazariz 
@dkngenda 
@staceypark 

- **quant_workgroup** -  **R Notebook** (.rmd) SQL and R code can both be run.
from 8/6/2020 **Support Workgroup Leads"

**Team PSD GitHub Code review must be baked into our GitHub/ZenHub workflows.**
- R Notebook code annotations managed directly in GitHub or is managed in the R Studio IDE.
- sttm on R Shiny 

**User-Centered Hypotheses related to #1442**
How does the work on #1442 solve the painpoints of the PI related to embedding SQL and R code in the same R Notebook and managed on the relevant GitHub repository for code review and testing across our branching scheme and integrate with the ZenHub project management workflow? 

Week 1 - User-center hypotheses: Both the Statistician/Data Scientist & the Principal Investigator will most efficiently provide feedback on the code if it's integrated in an R Notebook that we can check in/out of GitHub and manage via ZenHub asynchronous.

@anazariz week 2 (MVP) - R Notebook prototype on the va/research and va/operation for getting to the bottom of the R21 that we can iteratively review as you go.

- Short, rapid cycles - CI/CD philosophy.
- daily small code reviews by 
	 
- **We'll prototype on Anthony's VA GH Enterprise Account.**

**Comment by jamesmrollins** [comment]
Hi @lijenn @branscombj @dlkibbe !  Below is a prototype workflow to help us visualize how we could use GitHub actions in our markdown file creation and editing process.

https://app.lucidchart.com/invitations/accept/5a66143a-2b90-4d78-8f13-cc9d319de998

**Comment by jamesmrollins** [comment]
Due to @anthonycpichardo having a full plate and the availability of lintr on client-side devices, this issue has been triaged into the October epic.  This was decided in the 9/28 Workgroup Leads meeting.

**Comment by anthonycpichardo** [comment]
@jamesmrollins I added a couple test files as requested.

I was also able to get the lintr action running without any errors. 

Exciting!

I think theres some parameters we'll need to play with to set the lintr definitions we want to use but its running which is great.

Appreciate the work you and your team have done

**Comment by jamesmrollins** [comment]
Thanks @anthonycpichardo, that's is great news.
