### ISSUE TITLE
Task SQL Linter Action

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1442]
1. Description:
Create SQL Linter action to ensure that style guide #1440 is being followed.

**Comment by jamesmrollins** [comment]
@anazariz @anthonycpichardo @dkngenda    @hirenp-waferwire FYI

Below is a summary of a discussion regarding pain points associated with _protecting_ and managing SQL and related data:

1.  There are only production databases.  There are no concurrent DEV or TEST environment databases.  Therefore, it is impossible to test scripts and other SQL objects on other than a production database as there is currently no way to simulate a database in GitHub to conduct SQL script testing.  This must be done "by hand" in the production database.
2.  However, GitHub can manage branches, reviewer notifications, monitoring and automatic script naming and deployment of scripts to a location on the enterprise SQL system.  This may have to be done using a Secure File Transfer Protocol (SFTP) or a direct GitHub deployment if possible.  
3.  There is a vulnerability when revising SQL objects using pure CI/CD methodology.  For example, if a user pulls a query script from GitHub and it is saved to the enterprise SQL directory, it could overwrite a current production script prior to being adequately tested.  We will need a workaround to emulate a CI/CD process.
4. There are various locations for SQL scripts on the TeamPSD shared drive.  These must be consolidated on GitHub.

**Comment by jamesmrollins** [comment]
@anazariz @anthonycpichardo @dkngenda @hirenp-waferwire FYI

Below are some hypothesis which may help the pain points listed above:

### Hypothesis 

1. Desires an action that manages branch creation, reviewer notifications, file protection/naming, and deployment of scripts from GitHub to SQL Enterprise system.
2.  Desires an action that names an SQL script file with a _TEST extension, when merging a Feature branch with a QA branch, and deploys the file to the appropriate location in the SQL Enterprise system.  The Pull Request triggers a reviewer notification, that a test is necessary using the updated script.  Upon completion of the script, reviewer indicates favorable/unfavorable results in Pull Request.
3.  Desires an action to merge QA branch with Master.  The action renames the _TEST to a PROD file by removing the _TEST extension and deploys to the SQL Enterprise system.   

### Assumptions
From review of end_to_end_data_visibility_data_engineer and fast_learner_need_for_transparency_data_analyst
1.  Sees the lack of automated data workflows and templates as obstacles to role.
2.  Desires a method of alerting downstream consumers of changes and an effective means to measure the impact of the process change.
3. Desires a way to use GitHub to manage code reviews, reject or accept changes, and keep track of work. 
4.  Very concerned about inadvertently overwriting a script file that would damage a table. Desires a means to "mistake-proof" the SQL change process. 
4.  Users are willing to transfer actions to the enterprise GitHub, as the _Praxis team does not have this level of access inside the domain._

**Comment by anazariz** [comment]
## Database CD/CD

**Architecture**

As we have access to a single database (per production or each research project), our CD/CD processes must create a virtual dev/test/prod environment using a single database. One way to achieve this is shown below. Each **Major Area** is discussed below.  

![image](https://user-images.githubusercontent.com/39805164/89331129-1a913480-d646-11ea-8d88-73b6e244e592.png)

**Major Areas**
 - [ ] Database
 - [x] Objects
 - [x] Data

**Database**
As our databases are built/maintained by the VA DBA (DataBase Administration) team, there are no actionable items here.  

Note - a copy of the database build script may be extracted and checked into GitHub for future reference only. 

**Objects**
Each database may contain the following objects:

 - Tables
 - Indexes
 - Views
 - Programmability
 - Scripts (on the filesystem)

**Initial**
To create a baseline, the create scripts for all database objects  as well as all filesystem scripts should be extracted (database objects only) and checked into VA GitHub via the on-premise Git. 

**After Initial** 
Only the objects impacted per each project should be checked out of GitHub via Git. Changed objects should be checked back into GitHub using Git after testing. 

Regression and Integration testing is needed to insure that the object changes do not inadvertently break processes or other objects (such as table changes breaking views). 

**Data**
Data backup is necessary if the structure of a table or its contents are changed. Also, depending on the nature of the change to a table structure, table data can become corrupted or lost when the underlying table structure is changed. In addition to regular database backups (performed by the DBA), table content must be backed up **TWICE** (see diagram above).  A table can be backed up using one of the following methods:

1. BCP (Bulk Copy Program)
2. Generate  **Table**  Script with data
3. Make a copy of  **table**  using SELECT INTO
4. SAVE  **Table**  Data Directly in a Flat file
5. **Export**  Data using SSIS to any destination

If a table is based on the CDW data, the benefits of a back-up versus a rebuild using CDW must be determined. Testing of the table content must be performed using record count, hash procedures or other methods to make sure that before and after contents match.

**Comment by jamesmrollins** [comment]
-  Need more bridging between users' pain points and what is proposed above.
-  Need to integrate R workflows with SQL dependencies and visa versa
-  Would be good to describe the review process, perhaps with a mtl workflow diagram (algorithm).

**Comment by anthonycpichardo** [comment]
@jamesmrollins Your assumptions and hypothesis above reflect my pain points. I believe your assumptions all hold true for me. 

Side note: It would also be great for the linters or other actions to perform analysis on the code for security vulnerabilities. This would be something that would be useful throughout our codebase. Especially places with external users.

**Comment by jamesmrollins** [comment]
Thanks @anthonycpichardo for your feedback.  With regard to vulnerabilities, it would be good to investigate what actions are available (there will likely be a few) and decide which we will implement.

**Comment by jamesmrollins** [comment]
@anazariz @anthonycpichardo  my DEV team  @hirenp-waferwire would like to meet with you to discuss this action.  There are several concerns they have where they would appreciate direct access to you as SMEs.  They are 13.5 hours ahead, but are willing to meet at a time convenient for us - perhaps first thing in the morning?

**Comment by staceypark** [comment]
@lzim user feedback from 8/6 sim_ui meeting:
This Linter should consider both R & SQL. We've learned over the past 3 months that these need to be considered jointly rather than a laser focus on one or the other.

A meeting between TeamPSD quant team + James' dev team may be useful. Be sure to include all of Lindsey, David N., Ash, Anthony, and Stacey.

We should also consult with Jodie's team on this work, as they are also automating their data workflow, with Susannah Martins and Cora Bernard.

**Comment by jamesmrollins** [comment]
Based on decision at Workgroup Leads meeting 9/28, this issue has been triaged to October epic.
