### ISSUE TITLE
TASK Test Coverage and Execution platform

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1443]
Assess platforms to execute test cases and view code coverage of our R, SQL, and MD files.

Needs:
- To be Developed-

**Comment by anthonycpichardo** [comment]
Anthony's needs for this are :
- a platform and workflow that will allow users to execute their test cases and view results/logs.
- test coverage both at the project and repository levels
- tests are run automatically based on triggers (push, merge, etc.)

**Comment by jamesmrollins** [comment]
Hi @anthonycpichardo -  Were you able to find the appropriate libraries that would enable this action to run?  Thanks, James

**Comment by jamesmrollins** [comment]
Record of conversation with @anthonycpichardo regarding final steps for this issue and #1441 .  These actions are complete and in the anthonypichardo/research_demo forked repository.  Final steps are:

**@anthonycpichardo will:**
1.  Check out the test coverage libraries and configure yaml test coverage action file to use these.
2.  Merge the /research_demo repo with the lzim/research_demo when ready (preferrably NLT Friday, Oct 30)

**@jamesmrollins will:**
1.  Complete the feature branch/QA branch standing operating procedures and coordinate with @staceypark and @lijenn.
2.  Execution of actions will occur with the push to a feature branch, with a pull request to QA, and a pull request to Master.
