### ISSUE TITLE
CD for Splash Page Updates 

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1444]
Automated deployment of the splash page updates monthly.

**Comment by lzim** [comment]
@anthonycpichardo & @anazariz 

Did we ever hit "automation" for this task?  

Just combing through open issues and trying to assess the status.

Thanks!

**Comment by staceypark** [comment]
@anthonycpichardo @anazariz ?

> @anthonycpichardo & @anazariz
> 
> Did we ever hit "automation" for this task?
> 
> Just combing through open issues and trying to assess the status.
> 
> Thanks!

**Comment by anthonycpichardo** [comment]
We did not no.

This issue was in the backlog, forgot to remove the milestone/epic.

**Comment by lzim** [comment]
@anthonycpichardo  

I see this is a big estimate, it may be worthing lookin at **dec_epic** for some of this, as automation could potentially become very helpful.
