### ISSUE TITLE
July 7/20 Task: EES LucidMeetings Training Facilitators

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1445]
Look through LucidMeetings for meetings where EES Facilitator Training was discussed with Fawn. 
(edit: Seems like the previous EES lead for this Casey unless it changed to Fawn)

Title | Date | Meeting Link
-- | -- | --
EES MTL Facilitate meeting   with Casey | Nov. 7 2019 | https://meet.lucidmeetings.com/meeting/229539
EES & MTL   FY20 | Oct. 3 2019 | https://meet.lucidmeetings.com/meeting/228596
MTL Facilitate EES   updates | May 29 2019 | https://meet.lucidmeetings.com/meeting/217027
MTL Launch   Workgroup - EES | Mar. 14 2019 | https://meet.lucidmeetings.com/meeting/209087
MTL Launch Workgroup - EES | Feb. 28 2019 | https://meet.lucidmeetings.com/meeting/209078
  |   |

**Comment by lzim** [comment]
Hi @lijenn 

We want to plan QIIC communications about the week 3 MVP user testing.
Let's try to get this to Kelly by COB Monday.

FYI: @branscombj  and @dlkibbe 

Happy Friday!! 🏖️

**Comment by lijenn** [comment]
@lzim @staceypark I've updated the list of lucid meetings in the top card, let me know what else I can help with.
Thank you! :relaxed:
