### ISSUE TITLE
apr_epic story 1: Document NDS Approval Process

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1449]
Document Process once badge is received, the...
	NDS request/approve for the individual team member Lindsey approves, then the additional entity.
	NDS also approves team resources like our CDW workgroups, but Lindsey also approves all of these.

**Comment by lzim** [comment]
We need to do this for @dkngenda, Cindy & Tanya.

We have an email for this, and it should probably stay internal to Team PSD folder and email, not in the Team PSD manual.

FYI HQ:
@anthonycpichardo 
@staceypark 
@lijenn

**Comment by dkngenda** [comment]
NDS approval process:

Request Operations Access here: http://vaww.vhadataportal.med.va.gov/DataAccess/HealthcareOperationsRequestProcess.aspx#SubmitRequest


1.	Make sure VHA NDS Access Form for Health Operations  is selected at the Select Document box.
-	Click Create Document
![image.png](https://images.zenhubusercontent.com/5f0224f96b89aaab469e0290/9d8f7368-1757-444c-bb58-d26565654e91)
 

2.	In Explorer go to: https://epas.r02.med.va.gov/docedit.cfm
-	It will read your PIV information for you, then select:
-	Employee Agency: Veterans Health Administration
-	Employee Type: VA Employee (yes, for all of you, none of your are “contractors”)
-	Station Number: 640 VA Palo Alto Health Care system (for everyone, but the QIICs, who should choose their own station)
-	Supervisor: Zimmerman, lindsey (for everyone, but the QIICs, can use myself as the supervisor for this access, or use Cliff – Cliff or I will receive an email and need to approve the request)
-	Purpose of Use: Healthcare Operations

![image.png](https://images.zenhubusercontent.com/5f0224f96b89aaab469e0290/67b4bc16-9b8b-4a12-89d4-03a7f56677ad)
 

3.	Scroll Down, and select:
-	Data Sources: Corporate Data Warehouse (CDW)
-	Duration of Access: I will need access during the duration of my position.
-	Affirmation: check this
-	Save and Submit

 ![image.png](https://images.zenhubusercontent.com/5f0224f96b89aaab469e0290/5b2270bb-0994-4c7a-afa7-0043263e98ac)

4.	Select CDW SQL Datasets and the menu below will appear.
5.	
 ![image.png](https://images.zenhubusercontent.com/5f0224f96b89aaab469e0290/510dee47-ddd0-4879-8cea-56f5e694eefb)

6.	Select, 
-	Basic Read Access (CDW_Full)
-	Privileged Read patient Access (CDW_SPatient)
-	Staff Real SSN Access (CDW_SStaff)
-	MCA (DSS) Access (CDW_DSS)
-	Outpatient SQL Files (CDW_SE_IE_SF)
-	Then click Save and Submit.
![image.png](https://images.zenhubusercontent.com/5f0224f96b89aaab469e0290/3524a86e-abda-4a2a-8fd4-2127fa9a374f)

**Comment by lzim** [comment]
@staceypark @dkngenda 

There is an awful lot of my PII on this post from David above. 
Should this be tracked somewhere else?

For example, in our VA Operations GitHub repo or the Team PSD folder?

**Comment by dkngenda** [comment]
@lzim @staceypark 

I have removed the post. I can repost it on VA operations Github if that's okay

**Comment by lzim** [comment]
Great, thanks @dkngenda
Since you've reposted on VA Operations GitHub, I'm going to close this card.
I sent it to Jeff via email for Story 13 Power BI
