### ISSUE TITLE
wk3: Markdown Linter Action + Features (Facilitate MVP w/ #648 SP)

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1450]
**User-centered hypothesis:** The workflow orients these users to how to contribute a .md file to the repo.
 
- MVP (will test whether they can do this on their own):
.MD formatting with the linter folded in the branching strategy in front of 
 Next user group: Jane and Debbie, David N.
 
Need to get the MVPs in front of a larger group of users still in july_epic if we hope to set up tests in august_epic.

- SAY guide #648 SP Floors edits (session 5 Team Data Table - add the exclamation).

- Linter: Make it fail and make it pass as the way to train.
Needs: *Develop a list of needs for the linter:**
"Check for broken links"
"Check the font/style"
- Refactoring - Changing the inside of the code to improve the outside of it.
Refactoring Example for the Markdown file:
e.g., Compressing the file size for all the .gifs in the SEE and SAY guides.
e.g., "Team" Module instead of "Aggregate" - Need to figure out a solution for this level of change. Meta-data?

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire .  Please see below for protected branch, status and actions needed for the repository located here [jamesmrollins/mtl](https://github.com/jamesmrollins/mtl).  **Please note this a forked repository that is connected to lzim/mtl. Use care when merging branches.**

### Please provide the following:

**Background:**  We are using a multiple feature, standard branch topology for managing branch structures in GitHub.  See [Git Branching Strategy](https://medium.com/@sairamkrish/git-branching-strategy-for-true-continuous-delivery-eade4435b57e). 

**Use Case:**  When a user updates a .md file in the repository and then creates a branch using the word "feature." it will create a protected branch that requires reviewers.  

**Requirements:**
1.  The reviewers will be jamesmrollins and lijenn.
2.  When the branch is merged to the QA branch, it will trigger three test actions.
  a. [markdown linter](https://github.com/DavidAnson/vscode-markdownlint )
  b. [link checker](https://github.com/marketplace/actions/my-markdown-link-checker)
  c. [spell checker](https://github.com/streetsidesoftware/cspell)
3. Set up a test status check object in the readme.md in the root directory.  If possible, reporting by action would be desireable.  See [GitHub Marketplace](https://github.com/marketplace/actions/github-status-action) for more information.

![image](https://user-images.githubusercontent.com/30132017/88590906-586fd680-d010-11ea-8e88-6d2e06fe9cab.png)

**Comment by lijenn** [comment]
Hi @branscombj @dlkibbe @dkngenda!

Please help @jamesmrollins and I expand the current list of needs for editing/adding to markdown files:
1. "Check for broken links"
2. "Spell Check for typos"
3. "Check the font/style"
4. Refactoring (Changing "Aggregate Module" into "Team Module")

Some questions to help guide you while thinking of your wishlist/needs that could be automated:
Note: Don't worry about the technology that would be able to do it! Just list out needs that you would like to be solved through automation :)
- What else are you currently doing via brute force and unable to do with a keystroke?
- Do you know where to even begin looking if you were told to make an edit in a SEE/SAY guide or .markdown file in general? 
(How would you have known it was SAY Guide Session 5 to make #648 edits in?)
- What would you need to know before diving into the task (what prerequisites must you do in order to edit/add to a markdown file)?
- Is there a check-list (existing or self-created) that you refer to make sure you got all the edits in a guide before making a pull request/requesting reviewers?

**Comment by branscombj** [comment]
@lijenn @jamesmrollins @dkngenda @dlkibbe 

5. Measurement Based Stepped Care and Suicide Prevention [**and**, not **for**] is one specific instance.
6. It would be great for the linter to check that we use exactly the same verbiage to both name and describe a whole long list of terms (team challenge/priority): variables, resources (including "resources" itself - do we sometimes say "tools"?), concepts (systems thinking, feedback/feedback loops), metaphors and similes (traffic on the highway or touching a hot stove).

I wonder if we could painstakingly proof-read specific files and designate them as prototypes; send the linter to find terms, phrases, abbreviations, etc that are almost but not exactly the same in style, punctuation, spelling or wording. As we go through flagged items and disposition them, we teach the linter, and it replicates that decision through all other instances of that item it has pulled, so the flagged list ahead of us gets shorter as we go. Does this make sense?

**Comment by dlkibbe** [comment]
@lijenn @branscombj @jamesmrollins 
Tried to answer Jenn's questions below:

**1. What else are you currently doing via brute force and unable to do with a keystroke?**

-Uniformity in formatting - bullets vs. numbers; bold vs. italic vs. regular font; indents, spacing
-Updating the header (date & name updated when changes are made to a file) - I think you've already discussed the format and process for maintaining YAML headers, just not sure it can be automatic.
-Italicizing _Modeling to Learn_ and _MTL_ (I think we got all these but maybe not)
-Uniformity in phrasing and formatting between see guides and say guides to ensure facilitators can easily guide learners to specific segments of the session agenda 
- There are different formats to indicate a blank to be filled in sometimes in the same file. Some are just plain underlines _______ and others have brackets, e.g., "Your team's vision was about [ __]. Let's go to the [__ ] viz tab."
- Special formatting is needed for words that facilitators will actually say during sessions vs. descriptive or guiding text. We need to figure out how to set the script text apart. For example, text from MTL Red Part 1 Say guide appears in different font sizes and bold (section headings are also in bold that is not script): "Let's get started" or "Who would like to "drive" today?" followed by plain text '[Recommend the Team Lead]" ... it would also be helpful to have a separate look for reminder messages in the say guides like "Keep an eye on time." (not sure if it is possible to do this type of thing automatically). Let me know if this comment doesn't make sense.
- In WORD you can create the formatting to do a mail merge from a data set or table to a form or letter, e.g., certain titled cells will populate a form letter for example. Is there any way to do a merge of the team's vision, VISN, team's facility, team lead name, etc into the SAY files in advance of a team's sessions? This may help the QIICs especially.

**2. Do you know where to even begin looking if you were told to make an edit in a SEE/SAY guide or .markdown file in general? (How would you have known it was SAY Guide Session 5 to make #648 edits in?)**   

      With regard to the first question: Yes, working with Stacey, we've edited all of the versions of the see and say and guides on GitHub using markdown formatting.  There has been confusion about which version was most "up to date" -- mtl.how or lzim/teampsd -- so we started changing the dates in the YAML headers. With regard to question 2, I'm not sure what you're asking exactly - we typically would do a pull request, making specific edits to see and say files based on a review and feedback process (for example, after the QIICs training event), and then push them back to the master branch. 

**3. What would you need to know before diving into the task (what prerequisites must you do in order to edit/add to a markdown file)?**
  deadline for completion; who to tag in the github post that will review the edited files; whether the edits are for see guides, say guides, other MTL files or all of the files. I would like to know the uniform set of edits that are required; that is, what is the set of edits that need to be made in all of the files and what are they vs. those that are specific to one say or see guide or session 2 and 3 only vs. 4th-12th sessions.

4. What would make your life easier to add/create guides based on COVID-19 adaptations?
If we had a list of the guides that need to be created for COVID-19 or specific COVID-19-related adjustments that are required to existing guides.

5.  Is there a check-list (existing or self-created) that you refer to make sure you got all the edits in a guide before making a pull request/requesting reviewers?
  - I don't have a checklist. I would finish the required edits on session files for 1, 2, 3, and 4 in word using track changes and then apply the common edits across all the subsequent files

**Comment by branscombj** [comment]
@dlkibbe @lijenn @lzim 
I especially love this suggestion for tailoring team-specific guides or checklists for co-facilitators prior to each session!

> Is there any way to do a merge of the team's vision, VISN, team's facility, team lead name, etc into the SAY files [or checklist - whatever we are calling what we actually use as our facilitation guide?] in advance of a team's sessions? This may help the QIICs especially.

**Comment by jamesmrollins** [comment]
@branscombj @dkibbe and @lijenn **(FYI** @hirenp-waferwire)  Below are my hypothesis of features you would like, if possible, to help automate your editing tasks.

### Hypothesis

1.  A feature that would ensure the correct spelling, and the correct and consistent use of words and word phrases across all documents in a given repository in accordance with a given glossary of terms.

2.  A feature that would employ learning technology that would keep the linter up-to-date with the nuances and rules used by editors to maintain document format and style.

3.  A feature that would check for uniformity of formats and use of style elements such as bullets and numbering (when to use and where to use in the document), use of boldface and italics, use of blanks versus braces, use of underlines, use of indents and spacing, and specialty formats for a given purpose (such as a text format, like italics, that indicates a facilitator script).  

4.  A feature that would automatically update the YAML header information after a document update cycle is completed.

5. A feature that would merge team information into a given Say file prior to a session. 

6.  A workflow or action, that would help the editor manage the task; such as, communicating the deadline, identifying needed reviewers, identifying the edits needed, communicating an index of dependent documents that need to be reviewed, and opening required branches and pull requests.

### Assumptions
_From systems_thinker_ambassador_translator and learner_centered_facilitator_

1.  Users would prefer using platforms they already know how to use - versus having to learn something new.
2.  The features should identify other interdependent teammates who may have a contribution to make to the task.
3.  Features should reduce or at least not add burden to communications and should help user manage tasks.
4.  Features should reduce rework, improve workflow and improve efficiency.
5.  Features should improve the user's ability to find information specific to the task at hand.

**Comment by branscombj** [comment]
@jamesmrollins That looks like it captures it to me!
@dlkibbe @lijenn Do you see anything he missed?

**Comment by lijenn** [comment]
@jamesmrollins This may be difficult to find, but a **feature or GH Action to compress .gif and/or image files within markdown files without reducing the quality** (Use case: #1150)

Not directly related to Facilitate, but the feature may still be helpful if it exists:
**Feature or GitHub Action that can convert pdfs or powerpoint files into a markdown file?** 
This could be useful for a Bookdown Manual format (e.g the #1192 Team PSD or MTL Manual). 
Ash found [this](https://github.com/ssine/pptx2md) but I tried it and it couldn't get it to install on my laptop. 
And having a **broken link checker for markdown files** would still be appreciated, if possible.

Other than that, I think you got caught it all!
Thank you Debbie, Jane, and James!

**Comment by jamesmrollins** [comment]
@branscombj @lijenn @dlkibbe I added Jenn's requests to the main hypothesis thread above.  Thanks, James

**Comment by dlkibbe** [comment]
@jamesmrollins @branscombj @lijenn 

Three other things come to mind:
1. Will the see and say (and possibly other) files contain hyperlinks to cheat sheets? If so, we want to be sure the language int he cheat sheet matches that of the directions in the say file.
2. Sessions say guides and say guide checklists were created. Is there anyway to review them "automatically" so that if we update a say guide the checklist will also update? (This assumes that the headers or key actions in each file match for facilitator friendliness which I'm not sure is the case).
3. Acronyms & abbreviations - This is really included in James list above but thinking about the need for uniformity in the appearance of acronyms and abbreviations throughout the learning sessions such as q/h/f/d and Complex, Feedback, Behavior, Time (CFBT) or C.F.B.T. and experiment 1 vs. exp 1. Maybe a hyperlink after the first appearance of qhfd or cfbt so the learner can click and see what the acronym stands for.

**Comment by jamesmrollins** [comment]
@branscombj @lijenn @dlkibbe I added item 2 from Debbie's list to the Hypothesis above.  I didn't add 1 or 3 as it may already be covered in the hypothesis.  However, they both may be useful tests of the hypothesis once we get to the MVP.

**Comment by jamesmrollins** [comment]
@lijenn do you have a specific set of rules you want to use for the Markdown linter?  We are attempting to adjust the configuration of the linter, but wanted to know if there is a rule base we could use to check it out.

Thanks, James

**Comment by lijenn** [comment]
@jamesmrollins We had a list of potential rules documented [here in 1364](https://github.com/lzim/teampsd/issues/1364#issuecomment-652530030) from the linter, [Markdownlint by David Anson,](https://github.com/DavidAnson/markdownlint) I got to work back in May.

**Problem:** I think we may have some nuances based on the different types of needs for the markdown linter due to differing style guide needs for training documents, see/say guide or MTL, & bookdown format nuances, etc.

**Need:** I'm wondering if there is a linter or existing feature that could allow us to insert a pre-existing markdown template/create markdown templates (**can we insert a set or sets of custom made rules, not just have pre-built rules like we have for the Markdownlint?**). 

**Possible suggestions for linters**: I just found this linter from David Anson's Markdownlint repository which I linked earlier, and [this super linter](https://github.com/github/super-linter) seems to be a combination or support various types of linter (including Markdownlint), but has the ability to make [custom rules](https://github.com/github/super-linter#template-rules-files). 

**DEV Team could try to work out:**
- Super-linter for the custom rules confirguration and Markdownlint/other various linter support
- The existing custom rules configuration for Markdownlint (may only be available in the Visual Studio Code editor, but I am not sure)
- Remark-lint was another popular markdown linter that came up during my researching, but I am unsure of it's capabilities as I didn't explore it enough.

The reason I originally chose Markdownlint was because I recall seeing a function that if you used Markdownlint on the Visual Studio Code editor, you could set custom made rules to run markdown files against, but I couldn't figure out how to make it work or even know if it'd work on GitHub, since it was originally made for Visual Studio Code. So we had to settle for the existing built-in rules in Markdownlint, which may not address all our unique needs. 

Hope this helped!
Thank you, James!

**Comment by staceypark** [comment]
@lzim user feedback:
It is important to use strategies and tools that will scale and last without need for high level dev maintenance long term. Not that we don't want to specify our specific rules/needs, but we don't want to use strategies that are niche.

**Comment by jamesmrollins** [comment]
Hi @branscombj @dlkibbe @lijenn!  Below is a visual prototype to help us see an editing process that uses GitHub CI/CD actions.  Your feedback is encouraged.  Thanks James.

[Lucidchart](https://app.lucidchart.com/invitations/accept/b5954dba-ac47-40ba-8a42-499fa471b91d)

**Comment by lijenn** [comment]
Hi @branscombj @dlkibbe! Please let us know if you have any issues understanding the MVP Lucidcharts map that James produced to show the process of the Markdown Linter and how it would work on lzim/mtl. 

I know Jane will not be with us at tomorrow's Facilitate Workgroup meeting so let's see if we can address and immediate concerns asynchronously before we meet with Debbie tomorrow so we're better oriented:
- Are there **terms** and **language** that need to be **defined**?
- Does the process make sense in **flow** (directionality of the map, horizontally and vertically)? 
- What seems **new** in the process compared to the old way of editing markdown files?
   - **Does it address/solve the pain points you've mentioned** (Note: Not all pain point addressed at the moment since James is still working with DEV to incorporate all of our asks/needs)?

**Comment by branscombj** [comment]
Hi @lijenn - I have reviewed @jamesmrollins 's flowchart. I might need some spoon-feeding to get it and be able to answer your questions. @dlkibbe If it's clearer to you, go for it!

As an aside, I experience a funky process trying to open the Lucidchart. The link takes me to a Create and Account page, which I have to get kicked through to find a Login page. Not a big deal for me, but could be for other users, e.g. QIICs, if we're usingLucidCharts in this way with them.

**Comment by lijenn** [comment]
Thanks @branscombj! If that's the case, I'll see if I can simplify/redefine parts of the process's flow and language for it to look more clear and relevant to you and Debbie, probably by tying it back in with #648 at the least.

And thanks for notice about Lucidcharts! I'll keep this mind when we get the documentation up.
Please let me know if you both need the Team PSD login for it since you'll be able to see all of the team's flow maps and charts :) Might be easier to stay logged in on the Team account too.

**Comment by dlkibbe** [comment]
@lijenn can you re-send me an invitation to Lucid charts or was I supposed to use LZ's log-in?
![image](https://user-images.githubusercontent.com/31182258/89843041-61e75b80-db45-11ea-8b06-2943c6204cc3.png)

**Comment by lijenn** [comment]
@dlkibbe I've re-updated the link to not require an invitation, please sign in with LZ's log-in :)

**Comment by lijenn** [comment]
From SIM UI 9/24: @staceypark @lzim @jamesmrollins #648 
James updated that:
- the find-and-replace action is not working at all, troubleshooted for 12 hrs
- other find-and-replace actions on GH use the same code base & original code base owner does not have time to fix issues
- Recommend that we teach everyone Atom to do find-and-replace function from local client
- May reach out to a devops to see how we could develop our own custom ci workflow on GH

**Comment by jamesmrollins** [comment]
Hi @lijenn , @branscombj and @dlkibbe.  Looks like we got the Find and Replace action working!  We have loaded in on the [test MTL repository](https://github.com/jamesmrollins/mtl---TEST) for your verification.  If you are satisfied, then we can load directly on the lzim/MTL repository.  In general, the md linter actions, spell and link checkinig are triggered by the word "Feature."  And the find and replace action is triggered by the word "FnR."  We separated these actions as we didn't think you would want to "find and replace" each commit, but only use for a specific FnR task.  Although the FnR action does count the number of replacements, it does NOT list out the where replacements are made; however, prior to a merge a reviewer could look for the changes using git.  

### Instructions:
  **1. Regarding "Find and Replace" Action**: This action is triggered when creating a branch using the specific name format "FnR-AnyCharchater." (for example, FnR-feature1, FnR-feature2, FnR-xyz) or when committing to that branch. 

  **2. Currently, this action has a value parameter, "hello" and "world" to find and replace."** See the below image as a reference. You can change that "find and replace" value parameters with the file at this [file location](https://github.com/jamesmrollins/mtl---TEST/blob/master/.github/workflows/FindReplace.yml.)  You can target a file, directory of files or the whole repository.

![fnr parameters](https://user-images.githubusercontent.com/30132017/95250627-37292480-07cf-11eb-8a1e-f3b014f447f6.png)

  **3. Regarding "Markdown Lint" Action:** This action is triggered when creating a branch with a specific name format "Feature-AnyCharchater" i.e. (Feature-1, Feature-2, Feature-xyz), or commit to that branch.

Let me know what you think.  James

**Comment by jamesmrollins** [comment]
@hirenp-waferwire 


I added words to the list in the cspellcdict.txt dictionary and the action returned an error:

![image](https://user-images.githubusercontent.com/30132017/100158602-4c324380-2e61-11eb-863e-461bec40b3df.png)

 
Why is the markdown linter executing rules 13 and 41?  These are not called out for execution in the markdown.json.  

![image](https://user-images.githubusercontent.com/30132017/100158315-d29a5580-2e60-11eb-8236-ffdd71cf3274.png)

![image](https://user-images.githubusercontent.com/30132017/100159668-08403e00-2e63-11eb-9d25-c3769a5b62aa.png)


Can you remind me if the Actionchecker action can refine the file review to just the changed file, or must it check all files in a directory? Do I just comment out the getDirName instruction?

![image](https://user-images.githubusercontent.com/30132017/100159812-48072580-2e63-11eb-9985-df0cb82ab65a.png)


Thanks, James

**Comment by jamesmrollins** [comment]
#648 is blocking this issue.  At Workgroup Leads meeting 11/30, decided this issue shall be closed and #648 moved to January Epic.  @jamesmrollins will open a separate related issue to clean up all the MTL Repository .md files.
