### ISSUE TITLE
BUG - Stock values and Rate dial values do not zoom when the text does 

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#1451]
Uneven font size when +/- to zoom in/out.<br/><br/><br/><br/><br/>![image](https://s3.amazonaws.com/epicenter-asset/production/va/va-psd-sim/1595875664952621432_img0.png) <br/>

**Comment by jamesmrollins** [comment]
Hi @lzim.  I have some follow up questions:

1.  What resolution is your screen set to?
2.  What steps did you follow to create the conditions above, specifically:
 - From full-screen mode, did you start zooming in? or
 - From a window mode, did you start zooming in?
 - At what zoom where you at when this occurred?

Perhaps we can share a screen at the next team meeting.

**Comment by lzim** [comment]
@jamesmrollins I can't answer all your questions right now due to our deadline. But, it's interesting I posted this bug back in July because @staceypark and @branscombj observed these behaviors in pretty extreme ways yesterday that probably wouldn't be very confidence inspiring for our end users.

Until I can provide more information, however, the short answer is that it is definitely related to zooming in/out. But, perhaps most importantly even trying to get the browser resolution back to 100% wasn't sufficient to "reset" to even font size across the Sim UI. I had to log out and back in to resolve. That's all I can help with right now.

Here's what I see in System Preferences for my screen resolution:
![Screen Shot 2020-11-05 at 2 48 30 PM](https://user-images.githubusercontent.com/7454688/98305067-fe1ed400-1f75-11eb-9170-ba71caa62721.png)


We can follow-up on this later on, however. Thanks!

**Comment by lzim** [comment]
@jamesmrollins 

I saw this open issue and tested again from my VA PC laptop, whereas earlier observations were on Mac.
It is very easy for me to reproduce the zooming inconsistencies in Chrome again using the magnifying glass in the browser url bar.

**1. Replication of the inconsistencies in zooming in/out (e.g., Stock values and Rate dial values do not zoom when the text does.**
<img width="595" alt="zoom_inconsistency" src="https://user-images.githubusercontent.com/7454688/104364121-01c95c80-54cb-11eb-824d-810a4d86b239.PNG">

**2. Inspector Console** 
<img width="414" alt="inspector_console" src="https://user-images.githubusercontent.com/7454688/104364249-350beb80-54cb-11eb-814d-cc99707b414f.PNG">
