### ISSUE TITLE
8/31 Task: CRM Initial Work - Placeholder 

### ISSUE THREAD

**Issue by anazariz** [lzim/teampsd#1457]
This is a placeholder for the initial work on feature #1299 (CRM Implementation). Currently the amount of work needed is not  known. Additional Task tickets will be created as the amount of work is better understood.

**Comment by anthonycpichardo** [comment]
Special forces team has COVID constraints and has put this project on hold. Moving to icebox

**Comment by staceypark** [comment]
#1299 addresses CRM. Closing this
