### ISSUE TITLE
TBD mtl.how/team photo management

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1460]
### Check off requirements to verify progress through feature_tracker.
- [ ] 1. **DEFINE in work_breakdown**
  - [ ] a. Add photo management system in Epicenter admin for mtl.how/team in the same section that we currently update our bios in. Currently, James is the only person managing the photos to adhere to the needs of the system. We would like an automatic system (think like Facebook or Instagram) similar to what we use at mtl.how/sim for any TeamPSD HQ member to manage photos here.

  - [ ] b. **date & who** -  **Will Verify** requirement definitions **at 8/6 Sim UI meeting**
  
  Task Cards:
  #
---
- [ ] 2. **DESIGN** in **operations_to_do** and **research_to_do**
  - [ ] a. **what & why** - **_MVP_ of design** of requirements in a **algorithm map, wireframes or design** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** design **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 3. **DEVELOP** in **under_development** - "frozen"

  Task Cards:
  #
---
- [ ] 4. **TEST in functional_test**
  - [ ] a. **what & why** - **TEST requirements** using **testing_checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** via TEST **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 5. **PROD in done**
  - [ ] a. **what & why** - **_DOCUMENT_ feature** using **document_tracker** for the **5 D's.** 
  - [ ] b. **date & who** -  **DELEGATE**
    - [ ] **describe_learners** [Jenn & Rita]
    - [ ] **detail_facilitators** [Jane & Debbie]
    - [ ] **document_team** [Anthony]
    - [ ] **disseminate_scientists_va** [Anthony]
    - [ ] **depend_products** [hq & ees]
  
  Task Cards:
  #
---
- [ ] 6. **closed** - fully documented, trained and ready for the next release.

**Comment by jamesmrollins** [comment]
Hi @staceypark :  I have already documented this in #1246.  Can we use that or at least reference it here?

**Comment by staceypark** [comment]
closing since duplicated in #1246.
