### ISSUE TITLE
wk3 aug_epic: Say Guide BUG: missing image in blue 02 say file

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#1469]
**1. Add description:** 
There is an icon missing or broken link to an image file in the "Done" at the top of the [S02 say file for Blue](https://github.com/lzim/mtl/blob/master/blue/session02/s02_facilitator/mtl_session02_say.md):

<< Paste screenshots here>>
 
**2. Click on the right:**  
i. **Pipelines** - prioritize in a TeamPSD (& Workgroup) pipeline  
ii. **Assignee** - assign to an individual team member producing work for the issue  
iii. **Label**- assign workgroup (lead) responsible for tracking the task  
iv. **Projects** - assign to domain-specific TeamPSD tracker (issues, features, document, manuscript, team)  
v. **Milestones** - select monthly sprint milestone within the workgroup   
vi. **Estimate** - Estimate task in complexity points   
vii. **Epics** - assign to team-wide epic and TeamPSD master plan project  
iix. **Releases** - assign to key team release grouped with other relevant issues  

**3. If you anticipate that your **issue card** or **bug card** will have **dependencies** these can be added once the issue has been submitted.   
ix. **Add dependencies** - assess for and add dependencies *blocking* & *blocked by* this issue

**Comment by lijenn** [comment]
whoops this got lost a year ago...It has been fixed since then :) Closing this card.
