### ISSUE TITLE
August Task: Shortlinks to the TeamPSD & MTL Manual

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1470]
Task: Come up with shortlinks that are easy to remember and intuitive for everyone that would need to use the manuals.

**Team PSD Manual:**
**mtl.how/teampsd_manual** or **mtl.how/team_manual** may make sense for the TeamPSD manual.

**MTL Manual:**
**mtl.how/manual** would make the most sense since the base of the shortlink is already mtl.how.

What do you think @dlkibbe @branscombj @dlounsbu @jamesmrollins @lzim ?

**Comment by branscombj** [comment]
@lijenn 

> **Team PSD Manual:**
> **mtl.how/teampsd_manual** or **mtl.how/team_manual** may make sense for the TeamPSD manual.

I think it has to include PSD - team is too ubiquitous these days. So yes to teampsd_manual or I'm also ok with run-ons: **mtl.how/teampsdmanual**

> **MTL Manual:**
> **mtl.how/manual** would make the most sense since the base of the shortlink is already mtl.how.

Yes, this makes sense to me.

**Comment by lijenn** [comment]
Shortlinks are now at https://mtl.how/teampsd_manual and https://mtl.how/manual.
Thanks everyone :)!
