### ISSUE TITLE
automate & update teampsd tt_report contents

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1475]
Goal by Sept. 14 (Post Labor day week), tt_report should include:
- Remove LucidMeetings to reflect VA MS Teams Calendar that is integrated with Outlook (all meeting series/invites should be done via MS Teams)
- Automate from ZenHub: 
   - Burndown Report specific for the month's epic along with the total story points, issues and prs at the bottom of the report.
   - The icons located under the Control chart that shows the 'Issued moved from priority epic' all the way to 'median' of days it took. 
- Automate if possible:
  - Screenshots of the bug, feature, manuscript, document tracker.

**Comment by staceypark** [comment]
closing since we don't send this out anymore
