### ISSUE TITLE
8/28 Bug: Broken link from README.MD to Team PSD manual on lzim/teampsd 

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#1477]
Hi @lijenn I'm getting a **bug** from the **lzim/teampsd repo** when I click on the **readme.md** which is directing to this broken link:  https://github.com/lzim/teampsd/blob/master/mtl.how/manual

- Where should this link be pointing?

Thx!

**Comment by lijenn** [comment]
Corrected short link and re-linked it to mtl.how/teampsd_manual.
Thank you!
