### ISSUE TITLE
9/25 Task: 365 Integration Initial Work - Placeholder

### ISSUE THREAD

**Issue by anazariz** [lzim/teampsd#1479]
This is a placeholder for the initial work on the 365 platform Integration (VA Teams and Outlook). Currently the amount of work needed is not known. Additional Task tickets will be created as the amount of work is better understood.

**Comment by anazariz** [comment]
## Update: 8-31-20

Components of interest in Microsoft 365:

 1. Dynamics
 2. Office & Outlook
 3. Teams
 4. Power Platform (not including Power BI)
 5. SharePoint
 6. OneDrive

[Teams and Outlook email integration](https://docs.microsoft.com/en-us/microsoftteams/teams-outlook-email-integration)

As of last week I noticed that Item 2 thru 6 are now available in my VA 365. Initially I will research items 2 and 3 (hypothesize) as shown in the link I provided. Also, it looks as though we have access to the pro version of item 4. In that stack, Power Automate will allow us greater level of integration between the other components and maybe GitHub as well. Will find out.

**Comment by anazariz** [comment]
## Update: 8-31-20 - Continued

As mentioned about some integration between Outlook and Team has already been released by MS. and rest will follow soon. 
In addition to the native integration, I wanted to know if we can leverage the Power Platform for additional integration capabilities. I created a **Power Automate** process to intercept mtl.help & mtl.info emails and reroute them to the VA Teams Quant as postings. While compilations went without any issue, which means I could create the process, I keep getting a **"403"** error when I test the process. The error text says **"Forbidden"**. It seems like this is a common error, which is thrown when the recipient (my VA email account) does not have enough permission to perform the task. So, based on this, we may be able to figure out what permissions are lacking and close that gap. We may not want to route **help** and **info** emails to Teams but I am experimenting with several options so that we can pick the best one for our process.   

![image](https://user-images.githubusercontent.com/39805164/91783466-317b6600-ebb5-11ea-8caf-b5b30281e471.png)


The red exclamation point is the permission error (403 - "Forbidden")  that is thrown. 

![image](https://user-images.githubusercontent.com/39805164/91784072-c92d8400-ebb6-11ea-871d-cdd92609c6fa.png)

**Comment by anazariz** [comment]
## Update: 9-1-20

[Integrating Outlook and Teams](https://support.microsoft.com/en-us/office/send-an-email-to-a-channel-in-teams-d91db004-d9d7-4a47-82e6-fb1b16dfd51e)

**Note:** This feature needs to be turned on by your IT admin. Also, <ins>sending email to a channel isn't available if you're using Teams as part of an Office 365 Government plan</ins>.

**Comment by jamesmrollins** [comment]
This is a stale ticket.

**Comment by hnorthcraft** [comment]
#adjudicate_memo updating to dev label and 1 sp (to reflect background research into feature)
