### ISSUE TITLE
Facilitator Dashboard "Community" button still says "PLDR"

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1480]
**1. Add description:** 
@jamesmrollins please update the icon in the Facilitator Dashboard to say "Community" instead of "PLDR".

![Screen Shot 2020-08-31 at 3 57 05 PM](https://user-images.githubusercontent.com/31089501/91776649-a5f8d980-eba2-11ea-9599-a0ef2d5e2025.png)

**Comment by jamesmrollins** [comment]
Hi @staceypark -  I will change what you see below. This is an easy change, so I will get it done right away.

![image](https://user-images.githubusercontent.com/30132017/91881777-e30eab80-ec36-11ea-82d4-b510050fcc70.png)

**Comment by jamesmrollins** [comment]
@hirenp-waferwire I have reviewed the change in TEST.  Looks good.  Go ahead and move to production.  Thanks.  James

**Comment by lijenn** [comment]
This was updated and brought up in SIM UI 9/24 and in Prod. Thanks James!
