### ISSUE TITLE
R Cheatsheet: Team R Package Management 

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1484]
1. All current packages available for download (task for Anthony/David).
2. Citation for current version in Zotero (task for Stacey).
3. Master record on GitHub for the specific packages needed for each grant (task for Anthony?).

## 1. Link to the document and add relevant team members to the card.
- [ ] Add the link the current draft of the documentation for the issue:

## 2. Link to issues that must be edited in the document in the **issue_tracker** and **feature_tracker.** _(use the # for the link to the issue)_
- [ ] Issue 
- [ ] Issue 

## 3. Team Review
- [ ] Fidelity - check with Lindsey
- [ ] Data UI - check quant_workgroup
- [ ] Sim UI - check with model_workgroup and/or sim_workgroup

## 4. Review and Open Pull Requests _(use the # for the link to the pull request)_
- [ ] Check the draft for typos
- [ ] Check or open a pull request for the document edits

## 5. Review and/or Update Graphics
- [ ] Screenshots
- [ ] Gifs
- [ ] Logos/Icons
- [ ] Links

## 6. Dependencies
- [ ] Make sure that any edits you make that need to be added to **depend_product** are tracked (e.g., _MTL Video_)

## 7. Close Pull Requests
- [ ] Request review and/or close open pull requests for the document

**Comment by lzim** [comment]
This likely needs to be moved back to **dec_epic** unless it would help us get things done now.

@staceypark 
@dkngenda 

Cross-ref #832 R Library

**Comment by dkngenda** [comment]
@staceypark 
I suggest that R package management be done within the R notebook itself. That is ..

- Add code that installs packages required to run the notebook at the beginning of every notebook.
- Add statements  that dynamically updates to call out packages and R version the notebook is using.
Let me know what you think about this
