### ISSUE TITLE
wk2 TEST by 10/16: Single Log-in Facilitator Dashboard with Direct Session Navigation

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#1485]
### Check off requirements to verify progress through feature_tracker. **Cross ref #1481**
- [x] 1. Facilitators need a way to log in to the Sim UI and monitor multiple teams simultaneously.
  - [x] a. Currently, facilitators must have both a team login and a facilitator login to navigate either to a team session or the Facilitator Dashboard respectively.
  - [x] b. The facilitators cannot support multiple teams without first logging out of their current group and then logging back in to another group.
  Task Cards:
  #
---
- [x] 2. Hypothesis
  - [x] a. Devise a means for a facilitator, with a single login, to navigate to any team session underway (with an active runID).  
  - [x] b. Devise a means for the facilitator to review previously saved experiments from the same dashboard.
  - [x] c.  Devise a means for the facilitator to chat with all team leaders who are logged in.
  - [x] d.  Verified with Stacey, Jenn and Lindsey 9/17 in Sim_UI meeting.
  
  Task Cards:
  #
---
- [ ] 3. Design
  - [x] a.  See wireframe MVP at [Lucid Chart](https://app.lucidchart.com/invitations/accept/3c5717b9-12ff-4924-8c98-b0382151ee45)
  - [x] b. Use of run ID for all active sessions verified by James with Dave Bergman at Forio.
  - [ ] c. Jane and Debbie to provide input to wireframe.
  - [x] d.  Concept drawings for UX review/date

  Task Cards:
  #
---
- [ ] 4. **TEST in functional_test**
  - [ ] a. **what & why** - **TEST requirements** using **testing_checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** via TEST **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 5. **PROD in done**
  - [ ] a. **what & why** - **_DOCUMENT_ feature** using **document_tracker** for the **5 D's.** 
  - [ ] b. **date & who** -  **DELEGATE**
    - [ ] **describe_learners** [Jenn & Rita]
    - [ ] **detail_facilitators** [Jane & Debbie]
    - [ ] **document_team** [Anthony]
    - [ ] **disseminate_scientists_va** [Anthony]
    - [ ] **depend_products** [hq & ees]
  
  Task Cards:
  #
---
- [ ] 6. **closed** - fully documented, trained and ready for the next release.

**Comment by staceypark** [comment]
@jamesrollins
Is this feature card a duplication of #1481? 

Also, I see on Teams that you’re seeing a demo of the new facilitator login tonight. When can we expect it to be in Test for documentation? 

FYI: @lijenn

**Comment by jamesmrollins** [comment]
Hi @staceypark .  Below is an update on where we are in the Facilitator Dashboard redesign.

1.  We have accomplished Facilitator and Administrator logins.  Admin logins have the same permissions as a Facilitator, but also have access to the Tips Admin screen.  We have accomplished this by establishing two groups, "Facilitator" and "Administrator" in Epicenter.  We then build the login drop down from there.

**In Epicenter**
![image](https://user-images.githubusercontent.com/30132017/95616779-3d154480-0a1f-11eb-841b-be495c9c0fdb.png)

**Login Page**  Since I am in both Admin and Facilitator groups, I have both available in login.  If I was not in one of the groups, it would not show on my dropdown.

![image](https://user-images.githubusercontent.com/30132017/95616701-16570e00-0a1f-11eb-897d-7c253137d7f4.png)
 
2.  When an Admin logs in, the "Tips" icon is available.  When only Facilitator, the "Tips" icon is not available.

**Admin login**
![image](https://user-images.githubusercontent.com/30132017/95616989-93828300-0a1f-11eb-88bd-d70b136dee55.png)

**Fac login**
![image](https://user-images.githubusercontent.com/30132017/95617159-d6445b00-0a1f-11eb-854f-4892ad3db6ad.png)

3.  When the Admin or Facilitator wants to select a team to watch, they use the "Select Team" dropdown and select the group they want to monitor.  If there isn't an active run ID, then the green button will be faded.  If an active run ID is available, then the button will be bright.  When the user clicks the button, it directs them to the play page of the sim UI.  The user can add additional teams by clicking the "Add Team" icon in the lower right.

![image](https://user-images.githubusercontent.com/30132017/95617535-74d0bc00-0a20-11eb-9535-a5369e502d71.png)

4.  Regarding TEAM or what others call CHAT, we are able to provide many of the same characteristics of what we enjoy in MS-TEAMS.  This will take us some time to develop the UI and the backend Node Server functionality (approximately 50 DEV hours) 
Upon conclusion of DEV and TEST, we will be able to support:

a.  Person-to-person private chat.
b.  Person-to-group chat
c.  Conversation threads in group chat.
d.  Security of conversations in private and group chats.
e. Chat logs

5.  Regarding your question about "when."  **We anticipate being ready by the 20th of October.**  However, we want to do extensive testing, because rushing could bite us if we get in front of the QIICS and it malfunctions. So I might need some dedicated support to help out.

**Comment by jamesmrollins** [comment]
@staceypark  P.S.  Yes, #1485 is a duplicate of #1481.  Recommend we merge them.

**Comment by lijenn** [comment]
@jamesmrollins @staceypark 

Hi James, while we definitely want to be ready by next Tues. 10/20, I agree we'll not only need to do **testing**, 
but Stacey and I will also need to add in **documentation to the see/say guides and cheatsheet**.

We'll need the **Facil. dashboard in Prod by Thursday evening or Friday morning at the latest**. 
Is the Facil. dashboard already up in Test where we could help with user testing?

**Comment by jamesmrollins** [comment]
Hi @lijenn and @staceypark -  Below is the wire frame concept for the new chat functionality.  Since the picture below is somewhat hard to see, I have included a [chat wire frame.pdf](https://github.com/lzim/teampsd/files/5373837/chat.wire.frame.pdf) for better viewing.  It is styled after MS-Teams to take advantage of the user's learning of that platform.  However, there is much more that Teams does that ours doesn't.  However,  think we have bitten off all we can chew before the 10/20 deadline.  There are other features I'm sure we will think of that we can push in later iterations.

### Regarding the schedule:

1. I will see if I can get this into test by Friday 10/16 (but no guarantees).  My team has to develop this function from "scratch" as Epicenter does not have an API for this.
2.  That will give us Friday to test and Sunday and Monday to iterate and finish up documentation.  
3.  Target PROD by 10/20.  

### The design features:

- The ability to have a private chat with one or more people.
-  The ability to have a public conversation with all members of a team in a unique conversation thread.
- The ability to have multiple conversation threads within the public conversation. 
-  New icons for Team conversation, add new chat, reply, and new conversation.

![Wire Frame](https://user-images.githubusercontent.com/30132017/95910499-0445da00-0d55-11eb-9fd9-2fefa03ffa8c.png)

**Comment by jamesmrollins** [comment]
Hi @lijenn and @staceypark   Below is a list of documents that I will prepare (unless already produced).  I will prepare a .md file, provide supporting graphics and GIFs (if desired).  Please review this list and approve, or amend as needed.  Thank you.

### Facilitator Training Support Docs

- [ ]  **Navigate to an active session**
   - Differentiate between a team or an individual in drop down menu
   - Select an individual or team
   - Navigate to an active individual or team session
   - Return to Dashboard.

- [ ]  **View the status of a saved experiment**
   - Select an experiment.
   - Interpret the status gauge

- [ ] **How to chat with an individual or team**
   - Start a private conversation with an individual
   - Start a public conversation with a Team
   - Start a new thread within a public conversation

### Admin Training Support Docs

- [ ] How to set up a Facilitator and an Admin in Epicenter
   - How to add an Admin login in Epicenter
   - How to add a Facilitator login in Epicenter

**Comment by staceypark** [comment]
@jamesmrollins 
@lijenn and I have a couple questions:
1) Is there a reason only "Tips" is separated out between the Facilitator vs. Admin login? And how easy would it be to change that - i.e. if we want both "Tips" and "Tutor" to be only Admin.
- Perhaps we need to clarify, when a facilitator joins a session with a team, are they only accessing the "Play Screen" or should we treat it like they're joining that team's world, meaning they will have access to the front-end learner version of the quick tips, tutor, etc. Because I don't think the facilitators necessarily need to be able to edit the quick tips back end section for example.

2) We will definitely need all of these changes in **TEST by Friday 10/16** to make sure any documentation updates can be made with the appropriate screenshots. Since we are **meeting with the QIIC the morning of Tuesday 10/20,** we need everything in **PROD by no later than Monday 10/19 morning**.

3) For the Teams/Chat function, I don't think they need the ability to have "threads" per se, and am wondering how much DEV time that would save us.

4) In terms of the documentation listed above, I think that looks like a good list. Jenn & I think these should all take the form of flow maps on LucidCharts. We would need the **documentation completed by Monday 10/19 morning** as well so we can have time for review & editing as necessary

@branscombj @dlkibbe would appreciate any thoughts you guys have on this?

**Comment by jamesmrollins** [comment]
@staceypark  and @lijenn 

Regarding 1. There is no particular reason.  I can make both Tips and Tutor disappear when a Facilitator logs in.  When a facilitator joins an active session from the dashboard, they would go directly to the Play screen. Since they are in that session, they would have all the same icons the players do, plus a Dashboard button to get back to the dashboard.

Regarding 2 and 3.  I recommend we make definite plans for releasing information on the Dashboard direct session navigation, since that is done in DEV and potentially hold Chat for next month. I'm not sure how much time saving the discussion threads would save but I can ask DEV tonight and provide a revised estimate. That might help us hit Friday and then we can add threads in later.  As much as we use threads in Teams, it would not surprise me if it was ultimately needed.

Regarding 4.  You want flow maps - instead of .md/png/gif.  Got it!

**Comment by staceypark** [comment]
@jamesmrollins 
Ok in that case, I think Tips, Tutor, and More Info backend can all be just for Admin login.
> Regarding 1. There is no particular reason. I can make both Tips and Tutor disappear when a Facilitator logs in. When a facilitator joins an active session from the dashboard, they would go directly to the Play screen. Since they are in that session, they would have all the same icons the players do, plus a Dashboard button to get back to the dashboard.

I think the Teams/Chat function will definitely be important to teach all at once during the Facilitator training, but the threads function I think we can hold off on, especially if it will help us hit the Friday mark. Let us know what the dev team says!
> Regarding 2 and 3. I recommend we make definite plans for releasing information on the Dashboard direct session navigation, since that is done in DEV and potentially hold Chat for next month. I'm not sure how much time saving the discussion threads would save but I can ask DEV tonight and provide a revised estimate. That might help us hit Friday and then we can add threads in later. As much as we use threads in Teams, it would not surprise me if it was ultimately needed.

Yes, I will be updating the cheatsheet that has screenshots once things are in test, so I think we only need flow maps from you - unless @branscombj has other thoughts.
> Regarding 4. You want flow maps - instead of .md/png/gif. Got it!

Thanks for all your work James! 😄

**Comment by jamesmrollins** [comment]
@hirenp-waferwire please make the "More Info," "Tutor" and "Tips" icons available only for the Admin login.

![image](https://user-images.githubusercontent.com/30132017/95945049-8c9c9d00-0d9e-11eb-9d0a-f539b885e86e.png)

**Comment by jamesmrollins** [comment]
Hi @staceypark and @lijenn 
I discussed the issue of delivering Chat functionality by 10/16.  We are still a little tentative about hitting this date, but will closely monitor.  If we feel we are going to miss the target, we should know this by Thursday, so we can plan accordingly.

**We think we can complete this month:**
- Individual and multiple private chat function - all end users within the project will be accessible.
- Team public chat function
- Revised graphics and "look" in accordance with the wire frame above.

**For next month:**
- Chat log search functionality.
- Team conversation search functionality
- Conversation thread functionality.

**Comment by jamesmrollins** [comment]
Hi @staceypark and @lijenn .  Please find the workflow diagrams that support requirement listed here:

> Hi @lijenn and @staceypark Below is a list of documents that I will prepare (unless already produced). I will prepare a .md file, provide supporting graphics and GIFs (if desired). Please review this list and approve, or amend as needed. Thank you.
> 
> ### Facilitator Training Support Docs
> * [x]   **Navigate to an active session**
>   
>   * Differentiate between a team or an individual in drop down menu
>   * Select an individual or team
>   * Navigate to an active individual or team session
>   * Return to Dashboard.
> * [x]   **View the status of a saved experiment**
>   
>   * Select an experiment.
>   * Interpret the status gauge
> * [x]  **How to chat with an individual or team**
>   
>   * Start a private conversation with an individual
>   * Start a public conversation with a Team
>   * Start a new thread within a public conversation
> 
> ### Admin Training Support Docs
> * [x]  How to set up a Facilitator and an Admin in Epicenter
>   
>   * How to add an Admin login in Epicenter
>   * How to add a Facilitator login in Epicenter

### Diagrams in LucidChart

1.  [Navigate to an Active Session](https://app.lucidchart.com/invitations/accept/dbc64d9d-2b78-445c-bf5b-5dbb1752bc3f)
2.  [View Status of Experiment](https://app.lucidchart.com/invitations/accept/ae7d919d-2fc8-4d17-b3bd-1bfcae5586a9)
3.  [Use Team Function](https://app.lucidchart.com/invitations/accept/7865f01c-e7f8-4f0b-ae22-9b1440bed8e3)
4.  [Setup Admin/Facilitator Login](https://app.lucidchart.com/invitations/accept/f07924bb-bc16-4c77-9d0e-50d7ea366a92)

**Comment by staceypark** [comment]
@jamesmrollins Thanks for producing these!
@lijenn and I will review these once things are in TEST.

**Comment by staceypark** [comment]
@jamesmrollins are we still on track for TEST tomorrow?

**Comment by jamesmrollins** [comment]
@staceypark .  Yes, as of this morning's report from @hirenp-waferwire , we are on track.

**Comment by lijenn** [comment]
@jamesmrollins 
@staceypark and I are testing Chat and the notifications don't seem to come up for either the individual or group chat. No notifications are coming up in the Team icon, like how it looks for the News icon just as a reference.
![image](https://user-images.githubusercontent.com/59668647/96302630-fb037a00-0fad-11eb-9489-61658f8cca9b.png)

**Comment by jamesmrollins** [comment]
@lijenn @staceypark  you mean the red number that should appear on the "Team" icon in the header?  Probably can get that fixed by Monday.

We don't have the red number functionality inside the chat window (I didn't spec it).  Probably easy enough to incorporate when we put on final touches next month.

**Comment by lijenn** [comment]
Right, the red number that should appear on the "Team" icon. 

I think it might be helpful to also have that functionality inside either the individual Chat or group Team chat windows too just to know where the notification is coming from as a suggestion for final touches next month.

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire .  Please see bugs below.

1.  Bubble on Team icon missing to notify for pending chat view.
2.  Last chat showing in wrong part of chat log.

![image](https://user-images.githubusercontent.com/30132017/96304397-e2489380-0fb0-11eb-9570-f44201b89228.png)

**Comment by staceypark** [comment]
@jamesmrollins FYI @lijenn 
Apart from the chat notifications issue, the only other one I see is some copy editing on this text:
![image](https://user-images.githubusercontent.com/31089501/96306273-3b65f680-0fb4-11eb-8bcb-59b30490e5f0.png)

**Comment by jamesmrollins** [comment]
@staceypark  - All easily correctable from the Admin page. :-)

**Comment by jamesmrollins** [comment]
@hirenp-waferwire  - see above.  Please edit these changes in the Community Admin page.

**Comment by staceypark** [comment]
Hey @jamesmrollins 
@lijenn  and I want to check something else:

1. The dropdown for choosing teams seems to show all the individual and team worlds available - Is this true?
2. If #1 is true, does this mean that folks don't already need to be within a world to choose teams in that world - Meaning we can put the facilitators just in the facilitator login and their own individual worlds. And they will be able to interact with any team world without us having to put them in it on the backend.
3. Can we get the dropdown alphabetized? Not sure how the current list is organized but if #1 is true, then there will be A LOT of worlds in that dropdown in PROD.

![image](https://user-images.githubusercontent.com/31089501/96310034-5f790600-0fbb-11eb-8c56-fdc28e8c71bc.png)

**Comment by jamesmrollins** [comment]
Hi @staceypark and @lijenn 

Regarding:

1.  Yes.
2.  The menu will reflect all the group/worlds that has that facilitator as a facilitator.  No other modifications required. We just needed to differentiate between team group/worlds and individual group/worlds.
3. With respect to the list alphabetization, do you want by team then by individual?
4.  Also, should probably get rid of the "Team" prefix.  Unless @hirenp-waferwire needs it, it is redundant (I think).

**For example:**
100a1_abc_teama_team
Ann Anne 100a1_abc_teama_ind
Bob Baker 100a1_abc_teama_ind
Charlie Cook 100a1_abc_teama_ind
Debbie Davis 100a1_abc_teama_ind
583ge-wl_bhip_2019_03_team

_I think we should be able to sort based on number first, so lowest first number character would be highest in the order.  Then alphabetize names underneath.  Not sure, we'll need @hirenp-waferwire to weigh in._

**Comment by staceypark** [comment]
> Hi @staceypark and @lijenn
> 
> Regarding:
> 
> 1. Yes.

@lijenn that means that we will still need to add facilitators to those respective team's ind & team groups but they won't necessarily need to be assigned to a world within it probably.
> 2. The menu will reflect all the group/worlds that has that facilitator as a facilitator.  No other modifications required. We just needed to differentiate between team group/worlds and individual group/worlds.

I think that makes sense. Is it possible to make the non-italicized text and the italicized text on separate lines or no because of dynamic response.
![image](https://user-images.githubusercontent.com/31089501/96322321-70cb0e00-0fcd-11eb-926a-0d99389c45c1.png)

> 3. With respect to the list alphabetization, do you want by team then by individual?

Yes I agree. No need for Team prefix. But, the actual team name should change to be non-italicized in that case.
> 4. Also, should probably get rid of the "Team" prefix.  Unless @hirenp-waferwire needs it, it is redundant (I think).
> 
> **For example:**
> 100a1_abc_teama_team
> Ann Anne 100a1_abc_teama_ind
> Bob Baker 100a1_abc_teama_ind
> Charlie Cook 100a1_abc_teama_ind
> Debbie Davis 100a1_abc_teama_ind
> 583ge-wl_bhip_2019_03_team
> 
> _I think we should be able to sort based on number first, so lowest first number character would be highest in the order. Then alphabetize names underneath. Not sure, we'll need @hirenp-waferwire to weigh in._

**Comment by jamesmrollins** [comment]
@staceypark the names would have to break into multiple lines in order to be responsive and fit in the box.  We should be able to get rid of the italics.

**Comment by lzim** [comment]
For #3 @jamesmrollins & @staceypark, I would recommend sorting by individual then team. 

Only facilitators will have this big drop down list (not teams of learners in the field): 

So, as a facilitator, I’d rather see all of my logins together (i.e., by my name as an individual facilitator, and then have my own list of teams all together in alpha order), than have it go back & forth between facilitators like the Stacey & Jenn example at the bottom of the list above.

**Comment by jamesmrollins** [comment]
@staceypark  and @lzim this is not the login list.  This is the team list in the facilitator panel.  

With that said, I understand individuals in alphabetical order first and then by teams (see below):
Ann Anne 100a1_abc_teama_ind
Bob Baker 100a1_abc_teama_ind
Charlie Cook 100a1_abc_teama_ind
Debbie Davis 100a1_abc_teama_ind
100a1_abc_teama_team
583ge-wl_bhip_2019_03_team

In other news:
We have deployed the direct session navigation and improved chat functionality to PROD this morning.  Things we are still working on include the team sort discussed above, and the red chat notification bubble.  These we hope to have in place by tomorrow.

**Comment by lzim** [comment]
Question @jamesmrollins:

Should I be able to pull up the text in the Experiments Section when I navigate from my facilitator_login Dashboard via the Green "Go to Current Session" button?

I haven't tested all prior sessions, but I don't seem to be able to repopulate the text boxes for any of them.

FYI: @staceypark and @lijenn

**Comment by jamesmrollins** [comment]
@lzim I believe it depends on whether the session has been saved or not.  If the text is put into one of the text fields in an active browser session, the information is held locally.  When the user saves the data, it records it on the server.  Then all can see.  I will verify this with DEV tonight, but I believe it to be the case.

**Comment by lzim** [comment]
Okay, this is interesting. 

@jamesmrollins - Can you help me with defining "Current Session" for our guides & cheatsheets? 
- Does it just mean "the current state of this team's world, if it has been saved, but _without any of the team's history_?" 
- If so, then in terms of functionality, we not really joining the Sim session in progress with all the information that the learners will have at their disposal, which would include prior parameter decisions and text.
FYI: @staceypark  and @lijenn 

Here's my use case:

I'm in PROD and I cue up the BC run for Team 4. As you can see, it says the BC run, as well as the other 3 experiments were all 100% complete on the dashboard dial, which I think means that the Q/F/H/D boxes were all filled in when the session is saved (right?). 

But, when I click the green "Go to Current Session" and navigate to the Experiments Section, I don't have any previous experiments text to cue up. And, I don't have any text of prior runs available in the Control Panel of the Results Dashboard available at Expanded Outputs & Text to cue up either. 

![Screen Shot 2020-10-19 at 2 40 11 PM](https://user-images.githubusercontent.com/7454688/96514836-1cb46980-1219-11eb-92a7-588e53d26359.png)

**Comment by jamesmrollins** [comment]
@lijenn @lzim @staceypark  The "Go to Current Session" button navigates to the last session running that has not yet been reset.  A session can be named and saved but is still active until reset.  When a session is reset, it it saved under its experiment name and can no longer be edited. From that point forward, if a user navigates to that sim, a new run ID will be created and will become the "Current Session."  To access text from a previous experiment that has been saved and reset, one would navigate to the "Load Previous Experiment" dropdown in the Experiment section.

**Comment by lzim** [comment]
From @jamesmrollins 
> To access text from a previous experiment that has been saved and reset, one would navigate to the "Load Previous Experiment" dropdown in the Experiment section.

1. Using the "Load Previous Experiment" dropdown is 50% of what I am reporting does not work.
2. Using the Control Panel of the Results Dashboard available at Expanded Outputs & Text to cue up a previous experiment is the other 50% of what does not work.

None of the prior experiment values or text are available in any of the normal places, when I navigate there  in the team's world via the "Go to Current Session" selection from my facilitator_login.

I do copy that what I am navigating to is the run ID for the "Current Session" which is the "last session that has not be reset."

But, I won't effectively be able to join a fully function team's session in progress via my facilitator_login without access to the experiment history in those two "previous experiment" locations (experiment values and history).

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire .  We have spotted a few bugs regarding the Facilitator Dashboard, specifically with the navigation to team sessions and the availability of data.

**1.  Upon login, we notice it is throwing this error.**

![image](https://user-images.githubusercontent.com/30132017/96521490-488a1c00-1226-11eb-85d7-4b40fb722bd1.png)

**This is the associated console error messages.**

![image](https://user-images.githubusercontent.com/30132017/96521518-5475de00-1226-11eb-9811-0283e971b780.png)

**2. We notice that all the menu selections for Team Data are missing, yet one is selected for current session.**
![image](https://user-images.githubusercontent.com/30132017/96521701-b2a2c100-1226-11eb-8057-5ef900e2d4cf.png)

**3.  For some reason, all the associated experimental data for 640_mpd_team2_team has disappeared.**

I logged in as a Team Lead and found there is no current session.
![image](https://user-images.githubusercontent.com/30132017/96524566-82aaec00-122d-11eb-8747-86a62f2fee00.png)

So I loaded up a new session.

![image](https://user-images.githubusercontent.com/30132017/96524610-9ce4ca00-122d-11eb-83cc-7dfd1c4d7b00.png)

And logged in as a Facilitator to see if that corrected the experiment problem . . . it did not.

![image](https://user-images.githubusercontent.com/30132017/96524716-e3d2bf80-122d-11eb-86a7-e092d6e93edd.png)

**Comment by jamesmrollins** [comment]
@staceypark @lijenn  FYI @lzim 

1.  **We need to assign the facilitators a WorldID with team leader privileges.**  Epicenter requires a WorldID in order to anything to the simulation, such as start a session, choose a team data file or to run the sim. Thus, we need to ensure they have a WorldID, and it must be the same world as other members of the team. 

2.  **We have modified the login drop down to not include any listings of these individual WorldID's for Facilitators.** in order to simplify their login choices.  If a facilitator needs to navigate to their individual world to practice, they will need to navigate there through the Facilitator Dashboard, by selecting their personal team from the dropdown and clicking the "Go to Current Session" button.

3.  **We found the 640ao_mpd_team2 experiment files.**  They indeed were deleted by someone on that team.  However, since everyone has the same WorldID, we don't know exactly who.  However, they were "soft" deleted, so we were able to recover them.  Although I cannot precisely account for them, as I don't know how many were in the original listing.  

4.  **The error messages we experienced were caused by the wrong SP model.**  We have corrected this.  But keep in mind that we cannot use old data files that don't have episode counts and floors.

5.  **The team drop down team and individual listing should follow the format we described above by morning.**

6.  **The red chat notification bubble may not be ready by morning - we will try.**

**Comment by jamesmrollins** [comment]
Hi @lzim @staceypark @lijenn 

Here is an update and strategy for making this process a little more bulletproof.  The main issue revolves around the worldID.  The sim ui manages many things, including saving past experiments (AKA runIDs), using the worldID.  The problem with worldIDs, is they are disposable.  So if one goes in and deletes all users from a given world, the worldID is thrown away by Epicenter.  And so is all the things associated with the WorldID, such as the saved experiments.

### Findings:
1.  The saved experiments that suddenly disappeared, were NOT deleted. As I suspected, they are still on the server, but the associated WorldID linkage was broken.
2.  We were able to immediately restore 640a0_mpd_team4_team experiments but,
3.  640a0_mpd_team2_team experiments are still not associating properly.  We have the run IDs, so we should be able to get to the bottom of this soon.
4.  Since we are restricted to making calls to worldIDs with the available Get API, that meant we had to register the "facilitators" not as facilitators, but as Team leads, in order to have a worldID and to give them the ability to manipulate the sim (such as navigate to home and change simulations).  Problem is, it also means their login dropdown will have the team listing.  So we didn't accomplish simplifying the login (yet).  Moreover, it limits the call to just one world they share with others in the group, versus all of them (such as in an _ind group).
5.  If a group does not have an active runID, the facilitator has no way to navigate to home and start a simulation.  This must be done through a Team Lead login. 

### Way forward
1.  I consulted with Forio.  They suggested we use a Get APP that returns the groupID and that we base all of our experimental saves and so forth against the groupID.  Groups are more durable than worlds.  Even if you delete all endusers out of a group, the group will persist.  This should solve the disappearing experiment problem.
2.  If we base our code on the groupID, then we can go and fetch all related worldIDs for that group.  Now we can simply say an individual is a facilitator by setting them up as one in that group, and they would be able to enter into and manipulate any of the worlds in the group. 
3.  Since a person is now truly a facilitator in the system, they don't need a team lead world assignment.  And they don't need a special login any longer.  They would be able to navigate everywhere they need to be from the dashboard.
4.  We will need to provide a means for a facilitator to navigate to a team's homepage from the dashboard, if there is not an active run ID.
5.  We still need to provide a chat notification bubble.
6.  We still need to sort the team list in the dropdown as previously defined.

We will continue to refine this functionality and work with Forio.  I will report out as things progress.  Let me know if you have questions. James

**Comment by jamesmrollins** [comment]
Hi @staceypark @lijenn @lzim - todays update is below and is available in Test.

1.  Implemented group_ID reference for facilitators to remove requirement for Team Lead assignment and simplify login dropdown.  Facilitators now only have to be designated a "Facilitator = yes" in the end-user panel to have access to all worlds in that group.  
2.  Implemented a "Home" button on the Dashboard, to enable direct navigation to a Home page, and provide a means for the Facilitator to start a new run, should a current run not exist.
3.  Re-implemented the chat notification bubble on the Team icon in the top navigation menu.
4.  Implemented the teams sort in the teams dropdown as outlined above.

To Go
We are refactoring our code to use the groupID to save experiments.  This is a feature that will prevent lost experiments in the future and allow expanded sharing of experiments within a group.

**Comment by lijenn** [comment]
@jamesmrollins 
**0/22 Bug in Test-Slow**
Bug: Seeing 2 copies of same world, both worlds contain different experiments. 1st world has experiments (not needed as those were tests), 2nd world contains no tests at all.

Copy of same world:
![image](https://user-images.githubusercontent.com/59668647/96939772-cfd3cb80-1482-11eb-89f3-63c5b3793122.png)
1st world's experiments:
![image](https://user-images.githubusercontent.com/59668647/96939786-dc582400-1482-11eb-8c60-3ac69d1001f5.png)
2nd world's experiments:
![image](https://user-images.githubusercontent.com/59668647/96939803-e8dc7c80-1482-11eb-8b62-657faac20337.png)

**Comment by staceypark** [comment]
@jamesmrollins these are all the groups that DEV should look for experiments:
- 100a1_abc_teama_team
- 583ge_wl_bhip_2019_03_team
- 640a0_mpd_team2_team
- r21_manuscripts
- team_mtl_facilitate_pilot_2018_09

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire .  

Please see @staceypark 's comment for guidance on experiments to reference to groupID.
> @jamesmrollins these are all the groups that DEV should look for experiments:
> 
> * 100a1_abc_teama_team
> * 583ge_wl_bhip_2019_03_team
> * 640a0_mpd_team2_team
> * r21_manuscripts
> * team_mtl_facilitate_pilot_2018_09

### We tested the Sim UI Facilitator Dashboard functionality today and have these observations:

1. Chat bubble is not always clearing once a chat is reviewed.  It should count down, as chats are viewed.
2. Chat log should sort by most recent and be boldface if not viewed (see below).
3. The "you" prefix is not always showing (see below)

![image](https://user-images.githubusercontent.com/30132017/96940357-62c13580-1484-11eb-987a-def6643f3527.png)

**Comment by staceypark** [comment]
@jamesmrollins Chat notif bubble should appear on the "Team" icon regardless of where you are in the facilitator dashboard/sim. Currently red bubble disappears from the nav bar at the top when you're in the chat window.

**Comment by jamesmrollins** [comment]
@staceypark @lijenn  All is updated in PROD to include restoration of experiments.  

I updated the Lucid chart [diagram](https://app.lucidchart.com/invitations/accept/dbc64d9d-2b78-445c-bf5b-5dbb1752bc3f) to include the new "home" navigation to start a new session. 

Other things to keep in mind:  
1.  In order for groups to show up on the dropdown, one must use the "_ind" or "_team" suffix on the group name **AND** there must be at least one user assigned to a world in the group.
2.  Facilitator/admins must be set up in the Facilitator or Admin group **AND** they must be set up as a facilitator in the target group with the "Facilitator?" set to "yes."

**Comment by lzim** [comment]
@staceypark and @lijenn 

Those two points from @jamesmrollins  will be key for the MTL Technical manual Admin section.

**Comment by lzim** [comment]
> @staceypark and @lijenn
> 
> Those two points from @jamesmrollins will be key for the MTL Technical manual Admin section.


@staceypark and @lijenn I see @jamesmrollins Closed this, but just to double-check do we have it covered in documentation?
