### ISSUE TITLE
9/25 Update Team Data File Save Location

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1487]
When the team data table gets created with the data UI, the file saves back to the data_ui folder. Makes sense from a technical perspective since that's where the data UI resides.
 
Let's make it auto save to the team_data_table folder instead, since that would make more sense with our folder structure at mtl.how/data. We had held off on this due to other data UI related pauses.
 

Notes from Meeting with Stacey 09_22_2020:
When get patient level data button is clicked, the tabs will be updated under dataDiag, dataHf, dataMeas... etc.
 
When Create Team Data Table button is  selected the CCParams MMParams will be updated and a document will be produced. We want that document to be saved into the sim_ui team data fodler

**Comment by anazariz** [comment]
Fixed the File location item. Needs testing. Will bundle this with the "\'" ticket to be implemented. The Workbook with then be propagated.

**Comment by anthonycpichardo** [comment]
This is tested and complete.
