### ISSUE TITLE
10/1 This Afternoon mtl.how/data updates 

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1494]
mtl.how/data

BISL Station Splashpage - Still lists "(640) VA Palo Alto

1. Delete the Webpart.
2. Rename "splashchart.xlsb" to "facility.xlsb"
3. Move "facility.xlsb" to it's parent folder
4. Delete the "splash_page_admin" folder.
5. Edit the message to reflect below.
 
 
**MESSAGE:**
**View facility data** by opening the Excel File **"facility.xlsb"** in "Read Only" mode. 
**Team files are in team folders**. If you do not see a team folder, **request a team folder above.**

**Documentation**
1. SEE guide
- Needs edits to instructions
- Update .gifs
 
2. TMS Supplementary Documents

3. mtl.how/data cheatsheet
 
 
Divvy up Anthony, Ash, Jenn & Stacey this afternoon.

**Comment by anthonycpichardo** [comment]
https://github.ec.va.gov/EPMO/mtl_operations/blob/master/SplashPage/User%20Guides/splash_page_guide.md

Splash page guide on how to edit a document is available on mtl_operations.

**Comment by anthonycpichardo** [comment]
Division of Labor:
@anazariz : VISNs 1 - 6
@anthonycpichardo : VISNs 7 - 12
@staceypark  : VISN 15 - 19
@lijenn : 20 - 23

Let me know if there's any questions.

**Comment by staceypark** [comment]
Changes to make pre-GIF and SEE guide, cheatsheet, TMS update:

1. Change the instructions to describe how to open in Excel (and avoid the Web).
- EDIT FIRST LINE TO SAY: To view facility data click on the [...] next to the file "635_facility.xlsb" and click "Edit" to open in Excel.
- DELETE: "You can see all of your station's files at the bottom of the page."
2. Change the name of the file to include the sta3n (facility).
3. If all the facility data will be reviewed in Excel is there a way (e.g., using Developer Mode) to make sure the tables and graphs display well without overlaps. @anthonycpichardo @anazariz

**Comment by staceypark** [comment]
We decided not to change this. Instructions have been added in See, Say, & Cheatsheet regarding this.
> 2. If all the facility data will be reviewed in Excel is there a way (e.g., using Developer Mode) to make sure the tables and graphs display well without overlaps. @anthonycpichardo @anazariz
