### ISSUE TITLE
NOV Epic: CRM User stories with Scott Beck

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1497]
We need to review the user stories from Scott Beck on the CRM for Wave II CRM use

Teams link to file here:

**Comment by lzim** [comment]
I just pinged Scott B on the MSD 365 Teams thread to check on the location of this Excel file of User Stories. It doesn't seem to  be in our thread.

**Comment by lzim** [comment]
@anthonycpichardo 
@staceypark 

I will need more time to flesh this out. I believe the 3 of us need a meeting for it, although I cannot prioritize this over R21, R01 & IIR tasks.

Should we turn to this in **nov_epic**?

And to confirm, did we tell Scott we would not be meeting today?
I believe we did at the last meeting, but I'm not sure I saw the cancellation come through my email. Thanks!

**Comment by anthonycpichardo** [comment]
We did cancel today's meeting as discussed.

Let me know if the invite didn't come through on your end, that would be interesting.

**Comment by lzim** [comment]
It did come through @anthonycpichardo. But I had not it seen it when I saw this. Thanks!

**Comment by anthonycpichardo** [comment]
@lzim @staceypark  @lijenn I took a first pass at filling out the user story descriptions and acceptance criteria for the CRM.

Can you review and provide feedback. I've marked specific places where I had questions with -@HQ xxx-

**Comment by lzim** [comment]
> @lzim @staceypark  @lijenn I took a first pass at filling out the user story descriptions and acceptance criteria for the CRM.
> 
> 
> 
> Can you review and provide feedback. I've marked specific places where I had questions with -@HQ xxx-

@staceypark and/or @lijenn 

Can you look at this before the 12:30 w/Scott?

I’ll be busy with Qual and R Notebooks today.

**Comment by lzim** [comment]
Update from 10/21/20 meeting.

Lindsey edited Antony’s draft & we’re ready for asynchronous feedback from Barath & Jerry.
