### ISSUE TITLE
WK3 Triage why facility workbook was updated with incorrect list of facilities

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1508]
During 10/4/20 Splash Page propagation a small number of sites were updated with the incorrect facility list.

Triage what caused this to occur and how to prevent it in the future.

**Comment by anazariz** [comment]
When logged into VA thru Citrix, when the Citrix window is not maximized, if there is a live database connection, it's halted.  This may be a newly added security feature. When I ran the SplashPage program for the Sept 2020 cycle, I took the screen out of the Maximized mode to do some work in non-VA teams and received a database connection error. I had to rerun the program to resolve the data discrepancy.

**Comment by anthonycpichardo** [comment]
Will add this note to the data ui and splash page check documents
