### ISSUE TITLE
feb_epic Story 10: Model manuscript walkthrough of systems stories for CC, MM, Psy, & Agg

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1510]
@branscombj will write out the systems stories walkthrough of the models in the following order:
- mm
- psy
- agg
- cc

**Comment by branscombj** [comment]
these are all the 
### Feedback Loops designated in model diagrams (all portions "revealed"):
I'll check them off as completed. It looks possible to write the description of loops that occur in multiple models generically.

MM 
- [ ] Balancing existing and new patients 
- [ ] Wait time affects referrals 

PSY
- [ ] Balancing existing and new patients

AGG

- [ ] Fatigue increases clinic cancellations (R)
- [ ] Appointment backlog extends return visit interval (B)
- [ ] Overtime relieves work pressure slowly (B)
- [ ] Overtime relieves work pressure quickly (B)
- [ ] Burnout increases clinician quits (B)
- [ ] Fatigue increases ending early (B)
- [ ] Wait times affect intake evaluations (B)
- [ ] Start delays affect treatment decisions (B)
- [ ] RVI delays affects [sic] treatment decisions (B)

CC
- [ ] Balancing existing and new patients 
- [ ] Wait time affects referrals 

SP
- [ ] Higher care quality improves recovery

**Comment by branscombj** [comment]
### WAIT TIME AFFECTS REFERRALS (MM, CC)
The difference between the actual new patient wait time and referring providers’ target wait time influences referring providers’ willingness to refer patients for care. As the gap increases – as patients are waiting longer than providers feel is acceptable for their diagnostic cohort – providers cut back on making referrals, reducing the referral rate. This allows the number of patients waiting to start care to decrease which, in turn, causes the actual wait time to drop, reducing the gap between actual and target wait times and increasing referring providers’ willingness to refer patients.

**Comment by branscombj** [comment]
### BALANCING EXISTING AND NEW PATIENTS (MM, PSY, CC)
Scheduling requires balancing appointments for existing and new patients. With a given supply of available appointments, the more slots that are reserved for new patients, the higher the start rate of new patients, the higher the booking rate of appointments and the greater the number of appointments on the books. This increases the appointments for existing patients, which in turn decreases the slots available for new patients.

**Comment by branscombj** [comment]
### Fatigue increases clinic cancellations (AGG) 

> @lzim @TomRust Would it be more appropriate to call this Overtime Leads to Fatigue (which is rather a truism – but still)? Fatigue is not a variable in our model so it’s not quite right to say it causes anything. What we say in the model is that **overtime** increases clinic cancellations. But the feedback loop goes beyond that single causal relationship, so adding fatigue in its name helps get at the vicious cycle of overwork.

Working overtime, by limiting the time clinicians can spend on activities beyond direct care that help ensure patients complete scheduled appointments, leads to increases in the missed appointment rate. This means more appointments must be rescheduled, resulting in more appointments on the books. But more appointments means more work pressure, pushing the team toward further expanding overtime effort. This vicious cycle leads to fatigue.

**Comment by branscombj** [comment]
### Burnout increases clinician quits (AGG)

In the long term, overtime leads to clinician burnout and quitting. If overtime across the team **increases** and **more** clinicians quit, there are **fewer** actual hours available for services in the team, leading to **less** long-term overtime being worked.

> @lzim @TomRust This would seem to me to be a reinforcing loop instead: Overtime leads to burnout and that leads to more quits, but that means fewer bookable appointments and increasing pressure on remaining staff to add overtime appointments.

**Comment by branscombj** [comment]
### Overtime relieves work pressure slowly (AGG)

When the actual hours available for service in the team **increases** due to overtime, the appointment completing rate **increases**, **reducing** the number of appointments on the books. This **reduces** work pressure, leading the team to **reduce** the overtime hours it considers available for service.

**Comment by branscombj** [comment]
### Overtime relieves work pressure quickly (AGG)

When the actual hours available for service in the team **increases** (even if due to overtime), this has a relatively rapid, direct effect of **reducing** work pressure. Less work pressure then leads the team to **reduce** the overtime hours it considers available for service.

**Comment by branscombj** [comment]
### Appointment backlog extends return visit interval (AGG)

As **more** appointments accumulate on the books, the resulting **increase** in work pressure **increases** clinicians’ tendency to schedule return visits at **longer** intervals. This **reduces** the booking rate, **reducing** the number of appointments on the books.

**Comment by branscombj** [comment]
### Fatigue increases ending early (AGG)

Working overtime cuts down on the time clinicians can spend on activities beyond direct care that help ensure patients continue in care for their full course of treatment. Therefore, **increased** overtime in the team leads to a **reduction** in overall engagement duration of patients in the team.

> @lzim @TomRust This variable does not have any arrows that can be traced back to the variable “short-term overtime” that this “loop” starts with.

**Comment by branscombj** [comment]
### Wait times affect intake evaluations (AGG)

As patients waiting for intake evaluation **increase**, their wait time for evaluation **increases**, **reducing** the evaluation rate and **reducing** the number of patients waiting for intake evaluation. 

> @lzim @TomRust @jamesmrollins Is this piece of the model (or its labeling) correct? It seems to say that the Intake Evaluation Rate determines the Number of Patients Waiting for Intake Evaluation.

**Comment by lijenn** [comment]
@lzim @staceypark 
Please see the above for @branscombj's system stories for review and checklist above on what still needs to be completed. 

Thank you Jane for your work on this 💪!

**Comment by lzim** [comment]
Hi @branscombj @lijenn and @staceypark!

I’ll review this later today & mention Jane’s questions to @TomRust when we meet too.

Thank you, Jane! 🚀

**Comment by branscombj** [comment]
@lzim @TomRust @jamesmrollins Should this AGG model definition (i info) say "and referred to" a new service instead of "and start" a new service?? 

![image](https://user-images.githubusercontent.com/29778290/96293023-183d4600-0fb8-11eb-8c40-87ace6ffebae.png)

**Comment by branscombj** [comment]
### Wait Time Affects Referrals

The delay to starting a service, for patients who are waiting after either their initial intake or their care plan review, is affected by two things: the number of patients waiting to start the service and the starting rate for the service. As the delay increases, it affects treatment decisions by making the team less likely to refer patients. This allows the number of patients waiting to start to gradually drop, which in turn lowers the delay to starting that service.

**Comment by branscombj** [comment]
### RVI Delays Affect Treatment Decisions (AGG)

The actual return visit interval for patient appointments is affected by two things: the number of appointments on the books and the rate at which appointments are being completed. As the return visit interval increases, it affects treatment decisions by making the team less likely to refer patients to that service. This lowers the treatment decision rate for that service, reducing the number of patients waiting to start and subsequently in the service, which lowers the booking rate for that service and the number of appointments on the books, allowing the return visit interval to shorten.

**Comment by branscombj** [comment]
@lzim @staceypark @lijenn Done with my stab at these except as questions noted above.

**Comment by lijenn** [comment]
Thank you @branscombj! 
Would you also be able to write out r21 tt reports in a narrative form for these model manuscripts + SP (#1511)?

**Comment by TomRust** [comment]
hi @branscombj! Those loop descriptions look good to me!  I'm tempted to suggest adding something about Little's Law (to explain exactly how the number of patients waiting to start and the starting rate determine the wait time.  I just love how the units work out, i.e., patients / (patients/day) = days), but I'm not sure the average user would be helped by those details.  :-)

**Comment by lzim** [comment]
Hi @TomRust and @branscombj! 
Happy Thanksgiving 🦃 

This is a great point. I personally think that a little plain speak about Little's Law/queueing theory would be very effective, if added using our terms from our _MTL_ models._ It is so fundamental, but unfamiliar to most clinicians. In fact, even considering units carefully in relationship to time is not emphasized in the most common health science, behavioral science, statistical training most health professionals receive. A clear explanation could be an "Aha! moment" for some learners.

Moreover, for our scientific readers (not just frontline folks) the fact that it is a law that always holds in all situations is desirable for scientific advancement in the field of quality improvement/implementation science where the common answer to most problems is "it depends."

Would you want to say more than you do above about the conservation of staff time or about initialization and equilibrium/steady state? I always find the former (conservation) easy to explain, but struggle with explain the latter (initialization, equilibrium).

**Comment by lzim** [comment]
Hi @TomRust  Any thoughts about adding the Little's Law (see my comment above).

Also: Cross-ref: #1568 on this.

**Comment by branscombj** [comment]
> Hi @TomRust Any thoughts about adding the Little's Law (see my comment above).
> 
@TomRust @lzim Is something like this what you have in mind?

Many of the relationships in the MTL simulation models follow Little's Law, a simple but elegant formula. It states that the average number of, in this case, patients waiting to start care, is equal to the average starting rate (in patients per week) times the average wait time (in weeks). Or conversely, the average wait time is patients waiting to start divided by start rate.

**Comment by staceypark** [comment]
cross-ref #1511 from 1/11 #mm meeting: 
@TomRust @branscombj 
#2 Priority #1510 & 1511 - This is for facilitator training - We'll need no later than April (~ when wave 1 teams in session 5).
Tom will review Jane's questions about #1510 & #1511 Telling each "System Story" of each Module.

**Comment by TomRust** [comment]
That looks great! Maybe change that last sentence to explicitly state the units: "Or conversely, the average wait time _is the number of_ patients waiting to start divided by _the number of patients starting per week._

**Comment by staceypark** [comment]
from 2/22 mm meeting:
@branscombj will wrap this one first, by resolving the last few discrepancies based on Lindsey & Tom's comments.
Then she will turn to #1568 and wrap it by end of week, keeping in mind @lzim is working MTL Facilitator Manual on Friday 2/26

**Comment by branscombj** [comment]
**Systems Stories for CC, MM, PSY, and AGG**
I have compiled all of the above systems stories and notes about telling them into a table. I do not see responses from @lzim or @TomRust to the specific questions posed above, so those questions are highlighted in yellow in the table. I've also included and highlighted the other typos and potential errors in the sim UI that I found when working on this.
[FeedbackLoopsTable.docx](https://github.com/lzim/teampsd/files/6050454/FeedbackLoopsTable.docx)

**Comment by branscombj** [comment]
> @lzim @TomRust @jamesmrollins Should this AGG model definition (i info) say "and referred to" a new service instead of "and start" a new service??
> 
> ![image](https://user-images.githubusercontent.com/29778290/96293023-183d4600-0fb8-11eb-8c40-87ace6ffebae.png)

This is another question from above but not included on my compiled FeedbackLoopsTable attachment.

**Comment by branscombj** [comment]
Here is another question not included on my compilation document:
In AGG, we define New Patient Wait Time as "The average wait time for new patients to start in medication management, based on the number of patients waiting and the rate at which they start service." However, there is only one arrow to it, from the Number of Patients Waiting - not from Starting Rate. Shouldn't there be an arrow from Starting Rate too? It doesn't make sense that wait time would be only a function of how many are waiting.
![image](https://user-images.githubusercontent.com/29778290/109554254-fdb8c480-7aa1-11eb-925f-808e63b21352.png)

**Comment by jamesmrollins** [comment]
Hi @branscombj - The Start Rate has a direct affect of the size of the Patients Waiting to Start queue.  Drawing an arrow from the stock and the flow would be redundant? And story-wise you can see patients waiting (in the form of a backlog), but you cannot necessarily see patients starting.  My two pennies worth.

**Comment by dlkibbe** [comment]
@jamesmrollins @lijenn There is an apostrophe in the wrong place on the Aggregate module
should be patients' engagement vs. patient's engagement

![image](https://user-images.githubusercontent.com/31182258/122571976-4d080e00-d01b-11eb-8f05-a494a8c6dcf9.png)

**Comment by lzim** [comment]
@staceypark  We need to collate these in to their respective manuscript sections by the end of sept_epic.

**Comment by lzim** [comment]
@branscombj Are you able to help with SP after all?
I believe that is the last thing for this, right?

**Comment by lzim** [comment]
Just checking on the SP model too @branscombj  :smile_cat:
