### ISSUE TITLE
New Bug from Community: AGG RVI Delays Affects Treatment Decisions. Remove s from Affects

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#1512]
AGG model diagram - Label for balancing loop at the bottom reads RVI Delays Affects Treatment Decisions. Remove s from Affects.<br/><br/><br/><br/><br/>

**Comment by jamesmrollins** [comment]
Completed.

![image](https://user-images.githubusercontent.com/30132017/98295265-27376880-1f66-11eb-9de6-e407dd86f9dd.png)
