### ISSUE TITLE
wk4 feb_epic: Setup Teams for MTL Facilitation

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1513]
Discuss how the process for setting up Learners into MS Teams would look like.

**Comment by staceypark** [comment]
moving to december until we have GFE figured out

**Comment by lzim** [comment]
This is blocked by the sites selecting their teams during co-planning.

**Comment by lijenn** [comment]
Discussed 2/18 HQ WG:
We will not use Channels for the team meetings, need to add the Mute & Pin feature in the Teams Cheatsheet.

**Comment by lijenn** [comment]
That it is a separate invite for the two team meetings - Jenn to do first.

**Comment by lzim** [comment]
@lijenn 
@staceypark 

I am rethinking this decision in relation to #1705.
I've added a blocker.

**Comment by staceypark** [comment]
@lzim can you clarify what you mean by rethinking the decision? Is there something you would like to change?

**Comment by lzim** [comment]
@staceypark 
@lijenn 
@anthonycpichardo 

Following yesterday’s discussion.
We need to set up today (at a minimum)
- 570 PCMHI
- 666 Casper

**Comment by staceypark** [comment]
mainly tracking in #1705. closing this one.
