### ISSUE TITLE
New Bug from Community: Submitting a Bug Report - Red Warning on right of my screen saying Email Error or Error Email. 

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#1515]
When I submitted a bug report with a screen grab attached, I saw a red warning-like box appear in the upper right of my screen saying Email Error or Error Email. The report appeared to be sent, though. I'm going to check again with this one, without attaching an image and see if I see it this way too.<br/><br/><br/><br/><br/>
Yes, I did see it.

**Comment by lzim** [comment]
Here is the screenshot of this issue, which I replicated accessing https://mtl.how/sim via my VA Citrix login. 

![Screen Shot 2020-10-19 at 3 14 14 PM](https://user-images.githubusercontent.com/7454688/96517502-e4fbf080-121d-11eb-8359-e7982b850fe5.png)

**Comment by lzim** [comment]
So...this issue seems to only be happening from my VA Citrix log-in and did not replicate from my Mac laptop using Chrome.

@anthonycpichardo @jamesmrollins @staceypark @lijenn 

I was able to submit a bug #1537 from my personal laptop and I can confirm two things:

1. I received an email about my bug at my VA email:
![Screen Shot 2020-10-19 at 3 26 06 PM](https://user-images.githubusercontent.com/7454688/96518461-d44c7a00-121f-11eb-91ab-822df8d317ed.png)

2. The MTL Help Inbox also received a corresponding message: 
![Screen Shot 2020-10-19 at 3 27 24 PM](https://user-images.githubusercontent.com/7454688/96518498-e4645980-121f-11eb-8d04-6cda62c309f9.png)

**Comment by jamesmrollins** [comment]
@lzim @staceypark @anthonycpichardo @lijenn  I am going to login and check this out for myself. 

I am wondering if the GitHub Restful API is being interfered with by domain security?  I don't think we ever tested this with Citrix.  

@lzim, are you remoting your Menlo Park desktop through Citrix, or using one of the organization desktops?  If @lzim is using an organization desktop, @anthonycpichardo, can you try to replicate the problem with your remote desktop?  

Thanks, James

**Comment by lzim** [comment]
I used V21 Remote Desktop to create this error.

**Comment by jamesmrollins** [comment]
Hi @lzim.  Update from @anthonycpichardo and I regarding V21 and V01 General Citrix testing.

1.  Anthony successfully submitted a bug report from his Citrix enabled physical desktop (see #1543 )
2.  Anthony successfully submitted a bug report from a Citrix V21 desktop (see #1544 )
3.  Anthony successfully submitted a bug report from a Citrix V01 General desktop (see #1545 )
4.  All bug reports submitted to mtl.help in Outlook.

**Conclusion:**  Citrix is not blocking the API. 

**Updated Hypothesis**
When @lzim was attempting to submit bug reports, communications interruptions prevented the API from working, that was coincident with using the V21 desktop.  

**Recommendation**
@lzim login with V21 desktop and attempt to submit a bug report to confirm it is a consistent error.

**Comment by jamesmrollins** [comment]
@hirenp-waferwire , please change the outgoing email and issue titles from "New Bug Report from Participatory Learning" to "New Bug from Community."  Thank you, James

**Comment by lzim** [comment]
Thanks @jamesmrollins 

Lucky @anthonycpichardo 😂 Another possibility is a Mac/PC issue.

@lijenn Since you're a Mac user would you have any time tomorrow to see if you can successfully submit a bug from the Bug icon of the Sim Nav Bar via Chrome on your V21 Virtual Desktop?

**Comment by jamesmrollins** [comment]
Hi @lijenn - Did you get a chance to run the experiment @lzim requested above?  Thanks, James

**Comment by lijenn** [comment]
Hi @jamesmrollins I did, that result was in #1553.

**Comment by jamesmrollins** [comment]
@lzim - based on reviewing the evidence, can you try V21 from your desktop again?  Both Anthony and Jenn are able to push bugs through, which is leading me to believe the issue was simply a connection problem that coincided with your desire to submit a bug.  ~ James

**Comment by lzim** [comment]
@jamesmrollins  I just submitted one from V21 just fine. 
And, I got the email for Bug #1571, which when to the bug_tracker for triage, and I've already closed it.
I'll close this one too 👍
