### ISSUE TITLE
wk2? 2016 Paper Fee w/ PAVIR

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1517]
Need to talk with Luanne to get the 2016 paper Open Source.

**Comment by lzim** [comment]
Thanks @lijenn

In the email thread, Luanne sent the PAVIR information. The next ste is to fill out the rest of the information in the email and send it _to the journal_.

If you can draft the information, I can review & send to the journal this afternoon.

Thanks!

**Comment by lijenn** [comment]
@lzim I emailed you the info filled out to you last Friday! Let me know if it got lost and I can send it again.

**Comment by lzim** [comment]
Hi @lijenn Yes, I definitely got this email and I hope I can find time to still do this today, if possible.
Thanks!
