### ISSUE TITLE
wk2 Add Pivot Reset to xxx_facility.xlsb

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1518]
## description:  

**Development**

Based on the user feedback for the Telehealth/Stockton Data UI, let's add in a fiscal year view/filters for the Viz tabs on both the Data UI and Facility.xlsx files.

Each button will look as follows. 
![image](https://user-images.githubusercontent.com/39805164/99286061-3384b680-27ed-11eb-8a54-a1f1fd32ba01.png)

"Reset Pivot Chart" button exists in the data UI but not in the Facility Data via the Quick Explore function. Previously the facility data was a splashpage so this was not needed, but now that we are back in excel, it would make sense to add the button to mirror the data UI.

- Update session 2 instructions and cheatsheet to include quick explore details for facility data

**Comment by staceypark** [comment]
Reviewed and re-clarified requirements with @anthonycpichardo 
- "Reset Pivot Chart" is meant to reset the filters informing the data displayed on the chart, not the physical placement of the chart on the sheet.
- Default view of each sheet should not have the chart overlapping this button.

**Comment by lzim** [comment]
Thanks @staceypark 
This is currently really hard to navigate. Is it only hard to navigate in the facility file or does this need to be addressed for Data UI too?

@anthonycpichardo

**Comment by staceypark** [comment]
@lzim what do you mean by its hard to navigate? Do you mean because it's hidden behind the viz?

**Comment by lzim** [comment]
@staceypark 

Once you drill down, I think it’s hard to know how to reset and get back to the prior viz.

Does that make sense?

**Comment by anazariz** [comment]
## description:  

**Development**

Based on the user feedback for the Telehealth/Stockton Data UI, let's add in a fiscal year view/filters for the Viz tabs on both the Data UI and Facility.xlsx files.

Each button will look as follows. 
![image](https://user-images.githubusercontent.com/39805164/99286061-3384b680-27ed-11eb-8a54-a1f1fd32ba01.png)

I updated the initial version of the reset button code (completed prior to the Nov/2020 Facility propagation) and implemented the required changes. The reset button now resets the fields to their original values even if the filter field was changed (e.g. clicking on the lines and picking a different field). I also relocated vizEnc's pivot table so without the extra lines the page is initially centered better.  I will propagate the workbook today after testing. I will also update the ticket as well.  
 
**Details:**
1) The first pass of this work did not take into account the filter changes that could occur by clicking on a chart line. 
2) There are subtle differences between the data in Data UI vs Facility that makes copying the exact functionality from the Data UI not work in the Facility. Example: on Facility vizDiag there is "values" of the right side of the chart, which does not exists on the Data UI chart. So the code between the two workbooks is different in certain areas. 
3) Data UI had a data model that did not exist in the Facility workbook. Without it, vizEnc and vizHF would produce errors. So I created a data model (relationship).
