### ISSUE TITLE
NOV Epic: Bookdown Trigger from gh-pages branch.

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1532]
@jamesmrollins  has a better solution on how to trigger the bookdown action to generate the manual instead of us having to manually trigger the action from the Master branch (which doesn't make sense anyways since the manual/bookdown lives in the gh-pages branch).

Proposed solution/documentation for @lijenn  to test:
It is somewhat different than the general branch strategy, since it has its own dedicated gh-pages branch.  We could create a standing bd-QA protected branch.  Then, when bd-QA is merged into gh-pages, it could trigger the renderbook action automatically.

**Comment by jamesmrollins** [comment]
Hi @lijenn and @staceypark .  I have been working diligently for the last 2-3 days trying to get this bookdown rendering action to work any other way besides committing a file directly to the master branch.  While @anthonycpichardo indicates that he can get it to work in the research repo, I haven't been able to replicate his results there either.  I believe it is an issue with the jamesives/deployment action and I have sought community support in his github thread.  So - still working on it, but no luck so far.

**Comment by jamesmrollins** [comment]
@lijenn @staceypark @lzim  Update

I posted this issue with the deploy action author [here](https://github.com/JamesIves/github-pages-deploy-action/discussions/493).  However, I have not received any response.  

I have also turned the issue over to @hirenp-waferwire for troubleshooting, but assigned this a lower priority.  I want to set up an action that takes care of the md lintering and then renders and deploys to gh-pages at the appropriate step in the process.  

**Let me know if you want me to up the priority.**

**Comment by lzim** [comment]
@jamesmrollins  I think this is an okay order of priority.

@staceypark and @lijenn  Let us know if you think otherwise.

**Comment by jamesmrollins** [comment]
@lijenn @staceypark  Update

I think Hiren got renderbook.yml (renamed bookdown.yml) working on the TeamPSD repo. It works on a pull request to gh-pages.  Tonight, I am going to work with Hiren to do a scheme where a pull request to gh-pages will trigger the .md linter, link and spell checker.  Then a push or merge to gh-pages will trigger the renderbook process.  That should automate that workflow.   I'll give you an update on Tuesday morning.  Turns out that you have to set a PRESERVE function to "true" for it to deploy artifacts properly.  Thanks, James

**Comment by lijenn** [comment]
Thanks for troubleshooting this, James! Keep me posted, looks like it's going well.

**Comment by jamesmrollins** [comment]
Hi @staceypark and @lijenn,  I think we have the actions working in the lzim/Teampsd repo. 
 
They are documented in the Team PSD manual as follows:

  1.  When you are updating the Team PSD Manual, make a feature branch from the gh-pages branch, by navigating to the gh-pages branch and naming a  new one like so, "feature-gh-pages_*"
  2. Remember that format of the branch name is important, so don't add spaces and use the exact format.
  3. Navigate to the new branch and edit your documents.
  4. Open a pull request to merge the branch from the freature-gh-pages to gh-pages.
  5. The pull request will trigger the markdown linter, spell checker and link checker.
  6. Once you are satsified the document is good to go, then merge the two branches.
  7. The merge will cause the renderbook action to fire.
	
When updating a .md anywhere else in the repo, a pull request to QA will fire off the linters as well. 

Happy Veterans Day (well, tomorrow anyway) - James
