### ISSUE TITLE
may_epic story_7 - Automate MTL Blue tt reports 

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1536]
Review the grants and determine what type of feedback the TT report should provide the MTL Red & Blue teams.

**Comment by lzim** [comment]
Cross-ref #675.

Is there a new **issue_task** or **feature_card* that's depends on this (e.g., creating or automating the _MTL_ Red tt reports)? 

FYI: @anthonycpichardo & @staceypark

**Comment by anthonycpichardo** [comment]
There is not, we can create a new issue card for automating the MTL Red tt reports.

**Comment by lzim** [comment]
**Discussed at 11/2/2020 Workgroup Leads**

**1. Can we get tt_reports exported directly from the Sim (what about Red conditions?)?**
- If we move this from RedCap (keep RedCap for research measure only), then this can be in the Sim and we can use mtl.how/menu for blue and Red.

**2. Do we want to include the needs assessment in Red Sites to narrow down to which Team Data Table is really the focus?** 
- Does this fit w/what we said in the R01 about AF (and in IIR about uQI)?

**3. Ultimate feature request functionality here would be that when teams click on the "Export" icon from the Expanded Outputs and Text Section, it would produce all their work to date, i.e., their tt_report.**

FYI: @staceypark @lijenn @anthonycpichardo @jamesmrollins

**Comment by jamesmrollins** [comment]
Regarding @lzim's ultimate feature request: 

1.  Will @staceypark or @lijenn  please attach here or provide to me via email and example tt report? 
2.  If all the data contained in the tt report is generated from the sim UI, then I imagine we can automate the whole thing.  BUT, if there is other data coming from somewhere else, I would need to get my arms around that:
  - What data not sim ui related, is needed for tt report?
  - From where is it derived (i.e., sharepoint)?
  - What format does it follow (i.e., xlsx)?
  - To where would we want to post the export?  Right now, it downloads to the user's desktop.  Is this still good?

3.  Regarding REDCAP.  My sense from the last meeting was that @lzim thought having the user follow a link to navigate to a survey, to find the starting point model was fine as is.  BUT, I am unclear about how surveys, in general, are used in the program.

**Comment by jamesmrollins** [comment]
Below is the reference tt report I will use for the analysis, provided by @lijenn . 

1.  [sample_tt_report](https://github.com/lzim/mtl/blob/master/blue/session12/s12_resources/tt3.pdf)
2.  Regarding data:
  a. Team Starting Survey Red Cap data is not associated with the Sim UI and must be presented with each report.
  b. All other data from Sim UI Export
  c. P-chart, % EBP, where is this data coming from?

**Comment by jamesmrollins** [comment]
@staceypark @lijenn @anthonycpichardo @lzim

### OBSERVATIONS
1.  This is really doable.  In fact, looking at the format for the reports, we will likely have greater design flexibility and be able to conform more closely to the Team PSD standards for font, color and iconography, if we use .html with an associated export function to .pdf.  
2.  Will need a RedCap export of some kind.  We could use a RestfulAPI to move it over to the Sim UI automatically when the team is set up.  
    **Another alternative, is to put the survey into the Sim UI.**  
    - It would be relatively simple series of popups triggered by an icon on the Home page.  
    - The "Take the survey" icon would appear on first login and stay until the survey, or survey period is complete.
    - OR, we could control when the icon appears and disappears for a given team, from the facilitator dashboard.
3.  The data for the P-Chart, where is it kept?  Might need to import that as well.

**Comment by jamesmrollins** [comment]
The P-Chart is created by hand and the data must be queried using a SQL-R interface and then constructed and moved by hand to the tt report.

**Comment by staceypark** [comment]
12/9 support wg:
- _mtl_ red tt report: create tables similar to team data table in the sim (see below)
- we want 3 tt reports similar to _mtl_ blue with new query run for all team data tables (cc, mm, psy, agg, sp tabs) each time:
  - baseline
  - 3 months
  - 6 months (including pcharts* just like _mtl_ blue)
- *adding pcharts to the tt report is a SQL-R workflow that needs to be fleshed out and automated as well

![image](https://user-images.githubusercontent.com/31089501/101696717-60626d00-3a2b-11eb-81be-ae25134e0e9a.png)

**Comment by lzim** [comment]
@jamesmrollins 
@anthonycpichardo 
@staceypark 
@lijenn 

Can we discuss this on Wed next week 2/17 at wk3 sim_workgroup?

Could you join for 30-min at 3:30PM Anthony? 

As we’ve discussed a few times, while **Story 7** didn’t officially make the cut for the **2021 first 6-month roadmap**, I want to briefly touch base to see if there are any ways to **slice the users of this Story 7 automation into ignorable and non-ignorable** so James could make some relatively _independent progress_ that would **free up capacity on Team PSD support side** when the co-facilitators of **wave 1 Blue** teams prep for  **session 4** https://mtl.how/menu during **wk3 apr_epic**

As we discussed last month, I think we should adjust the scope of Story 7 because there are some relatively quick wins available, I think, but it would have to be with maximum independence for James and minimum reliance on Anthony & Stacey. 







teams

**Comment by lzim** [comment]
@jamesmrollins edited the title of this card to reflect needing to split this into weekly cards over **mar_epic** if this were to be done by **wk4**  **april_epic** when the _MTL Blue_ teams will receive their **tt1 report.**

**Story 7 "automate tt reports" on the LucidCharts 6 month roadmap would to be re-sliced to focus on:
- [ ] completion of mtl.how/menu outside of RedCap
- [ ] compiling of report all on Forio

**Comment by jamesmrollins** [comment]
This card does not have an estimate since coding effort estimate is in issue #1748
