### ISSUE TITLE
New Bug from Community: Testing issue #1515 from non-VA machine to see if I get the red Email Error message

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#1537]
Testing issue #1515 from non-VA machine to see if I get the red Email Error message.<br/><br/><br/><br/><br/>

**Comment by lzim** [comment]
Cross-ref #1515 for details on differences between VA test and non-VA test.

**Comment by lzim** [comment]
Closing since this is covered by original issue #1515

**Comment by hnorthcraft** [comment]
#adjudicate_memo per above comment, efforts tracked on different card. Assigning dup label.
