### ISSUE TITLE
Automate the MTL tt reports

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1538]
Automate the MTL  TT Reports to be sent out to the teams

**Comment by lzim** [comment]
Ideally, the automation of reports would be for both MTL Red & MTL Blue. And for MTL Blue, would be across three platforms:
- BISL (to become Power BI)
- Redcap
- Sim

@anthonycpichardo 
@staceypark 
@jamesmrollins

**Comment by anthonycpichardo** [comment]
Hey  @staceypark  can you link a copy of a TT report here so I can reference the items we need?

**Comment by staceypark** [comment]
https://github.com/lzim/mtl/blob/master/blue/session12/s12_resources/tt3.pdf

**Comment by anthonycpichardo** [comment]
Moving this item to the backlog

**Comment by lijenn** [comment]
@jamesmrollins this is now being tracked in their respective cards focusing on MTL blue and red tt reports:
Blue: #1536 
Red: #1812 

Closing this card to prevent duplicates.
