### ISSUE TITLE
WK4 Jenn loses permissions when granting Team Folder Access

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1539]
When granting users access to Team Folders Jenn loses her permissions to the Sharepoint.

First step will be to email BISLSharepointNotifications. I suspect it has something to do with her email again.

**Comment by lzim** [comment]
Let's stay on this as we're going to need Jenn functional with this within the next 30 days.

**Comment by lijenn** [comment]
Doug has resolved the issue. He was unable to reproduce the problem, but says he has have a better idea now of different permission groups that play a role in the issue. 

If others experience the same problem, we will need to contact BISLSharepointNotifications.
