### ISSUE TITLE
Logging in to simUI

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#154]
@lzim Please confirm what Project/Environment and World I should be using now and what our MTL Facilitate Pilot learners will be using.

I saw a couple of datasets with the up-to-date naming convention in Epicenter yesterday but could not get those to upload to the simUI.

I'm in Version 1.6 PROD (https://forio.com/app/va/va-psd-sim/login.html) 
in world 640a0_mpd-user-training-may-2018 (because the one that looks more current, team_mtl_facilitate_pilot_2018_09, won't load)
with data 640_a0_blue_2018_08_30.xlsx

**Comment by lzim** [comment]
Thanks @branscombj 

What you've noticed is that @staceypark has mapped us to a new group for the *MTL Facilitate Pilot.* 
named:  "team_mtl_facilitate_pilot_2018_09" 

But, I am not getting it to load either. Any ideas @staceypark and @jamesmrollins ??

I also asked @staceypark to add Team PSD members to this "individual world" group for next week:
"team_mtl_facilitate_pilot_2018_09"

@jamesmrollins  When I go to the Epicenter Admin at mtl.how/facilitate I see the data file we want to load into the new (currently unavailable) group Stacey created for us to use this week:
File is: "640_a0_blue_2018_08_30.xlsx"

FYI: @dlounsbu @dlkibbe @TomRust

**Comment by staceypark** [comment]
@jamesmrollins @lzim @branscombj @dlkibbe @TomRust @dlounsbu 

Thanks @branscombj and @lzim 
Fixed the issue and tested it.  Everything should work fine now.
It's because the world mapping xlsx in the Interface tab wasn't updated with the world mapping within the groups.
