### ISSUE TITLE
wk?? Task: Power Platform Alternatives to Dynamics

### ISSUE THREAD

**Issue by anazariz** [lzim/teampsd#1542]
**Power Platform Alternatives to Dynamics:**

**Comment by lzim** [comment]
@anazariz and @anthonycpichardo 

Proceeding with this should be dependent on careful review of draft roadmap in #1541 focused on VA processes. In other words, we really need your help with due diligence to help identify the straightest path through the VA environment for the integrated functionality we need. 

It is not clear to why, from a VHA perspective, which as we clarified in support workgroups yesterday is THE most important frame to approach plans for any of the Microsoft 365 work (i.e., procedures for approval [VIPR, VASI, etc.], navigation of relevant VA organizational entities and their associated funding needs [OIT, Special Forces, Enterprise Cloud Computing, etc.), _why would Power Platform be any different from MSD 365?_
