### ISSUE TITLE
WK4 : Local Co-Planning SAIL

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1554]
SAIL + MHOC Critical Scores + mtl.how/data

Five documents we need for local coplanning with all sites - 4 of the 5 are available in Team PSD > Grants > final_post_covid19_site_list	
coplanning preparation notes 
	meeting 1 agenda
	meeting 1 stakeholder map
	meeting 2 agenda
	meeting 2 process map

Task: put the FY20 Q3 MH SAIL data for the NIH sites from this example visn04_529_butler_notes.docx (note: we should use 04, not 4, so that these sort) in the folders (path is Team PSD > Grants > 0_post-covid_site_selection)

**Comment by lzim** [comment]
FYI: @staceypark  and @lijenn 

- We hope to start scheduling coplanning meetings this week and next to report them in our R01 progress report. 
- We need the "notes" information to start the co-planning meetings with sites and maybe this just covers SAIL?

Or, will this also cover the criticality information too?

NOTE:
- I emailed John K and Jay C today about the site questions we had this morning.
