### ISSUE TITLE
 Automate Local CoPlanning SAIL + Criticality + mtl.how/data population

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1555]
Outline Feature card to Automate the process of generating Local Coplanning Documents:

Five documents we need for local coplanning with all sites - 4 of the 5 are available in Team PSD > Grants > final_post_covid19_site_list

coplanning preparation notes 
	meeting 1 agenda
	meeting 1 stakeholder map
	meeting 2 agenda
	meeting 2 process map

We need to add this "coplanning preparation notes" to https://mtl.how/documents detail_facilitate like Jenn did already for the other 4 docs.

**Comment by lzim** [comment]
@anthonycpichardo  

Whoops, I missed #1554 at first. This is for the feature request is see...not the short-run work for wave 1.

**Comment by hnorthcraft** [comment]
#adjudicate_memo dup #1554
