### ISSUE TITLE
"Bug": SIM UI not loading (outside and inside VA)

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1563]
@jamesmrollins  

I can't seem to login into the SIM for some reason, experiencing this issue no matter what browser and within and outside the VA. 

Trying to log into the SIM via facilitator dashboard and it gets stuck at the loading screen right before the dashboard:
![image](https://user-images.githubusercontent.com/59668647/97638149-331cab00-19f9-11eb-8534-e02f86acb354.png)

FYI
@lzim @staceypark

**Comment by lzim** [comment]
Thanks for reporting this bug @lijenn !

@jamesmrollins I also encountered this last night in/outside VA, but I'm just getting a chance to post my screen grabs of my inspector:

**Citrix V21 Desktop using Chrome**
![Screen Shot 2020-10-28 at 6 10 30 PM](https://user-images.githubusercontent.com/7454688/97638489-dd94ce00-19f9-11eb-8430-b9108364fe9c.png)

**Personal Mac Laptop using Chrome**
![Screen Shot 2020-10-28 at 6 10 41 PM](https://user-images.githubusercontent.com/7454688/97638538-fdc48d00-19f9-11eb-8e0e-c3441f652443.png)

**Comment by lijenn** [comment]
Update: Using @staceypark's login works just fine...

Attached is also my 'View Page Source' as well when I encountered the same issue.
[sim_ui_not_loading_issue_1563.pdf](https://github.com/lzim/teampsd/files/5461585/sim_ui_not_loading_issue_1563.pdf)

**Comment by jamesmrollins** [comment]
I believe it is because you are not set up as facilitators in any groups.  So you login as a facilitator, because you are a part of the facilitator group, but it cannot find any instances in any of the other groups where you designated as a facilitator.  Try it now.  I just named @lzim and @lijenn as facilitator in several of the groups.

**Comment by lzim** [comment]
@jamesmrollins 
Yes, that does seem to have resolved it. I can see the r21_manuscripts and one other team.
But, do we know why we "lost" the mapping I had last week? Something related to promoting from TEST to PROD still?

Also, one other quick question - Do we need to have "_VA-PSD-Facilitator_" or can we just use "_Facilitator_"
![Screen Shot 2020-10-29 at 3 39 18 PM](https://user-images.githubusercontent.com/7454688/97640739-a83eaf00-19fe-11eb-8bc1-736d6b1461d2.png)

FYI: @staceypark @lijenn

**Comment by jamesmrollins** [comment]
@lzim - what mapping are you speaking of?  We did change how facilitators are identified.  So you must be in the facilitator group (that provides the login) and you must be identified as a facilitator in the target groups (that provides access to the groups active world ids). I am not sure on the VA-PSD, Facilitator.  I will check it out.

**Comment by lzim** [comment]
I'm referring to the mapping that @lijenn  and @staceypark  were doing for all the _MTL_ facilitators when we identified the bugs about not being able to pull up prior experiments, etc.
- For example, I was identified as a facilitator of team 4 last week, but now I'm apparently not.

 @lijenn and @staceypark 
Are you able to review the facilitator mapping again? per @jamesmrollins "We did change how facilitators are identified." 

I'm guessing you haven't already, or we wouldn't have been surprised that we could not get in the Sim.

**Comment by jamesmrollins** [comment]
@lzim I don't think we changed any of the previous mapping.  However, I should've checked the mapping when we migrated to PROD to ensure you were set up properly.  My bad! 😣

**Comment by staceypark** [comment]
@jamesmrollins how come we can't see "individual_login" from the initial login drop-down. I get that it wouldn't showup in the Dashboard since it doesn't end in "ind" or "team". But shouldn't it show up in the original dropdown then?

**Comment by jamesmrollins** [comment]
@staceypark the group naming must follow the "_ind" and "_team" suffixes naming convention. We need that in order to organize the parent/child relationship in the drop down menu.  The only exception is the r21_manuscript group, as I had Hiren hard code that one in, because I knew you were accessing experiments and such.

I recommend renaming the "individual_group" group to "Individual_group_ind."  Don't rename this group, as this won't work (I don't think they allow it any longer).  BTW, I will update the lucid workflows to reflect these procedures.

**Comment by staceypark** [comment]
@jamesmrollins Right, I understand that for worlds to show up on the Dashboard dropdown below, they must have the "ind" or "team suffixes following the naming convention to be a "child" to the "parent" of the facilitator login.
![Screen Shot 2020-10-29 at 4 32 32 PM](https://user-images.githubusercontent.com/31089501/97643229-5b5dd700-1a04-11eb-8cbd-2bec48a73150.png)


But, for the existing "individual_login" group, we had told and shown the facilitators this would show up on the same level as the "facilitator_login" or "admin_login" dropdown, when you first login. So like a normal login to a world, in the way a team would access it.
![Screen Shot 2020-10-29 at 4 30 39 PM](https://user-images.githubusercontent.com/31089501/97643155-36696400-1a04-11eb-813f-45872837bee9.png)


> @staceypark the group naming must follow the "_ind" and "_team" suffixes naming convention. We need that in order to organize the parent/child relationship in the drop down menu. The only exception is the r21_manuscript group, as I had Hiren hard code that one in, because I knew you were accessing experiments and such.
> 
> I recommend renaming the "individual_group" group to "Individual_group_ind." Don't rename this group, as this won't work (I don't think they allow it any longer). BTW, I will update the lucid workflows to reflect these procedures.

**Comment by staceypark** [comment]
@lijenn @lzim @jamesmrollins 
I just chatted with James, and he says you cannot be a facilitator and have regular world assignments at the same time.

**Comment by lzim** [comment]
> @lijenn @lzim @jamesmrollins
> I just chatted with James, and he says you cannot be a facilitator and have regular world assignments at the same time.

Thanks, I think that all facilitators will only need facilitator logins. But, they will need to be listed as facilitators for all their groups and worlds, which sounds like it still needs to be revisited at HQ (meaning: check the current mapping for our facilitators)?? And, we should make sure that these types of mapping don't have any stability when new features move from TEST to PROD.

**Comment by hnorthcraft** [comment]
#adjudicate_memo @lijenn @lzim best estimate for SP?
