### ISSUE TITLE
wk3: r01 Protocol review

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1567]
r01 protocol ready for review after edits and shortening from @dlkibbe & @dlounsbu 
 https://osf.io/c43ph/

**Comment by lijenn** [comment]
Adding a dependency from me on #1379 since we might need to add in references for the supplementary docs.

**Comment by lzim** [comment]
@anthonycpichardo will review the content for the CONSORT checklist details next. Thanks!

**Comment by staceypark** [comment]
@anthonycpichardo has finished his draft of the consort and @staceypark will review next.
