### ISSUE TITLE
ICEBOX: Webex (VA Teams back-up)

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1577]
Look into Webex due to current VA Teams issues

**Comment by lijenn** [comment]
Webex Features:
- Very similar UI features to Zoom
- Non-VA members can join the meeting link, either downloading the Webex desktop app (?) or join via browser
- Can record/save chat like Zoom, don't know where this is saved yet
- Will need a Chapter in Team PSD Manual if we move forward with Webex (dependent on if we move forward with GFE laptops #1578)

**Comment by lijenn** [comment]
Moving this to Icebox in case we need Webex, Teams seems to be like the best option as of now.

**Comment by lijenn** [comment]
closing this since Teams seems to be commonly used with the co-planning meetings we've been having.

**Comment by hnorthcraft** [comment]
#adjuducate_memo @lijenn 
 looks like there was some work, can we update the SP? Or is it actually 0?
