### ISSUE TITLE
wk1: GFE shipment for non-PAD folks

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1578]
See if we can get government furnished equipment (GFE) for the team in case Webex and Teams either don't work out or aren't favored by the field. 

Non-PAD members:
- [ ] David N.
- [ ] David L.
- [ ] Jane
- [ ] Debbie

**Comment by staceypark** [comment]
@lijenn is waiting on clarification on how non-PAD team members will pickup their GFE

**Comment by lijenn** [comment]
Updated David N., David L., and Jane and Debbie for the process. Jenn emailed the details for the request which must be done through YourIT. Closing issue.
