### ISSUE TITLE
?? "Super user feature sprint" - Fiscal Year View/Filters for Viz tabs - Data UI & Facility.xlsx

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1580]
### Check off requirements to verify progress through feature_tracker.
- [x] 1. **DEFINE in work_breakdown**
  - [x] a. **what & why** - **written definitions of requirements** in a **numbered checklist** on the **master_feature_card.**
  - [x] b. **date & who** -  **Verified** requirement definitions an **existing team meeting.**
 
**Based on the user feedback for the Telehealth/Stockton Data UI, let's add in a fiscal year view/filters for the Viz tabs on both the Data UI and Facility.xlsx files.**

Discussed 12/10:

We want the dashboard to either show the Calendar Year (current state) or the fiscal year.

The user should be able to select which view they want to have.

When in either the fiscal or calendar view we should display data up to the current date.

---
- [x] 2. **DESIGN** in **operations_to_do** and **research_to_do**
  - [ ] a. **what & why** - **_MVP_ of design** of requirements in a **algorithm map, wireframes or design** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** design **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #1619
---
- [ ] 3. **DEVELOP** in **under_development** - "frozen"

  Task Cards:
  #
---
- [ ] 4. **TEST in functional_test**
  - [ ] a. **what & why** - **TEST requirements** using **testing_checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** via TEST **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 5. **PROD in done**
  - [ ] a. **what & why** - **_DOCUMENT_ feature** using **document_tracker** for the **5 D's.** 
  - [ ] b. **date & who** -  **DELEGATE**
    - [ ] **describe_learners** [Jenn & Rita]
    - [ ] **detail_facilitators** [Jane & Debbie]
    - [ ] **document_team** [Anthony]
    - [ ] **disseminate_scientists_va** [Anthony]
    - [ ] **depend_products** [hq & ees]
  
  Task Cards:
  #
---
- [ ] 6. **closed** - fully documented, trained and ready for the next release.

**Comment by anthonycpichardo** [comment]
Meeting on this to discuss requirements 12/10 Quant_wg meeting

**Comment by anthonycpichardo** [comment]
@lzim  @lijenn  @staceypark 

For this view, how would you like to handle swapping between the fiscal year and calendar year views. Do we want to toggle a checkbox, or have a dropdown the user selects from?

**Comment by anazariz** [comment]
@lzim @lijenn @staceypark @anthonycpichardo 

I added what's called a context menu to the Data UI that will allow us to add the fiscal date filter without any additional artifacts (no buttons, etc.). To access the context menu you should right-click anywhere on the vizEnc pivot table (not the chart). Then go to the bottom of the menu and select "Switch to Fiscal Date". This will change the filter on the bottom of the screen to a fiscalyear (as seen below). Also as seen in the PivotTable Field (to the right of the screen) in the Rows section, fiscalyear was correctly added. 
To return back to the calendar date format just click reset. Please let me know if this works.     

![image](https://user-images.githubusercontent.com/39805164/101857483-700dae80-3b1c-11eb-9668-d3cf98f849dd.png)

**Comment by staceypark** [comment]
1/4 wkgp leads:
@anthonycpichardo will run point on our first "super user feature sprint" with Dr. Mathur (more efficient/feedback in meeting) & Dr. Norlander (likes to dig into data on own)
wk1: schedule meeting
wk2: go over prototype
wk3: feedback for further testing 
wk4: release for Feb

FYI: @lzim @lijenn @jamesmrollins

**Comment by anthonycpichardo** [comment]
Moving this to the backlog for reprioritization

**Comment by lzim** [comment]
@anthonycpichardo 

At **8AM Workgroup Leads** let's discuss where this **feature_request** fits in relationship to **Story 5.**
We decided not to move forward w/Super Users because @staceypark identified usability issues that precluded showing this to the **super users.**

It makes sense to make a plan for addressing those issues first.
We're going to want this in **Story 5,** so it should be linked to it.
We we will want this **batched** with whenever we review **R21 Findings** with our partners.

**Comment by staceypark** [comment]
Right click on table behind a visualization and click on "fiscal year view".
This only works through on-prem views though, not on SharePoint Online so far.
