### ISSUE TITLE
wk3??: MTL Data Resources to Stockton

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1581]
Discuss with Lindsey about what to send Stockton to get them running with mtl.how/data.
Blocked by #1667 Facility and #1668 Data UI testing.

**Comment by lzim** [comment]
@lijenn

We may want a VVC line on the VizEnc tab graph and in the table.

Let’s do a mock-up to see if this would help them.

**Comment by staceypark** [comment]
@anazariz is removing the CY/FY changes so @lijenn can send the VVC prototype to Stockton

**Comment by lijenn** [comment]
VVC Prototype was sent to Stockton/Telehealth on Fri. 11/20, no feedback yet.
Fiscal year prototype still needs to be completed in #1580

**Comment by lzim** [comment]
@anazariz 
@anthonycpichardo 
@staceypark 
@lijenn 

If everyone on the team has signed off on DEV QA & TEST QA, I recommend that we get PROD QA & close w/out the super users. 

Many folks in MTL Red will want to see this.

**Comment by lijenn** [comment]
Discussed 2/18 HQ WG:
To re-engage with Vhee from Stockton, we will want to walk through the R21 (Story 1 & 3) and how we would track this relationship (Story 6). We want to continue using ZenHub/GitHub for bugs and tasks, not for relationship management.

Closing as the Facility and Data files have been updated.
