### ISSUE TITLE
Nov epic wk?? Add Reset buttons to the facility.xlsx workbook

### ISSUE THREAD

**Issue by anazariz** [lzim/teampsd#1583]
## description:  

**Development**

Based on the user feedback for the Telehealth/Stockton Data UI, let's add in a fiscal year view/filters for the Viz tabs on both the Data UI and Facility.xlsx files.

Each button will look as follows. 
![image](https://user-images.githubusercontent.com/39805164/99286061-3384b680-27ed-11eb-8a54-a1f1fd32ba01.png)

I updated the initial version of the reset button code (completed prior to the Nov/2020 Facility propagation) and implemented the required changes. The reset button now resets the fields to their original values even if the filter field was changed (e.g. clicking on the lines and picking a different field). I also relocated vizEnc's pivot table so without the extra lines the page is initially centered better.  I will propagate the workbook today after testing. I will also update the ticket as well.  
 
**Details:**
1) The first pass of this work did not take into account the filter changes that could occur by clicking on a chart line. 
2) There are subtle differences between the data in Data UI vs Facility that makes copying the exact functionality from the Data UI not work in the Facility. Example: on Facility vizDiag there is "values" of the right side of the chart, which does not exists on the Data UI chart. So the code between the two workbooks is different in certain areas. 
3) Data UI had a data model that did not exist in the Facility workbook. Without it, vizEnc and vizHF would produce errors. So I created a data model (relationship).

**Comment by anazariz** [comment]
Was moved to #1518

**Comment by hnorthcraft** [comment]
#adjudicate_memo dup card
