### ISSUE TITLE
jan_epic(wk??): Add the stopcode 179 (Veterans Video Connect-VVC) to the vizEnc on Data UI 

### ISSUE THREAD

**Issue by anazariz** [lzim/teampsd#1584]
### Check off requirements to verify progress through feature_tracker.
- [x] 1. **DEFINE in work_breakdown**
  - [ ] a. **what & why** - **written definitions of requirements** in a **numbered checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** requirement definitions an **existing team meeting.**
  
Add the stopcode 179 (Veterans Video Connect-VVC) to the vizEnc on Data UI. As we don't yet have the VVC filter built, the following image shows the CPTCode as how the VVC filter should be placed and used.  

![image](https://user-images.githubusercontent.com/39805164/99317075-48c40a00-281a-11eb-9389-5476b4d3e73f.png)

Task Cards:
 #
---
- [x] 2. **DESIGN** in **operations_to_do** and **research_to_do**
  - [ ] a. **what & why** - **_MVP_ of design** of requirements in a **algorithm map, wireframes or design** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** design **asynchronously** or an **existing team meeting.**

Design was verified with @staceypark , @lijenn and @anthonycpichardo in a Teams meeting on 11/16./20 @ 11:00 am. 

1) The VVC column (stopCode(179) should be added to the dataEnc (tab). 
2) If SQL adjustment is needed is should be implemented  
3) The column should have 1/0 (True/False) values for VVC = True or not
4) The column should then be added to the appropriate Pivot Table on the vizEnc tab 
5) Then finally the filter should be added to page filter/chart as shown in the figure aboove

  Task Cards:
  #
---
- [x] 3. **DEVELOP** in **under_development** 

Complete

  Task Cards:
  #
---
- [ ] 4. **TEST in functional_test**
  - [ ] a. **what & why** - **TEST requirements** using **testing_checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** via TEST **asynchronously** or an **existing team meeting.**
  
In progress

  Task Cards:
  #
---
- [ ] 5. **PROD in done**
  - [ ] a. **what & why** - **_DOCUMENT_ feature** using **document_tracker** for the **5 D's.** 
  - [ ] b. **date & who** -  **DELEGATE**
    - [ ] **describe_learners** [Jenn & Rita]
    - [ ] **detail_facilitators** [Jane & Debbie]
    - [ ] **document_team** [Anthony]
    - [ ] **disseminate_scientists_va** [Anthony]
    - [ ] **depend_products** [hq & ees]
  
  Task Cards:
  #
---
- [ ] 6. **closed** - fully documented, trained and ready for the next release.

**Comment by lzim** [comment]
@anazariz and @anthonycpichardo 

Can you clarify what the next steps are for this?

**Comment by anthonycpichardo** [comment]
I believe this is complete and ready to close.

Can you confirm @anazariz ?

**Comment by anazariz** [comment]
@anthonycpichardo 

Yes, VVC was added to the vizEnc. However, per my understanding the prototype was still being evaluated/tested. @lijenn  may have more on that.

**Comment by anthonycpichardo** [comment]
@lijenn  @anazariz  where did we land on this issue?

**Comment by lijenn** [comment]
VVC was tested by you, Ash, Stacey, and I. The file with the mvp was emailed to Alka but she did not have time to review it. 
I recommend wrapping this in with the super user testing since I believe Alka's name was mentioned there as well.

**Comment by lzim** [comment]
@anazariz 
@anthonycpichardo 
@staceypark 
@lijenn 

If everyone on the team has signed off on DEV QA & TEST QA, I recommend that we get PROD QA & close w/out the super users. 

Many folks in MTL Red will want to see this.
