### ISSUE TITLE
Propose and Discuss Principles of Team Communications

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#1586]
**1. Add description:** 
Author and seek discussion regarding the principles for effective, written team technical communication to be included in the Team PSD manual.  Should be 500 words or less and explain how to effectively describe needs, assign to potential responders and follow up in GitHub discussion threads. 

**Starting outline below:**

1.  Keep it short - use an active voice.
2.  Use common words - avoid overuse of abbreviations and acronyms.
4.  State the bottom-line-up-front - what do you want?
5.  Provide facts bearing on the problem - what is important for people to know?
6.  Identify any assumptions you have made - what gaps have you identified?
8.  Briefly describe alternatives for teammates to consider.
7.  Make specific "asks" to individuals using the "@" function in GitHub and indicate when you need a response.

<< Paste screenshots here>>
 
**2. Click on the right:**  
i. **Pipelines** - prioritize in a TeamPSD (& Workgroup) pipeline  
ii. **Assignee** - assign to an individual team member producing work for the issue  
iii. **Label**- assign workgroup (lead) responsible for tracking the task  
iv. **Projects** - assign to domain-specific TeamPSD tracker (issues, features, document, manuscript, team)  
v. **Milestones** - select monthly sprint milestone within the workgroup   
vi. **Estimate** - Estimate task in complexity points   
vii. **Epics** - assign to team-wide epic and TeamPSD master plan project  
iix. **Releases** - assign to key team release grouped with other relevant issues  

**3. If you anticipate that your **issue card** or **bug card** will have **dependencies** these can be added once the issue has been submitted.   
ix. **Add dependencies** - assess for and add dependencies *blocking* & *blocked by* this issue

**Comment by lzim** [comment]
@jamesmrollins 

Let’s not overthink this. These look good to me as is. 

Will you please create a .md pull request to the Team PSD manual with this list. We’ll want these principles close to the top of the manual by chapter order, since it’s cross cutting.

I’m open to recommendations about where it fits best. Thoughts @lijenn or @anthonycpichardo?

Thanks!
