### ISSUE TITLE
Wk3 - Deploy SD-DOCs to MTL DEMO Website

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#1591]
### Check off requirements to verify progress through feature_tracker.
- [ ] 1. **DEFINE in work_breakdown**
  - [ ] a. **what & why** - **written definitions of requirements** in a **numbered checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** requirement definitions an **existing team meeting.**

1. Provide an HTML TeamPSD style consistent container to receive action generated SD-DOCs and present on the MTL DEMO website. 
2. Provide an access point or link from the main page.  

  Task Cards:
  # See #1432 
---
- [ ] 2. **DESIGN** in **operations_to_do** and **research_to_do**
  - [ ] a. **what & why** - **_MVP_ of design** of requirements in a **algorithm map, wireframes or design** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** design **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #1596 
---
- [ ] 3. **DEVELOP** in **under_development** - "frozen"

  Task Cards:
  #
---
- [ ] 4. **TEST in functional_test**
  - [ ] a. **what & why** - **TEST requirements** using **testing_checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** via TEST **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 5. **PROD in done**
  - [ ] a. **what & why** - **_DOCUMENT_ feature** using **document_tracker** for the **5 D's.** 
  - [ ] b. **date & who** -  **DELEGATE**
    - [ ] **describe_learners** [Jenn & Rita]
    - [ ] **detail_facilitators** [Jane & Debbie]
    - [ ] **document_team** [Anthony]
    - [ ] **disseminate_scientists_va** [Anthony]
    - [ ] **depend_products** [hq & ees]
  
  Task Cards:
  #
---
- [ ] 6. **closed** - fully documented, trained and ready for the next release.

**Comment by lzim** [comment]
@jamesmrollins 

Can we get the title of this card in conformance w/the wk1, wk2, wk3, wk4 feb_epic for tracking?

Thanks!

**Comment by jamesmrollins** [comment]
@lzim - Yeah, this is embarrassing.  The good news is that if I can get a sample model parameters file for the demo site that includes SP floors and episode counts (see #1698), I can deploy the code the model parameters file and close this issue.

**Comment by lzim** [comment]
@staceypark 
@jamesmrollins 

Looks like James still needs a ModelParameters.xlsx file that includes SP floors and episode counts, is that true?

If so, Stacey can you help me get what we need from **Team 4** _MTL Facilitator Training_ in Fall 2019.

Or, do you need my help to pull these?

**Comment by lzim** [comment]
File needed for DEMO and mtl.how/blue that has valid SP data.

Correct file: "100a1_abc_teama_All_2020_03_10.xlsx"

Next Steps:

[ ] "Get Team Data Table" make sure naming are lower case (Anthony create a new issue card #1736) wk1 mar_epic

[ ] Put this file mtl.how/blue (James)

[ ] Change file to use lower case (James)

[ ] Lower case for team, so they can find it. How do find out what team is using this file? (James).

**Comment by jamesmrollins** [comment]
Hi @lzim , @lijenn , @staceypark , @branscombj , @dlounsbu 

The table below describes all the places that 100a1_abc_teama_All_2020_03_10.xlsx is currently being used.  I intend to change the name of this file to incorporate all lower case letters, IAW our team standards. 

filename | worldname | groupname
-- | -- | --
100a1_abc_teama_All_2020_03_10.xlsx | World001 | david_ind
100a1_abc_teama_All_2020_03_10.xlsx | World002 | jane_ind
100a1_abc_teama_All_2020_03_10.xlsx | World001 | dev_test_team
100a1_abc_teama_All_2020_03_10.xlsx | World008 | individual_login
100a1_abc_teama_All_2020_03_10.xlsx | World001 | mtl_facilitate_2020_09_ind
