### ISSUE TITLE
1/11: Provide a Wireframe for MTL SD-DOC Page

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#1596]
### Check off requirements to verify progress through feature_tracker.
- [ ] 1. **DEFINE in work_breakdown**
  - [ ] a. **what & why** - **written definitions of requirements** in a **numbered checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** requirement definitions an **existing team meeting.**
  
Create a wireframe and algorithm that describes how this web page will look and how it will be updated automatically.

  Task Cards:
  #1591 
---
- [ ] 2. **DESIGN** in **operations_to_do** and **research_to_do**
  - [ ] a. **what & why** - **_MVP_ of design** of requirements in a **algorithm map, wireframes or design** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** design **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 3. **DEVELOP** in **under_development** - "frozen"

  Task Cards:
  #
---
- [ ] 4. **TEST in functional_test**
  - [ ] a. **what & why** - **TEST requirements** using **testing_checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** via TEST **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 5. **PROD in done**
  - [ ] a. **what & why** - **_DOCUMENT_ feature** using **document_tracker** for the **5 D's.** 
  - [ ] b. **date & who** -  **DELEGATE**
    - [ ] **describe_learners** [Jenn & Rita]
    - [ ] **detail_facilitators** [Jane & Debbie]
    - [ ] **document_team** [Anthony]
    - [ ] **disseminate_scientists_va** [Anthony]
    - [ ] **depend_products** [hq & ees]
  
  Task Cards:
  #
---
- [ ] 6. **closed** - fully documented, trained and ready for the next release.

**Comment by jamesmrollins** [comment]
Hi @lzim @staceypark @lijenn @dlounsbu @TomRust @dkngenda @branscombj  FYI: @hirenp-waferwire, 

Attached in this thread is a .png, high resolution wireframe describing the SDM-DOC documentation scheme for the MTL DEMO website.  

![sdm-doc_wireframe-01-01](https://user-images.githubusercontent.com/30132017/102930814-06fa3500-4452-11eb-99b3-7825d580884c.png)

The website would operate as follows:

1.  The modeler pushes a model update (via Dev and QA branch reviews) to lzim/mtl/blue/2.0_models on Master branch.
2.  An action will fire that runs the models through Ignacio Martinez-Moyano's SDM-DOC tool.
3.  The SDM-DOC tool produces a document .html file and deploys it to the necessary location in the Epicenter MTL DEMO project.
4.  The html drops into a container that formats it to the appropriate Team PSD style << This needs to be verified by @hirenp-waferwire >>
5.  The html web pages are accessed via the MTL DEMO Papers section (See wireframe).
6.  The MTL DEMO Papers section will be set up by @jamesmrollins.

**Comment by lzim** [comment]
@jamesmrollins 
These steps make sense to me even without meeting us tomorrow. 
- Do you see any added value in/need for in running though this with one of our modelers @TomRust @dlounsbu before development to make sure they don't think of something else? I wonder how comfortable everyone is with GitHub.
- If you can't think of anything modelers would need to check (versus just the reporting and documentation I need as PI), then I'm willing to approve "as is" without meeting.

Also, I see it's outside of the scope here, but thought it may be worth mentioning this related piece:
How will having the most current data file that matches that version of the .mdl files work? 

> The website would operate as follows:

>The modeler pushes a model update (via Dev and QA branch reviews) to lzim/mtl/blue/2.0_models on Master branch.
>An action will fire that runs the models through Ignacio Martinez-Moyano's SDM-DOC tool.
>The SDM-DOC tool produces a document .html file and deploys it to the necessary location in the Epicenter MTL DEMO >project.
>The html drops into a container that formats it to the appropriate Team PSD style << This needs to be verified by @hirenp->waferwire >>
>The html web pages are accessed via the MTL DEMO Papers section (See wireframe).
>The MTL DEMO Papers section will be set up by @jamesmrollins.

**Comment by lzim** [comment]
@jamesmrollins  

Is this card ready to close? I see it has no assignments and is not getting tracked any where using the "9 clicks" on the right.
Is #1591 done? I believe it was for **wk3 feb_epic**

And, I ask because of the WUSTL PSD Methods "Nerd Out" on Wednesday, during which I may want to relay where we are with this (may not have time either, but just checking).
