### ISSUE TITLE
Update Bios for Alumni on Team PSD Webpage

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#1597]
Related to issue #1246

Update Bios for Andrew, Rita and Savet on new Team PSD Admin page.

**Comment by jamesmrollins** [comment]
Hi @lzim and @lijenn .  Besides an initial howdy from Rita, everyone for the most part hasn't even returned my greeting.

**Comment by lzim** [comment]
@lijenn 
Did you create the new card yesterday about this?
Which should we use?

**Comment by lijenn** [comment]
New card for updating bios, mtl.how/team map, and Thank Yous are now tracked in #1701, I'll close this issue since I can help update the map with the update bios.
