### ISSUE TITLE
Spell Check, Link Check and Markdown Lint the lzim/mtl Repo 

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#1598]
Reference issue #1450
Update the lzim/mtl repository and ensure all files pass the QA actions.

**Comment by jamesmrollins** [comment]
Hi @dlkibbe and @branscombj.  I am currently spell checking, link checking and .md linting the lzim/mtl repo.  I have identified several standardization issues that I need to discuss with you regarding headings, use of graphics and related matters.  There are also elements on the pages of the see and say guides that are not working well within the markdown rules.  I have resolved many of them, by adjusting the rules or the characters used but need to check in with you to make sure I haven't altered the documents away from your preferences.  Once I understand your design intent, it will be easier for me to move through all the files.   

Reference branch: [feature-directory_scan](https://github.com/lzim/mtl/blob/feature-directory_scan/blue/session02/s02_facilitator/mtl_session02_say.md)

Below are some of my questions:

1.  What is the overall heading/title structure?  I see the following for major titles:
- Title
- Do and Done
- Learning Objectives
- In-session Exercise
- Done and Do
- Until next time . . . 
2.  The YAML header appears to be interfering with the use of h1 header. I am investigating a workaround.
3.  What are your criteria for the use of bold an italics?
4.  What are your criteria for using unordered lists?
5.  What are your criteria for using ordered lists?
6.  What are your expectations for the nesting of graphics?  Most graphics stack on top of the headings they relate to.  Some, such as time stamps are more randomly applied (although I suspect they are place where they are based on actual timing from practice.)
7.  What are your expectations regarding table structure?  Some tables appear to have items on the incorrect row.

I am still learning the nuances of the markdown language - I appreciate your patience with me.

Thanks,
James

FYI @staceypark @lijenn

**Comment by branscombj** [comment]
Hi @jamesmrollins. Thanks for this summary. @dlkibbe Do you have bandwidth to follow up with James on open questions? I'm entering my thoughts below and pinging HQ staff on a couple that I think may have existing answers somewhere.
  
> 1. What is the overall heading/title structure?  I see the following for major titles:
> 
> * Title
> * Do and Done

I think it's always Done and Do (past and future).

> * Learning Objectives
> * In-session Exercise
> * Done and Do
> * Until next time . . .

This list looks correct to me, although I don't know that we need "Until next time" to be a heading - it's just a closing script, right?

> 1. The YAML header appears to be interfering with the use of h1 header. I am investigating a workaround.
OK, I don't know about this.

> 2. What are your criteria for the use of bold an italics?
> 3. What are your criteria for using unordered lists?
> 4. What are your criteria for using ordered lists?

@staceypark @lzim @dlkibbe @lijenn Were the 3 above decided before? I seem to recall these are specified in a style guide somewhere.

> 5. What are your expectations for the nesting of graphics?  Most graphics stack on top of the headings they relate to.  Some, such as time stamps are more randomly applied (although I suspect they are place where they are based on actual timing from practice.)
> 6. What are your expectations regarding table structure?  Some tables appear to have items on the incorrect row.

We (Debbie and James?) might need to discuss/look at these together live.

Patience with you for learning programming language? You gotta be kidding - Debbie and I are the Luddites!
You said these are some of your questions, hoping you and Debbie can discuss any others. Glad to weigh in as needed!
Cheers and happy new year, all!

**Comment by jamesmrollins** [comment]
Thanks @branscombj and Happy New Year to you too!  Hi @dlkibbe , I am available today until 1 pm PST.  I am currently editing the document and making good progress, so I hope not to take too much of your time.  

Cheers!
James

**Comment by dlkibbe** [comment]
@jamesmrollins happy to talk today. I have my next meeting from 2-3p eastern. Can chat after 3 pm my time / 12 noon your time if that works.
@branscombj

**Comment by jamesmrollins** [comment]
@dlkibbe, I am sorry I missed your response.  I have turned off my notifications because of all the linting that I am doing and I missed it!!  Let me know what works for you next week and I will set us up a Teams meeting.  Again, sorry.  James

FYI @branscombj
