### ISSUE TITLE
wk2 - EES workflow flow map for CRM

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1603]
Create a flow map outlining the automation for EES processes in the CRM - ie getting facilitators, dates, etc setup.

Checkout with Jane and have draft ready for EES meeting this month

**Comment by lijenn** [comment]
ees map finalized at 12/9 support wg: https://lucid.app/lucidchart/d31a3763-58da-4d09-a8e2-495a1855aac0/edit?page=0_0#?folder_id=home&browser=icon
