### ISSUE TITLE
3 file edits 

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#161]
1. I made tweaks to Session 8 In-Session Exercise (making the text box directions stand out more) using a pull request and naming the new branch jane_0903.

2. I made similar tweaks to the Session 7 In-Session Exercise in a pull request where renamed the filepath to insert jane_0903 - but at the bottom my choices were to commit to master or start a new branch. I tried starting a new branch and naming it jane_0903 but it said it would turn that into a jane_0903_2 or something - another branch. So I committed to master. But I don't know what happened to the pull request since I'd rerouted the filepath at the top.

3. I created a bullet-point version of the Session 5 in-session exercise guide in another pull request by editing the existing say guide. But we should actually save that say guide somewhere rather than replacing it with this versiono because it's got some helpful facilitator script.

Sorry Lindsey - i believe in github i do; it's just really wearing me out trying to get the process into my thick skull.

**Comment by lzim** [comment]
@branscombj No problem. Thanks for finding a work around. 🔧 

Should I assume you're done with 5, 6, 7, 8 in-session guides (see files) for the night? If so, I'm going to take your work (already on master) and merge it with the other session components from the fidelity checklist, and the standard formatting Stacey I finished. I accepted your pull request to make session 5 a see file too.

Thanks!

Lindsey
