### ISSUE TITLE
apr_epic_week_4_story_7: Create Sim UI Chapter in Team PSD Manual

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#1610]
Provide a means for the user to add a course code to the MTL DEMO website via GitHub or the MTL DEMO Admin Dashboard.

Reference: #1760

**Comment by lzim** [comment]
@jamesmrollins 

Will we have something set up and instructions in the https://mtl.how/teampsd_manual for this soon?

I’d like to set up a code foe the WUSTL PSD Methods Nerd Out wk4 of Feb Epic - talk is 2/24.
Code is: wustl_nerds_2021

**Comment by jamesmrollins** [comment]
Hi @lzim -  I took care of the immediate need of entering the code above.  I will attempt to get the documentation up to date this week.  I think we have it documented somewhere already, so I will find it and put it in the manual. Sorry, many distractions with a PsychTools design review starting up again.

**Comment by jamesmrollins** [comment]
Hi @lzim.  It has indeed been documented already and is available [here](https://github.com/lzim/teampsd/blob/master/resources/training_guides/mtl_how_demo/course_code.md) for immediate use.  With respect to the Team PSD manual, there isn't a chapter that covers this kind of thing.  Can I create a chapter for common sim_ui procedures?

**Comment by lzim** [comment]
Yes, @jamesmrollins please do add a chapter to mtl.how/team_psd_manual for common **mtl.how/team** or **mtl.how/demo** tasks, which will be completed by **Team PSD Members.**

But, we don't want common **mtl.how/sim** tasks there, we want those in the _MTL Facilitation & Technical Manual_

FYI: @staceypark @lijenn

**Comment by jamesmrollins** [comment]
@lzim I plan to roll this issue into MTL Demo Admin upgrade that allows the entry of a code directly into the Admin screen.

**Comment by jamesmrollins** [comment]
From 4/26 workgroups:
1.  This should contain ADMIN procedures update.
2.  Due by week2 May Epic.

**Comment by jamesmrollins** [comment]
Issue is redundant with issue #1754
