### ISSUE TITLE
wk4 june_epic task: story_2 - develop a roadmap for finding efficiencies with our SQL scripts 

### ISSUE THREAD

**Issue by anazariz** [lzim/teampsd#1613]
Our SQL scripts used in our Research and Production environments rely heavily on SQL Server Temp tables. These tables have session lifetime. That means when the user disconnects from the database all table results are discarded. As there are heavy sequential dependencies between tables in our scripts (e.g. table D uses results of its predecessor, table C ; table C uses results from its predecessor, table B and so forth), when the session is disconnected, the script must be rerun from the very beginning to a particular intermediate table of interest regardless of whether changes were made to that table's predecessors or not. While this may be acceptable in shorter scripts, it is not optimal/scalable in "what-if" scenarios where a small change has to be made to an intermediate table (table D in our example above) and none of that table's predecessor. 
A balanced combination of Perm and Temp tables, stored procedures and functions as well as various types of views can aid in reducing the time needed to run such "what-if" scenarios. The objective of this roadmap is to come up with an optimal methodology (set of rules - what to use and where) and retrofitting of candidate scripts.

**Comment by lzim** [comment]
@anthonycpichardo 
@anazariz 

It looks like this issue card needs to folded into Story 2.

**Comment by anazariz** [comment]
### Realigning this issue to the Story 2 as depicted in [chart user_story_maps_2021_01 of Lucid Charts  ](https://lucid.app/lucidchart/4fb06b59-38f5-4d61-86f0-4620ceb93196/edit?page=0_0#)

A brief Recap: R21 and R01 grants use somewhat similar (in logic) scripts (based on the comparator script) for populating their data marts (a data model that is sourced from the CDW data warehouse and designed for the specific needs of each grant). 

The previous version of the script(s) used SQL Server Temp Tables, which are offloaded (not saved) when a session ends (user logs off of SQL server). This made it difficult to go to intermediate results. The scripts have been modified to produce Permanent table that do not disappear when the session ends. 

Are Temp tables still necessary? Yes. These table are still used in the code because they use large shared storage space (used by all databases on the server) that allow our scripts, which handle large volumes of data to complete. Once the data is gathered then the transient results are save to perm tables. To be able to distinguish between various types of perm tables, schema names and file naming conventions have been created. These schema and file naming conventions help identify related tables (e.g. R21). Identification of related tables helps in two ways:

1. Doing bulk operation such as listing table names, dropping tables (preparing for a fresh run from scratch, etc.).
2. Identifying a specific table that was involved in running a specific script (e.g. R21 Total Cohort, EBPsy Pharm Completers, etc.)

Examples: 

1. Our current R21 script includes code segment that drops all tables belonging to that script for a rerun from scratch.
2. Our current R21 script includes code segment that populates Temp Tables from Cached (Perm Tables) so that the script runs from whichever point it was halted at last. 

Current State:
A script has been created that creates a table with the following fields:

|itemno  |mart  |table_schema_name |meta|
|--|--|--|--|
| NULL|NULL|comSite.anchor|NULL|
| NULL|NULL|comSite.anchor_agg|NULL|

- itemno: shows the relative position of a table within the body of script
- mart: identifies how table are related - e.g. R21
- table_schema_name: identifies the schema and table name
- meta: actual verbiage describing the role of the table and the data it hold   

It must be notes that the Pern Table list is mutable as the needs of the mart change. Example, R21 started at the Facility level and later on changed to the Clinic level. Each of these levels have require different set of tables.

**Comment by anazariz** [comment]
Although the need for which tables need to be cached (become permanent tables) varies slightly with analytical needs, most of the tables that need to be permanent have been identified. In fact, in R21 and R01, perm tables have been used and have dropped the rerun times considerably.
