### ISSUE TITLE
ICEBOX Task: MTL Supplies to Learners

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1614]
How will we send out MTL equipment supplies (magnet, lanyard, etc.) to teams?
Could ask admin group to mail the items out?

**Comment by lijenn** [comment]
2/8 Workgroup leads:
- Stacey, Lindsey, Jenn, Anthony could go into the office and ship these out. 
- Jenn will email mary for the copy shop location's link.

**Comment by lijenn** [comment]
@lijenn Split and re-scope into cards that can be done a week at a time.
**wk1 mar_epic** - When do they go out?

**Comment by lzim** [comment]
#adjudicate_memo
We are no longer shipping supplies to learners as of 2024_mar_epic
