### ISSUE TITLE
wk3 Bugsin Data UI facility files & OLE actions

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#1617]
Ran into issues with VISN 22, Loma Linda (605) trying to open their facility_605.xlsb file today. 

- [x] **Error 4:**  The "Hidden" tab of the facility file needs to be "re-hidden."

<img width="323" alt="error_facility_file" src="https://user-images.githubusercontent.com/7454688/101829660-31f69780-3ae8-11eb-8802-d892c202115c.PNG">

Note: Dependencies that may require a separate issue task/documentation card:
- [ ] **Document** we need instructions for what to do if someone else has the file open?
- [ ] - [ ] **Error 1:** (see screenshot) OLE action.
- [ ] **Error 2:** An error message that said that .xlsb was an "invalid file name."
- [ ] **Error 3:** It did open Excel, but it was an empty file.
   - [ ] **Message 1:** If you just want to take a look at data, select "view only."
   - [ ] **Message 2:** If they do want to save any selections that make, we need a message about where to save the facility.xlsb file?

**Comment by anthonycpichardo** [comment]
Errors 1 2 and 3 are system issues that will require documentation to ease the pain points on our users, but can not be resolved as a development task with our current technology.

error 4 was corrected as part of #1668

**Comment by lzim** [comment]
@anthonycpichardo 

Is there updated **documentation** related to Errors 1 2 3?

**Comment by anthonycpichardo** [comment]
I've created #1733 to add the appropriate documentation.
