### ISSUE TITLE
WK1 + Task: Prototype Fiscal Year View/Filters 

### ISSUE THREAD

**Issue by anazariz** [lzim/teampsd#1619]
**Fiscal Year View/Filters Prototype**

Create a prototype using the Data UI vizEnc for switching between Fiscal and Calendar Year dates. 
Once approved, the design can be implemented in other Data UI and Facilitate viz tabs. 

@lzim @lijenn @staceypark @anthonycpichardo 

I added what's called a context menu to the Data UI that will allow us to add the fiscal date filter without any additional artifacts (no buttons, etc.). To access the context menu you should right-click anywhere on the vizEnc pivot table (not the chart). Then go to the bottom of the menu and select "Switch to Fiscal Date". This will change the filter on the bottom of the screen to a fiscalyear (as seen below). Also as seen in the PivotTable Field (to the right of the screen) in the Rows section, fiscalyear was correctly added. 
To return back to the calendar date format just click reset. 

**Please let me know if this works. The prototype is in the TeamPSD\quant_workgroup\final_datafiles folder and named DataToolsFRE14_nevermore_VVC_MVP.xlsm.**    

![image](https://user-images.githubusercontent.com/39805164/101857483-700dae80-3b1c-11eb-9668-d3cf98f849dd.png)

**Comment by anthonycpichardo** [comment]
Looks like those blank values came back based on your ss. Do we know why that is?

**Comment by anthonycpichardo** [comment]
Include a message to indicate how to use the filter.

**Comment by anthonycpichardo** [comment]
The prototype for this was created and reviewed. Remaining work tracked via #1580
