### ISSUE TITLE
wk1 nov_epic: 11/4 @4PM Stanford Invention Disclosure 

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1620]
Look into MTL invention disclosure to Stanford 
- login with SUN ID at otl.stanford.edu
- has similarities w/ both our eProtocol IRB and our VA tech transfer program office process

**Comment by lzim** [comment]
@staceypark 
Where are we this?
Can we make a plan for getting this to done?

**Comment by lzim** [comment]
We will submit this in mar_epic with the new VA invention # information.

**Comment by staceypark** [comment]
@lzim have you had a chance to look at the Word doc I drafted?
This may be a good one to do with the team together during a team time, for folks to familiarize more

**Comment by staceypark** [comment]
@lzim let's cover this 9am next wed 5/5

**Comment by lzim** [comment]
11/1 @staceypark & @lzim Finish & submit - on Schedule for 11/1 at 4PM

**Comment by lzim** [comment]
Whoo hoo!!!
