### ISSUE TITLE
Facility data spreadsheet sizes

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1622]
Some facilities are so big that we've reduced the facility data "look back" year window to 1 year instead of 2 years.
1. Could you create a list of all such facilities
2. Is it possible to add some sort of pop-up message for these types of facilities since it goes against everything else our materials say.

**Comment by anthonycpichardo** [comment]
This is no longer an issue, all sites are able to have a  full 2 years of data shown.

Corrected the code to allow for this. Will be available after next months propagation, unless you'd like us to rerun the propagation for this month.

Thanks.

Please close once a decision has been made.

@staceypark

**Comment by staceypark** [comment]
@anthonycpichardo great to hear that won't be an issue anymore.

@lzim @lijenn 
How many more co-planning meetings are there between now and Friday?
And, do we want to just run the propagation after just in case there are any problems? Or try to run it overnight, so we don't run into the 1 yr vs. 2 yr issue with any remaining sites before holidays?

**Comment by lijenn** [comment]
@staceypark @lzim None as of now, but potentially 1 co-plan meeting on Friday but will most likely be pushed to January. Lindsey does have a 30 min chat with 1 site/leader at a large VAMC on Friday though, not sure if you plan on viewing the data with him?
