### ISSUE TITLE
VA Teams Cheatsheet

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1623]
## 1. Link to the document and add relevant team members to the card.
- [ ] Add the link the current draft of the documentation for the issue: **See blocking dependencies below for related task cards**

## 2. Link to issues that must be edited in the document in the **issue_tracker** and **feature_tracker.** _(use the # for the link to the issue)_
- [ ] #1624 Issue Card for VA Teams Cheatsheet
- [ ] Related to #1513 Set up MTL teams on VA teams?

## 3. Team Review
- [ ] Fidelity - check with Lindsey
- [ ] Data UI - check quant_workgroup
- [ ] Sim UI - check with model_workgroup and/or sim_workgroup

## 4. Review and Open Pull Requests _(use the # for the link to the pull request)_
- [ ] Check the draft for typos
- [ ] Check or open a pull request for the document edits

## 5. Review and/or Update Graphics
- [ ] Screenshots
- [ ] Gifs
- [ ] Logos/Icons
- [ ] Links

## 6. Dependencies
- [ ] Make sure that any edits you make that need to be added to **depend_product** are tracked (e.g., _MTL Video_)

## 7. Close Pull Requests
- [ ] Request review and/or close open pull requests for the document

**Comment by lzim** [comment]
@staceypark is this this a duplicate card I don't see the **epic details in the title.**

Does this need to be split out in any way?
For example, we've discussed:

- [ ] Team PSD Teams
- [ ] _MTL_ Teams

FYI @lijenn I do want to briefly touch base about the decision to only use the calendar invite and not a channel at 8AM workgroup leads on Monday.

Principally, I wondering if sharing files that cache group edits in real-time is better facilitated with channels?
Should the channel begin in co-planning?
How does this fit with **Story 6?**
