### ISSUE TITLE
wk1 mar_epic story 1 Task: VA Teams/SharePoint MTL Cheatsheet

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1624]
Create VA Teams cheatsheet for MTL Learners

Adding some notes to include:
- Dialing into the conference line is always an option to fix audio
- It seems like scrolling interferes with the audio at least on GFE so far
- add #1656 (closed to incorporate into this card/task).

**Comment by lzim** [comment]
@staceypark 
@lijenn 
@branscombj 

I want to touch base at Facilitate Workgroup next Tues about how this Teams discussion went w/Joe of EES. Jenn won’t be there.

We’ll want this clear in Teams Guide.

**Comment by branscombj** [comment]
> @staceypark
> @lijenn
> @branscombj
> 
> I want to touch base at Facilitate Workgroup next Tues about how this Teams discussion went w/Joe of EES. Jenn won’t be there.
> 
> We’ll want this clear in Teams Guide.

I'm not sure if he fully took in the idea that facilitators are attending the team's existing meeting to conduct the session. The norm for "webinars" is for there to be a Word document attached to the course brochure in TMS that has the connection information and links to attend. He said he will ask around about alternatives. My hope is to avoid another step of work and opportunity for error, by putting generic language into TMS about the session taking place at the "location" of the team's standing meeting at that time. Vs his initial inclination that we should put the team's Teams link into the brochure. We all agreed that even though this makes it "public", no one who isn't invited would be able to actually enter the meeting.

As a side note: Jenn and I did discuss that we should make explicit in our process the step of having the team invite MTL co-facilitators to their Teams meeting. Should we ask them to invite all 9 of us? If only the 2, there could be a scramble if a sub is needed. But they might find it daunting to have 9 "strangers" invited to their team meeting. Need a decision on this.

**Comment by staceypark** [comment]
Need to add mute function and pin function

**Comment by staceypark** [comment]
@staceypark @lijenn 
Add instructions on how to get to team chat

**Comment by staceypark** [comment]
add instructions on how to use the O365 groups
