### ISSUE TITLE
wk1 task (by 1/14): Review/Add to EES Flow Map

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1626]
Hi Jane!

Before our monthly meeting with EES on Jan 14th, could you please help review and add to the EES email and task management workflow (focusing on the MTL Video, MTL Live, MTL Facilitate EES projects) on LucidChart:

https://lucid.app/lucidchart/d31a3763-58da-4d09-a8e2-495a1855aac0/edit?page=0_0#

**Comment by branscombj** [comment]
Hi @lijenn ! I did make a few additions/edits to the flow chart. I believe what we discussed before with EES was a spreadsheet we could send them with all the dets for any new team being started in MTL Live, and to which they would add the TMS links for each session and each team, which we would then input into all the team's pre-/post- emails and TT reports. Somewhere there's a spreadsheet sample I sent them, which they thought looked like it would fit the bill.

Happy New Year!

**Comment by branscombj** [comment]
@lijenn Should I go ahead and close something like this with a completion comment like the above? Is the idea to have shorter-lived Issues - small tasks we complete and close relatively quickly?

**Comment by branscombj** [comment]
Hi again @lijenn - My edits to the flow chart were based on my recollections of the earlier convo that I re-found in #1176 on April 2 and 3, including an Excel table shell attachment, and the responses to my questions there that came in an email from Elizabeth. I'm pasting those below. 
I don't exactly follow your comment from yesterday in that thread, but maybe this is related. In any case, I didn't want the already-discussed details on EES logistics to be lost - and there may be more of those details we could add to the flow chart before we meet with EES. If you'd like to have a chat about it together before then, let me know! 

4/2 email from Elizabeth:

We're trying to figure the best way to get the correct TMS links to our MTL Live participants. As you may know, the bulk of MTL participants will be attending 12 one-hour sessions over 6 months. After the first or 2nd session we will have worked with them to establish a fixed, recurring appointment like every other Tuesday at 9am Pacific. There is a possibility that something could happen during the 6-month period that would require a shift in one or all of the remaining session dates or times.

> Yes, we would like the dates and times in advance, as far in advance as possible. This allows our team to set up the TMS links for your team. If a date and time shifts, we will work with that change.

Would it be efficient for you and your team if we were to give you up-front (probably after the first session) all the sessions and their dates, time, and facilitators for each team that's going through MTL - and then make changes if and when they arise? We would most likely notify you of any scheduling changes at least 2 weeks in advance.

> Yes, this would be the most efficient.

If you made a change to one or more dates, I trust the link would still stay the same?

> Correct, the link would stay the same. We do need notice of the changes (changes cannot be made the day before). Ideally, we would not need to make too many changes, as this is administrative work for our team and the TMS team (a few hands would need to be involved), we could make the a change.

Then you could give us a list of all those links once you'd set them up in TMS, and we could give the team a table of all the session dates and links for their series.

> Yes, this is a great plan.

This is as opposed to setting up only the next 1-3 sessions at a time in TMS and us communicating the links to the right people over and over. I am assuming that the TMSystem can have a page set up for a live event that's in the future, and if someone should try to get credit for it the system would block them until after the event date?

> Yes, that is correct.

> MTL team our EES BV team is supporting the COVID19 communication for med centers (townhalls), this is a heavy lift at the moment.  If you have your start date in mind, please let us know, so we can prep our director, he may need to move around some resources.

**Comment by lijenn** [comment]
Hi @branscombj! Thank you SO MUCH for re-collecting what was discussed in the past as I had trouble with this!
And yes, the idea is to have short lived issue cards and closed with a completion comment once the task has been reviewed and looks good :)

You can also disregard my last comment in the #1176 thread, it's referring to the CRM MVP as we're trying to see if we can include the pre/post email templates, co-planning email/scheduling, and the team_tracker into the MVP for easier tracking and email management.

I definitely think all that you re-collected should be added to the flowchart before the 1/14 meeting...The current flow doesn't address the scenarios and details you have (e.g would the link change if we had to change one or more dates, timeframe to notify EES if we do make a change, giving EES the dates after session 1 or 2 vs after Co-Planning meeting 2 (Lindsey & QIIC meet with the actual provider team and they find a team meeting time during the co-plan 2 meeting, I believe after co-plan 2 is the goal right now), etc.)

It also helps to note that Joe is still fairly new to the MTL projects as the EES project manager since he joined the team right before covid so all the small details will definitely help orient him (and us too since it's been a while!!).

**Comment by branscombj** [comment]
Will you work on adding in other details? I can but I have another task ahead of it now. Once we have as many details as we know, maybe we can add specific questions in a new shape?

**Comment by lijenn** [comment]
@branscombj Sure can and sounds like plan! Will let you know when I finish, aiming for end of today or tomorrow and would like your eyes as a reviewer :)
