### ISSUE TITLE
jan_wk1 (draft) wk2 (submit): R01 Annual Report to VACO DUE Thursday 1/14 in RDIS

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#1631]
Adapt the R01 Annual Report submitted to NIH for submission to VACO (VA Central Office) in RDIS.
It is due to VACO before COB Thursday, January 14.

NIH RPPR (Progress report) is in Team PSD > Grants > R01 > rppr > year2 file name: "RPPR10066337.pdf"
I have started this and what is checked off below is completed.

I have assigned to Team PSD members based on what I want the assignee to be tracking (see below) for these two Team PSD priorities:
- Report  up what we did in year 2 in our **R01 protocol manuscript r01_protocol_impsci** - https://osf.io/8pzxu/ #559 - https://github.com/lzim/teampsd/issues/559
- Prepare for what needs to occur for R01 research across our **two 2021 six month roadmaps**.

1. **Collect FCOI Form from Co-Is** 
- [x] Remind Co-Is in tt_teampsd report (Jenn)
- [x] Remind Rachel, David and Shannon via email during wk1 (Stacey)
- [x] Remind Co-Is at Co-I meeting Wed 1/6 (Lindsey)
- [x] Lindsey
- [x] Rachel
- [x] Steve
- [x] David
- [x] Mark
- [x] Craig 
- [x] Shannon

2. **Update Personnel on Project**
- [x] Remove Andrew, Jessilyn and Rita (Lindsey) 

3. **Adapt NIH Progress report for last year for VACO**
- [x] Adapt NIH R01 RPPR to the 4000 character limit and _save as draft_ (Stacey)
- [x] Review/edit this paragraph (Lindsey)

4. **Adapt NIH Progress report for next year research plans for VACO**
- [x] Adapt the NIH R01 RPPR to the 400 character limit and _save as draft_ (David & Anthony)
- [x] Review/edit this paragraph (Lindsey)

5. - [x] **Submit & Lock** (Lindsey)

**Comment by staceypark** [comment]
@lzim all FCOI's done!

**Comment by staceypark** [comment]
@lzim last piece of incomplete training done as well. Looks incomplete in RDIS still because they haven't updated on their end (for Shannon), but she cc'ed me in the email where she forwarded the certificate to the appropriate folks.

**Comment by lzim** [comment]
Great job on your sections @staceypark 
I made only very minimal edits and it helped a lot!

Have a great long weekend! 🖼️
