### ISSUE TITLE
Update - and still needed...four things (but not for day 1) 

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#164]
Hi Everyone,

Great work getting everything ready!

**Please see the updated schedule here** - **You can also get there by typing mtl.how/facilitate_pilot into any browser window** 😄  https://github.com/lzim/teampsd/tree/master/mtl_facilitate_workgroup/mtl_facilitate_pilot

**I've hidden the links within the code. You just click on the blue text and it will take you there.**
- The in-session see guides are all linked to the standardized, formatted files here: https://github.com/lzim/teampsd/tree/master/mtl_facilitate_workgroup/mtl_live_guide
- The mutual learning activities are still posted in each day of mtl_facilitate_pilot and the links point there.

**Here are the four things I see that still need to be added/uploaded/pull requested:**
- session 6 Mutual Learning (day 2) - No file yet? Is that right?
- session 9 in-session/see guide (day 3) - No file yet? Is that right?
- session 9 and 10 Mutual Learning (day 3) - Systems Thinking will go here: https://github.com/lzim/teampsd/blob/lzim/mtl_facilitate_workgroup/mtl_facilitate_pilot/day3/systems_thinking_mutual_learning.Rmd
- sessions 11 and 12 in-session/see guide - Team Decisions and Team Plan will go here: https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/mtl_live_guide/mtl_live_session11_see.Rmd 

**When I arrive, I will have folders for everyone (Team PSD and our learners) and I will have name tags, and photo releases to sign. And I will have a camera 📷 📸**
 
I look forward to seeing you all in person!

Lindsey

**Comment by staceypark** [comment]
mtl facilitate pilot done and successful! 😀
