### ISSUE TITLE
wk2 mar_epic by FRIDAY 3/12 Story 6?: Setup VA REDCap for facilitator fidelity ratings

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1642]
@lijenn we need to make sure the fidelity rating survey skeleton in setup in REDCap along with the specific details for wave 1 teams

**Comment by lzim** [comment]
@staceypark 
@lijenn 

Let's briefly touch base on this one at **8AM Workgroup Leads**
_Is VA RedCap still the best platform for this?_

Is this platform the fastest way for facilitators to check their ratings against one another during their 30-minute debrief?

Wouldn't the fasted approach be to integrate into a platform such as the CRM (perhaps through PowerForms) in the future?
But, we'd need to get the standard data for analysis, of course _and_ the ability to the facilitators to review their rater agreement "live" post-session.

Added dependencies due **wk4 feb_epic**

**Comment by staceypark** [comment]
hq 2/25
- we want to add coplanning ratings for team engagement
- update the quick link
- add link to team tracker 
- some way to bake into crm?????

**Comment by staceypark** [comment]
@lzim 

Which set of fidelity items should we use for coplanning?

**Comment by staceypark** [comment]
For coplanning we will include:
- partner & build items 

For partner/build/apply fidelity we will stick to the 1-4/5-8/9-12 chunks aligned.

**Comment by staceypark** [comment]
Feedback on fidelity survey:

- [ ] add blue
- [ ] Date of Coplanning or Team Meeting
- [ ] Change co facilitator 1/2 to live lead and support (?) check say guides
- [ ] Add examples in prompts on how to answer question - see qual work on this

**Comment by staceypark** [comment]
@lijenn I've just had a realization about the data structure for the fidelity ratings, that I want to check out with you.
I think (unlike the measures) we don't need such a complicated structure because things don't need to "close"

**Comment by staceypark** [comment]
@lijenn im going to close this issue because we did already set it up.
I've created a new issue #1811 to track the new things we need to do
