### ISSUE TITLE
wk4 jan_epic Bug/Task: Font on mtl.how/teams is not Myriad Pro

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#1652]
Noticed that the https://mtl.how/team map is not in Myriad Pro font, not sure if this is bug or was in the approved design. Prefer to stay consistent with VHA graphics Myriad Pro on the map.

<img width="954" alt="font_va_laptop" src="https://user-images.githubusercontent.com/7454688/105432614-cc301c00-5c0c-11eb-8e3e-f3043e39088d.PNG">

**Comment by jamesmrollins** [comment]
Hi @lzim .  It is Myriad Pro and appears that way on my machine.  Looks like you are using Chrome. Was this on your Mac or Windows machine?  

@hirenp-waferwire please investigate.

**Comment by jamesmrollins** [comment]
Hi @lzim.  We were loading the graphics before the font, which was causing the system to use the default (times) font.  Now it should load the correct font.  When you have a moment, check it out.  It seems to pass tests with me.

FYI @lijenn
