### ISSUE TITLE
wk4_jan_Bug DataUI: MMParameters Tab all zeros when vizEnc shows Med Mgmt

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#1657]
**Review of Data UI for 605gc found all zeros in the MMParams tab (see screenshot).**
**1. I concluded that it was because I had not used the "Get Team Data" button.**
_So, really, all of the tabs should have reflected 0s to indicate that I had not made selectsions for the CCParams, MMParams, PSYParams, AGGParams, and SPParams tabs._
- Note that 0s in the MMParams tab are despite seeing >100 MM encounters/month on average for this set of Clinics in the **vizEnc** graph (not show to maintain data privacy).
- All other Params tabs have values. 
![image](https://user-images.githubusercontent.com/7454688/106047448-7e963200-6098-11eb-9e1d-b8d01aa33f99.png)

**2. So, I used correctly the "Get Team Data" button" to populate the tabs and received this VisualBasic Run-Time error.**
![image](https://user-images.githubusercontent.com/7454688/106058843-aa201900-60a6-11eb-91ec-33f633ecd42d.png)

**3. Lindsey needs to review or cache the "debug" results somewhere.**
@anazariz and @anthonycpichardo Let's decide where this should go.

**Comment by lzim** [comment]
**The logic is supposed to be:**

If you click "Get Patient Data" then the "Params" should be zeroed out until at "Get Team Data Button" is pushed to populate the "Params."

**Comment by anthonycpichardo** [comment]
Add messaging for users so they understand why they may be receiving an error message from their query timing out

**Comment by lzim** [comment]
**Ran "Get Team Data" within the 15 kill limit for LSV queries (Data UI at team levels).**
- "Get Patient Level Data" - took 9 minutes **605gc**.
- "Get Team Data" - "naming save issue."

![image](https://user-images.githubusercontent.com/7454688/106182746-2290e380-6154-11eb-92f4-ddb30c45013c.png)

**Discussed at huddle on Thurs 1/28/21**
- Lindsey will follow standard work for "data_ui" folder and "team_data" folder and try to get the data again.
- Test resolve any user errors.

@staceypark and @lijenn 
- **wk 2 facilitate_workgroup Feb 9, 2021**

Goal is to review document, provide re-orientation to reduce user errors and close bug.

**Comment by anthonycpichardo** [comment]
resolved as part of #1668

**Comment by hnorthcraft** [comment]
#adjudicate_memo efforts tracked to other card, assigning dup
