### ISSUE TITLE
WK 1 : BISL Migration : Identify Applications and users that will be impacted and what the impacts to the platform will be

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1659]
Identify Applications and users that will be impacted and what the impacts to the platform will be. 

Anthony will validate this by cross checking the session 2 and 3 guides as well as the co-planning mvp.

**Comment by lzim** [comment]
@anazariz @anthonycpichardo 

I reviewed the new Sharepoint online migration (quick link: https://mtl.how/data_migrate) and I don't see any of our VISN -> Facility pages. Should we check-in with Mason and Austin about this?
