### ISSUE TITLE
wk3 feb_epic: BISL Migration: Assess Power BI/Power platform implementation

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1661]
Ash/Anthony will  perform discovery on the Power BI and Power Platform resources we have at our disposal  and compile resources and documentation

Testing: Monthly Meeting with BISL partners occurs during week 3 monthly where we can validate any assumptions.

**Comment by anazariz** [comment]
Received our PBI Pro Lic. @anthonycpichardo and I are working on getting access to SQL Server via the Gateway.

**Comment by lzim** [comment]
@anazariz 
@anthonycpichardo 
I believe we now have 
- [x] pro licenses
- [x] premium site
- [x] gateway for LSV

Right?

I'm editing the title to reflect **Story 5** and **feb_epic**

**Comment by anthonycpichardo** [comment]
> @anazariz
> @anthonycpichardo
> I believe we now have
> 
> * [x]  pro licenses
> * [x]  premium site
> * [x]  gateway for LSV
> 
> Right?
> 
> I'm editing the title to reflect **Story 5** and **feb_epic**

This is correct
