### ISSUE TITLE
wk4 feb_epic: BISL Migration: Validate  & finalize the technology capabilities we will leverage

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1662]
Ash/Anthony will  validate  the technology capabilities we want to take advantage of.  

Test: Ash and Anthony will validate that this technology can be used to meet the needs we've identified in issues: #1660 #1661 #1662

**Comment by anazariz** [comment]
Ran a Data UI in the cloud to make sure we don't need a gateway. Test ran fine. Links need to still be fixed.

**Comment by anazariz** [comment]
@lzim, @anthonycpichardo 

1. Sharepoint capabilites have been validated for data accessibility (as currently exists in the on-premise site). 
2. Nneed a test plan for users. 
3. In parallel, the links and site organization will have to be corrected.  Creating a ticket for it.
