### ISSUE TITLE
WK4 feb_epic story 3 Task: List of Temp to Perm Tables Walkthrough and Signoff (PROD QA)

### ISSUE THREAD

**Issue by anazariz** [lzim/teampsd#1666]
**1. Do a walkthrough and obtain signoff on the List of Temp to Perm Tables :**

**Comment by anazariz** [comment]
List emailed to @anthonycpichardo

**Comment by dkngenda** [comment]
@anazariz @anthonycpichardo 

Do we need a meeting time set up for this?
