### ISSUE TITLE
wk1: Crosswalk/Scope CRM User Stories Requirements in Dynamics 

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1669]
Crosswalk and scope the user story requirements to determine if we should used a pre-built CRM or build a custom CRM with Power Apps. Check-in at Support WG and MSD workgroup meeting or asynchronously here. 

PSF will be bringing in an Architect to help us think through whether or not a OOB Module CRM or Custom Power Apps help us with our desired end state, not just the MVP. But we need to determine which OOB Module we would use.
 
**Static List - low level of complexity.** (Jenn)
F6 low "Import & Map Teams of Providers to Facilitators"
F12 low "Exchange online integration" 
F13 low "Outlook integration" (an "add-in")
F14 low "Outlook Integration: invitations" (a KEY story for informing the best fit for Outlook integration - "Dynamics 365 App for Outlook")
F15 low "Facilitator Assignment"
F17 low "Documentation/Notes" 
F18 low "File Storage/Access" (adding "fields")
and power app/forms #1683 

**Dynamic List - medium level of complexity.** (Ash/Anthony)
F7 medium "Manage Team Schedules for MTL"
F16 medium "Standard CRM & Co-planning Dashboard Elements"

**Automation Flows - high level of complexity** (due to incomplete understanding of 365 App integration capabilities, etc. to be refined based on HW on Friday 1/29). (Ash/Anthony)
F8 high "Create and send pre/post meeting emails from the email templates"
F9 high "Backup responders to Learner emails to Facilitators and Admins" (this is "Reporting")
F10 high "Email alerts"
F11 high "Create and send co-planning e-mail templates" (sending is "Scheduling")

**Comment by lijenn** [comment]
@anazariz @anthonycpichardo, just an update on cross-walking the **Customer Service Hub**:

**Static List - low level of complexity.**
F6 low "Import & Map Teams of Providers to Facilitators"
F12 low "Exchange online integration" **[need Ash's help as I'm not sure what I'm exactly looking for]**
F13 low ~~"Outlook integration" (an "add-in")~~ **[Add-in is available, missing permission and access error]**
F14 low "Outlook Integration: invitations" (a KEY story for informing the best fit for Outlook integration - "Dynamics 365 App for Outlook")
F15 low "Facilitator Assignment" **[could link Contacts to Accounts, use Accounts as MTL Teams]**
F17 low "Documentation/Notes" **[can't find a documentation/note field to add as an independent column into the overall dashboard, but can add a Description to Accounts/Contacts that are created]**
F18 low "File Storage/Access" (adding "fields")

 
**Dynamic List - medium level of complexity.**
F7 medium "Manage Team Schedules for MTL"
F16 medium "Standard CRM & Co-planning Dashboard Elements"

**Automation Flows - high level of complexity** (due to incomplete understanding of 365 App integration capabilities, etc. to be refined based on HW on Friday 1/29).
F8 high ~~"Create~~ and send pre/post meeting emails from the email templates" **[create templates available, unsure about sending workflow]**
F9 high "Backup responders to Learner emails to Facilitators and Admins" (this is "Reporting")
F10 high "Email alerts"
F11 high "Create and send co-planning e-mail templates" (sending is "Scheduling") **[found a rule creator, not sure if it'll meet our requirements, Ash could test this out?]**

FYI @staceypark

**Comment by anthonycpichardo** [comment]
Pushing forward with the Customer Service Module and James, Ash, Anthony, Jenn, Stacey, Matt and Jane will work through this module and familiarize ourselves with it.
