### ISSUE TITLE
wk2 due 2/16 (after Presidents Day): 2-3 Slides for PAVIR Board - HQ wg meeting 2/11 

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1671]
Put together 2-3 slides by 2/16 that describe our:
- research interests
- direction and goals
- the practicalities of growing our team to achieve our intended impact on improved VA care quality 
- composition of our research team (# of people working in our lab, shared facilities we use, sq ft occupied)
for the CEO to highlight at the board meeting.

This would focus on PAVIR projects: NIH R21, R01, and SAMHA MTL Hawaii grant.

**Comment by anthonycpichardo** [comment]
Bring to hq_workgroup on Thursday 2/11. Utilize visuals that can tell the story in a single slide.

- Research Interests (R21, R01, IIR) - Stacey
- Direction & Goals (SAMSHA replication, COVID19, Health Disparities, use of AI in healthcare) - Lindsey
- Practicalities - Team PSD 2.0 -> 2021 RoadMap ("limited scale problem.") - Anthony
- Composition - https://mtl.how/team (workgroups and website) - Jenn

**Comment by lijenn** [comment]
@lzim Updated the team slide with the 4 maps from mtl.how/team in the shared slidedeck in VA Teams in hq_workgroup channel under Files.
