### ISSUE TITLE
WK2 BISL Migration: Review Data UI SQL Queries and look for opportunities to optimize 

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1677]
Users are running into LSV runtime issues when pulling their data from the Data UI. 

This is a limiting factor on their ability to use our data tools and needs to be resolved.

Ash will review the queries and look for opportunities to speed up the time needed for execution.

**Comment by anazariz** [comment]
Have looked at potentials for optimization in DATA UI. Architecture (and optimization) may change depending on type of access to CDW and LSV.

**Comment by lzim** [comment]
@anazariz 
@anthonycpichardo 
Do we have documentation of the work completed for this, so that this can be closed?
Can we include **Story 5** in the title too?

I'm increasingly benefiting from filtering by the Story on the board.

**Comment by anazariz** [comment]
@lzim @anthonycpichardo 
I will update this ticket with the analysis that I have already performed. By Wed 2-24.
