### ISSUE TITLE
apr_epic story 4 QA Test: MTL technical manual 

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1679]
cross ref #1478 
@branscombj  @dlkibbe 

@lijenn @lzim and @staceypark  are working on putting together the MTL Technical Manual following the structure on #1478.
It would be great if one or both of you could review the manual for clarity, ease of use, comprehensiveness, etc. which you guys are awesome at 😄 

Once it is ready, you can review it here: mtl.how/manual

**Comment by staceypark** [comment]
update from 2/18 hq meeting: 
@lijenn and I plan to hand this over by COB Monday 2/18.
We are hoping you will be able to review by COB Wed 2/20, so we can make any updates/changes before the Facilitate meeting on Tues 3/2.

**Comment by lzim** [comment]
@staceypark @lijenn 

Can we confirm the answer to this at **8AM Workgroup Leads?**
_When can I and other Team PSD members get a training in how to add to a Bookdown?_

**Comment by lijenn** [comment]
Yes, I think Bookdown and an overview of what Stacey and I have for QA DEV of the MTL manual would be great for at least 30 min of this Thursdays 2/25 HQ meeting with the rest of the team.

**Comment by lzim** [comment]
@lijenn Will you put issue #1679 in the **hq_workgroup** meeting invite.

**Comment by hnorthcraft** [comment]
#adjudicate_memo adding operations label
