### ISSUE TITLE
june_epic QA PROD: MTL Manual - Review/Feedback at  Facilitate Meeting 

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1680]
Review MTL Manual at 3/2 Facilitate meeting for feedback.

**Comment by lzim** [comment]
@staceypark 
@lijenn 

Can we clarify ASAP at **8AM Workgroup Leads** when this will be reviewed by us BEFORE the **facilitate_workgroup** review on 3/2?
- [ ] DEV QA
- [ ] TEST QA
- [ ] PROD QA - Lindsey (pre-QIICs) 

I've signed up for PROD QA ideally ready by 3/1 Monday ~3PM latest.

Thanks!
