### ISSUE TITLE
Feature feb_epic: Story 6 - Configure CRM MVP

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1684]
wk2: Anthony, Ash, Jenn and Stacey configure CRM MVP  See flow map 1-5 & user stories F6, 9-13, 16, 17, 18?,19  & power apps/forms.
wk3: Anthony, Ash, Jenn and Stacey configure CRM MVP  See flow map 6-8 & user stories F7, 8, 14, 15

Keep @branscombj and Matt Moore updated.

cross ref wk 1: #1669 CRM Scope
> Static List - low level of complexity.
F6 low "Import & Map Teams of Providers to Facilitators"
F12 low "Exchange online integration" **[need Ash's help as I'm not sure what I'm exactly looking for]**
F13 low "Outlook integration" (an "add-in") **[Add-in is available, missing permission and access error]**
F14 low "Outlook Integration: invitations" (a KEY story for informing the best fit for Outlook integration - "Dynamics 365 App for Outlook")
F15 low "Facilitator Assignment" **[could link Contacts to Accounts, use Accounts as MTL Teams]**
F17 low "Documentation/Notes" **[can't find a documentation/note field to add as an independent column into the overall dashboard, but can add a Description to Accounts/Contacts that are created]**
F18 low "File Storage/Access" (adding "fields")
and power app/forms #1683

> Dynamic List - medium level of complexity. (Ash/Anthony)
F7 medium "Manage Team Schedules for MTL"
F16 medium "Standard CRM & Co-planning Dashboard Elements"

> Automation Flows - high level of complexity (due to incomplete understanding of 365 App integration capabilities, etc. to be refined based on HW on Friday 1/29). (Ash/Anthony)
F8 high "Create and send pre/post meeting emails from the email templates"
F9 high "Backup responders to Learner emails to Facilitators and Admins" (this is "Reporting")
F10 high "Email alerts"
F11 high "Create and send co-planning e-mail templates" (sending is "Scheduling")

**Comment by anthonycpichardo** [comment]
The app to use for development is published under the name "Modeling to Learn"

**Comment by anazariz** [comment]
We received new requirements and action plan during the Support WG meeting that should be posted here.

**Comment by lijenn** [comment]
Divvyed up tasks from Support WG 2/17:

ALL: Contribute and verify to our data dictionary cross walking Dynamics terms with MTL terms. (Looks like Lindsey created a glossary file: https://teams.microsoft.com/l/file/daf07176-b83c-4bfc-bddd-f87213bf85d2?tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf&fileType=docx&objectUrl=https%3A%2F%2Fdvagov.sharepoint.com%2Fsites%2Fteampsd_vha%2FShared%20Documents%2Fmsd365_workgroup%2Fcrm_updates_glossary.docx&baseUrl=https%3A%2F%2Fdvagov.sharepoint.com%2Fsites%2Fteampsd_vha&serviceName=teams&threadId=19:96e6417fb50d4323bbc588322e4a0866@thread.skype&messageId=1613602782323&groupId=1db500d5-0d01-4254-af42-ad3f78bafacd)
	
Branscomb, Jane M. - F8 Creating/transferring pre/post emails into Dynamics
	
Moore, Matt + ALL - Look more into how Campaigns work and how we could track the flow of the co-planning phase to the team phase ((F7, F16?).
	- Rollins, James M. (Praxis Analytix LLC) to look at technical aspects for how to set up a campaign in order to verify need to verify the proposal: We envision 5 "campaigns": co-planning, blue, redR01, redVA, follow-up. Each of these has a set of steps, activities, structures, and communication templates/schedules.
	
Pichardo, Anthony & Nazarizadeh, Afshin - F12& F13 Outlook and Exchange integration
	
Li, Jennifer - F6, F17 Import existing data of teams and facilitates.

**Comment by lijenn** [comment]
Discussed at 2/18 HQ Workgroup:
Tasks assigned at Support Workgroup will be split out to the assignees, these task cards will be tracked in the Feature tracker.

This card will remain open in Feature tracker for now for reference.
We will discuss this decision at **Feb_epic wk4 8am Workgroup Leads meetings**.

**Comment by anthonycpichardo** [comment]
If we're going to be breaking out the work as we've done for this card do we want to remove the week for the title?

@lijenn

**Comment by anthonycpichardo** [comment]
Pausing work on this. Moving to the icebox

**Comment by staceypark** [comment]
Liberty IT team will be in charge of the dev for this and we will review as users.
