### ISSUE TITLE
wk2 ASAP: Review option "A" for all 12 MTL Blue Post-test 

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1685]
Hi @branscombj & @dlkibbe!

I was reviewing some of the blue post-tests and wanted to double check if option "A" is the correct answer for all the 12 Blue session post-tests? Asking since I think some answers might not be option "A"?

**Here are some examples I had questions about, but would either of you be able to review the 12 post-tests just in case I missed something?**
**Please review Session 1-12 post tests here: https://github.com/lzim/teampsd/tree/master/ees_workgroup/post_tests**

EDIT: No review would be required if the changes were already made for MTL Video since we use the same post-test questions. Jenn will update Jane & Debbie.

Examples I caught:
Session 1
3. Which of the following creates a positive learning experience?
a. The learning was hands-on and experiential
b. The learning was based in an ideal world scenario
c. The learner learned from and taught others
d. Both a and c (is this the correct answer?)

Session 3
4. The data in mtl.how/data is presented:
a. Using means, medians and percentages
b. By VA VISN trends
c. In a format that allows a team to generate a team data table for use in the simulation model
d. Only a and c (is this the correct answer?)

Session 11
3. MTL Team Time reports are sent to MTL participants...
a. Once
b. Twice
c. Three times (Stacey confirmed this is the answer as 3x as they receive it once every 4 sessions).
d. Four times

4. MTL resources remain available to participants after completing the sessions...
a. For 1 week
b. For 1 month
c. For 1 year
d. Indefinitely (is it actually 1 week? I assumed it was indefinitely, but maybe I am wrong)

Session 12
4. Modeling to Learn resources include...?
a. A listserv [mtl.how@va.gov] (@lzim do we want to mtl.how or should we use mtl.help?)
b. Video sessions
c. Team time reports
d. All of the above (is this the correct answer?)

**Comment by lijenn** [comment]
Cross-checked if MTL Video had the correct options, but looks like MTL Video has outdated questions and answers.
Once the Blue Post-test are reviewed, we will need EES to update the post tests for both MTL Video and MTL Live.

Examples I caught for Session 11 crosswalk before I got a TMS error:
![image](https://user-images.githubusercontent.com/59668647/107272373-73c98e80-6a02-11eb-8775-a906333b75f0.png)
![image](https://user-images.githubusercontent.com/59668647/107272473-9a87c500-6a02-11eb-8ec4-38b2544e20c9.png)

**Comment by lijenn** [comment]
@branscombj @dlkibbe Let me know if it's possible that you guys might have a local word document with the most up to date post-tests questions and answers for MTL Blue? 

Asking since I noticed the post-tests for MTL Red Jane had sent me are more up to date that the ones [here](https://github.com/lzim/teampsd/tree/master/ees_workgroup/post_tests) in the repository.

**Comment by dlkibbe** [comment]
I'll look for the original word file @lijenn @branscombj

**Comment by branscombj** [comment]
[posttests1thru12_final_blue.docx](https://github.com/lzim/teampsd/files/5947270/posttests1thru12_final_blue.docx)
@lijenn I proof-read all 12 and found a couple more required updates. Two that we may need to check other documentation for are:
1. Discussion of browser limitations for the data UI.
2. Discussion of number of runs that can be compared in the sim UI (we increased it from current + 2 to current + 3).

I will now align Red Part 1 & 2 posttests with these.

**Comment by branscombj** [comment]
[posttests1thru2_final_red.docx](https://github.com/lzim/teampsd/files/5947490/posttests1thru2_final_red.docx)

OK @lijenn here is the parallel post-test set for MTL Red!

**Comment by branscombj** [comment]
> [posttests1thru2_final_red.docx](https://github.com/lzim/teampsd/files/5947490/posttests1thru2_final_red.docx)
> 
> OK @lijenn here is the parallel post-test set for MTL Red!

You will update the GH files with these and forward them to Joe?

**Comment by lijenn** [comment]
Hi @branscombj! Was reviewing before updating/sending the post-tests, I think Session 5, question 4:

> 4. The MTL sim UI is not compatible with 
a.	Explorer/Edge 
b.	Chrome 
c.	Firefox 
d.	Safari

The SIM will work on Edge, it just doesn't like Explorer. 
Let me know if you want me to correct that, but everything else looks good to me!

**Comment by branscombj** [comment]
Yes please correct that. Thanks for catching it!

**Comment by lijenn** [comment]
Hi @staceypark Would you mind giving this 1 last review before I send it to EES?
[posttests1thru12_final_blue.docx](https://github.com/lzim/teampsd/files/5954842/posttests1thru12_final_blue.docx)

**Comment by staceypark** [comment]
@lijenn answers look correct !
