### ISSUE TITLE
wk2 mar_epic MTL Manual: Add Team Name to Session Header.

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#1687]
THREE issues:

1) I logged in as a facilitator, then chose JaneBranscomb's IND world and Home. The User in upper left is listed as VA-PSD, Facilitator - not as me. Is that how it should show?

2) I ran a series of random sims trying to test how many runs can be compared (to make sure one of our post-test questions isn't outdated), but none of the runs I've named and then "Save and Exit"ed is showing up in the dropdown menu in Compare Experiments. I'm in AGG, using Chrome, logged in as described above.

3) I tried to use the bug report in the sim to report the above, but I got Error: Something went wrong. Please try again. I did not check the box saying I had a screenshot.

**2. Click on the right:**  
i. **Pipelines** - prioritize in a TeamPSD (& Workgroup) pipeline  
ii. **Assignee** - assign to an individual team member producing work for the issue  
iii. **Label**- assign workgroup (lead) responsible for tracking the task  
iv. **Projects** - assign to domain-specific TeamPSD tracker (issues, features, document, manuscript, team)  
v. **Milestones** - select monthly sprint milestone within the workgroup   
vi. **Estimate** - Estimate task in complexity points   
vii. **Epics** - assign to team-wide epic and TeamPSD master plan project  
iix. **Releases** - assign to key team release grouped with other relevant issues  

**3. If you anticipate that your **issue card** or **bug card** will have **dependencies** these can be added once the issue has been submitted.   
ix. **Add dependencies** - assess for and add dependencies *blocking* & *blocked by* this issue

**Comment by jamesmrollins** [comment]
Hi @branscombj 
 
**Regarding Item 1 above:**  The upper left identifies the team, not the individual, unless it is an individual team world. When you are a facilitator who is registered in the Facilitator Group, you will always have the VA-PSD Facilitator moniker, because you going into your individual world as a facilitator. If you deregister yourself from the Facilitator Group, AND change your facilitator role in the individual team world to "No" AND assign yourself to a world, you will see your team name in the upper left.

**Regarding Item 2:**  Did you try to "Save and Reset?"  or just "Save?"  If you don't reset, the experiment file stays open and will not register on your alternatives or previous experiments drop down.  I just ran through and saved several experiments, and it appears to function as designed.

**Regarding Item 3:**  That error occurs when the browser is not able to communicate with Github.  It is a GitHub API that is moving the bug information to the GitHub repo.  Since I can only affect client-side  actions, I cannot store the bug until communications is restored.  Anthony discovered this before, but I don't have a way to solve the problem at this point.

**Comment by branscombj** [comment]
> Hi @branscombj
> 
> **Regarding Item 1 above:** 
Got it, thank you!

> 
> **Regarding Item 2:** Did you try to "Save and Reset?" 
Yes, I meant to type Save and Reset not Save and Exit in my description. I will give it another go when I have a minute and let you know if I have the same issue.
> 
> **Regarding Item 3:** That error occurs when the browser is not able to communicate with Github. 
OK.

Thanks for your responses @jamesmrollins !

**Comment by lzim** [comment]
@jamesmrollins - Are these all resolved?
- [ ] How much of a hassle is it to change the name of the "Facilitator Team?" For example, I would think that "Facilitator" would be simpler and that "VA-PSD" is actually potentially a little redundant and/or confusing.

FYI: @lijenn and @staceypark 
@branscombj 

These three points all strike me as information that needs to be documented in the **_MTL Facilitation & Technical Manual_**

**Comment by jamesmrollins** [comment]
@lzim 

1.  Are all these resolved?  In my mind, yes.
2.  VA-PSD is what has always been there.  I will change it to "Facilitator"

**Comment by jamesmrollins** [comment]
@lzim @branscombj -  My information was dated, @hirenp-waferwire says we now have functionality where we can include the team name in the title.  It can say "your_team, Facilitator" in the header.  I would take us 4-5 hours to implement the code for this.  Do you want us to proceed?  Thank you, James

**Comment by lzim** [comment]
@jamesmrollins 
@branscombj 
@staceypark 
@lijenn 

Let’s briefly touch base about this at **8AM Workgroup Leads,** before implementing.

I think if “your_team” in James’ comment is the standard team name that will correspond to their team name in the team data file, then this makes sense to implement. 

I do not like the way it looks now.

**Comment by lzim** [comment]
**Key: O.H.I.O.**

- [ ] Will need: 570_team_name (# of char)...
- [ ] Ideal state: Set it up together at meeting...
Co-planning...
- [ ] James will review how the information is being ported in.

**Comment by jamesmrollins** [comment]
### Summary  
We can support adding the team name into the header based on the epicenter team name.  The team name can be truncated after any number of characters. An ellipsis at the end is possible. 

### Decision
Would like to maintain at least an inch of visual space and truncate from there – make it dynamic.

**Comment by jamesmrollins** [comment]
@hirenp-waferwire   Please add the team name to the header of the session web page, before the "Facilitator" title  (see below).  Truncate the team name to 12-15 characters, or a minimum of 1" of visual space.  Place an ellipsis ( . . . ) between the truncated team name and the Facilitator title.  I know we are challenged for room in the header - do you best.

![image](https://user-images.githubusercontent.com/30132017/110178783-cdcc3280-7dbb-11eb-8371-df3b0382506b.png)

**Comment by jamesmrollins** [comment]
@lzim  Below is what we have come up with in Test.  It appears to be able to fit the whole team name. We have a little work to do on how it handles tablet mode. 

![image](https://user-images.githubusercontent.com/30132017/110579940-8d9ee400-811c-11eb-9aef-98a64c406943.png)

**Comment by jamesmrollins** [comment]
and tablet mode is fixed

![image](https://user-images.githubusercontent.com/30132017/110655975-6542d400-8174-11eb-8da1-50bb69d1816f.png)

**Comment by jamesmrollins** [comment]
##Decision - use the ellipsis as the universal separator between team name and "facilitator."

We'll keep as much of the team name as we can, recognizing that there's responsive web design. e.g.,
"XXX_harm_reduction_dual_diagnosis...Facilitator"
