### ISSUE TITLE
 Story 1: Authorship 2.0 development

### ISSUE THREAD

**Issue by dkngenda** [lzim/teampsd#1688]
split from #1437 
**Authorship_App 2.0 features: **
- [ ] ability to add new papers and workgroups directly on the app.
- [ ] change any unclear flows.
- [ ] Add something that checks sum of write_analyze contributions.
- [ ] Ability for authorshipApp to export work estimates from the board to determine prior work categories.

[Authorship App](https://teampsd.shinyapps.io/teampsd_authorship_app/)

**Comment by lzim** [comment]
@dkngenda 
@staceypark 

Can we please use the **title** and **9 clicks** to clarify where this fits into **weeks** and **epic piplines**?
**I am also increasingly appreciating the ability to filter/search by story.**
This is **Story 1** right? Can we add to the title?

If you have any questions about where this fits, please bring it up at **8AM Workgroup Leads** 

Thanks!

Lindsey
