### ISSUE TITLE
wk2 QA Test: Review mtl.how/data Folder one-pager for Admin/Facilitator users

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1689]
Reviewer card for QA Dev in #1674.
- [ ] Instructions on how to change a team's folder name is clear and easy.
- [ ] Folder naming convention instructions are clear.
- [ ] Instructions on how add users to a team folder to grant folder permissions is clear.
- [ ] Visuals are clear and simple to follow.

**Comment by staceypark** [comment]
@lzim here's the updated one pager. Please take a look!
![mtl_how_data_folder_cheatsheet](https://user-images.githubusercontent.com/31089501/107300054-9624d180-6a2d-11eb-9a9e-d0309777f0de.png)

**Comment by lzim** [comment]
Initial look is good @staceypark  and @lijenn  Thanks!

I will review more carefully but I do not the divergent font for "Team Naming Convention" right away.

**Comment by staceypark** [comment]
@lzim barring any other edits from you, here is the latest on this from #1674 

> updated one pager based on feedback from @lzim (#1689) and QIICS
> 
> * change naming convention flow font to myriad pro
> * add details about what resources are in Master Data UI folder
> * rename file to include the word "facilitator" to clarify difference bewteen mtl.how/data cheatsheet and the mtl.how/data facilitator one pager
> * created #1699 for propagating to every facility
> * already updated mtl.how blue s2/3 and red part 1/2 facilitator folder to include new one pager

**Comment by lzim** [comment]
@lijenn I'm not sure what this is, it says reviewer card for #1674, but I'm not seeing a clear blocking chain on this.
