### ISSUE TITLE
Update IIR baseline/6mos measures in RedCap 

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1693]
- Add demos to RedCap (you can find the updated measures in the grants folder > r01 > appendix > final > measures_revised_demographics)
- See #1692 for measures order from Lindsey

**Comment by lzim** [comment]
@staceypark @lijenn 

Please use the **9 clicks** and update the **title** to clarify *epic* *week* etc.
Technically, I believe this can wait until another epic, if we're pressed on capacity now.

But, it needs to be estimated and tracked. Thanks!

**Comment by dkngenda** [comment]
@staceypark @lijenn Looks like at Thursday HQ meeting (9/24), it was decided that study arm should not be part of the randomization. Please see if the randomization [here](https://github.com/lzim/research/blob/qa_branch/survey_randomization.R) meets that requirement

**Comment by dkngenda** [comment]
@lijenn Check the updated randomization scheme. It looks like we will use the randomization scheme I had previously

**Comment by lzim** [comment]
@staceypark @lijenn @dkngenda 

Is this done, can this be closed?
Can this be closed?
