### ISSUE TITLE
wk4_feb_epic Data UI: Propagate new mtl.how/data facilitator one pager 

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1699]
Add mtl.how/data facilitator one pager to Master_DataUI folder for each facility.
You can find the file here: https://github.com/lzim/mtl/blob/master/blue/session02/s02_facilitator/mtl_how_data_facilitator_one_pager.pdf

FYI @lzim - Anthony will wait to propagate this until we are finished co-planning. However, I did manually add a copy of this to 666 for casper. Sorry realizing we probably should have updated and finished before st. louis and added there too 😅

**Comment by lzim** [comment]
@anthonycpichardo and @staceypark 

Where are we with this? I edited the title to reflect where I believe it needs to be scheduled.

**Comment by anthonycpichardo** [comment]
it was completed over the weekend. This can be closed.
