### ISSUE TITLE
Change default for which tiles are open in the UI

### ISSUE THREAD

**Issue by TomRust** [lzim/teampsd#170]
@jamesmrollins 

We just walked the team through the CC model.  Since we have to start with the experiments tile before we can see any outputs, is it possible to change the default for which tiles are open?

Specifically, how easy is for the Experiments Tile be open by default instead of the Outputs Tile?  I'm not suggesting a change to the layout, just which Tile is open.

--TOM

PS. If this is easy, could you add the rest of the team to this issue thread?  Thanks!

**Comment by lzim** [comment]
@TomRust and @staceypark @jamesmrollins 

James is going to make this change.  I also explained the expanded output chart defaults bug we experienced earlier and he's going to get the developers working on that too.

Thanks,

Lindsey

**Comment by jamesmrollins** [comment]
@TomRust 
Done!

**Comment by lzim** [comment]
So cool!!! Thank you.
