### ISSUE TITLE
Bug: Error message on facility file 

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1700]
I got this error message from the 666 facility file.
I just opened it and hadn't clicked on anything yet.
It has not produced any other problems yet as a result of this though. But not sure why it came up to begin with.

![image](https://user-images.githubusercontent.com/31089501/107699279-b7becc80-6c6a-11eb-90d4-5385e2a4706c.png)

**Comment by anthonycpichardo** [comment]
Hey Stacey, i haven't been able to reproduce this error. 

Are you still seeing this?

If not, we can close.
