### ISSUE TITLE
wk1 mar_epic: Authorship QA prod

### ISSUE THREAD

**Issue by dkngenda** [lzim/teampsd#1702]
@lzim As you review the app below are somethings to pay special attention to. They are organized by tabs within the app.

- split from #1437.
- New app functionality recommendations are being tracked on #1688 
- Authorship link -> [Authorship App](https://teampsd.shinyapps.io/teampsd_authorship_app/). 

QA Prod card details: 
## 1. workgroup:
- [ ] Review instructions for clarity.
- [ ] Calendar pops up when date text box is clicked.
- [ ] After selecting right paper and clicking submit, text below the button mentions the right paper.

## 2. prior_work:

- [ ] Review instructions for clarity.
- [ ] Click in the textbox and check whether you can select subcategories by using dropdown menu or searching by keyword

## 3. prior_work_rank

- [ ] Review instructions for clarity.
 **_Under prior_work_weights_**
- [ ]  Change subcategory weights, submit them and verify whether the pie chart changes appropriately
- [ ]  Check to see if there is an error message when your enter and submit subcategory weights.
**_Under manuscript_prior_work_summary_**
- [ ] Review Instructions
- [ ] Check if all navigation buttons and search box for the table are functional.
- [ ] Does the entries in prior_work_contribution add up to the percent assigned to prior work 
- [ ] Check the pie chart to see if all contributors in the table are also represented in the pie.
**_saved_prior_work_**
- [ ] Test the table navigation buttons and search box to review prior work assigned to other papers. 

**4. write_analyze_edit**

_select_authors_
- [ ] Review instruction for clarity
- [ ] Select authors and verify that all of them are listed in the identified contributors section.
**_author_contributions_**
- [ ] Review instruction for clarity
- [ ] Enter authors contributions and verify that they are reflected in the pie chart.

**5. author_order**

- [ ] Review instructions for clarity
- [ ] Check if all navigation buttons and search box for the table are functional.
- [ ] Check to see if all contributors (prior work, write, analyze and edit ) appear on the pie chart.

**6. authorship_overview**
- [ ] Review Instructions for clarity
- [ ] Check if all navigation buttons and search box for the table are functional.

** To verify whether your entries have been stored. Refresh the browser then** 

- [ ]  Go to prior_work_rank >>saved_prior_work. This table should show assigned prior work for the paper you've worked on
- [ ]  Go to  authorship_overview tab. All paper with authorship assigned should appear hear 

**Adding a subcategory** 
- [ ] Go to 2. prior work > add_edit_prior_work_subcategories. Select the appropriate option and review instructions for clarity. 

- [ ] To review any changes to authorship, refresh the app page

**Comment by lzim** [comment]
Discussed at **hq_workgroup**

**QA PROD** - Lindsey will receive this in the **4th week of the epic.** 

Lindsey will review with anticipation of no issues. 

But, if we need to discuss the app please get it on the agenda ASAP.
@staceypark @dkngenda

**Comment by dkngenda** [comment]
**UPDATE**
@lzim I have addressed @staceypark feedback on issue #1686  but I am running up against app deployment issues. The App runs fine in R studio but for some reason it's not deploying on teampsd shiny account. I am still trouble shooting this so I can hand it over to prod QA

**Comment by lzim** [comment]
@dkngenda 
@staceypark 

Can one of you please grab the review from **qual_workgroup** yesterday and add them to this QA PROD issue?

I recall that we wanted to be able to
- [ ]  **save** more often.
And, I believe there were a couple of text changes too that need to be added to this card.

I'm moving this to **wk5_mar** and assigning to @dkngenda for in advance our next meeting with **qual_workgroup** during **wk2_apr.**

**Comment by dkngenda** [comment]
New functionalities requested are being tracked on #1688. 

I started #107 yesterday to track other changes requested that do not involve restructuring the Apps logic.
