### ISSUE TITLE
wk2 mar_epic: Story 5/6 - Co-Planning Documents on Teams/SharePoint

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1705]
Story 5: SharePoint Online 365
Story 6: Co-planning documents

We want a cloud-sharing of our Co-planning documents that integrate with workflows for Story 5 & 6.
These shared documents need to be on the cloud (SharePoint or Teams).

Story 5:
- [ ] PI User Lindsey: **Queueing** up specific data parameters during co-planning meetings (~30 min prep time), need to **cache**/save.
LZ has these documents/data/parameters opened up almost all day. We are now showing leaders the data in co-planning and not waiting until Blue Session 2/Red Part 1. 

Queuing: Preparing selections in advance before the meeting (risk for Facilitator and front-end MTL users)
e.g. Leaders would select their clinic and the queue would run overnight.

Cache: Make a bunch of selections live in the moment and have the selections automatically saved for hand-offs.
e.g. If someone has a outage, someone else can support.

Story 6:
- [ ] These are all the co-planning documents (agenda, notes doc, stakeholder map, process map), that we need to open and use during the co-planning meetings.

We need to figure out a workflow on how to efficiently store and pull these documents for cross-coverage.

**Comment by lijenn** [comment]
Discussed at HQ WG 2/18:
@lzim & @lijenn 2/19 Friday 8:30 - Migrate Wave 1 NIH teams folder documents to Teams to cache this.
Pick up Story 5 & 6 at wk4 feb_epic Monday 8am wg.

**Comment by lzim** [comment]
@staceypark 
@anthonycpichardo 
@lijenn 
@anazariz 

This is one of our most important tasks to discuss at **8AM Workgroup Leads.**

I am re-thinking the decision to just use **Outlook** invites for teams.
I believe  want a **Channel/Sharepoint** for each team to achieve the **caching** needs we discussed on Thursday.

**Comment by lijenn** [comment]
@lzim @staceypark  @anthonycpichardo 

I'm just brainstorming how having meetings in channels could work.

To set up a Teams group for MTL Learner Teams, we must:
1. Create a Teams group (name: Modeling to Learn?)
2. Add all Learners as members into the Teams group
3. Create Private channels based on team name/site and assign Learners to their respective channel (Facilitators, Support WG, Admin will have access to all private channels) 
   - [private channels will prevent Learner teams from seeing each other's channel and info. unless Learners have been granted access to that channel)
4. Create the Team meeting in the Private Channel and copy and send the invite to ourselves
5. Copy and Paste the meeting link into a New Appointment invite in Outlook from the MTL.Help calendar and send the invite to the Learners (if any one from Admin is out or a date/time needs to be changed, someone else could edit the meeting invite this way)

Question:
6. Will the co-planning documents go into the new Team's group/channels or teampsd_vha in facilitate_workgroup channel (i.e where should Facilitators meet for inter-session prep, if Facilitators needed to pull these documents up while driving a meeting where should it go, how will Learners/Team Leads view/edit with these documents, **if docs should be in both the new Teams group and teampsd_vha how can we sync and cache the docs all together**)?
    - co-plan 1 agenda
    - co-plan 2 agenda
    - stakeholder map
    - process map
    - notes (this doc would probably not be in the new Teams group?)

**Comment by anthonycpichardo** [comment]
Note : Files uploaded to a teams chat are saved to the uploaders personal sharepoint and are accessible by everyone in the group thread.

**Comment by anthonycpichardo** [comment]
Discussed During 2/22 Workgroup Meeting:

Create the team at Sharepoint -> Teams Private Channel

...and the permissions would flow in that direction...

"Microsoft 365 Group"
User for hybrid Story 5/6 for #1705:
"O.H.I.O." or"O.P.I.O." 
- Story 9...

Only set them up and permission once for all our 365 resources.
- Microsoft Teams
- Microsoft Power BI
- Microsoft Dynamics

Inherited by Story 5 - Power BI
Inherited by Story 6 - Dynamics
Where does this "365 group" fit: "Entity structure in 365 app ecosystem."


P.I. reaction
"There is meaningful data structure in our org chart that may make sense in terms of our user permission to fully think through."
Key idea is that users would be permissioned into resources.
Organization Hierarchy determines permissions:
VISN ->
Facility (sta3n) ->
Clinic (sta6a) - >
Team

Questions: 
- What is our short-term plan?

- wk4 feb epic:

Check Microsoft documentation "Microsoft 365 Groups" documentation for our 3 apps we would like O.P.I.O. (Teams, Power BI, Dynamics [365].

Check VHA documentation for use of 365 groups (BISL, PSF; OIT partners) or other ways of inheriting permissions across our apps using 365
Groups
As an example, in our future state: (we don't want re-invent wheel and we don't want be inconsistent with VA norms/standards in 365 use.
Is there an OMHSP or some other standard in VA we should easily align with now?


Divvy Up - 1st step of stories to avoid rework...

*Hierarchy of Permissions in our Entity relationship**
Story 5/6...hybrid if we inherit from 365 groups
e.g., Story 6 on its own
Accounts (VISN/QIICs, Co-Planning) > Contacts individuals nested in teams (365 Dynamics specific)

What we really need:
VISNs (co-planning, permissions, documntation) ->
sta3n ->
sta6a ->
teams

"Right first step to avoid rework for all 365 Apps" needs to be
MTL pre-emails for all teams

wk1 mar_epic... If 365 Groups were set up -> Micrpsoft Teams (app) would inherit the 365 groups.

- Outlook invite to the meeting... 
- Shared documents for co-planning...

Background:
Grant & Story 5 & 6
wk1 (week before team meetings)
wk2 (Monday of their meeting)

R21 - Same week of team meeting
pre reminder of meeting
post is reminder of the homework.

Rework 
- videos weeks 1-24.
- pre/post "This week"

Implement 365 Groups inherited by Teams 
- wk1 mar_epic (next week).

O.H.I.O. Method
O.P.I.O. "O.Permission.I.O"

Ash <> "365 Group" inheritance 
Microsoft Teams (due 1st), look ahead (START HERE).
Microsoft Power BI (Stories 5) &
Microsoft Dynamics (Story 6).


Anthony - "365 Group" in VHA with our partners.

Stacey - pre/post email text changes to reflect weekly emails.

**Comment by anthonycpichardo** [comment]
Discussed at 1pm Team Time 2/23:
- The issue:
	- We were trying to figure out how to add providers to the teams on Thursday.
	- Jenn was unable to find the email of a provider due to an outdated map.
	- How could we more efficiently get this data and add them to email invites, the data folder on the BISL site, etc.
	- Hoping that something with Story 5 and 6 can help resolve the permissioning issue
- Mtl.help will be the master schedule and it will be color coded for Red Teams, Blue Teams, and Co-planning.
  - Jenn was trying to email folks from the Exchange admin list. 
  - Lindsey was providing permissions to the same users.
**We can lose teams by sending extra emails.**

**Comment by anthonycpichardo** [comment]
The reason that mtl facilitators and admins are sending them from mtl.help is so that we have ownership permissions to be able to change the invites.

**Comment by anthonycpichardo** [comment]
Using Teams to Create Groups

Pros:
- We can do this NOW from Teams
- Having a group email that contains everyone seems helpful for facilitators, email invites, etc.
- We believe it will sync to Story 5 permissions in the future
- We can benefit from the Teams functionality

Cons:
- 56 separate Groups and Sharepoints (not enforcing standardization can be chaotic)
- Awkward name of the email address (will they see this?)
- Does not seem to solve permissioning on on-prem BISL (Anthony will explore this further)
- Would be great if it was coordinated with the MTL name and brand

Questions:
Is there any way to link all 56 Groups together? (i.e., MTL).
How does it interface with onprem BISL?
How does these groups interface with Story 6?


**Teams Channel Sharepoint Modifications**
Standard Blocks on Sharepoints
Documents in Main Block
Quick Links on the Right Block

Remove these Blocks
News
Activity
Comments

Remove Everything from Left Bar
Home
Documents

Documents
folder: "local_co-planning"

Add Message:
- "Your team data user-interface (Team Data UI) includes PHI and should only be stored at https://mtl.how/data."

Uploaded Images:

Team Group - mtl.how/red or mtl.how/blue logo

Custom Image Thumbnails:
- mtl.how/data (have this)
- mtl.how/sim (have this)
- tms (have this)
- "community" button (have)

**Comment by anthonycpichardo** [comment]
Conclusion: 
56 groups solves end-user painpoints and is a permission solution for Team PSD members.

"Owners" when setting up the Group in Teams
- MTL Admin - Jenn, Stacey, Lindsey
- Relevant QIIC 
- Co-Facilitators

**Comment by lijenn** [comment]
**Additional proposals/to-dos** and **Blockers** before we notify the teams:
- [ ] Consider adding a channel for team meetings (e.g channel name: team meeting) since we have a co-planning channel and we wouldn't want to have the team meetings/chat thread be in the co-planning channel.
- [ ] A top Tab link to the SharePoint site - using the 'Open in SharePoint' button from the Files tab only brings you to the document folder of the channel that you are in, not to the actual homepage of the SharePoint site.
- [ ] Create the learner cheatsheet #1793 
- [ ] Draft email is in MTL.Help and ready to be sent out to teams
Confirm start dates for
- [ ] 570
- [ ] 589
- [ ] 666
- [ ] 660

Think through how to incorporate:
- [ ] 570 since their next meeting is MTL Red Part II

**Comment by staceypark** [comment]
Edit the message at the top " "Your team data user-interface (Team Data UI) includes PHI and should only be stored at https://mtl.how/data." - to have **red bold font**

**Comment by lijenn** [comment]
@lzim @staceypark @anthonycpichardo 

I was not able to send out the emails yet, making **final edits** and **thinking through my steps (see edits and checklist below)**.

**Edit: Current way of getting to the homepage of the SharePoint site is a little confusing/lots of clicks**:
Go to the General Channel > Files > click Open in SharePoint > click on the MTL logo on the SharePoint page that comes up > gets to Homepage of SharePoint site.

**New way: Add the HomePage of the SharePoint as a tab in the MS Teams group**:
General Channel > SharePoint tab > gets to HomePage of SharePoint site within MS Teams.
![image](https://user-images.githubusercontent.com/59668647/110400543-a6c86780-802c-11eb-81f3-e64e26615887.png)


Goal is to **send the emails out tmrw AM ASAP**. 
Reiterating the manual steps that I'll be taking and commenting here for documentation purposes (and mental model check!):
- [ ] 1. Ensure the VA Teams and SharePoint sites are clean and ready.
- [ ] 2. Finalize draft email to the 2 teams for this week + attached VA Teams/SharePoint Cheatsheet that Stacey is helping give a final review.
- [ ] 3. Generate the MS Teams meeting link within the Teams Channel (will not include invitees/emails here yet as the meeting invite should come from MTL.Help's Outlook)
- [ ] 4. Add bulk load to 0365 groups.
- [ ] 5. Use the email distribution email to send out the following emails:
- [ ] a. Meeting invite to reserve the team time in the calendar
- [ ] b. The 0365 email + cheatsheet
- [ ] c. The Pre-email [some trouble getting the tables to show up in HTML, Stacey giving tips in background).
