### ISSUE TITLE
wk2 apr_epic: Update Costing and Create Excel sheet by Quant WG 4/15.

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1709]
1. Move costing chart from lucidchart to excel on VA Teams
2. Add actors and times for actions.

Continuation of #1650

**Comment by lzim** [comment]
@lijenn @staceypark 

Can we clarify when this will be set up for Libby and I to add to?

It should be migrated probably **wk1 mar_epic** then two dependent wk2 cards assigned to Libby for review of **_MTL_ activities to be costed** and a card assigned to Lindsey to review **categorize _MTL activities in relation to ERIC strategies.**
Then, discuss at **wk3 quant_oper** make sense?

**Comment by staceypark** [comment]
closing this initial card. Adding three new cards based on today 4/22's budget impact meeting
