### ISSUE TITLE
wk4: QA Test Review MTL Technical manual

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1711]
@lijenn and I are working on putting together the MTL Technical manual right now.
We will be presenting this during the 3/2 facilitate meeting for final review.

We were hoping to have this handed over to you no later than Monday 2/22 for your review.
Would you be able to review and hand over no later than Wednesday 2/24 afternoon for us to update with any fixes before the Tuesday 3/2 meeting?

**Comment by staceypark** [comment]
sorry this is a duplicate of #1679

**Comment by hnorthcraft** [comment]
#adjudicate_memo adding operations label
