### ISSUE TITLE
may_epic - R01 submission: Email Imp Sci Editor about Supplementary Materials.

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1712]
- Task: Email Imp Sci editors if we can attach a .pdf with a link to the R01 OSF because Imp Sci specified that they do not want links, only files, for Supplementary Materials. 
    - LZ to review if this format is okay with Imp Sci. to close #1379 
- R01 notebook pending to be added as a resource.

Direct link to the additional_files.docx in the OSF: https://osf.io/cp65q/

**Comment by lzim** [comment]
@lijenn 
@staceypark 
@dkngenda 
@anthonycpichardo 

I reviewed this more carefully, I would like to include the .pdf of all the links in my letter to the editor. 

Let's discuss in relation to the R01 Manuscript blocking dependencies at **8AM Workgroup Leads.**

**Comment by lijenn** [comment]
@lzim 
@staceypark 
@dkngenda 
@anthonycpichardo 

Here is a word doc of the list of Additional Files (Imp sci refers to Supplementary Materials as Additional Files).
I did not include a link to the R01 Notebook (will this be uploaded onto the OSF?). 

Note: Links to the documents in OSF will not work/be broken links for people who are not added into the OSF until the OSF is made public.

![image](https://user-images.githubusercontent.com/59668647/109086451-709bf700-76c0-11eb-8d80-4ebf4e4ff273.png)
[Uploading r01_imp_sci_additional_files.docx…]()

**Comment by lijenn** [comment]
Direct link to the additional_files.docx in the OSF: https://osf.io/cp65q/

**Comment by lzim** [comment]
We are working on our special issue and close this. Thanks!
