### ISSUE TITLE
MOVED: w2 mar_epic: Send MTL Red Baseline Survey to Fresno (1st team)

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1713]
Send out MTL Red Fresno's Baseline Survey 

wk4  feb_epic for 570_fresno_pcmhi

After MTL Red Part 1 MTL Blue Session 1, separate and before the post-email (next week) - Provider survey is ready to send.
- IRB approval received for demographic mod.
- Demographics are programmed in the survey.
- Shortlinks for the survey that is easy for the team. 
    - Example: mtl.how/570_fresno_bhip_feedback1 (baseline/pre)
      mtl.how/570_fresno_bhip_feedback2 (6 month/post)

@staceypark We need to send them the survey on Thursday 2/25 AND finish the **R01 protocol** (need to determine if this feasible)

**Comment by lzim** [comment]
TBD when this will go out based on #559 [jan_2021_submit] r01_protocol_impsci - https://osf.io/8pzxu/

**Comment by lijenn** [comment]
now tracked in mtl_team_tracker/issues/23. Removing 9 clicks to prevent inaccurate ZenHub data.
