### ISSUE TITLE
Control Panel in Expanded Outputs AGG

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#172]
Hi @jamesmrollins @TomRust @staceypark @dlkibbe @branscombj 

Hi James, the changes we discussed last night are there. Hurray!

One thing we missed:

In the Control Panel in Expanded Outputs in AGG:
- The compare services radio needs to be changed from "Review" to "Intake" there as well.

Thanks!

Lindsey

**Comment by jamesmrollins** [comment]
@lzim 
Noted - will put on tonight's push.

**Comment by jamesmrollins** [comment]
Corrected
