### ISSUE TITLE
wk4 feb_epic: Story 6 CRM - Implement Outlook and Exchange integration

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1720]
Card is split from Configure CRM MVP #1684

@anthonycpichardo & @anazariz - F12& F13 Outlook and Exchange integration
Please assign your estimates.

cross ref wk 1: #1684 CRM Scope
> Static List - low level of complexity.
F6 low "Import & Map Teams of Providers to Facilitators"
F12 low "Exchange online integration" **[need Ash's help as I'm not sure what I'm exactly looking for]**
F13 low "Outlook integration" (an "add-in") **[Add-in is available, missing permission and access error]**
F14 low "Outlook Integration: invitations" (a KEY story for informing the best fit for Outlook integration - "Dynamics 365 App for Outlook")
F15 low "Facilitator Assignment" **[could link Contacts to Accounts, use Accounts as MTL Teams]**
F17 low "Documentation/Notes" **[can't find a documentation/note field to add as an independent column into the overall dashboard, but can add a Description to Accounts/Contacts that are created]**
F18 low "File Storage/Access" (adding "fields")
and power app/forms #1683

> Dynamic List - medium level of complexity. (Ash/Anthony)
F7 medium "Manage Team Schedules for MTL"
F16 medium "Standard CRM & Co-planning Dashboard Elements"

> Automation Flows - high level of complexity (due to incomplete understanding of 365 App integration capabilities, etc. to be refined based on HW on Friday 1/29). (Ash/Anthony)
F8 high "Create and send pre/post meeting emails from the email templates"
F9 high "Backup responders to Learner emails to Facilitators and Admins" (this is "Reporting")
F10 high "Email alerts"
F11 high "Create and send co-planning e-mail templates" (sending is "Scheduling")

**Comment by lzim** [comment]
FYI added **dependencies**.

**Comment by anthonycpichardo** [comment]
Pausing development of CRM for the time being. 

Closing.
