### ISSUE TITLE
wk4 feb_epic: Create VAPOR Video Quicklinks 

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#1725]
@erinash 
Thanks for being willing to set up the **quick_code URLs for these VAPOR videos.**
This way the **pre/post emails** are 
a) easier to code, and 
b) will always be current even if we need to update the video links again at some point.

FYI: @lijenn @staceypark 

- [x] mtl.how/vapor_wk01
- [x] mtl.how/vapor_wk02
- [x] mtl.how/vapor_wk03
- [x] mtl.how/vapor_wk04
- [x] mtl.how/vapor_wk05
- [x] mtl.how/vapor_wk06
- [x] mtl.how/vapor_wk07
- [x] mtl.how/vapor_wk08
- [x] mtl.how/vapor_wk09
- [x] mtl.how/vapor_wk10
- [x] mtl.how/vapor_wk11
- [x] mtl.how/vapor_wk12
- [x] mtl.how/vapor_wk13
- [x] mtl.how/vapor_wk14
- [x] mtl.how/vapor_wk15
- [x] mtl.how/vapor_wk16
- [x] mtl.how/vapor_wk17
- [x] mtl.how/vapor_wk18
- [x] mtl.how/vapor_wk19
- [x] mtl.how/vapor_wk20
- [x] mtl.how/vapor_wk21
- [x] mtl.how/vapor_wk22
- [x] mtl.how/vapor_wk23
- [x] mtl.how/vapor_wk24

**Comment by erinash** [comment]
Hello @lijenn @staceypark @lzim 
I set up the quick_code URLs for these VAPOR videos in Rebrandly. 

Therefore, **the names above will work for the pre/post emails.**
I'm closing the issue. Thanks! 🍔
