### ISSUE TITLE
wk4 feb_epic story 1: Reactivate REDCap Account (Anthony) by 2/24

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1730]
Please email REDCap to re-activate your RedCap account so I can give you access to the MTL surveys.
Reminder: Your REDCap username is your VHA alias/ID.

1. Go to: https://vhacdwweb05.vha.med.va.gov/index.php?action=myprojects (VA intranet)
and click on the red "Ask for Help" header at the top left of the page and check the "Re-activate my account" box.

OR

2. If you received an email from REDCap saying your account was suspended, you can just email them back to ask them to re-activate the account.

**Comment by lijenn** [comment]
FYI Anthony, saw your account got reactivated, you should see R01 MTL Red and Blue's Baseline and Follow up surveys in your RedCap account shortly. Thanks!

**Comment by anthonycpichardo** [comment]
Thanks Jenn!
