### ISSUE TITLE
june_epic Story 4: PROD QA - MTL Manual 

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1735]
Lindsey to review the MTL Manual after Jane reviews before the 3/2 Facilitate meeting.

**Comment by erinash** [comment]
@lijenn @staceypark 

@lzim said you confirmed that y'all are using Fedex for printing.
She wanted me to ask whether I should set up an account under her name.
Or, whether it will all be handled directly through ReqLogic.

**Comment by lijenn** [comment]
@erinash @lzim @staceypark 
I clarified with PAVIR that PAVIR's FedEx account only covers shipping.

Since our workflow would be to have the MTL co-facilitators fill out a form with their addresses and have the MTL guides printed and shipped to them, **I believe it would be better for us to have our own account to track both printing and shipping and then have PAVIR help cover the costs.**

@erinash Do you know how FedEx would invoice the printing and shipping costs? 
Do they require a credit card at the time of printing/shipping?

I ask since there's 2 ways PAVIR could help us cover the fees:
1. PAVIR pays FedEx directly: We would need an invoice and have it billed to PAVIR.
2. PAVIR reimburses us for the costs: Invoice would be billed to Lindsey and I would put in a check request to have the fees reimbursed to her.

**Comment by hnorthcraft** [comment]
#adjudicate_memo adding operations label
