### ISSUE TITLE
WK1 mar_epic Data UI : ensure that "Create Team Data" files have lower case file names 

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1736]
Edit the Create Team Data Folder drop down to ensure that all modules use lowercase file names

**Comment by anazariz** [comment]
@lzim @anthonycpichardo 
**Turn off excel file name capitalization:**

1. Display the Excel Options dialog box. 
2. At the left side of the dialog box click Proofing.
3. Click AutoCorrect Options. ...
4. Clear the Correct TWo INitial CApitals check box.
5. Click OK.
