### ISSUE TITLE
Green Sliders for CC, MM, and AGG - Using BC vs. Populating Values

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#174]
Throughout our four models - CC, MM, PSY, and AGG - we don't use "BC" for Green Variables but rather populate the sliders with a starting value.  Unlike the Red Variables whose values can be checked at the Team Data Table, there is no way for the learner to know what value "BC" means for Green Variables.  This issue occurs in the following places: 

CC - Referral Rate
MM - Referral Rate
AGG - Appropriate Service Proportions from Supply* and Intake Evaluation Rate
*This has a "BC" button that shows the values. I think it is confusing however that the rule for Green Variables is not consistent across the board.

## CC
![screen shot 2018-09-05 at 2 28 17 pm](https://user-images.githubusercontent.com/31089501/45160434-0cfb7780-b1af-11e8-9304-adcc792cf5fa.png)

## MM
![screen shot 2018-09-06 at 4 00 53 pm](https://user-images.githubusercontent.com/31089501/45185024-659e3500-b1ee-11e8-9fac-c871d29cf6e7.png)

## AGG
![screen shot 2018-09-06 at 3 52 15 pm](https://user-images.githubusercontent.com/31089501/45184641-27ecdc80-b1ed-11e8-973e-38246dffc03c.png)

**Comment by jamesmrollins** [comment]
@lzim @TomRust 
Not sure what we do about this one.  Give every one of these a BC button?  Perhaps we get away from the Team Data Table, and just give all the sliders a BC button?  In any case, we may have to see if we can fit it into 1.7 release.

**Comment by staceypark** [comment]
@lzim @TomRust @branscombj @dlkibbe @dlounsbu 
We decided to add a "bc" in all of the green experiment sliders (next to the "i") like in Agg: "Appropriate Service Proportions from Supply"

**Comment by dlkibbe** [comment]
That makes sense; the consistency will help the user. Thanks @staceypark
