### ISSUE TITLE
wk1 + mar_epic Story 5: Viability of leveraging 365 Groups for a one-time provisioning of 365 users

### ISSUE THREAD

**Issue by anazariz** [lzim/teampsd#1741]
**365 Groups:** 

Can we leverage 365 Groups to provision our users of 365 Dynamics, SharePoint, PBI and Teams only once. Meaning, these users should be able to use these resources without a need for re-provisioning per each software tool/platform.

**Comment by anazariz** [comment]
**Background:**

### Office 365 Groups:

https://www.youtube.com/watch?v=gg9LPzzeVrw

**How to create Microsoft 365 from Outlook**

In outlook help type "great group" 

### How does SharePoint 365 take advantage of Office 365 Groups
  
https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-connect-to-office365-group

- Being able to connect a Microsoft 365 group to an existing SharePoint site is important if you want to modernize that site.
- When you connect your site to a new Microsoft 365 group, a number of things happen:
1. A new Microsoft 365 group is created, and that group is connected to your site collection
2. A new modern home page is created on your site and set as the site's home page
3. The group's Owners are now the site collection administrators
4. The group's Owners are added to your site's Owners group
5. The group's Members are added to your site's Members group

### Connect a Microsoft 365 group using the SharePoint user interface

1. On the SharePoint Home page's navigation bar select "Settings" (gear icon) in the 
2. Then select the Connect to new Microsoft 365 group option, which launches a wizard that walks you through the group-connection process

![image](https://user-images.githubusercontent.com/39805164/108898815-88924e80-75cc-11eb-891c-f1f39b8eff20.png)

### How to change a SharePoint Classic to Modern 

PTSD_OMHO SharePoint was ported to the 365 platform as a Classic SharePoint site. This video explains how to change it to a Modern site.

https://www.youtube.com/watch?v=HvsxmCaO5GM

**Comment by hnorthcraft** [comment]
#adjudicate_memo assigning 1 sp to reflect efforts (documenting and research)
