### ISSUE TITLE
wk2 apr_epic story_6: Review Ash's CRM Prototype 

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1743]
- Review how the inbox and sent box rules are associated 
- how the to create rules for ensuring certain emails get assigned to their associated team subfolders

We will discuss decisions and findings at 3/3 support workgroups meeting

**Comment by anthonycpichardo** [comment]
This was not discussed during yesterdays support_wg meeting.

Should we bring it up during HQ?

@staceypark @lijenn @anazariz

**Comment by anazariz** [comment]
@lzim @staceypark @lijenn 

Closing this task.
