### ISSUE TITLE
story_7: Automate tt Reports Empowers all Users

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#1745]
**1. Add description:** 

- If we automated the tt reports for our study participants it would ease the time and eliminate the expertise required for Stacey, Anthony, Jenn, Facilitators, Teams & James to manually prepare those reports and send them out.   
- Due to need for integrated platform., this "Automate tt reports for all users" story needs to be coordinated with the  "Automated Monthly Data Updates on New Data Platform" (due to BISL platform migration) , the "One Time Registration across Platforms" story and the "Automate Team Data Upload to Sim UI" story.

**2. Click on the right:**  
i. **Pipelines** - prioritize in a TeamPSD (& Workgroup) pipeline  
ii. **Assignee** - assign to an individual team member producing work for the issue  
iii. **Label**- assign workgroup (lead) responsible for tracking the task  
iv. **Projects** - assign to domain-specific TeamPSD tracker (issues, features, document, manuscript, team)  
v. **Milestones** - select monthly sprint milestone within the workgroup   
vi. **Estimate** - Estimate task in complexity points   
vii. **Epics** - assign to team-wide epic and TeamPSD master plan project  
iix. **Releases** - assign to key team release grouped with other relevant issues  

**3. If you anticipate that your **issue card** or **bug card** will have **dependencies** these can be added once the issue has been submitted.   
ix. **Add dependencies** - assess for and add dependencies *blocking* & *blocked by* this issue

4.  Close outs

- [ ] Close dependencies
- [ ] Merge appropriate branches to master
- [ ] Verify that merges worked as intended

**Comment by hnorthcraft** [comment]
#adjudicate_memo Heather attempting best estimate at SP.
