### ISSUE TITLE
mar_epic_wk_2_story_7: Prepare MTL Blue and Red tt Report Wireframes

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#1747]
## Objectives:
- [x] Prepare an MTL Blue tt1, tt2 and tt3 wireframe.
- [x] Prepare an MTL Red tt1, tt2 and tt3 wireframe.

**Comment by jamesmrollins** [comment]
Hi @staceypark @lijenn @lzim.  Please find the proposed wireframe [here](https://lucid.app/lucidchart/invitations/accept/77054fa3-1102-42d3-b479-d7b82b751a0e). 

1. I am going to discuss with my DEV team tonight (Monday) and start an estimate.
2. **What is the data source for the P-chart?**

**Comment by jamesmrollins** [comment]
Another webpage built in Epicenter that has MTL Menu questionnaire. User navigates there by mlt.how/menu
Responses stored in Sim UI Data API
The facilitator would have a dashboard that summarizes the results in real time.
The participant needs a dashboard that summarizes results but calls out their individual scores.
Need a way to build the team dropdown in MTL Menu.

We need tt1-3 inclusive of the session 4 MTL Menu results.

**Comment by jamesmrollins** [comment]
Hi All,
Please indicate your agreement with the prototype design by checking the box below.  Feel free to reference and comment.  I am also working on the wireframe, of which, this is a part.  I did not include all questions contained in the questionnaire, as the design would be the same from dropdown to dropdown. Thank you,  James

- [ ] @lzim
- [ ] @staceypark
- [ ] @lijenn
- [ ] @branscombj
- [ ] @dkngenda
- [ ] @dlounsbu 

Below is a prototype Epicenter web page questionnaire for the mtl.how/menu 

![image](https://user-images.githubusercontent.com/30132017/110055732-5bebde80-7d12-11eb-8e47-bdd02069059e.png)

**Comment by staceypark** [comment]
@jamesmrollins I'm checking off the above to confirm that I've completed my review.
I've added my comments in **pink** sticky notes on the Lucid Chart document directly next to the point in the wireframe that it is relevant to: https://lucid.app/lucidchart/44590f55-08cb-4fe7-a3b4-19cd1e5b3cf8/edit?page=DLisWQauxZEYe#

**Comment by jamesmrollins** [comment]
This wireframe will be reviewed by the Sim UI Workgroup meeting on Wednesday.

**Comment by branscombj** [comment]
> @jamesmrollins I'm checking off the box in your comment above to confirm that I've completed my review.
> I've added my comments and questions for clarification in **pink** sticky notes on the Lucid Chart document directly next to the point in the wireframe that it is relevant to: https://lucid.app/lucidchart/44590f55-08cb-4fe7-a3b4-19cd1e5b3cf8/edit?page=DLisWQauxZEYe#

I don't think I have access to the wireframe. However, I love the prototype design for the MTL Menu above. Very clean and stylistically/navigationally in line with our simUI. It will be nice for folks to have seen this look once before they log in to the sim. The bigger design and programming task, I think, comes in the View Results (and export/stitch) to meet the above requirements. But I know you're up to it, @jamesmrollins 🦸‍♂️

**Comment by jamesmrollins** [comment]
### Decision: 
#1747

- NIH Red Teams do not need the MTL Menu, but do need a tt_report.
- With the first tt1 report due wk4_apr (2 mos after 2/24 or first NIH red team).
- For MTL Blue teams we do need to train facilitators in the new workflow.

### Schedule
testing wk3_apr
Menu in prod w4_apr
document wk1_may
training wk2 may

**The first MTL Blue session 4 MTL Menu 5/11.**

**Comment by jamesmrollins** [comment]
Hi @lijenn @lzim @staceypark .  The updated tt Report wireframe is available [here](https://lucid.app/lucidchart/invitations/accept/a7f2217c-9c5b-40f8-9e0b-79c5c2047437).  Thanks, James

**Comment by jamesmrollins** [comment]
Decision:  
The wireframe is approved and can be moved to development.
