### ISSUE TITLE
"Measured vs. Actual Time" in CC

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#175]
The "i" information for "Measured vs. Actual Time" in Care Coordination is incorret. The current definition is for Wait Time.

![screen shot 2018-09-05 at 3 06 19 pm](https://user-images.githubusercontent.com/31089501/45160592-84310b80-b1af-11e8-9174-79536ae553c6.png)

**Comment by jamesmrollins** [comment]
Please verify the following language and I will update model-information-popup file.

"This represents the relative change in time available for other Care Coordination (CC) or CC-related tasks consumed by overbooking patient visits. We assume that these "extra" appointments come at the expense of "other CC related tasks," such as , team coordination, patient reminder calls, chart review and other appointment prep, etc. It is constrained from going to zero, even if official appointment supply is zero."

**Comment by staceypark** [comment]
@jamesmrollins we discussed and agreed that the above language is the correct version for "Measured vs. Actual Time" in CC.  Just checked the sim and I see that it's changed.  Thanks!! :smile:
