### ISSUE TITLE
Add FindTime and Signature in MTL.Help Inbox instructions in MTL Technical Manual

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1750]
Add chapter for FindTime and add signature to Facilitators and all users of the MTL.Help inbox in MTL Technical Manual.

**Comment by lijenn** [comment]
From HQ WG 4/22:

Icebox until we see how this is incorporated in the CRM.

**Comment by lzim** [comment]
#adjudicate_memo
Not necessary.
