### ISSUE TITLE
wk2_may_epic_story_7:  Update MTL Facilitator and Tech Documentation

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#1754]
### Documentation

- [ ] Update Team PSD SOP.
- [x] Review/update Blue session 4, 8 and 12 See and Say guides.

**Comment by jamesmrollins** [comment]
As per discussion at 4/14 Sim UI meeting.

**Inventory Documentation and see if there is an impact to a see or say guide.**  Provide update as needed.

- MTL Facilitator and Technical Manual
- Documentation Tracker, Team "How To " Column.
- Take a look at mlt.how/documents and see if there are the right amount of team technical documents necessary to support the Sim UI. 
- There is a document tracker workflow map in Lucid Chart.  Also in Team PSD Manual.

**Comment by lijenn** [comment]
@jamesmrollins  Please help make the following changes to the buttons in the Facilitator Dashboard (below is Test) in addition to updating the TT report icon:

- [ ] Should say "Team Setup" not "Team Set-up".
![image](https://user-images.githubusercontent.com/59668647/117741194-b1cb7f80-b1b6-11eb-9b51-ce29877b0578.png)

For the following below:
- [ ] "Select Module" not "Select Model"
- [ ] "Select Team" capitalized.
- [ ] "Select first 3 experiments by date" (not capitalized "E" in experiments.
![image](https://user-images.githubusercontent.com/59668647/117741798-176c3b80-b1b8-11eb-8922-b873976d10ca.png)

There are a couple inconsistencies with the Selection Experiments and Select Reports boxes:
- [ ] Justify the top and/or bottom of the left and right boxes with one another.
- [ ] The left boxes have an outline, the right box should have an outline.
![image](https://user-images.githubusercontent.com/59668647/117741734-f0156e80-b1b7-11eb-83ad-f3154b6bd2a8.png)
![image](https://user-images.githubusercontent.com/59668647/117741493-7ed5bb80-b1b7-11eb-9d9b-339a648f2ea4.png)

**Comment by lijenn** [comment]
@jamesmrollins Ah, yes! Sorry! I thought I posted these in the QA card, but I clearly did not....thank you for catching that :)
