### ISSUE TITLE
story_8: Automate Team Data Upload to Sim UI Eliminates Admin Backend

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#1755]
**1. Add description:** 
Automate team data transfers between the Data and Sim UI's.  When the user creates a Team Data file, a Restful API transports the file to the appropriate Epicenter directory and automatically updates the drop down menu in the team's Sim UI Homepage.

 
**2. Click on the right:**  
i. **Pipelines** - prioritize in a TeamPSD (& Workgroup) pipeline  
ii. **Assignee** - assign to an individual team member producing work for the issue  
iii. **Label**- assign workgroup (lead) responsible for tracking the task  
iv. **Projects** - assign to domain-specific TeamPSD tracker (issues, features, document, manuscript, team)  
v. **Milestones** - select monthly sprint milestone within the workgroup   
vi. **Estimate** - Estimate task in complexity points   
vii. **Epics** - assign to team-wide epic and TeamPSD master plan project  
iix. **Releases** - assign to key team release grouped with other relevant issues  

**3. If you anticipate that your **issue card** or **bug card** will have **dependencies** these can be added once the issue has been submitted.   
ix. **Add dependencies** - assess for and add dependencies *blocking* & *blocked by* this issue

4.  Clean Up

- [ ] Merge respective code branches to master.
- [ ] Merge respective documentation branches to master.
- [ ] Close out blocking issues.

**Comment by lzim** [comment]
#adjudicate_memo
There is not an appetite for this - Not needed.
The Power BI export, and Sim UI upload is working fine.
Not planned.
