### ISSUE TITLE
may_epic_story_8: Update MTL Admin Dashboard to Remove Error Prone Processes

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#1757]
### Check off requirements to verify progress through feature_tracker.
- [x] 1. **DEFINE in work_breakdown**
  - [x] a. **what & why** - **written definitions of requirements** in a **numbered checklist** on the **master_feature_card.**
  - [x] b. **date & who** -  **Verified** requirement definitions an **existing team meeting.**

NOTE:  This story absorbs #1039 mtl.how/sim folder management for "MTL all"
  
  Task Cards:
  #1821 Workflow diagram
---
- [ ] 2. **DESIGN** in **operations_to_do** and **research_to_do**
  - [ ] a. **what & why** - **_MVP_ of design** of requirements in a **algorithm map, wireframes or design** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** design **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #1758 Wireframe
---
- [ ] 3. **DEVELOP** in **under_development** - "frozen"
#1759 Dev
#1822 Test

**Comment by hnorthcraft** [comment]
#adjudicate_memo efforts tracked on other cards, adding dup label.
