### ISSUE TITLE
wk_4_apr_epic_story_8: Code Sim UI Administration Page

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#1759]
### Objectives:

- [ ] Update code for Home Page IAW wireframe instructions
- [ ] Test actions to ensure the team data update process results in the update of the team's team data drop down menu.

**Comment by jamesmrollins** [comment]
@lzim @staceypark @lijenn  we are targeting having this to test by 19 April. I have set up #1860 QA Test card for @lijenn to help with testing.  I will develop testing instructions on that card the week of 12 April.

**Comment by jamesmrollins** [comment]
From Workgroups:
1.  James will split this card to close completed work (Team set up, admin screen structures, data api update).
2. The split will contain the team data, p-chart update process and the Team Update web page structure (as needed).  
3. @staceypark and @lijenn  , should we discuss Team Update web page structure at the upcoming Sim UI Meeting??

**Comment by jamesmrollins** [comment]
@staceypark and @lijenn Update:

I delayed any more work on the Admin workflows until we come to consensus about who is using it and how it will be displayed.  We should discuss this at the 4/28 SIM UI meeting.  The questions I have are:
  - Are Facilitators going to set up teams?  If so, do we want to move the Team Setup icon to the facilitator dashboard?  We could change the logo to make it unique.
  - Do we want the set up to be viewed as a single page, or as pop ups as in the current version?
  - Are facilitators going to update team data and p-charts?
  - Are facilitators going to set up tt reports?

**Comment by staceypark** [comment]
Decisions from 4/28 sim_ui workgroup:
- Team Admin (previously Sim UI Admin/Team Setup) & tt report buttons will be moved to Facilitator Dashboard and available in the facilitator_login to the sim
- Team Admin = gear logo + (text) Team Admin 
- tt report = tt logo + (text) Admin 
- End users will NOT get an email when they are added to the sim. Teams have to be uploaded at before start of session 3 due to post session 03 mtl menu homework. This which is too early for them to be introduced to/confused by 

@lijenn @staceypark for documentation fyi: all admins and support need to be added to every team as "facilitators" to be able to login and support that group at any time.

**Comment by jamesmrollins** [comment]
## DEV Completed with This Card:

1.  The general structure of the wireframe and navigation between all admin screens in the Sim UI. 
2.  The team set up dialogue structure for manual input.
- Add team
- Edit team 
3.  The interface between team setup and Epicenter and the tt report.
4.  Automatic email function (though function was suspended because timing was not close enough to participants actual use of the simulation.  HQ decided 4/28 to handle notifications using CRM).
5.  Single-sign on.  No matter where an admin or facilitator signs in, based on permissions, can navigate anywhere in the Sim UI.
6.  Removed the need for Dynamic Data folder in Epicenter.  Standardized file upload features across MTL DEMO, associated MTL Demo Tutor, Tips and More Info screens and Team PSD admin screens.
7.  Provided a Course Code management feature in MTL Demo.
8.  Made page logos brand consistent with purpose across all pages.

## Work Moved to May EPIC

1.  Automatic _team and _ind group creation.
2. Reorganization of Top Navigation bar and Facilitator Dashboard to move the TT Admin and Team Setup functions to the Facilitator Dashboard and allow access by Facilitators.
3. Addition of the "Clinical Role" field to Team Setup and Team Roster functions.
4. Addition of sort functions on columns.
5. Team data management function, to include drag-and-drop functionality for a data template to create teams from a CRM export.

**NOTE: The wireframes located in Lucid Charts have been updated to reflect these changes**
