### ISSUE TITLE
"Appointments For Existing Patients" MM & PSY

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#176]
"Appointments for existing patients" in MM and PSY does not have the "i" information.
In PSY, it is still labeled the legacy "Appointments used by existing patients." We standardized to "Appointments for existing patients" across all models. 

![screen shot 2018-09-05 at 3 28 35 pm](https://user-images.githubusercontent.com/31089501/45160767-dd00a400-b1af-11e8-9db8-873e4e896ff5.png)
![screen shot 2018-09-05 at 3 31 34 pm](https://user-images.githubusercontent.com/31089501/45160768-dd00a400-b1af-11e8-954c-3194cfe36115.png)

**Comment by jamesmrollins** [comment]
@staceypark @lzim @TomRust @branscombj @dlkibbe 

This is a label only and is not associated with an active variable in the SIM/UI.  It never has had an "i" icon.  However, with that said, we can pull the variable up from the pool of un-associated variables in the crosswalk table, copy the "i" information from the model and update.

**Comment by jamesmrollins** [comment]
Bug reported

**Comment by jamesmrollins** [comment]
Bug is corrected.

**Comment by staceypark** [comment]
@jamesmrollins  Thanks for getting the labels fixed and the "i" information added.
One last fix on this issue, in the PSY model, the label within the "i" information pop out text still needs to be changed to "Appointments For Existing Patients" 

![image](https://user-images.githubusercontent.com/31089501/45735243-018b5180-bb9c-11e8-89b2-10b28e3c468e.png)

**Comment by jamesmrollins** [comment]
@staceypark 
This is fixed, but we need to load an updated model-popup-information file. I will do that tomorrow.
James

**Comment by jamesmrollins** [comment]
Fixed
