### ISSUE TITLE
Saved Runs Missing

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#177]
Group: MTL Facilitate Pilot Team
World: 001
Model: Aggregate
Saved experiment shows up in the Experiment Maintenance Tile, but is not showing up in the Experiments Tile nor in the Expanded Outputs Tile in the Alternative Experiment selection section.

**Comment by jamesmrollins** [comment]
Based on what I can see, you have saved the current run, and it is listed in the experiment maintenance tile.  However, the run doesn't become available for reload until after the model is reset.  It would be kind of comparing the run against itself.

**Comment by jamesmrollins** [comment]
@staceypark @lzim @TomRust @branscombj @dlkibbe 
The "Save" function in Expanded Outputs is now enabled.  If the user desires, a save can be performed with out a model "Run."

**Comment by staceypark** [comment]
Great! Thanks @jamesmrollins
