### ISSUE TITLE
wk3 apr_epic: Review of MTL activities to be costed

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1773]
Jenn and Stacey will post the excel sheet in the Files tab in the quant_workgroup channel and notify Libby to review the costing of the MTL activies based off of the decisions from our feb_epic 3rd Thurs. quant_operations workgroup meeting.

Stacey and Jenn to implement decisions tracked in this card: #1709

We will review this altogether at 3/18 3rd Thurs quant_operations meeting tracked in #1775

**Comment by claradismuke** [comment]
Jen, have the excel sheets been posted in quant_workgroup? When I go to the folders I do not yet see a quant_workgroup only a qual_workgroup. Thanks Libby

**Comment by lijenn** [comment]
Hi Libby! No the excel sheet is not posted yet, I will ping you once it's posted :)
It will be posted here in VA Teams, let me know if you do not see it?
![image](https://user-images.githubusercontent.com/59668647/109826897-1d5e0300-7bf0-11eb-91d2-b9bcc9e330e6.png)

**Comment by claradismuke** [comment]
Jenn, now I understand the files are in Microsoft teams. I do see it! Thanks! Libby

**Comment by lijenn** [comment]
closing this old card as new cards were made by stacey based on the action items from today's meeting.

**Comment by hnorthcraft** [comment]
#adjudicate_memo adding VS labels
