### ISSUE TITLE
BACKLOG: Review & categorize MTL activities in relation to ERIC strategies

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1774]
Lindsey to review the costing of MTL activities that Stacey and Jenn are implementing from #1709 and categorize the activities according to ERIC strategies. 

Stacey and Jenn will upload the costing excel sheet in the Files tab in quant_workgroup channel.
We will review all together at the mar_epic 3rd Thursday quant_operations meeting, see #1775

**Comment by lzim** [comment]
@lijenn 
@staceypark 

Can we briefly huddle about this after **team_temp?**
I'm hoping that you two can divvy two priorities to:
- [ ] Need the Excel for the crosswalk of the ERIC & MTL Strategies for today's **11AM quant_operations** with Libby?
- Was that posted?
- We'll likely want to touch base with Libby about this work to see if we can get her going on _MTL_ **development costs**

- [ ] **wrap up all human subjects documents edits for review by PAVIR** - TOP TEAM PRIORITY FOR THE DAY (with Aim 1b)
- If this means we need to talk about **Project 2** with @dkngenda  we need to do so this morning @staceypark 
I meet with an _MTL_ team today if you check the **mtl.help calendar**

**Comment by lzim** [comment]
@staceypark Let's track this as a dependency of our cost manuscript, which doesn't have a card on the manuscript tracker yet. But, needs one.

**Comment by lzim** [comment]
Prioritizing the _participatory synthesis story_
And getting the datafeed from GitHub/ZenHub working.
