### ISSUE TITLE
wk3 may_epic: Review Costing of MTL activities at 5/20 quant costing meeting

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1775]
Review the costing excel sheet that Stacey and Jenn added to the Files tab in the quant_workgroup channel and ensure that it has been reviewed by both @claradismuke @lzim before we reconvene on 3/18 for the quant_operations workgroup meeting.

**Comment by staceypark** [comment]
@staceypark to send Libby the history of MOUs, contracts, and IPAs used to develop MTL
