### ISSUE TITLE
Y-Axis Error in Results Dashboard Chart in AGG

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#178]
Group: MTL Facilitate Pilot Team
World: World 001
Model: Agg Model

Y-axis did not scale on the chart for "Group - Actual Return Visit Interval"

![screen shot 2018-09-06 at 3 10 54 pm](https://user-images.githubusercontent.com/31089501/45184352-5322fc00-b1ec-11e8-91c4-793df51e8532.png)

**Comment by jamesmrollins** [comment]
@staceypark @lzim @TomRust 

I need the rest of the information so I can replicate.  Please provide experimental values or export the experimental run into a xlsx using the export function.

**Comment by staceypark** [comment]
These are the variables we changed.
![agg_1](https://user-images.githubusercontent.com/31089501/45230833-c762ab80-b28f-11e8-906c-7f01a4f89863.PNG)
![agg_2](https://user-images.githubusercontent.com/31089501/45230834-c762ab80-b28f-11e8-882f-3e6bfb101ec4.PNG)

**Comment by jamesmrollins** [comment]
Bug Reported

**Comment by jamesmrollins** [comment]
@TomRust @staceypark 
Stacey - Tom,
If you guys saved this experiment, can you send me the export file for the experiment?  We are not able to recreate the issue with experiment values alone.  We need to see what was generated as a result of the run.  

Thanks,
James

**Comment by staceypark** [comment]
@jamesmrollins posted this to sim_ui_workgroup > mtl_1.6 > bug_reports
https://github.com/lzim/teampsd/blob/master/sim_ui_workgroup/mtl_1.6/bug_reports/agg_bug_exp_values_2018_09_07.csv

**Comment by jamesmrollins** [comment]
Hi @TomRust 
Can the model values be rounded to three significant digits from within Vensim?  The chart function on the platform is reading the actual values returned by the model.  So for the example above, that looks to be oscillating, the real values returned by the model when we remove our three significant digits filter are as follows:

![chart oscillation problem](https://user-images.githubusercontent.com/30132017/45404017-1868fb80-b612-11e8-85e4-c4dfcb2d0b6e.png)

**Comment by jamesmrollins** [comment]
@staceypark @lzim @TomRust @branscombj @dlkibbe 

We have accomplished rounding to three significant digits prior to chart binding.  Keep in mind that model saves and export will also round to three significant digits.

**Comment by lzim** [comment]
Thanks @jamesmrollins!
