### ISSUE TITLE
wk? apr_epic story_1: r21_sp_nejm authorship

### ISSUE THREAD

**Issue by dkngenda** [lzim/teampsd#1781]
### Authorship​
​
- [ ] Shinyapp used to determine 1) **eligible** and 2) **responsible** authors​
​
- [ ] All authors pinged (@)​
​
- [ ] Authorship agreement signed​
​
- [ ] Workflow determined during **#manuscriptmonday** ​
​

**Comment by lzim** [comment]
#adjudicate_memo 
Card created, but this manuscript did not more forward.
