### ISSUE TITLE
Team Data Table in AGG

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#179]
In the Agg Model Team Data Table, all of the Appt Supply variables should have the "75th percentile" label instead of "median".

This is incorrect in the master crosswalk right now.

![screen shot 2018-09-06 at 11 47 19 am](https://user-images.githubusercontent.com/31089501/45184449-8cf40280-b1ec-11e8-99b3-3b94c018ba63.png)

**Comment by jamesmrollins** [comment]
@lzim @TomRust @staceypark @holbrooa @branscombj @dlkibbe 

When did we change that?

From Andrew:
![image](https://user-images.githubusercontent.com/30132017/45186240-aa6f9f00-b1e1-11e8-8387-cca840cc7611.png)

From Master Crosswalk:
![image](https://user-images.githubusercontent.com/30132017/45186299-d25f0280-b1e1-11e8-849c-33a8d799e551.png)

**Comment by lzim** [comment]
Hi @jamesmrollins "When did we change that?" 

I'm having the same thought in the reverse, when did it become median?
You'd think with all the MTL 1.6 standardization (and the documentation you've screen-grabbed), that it would have seemed like a surprise to see median there.

But...I'll get to the bottom of this issue next week. Can't pull on this thread now. 

Thanks!

@lzim @TomRust @staceypark @holbrooa @branscombj @dlkibbe

**Comment by jamesmrollins** [comment]
@lzim 
Actually, I thought I remembered us identifying this as the only exception.  In any case, if we are certain this is 75th Percentile, I will get after changing it.

**Comment by staceypark** [comment]
@lzim @dlkibbe @branscombj @TomRust @dlounsbu 
Tom reminded us that the reason for using Median in AGG is since we're looking across all services, the assumption that 75th percentile is the most accurate one does not scale well across all services. If we know that every single one is an overestimate and sum that across 7 services, we would be inflating the supply.

Also, to note for facilitation resources and guide, fidelity checklist - We want to include this rationale for using Median over 75th percentile in AGG for Appt Supply while using 75th percentile in PSY for Appt Supply

**Comment by dlkibbe** [comment]
That makes sense especially considering that "inflating supply" would potentially be a big problem
