### ISSUE TITLE
wk? april_epic story_1: r01_protocol_impsci - authorship

### ISSUE THREAD

**Issue by dkngenda** [lzim/teampsd#1794]
2. Authorship

- [ ]  Shinyapp used to determine 1) eligible and 2) responsible authors
- [ ]  All authors pinged (@)
- [ ]  Authorship agreement signed
- [ ]  Workflow determined during #manuscriptmonday

**Comment by lzim** [comment]
#adjudicate_memo
Covered by card [#764](https://github.com/lzim/research/issues/764)
