### ISSUE TITLE
mar_epic wk3 BUG: Memory Error for 570 Facility File

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1802]
New errror message when a provider tried to open the Facility file below:
![image](https://user-images.githubusercontent.com/59668647/110670256-0dab6500-8182-11eb-9ce9-797d7e0514cc.png)
Provider was still able to drive the Facility file through the Read Only ver. but we need to identify why this message shows up.

**Comment by anthonycpichardo** [comment]
Acknowledging. 

This isn't a bug that we can handle as their machine simply ran out of memory.

We can provide updated documentation for our users that there are high memory constraints from the application.

Where would we want this documentation.

@lzim  @staceypark  @anazariz @lijenn

**Comment by anazariz** [comment]
@lzim @staceypark @lijenn @anthonycpichardo 
I was able to open the file without any issues. The need to close some of their other applications and retry.

**Comment by lijenn** [comment]
@anthony Add message onto the mtl.how/data visn's page:
"Working with 2 years of data places demand on computer memory. To free memory, close other open applications (e.g. Outlook)."

@staceypark @lijenn #1478 Add screenshot into the MTL Technical Manual in Admin Chapter
![image](https://user-images.githubusercontent.com/59668647/110868372-55fb7d80-827d-11eb-9d15-69ff5efd3c55.png)

**Comment by anthonycpichardo** [comment]
Data UI has been updated with the above message.

@staceypark  @lijenn 

Can you update when the technical manual has been updated?

**Comment by lijenn** [comment]
Updated message has been made and is live on mtl.how/data made by Jenn.
