### ISSUE TITLE
wk2 - apr_epic - Bug: Run Time Error when Team Data Table is generated/Team Data Table file does not Automatically save into the team_data_folder

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1806]
1. Generated a Team Data Table. The output of the table looks fine, but this Run Time Error occurs:
![image](https://user-images.githubusercontent.com/59668647/110726838-fc3c7a00-81ce-11eb-8cf9-fe13a40f866e.png)
Debug:

![image](https://user-images.githubusercontent.com/59668647/110838759-b1b31000-8257-11eb-9010-5bdd3f0c0a6e.png)

2. I also noticed the generated Team Data Table file does not automatically save into the team's team_data_folder on mtl.how/data (not sure if this issue is related to the run time error).

Assigning @anthonycpichardo for now due to Ash being OOO.

**Comment by lijenn** [comment]
Hi Anthony, yup that should correct and confirmed with @staceypark

**Comment by anthonycpichardo** [comment]
Okay, I can make that update.

@staceypark  @lzim Approval to update the master_data_ui after 2pm? The last meeting based on the mtl_help calendar ends at 2.

The propagation will take about 15 minutes.

**Comment by lijenn** [comment]
@anthonycpichardo Wait till after tour/4:30pm Pacific to propagate.

**Comment by lijenn** [comment]
Hi @anthonycpichardo and @anazariz, re-opening the issue since I got the same error message and debug in the top post (except instead saying "data_sim_ui" it says "team_data_table" based on the decisions in the previous comment), it is still leading to the issue that the team data table that is generated from the data ui does not automatically get saved into the team's team data table folder. 

Could there be additional changes needed to fix the code as it doesn't seem like it's detecting the team's data table folder?

**Comment by anthonycpichardo** [comment]
Hey Jenn, just checking are you running these workbooks from the teampsd clinics folder or are you opening it from the mtl.how/data site?

**Comment by lijenn** [comment]
Yup from mtl.how/data site. See 570 harm's 3/18 data ui file, the data ui definitely registers that the team data table was created, but after the team table is generated the same Run-time error and debug shows up, even after the code edit to team_data_table. 

Question about the code, is it only looking for "team_data_table" in the folder name and it ignores anything that doesn't match it 100%? Cause the folder name is technically "stationnumber_teamname_team_data_table".

Also, the team data table file doesn't seem to take in the automatic file naming convention from the code, this issue could be resolved/related to how the file is saved though.

**Comment by anthonycpichardo** [comment]
I'll do some additional analysis on Monday.

Thanks for the update!

**Comment by anthonycpichardo** [comment]
@anazariz  This is ready to test.

Modified the method to find the parent folder slightly to avoid running into errors. 

It is now able to appropriately find the parent folder if it exists.

**Comment by anthonycpichardo** [comment]
This is propagated and ready to close @lijenn with your approval

**Comment by staceypark** [comment]
@anazariz @lijenn I think this is ready to close?

**Comment by jamesmrollins** [comment]
This bug is resolved.  See #1867.  Close.
