### ISSUE TITLE
Bug: 570 Harm - Outdated Browser Message Still Appears on mtl.how/data

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1807]
We had a provider from 570 Harm drive the meeting and I noticed that this outdated warning still showed up for him. I recall them either being on Edge or Chrome for this:
![image](https://user-images.githubusercontent.com/59668647/110848825-5ab33800-8263-11eb-8b43-5923ed876556.png)

Could there be a possibility that this removal wasn't propagated/edited nationally?

**Comment by anthonycpichardo** [comment]
That's really strange.

I just verified that the published version does not contain that message which would be true for everyone nationally.

**Comment by lijenn** [comment]
Discussed at hq_workgroup 3/11:
Do not close, but bottom of priority list for now.
