### ISSUE TITLE
wk3 mar_epic tt report for NIH Red

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1809]
nih red teams get 1 tt report after the end of their second session.
some teams got there TODAY and several will follow soon.

we need to:
- [x] decide the content of the report (I recommend their viz charts)
- [ ] create workflow for producing it
- [ ] send it to today's team asap

**Comment by lijenn** [comment]
Discussed at hq_workgroup 3/11:
@staceypark will create a feature request for @jamesmrollins to create a new wireframe for **MTL Red** sites.

**Comment by staceypark** [comment]
@lijenn @lzim @anthonycpichardo 
I found decisions we had made about MTL Red content on #1536.
I've added some quotes and questions from that on #1809.

**Comment by staceypark** [comment]
closing this one in lieu of #1747 and #1812
