### ISSUE TITLE
evaluation from R21

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#181]
[Zimmerman_R21_Appendix_FINAL_edit.pdf](https://github.com/lzim/teampsd/files/2358960/Zimmerman_R21_Appendix_FINAL_edit.pdf)

**Comment by dlounsbu** [comment]
1.	How would you rate the overall quality of today's webinar? 
1= poor, 2 = fair, 3=good, 4=very good, 5=excellent

2.	How relevant was the topic to your current work and interests? 
1=Not at all relevant, 2=Somewhat irrelevant, 3=Neither relevant nor irrelevant , 
4=Somewhat relevant, 5=Very relevant

3.	How easy was it for you to use your computer or device to participate in today's webinar? 
1=very difficult, 2=somewhat difficult, 3=neutral , 4=somewhat easy, 
5=very easy, no problems at all

4.	How well did today's webinar present an ecological perspective on the processes and goals of community intervention and exemplify the fundamental role of culture and context?
1= very poorly, 2 = somewhat poorly, 3 = adequately, 4 = somewhat well, 5 = very well

5.	Today's webinar had three learning objectives. Please rate the extent to which you agree with each of the following:
After today’s webinar, I understand the components of an ecological framework. (Objective 1) 
1= strongly disagree, 2 = disagree, 3 = neither agree nor disagree, 4 = agree, 5 = strongly agree
After today’s webinar, I understand how an ecological perspective differs from evidence-based practice. (Objective 2) 
1= strongly disagree, 2 = disagree, 3 = neither agree nor disagree, 4 = agree, 5 = strongly agree
After today’s webinar, I understand the development of community resources as the primary community intervention goal. (Objective 3) 
1= strongly disagree, 2 = disagree, 3 = neither agree nor disagree, 4 = agree, 5 = strongly agree

6.	Prior to today’s webinar, how would you rate your proficiency in applying an ecological perspective of community intervention and the fundamental role of culture and context?
1= no experience, 2 = novice, 3 = intermediate, 4 = advanced, 5 = expert

7.	After today’s webinar, to what extent did you gain new, useful knowledge about an ecological perspective of community intervention and the fundamental role of culture and context?
1 = not at all, 2 = a little bit, 3 = moderately, 4 = significantly, 5 = a great deal

8.	After today’s webinar, how confident are you in applying your new knowledge about an ecological perspective of community intervention and the fundamental role of culture and context?
1= very unsure, 2 = somewhat unsure, 3 = neither confident nor unsure, 
4 = somewhat confident, 5= very confident

**Comment by dlounsbu** [comment]
Benefits of Participation in MTL

For each of the following benefits, please indicate whether MTL will or will generate the following personal benefits:

a. Enhanced ability to address an important issue
[ ] Yes
[ ] No

b. Development of new skills
[ ] Yes
[ ] No

c. Heightened profile with my institution
[ ] Yes
[ ] No

d. Increased utilization of my expertise or services
[ ] Yes
[ ] No

e. Acquisition of useful knowledge about services, programs, or people in the
community
[ ] Yes
[ ] No

f. Enhanced ability to affect policy
[ ] Yes
[ ] No

g. Development of valuable relationships
[ ] Yes
[ ] No

h. Enhanced ability to meet the needs of my constituency or clients at the VA
[ ] Yes
[ ] No
