### ISSUE TITLE
wk1 may_epic Add measurement explanation to facilitator fidelity survey & restructure survey questions backend

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1811]
- [ ] Use qual definitions from coding of participatory codebook to add details in facilitator fidelity survey questions to ensure everyone is answering the questions in the same manner
- [ ] Checkout and restructure backend frame of data/question structure 
- [ ] Change co facilitator 1/2 to live lead and support (?) check say guides
- [ ] Make sure coplanning has partner & build

**Comment by staceypark** [comment]
- [ ] nih red will only have partner measures & va red will have partner & build measures

**Comment by anazariz** [comment]
@lzim, @staceypark and @lijenn propose to either meet today #MM or Qual meeting (next Wed) to discuss this issue.

**Comment by staceypark** [comment]
@lzim 
@lijenn and I also noticed we have HQ meeting after team time tomorrow. We could use that time to get this done as well.

**Comment by staceypark** [comment]
@staceypark  to add the images from lindsey's stanford slide deck to the beginning of the survey.
add color coding for facilitator/team (or use the words if cannot change colors).
