### ISSUE TITLE
Just When You Thought It Was Safe to Go Back in the Water: Ver 1.7 Concept

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#182]
@lzim @TomRust @holbrooa @staceypark @branscombj @dlkibbe 

Team PSD Warriors!

Some food for thought for the plane ride back.

![suicide prevention concept 1](https://user-images.githubusercontent.com/30132017/45195831-562ee400-b20e-11e8-9e1c-6ae8878cf8a0.png)

Cheers!
James

**Comment by dlkibbe** [comment]
@jamesmrollins I really like the text in the box - the white font on a blue background is easier to read; 508 compliance might also be enhanced.

**Comment by lzim** [comment]
I'm going to close this issue and open one that reflects all the decisions we made this week.
