### ISSUE TITLE
BUG: MTL Co-Facilitators Access/Permissions to Folders on mtl.how/data

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1827]
Issue: MTL Co-Facilitators seem to be losing access to their MTL team's folders on mtl.how/data.
They are able to see the tea, folders again when I add the co-facilitator to the team folder's user group list, but this shouldn't be needed since **all co-facilitators should have permissions that allow to see any folder on mtl.how/data.**

This issue didn't seem to come up until recently this or early last week as co-facilitators remember seeing team folders but then they suddenly weren't able to this week.

**Comment by anthonycpichardo** [comment]
@anthonycpichardo  will review Sharepoint permissioning and ensure that all facilitators continue to have access to all team folders.

**Comment by anthonycpichardo** [comment]
@lijenn  Who are the facilitators having permissions issues?

**Comment by staceypark** [comment]
3/31 support wkgps meeting:

@anthonycpichardo suggests that we reach out to Doug to start tracking down this issue.
relatedly: we had a clinician have issues with permissions that is now fixed, but we do not know why/how this was fixed. While this is great in the near term, we need to know how to fix this issue in the future if this happens again, so facilitators are not hanging without permissions to the data in the middle of a team meeting, or our frontline staff teams can't use the tools.

@anazariz has clarified that permissions are managed at the (active directory) systems level.

**Comment by anthonycpichardo** [comment]
Facilitators have the appropriate access and permissions to their folders.

Issue resolved. Confirmed via @lijenn
