### ISSUE TITLE
bug sim_ui: AGG completion rate charts do not load 

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1838]
![image](https://user-images.githubusercontent.com/31089501/112603318-129f2400-8dd2-11eb-9ae5-828093e1e293.png)

**Comment by jamesmrollins** [comment]
@staceypark is this session still active, or has it been saved?  Which group is this under?  I want to go in and take a look.  Thanks, James

**Comment by jamesmrollins** [comment]
Workgroup Leads discussed this bug and will come back to it after the wellness break.

**Comment by staceypark** [comment]
@jamesmrollins the group is 640ha_stc_2018_05_team.
It should be one of the saved experiments in that group

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire.  I was not able to create the error that was reported above by @staceypark.  However, the chart for Intake Completion Rate is not working properly (see below).  

![image](https://user-images.githubusercontent.com/30132017/113063367-0ddbc680-916a-11eb-8f3a-fe861e8ffc31.png)

**Comment by jamesmrollins** [comment]
There was a bug in the chart rendering function.  It is now corrected.
