### ISSUE TITLE
bug sim_ui AGG mode should be binary switch

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1839]
This switch should be binary, but right now I can move the slider to anything on the scale. Not even sure what it does if anything in between the two choices are selected. 
![image](https://user-images.githubusercontent.com/31089501/112616362-e048f300-8de0-11eb-9896-640a7381ec4e.png)

Separately, it seems to keep going to "Balanced" after I run an experiment or if queue up values from previous experiments using the Select Previous Experiment function, even if that experiment was with the switch toggled to "Service Proportions from Team Data". Not sure if this is a feature or bug.....

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire .  Please take a look above.  Currently, the slider moves dynamically between the two selections.  It should "snap" to one or the other when the user moves the slider.  Thanks, James

**Comment by jamesmrollins** [comment]
The issue was corrected by changing the increment on the slider to 100.  Since it is a dmnl variable, it is a percentage and was set up with a .1 increment.  Now it should toggle between the top of the scale (1 or 100%) and the bottom of the scale (0 or 0%).
