### ISSUE TITLE
wk3 apr_epic: Create Playlist for VAPOR videos

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#1841]
This seems like a back-burner thing but is it possible to organize the YouTube channel where the VAPOR videos are (and maybe this also applies to mtl Video?) so that they cycle through one after the other when you watch one - rather than being sent off to some unrelated video after you watch the clip? Maybe Playlists or something - I don't know - but I think it is possible.<br/><br/><br/><br/><br/>

**Comment by jamesmrollins** [comment]
@lijenn will move this to the feature kanban and complete next week.
