### ISSUE TITLE
Test Data UI Saving to Team Data Folder

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1848]
Test the functionality to save a team data table.

Code change in Module 1, search for my comment labeled AP 03/30/21 to see the change.

Expected behavior is that if the data table folder exists the team data table should get saved into that folder.

See #1806 for more details.

If testing is approved we can propagate this change for team use.

FYI @lijenn

**Comment by anazariz** [comment]
@anthonycpichardo, I completed the testing. The change looks good.
