### ISSUE TITLE
apr_epic quant workgroup folder cleanup

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1850]
@anthonycpichardo will work with @anazariz and @dkngenda to cleanup any old/outdated files from TeamPSD > quant_workgroup

Note: We have a convention of "archiving" old/outdated work for future reference and documentation rather than "deleting".

**Comment by anthonycpichardo** [comment]
Cleaned up any loose files/folders.

Left your work area alone @anazariz
