### ISSUE TITLE
WK1 + Bug: Facility "Secondary Stop Code" fix

### ISSUE THREAD

**Issue by anazariz** [lzim/teampsd#1854]
**1. Facility "Secondary Stop Code" fix:** 

The script **"splashSourceIncrementalUpdate.sql"**,which runs every month to update the 4 SQL Server tables used by the Facility.xlsb workbook to populate its tabs has an error. The script segment that updates the table on the dataDiag tab was doing a **"join"** on the **"secondary stop code"** instead of a **"left join"**. This could potentially drop location records that are used to create visits. In turn, the **splashSourceDiag** table (showing up in the workbook as **"dataDiag"**) could potentially end up with missing records. **Note that this issue does not exist on the Data UI side**. The discrepancy between the two scripts (Data UI and Facility) has been corrected. Testing is in Progress. April Propagation is pending testing completion.

**Comment by anazariz** [comment]
**Initial impact of the fix**

When **"Join"** was switched to a **"left join",** new records with a valid **"Primary Stop Code"** but null **"Secondary Stop Code"** were picked up. This was the correct behavior as not all records have a **"Secondary Stop Code"**. However ,the script crashed because for unknown reasons the Diag SQL Table did not allow nulls in the **"Secondary Stop Code"** (it allowed it in the "**Primary Stop Code"** field. I removed the field's ("not null") constraint and reran the update code successfully. However, the failure was an indication that there could have potentially been dropped records in previous runs. I am currently conducting tests to see:

1) The impact of the change in the current month
2) The impact on previous months

**Comment by anazariz** [comment]
**A/B Testing**

The 4 tables: splash.SplashSourceDiag, splash.SplashSourceEnc, splash.SplashSourceHF and splash.SplashSourceMeas were copied to   splash.SplashSourceDiag_AB, splash.SplashSourceEnc_AB, splash.SplashSourceHF_AB and splash.SplashSourceMeas_AB. The update was rerun against these 4 tables. The two sets will be compared to see if there is a delta. If there is a difference, data will have to be retrofixed.

**Comment by anazariz** [comment]
** Testing is complete **

Code was fixed. A/B testing showed that a data retrofix is not necessary. Proceeding to propagate.

**Comment by lijenn** [comment]
Ash has fixed this bug and updated/propagated the Facility file for March. 

Note from Ash's email on Mon. 4/5 7:28am that the propagation time has " become extremely complex, time consuming and unsustainable. There were numerous interruptions (the process would just stop) requiring a lot of handholding". 
Related to Power BI update: lzim/research#91
