### ISSUE TITLE
apr_epic wk1 Bug: Edit Splash page message for readability.

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#1855]
Please edit this message so that the second sentence starts on the second line, like this: 
"To free memory,

Doing so will improve readability and consistence of display in a variety of responsive web formats.

Thanks!

![image](https://user-images.githubusercontent.com/7454688/113456983-825d7200-93c3-11eb-94f9-b4c27f9db67e.png)

**Comment by lzim** [comment]
Looking in both **qual_workgroup** and **facilitate_workgroup** as assignees, since many teams are having team meetings next week.

Thanks! @anazariz and @lijenn

**Comment by lijenn** [comment]
@lzim  Edited! Could you please check the homepage to see if my edit was made globally?
![image](https://user-images.githubusercontent.com/59668647/113457564-fb10fe00-93c4-11eb-9413-df76589d2fa6.png)

**Comment by anazariz** [comment]
@staceypark @lijenn 

This issue has been resolved and can be closed.
