### ISSUE TITLE
wk3 apr_epic: Workgroup meetings in MTL.Help and Info Calendar

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1856]
@lijenn  to show @anazariz @dkngenda how to transfer the meetings Anthony cancelled into the MTL Help and MTL Info calendar.

Each of the meeting series owners needs to remove all attendees from the meeting link (but don't delete the meeting!), so they will no longer have the series sent from personal calendars. Then, you need to copy + paste the meeting info into an MTL Help / MTL Info Outlook invitation, add the appropriate attendees, and send.
    
mtl.info@va.gov  - Research Workgroup Meetings
Mon-Wed AM

- [x] *8AM Workgroup Leads
- [x] #manuscript_mondays
- [x] team_time
- [x] vapor
- [x] qual_workgroup
- [x] co-i
- [x] quant_research
- [x] *hq

Mon-Thurs (wk)
Friday Focus/Flex
 
mtl.help@va.gov - Operations
Modeling to Learn quality improvement (QI) initiative (Operations)
Production "Live" with QIICs and Teams
Scope Andons (Scope, Alert, Communicate)

Wed PM - Thursday AM

- [x] *facilitate
- [x] msd365_crm
- [x] support
- [x] sim_ui_model
- [x] quant_operations

**Comment by staceypark** [comment]
@anazariz @lijenn @jamesmrollins @dkngenda 
As we switch  our main team meetings to the MTL Help and Info calendars, note there is a workaround on how we schedule the meetings to ensure there is an audio line for folks to dial into (also in the first instructions above).

For meeting series that already exist:
1. Open the meeting series in your personal Teams calendar.
2. Remove all the meeting attendees from the existing meeting series (that was previously created from your personal calendar). This will remove it from THEIR calendars. 
3. DO NOT delete/cancel the series itself though. 
4. Copy the meeting info (including the link and dial in numbers).
5. Go to the MTL Help or MTL Info Outlook calendar and create a meeting series with the appropriate attendees added. 
6. Paste the information from Step #4 into the body and send.

For new meeting series:
1. Go to Calendar > New Meeting (purple button on top right).
2. Add the appropriate meeting title, time, frequency, and workgroup channel. 
3. Do NOT add any required attendees.
4. Save & schedule the meeting.
5. Open the meeting on your Teams calendar and copy the meeting info (including the link and dial in numbers).
6. Go to the MTL Help or MTL Info Outlook calendar and create a meeting series with the appropriate attendees added. 
7. Paste the information from Step #5 into the body and send.

**Comment by anazariz** [comment]
@lijenn showed Ash how to schedule a meeting in Outlook and modify the details from Teams.
