### ISSUE TITLE
wk3_may_epic_TEST_QA: story 8 Validate Team Administration

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#1860]
# Validate Sim UI Administration

## Conditions

- User is listed as an end user, with "Facilitator" set to "Yes" in the Admin group in Epicenter.
- User is listed as an end user, with "Facilitator" set to "Yes" in all groups in Epicenter.
- User is provided a login screen from any login within a TEST/PROD environment.

## Regarding Single Sign-on

After selecting "Administrator" from the login dropdown, the user is presented with a Admin version of the Facilitator Dashboard:
  - [ ]  Has "MTL Demo," "Team PSD," "Sim UI Admin" and "tt" icons available in the header menu.
  - [ ] When each of the icons are clicked, they result in navigation to the appropriate dash board?
  - [ ] When the destination dashboard is reached, the user can easily navigate back to origin?
  - [ ] When the destination dashboard is reached, any other dashboard can be reached?
- [ ] The Facilitator Dashboard allows the Admin to navigate to any team session?
- [ ] The Facilitator Dashboard allows the Admin to review experiment completion status, team rosters and statistics.

## Regarding _MTL_ Demo Dashboard

- [ ] The appropriate _MTL_ Demo logo is used to identify the dashboard?
- [ ] The Admin is able to easily add, rename or delete a course code?
- [ ] The Admin can set a custom number of days before the course code expires?
- [ ] The Admin can upload icons directly to the data API?
- [ ] The Admin can upload GIF files directly to the data API?
- [ ] Subordinate screens, such as "Quick Tips" and "More Information" display the _MTL_ Demo logo?

## Regarding Team PSD Dashboard

- [ ] The appropriate Team PSD log is used to identify the dashboard?
- [ ] The Admin can upload icons directly to the data API?

### Team Data

When the user clicks on the "Sim UI Admin" button, the UI presents a Sim UI Administration pop up that:
  - [ ] Presents a list of Team Data files and P-charts that are currently in Epicenter?
  - [ ] Shows the date the files were loaded into Epicenter?
  - [ ] Is in alpha-numeric order?
  - [ ] Provides a means to "Add," "Rename," or "Delete" a Team Data or P-chart file?
  - [ ] (For James to Verify) Updates the Team Data files listed in the GitHub repositories?
  - [ ] Provides a means to drag-and-drop files into the directory, or upload using the file manager?

### Team Set-up

When the user clicks on the "Sim UI Admin" button, the UI presents a Sim UI Administration pop up that:
  - [ ] Presents a list of teams that include "_team" and "_ind" extensions?
  - [ ] Shows the date the team was created?
  - [ ] Provides a means to "Add," "Edit," or "Delete" a team via dialogue?
    When "Add" button is clicked:
      - [ ] A "Team Set-up" pop up appears?
      - [ ] Provides a field to enter a team name, a Team Vision, and a dropdown to indicate the appropriate research arm (blue, VA red, NIH red)?
      - [ ] Provides a means to "Add," "Edit" or "Delete" team members?
      - [ ] "Add" dialogue provides a field to enter a team member's username, a role dropdown (Admin, Facilitator, Team Lead, Team Member)?
  - [ ] Provides a means to add a team by uploading an Excel template?
- [ ] When a Team is created, the appropriate _team and _ind groups are created in Epicenter?
- [ ] Users in "_team" are all assigned to world001.?
- [ ] Users in "_ind"  are assigned an individua world?
- [ ] The system creates a password based on the first two terms of team name, with second term ALL CAPS, and standard term "!01" at the end?
_For Example_: If a team is named "640a0_mpd_team4" the password would be "640a0_MPD!01"
- [ ] The system notifies the user of their username and password via email to their VA account?

## tt report

**See #1753 Validate tt Report Automation**

**Comment by lzim** [comment]
**Discussed at 04/14/21 Sim UI Workgroup**

**#1860 Story 8**
@staceypark will be a great Story 4 QA test
@lijenn will be a great workflow user to test Story 8.

**Story 7 & 8 - Co-facilitator prep for session 4 occurs May 4.**
Need: MTL Menu & tt report & Data UI upload by first week of May.

**#1754 Story 7 - Documentation**

_Modeling to Learn_ Facilitator & Technical Manual
https://mtl.how/manual

**Team PSD Document Tracker**
https://mtl.how/documents

**Comment by lijenn** [comment]
Jenn QA:

## Conditions

- User is listed as an end user, with "Facilitator" set to "Yes" in the Admin group in Epicenter.
- User is listed as an end user, with "Facilitator" set to "Yes" in all groups in Epicenter.
- User is provided a login screen from any login within a TEST/PROD environment.

## Regarding Single Sign-on

After selecting "Administrator" from the login dropdown, the user is presented with a Admin version of the Facilitator Dashboard:
  - [ ] Has "MTL Demo," "Team PSD," icons in the header menu.
  - [ ]  "Sim UI Admin" and "tt Admin" icons available in the dashboard.
  - [ ] When each of the icons are clicked, they result in navigation to the appropriate dash board?
  - [ ] When the destination dashboard is reached, the user can easily navigate back to origin?
  - [ ] When the destination dashboard is reached, any other dashboard can be reached?
- [ ] The Facilitator Dashboard allows the Admin to navigate to any team session?
- [ ] The Facilitator Dashboard allows the Admin to review experiment completion status, team rosters and statistics.

## Regarding _MTL_ Demo Dashboard

- [ ] The appropriate _MTL_ Demo logo is used to identify the dashboard?
- [ ] The Admin is able to easily add, rename or delete a course code?
- [ ] The Admin can set a custom number of days before the course code expires?
- [ ] The Admin can upload icons directly to the data API?
- [ ] The Admin can upload GIF files directly to the data API?
- [ ] Subordinate screens, such as "Quick Tips" and "More Information" display the _MTL_ Demo logo?

## Regarding Team PSD Dashboard

- [ ] The appropriate Team PSD log is used to identify the dashboard?
- [ ] The Admin can upload icons directly to the data API?

## Regarding the Sim UI Administration

### Team Data

When the user clicks on the "Sim UI Admin" button, the UI presents a Sim UI Administration pop up that:
  - [ ] Presents a list of Team Data files and P-charts that are currently in Epicenter?
  - [ ] Shows the date the files were loaded into Epicenter?
  - [ ] Is in alpha-numeric order?
  - [ ] Provides a means to "Add," "Rename," or "Delete" a Team Data or P-chart file?
  - [ ] (For James to Verify) Updates the Team Data files listed in the GitHub repositories?
  - [ ] Provides a means to drag-and-drop files into the directory, or upload using the file manager?

### Team Set-up

When the user clicks on the "Sim UI Admin" button, the UI presents a Sim UI Administration pop up that:
  - [ ] Presents a list of teams that include "_team" and "_ind" extensions?
  - [ ] Shows the date the team was created?
  - [ ] Provides a means to "Add," "Edit," or "Delete" a team via dialogue?
    When "Add" button is clicked:
      - [ ] A "Team Set-up" pop up appears?
      - [ ] Provides a field to enter a team name, a Team Vision, and a dropdown to indicate the appropriate research arm (blue, VA red, NIH red)?
      - [ ] Provides a means to "Add," "Edit" or "Delete" team members?
      - [ ] "Add" dialogue provides a field to enter a team member's username, a role dropdown (Admin, Facilitator, Team Lead, Team Member)?
  - [ ] Provides a means to add a team by uploading an Excel template?
- [ ] When a Team is created, the appropriate _team and _ind groups are created in Epicenter?
- [ ] Users in "_team" are all assigned to world001.?
- [ ] Users in "_ind"  are assigned an individua world?
- [ ] The system creates a password based on the first two terms of team name, with second term ALL CAPS, and standard term "!01" at the end?
_For Example_: If a team is named "640a0_mpd_team4" the password would be "640a0_MPD!01"
- [ ] The system notifies the user of their username and password via email to their VA account?

**Comment by jamesmrollins** [comment]
Hi @lijenn. Than you for the thoughtful QA TEST.

### Regarding your questions above:

- Sorted by date on default, wondered if we should have a filter icon for the Date/Time as well?
*The table can only have one sort focus at a time.  If you click the Date/Time header, it will get the sort icon.*
- Do you know what the number that is right below the Date/Time is?  
 *You are seeing the time the file was created. When the table is at higher zoom levels in the browser, the line will wrap. This is normal behavior.  To see the whole line, one line, decrease the zoom level.*

**Comment by jamesmrollins** [comment]
@hirenp-waferwire - please see the issues below:

## Dashboard Issues

1.  When attempting to open a team dialogue for editing, the browser hangs. **THIS IS AN INTERMITTENT PROBLEM.**

![image](https://user-images.githubusercontent.com/30132017/118542789-56464800-b708-11eb-8cd9-d39bc8536374.png)

2. When I checked Epicenter, the world ID is not what I expected.

![image](https://user-images.githubusercontent.com/30132017/118543366-0d42c380-b709-11eb-9639-2e260f75bb12.png)

3. When I added a test group - it doesn't appear in the backend.  But the front end displays just fine.

![image](https://user-images.githubusercontent.com/30132017/118544442-43347780-b70a-11eb-8829-f145e4414622.png)
