### ISSUE TITLE
wk2_apr_epic: QA TEST: re-create_stockton_agg_experiments_in_sim_ui

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#1861]
Testing criteria to be developed by @jamesmrollins by April 10.

**Comment by lzim** [comment]
@jamesmrollins @lijenn 

It looks like I"m assigned here, but I don't believe there is a task for me, right James?
Jenn do you have something, I don't think so ??

We probably need this card more descriptive, James.
And, if it's part of a series of cards, then it should be connected to those issues in dependency chain.
