### ISSUE TITLE
wk_?  ?_epic story_1: r21_qual_mtl_fidelity - https://osf.io/q9wsa/

### ISSUE THREAD

**Issue by dkngenda** [lzim/teampsd#1862]
Assign authorship app:

- [ ] Shinyapp used to determine 1) eligible and 2) responsible authors​
- [ ]  All authors pinged (@)​
- [ ]  Authorship agreement signed​
- [ ]  Workflow determined during #manuscriptmonday ​

**Comment by lzim** [comment]
#adjudicate_memo - I believe this is as duplicate card.
