### ISSUE TITLE
wk2-april_2021-Task-EBPharm Elapsed Days Polypharmacy Change 

### ISSUE THREAD

**Issue by anazariz** [lzim/teampsd#1869]
**EBPharm Elapsed Days Polypharmacy Change** 

Current algorithm does not consider a medication change while looking at the series of medications in (chronological order) for a patient to be  identified as a completer. Code change is required to incorporate a change in medication. 

Change in medication constitutes the beginning of a new (chronological) series. A patient could have qualified as a completer in the previous version of the code. Now, the patient may not qualify or qualify multiple times (doses per number of days). More detailed requirements will be added to this issue. The estimate includes the code change and Unit testing. Additional Dev/QA/Prod testing estimates not included in this issue.

**Comment by dkngenda** [comment]
Hi Ash, I just reviewed your 04/16 email on this issue. I think if your filters pick up the records you highlighted the we will capture the correct records.  By the way are you able to add a column for the initial EBPharm issue date (i.e Date when we start counting days to completion). Also, have we made a decision on how to capture  omnibus days to EBP completion ?

**Comment by anazariz** [comment]
1) @dkngenda, during the weekend I completed the coding of Dep, AUD, OUD. I'll run the whole thing today to get you the output.     
2) Let's do a quick huddle regarding the issue date because that is already part of the output. 
3) RE Omnibus: not yet.

**Comment by anazariz** [comment]
@dkngenda, I completed the DEP, AUD, OUD EBPharm, EBPsy and omnibus. All results are included it in the delivered Excel workbook. 
Proposing to closing this issue as all mentioned components have been delivered. 
We can create a new issue for producing the anchor table, median, etc., which are beyond the scope of this issue.

**Comment by anazariz** [comment]
@dkngenda can this be closed?

**Comment by dkngenda** [comment]
Yes I think we are done

**Comment by staceypark** [comment]
sounds like this is ready to be closed according @dkngenda and @anazariz.
I am closing.
