### ISSUE TITLE
Customizable Say documents needed

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#1871]
Some of the QIICs (I have been known to as well) are doing things like copying and pasting the See or Say guide into a Word document, making edits to make it more readable for themselves, and using that as an editable document to customize for the specific team & session with time stamps, facilitator assignments, and team-specific content. 

Clearly, our current materials are not meeting users' need. What I feel is wanting is a document - it could be a fillable form - that has the exact SEE guide on it, with spaces for times and facilitator initials. The times should be filled in with our best wisdom on how to manage the session, but editable during pre-meeting prep if cofacilitators need to. It should also have blocks for the team-specific and MTL goal-specific text to be filled in during between-session prep. The customized document needs to be saved somewhere, like attached to the team_tracker card, so all co-facilitators can access it -  not downloaded to one co-facilitator's computer.

This should arguably be the *only* facilitator session guide. If we need the longer SAY guides for facilitate learners to read and practice a more detailed script, those might be called Say Scripts and go in the manual. What I am envisioning could actually also be fine for learners - they'd see the SEE guide plus the blanks, not the filled in information. If so, we could eliminate one navigation click by not having separate facilitator and learner folders in mtl.how/blue. We would also reduce the total number of documents facilitators are expected to juggle, which is complicated currently.

That's my o🌲ion anyway! 😺

**Comment by lzim** [comment]
I'm going to close this as I believe the Notes section of the "Team Session & Details" in Dynamics will meet this need and is tracked on a separate issue.
