### ISSUE TITLE
wk4 apr_2021 Task: Story 5-WBS of Migration to SharePoint Online

### ISSUE THREAD

**Issue by anazariz** [lzim/teampsd#1886]
**WBS of Migration to SharePoint Online:** 

**NOTE: This workstream does not include Power BI**   

**Workstream 1:**
- [ ] ATO for PHI/PII (to be handled by @lzim & @staceypark)  - 8 Points - #1915

**Workstream 2: (heavy dependency on Workstream1)** 
- [ ] Analyze the gaps - what are the differences between the SharePoint Online and our current SharePoint On-Premises - **5 Points** 
#1916
- Filesystem and User Accounts - 2 Points
- App functionality (add user/team, create folder) - 3 Points     
 
- [ ] Close the gaps - **24 vs 48 Points** 
#1917
- Filesystem and User Accounts - 8
- App functionality **Restore** vs **Redesign using using 365 tools (prevent rework)** - 16 vs 40

- [ ] Redirect/Correct Link - **2 Points**
#1918
- MTL.how/data - 2 points

- [ ] Test Propagation Mechanism (Data UI & Facility)  - **16 Points** 
#1938

- [ ] Test Dev to Prod release process - **5 point**   
#1939  

- [ ] Update Technical Documentation - **3 point**

**Comment by lzim** [comment]
**Discussed at support_workgroup 04/14/2021**

**Check the inventory** from @anthonycpichardo of the https://mtl.how/data and https://mtl.how/data_migration
#1659
#1660
#1661
#1662

**1. Sharepoint Online Migration (Phase I)**
- BISL on prem WILL be sunsetted and we need to migrate.

**2. Power BI (Phase II)** - Only when Sharepoint Online Migration complete.

**Comment by staceypark** [comment]
@anazariz Current documentation on managing team folders and clinician permissions at **mtl.how/data** is here: https://spsites.cdw.va.gov/sites/PTSD_OMHO/Pages/Administrative.aspx

I think a previous idea we had was to use the existing "Request New Team Folder" and "Request Team Membership Change" as automated buttons. Currently these buttons only exist to "supply info" not automate any work. 

But, it'd be great if we could supply the appropriate info at these buttons and the folder creation, permissioning, etc. is done automatically.

**Comment by lzim** [comment]
**discussed at sim_ui_workgroup**

**Team Data Mode & Balanced Mode**
- Before time 0 (Today) depicts values from team data tables.
- Then the experiments start the model in equilibrium.
- Archived R produced tt_reports do not depict these aspects of how the simulation runs experiments.
- However, based on the validation reviewed today **we are getting reliable, valid results that can be reported in manuscripts.**

**Module from the R21 AGG & PSY**
**We do want to reproduce all 6 R21 Team Time Reports based on reverse engineering the experiments, using the team data from that time.**

This is consistent with _**Participatory Research** - Review the R21 Findings and the Simulation Experiments...ideally the clinicians can still review their old experiments in the Sim._


- [ ] _Next James will look at PSY MPD Team 1._

@staceypark will create an issue task card to get the RedCap data to @jamesmrollins

**Comment by staceypark** [comment]
@lzim is this meant to be here? Not sure what we need from the SharePoint migration.
I'm wondering if this is meant for #1900.

> **discussed at sim_ui_workgroup**
> 
> **Team Data Mode & Balanced Mode**
> 
> * Before time 0 (Today) depicts values from team data tables.
> * Then the experiments start the model in equilibrium.
> * Archived R produced tt_reports do not depict these aspects of how the simulation runs experiments.
> * However, based on the validation reviewed today **we are getting reliable, valid results that can be reported in manuscripts.**
> 
> **Module from the R21 AGG & PSY**
> **We do want to reproduce all 6 R21 Team Time Reports based on reverse engineering the experiments, using the team data from that time.**
> 
> This is consistent with _**Participatory Research** - Review the R21 Findings and the Simulation Experiments...ideally the clinicians can still review their old experiments in the Sim._
> 
> * [ ]  _Next James will look at PSY MPD Team 1._
> 
> @staceypark will create an issue task card to get the RedCap data to @jamesmrollins
