### ISSUE TITLE
Upload Deidentified Team Meeting Files 

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#189]
Hi @lzim @branscombj @dlkibbe @dlounsbu @TomRust,

As we wrap up the last of the R21 pilot team meetings, the Qualitative Workgroup is uploading and coding the entire corpus of team meetings.  
Please **deidentify** and **upload** any team meeting notes that you haven't to their appropriate team folder by **Friday 9/21** so our qual team can code them!
https://github.com/lzim/teampsd/tree/master/qual_workgroup/coded_meetings/

@TomRust @dlounsbu  - We're not seeing your notes from Friday 8/31 for Team 4.  Please upload your de-identified notes here: https://github.com/lzim/teampsd/tree/master/qual_workgroup/coded_meetings/team4

**Comment by staceypark** [comment]
**_PLEASE double check notes that you already have posted to ensure they are compliant with the below coding decisions and make sure notes that you will upload are compliant as well!_**

1) Team lead denoted as - **tlead**
2) TeamPSD Facilitators denoted as **2 letter initials** - i.e. LZ, SP, etc.
3) Team members denoted with **discipline** or **tmember** i.e. md, sw, etc.
4) Team names denoted as **team numbers** i.e. team 1, team 2, etc. 

_**We DO NOT want any identifying information for the teams or the team members, including team names, team members names, and team member initials.**_

**Comment by lzim** [comment]
Hello Team PSD Facilitate Workgroup @branscombj @dlkibbe @dlounsbu @TomRust !
😺 

@staceypark needs to make sure there are no missing team meeting notes by our 8AM Pacific on Monday for our Team PSD Qualitative Workgroup.

**Key Dependency:** The qualitative workgroup needs all team meetings uploaded into our RQDA workflow on Monday. Stacey will be working to make sure we have all team meeting notes on Monday uploaded and ready to go for the qual_workgroup meeting on Tuesday.

- Please upload any DE-IENTIFIED notes you have by Monday. The 

_However, if you are unsure, what the de-identified team name is, please check Lucid notes for that team or with Stacey._ **Watch for re-work potential across the team** We had a mix-up yesterday, which led to some rework for one of our co-facilitators, who prepped for the wrong team, and will not have to set that back up for the right time by Wed.

Thanks! 

Lindsey

**Comment by lzim** [comment]
Hello Everyone,

This issue is now closed. @staceypark and @swapmush are completing the final inventory of all de-identified Team Meetings this morning. We have a few R21 team meetings remaining, but the qualitative workgroup will be working on this today and so we are confirming that we have all R21 team meeting notes to date already.

Thanks! 👍
