### ISSUE TITLE
wk2 june_epic: story_6 10 Standard CRM & co-plan Dashboards

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1896]
CRM Config: 10 Standard CRM & co-plan Dashboards

**Comment by lijenn** [comment]
@hsnyder2 @apisano0920 FYI, I am updating the scheduled dates/times of the team meetings, I believe it impacts this story, but may carry over to other areas where the schedules of the teams is used. 

I'll let you know when I have confirmed the date/times that have changed.

(Please let me know who else should be pinged on these cards btw?)

**Comment by lijenn** [comment]
Discussed at Support WG Wed. 5/19:
- [ ] @lijenn will send @hsnyder2 and @apisano0920 the admin checklist for both MTL Red and MTL Blue
- [ ] @lijenn will ask Facilitators to record their prep session for @Spanglemonkey, I will also record my tasks alongside since I usually try to related tasks within the meeting. 
-  For next week's Support WG meeting on 5/26, we will need @MattMoore2 @branscombj to share features they'd want to see as Facilitators for the dashboard based on current pain points/needs that do not currently exist.

**Comment by lijenn** [comment]
@hsnyder2 and @apisano0920 Here are the checklists I have for:
- Co-planning phase
- Support Phase
- Team Meeting Phases for NIH Red and NIH/VA Blue. I'm still in-progress for VA Red checklists:

### Co-planning

1a:
- [ ] Initiate/Send Co-plan 1a Email + attach co-planning1a documents/files
- [ ] Schedule Co-plan 1a + attach co-planning1a documents/files, invite sent from MTL.Help@va.gov

If 1b is needed:
- [ ] Follow-up by sending Co-plan 1b + attach co-planning1a documents/files
- [ ] Schedule co-plan 1b + attach co-planning1a documents/files, invite sent from MTL.Help@va.gov

### Support
 - [ ] If the site is not ready to begin _MTL_, track the last point of contact made with the site/VISN Leadership (i.e. emails & meetings) and leave it in the column of the team_tracker where we left off of.
 - [ ] Track approximate date of when we need to reach out to the site/leadership to resume co-planning. 

2a:
- [ ] Initiative/Send Co-Plan 2a email + attach co-planning1a documents/files and 2a documents/files
- [ ] Schedule Co-plan 2a + attach co-planning1a documents/files and 2a documents/files, invite sent from MTL.Help@va.gov
- [ ] Get the team meeting date/time and members and clinical roles from the Process map, unless 2b is needed. 

If 2b is needed:
- [ ] Follow up by sending Co-plan 2b email + attach 2a documents/files
- [ ] Schedule Co-plan 2b + attach 2a documents/files, invite sent from MTL.Help@va.gov
- [ ] Get the team meeting date/time and members and clinical roles from the co-planning Process map document. 

### Team Meeting Prep
- [ ] List out all team dates/times in EES master list sheet
- [ ] Send Team Times to EES and request TMS Code
- [ ] EES confirms TMS course code and times are added to TMS
- [ ] Check TMS course listing/code for errors
- [ ] Set up MS Teams Group and add Learners
- [ ] Send Outlook invitations for team meetings to Learners from MTL.Help@va.gov
- [ ] Setup team folders on mtl.how/data 
- [ ] Prep Pre/post emails 
- [ ] Prep Baseline and 6 month follow up surveys

### NIH Red
NIH Red Part I
- [ ] Send Pre-email 1 week before team meeting
- [ ] Confirm attendance with EES for CMEs/CEUs 
- [ ] Send Post-email after team meeting 
- [ ] Send Baseline Survey after team meeting
- [ ] Facilitators: Prep data ui file before team meeting

NIH Red Part II
- [ ] Facilitators: Prep team data table before team meeting
- [ ] Send Pre-email 1 week before team meeting
- [ ] Confirm attendance with EES for CMEs/CEUs 
- [ ] Prep and send Team Time report # 1, attach to post email. 
- [ ] Send Post-email after team meeting 
- [ ] Send 6 month follow up survey in 6 months from last team meeting

### NIH/VA Blue Session 1-12:

NIH/VA Blue Session 1:
- [ ] Send Pre-email 1 week before team meeting
- [ ] Confirm attendance with EES for CMEs/CEUs 
- [ ] Send Post-email after team meeting 
- [ ] Send Baseline Survey after team meeting
- [ ] Email and schedule meeting with the MTL Team Lead to prep data for Session 2. 
- [ ] Facilitators: Document notes from intersession prep in team_tracker
- [ ] Facilitators: Document notes from Live meeting/debrief in team_tracker

NIH/VA Blue Session 2:
- [ ] Facilitators: Prep data ui file before team meeting
- [ ] Facilitators: Document notes from intersession prep in team_tracker
- [ ] Facilitators: Document notes from Live meeting/debrief in team_tracker
- [ ] Prep Sim UI and MTL Menu logins for Learners and Facilitators before Session 3 team meeting.
- [ ] Send Pre-email 1 week before team meeting
- [ ] Confirm attendance with EES for CMEs/CEUs 
- [ ] Send Post-email after team meeting 

NIH/VA Blue Session 3:
- [ ] Facilitators: Prep team data table before team meeting
- [ ] Facilitators: Document notes from intersession prep in team_tracker
- [ ] Facilitators: Document notes from Live meeting/debrief in team_tracker
- [ ] Send Pre-email 1 week before team meeting
- [ ] Confirm attendance with EES for CMEs/CEUs 
- [ ] Send Post-email after team meeting 

NIH/VA Blue Session 4:
- [ ] Facilitators: Document notes from intersession prep in team_tracker
- [ ] Facilitators: Document notes from Live meeting/debrief in team_tracker
- [ ] Prep and send Team Time report # 1, attach to post email.
- [ ] Send Pre-email 1 week before team meeting
- [ ] Confirm attendance with EES for CMEs/CEUs 
- [ ] Send Post-email after team meeting 

NIH/VA Blue Session 5:
- [ ] Facilitators: Upload Team Data file in SIM before team meeting
- [ ] Facilitators: Document notes from intersession prep in team_tracker
- [ ] Facilitators: Document notes from Live meeting/debrief in team_tracker
- [ ] Send Pre-email 1 week before team meeting
- [ ] Confirm attendance with EES for CMEs/CEUs 
- [ ] Send Post-email after team meeting 

NIH/VA Blue Session 6:
- [ ] Facilitators: Document notes from intersession prep in team_tracker
- [ ] Facilitators: Document notes from Live meeting/debrief in team_tracker
- [ ] Send Pre-email 1 week before team meeting
- [ ] Confirm attendance with EES for CMEs/CEUs 
- [ ] Send Post-email after team meeting 

NIH/VA Blue Session 7:
- [ ] Facilitators: Document notes from intersession prep in team_tracker
- [ ] Facilitators: Document notes from Live meeting/debrief in team_tracker
- [ ] Send Pre-email 1 week before team meeting
- [ ] Confirm attendance with EES for CMEs/CEUs 
- [ ] Send Post-email after team meeting 

NIH/VA Blue Session 8:
- [ ] Facilitators: Document notes from intersession prep in team_tracker
- [ ] Facilitators: Document notes from Live meeting/debrief in team_tracker
- [ ] Prep and send Team Time report # 2, attach to post email. 
- [ ] Send Pre-email 1 week before team meeting
- [ ] Confirm attendance with EES for CMEs/CEUs 
- [ ] Send Post-email after team meeting 

NIH/VA Blue Session 9:
- [ ] Facilitators: Document notes from intersession prep in team_tracker
- [ ] Facilitators: Document notes from Live meeting/debrief in team_tracker
- [ ] Send Pre-email 1 week before team meeting
- [ ] Confirm attendance with EES for CMEs/CEUs 
- [ ] Send Post-email after team meeting 

NIH/VA Blue Session 10:
- [ ] Facilitators: Document notes from intersession prep in team_tracker
- [ ] Facilitators: Document notes from Live meeting/debrief in team_tracker
- [ ] Send Pre-email 1 week before team meeting
- [ ] Confirm attendance with EES for CMEs/CEUs 
- [ ] Send Post-email after team meeting 

NIH/VA Blue Session 11:
- [ ] Facilitators: Document notes from intersession prep in team_tracker
- [ ] Facilitators: Document notes from Live meeting/debrief in team_tracker
- [ ] Send Pre-email 1 week before team meeting
- [ ] Confirm attendance with EES for CMEs/CEUs 
- [ ] Send Post-email after team meeting 

NIH/VA Blue Session 12:
- [ ] Facilitators: Document notes from intersession prep in team_tracker
- [ ] Facilitators: Document notes from Live meeting/debrief in team_tracker
- [ ] Send Pre-email 1 week before team meeting
- [ ] Confirm attendance with EES for CMEs/CEUs 
- [ ] Prep and send Team Time report # 3, attach to post email. 
- [ ] Send MTL goodies to Learners. 
- [ ] Send Post-email after team meeting 
- [ ] Send 6 month follow up survey in 6 months from last team meeting

**Comment by lijenn** [comment]
@hsnyder2 @apisano0920 

Here are the most up to date MTL Blue pre/post emails:
- NIH/VA Blue Pre-emails: https://github.com/lzim/teampsd/tree/master/mtl_facilitate_workgroup/pre_post_emails/pre_emails
- NIH/VA Blue Post-emails: https://github.com/lzim/teampsd/tree/master/mtl_facilitate_workgroup/pre_post_emails/post_emails
- Note that the VA Red pre/post emails are still in progress.

This is not in the templates on GitHub, but we also include a quick message at the top of the email before the template, like this:
![image](https://user-images.githubusercontent.com/59668647/119717541-466ee800-be1b-11eb-8fe9-4e1ecf301b96.png)

**Comment by lijenn** [comment]
@hsnyder2, @apisano0920, @Spanglemonkey re: Recordings of Facilitators.

Unfortunately, I was not able to record as it had slipped my mind and Having attended the prep, I don't think it might have been particularly useful since Lauren, as you mentioned, you may want to ask questions and it would not have been orienting as well since our prep sessions were only 30 minutes this week since we had our live team meetings this week. 

If you would still like a recording, we could try to record @branscombj and @MattMoore2's intersession prep next Tuesday since it'll be a full 2 hours length prep so you could see a full prep session? 

For today's 2pm Support Workgroup meeting, @Spanglemonkey we could continue the activity with the sticky notes and dashboard like we discussed last week, but get Jane and Matt's input since we got some of the Admin's perspectives but are missing the Facilitators.

**Comment by Spanglemonkey** [comment]
@lijenn that prep meeting recording would be awesome!
