### ISSUE TITLE
wk4 jun_epic: Master Data UI File - Add a PC/PCMHI dropdown to the SPReferrals tab

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1899]
![image](https://user-images.githubusercontent.com/59668647/115288345-30785400-a106-11eb-9973-92f0cd5872f9.png)
From the co-planning meeting on Tues.4/13 from 11-12pm Pacific with @lzim and @jwklocek, see below for the feature request:
 
Step up to Mental Health can happen through a PCMHI, but stepping down through PCMHI is a rare referral flow that we need to account for the data ui file. 

**Feature Request: Include an additional dropdown shown as 'PC/PCMHI' in the SPReferrals tab in the Data UI to allow teams can step down to PC/PCMHI.**
 
The data ui file will need to know if it's a step up or step down logic. 
**In this case, it is a step-down, which should have the same logic as the GMH.**

**Comment by lijenn** [comment]
@staceypark @anazariz 
Since the PC/PCMHI dropdown follows the same logic as GMH in the SPReferrals tab, I believe that this bug is blocked by #2019 where I believe there is a bug where GMH is selected.

**Comment by anazariz** [comment]
Closing - #1899 - Closed as inconsistent with the logic of the SPReferrals tab to have PC/PCMHI listed in the dropdown. Discussed a 6/18 support wg.
