### ISSUE TITLE
wk1 may_epic BUG: Engagement Duration vs RVI Language in Team Data Table

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1905]
From Tues. 4/20 prep at 6:30-8:30am Pacific:

@lzim There is confusion regarding the language highlighted below in the PsyParams tab of the Team Data Table:

@branscombj:
> Shouldn't Low, Medium, & High be modifying engagement duration, not RVI?
What would it mean to add to the text in column 1, "(low, medium, and high engagement duration)"?

> The **variables** that relate to low-, medium-, and high-engagement duration patients have names that are confusing (actually, inaccurate): the "low/med/high" in them looks like it modifies the main variable (RVI, number of initiators, etc.) rather than engagement duration. 

> MY suggestion for a quicker/dirtier fix than revising variable names (although that might not be so hard to do anymore?) is changing the Column A label in the data table in the dataUI and in the simUI popup:
"Engagement attributes for patients after their first 3 months **(by engagement duration: low, medium, high)**"

FYI @jamesmrollins  Jane's proposal will indicate the change in the SIM.

![image](https://user-images.githubusercontent.com/59668647/115473457-9b05be80-a1f0-11eb-9f8a-fe90b3735d3b.png)

FYI: @anazariz

**Comment by branscombj** [comment]
@lijenn 
The **variables** that relate to low-, medium-, and high-engagement duration patients have names that are confusing (actually, inaccurate): the "low/med/high" in them looks like it modifies the main variable (RVI, number of initiators, etc.) rather than engagement duration. MY suggestion for a quicker/dirtier fix than revising variable names (although that might not be so hard to do anymore?) is changing the Column A label in the data table in the dataUI and in the simUI popup:

"Engagement attributes for patients after their first 3 months **(by engagement duration: low, medium, high)**"

**Comment by anazariz** [comment]
need additional input from @branscombj

**Comment by jamesmrollins** [comment]
Hi @lzim @branscombj @lijenn @staceypark  - regarding changing labels and definitions in the Sim UI, all we have to do is go into the model at lzim/mtl/blue/mtl2.0_models using the TeamPSD Manual, chapter 11.9 procedure, and changing the name of the variable, and/or changing the definition, should that be the needed solution here.  Or just tell me what the change is and I will make it happen!  :-)

**Comment by lzim** [comment]
Thanks @jamesmrollins 

I am going to look at this today @branscombj  I believe this is a misunderstanding of the definition and I want to double-check.

**Comment by staceypark** [comment]
> Thanks @jamesmrollins
> 




> I am going to look at this today @branscombj I believe this is a misunderstanding of the definition and I want to double-check.

@lzim can we close this?

**Comment by dkngenda** [comment]
James and Jenn to scope out documentation

**Comment by staceypark** [comment]
from hq workgroup 5/6:
@lzim @branscombj let's briefly touch base on it at 8am 5/11 tuesday facilitate workgroup (even though we know next week will be co-planning) since all teams are using data tools right now

**Comment by lzim** [comment]
@anazariz 
Discussed at Support Workgroup Meeting 5/12/21

We need to add a minor edit to **Column A of the PsyParams** of the **Master Data UI** and **Team Data Table** 
The edit is reflected in the screenshot below.

FYI: @branscombj @lijenn @staceypark 
![image](https://user-images.githubusercontent.com/7454688/118054194-af922e00-b33a-11eb-9eef-c242d0dc80b5.png)

**Comment by anazariz** [comment]
I have implemented the changes. Will set up the testing.

**Comment by staceypark** [comment]
closing this since it passed testing in #1996 and #1995
