### ISSUE TITLE
potential Bug apr_epic: Missing Nurse in Data UI

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1906]
Ideally BEFORE Friday 4/23's 5-7am Pacific Prep meeting (Team Tracker card: lzim/mtl_team_tracker/issues/24)
Need to resolve no later than: Wednesday 4/28 10-12pm Pacific's Prep meeting

There is 1 missing nurse that is not shown in the Data UI file - I have messaged you the name and email.

@anazariz Can you look into this, maybe they are missing from the CDW?
May be related to the previous missing nurse we had before, but please double check.

**Comment by anazariz** [comment]
@lijenn , please take a look at [VA Github Issue #8](https://github.ec.va.gov/EPMO/mtl_operations/issues/8). I will start a similar triage and keep you posted.

**Comment by anazariz** [comment]
@lijenn @dkngenda 

I have found the issue with 1906 (which is similar to 1908). As I cannot discuss it on this thread, I'll chat with you guys tomorrow.

**Comment by lijenn** [comment]
Thanks Ash! Confirmed that is the same issue from [VA Github Issue #8](https://github.ec.va.gov/EPMO/mtl_operations/issues/8).

**Comment by hnorthcraft** [comment]
#adjudicate_memo efforts tracked to other card #1908 , assigning dup
