### ISSUE TITLE
R21 Wrap-up Tasks & any MTL 1.52 Export R21 Teams

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#191]
Hello R21 Facilitators we are wrapping up with our final R21 Teams. This is a huge milestone! :confetti_ball: 

The Facilitate Workgroup identified 3 primary wrap-up tasks related to the MTL 1.6 release and leaving them on good footing moving forward.

**Wrap-up Tasks for Team 4, Team 2 & Team 1:**

1. **Clean up their MTL 1.6 world - make sure they have a good data file.**
- *In order to do this and retain all their work, we need to have an export of all summer simulations run in MTL 1.52. Do we have this?  Did a facilitator export this?  Do we have one through Forio Epicenter?*

2. **Provide them help resources MTL 1.6**

3. **Last session for these teams** (session 10 - some combination of sessions 9, 10, 11, 12 )

- Team 4 (items 1-3)

- Team 2 (items 1-3)

- Team 1 (items 1-3)

**Teams that already finished**
- Team 6 (items 1-2)

- Team 5 (items 1-2)

- Team 3  (items 1-2)

Thanks!

@dlkibbe @jamesmrollins @TomRust @dlounsbu @staceypark @branscombj

**Comment by lzim** [comment]
Hello @branscombj @dlounsbu @TomRust @dlkibbe and @jamesmrollins @staceypark 

Everyone, due to the backwards incompatibility between _MTL 1.52_ and _MTL 1.6_ **we need to know by our 8AM this morning prep meeting** whether anyone was able to export Team 1 and Team 2's work (q/h/f/d text, runs, etc.) during the _MTL 1.52_ release. Did anyone do this?

At 8AM today, we need to clean up the "worlds" for teams 1 and 2 this morning for their wrap-up team meetings, *which are tomorrow morning.* We will have to re-create the teams's prior work in _MTL 1.6_ as we did last week for Team 4.

Please let us know, ASAP if you completed an export - Or, @jamesmrollins please let us know if we can still retrieve _MTL 1.52_ text and output. We need to delete this prior work, so that they have "apples to apples" _MTL 1.6_ work to use for ongoing learning after we wrap-up our team meetings with them. And, at the same time, we don't want to lose this work!

Thanks,

Lindsey

**Comment by branscombj** [comment]
Unfortunately, I did not off-load any of the teams' q/h/f/d or runs. 
We need a protocol for saving and/or warning users before any future simUI updates.

**Comment by jamesmrollins** [comment]
If I am given the group-world information for the desired exports, I may be able to retrieve them.  I am sorry that I allowed this to take us all by surprise.

**Comment by lzim** [comment]
@jamesmrollins if you can retrieve these it would be great!

We really need it for all the MTL 1.52 worlds in group: 
640a0_mpd-user-training-may-2018
World 001
World 002
World 003
World 004
World 005
World 006

**Comment by jamesmrollins** [comment]
@lzim  I will see what I can do . . .
