### ISSUE TITLE
wk3 apr_epic ANDON: VizMeas& DataMeas tabs in Data UI

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1913]
@anazariz
**Bug from Thurs. 4/22 team meeting from 8:30-10:30a Pacific** with @branscombj @hmarcia.
The VizMeas and DataMeas tabs are not reflecting the filtered clinic selections from the ClinicSelection tab, they are including other Divisions in the data. 

**Impact by Priority**
The bug above will be an ANDON to any active/existing data ui file, here are the 2 impacted teams listed in priority for this week and upcoming week:

1. Prep: wk3 **TOMORROW Friday 4/22 5-7am Pacific** - @dlkibbe @clairecollie 
2. Live Meeting: wk4 Mon. 4/26 from 10:30-12:30p Pacific - @lzim @jwklocek 
3. Live Meeting: wk4 Wed. 4/28 from 10-12p Pacific - @dlkibbe @clairecollie

**Comment by anazariz** [comment]
check vizdata + vizmeas for 589 + 605 --- filter not working correctly.

**Comment by anazariz** [comment]
@lijenn 

I found the bug. A missing filter was causing wrong records to be selected. Will need to walk you through it on Monday because the missing filter is applicable to a query that has two parts. I need to know if the filter needs to be applied to one of both. Will explain.

**Comment by dlkibbe** [comment]
Thanks @anazariz

**Comment by lzim** [comment]
Discussed at **8AM Workgroup Leads** 4/26
@jwklocek and I also noticed this prepping for our 11AM team today.
FYI John 😸

**Comment by lzim** [comment]
@anazariz  and @lijenn  will test this today so the fix is implemented today.
Top priority!

@staceypark back of QA
