### ISSUE TITLE
wk5 june_epic task: story_5 - redirect/correct Links

### ISSUE THREAD

**Issue by anazariz** [lzim/teampsd#1918]
**Story 5-Redirect/Correct Links**

mtl.how/data needs to point to our new SharePoint online site. However, as we cannot currently activate/test the link, we need to make sure that are no surprises when we make the switch at go-line time.

**Comment by anazariz** [comment]
changed the sprint as this is not preventing our current progress.

**Comment by lijenn** [comment]
@lijenn updated SharePoint online link from mtl.how/data_migrate to mtl.how/data.
