### ISSUE TITLE
aug_epic Create 1:1 questionnaire for new team member to ask you 

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1923]
Define questions that a new team member should ask you, to understand their role and expertise

**Comment by dkngenda** [comment]
1. What VA online resources did you consult most to familiarize with your day to day work?
     a) CDW page - 
     b) TeamPSD Manual - 
 2. How do you do QA for your code?
 3. How do you go about planning your week?
 4. If I were to contribute to your workflow, how would that typically go
