### ISSUE TITLE
wk2 sep_epic Create 1:1 questionnaire for new team member to ask you 

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1925]
Define questions that a new team member should ask you, to understand your role and expertise

**Comment by lzim** [comment]
@staceypark 
Where are these being collated?
Once mine are saved, I can close this card. Thanks!

**5 Questions to ask Lindsey as PI**

_Work focused:_
1. What is the PI's role on the team?
2. What is the most important thing I should know about my role on the team?
3. What are the most important skills for success on Team PSD?
4. What are the most important priorities for Team PSD right now?
5. What are you personally working on right now on behalf of the team?

_Personally focused:_
1. What book are you reading?
2. What seasonal activity are you doing most right now?
3. Has anything inspired you in the arts lately?
4. What are you looking forward to right now?
5. What do you find most relaxing?

**Comment by lzim** [comment]
@mnallajerla 

If you want to schedule a 30 minute 1:1 coffee chat with me sometime soon, we can do this exercise where you can ask me some questions as part of your onboarding, and we an get to know each other a little better.

**Comment by mnallajerla** [comment]
@lzim sounds good!

**Comment by lzim** [comment]
Scheduled for this week. I'm going to close this 😄
