### ISSUE TITLE
wk4 apr_epic: Team Data Table Bug: Receiving Time-out Errors even 

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#1935]
@anazariz I ran into timeout errors pulling data for _MTL Red part 2_ today after the morning session I facilitated with @jwklocek  

I waited to re-run it again tonight, assuming I'd be well outside the query run time limits, but got the same error message and debug stop (see screenshots).

We would want to get to the bottom of this by the end of the week, so we can prep next Monday.

Thanks!

![image](https://user-images.githubusercontent.com/7454688/116188973-1aa5f880-a6dd-11eb-89f0-6768d7c35926.png)

.![image](https://user-images.githubusercontent.com/7454688/116188834-e3374c00-a6dc-11eb-9e26-38a92ff234fd.png)

**Comment by anazariz** [comment]
Discussed the bug in HQ. @lijenn and @staceypark are not observing this issue.

**Comment by anazariz** [comment]
@lzim Should this issue can not be reproduced by other team members, can it be closed?

**Comment by lzim** [comment]
**For Discussion at 8AM Workgroup Leads Monday 5/3/21.**

I was able to produce and save the team data table on 4/30/21.

However, fyi @anazariz @lijenn and @staceypark it did not save **it back to the team data folder at https://mtl.how/data.**
_Should I close this bug and create a new one?_

Didn't Ash implement that procedure in the most recent Data UI?
We should make sure it goes out, _with active _MTL_ sites as top priority_, with the April propagation this week (**wk1 may_epic**).

**Comment by lijenn** [comment]
@lzim Yes, this bug should close.
The 'save to the team data folder bug' is already under development by Ash after the previous implementation/testing did not pass (tracked in #1903), priority has been assigned to wk1 may_epic MTL teams as top priority.
