### ISSUE TITLE
wk1 may_epic task: story 5 - test propagation

### ISSUE THREAD

**Issue by anazariz** [lzim/teampsd#1938]
**Story 5-Test Propagation**

- [x] Make sure that we are capable to write a small file from the TeamPSD Excel Workbooks to our new SharePoint online
- [x] Make sure that this capability does not break down with large files (Facility and Data UI)

**Comment by staceypark** [comment]
from 4/29 quant meeting: 
we need to get clear about #1915 ATO for PHI/PII first.

our plan B will only be implemented IF the worst case scenario happens of the ATO getting denied.

**Comment by anazariz** [comment]
Part 1 is complete. The Excel file named "write_test_file.xlsm" (in teampsd quant final_datafiles dev write_to_sharepoint folder) has a single button the propagates (using VBA) this file to the Administrative folder.

**Comment by anazariz** [comment]
Part 2 was completed - After receiving approval, a large size (82,519 KB) sample **"Facility"** file was successfully propagated from the on-premises TeamPSD folder to the new onLine SharePoint site. 
That completes both objectives of this task card.

The objective of this card was to overcome a potential process show stopper. The testing proved that files can be written from the on-premises folders to the online SharePoint site. UAT testing (to be scheduled) will test the new platform in its final (pre go-live) state.   

@staceypark can I close this ticket?

**Comment by anazariz** [comment]
@staceypark, closing this card as the work is done.
