### ISSUE TITLE
wk? may_epic task: story_5 SharePoint Online - dev to prod release process

### ISSUE THREAD

**Issue by anazariz** [lzim/teampsd#1939]
**Story 5-Dev to Prod Release Process**

1. Need to discuss with out SharePoint Migration team.
2. Are they going to be delivering to us 2 identical (Dev/Prod) platforms at go-live?

**Comment by lzim** [comment]
@lijenn and @staceypark 

What tasks remain before closing this?

**Comment by dkngenda** [comment]
We are in prod now. This issue will be closed

**Comment by hnorthcraft** [comment]
#adjudicate_memo efforts tracked to other card, assigning dup
