### ISSUE TITLE
wk3 may_2021 Task: Assign R21, R01, IIR ORD privileges to David  

### ISSUE THREAD

**Issue by anazariz** [lzim/teampsd#1940]
**Assign database privilege to David**

While testing out @dkngenda's R connection to the R21/R01 databases, we discovered that he lacks the required permissions to those databases objects. He can connect to the servers and see the databases but not the objects (tables, views, etc.) within. 
He need the same privilege level as @anazariz.

**Comment by lzim** [comment]
@staceypark 
Let's review the DART requests and make sure that David is listed, then go from there to check other permissions.

**Comment by staceypark** [comment]
Added @dkngenda to DART for R21 & R01.
Need IRB with SSN form to submit DART updates for IIR.

Opening #2008 to track remaining work.
