### ISSUE TITLE
jun_epic: Create AGG (2nd half) video walk/talk-throughs of system stories 

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1948]
Split from the Master Card tracking all system stories: #1815 

### Recording a video in Teams
Go to the calendar in Teams; click Meet Now and you can start a meeting with yourself, click More Actions and Start Recording. Share screen, use mousework, talk, etc. Go to More Actions to Stop Recording. Recording is saved in Chat.

AGG
- [x] Fatigue increases ending early (B)
- [x] Wait times affect intake evaluations (B)
- [x] Start delays affect treatment decisions (B)
- [x] RVI delays affect treatment decisions (B)

**Comment by branscombj** [comment]
https://user-images.githubusercontent.com/29778290/122577558-ee459300-d020-11eb-80b8-f36e2e9061b0.mp4

**Comment by branscombj** [comment]
https://user-images.githubusercontent.com/29778290/122577593-f7cefb00-d020-11eb-98ce-a90ca20b2722.mp4

**Comment by branscombj** [comment]
https://user-images.githubusercontent.com/29778290/122616554-932f9280-d058-11eb-98e3-731b3c820a65.mp4

**Comment by branscombj** [comment]
https://user-images.githubusercontent.com/29778290/122616791-1b159c80-d059-11eb-8ed2-a6c76e17360a.mp4

**Comment by hnorthcraft** [comment]
#adjudicate_memo adding operations label
