### ISSUE TITLE
wk5 nov_epic: Create CC & SP video walk/talk-throughs of system stories 

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1949]
Split from the Master Card tracking all system stories: #1815 

### Recording a video in Teams
Go to the calendar in Teams; click Meet Now and you can start a meeting with yourself, click More Actions and Start Recording. Share screen, use mousework, talk, etc. Go to More Actions to Stop Recording. Recording is saved in Chat.

CC
- [ ] Balancing existing and new patients 
- [x] Wait time affects referrals 

SP
- [ ] ??

**Comment by branscombj** [comment]
For CC - Wait Time Affects Referrals, see [AGG Wait Time Affects Referrals](https://github.com/lzim/teampsd/issues/1946#issuecomment-864291333) - I reference that the story works exactly the same in CC.

**Comment by lzim** [comment]
Discussed at #manuscriptmonday and w/ @branscombj briefly today.
Confirmed that it would be great to get these done and embedded in the SAY guide/_MTL_ Manual.

FYI: @staceypark  @lijenn @mnallajerla
