### ISSUE TITLE
We decided on our MTL 1.7 PROD Release Schedule - must complete for MTL Video

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#195]
Hello Everyone!

**RELEASE Schedule - Going from MTL 1.6 to MTL 1.7 for inclusion in MTL Video.** 📆 

As a culmination of all our progress to date, in the next 60 days, we have 2 major Team PSD Milestones with our key partners: frontline staff, OMHSP and EES
1. ***MTL 1.7* Release** - includes the "Measurement-based Stepped Care for Suicide Prevention Module"
2. ***MTL Video*** -  shoot at EES Studios in St. Louis week of 11/26/2018

**Below are the point people from the 6 Team PSD Workgroups completing the *MTL 1.7 Release* in time for the *MTL Video* Shoot in St. Louis the week of 11/26/2018:**
- **[hq_workgroup](https://github.com/lzim/teampsd/tree/master)** - @staceypark 
- **[quant_workgroup](https://github.com/lzim/teampsd/tree/master/quant_workgroup)** - @holbrooa (welcome back 👋)
- **[model_workgroup](https://github.com/lzim/teampsd/tree/master/model_workgroup)** - @TomRust 
- **[sim_ui_workgroup](https://github.com/lzim/teampsd/tree/master/sim_ui__workgroup)** - @jamesmrollins 
- **[mtl_facilitate_workgroup](https://github.com/lzim/teampsd/tree/master/mtl_facilitate_workgroup_workgroup)** - @dlounsbu @branscombj @dlkibbe @TomRust 
- **[ees_workgroup](https://github.com/lzim/teampsd/tree/master/ees_workgroup)** - @branscombj @dlkibbe 

**At our Team PSD workgroup meetings with this week, we decided on our immediate NEXT Steps for the MTL 1.7 release, which adds the ”Measurement-based Stepped Care for Suicide Prevention" module through a phased final development review process with OMHSP and Frontline Stakeholders.**

- *Please note the "who" and "when" of your workgroup, as we all will have other responsibilities in these and other workgroups over this period.  So, we will need people to triage and prioritize to **focus on the things that they only they can/need to do** in their workgroups at key times.*

**STEP 1** 
**MTL 1.6.1: Schedule stakeholder consensus meeting week of 10/1/2018**
 
***DECISIONS DUE: 10/5/12018***
-  ***Divergent thinking pre-work:***  *MTL* provides resources  for frontline decision-making. Stakeholders will remotely review the design and complete the RedCap survey. What decisions do staff feel they are making? What do they need to improve these decisions?  We will discuss the RedCap results and model diagram at the meetings.
 
***KEY STEP 1 Team PSD dependencies (3 workgroups - 4 action steps):***
- **hq_workgroup works on** 
1. programming RedCap pre-work, and 
2.  scheduling two stakeholder review meetings
- **model_workgroup works on** 
3. experiment/decision questions circulated via RedCap (DUE 9/25/2018 for circulation, DUE 9/28/2018 for Stakeholder response), with the 
- **sim_ui_workgroup works on** 
4. sim UI design file for the current SP Vensim .mdl and data UI inputs ("meas" tabs)

**STEP 2**
**MTL 1.6.2: TeamPSD Workgroups develop *MTL* resources to support Stakeholders' Decisions**
 
**WORK DUE: 10/12/2018** 

***Key STEP 2 Team PSD dependencies (4 workgroups):***
- **hq_workgroup** 
- **quant_workgroup**
- **model_workgroup**
- **sim_ui_workgroup**

**STEP 3**
**MTL 1.6.3: Stakeholder consensus meeting week of 10/15/2018** 
**DECISIONS DUE: 10/19/12018**
- **Stakeholders Review and finalize consensus recommendations for sim UI design, experiment functions and language for going in to sim UI development.** 

***KEY STEP 3 Team PSD dependencies (4 workgroups):***
- **hq_workgroup**
- **quant_workgroup**
- **model_workgroup**
- **sim_ui_workgroup**

**STEP 4** 
**MTL 1.6.4: Team Achieves Standardization for UI-Freeze based on Stakeholders Final Recommendations for what would support their decisions** 

**WORK DUE 10/26/2018 - MTL 1.7 UI Freeze - EES Master Brochures for *MTL 12-session plan* to EES**

***KEY STEP 4 Team PSD dependencies (6 workgroups):***
- **hq_workgroup**
- **quant_workgroup**
- **model_workgroup**
- **sim_ui_workgroup**
- **mtl_facilitation_workgroup**
- **ees_workgroup**

**STEP 5**
**MTL 1.6.5: Go from Development -> Test - MTL 1.7 available in Test** 

**WORK DUE 11/2/2018**

***KEY STEP 5 Team PSD dependencies (3 workgroups):***
- **hq_workgroup**
- **sim_ui_workgroup**
- **mtl_facilitation_workgroup**

**STEP 6** 

**WORK DUE 11/9/2018**

**1. MTL 1.7 available in Production** 
**2. MTL learner SEE and facilitator SAY files for SP Module completed**

***KEY STEP 6 Team PSD dependencies (3 workgroups):***
- **hq_workgroup**
- **sim_ui_workgroup**
- **mtl_facilitation_workgroup**
 
**STEP 7** 
**MTL 1.7.1 - SP Rehearsals for *MTL Video* Shoot in St. Louis** 

**WORK DUE 11/16/2018**
***KEY STEP 7 Team PSD dependencies (2 workgroups):***
- **hq_workgroup**
- **mtl_facilitation_workgroup**

----Step 8 will be minor tasks and relaxing with friends and family over the holiday----
----Then we have the MTL Video Shoot in St. Louis the week of 11/26/2018----

**Comment by dlkibbe** [comment]
Thanks for this detailed timeline and deliverables @lzim -- Jane and I are meeting tomorrow.

**Comment by dlounsbu** [comment]
So far so good with Prod 1.7. I have run some experiments for PSY, and I am really liking the interface. I got confused with some experiment naming/documenting, so I will try to clean that up and rerun. Then I will try to finish the SAY file experiment table.
