### ISSUE TITLE
wk3_may_epic_story7: Task Complete tt Admin Functionality

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#1958]
Complete tt Admin Functionality:

- [x] Model selection
- [x] Team selection
- [x] Experiment selection
- [x] Chart selection

**NOTE: We will need to consider how we archive and reset tt reports as this program scales.  Teams that finish initial training may want to continue using the tt report for other experiment series.**

**Comment by jamesmrollins** [comment]
@lijenn @staceypark @lzim @branscombj @MattMoore2  **FYI** @hirenp-waferwire 

## Update

- We are making good progress on developing the tt report functionality in the Sim UI. 
- We will deliver to TEST the tt Admin functions and the tt1 and tt2 page build function by Monday morning. 
- I will update MTL Facilitator and Tech manual by early afternoon Monday (Facilitator Dashboard instructions are complete).
- We will NOT be able to deliver the ability to print a PDF with page-break control. **A more detailed explanation follows.**
- We will be able to deliver the PDF functionality by the middle to end of next week.  I will publish an issue card to track this work.

### Why can't you deliver the PDF function by Monday?

Our work-around is to render each chart, table and block of text as an object, and then provide logic that respects page breaks.  This requires multiple rounds of trial-and-error testing to "tune" the app to render the page correctly.  This takes much time.  When the Sim UI constructs the tt1-3 reports, it takes data from the Sim UI and renders an infinite-scroll web page.  The user is able to scroll the mtl.how/menu, team data and charts seamlessly from beginning to end. However, when the page is rendered to a PDF, the PDF driver renders the entire page at once.  Then it divides the pages based on the printer's format settings (i.e., 8.5 x 11), and often divides the pages **right in the middle of the graphs or tables**.

**Comment by lijenn** [comment]
Thanks @jamesmrollins, sounds like we are still ready to test on Monday and have the tt Admin (without the PDF feature for the reports) and Team Setup will be ready in Prod on Tuesday. I'll help edit the documentation in your pull request.

I think it's fine to move forward without the tt report's PDF feature on Tuesday due to the page/line break issue cutting off graphs/tables.
Admin and Facilitators will still be able to see the report output and we don't need tt2 until Session 8.

**Comment by lijenn** [comment]
Discussed HQ 4/13:
Can still train using the PDF Function, the export of will just have graphs and tables cut off. 
But this will be fixed mid-late next week. We will still meet the need for the export on 5/26.
