### ISSUE TITLE
wk2_june_epic_story7: Task Develop mtl blue and red tt3 report

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#1962]
Develop tt blue and red tt report:

- [ ] Find a p-chart program object that can be formatted to specification.
- [ ] Add p-chart selection to tt Admin popup.
- [ ] Place chart in tt 3 report.

**Comment by hnorthcraft** [comment]
#adjudicate_memo Heather attempting best estimate at SP.
