### ISSUE TITLE
wk2_may_epic: BUG Investigate Team Data for R21 Team 3

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#1963]
## Facts
- Team data in the Team 3 Team Data xlsx file does not align with the Team Data reported in the tt3 report.
- James went back to the SharePoint to investigate the existence of other Team Data files.  There is an older May team data, but it does not have data that aligns with the tt3 report.

## Suggestions
- Attempt to locate the appropriate Team Data file.
- Reverse engineer the team data table from the tt3 report.

**Comment by staceypark** [comment]
@jamesmrollins were you able to find the team data file you need in the TeamPSD folder?

**Comment by jamesmrollins** [comment]
@staceypark no, I do not have access to that folder.

**Comment by staceypark** [comment]
@staceypark will look for the file & will work @jamesmrollins to figure out permissions to the TeamPSD folder

**Comment by staceypark** [comment]
@staceypark sent one more ModelParams file to @jamesmrollins 5/10.
If that one doesn't work either, we will not pursue trying to recreate the data any further, and instead focus on explianing how the sim helped the r21 teams, as the teams will likely not be wanting to re-experiment with 3 year old data.

**Comment by staceypark** [comment]
@jamesmrollins I think the rest of the conversation and work for this is reflected in #1965 so Im going to go ahead and close this
