### ISSUE TITLE
wk3_may_epic:  QA: TEST Review Analysis of r21_psy_jccp

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#1965]
Review analysis of r21_psy_jccp

- [x] Are variables selected for comparison correct?
- [x] Are the dynamics of the charts the same for each variable?
- [x] Are the QHFD comments correct and error free?
- [x] Is the experiment named correctly, following standard procedure?

See #1964 for issues related to PSY experiment inconsistencies.

**Comment by jamesmrollins** [comment]
Hi @staceypark @lzim.  I checked out the model parameters file sent by Stacey.  I renamed it "640a0_***_2021_05_14 and it is available for review in PROD.  There are a base case and three experiment runs available in the PROD Sim UI for this group with a 5/14 save date.  

## Findings

**The Team Data is markedly different vs. OSF in the Return-to-Clinic-Interval measurements (yellow).  I do recall a significant reorganization of the Team Data table in this area.  There are more minor differences in the numbers in other areas (blue).**

![image](https://user-images.githubusercontent.com/30132017/118316329-8a70fd00-b4ab-11eb-8172-c98f08792ba9.png)


**Chart results look more consistent with OSF tt3 report. While not an exact match, the range on the Y axis is more closely aligned and the curve behavior is also a closer match (see Supply Used by New Patients, Initiation Rate, Starting Rate, and Graduation Rate).**

![image](https://user-images.githubusercontent.com/30132017/118328966-4c7bd500-b4bb-11eb-9586-309a9dfe5f3a.png)

### PDF Report

[psy model analysis copy.pdf](https://github.com/lzim/teampsd/files/6481147/psy.model.analysis.copy.pdf)

**Comment by staceypark** [comment]
@lzim I think the places where the data is vastly different has to do with changes to data definitions and organizations as @jamesmrollins alluded to and the places in blue where the data structure didn't change and the actual values are similar, are close enough.

I would feel comfortable running with this file. Can I just confirm this with you?

**Comment by staceypark** [comment]
@jamesmrollins 
@lzim confirmed in 5/20 hq workgroup that yes, we can go ahead and use this model params file with this team.
