### ISSUE TITLE
wk2 jul_epic : md and bd file update and QA workflow story development

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1967]
Need for #1868 

Need to identify mapping/indexing of all files and the standardization of existing resources. 

### Check off requirements to verify progress through feature_tracker.
- [ ] 1. **DEFINE in work_breakdown**
  - [ ] a. **what & why** - **written definitions of requirements** in a **numbered checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** requirement definitions an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 2. **DESIGN** in **operations_to_do** and **research_to_do**
  - [ ] a. **what & why** - **_MVP_ of design** of requirements in a **algorithm map, wireframes or design** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** design **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 3. **DEVELOP** in **under_development** - "frozen"

  Task Cards:
  #
---
- [ ] 4. **TEST in functional_test**
  - [ ] a. **what & why** - **TEST requirements** using **testing_checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** via TEST **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 5. **PROD in done**
  - [ ] a. **what & why** - **_DOCUMENT_ feature** using **document_tracker** for the **5 D's.** 
  - [ ] b. **date & who** -  **DELEGATE**
    - [ ] **describe_learners** [Jenn & Rita]
    - [ ] **detail_facilitators** [Jane & Debbie]
    - [ ] **document_team** [Anthony]
    - [ ] **disseminate_scientists_va** [Anthony]
    - [ ] **depend_products** [hq & ees]
  
  Task Cards:
  #
---
- [ ] 6. **closed** - fully documented, trained and ready for the next release.

**Comment by staceypark** [comment]
hq workgroup 5/6:
Current SEE & SAY files are standard to our principles and will **not** change.

@jamesmrollins - can you detail:
1. What common errors you're experiencing and if there are any actions we can implement to counter those? (Please provide screenshots)
2. A concrete example that demonstrates what you mean by "non standard". Can you describe a use-case that we could imagine would work with the implementation of GH actions?
- a use case of replacing the word "team" is not something we imagine being able to tackle with GH actions without heavy programming or heavy human-involvement.
- current use cases we have open from GH Issues are #648 (affects Session 5 - first team 5/25), #1868 (affects Session 1)
3. How is the "index" going to be implemented? Is it going to be a **yaml** file (how we know GH actions already work)

**Comment by jamesmrollins** [comment]
Hi @staceypark.  FYI @lijenn 

I put a thumbs up to indicate I have read your post.  But, I really don't know how I can do what is being described.  For example, with #648, I don't know what the task is.  Is it taking a novel phrase explaining Floor Counts and placing exactly where it should go in the see and say guides?  If so, I'm not sure we know how to do that.  

Even the index idea is thinking out of the box - but I really don't know how we would do it. . . . 

Most of what I have implemented regarding actions have been pulled off the shelf.  The actions in many cases are coded in json and the yaml file just provides the execution order and variables that instruct the action.  I have looked several times for actions that approximate what we are doing with not much luck.

I look forward to brainstorming with you.

**Comment by staceypark** [comment]
@branscombj @dlkibbe 

#648 #1868 & #1967 
Dependent Issues that need to be addressed w/GitHub actions.

Sim UI Workgroup - Can Jane &/or Debbie attend Sim UI next Wed 5/19 @6:30pm Eastern?

- Reviewing how the current GH Actions work and resolving those open issues soon, will be key to prevent an accumulation of these issues.
- p-charts change in tt3 (need this over the summer).

**Comment by dlkibbe** [comment]
@staceypark @branscombj I can attend the meeting and will take notes. I need to get back into and work in the sim UI before then just to refamiliarize myself.

**Comment by lzim** [comment]
**Discussed at 5/19/21 Support Workgroup Meeting**

**Current GitHub Actions**
1. **Markdown Editor**
- uses standard rules (up to 48 can be implemented)
- titles
- remove extra spaces
- very sensitive
- if they don't follow the Markdown style guide, it will alert you to the lack of standardization.

**_Need/Next steps:_** There are not enough rules in our Markdown style guide or GitHub Actions now, to address #648 & #1868.**

2. **Spellchecker**
- Has a dictionary
- Very effective at catching spelling errors.

3. **Find and Replace**
- Limitations:
- Can only find an instance of a word (e.g., "aggregate")
- But, can't pay attention to where it is in the sentence, or usage context.

**Comment by jamesmrollins** [comment]
GitHub Actions - use case

#648 - Suicide Prevention Floors
#1868 - Session 1 say guide edits

These may have up to 8 edits in several other .md files on the mtl repo.

- What is the current state of our GitHub Actions for addressing these edits?
  - .md editor 
  - spell checker
  - find-n-replace
- What are common errors?
  - Using these three actions, are there errors that can be remediated with another action or training/policy?
    - Consider revisiting .md guide to add in the .md editor rules.  Although we want to avoid creating additional documentation.
    - Do we want more rules to be enforced?  Evaluate the rule list.
    - Action processes are available for use and documented in TeamPSD manual.
    - Most people don't know the action branches exist.  
    - 
- The lack of standardization and indexing is making it hard to close out issues.
  - 
- What can realistically be addressed with technological automation?

**Comment by lzim** [comment]
Decision: Bump the follow-up on this #1957 to wk2 jun_epic Sim UI.

**Comment by staceypark** [comment]
Closing this as it is scoped in #2125
