### ISSUE TITLE
wk2 may_epic Bug: Data in Viz tabs in Master Data UI file 

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1969]
@anazariz While looking at the latest master data ui file to prep for wk1 may_epic on Wed. May 6 at 8:30 am Pacific:

1) We noticed that the Viz tabs in the Master Data UI file already has data.
We did not expect to see any since there is no patient level data in the Data tabs, but there are still visualizations and data in the tables.
2) For this team/facility's Master Data UI file, it also had the wrong data from another team/facility when we looked at the divisionname filters.
3) Can you confirm if Viz tabs should even have data in the Master Data UI file at all?

Thanks!
FYI: @lzim @staceypark

**Comment by anazariz** [comment]
@staceypark, the implementation of an initialization routine for Data UI includes resetting the PIVOT tables and PIVOT charts.  While this task in itself is not overly complex, there are numerous other routines and modules that can potentially be impacted (and break). So based on that I am estimating 16 points to allow for a lot of Unit Testing.

**Comment by staceypark** [comment]
#1969 - URGENT priority for @anazariz   for all the co-facilitator prep this week, as all the teams are wrapping up their Data UI phase.

**Comment by staceypark** [comment]
closing this since it passed testing in #1996 and #1995
