### ISSUE TITLE
MTL Live Guide Session 1

### ISSUE THREAD

**Issue by dlkibbe** [lzim/teampsd#197]
Edit needed to characteristics of positive learning experience.
Phrase below needs to be completed.

"The learner had the support...."
@staceypark

**Comment by lzim** [comment]
Thanks @dlkibbe this is a pull request not an issue!
Please open a pull request to make the requested edit to complete the phrase.

@staceypark and I will review all pull requests and merge with master.

Thanks again!

Lindsey
FYI @branscombj
