### ISSUE TITLE
Due 5/13 BUG: Sim UI and MTL Menu - Sign In Loading Time

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1970]
Identified by @hmarcia 

After signing into mtl.how/sim, the Sim UI on either Edge or Chrome taking an abnormal amount of loading time (doesn't seem to end up loading at all).

We have troubleshooted by:
Clearing the cookies and cache, closing the browsers afterwards (have also tried leaving the browser up after clearing cookies and cache), and trying again starting from the login page.

Are there any other solutions to try or a fix that could address this loading time issue?
@lijenn was not able to re-create this issue, either on Citrix or the GFE laptop in the same browsers.

Screenshot:
![image](https://user-images.githubusercontent.com/59668647/117490104-3c944c00-af23-11eb-9c87-c17505c42be9.png)

FYI @staceypark

**Comment by jamesmrollins** [comment]
Hi @lijenn and @hmarcia .  Is the issue persistent?  Meaning, is @hmarica still having the loading issue?  If so, it may be helpful to open the inspection screen by right clicking in the browser window, and opening the "Console" tab.  Take a screen shot of the panel and post here.  That may help me determine if this is an internet traffic issue or other.  

## Right Click in browser window and select "inspect"

![image](https://user-images.githubusercontent.com/30132017/117491504-25565e00-af25-11eb-9950-45561510610d.png)


## Select console tab

![image](https://user-images.githubusercontent.com/30132017/117491647-52a30c00-af25-11eb-89e3-f94f103b45e7.png)

## Take a screen shot with clipping tool

![image](https://user-images.githubusercontent.com/30132017/117491736-6e0e1700-af25-11eb-90d3-fa8ff60470cb.png)

**Comment by hmarcia** [comment]
Thanks James!  here is what I found.

![image](https://user-images.githubusercontent.com/50675495/117500133-32d20f00-af4a-11eb-8e0d-0b88149d54b3.png)

**Comment by hmarcia** [comment]
oops, forgot to say @jamesmrollins to notify you, James.  Here is what I found  (and thanks again @lijenn 

![image](https://user-images.githubusercontent.com/50675495/117500457-aa07a300-af4a-11eb-91e0-ba47a66eea92.png)

**Comment by jamesmrollins** [comment]
Thanks @hmarcia !  That is very helpful.  I will forward to Forio and see what is up.  Thank you.  James

**Comment by lijenn** [comment]
Hi @jamesmrollins, there's definitely something going on with the loading time for some MTL Learners and Facilitators (i.e there has been at least a handful who experience the long loading period, I'm unable to re-create this and it doesn't seem like its a cookie/cache issue).

Let us know what Forio says :thinking:..this might be problematic once more teams go into Session 4 for MTL Menu and the remaining SIM sessions.

**Comment by jamesmrollins** [comment]
@lijenn back to forio with you feedback.  I will report when I hear something.  Regarding user error, I want to get a more nuanced run-down, because I may be able to design in some features to prevent that, or at least provide more information to the user about what is going on.

**Comment by jamesmrollins** [comment]
Hi @lijenn .  Although I have not really gotten a technical answer from Forio, they have indicated that indeed they were having some issues with the server side of Epicenter.  However, the errors we showed them did not jive with what they thought was going on with their back end.  

This bug was due by 5/13.  I imagine this was to support training.  Did you encounter any other problems?

**Comment by lijenn** [comment]
Hi @jamesmrollins, no other problems, it's particularly the loading time for the MTL Menu currently...let me see if anyone else on the core team gets this problem and see if I can provide a console report.

Yes, it was due as we wanted to support training but also ensure no one Learner encounter's these long loading times...let me get back to you on providing a console report specifically for MTL Menu.
