### ISSUE TITLE
wk3 may_epic: Pre/Post Emails - Remove Facilitator block and Add Team Vision

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1977]
Proposals from @branscombj: 
1) Remove the Facilitator block after Session 2 (if there is a sub, we'd add it to the top of the email in an open field text to let Learners know) - Would be easier to track the content in the email without having to jump over this block once Learners are familiar with their Facilitators.
2) Add the Team Vision - Helps to remind the Facilitators and Learners to refer back to the Team Vision.
3) Add a link to MTL Video

Thoughts? @lzim @staceypark @dlkibbe 

FYI This would require an edit to our email templates for the Dynamics @hsnyder2 @apisano0920 

--------------
**Current Template:**
![image](https://user-images.githubusercontent.com/59668647/117873947-3f5dac80-b255-11eb-9ed2-4d0ea098c5ad.png)

--------------
**With the above edits: The Team Vision will be on 1 line and the Do/Done boxes will be parallel in length, just doesn't showing up in GitHub.**
![image](https://user-images.githubusercontent.com/59668647/117874781-4802b280-b256-11eb-885e-1e4010555168.png)

**Comment by branscombj** [comment]
> Proposals from @branscombj:
> 
> 1. Remove the Facilitator block after Session 2 (can add it back when for substitutes) - Would be easier to track the content in the email without having to jump over this block once Learners are familiar with their Facilitators.
> 2. Add the Team Vision - Helps to remind the Facilitators and Learners to refer back to the Team Vision.
> 
Thank you @lijenn for entering this! Minor amendment: I wouldn't recommend putting the block back in when there's a sub; only if one of the ongoing facilitators has to change for some reason. We'll give a verbal/email (text at top) heads up about a sub where possible, but I expect teams will take an occasional sub co-facilitating with one of their regulars in stride.

**Comment by hsnyder2** [comment]
Sounds like the discussion here is what Pre and Post emails look like and how the content is organized/prioritized.  What would help the D365 implementation effort immensely is to get an example of the final version where someone has put red boxes around the content that needs to be "dynamic" -- ie. driven by data in D365 that's configured for a Team (dates, the named facilitators and/or their pics,) -- vs content that doesn't ever change (e.g. is "static").  Hope that makes sense.

**Comment by hsnyder2** [comment]
> @hsnyder2 Yes, that makes sense to me! Two follow-ups:
> 
> * Can we also identify a section that is customizable in real time - a field in the interface where facilitators or HQ can enter free text (2 sentences max, I'd estimate) that gets plugged in to a certain part of the email?
I'll have to check w @apisano0920 

> * Also, I think what I'm floating about the facilitators section of the email is if folks would be ok omitting or truncating it (dropping bios and pics) from the email templates after the first ~4 emails. Each of the 24 templates is a little different, so this would be a slight reconfiguration of the last ~20.
Yeah, we'll have to see how each of the 24 are different to ID how many actual templates are needed.

**Comment by apisano0920** [comment]
I already have an example of the this from Jen.

Arlene R. Pisano

Senior Application Developer
I4DM
8227 Cloverleaf Drive, Suite 312
Millersville, MD 21108
410-846-9198

From: hsnyder2 ***@***.***>
Sent: Tuesday, May 11, 2021 8:40 PM
To: lzim/teampsd ***@***.***>
Cc: Pisano, Arlene R. (Liberty IT Solutions) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [lzim/teampsd] wk2 may_epic: Pre/Post Emails - Remove Facilitator block and Add Team Vision (#1977)


Sounds like the discussion here is what Pre and Post emails look like and how the content is organized/prioritized. What would help the D365 implementation effort immensely is to get an example of the final version where someone has put red boxes around the content that needs to be "dynamic" -- ie. driven by data in D365 that's configured for a Team (dates, the named facilitators and/or their pics,) -- vs content that doesn't ever change (e.g. is "static"). Hope that makes sense.

-

**Comment by lijenn** [comment]
@apisano0920 I believe the two changes we are thinking of will slightly affect the example i gave you before.
1. We want to add an open text field to the top of the message (before the Session logo and the Veteran image that links to a video) in addition to the example I gave you. 
2. And we are deciding on possibly removing the Facilitator field after the 4th email.

Once I gather some more feedback from others. I'll post an updated example here.

**Comment by lijenn** [comment]
Additional proposal: Add a link to the relevant MTL Video for Learners that are not able to attend a Live meeting.

**Comment by lijenn** [comment]
Discussed at HQ workgroup 5/20, @lijenn to make the following edits:
- [ ] Agree w/moving facilitator block out of the Done/Do and put at the bottom after the done/do review.
- [ ] Remove facilitator block after we complete the PARTNER phase, starting w/BUILD
phase, which would be session 5 pre-.
- [ ] Agree w/keeping the team vision at the top of the pre/post emails for All emails between the session info/VAPOR video and the "We decided."
- [ ] After the, "Attendees...have been confirmed..." sentence, it would say, "Missed the team meeting? You can watch the session X video for CMEs/CEUs on TMS too."
- [ ] Agree w/keeping the team vision at the top of the pre/post emails for All emails between the session info/VAPOR video and the "We decided."
