### ISSUE TITLE
wk3 may_epic: GitHub Pages/Renderbook Actions - Large File Error

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1985]
Issue: Limited file storage error for Renderbook Action for the manual:
![image](https://user-images.githubusercontent.com/59668647/118493514-0ea6c880-b6d6-11eb-81f0-8701cbc639bb.png)
Action's output:https://github.com/lzim/mtl/runs/2597802975?check_suite_focus=true

Recommend testing this Potential Solution using Git Ifs for Large File Storage (test it in a forked repo, will need a copy of the current GH-pages branch in lzim/mtl):
- context: https://docs.github.com/en/github/managing-large-files/versioning-large-files
- https://sebastianengel.medium.com/file-abc-xyz-exceeds-githubs-file-size-limit-of-100-00-mb-git-large-file-storage-to-the-rescue-44334a420aef
- https://stackoverflow.com/questions/33330771/git-lfs-this-exceeds-githubs-file-size-limit-of-100-00-mb

FYI: @jamesmrollins, is this something you or DEV could work on or at least test the possible solution?

**Comment by lijenn** [comment]
Update: Not sure if Git Large File Storage will work for GH Pages....[source](https://docs.github.com/en/github/managing-large-files/about-git-large-file-storage)
![image](https://user-images.githubusercontent.com/59668647/118498028-752de580-b6da-11eb-99b8-f9984aef0bbb.png)



FYI: @jamesmrollins

**Comment by jamesmrollins** [comment]
Hi @lijenn @staceypark .  Since @lzim decided that printed outputs are no longer necessary, can we close this issue?

**Comment by lijenn** [comment]
Yes I believe so @jamesmrollins. In the case that someone does what a few pages printed out, I think we could just have people do the following:

1. Go to the chapter or section that want to print.
2. Ctrl/Command + A
3. Right click and select "Print" and select the pages they want to print from the manual.

That way anyone can save the pages they want as a pdf and print it out afterwards. 

Closing this card for now.
