### ISSUE TITLE
wk3 may_epic: team data table upload fail (not a bug, need to add to backend)

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#1986]
After uploading team data, SIM UI is not able to find the file: FileNotFoundError pops up<br><br>Will include screen shots<br><br><br/><br/><br/><br/><br/>![image](https://s3.amazonaws.com/epicenter-asset/production/va/va-psd-sim/1621259880739196234_img0.png) <br/>![image](https://s3.amazonaws.com/epicenter-asset/production/va/va-psd-sim/1621259880739491891_img1.png) <br/>![image](https://s3.amazonaws.com/epicenter-asset/production/va/va-psd-sim/1621259880739767540_img2.png) <br/>![image](https://s3.amazonaws.com/epicenter-asset/production/va/va-psd-sim/1621259880739473282_img3.png) <br/>

**Comment by staceypark** [comment]
@MattMoore2 
This is not a bug. The team data table needs to be uploaded in the backend for it to work on the frontend, where you tried to call the file. 

@jamesmrollins @lijenn @staceypark will get the team data table file for st. george uploaded ASAP so you can have it ready to use for tomorrow's team meeting and let you know on this issue.

We will train on the function and share documentation for the team data table upload & team management functions tomorrow 5/18 during the facilitate_workgroup meeting.

**Comment by branscombj** [comment]
Thank you @staceypark and @jamesmrollins ! Tomorrow @MattMoore2 and I have our inter-session prep for S05, team meeting next week. If the new feature we previewed last week is in place by tonight, I can upload the team data file to the backend, right?

**Comment by jamesmrollins** [comment]
Hi @branscombj and @MattMoore2, I will be adding this file to your menu here in a minute.  **Please do not add anything into the backend (Epicenter) because we are using CI/CD for our Sim UI.** This means there is a GitHub repo that has the contents of the Model Folder.  If you directly update Epicenter, it will be overwritten when we push code to Epicenter from GitHub.  When I finish this task, I will indicate here in this thread and will email you.  Thanks! James

FYI @staceypark @lijenn

**Comment by branscombj** [comment]
Got it @jamesmrollins ! Will await word and 🙏 thanks!

**Comment by MattMoore2** [comment]
Got it as well!!  THANK YOU!!!

From: branscombj ***@***.***>
Sent: Monday, May 17, 2021 8:57 AM
To: lzim/teampsd ***@***.***>
Cc: Moore, Matt ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [lzim/teampsd] wk3 may_epic: team data table upload fail (not a bug, need to add to backend) (#1986)


Got it @jamesmrollins<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjamesmrollins&data=04%7C01%7C%7Cd9b93bfa25e74ad9389008d9194c5cb0%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637568638025699710%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=HxVyBennjGNY6ti9foNgyekKzNviTBGmb7w16GwEsUU%3D&reserved=0> ! Will await word and 🙏 thanks!

**Comment by jamesmrollins** [comment]
Hi @branscombj and @MattMoore2 - You should be able to navigate to the team's home page and begin work.  Let me know immediately if you have any issues.  Thanks, James

FYI @staceypark @lijenn

**Comment by branscombj** [comment]
> Hi @branscombj and @MattMoore2 - You should be able to navigate to the team's home page and begin work. Let me know immediately if you have any issues. Thanks, James
> 
> FYI @staceypark @lijenn

I don't see our St. George team as an option in my Facilitators Dashboard:

![image](https://user-images.githubusercontent.com/29778290/118522570-357ef200-b70a-11eb-869a-94ff4a75949e.png)

**Comment by jamesmrollins** [comment]
@branscombj  - One moment please. . .

**Comment by jamesmrollins** [comment]
@branscombj - Which login did you use?  If you used your @gsu address, that is the reason.  You are currently a facilitator in that team as @va.gov

**Comment by branscombj** [comment]
> @branscombj - Which login did you use? If you used your @gsu address, that is the reason. You are currently a facilitator in that team as @va.gov

Ah, that must be it! Now, I wonder what my password is for the @va login.... ?? @staceypark can you help with that?

**Comment by jamesmrollins** [comment]
I just added your gsu address as a facilitator to that group.  It should show up on your menu.

**Comment by jamesmrollins** [comment]
@branscombj - I just sent an email with updated passwords for both accounts.  An explanation is in the email.

**Comment by MattMoore2** [comment]
All working! Thanks for fixing backend issues.  😊

From: James Rollins ***@***.***>
Sent: Monday, May 17, 2021 9:39 AM
To: lzim/teampsd ***@***.***>
Cc: Moore, Matt ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [lzim/teampsd] wk3 may_epic: team data table upload fail (not a bug, need to add to backend) (#1986)


@branscombj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbranscombj&data=04%7C01%7C%7C57485751d3694b8b45d608d919525959%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637568663756282792%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SqxsRU2Z3ymMvDuSgAiEY8eHBola9h%2B%2FKdVIikcjF%2FQ%3D&reserved=0> - I just sent an email with updated passwords for both accounts. An explanation is in the email.

**Comment by jamesmrollins** [comment]
FYI @branscombj @MattMoore2 @lijenn @staceypark .  We found a naming error regarding the team data file.  It had capitalizations in the model "SP", when all should have been lower case "sp."  All are corrected from the Data UI to the Sim UI.

Thanks,
James

**Comment by branscombj** [comment]
@MattMoore2 does not have any worlds to choose from in his facilitator dashboard except St. George Team. How can we get him an IND world @staceypark @lijenn @jamesmrollins ? Thanks!

**Comment by lijenn** [comment]
@MattMoore2 You should see a matt_moore_ind world now!

We are currently working on seeing if there's an easier way to get all facilitator's their own IND world at once as we're creating them separately right now. Keep you all posted.

**Comment by MattMoore2** [comment]
Confirmed!   I now have an ind world option.  😊

From: Jennifer Li ***@***.***>
Sent: Monday, May 17, 2021 1:43 PM
To: lzim/teampsd ***@***.***>
Cc: Moore, Matt ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [lzim/teampsd] wk3 may_epic: team data table upload fail (not a bug, need to add to backend) (#1986)


@MattMoore2<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMattMoore2&data=04%7C01%7C%7C510e2cf5883241c3ec2708d919745a60%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637568809807794763%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZRFKYG8UgkyRXONbFReM0Y%2BgIAVTbxKq%2BFvB3NXy1Y8%3D&reserved=0> You should see a matt_moore_ind world now!

We are currently working on seeing if there's an easier way to get all facilitator's their own IND world at once as we're creating them separately right now. Keep you all posted.
