### ISSUE TITLE
wk3 may_epic: SIM Aggregate - Team Data Table read in incorrectly on SIM 

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#1992]
From Intersession Prep Tues. 5/18 from 6:30a Pacific with @branscombj @MattMoore2 : <br><br>

SIM UI - Aggregate  

Team Data Table file from mtl.how/data is being read in incorrectly on the table in the Sim.The numbers are being pulled from the correct file, but the numbers are going into the wrong sections in the table on the Sim here.<br/><br/><br/><br/><br/>![image](https://s3.amazonaws.com/epicenter-asset/production/va/va-psd-sim/1621351090596272486_img0.PNG) <br/>

**Comment by jamesmrollins** [comment]
@lijenn.  Please email me the Team Data file so I can troubleshoot ASAP.

**Comment by jamesmrollins** [comment]
@anazariz @lijenn @staceypark @branscombj @MattMoore2 

## Problem Diagnosis

The format of the Team Data file has been changed to add a header row to the Agg tab.  This has thrown off the cell addressing in the model by one row.  The other module tabs are consistent between dated versions. See exhibits below.

**From legacy Team Data file 640a0_**_****_2019_04_14.xlsx**

![image](https://user-images.githubusercontent.com/30132017/118685658-19d22500-b7b8-11eb-8be2-a7fe4b0e24fc.png)

**From current Team Data File 660gg_**_******_****_*******_**_2021_04_26**

![image](https://user-images.githubusercontent.com/30132017/118685969-6a498280-b7b8-11eb-8d4c-03543f6f1813.png)

**From current Model agg_i_v15_2021_02_14.mdl - "Data_CC_Appointment_Supply_(median)"**

![image](https://user-images.githubusercontent.com/30132017/118686203-a5e44c80-b7b8-11eb-96bd-63d59611c660.png)

## Corrective Action

### Immediate
Adjust the 660gg_ *.* excel file by removing the header row and saving to epicenter instances. 

### Long Term

1. Correct the Team Data creation algorithm in the Data UI to produce the proper format - or - 
2. Correct the model data variables to address the proper cell in the new Team Data format.  This would require updating 77 data variables in the model to the correct address in the new Team Data format, plus testing.

**Comment by branscombj** [comment]
wow @jamesmrollins  you're sharp!

**Comment by jamesmrollins** [comment]
Hi @branscombj and @MattMoore2.  I have corrected the file you are using for 660gg in Epicenter.  So it should now work properly in your team data table.

**Question:  Did you add the header in?  We don't know where the header came from.**

FYI @staceypark @lijenn @anazariz

**Comment by MattMoore2** [comment]
Oh!  I do recall when reviewing data once, that header was copied from the bottom and pasted to top to better review data. However, I don't believe that was saved...  Jane, do you recall this?

From: James Rollins ***@***.***>
Sent: Tuesday, May 18, 2021 10:28 AM
To: lzim/teampsd ***@***.***>
Cc: Moore, Matt ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [lzim/teampsd] wk3 may_epic: SIM Aggregate - Team Data Table read in incorrectly on SIM (#1992)


Hi @branscombj<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbranscombj&data=04%7C01%7C%7C34d05727176e43ef9f1608d91a225cc2%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637569557166250313%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xXEntWW2dBk46XeMP83FSVZaeZRsZ1dmquKUByBEeiE%3D&reserved=0> and @MattMoore2<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMattMoore2&data=04%7C01%7C%7C34d05727176e43ef9f1608d91a225cc2%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637569557166260277%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZvR%2Fw3jWxqBymE6uutdSPwxGO1sqDapsQbABeLTexlQ%3D&reserved=0>. I have corrected the file you are using for 660gg in Epicenter. So it should now work properly in your team data table.

Question: Did you add the header in? We don't know where the header came from.

FYI @staceypark<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fstaceypark&data=04%7C01%7C%7C34d05727176e43ef9f1608d91a225cc2%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637569557166260277%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ORwyPHpIaGQR9G5a%2FLb2%2Bk5BB%2F6lmgJrYhsMsGx6rpc%3D&reserved=0> @lijenn<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flijenn&data=04%7C01%7C%7C34d05727176e43ef9f1608d91a225cc2%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637569557166260277%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=KK6X5v9hqt657%2BeN8pifojrDU22JRTUrtqLhLaY3yh8%3D&reserved=0> @anazariz<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fanazariz&data=04%7C01%7C%7C34d05727176e43ef9f1608d91a225cc2%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637569557166270222%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=UxBdBY4kWIpjgXt7O7ztQY2uj2ip%2B2zsX97b7hXGFmc%3D&reserved=0>

-

**Comment by branscombj** [comment]
> Oh! I do recall when reviewing data once, that header was copied from the bottom and pasted to top to better review data. However, I don't believe that was saved... Jane, do you recall this?

🤦 OMG that’s what happened! I did that! Grrr – sorry for the detour, @lijenn @MattMoore2 @jamesmrollins @anazariz ! I will leave the data files alone from now on.

**Comment by branscombj** [comment]
@lijenn I just tried loading the most recent team data table filename in the sim and I still got the crazy numbers. Went back to dataui and the most recent file there still had the header on the agg tab. Removed it and re-saved. Can you load that in the back-end to the sim so it will upload correctly when we use that filename? I'm not sure why @jamesmrollins 's fix isn't working for me but eek.
