### ISSUE TITLE
simUI units

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#201]
In AGG, we found a few variables' output charts still showing incorrect units: as shown on attached, the ones we caught are Total Starting Any Service (showing as %) and Total Patients in All Services (showing as pts/wk). The fact that these are both cross-service variables makes me wonder if those are the ones that this is happening for while the single-service variables are correct - just wondering.
[2018_09_25_expandedoutputs_labels.pptx](https://github.com/lzim/teampsd/files/2416704/2018_09_25_expandedoutputs_labels.pptx)

**Comment by jamesmrollins** [comment]
@branscombj I will look into this and report it.  Thank you.

**Comment by jamesmrollins** [comment]
The variable "Total Starting Any Service" is a unique variable measured in pts/wk and is not dependent on the other variables for the units of measure information. I have reported the error and should have it fixed by tomorrow.

**Comment by branscombj** [comment]
Oh! The variable name sounds like patients - not pts/wk. Should we rename it, @TomRust @lzim ?
Total per Week Starting Any Service
Total Starting All Services per Week??

**Comment by lzim** [comment]
@branscombj 

@jamesmrollins and I just walked this through, and I don't think it warrants a change. Let's leave for now.

Thanks!
