### ISSUE TITLE
wk4 may_epic task: test #2001 (Data Table Files lower case)

### ISSUE THREAD

**Issue by anazariz** [lzim/teampsd#2010]
**test #2001 (Data Table Files name all lower case)** 

As testing of creating new Data Table is only possible on the actual SharePoint site, please go to Facility 640, test folder and do the test with the file DataToolFRE16_nevermore.xlsm. 

How to test:
- [x] Open the file and go to the "Control" sheet
- [x] Select a "Station", click "Get Clinic List" 
- [x] Go to ClinicSelection tab, select a few clinics, click "Get Patient-Level Data"  
- [x] When done, click "Get Clinic Data Table" 
- [x] When the form appears, give it an uppercase name
- [x] Go to the data table folder and make sure that the name is not in uppercase

**Comment by lijenn** [comment]
Thanks, this worked Ash! I'm continuing to test in the other issue card to test all the bug fixes together in #1995 
Closing this card.
