### ISSUE TITLE
wk4 may_epic task: test #2001 (Data Table Files lower case)

### ISSUE THREAD

**Issue by anazariz** [lzim/teampsd#2011]
**test #2001 (Data Table Files name all lower case)** 

As testing of creating new Data Table is only possible on the actual SharePoint site, please go to Facility 640, test folder and do the test with the file DataToolFRE16_nevermore.xlsm. 

How to test:
- [ ] Open the file and go to the "Control" sheet
- [ ] Select a "Station", click "Get Clinic List" 
- [ ] Go to ClinicSelection tab, select a few clinics, click "Get Patient-Level Data"  
- [ ] When done, click "Get Clinic Data Table" 
- [ ] When the form appears, give it an uppercase name
- [ ] Go to the data table folder and make sure that the name is not in uppercase

**Comment by lijenn** [comment]
Closing this card since this QA test is also now being tracked in #1996
