### ISSUE TITLE
wk1 june_epic: Team Data Table file, SPParams tab - Edit "Constant" language

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2014]
Identified on Mon. 5/24 prep by @branscombj @hmarcia @lzim 

@anazariz Can we change the language here in column c from "constant" to something like "Variable" or "Value" instead?

FYI: @jamesmrollins Would this edit impact how the data is read into the Sim in any way?

![image](https://user-images.githubusercontent.com/59668647/119399651-fe6e8a80-bc8d-11eb-9015-7ead7d10745a.png)

**Comment by jamesmrollins** [comment]
Hi @lijenn.  No, it should not affect the sim.  The only thing that affects the sim ui is when the cell address changes, such as by inserting a row or column.

**Comment by anazariz** [comment]
@lijenn 
Changed to Value.

**Comment by branscombj** [comment]
Thanks!
