### ISSUE TITLE
story 5 icebox june_epic: Master Data UI file, SPReferrals Tab - Add a "Get previous clinic selection" button

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2015]
Identified on Mon. 5/24 prep by @branscombj @hmarcia @lzim 

@anazariz Similar to the ClinicSelection tab, can we also add a "Get previous clinic selection" button here as well?
@lzim Also mentioned we may have had this feature previously in a past ver. of Nevermore (e.g. 14), can you help check?

I've mocked up how this addition could look like in the SPReferrals tab:
![image](https://user-images.githubusercontent.com/59668647/119401164-fc0d3000-bc8f-11eb-88e7-8b9c7d81702b.png)

**Comment by anazariz** [comment]
@lijenn,

Cc: @lzim @staceypark 

This feature never existed, at least as far back as I went, which was version 11 on 8/9/2019.

![image](https://user-images.githubusercontent.com/39805164/120341874-1f496800-c2ac-11eb-9c9b-195f44c6d66c.png)

Adding this feature requires coding. I will have to assess the estimate and get back to you.

**Comment by anazariz** [comment]
Button to be added - Estimate 21 points

**Comment by staceypark** [comment]
This is related to our legacy platforms and will not be relevant to PBI.
decided on 8/5 hq workgroup

**Comment by hnorthcraft** [comment]
#adjudicate_memo assigning 1 sp to reflect efforts (documenting feature and discussion)
