### ISSUE TITLE
wk3 june_epic: Master Data UI file, SPReferrals Tab - Remove default selection in Column E

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2016]
Identified on Mon. 5/24 prep by @branscombj @hmarcia @lzim 

@anazariz Can we remove the default selection here in column E to make it obvious to a Learner or Facilitator that they need to make a selection here? 
Currently, it defaults to "SMH":
![image](https://user-images.githubusercontent.com/59668647/119402011-26abb880-bc91-11eb-9f8a-e4505d9ff1fc.png)

Note: We also need to add PC/PCMHI to this dropdown, issue #1899

**Comment by dkngenda** [comment]
**Pop-up warning about the default selection:** 
"Confirm that you selected clinics that you refer patients to and not clinics who you receive referrals from."

**Comment by anazariz** [comment]
Work estimate 5 Points.

**Comment by anazariz** [comment]
@lijenn ready for testing. Test card will be created.
Cc: @lzim @staceypark 

**What was done:**

A blank selection item was added to the "SPReferrals" tab's E2 dropdown list. The blank is now the default when the workbook opens. 
When the "Create Team Data Table" button on the "ClinicSelection" tab is clicked with either "SP" or "All with SP" E2 dropdown selection and a blank E2  dropdown selection on the "SPReferrals" tab, the message "In the SPReferrals tab, confirm that you selected clinics that you refer patients to and not clinics who you receive referrals from." is popped up and the user is given a choice to stay on the current page (CliniSelection) or the SPReferrals page with the E2 dropdown already focused.
  
![image.png](https://images.zenhubusercontent.com/5e4c0724779eee67006fe6c6/08085457-3376-44f9-9a27-9a4789b6686d)

**Comment by anazariz** [comment]
This work has been completed. Its test card is [2050](https://app.zenhub.com/workspaces/team-psd-workspace-5e4ac9bd8d388dfba6d9aef5/issues/lzim/teampsd/2060).

**Comment by anazariz** [comment]
Closing this card after receiving OK from @lijenn  (on Teams).
