### ISSUE TITLE
wk2 june_epic BUG: Master Data UI file - Get name of last team data table created 

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2023]
Identified on Fri. 5/28 with Jenn testing the data ui files propagated on Fri. 5/21.

@anazariz In cell C4, it does not refer back to the name of the last team data table file that was created even though a team data table was created and saved into the team_data_table folder:
![image](https://user-images.githubusercontent.com/59668647/120086843-64488100-c097-11eb-8770-13aebabc3e03.png)

**Comment by anazariz** [comment]
@lijenn, I have completed the fix. Currently creating the test ticket.

**Comment by anazariz** [comment]
Test @2040 received a pass. Closing this ticket.
