### ISSUE TITLE
wk1 jun_epic bug_fix_test task: test #2014 (column header rename) and #2019 (Unable to create Team Data Table)

### ISSUE THREAD

**Issue by anazariz** [lzim/teampsd#2026]
**test #2014 (column header rename) and #2019 (Unable to create Team Data Table)** 

How to test:

The test Excel file "DataToolFRE17_nevermore.xlsm" is on the on-premises SharePoint, which is in Facility 640, "Test" folder.   
   
- [x] open the Excel file using the SharePoint's Edit mechanism 
- [x] on the Control tab, select a Station and click "Get Clinic List" 
- [x] on the SPReferral tab make sure that you don't see two sets of "Remove all" and "Add Selection" - the ones you see should be in column C   
- [x] on the SPReferral tab make sure that you can make a partial selection from "Clinic Name" column (just like you do in the "ClinicSelection" tab 
- [x] make sure you select "GMH" in the in cell E2
- [x] select some clinics
- [x] on the ClinicSelectiontab "SP" or "All with SP" in cell E2
- [x] on the ClinicSelectiontab select some clinics
- [x] on the ClinicSelectiontab click "Get Patient-Level Data
- [x] when that finishes, click "Create Team Data Table"
- [x] when that finishes, in Facility 640 (on SharePoint) inspect the folder Test/Test_Team_Data_Table/<what ever you called you file>
- [x] make sure that column header in the produced file says value (see bug #2014) 
- [x] if the file exists and the column says "Value", test is a PASS

**Comment by staceypark** [comment]
6/3/21 8:30am Pacific prep with Jane & Marcia
We used this team's prep (where the issue was first identified) to do the testing and it all passed.
