### ISSUE TITLE
wk2 june_epic: Master Data UI - Removal of Column G in dataDiag and dataHF 

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2039]
BUG found on SharePoint Online on Tues. 6/8:

Please make the following edits to the master data ui:
- [x] dataDiag tab -> delete Column G
- [x] dataHF tab -> delete Column G
We don't need "patientssn" in the Data UI File at all.

We provide L4 and if they've requested restricted access there are asterisks.

**Comment by anazariz** [comment]
@lijenn,  I have completed the fix. Currently creating the test ticket

**Comment by anazariz** [comment]
This item was completed (release 18). Test #2040 received a PASS. Closing this ticket.
