### ISSUE TITLE
wk2-3 jun_epic IIR ZIM0003 Annual Report due 6/14

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#2042]
- [ ]  @dkngenda will take a first pass by Thursday 6/10
- [ ]  @staceypark will take a second pass Monday 6/14
- [ ]  @lzim will submit Monday afternoon 6/14

include Jenn & David as new hires in report

These should be consistent with updates already provided to NIH, VA, IRB, DSMB, ClinicalTrials.gov and our MTL activities.

**Comment by dkngenda** [comment]
@staceypark 

Looks like I do not have access to view IIR annual report in RDIS. Below is the message I get when I click on it

![image](https://user-images.githubusercontent.com/66848852/121543561-02f9a980-c9d7-11eb-9f00-fb7d5a7120c7.png)
