### ISSUE TITLE
wk2 jun_epic crosswalk sow & deliverables 

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#2044]
crosswalk original SOW & deliverables to the people from TeamPSD who would do this on their contract (prior to Thursday MTL Hawaii) meeting

**Comment by lijenn** [comment]
Discussed 6/10 HQ wg:
- @lzim created a mtl_hawaii_samsha channel in VA Teams and added the file in the channel.
- @lzim sent an email to the TeamPSD members to the channel and sent a meeting invite.
