### ISSUE TITLE
wk4 jun_epic task: SharePoint online path correction/testing in Data UI & Facility files

### ISSUE THREAD

**Issue by anazariz** [lzim/teampsd#2050]
The SharePoint online path needs to be corrected in the Data UI & Facility files before the 6/25 go-live to allow for correct propagation of files.

**Comment by anazariz** [comment]
@lzim @staceypark @lijenn @dkngenda 
Made great progress today. I had successfully written Excel files from Excel on=premises to SharePoint online. The issue I had was with folder manipulation (via Excel on-premises in SharePoint online). I was finally able to created a trusted site (via the old Internet Explorer) and then create Windows mapping. Once the mapping was in place, I was able to use the regular folder manipulation techniques in Excel.  

- [x] wrote a file to SharePoint online from VBA in an Excel on-premises workbook
- [x] tested the existence of a folder in SharePoint online from VBA in an Excel on-premises workbook
- [x] created a folder in SharePoint online from VBA in an Excel on-premises workbook

**Comment by anazariz** [comment]
@Data UI has been modified and ready for testing.
- [x] tested the "Propagate" button click - with an actual Facility 
- [x] tested the "Create Team Data Table" button click (from the test folder)

Working on the Facility one.

**Comment by lijenn** [comment]
@lijenn has tested data ui and facility propagation to SharePoint online.
@staceypark will be testing the facility propagation in @2108.
