### ISSUE TITLE
wk5 jun_epic task: SharePoint online pre & post cutover

### ISSUE THREAD

**Issue by anazariz** [lzim/teampsd#2051]
**test the new SharePoint online pre & post cutover**

### This is not a bug test. It's a platform health check.

The first refresh took place on 6/7. It started at noon and took 4 hours.
The second refresh is scheduled for 6/18 4 PM PST and is the actual cutover to the new online SharePoint. 

Prep

- [ ] Send an email to the users and inform them that the SharePoint platform will not be available from 5 PM PST until Monday 6/21 12 AM. Please note that, while the on-premises platform cannot be put in READ-ONLY mode during the migration, it **CAN BE** (recommended) put in the READ-ONLY mode afterwards.  

**Prior to cutover**

- [ ] Let @anazariz know your preferred Facility to be propagated (Facility and Data UI) for your testing
- [ ] Inspect the platform prior to the cutover to make sure that things look OK
- [ ] Inspect the 2 propagated Workbooks
- [ ] PASS

**Post cutover**

- [ ] Inspect the platform after the cutover (Friday evening to Sunday) to make sure that things look OK
- [ ] Inform the SharePoint team to put the platform in READ-ONLY mode
- [ ] When everything seems ok, switch the short link during the weekend
- [ ] PASS

**Comment by anazariz** [comment]
Changed the date because we postponed the go-live date by 1 week.

**Comment by anazariz** [comment]
@lijenn, Please test with 640 on/after 6/22. That's give me time to finish my end of the work (on Monday since Friday is a holiday). Thx!

**Comment by lijenn** [comment]
Discussed Thurs. 7/22 HQ WG:

Closing since we believe we have everything migrated.
