### ISSUE TITLE
wk3 june_epic: Fix links in MTL Links in Sim UI

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2053]
I clicked on the More Info button at the top of the page and none of the links in the MTL Links section worked.<br><br/><br/><br/><br/><br/>![image](https://s3.amazonaws.com/epicenter-asset/production/va/va-psd-sim/1623415443804471181_img0.PNG) <br/>

**Comment by lijenn** [comment]
Thanks for identifying this @dlkibbe and @clairecollie! I've assigned myself to fix these links.
FYI @jamesmrollins that i'll be working on the links here in the SIM.

Note: @dlkibbe @clairecollie P**lease make sure to include your GitHub usernames and the date/time your prep session was in your bug report** so the team knows which co-facilitators to reach out in case we need more information on the bug :)

**Comment by jamesmrollins** [comment]
Hi @lijenn @dlkibbe @clairecollie 

The links do work (unless you are outside the VA domain for mtl.how/data).  However, its the icon that is associated with the link, not the line of text.  The text used to say, "Click the icon . . . " but was edited for brevity.  Perhaps we should add it back in for clarity?

**Comment by lijenn** [comment]
Awesome, thanks @jamesmrollins! So we should be seeing logos next to where each of the descriptions.
BTW I don't think we need the "Click to access online team meetings" one since each this would have be team tailored since every team has a different microsoft teams link, which I don't think we can tailor in the Sim.

**Comment by jamesmrollins** [comment]
Hi @lijenn @dlkibbe @clairecollie 
All are fixed and should work now.

**Comment by dlkibbe** [comment]
Sorry @lijenn - that's the downside of reporting the bug on the SIM UI - we didn't have that template to go by to make sure we put all the right information in report. Thanks for the quick fix @jamesmrollins and @lijenn
