### ISSUE TITLE
wk3 jun_epic task: test #2016 (SPReferrals Tab - Remove default selection in Column E), #2066 (ANDON: Cannot get Patient Level) 

### ISSUE THREAD

**Issue by anazariz** [lzim/teampsd#2060]
**test #2016 (SPReferrals Tab - Remove default selection in Column E2**

Note-#2066 was added to this test on 6/17.     

**How to test:**

The test Excel file "DataToolFRE19_nevermore.xlsm" is on the on-premises SharePoint, which is in Facility 640, "Test" folder.   
   
- [x] open the Excel file using the SharePoint's Edit mechanism 
- [x] on the SPReferral tab make sure that the dropdown E2 is blank when the workbook starts. Do not make a selection, but add a few clinics to make sure that the test criteria is triggered (i.e. with a blank E2 selection).   
- [x] on the ClinicSelectiontab select "SP" or "All with SP" in cell E2
- [x] on the ClinicSelectiontab select some clinics 
- [x] on the ClinicSelectiontab, click "Create Team Data Table"
- [x] you should see the message in the SPReferrals tab, "In the SPReferaal tab, confirm that you selected clinics that you refer patients to and not clinics who you receive referrals from.".  
- [x] When you click OK, you should be placed on the "SPReferral" tab with the E2 cell in focus. 
- [x] if that happens test is a PASS

**Comment by lijenn** [comment]
@anazariz Regarding #2066 since we have added it to testing:

When clicking the "Get Patient-level Data" button, only the Viz tabs (vizEnc, vizDiag, vizHF, vizMeas) show the data, but all of the Data tabs are empty.

**Comment by anazariz** [comment]
@lijenn 

Can I close this card as well as  [#2066](https://app.zenhub.com/workspaces/team-psd-workspace-5e4ac9bd8d388dfba6d9aef5/issues/lzim/teampsd/2066)?

**Comment by anazariz** [comment]
Closing this card after receiving OK from @lijenn (on Teams).
