### ISSUE TITLE
wk3_jun_epic_story8: QA_test_validate_pdf_report_output

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2061]
# Validate tt PDF Report Output

## Given
- A team that has completed mtl.how/menu webpages.
- At least one base case and one experiment, but not more than 10 experiments.
- Proper configuration in the tt reports setup function.

## QA Checks

- [x] Does when the PDF button is pressed, the system renders a PDF output without timing out.
- [x] If pop ups are blocked, the Sim UI presents the PDF as a download.
- [x] The report pages have a header with the tt logo, title of the report and the team's vision statement.
- [x] (For blue research branch) The footer of the report has a mtl Blue logo on the right-hand side.
- [x] (For red research branch) The footer of the report has a mtl Red logo on the right-hand side.
- [x] The graphics have proper aspect-ratio and are clear.

**Comment by lijenn** [comment]
Thanks @jamesmrollins, the PDF function is working great :)

1. Did notice the _MTL_ Blue & Red logos are getting cut off in the bottom right hand of the PDF file and in the pop-up if pop-ups are allowed:
![image](https://user-images.githubusercontent.com/59668647/122435690-11067780-cf4d-11eb-9395-1548ebbfce92.png)

2. Minor issue: Aspect-ratio works as in the graphs are not getting cut off and work, but any way we could improve the clarity/reduce the blurriness of the text & graphs, if possible?
![image](https://user-images.githubusercontent.com/59668647/122436442-ac97e800-cf4d-11eb-8c12-aba589875c32.png)

**Comment by jamesmrollins** [comment]
Thanks @lijenn for testing this feature.  The clarity of the screens and the graphics getting cut off is related to screen resolution.  

- [ ] Was this PDF rendered at 1920 x 1080?  Please verify or correct.

## Some Context
The PDF generator has to literally render a screen capture of each chart from the html, then arrange them on the output page so they don't get cut in two. So there are Quality differences between different machines based on resolution.  I thought we had gotten to the bottom of those!  Another issue with the Psychotherapy Module is we can't get the Sankey Charts to render properly.  

## Recommendation
- Let's promote this version to PROD.  That way there is at least a 85% solution available.
- We will continue to refine for release next time we update.

**Comment by lijenn** [comment]
Agreed on the recommendation. 
Want me to open a a bug for the Psychotherapy Module for rendering Sankey Charts and one for the logo issue above?

**Comment by staceypark** [comment]
@jamesmrollins in regards to pulling a report from a team that has experiments, I tried it with the 100a1_abc_teama_team that we use for testing, and I didn't get any experiments to select.

![image](https://user-images.githubusercontent.com/31089501/122488181-cb1fd280-cf91-11eb-9ad9-a72678e93679.png)

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire.  See issues above related to PDF outputs for 1920 X 1080.  Still some issues with rendering.  Please promote to PROD after you take a look.

@lijenn.  Don't do a bug report on the Sankey, since it isn't an established feature yet.  I will likely open a feature card to it doesn't slip through the cracks.

**Comment by jamesmrollins** [comment]
@hirenp-waferwire  Please explain why these experiments below are not available.  

They can be seen from the panel shown below on the Home screen.  However, they don't show up in the session run screen.  @staceypark , my thinking is the mar_2020 are out-of-date because of the variable renaming that we did last year.  I ran a new base case, and the experiments showed up ok (see highlight in second screen capture).  

![image](https://user-images.githubusercontent.com/30132017/122659365-52a14900-d12c-11eb-8abe-5512ac949bb1.png)

![image](https://user-images.githubusercontent.com/30132017/122659386-9f851f80-d12c-11eb-9ba6-b16377ad7a7e.png)

**Comment by lijenn** [comment]
@jamesmrollins and @lijenn reviewed Prod outputs and looked okay!
