### ISSUE TITLE
wk2_june_epic_bug: AGG Chart Results Not Showing Correctly

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#2063]
**1. Add description: SimUI Results - Multiple Oddities** 
1. Wanted to Compare Services for a BC run in AGG but a) don't find any options in the dropdown menu except ones tied to a single service (CC Appointments; MM Appointments; etc) - nor do multiple services show up on the charts with one of those is selected - even though checking the Compare Services radio button does make the legend for the different services come up on the charts.
It seems like there are several issues, which you can see in these two screenshots:
2. The color of the trendline on the output charts does not correlate to the legend.
3. The value at 2 years shown in the trendline, e.g. Adjunctive Appointments, does not correspond to the value in the Appointments stock in the diagram.
4. Actually the value is the same for all the variables selected: 6.
5. The units do not match the variables, and they aren't even consistent for the same variable for different services (Adjunctive-Actual Hours Available for Service = weeks; CC-Actual Hours Available for Service= patients).

4. << Paste screenshots here>>
 
![image](https://user-images.githubusercontent.com/29778290/122114439-45652100-cdf1-11eb-83cf-b9d71bc1f850.png)

![image](https://user-images.githubusercontent.com/29778290/122114078-e0113000-cdf0-11eb-8d8a-64bef0853292.png)

**2. Click on the right:**  
i. **Pipelines** - prioritize in a TeamPSD (& Workgroup) pipeline  
ii. **Assignee** - assign to an individual team member producing work for the issue  
iii. **Label**- assign workgroup (lead) responsible for tracking the task  
iv. **Projects** - assign to domain-specific TeamPSD tracker (issues, features, document, manuscript, team)  
v. **Milestones** - select monthly sprint milestone within the workgroup   
vi. **Estimate** - Estimate task in complexity points   
vii. **Epics** - assign to team-wide epic and TeamPSD master plan project  
iix. **Releases** - assign to key team release grouped with other relevant issues  

**3. If you anticipate that your **issue card** or **bug card** will have **dependencies** these can be added once the issue has been submitted.   
ix. **Add dependencies** - assess for and add dependencies *blocking* & *blocked by* this issue

**Comment by jamesmrollins** [comment]
Hi @branscombj - I need to see this.  Is this in your _ind world?  Or is it in a _team?

**Comment by branscombj** [comment]
@jamesmrollins When I re-ran a bc just now the results looked MUUUCH more like it! You must've gotten to the bottom of whatever it was? Thank you so much! It's especially great that you could get to it quickly because our team members are logging in to their IND worlds, as @lijenn checked out. I don't think any have actually made it into a session or run anything yet, but they may be any minute. @MattMoore2 - I think we can trust the results now, if you're playing around with potential future team questions.

![image](https://user-images.githubusercontent.com/29778290/122283924-11eec900-cebb-11eb-9431-0ed8a0e278b4.png)
