### ISSUE TITLE
FEATURE: Team Data Table - Need to add "NA" in empty data cells in Column D, SPParams Tab

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2065]
Discussed at Wed. Support WG 6/16, 2:10p Pacific:
![image](https://user-images.githubusercontent.com/59668647/122300236-e7e5d880-ceb3-11eb-89a7-0d92c502d9c2.png)

**Comment by staceypark** [comment]
@anazariz I added the "NA" in FRE19 and updated the associated .txt to include issue #2065

FYI: @lijenn
