### ISSUE TITLE
wk3 june_epic ANDON: Nevermore18 Data UI - Cannot get Patient Level Data

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2066]
Identified by @lijenn in intersession prep on Thurs. 6/17 at 8:30a Pacific with @hmarcia @branscombj @lzim  

I did the QA test for Nevermore18 and I did not get this problem before when testing the same clinic selection for the same team:
![image](https://user-images.githubusercontent.com/59668647/122473036-2f349d80-cf76-11eb-8bd2-ea3d7fb2551d.png)

This bug needs to be fixed ASAP since:
- (Most urgent) @hmarcia and @dlkibbe are meeting with to get the clinicselection for the data_ui tomorrow Friday 6/18 or next Mon. 6/21. They will need time to review the patient level data before their Session 2 meeting on Tues. 6/22.
- @hmarcia and @branscombj are working on getting their SPReferrals clinics for their data_ui file from a team lead next Mon. 6/21

**Comment by anazariz** [comment]
@lijenn where exactly is this happening? and which version?

**Comment by anazariz** [comment]
Estimate to fix 5 points. Will close it today.

**Comment by anazariz** [comment]
Closing this card after receiving OK from @lijenn  (on Teams).

**Comment by staceypark** [comment]
@lzim @lijenn 
ANDON #2066 resolution should always be propagated.  **Andons should not be closed without being propagated everywhere**

**Comment by anazariz** [comment]
Done. [2074](https://app.zenhub.com/workspaces/team-psd-workspace-5e4ac9bd8d388dfba6d9aef5/issues/lzim/teampsd/2074)

**Comment by anazariz** [comment]
Propagation is complete.
