### ISSUE TITLE
Story TBD: Markdown and Bookdown actions streamline and ensure quality user-edits of on-line publications.  

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2071]
### Check off requirements to verify progress through feature_tracker.
- [ ] 1. **DEFINE in work_breakdown**
  - [ ] a. **what & why** - **written definitions of requirements** in a **numbered checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** requirement definitions an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 2. **DESIGN** in **operations_to_do** and **research_to_do**
  - [ ] a. **what & why** - **_MVP_ of design** of requirements in a **algorithm map, wireframes or design** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** design **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 3. **DEVELOP** in **under_development** - "frozen"

  Task Cards:
  #
---
- [ ] 4. **TEST in functional_test**
  - [ ] a. **what & why** - **TEST requirements** using **testing_checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** via TEST **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 5. **PROD in done**
  - [ ] a. **what & why** - **_DOCUMENT_ feature** using **document_tracker** for the **5 D's.** 
  - [ ] b. **date & who** -  **DELEGATE**
    - [ ] **describe_learners** [Jenn & Rita]
    - [ ] **detail_facilitators** [Jane & Debbie]
    - [ ] **document_team** [Anthony]
    - [ ] **disseminate_scientists_va** [Anthony]
    - [ ] **depend_products** [hq & ees]
  
  Task Cards:
  #
---
- [ ] 6. **closed** - fully documented, trained and ready for the next release.

**Comment by staceypark** [comment]
sim ui workgroup 6/23:
@jamesmrollins will study and create a process map for single-source update of mlt blue and red curriculum that updates all the through to bookdown.

**Comment by jamesmrollins** [comment]
As per conversation with @lijenn.

1. Is there a specific bookdown linter?  We need something that will control the format well enough to allow a push to GitHub Pages. 
2. Is there an action where we can update a single markdown (i.e., see or say guide) and it will propagate to all the places that it is used (i.e., lzim/mtl and lzim/manual). 
3. Can we develop an action that will pull information from a test repo into a prod repo? See card #2462
