### ISSUE TITLE
wk3_june_epic: feature - change date/time style on facilitator dashboard to be numerical

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#2072]
TeamPSD style is to do yyyy_mm_dd all numerical.
I think it's confusing for the months to be alpha, since it sorts a-z instead of by time.

![image](https://user-images.githubusercontent.com/31089501/123023307-06544400-d38c-11eb-91af-88b1501f094a.png)

**Comment by jamesmrollins** [comment]
Hi @staceypark - We will make the desired changes.

@hirenp-waferwire - Please see the above comments.  We need to change all date/time combinations in the Sim UI to a fully numerical standard of yyyy_mm_dd. The time is not required to be a part of the date stamp.

**Comment by jamesmrollins** [comment]
@staceypark this is complete.
