### ISSUE TITLE
wk4 june_epic BUG: SIM UI - Chats end up in different chat threads

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2083]
Indentified during Thurs. 6/24 at 9a Pacific by @staceypark and @lijenn, Facilitators: @lzim @hmarcia 

We will edit this bug in bit.

**Comment by staceypark** [comment]
@jamesmrollins the first couple of these messages are Matt, Theresa, Jane, Jane, Claire from when we trained with them awhile ago and then from when we recently started revisiting the chat function since teams are going to the sim.

The last one was from the team we facilitated that @lijenn mentioned above. It popped up in this 583 bhip team that we used to train a while go instead of the appropriate team.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/31089501/123337856-b34dce80-d4fc-11eb-9298-8b959463f396.png)

**Comment by jamesmrollins** [comment]
Hi @staceypark 

All teams within which, you are a facilitator, will appear in the left hand navigation.  To navigate to that team, just click on it.  The boldface teams in the listing are teams with an active conversation (see second picture).  **What am I missing in terms of functionality or understanding of the problem?**

Teams in Left Hand Navigation
![image](https://user-images.githubusercontent.com/30132017/123338617-05dbba80-d4fe-11eb-98ca-469db36b27e5.png)

Teams with conversations
![image](https://user-images.githubusercontent.com/30132017/123338689-260b7980-d4fe-11eb-8747-ad0cf99ad9d2.png)

After I added Myself as Facilitator and clicking on the team, I can see this conversation
![image](https://user-images.githubusercontent.com/30132017/123338977-9adeb380-d4fe-11eb-9fc1-8223f8abc295.png)

**Comment by staceypark** [comment]
@jamesmrollins so the bug "disappeared" unfortunately. But on that last screenshot you have, you'll see my screenshot is different. The message got routed to the wrong team.

**Comment by jamesmrollins** [comment]
@staceypark  please indicate who the user was that was entering the message, what team they were addressing, and where the message ultimately popped up. Also indicate whether the message was in both places or just one place. Meaning in the intended location and the wrong location. I can see where this would be very troubling.

**Comment by lijenn** [comment]
@jamesmrollins I can provide you with that information privately via Teams. In addition, here is the bug I saw.

![image](https://user-images.githubusercontent.com/59668647/123361410-dcce2080-d523-11eb-8b34-19bfcfe55b60.png)

1. The team lead (blue email) sent a test chat, but she was in the team world at this time...however her test chat was categorized into the _ind world?
2. The team world chat above and ind chats might be getting mixed here? Though, I'm unsure if the team member (green) email was in their team world or their ind world, we'd need to identify that first before answering this question.

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire 
Users are reporting that the chat function appears to be posting messages outside of team bounds.  I will post uncensored screenshots in the Teams thread.  Please investigate to see if you can find evidence of mis-posted chat messages between groups.

**Comment by jamesmrollins** [comment]
Hi @staceypark @lijenn. @hirenp-waferwire reports that this bug has been tracked down and fixed. It's followed break-fix route so is in PROD. Would you check it out please? Thank you

**Comment by lijenn** [comment]
Thanks @jamesmrollins, we'll test this today.

**Comment by staceypark** [comment]
@jamesmrollins 

@lijenn and I tested using a direct message, an ind world, and a team world and all routed correctly.
