### ISSUE TITLE
wk5 jun_epic dataUI v22 zeroes in SP

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#2085]
Work on Version 22 to make sure there is no data (there should be 0's) in Params tabs of the Data UI unless the team has included it when clicking on "Create Team Data Table"

**Comment by lzim** [comment]
This appears to be working with v23 nevermore.

@lzim with one of our active teams today 7/16/21.

@anazariz  Should we close this?

**Comment by lijenn** [comment]
@lzim noted that she saw this update in V23, closing the issue.
