### ISSUE TITLE
wk5 jun_epic: Data UI - Naming process for previous "Create Team Data Table"

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#2086]
Keep the naming process that lists the standard name of the Team Data file for previous "Create Team Data Table" and date that is produced, even though we will manually save

**Comment by lzim** [comment]
@staceypark and @lijenn 

Is this a documentation task now?

Since we determined that manual save of the Team Data Table should be sufficient for addressing the Sharepoint Online barriers to autosave we identified?

Thanks for clarifying/closing as necessary.

**Comment by lijenn** [comment]
@lijenn and @staceypark will test this for data ui to see if the naming process still remains the same for team data table files even though we now have to manually save on SharePoint online.

**Comment by lijenn** [comment]
Tested by @staceypark and @lijenn and it works!
