### ISSUE TITLE
wk5 jun_epic; wk1 jul_epic Migrate to SharePoint Online

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#2088]

**Comment by lzim** [comment]
@staceypark  @lijenn @anazariz 

What tasks remain on this, for example, #1918.
I know we are no longer working with the legacy on-premises site. 

Do we have remaining work to do on #2050 & #2058 in terms of communication w/BISL team.
Or, in terms of testing up the network mapping solution identified at the BISL Office Hours?

There are many blocking dependencies listed, however, these appear to all be related to resolving QA with facility and data ui propagation, but not related to _migration_ pre se. 

Is that accurate?

**Comment by lijenn** [comment]
BISL's first refresh occurred on Mon. 6/7 on SharePoint Online.

Recommendation: 

1. We do not need the BISL team to do another refresh/migration.

2. Stacey and Jenn to double check if functions and files from on-premise are on SharePoint online. 
Team that were beginning or about to use the data around 6/7 were Marcia and Debbie's team on Tues. at 4:30a Pacific and Marcia and Jane's team on Thurs. at 8:30am Pacific.

3. Can we delete the old/outdated data ui files that have been migrated to SharePoint Online and provide an updated freshly pulled data ui file for all the teams?
Old data ui files will not work on SharePoint online and some may still contain the SSN which is not compliant.

**Comment by lijenn** [comment]
Discussed on Thurs. 7/22 HQ WG:

We've migrated!
