### ISSUE TITLE
Closing criteria for issues

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#209]
I see that we are closing issues when the are decided.  I recommend that we not close an issue until the decision results in completion of the desired action.  For example, issue #194 was decided in terms of specifications for desired action, but there are two follow-up tasks yet to be performed. I need a new AGG model (which I haven't received due to SP focus) and I need to notify the DEV, make changes and move to PROD.

**Comment by lzim** [comment]
Discussed on our call today - agreed that issues can remain open until the decision-related work is implemented.

Thanks!
