### ISSUE TITLE
wk5 jun_epic Propagate Facility files for the entire country through June 2021

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#2091]
Propagate all facility files for all visns through June 2021 (not just the sites we are engaging with for the Modeling to Learn program)

**Comment by lijenn** [comment]
@lijenn @staceypark will propagate the facility files for co-planning and the rest of the sites and country.

**Comment by lijenn** [comment]
Discussed 7/22 HQ WG:
Propagation along with Data UI is constrained by the 14 co-planning sites.
Blocked by bug #2115.
Priority is Story 13 PBI.
