### ISSUE TITLE
wk4 jun_epic propagate master dataUI files through june 2021

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#2094]

**Comment by lijenn** [comment]
@lijenn @staceypark will propagate the data ui files for co-planning and the rest of the sites and country.

**Comment by lijenn** [comment]
Discussed 7/22 HQ WG:
Propagation along with Facility is constrained by the 14 co-planning sites.
Blocked by bug #2115.
Priority is Story 13 PBI.
