### ISSUE TITLE
wk5 jun_epic: Sim UI Bug - Experiments Not Saving in Facilitator Individual Team Worlds

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2096]
Identified by @MattMoore2 @branscombj @lijenn on Tues. at 6:30a Pacific/9:30a Eastern.

Workflow:
1. Experiments being saved (e.g. BC) are not showing up when the experiment is saved in the Facilitator's individual worlds via the Facilitator login/role, not the Alias login.
2. Unable to save another BC experiment via Alias login (due to point 1 above since the Sim seems to understand in the backend (?) that there was a BC experiment that saved.
3. Jane via Alias login saved another bc as "bc_bc" as the experiment name. Experiment was successfully saved.
4. Jenn via Facilitator login sees the experiments from Facilitator dashboard, but experiments are not in the Sim.

![image](https://user-images.githubusercontent.com/59668647/123822159-e2738f80-d8b0-11eb-997b-bd4c5fdd7100.png)

![image](https://user-images.githubusercontent.com/59668647/123821955-b7893b80-d8b0-11eb-856e-32a6c676252e.png)

**Comment by jamesmrollins** [comment]
@lzim @MattMoore2 @lijenn @staceypark Message received, will work it tonight. Since experiments save with time stamp, they can actually be named the same. However, they don't appear on experiment drop downs unless sim is reset.

**Comment by lijenn** [comment]
@jamesmrollins We'll need to prepare an ANDON (Scope, Alert, Communicate) plan for saving experiments in the individual team worlds if you find that it is the case that Facilitator's can't save experiments in their individual worlds from the Facilitator login and only their alias login.

This is going to impact @lzim today and the rest of the Facilitators starting tomorrow AM.

**Comment by jamesmrollins** [comment]
This is kind of weird. The login shouldn't affect saving an experiment.

**Comment by jamesmrollins** [comment]
@hirenp-waferwire here is a chronology of events regarding saving experiments:

## Steps Followed to Save an Experiment from the Facilitator-User Role	
1. [From facilitator role] User is mapped as a facilitator to the individual world (created from an alias)
2. [From facilitator role] User is unable to save an experiment in the individual world when logged as a facilitator
3. [From facilitator role] User is also unable to see any of the experiments that were saved in the world (currently only able to be saved from the alias login)
4. [From alias/team lead role] User is mapped to the individual world as a team lead and assigned the alias login
5. [From alias/team lead role] User is able to save an experiment 
6. [From alias/team lead role] User is able to see past and recently saved experiments in the Experiments blue header in the session and in the Experiment Maintenance blue header on the home page

## Additional Notes
1.  When the facilitator-user attempts to save an experiment and reset, the dialogue does not prevent the facilitator-user from doing the action.  It looks like a normal save and reset, but
2. The facilitator-user does not see the saved experiment in the drop down, nor does the _ind-user.

**Comment by jamesmrollins** [comment]
Hi @lijenn and @lzim 

We are 90% sure that we can get this fixed tonight.  The experiments are being saved, but to the wrong user.  We are going to do a deep dive and find root cause.  We will also test to make sure there are no difficulties saving in _team groups as well.  I will confirm tomorrow morning.

**Comment by lijenn** [comment]
Thanks for working hard on this @jamesmrollins!
Any updates? Would like to know if I need to alert the Facilitators to prevent rework.

**Comment by lijenn** [comment]
@branscombj @MattMoore2 Bug is fixed! You can save experiments to your individual worlds without the alias login, just login as a Facilitator with your email as you normally would. 

**Jane**, you will still see the experiment that you saved on Tues. 6/29 via your alias login (and other experiments!):
![image](https://user-images.githubusercontent.com/59668647/123996050-ca207500-d983-11eb-8af1-5846f1e06484.png)

**Matt**, I see you have 3 experiments, 2 from this Monday and 1 from last Monday that you'll see when you login:
![image](https://user-images.githubusercontent.com/59668647/123995672-701faf80-d983-11eb-875e-a9736d7d83b6.png)

Thanks again @jamesmrollins :)!!!
