### ISSUE TITLE
wk_3_jul_epic:  SIM UI Feature - Shared Co-Facilitator World

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2104]
Request: Not just an have an Individual world and Team world, but a shared co-facilitator world so co-facilitators can work and run experiements together in the same world.

### Check off requirements to verify progress through feature_tracker.
- [ ] 1. **DEFINE in work_breakdown**
  - [ ] a. **what & why** - **written definitions of requirements** in a **numbered checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** requirement definitions an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 2. **DESIGN** in **operations_to_do** and **research_to_do**
  - [ ] a. **what & why** - **_MVP_ of design** of requirements in a **algorithm map, wireframes or design** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** design **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 3. **DEVELOP** in **under_development** - "frozen"

  Task Cards:
  #
---
- [ ] 4. **TEST in functional_test**
  - [ ] a. **what & why** - **TEST requirements** using **testing_checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** via TEST **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 5. **PROD in done**
  - [ ] a. **what & why** - **_DOCUMENT_ feature** using **document_tracker** for the **5 D's.** 
  - [ ] b. **date & who** -  **DELEGATE**
    - [ ] **describe_learners** [Jenn & Rita]
    - [ ] **detail_facilitators** [Jane & Debbie]
    - [ ] **document_team** [Anthony]
    - [ ] **disseminate_scientists_va** [Anthony]
    - [ ] **depend_products** [hq & ees]
  
  Task Cards:
  #
---
- [ ] 6. **closed** - fully documented, trained and ready for the next release.

**Comment by jamesmrollins** [comment]
@lijenn I am definitely not clear on this use case.  Need further development of the idea-this is already possible by setting up a team with the two individuals on the same team as leads.  What am I missing?

**Comment by lijenn** [comment]
@jamesmrollins Ah, I was wondering if it was possible to have the sim auto-create it, like how team and ind worlds are auto created now...Otherwise yes, we can technically do that right now.

**Comment by jamesmrollins** [comment]
We need a common world for both facilitators and the PI to reference when running simulations and rehearsing.  This reference will aid in ensuring everyone is on the same page.  

- team_root_fac_shared_ind
- Would include @lzim @lijenn @staceypark @jamesmrollins with all fac_ind set ups

## Questions
- Do we still need both the shared fac_ind and the fac_ind worlds for facilitators?
- Does this meet the PI's expectations?

**Comment by jamesmrollins** [comment]
Decision at Workgroup Leads 7/12:  Discuss at Sim UI workgroup meeting

**Comment by jamesmrollins** [comment]
Decision at Sim UI meeting 7/14:  

- [ ] Create a shared Co-facilitator world (with black belts).
- [ ] Create a truly individual world inside a facilitator group.
- [ ] Leave the Co-facilitator _ind worlds.

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire - We would like to change the team setup function (this affects #1968).  See instructions below.

## New Team Setup

1.  Create a _team group.
2.  Assign all players to the same world according to role (facilitator, team lead, player).
3.  Create an _ind group.
4.  Assign all players and team leads to their own worlds.
5.  Create a _shared group.
6.  Assign facilitators to this group as team leads.
7.  Assign standing participants (see below) to the shared group.

_Note:  Standing participants would be in all shared groups._

## Standing Participants (aliases available in the facilitator_login group)

Lindsey Zimmerman
Stacey Park
Jennifer LI
James Rollins

**Comment by lijenn** [comment]
#2104 - @jamesmrollins  will provide an update about whether there is any risk to losing anything.
@lzim @staceypark @lijenn 

- [ ] Shared Facilitator

- [ ] Truly individual world

- [ ] Remove the co-facilitator _ind worlds - NEED TO BE CAREFUL ABOUT THIS due to all the prep this week.


Changing the set-up algorithm for world set-up.

Ask facilitators on 7/20 whether they want this for current teams.

**Comment by jamesmrollins** [comment]
@lijenn @staceypark @lzim  After discussion with @hirenp-waferwire, we don't anticipate any issues with existing groups when we update the New Team Setup algorithm. The New Team Setup will only affect new groups.  We will have to assign facilitator_ind worlds by hand in a facilitator_team.  But this should not be difficult and I will be happy to make that happen.

**Comment by lzim** [comment]
Thanks @jamesmrollins for confirming.

@lijenn and @staceypark will review these new features with facilitators and facilitate_workgroup this morning.

> @lijenn @staceypark @lzim After discussion with @hirenp-waferwire, we don't anticipate any issues with existing groups when we update the New Team Setup algorithm. The New Team Setup will only affect new groups. We will have to assign facilitator_ind worlds by hand in a facilitator_team. But this should not be difficult and I will be happy to make that happen.
