### ISSUE TITLE
aug_epic_wk5: Sim UI - Easily copy or transfer QHFD from Team World to the Facilitator Individual and Shared Worlds

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2105]
Request: Easily transfer QHFD from Team World into the facilitator world (i.e from a clipboard)

### Check off requirements to verify progress through feature_tracker.
- [ ] 1. **DEFINE in work_breakdown**
  - [ ] a. **what & why** - **written definitions of requirements** in a **numbered checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** requirement definitions an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 2. **DESIGN** in **operations_to_do** and **research_to_do**
  - [ ] a. **what & why** - **_MVP_ of design** of requirements in a **algorithm map, wireframes or design** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** design **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 3. **DEVELOP** in **under_development** - "frozen"

  Task Cards:
  #
---
- [ ] 4. **TEST in functional_test**
  - [ ] a. **what & why** - **TEST requirements** using **testing_checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** via TEST **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 5. **PROD in done**
  - [ ] a. **what & why** - **_DOCUMENT_ feature** using **document_tracker** for the **5 D's.** 
  - [ ] b. **date & who** -  **DELEGATE**
    - [ ] **describe_learners** [Jenn & Rita]
    - [ ] **detail_facilitators** [Jane & Debbie]
    - [ ] **document_team** [Anthony]
    - [ ] **disseminate_scientists_va** [Anthony]
    - [ ] **depend_products** [hq & ees]
  
  Task Cards:
  #
---
- [ ] 6. **closed** - fully documented, trained and ready for the next release.

**Comment by jamesmrollins** [comment]
Copying QHFD text via the clipboard will not work. Since QHFD is 4 separate fields, the clipboard in not capable of parsing the information into the destination fields.  However, if we make all saved (and reset) experiments available to _ind worlds sharing the same team root, that would scratch the itch.  James will verify with @hirenp-waferwire whether this is possible, or not.

**Comment by jamesmrollins** [comment]
@staceypark @lijenn This feature is now available in Test.  Please see QA Test card #2121 blocked issue above.

**Comment by lijenn** [comment]
In Prod and working great :) Thanks!
