### ISSUE TITLE
wk_3_jul_epic:  SIM UI Feature - Easily copy/transfer Team Data File from Team World to Facilitator IND and Shared World

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2106]
Request: Easily add the Team Data File from the Team World to the facilitator and shared world (e.g. from a clipboard or have it auto-populate).
- We do want to be able to override the data file if needed though

### Check off requirements to verify progress through feature_tracker.
- [ ] 1. **DEFINE in work_breakdown**
  - [ ] a. **what & why** - **written definitions of requirements** in a **numbered checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** requirement definitions an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 2. **DESIGN** in **operations_to_do** and **research_to_do**
  - [ ] a. **what & why** - **_MVP_ of design** of requirements in a **algorithm map, wireframes or design** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** design **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 3. **DEVELOP** in **under_development** - "frozen"

  Task Cards:
  #
---
- [ ] 4. **TEST in functional_test**
  - [ ] a. **what & why** - **TEST requirements** using **testing_checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** via TEST **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 5. **PROD in done**
  - [ ] a. **what & why** - **_DOCUMENT_ feature** using **document_tracker** for the **5 D's.** 
  - [ ] b. **date & who** -  **DELEGATE**
    - [ ] **describe_learners** [Jenn & Rita]
    - [ ] **detail_facilitators** [Jane & Debbie]
    - [ ] **document_team** [Anthony]
    - [ ] **disseminate_scientists_va** [Anthony]
    - [ ] **depend_products** [hq & ees]
  
  Task Cards:
  #
---
- [ ] 6. **closed** - fully documented, trained and ready for the next release.

**Comment by jamesmrollins** [comment]
@lijenn all the facilitator has to do is add the team data filename to their dropdown and they would be able to access it.  Not sure I fully understand the intent here.

**Comment by jamesmrollins** [comment]
There is a pain-point where the user has to know the team data filename in order to update their Home screen dropdown menu.  

- [ ] It would be better if the dropdown was automatically updated when the team data was added to Epicenter.  
- [ ] This would affect the training documentation for the Learner.  
- [ ] We would want to keep the ability to edit the team data dropdown. 

@staceypark says that this is important enough to complete right-away.

**Comment by branscombj** [comment]
Hey, butting in here. I just realized we show teams how to update their team data menu, ostensibly so that post-s12 they could pull a new dataset - which we've carefully taught them to do - and load it in the sim. But now I understand that if someone does that on their own, they'll be frustrated because we haven't uploaded the file to Epicenter for them first. This lesson does serve to show team members how to get their team data into their IND worlds - although if the feature discussed here is implemented it looks like they might no longer have to do that(?). 
>Would it make sense/be feasible to let any user who is assigned to a world upload a dataset to Epicenter? Something like changing the widget that is currently the team data menu maintenance so it is actually an uploading function. The data file they upload gets added to the complete list of data files that facilitators and admins see in the current dashboard, but the user only sees what they or their team lead uploaded?

**Comment by jamesmrollins** [comment]
@hirenp-waferwire   The team want to automate the deployment of team data files.

## When a Team Data File Is Uploaded Using the Facilitator Dashboard

1.  The Team Data is moved to Epicenter Model Directory.
2.  The Team Data name is added to the Team Data Dropdown Maintenance dialogue in the Home page for all _team, _ind and _share groups that use the same team root name.
3. The Team Data filename will contain the team root name. 

## Limitations

- [ ] While adding or renaming a file can occur in the Home/Team Dropdown Maintenance dialogue, these changes will not be reflected in the team data filename that is posted to Epicenter, nor will it update the name in the Team Data listing in the Facilitator Dashboard.  
- [ ] If the user changes the name to make it different from the automated posting, the team data table will not load and the sim will throw an error.

## Recommendation

@lzim @branscombj @lijenn @staceypark - We recommend removing the "Rename" button from the Team Data Maintenance dialogue.  Update training documents as required.

- [ ] Approved, please remove it 
- [ ] Nope, keep it.

**Comment by branscombj** [comment]
> ## Recommendation
> @lzim @branscombj @lijenn @staceypark - We recommend removing the "Rename" button from the Team Data Maintenance dialogue. Update training documents as required.
> 
> * [X]  Approved, please remove it
> * [ ]  Nope, keep it.

I think the reason for having it is in case you enter it incorrectly in the first place. The alternative, if we remove the rename functionality, will be to type the filename in anew - correctly - and delete the incorrect one.
