### ISSUE TITLE
wk_3_jul:  SIM UI Feature - Open Team Data on New Patient Referrals values and Balance Mode (i) information Windows at the same time

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2107]
Request: See the values at the same time while referring to the (i) information from Balance mode for "Use Team Data on New Patients Referrals"

Currently only 1 window opens at a time, can't have both windows open.
![image](https://user-images.githubusercontent.com/59668647/124164766-e987d280-da55-11eb-9567-37f98dffd9cb.png)

### Check off requirements to verify progress through feature_tracker.
- [ ] 1. **DEFINE in work_breakdown**
  - [ ] a. **what & why** - **written definitions of requirements** in a **numbered checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** requirement definitions an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 2. **DESIGN** in **operations_to_do** and **research_to_do**
  - [ ] a. **what & why** - **_MVP_ of design** of requirements in a **algorithm map, wireframes or design** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** design **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 3. **DEVELOP** in **under_development** - "frozen"

  Task Cards:
  #
---
- [ ] 4. **TEST in functional_test**
  - [ ] a. **what & why** - **TEST requirements** using **testing_checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** via TEST **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 5. **PROD in done**
  - [ ] a. **what & why** - **_DOCUMENT_ feature** using **document_tracker** for the **5 D's.** 
  - [ ] b. **date & who** -  **DELEGATE**
    - [ ] **describe_learners** [Jenn & Rita]
    - [ ] **detail_facilitators** [Jane & Debbie]
    - [ ] **document_team** [Anthony]
    - [ ] **disseminate_scientists_va** [Anthony]
    - [ ] **depend_products** [hq & ees]
  
  Task Cards:
  #
---
- [ ] 6. **closed** - fully documented, trained and ready for the next release.

**Comment by jamesmrollins** [comment]
@lijenn this may be possible, but will need to verify with @hirenp-waferwire

**Comment by jamesmrollins** [comment]
@lijenn - I now remember that according to ADA section 508 accreditation, we can only have one popup open at a time. While technically the QHFD short form is a popup, we were able to get around this requirement because the popup is presented when the AGG sim starts up.

**Comment by jamesmrollins** [comment]
Decision @ Workgroups Leads 7/12 - Allow concurrent popups in all simulation modules.

**Comment by jamesmrollins** [comment]
@hirenp-waferwire please make "i" information popup and any team data popups available at the same time.  

## See AGG Team Data/Balanced Mode switch BC and "i" popups
![image.png](https://images.zenhubusercontent.com/5e4eac12455ade27f3584cea/46236bd3-8523-4d1b-8c50-90e91ccaf237)

 
## See MM and CC Referral Rate BC and "i" popups

![image.png](https://images.zenhubusercontent.com/5e4eac12455ade27f3584cea/2e832054-c2da-4e68-a592-86ad19466841)

**Comment by jamesmrollins** [comment]
@branscombj indicated to me that orienting the BC values to a portrait aspect ratio would facilitate comparison of these values against the values on the Team Data table.

- [ ]  Approved?

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire.  I tested the change today, and it looks good.  Is it possible to change the aspect ratio of the BC popups to portrait (see example below). This will enable easier comparison against the Team Data Table.

![image](https://user-images.githubusercontent.com/30132017/125834877-3d41aa92-12e9-4f62-bbc0-4cc980863614.png)

**Comment by jamesmrollins** [comment]
Hi @branscombj and @lijenn how does this look?

![image](https://user-images.githubusercontent.com/30132017/125967881-068682fe-1a03-4f04-b5b7-7f4b6d65e170.png)

**Comment by branscombj** [comment]
@jamesmrollins @lijenn Looks FAB to me! @lzim are you ok with these changes??
