### ISSUE TITLE
wk5 jun_epic PROBLEM: Cannot run facility propagation

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#2108]
@anazariz 

Defined as "problem" according to our bug vs. problem vs. andon definitions, where a problem is a series of interrelated issues that keep arising (#2089, #2100, #2091)

Followed instructions for propagating on SharePoint Online that were recorded and documented in the quant_operations workgroup 7/1 meeting. Ran into errors. 

See Teams chat in quant_workgroup here for more details on steps followed and screenshot of errors: https://teams.microsoft.com/l/message/19:1dea54c6db60416e8985ba6bf7bb7883@thread.skype/1625193373961?tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf&groupId=1db500d5-0d01-4254-af42-ad3f78bafacd&parentMessageId=1625193373961&teamName=teampsd_vha&channelName=quant_workgroup&createdTime=1625193373961

**Comment by lijenn** [comment]
@staceypark will propagate a facility file on SharePoint Online.
