### ISSUE TITLE
FEATURE: QHFD text - Check on Default in Sim Session Experiments Dropdown

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2110]
@branscombj Noticed this when prepping for S8 on Tues. 7/6 at 6:30a Pacific.

@lzim @staceypark @jamesmrollins Was there a previous decision that explained why this is not checked on default?

Feature request: Have the text box checked on default when selecting a experiment in the Session's Experiment's dropdown:
![image](https://user-images.githubusercontent.com/59668647/124612258-08f07800-de27-11eb-98ec-9682072f3a26.png)

**Comment by jamesmrollins** [comment]
Hi @branscombj @lijenn @staceypark @lzim - Yes, this feature was ice-boxed around April 2020.  Please see dialogue [here](https://github.com/lzim/teampsd/issues/743#issuecomment-620032539).  In any case, it is real simple to change the checkbox default and can be done in 24 hours.  Just need a decision.

Thanks,
James

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire :  


## Please change the default to "Checked" for the Review Previous Settings dialogue for all Modules.

![image.png](https://images.zenhubusercontent.com/5e4eac12455ade27f3584cea/97c4c879-8463-49c9-97c2-45e4ac42d4bc)
