### ISSUE TITLE
wk1 jul_epic: Data UI - Update file path to propagate on SharePoint Online Cloud

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2113]
Data UI file - Update file path to propagate on SharePoint Online Cloud.

@anazariz please put your estimate and close when ready to test by @lijenn and @staceypark.

**Comment by anazariz** [comment]
I updated the Data UI file and updated the runbook that has the instructions on how to run the data UI propagation. I also propagated a specific Facility for @lijenn 's testing.

**Comment by lijenn** [comment]
@lijenn Tested the propagation for data ui to SharePoint with the updated code for the file path.
