### ISSUE TITLE
wk2 jul_epic: Test Data UI - Reset Pivot Chart in HF tab & Update file path to propagate on SharePoint Online Cloud

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2114]
Test for Data UI before propagating to rest of VISNs on SharePoint Online:
- [ ] #2102 vizHF Reset Pivot Chart
- [x] #2113

**Comment by anazariz** [comment]
I tested the reset on both Data UI and Facility. They both work file with small datasets. If they cause issues with larger datasets, the issue is cloud/bandwidth related.

**Comment by lijenn** [comment]
@staceypark @lijenn tested and were successfully able to propagate the data ui to SharePoint!
