### ISSUE TITLE
"Bug" or "Task": 7/7/2021 AGG: Units label on Chart

### ISSUE THREAD

**Issue by dlkibbe** [lzim/teampsd#2117]
**1. Add description:** 
@dlkibbe working in AGG model with her blue team data set. Ran a simulation modifying true missed appointment rates at approximately 4:15 pm eastern. All of the services charts with "Work Pressure" titles (Psych - Work Pressure, MM - Work Pressure, Group - Work Pressure, EBPsych - Work Pressure, CC - Work Pressure) on the Results Outputs screen has units label of dmnl (see screen shot). The work pressure variables in the model diagram have pct as the units. I'm not sure what dmnl stands for.

![image](https://user-images.githubusercontent.com/31182258/124823638-71cb1380-df3f-11eb-8099-c4909022bf2a.png)
 
**2. Click on the right:**  
i. **Pipelines** - prioritize in a TeamPSD (& Workgroup) pipeline  
ii. **Assignee** - assign to an individual team member producing work for the issue  
iii. **Label**- assign workgroup (lead) responsible for tracking the task  
iv. **Projects** - assign to domain-specific TeamPSD tracker (issues, features, document, manuscript, team)  
v. **Milestones** - select monthly sprint milestone within the workgroup   
vi. **Estimate** - Estimate task in complexity points   
vii. **Epics** - assign to team-wide epic and TeamPSD master plan project  
iix. **Releases** - assign to key team release grouped with other relevant issues  

**3. If you anticipate that your **issue card** or **bug card** will have **dependencies** these can be added once the issue has been submitted.   

ix. **Add dependencies** - assess for and add dependencies *blocking* & *blocked by* this issue

**Comment by jamesmrollins** [comment]
Hi @dlkibbe .  "dmnl" means "dimensionless."  In model-speak this is typically expressed as a percentage.  Since we hooked the model variable straight into the Sim UI, it is reading it verbatim from the model.  We may have to modify code to change it to %.  We will look into it.

**Comment by dlkibbe** [comment]
Thanks @jamesmrollins
