### ISSUE TITLE
ICEBOX wk2 jul_epic: Inconsistent/Intermittent bugs on Data UI version 23 - Document AutoSave OFF instructions

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2119]
@staceypark and @lijenn tested Marcia and Debbie's team (meets on Tuesdays at 4:30a Pacific, see MTL Help calendar) data ui on SharePoint Online.

See files mentioned below [here](https://dvagov.sharepoint.com/sites/VHAPTSDOMHO/Pages/VISN04/503.aspx?RootFolder=%2Fsites%2FVHAPTSDOMHO%2F503%2Faltoona%5Ftest%5Ffiles&FolderCTID=0x012000F4396ABAAABB8D48A705D48A002A10FD&View=%7BE9837187%2DAA4B%2D482D%2D8E72%2DC06CCD3447EF%7D):

1. Jenn created the **data ui on 2021_07_09** for Marcia and Debbie's team:
- successfully got patient level data
- no issues in the data tab (except for the remaining question to clarify what the defaults for the vizHF categories should be)
- got a team data table file

2. Jenn made a **copy of the data ui file above** for Stacey and Jenn to test multiple users on the same file (we did this since we had difference experiences while testing a Facility file at the same time, see #2116)
 In the this first copy of the data ui file, Stacey and Jenn were on the file at the same time. Stacey and Jenn both experienced a different bug pop-ups when trying to reset the pivot chart:

- Stacey:
![image](https://user-images.githubusercontent.com/59668647/125150110-02495580-e0f2-11eb-98f4-2ca9cd368135.png)

- Jenn:
![image](https://user-images.githubusercontent.com/59668647/125150122-1ab97000-e0f2-11eb-928f-cc8197e5e71f.png)
![image](https://user-images.githubusercontent.com/59668647/125150131-29078c00-e0f2-11eb-816d-f05daee33c58.png)

	
3. Jenn makes another copy of the original data ui file **(2nd copy)** and went in the file first and changed the filters in the viz tabs.
Stacey went in afterwards to test the reset pivot chart buttons in all the viz tabs and got the same error above.

4. In a **3rd copy** of the file, Stacey went in first and test the filters and reset pivot chart buttons and did not experience bugs.
Jenn went in the file after Stacey and also did not experience any bugs.

**Comment by lzim** [comment]
Discussed at hq_workgroup on 7/15/21.

It appears that these issues are resolved by turning off auto save on files hosted on Sharepoint Online.

We identified 10 documentation dependencies, which @lijenn plan to help update.
- [ ] SEE guides (Blue & Red) sessions 1-3
- [ ] SAY guides (Blue & Red) sessions 1-3
- [ ] Data UI Cheatsheet
- [ ] Provide guidance on Sharepoint Online
- [ ] "Data UI Propagation.docx" File #626 mtl.how/documents
- [ ] Facility file #627 "Splashpage_monthly_update_readme.docx"

**Comment by lzim** [comment]
Discussed at **hq_workgroup** 7/22/21

@staceypark 
@lijenn 

@jamesmrollins - We can chat at Mon 8AM Workgroup Leads about whether HQ could use help with this.

In terms of screen shots:
- [ ] Include AutoSave Icon (left hand)
- [ ] Include Save & Refresh, vs. Rename and Save (left hand)
- [ ] Include Seeing other users (right hand)
- [ ] Include message about whether I want to include others changes 

@lzim to review these in greater detail at 7/27 **facilitate_workroup** with facilitators.

**Comment by lijenn** [comment]
Discussed Thurs. 7/22 HQ WG:

Moved to Icebox to focus on priority tasks for PBI.

**Comment by lzim** [comment]
#adjudicate_memo
This is unnecessary due to the MTL 3.0 Power BI release in March 2022.
