### ISSUE TITLE
wk3 jul_epic: BUG Sim Menu - TT Report 2, Last page (text, logos, graphs) is stretched

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2123]
@jamesmrollins The last page of the tt report 2 looks to be stretched vertically compared to the other pages.
 Any way we could have it be the same size as the other graphs?

TT report was generated from Edge.

Other pages:
![image](https://user-images.githubusercontent.com/59668647/125811795-62810dd5-1d65-4990-bcff-0951b35b0abb.png)

Last page:
![image](https://user-images.githubusercontent.com/59668647/125813257-c3926584-45c3-4b8a-8d30-2d60149d5424.png)
![image](https://user-images.githubusercontent.com/59668647/125812187-cabfd54f-9a88-478b-85fe-a855e5b9abd9.png)
![image](https://user-images.githubusercontent.com/59668647/125813145-f232d7bf-60d4-4fc6-bbfb-08cc5f83fa53.png)

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire - I will send you the PDF via Teams tonight for investigation.

**Comment by jamesmrollins** [comment]
@lijenn @staceypark this has been corrected.

**Comment by lijenn** [comment]
Fixed! Thank you @jamesmrollins
