### ISSUE TITLE
wk2_mar: Provide Image Outputs from tt reports that complies with publisher requirements

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2124]
## Background

Many tt reports may be used to support research or other academic publications.  The ability to download a specific chart from a tt report would be useful when preparing publications.

## Features

- [x] A menu launched from export button that provides a checklist of charts to be downloaded.
- [x] When checked, an image is rendered and downloaded, named with the team name and chart name (exg. 640_graham_bhip_intake_evaluation_rate)
- [ ] ~~The output is in the PNG format.~~ Our development library only support PDF output.  however, from Acrobat, a .png format can be produced.

**Comment by jamesmrollins** [comment]
@lzim @lijenn @mnallajerla @hirenp-waferwire 

# Workflow to select desired charts for .PNG export from tt Admin popup

1. Click "tt Admin."
2. Click Team.
3. Click Module.
4. Click Experiment (note the illustration has combined the scroll into one screen for easier viewing).
5. Click desired Charts.
6. Click "Save Charts Only"

> The Sim UI will provide a save dialogue that will allow the user to direct the Sim UI where to save the files. The charts will be saved as individual files. The Sim will name the files using team_name_experiment_name_chart_name.png.

![image](https://user-images.githubusercontent.com/30132017/154149344-3478d245-cf8d-4c39-8595-f4da7618a1d4.png)

**Comment by jamesmrollins** [comment]
Discussed at Sim UI Meeting 2/16:

1. Control charts will be a graphic that will likely be a linear and LOESS chart to support tt3.  Contact @dkngenda regarding code to render the chart. We should split this off into its own issue.  Let's also check for an open issue card on this subject. This will touch David and Jeff.  
2. The .png export concept is approved.

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire - I did testing of the tt chart export and it works fine.  However the exports are pdf and not png.  Can you fix this?

**Comment by jamesmrollins** [comment]
@lzim @lijenn @mnallajerla  - I spoke with Hiren regarding how we are exporting this file.  While I thought .png was possible, I find that it really isn't.  However, from the .pdf, TIFF, JPEG and PNG are available for export. Moreover, since the PDF is exporting a bitmap, it too can be placed in PDF format in a document.  

Is this agreeable - or would you like further investigation into a .PNG only export option?

**Comment by jamesmrollins** [comment]
Sim UI 3/2

- Review Implementation Science and American Journal Community Psychology for specific requirements. 
- Implementation Science [Instructions to Authors about figures in manuscripts](https://implementationscience.biomedcentral.com/submission-guidelines/preparing-your-manuscript)
- [EM Manager](http://www.ariessys.com/wp-content/uploads/EM-Author-English.pdf)

**Comment by jamesmrollins** [comment]
Discussion with @hirenp-waferwire 

-  Need to check out whether or not we can adjust or specify chart resolution
- Since we render on the computer screen, there may be some limitations based on the user's screen size and resolution.
- @jamesmrollins will investigate publisher requirements and set up a table for @hirenp-waferwire to investigate how we might be able to fulfill the requirements, if possible.

**Comment by jamesmrollins** [comment]
FYI @lzim @mnallajerla @lijenn 

Hi @hirenp-waferwire :  Please see graphics file output specifications below.  Can our export functionality support these?  I also think we should constrain user choices to only be able to select one graph per export file. 

## Specifications

### Figure size and resolution

- Figures are resized during publication of the final full text and PDF versions to conform to the BioMed Central standard dimensions, which are detailed below.
- Figures in the final PDF version:
    - width of 85 mm for half page width figure
    - width of 170 mm for full page width figure
    - maximum height of 225 mm for figure and legend
    - image resolution of approximately 300 dpi (dots per inch) at the final size
    - colors based on the CMYK color model.
- Figures should be designed such that all information, including text, is legible at these dimensions. All lines should be wider than 0.25 pt when constrained to standard figure widths. All fonts must be embedded.

**Comment by jamesmrollins** [comment]
Conversation with @hirenp-waferwire 3/9

- Need a wireframe to layout the dimensions stated in mm above in pixels.
- Produce a representative half page graph.
- Output as PDF.

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire 

Please find the attached files that have the appropriate half page and full-page sizes supporting a 300 X 300 dpi resolution.  However, keep in mind the images **must be readable.** Currently, the lines are to thin and the numbers are too small and light.  I recommend that as we render these images in HTML, we thicken the lines so that when printed, one can read them. 

[85mm_half_page.pdf](https://github.com/lzim/teampsd/files/8225702/85mm_half_page.pdf)

[170mm_full_page.pdf](https://github.com/lzim/teampsd/files/8225701/170mm_full_page.pdf)

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire - I reviewed the downloads and have a few observations:

1.  The color model is RGB and needs to be CMYK to support print publications.
2.  The outputs seem a little "fuzzy" for 300x300 resolution.  Photoshop indicates their resolution is correct, is there a way we can sharpen the image? (see snip from full-page below)
3. The font is correct.
4. The color saturation looks good.

![image](https://user-images.githubusercontent.com/30132017/159592311-3f31feb3-6164-4e48-9bc4-adb560609a53.png)

**Comment by lzim** [comment]
Thanks @hirenp-waferwire 
This is going to be so important for the team 😺 

I agree @jamesmrollins there is a bit of "rasterization" in the font.
Thanks for catching the other components from the detailed requirements.

FYI: @lijenn @mnallajerla

**Comment by jamesmrollins** [comment]
@lijenn @lzim @mnallajerla - This is completed and in test slow. Say the word and I will promote to PROD.
