### ISSUE TITLE
ASAP Bug/Problem Facility File - Showing incorrect clinics within facility.xlxb file

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2126]
Issue identified by Lindsey on 7/15 and reported with screenshot on the quant_workgroup Teams Channel with request for @anazariz to resolve, beginning with the facility that supported by Jane & Marcia on Thursdays (with a supplemental meeting w/staff planned for Mon 7/19.

_Note:_ This has been observed previously, as a result this "bug" is recurring and labeled a "problem."

- [x] 1a. Confirm whether you have resolved reasons for this team's facility file includes other facility data and repropagated the original facility file?|

- [x] 1b. Describe below the quality assurance steps that you have taken to address this issue, as I observed it in this team's file, but QA is necessary, as the issue may be more widespread.
 
- [ ] 1c. Document in the "Splashpage_monthly_update_readme.docx" file what QA steps have been implemented in the splashpage to prevent this problem in the future (as it has happened in the past).
 
- [ ] 1d. Document in the "Splashpage_monthly_update_readme.docx" file how a Team PSD member can determine whether they are working with the correct facility file.

- [ ] 1e. Provide an estimate for next steps (story points) so that the team can confirm where resolution of this late bug issue should be prioritized.

_Thanks!_

**Comment by lzim** [comment]
@anazariz 

Let us know as soon as you have an update on #2115 #2126 or #2127 this morning, since one of the co-planning meetings is first thing tomorrow. Thanks!

@lijenn & @staceypark As a fallback we will want to queue up a Data UI for the two co-planning meetings with Matt, so that we can use this if the facility file bugs are not squashed in time.

**Comment by anazariz** [comment]
Objective: check to see if they were locations in 589 that do not belong to 589
 
I used the table splash.SplashSourceDiag that has location names. If the program is pulling in wrong locations, they should show up here.

--__________________________________________________________
**I ran the following queries:**

select distinct
  trim(locationname)
from 
   splash.SplashSourceDiag
where
       sta3n = '589'
   and trim(locationName) in (select trim(LocationName) from cdwwork.dim.location)

**Show me splash.SplashSourceDiag for 589 that are also in CDW (don't care if the sta3ns match**  
Got 2291 records
--_______________________________________________________

select distinct
  trim(locationname)
from 
   splash.SplashSourceDiag
where
       sta3n = '589'
   and trim(locationName) in (select trim(LocationName) from cdwwork.dim.location)

**Show me splash.SplashSourceDiag for 589 that are also in CDW (do care if the sta3ns match**  
Got 2291 records -- So matching records also match the sta3n

--__________________________________________________________

select distinct
  trim(locationname)
from 
   splash.SplashSourceDiag
where
       sta3n = '589'
   and trim(locationName) not in(select trim(LocationName) from cdwwork.dim.location)

**Are there locations in splash.SplashSourceDiag for 589 that are not in CDW (don't care if the stations match)?  
There were 387 records
--_________________________________________________________

select distinct
  trim(locationname)
from 
   splash.SplashSourceDiag
where
       sta3n = '589'
   and trim(locationName) not in(select trim(LocationName) from cdwwork.dim.location)

**Show me locations that are in splash.SplashSourceDiag for 589 but not in CDW**  
There were 387 distinct locations in splash.SplashSourceDiag that are also in CDW

--_________________________________________________________

select distinct 
   sta3n
from 
   cdwwork.dim.location 
where
trim(locationName) in
(
select distinct
  trim(locationname)
from 
   splash.SplashSourceDiag
where
       sta3n = '589'
   and trim(locationName) not in(select trim(LocationName) from cdwwork.dim.location)
)

**Using the 387 list, show me a distinct list of sta3ns**  
This came up empty, which means these are no longer in the CDW locations!

--___________________________________________________________
To make sure that the above query was producing good results, I took a couple of actual records

Select
   *
From
   cdwwork.dim.location
where 
   trim(locationName) in ('location 1 not listed', location 2 not listed')

Result set came back empty. so could these be locations that are no longer there or renamed (2 year period)?

**Comment by lzim** [comment]
@anazariz 

Your work above appears to be a misunderstanding of the issue were it was the incorrect **sta6a clinics** showing up in the facility file, like we discussed in the meeting and consistent with the screenshot in the **quant_workgroup thread of Teams** NOT the "location_name."

FYI: @staceypark and @lijenn

**Comment by lzim** [comment]
@anazariz and @staceypark  discussed this at an impromptu huddle to review #2115, #2126 & #2127.

Per above, @anazariz is clear now that the issue we observed with our Thurs team was misalignment between the **sta6a division** and the **facility sta3n** in the viz tabs. Not the location name. 

Lindsey hasn't checked every tab for the co-planning meeting tomorrow morning at 9AM, but I believe that the **divisionname** was correctly showing for that facility in the viz tabs.
