### ISSUE TITLE
ASAP BUG/PROBLEM VBA Missing Project Issue

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2127]
@anazariz identified this issue while inspecting Bug #2126 and described it on quant_workgroup Teams channel, inclusive of screenshots and reporting that he has identified this issue previously, hence it has moved from being a "Bug" to being a "Problem"

 - [ ] 1a.  Confirm whether you have resolved this recurring issue?
 
 - [ ] 1b.  Describe below the quality assurance steps that you have taken to address this issue, as you observed it in the 589 file, but QA is necessary, as the issue may be more widespread.
 
 - [ ] 1c.  Document in the "Splashpage_monthly_update_readme.docx" file how a Team PSD member can determine whether they are working with the correct facility file.

- [ ] 1d. Provide an estimate for next steps (story points) so that the team can confirm where resolution of this late bug issue should be prioritized.

_Thanks!_

**Comment by anazariz** [comment]
Excel has a plugin that helps with managing Pivot tables. I tried adding the tool to a test splash workbook but the tool created a project file in the workbook. Even though I did not use the feature in the production version, propagation carried the project with it, even though you could not see the project in the workbook. Anyhow,  I reverted to a previous version and the problem went away. The current version should not have this issue and this issue can be closed. 

Currently, the Facility file does not have a version number (like Data UI does).

**Comment by lijenn** [comment]
@anazariz Updated the current version for the SharePoint Online Facility file "splashmothership_online".

**Comment by lzim** [comment]
@anazariz 

Let us know as soon as you have an update on #2115 #2126 or #2127 this morning, since one of the co-planning meetings is first thing tomorrow. Thanks!

@lijenn & @staceypark As a fall-back we will want to queue up a Data UI for the two co-planning meetings with Matt, so that we can use this if the facility file bugs are not squashed in time.

**Comment by lzim** [comment]
@anazariz reports at a huddle 7/20/21 w/@lzim @lijenn @staceypark 

For the specific Thursday facility that Ash first observed this error with last Friday 7/16.
He re-propagaged that facility's file and opened it and confirmed he did not get the VBA missing project issue.
