### ISSUE TITLE
ASAP BUG Sim UI: "Failed" when joining Ind_world for team Errors w/Loading Data & Reporting a Bug through Sim UI

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2128]
@jamesmrollins 

I'm experiencing a continuation of the issues with loading team data in my ind world for the team Jane & Marcia will facilitate on Thurs 7/22. Unfortunately, there have been headaches on the data side for this team - so, I'm motivated to pre-empt any sim problems.

I tried to report this through the Sim UI directly, but got an error with that too. So, even though we may want to treat these as separate bugs, I've combined them here for tracking their impact in one place.

All were identified using Edge from my GFE laptop.

**Not loading a data file that I used previously**
![kansas_city_pct_loading](https://user-images.githubusercontent.com/7454688/126016231-4a073a02-fd24-475c-a722-994ab1d6711a.PNG)

**Failed Message & Console**
![failed](https://user-images.githubusercontent.com/7454688/126016259-1ed35903-38a7-4ec5-8240-af43aaf98e9a.png)

![upload_screenshot_sim_ui_bug](https://user-images.githubusercontent.com/7454688/126016261-c791512d-4364-492d-9b6c-5d99132bb8ee.PNG)

**Will not report a bug directly through Sim UI:** 
![upload_screenshot_sim_ui_bug](https://user-images.githubusercontent.com/7454688/126016226-e1f7e640-5d1d-4941-b524-4655ef82655e.PNG)

**Comment by lzim** [comment]
@jamesmrollins 

I am still getting the red "**failed**" error above when working with my individual world for this team that is meeting on Thurs to be co-facilitated by Marcia and Jane (see mtl.help calendar for facility). 

I reported this last week and I heard Marcia mention yesterday that she was also having some issues prepping for this team. I'm not sure if there are related issues.

Have you had a chance to look at this? I didn't hear any questions about it yesterday.

Thanks!

@lijenn @staceypark

**Comment by lijenn** [comment]
@jamesmrollins Getting the same Report Bug issue, looks like its related to the API?
Console:
![image](https://user-images.githubusercontent.com/59668647/126343967-f12331b2-b94a-464b-a80e-bc04a7bd5fa8.png)
![image](https://user-images.githubusercontent.com/59668647/126344023-c3ab82c1-84cf-40fe-8d0a-679e2e965334.png)

**Comment by jamesmrollins** [comment]
Hi @lzim.  Please see my follow up questions below.

- [ ] Are you in the office or at home when this happens?
- [ ] Do these issues persist or do they happen intermittently? 
- [ ] Are you using CITRIX or in a VPN connection when this happens?
- [ ] Can you attempt to load in private mode? (there may be an organizational policy preventing this). If possible, next time this happens, attempt to load in private mode to see if there is a difference.
- [ ] Are you seeing these errors on your private laptop?

**Comment by lzim** [comment]
@jamesmrollins 
We discussed this at hq_workggroup on 7/22/21

FYI: Government Furnished Laptop for these tests from home - So RESCUE VPN
I haven't tried on my personal laptop nor tried incognito mode (since we can't use it on VA domain per @lijenn).

For me this was only, and persistently, showing up for one team on Wed & Thurs last week.
I was able to work during the same session afterward with a different team and did my testing in that world instead.
So, it seems world-specific across 4-5 days and not set-up specific.

**Comment by jamesmrollins** [comment]
@lzim 
Thanks for the additional information.  We will check out the world-angle on this to see if there may be a corruption issue of some sort.

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire - Looks like we may be having a world corruption issue we may need to explain or track down.  I am available Sunday night to confer with you.

**Comment by jamesmrollins** [comment]
@lijenn @lzim @staceypark The issue loading an _ind session should be resolved.  We evidently had some remaining world_id code that was interferring with loading the session.  These have been corrected in PROD.  

Regarding the Community not passing the bug, that remains a communication error.  We may need to consider changing the error message to let the user know that, "We were not able to contact the Community message server, please try again later."
