### ISSUE TITLE
BUG Sim UI - Sankey Alternatives Display issue

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2129]
@jamesmrollins 

I was running a few simulation alternatives in PSY and noticed this odd reduction in the number of patients displayed in the alternatives Sankey graphs. The Current run looks correct, but all the alternative displays are artificially reduced. 
Will you please take a look?

Thanks!

<img width="732" alt="sankey_issues" src="https://user-images.githubusercontent.com/7454688/126019239-8efa900c-31a3-4f77-ba09-fc74e0fb4297.PNG">
<img width="813" alt="sankey_alternatives_issues" src="https://user-images.githubusercontent.com/7454688/126019240-0d8d7463-2e96-46bb-8fe2-91e598753cbd.PNG">

**Comment by dkngenda** [comment]
@jamesmrollins any updates on this?

**Comment by jamesmrollins** [comment]
@dkngenda I'm not sure what the issue is based on the graphs displayed above, but I will investigate, test and update this thread by the end of the day.

**Comment by jamesmrollins** [comment]
@hirenp-waferwire please see the diagram below and investigate cause and solution.

## Problem

1.  The sankey popup only shows proper run results for the bar chart of the current run.
2.  Alternatives that are selected return numbers that do not make sense. 
3.  It appears the recall of values from saved experiments are incorrect or corrupted somehow.

## Findings

1.  The current experiment and alternative 1 have exactly the same bc settings (all are default)(see first figure).
2.  The alternatives 2 and 3 have changes to experimental sliders that change outcome trajectory (see second figure).
3.  I exported experimental values and they are somehow the same for sankey bars in all alternatives.  
4.  These runs were conducted in PROD.
5.  I exported a couple of the experiments and the Sankey data is the same (see figure 3).

### Figure 1

![image](https://user-images.githubusercontent.com/30132017/126849237-2dbb68d7-e7f7-4917-82af-a888452c2be4.png)

### Figure 2

![image](https://user-images.githubusercontent.com/30132017/126849337-0c464fb4-23f7-4011-abe6-7988550059df.png)

### Figure 3

![image](https://user-images.githubusercontent.com/30132017/126849531-7f756b29-5fb5-459f-96b7-d230ee1866b5.png)

**Comment by jamesmrollins** [comment]
@lijenn @lzim @staceypark   This is fixed and available in PROD.
