### ISSUE TITLE
NEXT VERIFY DATE: feature_req definition Automatic simulation naming

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#2134]
### Check off requirements to verify progress through feature_tracker.
- [ ] 1. **DEFINE in work_breakdown**
  - [ ] a. **what & why** - **written definitions of requirements** in a **numbered checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** requirement definitions an **existing team meeting.**
  
Would it be feasible for the sim to automatically name each experiment for us based on settings?

  Task Cards:
  #
---
- [ ] 2. **DESIGN** in **operations_to_do** and **research_to_do**
  - [ ] a. **what & why** - **_MVP_ of design** of requirements in a **algorithm map, wireframes or design** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** design **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 3. **DEVELOP** in **under_development** - "frozen"

  Task Cards:
  #
---
- [ ] 4. **TEST in functional_test**
  - [ ] a. **what & why** - **TEST requirements** using **testing_checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** via TEST **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 5. **PROD in done**
  - [ ] a. **what & why** - **_DOCUMENT_ feature** using **document_tracker** for the **5 D's.** 
  - [ ] b. **date & who** -  **DELEGATE**
    - [ ] **describe_learners** [Jenn & Rita]
    - [ ] **detail_facilitators** [Jane & Debbie]
    - [ ] **document_team** [Anthony]
    - [ ] **disseminate_scientists_va** [Anthony]
    - [ ] **depend_products** [hq & ees]
  
  Task Cards:
  #
---
- [ ] 6. **closed** - fully documented, trained and ready for the next release.

**Comment by jamesmrollins** [comment]
Hi @branscombj - I distantly remember answering this before, and I don't think we can autosave.  **BUT** I am going to ask again since our capabilities are continually evolving.

**Comment by lijenn** [comment]
@jamesmrollins Here is Jane's ticket for the automatic experiment naming :)

**Comment by jamesmrollins** [comment]
@lijenn @branscombj  I have cross referenced these cards.

**Comment by staceypark** [comment]
duplicate. closing 8/5 hq meeting
