### ISSUE TITLE
wk3 sep_epic randomize survey measures 

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#2136]
randomize the order of the measures: some randomization exists but unsure if it works for our cases. need to test - update: randomization is for selecting records post completion, not for presentation to user. another option is to create 6 versions (all permutations, exclusive of demo) or 24 versions (all permutations, inclusive of demo) of the survey and use R to randomly assigned balanced for trial/arm and cboc/vamc.

**Comment by lzim** [comment]
@staceypark Plans to discuss this at Wed 11AM quant_workgroup.

FYI: @mnallajerla @dkngenda & @lijenn

**Comment by staceypark** [comment]
### 9/22 quant_research meeting
**What's been done**
We already sent out the same one version of the baseline survey to NIH Wave 1 MTL Red & MTL Blue.

**We are trying to correct for:**
- order effects (does the order of our measures influence later responses)
- response bias/attrition (forms of missing data bias)
- design effect biases - do not need to concern about this


**DECISIONS**
1. We want to randomize the order at the instrument level
2. Simple randomization of the instruments at each measurement occasion (by trial, wave, and baseline/6mos).

- NIH Wave 1 baseline - 4 instruments 
- NIH Wave 1 6 mos - 8 instruments 
- VA Wave 1 baseline - 3 instruments
- VA Wave 1 6 mos - 11 instruments
- NIH Wave 2 baseline
- NIH Wave 2 6 mos
- VA Wave 2 baseline
- VA Wave 2 6 mos

**Comment by dkngenda** [comment]
@staceypark @lzim @lijenn 

This is the randomization scheme I generated for the surveys. I used the survey plan in the grants to identify baseline and 6-month surveys
[survey_randomization.xlsx](https://github.com/lzim/teampsd/files/7214195/survey_randomization.xlsx)

**Comment by staceypark** [comment]
Need to be implemented in #1693
