### ISSUE TITLE
MTL Live Guides, in-session exercises, and session worksheets

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#214]
I'm creating this as a separate issue from #206 for things that pertain to MTL Video/Live but not to EES.

There are 12 MTL Live Guides [here](https://github.com/lzim/teampsd/tree/master/mtl_facilitate_workgroup/mtl_live_guide). Questions about these:

1. Should the title in these be as showing currently: 
       **Today we're modeling to learn how to align our team vision.**
- or as showing in the EES brochures:
       **_Modeling to Learn_ how to align our team vision.**

2. Shouldn't the **Done** content at the beginning of each session be exactly the same as the **Do** content at the end of the previous one? If so, I would like to take that content from the [Fidelity Checklist](https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/mtl_fidelity.Rmd) and update all the Live Guides with it. OK?

more to come, but those 2 were top for the moment.

**Comment by lzim** [comment]
**Following from Today's Meeting:**

**_We have two related issues:_**

MTL Live and MTL Video EES Master Brochures & Post-Test #206
https://github.com/lzim/teampsd/issues/206

MTL Live Guides, in-session exercises, and session worksheets #214
https://github.com/lzim/teampsd/issues/214

@branscombj and @dlkibbe 
**NEED to DOUBLE-CHECK and ALIGN the Fidelity Checklist, Sesssion Guides and the Pre- and Post-emails**

**Fidelity Checklist:**

https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/mtl_fidelity.Rmd

**Live guides:**

https://github.com/lzim/teampsd/tree/master/mtl_facilitate_workgroup/mtl_live_guide

**Pre-emails:**

https://github.com/lzim/teampsd/tree/master/mtl_facilitate_workgroup/pre_post_emails/pre_emails

**Post-emails:**

https://github.com/lzim/teampsd/tree/master/mtl_facilitate_workgroup/pre_post_emails/post_emails

**Comment by lzim** [comment]
@branscombj and @dlkibbe when drafting embed the icons for what you are describing from https://github.com/lzim/teampsd/tree/master/resources/icons

**Comment by staceypark** [comment]
**MTL STANDARD STYLE/TERMS for guide language, etc:
DECISION: Use "section" for all areas of the MTL sim UI that have a blue bar at the top.**

1. Never omit the title that already exists in the blue bar
2. If you are able to communicate which section is being indicated without using "section" that is fine - i.e. "Navigate over to Experiment Maintenance and ...."

Only exception is "Model Diagram" which is one part of the "[Model Name] Main Section"

@jamesmrollins Is asking if the word "Section" needs to be appended to the end of the title in the blue bar in the Sim UI.  I believe our decision to use "Section" only refers to language for the guides and brochures, **NOT any changes in the Sim UI.** ----- @lzim can you confirm?

**Comment by branscombj** [comment]
@lzim @staceypark @dlkibbe @ericasimon @jamesmrollins  
I hope the decision was confirmed not to include the word "section" in the blue bars. And (see 3 reasons in in #215) I advocate that we not capitalize the word "section", only the titles that are in the blue bars and Model Diagram.

**Comment by jamesmrollins** [comment]
@branscombj 
Hi Jane - "section" not included in model diagram, nor in the title bars of the sections.

**Comment by branscombj** [comment]
See if we're on track with [these say files](https://github.com/lzim/teampsd/tree/master/mtl_facilitate_workgroup/mtl_live_guide) 
There are more in progress. Also would appreciate help reviewing sessions 11 and 12 to finalize those learning objectives and in-session exercises, and reviewing the post-test questions. (But those should probably have been done after the Say files.) Thanks!

**Comment by dlkibbe** [comment]
I added say files for sessions 1 and 4 to the same location as Jane's say files. 
@branscombj @lzim @staceypark @TomRust @dlounsbu

**Comment by branscombj** [comment]
@lzim @dlounsbu @dlkibbe I have a proposal about qhfd text - it may be what you had in mind already. I suggest that after session 4, facilitators create and save a "run" with notes from the MTL Menu team need/plan discussion of session 4 in the Text section. Without adding something to the naming menu for this, facilitators can just go in after and rename it to something like "team_need_and_plan". This will give team a reference during Systems Story (session 6) and starting text for when they prepare to run exp 1 (session 8 - eight wks later). It will also model the use of qhfd for making mental models explicit (although negatively model saving incomplete work). 
Fidelity Check can use the partially complete run as an indicator. 
Would be even better to do it in-session, but it's freshest right at the end of session 4 and there's plenty to do in-session during 5 (Data Table), 6 (Systems Story), and 7 (bc).

**Comment by lzim** [comment]
All please note, following our meeting yesterday that the MTL Video _and_ MTL Live 
- learning SEE guides are now here:
https://github.com/lzim/teampsd/tree/master/mtl_facilitate_workgroup/learner_see

_and_

- facilitator SAY scripts are now here:

https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/facilitator_say/README.Rmd

**Comment by branscombj** [comment]
@staceypark @lzim I notice the Learning Objectives icon link is  broken in the [facilitator say ](https://github.com/lzim/teampsd/tree/master/mtl_facilitate_workgroup/facilitator_say) files - did it move?

**Comment by lzim** [comment]
It shouldn’t have moved...@staceypark can you help?
