### ISSUE TITLE
wk4 jul_epic task: PBI MVP for Data UI ClinicSelection and SPReferral  

### ISSUE THREAD

**Issue by anazariz** [lzim/teampsd#2140]
**PBI MVP for Data UI ClinicSelection and SPReferral**  

To minimize rework of documentation, create an MVP in PBI that resembles (as closely as possible) the current look and functionality of the ClinicSelection and SPReferral tabs.

**Comment by lzim** [comment]
Note @anazariz 

It appears this task card is a duplicate of #2112 focused on the review of the _Modeling to Learn_ videos to develop an MVP of the "ClinicSelection" and "SPReferrals" functionality in Power BI.

Cross-ref #1961

**Comment by lzim** [comment]
Closed because it's a duplicate of #2112.
