### ISSUE TITLE
wk4 jul_epic: Develop Pre/Post/Intersession Checklist for Infinite Scroll on Dynamics

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2141]
Idea was brought up on Wed. 7/21 CRM Meeting for an infinite scroll checklist to document the progression of team notes

**Comment by lzim** [comment]
Discussed wk2 aug_epic meetings.

Liberty has a plan to implement in QA for us to refine further from there.
Added the cell for tracking the # items complete of the # of session items.
