### ISSUE TITLE
dec_epic MTL FEATURE: MTL VA RED Say/See Guides

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2142]
**Discussed on Thurs. 7/22 HQ WG.**
**Updated at Support Workgroups 9/15/21**

wk2 sep_epic - DEV @lijenn > @lzim 
- Discuss further after hq_workgroup 9/16/21 at 4PM
wk3 sep_epic - TEST - **facilitate_workgroup** ready by COB 9/23 for covering at 9/28 Facilitate
wk1 oct_epic - PROD @lzim 

@lzim @lijenn Discussed that the See guides currently on mtl.how will remain the same for content and folder structure. 

But we will need to add VA Red prompts in the Say guides for team tailoring.

**Comment by hnorthcraft** [comment]
#adjudicate_memo efforts tracked on other cards, adding dup label
