### ISSUE TITLE
wk2 sep_epic feedback acceptance: update methods section

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#2143]
Revise methods section and upload here: https://osf.io/2u4ja/wiki/04_methods/

**Comment by staceypark** [comment]
@dlkibbe Knowing that you'll be out Thurs-Fri, wanted to ping you and see if you had any updates?

**Comment by staceypark** [comment]
@dlkibbe do you have an update on this?

**Comment by lzim** [comment]
@dlkibbe Will you ping me please, when you post this to OSF?
I'm going to work on collating the sections Intro, Methods, Results toward the end of the week to star the Discussion section. since Dexter should be done with boards next week and ready to help support this through submision :smile_cat:

**Comment by dlkibbe** [comment]
@staceypark the method section has been uploaded to osf as a word file and in the wiki pages. It is also attached here. The last paragraph in the methods section needs lots of work to document the analysis of the coding - I don't have enough qualitative manuscript writing experience to put the correct scientific framing here. Thank you for your patience.
[Methods_Feedback_Acceptance.docx](https://github.com/lzim/teampsd/files/7200056/Methods_Feedback_Acceptance.docx)

**Comment by lzim** [comment]
@dlkibbe posted this and it was discussed via email.

Next step is @lzim synthesizing contributions.

Closing this issue task.
