### ISSUE TITLE
2023 r21_qual_mtl_fidelity: participatory methods template is next step

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#2144]
Review the updates that Kathryn made and update the intro section: https://osf.io/q9wsa/wiki/03_introduction/

**Comment by lzim** [comment]
@teampsdkathryn @swapmush @dlounsbu @staceypark 

Following up on work in oct_epic - 

- [x] Participatory Fidelity Figure for contributions (Research, DEV, OP) - @lzim used this manuscript as the example.
- [x] Over last few weeks Lindsey, Kathyn & David outlined the key takeaways for the Discussion section 
- [ ] Awaiting Methods section outline on the who, when, why, how
- [ ] Synthetic edits - to drafted sections.

**Comment by lzim** [comment]
_Next Steps:_

**DECISION:**
- [ ] Meet wk2 mar_epic #manuscript_monday @lzim @dlounsbu & SWS.

**Comment by dlounsbu** [comment]
Fidelity to strategy key paper: Eisman et al.
