### ISSUE TITLE
NEXT VERIFY DATE: SIM UI Feature - See graphs of prev. experiment without re-clicking Run button

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2145]
Request: Be able to view the graphs and 2 year results in a past experiment without having to re-click Run button.

### Check off requirements to verify progress through feature_tracker.
- [ ] 1. **DEFINE in work_breakdown**
  - [ ] a. **what & why** - **written definitions of requirements** in a **numbered checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** requirement definitions an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 2. **DESIGN** in **operations_to_do** and **research_to_do**
  - [ ] a. **what & why** - **_MVP_ of design** of requirements in a **algorithm map, wireframes or design** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** design **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 3. **DEVELOP** in **under_development** - "frozen"

  Task Cards:
  #
---
- [ ] 4. **TEST in functional_test**
  - [ ] a. **what & why** - **TEST requirements** using **testing_checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** via TEST **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 5. **PROD in done**
  - [ ] a. **what & why** - **_DOCUMENT_ feature** using **document_tracker** for the **5 D's.** 
  - [ ] b. **date & who** -  **DELEGATE**
    - [ ] **describe_learners** [Jenn & Rita]
    - [ ] **detail_facilitators** [Jane & Debbie]
    - [ ] **document_team** [Anthony]
    - [ ] **disseminate_scientists_va** [Anthony]
    - [ ] **depend_products** [hq & ees]
  
  Task Cards:
  #
---
- [ ] 6. **closed** - fully documented, trained and ready for the next release.

**Comment by jamesmrollins** [comment]
Hi @lijenn and @branscombj - You should **NOT** have to click run to see the results of experiments on the Outputs and Text pop up.  When you choose the experiment from the alternatives dropdown, it should re-render the screen and show you the results.

**Comment by staceypark** [comment]
hq meeting 8/5 @lijenn will clarify conditions & possibly screenshots with @branscombj

**Comment by lzim** [comment]
Discussed a **facilitate_workgroup** - We CAN do this in the Results Dashboard.
