### ISSUE TITLE
wk1_Nov_epic : SIM UI Feature - Hard to see graph trendlines when it's at 1 or at 0

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2146]
Request: Clearly see where the line in the graph is, sometimes hard to see when it's at 1 or at 0 or unsure if there is someone at 1 or 0.

### Check off requirements to verify progress through feature_tracker.

- [ ] 1. **DEFINE in work_breakdown**
  - [ ] a. **what & why** - **written definitions of requirements** in a **numbered checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** requirement definitions an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 2. **DESIGN** in **operations_to_do** and **research_to_do**
  - [ ] a. **what & why** - **_MVP_ of design** of requirements in a **algorithm map, wireframes or design** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** design **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 3. **DEVELOP** in **under_development** - "frozen"

  Task Cards:
  #
---
- [ ] 4. **TEST in functional_test**
  - [ ] a. **what & why** - **TEST requirements** using **testing_checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** via TEST **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 5. **PROD in done**
  - [ ] a. **what & why** - **_DOCUMENT_ feature** using **document_tracker** for the **5 D's.** 
  - [ ] b. **date & who** -  **DELEGATE**
    - [ ] **describe_learners** [Jenn & Rita]
    - [ ] **detail_facilitators** [Jane & Debbie]
    - [ ] **document_team** [Anthony]
    - [ ] **disseminate_scientists_va** [Anthony]
    - [ ] **depend_products** [hq & ees]
  
  Task Cards:
  #
---
- [ ] 6. **closed** - fully documented, trained and ready for the next release.

**Comment by jamesmrollins** [comment]
Hi @lijenn and @branscombj - A picture is worth a thousand words!  😁

**Comment by lijenn** [comment]
@jamesmrollins Here's an example!
 Not at 1 or 0 on these graphs, but it really has to do with the colors and how it's hard to tell where the line is, especially for the trend lines at the minimum on the y-axis. It's just a part of the x-axis line or if it's actually the minimum # on the y-axis. 
See Psych - Patients in Service here:
![image](https://user-images.githubusercontent.com/59668647/127186377-671ac6a0-88db-4057-ba15-dcbbd537ea42.png)

**Comment by jamesmrollins** [comment]
From HQ Meeting 8/5.  

- For the minimum "x" axis, it should be one unit below the lowest value.
- Is there a "jitter" function that will allow two lines, one over the other.

**Comment by jamesmrollins** [comment]
Hi @lijenn - as per conversation with @hirenp-waferwire last night, the graphs depicted above do not show the trend line on top of the axis line, which may be reason they are difficult to see.  So it might be a bug.  We are going to investigate and also consider other ways to make line more visible.

**Comment by jamesmrollins** [comment]
@lijenn can you tell me which group that you produced the graph results above.  We want to take a closer look at it.  Feel free to put it into Teams and I will communicate to DEV.

**Comment by jamesmrollins** [comment]
Hi @lijenn and @lzim ,

## BLUF

We didn't hear back from the developers of the chart widget - we developed a color option that may solve the problem.

## Change X and Y Axis from VA Dark Blue to VA Grey

![image](https://user-images.githubusercontent.com/30132017/140182861-2e226098-a306-42fd-a7ca-c96f0e422af2.png)

**Comment by branscombj** [comment]
Good fix! I also wondered about having some lines dashed etc., but I'm not sure they'll show well on top of each other. I vote go with the above!


![image](https://user-images.githubusercontent.com/29778290/140232359-96966544-7216-4a6f-b2f2-dc8931666458.png)

**Comment by jamesmrollins** [comment]
**Decided:** Go with MVP.

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire -  The solution above has been released for DEV.
