### ISSUE TITLE
wk1_story_13: Develop a DEV/TEST/PROD Pipeline Process for PowerBI

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2159]
## Description
Develop a procedure that describes how to create development and test "branches" within PowerBI that enable testing, quality control and protect the production version of PowerBI.

**Comment by jamesmrollins** [comment]
## As discussed in the TeamTime Meeting 8/3 1 PM

See Chat in VHA Power BI Meeting from Monday, 7/26.  Specific instructions suggested for structuring the Power BI workspaces by data, viz and params and generalizing slicer and other PowerBI functions across the workspaces.  Also emphasizes certain constraints:

- Can't bring more than one data model together
- Can only bring datasets/workspaces together
- One dataset per workspace

**Comment by jeffhoerle** [comment]
I discovered that Power BI Pipelines can only be provisioned by BISL.  I submitted a request to have one created for our project on Friday.  I expect to have response by tomorrow or Wednesday.
