### ISSUE TITLE
GitHub questions

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#216]
I am still missing some detail on pull requests.

**How to find the chance to compare my branch to master**

I think what I know now is that you have to either (a) be IN the branch to get the "compare" button, and it's kind of inconspicuous:

![comparingtomaster](https://user-images.githubusercontent.com/29778290/46720837-9505ee80-cc3f-11e8-9dba-36443db47dce.png)

OR (b) you can go to the Pull Requests tab (which automatically kicks you back up to the master branch, by the way) and click to Open a New Pull Request. This brings up a Compare automatically and you can replace Master in either side of the compare with the branch you want to check on: 

![pullreqcompare](https://user-images.githubusercontent.com/29778290/46721427-f37f9c80-cc40-11e8-9e00-52314b007528.png)

**How to merge changes from master into my branch to get it into sync**

Now what I can't find is how I update my branch with changes others have made to the master. I see that the branches are Able to be merged - it even says they can be "automatically" merged -- but how? 

![abletomerge](https://user-images.githubusercontent.com/29778290/46721606-66891300-cc41-11e8-9836-b47d4f0ad90e.png)

**Comment by branscombj** [comment]
Output question:

Could someone instruct me on how to output files from GitHub in the various formats we’ve coded them for (Word or PPT in particular). I need to print out the various facilitation documents in order to efficiently compare across them and mark for corrections.

I’ve tried googling it and I searched the [GitHub help page](https://help.github.com/) but haven’t found anything on this.

I can copy and paste into Word, but it doesn’t render perfectly for page size (far less so for PPT) – and also I'm hoping for a way to do it in batch.

**Comment by lzim** [comment]
Hi @branscombj thanks for asking, I've added @ericasimon too.

The key thing to do is to always begin every work session with the **third image** you posted from the **pull request** menu. The short answer to your question: ***Pull requests are how you stay current with others' work on the master.*** 

First, you start the new pull request by clicking the "New pull request" green button on the screen:
![pull_request1](https://user-images.githubusercontent.com/7454688/46744303-b7a7ff80-cc5f-11e8-8466-5ea947fa80de.png)
![pull_request2](https://user-images.githubusercontent.com/7454688/46744306-b971c300-cc5f-11e8-8811-65dced35eb04.png)

Second, you have to complete the pull request by clicking the "Create pull request" green button on the screen 

**Always begin every work session by either:**
a) **starting a new branch** that you can compare to master via the start of the pull request process - it will be 100% consistent when you begin. **Note** that comparing branches doesn't actually complete the pull request it just helps you check for differences. 
b) **OR if you have a branch with open pull requests,** then you simply go do the same pull request compare branches menu, and do the same. **Note** that you always are pulling the branch on the right into the one on the left.

**The more detailed Team PSD screenshot tutorial for this process is in Team PSD Resources like other Github help, regarding resolving Conflicts, etc.:**  https://github.com/lzim/teampsd/tree/master/resources/github_guide/pull_requests
