### ISSUE TITLE
wk2 sep_epic facilitator fidelity surveys for VA Red

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#2160]
Given that VA Red is 12 sessions and we are sending out Partner/Build/Apply tailored pre/post emails (#1176), we will probably want the facilitator fidelity rating form to match that structure as well. 

Below are the current Partner/Build/Apply set of questions. I think these can work for VA Red with the exception of Apply?
@lzim @branscombj @dlkibbe Thoughts?

![image.png](https://images.zenhubusercontent.com/5e4c08b27596bf43c56647e4/b0be7b5f-3e42-49f6-a952-226f5d70bc1f)
![image.png](https://images.zenhubusercontent.com/5e4c08b27596bf43c56647e4/1c96cc74-813d-41f3-ad10-020e911740a9)
![image.png](https://images.zenhubusercontent.com/5e4c08b27596bf43c56647e4/221eb00f-c302-4073-a8ff-f00dec9d40bc)

**Comment by branscombj** [comment]
> Given that VA Red is 12 sessions and we are sending out Partner/Build/Apply tailored pre/post emails (#1176), we will probably want the facilitator fidelity rating form to match that structure as well.
> 
> Below are the current Partner/Build/Apply set of questions. I think these can work for VA Red with the exception of Apply?
> @lzim @branscombj @dlkibbe Thoughts?
> 
Yes, I think all except ApplyQ1-4 can work. I wonder how we will facilitate VA Red sessions, in particular how much we will tailor sessions with the data tool to the Partner-Build-Apply phases? I could see Apply questions 1-4 somewhat paralleling those for Blue - but if we facilitate toward something like you see in these draft questions, then we'd be leaning toward systems thinking, which might muddy the study. 
A-Q1. We helped the team consider the problem at hand in terms of multiple, interrelated variables.
A-Q2. We helped the team consider what causes cyclical trends they see in their data.
A-Q3. We helped the team consider how decisions they make might affect trends in team variables over time.
A-Q4. We helped the team consider time delays between when a problem arises and when they become aware and are able to respond to it.

**Comment by branscombj** [comment]
@lzim @staceypark Is there a typo in Apply Q1 ("at hand as in terms")? It's a difficult read.

Also it's helpful above to have the questions color-coded to reflect team vs. facilitator perspective. If there's a way to make this clearer in RedCap that would be great. I can't seem to always remember.

**Comment by lzim** [comment]
@staceypark @branscombj 

I'm not sure if this will muddy anything as the aim 1 comparator arm for the VA trial is usual quality improvement and the aim 2 mechanism of change are the participatory constructs, not systems thinking (that is for the NIH trial).

We know we'll be spending a lot more time on part 1 (six sessions) and part 2 (six sessions), so I'm wondering if what we want to do, is simply cover the partner items for 6 sessions, and cover the build items for 6 sessions. Thoughts?

**Comment by branscombj** [comment]
> @staceypark @branscombj

> We know we'll be spending a lot more time on part 1 (six sessions) and part 2 (six sessions), so I'm wondering if what we want to do, is simply **cover the partner items for 6 sessions, and cover the build items for 6 sessions.** <--- Yes, that!

**Comment by lzim** [comment]
@staceypark 
I think this was a DECISION:
PARTNER for 6 sessions
BUILD for 6 sessions
Note: this should apply to both co-planning and teams.

What else do you need?

**Comment by lzim** [comment]
@staceypark  What is this?
Can this be closed?

**Comment by lijenn** [comment]
This was completed, closing now.
