### ISSUE TITLE
wk1 sep_epic story_13: Premium App for Power Automate and Flow

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2165]
We are going to need a premium app (Microsoft Gov term - VA distinction to make it accessible to the team and VA) to get Power Automate & Flow to set up workflows - Reach out to Melanie.

@lijenn Can be used to OHIO our permission for PBI and Dynamics.

**Comment by lzim** [comment]
@lijenn  Do you mind replying to the thread with Melanie about this?

She pinged me via Teams to say she wanted to get on my calendar to check on Dynamics, so it might be particularly timely if you sent her a simple re-ping. Thanks!

**Comment by lijenn** [comment]
Scheduled for wk4 aug_epic on Thurs. 8/26.

**Comment by lzim** [comment]
Met w/Melanie and are working with her now re: Story 6 Dynamics UAT
