### ISSUE TITLE
wk2 aug_epic: story_6 UAT CRM 6.5 Configure Versions: Step 4 & 5 - Unable to view/fill out the fields in the Version & Session forms & VersionLevelEmail form.

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2166]
1. **Who encountered the bug:** Jennifer Li

2. **Which instance are you testing in?:** QA

3. **Date/Time of the bug:** 8/5/2021 around 6:20p Pacific.

3. **Role:** Admin

4. **Detailed description of the bug:** 

### Step 4 - Version & Session
When clicking on "New Version Checklist" in a Version titled "Live Red" that I created, I only see the "Name" and "Owner" field.
 I do not see anything else to fill out in the form that was mentioned in the guide (I only see fields 6.5 Steps 4.b.i. and 4.b.x, other fields in-between are missing).

1. I go to Version, added a new Version titled "Live Red". Program is Red, Evaluation is NIH.
2. Click on "Live Red" > click "Checklist & Session Details" tab > click "+ New Version Checklist"
3. Only able to fill out "Name" as "NIH Live Red Checklist". 
![image](https://user-images.githubusercontent.com/59668647/128466214-05c1d005-eaab-4f62-8221-5a541a7c9058.png)

Note: I'm also unable to fill out the "Phase", "Task", and "Session" column after I click "Save" and/or "Save & Close". 
The row gets greyed out and I see a "Activate" and "Deactivate" button on the top right of the column:
![image](https://user-images.githubusercontent.com/59668647/128466302-ab9b5bca-e2db-4951-9692-cfce3a82cbec.png)

Same bug when trying to fill out the New Session Detail form (missing fields mentioned in steps 4.f.ii - 4.f.ix):
![image](https://user-images.githubusercontent.com/59668647/128466503-cd924f35-d9a4-4fd1-8c01-a8368017b79c.png)
![image](https://user-images.githubusercontent.com/59668647/128466596-0995e845-4176-455c-a913-aafff3b584f6.png)

### Step 5 - Email Templates
Same bug for this, I only see the "Name" and "Owner" field when going to the "Email Templates" tab > "+ New VersionLevelEmail" form and unable to edit the fields I see on the grid after saving the name:

![image](https://user-images.githubusercontent.com/59668647/128467678-65cc93ed-74aa-4a82-9201-d8f6f0adb7f6.png)
![image](https://user-images.githubusercontent.com/59668647/128467791-141d0300-223f-4897-8236-d59e95455268.png)

**Comment by hsnyder2** [comment]
Thanks @lijenn .  I was able to reproduce.  Arlene's adjusted security settings so that all issues above should now work for you in QA.  You should be able to re-open Live Red Version and see all fields for the Version setup, including all fields for records created on all its associated tabs.  Can you confirm?  Thank you!

**Comment by lijenn** [comment]
Working now, thank you!
