### ISSUE TITLE
wk1 ASAP Sim UI BUG - Edits to team data table file in Team Data Dropdown Maintenance make changes across all individual worlds

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2167]
Identified in Test and also found in Prod on Friday 8/6/2021:

When adding a team data table file, deleting the file, and renaming the file, these actions will be reflected in all individual worlds that share the same team root (e.g. When a user deletes a file in their indiv world, the file will also be deleted in everyone else's indiv. world).
![image](https://user-images.githubusercontent.com/59668647/128569996-2408b6c8-8fa5-4b8d-8ff9-2b794792d624.png)

James is working with Dev to resolve this by Sunday 8/8 night.
Future recommendation is to remove this section completely since our new feature to auto-populate the team data #2148.

FYI @lzim @staceypark, we should discuss this on Monday 8/9 8am WG leads

**Comment by lzim** [comment]
Discussed at 8AM workgroup leads and confirmed this is not a BUG.
But, does require training, which we will cover at Facilitate Workgroup tomorrow.

@lijenn @staceypark @jamesmrollins Can we close this?

**Comment by lijenn** [comment]
Agree to closing, will need to add this in our existing documentation.
Tracking that effort in #2174
