### ISSUE TITLE
wk2 sep_epic wed 9/15  review and update results section on r21_qual_mtl_fidelity

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#2171]
take a second pass at r21_qual_mtl_fidelity results section before qual meeting: https://osf.io/q9wsa/wiki/05_results/
fyi: Swap out wk2 aug_epic

8/31 team time meeting: @swapmush will create a table of the count of participatory codes by code per session per team for the train data set

**Comment by lzim** [comment]
Hi @swapmush Did you review this section and upload the latest?
If so, @staceypark  I believe we can close this.

**Comment by lzim** [comment]
@swapmush posted to OSF and this card should have been closed. 
Working on the participatory methods section in support of the disucssion.
