### ISSUE TITLE
wk2 aug_epic: UAT Feedback - Deleted a MTL Team in Live Red, Adding a new MTL Team leads to an Invalid Argument & Duplicate Name Error

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2175]
1. **Who encountered the bug:** Jennifer Li

2. **Which instance are you testing in?:** QA

3. **Date/Time of the bug:** 8/10 at 7:04 AM

3. **Role:** Admin

4. **Detailed description of the bug:** Insert a description of the bug, add screenshots, and steps to reproduce. If following steps on the UAT script/guide, note which specific step.
 - Created Version: Live Red
 - Added a coplanning group
 - Added a MTL team in the coplanning group
 - Deleted the MTL team in the coplanning group 
 - Tried to re-add the MTL Team with the same name (get duplicate name error, can we delete a team and then re-add the team with the same name?)
![image](https://user-images.githubusercontent.com/59668647/128882469-e3758230-0664-4bf3-b43d-72f6dc1ccb11.png)
- Tried to re-add an MTL Team with a slightly different name (invalid argument error)
![image](https://user-images.githubusercontent.com/59668647/128881309-0f1feff1-5e3b-48cc-ada3-da6d099dca69.png)

I get this error when trying to add any MTL Team in the Live Red version.

**Comment by hsnyder2** [comment]
@lijenn Can you provide the **name of the team** you supplied that resulted in the error above?  And there may not have been one (I don't see it in the error message but you might have to scroll down) but if there's a link to a "log file" can you download and supply that as well?  Thx!

**Comment by hsnyder2** [comment]
FYI, per our call with @lijenn just now, Arlene will look for an existing (in the background) D365 Team and re-associate the new MTL Team with the old D365 Team (that had the same name).  Any D365 Teams whose MTL Teams were deleted will remain in the system and become orphaned if a new MTL Team with the same name is not recreated.  Should be a rare, so consensus was that this is okay.
