### ISSUE TITLE
wk2 aug_epic: UAT Feedback - Unable to find/add non-parent Facility for Associated Facility field for MTL Teams

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2176]
1. **Who encountered the bug:** Jennifer Li

2. **Which instance are you testing in?:** QA

3. **Date/Time of the bug:** 8/10 10:22am Pacific.

3. **Role:** Admin

4. **Detailed description of the bug:** 
- Created a MTL Team
- Tried to search for a non-parent Facility (e.g. 123GG) in the Associated Facility field
- Only shows the Parent Facility (e.g. 123)
- Tried going to the non-parent Facility in Facility or Clinics and checked that it's there and re-saved it
- Looks like the non-parent Facility now shows up as Most Recent 
- Able to add the non-parent Facility (Note: non-parent Facility still does not show up from typing it directly).

Any way we can get the non-parent to show up from searching for it?

I will add screenshots on the Teams discussion since we don't want to show Team names/station numbers on Github.

**Comment by hsnyder2** [comment]
Per @apisano0920 , this is fixed in QA and ready to retest.

**Comment by lijenn** [comment]
Bug fixed, thank you!
