### ISSUE TITLE
wk3 aug_epic: SIM UI TT Report 2 bug - On Edge: Stretched Graphs, distorted graphs after clicking export

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2178]
Identified by @lijenn for Jane & Marcia's team that meets on Thursdays at 8:30am Pacific 

@jamesmrollins I'll send you the team and file for this. It was exported from Edge. Also believe this is a Break Fix bug.
The Chrome version works great and will be using it for this team!

1. The last 2 pages of the report are stretched, 1 vertically, 1 horizontally:
![image](https://user-images.githubusercontent.com/59668647/129245245-8f6718cd-5d94-4148-a9fe-dedd02cd3512.png)
![image](https://user-images.githubusercontent.com/59668647/129245302-be12eb0c-81bf-4b51-80db-d9940af3ec0e.png)

2. Some of the graphs get distorted after clicking the PDF button to export it:
Before clicking export:
![image](https://user-images.githubusercontent.com/59668647/129245510-43997455-9875-4a8e-a317-0e81443d7730.png)

After clicking export:
![image](https://user-images.githubusercontent.com/59668647/129245416-423ad911-fb16-4bc2-b9d6-b6c7cfa68c2d.png)

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire .  See the problem reported above.  This appears to be happening in Edge only for some reason.  I will provide the tt report in teams for your reference. Please note the breakfix label.

**Comment by jamesmrollins** [comment]
Hi @lijenn .
@hirenp-waferwire  attempted to recreate the problem but it rendered properly.  He asked for you to try again, but ensure the browser zoom is set to 100%.  If you don't achieve proportional results, then please relate the browser version to us by clicking the three dots in the upper right corner, navigate to "help and feedback" and select "About Edge."

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire , 
- We conducted an experiment using Edge at 90% and got significant distortion in the PDF.
- We increased the zoom to 100% and that appeared to resolve the distortion issue.

**Comment by jamesmrollins** [comment]
Hi @lijenn .  This has actually been fixed.  But the fix is in TEST Slow.  It will update with the release at the end of the month.
