### ISSUE TITLE
Using R, R Studio and R Markdown - MTL Resources and Team PSD Manuscripts

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#219]
Hi Everyone,

Our quantitive and qualitative workgroups are going strong with this process already. I've cc'd the other workgroups who have questions about maximizing the power of our fully transparent, reproducible workflow. We are using GitHub for complete real-time version control. 

Below are instructions for using R, R Studio and R Markdown for the ability to immediately output files in multiple formats (e.g., .pdf, .doc, .html), etc.

**There are 4 steps.** 
The first 2 steps require a free download. 
The third step requires making sure you know how to use the RMarkdown using R Studio.
The fourth step requires opening and editing the .Rmd files in R Studio. **THIS IS ONLY SOMETHING YOU NEED TO DO AFTER ALL EDITS AND FORMATTING HAVE BEEN REVIEWED VIA THE PULL REQUEST PROCESS ON GITHUB."

**1. First, go to the Comprehensive R Archive Network (CRAN) https://cran.r-project.org to download R to your computer:**
![cran](https://user-images.githubusercontent.com/7454688/46744974-05713780-cc61-11e8-8bb3-680d6609f4cc.png)
You may never need to open R again. It will be the underlying language engine operating in the background on your computer.

**2. Second, go to R Studio downloads page https://www.rstudio.com/products/rstudio/download/ and download the free version of R Studio:**
![rstudio](https://user-images.githubusercontent.com/7454688/46745139-54b76800-cc61-11e8-8827-679d401bc4f1.png)
R Studio will be your home base. R Studio is a development environment that makes it much easier to manage your R workflow.

**3. Third, open R Studio on your computer so that you can edit and **knit** .Rmd (RMarkdown) files:
![rstudio2](https://user-images.githubusercontent.com/7454688/46745593-356d0a80-cc62-11e8-872f-62c0d6f72c1e.png)

**4. Finally, use the R Studio menu to open the .Rmd file that you would like to produce in a specific file format and click the knit button:**
![rstudio3](https://user-images.githubusercontent.com/7454688/46745999-f7bcb180-cc62-11e8-9ccc-60c1449bb1b4.png)

**Comment by branscombj** [comment]
Thanks! I was able to do this quite easily. The translation into Word was not perfect, but pretty close. It was so much easier for me - comparing 3 series of documents and marking them up on paper, then entering all those edits into the branch of my pull request.

**Comment by lzim** [comment]
@branscombj This is great news! I am so glad it was easy for you.

I have made several slide decks for presentation, .pdfs and .html web pages this way using .Rmd too.
This is going to reduce so much rework and make the best of the team's efforts available much more easily to so many more folks.

*A note about how awesome use of .Rmd is about to be (with some nerdy jokes referencing our log in [verb] and login [noun/adj] standard style decision @branscombj):*

The real payoff (noun) will come from the ability to edit together on GitHub from anywhere in the country with real-time (adjective) version control. And then, to be able to make sure edits get propagated throughout all our dependencies easily from the .Rmd code into (prepositional transformation) whatever format is needed immediately in real time (noun).
