### ISSUE TITLE
Error in date variable. Please see merge.R in data_scripts

### ISSUE THREAD

**Issue by joycepyang** [lzim/teampsd#22]
Despite attempting to use as.Date.character(x, ...) in order to change the format of DATE_1, the variable in our dropout data that we are using for date, I continue to get the error below:

> dropout2.df <- data2 %>% 
+   mutate(year = year(DATE_1), 
+                     quarter = quarter(DATE_1), 
+                    year_q = paste0(year, "-", quarter)) %>% 
+ group_by(sta6a,year_q) %>% 
+ summarise(obs = n()) %>% 
+ mutate(site_yq = paste0(sta6a,"-",year_q))
Error in mutate_impl(.data, dots) : 
  **Evaluation error: character string is not in a standard unambiguous format.**

Can anyone run my merge.R code in data_scripts and help me with debugging it please?

**Comment by lzim** [comment]
Hi Joyce,

Savet and I are reviewing the code, you need to create the R object for "DATE_1" because you are using lubridate commands on that variable and it is not specified.

For example,

mutate( DATE_1 = as.Date(DATE_1),

Year = year(Date_1),...)

**Comment by joycepyang** [comment]
Hi Lindsey and Savet, 

Thank you for addressing my help wanted/bug on github so quickly. I was excited to try the solution as you suggested; I did wonder if the as.Date change I was making on the DATE_1 variable was being made, but then not specified as an object. I'm unsure of how to specify it as an object though. When I tried your code addition, I was getting the same error.  Could someone try running my code below with the suggested addition to see if there are additional debugging suggestions?  I will also reproduce the error message below:

#set working directory
setwd("//vhapalmpncptsd1/Shared Research/TeamPSD/R")

#check working directory
getwd()

# Packages required for merging CDW and CPT
library(tidyverse)
library(magrittr)
library(rlang)
library (reshape2)
library(lubridate)

#set up both files as dataframes
file="comparatorsites_nov23_16.csv" 
data=read.csv(file,header=TRUE) 

file2="dropout.csv" 
data2=read.csv(file2,header=TRUE) 

comparator.df <- data
dropout2.df <- data2

#create combined variable in comparator df

comparator.df <- comparator.df %>% 
  mutate(year_q  = paste0(year, "-", quarter), 
         site_yq = paste0(sta6a,"-",year_q))

#attach the dropout df in order to work with individual variables
attach(dropout2.df)


#create combined variable in dropout2.df
dropout2.df <- data2 %>% 
  mutate(DATE_1 = as.Date(DATE_1),
    year = year(DATE_1), 
                    quarter = quarter(DATE_1), 
                   year_q = paste0(year, "-", quarter)) %>% 
group_by(sta6a,year_q) %>% 
summarise(obs = n()) %>% 
mutate(site_yq = paste0(sta6a,"-",year_q)) 

#######################################

##ERROR OUTPUT:

> dropout2.df <- data2 %>% 
+   mutate(DATE_1 = as.Date(DATE_1),
+     year = year(DATE_1), 
+                     quarter = quarter(DATE_1), 
+                    year_q = paste0(year, "-", quarter)) %>% 
+ group_by(sta6a,year_q) %>% 
+ summarise(obs = n()) %>% 
+ mutate(site_yq = paste0(sta6a,"-",year_q))
Error in mutate_impl(.data, dots) : 
  Evaluation error: character string is not in a standard unambiguous format.
>

**Comment by saveth** [comment]
Joyce,

Your DATE_1 is a factor, which has to be formatted as character then as a DATE object in R before you can use the "year" function on it. Also, sta6a should be STA6A. Here's fix for the code:

dropout2.df <- data2 %>% 
  mutate( DATE_1 = as.character(DATE_1),
          DATE_1 = as.Date(DATE_1, "%m/%d/%y"),
    year = year(DATE_1), 
         quarter = quarter(DATE_1), 
         year_q = paste0(year, "-", quarter)) %>% 
  group_by(STA6A,year_q) %>% 
  summarise(obs = n()) %>% 
  mutate(site_yq = paste0(STA6A,"-",year_q))
