### ISSUE TITLE
wk2 sep_epic: UAT BUG - Coplanning & MTL Team Email Template does not dynamically update the template browser size & Reached max. character fields from adding an image/logo

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2205]
1. **Who encountered the bug:** Jenn  

2. **Which instance are you testing in?:** QA

3. **Date/Time of the bug:** Thurs. 8/26 at 6:30pm Pacific

3. **Role:** Facilitator

4. **Detailed description of the bug:** Insert a description of the bug, add screenshots, and steps to reproduce. If following steps on the UAT script/guide, note which specific step.

This is in: v01_jenn_coplanning_email_group
- Began to edit the highlighted portions of the co-planning email template
- Copy and pasted my signature from an old outlook email into the email template
- Unable to scroll up or down in the template, the scroll also did not work when expanding the window of the template to pop-out

![image](https://user-images.githubusercontent.com/59668647/131057089-61cea8e1-92ef-4205-a7d7-1b296b59f9cd.png)

Here I'm trying to highlight the text below what is currently shown in the window, but I can't scroll down any further nor can I scroll up. Seems to be stuck/static here:
![image](https://user-images.githubusercontent.com/59668647/131057458-c8936732-d08b-43f7-9cc7-3e29a3c481e4.png)

**Comment by hsnyder2** [comment]
Arlene upped the Character limit for this issue (to 1,000,000, was 10,000).  Will need to retest after the change is moved to QA.

**Comment by hsnyder2** [comment]
Fix is in QA now.  (FYI, so is the new Session Validation functionality that requires Unique Session No.s.)

**Comment by lijenn** [comment]
@hsnyder2 I created a new Version (Live Red) and group "jenn_red_coplanning_group".
I tried to edit the coplan 1A email template in the group, but I think the window/browser for the template is still looking weird.
I'm able to scroll through all of it, but there seems to be a bit white space/chunk:

**Comment by lijenn** [comment]
The "combined email" for MTL Teams email templates seem to have the same browser window issue, unable to view the whole email, even using the scroll bar as I'm scrolled to the bottom:
![image](https://user-images.githubusercontent.com/59668647/132430700-d4995aaa-1bd1-428a-89ca-6d8f81494aa5.png)
