### ISSUE TITLE
wk4 aug_epic: UAT BUG - Current Session not updating for Group or Co-planning in Dashboard

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2207]
1. **Who encountered the bug:** Jenn

2. **Which instance are you testing in?:** QA

3. **Date/Time of the bug:** 8/27 4:30 pm Pacific

3. **Role:** Admin

4. **Detailed description of the bug:**

@hsnyder2 @apisano0920 It's my understanding that once some of the checklist items and all session details have been assigned dates, and setup complete is checked, the Current Session field for a Group or Team should start.
Note: I did not assign dates for all the Sessions in Teams, but I think I did for the Group.

Not sure if this is user error or an actual bug for this Group and this Team:
![image](https://user-images.githubusercontent.com/59668647/131199869-2968b3ac-affe-4d55-9512-14771f5b4bb8.png)
![image](https://user-images.githubusercontent.com/59668647/131199908-7df09b91-bcec-490b-b4ae-1dfdfdd95606.png)

**Comment by hsnyder2** [comment]
There are really 2 issues on this bug:
1. Arlene confirmed that the job did not run as designed and is identifying the cause for this. 
2. She ran it manually and the **Current Session** should have updated to Session 1A (checklist items not checked but assigned due dates were all in the past) but it updated to 1B.
