### ISSUE TITLE
wk5 aug_epic: UAT Bug - Blue Pre S01 Email Not Sending to Correct Emails (duplicate VA email instead of Gmail)

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2208]
1. **Who encountered the bug:** Jenn

2. **Which instance are you testing in?:** QA

3. **Date/Time of the bug:** Fri 8/27 10:30p

3. **Role:** Admin

4. **Detailed description of the bug:** 

- Set Team members to include the Pre S01 email (my VA and my gmail)
![image](https://user-images.githubusercontent.com/59668647/131221504-8af9c189-44e2-4b31-9355-07a5d93e0fc5.png)

- S01 email was only sent to my VA email (looks like it missed the gmail email and instead duplicated the VA email):
![image](https://user-images.githubusercontent.com/59668647/131221538-59b8363d-41bf-4005-b773-7baff28bcaa5.png)
![image](https://user-images.githubusercontent.com/59668647/131221627-9752b1b7-a16a-4d15-b5e6-578e4fcbbcb2.png)

**Comment by hsnyder2** [comment]
Arlene is investigating this.  Not sure why it's missing the 2nd Jenn Li (gmail) and adding Jenn Li VA email 2x to email w Subject "jenn2 blue pre s01 test CRM:00000001"
