### ISSUE TITLE
ICEBOX: D365 Prod Backlog (Bug) - Pre Email - Images/Logos still not loading by default

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2209]
1. **Who encountered the bug:** Jenn

2. **Which instance are you testing in?:** ~~QA~~ Prod

3. **Date/Time of the bug:** ~~Fri. 8/27 at 10:30p~~ Fri. 9/24 7:00am Pacific

3. **Role:** Admin

4. **Detailed description of the bug:** 

EDITED: This issue is still persisting from PROD. I've re-assigned to Howard for now.

Is there anything we can do about the images and logos not loading in Outlook and needing us to manually and load/download each one as it instructs on the default message that comes from Outlook? 
![image](https://user-images.githubusercontent.com/59668647/131221799-2492ab36-c7b7-45e2-aba5-d160c19c20ea.png)

**Comment by hsnyder2** [comment]
1. We may need to look into what might need to be done with MTLH and MTLI to have the images show up without having to click "Download Images."  Would make sense to see if this happens in PROD with the existing production accounts for MTLH and MTLI.
2. Also looks like you need to add actual image files to template (vs links to image files that you want to appear in the templated email, e.g. GitHub links).

**Comment by lijenn** [comment]
Note: Need to update Do image hyperlink (the link went to an outdated link for S01 See guide which is here: https://github.com/lzim/mtl/blob/master/blue/session01/s01_learner/mtl_session01_see.md)

**Comment by apisano0920** [comment]
This behavior is associated with the rich-text editor. We can look into it further when the project restarts and see if Microsoft has any suggestions on how to get it to open fully when the form is loaded. In the meantime refreshing the screen fixes the issue.
