### ISSUE TITLE
wk2 sept_epic UAT bug: no option to upload image

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#2211]
**Add a detailed description:** 
 
1. **Who encountered the bug:** : Stacey

2. **Which instance are you testing in?:** QA

3. **Date/Time of the bug:** 8/30/2021 10:30am

4. **Role:** Admin

5. **Detailed description of the bug:** Insert a description of the bug, add screenshots, and steps to reproduce. If following steps on the UAT script/guide, note which specific step.
Do not see "edit image" option as listed in UAT guide for adding personal photo

![MicrosoftTeams-image](https://user-images.githubusercontent.com/31089501/131423968-161d8d3a-4f0b-42ac-9b01-47efc8a7c748.png)

**Comment by hsnyder2** [comment]
updated Section 5.2 of Tester's Guide with instructions to do this.

**Comment by hsnyder2** [comment]
Did you follow steps in Tester's Guide?

> To replace the person icon on the far right of the image above with a custom image:
> 1.	Click the Cog in the image above and select Advanced Settings.
> 2.	From the Advance Settings page, click the person icon and select Edit Image.
> 3.	Click Choose File and browse to an image you would like to use and then click OK.
> 4.	The person icon should be replaced with the image you uploaded.

Works for me as an Admin user.  Doesn't work for you?

**Comment by staceypark** [comment]
Ok confirming this works now
