### ISSUE TITLE
wk5 uat: usability fixes

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#2215]
1. **Who encountered the bug:** Stacey

2. **Which instance are you testing in?:** QA

3. **Date/Time of the bug:** 9/1 6pm

3. **Role:** admin

4. **Detailed description of the bug:** 

Do not need items circled - is it possible to remove them
![image](https://user-images.githubusercontent.com/31089501/131767116-112c365d-c2f3-4ca4-88a9-65135f46b435.png)
 
Can not see the full text in a lot of buttons/dropdowns. Any way to increase the size of the button or make the text two lines?
![image](https://user-images.githubusercontent.com/31089501/131767466-5a8daae2-cfa4-413d-8163-3e32773b53e1.png)

**Comment by hsnyder2** [comment]
@staceypark  Thanks Stacey.  We can't do anything about the truncated button labels unfortunately.  Arlene, however, is looking into removal of the buttons you ID'd in the first part.

**Comment by lijenn** [comment]
Going into backlog.
