### ISSUE TITLE
wk5 aug_epic Review MTL data resources

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#2219]
- [x]  Read Session 2 & 3 guides under _MTL Blue_ at mtl.how for learners & facilitators 
  - https://github.com/lzim/mtl/tree/master/blue/session02
  - https://github.com/lzim/mtl/tree/master/blue/session03

- [x] Watch _MTL Videos_ on TMS for Sessions 2 & 3
  - [session 2](https://hcm03.ns2cloud.com/sf/learning?destUrl=https%3a%2f%2fva%2dhcm03%2ens2cloud%2ecom%2flearning%2fuser%2fdeeplink%5fredirect%2ejsp%3flinkId%3dITEM%5fDETAILS%26componentID%3d41544%26componentTypeID%3dVA%26revisionDate%3d1586807640000%26fromSF%3dY&company=VAHCM03)
  - [session 3](https://hcm03.ns2cloud.com/sf/learning?destUrl=https%3a%2f%2fva%2dhcm03%2ens2cloud%2ecom%2flearning%2fuser%2fdeeplink%5fredirect%2ejsp%3flinkId%3dITEM%5fDETAILS%26componentID%3d41433%26componentTypeID%3dVA%26revisionDate%3d1585580220000%26fromSF%3dY&company=VAHCM03)

**Comment by lzim** [comment]
@jeffhoerle 
Since you did this, I'm going to close this card.
Thanks!
