### ISSUE TITLE
wk1 sep_epic: UAT Bug - Post Emails did not send 1 day after Scheduled Session

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2226]
1. **Who encountered the bug:** Jenn

2. **Which instance are you testing in?:** QA

3. **Date/Time of the bug:** Thurs. 9/2 10:30pm Pacific

3. **Role:** Admin

4. **Detailed description of the bug:** 

- Done on Wed. 9/1, I scheduled Session S01 for jenn4_mtl_team_email to be 9/2 at 5:15pm Pacific
![image](https://user-images.githubusercontent.com/59668647/131958195-7eaa5cd7-009e-405f-bfa8-9fa00354f8d2.png)

- I set up and sent a Post email for S01 for this team
- The post email did not arrive at 9/2 around 10pm Pacific (9/3 1am Eastern) as expected based on how the current nightly routine is set up
![image](https://user-images.githubusercontent.com/59668647/131958256-00879fe6-0486-40f1-89a0-c91f8e0942ce.png)

**Comment by hsnyder2** [comment]
@lijenn If S01 is scheduled for 9/2 and "Days After Session to Send Post Email" = 1, then the email would be sent the night of 9/3, **_which is tonight_**.

If you want to have them in folk's inboxes the day after the session, set "Days After Session to Send Post Email" = 0 so they're fired off the night after the session and show up in folk's inboxes the next day.

Make sense? 

Don't think this issue, as described above, is a defect.  Unless I'm misunderstanding it (?)

**Comment by lijenn** [comment]
@hsnyder2 Thanks for clarifying, you got my misunderstanding! So I did end up waiting for it to send the night of 9/3 and I never received it. It doesn't look like it went out according to Dynamics either:
![image](https://user-images.githubusercontent.com/59668647/132348184-110b3f60-581a-4de5-8b9a-f9239de95a81.png)

Not sure if I did something wrong in the steps here, I could try to set up a new team and test it again using 0 days?

**Comment by hsnyder2** [comment]
OK, looks like the Post email was set up after the Team's "Setup Complete" box was checked.  Perfectly valid.  What's happening is that those emails that are set up after "Setup Complete" are not getting reassigned to the Team (they remain owned by the user who created it).  Arlene is working on a fix.  This will probably also happen with any CP, Pre or Post emails that are set up after the Group or Team "Setup Complete" box is checked (fyi).

**Comment by hsnyder2** [comment]
Arlene's got a fix for this in DEV and we're testing it now.  Will want to deploy this fix to QA to have you retest once that's happened (fyi).
