### ISSUE TITLE
Due + Bug: On mtl.how, remove mtl.how/live links and Adobe Connect refs

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#2227]
**1. MTL Links still has mtl.how/live => AdobeConnect** 

Not sure if the linter could look for other instances of this outdated content?

<< ![image](https://user-images.githubusercontent.com/29778290/132106786-066faec9-f062-4f63-a89b-867e2da88301.png)>>
 
**2. Click on the right:**  
i. **Pipelines** - prioritize in a TeamPSD (& Workgroup) pipeline  
ii. **Assignee** - assign to an individual team member producing work for the issue  
iii. **Label**- assign workgroup (lead) responsible for tracking the task  
iv. **Projects** - assign to domain-specific TeamPSD tracker (issues, features, document, manuscript, team)  
v. **Milestones** - select monthly sprint milestone within the workgroup   
vi. **Estimate** - Estimate task in complexity points   
vii. **Epics** - assign to team-wide epic and TeamPSD master plan project  
iix. **Releases** - assign to key team release grouped with other relevant issues  

**3. If you anticipate that your **issue card** or **bug card** will have **dependencies** these can be added once the issue has been submitted.   
ix. **Add dependencies** - assess for and add dependencies *blocking* & *blocked by* this issue

**Comment by lzim** [comment]
Discussed at **sim_ui_workgroup** 09/15/21
@mnallajerla 
Will open a pull request to remove the reference to Adobe Connect & add the mtl.how/demo site.

- [ ] Remove Adobe Connect
- [ ] Reorder into team, tms, demo, refs
- [ ] ADD text for demo

Text to add:
1.  [_MTL Blue Demo_](https://mtl.how/demo) - _MTL Blue_ demo simulation. 

Section of the Manual on using branches - https://lzim.github.io/teampsd/11-track-issues-features.html#use-github-branches

Open pull requests with a meaningful branch name for that feature that names the issue task card something helpful.

Then merge it back in to QA.

Your reviewer will approve the Pull Request (PR) 
@jamesmrollins @staceypark @lijenn could all be your reviewer on this.
Ask any of us to approve it.

**Comment by mnallajerla** [comment]
@jamesmrollins @staceypark @lijenn @lzim 

Unable to create the pull request with QA as the base branch, but it's able to be merged with master as the base branch. Any tips? Pictures below of the issue I am running into.

![Screen Shot 2021-09-16 at 10.15.07 AM.png](https://images.zenhubusercontent.com/6130066bf230e9289f9a2c0c/bc0a0396-2a4e-4ea8-8eac-48f801ca24c0)

![image.png](https://images.zenhubusercontent.com/6130066bf230e9289f9a2c0c/9279f1fe-01ae-4bb4-982b-f96160ef3a17)

**Comment by mnallajerla** [comment]
Discussed above question in HQ Workgroup meeting. Pull request has been created for approval from @jamesmrollins @staceypark @lijenn

**Comment by jamesmrollins** [comment]
HI @mnallajerla - If you have time early this afternoon around 1pm PST, I can review this with you and answer any questions you may have with respect to the action failures and such.  Thanks,  James

**Comment by mnallajerla** [comment]
@jamesmrollins that would be amazing, thank you! Will send you a meeting invite.

**Comment by mnallajerla** [comment]
Changes have been made and pushed through.
