### ISSUE TITLE
wk1 sep_epic: Order Team PSD books and items

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2230]
@mnallajerla I'm creating this issue card to track the efforts of ordering your items, ping me once you have the pdf of your Amazon cart, please! 

Let's try to get this one done today since it's a bit time sensitive, I'll put in the order once you're ready :)!

**Comment by mnallajerla** [comment]
Thank you! Well get to this after our 11am meeting

**Comment by mnallajerla** [comment]
Emailed, thank you!
