### ISSUE TITLE
ICEBOX Story K & L : Include Race/Ethnicity Data in MTL Splash Page

### ISSUE THREAD

**Issue by dkngenda** [lzim/teampsd#2238]
@anthonycpichardo commented on [Thu Sep 03 2020](https://github.com/lzim/research/issues/31)

Include Race & Ethnicity Data from the CDW Dimension table and link it to the data in our Splash Page

---

@lzim commented on [Wed Oct 14 2020](https://github.com/lzim/research/issues/31#issuecomment-708500710)

@anthonycpichardo 

This will need to be thought thru for inclusion in wave2 & PowerBI ~ Dec/Jan can we move to **dec_epic** backlog? It’s only two sprints away.

Thanks!

---

@dkngenda commented on [Thu Aug 05 2021](https://github.com/lzim/research/issues/31#issuecomment-893902189)

To be discussed on 8/17 during post-doc mentorship. 

---

@lzim commented on [Fri Sep 10 2021](https://github.com/lzim/research/issues/31#issuecomment-917230291)

@dkngenda 
@lijenn 
@staceypark 
@mnallajerla 

Since this is about the old "splashpage," it should be moved to the Team PSD repository or the VA Operations repo (if we can get our DevSecOps or CI/CD workflow source managed there).

@dkngenda  Do you mind migrating the ticket & closing this one on the research repo, please? thanks! :smile_cat:

**Comment by dkngenda** [comment]
This issue was moved from the research repo to teampsd repo

**Comment by lzim** [comment]
So can we close this @dkngenda ?

**Comment by lijenn** [comment]
Do we need to discuss this for 2024_feb_roadmap @dkngenda?

**Comment by lzim** [comment]
#adjudicate_memo
Closing because this is on Research Repo
