### ISSUE TITLE
wk2 sept_epic: UAT BUG - Non-templated Email is Pending to Send

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2239]
1. **Who encountered the bug:** Jenn
2. **Which instance are you testing in?:** QA
3. **Date/Time of the bug:**  9/8 around 9am Pacific, noticed originally from #2229, but looks like it may not be related to when emails/the nightly plug in goes off. 
4. **Role:** Admin

5. **Detailed description of the bug:**

@hsnyder2 I was trying to send from D365 from the Emails under Main on the left hand nav, ~~is this email pending because we're scheduling emails (all emails, not just templated ones?) to go out at 8AM ET?~~ Doesn't look like it since it's still pending.

I clicked 'Send' after I drafted on this email on Friday 9/8 around 9am Pacific, still looks to be pending after the weekend:
![image](https://user-images.githubusercontent.com/59668647/132885329-0f6851b2-5225-461b-b9b9-ffb148390d4b.png)

**Comment by hsnyder2** [comment]
Can't send from D365 as anything but one of the Shared Accounts configured for this D365 instance (MTLH and/or MTLI).  If you change the sender of the Ad Hoc email to one of those and hit send, the initial status will be "Pending Send" but will change to "Sent" as soon as it sends (which it will, as long as sender is one of the 2 emails above).
