### ISSUE TITLE
wk2 sep_epic: UAT Bug - Leftover data from Live Blue version into a new Live Red version

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2240]
1. **Who encountered the bug:** Jenn

2. **Which instance are you testing in?:** QA

3. **Date/Time of the bug:** 9/13 Friday, maybe around 9am Pacific??

3. **Role:** Admin

4. **Detailed description of the bug:** Noticed some leftover (old?) data from Live Blue Version into the Live Red Version (that I made on either Thursday or Friday) in the Pre and Post Emails tab:
![image](https://user-images.githubusercontent.com/59668647/133107570-61a4233b-89d6-4ded-b808-f38ef06f7c67.png)

**Comment by hsnyder2** [comment]
Good catch.  Arlene's ID'd the root cause and fixed.  The fix is now in QA and ready to retest.

**Comment by lijenn** [comment]
@hsnyder2 & @apisano0920 Shoot, I missed one. The pre and post emails are looking good for Teams, but I just found one in the new jenn3_red_coplanning_group I made, looks like I missed it in jenn2_red_coplanning_group too since I see it there:
![image](https://user-images.githubusercontent.com/59668647/133369797-efb9497d-85e2-48da-99f8-2c2dbd3b8cb7.png)
