### ISSUE TITLE
wk3 sep_epic Add Meghana to all accounts 

### ISSUE THREAD

**Issue by mnallajerla** [lzim/teampsd#2242]
Hi @staceypark @lijenn 

Could you share me on the appropriate LucidCharts, Osf, Authorship App, and any other platforms/files I need to be on? Thank you! 

Lucid Charts accounts: mnallajerla@pavir.org
OSF - Meghana Nallajerla

**Comment by staceypark** [comment]
Added you to LucidCharts. You should have gotten an invitation to setup an account.
There's nothing to "add" you to on OSF as its on a manuscript by manuscript basis.
