### ISSUE TITLE
wk2 sep_epic: SIM UI ANDON - Experiment Results Default to Balanced Mode

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2249]
Found on Thurs. 9/16 with Marcia & Jane for prep:

This is present in Team World and Individual Worlds. 
Effecting new experiments and looks to be showing up in previous experiments too before the #2121 release, but it's difficult to determine if it's just a toggle bug and not a bug that affects the data/results of the experiment.

Before running a Team Data Experiment:
![image](https://user-images.githubusercontent.com/59668647/133658041-0b280590-723b-4b8d-aee1-24c3727e7388.png)

After running/viewing the results of a Team Data Experiment:
![image](https://user-images.githubusercontent.com/59668647/133658076-8577eb66-34d4-4034-86cc-238e0a2a2fce.png)

Console:
![image](https://user-images.githubusercontent.com/59668647/133660009-8a6ebb26-e02b-4d10-929d-63c9fa49bb9a.png)

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire.  Looks like we are having the issue of the balanced mode switch, switching on its own from "1" to "0".  Can we get this fixed please?  Thanks, James

**Comment by jamesmrollins** [comment]
Hi @lijenn, @staceypark FYI @lzim @branscombj 

The bug is fixed:

![image](https://user-images.githubusercontent.com/30132017/133825384-0165c412-0e76-4e89-9769-0d60f50525b6.png)

**Comment by branscombj** [comment]
Thank you! Re: original report above, yes, it was actually running the sim in Balanced Mode - results were for balanced. I just ran one bc test in each mode and the results look how I would expect them to.

Could I request that this setting be included in the Current Run Experiment Values list? Granted, when the auto-naming goes into effect, it should be easy to see which mode was used and less easy to fail to include that setting in the experiment name. If that new naming functionality obviates this request, then it may obviate the whole need for the Current Run Experiment Values section! ?

**Comment by jamesmrollins** [comment]
Hi @branscombj .  Yes, I specified that we will indicated the mode in the auto-save function.  But I think we should also add it to the  current run experiment values, since the auto-name doesn't execute until you save it.  So, if you were facilitating from the large outputs and text section, you would have to toggle back to the main page to see your settings.  What are your thoughts on that?

**Comment by lijenn** [comment]
I also tested and found it fixed for previous experiments as well. I agree with @jamesmrollins point above to @branscombj's suggestion. 

I think we should keep the Current Run Experiment Values section and have the Team Data and Balanced Mode values in that table, even if the auto-naming feature coming in wk1 of oct_epic for redundancy sake and ability to view the values while looking at the results graphs.

**Comment by lijenn** [comment]
@jamesmrollins Resolving this ANDON may have resulted to missing experiments. 
LMK if I should make a new bug and close this, I re-opened this to track the need for CI/CD from DEV, TEST, PROD.

1) Tuesday Team
Debbie & Marcia 

2) Wednesday
Debbie & Claire

Are reporting that they may be missing experiments and Q/H/F/D text that they believe are related to ANDON #2249 being corrected at the end of last week.

Sounds like these 2 are missing a weeks' worth of work and Jane and Marcia's Thursday team may have been spared b/c they meet on separate schedule.

**Comment by jamesmrollins** [comment]
Please send GROUP details via TEAMS.  Did they provide an experiment name?  Are all experiments missing, or just work-in-process?

**Comment by lzim** [comment]
@jamesmrollins 

Just to double-check re: 
> Please send GROUP details via TEAMS. Did they provide an experiment name? Are all experiments missing, or just work-in-process?

Are you able to use the mtl.help@va.gov calendar workflow to confirm what the groups are when Jenn de-identifies by writing this on GitHub?
>Tuesday Team
Debbie & Marcia

> Wednesday
Debbie & Claire
