### ISSUE TITLE
wk3 dec_epic Facilitate WG: TEST QA - VA Red Say Guide Prompts 

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2251]
Tues Facilitate WG - Review VA SAY Guide Prompts, Pre/Post Emails.

**Comment by mnallajerla** [comment]
do we need to review the guides with facilitators before this can be closed?

@lijenn 

Otherwise -Since we completed Red Part I guides and have separate cards for Red Part II DEV (#2438) & QA (#2439), we could close this card.

**Comment by lijenn** [comment]
Tracking in #2438 & #2439
