### ISSUE TITLE
wk2 feb_epic PROD QA - Review MTL Blue S2 &S3 See & Say Guide with Theory of Change edits

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2252]
Review theory of change edits for MTL Blue S2 & S3.

 @lijenn & @mnallajerla will copy over the edits into MTL Red Part I and remove SIM references once the MTL Blue guide has been approved.

**Comment by lzim** [comment]
@lijenn I tried to keep the dependency chain in check for VA red with knowledge of the co-planning schedule. 
But, please let me know if we need to time at 8AM workgroup leads to discuss.
