### ISSUE TITLE
wk3 dec_epic: DEV QA - VA Red Say & See Guide Prompts & Updates

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2255]
Scope requirements and develop prompts for team tailoring for the Red Say guides for VA sites.

**Comment by lijenn** [comment]
Part 1 - Partner Phase

6 session
Viz tabs
Data tabs

Part 2 - Build Phase
6 session
Params tabs 
- Start with highest priority (i.e. 1 of the 5 modules)
- Then consider different modules

NIH vs VA Red - Facilitator Time & Attention needs to be parallel 

Pre/Post & Done/Do:
- What Veteran does the team need to discuss this week? [Is this a pre/post or done/do prompt]
- What viz tabs does the team need to decide this week?

NIH & VA Red
Facilitator (time & attention)
Pre/post (done/do) (3 cycle iteration):
data tabs: What Veteran does the team need to discuss this week?
viz tabs: What team trend does the team need to discuss this week?

[5:18 PM] Zimmerman, Lindsey E.
DECISION:

Done/Do review
"We decided..."
No change the to Red email templates all tailoring is done by facilititators in Dyanmics.

​[5:19 PM] Zimmerman, Lindsey E.
    Facilitator Red > Part 1

va_part_1_say_data (3 sessions)
va_part_1_say_viz (3 sessions)
va_part_1_say_params (6 sessions)

**Comment by mnallajerla** [comment]
@lijenn  - Since we completed Red Part I guides and have separate cards for Red Part II DEV (#2438) & QA (#2439), closing this card. I copied over the notes in your comment to the MasterCard as well.
