### ISSUE TITLE
wk2 sep_epic: UAT Bug: Email Response Date is incorrect (date and time are wrong)

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2256]
1. **Who encountered the bug:** Jenn

2. **Which instance are you testing in?:** QA

3. **Date/Time of the bug:** 9/17 10:00am Pacific

3. **Role:** Admin

4. **Detailed description of the bug:**

- Added myself (VA email) to Live Blue team (jenn_9/17_mtl_team)
- Sent an ad hoc email to myself from D365 under MTL Help
- Used my VA email to respond to the ad hoc email
- Email Response date says I responded yesterday at 5:00pm Pacific, but I sent out this email and responded to it today 9/17

![image](https://user-images.githubusercontent.com/59668647/133826758-90f7a7a0-72e9-45d6-a74d-d151ef242511.png)

**Comment by hsnyder2** [comment]
Looking at it now.

**Comment by hsnyder2** [comment]
OK, well this one was unexpected.  It worked before so Arlene checked to see if any intervening changes might have broken it, but no.  All she did was change the C# command from Date/Today to Date/Now.  That's all that seems to have been needed to fix this.  Makes me wonder if MS isn't making changes to D365 behind the scenes i.e. not announcing when the product's been updated to a newer release.  Can't think of any other reason why Date/Today stopped working.
