### ISSUE TITLE
Cannot get two worlds to load in MTL 1.6 PROD team_mtl_facilitate_pilot_2018_09 and ind_mtl_facilitate_pilot_2018_09

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#226]
@jamesmrollins 

Yesterday and today, I have been unable to log-in to "team_mtl_facilitate_pilot_2018_09" or "ind_mtl_facilitate_pilot_2018_09" from my laptop using Safari or Chrome.
![world_bug](https://user-images.githubusercontent.com/7454688/46921055-72f7cd80-cfab-11e8-939e-e0dcf52828ce.png)

I can't get this detail and take a screenshot at the same time, but what I get when I push the button is a greyed out 🚫

**Comment by lzim** [comment]
@jamesmrollins 

- Thanks for the reminder to include screenshots of the inspector/developer details for the bug from the browsers

- Safari Inspector
![safari_inspector_errors](https://user-images.githubusercontent.com/7454688/46921555-bce3b200-cfb1-11e8-8045-ecb1f4a2eb17.png)
![safari_inspector_warnings](https://user-images.githubusercontent.com/7454688/46921557-be14df00-cfb1-11e8-9ab9-8d89961fd778.png)

- Chrome Developer
![chrome_developer_error](https://user-images.githubusercontent.com/7454688/46921590-24016680-cfb2-11e8-9956-6c0cc0e3f3e7.png)

**Comment by lzim** [comment]
@dlkibbe and EVERYONE!

Until this bug is resolved, please go to https://mtl.how/facilitate and map yourself to your own individual world.

- I just got bumped out of the MPD world by a team member starting a new session for the world **"640a0_mpd-user-training-may-2018"**
- But do keep in mind that the team worlds of the R21 pilot sites are still live to those users and we do not want to develop or test in them, which could interference with their use by the teams.

THANKS 😺 

FYI: @ericasimon and @staceypark and @jamesmrollins

**Comment by branscombj** [comment]
I can't log in* to those worlds either from Chrome. I get the circle/slash icon and no "thinking" activity like it's trying to open the sim. Interestingly, in end user details, it does show my log-in attempt* at 4:49pm:
![bug20181014](https://user-images.githubusercontent.com/29778290/46922135-984c0200-cfd2-11e8-91f2-cf0e06fdef55.png)

However, when I look at the world-team mapping spreadsheet for VA PSD Simulation -- PROD,  I don't see the _team_ or _ind_ _facilitate_pilot_ Groups listed; only these 3 groups are mapped to world for that sim:

640a0_mpd-user-training-may-2018
test-group-for-dev-may-2018
640_individual_world
![bug20181014_2](https://user-images.githubusercontent.com/29778290/46922219-dd246880-cfd3-11e8-9037-6b5b26541c47.png)
[world-team-mapping (4).xlsx](https://github.com/lzim/teampsd/files/2476885/world-team-mapping.4.xlsx)

**Comment by jamesmrollins** [comment]
Sorry for the login issues. I will be back at my desk in a few hours and will investigate. Are their any worlds that teams are in the middle of a session that I need to be aware of?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by dlkibbe** [comment]
I was working in PSY but deleted run & logged out.

**Comment by lzim** [comment]
@jamesmrollins 

- All teams in the world "640a0_mpd-user-training-may-2018" likely have a current session going from their last team meeting.
- Not sure whether our OMHSP partners would be in "team_mtl_facilitate_pilot_2018_09" or "ind_mtl_facilitate_pilot_2018_09" (or how they could be given the issue)

- Thanks for 🔍 sleuthing around at the admin level @branscombj 
- I am not sure what would be going on with why they wouldn't be in the world team mapping "team_mtl_facilitate_pilot_2018_09" or "ind_mtl_facilitate_pilot_2018_09"

**Comment by lzim** [comment]
@branscombj Thank you to for your attention to this Team PSD style issue for MTL Resources.

Yes, after checking several style standards **here is our decision:**
- Log in (two words) should [only] be used as a verb. 
- Login (one word) can be a noun or an adjective.

*Examples that explain standard style usage:*
- Your *MTL* login (noun) is comprised of your VA email and your password.  
- You can reach the *MTL* login page (adjective) by typing mtl.how/sim in your Internet browser.
- Please log in (verb) to the sim UI.

We should not use "log-in" or "log into." Thanks! FYI: @ericasimon and @staceypark #

**Comment by jamesmrollins** [comment]
Looks like a user error.  The Admin needs to map the group and world so the Simulation can find the user. See the world-team-mapping file in the Interface Directory, Dynamic Data file.  I will fix it.

**Comment by lzim** [comment]
@jamesrollins and team,

Let’s keep an eye on the explanation for this. I think @branscombj said the same. She found the worlds in question weren’t in the world team mapping file (see above), i.e., a user error.

It’s just odd because I had been using those worlds repeatedly between 8/30 and 10/3 (my last memorable use for a demonstration), and I’m not sure who would have changed the mapping or for what reason.

It means the individual and team worlds with all our OMHSP leaders is (has been) down.

**Comment by jamesmrollins** [comment]
Hmm . ..  interesting.  It is possible that one could have during an update, updated the file, and then uploaded the original or a legacy copy instead.  Since we can version them in the filename, it could be a very easy mistake to make.   In any case, it should be working now.  I hope this did not inconvenience the  OMHSP leaders.

**Comment by lzim** [comment]
@staceypark can you weigh-in?
Do you know why we would have this mapping issue?  I'd like to resolve ASAP.

By end-user, other than when @branscombj @dlkibbe and I tried to get in to the sim yesterday, the last sim UI users were @staceypark and @TomRust on 10/11.

**Comment by staceypark** [comment]
@lzim @jamesmrollins 
Sorry, I think this may have been my fault.  I updated the team world mapping file late Friday before I left, for one of our providers.  I must have used the wrong version. Seems like the most plausible explanation here.

So I guess the good news is that the Sim UI would have been down only between late Friday and this morning. And the lesson for me and everyone is to make sure to have **only one copy of the world mapping file at any given point in time (by deleting the copy in your Downloads, once you update and upload) to prevent confusion with versions in the future**.

Sorry for the extra work and confusion I caused! 
Thanks @branscombj for hunting down the details and @jamesmrollins for getting it fixed!

**Comment by staceypark** [comment]
@branscombj @jamesmrollins 
Should work now. The issue with the new excel was: 

**Team vs. Individual Mapping in World Mapping xlsx**

Team mapping - Group Name | World # | World Name
- In team mapping, there is **_only one world per team_** and the World Name is the team name (i.e. TeamPSD). Each member is mapped to that world through Multiplayer Assignments, not the world mapping xlsx.

Individual mapping - Group Name | World # | World Name
- In individual mapping, there is **_one world per team member_** and the World Name is each team member's name (i.e. Stacey Park). Because there is a separate world for each member, this must be reflected in the world mapping xlsx.

The world mapping xlsx is to identify and map _**each unique world**_ not user. As such, no "World #" should ever be repeated twice within the same "Group" in the mapping.

**Comment by branscombj** [comment]
Whew! @staceypark -Thanks! 
That goes into the facilitator resources for back-end sim UI prep.
