### ISSUE TITLE
sep_epic Power BI documentation & findings

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#2262]
discussion from 9/21 huddle with @jeffhoerle 

Where will the clinic selection feature be located?
- So far, the only way for the clinic selection and the resulting visualizations can be nested within one location is to use the solution Ash already created in his demo
- Otherwise, Jeff recommends we have the clinic selection in a separate place. 
- The issue is that the clinic selection cannot be "cached," in multiple ways: 
  - You cannot "build up"  a clinic selection list meaning if you want to filter by provider first, add the results to a list, then filter  by clinic location, and add that result to list, there's no way for that initial "provider filter" list to be held.
  - We also cannot save a set of clinics to go back to in the way we have the "get previous clinic list" for running patient level data or running the team data table.

**Comment by staceypark** [comment]
We can get data by either importing the data ahead of time or implementing a direct connection. Importing the data is restricted to 10gb. Importing data ahead and working with it is much faster than doing a direct connection. VA already has documentation on how to setup the row level security permissioning for this method.

Due to the 10gb restriction, we may need to have 18 separate visn data models instead of one national data model. But, @jeffhoerle is hopeful so far that we can put it all together in one model.

Key value proposition: Important for our clinicians/end users to be able to be in the "driver seat" of creating their clinic selections/data sets and querying them aka transform the data themselves. 

Need to update PTSD_OMHO "staging data base" then have PBI refresh its data based on PTSD_OMHO. PTSD_OMHO needs to be updated by using SQL script. In the past, this was the splashSourceIncrementalUpdate. We need an identical process in PBI. We update on the monthly schedule, because otherwise the data "drops" drastically since all the data for the month is not in it and we've learned not to do this with our user base. 

PBI updates can be scheduled (this is the current propagation step), but we do not currently know of a way for PTSD_OMHO to be done automatically.

Replicating data & viz tabs, with modified queries that give the same results. Jeff is doing this one station at a time, for a smaller set of data to work with.

**Comment by mnallajerla** [comment]
Closing this issue. Referencing it in PBI Documentation (#2310) & Tracking cards (#2399)

**Comment by hnorthcraft** [comment]
#adjudicate_memo efforts tracked to other card, assigning dup
