### ISSUE TITLE
Output Charts Review for all MTL 1.6 Modules - PSY needs PTSD cohort

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#227]
@jamesmrollins and @TomRust 

Noticed that the output charts in the PSY Results Dashboard have the incorrect patient cohorts for the EBP and HS Gold, Silver and Bronze variables should have:
- PTSD
- Dep
- AUD
- Other 
- Currently omits PTSD.

@dlkibbe and @branscombj 
Want to make sure you noted an action item that came out of our MTL 1.7 release modeling workgroup and sim ui workgroup meetings last week:
- We realized that there are variables in the Results Dashboard that are not viewable any other place.
- The variables above are great examples EBP and HS Gold Silver and Bronze (designed to reflect SAIL definitions).
- This would be something we would likely point out somewhere between session 9 and 10, and should be included in the Facilitator SAY file.

@dlounsbu @staceypark and @ericasimon 
- Need to review to find any other possible issues like the PSY one I list above.
- We didn't explore these much during the R21 pilot, so need to double-check them as a team.

Thanks all!

**Comment by staceypark** [comment]
@lzim 
Did you mean AUD, DEP, OUD & PTSD? Instead of Other?
Because currently in _MTL 1.7_ that is the four cohorts I see.

@branscombj @dlkibbe @TomRust 
This is a model specific addition. Our current model specific details are only in this file below.  Would these get added somewhere in here?:
https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/facilitator_say/model_details_say_scripts.md

**Comment by branscombj** [comment]
@staceypark Thanks for the question! It would be nice to have that kind of model-specific info in the unified document you referenced. Then as @lzim mentioned above, it should be incorporated into the scripts, probably in Session 9 or 10. Are those variables easy to identify and pull from the variable crosswalk? If you'll point me to it and how to ID them, I'll pull them into the Model Details file

**Comment by jamesmrollins** [comment]
@lzim @staceypark @branscombj  I changed the "Other" to "PTSD" in PSY.  If you find any other strays, let me know.
