### ISSUE TITLE
ICEBOX: 365 Prod Backlog (Bug) - Transfer and Fix Deployments from QA to Prod

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2270]
1. **Who encountered the bug:** Jenn

2. **Which instance are you testing in?:** Prod

3. **Date/Time of the bug:** 9/23 at 2pm Pacific

3. **Role:** Admin

4. **Detailed description of the bug:** 

1) Noticed that the **Live data we used from QA are not in Prod** (i.e. The teams, groups, Contacts, Versions), is there any way this can be deployed from QA to Prod to reduce the efforts of re-inputting the data? 
    - We only want to set it up once (O.H.I.O principle!)
    - Can we select the Teams & Coplanning Groups we'd like to deploy from QA to Prod? I have a lot of test Teams and Groups that can remain in QA.
    - Nothing in Prod right now except my test Group & Team:
![image](https://user-images.githubusercontent.com/59668647/134688899-080f135d-09f1-4907-8429-9c834f133130.png)

    
2) Noticed the **Prod Contacts** have synced the information from existing emails from our shared inboxes
    - It looks to be **missing the first name field and adding it to the last name field**. Unless this can be fixed automatically, it will require manual rework from us to edit it
![image](https://user-images.githubusercontent.com/59668647/134689527-f20439ed-ace0-428e-ab90-889f096b13c2.png)

**Comment by apisano0920** [comment]
No data was transferred from QA to PROD. Part of the reason for doing UAT in QA instead of in PROD was so that you had an environment where you could do whatever you needed to do to test the application. Anything you added in the QA environment that you need to have in PROD will need to be added there.
