### ISSUE TITLE
wk4 sep_epic Authorship App Usability Testing

### ISSUE THREAD

**Issue by mnallajerla** [lzim/teampsd#2275]
@dkngenda, documenting the subcategory usability issues we just discussed:

In Section 2.d of the App (see screenshot below), add

1. Asterisk next to author names to convey to user that author names are required for new sub-category to save
2. Add note that user must click "Save" button for sub-category to save
3. Add note that user must click "reload app" button for sub-category to save

![Screen Shot 2021-09-27 at 3.53.25 PM.png](https://images.zenhubusercontent.com/6130066bf230e9289f9a2c0c/88832b96-f83f-496b-8b09-0ecca83acf77)

**Comment by dkngenda** [comment]
@mnallajerla  
1. I added the asterisk on the first author detail since it's the only one required (i.e a prior work category has to be associated with atleast one author.
2.  Number 2 and 3 are part of the instructions on that page.

**Comment by mnallajerla** [comment]
@dkngenda ok sounds good! I think there is a small chance people may miss those instructions,but we've covered it in the video as well so I think it should be fine. 

Also, I wonder if it would be helpful to mention the addition of the author name in the instructions as well, something like this: 

After adding a new subcategory, enter in author information for at least one author, then click `Save,' then `Reload App` buttons for the app to save and load the new subcategory. 

You must enter (1) at least one author, (2) save AND (3) reload for the category to save"

**Comment by mnallajerla** [comment]
@dkngenda Is this issue good to be closed?

**Comment by dkngenda** [comment]
> @dkngenda Is this issue good to be closed?

Yes. You can go ahead and close this card. i have updated the instructions to reflect your suggestion

**Comment by mnallajerla** [comment]
Great, thank you!
