### ISSUE TITLE
wk1 oct_epic authorship app faq videos + text

### ISSUE THREAD

**Issue by mnallajerla** [lzim/teampsd#2278]
- [x] Add text for FAQ 1 (registering new subcategory)
- [x] Make video for FAQ 1
- [x] Make video for FAQ 2 (How do I assign a new subcategory to a manuscript?) [This was already done]
- [x] Add text for FAQ 2 (How do I assign a new subcategory to a manuscript?)
- [x] FAQ 3: How do I assign "Write, Analyze, Edit" subcategories to a paper? > make video
- [x] Write and update text for FAQ 3
- [x] FAQ 4: How do I review prior work assignments to a manuscript? video 
- [x] FAQ 4: How do I review prior work assignments to a manuscript? text
- [x] FAQ 5: How do I review my rank on a manuscript? video 
- [x] FAQ 5: How do I review my rank on a manuscript? text 
- [x] Upload videos for FAQ 1-5 to authorship app
- [x] Edit the app in R to push changes through!

- [x] Make a pull request so @dkngenda can review changes

**Comment by mnallajerla** [comment]
@lijenn Would you be able to give me access to the Team PSD youtube account to upload the FAQ videos?

**Comment by mnallajerla** [comment]
FAQ 1: How do I register a new subcategory?

1. Navigate to “2. manuscript_effort” then “d. add_or_edit_prior_work_subcategories” (the last tab in the top right, in this section)
2. Under “Add or edit subcategory?,” click “add”
3. Enter the name of the new subcategory and the possible points 
4. Enter in author information for at least one author
5. Click 'Save’ 
6. Click ‘Reload App’
7. After the app reloads, navigate back to “2. manuscript_effort” and check to make sure the subcategory saved 
8. Watch the video below for a walk-through of the process

**Comment by lijenn** [comment]
@mnallajerla For the Team PSD Youtube Account, it looks like only @erinash @lzim are the only ones that can add you.
1.  I believe they'll need @mnallajerla's gmail account to add you as Brand Account Manager the LZPhD YouTube channel.
 2. @erinash @lzim You'll need to add @mnallajerla gmail address from here https://myaccount.google.com/brandaccounts (Referencing [4.3.2 from the Team PSD Manual](https://lzim.github.io/teampsd/4-team-psd-2-0-monthly-process.html#create-a-google-account))
 3. @mnallajerla Should receive an invite email to get access to the channel.

**Comment by mnallajerla** [comment]
@dkngenda For FAQ 5 (FAQ 5: How do I review my rank on a manuscript?), is this where they should go to do that? 

 ![Screen Shot 2021-10-01 at 4.03.55 PM.png](https://images.zenhubusercontent.com/6130066bf230e9289f9a2c0c/8e464391-5d7a-45e1-a4b4-fe17d25b3127)

**Comment by dkngenda** [comment]
@mnallajerla Yes! We should probably mention that the final authorship ranking should be done after everyone has agreed to the ranking.

**Comment by mnallajerla** [comment]
@dkngenda - Is there a formal process to agree / accept authorship ranking within the app (versus verbally confirming with co-authors)?

**Comment by dkngenda** [comment]
There is no process within the app. Maybe this will be something that gets accomplished through the manuscript tracker. @staceypark What do you think?

**Comment by mnallajerla** [comment]
Made "rough drafts" of all the videos and sent them to @dkngenda for review before making final edits. 

Still need access to Team PSD Youtube @lijenn @lzim to get the videos uploaded and linked to Authorship App

**Comment by mnallajerla** [comment]
Questions for @dkngenda 

1. Why do the prior work (FAQ2) and remaining work (FAQ3) subcategories not match???	(ie, for FAQ 3 - what if research idea has already been conceptualized? How do we credit that though?) > I may be confusing the write/analyze/edit categories in 2c and 4. I think this really needs to be clarified, and why these subcategories are different from the subcategories in 2a. 

2. What determines the maximum points for each write/analyze/edit subcategory in 2c?

**Comment by mnallajerla** [comment]
@dkngenda to add "final" to tab 5 title 

Additional FAQs:

- FAQ 6: What determines the maximum points for each write/analyze/edit subcategory? 
There are guidelines in literature that were used by the team to decide those points.
- FAQ 7: How is the final author ranking computed?

Prior work done on the manuscript + write/analyze/edit assigned work are factored together to provide the final authorship score in tab 5

**Comment by mnallajerla** [comment]
Pull request made and @dkngenda reviewing the edits. Closing this issue, and will make a new one for any new edits that emerge.
