### ISSUE TITLE
wk2 oct_epic Implement RLS feature in PBI

### ISSUE THREAD

**Issue by jeffhoerle** [lzim/teampsd#2279]

**Comment by mnallajerla** [comment]
Discussed @ 11 am quant research 

Double check RLS support use cases for different MTL user groups @ 2 PM 

FYI: @lijenn @dkngenda @mnallajerla @staceypark

**Comment by mnallajerla** [comment]
Notes from 2 PM Support: 
**Which users need permission and how can we give those users access?**

- Admin level role - _should_ have access to all data nationally

- Facilitators - _can_ access to all data nationally; All central office needs;Restricted access

- Co-Planning (VISN leadership, Chief of Staff, Assoc. Chief of Staff etc) did not get PHI
_- Can view anything under the viz tab but not data tabs 
- Would be ideal to keep data tabs but restrict PHI (ie, veterans’ names)_

**RLS vs LSV:** Different ways to give permission to data 
Row Level Security: 
- Implementation in power BI that we are using to manage access to data 
- Can filter out at a row level who can access what data 

Local Server Views: 
- Accessing SQL 33 or Field Reporting Enclaves (FRE)

**Use cases - at what level should access be given / how?**

- Ie, for example, Chula Vista (site) is a part of different (state 3 N?) and different VISN

- Potential solution → manually give permission to users who are at the intersection of some of these different systems 

- Question --- is it possible to give access to this data outside the existing infratructure WITHOUT giving national access

- Potential solution → have the QIICs/ facilitators pull the data; 
but - Problem: visuals would not be able to be shared 

_Documenting this here for now, did not capture all the details that would likely be relevant for different audiences_
FYI: @lzim @staceypark @lijenn @dkngenda @jeffhoerle

**Comment by lzim** [comment]
@jeffhoerle 
I cannot recall whether we addressed all of our use cases for this during the meeting or not without double-checking the record in Teams. **But, I believe we DID.** :😊 
Do you remember @staceypark & @lijenn ?

And, I believe @mnallajerla Was scribing without access to the chat. 

@mnallajerla 
Thanks for scribing, Can you confirm the date of this **support_workgroup**? Was is 10/6??
Will you please include the dates when you scribe too, in case we need to double-check something on the thread? Thanks!

**Comment by jeffhoerle** [comment]
Yes, I believe all use cases are being accommodated with RLS.  We were concerned about users who needed access to more than one Sta3n, but tested out a handful of users in the LSV and all users had access to multiple Sta3ns (i.e. had access to all the Sta3ns that they needed).  You will need to request that all Facilitators be granted access broader access in the LSV.

**Comment by lzim** [comment]
We tested and LSV permissioning is working as intended.
