### ISSUE TITLE
wk2 dec_epic Draft "param tab" visuals in PBI - DEV

### ISSUE THREAD

**Issue by jeffhoerle** [lzim/teampsd#2284]
Param Tabs in PBI (except SP) Remaining Work to re-organize these tabs, add data descriptions. 

[[See Support WG Thread 12.10.21](https://teams.microsoft.com/l/message/19:bfdf92c7846542b58e9961e1d8cc671e@thread.skype/1639154641837?tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf&groupId=1db500d5-0d01-4254-af42-ad3f78bafacd&parentMessageId=1639154617859&teamName=teampsd_vha&channelName=support_workgroup&createdTime=1639154641837) for all details mentioned below]

**DECISION:** 

- [x] Prioritize completion of CC, MM, PSY, Team (AGG) tabs
- [x] Includes re-naming tabs in full forms, characters permitting (Medicine Management
- [x] Include splitting each tab as discussed on Support WG Thread on 12.10.21 
- [x] Include data descriptions for each tab [CC, MM, PSY, Team (AGG)]
- [x] Review PSY Params for a workable size (~12-14 rows) and greatest corresponence to Sim UI.

**Timelline**
- @jeffhoerle anticipates being done with this by EOD on Monday, 12.13.21.
- QA Cards - to Test on Tues 12/14 & Wed 12/15...
- Finish documenting Thurs 12/16 #2383
- **Session 3 with Team Friday 8AM Pacific 12/17**

**Comment by mnallajerla** [comment]
Discussed at Quant 12.9.21 

Made a separate card for SP Dev (#2410). The remaining params tabs have been developed and ready for testing. See #2408.

**Comment by lijenn** [comment]
@jeffhoerle Can you help clarify what visuals are in this card? It was our understanding from yesterday's 12/8 Support WG meeting that @mnallajerla and I can go ahead with testing and having our leading MTL Blue team use the CC, MM, PSY, & AGG param tabs for user testing. 

Is that still the case?

**Comment by lzim** [comment]
**Discussed at 12/15/21 Support Workgroups**
- These are all DEV'd.
- There are remaining TEST and documentation task to wrap wk2 dec_epic
- Note #2415 MM Bug being tracked on it's own card.
