### ISSUE TITLE
ICEBOX: D365 Prod Backlog (Bug/CR) - Add Survey Email for Version Templates & 2 Tabs (Survey Emails) & MTL Info Emails at Team level

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2287]
1. **Who encountered the bug:** Jenn

2. **Which instance are you testing in?:** Prod

3. **Date/Time of the bug:** 9/28 3:10pm Pacific

3. **Role:** Admin

4. **Detailed description of the bug:**

Was trying to set up our templated survey emails to be sent from MTL Info.
Templated emails are only sent from MTL Help right now.

Even without this implementation, the out of box Email Template button in the top nav when creating a New Email is stuck at the loading screen and does not seem to work (see bug in #2291)
![image](https://user-images.githubusercontent.com/59668647/135175918-e53260da-26a3-4462-a8be-9d72c1c6ef95.png)

## Requirements:
1. Need to add a new type of templated email at the Version level (can call it Survey)
   - These templated Survey emails will be sent at the Team level 
   - Should be sent from MTL Info
![image](https://user-images.githubusercontent.com/59668647/135175240-1fde4be5-72dc-42af-b3c5-229d82f205c3.png)

2. Need two tabs at the Team Level (Survey Emails and MTL Info Emails):
   - Survey Emails: Will show the templates to use for the survey emails
   - MTL Info Emails: Will show the emails sent by us from MTL Info to the team and responses and emails sent by the team to MTL info
![image](https://user-images.githubusercontent.com/59668647/135174782-5efccbc8-0d6d-4849-b900-b7ca47122fc1.png)

3. Since every templated email/task/appointment needs a Session associated with it, I believe we can just label the Session as Survey for now.

**Comment by lzim** [comment]
**hq_workgroup 9/30/21** 

- We CAN create email templates in Dynamics. 
- But, for some reason they can only be sent from mtl.help@va.gov, but not mtl.info@va.gov 
- It is in the requirements for mtl.help@va.gov and mtl.info@va.gov workflow maps in the templates folder.
- _How many other things like this are not in the backlog?_

@lzim will ask about getting things like this done.

**Comment by hnorthcraft** [comment]
#adjudicate_memo updating to 1SP
