### ISSUE TITLE
Bug Data UI: Monthly incremental update not working

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#2288]
@jeffhoerle 
Last month, we were unable to run the monthly incremental update for propagating the data UI (from the file in TeamPSD > quant_workgroup > splash_pages > splashSourceIncrementalUpdate). I got the error in the screenshot below from running the SQL code. 

The issue with not being able to run this incremental update, is the sharp drop teams will see in their data because the visualizations will "end" on the day we propagate.

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/31089501/135536966-818c8965-9ce4-4828-a0be-131416747efa.png)

**Comment by lzim** [comment]
Discussed at hq_workgroup 9/30/21 
Invited @jeffhoerle to **8AM Workgroup Lead**s on Monday 10/4 to further clarify this (if needed).

**Comment by jeffhoerle** [comment]
@staceypark - When you run that script, are you logged onto vhacdwa01.vha.med.va.gov or vhacdwdwhsql33.VHA.MED.VA.GOV?  It appears PTSD_OMHO only exists on vhacdwa01... so if you were signed into vhacdwdwhsql33 that would explain why that name was "invalid".

But if you are signed into vhacdwa01, I don't see an obvious reason why that didn't work.  On Monday, perhaps you can share your screen with me and we can debug for 5 minutes.

**Comment by staceypark** [comment]
Decision: 10/4 Workgroup Leads meeting - The shoulders showing in the Data UI has not been an issue for the providers.

**Comment by hnorthcraft** [comment]
#adjudicate_memo @lzim @lijenn  please update sp estimate and vs label
Thanks!
