### ISSUE TITLE
wk1 oct_epic: BUG - Sim UI Andon Alert Message only pops up for Learners, not Admins or Facilitators

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2290]
@jamesmrollins I noticed the Andon alert I set up earlier did not show up for me as I just re-entered the Sim today after setting it up earlier.

Upon setting the alert up, I tested it in both the Learner's individual and team world and it is there:
(Side note: Using the bolding markdown language doesn't work because I think the entire text is already in bold? Is there anyway were we make still use markdown to bold specific parts?):
![image](https://user-images.githubusercontent.com/59668647/135545510-4ab397cf-84dd-4927-92ff-fa34a3b7d07e.png)

But I do not see it for me when I log in as an Admin or Facilitator. 
I tested this with Stacey and Lindsey's account too and do not see the alert message.
![image](https://user-images.githubusercontent.com/59668647/135545650-e6e11dc3-582c-43c8-8eab-a3ded688f226.png)

**Comment by jamesmrollins** [comment]
Would like to target Andon alerts to facilitators only, end-users only and both facilitators and end-users. See #2197
