### ISSUE TITLE
ICEBOX: D365 Prod Backlog (Bug) -  Out of box Email Template button stuck at loading screen 

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2291]
1. **Who encountered the bug:** Jenn

2. **Which instance are you testing in?:** Prod

3. **Date/Time of the bug:** 9/28 3:10pm Pacific

3. **Role:** Admin

4. **Detailed description of the bug:**

Tried to manually set up a templated survey email due to the issue in #2287, but the out of box Email Template button in the top nav when creating a New Email is stuck at the loading screen and does not seem to work:
![image](https://user-images.githubusercontent.com/59668647/135546303-9d6a521d-0531-405a-b547-153972aa2e04.png)

**Comment by hnorthcraft** [comment]
#adjudicate_memo updating to 1SP
