### ISSUE TITLE
ICEBOX: D365 Prod Backlog (Usability/CR): Activity Dashboard – Tasks to show actual name/description of the task instead of  “Checklist item…

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2293]
1. **Who encountered the bug:** Jenn

2. **Which instance are you testing in?:** Prod

3. **Date/Time of the bug:** 9/28 3:10pm Pacific

3. **Role:** Admin

4. **Detailed description of the bug:**

Hard to know what the actual tasks are in the Activity Dashboard since it just says  “Checklist item…" and not the actual name/description of the task.
![image](https://user-images.githubusercontent.com/59668647/135548604-6ca8e368-df63-40fc-b79d-75ea19a6d74c.png)

**Comment by hnorthcraft** [comment]
#adjudicate_memo updating to 1SP
