### ISSUE TITLE
ICEBOX: Data UI Bug/Story 13 Power BI - vizHF Shows Incorrect Default Filtered Categories 

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2304]
We have the vizHF graph to filter to specific categories by default documented here (https://github.com/lzim/teampsd/issues/2102#issuecomment-882777224) after querying the data.

I think it's okay to not fix this in the current version if there is no time, but it is a requirement to keep track of for PBI.

We were unable to get the documented default filters to show up as I still get the 4 VA Suicide filters on the current Production version of the data ui:
![image](https://user-images.githubusercontent.com/59668647/136270482-904a9ebd-fbde-4f3c-8f44-c6937ac43a5d.png)

When I ran Jeff's file, I got all the filters checked on default (luckily it allowed me to catch #2303).
![image](https://user-images.githubusercontent.com/59668647/136270696-749cd71f-baab-4773-b380-984428f8c0e9.png)

**Comment by staceypark** [comment]
DECISION: As long as there isn't any missing data, our goal is to get off the legacy platforms and move to Power BI.
