### ISSUE TITLE
wk2 oct_epic Tues AM 10/12: Please set up 3 course codes for mtl.how/demo 

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2305]
@staceypark @jamesmrollins @lijenn 

Will you point @mnallajerla to the correct location in the [_MTL_ Manual](https://mtl.how/manual) to create 3 course codes for [_MTL_ Demo](https://mtl.how/demo) in the Admin Dashboard of the sim, please?

_We need these 3 codes created by Tuesday 10/13 if we can:_
iri_methods_2021
northwestern_psmg_2021
informs_2021

**Comment by jamesmrollins** [comment]
@mnallajerla you can always reach me for support.  I am going to create written instructions this morning.  When they publish, it would be good for you to be the tester.

FYI @lijenn

**Comment by jamesmrollins** [comment]
Hi @mnallajerla @lijenn @lzim.  The Course Codes are set up in _MTL_ Demo.  Instructions for the _MTL_ manual will be finished tomorrow.

![image](https://user-images.githubusercontent.com/30132017/136497107-de8c7f72-07f9-4182-a70e-46f063a27978.png)

**Comment by jamesmrollins** [comment]
@mnallajerla if you want to see a draft of the manual as you look around the Sim UI administrator functions, just [click here](https://github.com/lzim/mtl/edit/feature-gh-pages_sim_ui_admin/sim_ui_administration.md)
