### ISSUE TITLE
wk2 oct_epic: SIM UI - Change Header of export from Team Statistics

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2308]
Discussed at Wed Overflow 10/13 at 8am Pacific:

1) Talk w/ @jamesmrollins about changing the header "% present" to "% logged in" at 10/13 Sim UI meeting:
![image.png](https://images.zenhubusercontent.com/5e4c0e167596bf9860664828/c6bd8d3e-decb-488a-bc86-ac1ad129ea23)

2) Can we also get a bulk export feature to select multiple worlds (team and individual) to export in one go?

**Team World**
- Total # of experiments
- Average time per experiment
   - Remove any outliers > 60 minutes.
- Average & Range in Team World during team meeting.
- Average & Range Completion
- Need to merge the overall attendance at team meeting data with the Sim UI team world use live.

**Individual Worlds**
- number of team members who log in to their individual world
- Average/Range # of experiments team members run on their own.
- Median time in minutes for experiments in individual worlds.
- Average/Range % complete.

**Comment by jamesmrollins** [comment]
@lijenn.  This is complete.  I will open a different card regarding the API for @dkngenda
