### ISSUE TITLE
wk4_oct_epic: SIM UI FEATURE - Add Team Vision in team and ind worlds under the top nav bar

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2312]
Requested by Jane & Marcia from their live team meeting on Thursday at 8:30a Pacific:

Hi @jamesmrollins Can we add the Team Vision text somewhere here (highlighted) in the **team and individual worlds**:
![image](https://user-images.githubusercontent.com/59668647/137366034-cf1d017f-c3a7-4118-ac6e-020812940f21.png)

**Things to keep mind of:**
- We won't get their team vision until Session 1
- We do add the Team Vision in during their Sim UI world setup. 
_Could the text we want to add in this request be managed from here?_
![image](https://user-images.githubusercontent.com/59668647/137366533-9b3aae82-ae3e-4593-a1d6-4574309e0b1a.png)

-------------------------------------------------------------------------------------------
### Check off requirements to verify progress through feature_tracker.
- [ ] 1. **DEFINE in work_breakdown**
  - [ ] a. **what & why** - **written definitions of requirements** in a **numbered checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** requirement definitions an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 2. **DESIGN** in **operations_to_do** and **research_to_do**
  - [ ] a. **what & why** - **_MVP_ of design** of requirements in a **algorithm map, wireframes or design** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** design **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 3. **DEVELOP** in **under_development** - "frozen"

  Task Cards:
  #
---
- [ ] 4. **TEST in functional_test**
  - [ ] a. **what & why** - **TEST requirements** using **testing_checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** via TEST **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 5. **PROD in done**
  - [ ] a. **what & why** - **_DOCUMENT_ feature** using **document_tracker** for the **5 D's.** 
  - [ ] b. **date & who** -  **DELEGATE**
    - [ ] **describe_learners** [Jenn & Rita]
    - [ ] **detail_facilitators** [Jane & Debbie]
    - [ ] **document_team** [Anthony]
    - [ ] **disseminate_scientists_va** [Anthony]
    - [ ] **depend_products** [hq & ees]
  
  Task Cards:
  #
---
- [ ] 6. **closed** - fully documented, trained and ready for the next release.

**Comment by jamesmrollins** [comment]
Decided in the Sim UI meeting 10/20

- It may be empowering to associate the Team Vision with the model diagram.  This could help the facilitator and the learner make the association between what they want and the system that affects their vision.
- The bold face in the blue header does pop.
- Associating the model parameters with the experiments section makes more sense.
-
