### ISSUE TITLE
FACILITATOR SAY SCRIPTS - DUE 10/24/2018 - MTL Facilitate Workgroup

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#232]
Hello Everyone,

Please find the new folder for working on our Facilitator SAY Scripts here:
https://github.com/lzim/teampsd/tree/master/mtl_facilitate_workgroup/facilitator_say

s1 - Lindsey & David
s2 - Lindsey & Andrew (or Tom)
s3 - Lindsey & Andrew (or Tom)
s4 - Lindsey & Jane
s5 - Lindsey & Debbie
s6 - Lindsey & Jane
s7 - Lindsey & Jane
s8 - Lindsey & Debbie
s9 - Lindsey & Tom
s10 - Lindsey & David
s11 - Lindsey & Debbie
s12 - Lindsey & David

**Comment by branscombj** [comment]
The Facilitator Say files for sessions 1 and 5-12 are ready for the co-facilitators above to run them on down the field (or to the next base - more relevant to what's on my tv right now). You will note that they were last revised prior to today's decisions and will need, among other things:
+ To start with "We decided" when recapping what the DO from the end of the last session was;
+ To follow the guidance on "we";
+ To be written for MTL video for the immediate purpose (e.g. not include probing questions of participants).

**Comment by dlkibbe** [comment]
I have updated the say files for 1, 2, and 4. I will complete sessions 3 and 8 later this morning.

**Comment by dlkibbe** [comment]
I have updated the say files for 1, 2, and 4. I will complete sessions 3 and 8 later this morning.

**Comment by branscombj** [comment]
Thanks @dlkibbe! Per the divvying, I think you should prioritize finalizing 5, 8, 11 now, if all recent "say" work is updated in the rmd say files. 
OK by me to delete the old "[liveguide](https://github.com/lzim/teampsd/tree/master/mtl_facilitate_workgroup/mtl_live_guide)" folder.

**Comment by lzim** [comment]
@branscombj @dlkibbe @TomRust @dlounsbu @staceypark 

COMPLETE SCRIPTS POSTED BEFORE 8AM this WED 10/24! https://github.com/lzim/teampsd/tree/master/mtl_facilitate_workgroup/facilitator_say

**_Our 3 rehearsals are:_**
**10/24** - Full timed trial run of each 30 minute exercise (demonstrate live)  in 12 session plan - finalize standardization of facilitator say scripts on GitHub (6 hours)

**11/7** - Full timed trial run of the done/do for 12 session plan (3 hours); Practice 30 minute exercises of sessions 5-10 tailored to each module (MM, PSY, AGG, SP, CC) (3 hours)

**11/14** - Full timed trial run of each 30 minute exercise (demonstrate live) in the 12 session plan (6 hours)

- s1 - Lindsey & David
- s2 - Lindsey & Tom (or Andrew)
- s3 - Lindsey & Tom (or Andrew)
- s4 - Lindsey & Jane
- s5 - Lindsey & Debbie
- s6 - Lindsey & Jane
- s7 - Lindsey & Jane
- s8 - Lindsey & Debbie
- s9 - Lindsey & Tom
- s10 - Lindsey & David
- s11 - Lindsey & Debbie
- s12 - Lindsey & David

**Comment by dlkibbe** [comment]
@lzim @branscombj @staceypark As a reminder, due to conference attendance, I will be on the call from approximately 2:00 - 4:00 pm at an airport.

**Comment by branscombj** [comment]
@TomRust @dlkibbe @dlounsbu - Put another way, we need to have in-session scripts (i.e., excluding Done/Do segments) finalized for rehearsal by tomorrow at 11am Eastern. Lindsey is co-facilitator for all sessions.
David 1, 10, 12
Debbie 5, 8, 11
Jane 4, 6, 7
Tom 2, 3, 9 (if not Andrew 2, 3)

**Comment by lzim** [comment]
@staceypark we do have a demo version, we should use the one from the MTL Facilitate Pilot as it has SP in it.

Thanks!

**Comment by lzim** [comment]
@branscombj and @dlkibbe 

- Please work to flesh out any missing experiments and clean up the language here:
https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/facilitator_say/model_details_say_scripts.md

@TomRust and @lzim will add the Measurement Based Stepped Care for Suicide Prevention examples

@staceypark will work to build out the demonstration worlds that we will use for the _MTL Video_ shoot.

**Comment by branscombj** [comment]
3 questions  - these are from MM but they apply to others too:

1.	Is it correct that the polarity of Completing Rate -> True Missed Appointment Rate is +? If so, I’m not getting something. I’d think that more Completed Appts either means "completed by patients showing up", therefore directly reducing missed appts, or means more appointments passing by on the calendar, whether show or no-show, i.e. the denominator for Missed Appointment Rate, which would also reduce Missed Appt rate. What am I missing?
2.	I remember (not crisply) the discussion of what “measured” vs “actual” time means; but it’s not made explicit in the “i” text and I’m having trouble explaining it in script.
3.	Is the name of the next variable, Effect of Task Time on Missed Appointments, still correct after changing the prior variable to this Measured Vs Actual name? Note the heading in the “i” box of the 2nd variable below. Also note that in the text for that one, it refers to the meaning of the quantity as "provider fatigue" - the only time that part of the concept appears.
Thanks!
Jane 

Variable label: Measured versus Actual Time
"i" box heading: Measured versus Actual Time
"i" box content: This represents the relative change in time available for other MM-related tasks consumed by overbooking patient visits. We assume that these "extra" appointments come at the expense of "other MM related tasks," such as , team coordination, patient reminder calls, chart review and other appointment prep, etc. It is constrained from going to zero, even if official appointment supply is zero.

variable label: Effect of Task Time on Missed Appointments
“i” box heading: Effect of "Other MM Tasks Time" [sic] on Missed Appointments
"i" box content: The deviation from the the base case missed appointment rate is controlled by an exponent that reflects how sensitive both patients and providers are to provider fatigue. The negative sign on the exponent indicates that this is inversely coded, i.e., decreasing time for other MM tasks (e.g., appointment prep, follow-up, reminder calls) increases the missed appointment rate. Patients start to experience this reduced quality by their next appointment, which occurs after the teams actual return visit interval. The effect is restricted from going below 1, as lower than official work hours do not influence providers or patients to come more regularly to their appointments.

**Comment by branscombj** [comment]
@staceypark could you get us the MTL menu referenced above when you get a chance please
https://github.com/lzim/teampsd/issues/232#issuecomment-432680608 - Thanks!

**Comment by branscombj** [comment]
Morning team @lzim @dlkibbe @dlounsbu @TomRust 
Can anyone can help me with the 3 Questions above https://github.com/lzim/teampsd/issues/232#issuecomment-434050396 Thanks!

**Comment by TomRust** [comment]
Sorry @branscombj , I didn't see your questions.  

1) "Completing Appointments" doesn't necessarily mean that both the provider and patient were at the appointment.  You're right that it means "more appointments passing by on the calendar, whether show or no-show."  The model takes what we know about the ratio of missed appointments to total appointments (the Missed Appointment %), and applies that ratio going into the future, regardless of how many appointments they have per week. We're assuming that the appointment rate is not influencing the % who no-show (it will affect the # who no-show (i.e., the Missed Appointment Rate), but not the %).  

2)  The "relative change in time available for other MM-related tasks" is how much time the team loses for these "other tasks" when they start overbooking.  It is the ratio of "Official Total Appointment Supply over the "Current Total Appointment Supply," so as current hours increase (because they start working through lunch), then the ratio decreases.  The tricky part about this is that the variable is not measured in hours, but as a ratio.  Example, if they are a big team, with lots of hours, and they start overbooking 1 hour a week, the variable "Measured versus Actual Time" will decrease a tiny bit  (to maybe 0.99 instead of 1).  If a very small team started overbooking 1 hour per week, then we'd see a much larger drop in "Measured vs Actual Time"...maybe it would drop from 1 to 0.8 or 0.7.  What we care about is the **relative** change in time available for non-patient-facing care delivery.

3) If "Effect of Task Time on Missed Appointments" is not immediately clear, then it's not correct.  :)  How about "Effect of Losing Non-Patient-Facing Care Delivery Time on Missed Appointments"?  The Effect only applies when the team loses non-patient-facing time (there is no negative overtime, and even if there were, we assume it would not reduce the Missed Appointment %).

**Comment by staceypark** [comment]
@branscombj 
Here is a copy of the plots (the view we would walk through learners with):
[mtl_menu_demo_plots.pdf](https://github.com/lzim/teampsd/files/2550450/mtl_menu_demo_plots.pdf)
Here is a copy of the results in an excel sheet format:
[mtl_menu_demo_data.xlsx](https://github.com/lzim/teampsd/files/2550446/mtl_menu_demo_data.xlsx)

@lzim 
Below are 5 copies of the survey, one for each module, that we can fill out with tailored responses to fit each module:
https://is.gd/cc_demo
https://is.gd/mm_demo
https://is.gd/psy_demo
https://is.gd/agg_demo
https://is.gd/sp_demo

**Comment by lzim** [comment]
Thanks @tomrust and @staceypark!

**Comment by staceypark** [comment]
@dlounsbu HOw are the scripts coming along for sessions 11 & 12 tomorrow?

**Comment by branscombj** [comment]
@dlounsbu Please look at them and edit if you see things you want to improve. You can give them a time check as well.

**Comment by lzim** [comment]
Thanks @branscombj @dloundbu for moving these sessions forward!

**Comment by branscombj** [comment]
@lzim, @dlkibbe and I discussed the "Next are the dones and dos" edit, which I propose tweaking to say "Next is our Done/Do review" at both the beginning and end of each session, without naming the session.

So Session 1 begins, "I'm _, I'm _, and today we're modeling to learn..." We start and end each session by reviewing what we've done and what we will do next. Before this first session, we... . In today's session we will..."

Session 1 in-session exercise ends "Thank you for modeling to learn... . Next is our Done/Do review."

End of Session 1 Done/Do review starts: "Today we... Before next time we will..." and goes into the 3 S's.

Session 2 begins, "I'm _, I'm _, and today we're modeling to learn..." Next is our Done/Do Review."
Session 2 Done/Do Review starts, "Before the session, we... . Today we will..." 
Session 2 In-session exercise ends: "Thank you for modeling to learn... . Next is our Done/Do Review."
End of Session 2 Done/Do review starts: "Today we... . Before next time we will..."

We could end each end-of-session Done/Do Review with simply, "Thank you for Modeling to Learn!"

**Comment by dlkibbe** [comment]
@lzim I'm making the edits to the scripts today.

**Comment by branscombj** [comment]
@dlkibbe ,

I tweaked your edits to Sessions 1-5 in your branch and created a pull request for all of those changes.

Subject to others’ review and feedback, I settled on the following which seemed to me most concise and flowing (Session 1 is slightly different because it’s the first one; but in general):

1.	Facilitator introductions: I’m _, I’m _ and today we’re modeling to learn _
2.	Next, some version of, “As shown in the Done/Do table of the Learner See Guide for this session:” then just recite the Done, Do and Resources from the Done/Do table.
3.	Next is the facilitator line, “After this session you will be able to:” followed by reading the learning objectives.
4.	After LO 3, facilitator says “Let’s get started:” and goes straight into Step 1.
5.	After the last step, facilitator says, “That’s it for modeling to learn how to whatever it is. Next is our Done/Do Review.”
6.	For the Done/Do review, facilitator reads from the table, then expounds on the Do with a section of script I’ve labeled “DO demo”.
7.	Facilitators go through Steps 1 through n of the DO demo.
8.	After the last step they say, “Until next time, thanks for _Modeling to Learn_!

If this is good by you and @lzim , perhaps you could continue making those edits in Sessions 6-12?

Non sequitur : I think it's fine, but I just realized that the Learner See Guide we show during MTL Video will have the MTL Live logo at the top of each session guide. OK?

**Comment by dkibbe** [comment]
I am not on this list. I am not D L Kibbe. Please remove my name.

Thx,

Dennis (not L) Kibbe

**Comment by branscombj** [comment]
@lzim  All of the standard transitional language for the facilitator say files has been pushed to master.  @dlounsbu @TomRust  **When you have finished fleshing out experiments 1, 2 and 3 either in the 1.7 simUI test world or in the [Model Details for Facilitator Say Scripts](https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/facilitator_say/model_details_say_scripts.md) for your module, please ping @dlkibbe  and me** so we can import them into the Session 5-10 Say files for each of the modules. Thanks! 
_p.s. We need to be careful with our tagging: I saw that a "dkibbe" was tagged who is not Debbie, and I accidentally tagged a not-David Lounsbury whose github username starts with dlo._

**Comment by branscombj** [comment]
@lzim @TomRust @dlounsbu @dlkibbe Still so many questions as I run sims. Running CC in 1.7 with the abc dataset Tom built/Stacey uploaded. Starting Rate in table is 3.82. Showing on widget is 31.94. Where does that number come from? When I run a BC, it doesn't drop from 31.94 to 3.82; it drops from 4.4 to 3.82. Where did the 4.4 come from? How would I know that choosing Use Team Data ON would mean decreasing Starting Rate by that smaller amount vs the huge one indicated by the widgets?

What numbers populate the widgets in default view, anyway?

**Comment by lzim** [comment]
@jamesrollins take a look at @branscombj’s post

**Comment by lzim** [comment]
Happy WEEKEND er'body :wave:

Two questions - I was going to start a work session, but I noticed there aren't any pull requests?
I'm happy to review them as they come in over the weekend, rather than have a glut of things :ocean: next week as we get closer to the holiday.

- If there aren't any edits to merge with the Master via pull requests, **are there instead updated experiments to review in the "demo_worlds"?** @branscombj and my own testing has identified places where our allowable range and the dataset are unworkable together. 
- We want to make sure we get on that with @TomRust and @jamesmrollins **by COB Sunday or AM Monday if we can, since it requires work on the .mdl files and with  DEV to fix. Are there others?** ***Especially in MM, PSY, AGG or SP?***

- Quick note on the "i" information - we'll keep that tracked in the **Master Cross-Walk - Check-out System #208**  

- @jamesmrollins will take our GitHub work and add it to the ***MASTER CROSSWALK FILE FOR DEV on MONDAY***

THANKS All! ☺️ 

@branscombj @branscombj @TomRust @dlounsbu @staceypark

**Comment by dlkibbe** [comment]
@lzim @branscombj my bad... I edited session 6 say file on the master. Not done yet... Today is my work day for MTL.

**Comment by branscombj** [comment]
@lzim and @dlkibbe Also fleshed out bc and exps in CC and MM, but ran into questions again, which I've posted - except one I only emailed to Tom - but I'll post that one too in case others can clear it up.

**Comment by staceypark** [comment]
@branscombj @dlkibbe @dlounsbu @TomRust @lzim 
Hi all, As folks are finishing up writing the SAY scripts, I wanted to add something I noticed while reviewing the systems stories and experiments in the suicide prevention module.
It is really helpful for me as the "learner" for the q/h/f/d:
1) To be consistent across the bc through exp 3 in level of detail and style used to walk through the story
2) Reference specific model variables that I can look for and pull up in the Results Dashboard.

@lzim Tom is updating the SP module scripts to make them clearer and they'll be ready by 9AM pacific tomorrow.

**Comment by staceypark** [comment]
@branscombj @dlkibbe @dlounsbu @TomRust @lzim
AGG Questions
**Basecase**
1. Hypothesis: The script is written in a matter that makes it seem as if MM and PSY have the highest engagement time and account for the highest service proportions. However, based on the team data table in the sim, Adjunctive is next highest.  This is confusing.
2. Findings: "Interestingly, patients receiving group services drops to about 100 patients at about 1.5 years into the simulation run." I'm not sure how/where you're seeing that?

**Comment by dlounsbu** [comment]
What I saw was that the engagement time was too long, based on evidence based practice. An evidence based dose of PSY would be delivered in 12 to 14 weeks.

When I change the Return Interval, Interesting things happened, including a reduced number of PSY patients.

I agree we can provide additional context and should clarify my thinking.

D

David Lounsbury
Sent from my iPhone

On Nov 20, 2018, at 9:33 PM, Stacey Park <notifications@github.com<mailto:notifications@github.com>> wrote:


@branscombj<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbranscombj&data=02%7C01%7Cdavid.lounsbury%40einstein.yu.edu%7C405cbcd844a24dadcca908d64f59c7db%7C04c70eb48f2648079934e02e89266ad0%7C1%7C0%7C636783644357863352&sdata=gpl6cDiikEoka6IwDwcqfcsf238u1Pyg11sNb86S02g%3D&reserved=0> @dlkibbe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdlkibbe&data=02%7C01%7Cdavid.lounsbury%40einstein.yu.edu%7C405cbcd844a24dadcca908d64f59c7db%7C04c70eb48f2648079934e02e89266ad0%7C1%7C0%7C636783644357863352&sdata=yGLZSYD1s2TxyyRr28WBGRlcqKftbgSn0%2B0tPoyi7II%3D&reserved=0> @dlounsbu<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdlounsbu&data=02%7C01%7Cdavid.lounsbury%40einstein.yu.edu%7C405cbcd844a24dadcca908d64f59c7db%7C04c70eb48f2648079934e02e89266ad0%7C1%7C0%7C636783644357863352&sdata=DMn9THC2rqxH1o76RA7Sa54Oxlv3pWnaxGrHJNO1BBE%3D&reserved=0> @TomRust<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTomRust&data=02%7C01%7Cdavid.lounsbury%40einstein.yu.edu%7C405cbcd844a24dadcca908d64f59c7db%7C04c70eb48f2648079934e02e89266ad0%7C1%7C0%7C636783644357863352&sdata=hkq4k%2FVWlk4d1RwJdFm1AR5rPRf1Dp8PKcZaFWQCeoE%3D&reserved=0> @lzim<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flzim&data=02%7C01%7Cdavid.lounsbury%40einstein.yu.edu%7C405cbcd844a24dadcca908d64f59c7db%7C04c70eb48f2648079934e02e89266ad0%7C1%7C0%7C636783644357863352&sdata=WrwJQDaxbbDFfgMjRVaIkg%2FXarotGpqRIVxWSRLN6DY%3D&reserved=0>
AGG Questions
Basecase

  1.  Hypothesis: The script is written in a matter that makes it seem as if MM and PSY have the highest engagement time and account for the highest service proportions. However, based on the team data table in the sim, Adjunctive is next highest. This is confusing.
  2.  Findings: "Interestingly, patients receiving group services drops to about 100 patients at about 1.5 years into the simulation run." I'm not sure how/where you're seeing that?

**Comment by dlounsbu** [comment]
I think we need to keep in mind that there are a multitude of possible experiments that teams can run. And running 3 or 4 quick experiments is all just a warm up exercise.

Also, I would argue that, especially in AGG, there may not be an obvious optimal strategy. But we can model to learn ....

David Lounsbury
Sent from my iPhone

On Nov 20, 2018, at 9:33 PM, Stacey Park <notifications@github.com<mailto:notifications@github.com>> wrote:


@branscombj<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbranscombj&data=02%7C01%7Cdavid.lounsbury%40einstein.yu.edu%7C405cbcd844a24dadcca908d64f59c7db%7C04c70eb48f2648079934e02e89266ad0%7C1%7C0%7C636783644357863352&sdata=gpl6cDiikEoka6IwDwcqfcsf238u1Pyg11sNb86S02g%3D&reserved=0> @dlkibbe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdlkibbe&data=02%7C01%7Cdavid.lounsbury%40einstein.yu.edu%7C405cbcd844a24dadcca908d64f59c7db%7C04c70eb48f2648079934e02e89266ad0%7C1%7C0%7C636783644357863352&sdata=yGLZSYD1s2TxyyRr28WBGRlcqKftbgSn0%2B0tPoyi7II%3D&reserved=0> @dlounsbu<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdlounsbu&data=02%7C01%7Cdavid.lounsbury%40einstein.yu.edu%7C405cbcd844a24dadcca908d64f59c7db%7C04c70eb48f2648079934e02e89266ad0%7C1%7C0%7C636783644357863352&sdata=DMn9THC2rqxH1o76RA7Sa54Oxlv3pWnaxGrHJNO1BBE%3D&reserved=0> @TomRust<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTomRust&data=02%7C01%7Cdavid.lounsbury%40einstein.yu.edu%7C405cbcd844a24dadcca908d64f59c7db%7C04c70eb48f2648079934e02e89266ad0%7C1%7C0%7C636783644357863352&sdata=hkq4k%2FVWlk4d1RwJdFm1AR5rPRf1Dp8PKcZaFWQCeoE%3D&reserved=0> @lzim<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flzim&data=02%7C01%7Cdavid.lounsbury%40einstein.yu.edu%7C405cbcd844a24dadcca908d64f59c7db%7C04c70eb48f2648079934e02e89266ad0%7C1%7C0%7C636783644357863352&sdata=WrwJQDaxbbDFfgMjRVaIkg%2FXarotGpqRIVxWSRLN6DY%3D&reserved=0>
AGG Questions
Basecase

  1.  Hypothesis: The script is written in a matter that makes it seem as if MM and PSY have the highest engagement time and account for the highest service proportions. However, based on the team data table in the sim, Adjunctive is next highest. This is confusing.
  2.  Findings: "Interestingly, patients receiving group services drops to about 100 patients at about 1.5 years into the simulation run." I'm not sure how/where you're seeing that?

**Comment by branscombj** [comment]
@staceypark @lzim @dlkibbe @dlounsbu @TomRust 
All- I finshed bc & exp1,2,3 for MM in the 1.7 TEST environment, MM Demo world. Please check it out before I transfer it to the Say script. Thanks!!

**Comment by dlounsbu** [comment]
@branscombj I have called up and read through, and compared all of your experiments in MM. Your Q,, H, F, and D text was very clear and corresponds with what I was able to see in the expanded output figures. I think this can be your final!

**Comment by TomRust** [comment]
@lzim @branscombj @dlkibbe @dlounsbu 

I've been putting the final touches on the scripts for SP across all the SAY files, and am a bit confused.  I thought we needed to be as explicit as possible with the SAY scripts -- putting in all the directions (eg, "click on...") and explanations for why we're finding the results that we see.  The text explaining the hypothesis and findings for the SP experiments are paragraphs long.  

Should I cut them down to match the length of the others?  If so, then where should I save all that detail that we need to say in the video?  

--TOM

**Comment by branscombj** [comment]
@TomRust - One response is to see if the content is fairly balanced for SP across each set of qhfd. Sometimes you can put a little more of the "thinking out loud" into the previous or next box, and that might make the delivery feel more balanced. 
   If you're asking about making the text the same as for the other modules, I think it's good to head in that direction, but also know some are just more complex than others and may need a little more content.
   Yes to directional verbiage, navigation, etc, which may not be as well fleshed out in some of the others but I have it on my agenda to go through everything for that as much as I can.
   If you cut any material from the Session Say Scripts that you think is useful to hang onto for future reference, please put it in the Model Details Say Scripts. Those will also need to be built out for MTL Live with scripts for all the rest of each systems story and reveals that we're not using in MTL Video.

**Comment by TomRust** [comment]
Thanks, @branscombj! 

One more question for the group, though @lzim @branscombj @dlkibbe @dlounsbu:
I thought we were going to use the same set of experiments for PSY in MTL Video that we did with the TAS group from our MTL Facilitate Pilot.  Is that not right?  @staceypark: Didn't you paste in the QHDF text from the MTL Facilitate Pilot World?

**Comment by dlkibbe** [comment]
I re-ran CC experiments in PROD, but did it in my individual world. I have 1 left to run and can re-run others. First, I was going to work on making the say file scripts for Q,H,F,D more uniform/same voice in response to @lzim comment from earlier.
@branscombj @lzim @jamesmrollins @TomRust @staceypark @dlounsbu

**Comment by branscombj** [comment]
@lzim @dlkibbe @dlounsbu @TomRust @staceypark 
Debbie and I get in tomorrow at 6:25. I have rental car (full-size this time!). Let me know if you're commuting around then and want to ride with us. @lzim I'm up for dinner and if @dlkibbe  is OK it's fine with me to go straight from the airport without checking in first.
Am I getting that @dlounsbu  prepared a different set of experiments for PSY than what you wanted to use, @lzim ? Do those need to be redone?

**Comment by branscombj** [comment]
@lzim and @dlounsbu (& @dlkibbe @TomRust ) - I have been using the Blame function to compare what was pasted in to the [Model Details Say Scripts](https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/facilitator_say/model_details_say_scripts.md) file by Lindsey with what David developed and pasted in from his MTL1.7test work. It looks to me like basically the same course of experiments, except that David increased how much he moved a lever in exp 2 to show a larger effect; fleshed out the script with more detail; and worked up exp 3 which wasn't there. Was this not the set of experiments we did with TAS?

**Comment by lzim** [comment]
Actually, I was wondering about PSY because of @tomrust's question about it being different than the TAS. If it is not and matches the Model Details file, then don't worry about that :smh

**Comment by dlkibbe** [comment]
@staceypark I've run the cc experiments but was waiting for the "repair" to the slider range to run experiment 3 and generate the say text as referral rate was the final variable to be tested. 
See report here: https://github.com/lzim/teampsd/issues/287#issuecomment-441285212

**Comment by branscombj** [comment]
@lzim I bet it was in Issues where you found you could copy and paste from Excel and it would auto-format as a table! Below is the status of the non-module-specific sessions. @dlkibbe and I are at our gate working on some of this.


Session | Min | LZ& | Status | Needs
-- | -- | -- | -- | --
1 | 30 | David | 100% |  
2 | 30 | Tom | 100% |  
3 | 30 | Tom | 95% | Key SP variables bullet under step 3b
4 | 30 | Jane | 80% | Menu output for each module; any accompanying script beyond   module blurbs that I pasted in.
11 | 30 | Debbie | 99% | For MTL Video: add some script about what "some other   teams" decided (vision, need, Qs, Ds)?
12 | 30 | David | ? | Now have some dup script in sess 11 & 12. What should be   different?
DoneDo | Min | LZ& | Status | Needs
1 | 15 | ? | 100% |  
2 | 15 | ? | 0% | Full script
3 | 15 | ? | 80% | More detail for navigation; fill in time est for mtl menu
4 | 15 | ? | 100% |  
11 | 15 | ? | 90% | Words about SP for last bullet of Step 2
12 | 15 | ? | 0% | Do we need a DO Demo for Session 12?

**Comment by lzim** [comment]
@branscombj @dlkibbe @TomRust @dlounsbu and @staceypark 

Following up on last week - I think we should start on having two sets of SAY files (I know, crazy that I would suggest two sets, when I always want to simplify to a singular version). 

But, in this case, I propose that we keep the _MTL Video_ set of SAY so that we have a record of exactly what we did for _MTL Video_ Including all the examples.

Then, I think we should draft our "final" more universal set of the 12-session plan for _MTL Live_ that has all the insights from last week, but none of the details that would be specific to a particularly teams need. What do you all think?

Lindsey

**Comment by branscombj** [comment]
That makes sense to me. Actually, what would be really helpful would be to get the actual, as-recorded sessions audio-transcribed. They have all of your ad libs including principles, metaphors, and clinician perspective. Rev.com is a service I’ve used that’s fast and accurate and costs $1 per recorded minute. Could we do that? They do captions for the same rate — do we have to do it for 508?

**Comment by dlkibbe** [comment]
@lzim I agree with this proposal. If transcription is not in the budget, we have a head start with the edited say files on my laptop.

**Comment by lzim** [comment]
@branscombj @dlkibbe @dlounsbu @tomrust and @staceypark

Yes, everything said on camera will all be transcribed for closed captioning to make _MTL Video_ 508 compliant.

Not sure about how smooth that will be for use as SAY files, but we can ask Elizabeth and Ann.

**Comment by staceypark** [comment]
Next steps: 
1. EES team will send out links to MTL Video for team to review. We will divvy up the review.
2. Once finalized, they’ll do captioning and send us transcripts.
3. We can use those to produce 1) Verbatim SAY files and 2) Finalize SAY files for future facilitators
