### ISSUE TITLE
wk4 oct_epic: SIM UI - Unable to upload Team Data Files to produce Red TT Reports

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2326]
@jamesmrollins While trying to produce tt red reports, I am unable to upload the team data file for MTL Red teams.
After selecting a team and selecting the file I want to upload, I see that the file is uploading based on the loading bar:
![image](https://user-images.githubusercontent.com/59668647/138795588-a8c96d1d-03cb-45d9-91ef-341caad37905.png)

However, I cannot find the file that I just uploaded in Team Data and therefore, cannot produce a Redd TT report.

**Comment by jamesmrollins** [comment]
Hi @lijenn - this problem in our estimation was an internet communication issue that was preventing the API from transmitting necessary information indicating the file was indeed transferred.  I recommend we close this issue.
