### ISSUE TITLE
wk1_nov_epic: SIM UI - Collapsible Experiment Timeline for Model Diagram Scroll

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2329]
Discussed in https://github.com/lzim/teampsd/issues/2315 Model Diagram Scroll:

Due to the Experiment Timeline blocking the majority of the Model Diagram, this prevents Facilitators and Learners from developing CFBT skills without being able to see the whole systems story. A collapsible Experiment Timeline could help solve this issue:

![image](https://user-images.githubusercontent.com/59668647/139161353-7e34d162-bca0-4144-b0f1-b31b498043a8.png)

### Check off requirements to verify progress through feature_tracker.
- [ ] 1. **DEFINE in work_breakdown**
  - [ ] a. **what & why** - **written definitions of requirements** in a **numbered checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** requirement definitions an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 2. **DESIGN** in **operations_to_do** and **research_to_do**
  - [ ] a. **what & why** - **_MVP_ of design** of requirements in a **algorithm map, wireframes or design** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** design **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 3. **DEVELOP** in **under_development** - "frozen"

  Task Cards:
  #
---
- [ ] 4. **TEST in functional_test**
  - [ ] a. **what & why** - **TEST requirements** using **testing_checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** via TEST **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 5. **PROD in done**
  - [ ] a. **what & why** - **_DOCUMENT_ feature** using **document_tracker** for the **5 D's.** 
  - [ ] b. **date & who** -  **DELEGATE**
    - [ ] **describe_learners** [Jenn & Rita]
    - [ ] **detail_facilitators** [Jane & Debbie]
    - [ ] **document_team** [Anthony]
    - [ ] **disseminate_scientists_va** [Anthony]
    - [ ] **depend_products** [hq & ees]
  
  Task Cards:
  #
---
- [ ] 6. **closed** - fully documented, trained and ready for the next release.

**Comment by jamesmrollins** [comment]
## Decided MVP 1 with Changes

- Change entire name to "Reveal Causes."
- Move checkboxes to top of menu and move timeline and run buttons to the bottom.
- James to design an MVP and present by Monday.

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire - I put this in GitHub on Saturday.  I'm not sure why it didn't save - I must have forgotten to save it.  Below is what the final design looks like.

![image](https://user-images.githubusercontent.com/30132017/141721810-20bf89ac-f1cb-40f9-9833-7b64d780beb8.png)
