### ISSUE TITLE
wk5 nov_epic story_13 Discuss with BISL where/how to host PBI for user testing

### ISSUE THREAD

**Issue by jeffhoerle** [lzim/teampsd#2347]

**Comment by mnallajerla** [comment]
Transferring what we discussed at Overflow 8 AM 11.24.21 here for reference:

DECISION on #2347: 

- [ ] We hope @jeffhoerle  will be able to get Gateway and DEV > TEST > PROD instances set up early wk5 nov_epic (next week).
- [ ] We will point the Chula Vista team to the PBI TEST instance 
- [ ] Once published we will point https://mtl.how/data_test there.
- [ ] Need to get Durham out of the Data tabs (see #2371 for more info)

FYI: @lijenn @lzim @dkngenda @staceypark

**Comment by lijenn** [comment]
Discussed 8am Workgroup Leads:

Gateway:
When you publish a report to a pipeline, it's uploaded as a blank report with no date.
To get data populated, it needs to bounce off a gateway as the data source.

**Comment by mnallajerla** [comment]
Update on access issue above (checkbox #1) - Gateway is fixed but @lijenn and I tested access and I cannot access my own "team" (Palo Alto)'s data: 
![image.png](https://images.zenhubusercontent.com/6130066bf230e9289f9a2c0c/292e96e0-3ff0-4c9a-92e9-dc63b545847a)

**Comment by mnallajerla** [comment]
Notes from Prep:

- [ ] Bug #2393 still an issue 

- [ ] Selecting multiple choices at once = would be helpful (either a "Select All" button or way to select multiple clinics at once)


FYI @lijenn

**Comment by mnallajerla** [comment]
Notes from Chula Vista Session 2:

> Question from the team: Can "Other" category be broken down further?



In the data tabs, the "ICD Code Description" column has details of what the "Other" category may be

At this moment, there is not a way to break down "Other" category in the Viz tabs. Thank you to the team for raising this, we will make a note of it and look into it :)

**Comment by mnallajerla** [comment]
@lijenn & @mnallajerla discussed at 12.9.21 Quant Operations WG. This card is good to be closed.
