### ISSUE TITLE
wk3_nov_epic facilitate Typo in Purpose section of Community of Practice

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#2359]
## 1. Link to the document and add relevant team members to the card.
- [ ] Add the link the current draft of the documentation for the issue: https://github.com/lzim/mtl/wiki/02_Purpose

## 2. Link to issues that must be edited in the document in the **issue_tracker** and **feature_tracker.** _(use the # for the link to the issue)_

a) I deleted the duplicate text in bold:

> This policy is subordinate to the Team Participatory System Dynamics (Team PSD) Issues Tracker Policy and Procedure, and details the governing principles, definitions, responsibilities and procedures for managing cards and issues that **Participatory Design, Learning and Research Process, Policy and Procedure** come to the CP tracker from the Participatory Learning, Design and Research (PLDR) algorithm within the Modeling to Learn (MTL) Simulation User Interface (Sim UI). This policy applies to all Work Group members in Team PSD and the wider Community of Practice (CP) involved with research under the R21, R01, and IIR grants , commonly known as Modeling to Learn (MTL). Any issues identified with this policy should be brought to the attention of the Principal Investigator, Lindsey Zimmerman, (lindsey.zimmerman@va.gov) or designee.

b) I am not sure: Would we still say PLDR algorithm or would we say Community button (/option/icon/app)?

## 3. Team Review
- [ ] Fidelity - check with Lindsey
- [ ] Data UI - check quant_workgroup
- [ ] Sim UI - check with model_workgroup and/or sim_workgroup

## 4. Review and Open Pull Requests _(use the # for the link to the pull request)_
- [ ] Check the draft for typos
- [ ] Check or open a pull request for the document edits

## 5. Review and/or Update Graphics
- [ ] Screenshots
- [ ] Gifs
- [ ] Logos/Icons
- [ ] Links

## 6. Dependencies
- [ ] Make sure that any edits you make that need to be added to **depend_product** are tracked (e.g., _MTL Video_)

## 7. Close Pull Requests
- [ ] Request review and/or close open pull requests for the document

**Comment by jamesmrollins** [comment]
Hi @branscombj - Yes - definitely more meaningful to the user to call it the Community button - it replaced the PLDR term years ago.  Another question - what is a "CP Tracker?"  All the Community button submissions go to the Bug Tracker - Triage queue.  I'm not sure we ever set up a CP Tracker (kanban)?

I'm going to do some Community button testing to see what actually happens (been a long time).

**Comment by jamesmrollins** [comment]
Hi @branscombj - I reviewed the Community Button functions and found that indeed, the comments land in the Bug Tracker.  That way the Workgroup Leads will spot it and respond.   May I suggest the following language:

"This policy is subordinate to the Team Participatory System Dynamics (Team PSD) Issues Tracker Policy and Procedure, and details the governing principles, definitions, responsibilities and procedures for managing issues that come to the Bug Tracker Project from the Community button algorithms within the _Modeling to Learn_ (_MTL_) Simulation User Interface (Sim UI). This policy applies to all Work Group members in Team PSD and the wider Community of Practice (CP) involved with research under the R21, R01, and IIR grants , commonly known as _Modeling to Learn_ (_MTL_). Any issues identified with this policy should be brought to the attention of the Principal Investigator, Lindsey Zimmerman (lindsey.zimmerman@va.gov), or designee."

**Comment by branscombj** [comment]
Thanks, @jamesmrollins - works for me!
