### ISSUE TITLE
wk3 nov_epic: DUE 11/30 IRB Renewal & Mods via eProtocol

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2360]
**R01 & IIR**

**Modifications needed for re-submisison no later than 11/30.**
- [x] Add Meghana
- [x] Remove any old staff
- [ ] Add the open feedback item to the provider survey

_Note:_ I know @staceypark was working on this, but I searched for "IRB" and didn't find a card.

_Additional note:_ We may  need to include incentive for completion of volunteer provider surveys. Lindsey is seeking advisement on this.

Here is the link to Survey guidance: https://www.research.va.gov/resources/SurveyGuidance.pdf

**Comment by mnallajerla** [comment]
Once I'm added onto the protocol, please let me know how I can help with updating or making any edits. I am pretty familiar eProtocol and can easily jump in.

**Comment by mnallajerla** [comment]
Discussed @ 11/15 WG Leads: Sounds like @staceypark submitted and we received confirmation email?

@lzim @lijenn
