### ISSUE TITLE
wk4_nov_epic: QA PROD Sim UI Graph Lines and Collapsible Timeline

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2365]
## UAT Checklist regarding #2329 Collapsible Timeline.

- [x] Title of dialogue box is changed from "Timeline" to "Reveal Dynamics over Time" for all models except SP that is still "Setting View" since the radio buttons change entire model diagram between GMH, SMH and PC/PCMHI. 
- [x] The dialogue box provides a collapse standard triangle in the proper orientation that collapses box to just the title, and expands to full length. 
- [x] All reveal checkboxes work as indicated.

## UAT Checklist regarding #2246 Hard to See Graph Trendlines

- [x] All graph "x" and "y" axis are now VA Grey.  
- [x] All trendlines when juxtaposed on trendlines are visible (especially black).

## Following documents are updated to reflect changes

- [x] Sim UI Cheatsheet
  - [x] Session 4
  - [x] Session 5
  - [x] Session 6
  - [x] Session 7 
  - [x] Session 8 
  - [x] Session 9
  - [x] Session 10
  - [x] Session 11
  - [x] Session 12
- [x] mtl_session05_see.md 
  - [x] sim_ui_sp_i_information.gif
  - [x] sim_ui_sections.gif
  - [x] s5_i_information.gif
  - [x] sim_ui_pop_ups.gif
- [x]  mtl_session06_see.md - Updated "Reveal Dynamics over Time" text
  - [x] sim_ui_reveals.gif
  - [x] sim_ui_text_fields.gif
- [x] mtl_session07_see.md
  - [x] sim_ui_text_fields.gif
- [x] mtl_session08_see.md
  - [x] sim_ui_previous_exp.gif 
  - [x] sim_ui_adjust_sliders.gif

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire .   Please make adjustments to the designs as shown below:

![image](https://user-images.githubusercontent.com/30132017/141838155-ffb3b7b5-4487-4a2e-b713-c734fb4f29fb.png)

**Comment by jamesmrollins** [comment]
From Sim UI 11/17:

- James Ok to update the .gifs and documents listed above.
- James will complete by Monday.
- @mnallajerla will provide QA via pull requests for the documents.

**Comment by jamesmrollins** [comment]
HI @lijenn .  Here are a few news release ideas.

### New Features Release

On December 3rd, you may notice new changes to the Simulation User Interface.  Based on user feedback we made several changes we hope improve the ease-of-use and understanding of the interface.

-  The Experiment Timeline has been redesigned to be collapsible to improve the viewing area of the simulation diagrams.  It is also reformatted to place the Reveal Dynamics over Time checkboxes on the top.
- The Question, Hypothesis, Findings and Decision Text box now has three sizes so the user can adjust the size to view the Diagram, Text and Outputs sections all open at the same time.
- The x-axis and y-axis of the charts in the Outputs and Text section have been changed from dark blue to light grey to improve visibility of lines.

**Comment by lijenn** [comment]
@jamesmrollins Thanks so much for your work on this :)

Edited slightly below, let me know if you have any thoughts. 
Also let me know if you'd like me to make these edits in News and turn on the message.

### New Features Released on 3 December!

-  The Experiment Timeline has been redesigned to be collapsible to improve the viewing area of the simulation diagrams. It is also reformatted to place the Reveal Dynamics over Time checkboxes on the top.
- The Question, Hypothesis, Findings and Decision Text box now has three sizes so you can adjust the size to view the Diagram, Text and Outputs sections all open at the same time.
- The model diagram now has a scroll bar to refer to feedback loops as write in the Text box and view results in the Output box.
- View your Team's Vision statement in the diagram header. The Team Data filename is now located in the Experiment section header.
- The experiment save button now automatically generates the experiment name based on the variables you changed.

**Comment by jamesmrollins** [comment]
Hi Jen did it see you made looked really good but we do have a 150 word limit for the news feed it looks like your contributions may be longer than that

**Comment by lijenn** [comment]
:O Is it? I'm getting 134 word count @jamesmrollins

**Comment by lijenn** [comment]
@jamesmrollins I just added it into the Sim and it fits within the word count! Anything I'm missing about it? 
Otherwise, I think we can activate it:
![image](https://user-images.githubusercontent.com/59668647/143359598-9ae3696a-2361-491e-945c-65a46c6752d2.png)

**Comment by jamesmrollins** [comment]
Thanks @lijenn - I is now active.  I should have guessed you would have checked the word count :-D ,  I will instruct @hirenp-waferwire to promote Test to PROD.
