### ISSUE TITLE
wk3 nov_epic Power BI LEARNER Facing Documentation DEV S2

### ISSUE THREAD

**Issue by mnallajerla** [lzim/teampsd#2369]
- [x] Review See & Say guides for Sessions 2 
- [x] Review See & Say guides for Sessions 3 
- [x] Identify WHAT needs to be changed ( see #2310 for more WHERE) 
- [x] Make drafts and changes + Pull requests for Jenn
- [x] Make sure to create 'MTL 2.0 Release' page documenting previous version

_Focus on MTL Blue Session 2 and anything related to it, since the same info will carry over to other documents/places.
We can divvy up the carrying over of edits once we have the edits first._

In priority:

- [x] MTL Session 2 SEE guide
- [x] MTL Session 2 SAY Guide
- [x] MTL Blue Session 1 Do/Done - SEE (Carry across)
- [x] MTL Blue Session 1 Do/Done etc - SAY (Carry across)

Tier 2 - [Aim for EOD tomorrow, Monday EOD latest]
- [x] MTL Session 2 SAY Checklist
- [x] Data Cheatsheet (Learner facing; this is visual driven but we could still work on text first)
- [ ] One pager (Facilitator facing; this is visual driven but we could still work on text first)

## 1. Link to the document and add relevant team members to the card.
- [x] Add the link the current draft of the documentation for the issue:
- [x] Session 2 SEE Guide: https://github.com/lzim/mtl/blob/master/blue/session02/s02_learner/mtl_session02_see.md
- [x] Session 2 Data CHEATSHEET: https://github.com/lzim/mtl/blob/master/blue/session02/s02_learner/mtl_how_data_cheatsheet.pdf
- [x] Session 2 SAY Guide -  https://github.com/lzim/mtl/blob/master/blue/session02/s02_facilitator/mtl_session02_say.md

## 4. Review and Open Pull Requests _(use the # for the link to the pull request)_
- [x] Check the draft for typos
- [x] Check or open a pull request for the document edits

## 5. Review and/or Update Graphics
- [x] Screenshots
- [x] Gifs
- [x] Logos/Icons
- [x] Links

## 6. Dependencies
- [x] Make sure that any edits you make that need to be added to **depend_product** are tracked (e.g., _MTL Video_)

## 7. Close Pull Requests
- [x] Request review and/or close open pull requests for the document

**Comment by mnallajerla** [comment]
WHAT in Power BI Learner facing guides needs to be updated:

- Eraser feature - clearing selection
- Filter feature - different from previous Excel use 
- Focus Mode - for zooming in 
-

**Comment by mnallajerla** [comment]
- When taking images/GIFs, keep the URL and workspace out of it so that it does not confuse the learners.

**Comment by mnallajerla** [comment]
### running list of questions for check in with @lijenn 

- [ ] - Review rough draft of S2 SEE > edits to be carried through everywhere else 
- [ ] - Review Questions

Questions: 
- [ ] - mtl.how/data or https://mtl.how/data_test >>>> needs to be updated. 
- [ ] Know there was previous discussion about Clinic Selection function, the current Data UI I have access to starts at Step 3. Verify it's right. >>> Home screen for mtl.how/data >> where would the learners start off


FYI: @jeffhoerle

**Comment by mnallajerla** [comment]
GIFs:

- use snagit to screen record and make GIFs
- GIFs are stored in Team PSD, but the guides are made in MTL 

How to upload GIFs:
- [ ]  Make a feature branch on Team PSD 
- [ ] Make a new folder in > Resources > GIFs 
- [ ] Upload GIF files to that folder in that branch 
- [ ] This branch needs to be added to Master 
- [ ] Take the final URL and put it in the Session 2 edits 

Naming GIF files: 
"pbi_eraser_icon" etc

**Comment by mnallajerla** [comment]
@lijenn answers: 
- [ ]  mtl.how/data >> Keep it as is in Session 2 (don't change URL)

- [ ]  Know there was previous discussion about Clinic Selection function, the current Data UI I have access to starts at Step 3. Verify it's right. >>> Home screen for mtl.how/data >> where would the learners start off
- [ ]  GIFs - review how to do them
- [ ]  review what needs to be done by when

FOR 8 AM WORKFLOW:
- [ ] Clarify with @jeffhoerle - What will the homepage for the mtl.how/data be? How would learners navigate to their VISN etc?  
- [ ] Obtaining patient - level data in session - is that something that would still be kept as is?


ACTION ITEMS:
- [ ] @mnallajerla to request Power BI Pro


REMOVALS to Track:
- "Shortcut clinic selection" in MTL 2.0

**Comment by mnallajerla** [comment]
Permissioning Conversation: See [Here
](https://teams.microsoft.com/l/message/19:bfdf92c7846542b58e9961e1d8cc671e@thread.skype/1634161865660?tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf&groupId=1db500d5-0d01-4254-af42-ad3f78bafacd&parentMessageId=1617654845666&teamName=teampsd_vha&channelName=support_workgroup&createdTime=1634161865660)
Admin User Role: 
Access to all data in the country.
And grant permissions to others.

Facilitators User Role: 
Access to all data in the country.

Co-planning:
VISN & Sta3n (ACOS)
Shouldn't need PHI.
Keep viz & data tabs.
Within data tabs - restrict the columns that include Veteran names.

Learners: 
Need PHI for their local patients.

RLS that Jeff implemented is based on existing LSV permissions

**Comment by lijenn** [comment]
MTL 2.5 GIFs will be stored here on [this branch and in this folder](https://github.com/lzim/teampsd/tree/feature-mtl_2.5_pbi_gifs/resources/gifs/mtl_2.5) on lzim/teampsd.

**Comment by mnallajerla** [comment]
Remaining Tasks on Wednesday 11/24/21:

- [ ] Meghana to make screen recording for (1) eraser feature & (2) 5 data tabs
- [ ] Questions & Clarification with Jeff @ 8 AM
- [ ] Make screen recording for filter feature 
- [ ] Convert all screen recordings into GIFs and upload to GitHub
- [ ] Finish Text Edits for MTL Session 2 SEE Guide 

Carry over these text edits to:
- [ ] MTL Session 2 SEE guide
- [ ] MTL Session 2 Checklist 

In LucidCharts:
- [ ] Edit Data Cheatsheet (Learner Facing)
- [ ] Edit One Pager (Facilitator Facing)

~~ DONE! ~~ Enjoy the Holiday Weekend!

FYI: @lijenn

**Comment by mnallajerla** [comment]
Permissioning conversation: [add to SAY Guide]

_**New in MTL 2.5**_
- We are able to support Clinical Resource Hub providers in the new PBI Data UI because they are granted more than one local server access

**Comment by mnallajerla** [comment]
Something that would be helpful for SAY/Facilitator Facing

What's New
What's been updated
What's a Bug Fix
What's been removed

**Comment by mnallajerla** [comment]
NEW Things from 8 AM WG Leads on 11/29

- [ ] Document drill/up down fork arrow
- [ ] Make note about which filters to use in Viz tabs
- [ ] Edit first step in Session 2 guide to updated Landing page

@lijenn

**Comment by mnallajerla** [comment]
to add to SEE, SAY, checklist - 

- [ ] Clarify that the filters in the light blue and dark blue columns only apply to the green Clinics column.
- [ ] By default, the data and viz tabs is to show all the data for all sta3ns and clinics.

**Comment by mnallajerla** [comment]
MEGHANA:
- [x]  MTL Session 2 SEE Guide - 
- [x] MTL Session 2 SAY guide
- [ ] MTL Session 2 Checklist 
- [ ] MTL Session 1 DO and DONE at end (x2) - need gif 
- [x] MTL Session 3 DO and DONE at beginning (x2)

JENN
- [ ]  MTL Session 2 SEE Guide - Proof read
- [ ] MTL Session 2 SAY guide - Proof read 
- [ ] MTL Session 2 Checklist - Proof read

**Comment by mnallajerla** [comment]
@lijenn - The individual clinic selections portion of the session did not add more than 1-2 minutes to session today! I made a note of it on the mastercard but am closing this card for now since we are done with DEV & QA for 99% of these materials :)
