### ISSUE TITLE
wk2_jan_epic: Sim UI re-address data inputs from team data file

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2370]

**Comment by jamesmrollins** [comment]
Hi @jeffhoerle FYI @lijenn @mnallajerla 

The first pass on the ModelParameters.xlsx file came out pretty clean.  Below are some exceptions to investigate. However, since the values all populate a single row, I will need to wait for MM to be corrected before addressing MM, PSY or AGG, due to cell shifts. 

## MM Model

1. Missing "Appointment Slots % (with x waiver)"
2. Missing "Appointment Supply (mean).
3. Missing "Appointment Supply (median).
4. Missing "Slot Allocation % (without x waiver) -> OUD"
5. "{MM} Engagement (median)" should be "{MM}Engagement Duration (median)"

## AGG Model

The variables below should return a zero versus a blank:

1. {AGG} AUD->ebpsy 
2. {AGG} True Missed Appointment %->group
3. {AGG} Appointment Supply (median) -> group
4. {AGG} Engagement Duration (median) -> group
5. {AGG} Service Proportion from Team Data -> group
6. {AGG} Return Visit Interval (median) -> group

**Comment by jeffhoerle** [comment]
**MM Model**
1. The Excel macro doesn't appear to calculate this parameter.  There is no code in the SQL query.  It appears to be hard-coded at "0.5".  Is this the desired behavior?
2. Already in the file, cell M1
3. Already in the file, cell N1
4. This parameter is always calculated as "" (i.e. blank).  I didn't include it, but will include it in the next file I send you.
5. The Excel file calls this "Engagement (median)", but I have changed it in my code to align with your suggestion.  The Excel file also uses the same title in CC.  Perhaps I should update that too?

**AGG Model**
Will get these corrected.

**Comment by jamesmrollins** [comment]
Hi @jeffhoerle FYI @lijenn @mnallajerla 

Thanks for taking a look at these!  

1. Regarding MM Appointment Supply - I don't know how I missed those, sorry.
2. Regarding Slots Allocation (without x waiver) -> OUD - This is likely set to zero, because a provider would require an X waiver (this is a special DEA certification) to administer opioid therapeutics such as methadone, please correct me if I'm wrong @lzim.  In any case, we would need at least a zero pass to the sim.
3. Regarding Appointment Slots % (with X waiver) - This is not provided in the data.  There is a note in the original ModelParameters.xlsx that verifies this, "This parameter is not estimated in the data. It is just provided here as an input to the model for later user manipulation."
4. Regarding Engagement (median) - Thanks for updating this. Maintaining standardization of terms helps researchers audit the relationships between data files and the sim.

**Comment by jamesmrollins** [comment]
@jeffhoerle FYI @mnallajerla @lijenn 

Jeff indicated that he will provide a data export that will include the data variable names that support SP.  James can then audit the list to ensure it is complete and populate with sample information that will enable further development and testing.

**Comment by jamesmrollins** [comment]
@lzim @jeffhoerle @TomRust @lijenn @mnallajerla 

**The attached anonymous ModelParametes.xlsx contains the details of what is below.**

[ModelParameters.xlsx](https://github.com/lzim/teampsd/files/7747978/ModelParameters.xlsx)

## Follow up Discussion to New Team Data File

### Regarding Model Changes

- [ ] Psy Module was not standardized by yours truly and requires 27 variable renames to make consistent with parameters naming.

### Regarding New Team Data Changes

- [ ] There is an improperly coded variable called "{PSY} Completers RVI" that should be black (non-asterix), as it is not used in the model.
- [ ] There are 68 variables in the AGG that require name modification to match exactly what is in the model. 

### Regarding MM

- [ ] After review with @jeffhoerle and @TomRust on 12/20, the model should perform as designed with the newly provided slots allocations data without any changes to the current model.

## New Feature Recommendation

- [ ] Since waivered and non-waivered appointments per week data is available, we recommend using that data instead of proportions. _Keeping in mind:_
  - [ ] The Sim UI Experiments sliders graphic would need to be changed from "%" to "Appts per Wk" (this would be a minor change).
  - [ ] The model would require modification and simplification to remove the current scaled Appointment Slots % calculations (this would be more precise and a minor change).
  - [ ] The curriculum uses AGG for its GIF demonstrations, so there will likely be very little impact to curriculum regarding the new experiment slider visual in MM.  
  - [ ] May affect the video lesson regarding MM.

**Comment by jamesmrollins** [comment]
From 1/5 Sim UI Meeting with @lzim and @lijenn 

## Updated Model Parameters File

[Model Parameters](https://app.zenhub.com/files/87591711/1399f8f6-8eed-420e-8258-b8541574e1c3/download)

### Incorporated These Decisions

- [ ] Proper abbreviation for psychotherapy is "PSY."
- [ ] Proper abbreviation for Evidenced Based Psychotherapy is "EBPsy."
- [ ] @lijenn to review model parameters file linked above and coordinate changs with @jeffhoerle.

### These Additional Decisions Were Made Regarding Delivery and Sim UI Changes
- [ ] New models and team data files available in PROD by 1/14
- [ ] Gray out Suicide Prevention radio button on Sim UI Home Page and add note that says, "_Coming in 2022_)

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire .  Please make the changes below in the TEST-SLOW instance.  Thank you.

![image](https://user-images.githubusercontent.com/30132017/148663652-cb5288f3-24f2-471c-be5c-6d01ee611df0.png)

FYI: @lijenn @mnallajerla

**Comment by jamesmrollins** [comment]
FYI @mnallajerla @lijenn 

Hi @jeffhoerle - Please see below for some edits to the ModelParameters.xlsx. 

## Psy Module Add Variables as Indicated to New Export

![image](https://user-images.githubusercontent.com/30132017/148689998-56f3f6bd-7ad9-4ae1-9772-1e02164dc92b.png)


## Agg Module Remove Variables as Indicated from New Export 

![image](https://user-images.githubusercontent.com/30132017/148690310-2d5015e6-6ade-4bdf-b8da-294d77c4cff9.png)

**Comment by jamesmrollins** [comment]
FYI: @lijenn 
Hi @jeffhoerle - Still a couple of columns left to delete (AT and BZ).  See attached file with columns in red.

[Corrected dataexport_20220110.xlsx](https://github.com/lzim/teampsd/files/7842643/Corrected.dataexport_20220110.xlsx)

**Comment by jamesmrollins** [comment]
FYI: @lijenn 
Hi @jeffhoerle - Thanks for quickly turning around the attached file.  I checked it out this morning and we are 100% in alignment between export and model!  

[Copy of dataexport_20220111.xlsx](https://github.com/lzim/teampsd/files/7849022/Copy.of.dataexport_20220111.xlsx)

@lijenn we are currently adjusting the code in the Sim UI to match all of the variable changes.  The final tally was 125 name changes across the 4 modules. These hopefully will be available for us to begin testing tomorrow, latest Thursday.

**Comment by lijenn** [comment]
@jamesmrollins & @jeffhoerle Thank you both for your work! I'll keep an eye out for testing #2413 tomorrow or Thursday.
FYI @mnallajerla
