### ISSUE TITLE
wk4_nov_epic: Sim UI Error message causing user confusion

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2372]
**1. Add description:** 

Error message regarding a new session startup is confusing for individual world users.  Current message is below.

“Starting a new simulation will stop the previous session for all team members. Session decisions and results may not have been saved. Do you wish to proceed?”

The message is a system message that is triggered when a user desires to change from one type session to another, regardless of the status of session (not run, run).
 
**2. Click on the right:**  
i. **Pipelines** - prioritize in a TeamPSD (& Workgroup) pipeline  
ii. **Assignee** - assign to an individual team member producing work for the issue  
iii. **Label**- assign workgroup (lead) responsible for tracking the task  
iv. **Projects** - assign to domain-specific TeamPSD tracker (issues, features, document, manuscript, team)  
v. **Milestones** - select monthly sprint milestone within the workgroup   
vi. **Estimate** - Estimate task in complexity points   
vii. **Epics** - assign to team-wide epic and TeamPSD master plan project  
iix. **Releases** - assign to key team release grouped with other relevant issues  

**3. If you anticipate that your **issue card** or **bug card** will have **dependencies** these can be added once the issue has been submitted.   
ix. **Add dependencies** - assess for and add dependencies *blocking* & *blocked by* this issue

**Comment by jamesmrollins** [comment]
## Recommended Change

### FROM
“Starting a new simulation will stop the previous session for all team members. Session decisions and results may not have been saved. Do you wish to proceed?”

### TO
“Starting a new simulation will clear information from the previous session. If necessary, save the previous experiment before proceeding.”

**Comment by lzim** [comment]
Sounds good @jamesmrollins :smile_cat:

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire - Please see above.  We need to change the words for the starting new session warning message.  Let me know if you have questions.
