### ISSUE TITLE
Readme files not rendering properlly

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#238]
Does anyone know why the Readme files in most of our teampsd folders on GitHub are rendering for me in Rmarkdown code instead of as web pages all of a sudden? Thanks!

**Comment by lzim** [comment]
@branscombj @dkibbe @staceypark and @ericasimon

This emerged over the weekend (or so) as far as I can tell.

I assume that the explanation is that GitHub has changed something with regard to .RMD read me files.

The solution is to re-name the file extension from .Rmd (RMarkdown) to .MD (Markdown).

**Comment by staceypark** [comment]
@branscombj @dlkibbe @ericasimon @lzim 
Yep, changing to .MD (Markdown) does make it work.
I've also reported the issue to support@github.com and am waiting to hear back from them.
