### ISSUE TITLE
wk2 dec_epic story_13 Data UI Page Compression  (PTSD_OMHO) - Duplicate Tables

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2381]
@jeffhoerle  
@dkngenda 

- [ ] Run stored procedure to compress tables & indexes on PTSD_OMHO
- [ ] Address questions about duplicate tables

@jeffhoerle Is this something you need support on?
If so, and it's urgent, we could touch base about it at 8AM workgroup leads on Monday after the holiday (11/29).
If it's not urgent, then we could touch base at our standing meetings on Wed/Thurs next week.

Let us know and thanks! :smile_cat:

**Comment by lijenn** [comment]
Discussed 12/6 8AM WG:
- @jeffhoerle Followed up with Glenn, but need to follow up again regarding the time out error that Jeff recieved.

**Comment by lijenn** [comment]
Discussed 12.9.2021 at Quant 11 w/ @mnallajerla :

**To be discussed and triaged Monday 12/13  8am WG Leads**
Need to think this task through with @dkngenda 's remaining time on team, possibly any Knowledge Transfers as well? FYI @jeffhoerle

**Comment by jeffhoerle** [comment]
Ran SQL Compression code successfully on Friday (12/10).  Closed.
