### ISSUE TITLE
wk2 dec_epic PBI Documentation Session 3 PROD 

### ISSUE THREAD

**Issue by mnallajerla** [lzim/teampsd#2385]
Review:

- [ ]  Session 3 SEE Guide
- [ ] Session 3 SAY Guide
- [ ] Session 3 SAY Checklist
- [ ]  Session 3 One Pager

Session 3 Materials:
DEV - #2383
QA - #2384
PROD -  #2385

PBI Documentation MasterCard: #2310

[will fill in more information later, this is to hold space on the board for this documentation development and testing]

**Comment by lijenn** [comment]
Work was completed back in dec_epic and in Prod. New card to be opened for wk2 feb_epic to include SP Data UI documentation.
