### ISSUE TITLE
wk1 feb_epic: PI Emergent Issues

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2388]
wk5

_Top Priorities_
1. Power BI Data UI UAT
2. IIR Progress report
3. Manuscripts

- [x] Jim Budget check
- [x] Natalia Recruiting (8 pts)
- [x] Health equity funding
- [x] Mailing _MTL_ materials to sites
- [x] Get Badges Gracelyn & Danielle & Carrie O

- [ ] OASC provider survey completion help
- [x] Facilitators Co-planning
- [x] RPDS format & schedule

- [x] Feedback Acceptance
- [ ] FCOI

**Comment by lijenn** [comment]
@lzim Please check off emergent issues you've completed from nov_epic and add anything you need to track for wk1 feb_epic that aren't already on the board, thank you!
