### ISSUE TITLE
wk 1 jan_epic Adding Meghana to IRB, DART, VINCI for all grants

### ISSUE THREAD

**Issue by mnallajerla** [lzim/teampsd#2395]
Make sure Meghana has access to:

R01
- [x] IRB
- [x] DART
- [x] VINCI Project Correspondence Site 
- [x] CDW ORD Workgroup 

IIR
- [x] IRB
- [x] DART
- [x] VINCI Project Correspondence Site 
- [x] CDW ORD Workgroup 

R21
- [x] IRB - Update 12.8.21 DART meeting - @staceypark , @lijenn > Need to submit IRB Mod to add @mnallajerla to R21(submit along with research rep #328)
- [x] DART
- [x] VINCI Project Correspondence Site 
- [x] CDW ORD Workgroup 

Redcap
- [x] Check Redcap Access for All projects as well

**Comment by mnallajerla** [comment]
Update @ 10 AM DART Meeting 12.8.21

R01 & IIR IRB's: Added to list of personnel and resources 

DART: All 3 grants (R01, IIR, R21)

**Comment by staceypark** [comment]
@mnallajerla does not have editing privileges yet. We will change Meghana to the Admin Contact and add Stacey to the Other Personnel section

**Comment by mnallajerla** [comment]
@lijenn - did we check my redcap access?

**Comment by mnallajerla** [comment]
Checked in VINCI Central and seem to have access to all ORDs.

**Comment by mnallajerla** [comment]
Hi @lijenn - I think we are all set to go on this card once I have access to the redcap projects. Thank you!

**Comment by lijenn** [comment]
@mnallajerla Please check off the RedCap Projects you have access to then we can close this card!
- [ ] MTL Live Fidelity Ratings 
- [ ] [Final] Modeling to Learn Feedback (R01 Baseline 1a)
- [ ] [Final] Modeling to Learn Follow-up (R01 6 month 2a)
- [ ] [Final] Modeling to Learn Feedback (IIR Baseline 1a)
- [ ] [Final] Modeling to Learn Follow-up (IIR 6 month 2a)

Please let me know if you are missing any.

**Comment by mnallajerla** [comment]
hi @lijenn - It looks like I still do not have access to any projects. My VA redcap is connected to my VA email. 

This is what I still see: 

![image.png](https://images.zenhubusercontent.com/6130066bf230e9289f9a2c0c/dc1860ff-e22c-49cf-84b7-1b3ca9d1a89e)

**Comment by mnallajerla** [comment]
Confirming I now have access to all of the REDcap projects.
