### ISSUE TITLE
wk4 jan_epic: PBI ClinicSelection - Rename "IsInactive" filter to "Is Active?" or "Is an Active Clinic?"

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2398]
Wording of this column may be confusing to users, recommendation is to rename it to:
![image](https://user-images.githubusercontent.com/59668647/144479765-e25ce1f4-4f96-4504-af23-410331cf88e7.png)

Is Active? 
- Yes
- No

OR 

Is an Active Clinic?
- Active
- Inactive

**Comment by jeffhoerle** [comment]
Change has been implemented in both (Data & Viz) and (Team Data) pbi reports.  Closed.
