### ISSUE TITLE
wk5 jan_epic: GFE Laptop for David L.

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2405]
See if we can remap Jane's laptop to David.
If not, submit new request via YourIT for David

@lijenn @lzim @dlounsbu @mnallajerla - Re alerting our attention to this :)

**Comment by mnallajerla** [comment]
Hi @lijenn  - 

Was just wondering if we had any updates? Thank you! 

FYI: @dlounsbu @lzim

**Comment by lijenn** [comment]
David received his GFE laptop at the beginning of mar_epic, closing this card.
