### ISSUE TITLE
Wk1_feb_epic: SIM UI Rename AGG to Team (AGG) Care

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2425]
Scrub through SIM UI related products, demo and team websites to find instances of the use of the term "AGG" or "Aggregate" and replace with new term "**Team (AGG) Care**."  Below is a starting list of places that will require an update.  Note that AGG will not

## Update Sim UI Interface

- [x] **Home Screen Menu Selection**
- [x] **Main Diagram Page Header**
- [x] **tt Reports setup dialogue**
- [x] Outputs and Text Page Header
- [x] More Info Page
  - [x] Navigating Home Screen
  - [x] MTL Modules
  - [x] MTL Sections
    - [x] Play Screen
    - [x] Text
    - [x] Model Diagram
    - [x] Outputs and Text (Text pop up update)

## Vensim Model

- [x] Do NOT rename AGG to TC - Retain AGG
- [x] No other uses of the term AGG detected between models.

## Associated MTL Documents

- [ ] mtl/blue/session04/s04_facilitator/mtl_session04_say.md
- [ ] mtl/blue/session04/s04_learner/mtl_session04_see.md
- [ ] session04/s04_learner/mtl_how_sim_cheatsheet.pdf
- [ ] **session05/s05_learner/mtl_session05_see.md** 
- [ ] **session05/s05_facilitator/mtl_session05_say.md**
- [ ] session06/s06_facilitator/mtl_session06_say.md
- [ ] session06/s06_learner/mtl_session06_see.md
- [ ] session07/s07_facilitator/mtl_session07_say.md
- [ ] session08/s08_facilitator/mtl_session08_say.md
- [ ] session08/s08_learner/mtl_session08_see.md
- [ ] session09/s09_facilitator/mtl_session09_say.md
- [ ] session09/s09_learner/mtl_session09_see.md
- [ ] session10/s10_learner/mtl_session10_see.md
- [ ] session11/s11_learner/mtl_session11_see.md
- [ ] red/part2/part2_learner/mtl_red_part_2_see.md

## Team PSD Manual

- [x] General search on "AGG" and "Aggregate"  - negative results

## MTL Manual

- [ ] Investigate and implement a DEVOPS CI/CD option so when a main .md file is updated in the Blue directory, it also updates gh-pages branch in lzim/mtl

## Dev OPS

- [x] ~~Update GitHub actions to recognize model file name using "TC" versus "AGG" when executing update model actions.~~ Decided that model naming will not change.

**Comment by lzim** [comment]
@jamesmrollins - thanks for creating this issue task card - **Note there were initially a couple of incorrect assumptions made in the list of requirements above - I edited your initial post** to reflect that the change is to **"Team (AGG) Care"** and to note that we will **NOT be changing from "AGG -> TC"** (see bullet under "Vensim model" header)

FYI: @mnallajerla & @lijenn 

**Our convention for this change is to use **"Team (AGG) Care"** as the **first screenshot from the Data UI** indicates below - Here are 3 principles we are following with this convention**
1. "Team (AGG) Care" helps to reflect the fact that these data still reflect "the aggregate mix of services in the team"
2. "Team (AGG) Care" also eases the transition among our existing user base of providers and facilitators, which are much larger now than used to be true and these changes can be much more disruptive.
3. Finally, **retention of "AGG" as the abbreviation for "Team (AGG) Care"** (_not TC_), will lead to far fewer changes to the existing user-interfaces and guides, as is shown in the second Data UI screenshot indicates below

![image](https://user-images.githubusercontent.com/7454688/146609923-31dc717c-7f02-42fa-bcfb-e78e208cd823.png)

**See how we are still use "AGG" as the abbreviation in many instances of the Data UI Team Data Tables as shown here:**
![image](https://user-images.githubusercontent.com/7454688/146610202-8b8908cb-172d-4012-b8b1-41f3435c5d81.png)

If you have any questions about this implementation, please let me know.
Hopefully, this reduces scope substantially and reduces risk of more translation errors between the Data UI going to PROD on Monday, and for the existing user base.

FYI: @lijenn @mnallajerla

**Comment by jamesmrollins** [comment]
@lzim Nice workaround! That will prevent allot of model rework. But I hear you saying that UI changes and dependent document chances will still be necessary.

**Comment by lijenn** [comment]
Identified by @lzim in John & David's S05 prep on Wed. 1/19

@jamesmrollins, please help change Aggregate on the Sim UI to be Team (AGG) Care.
![image](https://user-images.githubusercontent.com/59668647/150212456-76d7e243-9b25-4c34-879f-e92d99fc9671.png)

**Comment by jamesmrollins** [comment]
Hi @lzim and @lijenn 
FYI @mnallajerla 

I plan to keep working on this list as time becomes available, until it is complete.  I will seek to complete all items on the checklist by the end of next week.

**Comment by jamesmrollins** [comment]
@lzim - When you bypassed updating the GIFs that had AGG images, did you mean for all time, or just for the immediate priority of the Friday Training?

FYI: @lijenn @mnallajerla

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire - Please see changes below.

## Outputs and Text Pop-up (Expanded)

![image](https://user-images.githubusercontent.com/30132017/151886311-76c90867-1dc6-492c-afb4-1acdd041ebe2.png)

## Home Page

![image](https://user-images.githubusercontent.com/30132017/151886457-3bea31b7-fa7a-48f2-96ab-9c022ed5feb3.png)

## More Info Page

### _MTL_ Navigation - Navigating the Home Screen 1, 2, and 3

![image](https://user-images.githubusercontent.com/30132017/151886771-dd9332f7-9a23-42e5-b8ae-05f0cf051690.png)

![image](https://user-images.githubusercontent.com/30132017/151886923-2c48e0d0-6d36-433b-9d0a-37d14502f9ad.png)

![image](https://user-images.githubusercontent.com/30132017/151887064-6ba75a4b-e688-4f6c-8d6f-1b859fd84267.png)

## _MTL_ Sections

### Play Screen

![image](https://user-images.githubusercontent.com/30132017/151891067-f026dded-5153-4f0b-a145-ab13a907e7c8.png)

### Text

![image](https://user-images.githubusercontent.com/30132017/151891305-b8b7951b-f859-4183-a44d-42e48264ce7b.png)


### Experiment

![image](https://user-images.githubusercontent.com/30132017/151891608-195f26bb-fd7c-4d6f-9f54-c8a79fc1a114.png)

### Model Diagram

![image](https://user-images.githubusercontent.com/30132017/151892116-b941d3cc-ed49-4b75-ba7a-32c79c6e5f66.png)

### Outputs and Text 1 and 2

![image](https://user-images.githubusercontent.com/30132017/151892353-4f21f1bb-f7eb-4191-b0b2-31cba9a07d6c.png)

![image](https://user-images.githubusercontent.com/30132017/151892501-6bd83200-56b2-4a07-b228-e72c6c695983.png)
