### ISSUE TITLE
wk1 apr_epic: Add New Members & Clean up MTL.How/team

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2426]
- [x] Add the new QIICS
- [x] Move Swap to Facilitator
- [x] Alumni - Stacey & David
- [x] Clean up Alumni

@mnallajerla Let's do this task together!

**Comment by lijenn** [comment]
Task was completed in wk1 apr_epic. 

Not sure if documentation for this exists somewhere @jamesmrollins?
@mnallajerla would be a great tester considering that we are still waiting on the bios of 2 Facilitators and need to add it to the Team page. 

Let's make an issue card for the documentation if it doesn't exist as this is a part of Story I TRAIN that we hope James can support us with.

**Comment by jamesmrollins** [comment]
@lijenn @mnallajerla - Yeah, there's probably documentation somewhere . . .  Don't ask me where!
