### ISSUE TITLE
wk2 mar_epic: Story 13 PBI -LSV Testing and Move to Prod

### ISSUE THREAD

**Issue by mnallajerla** [lzim/teampsd#2429]
See #2393

Update on 1.14.22:
Wait for further movement on RLS/LSV issues before moving futher with PROD or these lists. 

 - [ ] Transfer Dynamics Readers list to PROD version of PBI

**Comment by lijenn** [comment]
Discussed 1/31 8am WG with @lijenn & @mnallajerla:

Due to the RLS issue for Prod, this is in Icebox until we move into Prod.

**Comment by mnallajerla** [comment]
@lijenn now that we are in Prod shall we revisit this and the related documentation?

**Comment by lijenn** [comment]
@mnallajerla I believe we won't need to do this specific task anymore given the workaround for RLS! I would recommend closing this card.

For documentation in #2476, I also recommend we close that so the card does not remain open and mess with our cost data. 
The work in that card is technically done, but we should open a new card to revisit the Data Cheatsheet, One-Pager, and the Red Part I, Part II, and Blue Session 2, Blue Session 3 guides that mention RLS given today's update from Jeff.

**Comment by mnallajerla** [comment]
Okay great, @lijenn . Closing this.
