### ISSUE TITLE
wk2 dec_epic: Missing clinics in ClinicSelection in the PBI Viz & Team Data/Param report vs clinics in the Test APP

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2430]
Found on 12/15 Prep with John & David at 2:15p Pacific:

Attempted to create a bookmark for their team. Tried to select clinics from the Test App in the PBI Viz Report to create the bookmark.
But clinics showing up in the App are missing from the PBI Viz & Team Data/Param report:

APP:
![image](https://user-images.githubusercontent.com/59668647/146276205-823b09a7-a595-47fd-a9e5-1f467b086dff.png)

PBI Report:
![image](https://user-images.githubusercontent.com/59668647/146276279-d3bb403b-677f-4213-9f85-cde67edca069.png)

**Comment by jeffhoerle** [comment]
We discovered that these clinic names changed in CDW, so could not be found in PBI after a recent refresh of the data.

Lesson learned: Users need to be actively aware of what clinics are selected and that it will be important to continually review the clinic selections to ensure accuracy.
