### ISSUE TITLE
wk1 jan_epic Removing calculated parameters team data files that model does not consume?

### ISSUE THREAD

**Issue by mnallajerla** [lzim/teampsd#2447]
**Question:** Should we remove calculated parameters team data files that the model doesn't consume? 
Any reduction in unnecessary calculations would give a performance boost (reduce memory use).

DECISION: From @lzim  POV - We could remove any variables from the team data export file that are not consumed by the Vensim model. 

@jamesmrollins - Was there ever a card created about the issue of reviewing parameter values that Vensim doesn't use?

FYI: @TomRust @jeffhoerle @lijenn

**Comment by jamesmrollins** [comment]
Hi @mnallajerla .  No, this discussion was a part of the #2370 Sim UI Re-address data inputs from team data file card.  The supporting file with the non-used data identified is contained therein.

**Comment by mnallajerla** [comment]
Hi @jamesmrollins - Thank you! We just huddled with Jeff in the[ Support WG Thread (see conversation)](https://teams.microsoft.com/l/message/19:bfdf92c7846542b58e9961e1d8cc671e@thread.skype/1641592336082?tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf&groupId=1db500d5-0d01-4254-af42-ad3f78bafacd&parentMessageId=1641592336082&teamName=teampsd_vha&channelName=support_workgroup&createdTime=1641592336082) and sounds like he has worked on things in PBI/his end of things. 

Wanted to alert you to that.

FYI: @lzim @lijenn

**Comment by mnallajerla** [comment]
Discussed at WG Leads on 1/10/2022. This has been done.
