### ISSUE TITLE
wk1 jan_epic: PBI Test Bug - Inactive Clinics Not Showing Up in ClinicSelection Tab 

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2448]
Identified by @lijenn in prep of David & John's live MTL Blue Session 4 team meeting on Friday 1/7 at 8:30am Pacific:

@jeffhoerle @lzim @mnallajerla 

When trying to prep the bookmark for the team, I am unable to find any inactive clinics that should still appear within the 2 year range. Furthermore, I am unable to find any inactive clinics across all the 4 VISNs that are in TEST when using the "Is an Active Clinic" filter:
![image](https://user-images.githubusercontent.com/59668647/148477093-96a4b3fc-78aa-45a9-972e-ad8cf998da9f.png)

But when I search for ZZ in the green column, I see some but not all inactive clinics.
Note: The "Is an Active Clinic" filter does not seem to think these are considered inactive when I check "No" in the filter:
![image](https://user-images.githubusercontent.com/59668647/148478816-3fcee947-0c74-4e83-a87e-c0e9673d38ed.png)

**Comment by hnorthcraft** [comment]
#adjudicate_memo assigning 1 sp to reflect efforts (documenting bug and discussion)
