### ISSUE TITLE
wk2 jan_epic Add item for 3rd facilitator on fidelity Redcap Questionnaire 

### ISSUE THREAD

**Issue by mnallajerla** [lzim/teampsd#2449]
Discussed in Friday 1.7.22's team debrief that we may have 3rd facilitators (either supporting or doing ride-along), and we need to add optional items for 3rd facilitator in the redcap fidelity questionnaires for those instances.

**Comment by mnallajerla** [comment]
@lijenn - Looks like you already did this, thank you!!

**Comment by hnorthcraft** [comment]
#adjudicate_memo adding operations label
