### ISSUE TITLE
wk2 jan_epic Add documentation on how to add facilitator access to MTL Menu

### ISSUE THREAD

**Issue by mnallajerla** [lzim/teampsd#2450]
Hi @jamesmrollins - Following up on our conversation from Friday 1.7.22 in the SIM UI WG thread. 

We do not have documentation in the MTL manual on how to give facilitators access to teams' MTL menu responses. Could we add documentation on how to do this? 

Thank you!

**Comment by jamesmrollins** [comment]
Hi @mnallajerla - Did you want me to add this to chapter 9 of the MTL Manual?  I could add it either as as subsection to 9.5 - Produce a team_time Report, or its own section.  I recommend the former since it won't change the chapter structure.

**Comment by jamesmrollins** [comment]
Decided at the 1/13 HQ Meeting to be after subsection 9.2
