### ISSUE TITLE
wk2_jan_epic: QA TEST sim ui team data import function 

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2453]
## QA Checklist

- [ ] Power BI exports team data file with appropriate name using _MTL_ convention.
- [ ] The xlsx file imports into Sim UI and Epicenter and updates the Team Data listing in the Facilitator Dashboard.
- [ ] The Home screen of the associated team lists the Team Data in the Team Data dropdown and Maintenance section.
- [ ] Sim UI Modules load and run properly using new Team Data files.
  - [ ] CC
  - [ ] MM
  - [ ] PSY
  - [ ] AGG
- [ ] The Suicide Prevention section is grayed out and has a "Coming in 2022" message.
- [ ] All current teams have new Team Data File
  - [ ] Team 1
  - [ ] Team 2
  - [ ] Team 3
  - [ ] Team 4

**Comment by lijenn** [comment]
Thanks for this card @jamesmrollins, I will aim to complete by Wednesday COB.
