### ISSUE TITLE
wk2 jan_epic Archive compression code

### ISSUE THREAD

**Issue by mnallajerla** [lzim/teampsd#2458]
- CDW best practice is to - Conserve memory space of shared resources (servers, databases, etc).
- We received CDW code in December that went through all the tables and compressed the tables anywhere it could. 
- This task card is to track archiving that code in the Team PSD databases

**Comment by mnallajerla** [comment]
Hi @dkngenda - what else needs to be done for this task?

**Comment by dkngenda** [comment]
Hi @mnallajerla - This card can be closed. The compression card can be found [here](https://github.com/lzim/research/tree/master/sql%20utility%20code%20snippets)
