### ISSUE TITLE
wk3 jan_epic MTL Test repo setup

### ISSUE THREAD

**Issue by mnallajerla** [lzim/teampsd#2462]
Issue card to track MTL Test set up. [See conversation from HQ WG for more information](https://teams.microsoft.com/l/message/19:b53cd5f1ece145409afbd3b42a666f20@thread.skype/1642122749968?tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf&groupId=1db500d5-0d01-4254-af42-ad3f78bafacd&parentMessageId=1599865661462&teamName=teampsd_vha&channelName=hq_workgroup&createdTime=1642122749968)

NEED:

- [x] test repo and guides (with correct links)
- [x] Create a mtl.how/sim_test logo @lzim 
- [x] Create a mtl.how/data_test logo @lzim 
- [x] Session 5 Gif contains old bisl/excel file on mtl.how Prod guide - Update in TEST

Links: 

List to update in the TEST repo:
- [x] mtl.how - PROD guides > mtl.how/test - TEST guides
- [x] mtl.how/data > mtl.how/data_test
- [x] mtl.how/sim > mtl.how/sim_test
- [ ] mtl.how/red (?)
- [ ] mtl.how/blue (?)

List of new quick links that need to be created:
- [x] mtl.how/sim_test -> Sim UI TEST
- [x] mtl.how/data_test -> Data UI in TEST  (PBI)
- [x] mtl.how/test - forking the guides TEST repo; mtl.how/test repointed to this repo
- [ ] mtl.how/red (?)
- [ ] mtl.how/blue (?)

Also need to update:

- [x] Icons
- [ ] PDFs / CheatSheets (need for session 5?)
- [ ] Re-fork to lzim 

FYI: @lzim @lijenn @jamesmrollins @jeffhoerle

**Comment by mnallajerla** [comment]
@jamesmrollins - I was able to update the SIM UI link in the test repo with no issues. Thank you for all your help with this :) 

I ran into an issue when trying to update the mtl.how link to "mtl.how/test" using the FNR action. I got an error code "128" in the Action Runner. Any pointers? Thank you!

**Comment by jamesmrollins** [comment]
## Focus

- Monitoring our learning skill, pace, manageable.  
- Which are the most important learning curves...

## By Friday Morning 1/21 0800 EST.

- [ ] "How to navigate to the Data UI" _mtl_ Manual update.
- [ ] Establish MTL repo at lzim/mtl_test 
- [ ] Update ICON links 
  - https://mtl.how/test 
  - https://mtl.how/data_test 
  - https://mtl.how/sim_test 
- [ ] Links have been updated in the TEST repo. 
- [ ] Run down the GitHub Actions associated with 128 error above. (@jamesmrollins )
- [ ] Assess repo for future action development and promotion SOP (for story development)

## Get 'er Done!

**Comment by lijenn** [comment]
@mnallajerla @lzim @jamesmrollins 

**1. mnallajerla/mtl_test edits were commited into lzim/mtl**
Last week, we tried to bring mnallajerla/mtl_test repo up to date with lzim/mtl by making a pull request to pull everything from lzim/mtl --> mnallajerla/mtl_test. 

We encountered a merge conflict with the find and replace.yml. 
We resolved it and thought it would only push the commit from that conflict into lzim/mtl, but instead pushed all commits from mnalljerla/mtl_test into lzim/mtl. 

This change updated all the Prod links into Test links on lzim/mtl. I used FNR to change the links back to Prod links.

**2. To prevent these mistakes and encourage a better Test to PROD workflow, here's 3 recommendations we/I could test:**

**short-term solution 1:** [Merging branches between 2 different repos](https://stackoverflow.com/questions/38468700/how-to-merge-branches-in-2-different-repositories), I interpreted their diagram similar to our use case.
**short-term solution 2:** [Merging repositories into one repo based on this user's experience](https://medium.com/altcampus/how-to-merge-two-or-multiple-git-repositories-into-one-9f8a5209913f) that notes the most complicated thing to manager is merge conflicts as we experienced above or [another similar source](https://www.w3docs.com/snippets/git/how-to-merge-two-git-repositories.html)

While it is isn't impossible to set up a workflow having a lzim/mtl_test and lzim/mtl repo, best practice seems to discourage the use of two repositories using one to contain test work and one to contain prod work. 

**Best long-term solution:** Multiple sources have suggested to use one repo for prod work and use branches to hold test work, ultimately using some sort of continuous integration and deployment (CI/CD) tool (e.g. CircleCI, Travis, etc.) to manage conflicts. We could direct Learners to a specific MTL_Test branch within the lzim/mtl repo?

We may want to consider closing the loop on our CI/CD work and learnings from Team PSD 2.0 and get it fully integrated either in our 1st half or 2nd half of the year as a story.

**Comment by mnallajerla** [comment]
@lijenn & @jamesmrollins - Is this card good to close? 

We have the test repo set up. We need to update the icons and things as we go, which I have been tracking.

**Comment by jamesmrollins** [comment]
@lijenn @mnallajerla 

- It depends.  This repo is started by not finished in terms of actions. BUT
- We need to map out our use-cases and align actions to automate link update activities when promoting to PROD.
- I have started a story on the story board for this. SO

Recommend we close this card and let the story card pick up the remaining work . . .

**Comment by mnallajerla** [comment]
Hi @jamesmrollins - that sounds good. Closing it now.
