### ISSUE TITLE
ICEBOX: PROD D365 - Pre/Post Emails Templates not sending 

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2465]
Discovered by Jenn and David L.:

Tried to send a Pre email to John & David's VA Blue team on Fridays at 9:00am Pacific, but email never sent. 
Jenn re-created the template and tried to send it again, but David & Jenn confirmed they never received the email.

![image](https://user-images.githubusercontent.com/59668647/149973658-378bbab2-ad62-4187-aa94-7c542b8b5936.png)

**Comment by hnorthcraft** [comment]
#adjudicate_memo updating to 1sp closed as not planned/icebox
updating value streams
