### ISSUE TITLE
wk3 jan_epic find and replace branch not working - BUG

### ISSUE THREAD

**Issue by mnallajerla** [lzim/teampsd#2466]
Find and Replace workflow not working. Specifically, the actions are not running after the YML file is updated.

 See #2462 and the [thread in Support WG](https://teams.microsoft.com/l/message/19:bfdf92c7846542b58e9961e1d8cc671e@thread.skype/1642190056640?tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf&groupId=1db500d5-0d01-4254-af42-ad3f78bafacd&parentMessageId=1642190056640&teamName=teampsd_vha&channelName=support_workgroup&createdTime=1642190056640) for more information.

**Comment by jamesmrollins** [comment]
Hi @mnallajerla .  Is it possible to keep this discussion in the original thread, instead of starting a new bug? Also, if possible, I would like to share a screen with you to see the process you are following.  Was this in your forked repo?
