### ISSUE TITLE
wk4 jan_epic: MTL Manual bug - broken S5 logo/image links

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2467]
Identified during John & David's prep s05 on 1/19:

Broken links for logos and images, overall formatting is off. 
The chapter looks out of sync in the table of contents too.

https://lzim.github.io/mtl/6-mtl-live-session-05.html#DontClick
![image](https://user-images.githubusercontent.com/59668647/150213883-7530ea23-a00b-41ab-8db1-6b246ffa217c.png)

**Comment by jamesmrollins** [comment]
Hi @lijenn - In noted this problem also when I was updating the Test repo on Thursday night.  When I have a chance, I will look into this also.

**Comment by lijenn** [comment]
@jamesmrollins I will be looking into this today, thank you!

**Comment by lijenn** [comment]
@jamesmrollins I noticed we didn't have a FindReplace.yml for the lzim/mtl gh-pages branch so I added one.
I noticed in bookdown, it likes it's .png files to come from the raw source so I tried to FNR .png -> .png?raw=true but it failed with this error code at: https://github.com/lzim/mtl/actions/runs/1743318466
![image](https://user-images.githubusercontent.com/59668647/150901432-4c461d8e-6181-42c2-82a2-1c758c2bbbfd.png)

Maybe I missed editing something in the YML file for it work in the gh-pages branch here?
https://github.com/lzim/mtl/blob/fnr-png_bookdown/.github/workflows/FindReplace.yml

Will look more into this myself tmrw, thank you!

FYI @mnallajerla

**Comment by jamesmrollins** [comment]
Hi @lijenn - I am grasping at a few straws here . . . 

## Try removing this space

![image](https://user-images.githubusercontent.com/30132017/150982796-dbbe10ce-4e92-456b-85dd-9feb922ed31d.png)

## Try adding a wildcard to the argument

find: "\*.png"
replace: "\*.png?raw=true"

## Try escaping the characters 

### From the jacobtomlinson gha-find-replace issues log

[regular expression syntax not documented](https://github.com/jacobtomlinson/gha-find-replace/issues/13)

### Syntax explanation

[golang docs on regular expressions](https://github.com/google/re2/wiki/Syntax)

### For example

find: ".png"
replace: ".png\\?raw\\=true"

Or some combination  . . .  hope this helped!
