### ISSUE TITLE
wk3 jan_epic: SIM UI TEST - Rename Aggregate to Team (AGG) Care

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2468]
Identified by @lzim in John & David's S05 prep on Wed. 1/19

crossref: #2425 

@jamesmrollins, please help change Aggregate on the Sim UI TEST to be Team (AGG) Care.
![image](https://user-images.githubusercontent.com/59668647/150214249-0421bcfa-eaa0-40a7-b331-9a8346f708d6.png)

FYI @mnallajerla

**Comment by mnallajerla** [comment]
Hi @jamesmrollins , here is another screenshot of a second instance where "Aggregate" needs to be changed to "Team Care" 
![image](https://user-images.githubusercontent.com/89947989/150231936-684c31db-09e9-46c0-a0a3-5c876faec2b8.png)

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire 

Please make the following changes to the Sim UI and promote to Test Slow.  Please note that we will be replacing all instance of the "AGG" or "Aggregate" with "Team (AGG) Care."

## Change Home Page Menu

![image](https://user-images.githubusercontent.com/30132017/150264827-24297abd-115b-47c4-b2f8-0dd1d298623a.png)

## Main Diagram Header

![image](https://user-images.githubusercontent.com/30132017/150265119-4f6160a3-da8b-4df2-bea6-7a9756d4e17e.png)

## Team Set Up

![image](https://user-images.githubusercontent.com/30132017/150265233-2ab44137-665b-4a67-a9df-6959b0be8f16.png)

## tt Dropdown (and any subsequent report pages)

![image](https://user-images.githubusercontent.com/30132017/150265439-6b7131a1-7c8c-441d-b516-1ee67c5e34cc.png)
