### ISSUE TITLE
Sim UI - EDIT .xls EXPORT (CURRENT ISSUE) - OLD issue of the default values (RESOLVED)

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#247]
I'm working in PROD tonight, wondering if it's operating properly; maybe in flux with development and if so should I hold tight while UI changes are being made?

Browser, time, module, dataset, screen shots are on the attachment. Basically, I'm wondering if the widget in the model diagram shouldn't be reflecting the value in the team data table for Starting Rate when the switch is set to Use Team Data for Starting Rate. And the two base cases (with and without that switch set to On) yield Starting Rate charts that don't seem to jibe. (Didn't include those in screen shots.)

[cc questions 102818.pptx](https://github.com/lzim/teampsd/files/2523496/cc.questions.102818.pptx)

**Comment by lzim** [comment]
@branscombj and @jamesmrollins and @TomRust 
FYI @staceypark and @ericasimon 

I'm not sure if I understand the issue. @branscombj can you take a screenshot of your inspector or developer information to help with any debugging?

**Comment by branscombj** [comment]
inspector or developer information? I don't know what that means.
Just wondering if the current PROD version of the sim UI should be running properly right now because I'm seeing things like I attached above. If I should be using a different version, please let me know. I'm trying to build out session 5-10 scripts and need to know that what I'm seeing is correct. 
In the case above, I expected to see an oscillation in some outputs in the Base Case, but did not. And noticed that the widget, Team Data table, and output values didn't align.

**Comment by jamesmrollins** [comment]
Hi @branscombj !  

I will dig into this and see what I can find.  I will start with running the Vensim model to see what values it is returning versus what the Sim UI is reporting.  This is going to take me a while to track this down, and I have doctor appointments this morning and early afternoon. I will try to resolve/explain today.

Thank you,
James

**Comment by jamesmrollins** [comment]
@branscombj 
Hi Jane - here is an update.  I have verified that the Sim UI and the vensim model (CC_PROD.vmf) are returning ifferent results.  I am not sure what the sudden change is, but we will investigate further.  The are a few hypothesis we will follow:
1.  The server version of Vensim may have a bug.  We have had this issue with the PSY model before. 
2.  We are somehow not pointing the code at the right variables.  This is highly unlikely since we haven't changed the code for quite a few months now.

I will let you know what we find out.

Thanks for the report,
James

**Comment by lzim** [comment]
Thanks @jamesrollins and @branscomj!

@staceypark are you able to put something together that explains how to capture any errors recorded by your browser, for example it’s called inspector under the develop Safari menu item and it’s under Tools > develop in Chrome.

It’s helpful to know how to do this for debugging some things.

Thanks!

**Comment by lzim** [comment]
@branscombj @jamesmrollins @saveth @staceypark @ericasimon @joycepyang @dlounsbu @TomRust @dlkibbe @holbrooa 

Thanks @branscombj for bringing this to the Team's attention! @jamesmrollins and I were on the line first thing this AM to discuss the issue, which Forio is investigating today.
I have asked @jamesmrollins to provide updates to EVERYONE here, as you may find similar issues to those @branscombj identified until this is resolved.

We will be working to resolve ASAP! :rescue_worker_helmet:

**Comment by jamesmrollins** [comment]
I just spoke with Epicenter and they are tossing the dead chicken over the fence to me.  According to their results, the model is running correctly in the Epicenter platform.  Somehow, according to them, our code is not interpreting it correctly.  Although I am unsure why, all of a sudden, this is the case as the model has been running for over 6 months now.  Nevertheless, we will dig into their suggestion and see what we can resolve by Monday.  Thank you for your patience . . .

**Comment by branscombj** [comment]
@jamesmrollins @lzim @TomRust @dlkibbe @dlounsbu A couple of folks have told me the sim's running properly again, but I'm still getting the results in the [image above ](https://github.com/lzim/teampsd/issues/247#issuecomment-435379762) 
If those results for BC in CC with Use Team Data ON are correct, I would really appreciate if someone could give me a few minutes of time to talk through them. Debbie and I are having a hard time finalizing scripts for sessions 5-10 without being able to line up sim results with system stories as we understand them.
Thanks!

**Comment by staceypark** [comment]
@jamesmrollins the sim isn't opening at all for me right now? I'm stuck on the "Please wait while redirecting to user's decision details" message.

@lzim @TomRust @dlkibbe @dlounsbu @branscombj anyone else experiencing the same problem?

**Comment by jamesmrollins** [comment]
I will take a look at it when I get home

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by dlkibbe** [comment]
Yes, I've been having problems getting on but I thought it might be my dad's router... I have been having internet problems since Sunday due to rural connectivity issues.

**Comment by branscombj** [comment]
@staceypark @jamesmrollins I just logged in with no problem to 2 worlds, logging off in between.

**Comment by jamesmrollins** [comment]
@staceypark @branscombj @dlkibbe I just logged in as well.  Sometimes, when the internet is slow, there are issues loading the Sim UI.  But they usually don't last long.  I was having some issues this morning, because I was also using Skype.  Soon as I closed Skype, everything worked well.

**Comment by jamesmrollins** [comment]
@branscombj @staceypark @TomRust @dlounsbu @lzim @dlkibbe Pursuant to decisions made during a July 11 Lucid Standardization Committee Meeting, Takouba will ensure the following Team Data use settings are "on" for the following models and variables:

CC Model | "Use Team Data for Starting Rate" | "On"
MM Model | "Use Team Data for Starting Rate" | "On"
AGG Model | Select Mode | "Service Proportions from Team Data" 

The decision was supported in part, to reduce the potential for confusion for the learner. Most teams would select to use their team data for a starting point. Therefore, it was thought that we should set these as the defaults.  

If you have any issues with these decisions, please register them here before COB (PST), 9 NOV 2018.

Thank you,
James

**Comment by lzim** [comment]
Thanks again, in particular to @branscombj @TomRust and @jamesmrollins for work to identify and address this issue. FYI: @staceypark  @dlounsbu @dlkibbe @ericasimon as this is related to finalizing MTL 1.7 scripts for the *MTL Video* shoot in a couple weeks.

Despite, SD conventions about starting models in equilibrium, I concur with @jamesmrollins proposed solution to have the team data on as default, which is consistent with our standardization committee meeting decision over the summer (see Decisions in Lucid and refer to 7/11/2018 meeting for discussion and context) to: 
1. Always run the base case with all feedback loops on
2. Always run the base case with team data to enable "apples to apples" comparisons of bc, exp 1, exp 2, and exp 3 system behaviors, in which the "what if" of "base case of no new decisions" accurately reflecting many teams out-of-equilibrium.

We did a lot of piloting, particularly with the AGG module, to identify this is that best approach for our stakeholders' needs.

> **Proposed Solution:**
> Change the default settings to "on" for the "Use Team Data for Starting Rate" switches. When the user selects a session from the home screen, the simulation will present values at time zero. The user can then select experimental values, which will be entered into the model and run from the start (negative time position), through to week 104.

**Comment by lzim** [comment]
@jamesmrollins @saveth @staceypark @ericasimon 

@jamesmrollins question we are working on the export function with @saveth 
And we are trying to find out where it is recorded what the base case values are that the model reads, for example -0.01 or -1. Is that in the master crosswalk?

- https://github.com/lzim/teampsd/blob/master/resources/master_crosswalk/current/master_crosswalk_table_v16.2_5nov18.xlsx

What we want @saveth to be able to list what the experimental values are from the export and filter out those values that were not changed (i.e., base case values), since those are already reflected in the team data table.

**Comment by jamesmrollins** [comment]
Usually, the base case signal value is the first negative increment of the scale.  So if the increments are 0.01, then the value that signals the model to use base case is -0.01.  The default value, scale and base case signal value is not uniformly indicated in the crosswalk, since we didn't have those values listed as a part of the format until agg.  That's part of the reason why I have checked it out, because I need to correct all of that.


James Rollins

Managing Partner

Takouba Security, LLC.

1423 E. 29th Street, Suite 238

Tacoma, WA 98404

(425)919-5153[cid:ba3d2eec-efde-49b2-9628-7a28e6a856e8]

www.takoubasecurity.com<http://www.takoubasecurity.com>




________________________________

**Comment by lzim** [comment]
yeah @jamesmrollins that what I thought and why I put it in this issue, not just issue #245 
We want to include the tt reports in the MTL Video shoot in St. Louis in a couple weeks, can you be sure to ping @saveth when you post the Master Crosswalk update?

She is going to be working on this over the weekend.

@jamesmrollins is working on this now, @saveth 
fyi @staceypark and @ericasimon 

> Usually, the base case signal value is the first negative increment of the scale. So if the increments are 0.01, then the value that signals the model to use base case is -0.01. The default value, scale and base case signal value is not uniformly indicated in the crosswalk, since we didn't have those values listed as a part of the format until agg. That's part of the reason why I have checked it out, because I need to correct all of that.

**Comment by saveth** [comment]
@jamesmrollins thanks for the updating the master crosswalk. I used it to create the table of parameter changes the team made for each experiment in #271 .

**Comment by jamesmrollins** [comment]
Hi @saveth, If you have access to 1.7, try downloading an export file.  It should be exporting an .xls file in columnar format.  Let me know if you have difficulties.  Thanks, James

**Comment by jamesmrollins** [comment]
Hi Savet,
Will you see if you can open this file?  Let me know if you have any difficulties.

Thanks,
James

James Rollins
Managing Partner
Takouba
www.takoubasecurity.com
(425)919-5153

**Comment by saveth** [comment]
@jamesmrollins I don't have access to MTL 1.7. @staceypark can you export the file for psy from mtl 1.7 for me?

**Comment by staceypark** [comment]
@saveth Hi! Apologies I've been buried in other stuff.  I'll send you a file and give you a login to the _MTL 1.7 TEST_ in a couple hours as well.

**Comment by staceypark** [comment]
@saveth I was able to set you up with a login. The username is your VA email and password is the same one you've been using. Ran into some issues in pulling the export file however, which I reported to James on #257

**Comment by staceypark** [comment]
@jamesmrollins I just tried exporting a psychotherapy file from _MTL 1.7 Test_, but it gave me a .csv file instead of the .xls?
Also got an error, which I reported in #257 . Not sure if that may have caused the .csv file issue though.

@saveth I'll still send you the .csv I pulled in case that's useful?

**Comment by jamesmrollins** [comment]
@staceypark @saveth The only model exporting .xls is the SP model in Test.  We are attempting to resolve the time-step issue as the highest priority.  After that is resolved, we will implement to export .xls to other models.  Stay tuned!  James

**Comment by jamesmrollins** [comment]
Good Morning @saveth @staceypark, the export .xls function is available for all models in Test.

**Comment by staceypark** [comment]
@saveth I ran and saved sample runs in all 5 modules here:
https://github.com/lzim/teampsd/tree/master/quant_workgroup/mtl_viz

**Comment by saveth** [comment]
@staceypark I can't download the .xls file from the path you mentioned above. Nor can I seem to send the file to myself per my email. Help please.

**Comment by staceypark** [comment]
Hi @jamesmrollins 
Looks like I can export to .xls through both the export button in the Experiment Maintenance and through the Outputs on my VA machine using Chrome 🎉 😄 

On my Mac, previously the Experiment Maintenance export button gave me a .csv file and the Outputs export gave me a TextEdit document.  Now both export buttons give me a TextEdit document on my mac?

**Comment by staceypark** [comment]
@jamesmrollins The file format you sent to @saveth to work with does not match the exports I'm pulling from the sim.  I've been trying to debug her code, and after changing the exports from ones today to the ones you sent, her code works again.

The exports are .xls files. I've tried changing them to .xlsx and that doesn't make the code run all the way through either.  But using the .xlsx you sent makes it run?

I wonder if it's related to this issue: https://github.com/tidyverse/readxl/issues/480
Are we still forcing a different file extension to be .xls?

**Comment by staceypark** [comment]
Issue resolved - Download and resave as .xls
