### ISSUE TITLE
wk2 feb_epic: MTL Guides & Sim UI Documentation: SP New Episodes of Care unit from week -> months

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2472]
Discussed 1/20 Quant Operations:

We made the decision to change the unit for SP New episodes of care from weeks to months in MTL Data UI.

**Clinicians think through decisions episodes of care in the unit of months.**
**Unit of time - Model is meant to match the decision it's meant to support, including the definition of the unit of time.**

Need to comb through existing documentation on guides and the sim ui on this decision.

**Comment by jamesmrollins** [comment]
@lijenn - Is this to be completed by Feb 14?

**Comment by lijenn** [comment]
@jamesmrollins I believe it will depend on whether or not Swap & Matt's MTL Blue team plans to meet next Tues. Feb 1st for Blue Session 01. We will be reaching out to their team tomorrow to see if that is still the case since they rescheduled Session 1 due to staff being out from covid.

If so, this team may want to use SP & we'll need to coordinate the user testing with @jeffhoerle.

The documentation would ideally be done by Tues Feb 8th when Facilitators meet to prep for Session 2.

Let's discuss more Support WG on 1/26 at 11AM Pacific/2PM Eastern on updates related to SP.

**Comment by lijenn** [comment]
Confirmed that this requires no changes to the Sim. It was only changed on the UI side in power bi. 

We will simply remove references to 39 weeks in the existing SEE/SAY documentation to say 9 months instead, already tracked in #2486
