### ISSUE TITLE
story13: PBI MTL Data Homepage VISN Dropdown

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2473]
Discussed 1/20 Quant Operations:

![image](https://user-images.githubusercontent.com/59668647/150416864-ea3ab5a1-d1dd-49e8-8c61-797f2545af51.png)
![image](https://user-images.githubusercontent.com/59668647/150416915-6f79bacb-f288-4369-8ecf-22ee68a829f4.png)

**Comment by jeffhoerle** [comment]
I've uploaded a landing/welcome page to the TEST app.  I can't insert hyperlinks (like the example above).  Will await feedback!

**Comment by jeffhoerle** [comment]
Landing page seems to be working well.  Closing.
