### ISSUE TITLE
wk4 jan_epic BUG - vizFlag & vizMeas tabs broken

### ISSUE THREAD

**Issue by mnallajerla** [lzim/teampsd#2474]
From @jeffhoerle : 

Quick heads up: I just realized that I unwittingly broke the vizFlag and vizMeas pages on the VISN 22 report I published last night (everything else works fine).  I'm going to let it be for the time being unless I'm told otherwise.  It will be fixed when I publish the report next.

**Comment by jeffhoerle** [comment]
V22 Report fixed and updated.
