### ISSUE TITLE
wk4 jan_epic Giving Meghana EpiCenter access

### ISSUE THREAD

**Issue by mnallajerla** [lzim/teampsd#2475]
@lijenn @jamesmrollins  - I set up my epicenter account but do not see any of the projects you showed me yesterday. I poked around a bit but can't seem to find them - am I added to the projects on EpiCenter as well? Thank you! 

![image.png](https://images.zenhubusercontent.com/6130066bf230e9289f9a2c0c/cd62589c-231c-4bd5-967a-186912406f4e)

FYI: @lzim

**Comment by lijenn** [comment]
@mnallajerla Just sent you an invite to the Veterans Affairs group on Epicenter. 
Let me know if you see a total of 13 projects associated with MTL Menu, Demo, TeamPSD, and Sim UI. Thanks!

**Comment by mnallajerla** [comment]
@lijenn - I checked both my "Other" and Junk inbox and do not see the invite. Did you send to my VA email? Thank you!

**Comment by mnallajerla** [comment]
Confirming I now have access. Thank you @jamesmrollins !! :)
