### ISSUE TITLE
wk4 jan_epic Update RLS permissioning instructions in PBI Documentation 

### ISSUE THREAD

**Issue by mnallajerla** [lzim/teampsd#2476]
- RLS permissioning is no longer at the previous link we indicated. @jeffhoerle has shared these links change when new version of PBI reports get published
- See Support WG thread for new instructions - these need to be added to our TEST and PROD documentation and Facilitator One Pager. 

FYI: @lijenn @lzim

**Comment by mnallajerla** [comment]
hi @lijenn - may be a good time to re visit this since we discovered some work arounds and also are wrapping up PBI documentation.

Would this make sense in the Data cheatsheet or facilitator one pager?

**Comment by lijenn** [comment]
Would recommend closing since the work here was done (and for accurate cost data). Let's make a new card to track those 2 resources + Guides where RLS is mentioned.

**Comment by mnallajerla** [comment]
@lijenn let's refer back to #2310 to track related documentation since that falls under PBI related documentation. I will make a comment on that issue.
