### ISSUE TITLE
Team p-chart

### ISSUE THREAD

**Issue by saveth** [lzim/teampsd#248]
@lzim @holbrooa @ericasimon @staceypark 

As I'm creating the R code for the p-charts, I have a few questions that I hope one of you can address:
1) Why are we using 13months average instead of 12months?
2) Shouldn't the first year average depend on when a team join the project? Or are we using only one baseline for all team?
3) Is there a reason why we're using 3sd instead of 2sd for the confidence interval?

**Comment by lzim** [comment]
Great! Both would be perfect. Thanks @saveth!

**Comment by lzim** [comment]
@saveth 

**Here are four hex codes for the p-chart panels** 
- UCL - VA Vibrant Green - #78B43
- Mean - VA Bright Red - #C4262E
- LCL - VA Vibrant Purple - #685BC7

Please the same color for the actual data line each panel (Other, MPD, STC):
- VA Light Blue #0083BE

**In the legend**
- Only include the "Upper Control Limit (UCL), Lower Control Limit (LCL) and 12-month pre-mean 
- Leave the clinics/settings for the headers of the 3 graphs (2 versions)

**We need 2 versions of the p-charts** - one for the frontline teams that read:
- "Other", "Menlo Park," and "Stockton"

**A second version of the p-charts that read:**
- "Other 7 clinics from the same HCS"
- "PSD Partner Clinic 1"
- "MTL Partner Clinic 2"

**Y-axis label:**
- Evidence-based Psychotherapy (%)

![pcharts_v1](https://user-images.githubusercontent.com/7454688/48282602-025b9980-e40f-11e8-8790-3e02471c3918.png)

FYI @staceypark and @ericasimon

**Comment by saveth** [comment]
@lzim ggplot requires N unique colors = N unique values for the legend. We can't have all three locations the same color. How about dark blue, light blue and dark red?

**Comment by saveth** [comment]
@lzim @ericasimon @saveth Please review the changes in pull request #262. If you're happy with all the updates, then merge with master. I think it's ready for you to use in the upcoming national presentation. :)

**Comment by lzim** [comment]
Great thanks @saveth!!

I’m going to work on this now. :smile:

**Comment by saveth** [comment]
@lzim I've updated the p-charts so that the dual grey shading has been removed, only one per graph now. I think if you're happy, we can close this issue after merging #275 .
