### ISSUE TITLE
wk5 jan_epic BUG SIM Shared world not loading for Friday Blue team

### ISSUE THREAD

**Issue by mnallajerla** [lzim/teampsd#2484]
Hi @jamesmrollins  - in prep with @dlounsbu and @john and we are unable to load the shared world for the team.

**Comment by lijenn** [comment]
Thanks @mnallajerla! It's also helpful to provide the console log when issues like this occur so DEV can see the error:
1. Right click on anywhere on the page
2. Click "Inspect"
3. The default tab is "Elements", click on the ">>" to switch to "Console" and post the log for @jamesmrollins below:
![image](https://user-images.githubusercontent.com/59668647/151639342-1dcd4d31-e5b6-4149-a8f8-2c91fdadddb7.png)

**Comment by jamesmrollins** [comment]
FYI: @lijenn

Hi @mnallajerla 

## Problem is the *2022_01_19.xlsx file is not available - the sim will not load.

![image](https://user-images.githubusercontent.com/30132017/151711606-d90d3020-26fc-4602-a9cd-90dc2c5c4812.png)


## If the 2022_01_19 file was deleted from the Facilitator Dashboard, it should be removed from Home Page Dropdown Maintenance listing

![image](https://user-images.githubusercontent.com/30132017/151711890-90e884de-d87e-4cd5-8a36-934626b1f33c.png)

![image](https://user-images.githubusercontent.com/30132017/151711978-5c9b7c03-2fc7-4100-b3f6-b566ff5e0775.png)

**Comment by mnallajerla** [comment]
I have tested this and it is working alright for me. Have requested the facilitators to confirm on their end as well
