### ISSUE TITLE
wk2 feb_epic SP Documentation DEV

### ISSUE THREAD

**Issue by mnallajerla** [lzim/teampsd#2486]

**Comment by lijenn** [comment]
@mnallajerla here are some things that are top of mind when it comes to SP documentation, please feel free to add anything I'm missing :eyes:
I can also help out with edits and review on Monday before the data bootcamp on Tuesday. Thank you!

#mtl_facilitators #mtl_learners #mtl_admin discussed on Thursday Quant Ops 2/10/22:

**Clinic Selection comparison tab** (not sure of final name...)
- [ ] SEE & SAY Guides + Checklists: After Session 1 (the last Do) and before Session 2 (the first Done), add reminder to complete asynchronous checking that does not require a meeting, they can post these clinic selections in the channel (based on the new tab that Jeff will be adding to PBI). This would occur AFTER the Facilitators meet with the Team Lead to attempt to create the clinicselections for the team before Session 2 live meeting.
- [ ] Data Cheatsheet: include SP tabs and brief description @lijenn can help with this
- [ ] Data Cheatsheet and Facilitator one-pager: include how to do asynchronous checking of clinic selections @lijenn can help with this
- [ ] Checklist in CRM: Add step after session 1 to remind facilitators to ensure clinic selections are posted in Teams channel @lijenn to help with this (Note: add @mnallajerla to CRM via YourIT)

**SP Edits across SEE/SAY Guides & Checklists + GIFs**
(Note: It looks like SP is first mentioned in Session 3, but I believe we need to move any clinic selection documentation for SP to Session 2 and then mention the 
- [ ] Suicide Prevention/SP to be renamed Team (SP) Flow: Measurement Based Stepped Care and Suicide Prevention
- [ ] Double check existing Guides documentation for SP are accurate with what is shown in Power BI and make edits as needed (e.g. the tab in PBI should say 'Team (SP) Flow' and remove references to 39 weeks to say 9 months instead)
- [ ] GIFS: One that shows the SP clinic selections tab for Session 2 and walk through how to make selections in the tab & One that shows the sp params being populated in session 3.

**Comment by mnallajerla** [comment]
These things also need to be updated in RED Guides, in the same places. However, did not add that here because we have not done RED documentation yet and can do it altogether.

**Comment by mnallajerla** [comment]
Questions to Review:

- [ ] HF, Diag, SP (Meas?) Tab???

**Comment by lijenn** [comment]
- [ ] @lijenn add export of clinic selection and a checklist task for MTL RED (already done for MTL Blue) in the CRM

**Comment by mnallajerla** [comment]
@lijenn I am all good for this card. If you are done with your portions for CRM, I can close it. Thank you!

**Comment by mnallajerla** [comment]
Hi @lijenn - same with this card, thank you! :)
