### ISSUE TITLE
Asynchronously Upvote Backlog Features

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2492]
Tech stack is invisible to the front-line.

What method can we develop to have the front-line upvote backlog and features?
Community of Practice??

**Comment by jamesmrollins** [comment]
Sim UI 3/2

- Will discuss at the 3/10

**Comment by matthewtomo** [comment]
#adjudicate_memo
@matthewtomo @jamesmrollins @ljmoody 
- Marking as closed for now since we do not currently plan on moving forward with this feature
