### ISSUE TITLE
wk2 feb_epic BUG Filter panel disappears when using personal bookmarks from prior to data update

### ISSUE THREAD

**Issue by mnallajerla** [lzim/teampsd#2498]
Hi @jeffhoerle - 

We've identified an issue with the facilitators today - When using personal bookmarks for clinic selections, made before the most recent (2/4/22) data update, the filter panel on the side of the screen disappears. Please see screenshots:

No filter panel, when I use my personal bookmark from 1.21.22:

![image.png](https://images.zenhubusercontent.com/6130066bf230e9289f9a2c0c/e6f7ead8-fd43-40cb-a97f-e400ab088caa)

Filter panel with regular clinic selections made by hand, or personal bookmarks post 2/4 update:
![image.png](https://images.zenhubusercontent.com/6130066bf230e9289f9a2c0c/3ac88de5-df69-445d-b61e-4a66ce28610a)

FYI: @lijenn @lzim

**Comment by jeffhoerle** [comment]
Hey @mnallajerla.  This is strange behavior.  I can only take a guess at what's happening.  A personal bookmark remembers the report "state"... such as what clinics were selected.  But it might also remember whether the Filter panel was visible?  I believe that with one of the previous report version that the Filter panel was hidden.  It has since been added back, but if the personal bookmark remembers that the Filter panel was hidden when it was added/updated then it could be hiding it now?

If anything, this sounds like a bug in the Power BI cloud service.

**Comment by mnallajerla** [comment]
Thank you@jeffhoerle 

Could it be possible it is a clinic selections issue? Because, when we remake a *new* bookmark using old one as a starting off point, with the previous clinic selections, the same issue is coming up. 

I can demonstrate this for you tomorrow, or make a screenrecording and share it in our Teams thread. Thank you! 

FYI: @lijenn @lzim

**Comment by jeffhoerle** [comment]
My guess is that as soon as you click on the old bookmark, it somehow tells the report to "Hide Filter Panel".  Changing the clinic selections and doesn't do anything to undo that.

Again, these are only guesses.  We'll review more tomorrow.

**Comment by lijenn** [comment]
#adjudication_memo

@jeffhoerle Has already fixed this issue in the latest revisions to the Data UI. If users are seeing the filter panel missing, they are likely on an old bookmark that has an outdated version of the Data UI.

See Solution posted in teampsd_vha / facilitate_workflow at Feb 22, 2022 5:09 PM Pacific:
[Zimmerman, Lindsey E. (she/her/hers): Troubleshooting "Filter Panel Disappeared"… ](https://teams.microsoft.com/l/message/19:cb0b9866ac224a179236c0cc3e2ee56f@thread.skype/1645578575623?tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf&groupId=1db500d5-0d01-4254-af42-ad3f78bafacd&parentMessageId=1643935131947&teamName=teampsd_vha&channelName=facilitate_workflow&createdTime=1645578575623)

Closing this card!
