### ISSUE TITLE
wk3_feb: Update Sim UI SP Module Labels

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2501]
# Update SIM UI SP Module Labels

The current labeling in the Sim UI is called "SP" or "Suicide Prevention."  However, the module covers many scenarios that include Measurement Based Care (MBC) and Stepped Care.  Moreover, the module supports care team decisions for flowing patients to higher or lower steps of care, depending on the location of the clinic in the hierarchy. Therefore, the Team would like to rename instances of "Suicide Prevention" or "SP" to "Team Flow" or a related title.

### Home Page. "Join Current Session" and "Start a New Session"

![image.png](https://images.zenhubusercontent.com/5e4eac12455ade27f3584cea/3ed8fc23-ec4d-47f2-9b5d-a57e197720fb)

### More Info Page.  "_MTL_ Modules" section.  _Note:  We can change this from Admin Dashboard if necessary._

![image.png](https://images.zenhubusercontent.com/5e4eac12455ade27f3584cea/f6cf73b6-473b-4cb4-a889-5e41125f5982)

### Play Page.  "Main Diagram" header.

![image.png](https://images.zenhubusercontent.com/5e4eac12455ade27f3584cea/27716771-a5c0-4a14-83d2-8025aa11b64e)

### Outputs and Text Popup. Description.

![image.png](https://images.zenhubusercontent.com/5e4eac12455ade27f3584cea/9a85744d-d150-4500-8d7f-3804e551b60c)

## Assumptions

- [x] There will no data variable name changes.
- [x] There will be no model variable name changes. 
- [ ] **Long titles (i.e., GMH Measurement Based Stepped Care and Suicide Prevention) will be changed to "Team Flow"**

**Comment by lijenn** [comment]
Thanksfor the initial assessment @jamesmrollins! Noting that it'll also need to change for the tt reports:
![image](https://user-images.githubusercontent.com/59668647/153309834-5ecdc143-58bd-4d37-a43a-95155a5dff58.png)

**Comment by jamesmrollins** [comment]
Hi @lzim - I documented the changes in #2481 and added the dependency here.
