### ISSUE TITLE
wk1_mar: Update gif files in _mtl_ Blue and Red documentation to reflect Team (AGG) Care naming

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2505]
**Reference #2425**

# gif Edits Are Required in These Files

- [x] mtl/blue/session04/s04_facilitator/mtl_session04_say.md
- [x] mtl/blue/session04/s04_learner/mtl_session04_see.md
- [x] session04/s04_learner/mtl_how_sim_cheatsheet.pdf
- [x] **session05/s05_learner/mtl_session05_see.md** 
- [x] **session05/s05_facilitator/mtl_session05_say.md**
- [x] session06/s06_facilitator/mtl_session06_say.md
- [x] session06/s06_learner/mtl_session06_see.md
- [x] session07/s07_facilitator/mtl_session07_say.md
- [x] session08/s08_facilitator/mtl_session08_say.md
- [x] session08/s08_learner/mtl_session08_see.md
- [x] session09/s09_facilitator/mtl_session09_say.md
- [x] session09/s09_learner/mtl_session09_see.md
- [x] session10/s10_learner/mtl_session10_see.md
- [x] session11/s11_learner/mtl_session11_see.md
- [x] red/part2/part2_learner/mtl_red_part_2_see.md

## Make these updates in Test Repo.

**Comment by lijenn** [comment]
@mnallajerla is tracking other Power BI documentation items in #2310, I'm going to link this card to her card.

**Comment by jamesmrollins** [comment]
This is now a pull request to @mnallajerla for wk 2 Mar
