### ISSUE TITLE
story_f: User needs a devops actions scheme to move all test repositories to production

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2510]
## Reference

- #2125 User needs markdown and bookdown actions to streamline to ensure quality of edits

## Narrative

By having an integrated repository system between document and code repositories, releases can be prepped and coordinated asynchronously. Then automation can be used to pull both code and doc updates to PROD at the same time.

## Deliverables

- [ ] Migrate forked @mnallajerla/lzim/mtl_test repo to an lzim/mtl_test repo.
- [ ] Create a Master Action Flow Diagram that describes how all repos will interact in the Test -> Prod flow.
- [ ] Create and test actions that support flow.

**Comment by jamesmrollins** [comment]
From Sim UI Meeting 2/23:

- Edits are under Meghana's repo instead of Lindsey's.
- Need to set up CI for work flowing into these repos. 
- Iterative "Find and Replace" for names and links doesn't appear feasible or scalable.
- With branching, we are getting merge conflicts.  Sometimes the links are not updating from _test to _prod.  This would be nice to reliably automate.
- Some repos have "badges" that identify documents that are covered by CI.  See ([department-of-veterans-affairs/vets-website: Frontend for VA.gov (github.com)](https://github.com/department-of-veterans-affairs/vets-website)
- Need to go to the TRMS and look at "Circle CI" and "Travis CI" as a potential solution we might use. Identified in TRMS as NOT approved.  Need to understand what they do.  Also, check out the marketplace. [TRMS](https://www.oit.va.gov/Services/TRM/SearchPage.aspx)
- Open source solutions is still a governing value with respect to what solutions we choose.

**Comment by lijenn** [comment]
Discussed Mon 8am 3/14/22:

Documentation must include the workflow processes (e.g. old release would be archived in it's own folder) in addition to how the action scheme works.

[9:04 AM] Zimmerman, Lindsey E.
Team PSD 2.0 Manual -> Release Workflow specified in Team PSD 3.0 Manual
Team PSD Workflows 
- Onboarding
- LucidCharts Diagram
- ZenHub also has release
(Cross-cutting: Dynamic Workflow & Data feed Team PSD 3.0 -> # (Issue #) Story K Onboarding and Documentation)
Creation of fnr-2.0_3.0 branch - the branch to replace the TEST extensions when moving to PROD. 

[9:04 AM] Nallajerla, Meghana R.
New Release Workflow: Create release folder for old versions of guides James - Issue Card (#) to document this workflow?

Story K - Onboarding "Team PSD 3.0 Manual"
- GitHub new MTL Release (MTL Documentation & Sim UI) @jamesmrollins 
- Dynamics Workflow - @lijenn 
- Team 3.0 Data feeds - @dkngenda & @mnallajerla

**Comment by lijenn** [comment]
@jamesmrollins 

Use case: I see that the FNR for Team (SP) Flow found it's way through the archived file for a 1.7 release.

Could you ask DEV if there's a way to add something similar to a Git Ignore to the FNR action yml file to prevent it from searching certain folders/file paths?

It would keep the archived files untouched, save time in the pull request process for reviewers, and possibly improve the Action processing time.
 
![image](https://user-images.githubusercontent.com/59668647/158275741-cbf76475-3bd6-4cd4-b614-0f8a379bdaca.png)

**Comment by hnorthcraft** [comment]
#adjudicate_memo updating to 1SP
