### ISSUE TITLE
wk2 mar_epic: Story 13 PBI - Document How-Tos to upload/update files and pdf cheatsheets on the landing page

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2514]
Discussed 8am WG Leads 2/28:

@jeffhoerle Can we update the existing data ui landing page by ourselves (e.g. we want to upload a pdf of CPT codes)?

Does this documentation exist from the documentation you made in the lzim/research repo?

If not, could you create this documentation? 
We could then test it since we don't want to be reliant on you or our future computer scientist and engineer to be able to upload a file to the landing page ourselves.

**Comment by lijenn** [comment]
Here is the PDF we want to upload: [cptcode_cheatsheet_v2](https://dvagov.sharepoint.com/sites/VHAPTSDOMHO/Pages/VISN21/640.aspx?RootFolder=%2Fsites%2FVHAPTSDOMHO%2F640%2FMaster_DataUI&FolderCTID=0x012000294B49F4C77E0A4EAD5CEEA0EE22F232&View=%7B143FCEF7-103D-4B86-A61D-0441C9E68ADC%7D&OR=Teams-HL&CT=1646083833573)
Also @jeffhoerle Is there a way to cross-walk the list of CPT codes we have listed above and what is currently in Power BI? (e.g. We believe VVC codes need to be updated).

@lijenn will cross-walk for any other documents and guides left on https://mtl.how/data that we may want to update and add to Power BI Data UI.

**Comment by jeffhoerle** [comment]
@lijenn, updating the Landing Report is basically the same as updating the DataUI, but much simpler.  I'll update the GitHub documentation.

The CPT codes in that PDF exactly match the mapping in the project of CPT to Encounter Type (e.g. Art Therapy, Addiction, etc). 

Currently, the project will tag a clinic as VVC if it's **Secondary** Stop Code is 179.
