### ISSUE TITLE
wk1 mar_epic Moving "View Clinic Selections" Tab to Top part of PBI & Updating the Team Data for SimUI - Beta tab

### ISSUE THREAD

**Issue by mnallajerla** [lzim/teampsd#2518]
Hi @jeffhoerle - Right now, the "View Clinic Selections" tab is at the very bottom of the menu, beneath the Data, Viz and Team Data tabs: 

![image.png](https://images.zenhubusercontent.com/6130066bf230e9289f9a2c0c/e5c4b20d-947b-42c0-960b-f5e74f8f3854)

Would it be possible to move this up and have it placed beneath the "Clinic Selections" and "Team Flow" selections tabs? (ie, the highlighted area below): 

![image.png](https://images.zenhubusercontent.com/6130066bf230e9289f9a2c0c/a9bef3a7-0d36-4ae3-b312-bbe054587850)

FYI: @lzim @lijenn

**Comment by lijenn** [comment]
Hey @jeffhoerle, could you let @mnallajerla & @jamesmrollins know when you are able to the below done?
They are updating the GIFs for our documentation as our current GIFs are out of date.

- [ ] Move the "View Clinic Selections" tab up and below the "Team Flow Selection" tab.
- [ ] Update the "Team Data for SimUI - Beta" tab as the main tab for the Sim UI (and remove "- Beta").

**Comment by jeffhoerle** [comment]
@mnallajerla, @jamesmrollins , @lijenn - I have made all the edits to the report, but I am waiting until Monday morning (3/7) to publish it to the TEST workspace.  I expect it will be there by 11am(ET) on 3/7.  Will be sure to message you all once it's published.
