### ISSUE TITLE
URGENT BUG SIM_UI team AGG care shared world not loading during prep for FRI AM 

### ISSUE THREAD

**Issue by mnallajerla** [lzim/teampsd#2520]
Hi @jamesmrollins  - 

**We are unable to prep today** for tomorrow FRI AM meeting because team AGG care shared world is not loading. 
Will you please let @lzim @lijenn @mnallajerla @dlounsbu @jwklocek know 

- [x] When you might be able to look at this?
- [x] When you think this might be resolved?

We are looking for workarounds right now using indiv worlds.

![image.png](https://images.zenhubusercontent.com/6130066bf230e9289f9a2c0c/50024695-fec1-49c4-80ba-31ee8ec31a1a)

THANK YOU!

**Comment by jamesmrollins** [comment]
Hi @mnallajerla, @lzim @lijenn 

Are you using a fresh, unparsed, team data file??

**Comment by jamesmrollins** [comment]
I uploaded that SP file @lzim created last Thursday and ran it in AGG with no hitch.

![image](https://user-images.githubusercontent.com/30132017/156647414-927a39fa-d6b5-44cc-ae0b-2b594a2d6172.png)

**Comment by jamesmrollins** [comment]
@lzim @lijenn @mnallajerla @dlounsbu @jwklocek @mnallajerla 

It also appears to work with my Team Data file (as above) in the session in question.  So, I am thinking it is an issue with the Team Data file.

![image](https://user-images.githubusercontent.com/30132017/156648557-99169f58-d4e1-4675-889c-f5ee2b666b10.png)

**Comment by lzim** [comment]
@jamesmrollins I see you're testing in a different world with a different file. And, glad to here that is working fine. 

Thanks! **We're finding that the Sim UI is hanging in all 3 worlds** (ind, shared, team) with the file from **2022_01_20**

- [ ] We have a provider from this team who wanted to review today in his **individual world** but reported that **he doesn't have an individual world in his login drop down (this may be a separate bug?? TBD)** 
- [ ] @lijenn  is going to **impersonate this user** to check it out, he was not able to produce a screenshot for us.
- [ ] @lzim am going to **review the Clinic Selections** with the team and produce a **fresh data file**.

@jamesmrollins _What do you think we can expect in terms of behavior of the Sim UI if we upload a fresh data file?_
This team had only run their base case in their team world at the last team meeting, but 

![image](https://user-images.githubusercontent.com/7454688/156650475-656922a3-9ef8-41db-ba0c-4e044d86c21c.png)

**Comment by lzim** [comment]
@jamesmrollins  I just confirmed that the file for this time is of the old format. 
We'll work to produce a fresh file.

**Comment by jamesmrollins** [comment]
Hi @lzim - I have high confidence the Sim UI will work normally once it has a correct Team Data File.  That is the only item that is different between working and non-working sessions shown earlier in the thread.
