### ISSUE TITLE
wk2 mar_epic BUG duplicate named data files in SIM UI w/ different values 

### ISSUE THREAD

**Issue by mnallajerla** [lzim/teampsd#2521]
@jamesmrollins - 
Discussed with @lijenn and @lzim.
This is not urgent but worth looking at for the future. 
We can discuss next week. 

We resolved this issue in the shared world for tomorrow morning's (check MTL.help calendar) team meeting but wanted to alert your attention to it - 

- [x] 2 of the same named file are showing up in the SIM
- [x] deleting 1 deletes both
- [x] We also saw a data discrepancy between the files in the Shared and Team world even though we used the same NAMED data file 01_20.

![image](https://user-images.githubusercontent.com/89947989/156640077-2fd7da25-a281-4da2-a8c4-bb8acb315705.png)

**Comment by jamesmrollins** [comment]
Hi @mnallajerla - A follow up question regarding the Team Data file.  Was the file that was loaded straight from the Data UI, or was it already parsed (meaning reused from the Epicenter Model folder)?

Thank you - James

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire - please take a look at the above.  There are instances where the file is uploading duplicates and deleting duplicates.  I went to the homepage of the team in question above and found there is no listing of team data, even though they have used team data to start a new session.

## When I visited the Team Home Page, I see there are no listed Team Data Files.  There is a Team Data File that has been used to load the session.  And that Team Data file is in the Epicenter folder.

![image](https://user-images.githubusercontent.com/30132017/156644021-0e441b69-eb49-4cd0-aaaa-beb88e2b4ef3.png)

## From that team home page I was able to upload a team data file with no problems.

![image](https://user-images.githubusercontent.com/30132017/156644288-58cce5ed-0aff-4f37-88e0-8919f99304e3.png)

## However, the file I uploaded in Teams is not listed in Shared.  Yet, the Team Data file is listed in Shared. Shouldn't they be in both?

![image](https://user-images.githubusercontent.com/30132017/156644955-e98f08a9-2682-4e17-9080-56c6cbd96c8d.png)

## When I uploaded a test file to the Shared Team Data, I was not able to replicate the error.  I was also able to delete the file.

![image](https://user-images.githubusercontent.com/30132017/156645361-8f951699-6453-4c86-a5f3-b680771a57d7.png)

**Comment by hnorthcraft** [comment]
#adjudicate_memo assigning 2 sp to reflect efforts (documenting bug, research, and discussion)
