### ISSUE TITLE
ICEBOX: D365 Prod BUG - Some Co-planning and Teams only show up in the Associated View

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2537]
Co-planning group and and Live Team does not show up in the "My/All Co-planning Groups" or "My/All MTL Teams" dropdown, they only show up in the "Co-planning Group Associated View".

![image](https://user-images.githubusercontent.com/59668647/158217236-ff7f0fa2-ebb0-454a-901a-44a3e39616f5.png)

**Comment by hnorthcraft** [comment]
#adjudicate_memo updating to 1SP
