### ISSUE TITLE
Edit to MTL_red_part_1_say_checklist

### ISSUE THREAD

**Issue by dlkibbe** [lzim/teampsd#2538]
**1. Add description:** 
I went to mtl.how/test to look at the say guide checklist. The red part 1 say checklist needs minor edits @lijenn 

Location: https://github.com/lzim/mtl/blob/Test/red/part1/part1_facilitator/mtl_red_part_1_say_checklist.md

1. Following the introduction line of "Hello! I'm __________ and I'm __________. Today we're modeling to learn how to check our patient data and team trends." The checklist text says:  "Navigate to the Learner See Guide for **Session 2** to show Done and Do"
Given the red teams are doing 12 sessions in the data ui, the language should be generic "Navigate to the Learner See Guide for the session to show the Done and Do."

2. The text contains reference to the Sim Ui. 
  a. Delete text: "Review use of sim UI – to look at team trends 2 years into the future to answer what if questions about different decisions the team could make."
  b. Delete image: The image with _Data UI What Is_ and _Sim UI What If_ should be removed from the say checklist since the Red Teams don't see the Sim UI.

<< Paste screenshots here>>
1. When was the bug discovered? State the time and date. (Applies to Bugs, Data, and SIM UI) (Support Team - Check the MTL.help calendar to see who this bug impacted; De-identified, do not name team)
2. Is this an invidivual or shared world? (Do not name specific world, keep de-identified)
4. What is the name of the experiment? (Ok to name, not identifiable).
 
**2. Click on the right:**  
i. **Pipelines** - prioritize in a TeamPSD (& Workgroup) pipeline  
ii. **Assignee** - assign to an individual team member producing work for the issue  
iii. **Label**- assign workgroup (lead) responsible for tracking the task. If this is a bug, add "Bug" label.   
iv. **Projects** - assign to domain-specific TeamPSD tracker (issues, features, document, manuscript, team)  
v. **Milestones** - select monthly sprint milestone within the workgroup   
vi. **Estimate** - Estimate task in complexity points   
vii. **Epics** - assign to team-wide epic and TeamPSD master plan project  
iix. **Releases** - assign to key team release grouped with other relevant issues  

**3. If you anticipate that your **issue card** or **bug card** will have **dependencies** these can be added once the issue has been submitted.   
ix. **Add dependencies** - assess for and add dependencies *blocking* & *blocked by* this issue

**Comment by lijenn** [comment]
Thanks for catching it, fixed!
