### ISSUE TITLE
mar_apr_jun Story C MTL Video 3.0 EES Pop-up Timestamps

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2541]
# _Modeling to Learn Video 3.0_ 

Cross-ref last video series #748

### EES Was [notified via Teams](https://teams.microsoft.com/l/message/19:0016aeb1126c42e4b18fb2abbebee1d6@thread.skype/1651110336239?tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf&groupId=1db500d5-0d01-4254-af42-ad3f78bafacd&parentMessageId=1650932118208&teamName=teampsd_vha&channelName=ees_workflow&createdTime=1651110336239) this video is ready on 04/27/22

Time | Correction Type | Description | Photo Name |
-- | -- | -- | --
0:41 | Add Pop-up | Go to mtl.how for all *Modeling to Learn* (MTL) resources | Swap Mushiana PsyD
5:09 | Add Pop-up | The beginning and end of every MTL session has a “Done” and “Do” review | Lindsey Zimmerman PhD
8:59 | Add Pop-up | MTL Session 1 Goal: Integrate “Your Vision” with the “Team Vision” | Swap Mushiana PsyD
22:55 | Add pop-up | MTL participants receive Pre- and Post-session emails with “Done” and “Do” reminders | Lindsey Zimmerman PhD

## MTL Blue 3.0 - Session 02 Take 2 (mtl_blue_data_ui_take2)

Time | Correction Type | Description | Photo Name | Notes 
-- | -- | -- | -- |  -- 
0:39 | Add Pop up | Go to **mtl.how** for all _Modeling to Learn_ (MTL) guides and resources  | Lindsey Zimmerman PhD
4:45 | Add Pop-up | The beginning and end of every _MTL_ session has a “Done” and “Do” review | Swap Mushiana PsyD
5:20 | Add Pop-up | _Modeling to Learn_ VA partner Teams have a Microsoft Teams channel for meetings and asynchronous engagement | Swap Mushiana PsyD
7:25 | Add Pop-up | Each _MTL_ session has three learning objectives to facilitate learning | Lindsey Zimmerman PhD
15:20 | Add Pop up | Navigate to **mtl.how/data** for _MTL_ Data User Interface (Data UI) in Microsoft Power BI | Lindsey Zimmerman PhD
22:23 | Add Pop up | Zoom-in using the "data" tabs to view patient-level data and zoom-out using the  "viz" or visualization tabs to view team trends over time | Lindsey Zimmerman PhD
22:40 | Add Pop up | There are diagnoses (Diag), encounters (Enc), health factor data (HF), measures (Meas), and behavioral and suicide risks (Flag) tabs for **both** "data" and "viz" tabs  | Swap Mushiana PsyD
23:30 | Add Pop up | _MTL_ Data UI contains protected health information, so you will need your PIV card for access   | Swap Mushiana PsyD
24:50 | Add Pop up | _Trouble accessing MTL Data UI?_ Check Local Server View access, verify CPRS permissions, or reach out mtl.help@va.gov for assistance | Lindsey Zimmerman PhD
42:20 | Add pop-up | MTL participants receive Pre- and Post-session emails with “Done” and “Do” reminders | Lindsey Zimmerman PhD
43:20 | Add Pop up |  Review Clinic Selection and Team Flow Selection Tabs to build your clinic selections | Swap Mushiana PsyD
47:40 | Add Pop up | Looking ahead, review the five common care problems tabs along with each of the "descriptions" and "details" tabs for CC, MM, PSY, Team (AGG) Care, and Team (SP) Flow.  | Swap Mushiana PsyD

## MTL Blue 3.0 - Session 03 
Time | Correction Type | Description | Photo Name | Notes 
-- | -- | -- | -- |  -- 
0:53 | Add Pop up |  Modeling to Learn_ (MTL) Session 3 reviews five common care problems to help Teams understand how Veterans flow through care  | Swap Mushiana PsyD
7:28 | Add Pop up | Go to **mtl.how** for all _Modeling to Learn_ (MTL) guides and resources  | Lindsey Zimmerman PhD
9:20 | Add Pop up | The goal of _MTL_ Session 3 is to produce Team data for simulation for efficient learning and meet Veterans needs  | Swap Mushiana PsyD
11:35 | Add Pop-up | The _MTL_ “Done” and “Do” review bridges prior Team learning with the current session | Swap Mushiana PsyD
11:59 | Add Pop-up | Each _MTL_ session has three learning objectives to facilitate local team learning | Lindsey Zimmerman PhD
18:35 | Add Pop-up | The five _MTL_ common care learning modules include: Care Coordination (CC), Medication (MM), Psychotherapy (PSY), Team (AGG) Care, and Team (SP) Flow  | Swap Mushiana PsyD
18:49 | Add Pop-up | We use clinic selections to review common care problems relevant to team's learning priority | Lindsey Zimmerman PhD
30:22 | Add Pop-up | Review the "Descriptions" and "Definitions" tabs under each learning modules for additional information about team data | Lindsey Zimmerman PhD
31:05 | Add Pop-up | Data "Descriptions" and "Definitions" in the color red means read in from Team Data to the simulation model  | Swap Mushiana PsyD
34:26 | Add Pop-up | Complete the _MTL_ menu at **mtl.how/menu** to prioritize team learning in preparation for _MTL_ Session 4 | Lindsey Zimmerman PhD

**Comment by lzim** [comment]
@lijenn Will take a look at the table above and add any _Modeling to Learn 3.0_ pop-ups related to Power BI.
She will create a cross-referenced issue task card dependency.

**Comment by lijenn** [comment]
Hey @swapmush! Lindsey mentioned you were working on this in a Word Doc. 
**Knowing that this needs to be done before you both film, can you transfer your work to GitHub in this card so we can work on it together?**

Let me know if you need any help with formatting tables or with Markdown in general :)

You may find this Cheatsheet useful, specifically 'Tables' in the bottom 'GitHub Flavored Markdown' section:
https://enterprise.github.com/downloads/en/markdown-cheatsheet.pdf
![image](https://user-images.githubusercontent.com/59668647/160892724-9ea069a5-d371-4f19-b2cd-069613e99a83.png)

**Comment by swapmush** [comment]
Session # 3 - Pop-Ups

  Time | Correction Type | Description | Comments 
------- | ----------------- | ------------- | ------------
2:36  |    Add pop-up   |  MTL Data User Interface (UI) = mtl.how/data |
2:55     | Add pop-up   |   DELETE: "MTL Data UI - use Internet Explorer DELETE “Log in to mtl.how/data in Explorer”  |  SAY: Log into mtl.how/data in any browser (we can specifically mention edge, chrome,..) |
3:45     | Add pop-up   |    DELETE: “Create Team Data Table for Sim UI generates file with a tab for each MTL module" REPLACE: "Team data autogenerates into each tab under clinic selection"  |
7:35    | Add pop-up  |  DELETE: "Data UI has 1 folder with team data and 1 folder for Sim UI" | 
7:50    |   Add pop-up   |  "CC = Care Coordination Module"
10:50     |  Add pop-up    | "Red Text populates the Team Data Table in Sim UI"
11:20      |   Add pop-up   |  "MM = Medication Management Module"
13:45      |   Add pop-up   | “PSY = Psychotherapy Module   
16:10   |   Add pop-up   |  DELETE: "DataNotes – last tab in data UI file has good info for new MTL users!'' REPLACE: "Data for Sim UI tab has good info for new MTL users! |  Should this moved to later, after descriptors and details tab review?"
19:22    |   Add pop-up   |  EDIT: "Team Care (AGG) = Aggregate Mix of Services Module"
21:03     |   Add pop-up   |  EDIT: "Team (SP) Flow = Suicide Prevention Module"
22:31     |   Add pop-up   |  EDIT: "Pause & Review Info in Parameters descriptors and details for each MTL module.”
25:59     |   Add pop-up   |  DELETE: "Column E in the Params tabs provides add’l variable details"

**Comment by swapmush** [comment]
Session # 4 - Pop-Ups

  Time | Correction Type | Description | Comments 
------- | ----------------- | ------------- | ------------
2:50  |    Add pop-up   |  MTL.how/menu: staff survey to prioritize team needs |
6:05     | Add pop-up   |   EDIT: MTL Modules: Aggregate Services, Care Coordination (CC), Medication Management (MM), Psychotherapy (PSY), Team (AGG) Care, and Team (SP) Flow |
10:12     | Add pop-up   |  "MTL Module: Care Coordination (CC)" |
10:55    | Add pop-up  |  "MTL Module: Medication Management (MM)" | 
11:55  |   Add pop-up   |  “MTL Module: Psychotherapy (PSY)”
10:50     |  Add pop-up    | "Red Text populates the Team Data Table in Sim UI"
12:50    |   Add pop-up   |  EDIT: "MTL Module: Team (AGG) CareAggregate mix of services (AGG)"
13:45      |   Add pop-up   | “EDIT: MTL Module: Team (SP) Flow"
16:29   |   Add pop-up   |  "Over 12 sessions, MTL participants get 4 “team time” progress reports" |

**Comment by epearman** [comment]
@lzim @emilymetcalf114 - what do we want to do with Story C task cards for the time being? backlog?

**Comment by lzim** [comment]
As of **#2024_jan_epic**

#adjudicate_memo

The _MTL 3.0_ videos are live at https://mtl.how/ 
However, the OMHSP requested pivot from external implementation facilitation to consultation from Fall 2022 to Fall 2023 lead to the work with ILEAD to produce the enduring version of _MTL Video_ in St. Louis August of 2023.

This card can be closed.
