### ISSUE TITLE
wk4 mar_epic: Brainstorm Pop-ups for Session 2 for MTL Video 3.0

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2542]
@lijenn to help Brainstorm Pop-ups for Session 2 
 
 Larger Pop-Up Task for MTL 3.0 is #2541

**Comment by swapmush** [comment]
Session # 2

  Time | Correction Type | Description | Comments 
------- | ----------------- | ------------- | ------------
0:22     |    Add pop-up   |   ADD "Open the learner see guide at mtl.how" |
0:36     | Add pop-up   |   “Done” = What we did last or in between sessions |
0:49     | Add pop-up   |    “Do” = What we will do today |
0:56     | Add pop-up  |  “mtl.how/data is Data User Interface or Data UI” SAY: “…which is now in PowerBI. View the consortia map choose a tab scroll to your VISN. You can only see your own VISN.This access is via "Row-level security in Power BI." "Local server views at a data base level, which means that it's checking your permissions again VISN-level permissions on badge when the MTL Data UI shows you a Power BI Report. Some users may have issues with their permissions. If that happens to you, email mtl.help@va.gov."  |  If we have time, it would be great for a pop-up to SAY: “Email [mtl.help@va.gov](mailto:mtl.help@va.gov) if you have access issues.”

**Comment by lijenn** [comment]
@lijenn is providing support doing QA in the larger issue card #2541
