### ISSUE TITLE
wk4 mar_epic BUG Fix all TEST>PROD links and 2.0>3.0 denotations in PROD Documentation

### ISSUE THREAD

**Issue by mnallajerla** [lzim/teampsd#2543]
Hi @jamesmrollins 

Thank you for using FNR to replace all TEST links (ie, mtl.how/data_test and sim_test) and MTL 2.0 with 3.0. 

However, @lijenn and I discovered during QA that there are still TEST links and MTL 2.0 numbering in the Master PROD branch, where there should not be. 

Would you be able to look into this? I am manually fixing what I am catching but I don't think I will be able to grab all of them that way. Thank you!

FYI: @lzim

**Comment by jamesmrollins** [comment]
Hi @mnallajerla - Yes I had that problem too.  I am not sure why fnr is having trouble so I am looking into it. In the meantime, if you are inside the markdown document in edit mode, you can press cntrl-f and get a search window.  Type in your search term and it will highlight it in the document. This is what I did when prepping the blue 3.0 test to prod merge.

**Comment by mnallajerla** [comment]
@mnallajerla ran the FNR with @jamesmrollins help and the data_test and sim_test links are now fixed :) 

However, we do still need to correct for 2.0 > 3.0 Links. 

FYI @lijenn

**Comment by mnallajerla** [comment]
Hi @jamesmrollins & @lijenn - I took care of this for the PROD links, but the 2.0 outdated links might need some QA / fixing. Thank you!

**Comment by mnallajerla** [comment]
Hi @jamesmrollins - I think I fixed this before I left, do you think we can close this card?
