### ISSUE TITLE
ICEBOX: D365 Prod BUG - Copy and pasting Pre/Post Emails into Outlook distorts images and text, HTML code does not convert

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2546]
When was the bug discovered? 3/29/2022 at 10:30am Pacific in Facilitate Workgroup in _MTL_ CRM Production Environment 
Who discovered the bug? David, Lindsey, Swap, Jenn

We tried this as a workaround to #2465 

1. Copy and pasting Pre/Post Emails into Outlook distorts images and text
![image](https://user-images.githubusercontent.com/59668647/160674602-55d14fc3-7232-49a3-af97-5fa81e3806b7.png)

2.  HTML code does not convert
![image](https://user-images.githubusercontent.com/59668647/160674732-b99fb7e7-2480-424e-a438-99929e044bdc.png)

**Comment by hnorthcraft** [comment]
#adjudicate_memo updating to 1SP
