### ISSUE TITLE
wk4 apr_epic: STORY C - DEV   Blue Session 5-8 , Session 6 Add System Tracing 

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2558]
wk4 apr_epic: STORY C - DEV   Blue Session 5-8 , Session 6 Add System Tracing

**Comment by mnallajerla** [comment]
Closing this card as this work has been completed. See [Pull request 335](https://app.zenhub.com/workspaces/team-psd-workspace-5e4ac9bd8d388dfba6d9aef5/issues/lzim/mtl/335) on MTL for more info:
