### ISSUE TITLE
MTL Ver 1.7 Suicide Prevention - Test

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#257]
Good Evening Everyone!  Version 1.7 is now in test.  I encourage all to begin using it to identify any bugs.  We still have to deploy the export function and we have more "i" information Pop up mapping, **so no need to report those**.  Functionality appears to be working.  I am going to work with @TomRust to verify model data returns.  

To report a bug, use this issue thread.  Please do a screen capture and highlight the issue using the snip tool. Describe the problem by identifying where you found the issue (i.e., GMH Stepped Care or GMH Patients Waiting), what the issue is (i.e., "Patients misspelled").  Try to be as clear as possible, because I have to reconstruct the problem.  I will follow up if I have any questions.

**To keep things simple, use the logins below:**

Test URL: https://forio.com/app/va/va-psd-test/login.html
Team Lead >>
Username: testuser1
Password:  test123A

Player >>
Username: testuser2
Password:  test123A

**The model parameters file to use is shown below:**
![image](https://user-images.githubusercontent.com/30132017/48111344-f05ada80-e205-11e8-92c3-e2a34c609575.png)

**Comment by staceypark** [comment]
@jamesmrollins 
We are planning on building out several worlds for people to build systems stories and experiments for each of the 5 modules in preparation of MTL Video.

If we're all using the same single login, I imagine that we will have issues with users crashing and overwriting each other, but perhaps it is built in a way that it will not? Can you explain how this will work out?

**Comment by staceypark** [comment]
@lzim @dlounsbu @dlkibbe @branscombj @TomRust 

The demo groups for all 5 modules (cc, mm, psy, agg, and sp) have been built out in _MTL 1.7 Test_.
These will be used to prep sessions 5-10 for each module. 
**_Everyone is in the same world in here._**

There is another group called "va-test-group-may-2018".  
_**Everyone is in their own world in here. Feel free to test and play however you want in this one.**_

**Comment by lzim** [comment]
@staceypark

I didn’t get the conclusion of your exchange with @jamesrollins.

- are we using our own VA emails logins for the 5 module-based team worlds you set up in MTL 1.7 test?

@branscombj @dkibbe @dlounsbu @tomrust?

**Comment by staceypark** [comment]
@lzim @dlounsbu @dlkibbe @branscombj @TomRust
In regards to the username and password for _MTL 1.7 Test_, please continue to use the email and password combination you've been using until now for _MTL 1.6 Prod_.

@TomRust Thanks for sending the updated data file! 🎉 
They have been populated into the CC, MM, PSY, AGG, and SP module worlds for everyone. However, to put them in your individual worlds, in "va-test-group-may-2018", folks will need to add the data files yourselves as I don't have everyone's passwords.

You can add the file through the Team Data Menu Maintenance section: 100a1_abc_teama_2018_11_01.xlsx

also @TomRust for the SP demo module/story buildout, there were some helpful notes from today's process improvement group meeting that you may want to reference.  Sent you the direct path to your email, since we don't want to post VA paths on here.

**Comment by jamesmrollins** [comment]
@staceypark I have noted your bug, thank you.

**Comment by branscombj** [comment]
**_Can someone fill me in on what you have to do to earn a taco like @staceypark gave @TomRust above? - I would like one. Jane_**

**Comment by branscombj** [comment]
**Which data file did @TomRust provide/ you upload, @staceypark ?** 
From Lucid to-dos - Tom provide the data files to Stacey for our MTL 1.7 testing:

- STC for CC, MM, AGG
- PCT for PSY
- ADD a good SP

**Comment by branscombj** [comment]
@jamesmrollins There is some faint weirdness in the image I see here, using CC in 1.7 in MS Edge. Do you see it below the Our Question box and the line through text under Our Hypothesis? It's a sort of shadowing. AHHH: It's the part of the system diagram behind the Text section that shows through when I put my cursor in one of the text boxes. May be particular to this browser; but note above that this is the only browser that's working for me with 1.7.

![image](https://user-images.githubusercontent.com/29778290/48457341-590aff80-e790-11e8-8708-440a79c61ff1.png)

**Comment by jamesmrollins** [comment]
Hi @branscombj , I am running this on MS Edge and cannot see any issues.  To help us troubleshoot, please right click on your browser, choose "Inspect elements", and click on the "Console" tab (see red circle below) and screen capture all the messages.  This is where the browser logs any errors.  This may give us some clues as to what is affecting your build.

![image](https://user-images.githubusercontent.com/30132017/48459785-936ca080-e780-11e8-8ef3-d3765eb77229.png)

Thank you,
James

**Comment by branscombj** [comment]
@jamesmrollins , yes.

**Comment by branscombj** [comment]
@jamesmrollins Now I've switched to AGG. I closed the browser and reopened and signed back in (but I hadn't logged out of the sim UI) and here is my main page image and the console messages now up:
![image](https://user-images.githubusercontent.com/29778290/48460399-d2a8ea80-e79c-11e8-8a62-a47e5e594fac.png)
![image](https://user-images.githubusercontent.com/29778290/48460452-0c79f100-e79d-11e8-9116-f231a73376d2.png)
![image](https://user-images.githubusercontent.com/29778290/48460463-14d22c00-e79d-11e8-92e1-46a937a1a5fe.png)

**Comment by staceypark** [comment]
@jamesmrollins 
Several items incoming...
1. Patient load shadow variable on the default view needs i information.
2. GMH Stepped Care - Can the reinforcing loop Higher Care Quality Improves Recovery be moved to lower in the image under GMH Patients in Community Care 
3. Experiment timeline in the stepped care view is covering the model diagram
4. SP GMH Screen - Arrows coming out of care quality should minus.
5. SP GMH - Connection between GMH Effect of Patient Load on Care Quality to the GMH Care Quality should be a minus sign
6. In trying to produce a psy export file from _MTL 1.7 Test_ for Savet, I wasn't able to "Save & Reset".  Below are the errors produced.
![screen shot 2018-11-15 at 1 56 35 am](https://user-images.githubusercontent.com/31089501/48548886-09593080-e883-11e8-81c9-f08aaa949afc.png)
![screen shot 2018-11-15 at 2 59 18 am](https://user-images.githubusercontent.com/31089501/48548884-06f6d680-e883-11e8-8a7d-560388da36a2.png)

**Comment by TomRust** [comment]
@jamesmrollins 

I concur with these 4 changes to the SP UI:
1. On the Measurement Based Care/default view -- Add an "i" icon to the "Patient Load" shadow variable on the default/measurement base care view (we have that text, [here](teampsd/resources/master_crosswalk/info/SPModelInfo.md)).
3. On the stepped care view- Move the "Experiment Timeline" in the stepped care view so that it doesn't cover the model diagram
4. On the stepped care view- Change the polarity on the arrow pointing from "Care Quality" to "Time to Unflag High Risk Patients" (all arrows coming out of "Care Quality" should minus: as quality increase, the time patients are in either "have a flag" or "high-symptom" status goes down).
5. On the stepped care view - Change the polarity of the arrow connecting "GMH Effect of Patient Load on Care Quality" and "GMH Care Quality" to a minus sign.  (as the load increases, the effect goes up, and quality goes down)


@lzim I am confused by this one:
2. On the Measurement Based Care/default view - move the reinforcing loop "Higher Care Quality Improves Recovery" to lower in the image, under "GMH Patients in Community Care"

If the label is moved there, then it will no longer be inside the loop it is naming.

**Comment by jamesmrollins** [comment]
Added 4 items approved by @TomRust to tonight's push.  Will add last, pending @lzim comment.

**Comment by TomRust** [comment]
@lzim , @branscombj , @dlkibbe 

Sorry, but I don't understand the descriptions in the Lucid involving a connection between "Effects of MBC on Patient Symptoms and Risk" (which is just a view label, not an actual effect) and Patient Load.  Patient Load does not affect MBC.  They both affect "Time to Detect," "Time to Improve," and "Time to Unflag," but not each other.  The loop I thought we were trying to describe connects patient load, quality, number of "low symptom" patients, those low symptom patients leaving the setting, and the patient load.  MBC is not part of any loop.  It is an exogenous effect controlled by the user.  

How about this for the text for after we have explained the "Patient Load" variable: As care quality goes down [TOGGLE TO MEASUREMENT BASED CARE VIEW], then high-symptom patients improve faster than before (see the arrow to “Time to Improve” which affects the number of patients each week whose symptoms improve enough to be eligible to be stepped down to a less intense level of care), and 2) patients with high risk flags improve faster than before (see the arrow to “Time to UnFlag” which affects the rate at which patients with high risk flags have those flags removed). This causes more patients to flow into the “low symptom” group, so more patients can both end their care and be recommended to step down to a lower level of care.  [TOGGLE BACK TO STEPPED CARE VIEW] As more patients leave this setting, it further reduces the total number of patients in the GMH treatment setting, thus further decreasing the patient load and increasing quality.  When moving this direction, this type of reinforcing loop is often called a “virtuous circle.”  However, this feedback loop also works in the opposite direction, where small increases in patients can lead to lower quality, more patients staying with “high symptoms,” resulting in even higher patient load.  When this happens, this same loop is referred to as a “vicious circle,” or a “death spiral.”

**Comment by TomRust** [comment]
![image](https://user-images.githubusercontent.com/32961420/48584253-36dfc180-e8f7-11e8-8a0f-1bc02a79a540.png)

To me, it's clearer if this arrow (circled) is negative instead of positive.  Then we can explain the reinforcing loop "Higher Care Quality Improves Recovery" with: When "Care Quality" increases, the number of patients in the grey box labeled "Effect of MBC on Patient Symptoms and Risk" decreases (then users zoom into it to see how), which then decreases "Patient Load," further increasing "Care Quality."

**Comment by staceypark** [comment]
Got this error in Chrome in the Psychotherapy module

![screen shot 2018-11-15 at 10 36 29 pm](https://user-images.githubusercontent.com/31089501/48602314-9655c580-e927-11e8-8746-10f7901ecd99.png)

**Comment by jamesmrollins** [comment]
@TomRust @lzim  I didn't include any changes regarding the loops in tonight's push to give you two an opportunity to discuss and decide.  @TomRust when do expect to complete the "i" information for SP?

**Comment by jamesmrollins** [comment]
Hi @staceypark - we are currently editing the models in development, so you are likely finding errors because we are in the middle of updating.  James

**Comment by lzim** [comment]
@jamesrollins and @tomrust

Yes, changing the red circled plus on the arrowhead to a minus sign in Tom’s post solves it for me. Fine to leave the loop label where it is.

Okay @jamesrollins?

**Comment by jamesmrollins** [comment]
@lzim @dlounsbu @dlkibbe @branscombj @TomRust @saveth @staceypark @ericasimon the models are now at equilibrium at startup.  Kudos to DEV and especially David Berkman at Forio for sticking with us through the wee hours of the morning.  The models should now put out .xls files for exports, please help us verify that it meets your needs. I will add in the "plus" on the arrow head as indicated by @TomRust above by Monday morning.  If all is well through today, then I will promote the sims to PROD early next week (likely by Monday morning).  Thanks, James

**Comment by lzim** [comment]
Thanks to you @jamesmrollins :prince:  for all of your efforts to work with Dev and Forio to get this done!!
Amazing :trophy: !!!

@branscombj @dlkibbe @TomRust and @staceypark 

At HQ, @staceypark @ericasimon and I are working today on a mix of MTL tasks and IIR grant tasks. We are available for GitHub Reviews and/or questions anytime outside of our 9AM-10AM quant workgroup meeting with @saveth and @joycepyang 

Thanks ALL!!!

**Comment by TomRust** [comment]
@jamesmrollins : the iText is ready, and in this folder: [https://github.com/lzim/teampsd/tree/master/resources/master_crosswalk/info](https://github.com/lzim/teampsd/tree/master/resources/master_crosswalk/info)
Jane, Debbie, and Lindsey are going to review it Monday/Tuesday, and it should be ready to swap into the UI COB Tuesday.  Does that timing work for you?

--TOM

**Comment by jamesmrollins** [comment]
Thanks @TomRust.  **HERE IS THE PLAN:**  By Monday morning, I am going to check out and update the master crosswalk table with the "i" information @TomRust developed.  

@lzim @dlkibbe @branscombj  when you review the "i" information on Monday/Tuesday, please check out the master crosswalk table and edit directly in there, vice in the info table that Tom created. When you are finished, please let me know.

I will review the master crosswalk and ensure the pop up information links are still good, then I will update the Sim UI and test.

Thanks all!
James

**Comment by lzim** [comment]
LET ME DOUBLE-CHECK because I believe @jamesmrollins, @dlkibbe and @branscombj are all talking about turning to the "i" text tomorrow = SATURDAY.
So, I'm not sure if @jamesmrollins last post really will work.

Did you realize @jamesmrollins, that @dlkibbe and @branscombj would also be editing over the weekend?

If you're hoping to get a jump on migrating Tom's text to the Master Crosswalk we may need to leverage the time zone differences or something instead as an alternative workflow??

The goal was to get folks iteratively editing with version control in GitHub before we had to move into the serial editing that the Excel Checkout system requires here Master Cross-Walk - Check-out System #208 - https://github.com/lzim/teampsd/issues/208

Thoughts??

**Comment by jamesmrollins** [comment]
No worries - I can delay until Monday.  But I am enlisted into kitchen service starting Wednesday.  So I want to get all this settled prior to my turkey preparation operations (TPO).  😊


James Rollins

Managing Partner

Takouba Security, LLC.

1423 E. 29th Street, Suite 238

Tacoma, WA 98404

(425)919-5153[cid:afaf743c-ad24-461f-80e7-8146a541d61d]

www.takoubasecurity.com<http://www.takoubasecurity.com>




________________________________

**Comment by branscombj** [comment]
RVI slider in CC lists units of appt/wk - Should be **wks**.
![image](https://user-images.githubusercontent.com/29778290/48647636-8affaa00-e9ba-11e8-8b04-0019a9c46296.png)

**Comment by branscombj** [comment]
@jamesmrollins @lzim @TomRust Also the maximum RVI allowed is 16, so I can't increase it over the value in the data we're using.

**Comment by branscombj** [comment]
@jamesmrollins I am so sorry these are coming in so late! The order of the diagnostic cohorts (top to bottom) in the Experiment sliders in MM is not consistent.

![image](https://user-images.githubusercontent.com/29778290/48648964-1b3fee00-e9bf-11e8-9fb2-52e1c319e504.png)

**Comment by lzim** [comment]
@jamesmrollins @staceypark @branscombj @dlkibbe @TomRust @dlounsbu 

I was working in CC yesterday and I noticed that I also could not adjust the Referral Rate above the value that was reflected in the "BC" rate for an experiment of "What what would happen to our wait-times if we suddenly received an increased our referrals to CC?" 

The range of the estimated "BC" value exceeded the allowable slider range.

**Comment by jamesmrollins** [comment]
So @tomrust I need a new extended range, since earlier we couldn’t envision anyone exceeding 16 weeks.  Can we go up to 24 weeks?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by branscombj** [comment]
@TomRust @lzim @jamesmrollins 

No New Patient Wait Time output chart in MM, eh? Bigger question: What to make of these bc results? I see that Team Data Table Starting Rates are above the widget value for AUD, DEP and Other, and their results look like those shown in the first image. For OUD, the Team Data TAble starting rate = what's shown on the widget, and it looks like the second image. I've also pasted the results tables for AUD, OUD and DEP - Referral Rates in top row, Starting Rates in bottom row.

(The two "Alternatives" are both bc runs with Team Data Table ON; they just have different qhfd text as I tried to figure this out. But does it seem weird that Alt 2 doesn't have data showing in the table, and that the charts have Alt 2 results from -T(0) to T(0) and Alt 1 results from T(0) to T(2y)?

![image](https://user-images.githubusercontent.com/29778290/48674896-87d1fe80-eb1f-11e8-8d32-1503ab126ff5.png)

![image](https://user-images.githubusercontent.com/29778290/48674913-ac2ddb00-eb1f-11e8-92d9-234871c21aff.png)

![image](https://user-images.githubusercontent.com/29778290/48675028-66721200-eb21-11e8-947b-767b2e6df9e7.png)

**Comment by jamesmrollins** [comment]
@branscombj @TomRust @lzim Good Morning All. . .

Can you tell me what ModelParameters file you are using for your results?  I will verify returns in the desktop Vensim model later this afternoon.

New Patient Wait Time was not specified as an output chart, rather only as an "i" information variable.  It is currently mapped to the Vensim "Actual New Patient Wait Time" variable.  When I ran a base case in Vensim, "Actual New Patient Wait Time" returned a level value.  I will need @TomRust to advise if the variable would show any dynamic results, although I don't think so:

![image](https://user-images.githubusercontent.com/30132017/48675982-05444180-eb15-11e8-8b6e-84d9768b68e4.png).  

Regarding the second issue, I believe the "bc_oud_2018_11_16" issue is the operator forgot to run the model before saving the file.  This is possible at this point, because the model is technically run to "today" thereby satisfying the "save" function criteria that the model must be run first. I was able to repeat this error.  I will see about putting in a fail-safe.

Happy Sunday!
James

**Comment by branscombj** [comment]
Thanks, @jamesmrollins ! I'm running the data parameters file that @TomRust pulled together for our video use, which Stacey named 100a1_abc_teama_2018_11_01.xlsx and uploaded to all the 1.7 Test worlds we're using.

RE: the bc_oud_2018_11_16 run, I believe you are correct. However, **I am not sure if you should change the functionality**: It may be good to be able to update text, save, and not run yet in case you get interrupted before you finish thinking through the experimental settings you want to use. Granted, this risks the user saving a "run" they never actually Ran, with a name and text etc and results like those I showed (see below for "un-run" results alone). @lzim @dlkibbe @TomRust @dlounsbu your thoughts?

@lzim regarding the decision to not include a New Patient Wait Time output chart in MM: Maybe this makes sense because we're not really talking about "new" patients - only patients referred within the team - in MM, right? Still, there remains the same Referral/Wait Times dynamic, so I would have thought users would be interested in what wait times for different services are doing?

Results of a "run" that has been saved without ever hitting Run: shows behavior up to Time 0.
![image](https://user-images.githubusercontent.com/29778290/48676503-e013fb00-eb35-11e8-92c3-6d7ee114766b.png)

**Comment by branscombj** [comment]
@lzim @jamesmrollins @TomRust Unit label: Patients in MM, should be Patients not Pt/wk. 
![image](https://user-images.githubusercontent.com/29778290/48676728-cb853200-eb38-11e8-9074-89a4f5eb099b.png)

**Comment by lzim** [comment]
@jamesmrollins @dlkibbe @TomRust @dlounsbu @staceypark 

- **@TomRust are you able to help with the questions about the bc run and the Actual New Patient Wait Time?**

- **Re: Functionality @jamesmrollins I absolutely agree with @branscombj - We DO want to be able to save our work as we go, text entry, in particular before hitting run:**
>RE: the bc_oud_2018_11_16 run, I believe you are correct. However, I am not sure if you should change >the functionality: It may be good to be able to update text, save, and not run yet in case you get interrupted before you finish thinking through the experimental settings you want to use. Granted, this >risks the user saving a "run" they never actually Ran, with a name and text etc and results like those I >showed (see below for "un-run" results alone). @lzim @dlkibbe @TomRust @dlounsbu your >thoughts?

**Comment by branscombj** [comment]
@jamesmrollins here is another screen shot of the ["shadow lines" effect ](https://github.com/lzim/teampsd/issues/257#issuecomment-438522214)I'm seeing in 1.7 Test using Edge. I took a 2nd shot after scrolling the model diagram in the background up a little, so you can see that the lines in the text section are "coming through" from behind. 
These disappear when I drag the text window somewhere else, then reappear when I click to put my cursor inside one of the text boxes. The appear in different parts when I put my cursor in different boxes.

![image](https://user-images.githubusercontent.com/29778290/48677094-c971a200-eb3d-11e8-9ded-98a2d6f8e506.png)
![image](https://user-images.githubusercontent.com/29778290/48677098-d7272780-eb3d-11e8-9571-a1ad5ed9cf70.png)

![image](https://user-images.githubusercontent.com/29778290/48677138-6f251100-eb3e-11e8-9163-60bbbac418ca.png)
![image](https://user-images.githubusercontent.com/29778290/48677156-7d732d00-eb3e-11e8-8e9f-3bdd4fd1a4fd.png)
![image](https://user-images.githubusercontent.com/29778290/48677160-8c59df80-eb3e-11e8-8595-46b59aabb55a.png)
![image](https://user-images.githubusercontent.com/29778290/48677165-9380ed80-eb3e-11e8-86d7-ebfc613ce2f7.png)

**Comment by jamesmrollins** [comment]
@branscomb @lzim no worries on the mistake proofing. Now that you know what is going on, it is easy to spot the errors.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jamesmrollins** [comment]
@branscombj @lzim @TomRust   Regarding the MM model discrepancies between team data reflected in the data and the data showing in the widget, the widget values are consistent with the Vensim run on my pc using the same model parameters.  

![image](https://user-images.githubusercontent.com/30132017/48683903-1ff1d700-eb64-11e8-9fc8-f25171e59bb1.png)

![image](https://user-images.githubusercontent.com/30132017/48683917-326c1080-eb64-11e8-9be4-d91af9f471ef.png)

If the numbers need to be closer, then I believe a model adjustment may be necessary.

James

**Comment by jamesmrollins** [comment]
@brancombj - I'm not doubting what you saw, but I was not able to verify those units of measure errors you show in the MM charts.  Has this happened again, or was it just that one time? I am assuming you were in 1.7 Test, correct?

**Comment by branscombj** [comment]
Hey @jamesmrollins - I'm in 1.7 MM with tom and debbie and we see incorrect unit labels on 4 of these 6 charts:
![image](https://user-images.githubusercontent.com/29778290/48726324-fc2e9f80-ebfc-11e8-8b55-c1ecfaa87d29.png)
@lzim @dlkibbe @TomRust

**Comment by jamesmrollins** [comment]
@lzim @dlkibbe @TomRust @branscombj   This is weird indeed - look at my results below.  I think we need to capture the "inspect" code on the console.
**Pre-run**
![image](https://user-images.githubusercontent.com/30132017/48728655-612cca00-ebea-11e8-9b53-f9c09ecce188.png)

**Post Run**
![image](https://user-images.githubusercontent.com/30132017/48728793-d26c7d00-ebea-11e8-8a11-3eed180b7ab6.png)

Do the charts correct themselves at any point in your interaction with the SIM?  I think I have observed the same phenomenon, but then it corrects itself (somehow).  Have you witnessed similar?

James

**Comment by branscombj** [comment]
![image](https://user-images.githubusercontent.com/29778290/48729078-b4ac1180-ec04-11e8-8229-2af8628d19cf.png)

**Comment by branscombj** [comment]
@jamesmrollins @lzim New functionality issue - but fine for back burner, imo: When I pull up a previous experiment in order to use it as a starting place, I can't get out of that without Running. I tried going back to Select Experiment and "selecting" the default (no-run) row; and I tried Save-Discard. Only Run or Logoff worked. So the shortest way out currently is Run-Reset-Discard.

**Comment by lzim** [comment]
@jamesmrollins @branscombj I think that's new??

**Comment by jamesmrollins** [comment]
@lzim @branscombj  Yes, that is not a part of the original function.  It would have to be designed in.  I certainly agree that it would be an improvement.  I will add this to the 1.8 list.

**Comment by dlkibbe** [comment]
@jamesmrollins today @branscombj and @TomRust  and I were working on MM experiments. 
I exported the experiment file titled aswpxw_oud_50_aswpxw_other_31_rr_oud_5_utdsr_0_2018_11_19  

The Our Findings and Our Decisions text is switched in the Excel file that I exported.
![image](https://user-images.githubusercontent.com/31182258/48742420-e1741f00-ec2c-11e8-9860-bd9613f44719.png)

**Comment by lzim** [comment]
@dlkibbe that's an old error that I thought had been fixed. 

Right @jamesmrollins and @staceypark?

**Comment by jamesmrollins** [comment]
@dlkibbe @lzim @staceypark  I don't have a record of this as a bug.  Nevertheless, it is odd and I am trying to replicate.  Right now, it seems to work ok, for me. 

![image](https://user-images.githubusercontent.com/30132017/48743237-16757700-ec17-11e8-94c8-bf905e7672b8.png)

![image](https://user-images.githubusercontent.com/30132017/48743273-4a509c80-ec17-11e8-80f0-6dd09495b6e1.png)

I am going to take a look at those files that Debbie cites above and export it and see if I get the same issue. @dlkibbe  what group/world were you operating in, when this occurred?

Thanks,
James

**Comment by jamesmrollins** [comment]
@lzim  Pending any serious bugs, I plan to move 1.7 to PROD tomorrow night.  Let me know if you have any concerns.  Thanks, James

**Comment by lzim** [comment]
@jamesmrollins - that sounds good

@branscombj @dlkibbe @dlounsbu @TomRust are trying to get through the rest of the tests/session scripts tomorrow - Tues 11/20

As you complete them, let @staceypark and I know via Lucid, GitHub, or text.
I am reviewing SAY Files for clinical content as the Pull Requests come in.
@staceypark is re-running the sims and exporting them.

THANKS!

**Comment by branscombj** [comment]
@lzim @jamesmrollins Select Patient Cohorts section should not say PTSD (Other) - I think it should just say Other.

![image](https://user-images.githubusercontent.com/29778290/48783051-82a2ba00-ecad-11e8-8320-f20e358dbacb.png)

**Comment by lzim** [comment]
@jamesmrollins @branscombj @TomRust @dlounsbu @staceypark 

MM should not have PTSD, it should have AUD, DEP, OUD and OTHER.

Thanks!

Also, @branscombj and @dlkibbe I've been accepting Debbie's PR as they come in #282 and #285 ...
But, this morning Pull Request #284 came in with conflicts for the session 6 SAY file that I wasn't sure how to resolve, can one of you take a look?

Thanks :nerd_face:

**Comment by dlounsbu** [comment]
I noticed that some of the i information windows in the Experiment section are still just place holders.

**Comment by lzim** [comment]
Hi @dlounsbu  see if you can contribute to the "i" information review via the links and discussion at the Master Crosswalk issue #208 Thanks!

**Comment by staceypark** [comment]
@jamesmrollins There are two "GMH Patients Waiting to Start" in the Variable Dropdown list in the Results Dashboard.

![image](https://user-images.githubusercontent.com/31089501/48802735-f3090580-ecc4-11e8-87c1-e2d9872fd20a.png)


@jamesmrollins @lzim Our sliders for implementing MBC/Stepped Care are a scale of "None - Partial - Full".  How will we represent that in the save tile?  Will we teach to numbers "0 - 1- 2"? Or include another dropdown for this particular scale?

**Comment by jamesmrollins** [comment]
We should use 0=none, .5=partial and 1= full.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jamesmrollins** [comment]
@branscombj @lzim  Roger on MM model checkbox, will report to DEV and fix.

@staceypark  Have reported the double entry on the variable drop down to Dev.  Should be fixed by morning.  I am going to pass your MAC file onto DEV to see if they can learn why your MAC is having issues with download.  @lzim, does your MAC have issues doing .xls exports?

@dlkibbe We were not able to track down why we got mixed up results, regarding the text fields.  We are sure the variables are binding correctly in the code (see below).  If possible, would you repeat the same process again to create the experimental file and export, to see if the error occurs again?

![code](https://user-images.githubusercontent.com/30132017/48812906-468d4a80-ece9-11e8-81c2-4508944e00bb.png)

@lzim @TomRust @staceypark @branscombj @dlkibbe @dlounsbu @saveth   Version 1.7 will be live tomorrow on PROD.  Please begin using PROD and report any follow up bugs, if they should occur.  Last step is for me to do final variable to label alignment for model-popup-information and upload- is it ready?

Thank you,
James

**Comment by jamesmrollins** [comment]
@dlkibbe  Regarding the request above . . .  please disregard.  We found and fixed the bug.  While it was exporting fine from the save tile, it was reversed when exporting from the Home screen.

**Comment by dlkibbe** [comment]
@jamesmrollins thanks for fixing the export issue. I'm going into PROD now to work. 
@lzim are we keeping this same issue #257 for reporting on any bugs Version 1.7 PROD?

**Comment by lzim** [comment]
@dlkibbe @branscombj @dlounsbu @staceypark @tomrust and @jamesrollins

Yes, let’s continue to track here any issues in _MTL 1.7_ PROD

Thanks!

**Comment by branscombj** [comment]
@lzim @staceypark @TomRust @dlounsbu @jamesmrollins - 
@dlkibbe and I are working in the TEST version this morning because the worlds we're using to develop MTL Video scripts are not yet mapped to the PROD version. I can do that later but wanted to keep moving. If anyone has a minute to do that mapping, just let us know! Thanks!

**Comment by branscombj** [comment]
ps @lzim - I misspoke when I said i was hoping to have Wed and Thur off - I meant Thur and Fri! Just getting my days mixed up - I'd always planned on working today. So.. I am! But I can carve out some time after tomorrow too for a rehearsal. Even if just you and me for a couple of the sessions I co- with you.

**Comment by dlounsbu** [comment]
@branscombj @lzim @dlkibbe @staceypark I am working today as well, but I need to split my time between MTL and a grant proposal to HRSA (a 'Healthy Start' competitive renewal that happens to be due next week).

Please ping me with anything that you need regarding editing say scripts, etc.

**Comment by staceypark** [comment]
@jamesmrollins By the way, I tested exporting from Safari on my Mac.  It gives me .xls correctly. Chrome still gives me the TextEdit Documents

**Comment by lzim** [comment]
@staceypark Where are we with this? I wasn't sure when I talked to @jamesmrollins earlier in the week.
