### ISSUE TITLE
Done wk4 apr_epic: Story E RECORD Lindsey and Swap - VIDEO Blue  Session 1

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2597]
Story E RECORD Lindsey and Swap - VIDEO Blue  Session 1
Posted Video and Timestamps for EES on 04/27/22

@lzim Note on data validity per meeting at overflow on Wed 04/27/22
- [x] Added Swap as Assignee
- [x] Changed the story points to reflect 5 points each for 10 story points total.
- [x] Included both development and operations label since the new videos series is in support of the _MTL 3.0_ major release.

**Comment by lzim** [comment]
Recorded s1 team_vision 04/25/2022
@swapmush will update the **s1 pop-up table with accurate timestamps**: https://github.com/lzim/teampsd/issues/2541 and alert the **ees_workgroup** on Teams when it is ready.

**Comment by lzim** [comment]
@lzim notified EES that this video is recorded and timetamps identified on s1 topic of ees_workflow 04/27/22.
