### ISSUE TITLE
apr_epic wk TBC sim_ui feature:  Hard to see which world I'm in (individual, shared, team)

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2606]
When I was asked to safe or discard, I scanned the screen to tell which world I was in. Although it may be a little hard to tell this due to redacting team details, if you look at the screenshot in the upper left by the **home button** with the responsive design and truncated name, I can see I'm logged in as a facilitator [yellow highlight], but **I could not tell, which world I'm in (individual, shared, team).**

FYI for consideration at **8AM Workgroup Leads** @lijenn & @jamesmrollins  
![sim_ui_world_view](https://user-images.githubusercontent.com/7454688/162504102-917919f0-5539-429c-934f-e38448c47aaa.PNG)

**Comment by jamesmrollins** [comment]
FYI @hirenp-waferwire 

Hi @lijenn and @lzim.  This should be an easy fix.

![image](https://user-images.githubusercontent.com/30132017/162865353-73826f16-4f16-4cd3-aec7-871baad02f06.png)

**Comment by jamesmrollins** [comment]
Hi @lzim and @lijenn See the fix below that makes plain which world you are saving in:

![image](https://user-images.githubusercontent.com/30132017/163248654-7aad7235-f737-468c-a8a1-5806d15fa43f.png)
