### ISSUE TITLE
wk4 apr_epic   BUG SIM UI: Team Set up did not create shared world. 

### ISSUE THREAD

**Issue by swapmush** [lzim/teampsd#2616]
**Sim UI PROD: Swap tried to set up a team as facilitator, but it only created an individual and team world, not a shared world.** 

<img width="821" alt="SimUI_bug" src="https://user-images.githubusercontent.com/23065779/163902244-a7c1230c-4034-447f-a3e0-bbd395ce73a8.png">

1. MTL 3.0 Video Recording Meeting on Monday at 6pm. Discovered with LZ, Swap, and Jenn.  
2. Shared world

**Comment by jamesmrollins** [comment]
FYI @swapmush 

Hi @hirenp-waferwire - Please see below.  The team creation function is not creating a shared world.  Please investigate and correct.  

![image](https://user-images.githubusercontent.com/30132017/164103008-4ed0c1da-8b8a-47a0-9ee8-d4cdf3a0ef1e.png)

**Comment by lijenn** [comment]
Thank you! I tested and looks like it's working.
