### ISSUE TITLE
wk1 may_epic Course code for Dr. Fort Class 

### ISSUE THREAD

**Issue by mnallajerla** [lzim/teampsd#2621]
- [x] Create course code for Dr. Fort's Class -  #cu_fort_2022

- [x] QA Chapter in MTL Manual on creating course code

**Comment by mnallajerla** [comment]
### QA on Course Code Instructions in [MTL Manual (Chapter 10.3.3)](https://lzim.github.io/mtl/10-simulation-user-interface-sim-ui-administration.html#update-course-code)

Hi @jamesmrollins & @lijenn - 

My task was to create a course code for an upcoming presentation Swap is doing for Dr. Meredith Fort. In the process, I was to QA [Chapter 10.3.3 in the MTL Manual](https://lzim.github.io/mtl/10-simulation-user-interface-sim-ui-administration.html#update-course-code) on updating course codes.

This chapter looks incomplete to me, or like some type of error occurred, because the information is missing (instead of having a graphic, the instructions just say "Overview graphic" etc - please see below):
![image.png](https://images.zenhubusercontent.com/6130066bf230e9289f9a2c0c/162d9775-6dd5-4a43-bf9c-3ea30975c194)

**Comment by jamesmrollins** [comment]
Hi @mnallajerla 

I interpret your checklist above as you were able to complete the task, despite my lacking instructions.  If not, let me know and I can correct.  I will investigate what is going on with the rest of it.

**Comment by jamesmrollins** [comment]
Hi @mnallajerla 

## The graphic links are broken.  These will be fixed pursuant to our Training priorities.

![image](https://user-images.githubusercontent.com/30132017/166960873-2fddadaf-45ca-4b1e-87d7-ed7c7be4b0a3.png)

**Comment by mnallajerla** [comment]
Thank you so much @jamesmrollins . Please let me know when it is fixed, or if you are tracking this task elsewhere. We can close this card once it's been fixed. Thank you!
