### ISSUE TITLE
apr_may_jun Story C MTL Video 3.0 Internal Pop-up Timestamps

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2644]
# _Modeling to Learn Video 3.0_ 

Cross-ref last video series #748
Cross-ref EES Tables on ees_workgroup #2541 

### Internal

Time | Correction Type | Description
-- | -- | -- 
0:41 | Add Pop-up | Go to mtl.how for all Modeling to Learn (MTL) resources |
3:25  | Add Pop-up | Click the "TMS" link for each MTL session to receive continuing education credits for VHA providers |
5:09 | Add Pop-up | The beginning and end of every MTL session has a “Done” and “Do” review |
8:59 | Add Pop-up | MTL Session 1 Goal: Integrate “Your Vision” with the “Team Vision” | 
10:13 | Add pop-up | Hit pause. Write down characteristics of a good learning experience |
12:45 | Add pop-up | Hit pause.  Write down your "best-case" scenario for team learning |
22:55 | Add pop-up | MTL participants receive Pre- and Post-session emails with “Done” and “Do” reminders |

**Comment by swapmush** [comment]
## MTL 3.0 Blue - Session 01 
### Internal
Time | Correction Type | Description
-- | -- | -- 
0:41 | Add Pop-up | Go to mtl.how for all Modeling to Learn (MTL) resources
3:25  | Add Pop-up | Click the "TMS" link for each MTL session to receive continuing education credits for VHA providers. 
5:09 | Add Pop-up | The beginning and end of every MTL session has a “Done” and “Do” review
8:59 | Add Pop-up | MTL Session 1 Goal: Integrate “Your Vision” with the “Team Vision”
10:13 | Add pop-up | Hit pause. Write down characteristics of a good learning experience. 
12:45 | Add pop-up | Hit pause.  Write down your "best-case" scenario for team learning.
22:55 | Add pop-up | MTL participants receive Pre- and Post-session emails with “Done” and “Do” reminders
