### ISSUE TITLE
wk1 may_epic simUI Bug: MM Module PROD "Engagement Duration" in model diagram needs to be card stack icon

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2649]
@jamesmrollins 

Was working through MM in PROD w/@swapmush and @lijenn today and found that Engagement Duration in the model diagram doesn't have a card stack icon for multiple presenting concerns. It should. Thanks!

![image](https://user-images.githubusercontent.com/7454688/166755644-5ba185e9-99d2-40ed-affc-b8b1730a2ba5.png)

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire - Please make the correction noted below.


## Engagement Duration needs to be a stacked icon

![image](https://user-images.githubusercontent.com/30132017/166792963-3536aeb7-096a-4794-b1b6-553e89c89335.png)

## Example stacked icon

<img width="334" alt="image" src="https://user-images.githubusercontent.com/30132017/166790684-d43925c2-becb-4209-a125-19c98a89e749.png">
