### ISSUE TITLE
wk2 may_epic Story H & Story I: mtl.how/team - Edit to reflect recruiting for Workstream Leads & Re-org Workgroup to reflect Team PSD 3.0 Workflows

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2651]
@jamesmrollins 
@lijenn 
@mnallajerla 

Consistent w/**Story H - Hiring** and **Story - Training**
We'll discuss at tomorrow's 05/04 TRAIN.

We need to re-organize https://mtl.how/team to reflect our Workstreams and Workflows _while we're recruiting_
Cross-ref #2617 

Workflows are labeled under each Manager Workstream
https://lucid.app/lucidchart/0cd93668-a02d-4176-b97d-4f342985a57f/edit?page=0_0&invitationId=inv_89386cd8-aa97-4ee2-9c18-371e4a2b7781#

**Comment by jamesmrollins** [comment]
@lzim @mnallajerla @lijenn 

## Please Find the Chapter Guide Below

Please note the chapter 9 files are messed up, so H2's will need to be fixed


|Chapter|Title|
|---|---|
|1|"index.Rmd",|
|2|"use_and_contribute_to_teampsd_manual.md",|
|3|"standard_operations.md",|
|4| "shared_workstreams_across_management_trio.md",|
|4.1|"manage_teampsd_vha_worflows_via_teams_and_outlook.md", |
|4.2|"edit_guide_via_pull_request_and_plan_dev_test_prod_quality_assurance_sync.md",|
|4.3|"improve_teamPSD_manual.md"|
|4.4|"manage_oulook_shared_calendars_and_meeting_series.md,"|
|4.5|"improve_mtl_3_manual.md",|
|4.6|"scope_workflow_dependencies_using_user_stories_and_zenhub_github.md",|
|4.7|"coordinate_train_workflow.md",|
|4.8|"onboard_new_team_member_to_va.md",|
|4.9|"hire_a_new_team_member_through_pavir.md",|
|5.0|"co_coordinated_workstreams_r&d_dataops_devops.md",|
|5.1|"manage_research_repository_including_readme.md",|
|5.2|"request_new_research_data.md",|
|5.3|"submit_vaco_and_vapahcs_progress_report.md",|
|5.4|"contribute_to_teampsd_manuscript.md",|
|6|"research_and_development_workstreams.md",|
|6.1|"manage_research_and_development_workstream.md",|
|6.2|"achieve_research_value_stream_kpi.md",|
|6.3|"manage_research_calendar_and_mtl_info_inbox.md",|
|6.4|"coordinate_manuscript_monday.md",|
|6.5|"coordinate_team_time.md",|
|6.6|"send_provider_surveys.md",|
|6.7|"renew_or_modify_irb.md",|
|6.8|"submit_nih_grant_with_pavir.md"|
|6.9|"submit_grant_to_va.md",|
|6.10|"manage_authorship_app.md",|
|6.11|"manage_manuscript_tracker.md",|
|6.12|"submit_peer_reviewed_manuscript.md",|
|6.13|"send_stanford_qi_course_evaluations.md",|
|7|"dataops_devops_workstreams.md",|
|7.1|"manage_dataops_and_devops_workstream_permissions.md",|
|7.2|"achieve_development_value_stream_kpi.md",|
|7.3|"manage_va_contracts.md"|
|7.4|"sync_bug_tracker_progress_to_squash_teampsd_and_research_bugs.md",|
|7.5|"sync_feature_tracker_progress_to_develop_teampsd_and_research_features.md"|
|7.6|"coordinate_code_review.md",|
|7.7|"update_r_notebook.md",|
|7.8|"improve_msd365_integration.md",|
|7.9|"refresh_data_r01_or_iir.md",|
|7.10|"update_vensim_model.md",|
|7.11|"update_sim_ui_module_document.md",|
|8|"peopleops_workstreams.md"|
|8.1|"manage_peopleops_workstream_permissions.md",|
|8.2|"achieve_operations_value_stream_kpi.md",|
|8.3|"manage_operations_calendar_and_inbox.md",|
|8.4|"coordinate_vapor.md",|
|8.5|"engage_new_mtl_coplanning_group.md",|
|8.6|"setup_new_mtl_live_team.md",|
|8.7|"facilitate_mtl_live_team.md",|
|8.8|"organize_mtl_facilitate_for_all.md",|
|8.9|"purchase_through_reqlogic.md",|
|8.10|"coordinate_ees_workflow.md",|
|8.11|"coordinate_all_hands.md",|
|8.12|"coordinate_non_research_external_partners.md",|
|8.13|"orient_team_members_to_documentation_using_document_archive.md",|
|9|"teampsd_2.0_monthly_process.md",|
|9| "teampsd_monthly_process_week_3.md",|
|9|"teampsd_monthly_process_screencast.md",|
|9|"teampsd_monthly_process_youtube.md",|
|9|"week_4.md",|
|10|"va_citrix.md",|
|11|"ms_teams.md",|
|12|"open_science_framework.md",|
|13|"lucidcharts.md",|
|14|"github_+_zenhub.md",|
|15|"manage_with_zenhub.md",|
|16|"track_issues_and_features.md",|
|17|"glossary.md"|

**Comment by hnorthcraft** [comment]
#adjudicate_memo Heather attempting best estimate at SP.
