### ISSUE TITLE
wk2 may_epic Story I: Add content to 3.0 Workflow in the Team PSD Manual

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2658]
- [x] Add content to work completed in #2617 

- [x] QA content @jamesmrollins added and ask questions by Wednesday, 5.11.22

**Comment by mnallajerla** [comment]
Completed edits to R&D workstreams this afternoon. Thank you!

**Comment by mnallajerla** [comment]
@jamesmrollins (for when you are back in office) - I think this card may be good to close?

**Comment by jamesmrollins** [comment]
I think so. We still have to do a video tomorrow for how to update Team PSD gh-pages manual.

**Comment by mnallajerla** [comment]
@jamesmrollins  - Yes! and I think that is tracked on #2617 LucidCharts Workflows. I am closing this card. Thank you :)
