### ISSUE TITLE
wk4 may_epic Story I: Train Fix documentation for making course code

### ISSUE THREAD

**Issue by mnallajerla** [lzim/teampsd#2659]
Transferring @jamesmrollins component of the work from #2621 to track here. Thank you!

> 

## The graphic links are broken.  These will be fixed pursuant to our Training priorities.

![image](https://user-images.githubusercontent.com/30132017/166960873-2fddadaf-45ca-4b1e-87d7-ed7c7be4b0a3.png)

**Comment by lijenn** [comment]
#ajudication_memo: Jenn confirms that she sees the broken course code documentation images have been fixed via https://lzim.github.io/mtl/8-admin-technical-manual.html#update-course-code. Closing issue!
