### ISSUE TITLE
wk3_may: Update Team PSD website

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2661]
## Update Team PSD website

- [x] Incorporate new workstream/workflow architecture for maps and team organization.
- [x] Add a new feature for employment opportunities.

**Comment by jamesmrollins** [comment]
FYI @lzim @mnallajerla @lijenn 

## User Information from Google Analytics

1.  Total Visitors over Last 90 Days

![image](https://user-images.githubusercontent.com/30132017/167671181-661918ba-6c24-4220-9729-f50b1ab04fff.png)

2. Source of Visitors over last 90 Days

![image](https://user-images.githubusercontent.com/30132017/167671276-a4d1afc4-65f6-4b0c-8fc6-8962627bf8d7.png)

3. Results of Bing Search for "Team PSD"

- The GitHub repo is in the top 3
- The Team PSD website is not listed, likely due to the url.

![image](https://user-images.githubusercontent.com/30132017/167671649-03c97c14-50fa-4895-98ef-9b213aa53b05.png)

![image](https://user-images.githubusercontent.com/30132017/167671836-c61aa6ed-487e-4962-af7f-890ca26ec780.png)

4.  Pros and Cons

Pros
- Providing a link in employment websites to Team PSD, may increase visit rate.
- Alias of the Forio webserver that uses the term "Team PSD" my increase search and visit rate.  I dunno, just thinking out loud here.
- Continue promoting through various briefings and presentations (likely the source of visitors to date).

Cons
-  Not much bang for the buck in terms of pulling in potential applicants.

**Comment by jamesmrollins** [comment]
@lzim @lijenn @mnallajerla 

# Rapid Prototype

![image](https://user-images.githubusercontent.com/30132017/167676708-504de152-edcd-4471-bcb2-ee978b932648.png)

**Comment by lzim** [comment]
Great, thanks @jamesmrollins 

Thanks for this work on and this and the design prototype!
Let's touch base about the https://mtl.how/team website re-design at **Team Train tomorrow at 10AM**.

**Search Engine Management (SEM):** Let's discuss the Bing and Google Management 
- Added SEM as a workflow on **[Story I Train Workflow Inventory](https://lucid.app/lucidchart/0cd93668-a02d-4176-b97d-4f342985a57f/edit?invitationId=inv_89386cd8-aa97-4ee2-9c18-371e4a2b7781&page=0_0#)**

**Google Chrome** - Same searched for "Team PSD" from my VA machine - Not too bad a return of this halfway down my page.
- Notably: GitHub did _NOT_ return on the page via Google Chrome.
![image](https://user-images.githubusercontent.com/7454688/167962929-fb3c7402-9c26-4463-9f49-ed440245cb14.png)

**Team PSD Site Design Prototype:** 
- Wasn't thinking of hiring announcements as a pop-up. 

- [ ] Would like an new editable section under the map for announcements w/links.
- [ ] Would like to add section for **PI and new management trio.** To orient everyone.  
- [ ] Want to reorganize the page to reflect incoming Managers' _workstreams_ of interrelated _workflows_ as covered in **team_workflow channel** and on **Story I Inventory** (LucidCharts) above. 
   - Need to think this through design together a bit more tomorrow.

Thanks again!

**Comment by lzim** [comment]
BTW: Searching for "Team Participatory System Dynamics" is returning several relevant resources from the team. And, key colleagues work too. 

But, check out this interesting thing in Google's Search Engine from the **D&I Academy Health Workshop** @TomRust  and I gave, which they posted to YouTube:

![image](https://user-images.githubusercontent.com/7454688/167964214-062c48b7-17b5-47c1-8835-bced32a9a1ee.png)


FYI: @mnallajerla & @lijenn

**Comment by jamesmrollins** [comment]
@lzim @lijenn @mnallajerla   Below are notes regarding the Team PSD up-design:

- [ ] Can we somehow simplify or graphically represent the landing page?  The text as presented is dense and not visually appealing.
- [ ] Would like to add position titles to the picture captions on the national maps,  and to the individual bios in the supporting sections. 
- [ ] Recommend three maps, one for each value stream, instead of one for each workflow. Three maps will load faster than 4 or 5 and accomplish communicating who is doing what.
- [ ] Hiren is available next week to make the desired changes.  I will still need to add the input admin screens to the wireframe before next week to make that happen.
- [ ] Need some ideas for award icons or logos and the actual award text of the first two winners by the time we implement.

**Comment by lzim** [comment]
@jamesmrollins  
@lijenn  and I huddled and made this DECISION about the color ways moving forward: 

**_We will default to describing the value streams in this order_** 
Research -> Dev -> Operations

We will uses these 4 colors for 4 maps (Red will go unused for now)
**Research** - Green
**Development** - Light Blue
**Operations Partners** - Purple (EES, OMHSP, VAPOR)
**Facilitate** - Navy

![image](https://user-images.githubusercontent.com/7454688/169158286-c74530db-a580-4776-850c-9a6b78cf638d.png)

**Comment by lijenn** [comment]
@jamesmrollins, @lzim and @lijenn also discussed that we need to get the color standards documented the same across these cross-cutting resources, we already fixed it on LucidCharts templates:
- [ ] https://github.com/lzim/teampsd/blob/gh-pages/stylesheet_colors/colors.md
- [ ] The Team PSD Manual
- [x] LucidChart Template

**Comment by lzim** [comment]
**Updates based on training_workflow 05/19/22**

**EDITs to Award Section**
- Finalize icons
- Definition
- Past Awardees (will ADD what received award for in that year)

**"Team Award" for helping the team to achieve more than the sum of our parts.**
2020 - Stacey Park
2021 - Jenn Li & David Ngendahimana, PhD

**"Values Award" for innovating to help the team realize participatory values.**
2020 - Jenn Li
2021 - Geoff Hoerle

*Made live edits to the Workflows*

**DECISION:**
Alumni - RED

![image](https://user-images.githubusercontent.com/7454688/169377302-1b3ea671-785d-49ea-8538-8046be609815.png)

**Comment by jamesmrollins** [comment]
For your approval @lzim @lijenn @mnallajerla 

# Team PSD Award Winners

- [ ] Does the award medallion meet with expectations?
- [ ] Does the award explanations meet with expectations?

<img width="395" alt="image" src="https://user-images.githubusercontent.com/30132017/169415321-a7ac4249-3ca9-4778-8f0c-4a3a49285e6a.png">

**Comment by jamesmrollins** [comment]
For your approval @lzim @lijenn @mnallajerla 

# Incorporating "What we do?"  with sections

- [ ] Does this idea meet with expectations.
- [ ] Will require light redesign of the logos to match up with new schema.

<img width="413" alt="image" src="https://user-images.githubusercontent.com/30132017/169415553-5a0b461b-602f-4a10-b225-3196c8d5ecfc.png">

**Comment by lzim** [comment]
@jamesmrollins 

For the medallion, I'd like the "Team PSD to be small" and the "Values" or "Team" to be large on the medallion icon.
I want to be able to see at a glance "Values" or Team" on the page to distinguish them. 
With Team PSD largest the team and values awards look the same at a glance.

Also, I do not like the wordiness for the written out text, I prefer the succinct text provided for the medallion: 
"Team PSD team award for helping the team achieve more than the sum of our parts."
"Team PSD values award for innovating to help the team realize team participatory values."


> For your approval @lzim @lijenn @mnallajerla 

> # Team PSD Award Winners

> - [ ] Does the award medallion meet with expectations?
> - [ ] Does the award explanations meet with expectations?
> - [ ] If you have any bling money left, you could make challenge coins with this design.

<img width="395" alt="image" src="https://user-images.githubusercontent.com/30132017/169415321-a7ac4249-3ca9-4778-8f0c-4a3a49285e6a.png">

**Comment by lzim** [comment]
@jamesmrollins 

Please go with Alternative 1. 
I see where you were going with your recommendation of Alt 2.
But, I do think scrolling quickly to find someone, **Alternative 1 is clearest.**

**Comment by lzim** [comment]
NOTE @jamesmrollins: Please grab the latest _MTL 3.0_ descriptions from the workflow channels on Teams.
Thanks!

**Comment by jamesmrollins** [comment]
Regarding updated workflow descriptions above - this will require an update of text at the dashboard level during deployment.

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire - we are approved to develop the Team PSD 3.0 website.  I will send reference files to you via email as they are too big for this repository.

**Comment by jamesmrollins** [comment]
@lijenn @lzim - none of the logos for the "What We Do" section are in the resources/logos folder of the lzim/teampsd repo.  **Do we know where these are located?**

Hi @hirenp-waferwire - Please find initial edits below.  I will continue configuration and testing tomorrow.  

## Improvements for Team PSD Award Winners Section on Admin Panel

- Medallions look good!
- See below for changes to admin panel.

![image](https://user-images.githubusercontent.com/30132017/172259082-265992fa-3495-4ed7-a6c6-6b528ac14b9e.png)

## Team PSD News Section on Admin Panel

- When deleting articles, the undeleted articles do not relist.  Is corrected when screen is refreshed.
- Can we add in the picture framing feature to help fill the entire photo space correctly?

![image](https://user-images.githubusercontent.com/30132017/172260259-99c1908f-b055-4714-b9c6-60aabb7d7ddf.png)


![image](https://user-images.githubusercontent.com/30132017/172260727-3003d39c-e3d9-4393-a85a-9fa64b14b040.png)

## Change all Instances of "Workgroup" to "Workflow" 

![image](https://user-images.githubusercontent.com/30132017/172260811-d41d3c2f-254b-4d01-a87b-a16ff828d127.png)

## Add a "None" Selection to Section dropdown.

![image](https://user-images.githubusercontent.com/30132017/172263420-466ccf2d-d7b0-4961-be40-821a93e3a999.png)
 
## Can We Freeze Frame the First Row of all the Admin Matrices?

![image](https://user-images.githubusercontent.com/30132017/172263555-2bb396c6-f94e-4adf-8b1f-58d90e68b754.png)

## Change Header Name for Colors

![image](https://user-images.githubusercontent.com/30132017/172263920-9e8df186-e62a-4825-959d-344a4b8e56b8.png)

**Comment by lijenn** [comment]
@jamesmrollins The "What We Do" logos are located in [Resources/Workgroups](https://github.com/lzim/teampsd/tree/master/resources/workgroups) of lzim/teampsd!

**Comment by jamesmrollins** [comment]
Awesome! Thanks @lijenn

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire - Here are tonight's issues.

## Complete Slider Issue

## Alphabetizing award winners appears inconsistent in the case shown below.

![image](https://user-images.githubusercontent.com/30132017/172960330-0e462bc2-2b0e-46a1-9509-af006f021aef.png)

## Check font sizes for all colors.  The subheadings should be the same size as the Light Blue

![image](https://user-images.githubusercontent.com/30132017/172960570-2407161b-b2e8-4ac0-b748-7cf7368c8b71.png)

## No need for years this far back.  Will this menu update to add new years as we get older?

![image](https://user-images.githubusercontent.com/30132017/172962126-c7c5c681-a5e9-4066-a0f8-3f3f89ee0c35.png)

## Team PSD Leaders section not working

- To add a new biography, one must first select a section and then "Add Member"
- Then add in the "Team PSD Leaders" division selection
- In this use case, we likely need a standing "Team PSD Leaders" section or allow record creation without a section choice, then allow the choices in the row. When a person selects the "Team PSD Leaders" division, the section becomes null.

![image](https://user-images.githubusercontent.com/30132017/172962860-21a6f5cb-46d9-45f2-beb7-9da4d7a8a049.png)

## May need to specify the origin of biographic data records as by either "section" or "division" on the Map Slider section.  Because "Facilitators" is a section, and the rest are divisions.

![image](https://user-images.githubusercontent.com/30132017/172965665-c5ea40af-ef67-4840-a855-4ac3bb37b243.png)

## Small issue with "Add" icon and freeze row

![image](https://user-images.githubusercontent.com/30132017/172963124-4e18eb01-5559-4551-a454-9eebf255b229.png)

## When adding a new member or new resource, the new row appears under the freeze row

![2022-06-09_16-50-58](https://user-images.githubusercontent.com/30132017/172963484-5ca2f2e7-bb56-43e6-8893-8a17859efc7e.gif)

**Comment by jamesmrollins** [comment]
Hi @lzim - we will likely need to add one more map to place the Team PSD leaders.  The Webpage builder is now organized to apply people by division to the different maps (it used to be by section). Recommend light green.

![image](https://user-images.githubusercontent.com/30132017/172965193-397303a3-71d8-4817-93ad-f46113d1a347.png)

**Comment by jamesmrollins** [comment]
@lzim we are making progress.  However, we have many thorny technical issues building in the admin flexibility around sections and divisions as they are displayed on the webpage. Further, we are encountering issues getting the map slider to move correctly (this is a long standing issue).  I am hoping to have this ship-shape by next week.  Sorry for the slow progress, @hirenp-waferwire is pretty slammed this month with several projects.

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire - Below are changes to Team PSD website and Admin

## Website
- Please center the logo over the block of text as is on PROD (See image 2 below)

![image](https://user-images.githubusercontent.com/30132017/175189238-0dd24afc-c06f-4c36-a5bc-737d2bca4b84.png)

- PROD
![image](https://user-images.githubusercontent.com/30132017/175189326-62f7ef9f-4462-4e7f-80d6-ff18f611c202.png)

### Change text in the website's "Easter Egg"

> You must be someone who likes to see how things work. If you're interested in improving healthcare, consider joining our team! Email us at  [mtl.info@va.gov](mailto:mtl.info@va.gov) and put "Team PSD Easter Egg" in the subject.

![image](https://user-images.githubusercontent.com/30132017/175189914-9a65a9e8-2e7b-410f-9cac-c2f56df1e3a0.png)

## Admin Panel Bio Section

- Please rename "Division" to "Value Stream" in the header row.
- When refreshed, page should reorder biographies by "Value Stream" then "Workflow" then "Sequence number"

![image](https://user-images.githubusercontent.com/30132017/175165938-79b43ce1-a4ef-4a7d-af46-ced9ecc480a6.png)

## For James Only

- Use light grey on the Team PSD Leaders map.
-  Only use title for Team PSD Leadership. All else have a role on the team.
-  Use light dark blue on the  (until we develop a white font capability)
- Change Lindsey's title to "OMHSP MTL Lead and Principal Investigator"

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire - Just a couple more refinements:

## Please change the heading highlighted below to "Value Stream" and "Workflow" respectively.

![image](https://user-images.githubusercontent.com/30132017/175432722-dd1f86e8-ddcd-4db4-9d2d-d2524fcc83e5.png)

## Please promote the Team PSD Website to PROD tonight.

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire Please replace the Team PSD website Team PSD Award medallions with the below.  An eps file was sent to you via email.

<img width="135" alt="image" src="https://user-images.githubusercontent.com/30132017/175646077-ebc8c77a-e606-4725-b82c-94045366833b.png">

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire  below are some tweaks for the Team PSD Website

## Put in legend button that contains the information in the image below

- Please clean up the image and format
- Create a small button in the header of the bio section on the very right.

### Legend Information

![image](https://user-images.githubusercontent.com/30132017/175695746-8d408394-8ecf-4ce1-93cb-1b32e2b545eb.png)

### Button location

![image](https://user-images.githubusercontent.com/30132017/175696252-2a68e0da-820b-4724-9b09-c59e812ca6b7.png)


## Maps Utility

- Please add the title in light blue for the Team PSD Leaders on the map
- Can we improve the location memory for Photos and text boxes?  Every time I go in, I have to start all over.

![image](https://user-images.githubusercontent.com/30132017/175695898-7ecbaadb-f093-495c-9381-3ce906f21da5.png)

## Resource Section

- There is no dropdowns to align the workflow logos with the website bios

![image](https://user-images.githubusercontent.com/30132017/175696545-7ab87384-95d0-4765-98a8-8c7064e02025.png)

**Comment by hnorthcraft** [comment]
#adjudicate_memo @lijenn @lzim This card looks like there was a lot of work attached. What is best SP estimate?
