### ISSUE TITLE
ICEBOX Story G: User needs markdown, LaTex and bookdown devops actions to streamline publication and ensure quality on-line publications, and research documents

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2675]
Need: GitHub Actions to enforce heading and sub-header style in Manuals.

Follow APA Style 7th Edition
- Title Case 
- Lower level headings in sentence case 

Observation: We saw confusing Headers in our manuals.
For example, we typically do NOT capitalize:
"across" and "and"

**Comment by jamesmrollins** [comment]
Hi @lzim - I will see if their are actions in the community that may support this and advise.

**Comment by jamesmrollins** [comment]
@lzim below is the APA style guide for headings:

- This isn't consistent with what you said above about lower level heading being in sentence case.  
- Please clarify.

<img width="314" alt="image" src="https://user-images.githubusercontent.com/30132017/188935003-a941bc5f-949a-454f-94c1-8d3d940d87b7.png">

**Comment by jamesmrollins** [comment]
Hi @emilymetcalf114 please find the prototype logic for this action below on [Lucid Chart](https://lucid.app/lucidchart/8cf71ee2-f75f-40f5-a4e8-25a03b536b9d/edit?viewport_loc=-94%2C-212%2C2271%2C1078%2C0_0&invitationId=inv_da2f88f5-6c30-46f8-8c21-7cede0972b4a#)

**Comment by jamesmrollins** [comment]
@hirenp-waferwire this project is released.  Supporting files attached to thread. 

- [preposition_list.txt](https://github.com/lzim/teampsd/files/9509442/preposition_list.txt)
- [APA Editor Action for Markdown Files v.1.0.pdf](https://github.com/lzim/teampsd/files/9509738/APA.Editor.Action.for.Markdown.Files.v.1.0.pdf)

**Comment by lzim** [comment]
**Decision at sim_ui_workflow**
w/ @jamesmrollins @emilymetcalf114 @lzim 

### User Need/Use Case for Enforcing Style in R Markdown/Markdown
All you change is the YAML header metadataAPA css, csl Biomed css, csl Use Case: O.H.I.O (only handle it once)

1. We build it in Markdown & R Markdown w/a YAML header
2. IF we get review that we have to switch from one to the other

_Next Steps:_ Pick up this conversation at 09/27 **team_time** with @KimCase123 Emily Pearman, & @dkngenda 

-  [ ]  **Review this [DevOps Document](https://lucid.app/lucidchart/e222541a-eace-412f-b35e-fdb5d2c97efd/edit?viewport_loc=-69%2C-2765%2C3700%2C1776%2C0_0&invitationId=inv_b0eb12aa-b843-4da6-849d-9a7408e40c9a#) for the Meeting that @jamesmrollins** 
- [ ] **Review this [OSF Cheatsheet](https://github.com/lzim/teampsd/blob/master/resources/cheatsheets/mtl_how_osf_cheatsheet.pdf)**
- [ ] **[Relevant YAML RMarkdown Manual](https://bookdown.org/yihui/rmarkdown-cookbook/rmarkdown-anatomy.html)**

FYI: @emilymetcalf114

**Comment by jamesmrollins** [comment]
@lzim @epearman @emilymetcalf114 @dkngenda 

11/3 Update

## It may be possible to automate document production

- [ ] See diagram below in [LucidCharts](https://lucid.app/lucidchart/e222541a-eace-412f-b35e-fdb5d2c97efd/edit?viewport_loc=-22%2C-2505%2C2960%2C1136%2C0_0&invitationId=inv_b0eb12aa-b843-4da6-849d-9a7408e40c9a)
- [ ] I found a method on YouTube called ["Book as code"](http://www.youtube.com/watch?v=6YGmNtsmz2k) that uses CI/CD to publish guides using LaTex.
- [ ] This may provide the flexibility to assemble full journal articles for various journals by simply changing document class.  This would require:
  - Maintaining text in its simplest form in folders that can be addressed via a repo.  This text would be straight text, and use LaTex to address citations, graphics and tables.
  - Maintaining diagrams in folders that can be addressed via a repo (similar to how we do mtl.how/manual.
  - Provide an action a researcher would use to update an r-notebook, render graphics and tables and then deposit in the folder mentioned above.
  - Provide an action a researcher would use where Zotero would provide a bibliography and then upload to a repository location co-located with LaTex files. This would provide citations where necessary in the document.
  - Provide an action that would lint and then render a preprint document that would be uploaded via API to OSF preprint for review. 

## For full diagram go to [LucidChart](https://lucid.app/lucidchart/e222541a-eace-412f-b35e-fdb5d2c97efd/edit?viewport_loc=-22%2C-2505%2C2960%2C1136%2C0_0&invitationId=inv_b0eb12aa-b843-4da6-849d-9a7408e40c9a)

<img width="640" alt="image" src="https://user-images.githubusercontent.com/30132017/199801822-ee1c5b89-0624-4e59-b7bb-d7c492b6e98f.png">

## Next Steps

1.  Continue research to verify technical feasibility of the automated process.
2. Break this card down into dependent cards that provide incremental progress and story point collection.
3.  Create actions that incrementally provide services identified above (R-code graph and table updates, Zotero exports and others).

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire - I checked out the custom_markdown_action and **it works very well!**  Below are a few things that we may need to work through.

- [ ] I changed the name of the action to apa_editor_action to help the end user understand the purpose of the action.
- [ ] I attempted to use in one of our current repositories by adding the action and changing the trigger to "gh-pages." However, it did not work properly.  I will need assistance modifying the trigger.
- [ ] Many of the "Use sentence case with numbered and bulleted steps were created because of the use of formal nouns.  Formal nouns are capitalized.  Is there a way we can catch those? Typically, formal nouns will be 1-4 words for like 90% of the use cases out there. 
- [ ] Can we change the error message from, "error at XX lines" to "error on line XX" please?

![image](https://user-images.githubusercontent.com/30132017/206044993-09eef4ff-9110-4a0a-be60-9e8c5be299e4.png)

**Comment by lijenn** [comment]
What is the difference between this card and #2125? Looks like #2125 can close if the work is being tracked in this card.

**Comment by matthewtomo** [comment]
#adjudicate_memo
@matthewtomo @jamesmrollins @ljmoody 
- Marking as closed because we are no longer pursuing LaTex for now

**Comment by hnorthcraft** [comment]
#adjudicate_memo updating to 1sp icebox/closed as not planned
