### ISSUE TITLE
mtl.how/demo: mtl 3.0 release (CI/CD)

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2680]
@jamesmrollins Part of CI/CD for moving model files to mtl 3.0. 
https://mtl.how/demo models don't reflect MTL 3.0 for: 

	Team (AGG) Care 
	Team (SP) Flow

**Comment by jamesmrollins** [comment]
FYI @lzim 

@hirenp-waferwire the SD Docs are not updating in the CI/CD flow.  See below.  

- The models are behind the latest updates available in the 2.0 folder. 
- The models in the demo sim are correct.

![image](https://user-images.githubusercontent.com/30132017/169936426-f2dd5d2e-766a-40e7-a4bc-6447aa6bd8fa.png)

**Comment by jamesmrollins** [comment]
@lzim - corrected titles of model documentation.

![image](https://user-images.githubusercontent.com/30132017/169939187-200dbdad-fe36-4569-b20e-41c9cb5d8f59.png)

**Comment by jamesmrollins** [comment]
- [ ] We will also track updating the lzim/mtl/blue/mtl3.0_model folder in this thread.
