### ISSUE TITLE
wk2 jun_epic: Refresh Data UI Cheatsheet w/Images from former Facilitator One-pager being sunsetted

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2690]
**DECISION:** 

We will no longer reference a Facilitator 1-pager, as the content reflects content we believe all Learners will want to know. 

Add the Clinic Selection Export and Sim UI Data Export information image files from the f[acilitate 1-pager](https://lucid.app/documents#/documents?folder_id=281232749&browser=icon) to the data cheatsheet.

Once the [Cheatsheet is updated in LucidCharts ](https://lucid.app/documents#/documents?folder_id=281232682&browser=icon )add it to these locations on https://mtl.how
- [x] Blue s2 SEE
- [x] Blue s2 SAY
- [x] Red p1 SEE
- [x] Red p1 SAY

**Comment by lijenn** [comment]
#adjudication_memo: Data UI and Facilitator One-pager have been merged and is live on mtl.how in Blue S2 SEE & SAY, Red P1 SEE & Say. 

Cheatsheet is here on Lucid > lzim/mtl > Cheatsheets > [mtl_how_3.0_data_cheatsheet](https://lucid.app/lucidchart/d78a7f1b-505c-4e67-9fde-1776d8227e25/edit?from_internal=true)
