### ISSUE TITLE
Next MTL 3.0 Recording 07/11: Sim UI mtl.menu -  Set up passwords at MTL menu that carry forward to Sim UI AND Create a Demo MTL Menu

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2699]
**Discussed 06/17/22 training_workflow**

@jamesmrollins as we discussed it would be great to add the password set-up dialogue to https://mtl.how/menu 

**- [ ] Users set up password after entering their email to log-in to mtl.menu (end of _MTL Blue_ session 3).**
![image](https://user-images.githubusercontent.com/7454688/174409534-702b39dd-2b67-4ee2-a7ed-3e2c2bb884d3.png)

**- [ ] Need a demo version that shows the questions like the .gif from the end of session 3.** 
![image](https://user-images.githubusercontent.com/7454688/174409487-c5a89226-d466-4f57-992e-7bd03c4d25e0.png)

**- [ ] Note that facilitators need to be able to access this view for demonstration, not just go straight to the responses.**

**- [ ] Demo version pre-populated with responses e.g., a good version was covered at our meeting.**

**- [ ] Would like to see the yellow indicating depicting individual learners response within the distribution of team.**
![tempsnip](https://user-images.githubusercontent.com/7454688/174410916-65b03d39-99c0-478e-95c8-592995854853.png)

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire.  We would like to develop a [Menu End-user Enrollment Process](https://lucid.app/lucidchart/41c0aacf-b2d8-40a0-90d2-f4b1400777f7/edit?viewport_loc=-142%2C-44%2C2725%2C1295%2C0_0&invitationId=inv_6e720a89-e1ef-4b67-ab41-5f8d823cef53#) where the users can register as end-users in Epicenter from the Menu login. This will improve the security of the interface, by restricting the access of team members to their own account. This will not replace team setup in the Facilitator Panel; however, **the Facilitator will need to set up a blank team prior to the Menu login setup.** That way the system will know who is a user, and who is a Facilitator associated with the team.

We are looking to complete this by Tuesday, 8 AM PST.  We will use the Breakfix route to PROD. 

@lzim - We could provide a team dropdown for the teams to select from, but that would expose them to other teams.  Is this ok, or do you want to just give them the Team ID to enter in the field?

![image](https://user-images.githubusercontent.com/30132017/174450329-66041443-553e-4a4d-bdbb-41bc902c00a1.png)

**Comment by jamesmrollins** [comment]
FYI @lzim 
Hi @hirenp-waferwire - We would like to add in a [non-functional "demo" menu selection](https://lucid.app/lucidchart/ce65224e-d59e-4d07-ab00-f0a03f750389/edit?viewport_loc=-74%2C-11%2C2725%2C1295%2C0_0&invitationId=inv_c4c5a954-8b9c-4320-bce6-443011d9a738#) from the facilitator panel.  The Menu would be able to click buttons on and off but would not have a "Submit" button to push the form.  There would be a "View Results" button in the upper right that would display a sample results form.  I will tell you which team's results to de-identify and use when we meet on Sunday night. 

![image](https://user-images.githubusercontent.com/30132017/174451298-f37e81e8-bbb9-4408-af6f-b9be42606af7.png)

**Comment by jamesmrollins** [comment]
@lzim - This is where we landed on this feature this weekend:

1. The demo page is set up, but we forgot to de-identify the team in the header.  We are sorry about that - trying to see if I can rouse @hirenp-waferwire to correct it, but it is his evening time.
3. The Epicenter API does not allow us to change or update a password directly using a text input, such as the menu login screen.  It only offers the password reset function, which includes an email with a reset link procedure.  
4. So we will need to set the team up and give them the standard password.

**Comment by lzim** [comment]
@jamesmrollins  

**The Demo looks great 😸  with the exception of the Team name being displayed.**
- [ ] Change team name to "**mtl_3.0_blue_demo**"

- _Is it necessarily the case that 3 has to follow from 2?_
> 2. The Epicenter API does not allow us to change or update a password directly using a text input, such as the menu login screen. It only offers the password reset function, which includes an email with a reset link procedure.
> 3. So we will need to set the team up and give them the standard password.

I'm so sorry that we didn't look at this together yesterday when we spoke.  I realize that we're up against API constraints, but we also have a possible cakewreck related to 2 below, which I know is frustrating, since we tried to move fast. 🍰 ☹️ 

1. I DID realize when we spoke yesterday that facilitators will always have to set up the team, which is what I always expected for multiple reasons. 
2. However, I was hoping that the password reset dialogue could be prompted **without having to provide the users with a PASSWORD first. The Team ID concept further complicates learner & facilitator first experience with the Sim UI.**

The solution in PROD requires several additional steps, which @swapmush & @lijenn discussed, and although it would be sunk cost, we believe _going back to the original **no password** use_ of the _MTL_ Menu is preferred over additional complications to first Sim UI use. 

**Design intent for updates to _MTL Menu_**
- Learners are prompted to set up or reset their own password when they log in to the _MTL Menu._

**Possible learner- and faciltiator- centered options**
1. The team's **auto-generated password is grabbed in the backend** when user begins _MTL Menu_ dialogue and they reset it. - PRO: Preferred, original intent.
2. The team's **auto-generated password is listed or provided to the team member visually in the _MTL Menu_ dialogue**, which learner then use to reset. PRO: The facilitator and team do not rely on clunky knowledge of conventions to manage this process. CON: Still not a one-time PW set up for the team.
3. **Go back to the status quo where there is no PW for the _MTL Menu_** the team then has to use the auto-generated password for session 5 Sim UI login. PRO: First experience with Sim-related logins is smooth & easy. CON: In particularly conflictual teams, then the shared auto-generated PW may be problematic AND the team still has to set up the PW for session 5.

@jamesmrollins Note below are the rules we have for SIM UI Auto-generated password, note that the 3 one down is underspecified, while the others are clear and marked with x and "okay"

- _Can we get a rule for the # of characters of the team name that will auto-generated as the password?_
You, @lijenn and I could not figure out what the specific rule is, for example, why PALO vs. PALOALTO or something. 
So, this further complicates everything for learners/facilitators unless we define the number of characters.

e.g. 123_PALO!01
- [x] 3-digit sta3n - okay
- [x] underscore - okay
- [ ] we need to know how many characters of team name are auto-generated
- [x] in all caps - okay
- [x] exclamation mark- okay
- [x] 01 - okay

**Comment by lzim** [comment]
![image](https://user-images.githubusercontent.com/7454688/174915956-6eca789f-d04b-40cb-9f47-d9070904c690.png)

**Comment by lzim** [comment]
**Based on conversation 06/21/22 w/ @lijenn & @jamesmrollins**

"Set up Password" 
OR
"Verify Account"

**Comment by jamesmrollins** [comment]
FYI: @lzim 

Hi @hirenp-waferwire - Thank you for the quick turn-around of this feature.  It is working well. However, when the user completes the input of the desired password, it does not return them to the correct URL.  Should be: https://forio.com/app/va/va-psd-mtlmenu/survey.html

![image](https://user-images.githubusercontent.com/30132017/175436211-ae10ff6c-668f-4b82-975d-a4d5b9c54b75.png)

**Comment by lijenn** [comment]
@jamesmrollins Thanks so much! I tested in Prod and saw you got the documentation done too.

I think the only thing left was the edits on the Sim UI + documentation for:

>At mtl.how/sim
>- [ ]  Change "Username" to "VA Email"
>- [ ] Change the Reset Dialogue from "user name" to "VA email"
 
 For documentation, I believe it only impacts in S4 See and S5 See's gif ([/lzim/teampsd/master/resources/gifs/mtl_2.0/sim_ui_1.gif](https://github.com/lzim/teampsd/blob/master/resources/gifs/mtl_2.0/sim_ui_1.gif)), since you already made the text edits in the guides to say "VA Email".

**Comment by jamesmrollins** [comment]
Thanks for the review @lijenn.

@hirenp-waferwire - Please change the "Username" label to "VA Email" on all the logins - thank you.

![image](https://user-images.githubusercontent.com/30132017/176563134-7e0e8c4c-a670-4e8b-a9f2-4d74f1353363.png)
