### ISSUE TITLE
wk2_jul: Feature - Facilitator Registration Process and Login Setup in Sim UI

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2702]
FYI @lijenn @lzim 

## Feature Objectives

This feature will provide:

- A user-friendly way for on-boarding Facilitators to self-register and set up their logins to the Sim UI.
- Security to prevent just anybody from setting themselves up as a Facilitator.

## Benefit Hypothesis
Upon implementation, new Facilitators can be given a link to follow that will give them access to a registration screen. The registration process will free up operations staff to do other things by empowering the Facilitator to self-register and set up their access to the Facilitator Dashboard.  From the Dashboard, the Facilitator can set up teams and invite end users.

## Assumptions

- [x] The Facilitator will use self-help means to learn how to set up a team in the Facilitator Dashboard.
- [x] The Facilitator knows how to download a team roster (or otherwise knows who is on the team) and Team Data to set up a team.

## Requirements

- [x] A wireframe that mocks up the registration page.
- [x] A workflow that describes how the registration page will set the Facilitator up within Epicenter as a Facilitator and record a password.
- [x] A secure link to a registration screen.
- [x] A registration screen that verifies the identity of the Facilitator and allows them to establish a password.
- [x] After login the Facilitator will be granted immediate access to the Facilitator Dashboard.

**Comment by jamesmrollins** [comment]
Hi @lzim and @lijenn  - below is the workflow for a [facilitator self-registration process](https://lucid.app/lucidchart/0b8d2254-f38c-4874-ad37-529f97a13901/edit?viewport_loc=-17%2C-3%2C2219%2C1055%2C0_0&invitationId=inv_c472763f-6bac-44c4-bc69-ca2fdca4bcc4#) to support discussion at the Sim UI Meeting tomorrow 7/13.

<img width="296" alt="image" src="https://user-images.githubusercontent.com/30132017/178586702-7f46a156-bf75-4dc7-87c4-71a0aff5f930.png">

**Comment by jamesmrollins** [comment]
Hi @lzim - Here is the wireframe for the facilitator registration.  The Tutor Sequence will be published later next week.
FYI: @hirenp-waferwire - I will give you a thumbs up via Teams and then you can start DEV.

## Wireframe

![image](https://user-images.githubusercontent.com/30132017/179315478-0d254a89-e9ad-487c-9624-62ab5f46d735.png)

## Algorithm

![image](https://user-images.githubusercontent.com/30132017/179315566-cee0fcdf-1b17-4b88-b659-98f6ed244ae8.png)

## Supporting Files for Dropdowns

### Facilities and Clinics

[facilities_clinics.xlsx](https://github.com/lzim/teampsd/files/9124313/facilities_clinics.xlsx)

### VISN

[VISN.xlsx](https://github.com/lzim/teampsd/files/9124314/VISN.xlsx)

### Wireframe PDF

[Facilitator_registration copy.pdf](https://github.com/lzim/teampsd/files/9124318/Facilitator_registration.copy.pdf)

**Comment by jamesmrollins** [comment]
Hi @lijenn @lzim  UPDATE

FYI: @hirenp-waferwire 

1.  We are having issues with cookies interfering with our registration functionality.  It is delaying our progress.  
2. Since we have not progressed, yet, to changes on the facilitator dashboard (mtl manual and tutor), I have delayed the dependent task for developing the tutor wireframe.
3. Once we resolve these bugs, we should be able to get the Tutor functionality in place within a few days.

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire - Please find the Tutor stop locations below.  I will put the text in the Tutor Admin panel once you have these stop locations created.

## Main Dashboard
![image](https://user-images.githubusercontent.com/30132017/181117550-21e86077-73e5-45f1-9199-a0f3fbdc4fbd.png)

## Team Setup Popup
![image](https://user-images.githubusercontent.com/30132017/181118118-935d6d7f-44ee-440c-bbbd-73c580e168b3.png)

## Team Setup Popup - Team Setup
![image](https://user-images.githubusercontent.com/30132017/181118391-48a63d6d-58f7-4536-8499-11857251856b.png)

## tt Admin Popup - tt reports top (need tutor icon)
![image](https://user-images.githubusercontent.com/30132017/181118958-5e765b9f-2659-4b33-9e5e-2a5324e8373e.png)

## tt Admin Popu - tt reports bottom
![image](https://user-images.githubusercontent.com/30132017/181119383-0a852924-a869-43e2-a6d0-ea98e02f795c.png)

**Comment by jamesmrollins** [comment]
@hirenp-waferwire - Here are the associated explanations.

## Main Dashboard

|Station|Narrative|Link|
|---|---|---|
|1|The Tutor button will introduce you to the features of this page.|-|
|2|Access the team time report setup page|[Product Team Time Report](https://lzim.github.io/mtl/7-facilitator-technical-manual.html#produce-team_time-report)|
|3|Set up a team using the team setup page-there is a Tutor on this page too.|[Setup a Team](https://lzim.github.io/mtl/7-facilitator-technical-manual.html#set-up-a-team)|
|4|View teams statistics to see how experiments are proceeding. You must first select a team to see results.|-|
|5|See who is on the selected team.|-|
|6|The _MTL_ Manual is a comprehensive reference on many _MTL_ features and processes.|[mtl.how/manual](https://mtl.how/manual)|
|7|Click here to navigate to the Home page of any team.|-|
|8|Click here to navigate to an active session. If button faded, then there is no active session.|-|
|9|Use this dropdown to find a team.|-|
|10|This speedometer indicates how far the team has progressed with the selected experiment.|-|
|11|Use this dropdown to select an experiment.|-|
|12|Click here to expand the section.  Each section can only show one team at a time.|
|13|Click here to close the team dashboard|-|
|14|Click to add a team to the infinite list.|-|

**Comment by lijenn** [comment]
@jamesmrollins @lzim Thanks for your hard work on this!!!
Some feedback and questions:
- [ ] _Is the Approver the same as the Requester just in this TEST/QA instance?_ 
I got the Approver email while also being the Requester. 
I assumed the Approver email would go to anyone with an Administrator login (i.e. Lindsey and the Manager Trio)? 
- [ ] I signed up in TEST with a new/unregistered email. When I logged in, Epicenter assigned me the **Admin** login. 
_Should it be Facilitator?_
![image](https://user-images.githubusercontent.com/59668647/184263683-5b036670-f330-49d9-b0d4-4d9a21a067ea.png)
- [ ] The 'Facility or Clinic' field on the Approval page is showing the VISN rather than the name of the facility/clinic. ![image](https://user-images.githubusercontent.com/59668647/184260605-4bc57862-6e6a-431f-b8ce-e81b83908095.png)
- [ ] The two password masking/unmasking icons and toggles are inconsistent:
![image](https://user-images.githubusercontent.com/59668647/184260129-ee517204-9684-4b0d-99d7-553078605348.png)
- [ ] The 'Repeat Password' masking/unmasking icon only appears when you type out the password. It then disappears after you click out of the text box and doesn't come back.
![image](https://user-images.githubusercontent.com/59668647/184260560-efe2d147-fffc-4f73-a1ff-17a3d7637984.png)
- [ ] _When you say the highlighted below, do you mean that Tutor should automatically popup to instruct the user/Facilitator?_ If so, Tutor did not automatically popup for me upon my first new login in TEST.
![image](https://user-images.githubusercontent.com/59668647/184265146-46342650-5e33-462f-886c-d0cd89ca0729.png)

Please let me know what I can clarify!

**Comment by jamesmrollins** [comment]
FYI @hirenp-waferwire 

@lijenn thank you for the review.  We will correct the issues you identified above.  However, related to the Admin login and the Tutor, when you set up the account, did you ensure that you started from a fresh login?  Meaning, did you ensure the email you used was not already an end user in Epicenter?  If not, try the process by first deleting the end user from the Epicenter account and then reregister.  That will likely clear the Admin login problem.  For the Tutor problem, see below.  Below are some other explanations:

1.  Yes, the approver is the requester for the Test instance.  When we promote to PROD, it will point to mtl info.
2. I retried the login procedure again resulting in a Facilitator session, I cannot explain the Admin login you show above. Again, try clearing the end user account and try the process again.

<img width="553" alt="image" src="https://user-images.githubusercontent.com/30132017/184893212-2904f49c-f604-4aa4-8a26-db940a37e7c2.png">

3. The Tutor issue is likely because your browser has a cookie from another login that is saying you have already seen it.  Try clearing your cookies and logging in with a new end user.  It should appear then. Otherwise, clicking the tutor icons will also make them appear.

**Comment by emilymetcalf114** [comment]
Hey @jamesmrollins! 
Here is how my test went: 
1) I entered my information (using a new personal gmail in chrome). I specifically selected my facility/clinic as Palo Alto (sorry I didn't capture this screen shot! but everything seemed smooth sailing on the initial page)
Of note, looking at Jenn's notes from her test on this part of the process, issues with the password masking/unmasking icon are resolved - they were consistent and worked as they should! 

2) I received the email to approve my registration to the email I used to register (this is correct for testing purposes)
![image](https://user-images.githubusercontent.com/111393225/189226133-863decf7-dc7f-472b-a0b5-e688456aaf0f.png)
3) I approved my registration request by following the link in the email. **Issue: The facility/clinic I selected changed from Palo Alto to Pacific Islands**
![image](https://user-images.githubusercontent.com/111393225/189226604-d668f05d-4566-4c44-93f2-2c53f65173a1.png)
4) When I logged in for the first time, **I received an Andon alert?** 
![image](https://user-images.githubusercontent.com/111393225/189226967-9097b3ff-5bf2-4df9-9903-b68f57ebb46e.png)
5) When I closed out the Andon alert, this is all I saw: 
![image](https://user-images.githubusercontent.com/111393225/189227019-c082aa59-922c-48e2-a32e-b07130942d7a.png)
**It shows me in Administrator mode. I also am missing most of the functionality, and the tutor did not start up**

6) I read your note above about clearing cookies. So I closed my browser and cleared all cookies, and logged back in. Now I see this:  **(even less functionality)** 
![image](https://user-images.githubusercontent.com/111393225/189227483-42cb5d3d-7614-4557-9754-4df02b2f6190.png)

**Comment by jamesmrollins** [comment]
HI @emilymetcalf114 - thanks for conducting this test for me!  

Besides the Tutor Function - everything appears to be working correctly.  

Regarding:

4.  Andon alerts always appear on first login.  But that shouldn't interfere with the Tutor function.  @hirenp-waferwire  will look at it when he returns from Holiday.
5.  You must have logged in as an admin before (see "Admin" in upper left), so clearing the cookies was a good idea. 
6. This is correct (see "Facilitator" in upper left).  Try clicking the "ADD TEAM" icon.  You are not set up with any teams, so the screen is very basic.

**Comment by emilymetcalf114** [comment]
Hey @jamesmrollins 
When I click on the + Add Team button, it looks like this! 
![image](https://user-images.githubusercontent.com/111393225/189233882-fe1c135c-dce7-493d-b295-be0e263f4934.png)
Tutor does not automatically pop up, but I can click on to initiate. 
![image](https://user-images.githubusercontent.com/111393225/189234263-49cde0da-3554-47da-93a6-92fa2d3825cb.png)
![image](https://user-images.githubusercontent.com/111393225/189234311-a2e75fee-31eb-4303-a5f6-6fd9ce4b0059.png)
![image](https://user-images.githubusercontent.com/111393225/189234360-f620f52c-db97-4ba4-953a-df5d7d438bdb.png)
(has tutor button now) 

![image](https://user-images.githubusercontent.com/111393225/189234521-e907620b-84d5-4629-a03b-e931515d231a.png)
