### ISSUE TITLE
ASAP ANDON: Sim UI PROD not responsive at login Chrome, Edge, Safari

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2707]
@jamesmrollins I was preparing a few things this AM in the Sim UI & I’m unable to login to PROD.
Sim UI was unresponsive at click of **green “Login” button** after entry of username and password. 
**Password reset is responsive.** _Should I reset?_

**I checked this AM:**
**VA GFE**
- [x] Chrome
- [x] Edge

**iPad**
- [x] Chrome
- [x] Safari

**Comment by jamesmrollins** [comment]
Don't reset. It's likely a cookie problem. Can you clear your cookies?

**Comment by lzim** [comment]
@jamesmrollins 

Per Teams chat in sim_ui_workflow
Cookie reset resolved fro Edge, but not Chrome.

**Comment by jamesmrollins** [comment]
@lzim did you reload the page before clicking "Login"

**Comment by lzim** [comment]
@jamesmrollins 
_Will you please post screenshots for each Browser of where cookies need to be reset?_
- I'm still not getting a resolution in Chrome, but would help to be sure I'm doing what's needed.

We'll need to go over this with facilitators at 8AM faciltiate_workflow tomorrow, so that they can cover it with their _MTL Live_teams tomorrow and throughout the week.

**Comment by lzim** [comment]
_Note:_ I will try Safari later, but will use Edge for the _MTL 3.0 Video_ shoot w/Swap from 2PM-5PM today.

**Comment by jamesmrollins** [comment]
WILCO

**Comment by jamesmrollins** [comment]
# Cookies may interfere with Sim UI login

There is an unidentified cookie that is preventing the Sim UI API login function from working.  To enable the login function, follow the steps below. If the browser doesn't accept the login after refresh (see Step 3 below), try closing the browser and reopening it.  

## Step 1 - Navigate to your browser's setting menu

### CHROME

![image](https://user-images.githubusercontent.com/30132017/180877421-096ea1a2-108a-45a6-a54c-87c180209acb.png)

### EDGE

![image](https://user-images.githubusercontent.com/30132017/180877250-5e3e9c49-bb1c-44cc-ba0a-2ca09eb72556.png)

## Step 2 - Navigate to your cookie settings and delete cookies

### CHROME

![image](https://user-images.githubusercontent.com/30132017/180877789-41f35eeb-634e-4190-9a63-08ae2149c962.png)

![image](https://user-images.githubusercontent.com/30132017/180878370-aa719411-be89-44fd-bfc8-a4c3b1123081.png)

![image](https://user-images.githubusercontent.com/30132017/180878577-45f99da1-7f3b-4113-b9d4-a5c9bcbe42ab.png)

![image](https://user-images.githubusercontent.com/30132017/180878654-e797b956-5b5f-41e2-98ee-dcb06530ac01.png)


### EDGE

![image](https://user-images.githubusercontent.com/30132017/180877623-a54353dd-730c-4170-8a44-29d805f5fe1c.png)

![image](https://user-images.githubusercontent.com/30132017/180877974-99973f8b-d729-4935-b1d9-ad03fad7c788.png)

![image](https://user-images.githubusercontent.com/30132017/180878128-c046f0b0-ab3a-48a4-a680-bf193174edb7.png)

![image](https://user-images.githubusercontent.com/30132017/180878889-f5a64f1d-ba8c-4081-bf4d-cf01c9e67446.png)


## Step 3 - Refresh your browser

### CHROME

![image](https://user-images.githubusercontent.com/30132017/180879173-39962628-1fb3-4984-80d4-302939f4bc78.png)

### EDGE

![image](https://user-images.githubusercontent.com/30132017/180879376-bc21db23-40c2-42cc-a99f-7b26261ba1ee.png)

**Comment by lzim** [comment]
@jamesmrollins 
_Is this waiting on me to check Safari?_
_Does this need to be documented in the manual?_

**Comment by jamesmrollins** [comment]
@lzim - I could put this in the manual, but would improve the graphics a bit.
