### ISSUE TITLE
wk4_jan_Story F: As an operations user, I need a convenient way to create a test branch in lzim/mtl

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2710]
## User Story

The user currently must find and replace each link for the links below, throughout all lzim/mtl documentation:

- mtl.how/data -> mtl.how/data_test
- mtl.how/menu -> mtl.how/menu_test
- mtl.how/sim -> mtl.how/sim_test
- mtl.how -> mtl.how/test

This requires 4 separate runs of the find and replace action ( 8 runs, if one includes returning branch to Master), plus quality checks.  The user would appreciate a standard action that would create a test branch and automatically change the links to Test. Therefore, any changes to the sim, documentation or related repository information can be achieved in the test branch, and then promoted to Master when ready. 

## Definition of Done

- [x] A completed GitHub action the user can call to create a test branch.
- [ ] The GitHub action has been quality tested to ensure a stable action process.

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire please refer to the [teampsd_mtl_DEVOPS_architecture](https://lucid.app/lucidchart/e222541a-eace-412f-b35e-fdb5d2c97efd/edit?viewport_loc=3290%2C-59%2C2821%2C1271%2C0_0&invitationId=inv_b0eb12aa-b843-4da6-849d-9a7408e40c9a) for instructions on this action.  I am available for discussion and clarification.  The image below is the diagram we are referring to.

<img width="761" alt="image" src="https://user-images.githubusercontent.com/30132017/197297432-e19bdf1b-a1ea-42e0-9779-553cebc60d2b.png">

**Comment by jamesmrollins** [comment]
@hirenp-waferwire I did not get a chance to test this today.  I will test tomorrow 12/7

**Comment by lzim** [comment]
#adjucicate_memo

_How should this be handled to accurately track effort from Nov to Feb 2023?_
@jamesmrollins 
@emilymetcalf114 
@epearman
