### ISSUE TITLE
oct_epic BY OCT 28: Story I TASK: Test the D365 CRM DEV Clone Enviornment Using User Tester's Guide for Platform Functionality

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2711]
| Environment Name | URL |
| ------------- | ------------- |
| VA MTL DEV  | dvagov-psd-dev.crm9.dynamics.com  |
| VA MTL QA  | dvagov-psd-qa.crm9.dynamics.com  
| VA MTL PROD  | dvagov-mtl.crm9.dynamics.com

Microsoft Dynamics 365 released wave 1 release updates in 2022 (search for keywords like "Dynamics 365", "2022 release", "wave 1", "release" in [MSD D365 SharePoint](https://dvagov.sharepoint.com/sites/OITPlatformServicesCRMTeam/VAMicrosoftDynamicsPlatform) for latest updates.

- [ ] Test and Review our D365 CRM User Tester's Guide for functions/features in QA and PROD to ensure new releases do not impacting existing functionality. Guide is in MS Teams > facilitate_workflow > [Dynamics 365 > D365 Tester's Guide](https://teams.microsoft.com/_#/files/facilitate_workflow?threadId=19%3Acb0b9866ac224a179236c0cc3e2ee56f%40thread.skype&ctx=channel&context=Dynamics%2520365&rootfolder=%252Fsites%252Fteampsd_vha%252FShared%2520Documents%252Ffacilitate_workgroup%252FDynamics%2520365)

- [ ] Review/update the [bug_tracker](https://mtl.how/bugs) by looking at existing bugs and/or creating new issues for new bugs

**Comment by lijenn** [comment]
@emilymetcalf114  @lzim  Discussed at 9/15 train_workflow:
![image](https://user-images.githubusercontent.com/59668647/190487485-a1ef5244-1c4b-4ab6-a1c6-3bf6d044921e.png)

If Dawn went through and provisioned the lower instance (I'm assuming Dev or QA), that is fine. But we do need to check how this new release impacts our current environments.

If we do encounter new bugs, we should document it in the bug_tracker and report it to Dawn.

Deadline for Wave 2 release to be pushed to Prod is Oct. 28th.

Release Schedule - https://docs.microsoft.com/en-us/dynamics365/get-started/release-schedule#how-do-i-enable-the-early-access-features-in-an-environment

**Comment by lijenn** [comment]
Discussed train thurs 10/27/22:
Jenn is testing & will let Dawn know by the end of the day weather to release the DEV instance.
	
Jenn thinks based on emails w/Mimi & Dawn (in mtl.help@va.gov) this will be released all the way to PROD.

**Comment by emilymetcalf114** [comment]
@lijenn 
Please confirm if this is done and ready to close.

**Comment by lijenn** [comment]
Jenn finished reviewing Dynamics with Wave 2 release and asked Dawn to roll out updates for all CRM environments (Dev, Test, Prod) on 10/28 in MS Teams chat.
