### ISSUE TITLE
Feb_epic TASK: Audit usage and licensing for Data Camp , R Shiny Server and Lucid Chart subscriptions 

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2712]
EDIT: Audit all licensing and usage for Data Camp, R shiny and Lucid chart to ensure we have appropriate subscriptions. 

Our DataCamp subscription is now expired, revisit in January 2023 to assess if we should renew and how many licenses we need.
See MTL INFO inbox for email thread.

**Comment by epearman** [comment]
**Functional Requirements**
- [ ] @emilymetcalf114 investigate how many users of Lucid Charts we need.
- [ ] @epearman will check with @dkngenda to see how many users of the authorship app he thinks we have. 

**DECISION:**Lucid Chart will be on SAMHSA

**Comment by lzim** [comment]
#adjuciate_memo

@epearman  & @emilymetcalf114 
_Should I close this card for jan_epic?_ 
Here's the effort I have on this:
- [x] @jamesmrollins Review and provide update on usage for Forio Epicenter (2 pts)
DECISION: Renewed Forio Epicenter at the **Large** License Feb 2023 based on usage & # of projects
- [x] @lzim Reviewed and updated LucidCharts for 50 users - 
_Next Steps:_ Will_ renew on the SAMSHA Hawaii budget. 
- [x] @epearman & @lzim Discussed and decided to postpone DataCamp for now unless there is a targeted workflow_user need for **Story B/J** (FYI: @dkngenda  @jamesmrollins)

- [ ] STILL NEEDED: @dkngenda _Can you help @epearman & Heather Marsh (incoming R&D Manager for teampsd_portfolio) determine what we need to budget for our Shiny Server app if we are going to be writing regularly?_
_Does this need discussion or just on the board?_

**Comment by dkngenda** [comment]
These are the shiny subscription payment plans. We are currently on the standard plan which is 1,100/year.  We also need a Dropbox account to back up the data. A free dropbox account has enough space for our purpose

![image](https://user-images.githubusercontent.com/66848852/217364447-448a9983-8f45-451d-b176-e765119b6400.png)

**Comment by lzim** [comment]
**Discussed at wk1 feb_epic team_time**

_Use case:_ Publish the authorship app manuscript and it attracts attention.

**Current State:** 
_Why:_ In the latest release there is an authentication page thru Shiny Server ($99/mo).
- **Advantage:** There is no limit in how many hours can run.

- [ ] @dkngenda is aware of a new package that would authenticate without R Shiny Server.
- **Drawback:** Limit 5 applications & # of hours they can run.

_How:_ Paid Subscription version Shiny_ Server is communicating with David's personal DropBox account.

**Comment by emilymetcalf114** [comment]
Lucid Charts renewed on separate card #cross-ref #2882.

@dkngenda 
@epearman 
@lzim 
_Can this card be closed, and was all effort completed in Feb_epic? 
Are the story points correct?_

**Comment by epearman** [comment]
Closing this card. I have broken off the remaining tasks regarding R shiny in #crossref #2915
