### ISSUE TITLE
wk5 aug_epic: Story A TASK: Renew shinyapps.io for Authorship

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2713]
Need to renew subscription at https://www.shinyapps.io for the Authorship this Fall.

**Comment by emilymetcalf114** [comment]
#adjudicate_memo
@KimCase123 and @emilymetcalf114  met with Luanne on 08/31/2022 for training in ReQLogic and to complete this task. Moving the card a day later during training_workflow.
