### ISSUE TITLE
wk4 aug_epic Bug: post-session fidelity survey not working 

### ISSUE THREAD

**Issue by emilymetcalf114** [lzim/teampsd#2715]
@dlkibbe discovered that the post-session fidelity survey is not working during the _MTL_ team mtg at **10:30am on 2022.08.22.** Reported in facilitate_workflow to @lzim and @emilymetcalf114. 

They could not complete the survey today after the session because they received this message: 

![image](https://user-images.githubusercontent.com/111393225/186003125-c00ea433-14a7-474d-983b-55da3d8932fc.png)

@dlkibbe: 

1. Which **browser** were you using when you received this error message? 
2. Could you try using **Ctrl + Shift + i** to pull up the Inspector Console in Chrome to see what error message you are getting? 

@lzim tried using Chrome and was able to get in ok (left side of screen) and the Inspector Console did not show any errors (right side of screen) 
![image](https://user-images.githubusercontent.com/111393225/186027140-025b4d64-9616-4478-a90b-7cf3db04d39e.png)

**Comment by dlkibbe** [comment]
Hi @emilymetcalf114  - I usually go in to Google Chrome to complete the survey. I can enter the information into the home page (team name, session no.), but when I click submit, it gives me the thank you for taking the survey message (again today). I clicked on ctrl-shift-I and selected the console, no error message is appearing. I'm tagging @jwklocek to see if he still has the same issue. This had happened once before to us and Lindsey experienced the same error but I'm not sure how it was "reset."

**Comment by emilymetcalf114** [comment]
#adjudicate_memo
@lijenn saw this bug in the prep chat and fixed on 8/25
