### ISSUE TITLE
8/24/22 Bug Facilitator unable to access SIM UI 

### ISSUE THREAD

**Issue by swapmush** [lzim/teampsd#2717]
**1.  Tanya MTL Blue Facilitator unable to log-in to SIM UI. They do not have "facilitator" option in drop down menu. Discovered last week. Tanya was added as facilitator to Team by Swap in SIM.

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire - I screen shared with the user and found this problem to persist.  User was added with Facilitator Panel via API.  See screenshots below:

## During Login User Unable to See Facilitator in Dropdown

![image](https://user-images.githubusercontent.com/30132017/186269395-297a290f-92cd-4b66-abe8-d35132181934.png)

## User Is Facilitator in Epicenter

![image](https://user-images.githubusercontent.com/30132017/186269347-cbed419b-5670-45ac-b215-b64b4379c6d1.png)

**Comment by jamesmrollins** [comment]
@hirenp-waferwire - I found the the end user above was not in the facilitator_login group in Epicenter.  However, @swapmush indicated that he set the facilitator up using the Sim UI Team Set Up (see below)

<img width="520" alt="image" src="https://user-images.githubusercontent.com/30132017/186324948-51229b94-1ede-4226-beff-ec21940bf939.png">

**Comment by jamesmrollins** [comment]
@emilymetcalf114 experienced trouble logging in via Chrome or Edge.  Cookies were deleted, but login issue persists.  See screen below for errors.

@hirenp-waferwire will address 8/24

![image](https://user-images.githubusercontent.com/30132017/186577160-3ca74e34-e2ae-4fa3-9c9f-a6c5a1e3dfa4.png)

**Comment by emilymetcalf114** [comment]
I was able to log in successfully in to SIM UI at 7:15am on 8/25/2022!

**Comment by emilymetcalf114** [comment]
@jamesmrollins 
In the sim_ui, I am able to see 459_pacific_islands _team and _shared groups, but not _ind. 
I logged into epicenter and you added me to 459 _ind yesterday, yet I still can't see any _ind groups:
![image](https://user-images.githubusercontent.com/111393225/186720585-2967da81-904a-4be4-b88a-a5b623beeb46.png)

**Comment by jamesmrollins** [comment]
Hi @emilymetcalf114 - The reason you don't see any _ind groupees is because their aren't any in the group yet. However, you should still see the _ind team header.  I will check it out.

**Comment by jamesmrollins** [comment]
@emilymetcalf114 we don't display a team header group, because each _ind is assigned to their own world.  Its difficult to explain, but the _team and _shared groups all share the same world.  The _ind group, each individual has their own world and that is what shows.  They are indented underneath the _team world so they are at least grouped to easily find them. 

FYI @hirenp-waferwire
