### ISSUE TITLE
Bug:  Default Facilitators not Loading Into New Teams

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2720]
When a facilitator creates a team, the sim is supposed to load in the group creator, Dr. Z, EM, and JR as facilitators automatically.  It is not.

- [x] Update code to remove JL and SP.
- [x] Add in LZ, EG, JR

**Comment by emilymetcalf114** [comment]
Hey @jamesmrollins 
@dlkibbe built the teams (for the _MTL_ blue team that meets on Mondays at 9 am) in the sim last week, following the instructions in the manual. None of the default facilitators were added.

**Comment by jamesmrollins** [comment]
I will check it out @emilymetcalf114 . Although I will say I tested this and it appeared to work.

**Comment by emilymetcalf114** [comment]
Is this functionality only supposed to happen for the creation of the _shared world? 
Digging a little deeper I noticed that this DID work for the _shared world, but did not occur for the _ind or _team worlds. 
Is that by design?

**Comment by jamesmrollins** [comment]
@emilymetcalf114 This is tested and complete
