### ISSUE TITLE
9/1 Bug: unable to log into SIM

### ISSUE THREAD

**Issue by Cyamo483** [lzim/teampsd#2722]
**1. After entering my VA email and log-in, there is a yellow outline around "log in," and then nothing changes/loads. I attempted on both Chrome and Edge with same result

![image](https://user-images.githubusercontent.com/112109819/186727728-3a0d186c-c246-4f2f-9f6b-edcd59ff272d.png)

<< Paste screenshots here>>
1. When was the bug discovered? 8/25/2022
2. Is this an invidivual or shared world? log in screen
3. What is the name of the experiment? n/a

**Comment by emilymetcalf114** [comment]
Hey @Cyamo483 
I was having the same issue - please try clearing the cookies in your browser and seeing if that allows you to move to the next step (a pop up should appear asking which world you want to enter). I had to clear cookies in both Chrome and Edge for my login to proceed. 

If this doesn't work, could you let us know, and include a screen shot of the errors being generated by:
right clicking in the window --> selecting "Inspect" (the last option) -->selecting "Console" (second option in the top grey menu bar on the right side of your screen).

**Comment by emilymetcalf114** [comment]
@Cyamo483 let me know if you are able to login now! thanks 😄

**Comment by hnorthcraft** [comment]
#adjudicate_memo

updating 1 sp
