### ISSUE TITLE
Bug: Unable to calculate team data Viz or data file in Data UI

### ISSUE THREAD

**Issue by dlkibbe** [lzim/teampsd#2723]
**Next team meeting _MTL_ Blue Session 3 is Mon, Sept 19 9am**

Data UI -  data set
On 8/23 and 8/30, I attempted to generate the team data file for team that would be uploaded to the SIM UI.
I received the same error message both times. Screenshot 1 (image 4 in title) is the first screen I see after trying to generate the file. When I click on details, screenshot 2 (image 3) is the details for the error. @jwklocek attempted to do the same on 8/30 with the same dataset and received the same error.

<< Paste screenshots here>>

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/31182258/187671591-905029eb-b63d-4d53-821b-b839f3e98882.png)

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/31182258/187671516-2fc839e7-73f2-4721-94a7-cafbd7ae1c02.png)

1. When was the bug discovered? On 8/23 - two attempts early a.m. and early afternoon and 8/30 about 12:30 pm

3. Is this an invidivual or shared world? Not in SIM UI, in Data UI/Power BI

5. What is the name of the experiment? Not an experiment.
 
**2. Click on the right:**  
i. **Pipelines** - prioritize in a TeamPSD (& Workgroup) pipeline  
ii. **Assignee** - @jamesmrollins  
iii. **Label**- assign workgroup (lead) responsible for tracking the task. If this is a bug, add "Bug" label.   
iv. **Projects** - assign to domain-specific TeamPSD tracker (issues, features, document, manuscript, team)  
v. **Milestones** - select monthly sprint milestone within the workgroup   
vi. **Estimate** - Estimate task in complexity points   
vii. **Epics** - assign to team-wide epic and TeamPSD master plan project  
iix. **Releases** - assign to key team release grouped with other relevant issues  

**3. If you anticipate that your **issue card** or **bug card** will have **dependencies** these can be added once the issue has been submitted.   
ix. **Add dependencies** - assess for and add dependencies *blocking* & *blocked by* this issue

**Comment by KimCase123** [comment]
@jeffhoerle discussed at *9_12_22 8am workflow* with @lzim

@jeffhoerle - @lzim is wondering if you can help us troubleshoot this bug.  We could use 2pm workflow meeting to discuss or we can resolve asynchronously.

@dlkibbe we moved this bug to the research bug tracker (issue num)

**Comment by lzim** [comment]
@emilymetcalf114  & @lzim 
Discussed at **hq_workflow** 09/22/22

#adjucate_memo
Discussed how much time this took for our **IIR Aim 3 Costing**

@dlkibbe & @jwklocek 
_How much time do you think this bug took you two work on (thank you 🙏🏽 !)?_

We want to track your effort for @claradismuke 's work on costing.

**Comment by dlkibbe** [comment]
My estimated time is 1.25 hours from first discovery to my email last night.

**Comment by emilymetcalf114** [comment]
#adjudicate_memo
@emilymetcalf114 and @lzim discussed at **hq_workflow 9/22**
adjusted the effort to 9 story points divided between the facilitate team. support_workflow story points tracked on #430.
