### ISSUE TITLE
wk4 oct_epic Story B: Dynamics Jenn transition plan, Emily M and Emily P can't access CRM

### ISSUE THREAD

**Issue by emilymetcalf114** [lzim/teampsd#2730]
@lijenn  to add @emilymetcalf114  and @epearman  to our current # of seats in CRM. 
Story B - Dynamics 365

DECISION
- [x] How: Transition permissions & workflows
- [x] How: Dynamics App tracks _MTL_ activities

Mon
10AM dynamics - on your own time or office hours

Wed
11AM - support_workflow

Thurs
*8AM-10AM training_workflow

**Comment by emilymetcalf114** [comment]
Error message has changed: several weeks ago, when navigating to mtl.how/crm, @emilymetcalf114 saw a message that I didn't have access. Now I see this: 
![image](https://user-images.githubusercontent.com/111393225/197573059-56f5ea79-2fb7-4456-9361-1d6673254fd6.png)

**Comment by emilymetcalf114** [comment]
**Discussed at training_workflow wk4 Oct_epic** 
@lijenn @epearman @lzim @emilymetcalf114 

@lijenn to email Mimi/DTC team from mtl.help@va.gov to get Emily P and Emily M unblocked in their access to CRM Dynamics 365.

**Comment by lzim** [comment]
**Story B - Dynamics @lijenn Transition Planning**
**@lzim sent an email wk1 nov_epic** with this below to Bharath, Dawn & Mimi, @lijenn @emilymetcalf114  & @epearman about this. 

- [x] @lzim 
- [ ] @epearman has access
- [ ] @emilymetcalf114 has access

**Comment by emilymetcalf114** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-PSD-Workspace-5e4ac9bd8d388dfba6d9aef5/issues/lzim/teampsd/2730?planning-poker) with Zenhub @lijenn

**Comment by emilymetcalf114** [comment]
#adjudticate_memo
obtained access mid-Nov.
