### ISSUE TITLE
wk2 sept_epic Bug: SIM_UI not reading Data_UI team data file correctly

### ISSUE THREAD

**Issue by emilymetcalf114** [lzim/teampsd#2734]
During facilitate_Workflow on 9/6, @MattMoore2 mentioned how the data that the team has been looking at in the Data_UI and the data file uploaded into the Sim_UI look different. 

He pulled the data that @lzim helped out with the week before, and the data looks very different than what was seen in the psychotherapy model. Exceedingly high weird numbers that don't make any sense:

![image](https://user-images.githubusercontent.com/111393225/190021215-41f1b992-f633-49aa-b926-c93ad59b53f4.png)

He mentioned that they were able to go back to an older data file (from July 26) that was accurate enough for them to proceed, which looked like this: 
![image](https://user-images.githubusercontent.com/111393225/190021386-ee55be62-f230-4cca-8368-a7ac9b22f92b.png)

@dlkibbe mentioned that she has seen this happen to her too in the past, and she thought that last time the issue was the Sim_UI not reading the data correctly, and going back to the old data set should be fine. 

1. Discussed at facilitate_workflow on 9/6, not sure when @MattMoore2 discovered it initially. 
2. Shared world

**Comment by jamesmrollins** [comment]
@emilymetcalf114 This may actually be a data ui problem. To evaluate, we need to look at both files side-by-side. I will check it out and advise you.

**Comment by jamesmrollins** [comment]
@emilymetcalf114 I did a deep dive this morning and found a few things that may illuminate this problem.

1.  I believe the target team data file is empty.  This would cause the model to not operate correctly.  
2. What is an anomaly, however, is the model is returning values of any kind.  If the model is run in the client, it simply says "Need a value" for the "GetDirectConstants" function, In the sim, it should return a zero.
3. The sim appears to be loading a correct team data file just fine.  
4. So what doesn't make sense, logically, is that the sim loads one parameters file correctly, but not the other.

## No Team Data in clinic_selections File

![image](https://user-images.githubusercontent.com/30132017/190198468-6bc17868-e0cf-47c6-9509-e6259a09d335.png)

## Model Not Showing Zeros in the Data Variables

![image](https://user-images.githubusercontent.com/30132017/190198698-d6b0f26e-999c-4b55-a66f-051b8bf70b53.png)

## Sim Appears to Load Correct Team Data File Correctly

![image](https://user-images.githubusercontent.com/30132017/190199012-dbbd7158-52e9-4234-a8dd-45f9d700f464.png)

![image](https://user-images.githubusercontent.com/30132017/190198948-c3eb00c6-59b9-4e0c-b45d-0c789cd57e2d.png)

**Comment by lzim** [comment]
Thanks so much @jamesmrollins for your hard work on this!
I don't know the history for why Ok City tried to pull the version 2 file.

And, both faciltiators are out next week with @dlounsbu & @lzim covering next week.
We used the file that is working properly. 
So, I think we can close this bug, unless the team requires us to open again next week when we meet with them.

**Comment by hnorthcraft** [comment]
#adjuducate_memo @lijenn @lzim
can we update the SP?
