### ISSUE TITLE
i Text review

### ISSUE THREAD

**Issue by TomRust** [lzim/teampsd#274]
Hi @dlkibbe, @branscombj , @dlounsbu , @lzim ,

I've been updating the i-text, and would love your review and edits.  I've got SP and CC done now, and will be working on the other three tomorrow.  The sooner I can get your comments, the faster I can incorporate your suggestions into the other models' text. The files are [here](teampsd/resources/master_crosswalk/info/).

Thanks!
--TOM

**Comment by lzim** [comment]
Great! Thanks @tomrust :smile:
Can you update your link I’m getting an error??

**Comment by branscombj** [comment]
Yikes - the crunch-time. I will not be able to look at these until I get through with the last 3 batches of sessions 7-10, @TomRust

**Comment by dlkibbe** [comment]
@TomRust I'll look at them tomorrow. Focused on say scripts today.

**Comment by lzim** [comment]
FYI @TomRust @branscombj @dlkibbe @staceypark and @dlounsbu 
I was able to trace the path, not sure why it didn't work for me:
https://github.com/lzim/teampsd/tree/master/resources/master_crosswalk/info

**Comment by dlkibbe** [comment]
@lzim the link didn't work for me either. Thanks for sharing it.

**Comment by lzim** [comment]
I'm going to close this issue so that it can be discussed at
Master Cross-Walk - Check-out System #208 
Since, we need to get these to DEV on Monday :bowtie:
