### ISSUE TITLE
wk2_jan_epic BUG: Sim UI Shared World In Session Advances to end of Timeline

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2744]
Discussed at **support_workflow** 
_Note:_ Met at 3:30PM on Tues 09/27

@jamesmrollins @lzim @emilymetcalf114 

**Discussed the Sim UI behavior observed during co-facilitator prep today for Session 6 _MTL Blue_** 

- [ ] Shared World (observed)
- [ ] Individual not observed/tested
- [ ] Teams not observed/tested

**Observed when in the Session** 
Experiments Section
1. Pull up prior experiments & text 
2. Pulls up the text
3. Then runs to the end of the timeline on its own without us hitting "run."

#adjudicate_memo
09/27/22
We did not spend much time on this bug in co-facilitator prep.
So, we did not apply facilitate_workflow label.

**Comment by jamesmrollins** [comment]
Hi @lzim and @emilymetcalf114 

## I attempted to replicate issue in the OKC_TRS_Shared world

- [ ] Not able to replicate after 12 repetitions.  
- [ ] Returned the sim all the way to Home and Team Data reload each time.
- [ ] Attempted to load each experiment, none resulting in autorun feature :-).
- [ ] Asked @hirenp-waferwire to take a look. 

## Reviewed Meeting 

- [ ] Observed a module at 2 yr run out at time hack 1:49:34
- [ ] Did not observe the module in the run process.
- [ ] Noticed that text had been cleared from the text fields (was previously loaded with base case).
- [ ] Apparently none of the users in the session pressed the "Run" button.

**Comment by lzim** [comment]
Thanks @jamesmrollins for testing this 🤷🏽‍♀️ 

I'm wondering if we should keep tracking it on the board for now.
Or, if we should close it and re-open if we get a repeat of this behavior.

**KEY QUESTION: I wonder if we need multiple users to be logged in to the Shared World at the same time to replicate the behavior.**
_Was your test one user in shared world at a time?_
_Does that make sense?_

**Comment by jamesmrollins** [comment]
Hi @lzim and @emilymetcalf114 

- We should leave this card open for awhile.
- I did not test with multiple users.  
- Perhaps we can run a quick test during the Sim UI meeting today with your jinxed machine :-).

**Comment by lzim** [comment]
**@jamesmrollins discussed at hq_workflow wk3 oct_epic**

_What do you need from @emilymetcalf114 @epearman do test this?_

**Comment by jamesmrollins** [comment]
@emilymetcalf114  and @epearman, let's discuss this on Monday 10/24 an set aside 15 minutes in an existing ceremony (such as support_workflow) to conduct this exercise.  I can also be available at another non-ceremony time as well.  The main thing is the create the same conditions as @lzim had above when the sim advanced without her apparent command.
