### ISSUE TITLE
wk4_sep_epic_BUG: Agg model not loading

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2745]
## AGG Model Is NOT Running Properly in Sim UI

- [ ]  Rounding problem with experiment panel (see image 1 below)
- [ ]  Multiple server access call problems
- [ ]  Issue has been elevated to Forio.  
- [ ]  All other models are running fine.

## Rounding Problem In Experiment Panel

![image.png](https://images.zenhubusercontent.com/5e4eac12455ade27f3584cea/a106022c-01d9-4f89-a34a-0e1a23204cee)

## Server Side Issues

![image.png](https://images.zenhubusercontent.com/5e4eac12455ade27f3584cea/ae87463b-3295-44e5-aa69-f88bd9a1df7e)

## Network Issues

![image.png](https://images.zenhubusercontent.com/5e4eac12455ade27f3584cea/5de562ab-ce3a-4de6-94cb-e7d7492a5bcb)

**Comment by jamesmrollins** [comment]
@lzim and @emilymetcalf114 

## We got to the bottom of the problem with the Agg Model.

- [ ] The Agg model runs fine.
- [ ] The problem arose because the user (me) forgot that the highly capable Sim UI takes the Power BI export and reformats it so the model can read it (See first image). When I was uploading test model parameters, i was using already processed files. So the Sim UI double processed the files, which corrupted them and crashed the Agg model.
- [ ] The problem also arose because I was needing to name a team data file that was already uploaded for use in the Home dropdown of another team.  Again I uploaded a post-process file and corrupted it.

## Original Power BI Format

<img width="947" alt="image" src="https://user-images.githubusercontent.com/30132017/193198822-b28fe10c-1be3-4506-893b-6d3847834e25.png">

## Uploaded Team Data File Format (post processing)

<img width="708" alt="image" src="https://user-images.githubusercontent.com/30132017/193198908-1fbaa6fd-f2b5-40e2-b598-bec2758e0778.png">

## Corrective Action

- [ ] We are going to investigate a means to check the file format prior to upload from any of the Team Data upload points in the Sim UI. However, this may not be possible, so we may be limited to providing the user with a message that asks if the file is directly from a Power BI export.
- [ ] I am going to add in a file naming function to the Team Data upload points, so a user can identify a file already in the model directory for use within a different team.

**Comment by lzim** [comment]
Thanks for the work on this and the update @jamesmrollins 
I'm in the Team (AGG) Care module now for our _MTL 3.0 Blue_ team that meets next Thurs. 
Testing now and this is working okay for me, **I'll let the co-facilitators know in their prep-channel.**
Makes sense to implement file checking and naming protocols described above.

We need to coordinate documention: @emilymetcalf114  
**This should be covered in the manual along with instructions on naming & saving files for the team in their 
Microsoft Teams _MTL Team_**
_Can we cross-ref that issue task card for cleaning up and standardizing team files for each active team?_

Seems like this should be split into the respective issue task or feature cards and the bug closed.

**Comment by lzim** [comment]
@emilymetcalf114 
_Were you able to create an issue task card for backing up team data files?_ (see above)

We can close this when that task is created. Thanks!

**Comment by jamesmrollins** [comment]
Hi @lzim and @emilymetcalf114 
FYI @hirenp-waferwire 

- [ ] We are not able to check the file format and throw an error prior to upload; however,
- [ ] We are able to provide a warning flag at both the Facilitator Dashboard team data file upload and the Home page team data upload points (see below).
- [ ] It is available in Test Slow instance.
- [ ] What do you think about shortening the outgoing message, "Did this file come directly from a Data UI Team Data export?"

<img width="619" alt="image" src="https://user-images.githubusercontent.com/30132017/193836663-f6ce60bd-885a-4d5a-a3b3-5e61b8bfd33d.png">
