### ISSUE TITLE
sept_epic: PI Emergent Issues

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2746]
**PI Emergent Issues
sept_epic**

wk1
OOO

wk2
- [x] Update R & R Studio (3 pts)
- [x] RPDS evaluation (1 pt)
- [x] Call w/COS Cohen (1 pt)
- [x] Call w/Marcia Hunt (1 pt)

wk3
- [x] R&D Manager Update PAVIR, NCPTSD, Platforms, permissions (5 pts)
- [x] Manager DataOps Manager PIV, onboarding, laptop request, telework agreement etc. (3 pts)
- [x] NIDA P50 scheduling (1 pt)
- [x] NIH Data Sharing Webinar (2 pts)
- [x] ISDC plenary call (1 pt)
- [x] Swap transition planning (2 pts)
- [x] RPDS planning (2 pts)
- [x] Stanford Residency Recruitment (3 pts)
- [x] Stanford chat w/Carmen (1 pt)

wk4
- [x] Budget Meeting w/Marisela (2 pts)
- [x] R & D Manager REQ & reposting (1 pt)
- [x] Suicide Prevention Trials Database Scheduling (1 pt)
- [x] Cruden K01 Scheduling (1 pt)
- [x] Duke R21 scheduling (1 pt)
- [x] HENRI scheduling (1 pt)
- [x] NCPTSD Training Committee scheduling (1 pt)

**32 points** 
**Story H**

**Comment by hnorthcraft** [comment]
#adjudicate_memo thank you for the vs labels, is there a sp estimate? @lzim
