### ISSUE TITLE
oct_epic wk4: Reply to Dawn for CRM Wave 2 & Reopen CRM License Ticket

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2747]
Jenn will reply to Dawn to ask/confirm the following:
- [x] Confirm to deploy Wave 2 in a Dev clone
- [x] Ask why Prod instance is not showing up
- [x] Ensure Emily M. and Emily P. get access to CRM

**Comment by emilymetcalf114** [comment]
#adjudicate_memo
Emily M and P got access to CRM wk 2 nov_epic
Wave 2 instance deployed wk4_oct 
@lijenn tested extensively, needs to document effort - provide storypoints
cross-ref with #2730

**Comment by emilymetcalf114** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-PSD-Workspace-5e4ac9bd8d388dfba6d9aef5/issues/lzim/teampsd/2747?planning-poker) with Zenhub @lijenn

**Comment by lijenn** [comment]
Issue has been re-estimated and assigned epics and sprint, closing card.
