### ISSUE TITLE
Bug Data UI - Selected clinics not matching exported clinic list

### ISSUE THREAD

**Issue by dlkibbe** [lzim/teampsd#2751]
**1. Add description:** 
The blue team facilitated by @jwklocek and @dlkibbe (DK) with support from Carla Nappi  (CN) and Nate Askerlund noticed different numbers in the team data table results when compared across all 4 facilitators. We decided to compare clinic selections.  DK notified CN about clinics that were in DK's list but not in CN's list. She advised that those clinics were selected in her bookmark but were not appearing in her Excel export or in the View clinic selections tab. Two screenshots and the excel file are attached for reference. 
![CNappi View Clinic Selections tab screenshot 10-4-22](https://user-images.githubusercontent.com/31182258/194164397-e79f4d50-850b-444c-90c8-09451626ef48.png)
![CNappi clini
[Carla ALX Clinic List.xlsx](https://github.com/lzim/teampsd/files/9718992/Carla.ALX.Clinic.List.xlsx)
c selections screenshot 10-4-22](https://user-images.githubusercontent.com/31182258/194164401-c828f0da-7107-4cc6-b0f1-03072d18d0c5.png)

1. When was the bug discovered? October 4, 2022 - 7:00 pm 
2. Is this an invidivual or shared world? Neither, Data UI / Power BI
3. What is the name of the experiment? No experiment, data only.

**Comment by emilymetcalf114** [comment]
Differences in the selected clinics between facilitators is due to local operational changes to the clinic grid, both names and providers

Differences between the selected clinics and the view of selected clinics is due to zz'ed/inactivated clinics that were deactivated > 2 years ago (outside our timeframe) and drop off from our analysis
	
	I went through and compared these two lists of clinics in the data ui from the bookmark I made a few weeks ago - the clinics that are selected in the bookmark but were deactivated in Aug-Sept 2020 (outside of our 2 year window) drop to the very bottom of my list. These are all the same clinics that are no longer listed in the view of selected clinics tab. If I de-select them under clinic selections, they disappear altogether. 

	It seems likely that this is why the data didn't look like it was changing visually when John was switching between bookmarks - I wouldn't expect the data to change, if the only differences between clinic lists are names of clinics not being used in analysis either way (outside of the time window). 

	If we were looking at the names of clinics outside our time frame as a way to determine if carla's clinic selection list was updating as she switched bookmarks, we wouldn't have been able to tell.

**Comment by emilymetcalf114** [comment]
#adjudicate_memo
work completed in Oct, bug resolved.
