### ISSUE TITLE
oct_epic: Story B - Update the Agg Care Appointment Supply Data Notes Documentation in Data UI 

### ISSUE THREAD

**Issue by emilymetcalf114** [lzim/teampsd#2753]
cross_ref #2743 

The documentation needs to be clearer that:

CC, MM, PSY are using appt/wk for appointment supply (75%ile, etc.) in any given week
and
Team (AGG) care is using hrs/wk for appointment supply 

Clearly this documentation is not sufficient for facilitators to read it an understand what it is doing.
![image](https://user-images.githubusercontent.com/7454688/193331720-fdb5a42b-ce16-417c-a364-e3911774989a.png)

There is also a typo: says hours in the text but appt/wk at the end
![image](https://user-images.githubusercontent.com/111393225/194179018-097be604-9e87-4be4-b9ac-0037dea09608.png)

There is also a typo in the legend:
![image](https://user-images.githubusercontent.com/111393225/195182622-daa84b2e-79ea-457d-8989-beb906851249.png)

**Comment by lzim** [comment]
@epearman - Thanks for the legacy screenshot.
_We want to identify the best location of this information in Power BI and get it in PROD_

![image](https://user-images.githubusercontent.com/7454688/198398880-69e6ffab-bb58-4010-b100-d7635e578511.png)

- [ ] Change **appt/wk** to **hrs/wk** to be consistent with a calculation of the number of visits multiplied by the most common duration
- [ ] **Edit second sentence** [DRAFT TEXT BELOW]:
Visits of different durations were standardized to hrs/wk. Visit count medians were multipled by the most visit common duration of each type: 1 hr for Intake, Psy, EBPsy, & Group (6 pts per group), 30-minutes for CC & MM, and 15-minutes for team adjunct services. 

> array documented: 
select 'Appointment Supply (median)' as Label, [Intake] as intake, [psy] as psy, [ebpsy] as ebpsy, [cc]*0.5 as cc, [mm]*0.5 as mm , [adjunct]*0.25 as adjunct, ([group]*1.0/6) as 'group'

@jamesmrollins - **Need documentation to cover Other Services going to 0, when Intake flow is Revealed**
- [ ] Update [Session 6 SEE](https://github.com/lzim/mtl/blob/master/blue/session06/s06_learner/mtl_session06_see.md) documentation 
- [ ] Update [Session 6 SAY](https://github.com/lzim/mtl/blob/master/blue/session06/s06_facilitator/mtl_session06_say.md) documentation 

FYI: @emilymetcalf114

**Comment by epearman** [comment]
Documentation updated for Monday Blue MTL live team: in testing instance.

- [ ] @emilymetcalf114 Can you check the documentation on the [test ](https://app.powerbigov.us/groups/me/apps/857e87fb-976f-49b1-b84f-0f5dc8208e7d/reports/504dd198-86aa-40cf-9bfe-1e11ddb566b5/ReportSection2a8d7028dbe309a4e18e?ctid=e95f1b23-abaf-45ee-821d-b7ab251ab3bf) site?

**Comment by emilymetcalf114** [comment]
FYI @epearman 
**On 10/27/2022 after hq_workflow**
I checked 3 tabs in the test pipeline for the VISN mtg on Monday

- Team (AGG) Care tab - Legend
- Team Care Descriptions - Appointment Supply (median) 
- Team Care Details - Appointment Supply (median) 

All 3 are updated to be accurate and clear!

**Comment by emilymetcalf114** [comment]
10/31 - @emilymetcalf114 submitted a pull request to @epearman with
- [ ] updates to the session 6 SAY guide

@lzim 
I reviewed the session 6 SEE guide and SAY-checklist, and they do not provide any detail on measures or individual modules, so I couldn't find a good place to include this documentation.

**Comment by epearman** [comment]
This issue has been closed: 
- Any remaining functional requirements related to this ANDON are listed in the Training card crossref #2775.
- Production role of these changes across all VISN is tracked in crossref [455](https://app.zenhub.com/workspaces/team-psd-workspace-5e4ac9bd8d388dfba6d9aef5/issues/lzim/research/455).
