### ISSUE TITLE
wk3 oct_epic: Add both Emilys to Power BI enviornments and Deployment Pipeline

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2756]
Dependent on @emilymetcalf114 & @epearman submitting their power bi pro license first. 

- [x] Grant access to Dev, Test, Prod
- [x] Deployment Pipeline

**Comment by emilymetcalf114** [comment]
I submitted my pro license request 10/13- I believe @lzim has to approve, so that won't process until next week.
FYI @lijenn

**Comment by emilymetcalf114** [comment]
@epearman , this issue card can be closed, correct? Do you want to add detail on SP, milestones, etc?

**Comment by epearman** [comment]
@emilymetcalf114 

Yes this issue can be closed, directions for how to get added to all the appropriate Power BI workspaces, pipelines, and gateways are listed in  _7.12 Update the Modeling to Learn Power BI Data UI instances_ on the training_workflow channel (see step 9) and on Lucid charts _#2617_team_psd_3.0_workflows - 7.1 Manage DataOps & DevOps Workstream Permissions_
