### ISSUE TITLE
wk1 nov_epic:  QA TEST: Verify BUG, Simulation Automatically Advancing with Multi-players

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2763]
FYI: @lzim 

@emilymetcalf114 @epearman 

In #2744 Lindsey was seeing what appeared to be the simulation advancing to 104 weeks by itself.  Should require the user to click the "Run" button.  I ran several tests in the same _shared world but was not able to replicate the bug using any of the conditions below.  We need to verify the same with multiple players.

## TEST

Set up a multiplayer Sim UI environment and attempt to get the sim to automatically advance.  Run test with each module.

## Conditions
- With Multiplayer, one facilitator, one member, one team lead.
- When loading a saved experiment without text.
- When loading a saved experiment with text.
- When switching Team Data files.
- In each module shared world type (_shared and _team).

## Steps
1. James will set up a test environment and be facilitator.
2. Will assign EmilyM as team member, and EmilyP as Team lead.  
3.  We all login to the same Team world.
4.  James will lead participants through scenarios in "Conditions" above.
5.  Attempt to elicit the BUG.

**Comment by lzim** [comment]
@jamesmrollins  _Can this be closed?_

**Comment by lzim** [comment]
Discussed **wk2 jan_epic hq_workflow**
This can be closed.
