### ISSUE TITLE
wk4 oct_epic: ANDON QA TEST Appointment Supply DAX Code in 3.0 Release of Team (AGG) Care not consistent w/Prior Releases

### ISSUE THREAD

**Issue by epearman** [lzim/teampsd#2764]
ANDON #[2743](https://app.zenhub.com/workspaces/team-psd-workspace-5e4ac9bd8d388dfba6d9aef5/issues/lzim/teampsd/2743) Found that calculations for median appointment supply in the AGG care model did not properly translate form TeamPSD 2.0 to TeamPSD3.0. TeamPSD 3.0 data UI was calculating all appointments as 15 min (appts/week *0.25 = hrs/week) instead of the following array from TeamPSD 2.0:
![image.png](https://images.zenhubusercontent.com/63331eaba895626f74a7c3a6/b517974d-3a76-4dee-8d52-38aa7f350717)

## TEST
@emilymetcalf114 to compare the new Test Data UI with old Production Data UI and export updated dataset for Sim UI. 
@lzim to test the new exported dataset in the Sim UI

## CONDITONS
- Data refresh occurs monthly for parameters in the Data UI - @emilymetcalf114 make sure to load the Test and Production Data UI at the same time for comparison.

## STEPS
- [x] @emilymetcalf114 make the same selections on the Test and Production UI and compare the old appointment supply parameters with the new appointment supply parameters. 
- [x] @emilymetcalf114 Export the updated data sets for @lzim to test in the SIM UI
- [x] @lzim to test the new data export in the SIM UI.

**Comment by lzim** [comment]
**@lzim tested bc, exp1, exp2, exp3 in the Shared World with the 10/26 data for our Thurs s7 next week 11/3.**
- [x] Updated @theresaschmitz, Cindy & @KathleenDarchuk on co-faciltator prep-channel
- [x] Re-ran and **saved all 4 experiments in Shared World**

_Next Steps:_
- [ ] @lzim to test our Monday team and communicate w/ @dlkibbe @jwklocek @robert-askerlund & Carla
**PeopleOps Workstream**
- [ ] **Communicate update to the teams** (help w/this please @emilymetcalf114) about the **resolution of the ANDON** and **DECISION to re-convene next wee**k.
- [ ] **Review the saved updated results** and **update Q/H/F/D** refine understanding asynchronously
- [ ] **Edit the text and working conceptualization** accordingly on co-facilitator prep

**Comment by lzim** [comment]
**Discuss at hq_workflow wk4 oct_epic**
**Remaining from #2743** 
> - [ ] Describe Missed Appointment for Intake to 0 and provide rationale.
> - [ ]  [list task "functional requirements"] on documentation card Update the Agg Care Data Notes Documentation in Data UI  #2753

@emilymetcalf114 
**We'll complete the ANDON #2743 Scope, Alert, Communicate until resolved on the task list above.**

@epearman I believe we're ready for these steps:

> - [ ] [Publish to production](https://github.com/lzim/research/blob/master/data_ui/PublishingToPROD.md) once tested.
> - [ ]  Merge updated DAX code to GitHub - crossref https://github.com/lzim/teampsd/issues/2762

**Comment by emilymetcalf114** [comment]
Message from @epearman on 10/27 - 

Issues deploying from TEST to PROD and ran out of time. 

- [ ] @epearman to troubleshoot on Monday wk1 nov_epic  
- [ ] @emilymetcalf114 to communicate to Monday _MTL_ live session team 

FYI @lzim 

![image](https://user-images.githubusercontent.com/111393225/198692545-a478cdcc-e374-4ad3-8241-56d830ec3f37.png)

**Comment by epearman** [comment]
This issue has been closed: 
- Any remaining functional requirements related to this ANDON are listed in the Training card crossref #2775.
- Production role of these changes across all VISN is tracked in crossref [455](https://app.zenhub.com/workspaces/team-psd-workspace-5e4ac9bd8d388dfba6d9aef5/issues/lzim/research/455).
