### ISSUE TITLE
wk1 nov_epic story B: Jenn & Emily to search emails for correspondence with EES 

### ISSUE THREAD

**Issue by emilymetcalf114** [lzim/teampsd#2765]
@lijenn to search personal email for documentation with EES. Looking for:

- [x] confirmation that Tues and Thurs _MTL_ blue team session dates were loaded into TMS
NOTE: For this one, the only confirmation I have are the ones you already found/sent to me...

- [x] confirmation that lists of attendees were sent to EES to be registered for sessions 1-4 (both teams) 
- [x] confirmation that attendees were actually registered by EES for sessions 1-4 (both teams) 
- [x] Any emails that are discovered will be fwded to MTL.help@va.gov and to @emilymetcalf114 for tracking and documentation. 
- [x] @lijenn to estimate story points for this - edited to 5, took lots of searching.

@emilymetcalf114 will look for **emails and documentation in Teams channel** for how the team dealt with live teams not getting CEUs in a prior instance. 
- [x] we think that our Monday live session _MTL_ blue team did not receive CEU credits for sessions 1-3
- [x] this happened to a team once before. 
- [x] @lijenn thinks we have 2 options: 
  - [x] offer optional extra sessions at the end (@emilymetcalf114 looking for documentation of how we did this) 
  - [x] direct learners to the videos for CEU credits instead

**Comment by emilymetcalf114** [comment]
Hey @lijenn! 
_Do you know when you might be able to search your inbox for attendee correspondence from EES?_

We want to communicate to the teams as soon as possible about next steps and this piece is critical to understanding the scope before we move forward (blocking dependencies). 

Thanks!!!

**Comment by lijenn** [comment]
@emilymetcalf114 Apologies for the delay! I'll get this done today.

**Comment by lijenn** [comment]
@emilymetcalf114 Found and fwding Tuesday and Thursday S1-4 CEU confirmations right now.

Note for the first task: confirmation that Tues and Thurs MTL blue team session dates were loaded into TMS
For this one, the only confirmation I have are the ones you already found/sent to me. I couldn't find any other confirmations.
