### ISSUE TITLE
nov_epic: Bug - Story B - PTSD_OMHO_PBI_Daily failed to run on 11/1/2022

### ISSUE THREAD

**Issue by epearman** [lzim/teampsd#2777]
@epearman to look into this and scope the issue, especially if it continues for more than one day in a row.

**Comment by epearman** [comment]
#adjudciate memo - documentation on steps taken to resolve this bug and story points used are tracked in issue card #crossref #[461](https://app.zenhub.com/workspaces/team-psd-workspace-5e4ac9bd8d388dfba6d9aef5/issues/lzim/research/461)

**Comment by hnorthcraft** [comment]
#adjudicate_memo per comment above, efforts tracked to other card, marking as dup
