### ISSUE TITLE
jan_epic Story B: ILEAD MTL Live Red session part 1 accreditation renewal due Mar 2, 2023

### ISSUE THREAD

**Issue by emilymetcalf114** [lzim/teampsd#2783]
@emilymetcalf114 spoke with Joe Bloomquist on 11/15/2022. 
- Our current accredited brochure for live sessions will expire on March 2, 2023. 
- We can't schedule live sessions in TMS past this date until the accreditation is renewed. 
- We know that we will have a new project manager to work with starting in January. 

@lzim based on how long this has taken in the past, when should we start this process?

- [x] @emilymetcalf114 to add to EES_workflow agenda to scope out the requirements with Joe during wk2 dec_epic.

**Comment by emilymetcalf114** [comment]
Discussed with @lzim wk2 jan_epic during **ilead_workflow**
Story B,E,M -
- [ ] Re-accredit _MTL 3.0 Live Red and Blue_ as is, with committee - top priority Jan_epic for February deadline
- [ ] _MTL 3.0 Video Red and Blue_ record a set of completed videos (blue sessions 4-12, red 1&2) consistent with _MTL 3.0_ guides, but possibly abbreviated (session 5 -10: maybe not every module, maybe use case studies/use cases for each module, for example) backlog until at least March (after Emily P's vacation? since @lzim will be helping with coverage...) **Complete video recordings March - May**
  - [ ] ilead already has _MTL Blue_ session 1-3
  - [ ] @emilymetcalf114 to update story maps and make issue task cards 
- [ ] TBD what to do with _MTL 3.0_ Facilitator supports that Swap and Lindsey completed on Teams through _MTL 3.0 Blue_ session 3. 
- [ ] Want to get the _MTL 3.0 Facilitate Blue and Red_ brochures done (for any LIP to get licensure hours from Lindsey for facilitating _MTL_ at a VA facility) in June after the grant goes in. "train the trainer" or refresher. 2 brochures, 2 course codes, Lindsey as the only faculty.

**Comment by emilymetcalf114** [comment]
@lzim and @emilymetcalf114 met with ilead_workflow transition team on wk4 jan_epic
oriented new team to _MTL_ projects. Went over steps for re-accreditation. 
@emilymetcalf114 met with Annie a second time for 30 minutes to confirm details for re-accreditation. 

- [ ] _MTL 3.0_ Live Red sessions need to be renewed NOW
- [ ] _MTL 3.0_ Live Blue sessions are not due for re-accreditation until May 2024.
- [ ] _MTL 3.0_ Video Red & Blue need to be re-accredited by **April 2023**

**Comment by lzim** [comment]
#adjudicate_memo 

@emilymetcalf114  _Do we need to split this off as two cards one to cover jan_epic effort and one to cover feb_epic effort?_

Moving it to **feb_epic** since **jan_epic** is closed now. 
But, not sure how to cost the story points. 

Please bring to **hq_workflow** if you questions about how to handle this.

Thanks!

**Comment by emilymetcalf114** [comment]
#adjudicate_memo
updated this card to reflect Jan effort. 
Created new card to capture Feb effort, when this work was completed. 
#cross-ref #2887
