### ISSUE TITLE
Story B: Make a #2617 training video on how to add new facilitators as a fidelity rater in RedCap

### ISSUE THREAD

**Issue by emilymetcalf114** [lzim/teampsd#2784]
When facilitators review their fidelity results after a session, the graphs show a list of all of the facilitator's names. 
@emilymetcalf114 needs to be added to the list of displayed names. 

@lijenn - I'm not sure how to do this in redcap, maybe we can discuss at **training_workflow** in **wk5 nov_epic**?

**Comment by emilymetcalf114** [comment]
Hey @lijenn,
@lzim and I discussed this issue card today. 

**It would be great if we could create a quick training video on how to do this when we go to add me**

We can discuss (or even do this) during training_workflow this week or next week ( we will see how it fits in), or complete asynchronously. 

Thanks!

**Comment by lijenn** [comment]
@emilymetcalf114 I'm lots of issues with VA VPN lately so I can't get on RedCap. I'm working with IT to see what's going on.

_Can we do this at wk3 train_workflow with you sharing the screen?_
I can guide us through the instructions as we record.

**Comment by emilymetcalf114** [comment]
Hey @lijenn 
Thanks for the update. Yes, this plan works for me! Thanks!
