### ISSUE TITLE
2023_#story_b: FEATURE: Generate _mtl_ reports incrementally in the sim_ui

### ISSUE THREAD

**Issue by emilymetcalf114** [lzim/teampsd#2785]
There are two new requests for how we generate tt reports: 

- [ ] Produce incremental reports for each phase (tt1 partner, tt2 build, tt3 apply), while retaining the function of producing a tt1-tt3 cumulative report
- [ ] Produce the tt report PDF directly in the sim_ui after selecting and saving the variables, without navigating to mtl.how/menu. 

## Decision Meters - Cross Reference:

#2804 
#2951 
#2950 
#2949

### Check off requirements to verify progress through feature_tracker.
- [ ] 1. **DEFINE in work_breakdown**
  - [ ] a. **what & why** - **written definitions of requirements** in a **numbered checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** requirement definitions an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 2. **DESIGN** in **operations_to_do** and **research_to_do**
  - [ ] a. **what & why** - **_MVP_ of design** of requirements in a **algorithm map, wireframes or design** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** design **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 3. **DEVELOP** in **under_development** - "frozen"

  Task Cards:
  #
---
- [ ] 4. **TEST in functional_test**
  - [ ] a. **what & why** - **TEST requirements** using **testing_checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** via TEST **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 5. **PROD in done**
  - [ ] a. **what & why** - **_DOCUMENT_ feature** using **document_tracker** for the **5 D's.** 
  - [ ] b. **date & who** -  **DELEGATE**
    - [ ] **describe_learners** [Jenn & Rita]
    - [ ] **detail_facilitators** [Jane & Debbie]
    - [ ] **document_team** [Anthony]
    - [ ] **disseminate_scientists_va** [Anthony]
    - [ ] **depend_products** [hq & ees]
  
  Task Cards:
  #
---
- [ ] 6. **closed** - fully documented, trained and ready for the next release.

**Comment by jamesmrollins** [comment]
FYI @lzim 
Hi @emilymetcalf114  
I think I understand the second feature above, but the first one will require more explanation for me to understand.  There is a lot of flexibility already built into the report, so I may be able to accomplish what you want with the current design.  However, I think I might not fully understand the ask.

**Comment by jamesmrollins** [comment]
12/7 - As per Sim UI Meeting
- @emilymetcalf114  suggests holding this feature until further understandings about bookability can be determined by Team PSD.
- Sim UI Team will put this feature on hold until further notice.
- Reevaluate in Feb 23.

**Comment by jamesmrollins** [comment]
- [ ] Investigate reporting via PDF and PPT for specific tt report and site report uses.
- [ ] The tt report builder is onerous - investigate ways to simplify.
- [ ] Investigate why we are collecting research arm data in the "Team Setup"
- [ ] Executive Leadership Team (ELT), Primary Care Services (PCS) and Government Accountability Office (GAO). 
- [ ] The report will be used to support the facilitator, System SME and Site Team.
