### ISSUE TITLE
april_epic: Update mtl.how/team to include Emily P & orient her to ADM role in Sim UI

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2789]
Hi @jamesmrollins can you help with these tasks in **wk5 nov_epic** or **wk1 dec_epic**

mtl.how/team
- [x] @jamesmrollins orients @epearman Sim UI as an ADM user
- [x] @epearman addes her P.D. and photo to the new DataOps Manager at https://mtl.how/team

**Comment by emilymetcalf114** [comment]
@jamesmrollins 
@emilymetcalf114 
@epearman 
@hthrmarsh 

**wk4 2023_mar_epic training_workflow** 
Created training video covering:

- Adding users to administrative world in sim_ui
- Orientation to Forio Epicenter
- Adding Heather and Emily P (administrative access) 
- Updating Team PSD and _MTL_ Demo websites

#cross-ref #2875 and #2886
