### ISSUE TITLE
wk2_jan_epic: Create Growth Award Medallian for mtl.how/team

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2790]
@jamesmrollins Yesterday at **All Hands** we announced Jenn Li as our inaugural 2022 **growth award** winner.

Definition of the award:
The Team PSD **Growth Award** recognizes the mutual benefits of a team member whose professional growth was supported by the team, and whose personal growth then spurred overall Team PSD growth.

- [x] @jamesmrollins Please help create a new logo, which @lzim can help with and post to mtl.how/team

**Comment by jamesmrollins** [comment]
@lzim With pleasure!

**Comment by lzim** [comment]
@jamesmrollins 
Love the tree graphic, beautiful.
Approved!

Please edit the text to read:
For mutually beneficial individual and team growth

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire - Please add the medallion .png file (emailed separately) to the Team PSD Admin Web Page, Team PSD Award Winners section award drop down menu.

![image](https://user-images.githubusercontent.com/30132017/212180084-952f4c8a-da55-4384-9fd3-594dd81c6ead.png)
