### ISSUE TITLE
Story_F: QA TEST: Version Test Branch testing

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2803]
## QA Test and review of user documentation for Version Test Branch

- [ ] 1. Navigate to Team PSD Manual, chapter 7.13 update #2830 pull request for instructions.
- [ ] 2. Using the instructions, create a test_version branch going from _mtl 3.0_ to 4.0.
- [ ] 3. Monitor action to determine the function was completed successfully.
- [ ] 4. Navigate to the test version branch.
- [ ] 5. Inspect 5-6 files to determine if the replacements occurred as expected.

**Comment by epearman** [comment]
@jamesmrollins what are the next steps for this card? I saw it was planned for **wk1 jan_epic** on the story board. Is this still the case or does it need to be pushed back?

**Comment by jamesmrollins** [comment]
@epearman I'll put in a testing outline and we can get it done next week if you have time.

**Comment by emilymetcalf114** [comment]
@jamesmrollins Thanks! It would be great to see what the functional requirements are for this test too for next steps. Will this require meeting time for all 3 of us?

**Comment by epearman** [comment]
@jamesmrollins, @emilymetcalf114 and I have reviewed the directions in #crossref #2830 and we requested some changes. Once these changes have been made and clarified we will tests the actual test branch function. 

FYI @lzim
