### ISSUE TITLE
ASAP: DataUI missing Individual Face-to-Face Provider Clinics Thurs 9AM Pacific Team

### ISSUE THREAD

**Issue by cmnappi** [lzim/teampsd#2816]
@epearman - **This team meets next on Thurs 01/06/22.**

During MTL red session with cheyenne, several providers noted  some of their clinics missing. 

for example, the provider in the table below is missing his face to face clinics from the data UI. others indicated the same issue. 

 
![image](https://user-images.githubusercontent.com/30132017/208784828-759ad966-9f96-4ca3-b9e0-64b978d9109d.png)

**Comment by lzim** [comment]
- [ ] Review the Thurs 9AM Pacific Red Team Clinics File (in Teams Co-Facilitator Prep under [Files](https://dvagov-my.sharepoint.com/:x:/g/personal/lindsey_zimmerman_va_gov/ETQq69wEL8VEm3JAq8kiXEcBvOXD-F0wznNWch4ZlMJ4Og) and look for Individual clinics that are not **phone** or **VVC**.

**Comment by epearman** [comment]
@emilymetcalf114

**Comment by emilymetcalf114** [comment]
@cmnappi @epearman @lzim @dlkibbe 

I have gone through the data_ui and the excel list of clinics that the team lead provided us side by side. I was able to find every single clinic in the data_ui with the exception of the 2 in-person clinics for the provider listed above in the screen shot. All other provider clinics were found. 

While I was searching, I only limited to the Sta3n, I did not select divisions or any other criteria to narrow down the list. 

A few notes on finding clinics: knowing that they are reorganizing their clinics, some clinics may be de-activated and start with "zz". Some of the deactivated clinics were no longer linked to a specific provider, so they wouldn't show up if you are only searching by provider name. 

@epearman is going to continue to dig in to the PowerBI to see if she can find these two missing clinics. 

If Emily P doesn't find anything, it may be worth asking the team lead. It's possible there is something going on locally and she may be able to help.

**Comment by emilymetcalf114** [comment]
@cmnappi @dlkibbe @epearman @lzim 

There is one provider that does not come up at all in the data_ui when you search for her name (initials AW, BHIP 2). She is new, and when the team lead provided the spreadsheet of clinics, this provider was not listed, so we do not know the names of the clinics she took over. 

If we reach out to the team lead, we should ask her for the names of AW's clinics as well. 

@epearman, is this something that would update in the data_ui **daily, or monthly**? I'm curious when we would expect to see her in the data_ui once her clinics have been affiliated with her on the local level.

**Comment by epearman** [comment]
> @cmnappi @dlkibbe @epearman @lzim
> 
> There is one provider that does not come up at all in the data_ui when you search for her name (initials AW, BHIP 2). She is new, and when the team lead provided the spreadsheet of clinics, this provider was not listed, so we do not know the names of the clinics she took over.
> 
> If we reach out to the team lead, we should ask her for the names of AW's clinics as well.
> 
> @epearman, is this something that would update in the data_ui **daily, or monthly**? I'm curious when we would expect to see her in the data_ui once her clinics have been affiliated with her on the local level.

@emilymetcalf114 this would updated daily in the Data UI.

**Comment by epearman** [comment]
@cmnappi @dlkibbe 

For the provider mentioned above (initials BF). I noticed in CDW that their clinic CHY MH NP06, was inactivated over two years ago which is why it is not showing in the Data UI. 

As for their other clinic CHY MH NP06 INTAKE, it is active as of Jan 16 2023, so I am not entirely sure yet why it is not showing in the Data UI. I will look into this more.

**Comment by cmnappi** [comment]
Hi all - thanks for looking into this!

CHY MH NP06 had 47 visits in the past 60 days.
CHY MH NP06 INTAKE had 5 visits in the past 60 days.

Provider Bookability tool is showing these as existing clinics that are being used.

Carla M. Nappi, Ph.D.
National Mental Health Quality Improvement and Implementation Consultant (QIIC)
Office of Mental Health and Suicide Prevention (11MHSP)
VHA Central Office
***@***.******@***.***>
970-914-1305

Field Based: Grand Junction, CO
Suicide Prevention is Everyone's Business. #BeThere<https://www.veteranscrisisline.net/BeThere.aspx>.
***@***.***

From: epearman ***@***.***>
Sent: Thursday, December 22, 2022 9:22 AM
To: lzim/teampsd ***@***.***>
Cc: Nappi, Carla M. (she/her/hers) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [lzim/teampsd] ASAP: DataUI missing Individual Face-to-Face Provider Clinics Thurs 9AM Pacific Team (Issue #2816)


@cmnappi<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcmnappi&data=05%7C01%7C%7C533c1eff3f4d44e120af08dae438af5a%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638073229361676669%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=x%2Bv7ATuaD9q%2FztRa3KMQng6zaCNYkt4GaUCPcLUPgxk%3D&reserved=0> @dlkibbe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdlkibbe&data=05%7C01%7C%7C533c1eff3f4d44e120af08dae438af5a%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C638073229361676669%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yrgJma1ko0QoJN8lUXOmg6HW9gaBmWE%2B0B%2F2l6%2FoWqc%3D&reserved=0>

For the provider mentioned above (initials BF). I noticed in CDW that their clinic CHY MH NP06, was inactivated over two years ago which is why it is not showing in the Data UI.

As for their other clinic CHY MH NP06 INTAKE, it is active as of Jan 16 2023, so I am not entirely sure yet why it is not showing in the Data UI. I will look into this more.

-

**Comment by epearman** [comment]
@cmnappi @dlkibbe @emilymetcalf114 @lzim 

**_The issue has been resolved._** All clinics should now be showing **_with the exception of CHY MH NP06_** which has an inactivation date of over two years ago (this inactivation date would need to be changed locally for the clinic to appear in the DataUI). 

When I recently took over ownership of the PowerBI dashboards from my predecessor, it had unscheduled the automatic daily refreshes of the PowerBI dashboards that was happening earlier (this is a separate refresh process form our SQL server jobs) as such, the dashboards had not been refreshed to reflect the data in our servers since I last manually refreshed them on Dec 12, 2023. This is why the clinics were missing. I have now programmed the automatic daily refreshed and this problem will not occur again.

- [ ] @epearman make sure the programmed daily refreshed worked after returning from winter holiday on 12.28.2023

**Comment by epearman** [comment]
@emilymetcalf114 lets estimate our story points for this effort via planning poker on https://github.com/lzim/research/issues/491

**Comment by epearman** [comment]
We were not able to discuss this today at wk1 jan_epic **facilitate_workflow.** 

@cmnappi please let me know if you have any questions about this. Especially regarding clinic CHY MH NP06, which was inactivated over two years ago.

**Comment by emilymetcalf114** [comment]
@epearman even though the clinic was inactivated over 2 years ago, are you able to see in the system that it is still being used for scheduling appointments (like @cmnappi mentioned above)? Something about this seems off to me.

**Comment by hnorthcraft** [comment]
#adjudicate_memo per comment above, efforts tracked to other card, marking as dup
