### ISSUE TITLE
ASAP: Data UI dataMeas Check for GAD7 & CSSRS tab for Thurs 9AM Pacific Team

### ISSUE THREAD

**Issue by cmnappi** [lzim/teampsd#2817]
@epearman - **This team meets next on Thurs 01/06/22.**

The dataMeas section in the data UI did not include **GAD7** or **CSSRS**, both of which are used frequently by the site.

**Comment by lzim** [comment]
- [ ] Confirm that CSSRS is not in **dataHF tab** as it used be a Clinical Reminder, not a patient-reported outcome or MBC

**Comment by epearman** [comment]
Functional Requirements:



[ ] Check if GAD7 and/or CSSRS is in the dataMeas tab

[ ] Check if CSSRS is in the DataHF tab

What is CSSRS?

Are these CPT codes I am looking for?

**Comment by epearman** [comment]
#crossref lzim/research#497

**Comment by epearman** [comment]
# ABOUT GAD-7

**GAD-7 is not included in the DataMeas tab although it is available in the original data source (the measures domain in CDW)**

- [ ] I can quickly update the DataMeas tab to include this with approval from @lzim 

# About CSSRS

1.  CSSRS is in the Health Factors domain of CDW which is reflected in the dataHF of the Data UI.
2. There are no filters applied to the Health Factor Type field in this tab, so what you see there is all the data for the clinics selected. 
3. It looks like how the CSSRS is categorized in the HF domains varies greatly between locations. Please see the attached excel for all the possible different names given to the CSSRS in the HF domain in CDW.       

[CSSRS Health Factors.csv](https://github.com/lzim/research/files/10282686/CSSRS.Health.Factors.csv)

**Comment by epearman** [comment]
@cmnappi @dlkibbe @lzim @emilymetcalf114 

- GAD-7 has been added to the dataMeas tab across all VISNS.
- See note above regarding CSSRS.

**Comment by epearman** [comment]
@emilymetcalf114 lets track our story points for this effort https://github.com/lzim/research/issues/497

**Comment by epearman** [comment]
Discussed this today at wk1 jan_epic **facilitate_workflow.**

**Comment by emilymetcalf114** [comment]
@epearman is this issue ready to close?

**Comment by hnorthcraft** [comment]
#adjudicate_memo per comment above, efforts tracked to other card, marking as dup
