### ISSUE TITLE
Story B: Updates to MTL Manual - clearer instructions for submitting new bugs

### ISSUE THREAD

**Issue by emilymetcalf114** [lzim/teampsd#2820]
Discussed during facilitate_workflow on 12/20

- [x] lift out/make more obvious in the _MTL_ manual to assign new bugs to the **bug tracker**. 
- [x] Add details or screen shots/instructions to follow the new issue **template** in github, what are the critical steps for facilitators/occasional users? 

![image](https://user-images.githubusercontent.com/111393225/208722339-55fde7b9-d6c9-4006-83a4-bb4f93006cb1.png)

![image](https://user-images.githubusercontent.com/111393225/208753476-c8a50c20-3b51-415a-afd8-1ae2540c2bdd.png)

**Comment by jamesmrollins** [comment]
@emilymetcalf114 

## You want to improve this one?

![image](https://user-images.githubusercontent.com/30132017/208755942-fad42a86-3b5d-4d8a-bb83-de13c2ba9d2b.png)

## and potentially, this one?

![image](https://user-images.githubusercontent.com/30132017/208756890-1d38def4-62fe-476c-bd86-11a871bc09e0.png)

## There is also one for reporting a bug in the research repo.

**Comment by emilymetcalf114** [comment]
Hey @jamesmrollins 
Yes, I think section 2.3 is especially important to update, so that's the section I would prioritize, but all 3 should probably be updated for consistency.

**Comment by jamesmrollins** [comment]
Hi @emilymetcalf114 - I have added instructions for bug reporting in the mtl manual in chapter 7 - Facilitator Tech Manual.

See pull request #2799 for details.
