### ISSUE TITLE
jan_epic: Is BHL captured in the Data UI?

### ISSUE THREAD

**Issue by epearman** [lzim/teampsd#2829]
@epearman to see if BHL is captured in the Data UI. 

FYI: @cmnappi @emilymetcalf114

**Comment by epearman** [comment]
@cmnappi @emilymetcalf114 I am seeing some health factor categories indicating referral to BHL. Please see attached list below for all BHL values I found in the CDW health factors table. These are the items I would look for the dataHF tab. 

Please let me know if you have any question about this.

**Comment by emilymetcalf114** [comment]
@epearman 
did you see @cmnappi's question in the teams channel about this? 
"In BHL, staff members enter Measurement Based Care  assessments. Would the data entered there also go into DataMeas tab?"

**Comment by epearman** [comment]
@emilymetcalf114 thanks for this question. @lzim mentioned that she thinks this is the case. The next steps will be for Lindsey to connect with her BHL contact so that I can confirm this. 

- [ ] @lzim connect @epearman with BHL contact.
