### ISSUE TITLE
wk3 jan_epic: Review Team PSD manual for content to user story mapping

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2831]
- [ ] Review Team PSD Manual for content related to conducting user story mapping.

**Comment by jamesmrollins** [comment]
@epearman @emilymetcalf114 - 

## Findings

I reviewed the Team PSD Manual and did not find an instruction set for how the Program Board is used for programming capacity and integrating with issues in GitHub. 

## Recommendations

- [ ]  Publish a chapter that explains how the Program Board is organized.
- [ ]  Explains how stories budget capacities of participants by story and then allocates that capacity over the coming months by workflow.
- [ ] Illustrates how to read the board both _horizontally_ and _vertically_ to find dependencies and identify opportunities to program work.
- [ ] Illustrates how to link issues on the program board, to issues in the feature/bug/zenhub trackers.

**Comment by lzim** [comment]
**Discussed at 8AM_workflow Leads  wk4 jan_epic**

@lzim 
@emilymetcalf114 
@epearman 
@jamesmrollins 

Lindsey outlined her recommendations for what to cover in this training
[See User Story Mapping & SAFe here](https://teams.microsoft.com/l/message/19:09778e4391404920a8a20c7ef4ec3de3@thread.skype/1675095428897?tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf&groupId=1db500d5-0d01-4254-af42-ad3f78bafacd&parentMessageId=1670344725699&teamName=teampsd_vha&channelName=all_teampsd&createdTime=1675095428897&allowXTenantAccess=false)

_Next Steps:_
- **training_workflow** wk1 feb_epic
@emilymetcalf114 & @epearman Record the review of these skills.

**Comment by epearman** [comment]
Closing this card since this activity was completed. Efforts to create training materials will be tracked at #crossref #2863
