### ISSUE TITLE
Jan_epic: Ctrl + click to select group of clinics in Data UI 

### ISSUE THREAD

**Issue by epearman** [lzim/teampsd#2833]
This was feature asked about by the MLT red Thursday 9am team.

- [ ] What are the requirements to produce this feature?

**Comment by epearman** [comment]
- [ ] @epearman attend PowerBI office hours to see if this function is possible

**Comment by hnorthcraft** [comment]
#adjudicate_memo assigning 1 sp to reflect efforts (documenting ask and powerbi research)
