### ISSUE TITLE
wk1 Mar_epic: TeamPSD All staff presentation March 14

### ISSUE THREAD

**Issue by emilymetcalf114** [lzim/teampsd#2837]
- [ ] **Team PSD presentation at NCPTSD Staff Meeting NEXT week on Tues 3/14/23 at 2PM Eastern/11AM Pacific**
 
PRACTICE wk2 2023_mar_epic Mon at 4:30PM Eastern/1:30PM Pacific 
PRESENT wk2 2023_mar_epic Tues at 2PM Eastern/11AM Pacific - Next Week
 
Limit to no more than 3 slides per presenter (2 min per slide) = 42 min update w/6 minutes per presenter.
 
Would be great for all to be able to present their own slides, but we can cross-cover as necessary !
 

- @lzim - 
**Themes** OMHSP pivot, OMHSP DEISC Data & Disparities, health equity, hawaii 
**Organization & timelines** - Team PSD Enterprise SAFe, Mgmt Trio & Data Science Hire
**KPIs**
- @hthrmarsh  - Present R&D Manager User-Persona Slide, Portfolio Overview & Key Objectives for Health Equity Grant (mar-may & jul-sept).
- @emilymetcalf114 - Present PeopleOps Manager User-Persona Slide & Key Objectives for Story B progress on enrollment DSMB updates, pivot, Present the Hawaii PAR cadence and Hexagons
- @epearman (on vacation) - @lzim to Present DataOps Manager User-Persona and NIH Data Sharing, Authorship_App Prior Work Data from GitHub, Next steps related to Health Equity Prototypes.
- @dkngenda  - Present User-Persona Slide & Updates and next steps related to Research Findings & Data Feed Development
- @claradismuke  - Present User-Persona Slide & Updates on Aim 3 Cost Aim
- @jamesmrollins  - Present Decision Dashboard Prototype

Slide deck for editing can be found under files in our all_teampsd channel on teams under presentations: 
![image](https://user-images.githubusercontent.com/111393225/223565860-3b80799f-8906-4b78-ad96-dbe5be9f592c.png)

**Comment by dkngenda** [comment]
@emilymetcalf114 @lzim 

I've uploaded the two slides requested for on this card. Happy to get any feedback on those so I can make appropriate edits. 

... Were we supposed to meet to go over these?? Not seeing an ongoing meeting now :)

**Comment by emilymetcalf114** [comment]
@dkngenda 
@jamesmrollins 
Are you available to join the Teams Mtg at 10:50am to discuss the presentation at 11am? 
See meeting link in quant_workflow post. thanks!

**Comment by emilymetcalf114** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-PSD-Workspace-5e4ac9bd8d388dfba6d9aef5/issues/lzim/teampsd/2837?planning-poker) with Zenhub @hthrmarsh @jamesmrollins @lzim @dkngenda

**Comment by hthrmarsh** [comment]
Thanks @emilymetcalf114! I'll refrain from voting since my effort and participation was quite minimal and I can't see the full scope of this yet.
