### ISSUE TITLE
update say guides with tips

### ISSUE THREAD

**Issue by emilymetcalf114** [lzim/teampsd#2838]
Discussed during _MTL blue_ session 12 prep and sim_ui_workflow wk2 jan_epic

- [ ] QIICs found that nothing was coming up in data_ui datatabs under filters. They needed to click on the table first for the filters to come up. @emilymetcalf114 checked the Say guides and this tip is not documented. 
- [ ] Additionally, for clinic selections, we need to add tips on using stems for search terms, with examples and screenshots, to make the clinic selection list. 

@emilymetcalf114 to add to:
- [ ]  blue session 2 say guide
- [ ] red part 1 say guide

**Comment by lzim** [comment]
#adjudicate_memo - Stale card #wontfix

**Comment by hnorthcraft** [comment]
#adjudicate_memo updating to 1SP
