### ISSUE TITLE
feb_epic: Story B Dat UI Bug - Cannot Select More than 1 clinic in viz tabs

### ISSUE THREAD

**Issue by dlkibbe** [lzim/teampsd#2841]
**1. Add description:** 

Focus: @cmnappi and I are working with a single site that has 5 BHIP Teams. 

Issue: In the data UI, viz tabs, Clinic name -> providers drop down menu, only 1 provider name can be selected at a time.

Description: Helpful to have a feature that allows for selection of multiple providers in the Clinic name -> providers drop down menu. 
A provider may have 5-10 clinics in which they are coding for services. This feature would be helpful if we do a clinic selection for the entire site (more than 100 clinics) or if we are working  with 1 BHIP team in the site (approx 5 providers with 20-25 clinics).
Request: *Is it possible to add the shift + select option in this drop down menu so we can select all of the clinics associated with a single provider so the viz trends represent that provider or that a team or providers?*
(Screenshot has provider names blacked out)
<img width="502" alt="Screenshot - provider dropdown menu" src="https://user-images.githubusercontent.com/31182258/212134630-d72b5160-dc8a-4057-8c62-4ffcec27f46b.PNG">

<< Paste screenshots here>>
1. When was the bug discovered? Not a bug - just a request for a feature. Prep session 1/12/2023 in Data UI
2. Adding this feature would allow all MTL facilitators to support teams in selecting a 
3. Is this an invidivual or shared world? NOT SIM UI
4. What is the name of the experiment? NOT SIM UI

**2. In order for Team PSD to track this issue you must assign
- [ ] issues/bugs -  Select **bug_tracker** under project, on the right to initiate tracking a Bug.
- [ ] features 
- [ ] manuscript 

**3. Support Workflow:**  
i. **Pipelines** - prioritize in priority pipeline  
ii. **Assignee** - assign to a workflow user  
iii. **Label**- label value stream and workflow 
iv. **Milestones & Epics** - select monthly sprint milestone (GitHub) & epic (ZenHub) within the workgroup   
v. **Estimate** - estimate task in complexity points   
vi. **Epics** - assign to team-wide epic and TeamPSD master plan project  

**3. If you anticipate that your **issue card** or **bug card** will have **dependencies** these can be added once the issue has been submitted.   
viii=. **Add dependencies** - assess for and add dependencies *blocking* & *blocked by* this issue

**Comment by epearman** [comment]
Update 1/26 during Thursday MTL Red session: we CANNOT select multiple providers on vizEnc and vizHF - the other viz tabs you can (you can select multiple providers on the Flag tab but when you hit apply nothing happens to the data)

**Comment by epearman** [comment]
@dlkibbe Due to current settings on PowerBI, **_to select multiple providers in the viz tab you need to use `ctrl+command+click` or `ctrl+command+click` for PC_**.

The same goes for any of these selection menus in the Viz tabs. 

Please let me know if you have any questions about this. 
FYI @lzim @emilymetcalf114

**Comment by epearman** [comment]
Next Steps: Ensure that multiple selections can be made without have to use  `ctrl+command+click` across all slicers across all visuals.

**Comment by epearman** [comment]
Bug is resolved, testing is tracked in #2879
