### ISSUE TITLE
wk1_feb_epic bug: data_ui vizFlag graph not changing after adjusting filters

### ISSUE THREAD

**Issue by emilymetcalf114** [lzim/teampsd#2848]
**@cmnappi reported in VA Red team prep on 1/18/2023:** 
Team meets next tomorrow, 1/19, but this bug should not impact the meeting. 

"When selecting Clinic Name - Providers on the vizFlag tab, a filter does not occur - the data stays exactly the same as if all clinics were selected."

@emilymetcalf114 replicated this phenomenon with the same team, another team within the same visn, another team within the same consortia, and a completely different team, all with the same results. 

**Data_ui: In the vizFlag tab**, when making any selections in the "clinic name --> Providers" filter, and applying the filter, the graph does not change. 

The graph does not change if you adjust the "VisitDateTime" slider either. 

![image](https://user-images.githubusercontent.com/111393225/213326492-4cf3622d-1234-4fcc-ac84-1d1fac168d0e.png)

**Comment by epearman** [comment]
Will review this issue during PBI office hours **wk1 feb_epic**

**Comment by lzim** [comment]
#adjudicate_memo

This is still open. 
_Should it be tracked with effort in both jan_epic & feb_epic @epearman ?_
- [ ] @epearman please add story points estimate for this task so we can scop.

**Comment by epearman** [comment]
@lzim no effort was made on this bug in Janurary.

**Comment by epearman** [comment]
Solution:

1. Navigate to the model
2. Find the relationship between visits and patients and double click the line connecting the visits and patients table. 
![image](https://user-images.githubusercontent.com/67978478/217918391-9094b4f7-53b3-4705-bbe1-4e5094ce6f51.png)

3. Under Cross filter direction select "both" and press "ok"
![image](https://user-images.githubusercontent.com/67978478/217918700-d96bbc63-4e7f-48e8-80e6-37e560324ac8.png)

**Comment by epearman** [comment]
I also noticed that the DateTime slicer was not filtering in the vizMeas or the viz Flag tab for the same reason, Due to a one way relationship in the model. I changed the relationship between the Visits table and the Dimlocation table to both ways and the dates are also filtering now.

**Comment by epearman** [comment]
Bug resolved and in Testing see #2879
