### ISSUE TITLE
wk4 jan_epic: Story J, A2 and A3: Updating the IIR data pipeline tracker 

### ISSUE THREAD

**Issue by epearman** [lzim/teampsd#2849]
The[ IIR pipeline](https://app.powerbigov.us/groups/me/apps/8c88035e-be54-40c7-90f4-726514d5f0cc/reports/fa9dda80-aa4e-4082-8eda-4685edb0d518/ReportSectiona0927ee2070705ecaa35?ctid=e95f1b23-abaf-45ee-821d-b7ab251ab3bf) is showing R01 measures of Systems thinking skills and learning Organization. 

![image.png](https://images.zenhubusercontent.com/63331eaba895626f74a7c3a6/b740979a-5c5a-4d9c-bdae-964eaa900ff8)

You can see the IIR measures [here] for reference (https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/evaluation/measures.md)

@dkngenda when do you think you would be able to look into this? Do you need any help or discussion around this before hand?

**Comment by dkngenda** [comment]
@epearman @lzim 

Below are a few verification questions just so am sure am pulling data correctly.
- At baseline, we only have 4 responses on demographic and burn-out questions for two blue teams 
![image](https://user-images.githubusercontent.com/66848852/214375963-ee54f4d7-4faf-450a-ad5b-de3a05f11325.png)
- Some teams do not have coplan survey data but have rater information (e.g v06_558_durham). Is this correct
![image](https://user-images.githubusercontent.com/66848852/214366292-48e14e9d-0042-4b6c-912b-d64d92084b80.png)
- Some teams had two versions of the same questions (e.g v16_502_alexandria). Which versions should I use?
- Among blue sites, only Chula vista CBOC has had a live session so far?

**Comment by epearman** [comment]
Question: **Where there other scales administered at baseline?**
Update: Folder names were changed so the R01 data dashboard was not refreshing - David N has fixed this and the data is refreshing. 
Update: EBP reach and fidelity surveys are not in the IIR pipeline at the moment because data needs more work. 


![image](https://user-images.githubusercontent.com/67978478/214395897-75486f32-97ce-4b77-b445-a8a8b96ad9ff.png)

**Comment by epearman** [comment]
#ajudicate_memo - closing this issue and tracking feb efforts for it on lzim/research#531
