### ISSUE TITLE
BUG Sim UI CC Module: Engagement Duration is not an array, should not be "Card Stack" in Main Model Diagram

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2850]
@emilymetcalf114  
@epearman 
@lzim 

@jamesmrollins - Discovered this when talking about **health equity level aggregation** (VACO, VISN, sta3n, sta6a, team), and **system dynamics modeling stock (state) mixing** (link the **time to the decision-making**, because that what the model informs: daily, weekly, monthly, quarterly). Decisions by different people, in different contexts what's the relevant intervals of time, rates of time, valid observation over time, accumulation over time.
 
**wk4 jan_epic vapor meeting**
![image](https://user-images.githubusercontent.com/7454688/214441283-c2f93071-e6a2-4f98-a3df-e8ace8abb5b6.png)

**Comment by jamesmrollins** [comment]
@lzim FYI

@hirenp-waferwire  please investigate Lindsey's findings and correct. The controls icon should be a single control, not a stacked control. Thank you.
