### ISSUE TITLE
Feb_Epic: Bug Sim UI Team (SP) Flow: Cannot scroll and close the MH Continuum View

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2853]
**Identified at vapor wk4 jan_epic** 

@emilymetcalf114 
@epearman 

@jamesmrollins 
I'm on my VA GFE using Chrome and findings that I can't scroll up enough to close the MH Continuum view. 

![image](https://user-images.githubusercontent.com/7454688/214454598-ce2c64d8-3719-427f-a06d-21c2f9bd10cb.png)

**Comment by jamesmrollins** [comment]
@lzim @epearman @emilymetcalf114 @hirenp-waferwire 

## Problem

The Stepped Care pop up is a free window that can be moved around on the main system diagram in Team (SP) Flow tile. To move the window, the user must grab the popup header space with a click and then drag popup to desired location.  However, if the user drags the header _underneath the main system diagram header_ the popup header will disappear, and the user can no longer manipulate the popup. Furthermore, the slider on the right of the main system diagram does not allow the user to move the main system diagram up to reexpose the popup.

## Solution

- Make it impossible to move the popup header beneath the main system diagram header.

**Comment by lzim** [comment]
#adjudicate_memo

jan_epic is closed - moving to feb_epic, _but not sure if there is effort to track across both months ??_
@jamesmrollins 
FYI
@epearman 
@emilymetcalf114
