### ISSUE TITLE
wk_5 2024_jan_epic: FEATURE: Dynamic Decision Dashboard

### ISSUE THREAD

**Issue by ghost** [lzim/teampsd#2854]
## Benefits Hypothesis:

The Stock Infographic supports the OMHSP Pivot to "Bookability" with respect to conforming with bookable hours and appointment length standards.  Also support the use case where the Sim UI is used to support the Build Capacity phase from the start of the relationship with the user. Systems view and understanding is reinforced through the use of functional causal diagrams accessible directly from the home page. Navigation to more detailed model dynamics over time are accessible from the home page.  

## Functional Requirements

- [ ] Show where veterans are (where is the volume across all the modules?).
- [ ] Would replace the partner phase - showing the initialization of all the models at once. 
- [ ] Show stocks of all modules in one infographic (MM, CC, PSY, AGG, Team (SP) flow).
- [ ] Ability to show a causal diagram with charts that would illustrate relationships between variable. 

## Non-functional Requirements

- [ ] Support multiple levels of aggregation from VISN to sta6a.
- [ ] Support multiple time denominators (week/month).
- [ ] Support multiple model runs (episodes) at the same time.
- [ ] Support standard scales between modules and widget.

**Comment by jamesmrollins** [comment]
@hirenp-waferwire 

- [ ] Review attached wireframe.
- [ ] Using the Episode Run API developed in last sprint, provide return values to stocks as shown in the wireframe.
- [ ] Note there is some deliberation about how to handle different measures of time (weeks and months) that may be handled by the webpage. 
- [ ] Navigation to any Episode would be handled by the Play button as shown.
- [ ] Navigation to the Synthsim pop up would be handled by the Feedback button.
- [ ] "i" information would be made available as in the module.

## Wireframe

![image](https://user-images.githubusercontent.com/30132017/217961947-f3f1be6b-c65f-40c8-b758-eaf88d789221.png)

[Decision Dashboard.pdf](https://github.com/lzim/teampsd/files/10702375/Decision.Dashboard.pdf)

**Comment by jamesmrollins** [comment]
@epearman FYI

## Status Update:

- After much investigation, we determined that we must upgrade to V 3.0 for managing Groups, World and Users.  
- This will affect login and facilitator dashboard.
- We are not sure what else in the Sim UI will be affected.  Thus, we are going to start with Login, then test for functionality regarding episode / world ID detection and management. 
- Then we will assess the affect on experiments retrieval. This is a concern.  However, Forio indicates that we should not have any issues with V3 reading V2 World ID.

## Way Ahead

- When the login issue is resolved, then we will move to running all 5 models at the same time.
- A working prototype should be available shortly thereafter.

**Comment by jamesmrollins** [comment]
FYI: @epearman @emilymetcalf114 @hthrmarsh 

## Latest drawing 

![image](https://user-images.githubusercontent.com/30132017/227028306-fb7c4f4b-0151-4d85-9d0d-9f438842dc99.png)

**Comment by epearman** [comment]
Q1: Is there a requirement to show inflow and outflow in the stock diagrams?

**Functional Requirement:**
- [ ] In Dynamic Decision Dashboard, we have our three units of time: 
    1. patients/week 
    2. appointments/week
    3. episodes of care/week 
- [ ] We can see the stock volume across all five common care problems.

**Non Functional Requirement**
- [ ] Need to prepare for Health Equity module (6th module).
- [ ] Stocks ARE standardized to time because all in weeks.
- [ ] Widget that will come from the 5 modules.

**Comment by epearman** [comment]
@jamesmrollins can I confirm if the Dynamic Decision Dashboard is available on mtl.how/sim_test yet?

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire Please see below for changes to the Dashboard:

## Standardize Widget Scales

**This is the number one priority.**  For patients and appointments, we need a standard scale on the widgets that gives supports judgement of the relative size of the numbers in comparisons across modules.

![image](https://user-images.githubusercontent.com/30132017/230497844-8c1148a9-9da0-4d93-ab1e-aeec43a6f114.png)


## Change Report Title

![image](https://user-images.githubusercontent.com/30132017/230496890-afb62e3f-405f-4116-bf66-ac0610c931af.png)

## Change Section Title

![image](https://user-images.githubusercontent.com/30132017/230498026-c410c939-b513-4a29-ace2-21ca33b9bfbe.png)

**Comment by lzim** [comment]
### Discussed at sim_ui_workflow wk3 2023_apr_epic 

**DECISION**

### Applies to Sim UI
- [ ] **DEV** @jamesmrollins will ask Hiren to hard code @lzim username and password for DEV
- [ ] **QA_TEST Card** @emilymetcalf114 @epearman

**Comment by epearman** [comment]
Update from**wk3 apr_epic 8am_workflow** 
@lzim 
@jamesmrollins 
@hthrmarsh 
@emilymetcalf114 

Likely waste and rework for anyone to be thinking they will TEST this until. 

- [ ] @lzim signs off on whether the standardization and scale functional requirements are approved.
- [ ] May need time with David L, David N on this too.

**Comment by jamesmrollins** [comment]
Cross Reference: lzim/research/ #681

**Comment by ljmoody** [comment]
Hi @jamesmrollins, checking in on the status of this card. I see it's blocked by #2968. Is that still the case? If not, is it possible to close this issue since DDD is being tracked by:

#2979, clear meters of performance in dashboard
#3029, test
#3032, train
#3030, document
#3023, tutor prompt wireframe for DDD

**Comment by lijenn** [comment]
I agree with Laura's comment above. The overall DDD is completed and we are waiting on those issue cards and data file access #3091.
