### ISSUE TITLE
Story B Data UI VIZ chart lines are differing colors among users for the same variable

### ISSUE THREAD

**Issue by ghost** [lzim/teampsd#2856]
Feature Requested during MTL Red Thursday live session. The VIZ chart lines are different colors between users. Shouldn't the same colors be applied to the same variables so that when users are logging in they will see the same visual?

**Comment by epearman** [comment]
Functional Requirements:

- [ ] Replicate but with @emilymetcalf114 
- [ ] Ask about this feature during wk1 **feb_epic** PBI office hours

**Comment by epearman** [comment]
Where users selecting the exact same variables on the filters, or different variables, or were no variables selected at all?

**Comment by epearman** [comment]
This [blog ](https://radacad.com/set-power-bi-data-color-all-visuals-to-follow-same-color-for-the-same-data-point)provides a work around using DAX coding, you need to make a table specifying each color for each variable across all of the visuals, I would estimate several story points.

**Comment by hnorthcraft** [comment]
#adjudicate_memo closed as not planned marking with 1sp
