### ISSUE TITLE
Feature - Create a CC Sythsim pop up prototype in JavaScript

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2873]
## Benefit Hypothesis

The Synthsim popup prototype will validate whether it is possible and feasible to load a browser executable causal diagram of a given module (i.e., CC, MM, Team (AGG) Care, PSY, Team (SP) Flow). This will enable the end user to use a visual tool to explain the direct and inverse effects of feedback loops within the module. The tool will be dynamic, allowing the end user to manipulate the feedback loops and showing the effects in all variables in the system.

## Functional Requirements
- [x] Client execution of a model in browser.
- [x] Provides sliders to manipulate causal feedback loops.
- [x] Uses charts to illustrate the direct or inverse effects of the feedback.
- [x] Provides a simple causal diagram to illustrate the system.

## Non-functional Requirements
- [ ] Can toggle between weekly and monthly time denominators.

**Comment by jamesmrollins** [comment]
@hirenp-waferwire 

- [ ] Review attached spreadsheet.
- [ ] This is an example of a "hand integration" process that uses time sequenced arithmetic to achieve the function of an integral. 
- [ ] The diagram is a web page (popup) with charts and sliders to manipulate the data table.
- [ ] The data table is not a part of the pop up.  It would be in the background.

[Syntysim.Prototype.xlsx](https://github.com/lzim/teampsd/files/10702454/Syntysim.Prototype.xlsx)

**Comment by epearman** [comment]
#adjudicate_memo moving to the backlog until blockers are removed.
