### ISSUE TITLE
wk_1_feb_epic_story_B: Feature -  Configure the Epicenter API to allow simultaneous model runs under the same group id

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2874]
## Benefit Hypothesis

To provide base case results of all stocks in the _MTL_ suite of modules, an episode tier must be added, so multiple world ids can be associated with a single Group ID.  This will allow the models to run within their own episode, while maintaining security and group access.

## Functional Requirements

- [x]  Configure the Epicenter APIs in a manner so that they can run all models at the same time.
- [x] Return the results of the model run to the browser instance.

**Comment by epearman** [comment]
@jamesmrollins I am trying to close out Feburary epic, can this issue be closed?
