### ISSUE TITLE
wk?_feb: Feature (enabler): Review UAD bookability

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2876]
Discussed at **wk1 feb_epic** **sim_ui**

**DECISION**
Hold on this issue since we need to review and align it with UAD and bookability
#crossref #2851 - ASAP Due Bug: Re-Review the Binning of Encounters for Time Assumptions
**1. Discussion - Evaluate in relation to UAD - bookability and labor mapping - wk1_feb mixed_methods**     

- [ ] @jamesmrollins review UAD [bookability](https://teams.microsoft.com/l/message/19:bfdf92c7846542b58e9961e1d8cc671e@thread.skype/1675184739642?tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf&groupId=1db500d5-0d01-4254-af42-ad3f78bafacd&parentMessageId=1675184739642&teamName=teampsd_vha&channelName=support_workflow&createdTime=1675184739642&allowXTenantAccess=false)
- [ ] @emilymetcalf114 review UAD bookability
- [ ] @epearman review UAD bookability
- [x] @lzim review UAD bookability

///////////////////////////////////////////////////////////

## Reference Support_workflows

- [UAD Bookability Presentation](https://teams.microsoft.com/l/message/19:bfdf92c7846542b58e9961e1d8cc671e@thread.skype/1675184739642?tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf&groupId=1db500d5-0d01-4254-af42-ad3f78bafacd&parentMessageId=1675184739642&teamName=teampsd_vha&channelName=support_workflow&createdTime=1675184739642&allowXTenantAccess=false)

## Benefits Hypothesis

Review of the Bookability policies will enable designers to understand the affects the new policy may have on data_ui, models, and sim_ui.  Key emphasis will be on units of measure, labor flows and other indications of capacity management.

**Comment by lzim** [comment]
_Are folks tracking UAD through the  link to MHOC Dynamic Labor Mapping and QIIC Consultative Topics?_

@jamesmrollins 
@emilymetcalf114 
@epearman 
@hthrmarsh

**Comment by hnorthcraft** [comment]
#adjudicate_memo updating to 1SP
