### ISSUE TITLE
ICEBOX #health_equity_contract: As a SSME, QIIC, MH Leader, I need MHOC standard info reflected in the Team Flow Model.

### ISSUE THREAD

**Issue by ghost** [lzim/teampsd#2881]
![MicrosoftTeams-image (8).png](https://images.zenhubusercontent.com/63331eaba895626f74a7c3a6/6b9964cf-2141-424a-8cc5-64afe1ffa927)

We currently have our supply_demand_ratio variable in the sim UI as (unique patient/Unique LIPs). However, OMHSP has published work (see above) and MHOC dashboards that report the staffing ratio the other way around (i.e. 7.72 LIPs/1000 pts)

- [ ] @jamesmrollins to update the sim_ui supply_demand_ratio in SP flow variable to match OMHSP staffing ratio. 

We can discuss this more during wk4 feb_epic **sim_ui_workflow**

**Comment by epearman** [comment]
![image.png](https://images.zenhubusercontent.com/63331eaba895626f74a7c3a6/a61f2ece-d5c8-404a-905e-117568f58737)

**Comment by epearman** [comment]
![image.png](https://images.zenhubusercontent.com/63331eaba895626f74a7c3a6/a61f2ece-d5c8-404a-905e-117568f58737)

**Comment by epearman** [comment]
**sim_ui wk4 feb_epic** - Locations of supply dmeand variable in the sim ui

![image.png](https://images.zenhubusercontent.com/63331eaba895626f74a7c3a6/62988311-e093-4cb3-9c38-5d3fe82dfa88)

![image.png](https://images.zenhubusercontent.com/63331eaba895626f74a7c3a6/2a540394-f5fe-4c0b-9d55-727b0ab93b1c)

**Comment by jamesmrollins** [comment]
@epearman 
@lzim 
@emilymetcalf114 

## Observations

1. The model variables support an estimation of the effect the Total Management Patients and Patient Load have on care quality. 

![image](https://user-images.githubusercontent.com/30132017/222560348-a22c4714-30dd-4a1c-ab43-750dcb1d3dca.png)

2. There is no representation of the number of providers in this part of the model. 
3. If the MHOC goal stated above is now ground truth, do we want to set up a user variable that expresses the staff to patient relationship as a ratio, and warns them if they are below SPR of 6.97, or a rewards them if they get to 11.39 or above?  
4. The paper does not really describe the relationship between the service or provider type and staffing ratios.  Perhaps that is built into the SAIL composite measure? If so, how does SAIL derive that composite?  
5. The paper indicates thresholds for staffing ratios against SAIL performance. However, it does not illustrate the acceleration of the change between the range of the thresholds ( from <6.96 to 7.74 to >11.39).  What does that curve look like? This may be important with respect to calibrating the sensitivity of the effect of the ratio change, relative to the incremental position on the slider.

**Comment by lzim** [comment]
@jamesmrollins

**It appears that this card is tracking the Sim UI side and Data UI is tracked in #2881**

Unrealistically listed in **mar_epic** adjusted to **may_epic**

_Note:_
- [ ] @jamesmrollins & @epearman 
_Where is source value for "User GMH Total Manageable Patients" if it is not listed in Team (SP) Flow in Data UI (see #2881)?_

_Note:_ Appears that this is following the manuscript, but **not the MHOC Sharepoint within VHA domain.**
- [ ] Align with the MHOC data feel through @lzim coordination with OMHSP PERC and Dr. Boden.

**Comment by jamesmrollins** [comment]
@lzim 
@emilymetcalf114 
@dlounsbu 
@epearman 

## Observations

- [ ]  Variables in the Team SP Flow model need to be adjusted to use MHOC reports.  @lzim suggested we start with the MHOC Quarterly Report - By Facility variables (See illustration 1 below.). Other report illustrations are available in [Teams/quant_workflow/Files/covariates_staff_supply folder](.  
- [ ] These variables will modify the variables we currently use in the model around the Care Quality Reinforcing loop, including Patient Load, Total Manageable Patients and Sensitivity to Patient Load. See illustrations 2 and 3 below.
- [ ] Key dependency with #2884 for potential team data modification and direct constants mapping.  

### Illustration 1 - Quarterly Report

![image](https://user-images.githubusercontent.com/30132017/225757437-c53826dc-9fbc-42d5-8b21-af721265c226.png)

### Illustration 2 - Team SP Flow Model Reinforcing Loop

![image](https://user-images.githubusercontent.com/30132017/225757094-9b3ce28b-ffd0-4d4b-a58e-e2013b3f07e8.png)

### Illustration 3 - Vensim Model Area Requiring Modification

![image](https://user-images.githubusercontent.com/30132017/225757281-3fc0f576-bbc6-4c36-b0a4-101cb2d909c7.png)

## Actions

- [ ] @dlounsbu could you take a look at the [Team SP Model](https://github.com/lzim/mtl/blob/master/blue/mtl3.0_models/sp_i_v4_2022_02_17.2.mdl) and estimate your work content please? Please let me know if I can help you in any way. 
- [ ] @jamesmrollins will provide updated webpage design based on model modifications for system diagram, Team Data Table and "i" information popups.
- [ ] Review "i" information for variables to align with MHOC definitions. 
- [ ] @epearman is evaluating Team Data feeds in #2884.

**Comment by jamesmrollins** [comment]
## Sim UI Workflow 5/3/2023
- [ ] We are NOT developing to MHOC because of data latency.
- [ ] Need to focus on fluency with BHIP and MHOC, their similarities and differences.
- [ ] Don't have a clear way forward at this point.

**Comment by lijenn** [comment]
Moving this to upcoming epic since this looks related to #health_equity.

**Comment by lzim** [comment]
wk1 2024_06 Scoped by #wontfix or develop 
#adjuciate_memo - 5 story points to reflect the work scoping this out.
