### ISSUE TITLE
wk2_jun:  Team PSD Team & Demo Website are not current for MVP Slide Deck Review w/Partners

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2886]
@hthrmarsh 
@emilymetcalf114 

_Will you two make sure there is an open issue card to update https://mtl.how/team please?_

There are at least these updates needed: 
- [x] Remove Kim Case
- [x] Add Heather to Research Map & Leadership Section
- [x] Add Emily P to Research Map & Dev Map & Leadership Section
- [x] Remove R&D Manager search

- [x] @jamesmrollins Please clean up this image on the site
![image](https://user-images.githubusercontent.com/7454688/225168172-830179e0-62ec-43da-8e15-f5a2b8bb9b1b.png)
- [x] Update Leaders map to reflect Management Trio, remove Jenn and Kim Case.
- [x] Double-check that grey is VHA style grey
- [x] Update “Facilitators” Map to say “Trained Systems Experts and Modeling Consultants”
- [x] Add Growth award winner in 2022, Jenn Li, with relevant medallion.
- [x] Add Team award co-winners in 2022, Emily M & Emily P for "For Helping Team PSD to achieve more than the sum of its parts during a transition an unexpected gap in Management Trio Staffing."
- [x] Operations Partners map needs to be relabeled "Education"
- [ ] @emilymetcalf114 Add Anne from ILEAD and any other updated ILEAD partners 

#adjudicate_memo - functional requirements from duplicate card #crossref #2875
- [ ] Add the link to the Data Scientist USA Jobs job post when available
- [x] Update the Maps & Sections to reflect the updated terminology and roles of Team PSD members, e.g.,:

**Comment by emilymetcalf114** [comment]
#cross-ref #2875
some duplication between issue cards to reconcile

**Comment by emilymetcalf114** [comment]
@jamesmrollins 
- [ ] How do we add **new valuestreams and workflows** to the website?
- [ ] Where are the map images saved? I think the title of each map is in the image itself, correct? So to update the title text, the image needs to be updated
  - [ ] We also need to check the grey color (see above) 
- [ ] How do we update Awards to list the new Growth Award, with icon
![image](https://user-images.githubusercontent.com/111393225/228917437-0f51ba24-79ba-41c5-a858-e98c67265e52.png)


@hthrmarsh 
- [ ] Add Sam for VAPOR

**Comment by emilymetcalf114** [comment]
@lzim 
Is there a blurb already written up for Jenn's 2022 Growth award that we can use for the site?

**Comment by jamesmrollins** [comment]
@emilymetcalf114 

- [ ]  The types of Value Streams are standardized, so you can only add it as an association to a Workflow (see below). The only reason for the Value Stream selection is so the computer knows what color to assign.

![image](https://user-images.githubusercontent.com/30132017/228970668-02642ea9-02ec-4b12-9b0e-7ce164f6af91.png)

- [ ] Workstreams are similarly standardized, but you can add resource rows to a given workflow.

![image](https://user-images.githubusercontent.com/30132017/228970035-75a0f6ff-601a-4222-9431-aeba33d7778b.png)

- [ ] Images are saved on [GitHub](https://github.com/lzim/teampsd/tree/master/resources/slider_maps) and I have updated the "Facilitate" map to say, "Consult and Facilitate." I've also provided a copy in this post.
- [ ] The gray above is actually VA Navy Blue at 75% opacity.  I had to decrease the opacity to make the text of people readable.
- [ ] I am not sure about your awards question. It appears you have mastered that:

![image](https://user-images.githubusercontent.com/30132017/228963392-aa91446f-19d8-4829-a101-1dbb2e2e26f9.png)

- [ ] ![consult_facilitate_map](https://user-images.githubusercontent.com/30132017/228967348-415918f6-38bb-4e37-9422-1d1383c969d9.png)

## Notes:

1. If we want to rename the workflows, we will need to put in a feature request.  It is a very small change, so can send it through breakfix. 
2. Navy blue was reserved for the Facilitators on the map sliders.  I have already renamed it Consult and Facilitate.

**Comment by hthrmarsh** [comment]
Updated Sam on the Team MTL website - I sent her an email asking for a picture with better resolution since the one on the site is blurry. If she sends one along, I'll swap it out.

**Comment by hthrmarsh** [comment]
Updated Sam's photo on the website.

**Comment by hthrmarsh** [comment]
@lijenn 
Can you provide us with a blurb for why you won the 2022 Growth award that we can use for the site?

**Comment by lijenn** [comment]
@hthrmarsh Give this a try:

Jenn’s 3-year track record starting off as Health Services Research Assistant to becoming a Development and Operations Manager on Team PSD reflects a strong career trajectory by growing for the team through increased levels of scale, impact, and leadership.

**Comment by emilymetcalf114** [comment]
I have added Jenn's award description to the website.

**Comment by lzim** [comment]
**#mgmt_trio**
- [x] @lzim removed the posting for the R&D Manager from the Team site **wk1 2023_may_epic** -1 pt

@hthrmarsh 
@emilymetcalf114 
@epearman 
@jamesmrollins 

There are several checkboxes of requirements above that look to still be open.

_Is this ready to close?_
_Do we need to inventory whose responsibility it is to update the Team Site?_

I don't think it's current for some partners, like ILEAD.
It doesn't have the SAMSHA grant details either.

_What are the story points estimated spend on this to date?_

**Comment by hthrmarsh** [comment]
- [ ] Added Sam to the Research map. 
- [ ] Removed duplicate entries for Heather M and Emily P (under leadership and value stream sections)

**Comment by hthrmarsh** [comment]
@jamesmrollins 
- [ ] Add Kate Macia to Team PSD page under Co-Is. 

**Bio:**
Kathryn Macia, Ph.D., Co-Investigator. Dr. Macia is a Research Health Science Specialist at the HSR&D Center for Innovation to Implementation (Ci2i) and National Center for PTSD (NCPTSD) Dissemination and Training Division at VA Palo Alto Health Care System (VAPAHCS). She has been involved in VA research since 2012 and recently completed a VA Advanced Postdoctoral Fellowship in health services research at NCPTSD and Stanford University, following the completion of her Clinical Psychology PhD. Dr. Macia has a strong background in Veteran homelessness and mental health including trauma/PTSD treatment, health services research, and quantitative methods. She has a high level of expertise in advanced statistical methods and analysis of data relevant to the current project, which has included leading and consulting on topics relevant to data analysis for RCTs and other funded research projects. 
Picture:
- [ ] @hthrmarsh to send

**Comment by jamesmrollins** [comment]
Hi @hthrmarsh - Will update when I get the picture.

**Comment by hthrmarsh** [comment]
![KathrynMaciaPicture.jpg](https://images.zenhubusercontent.com/6408f6bee4d68058a5b2cf6b/d0177951-c37f-45a1-a0a4-7d406d5d65f4)

**Comment by hthrmarsh** [comment]
Thanks @jamesmrollins!

**Comment by jamesmrollins** [comment]
@hthrmarsh  Done deal!
