### ISSUE TITLE
april_epic Team PSD team_time (tt) Newsletter Revival for apr_epic & may_epic

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2889]
### Management Trio Develop Team PSD _Weekly_ Newsletter for April (then May)

Located [here](https://dvagov.sharepoint.com/:w:/r/sites/teampsd_vha/Shared%20Documents/General/teampsd_team_time_report/2023_apr_epic_tt_report.docx?d=w1b76e1483d1d41fe854486d0061bd3dc&csf=1&web=1&e=0ZPR5p)

- [ ] **Icon** https://github.com/lzim/teampsd/blob/master/resources/logos/tt_title.png
tt1 team_time
tt2 team_time
tt3 team_time
tt4 time_time

@lzim 
@hthrmarsh 
@emilymetcalf114 
@epearman 

**wk1 apr_epic** 

### Assignments for developing the sections for the month of April are below:
- Monthly newsletter - Provide the view/orientation for the key deliverables whole month.
- Each Monday highlight the weekly specifics for what needs to occur that week.

- [ ] @lzim & @hthrmarsh Education/Growth
- [x] @hthrmarsh Portfolio
- [ ] @hthrmarsh & @epearman & @lzim Research
- [ ] @emilymetcalf114 Operations
- [ ] @epearman for Development

#### After 8am_workflow leads to account for any 

- [x] Use **value stream standard colors** and **order**
- [x] List the relevant **Management Trio** and/or Lindsey
- [x] **Provide links** to the workflow, resource (OSF), meeting link

_Below are examples of the updates needed for each of our 5 value streams_

#### Education/Growth (orange)
- **Story H** – Data Scientist process
- **Key external dates:** Conferences; Annual VHA updates, CDIAS, IRI
- **Mentee dates:** Dissertation dates, etc.

#### Portfolio
- Key deadlines for the next **upcoming grant submission**
- Key **annual reports**, IRB, annual updating

#### Research
- Every key **#health_equity_gran**t meeting (monthly; **co-Is**)
- Every paper milestones (**3 priority papers: mar_epic**/R21; **apr_epic**/fidelity; **may_epic**/cost)

#### Operations
- Every **R01/IIR MTL Co-planning** Meeting with our 30 sites incl. ILEAD
- Every **SAMSHA Cadence** Dates & Point Person, Activity

#### Dev Cadence Milestone
- **DEV/TEST/PROD/TRAIN cadence** milestones 
- **mar_epic** tt_reports
- **apr_epic** #health_equity sankey

**Comment by emilymetcalf114** [comment]
- [ ] start with introductions to the #mgmt_trio with pictures and roles (use screen shot from the Team PSD website)

**Comment by epearman** [comment]
#ajudicate_memo did not finish the april newsletter in time. 

- Will publish a may newsletter #crossref #2952

**Comment by lzim** [comment]
**2023_apr_epic** **team_time** not sent.

**Comment by hnorthcraft** [comment]
#adjudicate_memo assigning 1 sp to reflect efforts
