### ISSUE TITLE
ASAP Management Trio can add to Team PSD SAFe Manual without synchronous support

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2891]
### Managment Trio Can Independently Update the Team PSD Manual 
- [ ] @epearman 
- [ ] @emilymetcalf114 

#### Review instructions for Contributing to the Manual 
https://lzim.github.io/teampsd/2-use-and-contribute-to-this-manual.html

- [ ] Cross-Ref: #2891 To update the leave guidance in **Team PSD SAFe Manual**

**Comment by lzim** [comment]
Closing this card referencing specific team members.

This cross-cutting skill will be covered for all Team PSD members at the 11/02 training_workflow.

**Comment by hnorthcraft** [comment]
@lzim #adjudicate_memo

Please update sp estimate.

Thanks!
