### ISSUE TITLE
wk1 2023_apr_epic MTL SIM UI TEST and PROD Bug: Website is not loading on Chrome on Lindsey's VA GFE machine

### ISSUE THREAD

**Issue by epearman** [lzim/teampsd#2894]
**1. Add description:** 

**Added that this is happing at the log in to** 
- [ ] https://mtl.how/sim
- [ ] https://mtl.how/sim_test
- [ ] @lzim Chrome VA Laptop on GFE 
- [ ] @lzim Edge VA Laptop on GFE 

During **consult_facilitate_workflow** we saw that the sim UI Test site was hung. We got a runtime error and the website would not load (see image below for error thrown when trying to load in Google Chrome). 

![image](https://user-images.githubusercontent.com/67978478/226681453-4adc4e2d-afa2-4eab-9c48-37741fa92c23.png)

Affecting the review #2835 

Lindsey could not log in but David L was able to log in.

**Comment by jamesmrollins** [comment]
@epearman Use the Devmodelparameters team data file and it will work.

**Comment by lzim** [comment]
#### Management Trio review the Team PSD Manual and training_workflow video on Bugs and check off when complete

[Team PSD Manual](https://lzim.github.io/teampsd/16-track-issues-bugs-features.html#report-a-bug-via-github-to-improve-modeling-to-learn-resource)
[training_workflow](https://teams.microsoft.com/l/message/19:d15133fbfb4d4c3a8c81701292b1890d@thread.skype/1655308697615?tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf&groupId=1db500d5-0d01-4254-af42-ad3f78bafacd&parentMessageId=1655308697615&teamName=teampsd_vha&channelName=training_workflow&createdTime=1655308697615&allowXTenantAccess=false)

- [ ] @emilymetcalf114 
- [ ] @epearman 
- [ ] @hthrmarsh 

### _Note_: From **systems_sme** **wk3 mar_epic**
@jamesmrollins 
@dlkibbe 
@dlounsbu 
@emilymetcalf114 
@epearman 
@hthrmarsh 

1. This bugs requires navigational information reported in the bug to be squashed.

2. When reporting the Bug report that it occurred on the log in screen.

3. Without this information James responded about Data uploads within the Sim UI.

#### Also Follow-up on the Bug 
@jamesmrollins 

1. I believe in reviewing the **systems_sme** transcript (I led another call during the review) that this Bug resolved in the background for @dlounsbu 

2. Managers help Team members to close this loop.

**Comment by epearman** [comment]
@jamesmrollins, David L and Emily M were able to log onto their Forio account on mtle.how/sim_test using Chrome. However, I was not able to get a response from the "login" button when trying to log into my Forio account on mtl.how/sim_test.

Upon pressing 'login' I got no response form the webpage using chrome (see screenshot below).

![image.png](https://images.zenhubusercontent.com/63331eaba895626f74a7c3a6/666d7902-5b61-4e08-91f1-1422bc70e5d9)

**Comment by jamesmrollins** [comment]
@epearman 

I looked at Epicenter and you have not registered as a Facilitator in the Test project.  So you don't have a login. 

1.  Click on "Facilitator Registration" and complete the form.
2. This should take care of the problem.
3. Please try it again after registering and see if it resolved the problem.  If not, let me know in this thread.

Thank you,
James

**Comment by epearman** [comment]
@jamesmrollins Thanks for the help I am now able to log in. 

@lzim do you want to see if you are still getting a runtime error when logging into mtl.how/sim_test before we close this bug?

**Comment by lzim** [comment]
**Update from prep for the DEISC presentation to Dr. Campbell**

No, this bug is not resolved for me.
**I cannot access mtl.how/sim or mtl.how/test_sim in Chrome.**
But, I can 

- [x] @epearman okay on all 4 (test, prod, chrome, edge)
- [x] @dlkibbe

**Comment by lzim** [comment]
Check the **temporal pieces** of when this is being access.
Check the **regional pieces** for variation by local VA OIT.

**Comment by jamesmrollins** [comment]
> Check the **temporal pieces** of when this is being access. Check the **regional pieces** for variation by local VA OIT.

@lzim I'm not sure how to do this kind of checking.  We could start by putting in a ticket with OIT at Palo Alto.  It appears to be isolated to your laptop, so maybe they can check using your IP.  In the meantime, I will ask Forio to see if they have any evidence of your sim_ui userID call reaching their server.

**Comment by epearman** [comment]
Thanks @jamesmrollins, would Forio be able to see if a server connection from Lindsey's ID was made on Chrome specifically? Because she has been able to log in on Edge just not in Chrome. 

I might also recommend that @lzim test her login on Edge on different machine if possible.

**Comment by jamesmrollins** [comment]
@epearman I consulted with Forio and they indicated their servers didn't log any errors during the time that Lindsey was attempting login.  If Edge is logging in and Chrome is not, that would eliminate a communication error from the gateway.  I would say it is a cookie issue.  Sometimes, they just get in the way.  She might try logging in again and clearing her cache for the site:

![image](https://user-images.githubusercontent.com/30132017/230155910-52d2a8ec-f179-4a4a-8b01-c10a93bf49c7.png)

**Comment by epearman** [comment]
Discussed in **wk1 2023_apr_epic at support_workflow**

- [ ] Directions for clearing site specific caches should be in the TeamPSD and MTL manual if not already

**Comment by lzim** [comment]
@jamesmrollins 

@epearman 
**#data_ops_workstream** 

FYI: @emilymetcalf114 
**#people_ops_workstream**

### Need the general Forio Login & PW to work in the **DEV** instance of the **#sim_ui** to align with for these **user_workflow**
- [ ] #mgmt_trio
- [ ] #systems_sme_workflow
- [ ] #support_workflow

### World login in fixed location on landing page makes this look "hung" when it may not be; Need responsive dsign for zooming in/out as screen sharing facilitators
- [ ] https://mtl.how/sim_test (TEST)
- [ ] https://mtl.how/sim (PROD)

_Zoom in we can't find the world menu:_
![image](https://user-images.githubusercontent.com/7454688/231221520-b87756f8-b6d8-4da7-844e-4b04eb6ecea7.png)

_Zoom out to find:_
![image](https://user-images.githubusercontent.com/7454688/231220155-9853770a-b320-4101-b4fe-b353c40e476b.png)

**Comment by jamesmrollins** [comment]
@hirenp-waferwire please review the above. When zoomed in, world selection should be responsive and show in the screen.

**Comment by epearman** [comment]
FYI @jamesmrollins 

I tested the new feature in chrome on all three below: 
- [ ] Sim DEV - looked like photo below - I was zoomed in and still saw the world selection prompt. 
- [ ] Sim Test - had not "select world prompt" automatically logged in
- [ ] Sim PROD - looked like photo below - I was zoomed in and still saw the world selection prompt. 

![image.png](https://images.zenhubusercontent.com/63331eaba895626f74a7c3a6/4d360f33-0b86-424c-8bbf-74b96f693810)

**Comment by jamesmrollins** [comment]
@epearman that was the solution to the zoom problem regarding World Selection.  It is operating as designed.

**Comment by epearman** [comment]
@jamesmrollins great I am going to close this issue then. Thanks James and @hirenp-waferwire
