### ISSUE TITLE
Zenhub trial is ending, need to decide what type of subscription to use moving forward

### ISSUE THREAD

**Issue by epearman** [lzim/teampsd#2895]
lzim's Zenhub trial is ending 

Hey there, 
Thanks for signing up for Zenhub. We hope you have been enjoying your free trial. 
This is a reminder the lzim trial for Zenhub is about to expire on 2023-03-29. We'd love to keep you as a customer and help continue bridging the gap between the development team and the rest of your organization. You can subscribe to a plan by heading to your account settings page to continue using Zenhub. 

A paid subscription is required to access Workspaces, Roadmaps, and Reports for private GitHub repositories. If you run an Open Source project, or are teaching a University Course, you can apply for[ free Zenhub access ](https://help.zenhub.com/support/search?term=%22request+free+access%22)

Cheers, 
The Zenhub Team 

____________________________________________________________________________________________________________________

We have 11 users they state right now, but at the Growth level this is a little more than $1000/year if billed annually.

- [ ] My account expires 03/29. Need to determine who all we need using ZenHub in this way.
- [ ] Also, should double-check the latest on VHA guidance re: GitHub/ZenHub vs. Jira and Azure, etc. and check on Hawaii DOH too.

**Comment by epearman** [comment]
**Current Users:**
![image.png](https://images.zenhubusercontent.com/63331eaba895626f74a7c3a6/e8dd40b8-e37b-4b17-9b91-2b142fe8f9ac)

- [ ] Review During wk3 overflow_workflow who to remove from these users.

**Comment by hthrmarsh** [comment]
Hi @epearman. You mentioned you though we could have 8 licensed users (not 11). Can you confirm the list?

**Comment by epearman** [comment]
My recommendation is to remove the following users:
- [ ] Anthony
- [ ] Jenn
- [ ] Kimberly 
- [ ] Meghana

My recommendation is to add the following user:
- [ ] Stacey 

That would give us 8 users total

**Comment by hthrmarsh** [comment]
@epearman @emilymetcalf114 

I got 12 users, not 13. PDF of pricing saved here: 
![image](https://user-images.githubusercontent.com/126210778/228664091-23aa9ec8-d741-41a6-9b06-356c4e99aff9.png)

**Comment by hthrmarsh** [comment]
@epearman @emilymetcalf114 

Emily P submit ReQlogic request 3/29/23.

**Comment by emilymetcalf114** [comment]
Renewed 3/30/2023
@epearman working with PAVIR to set up Zenhub as a Vendor

**Comment by hthrmarsh** [comment]
@pearman @emilymetcalf114 
Zenhub purchased - received invoice and receipts on 3/31/23.

**Comment by hthrmarsh** [comment]
@lzim 
![image.png](https://images.zenhubusercontent.com/6408f6bee4d68058a5b2cf6b/49c26df1-7ca2-4c14-bdde-5216b89388a5)

**Comment by hthrmarsh** [comment]
Cross-reference #700[https://app.zenhub.com/workspaces/team-psd-workspace-5e4ac9bd8d388dfba6d9aef5/issues/gh/lzim/research/700](url)

Effort tracked on that card. Re-closing this one.
