### ISSUE TITLE
Story B: API integration for LEAF requests

### ISSUE THREAD

**Issue by epearman** [lzim/teampsd#2896]
- [ ] @jamesmrollins  and @emilypearman to investigate if LEAF integration with GitHub is possible via API

**Comment by epearman** [comment]
**Decision**
who: @lzim @hthrmarsh @emilymetcalf114 
When: System_sme_support_workflow
scribbed: Support_workflow

**100% sure we need to be in LEAF ASAP for _Modeling to Learn**_

**Comment by epearman** [comment]
#adjudicate_memo closing this card since it is a duplicate of #2897

**Comment by hnorthcraft** [comment]
#adjudicate_memo per comment above, efforts trackd to other card, marking as dup
