### ISSUE TITLE
2023_jun_epic #story_b: Backend: GitHub/ZenHub API integration; Frontend: LEAF frontend (a new 'consult' LEAF; 6 Issue Template that could be LEAF Forms)

### ISSUE THREAD

**Issue by epearman** [lzim/teampsd#2897]
- [x] @jamesmrollins  and @emilypearman to investigate if LEAF integration with GitHub is possible via API

______________________________________________________-

**DECISION**
who: @lzim @hthrmarsh @emilymetcalf114 
When: **wk4 april_epic System_sme_support_workflow**
scribbed: Support_workflow

**100% sure we need to be in LEAF ASAP for _Modeling to Learn**_

**Top priority to capture the volume of the end of trials to justify our future budget.
Prioritize in next 2023_roadmap_q2**
-Propose in the #health_equity_grant if we can get the partnerships and clarity in time
-Set up in next quarterly roadmap Jul-Sept (q4 of FY23)

**NOW if can - reported that in FY22 Team PSD**
squashed 200+ bugs
developed 200+ features
 
**Budget Request for FY23 & FY24**
Costing Aim with HERC for HSRD grant.
Planned to describe our value streams.

 
**We should retain the GitHub/ZenHub functionality, but identify API integrations**
#story_j
GitHub Actions

**Comment by epearman** [comment]
@jamesmrollins, thank you for looking into this so quickly, can you add your preliminary findings on this issue to this card as well?

**Comment by jamesmrollins** [comment]
FYI: @epearman @emilymetcalf114 @hthrmarsh 

- [ ] LEAF Preliminary Information Regarding LEAF [#LEAF_support_services](https://leaf.va.gov/platform/service_requests_launchpad/) contains portal entry for general and national project consultations, tech support, CoP and others. 
- [ ] [#LEAF_community_of_practice](https://teams.microsoft.com/l/team/19%3aVVK_SN9d7f5QaTBELBbp63xihDMZ2tJUjuZsXXKjadY1%40thread.tacv2/conversations?groupId=56e12324-7248-4ed5-a983-613c9bf3acad&tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf) contains the Team and channels that support the LEAF CoP.
- [ ] [#LEAF_GitHub](https://github.com/department-of-veterans-affairs/LEAF) contains the public LEAF repo.
- [ ] No evidence of API in the support channels, nor any hits on general searches in the Team channel or their Tech Support Portal. Did put in a query on the CoP channel to see if anyone knows anything about an API.

**Comment by jamesmrollins** [comment]
FYI: @epearman @emilymetcalf114 @hthrmarsh 

Results of CoP question - **BOOM!!**

[LEAF_Using_JSON_with_Excel_Power_BI.pptx](https://github.com/lzim/teampsd/files/11103512/LEAF_Using_JSON_with_Excel_Power_BI.pptx)

**Comment by epearman** [comment]
This will be prioritized next roadmap 2023_Q2

**Comment by epearman** [comment]
Overview of [LEAF_Using_JSON_with_Excel_Power_BI.pptx](https://github.com/lzim/teampsd/files/11103512/LEAF_Using_JSON_with_Excel_Power_BI.pptx)
- Exports LEAF reports to an excel file
- Excel file is set up based on users credentials
- Excel file can be set up to refresh LEAF report data upon opening     
 
**Next Steps:**
- [ ] Scalability across users would need to be tested (i.e. if one user sets up the excel file and uploads it to GitHub would it work for a second user upon opening? 
- [ ] Scope out setting up our LEAF site for _MTL_

**Comment by epearman** [comment]
When setting up a site they will ask optionally for an executive sponsor.

![image.png](https://images.zenhubusercontent.com/63331eaba895626f74a7c3a6/3170bba8-9c9a-46b6-b422-04a29865e6e2)

If storing PII or PHI you will need to ensure you follow these [secure steps](https://leaf.va.gov/launchpad/files/LEAF%20Secure%20Status_Tutorial.pdf)

**Comment by epearman** [comment]
Directions to Enroll in Training: 
1. [Go to the Leaf Launchpad](https://leaf.va.gov/platform/service_requests_launchpad/)
2. Select "Register for Training"
![image](https://user-images.githubusercontent.com/67978478/236009865-09e1211a-7ca3-4477-a49c-3001f3b4c1d1.png)

[Our LEAF Test site for learning ](https://leaf.va.gov/VISN21/640/teampsd_test/)

**Comment by hthrmarsh** [comment]
@pearman - I've registered for the training. If you're registering, use the test site already created by Emily: https://leaf.va.gov/VISN21/640/teampsd_test/

**Comment by epearman** [comment]
**DECISION**
**[Scribed in:](https://teams.microsoft.com/l/message/19:49d24892646e40e890025a334c2cbcf8@thread.skype/1683225222722?tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf&groupId=1db500d5-0d01-4254-af42-ad3f78bafacd&parentMessageId=1680129338495&teamName=teampsd_vha&channelName=systems_sme_workflow&createdTime=1683225222722&allowXTenantAccess=false)** **system_sme_workflow** during **wk1 2023_may_epic**
**LEAF demo attended by:** @lzim @hthrmarsh @epearman 
- [ ] LEAF development to be narrowed and aligned with GitHub issues (R01 & IIR Trial continuity; Aim 3 Cost dependency) at our june_roadmap.
- [ ] Will decide when to attend a training session after june_roadmap
- [ ] Backlog this issue card until then

![image](https://user-images.githubusercontent.com/67978478/236298013-01ca2f41-829d-4d16-b5b5-b1fafa86d270.png)

FYI:
@jamesmrollins

**Comment by lzim** [comment]
@jamesmrollins 

1. We will ultimately pursue LEAF.
2. Top priority for 2023_may_epic we need @emilymetcalf114 & @epearman to ensure no data loss with site set up across Teams/Sharepoint/Dynamics/Sim UI for trial sites.
3. But, because we are going to begin narrower LEAF/GitHub API for our consult, bug & feature templated issue cards, if you have bandwidth to take the more involved LEAF training to scope out what that entails, please do. 

LMK if you have questions.
Thx!

**Comment by jamesmrollins** [comment]
Consult workflow skeleton:

1. Site has been identified usually a STA3N. They either self-identify or they are on the MTL site list.
2. If self-referred, review the trial list for MTL for where the site is in the study.
3. Assumption:  We will be given a fundamental entity (site=STA3N) to start the intervention.
4. Part one will start with same Data UI Review for both Red and Blue.
5. Part two starts with asking for area of focusing the Sim_UI and which clinic would be in scope.

**Comment by jamesmrollins** [comment]
FYI @epearman @hthrmarsh @lzim 

Met with a collaborator from the LEAF CoP meeting today.  The recording is in the Sim UI Workflow.  He discussed how access JavaScript and the general structure of LEAF from a coder's perspective.  So it is technically possible to use the GitHub API to move information from LEAF to GitHub.  Furthermore, Michael Gao, LEAF's creator confirmed that it is possible to use the API.  So good news, in terms of using LEAF as a user interface.  I also received information about how to get LEAF to post to an Outlook calendar.  So we may find it is fully capable of helping us manage our consults.

**Comment by lzim** [comment]
@jamesmrollins to update Title of card & Data based on #sim_ui_workflow F2F wk5 2023_may_epic

Top priority to initiate a Team PSD _MTL consult_ in LEAF.
Secondary priority the API integration
