### ISSUE TITLE
wk3 2023_apr_epic Story H: PeopleOps and DataOps PAVIR PDs for Program Manager II review with PI

### ISSUE THREAD

**Issue by emilymetcalf114** [lzim/teampsd#2906]
@epearman #data_ops_workstream
@emilymetcalf114 #people_ops_workstream

- [x] Use **hiring_workflow** for 1:1s with @lzim to review updated drafts of PAVIR PDs for Program Manager II positions

**Comment by epearman** [comment]
#ajudicate_memo, this card has been split into #588 and #589

**Comment by epearman** [comment]
#adjuidcate_memo duplicate of card #crossref # lzim/research/#583.
