### ISSUE TITLE
wk1 2023_jun_epic #story_b: Team PSD workflow master deck for site consults (data & modeling)

### ISSUE THREAD

**Issue by emilymetcalf114** [lzim/teampsd#2909]
@emilymetcalf114 #people_ops_workstream

["**_Team PSD co-coordinates MTL site consults with OMHSP QIICs, ILEAD and field sites._**" slides]("[Team PSD co-coordinates MTL site consults with OMHSP QIICs, ILEAD and field sites."](https://dvagov.sharepoint.com/:p:/r/sites/teampsd_vha/Shared%20Documents/systems_sme_workflow/Team%20PSD%20co-coordinates%20MTL%20site%20consults%20with%20OMHSP%20QIICs,%20ILEAD,%20and%20field%20sites.pptx?d=w0e66a511c5524da2b13dafb820a65e2e&csf=1&web=1&e=gFyWLZ))

Break up into weeks: 

- [ ] Power Point Slide deck step by step guide with screenshots for using the [mtl.help@va.gov](mailto:mtl.help@va.gov) calendar.
  - [ ] Draw screenshots from what went over 4/4 and 4/5 with #systems_sme_workflow and #support_workflow
- [ ] Track on 2617 as a draft.
- [ ] Team PSD Manual
- [ ] MTL Manual
- [ ] sharepoint

**Comment by lzim** [comment]
### Discussed at 8am_workflow & systems_sme_workflow
wk4 2023_apr_epic

@emilymetcalf114 
I recommend that t primary focus of this slide deck be the following cross-cutting use:

_User Story Map_: **"Team PSD co-coordinates _MTL_ site consults with OMHSP QIICs, ILEAD and field sites."**

### User_workflows that may consult with this slide deck for _standard work_:
- 8am_workflow - to align interdependen workstreams
- **consult_workflow** - to align with QIIC workflows
- **systems_sme** - to prepare and package recommendations
- **ilead_workflow** - to ensure accreditation 
- **support_workflow** - to respond to bugs and develop features

### Functional Requirements for this Slide Deck "Co-cordinate _MTL_ site consults with OMHSP QIICs, ILEAD and field sites."
- [ ] Describe process of being added to mtl.help@gov shared Operations calendar
- [ ] Use call out to define each detail for _MTL_ process
   - [ ] Consortia & QIIC mapping
   - [ ] VISN
   - [ ] Red (data consult) / Blue (modeling consult)
   - [ ] Sampling/Randomization Strata (Large/Small VAMC/CBOC)
   - [ ] Next Step in process - Email Clinic Selections to

FYI: Picking this up from today **wk4 2023_apr_epic** **systems_sme_workflow**
@dlkibbe 
@dlounsbu 
@hthrmarsh 
@epearman 
@jamesmrollins

**Comment by emilymetcalf114** [comment]
@dlkibbe 
@emilymetcalf114 
@epearman 
discussed wk4 2023_apr_epic 

@lzim
We recommend switching the order of functional requirements #9 (Recommendations) and #10 (time based evaluation of common care problems) so that all recommendations are provided at the end after reviewing the data.

**Comment by emilymetcalf114** [comment]
discussed during #consult_workflow and got feedback from QIICs
@lzim 
@epearman 
@hthrmarsh 
@dlkibbe 
@emilymetcalf114 
#mgmt_trio 
#systems_smes        

Additional functional requirements added: 
- [ ] @emilymetcalf114 move definition links to the beginning of the slide deck 
  - [ ] Provide links to CPT codes or define CPT codes for Psychotherapy & Medication Management on the slide. 
  - [ ] Bin definitions.
    - [ ] Defining the Addiction Bin 
    - [ ] Definition on the slide CPT guide
    - [ ] Link to the CPT guide so the end-user is super clear about what the selection means, otherwise they cannot use it.
- [ ] User message for link in the slide "View and interact with your local MTL data at this link: mtl.how/data"
- [ ] Use MTL Blue and MTL Red Logos in the master slide deck template for data only (Red), or add simulation (Blue).
- [ ] narrow view of top encounters
- [ ] include box with data/numbers of encounters 
- [ ] show F2F side by side with VVC and a statement about the trends - Both could be increasing, both decreasing or moving in opposite directions.
  - [ ] F2F on left
  - [ ] VVC on right
- [ ] @epearman Include instructions on use of Stop Codes in the Clinic Selection.

**Comment by epearman** [comment]
#**Discussed wk1 2023_may_epic**
**Who:**
@lzim 
@epearman 
**FYI:**
@emilymetcalf114 
@hthrmarsh 
@dlkibbe 

**Next Steps: Requirements**
- [ ] #blocked by lzim/teampsd#2909 MTL 3.5 Red & MTL 3.5 Blue Slide Templates 
- [ ] Teams/Sharepoint set up
- [ ] Site CoPlanning Groups in Dynamics
____________________________________________________________________________________________

**Slide deck conventions discussed during wk1_2023_may_epic overflow_workflow:**
- 1/2" from edges and in the middle
- Title should have # and period at end of title
- Links should tell someone what they can find there
- Table formatting		
- Remove words from the rows/columns if appears in the table header
- mtl.help and mtl.info do not need to be capitalized
- Shouldn't be wasted space around the text in the call outs
- Break up clauses intentionally (e.g. you wouldn't have Team PSD SAFe break across two lines)

**Comment by hthrmarsh** [comment]
@lzim I cleaned up the slides according to the conventions scribed above and updated/added a couple of transitions slides. 

**Slides are here:**
![image](https://user-images.githubusercontent.com/126210778/236896788-58d92cf2-6101-4730-8893-832c4e11d309.png)

FYI @emilymetcalf114 @epearman

**Comment by lzim** [comment]
Great! Thanks @hthrmarsh for following through to further implement 
**wk4 2023_apr_epic and wk1 2023_may_epic workflow_user** feedback.

FYI: 
@emilymetcalf114 - OOO today
@epearman - cross-covering w/ @jamesmrollins 
@dlounsbu & @dlkibbe 

#### THIS WEEK wk2 2023_may_epic

- [ ] @lzim - To standardize _MTL 3.5 Red_ and _MTL 3.5 Blue_ Master Slide Deck Templates, 
After 4PM today - I am going to
 
- [ ] 01. **Align the slides thesis sentences** to the existing 
   - [ ] 02. **accredited learning objectives and
   - [ ] 03. .gifs** in the _[MTL Blue](https://mtl.how/blue)_ and _[MTL Red](https://mtl.how/red)_ guides. 
      - @hthrmarsh & @epearman - You two may be able to help with adding the .gifs if I clarify which are needed.
   
- 04. Check against grant/trial strategy constructs in 
      - [ ] 05. R01 grant (Audit & Feedback)
      - [ ] 06. IIR Grant (usual Quality Improvement) 
      
- [ ] 07. **Measures of Aim 2 constructs in in Clinical Trials Registration/IRB** for
      - **R01 systems thinking**
        - [ ] 08. Aim 2 Provider Survey 
        - [ ] 09. Aim 2 IRB Modification coding C.F.B.T. from Sterman, 2006
        
      - **IIR Grant participatory learning**    
        - [ ] 10. Aim 2 Provider Survey 
        - [ ] 11. Aim 2 IRB Modification coding Participatory Constructs from Oetazel et al., 2018
        
#### Once we have these, we hope we can add the site specific information in a way highly aligned to all prior work on the trials
        
 #### _Next Steps: 2023_may_epic_
 **wk2**
- [ ] 1. **#qiic review** tomorrow
   - [ ] 2. @lzim Update **HSRD DSMB**
   - [ ] 3. @lzim Update **NIDA DSMB**

**wk3
- [ ] 4. #systems_sme_workflow 
   - [ ] 5. Finalize **9 sites slide decks** and engage sites **wk3 & wk4 2023_may_epic**
   - [ ] 6. Finalize **9 site recommendation paragraphs** for #qiics
 
 **wk3 
- [ ] 7. @lzim ncorporate in **ILEAD Pre-Prod Scripts DUE 7/21**
   - [ ] 8. Clinical Perspective
   - [ ] 9. Leadership Perspective
   - [ ] 10. Improvement/Change/Quality Manager Perspective
   - [ ] 11. Data/Modeling Perspective
   - [ ] 12. Evaluator/Scholar Perspective    
 
 **wk3       
 - **OMHSP Sharepoint/Data Dashbaord Integration Review to prep for BHIP Meeting 05/18**
        - [ ] 13. BHIP Team Implementation/Staffing
        - [ ] 14. Productivity/Staffing (MHOC /MHHI)
        - [ ] 15. EBP Start/Dose (SAIL coverage/continuity)
        - [ ] 16. Health Disparities/Equity (JEDI; Joint Commission #health_equity_grant & #health_equity_contract)
        - [ ] 16. PTSD Mentorship Dashboard
        - [ ] 17. PDSI (OUD & AUD EBPharm)
        - [ ] 18. LEAF
        - [ ] 19. QIIC

**wk4
- **OMHSP Review w/Leadership - Dr. Campbell's 2nd quarterly update this Fri 05/12**
    - [ ] 20. BHIP Kendra & Lauren - next week 05/18
    - [ ] 21. NCPTSD & Stacey P
    - [ ] 22. Cliff & Claire
    - [ ] 23. PECs Rani & Jodie
    - [ ] 24. HERC cost analyses  
    
#### 2023_jun_epic
    - [ ] 25. Ilse & Jay - Laura 
       - [ ] 26. RO1 (return on investment #portfolio horizons) Definitions & Guidance - BUILD based on QA of **one_deck** iterations
          [ ] a. Efficacious
          [ ] b. Pivot/Divest
          [ ] c. Future

**Comment by lzim** [comment]
[#consult_workflow wk2 2023_may_epic ](https://teams.microsoft.com/l/message/19:cb0b9866ac224a179236c0cc3e2ee56f@thread.skype/1683648224847?tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf&groupId=1db500d5-0d01-4254-af42-ad3f78bafacd&parentMessageId=1670342633287&teamName=teampsd_vha&channelName=consult_workflow&createdTime=1683648224847&allowXTenantAccess=false)- We reviewed our _MTL Red/MTL Blue_ Sites and MAster Slide Deck plan with the #qiics

- [ ] @lzim to track OMHSP release of "[the Directive](https://teams.microsoft.com/l/message/19:cb0b9866ac224a179236c0cc3e2ee56f@thread.skype/1683648594450?tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf&groupId=1db500d5-0d01-4254-af42-ad3f78bafacd&parentMessageId=1670342633287&teamName=teampsd_vha&channelName=consult_workflow&createdTime=1683648594450&allowXTenantAccess=false)" on 05/09/2023 

- [ ] **DECISION:**
- The _MTL Red & MTL Blue slide decks will be the SAME for the first section of slides._
- Based on clinical area the Site is looking for support; and that we identify using the _MTL Red Data UI_ will will request a meeting with the _MTL Blue_ Team/Leads to make clinic selections.

**Comment by lzim** [comment]
Discuss #adjucate_memo at 
wk2 2023_may_epic hq_workflow

**Comment by hthrmarsh** [comment]
Cannot close this card at end of wk4 Sprint.

**Comment by lzim** [comment]
No work on this exact card not covered elsewhere.
