### ISSUE TITLE
2023_apr_epic story b: Prep production of MTL 4.0 video recordings in St. Louis ILEAD studio wk1 2023_aug_epic

### ISSUE THREAD

**Issue by emilymetcalf114** [lzim/teampsd#2919]
**Discussed during wk2 2023_apr_epic ilead_workflow**
@lzim 
@emilymetcalf114 

**Preparation for production of _MTL 4.0 video_ recordings in St. Louis Studio wk1 2023_aug_epic** 

_Next Steps:_
- [ ] Outline the core competencies in each track.
- [ ] Core content for everyone.
- [ ] How it branches out from there. (Serial - each video points to a next video)
- [ ] Integrations/Operations across OMHSP and across other VHA Program Offices, including External Accreditation.
- [ ] **Need Content Creators for each track.**
- [ ] scripts for each video: **DEADLINE: July 23, end of wk3 2023_jul_epic**
- [ ] map out visuals for each video 
- [ ] slide deck outlining content (organized by QIIC consultative services menu?)

**Comment by hthrmarsh** [comment]
![image.png](https://images.zenhubusercontent.com/6408f6bee4d68058a5b2cf6b/b4202a31-39b1-4e6b-abd6-23f423ef8e15)

**Comment by dlkibbe** [comment]
@lzim @hthrmarsh @emilymetcalf114 please let me know how I can help with the scripts for the videos.

**Comment by hthrmarsh** [comment]
- [ ] Scripts due 7/23/23

**Comment by dlkibbe** [comment]
ILEAD scripts completed and saved on OSF https://osf.io/3av45/

**Comment by dlkibbe** [comment]
Scripts for 33 videos are found on to OSF in folder: mtl_4.0_ilead_copy_only
