### ISSUE TITLE
Version 1.8 "Critical Additional Features" List

### ISSUE THREAD

**Issue by TomRust** [lzim/teampsd#292]
***I'm starting a list of features for consideration to include in MTL 1.8.  Please add to the list, comment on feasibility, or ask clarifying questions.  I assume we’ll review the list as a group in a future meeting to decide which are necessary for v1.8 vs. v2.0 vs. “just nice to have.”***

1. All – 
   * a. Be able to change between settings, cohorts, or services easily (with similar speed to using the radio buttons in the Experiment Timeline section) when using a mobile device.
   * b. Make “Engagement Duration” an experiment variable in CC, MM, and AGG.
   * c. Fix the “Run for 1 quarter at a time” option

2. For CC and MM – 
   * a. Change the variable name in model diagram from “Additional Appointments for New Patients” to “Appointments for New Patients” **&** change its experiment slider to show that it is adding to the existing supply for new patients, not replacing (i.e., it will work like “Supply” slider in SP).  Also, change the model structure so that these appointments are subtracted from the total supply, instead of coming from other services outside the model.

   * b. Change the variable name for "Appointments for Existing Patients" to "Appointments **used by** Existing Patients,” as this is a more accurate description of how the feedback loop works.  Existing patients are not allocated a specific portion of the supply (there is no allocation decision), but instead individual patients take as much supply as then need, with the remainder going to New Patients.  To me, “Appointments for Existing Patients” sounds like the number of slots the team has allocated, as opposed to the result of prioritizing existing patients over new patients.

   * c. Add these variables to the Results Dashboard drop down list, and add “Actual RVI” to the default chart set:
        * Appointments for Existing Patients
        * Appointments for New Patients
        * Actual RVI

   * d. Allow the learner to use “Team Data on New Patient Start Rate” **without** severing the main feedback loop.  There would still need to be a switch, but it would toggle between using team data for the “New Patient Start Rate” or the “75th% Appointment Supply.”  As we said in the video, this is a choice users have to make: Which estimate is a more realistic representation of their current state, the patient start rate or the appointment supply?  If they want feedback, then they can’t have both set in stone.  This is already the case in our current design, where when the learner uses “Team Data on New Patient Start Rate,” then the supply data isn’t used to determine the start rate (i.e., supply is not a constraint on patient starts).  

3. For MM only – 
   * a. Change diagram in MM to include positive arrow from “Appointments for Existing Patients” to “Completing Rate” (it’s in CC, but not MM!)
   * b. Add a switch to automatically implement the slot allocation across patient cohorts that maximizes new patient starts while maintaining target RVI.  This would allow the learner to see the exact right slot allocation for any change they make to RVI, so they no longer have to guess at it.  OR, a simpler option would be to simply display these “optimal” allocation %s at the end of each run.

4. For PSY – 
   * a. Add an experiment where the RVI for patients in their first 3 months can be reduced to less than 1 week (ie, they receive more than one visit per week), which in turn **reduces** their engagement duration…and increases their graduation %?

4. For AGG – 
   * a. Replace the green “Service Proportions” sliders with a single switch to automatically/dynamically adjust the service proportions to maintain the target RVI and wait time to accommodate any changes the learner makes to supply allocation.  This would make the optimal results of any supply allocation change easier to see, as users could see what the optimal service proportions would be for any experiment they run with supply allocation, not just the for the base case.  
   * b. I could also build a switch that automatically finds and uses the optimal supply allocation for any set of service proportions (i.e., the inverse ability of 4a above).
   * c. Add break “Telephone” out of “Adjunct”

**Comment by branscombj** [comment]
2a: would “appointments *available* for new patients” be appropriate? It suggests the “what’s left” aspect.

**Comment by lzim** [comment]
Thank you @TomRust!

I will add what @jamesmrollins and I already worked on for MTL 1.8, MTL 1.9 and MTL 2.0 plans. We definitely want to keep an eye on all known issues that could compromise our effectiveness supporting our learners. 

Lindsey

**Comment by TomRust** [comment]
RE: 2a -- @branscombj : I love it.  "Appointments Available for New Patients" is definitely clearer to me about the "new patients get 'what's left'" assumption of that feedback loop.

**Comment by TomRust** [comment]
@lzim: Even if we don't have a full list, if there are any items definitely needed in 1.8 that are in my wheel-house, just let me know.  I can start on them this week.

**Comment by staceypark** [comment]
.xls export issue
![image](https://user-images.githubusercontent.com/31089501/50304461-d9361c00-0444-11e9-8a34-cb91525c4b23.png)

**Comment by lzim** [comment]
I'm going to close this, to be replaced by the new issue #298 that @jamesmrollins opened today, which reviews our timeline and proposed development plan.

Thanks!
