### ISSUE TITLE
may_epic story b: email to Cliff and Claire to align OMHSP tools, resources, and reports with MTL 

### ISSUE THREAD

**Issue by emilymetcalf114** [lzim/teampsd#2924]
_Next Steps_
@lzim 
1. **Consultative Topics** Would we send the Consultative Site Visit Topics to MTL sites or use the one they already completed? 
- Align this appropriate, feasible??

2. **QIIC Report Template** - work in progress. 
- Align this appropriate, feasible??
- Strengths
- Policy Non-Compliance
- Safety Concerns
- Process Enhancements

3. **QIIC site visit list** Review explicitly the Site Visit vs. MTL random site sampling overlap.

**Comment by epearman** [comment]
discussed during **wk 2023_apr_epic team_temp**
- [ ] Need slide decks from #corssref #2909 before we reach out to Cliff and Claire

**Comment by lzim** [comment]
wk1 2024_06 @lzim updated card during June Roadmap Event https://mtl.how/2024_roadmap
- [x] Last update to Claire Collie was thru co-I and DSMB role in fall 2023.
- [x] #adjuciate_memo - 3 pts reflects prior work
