### ISSUE TITLE
2023_may_epic Story b: powerpoint slide deck how to prep blue recommendations for sites in the sim_ui

### ISSUE THREAD

**Issue by emilymetcalf114** [lzim/teampsd#2927]
@emilymetcalf114 #people_ops_workstream

Break up into weeks:

- [ ]  Power Point Slide deck step by step guide with screenshots
- [ ]  Track on 2617 as a draft.
- [ ]  Team PSD Manual
- [ ]  MTL Manual
- [ ]  sharepoint

**Comment by lzim** [comment]
#adjudicate_memo - Stale card covered on other issue task cards.
