### ISSUE TITLE
ICEBOX Teams activity analytics scheduled refresh has been paused on Power BI for Lindsey

### ISSUE THREAD

**Issue by ghost** [lzim/teampsd#2936]
### **Issue:**
- @lzim received an automatically generated email for Power BI saying the her scheduled refresh for _Teams activity analytics_ in _My Workspace_ has been paused due to inactivity. 
    - Scheduled data refreshes are always paused in Power BI when no one has viewed the dashboard for the last two months.
 
### **How to create a "Teams Activity Analytics" in "My Workspace"** (I am thinking this is what Lindsey did at one point)
1. Open Teams go to "Apps" on the bottom left hand side, under the search bar search for "Power BI" and select the "Power BI" app. 
![image.png](https://images.zenhubusercontent.com/63331eaba895626f74a7c3a6/e134ff9a-adff-442d-8e4c-10556d7f8ab0)

2. Once you are in "Power BI" go to "Create" and select "Analyze you Teams data"
![image.png](https://images.zenhubusercontent.com/63331eaba895626f74a7c3a6/e360f046-15fb-4901-9eca-8221254b8e28)

### **How to view a previously created Teams activity analytics in My Workspace**
1. On the bottom left hand side of team select the three dots and then select "Power BI".
![image.png](https://images.zenhubusercontent.com/63331eaba895626f74a7c3a6/5be4c443-6515-411c-b305-6014935208f6)
 
2. Then select "My workspace" and select the "Teams activity analytics" Report.
![image.png](https://images.zenhubusercontent.com/63331eaba895626f74a7c3a6/12d4a0f7-85d8-41fb-b986-ec854703ab24)

3. You can then see the Teams activity analytics.
![image.png](https://images.zenhubusercontent.com/63331eaba895626f74a7c3a6/1d299905-75f3-481e-878f-14e12f97b63c)

4. Once you complete step 3 above Power BI will register that a user has accessed this report and it will restart automatic data refresh.

5. To double check the last data refresh return to step 2. above and instead hover over "Team Activity Analaytics" **Dataset** and click the three dots that appear and click "settings"

![image.png](https://images.zenhubusercontent.com/63331eaba895626f74a7c3a6/95d02b36-2491-40e3-85d8-e74c850f2e5a)![image.png](https://images.zenhubusercontent.com/63331eaba895626f74a7c3a6/d57e8a3e-79fd-4a1b-b6bf-13d8f7ee2e65)

6. You can then see the latest refresh and refresh history. 
![image.png](https://images.zenhubusercontent.com/63331eaba895626f74a7c3a6/e8ee89ec-c815-49d4-9f6e-e49fe762795b)

**Comment by epearman** [comment]
- [ ] @lzim to follow the steps above and check that her data refresh has restarted.

**Comment by hnorthcraft** [comment]
#adjudicate_memo updating to 1SP closed as not planned/icebox
