### ISSUE TITLE
wk1 may_epic #story_e: fill out ILEAD training support request form for CPTSD due May 3

### ISSUE THREAD

**Issue by emilymetcalf114** [lzim/teampsd#2938]
email from Cybele 4/17 to mtl.help: 

ILEAD (formerly EES) has issued its annual call for training support requests. As has been our practice for many years, the Executive Division will compile and submit these requests to ILEAD as a group for the entire National Center. This is certainly not your only chance to ask ILEAD for help, but they do prefer that program offices submit the bulk of their requests now. Please get your requests to me, using the attached spreadsheet by **Wednesday, May 3**. 

On the form list any new or continuing educational activities that need ILEAD project and/or financial support for development, travel, or continuing education credits. We commonly include the creation of online courses, face-to-face meetings, virtual meetings or lecture series that offer continuing education credits, podcasts, and video development.

**Comment by emilymetcalf114** [comment]
discussed at **ilead_workflow wk1 2023_may_epic**
@lzim 
@emilymetcalf114 

Made updates and submitted.

**Comment by lzim** [comment]
Great work on this @emilymetcalf114 ! 
I appreciated you sending it on to Cybele on behalf of D&T Division !
