### ISSUE TITLE
wk3 2023_apr_epic #story_b #story_e: preparing budget for OMHSP/NCPTSD to cover travel costs for ILEAD MTL 3.0 video recordings and email to ILEAD

### ISSUE THREAD

**Issue by emilymetcalf114** [lzim/teampsd#2942]
#cross-ref master card #2919

- [x] Budget: OMHSP/NCPTSD to cover travel costs - discuss with Cybele. FYI @hthrmarsh 
  - [x]  need to determine # of people traveling (2-6 people) and where are they traveling from?
  - [x]  SFO to St Louis, NYC to St Louis, Atlanta to St Louis,
  - [x]  Concur travel (VA operations funds)
  - [x]  2 travel days, 4 full days (Sun 07/30 - Fri 08/04)
  - [x]  @emilymetcalf114 to budget out flights and lodging and ME&I (conservative) and draft email to Cybele
  - [x] @lzim to finalize email

**Comment by emilymetcalf114** [comment]
Person | Airfare | Lodging | M&IE | Total
-- | -- | -- | -- | --
Lindsey | San Jose round trip to St. Louis: $346-$606 | $141x5 nights=$705 | ($48x2 travel days)+($64*4 full days)=$352 |  $1,403-$1,663
David L | NYC round trip to St. Louis: $162-$694 | $141x5 nights=$705 | ($48x2 travel days)+($64*4 full days)=$352 |  $1,219-$1,751
Debbie? (track?) | ATL round trip to St. Louis: $208-$254 | $141x5 nights=$705 | ($48x2 travel days)+($64*4 full days)=$352 |  $1,265-$1,311
Total |   |   |   |  $3,887-$4,725
Clinician track | XX | $141x5 nights=$705 | ($48x2 travel days)+($64*4 full days)=$352 | $1,057+airfare
Leadership/Admin Track | XX | $141x5 nights=$705 | ($48x2 travel days)+($64*4 full days)=$352 | $1,057+airfare
Implementation Scientist Track | XX | $141x5 nights=$705 | ($48x2 travel days)+($64*4 full days)=$352 | $1,057+airfare
Data Scientist Track and/or Systems Modeling Track | XX | $141x5 nights=$705 | ($48x2 travel days)+($64*4 full days)=$352 | $1,057+airfare
Total |   |   |   |  $8,115-$8,953+(airfare x 4)

**Comment by hthrmarsh** [comment]
- [ ] @hthrmarsh @emilymetcalf114 travel estimates for ISDC (ADM funds) and ILEAD (funding source TBD)

- [ ] @lzim to check with Cybele about NCPTSD funds for 2-3 travelers.

ISDC (*07/23-07/27) OPM per diem (Jul)
Lindsey Dep SFO -> ORD
- Dep. Sun 07/23
- Flight to St. Louis on Sun 07/30
*only lodging during conf. days
6 nights lodging
2 travel days

Lindsey will check with David about this and whether we want to make this a working time or off time.
Staying in Chicago for Fri-Sun is more manageable/affordable than traveling back to California in between.
ILEAD (07/31-08/04) OPM per diem (Jul/Aug)
David Dep Chicago -> St. Louis
Return to NYC on Fri 08/04
5 nights lodging
2 travel days
Lindsey Dep Chicago -> St. Louis Return to SFO on Fri 08/04

**Comment by hthrmarsh** [comment]
**ISDC (*07/23-07/27) OPM per diem (Jul)**
Lindsey Dep SFO -> ORD
- Dep. Sun 07/23
- Flight to St. Louis on Sun 07/30
*only lodging during conf. days
6 nights lodging
2 travel days

**Comment by hthrmarsh** [comment]
ISDC (*07/23-07/27) OPM per diem (Jul)
Lindsey Dep SFO -> ORD
- Dep. Sun 07/23
- Flight to St. Louis on Sun 07/30
*only lodging during conf. days
6 nights lodging
2 travel days

**Comment by emilymetcalf114** [comment]
Person | Airfare 
-- | -- 
Lindsey | SFO to Chicago: $208 one-way

**Comment by lzim** [comment]
@emilymetcalf114 
@hthrmarsh 

**BLUF:**  
- _Would you say, it would be ~$3300 for 2 travelers and ~$6600 for 4 travelers?_

If so, @emilymetcalf114  please reply to the email I sent to Cybele with those to estimates and we can see what she says. 

Thanks!

**Comment by hthrmarsh** [comment]
_Next Steps:_
- [ ] @lzim @emilymetcalf114 Confirm if NCPTSD funds for ILEAD trip
- [ ] If no, @hthrmarsh check with Marisela for ILEAD + ISDC travel costs using PAVIR ADM funds 
- [ ] If yes, @hthrmarsh okay with Marisela ISDC travel costs using PAVIR ADM funds

**Comment by lzim** [comment]
### Discussed at #systems_sme_workflow
@lzim
@dlkibbe 
@dlounsbu

**Comment by emilymetcalf114** [comment]
#adjudicate_memo 
wk3 2023_apr_epic
@lzim emailed D&T division and confirmed funding for 4 individuals for ILEAD recording travel to St. Louis. 
_Next steps:_
#cross-ref #2945 & #2948

**Comment by hthrmarsh** [comment]
**Discussed wk4_2023_may_epic during systems_sme_workflow:**
$6750 Chicago trip for 3 travelers assuming @dlkibbe @dlkibbe @lzim have a working weekend in Chicago. 

Rationale: 1,843 per 3 travelers (5,529) plus 2 additional hotel nights at per diem rate = $6750
