### ISSUE TITLE
2023_may_epic #portfolio: @lzim & @dlounsbu to prepare/draft/submit AHSR abstract (due 5/31/23)

### ISSUE THREAD

**Issue by hthrmarsh** [lzim/teampsd#2944]
@lzim 
@hthrmarsh 

**AHSR abstract (due 5/31/23): https://www.ahsrconference.org/2023/abstracts/**

Full submission details: https://ahsrconference2023.dryfta.com/submit-abstract. No abstract fee for submission. 

- [ ] @lzim to write abstract for AHSR
- [ ] @hthrmarsh to review/provide edits/review
- [ ] @lzim or @hthrmarsh to submit 

![image](https://user-images.githubusercontent.com/126210778/233499333-ba4c3515-2273-4ce2-8c66-545e873cd841.png)
![image](https://user-images.githubusercontent.com/126210778/233499294-ecc0b6e8-0880-4d9b-842c-a0cc13a15ba1.png)

**Comment by lzim** [comment]
@dlounsbu & @lzim to meet during **mixed_methods** in 2023_may_epic to finzlie this along with manuscripts.

**Comment by lzim** [comment]
@dlounsbu & @lzim to meet during **mixed_methods** in 2023_may_epic to finzlie this along with manuscripts.

**Comment by hthrmarsh** [comment]
@lzim 
Was this submitted? Can I close this card?

**Comment by hthrmarsh** [comment]
Registration completed. 
@hthrmarsh to submit check request for @lzim 

![image](https://github.com/lzim/teampsd/assets/126210778/976066d1-9a40-4c23-a60c-30af8c910ef5)
