### ISSUE TITLE
wk4_2023_apr_epic Portfolio: ISDC travel and booking

### ISSUE THREAD

**Issue by hthrmarsh** [lzim/teampsd#2945]
ISDC travel and booking

- [x] @hthrmarsh ISDC costs to Marisela ISDC travel costs using PAVIR ADM funds
- [ ] @lzim book travel

<html>
<body>
<p style="box-sizing: inherit; margin-bottom: 16px; margin-top: 0px; color: rgb(40, 41, 51); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Lindsey flight to ISDC (one-way; return flight covered by ILEAD trip?)</p>

Person | Airfare | Lodging | M&IE | Ground | Registration |Total
-- | -- | -- | -- | -- | -- | --
Lindsey | SFO to Chicago: $208 one-way | $187x6=$1,122 | ($79x5 full days=$395) + ($59.25x2 travel days =$118.50) = $513.50 | ~$100 | $695 member until May 30 | $2,638.50

FYI: @emilymetcalf114

**Comment by hthrmarsh** [comment]
@lzim 
Lindsey - do you need to have the ADM funds cover registration costs? 
https://systemdynamics.org/event/2023-international-system-dynamics-conference/

**Comment by lzim** [comment]
@hthrmarsh 

Yes, ADM funds will be for travel and registration. 

- [ ] @lzim to confirm the schedule with @dlounsbu briefly at **#systems_sme_workflow wk4 2023_apr_epic** 

> @lzim
Lindsey - do you need to have the ADM funds cover registration costs?
https://systemdynamics.org/event/2023-international-system-dynamics-conference/

**Comment by lzim** [comment]
@dlounsbu 
**Here are the questions we have re ISDC end of July-> St. Louis first week August.**

- [ ] Have you already booked your ISDC travel? 
- [ ] If no, would you want to fly from ISDC in Chicago to ILEAD in St. Louis? (vs. fly back to NYC between the two).
- [ ] If you would like to go from Chicago to St. Louis, would you want to do working sessions in between or down time? 
- [ ] NCPTSD is going to pay for this travel, which means it would be booked via the VHA Concur system.

**Comment by hthrmarsh** [comment]
Heather emailed request for Lindsey using ADM funds to Marisela 4/27/23

**Comment by lzim** [comment]
@hthrmarsh 

Please clarify the repository when posting an issue task # from different repository.
Like this: lzim/research/issues/661
