### ISSUE TITLE
508 Compliance

### ISSUE THREAD

**Issue by LKDOLIN** [lzim/teampsd#295]
![image](https://user-images.githubusercontent.com/46031561/50302611-941be500-0458-11e9-94e9-e77c8563e4dd.png)

Testing this cool thing @jamesmrollins

**Comment by jamesmrollins** [comment]
Hi @LKDOLIN ,
I'm sorry I missed this thread.  I am happy to see you are reviewing this program.  I look forward to your feedback.  Thank you!  James

**Comment by jamesmrollins** [comment]
@LKDOLIN and I met today to discuss way forward for 508.

1. Lara provided me with a 32 point checklist to screen 508 and provided training on the ANDI screening tool. 
2. We discussed the checklist items.
3. @jamesmrollins will review items with DEV.  When complete, I will refer to Elizabeth Dolin for 508 review.  Lara suggested we conduct an EES e-Learning Certification, to wit, Lara will be reviewer.
4. Lara indicated she would also contact Elizabeth to inform her of the request that will be headed her way.

**Comment by LKDOLIN** [comment]
To follow-on, #4 has been completed. 😊

**Comment by lzim** [comment]
Thanks @LKDOLIN and @jamesmrollins for keeping this moving.

We got an update from James on our call with @Bowlied this morning.

I really appreciate all of your efforts very much.

Lindsey

**Comment by jamesmrollins** [comment]
@LKDOLIN @TomRust here is the concept we explored last week for a verbal description of feedback loops.  The numbers indicate the tab order the visually impaired user would take through the description of the feedback loop. Note that the causal arrows are images and therefore can be custom tagged.  The variables indicated by text can only be identified "as read" by the browser assistance device.  We cannot embellish the description.  Thoughts welcome.  But this is going to be a bucket-load of work!

![image](https://user-images.githubusercontent.com/30132017/56478559-2a8f0000-6465-11e9-8454-75a807813160.png)

**Comment by LKDOLIN** [comment]
Good morning!

This is some top quality work here! I understand the tagging of graphical information and totally agree it should be completed. However, I see you’ve got small blocks of text (not in graphics, at least not visually) also tagged similarly. We should see if JAWS reads these. Graphics too really. If JAWS (or other assistive technology) reads these without the tagging included, you wouldn’t need to add the tags.

Let’s set up a time to go over these. I’m looking pretty good for this afternoon, and all day Wednesday and Thursday.

Thanks!
Lara

**Comment by jamesmrollins** [comment]
Hi @LKDOLIN !  Need to discuss with you the way forward regarding our 508 certification efforts.  I will likely have the CC model ready for review by Monday.  So I wanted to ask:
1.  Do I need to obtain a memo to your division formally requesting you to review our product?
2.  If so, what information should I include in the memo, and to whom should I address the memo?
3.  In terms of strategy, do we want to look at the models as they come out, or wait until they are all done.  I recommend we look at them as the come out, because they all have common elements that we can clear and reduce the workload to review the rest.  
4.  Do you want me to be present during the review (if that doesn't present a conflict)?  I would be happy to assist. 

Thank you
James

**Comment by LKDOLIN** [comment]
Hello @JMROLLINS!

Please see my responses below in italics. So sorry I missed your call earlier. I’ve been on back to back calls since 0630. It’s been one of those days!

Thanks!
Lara

**Comment by lzim** [comment]
@LKDOLIN and @jamesmrollins 

Thanks for keeping this moving 👍

**Comment by jamesmrollins** [comment]
Thanks @LKDOLIN !  I will reach out to you next week when CC is off the press and schedule a workshop.

Have a great weekend!
James

**Comment by LKDOLIN** [comment]
Sounds great, thanks James!

**Comment by staceypark** [comment]
@jamesmrollins I took a look at the issues and it doesn't look like there are any "functionality" issues, so I think we can do the final walk with @LKDOLIN and sign off.

FYI: @lzim

**Comment by jamesmrollins** [comment]
Hi @staceypark @lzim,

@LKDOLIN and I reviewed the simulation 508 compliance on Monday , 10/7 and completed the 508 checklist.  Lara will forward to the 508 office with a recommendation to certify.  

Thanks again Lara for helping us to make this a more accessible program!

James

**Comment by LKDOLIN** [comment]
One little clarification: I’ll do the certifying, not recommend certification. One less step!

**Comment by jamesmrollins** [comment]
@LKDOLIN an excellent clarification, even better - Thank you!

**Comment by staceypark** [comment]
@LKDOLIN How will we know when the certification has gone through? Should we expect an email from you with some sort of document?

**Comment by LKDOLIN** [comment]
I’ll send out the cert email. In fact, I will send it today. Who all on your side should be included on that email? Other addressees include two people at the VA 508 Office, my counterpart here, and that’s pretty much it.

**Comment by staceypark** [comment]
@LKDOLIN I think it would be a good idea to include Lindsey, James, and myself on that thread.

**Comment by lzim** [comment]
@jamesmrollins @LKDOLIN and @staceypark 

Are we ready to close this issue?? 🍾

**Comment by LKDOLIN** [comment]
It is D-O-N-E, DONE DONE DONE! That’s a wrap! You’re officially certified as fully compliant with Section 508. Party time!

Lara

**Comment by staceypark** [comment]
🎈 🎉 🍾 THANK YOU everyone!!
