### ISSUE TITLE
Story B: MTL Consultation and Capacity Story Boards

### ISSUE THREAD

**Issue by ghost** [lzim/teampsd#2954]
Team members review the[ story board ](https://lucid.app/lucidchart/55e08081-f499-416f-92c6-7f1f8254d29b/edit?invitationId=inv_c942b5c9-d9cc-4be5-9cef-2c244ab2ca11&page=0_0#)that @jamesmrollins Developed to map development of MTL Direct Consultation
- [ ] @lzim
- [ ] @hthrmarsh 
- [ ] @emilymetcalf114 
- [ ] @epearman

**Comment by jamesmrollins** [comment]
Hi @hthrmarsh - At this point, we may be better looking at the issue holistically, meaning we are trying to build a shared understanding of how we envision these two platforms working to support consultation and health equity analysis and our research aims:

1. Did we leave something out?
2. Did we find all the dependencies?
3. Did we consider how these features will collect and move information that supports research aims?

**Comment by lzim** [comment]
#adjuciate_memo - Unclear what this card is referencing #wontfix - 0 story points
