### ISSUE TITLE
2024_10 Update SAMHSA grant on mtl.how/team and mtl.how.demo

### ISSUE THREAD

**Issue by ghost** [lzim/teampsd#2957]
### Both [mtl.how/team](https://mtl.how/team) and [mtl.how/demo](https://mtl.how/demo)
- [x] Add the SAMHSA grant number to the top paragraph with the other grants
- [x] Add the SAMHSA, Hawaii DOH/CAMHD Logos to the appropriate sections

### Icons - Update logos to be consistently lower case
- [x]  demo not Demo
- [x]  facilitate not Facilitate

## AC for card closure
- [x] PROD instance updates reviewed by Lindsey
- [x] any modifications from review are made - _request made at 10/10 #sim_ui meeting to update maps+sliders which will be tracked via #3306_
- [x] close card once updates are made to PROD

**Comment by ljmoody** [comment]
@lzim, further clarification is needed:

## Add the SAMSHA grant link to the top paragraph with the other grants
1. What is the SAMSHA grant link? 
2. Should the intro paragraph on both /team and /demo be exactly the same? (They differ slightly now.) If so, which one is the most up-to-date currently?:
- [ ] /team site
![image](https://github.com/user-attachments/assets/53940e17-6b68-4104-aa0e-9ad06d002d3a)

- [ ] /demo site
![image](https://github.com/user-attachments/assets/b7b1372c-19b0-4001-9c5d-d1191c7d37e3)

3. Where would you like the link to be in relation to the other links? --and are there specific grant numbers associated with it as the r01, r21, etc?
![image](https://github.com/user-attachments/assets/e25cfdd0-7966-4a63-a4af-35e300e07018)
 
## Add the SAMSHA, Hawaii DOH/CAMHD Logos to the appropriate sections
1. Do these logos already exist? I cannot find them in teampsd, mtl, or research repos.
2. Where are the "appropriate sections" on the /team page to place these logos? --And should the logos be clickable?
3. Where are the "appropriate sections" on the /demo page to place these logos? --And should the logos be clickable?

fyi @matthewtomo

**Comment by lzim** [comment]
Thanks @ljmoody 

### Logo location
- The bottom of the page where the NCPTSD and NIDA logos are.

### Agency Logos
- [ ] SAMSHA logo can come from the Internet
- [ ] CAMHD logo can come from the Internet

### Text
- [ ] There isn't a link, but the grant to be added for SAMSHA is **H795M082961**
Neither paragraph appears current as neither describes the current **#consult_workflow** However, they should stay distinct as they are different websites. So, keep that distinction between /team and /demo
- [ ] But remove the sentence _Modeling to Learn_ supports frontline... from both.

Thanks!

**Comment by ljmoody** [comment]
@lzim, I'd like to review in either wk2 2024_10 #support_workflow or #sim_ui_workflow. Updates made so far (specific to this card only):

### mtl.how/demo TEST instance updates:
- [x] update logos: lowercase letters only
- [x] add SAMSHA grant H795M082961 to top paragraph
- [x] add SAMSHA and CAMHD logos to bottom of page
  - [ ] Descriptions are needed in order for logos to show; I added placeholder text 
- [x] remove "supports frontline" sentence

### mtl.how/team PROD instance updates:
- [x] add SAMSHA grant to top paragraph
- [ ] add SAMSHA and CAMHD logos to bottom of page
  - [ ] _Do you mean for these logos to fall under the Contact Us section?_ Clarification needed.
- [x] remove "supports frontline" sentence


What language would you like to describe the current #consult_workflow?

**Comment by lzim** [comment]
**wk 2024_10 - #sim_ui_workflow**
@lzim
@ljmoody 
@matthewtomo 
@jamesmrollins 

**Try to work for Tuesday 10/15 before our presentations.**

**Comment by ljmoody** [comment]
**Discussed at wk2 2024_10 #sim_ui_workflow**
@matthewtomo @ljmoody @lzim @jamesmrollins 

- [ ] **Goal: by Tuesday 10/15 COB: update Team PSD map / sliders - @matthewtomo & @jamesmrollins 

✔️ Laura created #3293 for lzim to work on after the above task is complete.

**Comment by ljmoody** [comment]
- Tracking maps/sliders work in a new card, #3306.
- All tasks on this card are complete and the Demo and Team sites are updated with: 
  - SAMHSA grant info 
  - HSRD changed to HSR
  - SAMHSA logo (Demo site only)
  - HSR logo (Demo site only)
- **#adjudicate_memo**: updated card from 3 to 5 points, given the effort involved; removed Matthew from card since his effort on Demo site was via card #3158

Closing this card as complete. 🚀

**Comment by lzim** [comment]
Thanks @ljmoody !!!

We just heard a talk by NIDA and SAMSHA leaders here at the meeting.
This is really timely!
