### ISSUE TITLE
2023_may_epic #story_b: Mtg about BHIP rollout and MTL alignment 

### ISSUE THREAD

**Issue by emilymetcalf114** [lzim/teampsd#2959]
@lzim to meet about BHIP roll out alignment with _MTL 3.5_ alignment. 

Agenda: 
- [ ] If/how the QIICs and the pilot facilities are using MTL to address questions and problems with staffing, care delivery, etc. in BHIP 
- [ ] How and when you all expect to scale up 
- [ ] How we can stay coordinated 
- [ ] Can/should I recommend that people seeking consultation go to you? 
- [ ] in relation to which questions? 
- [ ] Should that happen later?

**Comment by hthrmarsh** [comment]
@lzim 
@emilymetcalf114 

Scheduled 5/18/23:

![image.png](https://images.zenhubusercontent.com/6408f6bee4d68058a5b2cf6b/d9cfafdc-8a0e-40b5-ae4c-442bb0f2b116)

**Comment by lzim** [comment]
#adjudicate_memo - Meeting occurred in May 2023 but was never closed.
