### ISSUE TITLE
jun_epic_#story_b: as a system SME user, I need to login to a screen that gives me access to facility/site engaged for consultation

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2960]
## Definition of Done:
- [x] Update login procedure from Epicenter API V2, to Epicenter API V3 to facilitate the use of episodes for multiple model runs and user access to each run.
- [x] Ensure navigation is consistent with current Facilitator Dashboard.

**Comment by lzim** [comment]
**wk2 2023_may_epic
support_workflow**

Discuss
@lzim 
@jamesmrollins 
@emilymetcalf114 
@epearman

**Comment by jamesmrollins** [comment]
@lzim @epearman 

For support_workflow 5.10.2023

## Update

- [ ] We are currently trying to develop code so that we can assign all members of a group to an Episode.  An Episode is a single model run, inside of a group.  A Group can have multiple Episodes of model runs at the same time.  The API must return a project token to each user, and it is not working correctly.  The project token is also necessary for Team (Chat) functions.  
- [ ] Right now, Forio is working to provide a more complete working version of the API so we can get a project token to accomplish this feature.  We it may be a week or so away from complete resolution of this task.

**Comment by jamesmrollins** [comment]
@lzim @epearman 

## Question

Do we want to maintain the legacy home page alongside the Dynamics Decision Board?  This would enable us to still support legacy MTL 3.0 and reduce the need to change our documentation.
`If we want both, then when we create a team, we will add a "Consult" button that will set the team up to use the Dynamic Decision Board interface. This is a minor impact to coding effort`

**Comment by lzim** [comment]
**wk 3 2023_may_epic**
**support_workflow**

@epearman 
@jamesmrollins 
@hthrmarsh 
@lzim 

**DECISION:** 
Focus on aligning **user role group to platform dependencies** among the **consult_workflow** and the **Forio Epicenter v3 API** at the 2023_jun_roadmap planning meetings with #sim_ui_workflow @jamesmrollins & @lijenn (**Day 1; May 30).

#### All the _MTL 3.0_ PROD Release documentation is https://mtl.how/manual 
_MTL Workflow_ handoffs across platforms -  Team Set up in Teams, Sharepoint, Dynamics, Data UI & Sim UI
**Roles:** Guides are "Facilitator SAY guides" and "Learner SEE Guides" at https://mtl.how

#### Dependencies
- [ ] **#story_b pivot:" No longer "Facilitators and Teams of Learners" No we have "**sites**" receiving "**consultation**" to make "**decisions**."
- [ ] **ILEAD** Professional Development Teams 
   - [ ] Clinicians
   - [ ] Leaders
   - [ ] Improvers
   - [ ] Data/Modelers
   - [ ] Evaluators/Researchers
- [ ] **Forio Epicenter v3 API** - has different capabilities and role groups.
- [ ] **Microsoft Dynamics 365** - we need to 
- [ ] **LEAF** - can this support the initiation of the *8consult


**Sim UI DEV Instance**
https://mtl.how/sim_dev
- [ ] Identified we were missing a "Member" drop down in the Team Set up Menu

 
**Sim UI PROD Instance** 
https://mtl.how/sim

**Admin Role** - Artificial, a Facilitator with access to a different screen. 

#### Teams Setup Menu
 
**Facilitator - Facilitator,** **Team Lead,** and **"Team Member"**


 
_Previous State:_ **facilitate_workflow**
co_planning group
team is selected and set up
facilitated team meetings "MTL Facilitate & Teams of Learners"
 
_Current State_: **consult_workflow**
site engagement (3 sources: MTL study site lists, OMHSP site list, self-refer via mtl.help@va.gov
 
#### Team PSD #systems_smes provide a pre-packaged templated response 
(30 days lead time; 30 days to produce the recommendations report/slide deck):
- Report of recommendations, brief included in overall report that goes through Executive Leadership to Patient Care Services
- Slide deck summarizing _MTL_ resources_ used to guide the recommendations"
- No prep other that the consultants use the platforms to provide site consultation.

#### Desired Future State
- [ ] Integrated within OMHSP Sharepoint
- [ ] ILEAD videos and accreditation offered for consults
- [ ] LEAF is user-facing interface for initiating consultation
- [ ] LEAF API is integrated with GitHub, Forio, Power BI APIs

**Comment by lzim** [comment]
@jamesmrollins to update Title of card & Data based on #sim_ui_workflow F2F wk5 2023_may_epic
