### ISSUE TITLE
wk4 2023_apr_epic #story_b: Enabler Update login and run procedures to use Epicenter API V3 

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2962]
## Definition of Done

- [x] Review access procedures and update to Epicenter V3 API.  This includes creation and use of access tokens, permissions, and episode, group and world assignments. 
- [x] Ensure login dialogues are consistent with current version of Sim UI.

**Comment by lzim** [comment]
### wk2 2023_may_epic
#### support_workflow

Discuss
@epearman 
@jamesmrollins 
@lzim 
@emilymetcalf114
