### ISSUE TITLE
2023_wk2_nov_epic #story_b: Enabler: Update user documentation in _mtl_ Manual to explain Facility Sim UI Self-Registration

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2966]
## Update Points

- [x] Review Team setup functionality in Sim_UI
- [x] Devise and include relevant visual aids to promote user understanding.
- [x] Update the mtl.how/manual/Facilitator Technical Manual in the appropriate section.
- [x] Open a review pull request and ask @lijenn to review.

**Comment by jamesmrollins** [comment]
Hey @ljmoody I’m using Zenhub in GitHub, [click this link](https://app.zenhub.com/workspaces/team-psd-workspace-5e4ac9bd8d388dfba6d9aef5/board) to join my workspace and see other features available in GitHub or [download the Zenhub extension](https://www.zenhub.com/extension) and sign up with your GitHub account.
  _Posted using [Zenhub](https://www.zenhub.com)_

**Comment by ljmoody** [comment]
@jamesmrollins, please clarify what you mean by "Review Group setup functionality in Sim_UI".

Is this the self-registration documentation? 
Or perhaps you're referring to the process of a setting up a team, [Section 7.4](https://lzim.github.io/mtl/7-facilitator-technical-manual.html#set-up-a-team)?

**Comment by jamesmrollins** [comment]
Angels Meeting 7/14: Design review, decided to remove Tutor Feature from requirements for Self-registration wireframe.  Current design is ubiquitous in the web-verse and most should be able to navigate.

**Comment by lijenn** [comment]
Jenn and Laura decided the documentation for this is done. We are only waiting for the vault API issue to be resolved in #3026.
