### ISSUE TITLE
ICEBOX #story_b: Enabler: data scales are standardized to scales and organizational goals reflected in enterprise dashboards

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2968]
## Context

- Standard scales ensure that quantities have the same basis for comparison and do not visually imply equality.
- Scales should be uniform with enterprise scales and reflect success in the same manner.
- Scales should be uniform between the Data UI and Sim UI.

## Definition of Done

- [x] Review enterprise dashboards for standard quantities.
- [ ] Review enterprise dashboards for the expression of "success" on scales.
- [x] Propose a stock design (sketch) that incorporates an easy-to-read scale that indicates uniform minimum and maximum quantities, the point at which organizational goals are achieved.
- [x] Propose a flow meter design (sketch) that incorporates an easy-to-read scale hat indicates uniform minimum and maximum quantities, the point at which organizational goals are achieved (if appropriate).
- [x] Write code and Implement stock design on the Dynamic Decision Dashboard.

**Comment by lzim** [comment]
**wk2 2023_may_epic
support_workflow**

@lzim
@jamesmrollins 
@epearman 
@emilymetcalf114 
To discuss what this means.

**Comment by lijenn** [comment]
Let's talk about this to see where we are and if this is still needed or feasible at wk1 2024_08 or wk2, if needed.

**Comment by lijenn** [comment]
Discussed sim_ui_workflow 8/7:
@ljmoody @lijenn @matthewtomo @jamesmrollins 
- [ ] @jamesmrollins assumes we need to review https://mtl.how/sail and review the measures and scales that needs to be incorporated in the dashboard
- [ ] Need a crosswalk between a SAIL measure and a target stock

**Comment by matthewtomo** [comment]
**week 3 2024_08 Praxis Meeting**
@matthewtomo @jamesmrollins @ljmoody 

> - [ ] @jamesmrollins assumes we need to review https://mtl.how/sail and review the measures and scales that needs to be incorporated in the dashboard
- @jamesmrollins still needs to do this

**Comment by lzim** [comment]
**wk4 2024_08 #9am_workflow**
@lzim
@jamesmrollins 
@matthewtomo 
@dlkibbe 
@lijenn 
@ljmoody 

**DECISION:**
-  Close the goal of aligning to a VHA or OMH enterprise measure - there are many.
- However, the **grasping a sense of scale at a glance is an important.**
> Propose a stock design (sketch) that incorporates an easy-to-read scale that indicates uniform minimum and maximum quantities, the point at which organizational goals are achieved.
 > Propose a flow meter design (sketch) that incorporates an easy-to-read scale hat indicates uniform minimum and maximum quantities, the point at which organizational goals are achieved (if appropriate). 
 - ICEBOX this card for now.

**Comment by lzim** [comment]
#adjudicate_memo - we won't do this.
