### ISSUE TITLE
Story J Data Feeds: Show Distribution of Issues visual by number of issues and then also by number of story points

### ISSUE THREAD

**Issue by ghost** [lzim/teampsd#2970]
- [x] @dkngenda can we have a second visual just like the distribution of issues (see below) but shown by number of story points instead of number of issues. 
![image.png](https://images.zenhubusercontent.com/63331eaba895626f74a7c3a6/07682dac-0b85-4e4a-93f8-ec6df2e2c185)

**Comment by lzim** [comment]
Related issues@lzim identified on the Board by searching for **#story_j**

**1. Priority Epic** 2023_may_epic https://github.com/lzim/research/issues/639
**3. Epic Backlog** https://github.com/lzim/teampsd/issues/2970
****Icebox** https://github.com/lzim/research/issues/554
**Icebox** https://github.com/lzim/teampsd/issues/2445

**#mgmt_trio** - **Need to align these issues,** which are distributed across 3 areas of prioritization (Icebox, 1. Priority, 3. Epic BAcklog) without the **dependencies** identified:
@hthrmarsh 
@epearman 
@emilymetcalf114

**Comment by dkngenda** [comment]
@lzim @epearman  

The data tracker should now shows both story point and issue across the three workstreams. Note that a considerable number of issues (53%) do not belong to any of the three research streams (at least as documented on github)

![image](https://github.com/lzim/teampsd/assets/66848852/93005065-0cc7-41a9-af8f-f0dec0cda0cd)

**Comment by lzim** [comment]
Done. Closing the card. Thanks @dkngenda
