### ISSUE TITLE
ICEBOX #story_b: FEATURE: Consult issue form submission via LEAF MVP

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2973]
## Definition of Done

- [x] Complete LEAF training
- [x] Develop a draft story map for Consult workflow.
- [x] Develop a draft story map for GitHub issue templates.
- [x] Investigate and report out in the issue, if GitHub API can be used in conjunction with LEAF. (see issue #2897 for report)

Cross Reference: #2897

**Comment by jamesmrollins** [comment]
## Definition of Done

- [ ] Complete LEAF training
- [ ] Develop a draft story map for Consult workflow.
- [ ] Develop a draft story map for GitHub issue templates.
- [ ] Investigate and report out in the issue, if GitHub API can be used in conjunction with LEAF.

**Comment by lzim** [comment]
We will review the **user_story_maps** 
**wk3 support_workflow/sim_ui_workflow**

**Comment by matthewtomo** [comment]
#adjudicate_memo
@jamesmrollins @matthewtomo @ljmoody 
- Marking card as closed because we are not moving forward with LEAF integration at this time
- Keeping story points to cover investigation work
