### ISSUE TITLE
wk2 2023_may_epic: MTL Hawaii Coverage 

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2974]
**#people_ops_workstream** 
Led by @lzim 

#### wk1 2023_may_epic - > Data, IP, Process Measures
- [x] @lzim fielded and moved forward data/process measure discussion via email.

#### wk2 2023_may_epic
- [x] @dlounsbu & Pua H co-faciltated CO FGC; @lzim prepped at **#systems_sme**
- [x] @lzim facilitated discussion of process measures and we finalized the items & approach.
- [x] @lzim finalized this updated schedule via email, during meeting and arranged Team PSD coverage 
- [x] @lzim changed Hexagons to Team PSD "Red means 'read in from team data'  ![image.png](https://images.zenhubusercontent.com/5e4ac859b8781e56a5b7d6a1/f1c26440-7ae1-42db-93fa-28061dd6e00f)
- [x] @lzim compiled the 4 types of information from Hexagons for the wk3 meeting
> 1st Thurs – Carol, Amanda, relevant CAMHD staff
Primarily “Contracted Community Provider/Families” 
> 2nd Thurs - Keli, Jamie, Max, Jhansi, Dana, David J
Primarily “Data” focus – I recommend keeping a leader/CSO perspective (e.g., Keli/Jamie) with state-level view in this data call if it’s possible.
> 3rd Thurs – Kurt, Jamie, Scott, Keli - at 9AM Hawaii/12noon Pacific/3PM Eastern (@lzim, Gracelyn & Carrie to cover).
Primarily statewide “CSO/Clinical perspective”
> 4th Thurs - Leah, Shana, Mady, Scott or Pua 
Primarily “Leader” focus for Branch/Centers.

**Comment by lzim** [comment]
**wk3 2023_may_epic**

#### CSO/Clinical Perspective w/Pua H and Pua P**
@lzim
Gracelyn C
Carrie O

**1. Began our convergence introduction to Causal Loop Diagramming.**
Quick Link: https://mtl.how/camhd_cld_convergence
- [x] Introduced causality as direction of influence over time depicted with an arrow
- [x] Introduced the symbols + for same direction over time, and - for opposite direction over time.
**2. Focused on the comprehensive or time spent on info gathering from MHS1 Intake, to IMHE or Evaluation, to Eligibility Determination.

#### Phase 2 and Contract Mod 2 review
@lzim
@hthrmarsh 
Marisela D

**1. Contract Mod 2** - Awaiting Hawaii approval of notary.

**wk4 2023_may_epic**

**1. Phase 2 Invoice** - 
- [ ] @lzim - Pua H is moving forward with the 5 items identified for process evaluation.
- [ ] @lzim - To talk w/Sub-awards to Einstein & GHPIC @dlounsbu & Carrie
- [x] @lzim - Email Team PSD about the CLD Convergence Tab for review at KFGC on Wed with @TomRust & Pua H.

**Comment by hthrmarsh** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-PSD-Workspace-5e4ac9bd8d388dfba6d9aef5/issues/lzim/teampsd/2974?planning-poker) with Zenhub @lzim

**Comment by hthrmarsh** [comment]
#adjudicate_memo @lzim I'm leaning towards 13 story points per week for a total of 52 story points. The 13 points per week fits with the story points for the weekly operation cadences.

**Comment by lzim** [comment]
**wk5 2023_may_epic**

- [x] @lzim drafted a CLD "causal_loop_coverage" tab in Lucid reviewed w/@dlounsbu
- [x] @lzim drafted an aging chain - reviewed with KFGC & CAMHD leadership wk4 & wk5
- [x] @lzim and Pua finalized the process evaluation https://mtl.how/camhd_feedback
