### ISSUE TITLE
2023_wk3_jun_#story_b: QA DEV: Wireframe Review - facility self-registering user, I need to login.

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2978]
Definition of Done:

- [x] Review Facility Self-Registration Portal Wireframe.
- [x] Document any changes or required edits.

**Comment by jamesmrollins** [comment]
@lijenn - Your action. 

FYI:  @lzim @ljmoody @hirenp-esquare 

## See Wireframe for User Self Registration and Facilitator Dashboard changes

[Sim UI Release 3.5 - Self Registration and Fac Dash Update.pdf](https://github.com/lzim/teampsd/files/11728939/Sim.UI.Release.3.5.-.Self.Registration.and.Fac.Dash.Update.pdf)

- [ ] Still need to determine why we are indicating the Research Arm in setup.
- [ ] We will also need to update the auto-setup template function.  Will include in the LEAF wireframe.

## Regarding experiment and team data opt-in and attribution

![image](https://github.com/lzim/teampsd/assets/30132017/255270ee-de64-414f-a945-b3cb165f54a0)

- [ ] I am either going to create a new card for this feature and program it separately or add to the Reports Generator wireframe (likely).  
- [ ] @hirenp-esquare and I need to wargame how to attribute experiments somehow, in a manner to which it will not show up in the filename.  Likely will show up in the file header as the username. When the experiment file is downloaded and opened, then the username would be reviewable.
- [ ] Need to clarify the "Opt in" feature.  Is this a warning message similar to the cookie message, where folks need to be warned that their experiments will be accessible to others?

**Comment by lijenn** [comment]
Wireframe Review 
- [ ] Remove "Team" from "Team Data"
- [ ] "Team Setup" becomes "Facility Team Setup"
- <img width="702" alt="image" src="https://github.com/lzim/teampsd/assets/59668647/9e7b45cb-8001-4ffe-9b13-877d9f8fbf91">
- [ ] Geo-location should also include underscores for spaces (e.g. Palo Alto -> palo_alto)
- <img width="419" alt="image" src="https://github.com/lzim/teampsd/assets/59668647/cb7c459a-d04a-4f80-9d93-9a11d2af4cb6">
- [ ] @lijenn explore why research evaluation exits in existing design, look for research arm lucidchart wireframe.

-------
Logic Review/Questions
- [x] Do we need a Facilitator self-registration from Debbie's test in #2998)?
No, updated wireframe for self-registration should work for Facilitator, Lead, and Member roles since Adjudicator will assign the role.

**Comment by jamesmrollins** [comment]
FYI @lzim @dlkibbe @lijenn @ljmoody 

@hirenp-esquare - Please begin review and determine if you have questions regarding this wireframe.  I will be available Tuesday night after 9:30 PST, and Wednesday.

Updated wireframe and algorithm documents based on @lijenn feedback.

[Sim UI Release 3.7 - Self Registration and Fac Dash Update.pdf](https://github.com/lzim/teampsd/files/11740399/Sim.UI.Release.3.7.-.Self.Registration.and.Fac.Dash.Update.pdf)

**Comment by lijenn** [comment]
@jamesmrollins @lzim There are two instances where we have a Research Evaluation dropdown. One was in the Facilitator Self-registration and in Team Setup (now called Facility Team Setup) in the Sim UI.

**Facilitator Self-registration**
The [Lucidchart ](https://lucid.app/lucidchart/0b8d2254-f38c-4874-ad37-529f97a13901/edit?page=0_0&invitationId=inv_c472763f-6bac-44c4-bc69-ca2fdca4bcc4#)documents that there's a Research Evaluation in the intake form, but the logic doesn't mention anything about how/what it's used for.

**Facility Team Setup**
The [Lucidchart ](https://lucid.app/lucidchart/5dee6c56-1f51-40e8-aa06-4254452d0377/edit?page=DLisWQauxZEYe&invitationId=inv_c4194f82-432e-423d-a8af-a917fdf1f60d#)documents that it's used for TT reports. I believe this is how the TT reports knows when to have _MTL_ Blue or _MTL_ Red logo depending on the team.


It doesn't seem like having a Research Evaluation field in the previous Facilitator self-registration intake form did anything, so I don't think we need this field in the Facility self-registration.

But @jamesmrollins, what happens in the backend when a Facility team fills in the "Activity" and "Geo-location" sections?
- [ ] Would an adjudicator still need to into Facility Team Setup and make a selection in the Research Arm dropdown (assuming this is for facility that's participating in _MTL_ live facilitation)?
- [ ] What if a Facility team doesn't need to be in Research Arm (i.e. do we still have to make a selection in Research Arm)?

---------

**Wireframe Review for Site User Self Registration Process**
- [ ] For item 2, Activity Dropdown, is activity the right term? 
_Would "What type of team is at this facility?" be more clear?_
- [ ] For item 3, Geo-location, could we just say location or "Where is the facility located?"?
- [ ] For item 3's (i) information, I don't think we need to include "nearest". I assume the facility team always refers to the exact city/town they work in?

**Comment by lijenn** [comment]
Jenn decided the wireframe for this feature is already done. What is remaining for Dev is to work on the Vault API for Test Self Registration.
