### ISSUE TITLE
2023_wk4_jun_#story_b: QA DEV: Wireframe Validation: Meters of facility performance

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2980]
## Definition of Done:

- [x] Wireframe reviewed and validated against user design intent.
- [x] Feedback and corrections incorporated into final wireframe.

**Comment by lijenn** [comment]
Laura and Jenn decided the wireframe for Meters of Performance (i.e., home page of dynamic decision dashboard) is done.
