### ISSUE TITLE
ICEBOX #story_b: Enabler: Update user documentation in mtl manual to explain LEAF registration.

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2983]
## Definition of Done

- [ ] Review process flow in LEAF and document steps for completion.
- [ ] Investigate means for embedding help directly into LEAF.
- [ ] Update in mtl_manual
- [ ] Update in TeamPSD_manual

**Comment by lzim** [comment]
#adjudicate_memo
We are not developing LEAF.

**Comment by hnorthcraft** [comment]
#adjudicate_memo updating to 1SP closed as not planned/icebox
