### ISSUE TITLE
2024_feb_roadmap #story_l: As a consultant, I need an easy-to-use reports generator from the Sim UI.

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2985]
## Definition of Done

- [x] Provide a validated wireframe that illustrates how the reports generator will work.
- [ ] Investigate reporting via PDF and PPT for specific _mtl_ Report uses - incorporate these options as intuitively as possible to reduce the need for users to make multiple format selections.
- [ ] Provide an easy-to-use interface that reduces clicks and selection choices, rather incorporates choices already made on the decision dashboard.
- [ ] Investigate why we are collecting research arm data in the "Team Setup." Provide a brief summary in this thread attn: PI.
- [ ] Maximize transportability of report elements such as text and charts.  Executive Leadership Team (ELT), Primary Care Services (PCS) and Government Accountability Office (GAO) are target reports that mtl reports may feed into. 
- [ ] The report will be used to support the consultant, System SME and "Facility Team."
- [ ] Place at the top of the report, "Summary of Recommendations" field with full edit capability.
- [ ] Include Decision meters, see #2804 .
- [ ] Include opt-in warnings for experiments and team data. See https://github.com/lzim/teampsd/issues/2978#issuecomment-1588233242 for more information

![image](https://github.com/lzim/teampsd/assets/30132017/c1e5f8ac-d922-4fb2-aed3-774d634ed193)

**Comment by jamesmrollins** [comment]
Wireframes for the Reports Builder and Facilitator Dashboard Changes.

[Sim UI Release 3.7 - Facilitator Dashboard and Reports Generator.pdf](https://github.com/lzim/teampsd/files/12613360/Sim.UI.Release.3.7.-.Facilitator.Dashboard.and.Reports.Generator.pdf)

**Comment by lijenn** [comment]
Wireframe for MTL reports is completed. Currents updates on this feature are in #3028. Closing this card!
