### ISSUE TITLE
2023_wk3_jul_#story_b: QA DEV:  Wireframe Validation:  MTL Reports Generator

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2986]
## Definition of Done:

- [ ] Wireframe reviewed and validated against user design intent.
- [ ] Feedback and corrections incorporated into final wireframe.

**Comment by lijenn** [comment]
Jenn and Laura found that we are tracking the review of the wireframe in #3067. The development work has been done already, so we are closing this card!
