### ISSUE TITLE
2024_wk2_mar: MTL 3.5 Remove video icon in the Tutor of MTL 3.0 Sim UI PROD

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2991]
### Discussed wk1 2023_jun_epic

- [ ] @jamesmrollins - @lzim & @staceypark met and realized that for _MTL 3.5_ we can remove the video icon from the Tutor and we should be good to go for our ILEAD "evergreen" script-building & production in wk1 2023_aug_epic.

### Check off requirements to verify progress through feature_tracker.
- [ ] 1. **DEFINE in work_breakdown**
  - [ ] a. **what & why** - **written definitions of requirements** in a **numbered checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** requirement definitions an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 2. **DESIGN** in **operations_to_do** and **research_to_do**
  - [ ] a. **what & why** - **_MVP_ of design** of requirements in a **algorithm map, wireframes or design** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** design **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 3. **DEVELOP** in **under_development** - "frozen"

  Task Cards:
  #
---
- [ ] 4. **TEST in functional_test**
  - [ ] a. **what & why** - **TEST requirements** using **testing_checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** via TEST **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 5. **PROD in done**
  - [ ] a. **what & why** - **_DOCUMENT_ feature** using **document_tracker** for the **5 D's.** 
  - [ ] b. **date & who** -  **DELEGATE**
    - [ ] **describe_learners** [Jenn & Rita]
    - [ ] **detail_facilitators** [Jane & Debbie]
    - [ ] **document_team** [Anthony]
    - [ ] **disseminate_scientists_va** [Anthony]
    - [ ] **depend_products** [hq & ees]
  
  Task Cards:
  #
---
- [ ] 6. **closed** - fully documented, trained and ready for the next release.

**Comment by lijenn** [comment]
@tejaspesquare Please remove this Video Icon in all Tutor prompts in Prod:

<img width="715" alt="image" src="https://github.com/lzim/teampsd/assets/59668647/e8b5758a-f09e-4a36-93aa-1e7be753072e">

**Comment by tejaspesquare** [comment]
@lijenn  -  Video icon is disabled now on prod.

![image](https://github.com/lzim/teampsd/assets/144898781/6c612744-cf1f-44d7-8254-cad75444b656)

**Comment by ljmoody** [comment]
Thank you, @tejaspesquare! I can verify that the Tutor video icon is disabled in PROD instance. 🚀 

@lzim, because you created this card and there are many unchecked checkboxes in your initial post/comment, I'd like to leave the dispositioning of this card to you at this point.

**Comment by lzim** [comment]
Thanks @ljmoody!
As we work on #support_workflow efforts with @lijenn 

Reflecting our pivot to the _MTL 3.7 Consult Manual:_
_Should the Tutor say "Manual" instead of "Guide?"_

**Comment by lzim** [comment]
Closing this card, but added to wk1 2024_apr_epic #support_workflow agenda.
