### ISSUE TITLE
#2023_wk3-4_oct_story_I: As a Team PSD member, I need a GitHub refresher

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2992]
## Definition of Done

- [x] Discuss topics of interest with users.  Identify training needs.
- [x] Training date NOV 2
- [ ] Review adequacy of technical documentation  to ensure needs are covered.
- [x] Develop documentation for installing GitHub Desktop.
- [x] Create brief training outlines in the thread for members to review and comment.
- [x] Provide training during the training_workflow and record it.
- [ ] If training is of sufficient or better quality than existing recordings, update in the manual.

**Comment by lijenn** [comment]
Jenn and Laura decided to close this card since the training was completed. See #3084 for the work to add the training details in the Team PSD Manual.
