### ISSUE TITLE
wk? 2023_jun_epic Need to decide review self-registration for mtl.how/sim_test and mtl.how/sim_prod

### ISSUE THREAD

**Issue by dlkibbe** [lzim/teampsd#2998]
Discussed **#systems_sme_workflow wk2 2023_jun_epic** 
Cross-ref: #2964

@lzim 
@dlkibbe 
@jamesmrollins 
@lijenn 

#### We Dynamic Decision Dashboard at https://mtl.how/sim_dev 
_Do we want **#systems_sme_workflow** to be registered in DEV?_
- [x] **DECISION:** No. **#systems_sme_workflow** will not work with DEV, but will work with TEST and PROD.

_Next Steps:_
**#sim_ui_workflow** - Review the decisions from the F2F re: Sim UI self-registration with **#systems_sme_workflow**

**Comment by hnorthcraft** [comment]
#adjudicate_memo efforts tracked to #2964 , assigning dup
