### ISSUE TITLE
wk5_2024_jan_epic #story_l: Document MTL 3.5 workflow to include data ui export to sim ui for an MTL Report to be emailed

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#3001]
Discussed jun_epic sim_ui_workflow 2023_06_14

We need to set up _MTL 3.5 Red_ consults in the Sim UI (i.e we need to export their data) in order to email them a MTL report.

Update MTL 3.5 Manual to include how:
- [ ] We need to export from a _MTL_ Data UI a dataset based on clinic selections
- [ ] Set up _MTL_ Red consults in the sim UI

- [ ] @lijenn will tell Debbie we need to set up _MTL 3.5 Red_ teams in the Sim Ui

**Comment by ljmoody** [comment]
Captured content and using to develop #2987-Document Reports Generator
