### ISSUE TITLE
“I” information review and Master Crosswalk Workflow

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#301]
@jamesrollins and @tomrust

If @branscombj is going to review the current “i” Information that mainly Tom has drafted, should she do so here?

https://github.com/lzim/teampsd/tree/master/resources/master_crosswalk/current

Thanks for helping to clarify our workflow for “i” info update and review.

FYI @staceypark

**Comment by staceypark** [comment]
"i" information here: https://github.com/lzim/teampsd/tree/master/resources/master_crosswalk/info

**Comment by branscombj** [comment]
@lzim @TomRust Can we drop "due" from the names of any effect size variables where it currently exists; e.g. (AGG) Sensitivity of Staff Burnout Due to Long-Term Overtime.

**Comment by branscombj** [comment]
@lzim @dlkibbe Can we shorten the definitions of variables in the Team Data Tables by reducing explanations of the "cohort over a year", which is described in the introductory text of the i info box?

**Comment by branscombj** [comment]
> "i" information here: https://github.com/lzim/teampsd/tree/master/resources/master_crosswalk/info
> 
> 1. There are .md files for dynamic editing and viewing
Caution: Since there is a separate .md file for each module, we need to be careful that revisions that would apply in multiple modules are made in each place in the Excel file, if decided via GitHub pull request for one module.

**Comment by lzim** [comment]
Drawn from CC Issue #306 for review:

Review @branscombj and @dlkibbe please review the following "i" text for the switch:

“Control what data are used in the simulation - Select 0 for "RVI" to prioritize existing patients, where the team first sees all existing patients at the RVI estimated from the data, and only starts as many new patients as there are remaining open slots (based on RVI, supply, and missed appointment data). Select 1 for "New Patient Starts" to prioritize new patients, where the team first sees all new patients at the rate estimated from the data, and only sees existing patients at the RVI possible given the remaining open slots (based on start rate, supply, and missed appointment data).”

**Comment by lzim** [comment]
Drawn from CC Issue #306 for review:

Review @branscombj and @dlkibbe please review the following "i" text for the switch:

“Manually adjust the median number of weeks that patients receive care coordination visits with the team. (wks)”

@dlkibbe proposed this: 
> Change "i" text for "Additional Appointment Supply for New CC Patients" to, "Increasing the clinical hours allocated specifically to new patients will directly reduce the appointment hours available for existing patients."

But, I think we can get even shorter: "Increasing hours specifically for new patients reduces the hours available for existing patients."

**Comment by lzim** [comment]
Drawn from MM Issue #309 for review:

@branscombj and @dlkibbe please review the following "i" text for the switch:
“Control what data are used in the simulation - Select 0 for "RVI" to prioritize existing patients, where the team first sees all existing patients at the RVI estimated from the data, and only starts as many new patients as there are remaining open slots (based on RVI, supply, and missed appointment data). Select 1 for "New Patient Starts" to prioritize new patients, where the team first sees all new patients at the rate estimated from the data, and only sees existing patients at the RVI possible given the remaining open slots (based on start rate, supply, and missed appointment data).”

Provide following "i" text for the slider:

“Manually adjust the median number of weeks that patients receive medication management visits with the team. (wks)”

**Comment by lzim** [comment]
Hello Everyone, 

We need a consolidated issue for the latest _MTL 1.8_ edits out of the _MTL 1.7 to MTL 1.8_ development sprint are described across these open issues.

Yesterday, I attempted to copy out of the open issues below the relevant "i" text:
* #298 **1.7 to 1.8 Agile Development**
* #301 **“I” information review and Master Crosswalk Workflow**
* #306 **1.7.4 CC Modifications**
* #309 **1.7.4 MM Modifications**

The most recent edits should be reflected soon in a new **Master Crosswalk** uploaded soon here by @jamesmrollins:
https://github.com/lzim/teampsd/tree/master/resources/master_crosswalk/current

**There are edits that will need updating in the 
* data UI code @holbrooa  
* tt reports @saveth 
* based on modeling work by @TomRust 
* sim UI work by @jamesmrollins and 
* "i" edits by @dlkibbe and @branscombj 

I've included team members from all these interdependent workflows. We are still looking for the best version contrl approach to the "master crosswalk" and "i" upload...

**Comment by jamesmrollins** [comment]
@lzim @TomRust @staceypark @saveth @branscombj @dlkibbe @dlounsbu @holbrooa  I have updated and converted the Master Crosswalk table into mark down language.  It is currently in a pull request waiting for your inputs and approval.  I also updated the Pop-Up-Information table and converted it to mark down language.  It too is in a pull request.  

I'm not sure I got this right, but I tried based on the tutorials provided.  If you need to correct or add, just go into the raw data and make your edits directly into the mark down file.  When we are good to go and it the pull request gets pulled into master, then I can generate the necessary xlsx files for the SIM UI.

Thanks,
James

**Comment by TomRust** [comment]
@branscombj -- Sorry for the delay: Yes, let's drop "due" from any sensitivity slider.  It reads fine to me without it.

**Comment by staceypark** [comment]
@saveth @holbrooa @lzim @jamesmrollins @dlkibbe @branscombj @TomRust 
The master crosswalk and "i" information workflow has been moved to: https://osf.io/ygp36/

Please use the "check in/out" function to let others know when you are working with the file.
You do not need to rename the file after editing, because OSF will automatically version control for us. You can also chat and "@" individuals to discuss issues directly in OSF.

You can find OSF instructions below or ping me with any questions:
https://github.com/lzim/teampsd/blob/master/resources/cheatsheets/osf_cheatsheet.pdf

**Comment by lzim** [comment]
Per @staceypark's last post in March, and our discussion on Today's MTL Launch call.
We are using Open Science Framework for file version control on the Master Crosswalk here: https://osf.io/ygp36/

With the OSF Cheatsheet here: https://github.com/lzim/teampsd/blob/master/resources/cheatsheets/osf_cheatsheet.pdf

I'll close this issue 🏁 

> @saveth @holbrooa @lzim @jamesmrollins @dlkibbe @branscombj @TomRust
> The master crosswalk and "i" information workflow has been moved to: https://osf.io/ygp36/
> 
> Please use the "check in/out" function to let others know when you are working with the file.
> You do not need to rename the file after editing, because OSF will automatically version control for us. You can also chat and "@" individuals to discuss issues directly in OSF.
> 
> You can find OSF instructions below or ping me with any questions:
> https://github.com/lzim/teampsd/blob/master/resources/cheatsheets/osf_cheatsheet.pdf
