### ISSUE TITLE
ANDON Bug : Team Data not uploading in PROD

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#3011]
**1.Team Data file is not loading from either the Team Setup menu and from session home page:** 

FYI @lijenn @lzim @dlkibbe @dlounsbu 
Update Monday 9/25:
1. Discussed with Forio Team, likely a user private key problem that needs to be updated.
2. Will work with the Praxis DEV Team tonight to resolve.
3. Forio on standby tonight should they be needed.

1. When was the bug discovered? 9/22
4. Is this an invidivual or shared world? Team world
5. What is the name of the experiment? N/A

**2. In order for Team PSD to track this issue you must assign
- [x ] issues/bugs -  Select **bug_tracker** under project, on the right to initiate tracking a Bug.
- [x] features 
- [x] manuscript 

**3. Support Workflow:**  
i. **Pipelines** - prioritize in priority pipeline  
ii. **Assignee** - assign to a workflow user  
iii. **Label**- label value stream and workflow 
iv. **Milestones & Epics** - select monthly sprint milestone (GitHub) & epic (ZenHub) within the workgroup   
v. **Estimate** - estimate task in complexity points   
vi. **Epics** - assign to team-wide epic and TeamPSD master plan project  

**3. If you anticipate that your **issue card** or **bug card** will have **dependencies** these can be added once the issue has been submitted.   
viii=. **Add dependencies** - assess for and add dependencies *blocking* & *blocked by* this issue

**Comment by jamesmrollins** [comment]
@lzim @dkibbe @dlounsbu @lijenn @ljmoody 

The sim_ui team data upload function is working this morning.  I am going to do more testing with various browsers and remove the ANDON alert.  Thought you might want to get an update prior to your meeting with McClelland.

**Comment by lijenn** [comment]
I think this issue can close @jamesmrollins? Thanks!

**Comment by lzim** [comment]
I'm going to close. Re-open if necessary @jamesmrollins 

thanks for cleaning the board @lijenn :smile_cat:
