### ISSUE TITLE
wk1 2023_oct_epic Story B: QA TEST Clear Meters of Performance for MTL 3.7 Release wk1 2023_oct_epic

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#3013]
@jamesmrollins Please find Laura and my QA TEST review for #2979. Let us know if you have any questions.

@jamesmrollins Have you added E-Square members to this repo? If not, we need @lzim to do it due to 2-factor sign-in.

**Comment by ljmoody** [comment]
Hi @jamesmrollins. Please review the feedback below from the test session @lijenn and I had today. 
- [ ] 1. @ljmoody was able to create teams successfully (with Praxis login). While the team showed up in the Settings>Facility Team Setup, but the team did not show up in the Select Team dropdown menu. Same when logged in using Laura's VA email.
- [ ] 2. Carets should show/hide the different modules in the Dynamic Decision Dashboard: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBckQ0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--32577309e80c29d8479fce6040e91a1e0a4cbdd8/45bbc881-b989-48e3-9817-a44c3adda6ee.jpg)

- [ ] 3. Information box should have description of what the meter is showing:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBckg0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b467bac2c5c1fa47839e956d78ecd62d450f6265/3f30e052-f88f-4999-be1c-b56225d39290.jpg)

- [ ] 4. All Directives buttons (except Care Coordination) display nothing when clicked:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBclA0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b7f62d43468615fe578974b286405ad354fa1fad/bac86da9-8c9d-4f14-a4f0-078024960190.jpg)

- [ ] 5. When a user clicks on Play, they must re-select the team data in the Dynamic Decision Dashboard:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBclQ0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0a7f2483dd98bfe76c3f47125670472f909383a4/fe9accc4-a6a8-43a2-88d1-6b2e2a486108.jpg)

- [ ] 6. Episodes of Care does not do anything with the team data loaded (we were unable to test):
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBclg0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7b62b18b75fd9560deb5ed569f0d8af250952ed3/aed8fc31-fd65-401d-bc20-8a5dae1fdaa2.jpg)

- [ ] 7. Traffic Lights are buggy; unable to edit any of the fields:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcmI0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d1c926465476ac7e9632b5eb8e2a9377478d7072/8543650f-4036-477e-b650-61a22ae07994.jpg)

- [ ] 8. Boxes containing traffic lights aren't lined up on bottom:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcmY0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--89dc15cb582b82823a0148ca01b327b407f2817c/df943466-33f4-44ef-b5f0-e716904216e9.jpg)

- [ ] 9. Tutor button doesn't work with any of the additional features.

- [ ] 10. **SUGGESTION:** Remove "Episodes of Care" in modules where it doesn't make sense (CC, Team Care, Team Flow).

**Comment by lijenn** [comment]
Hi @tejaspesquare! Let us know if you have any questions or updates on the remaining checklists above in Laura's post!

**Comment by tejaspesquare** [comment]
> Hi @tejaspesquare! Let us know if you have any questions or updates on the remaining checklists above in Laura's post!

Hello @lijenn We have noted changes & added into to-do list. Will reach out to you or Laura Moddy in case any clarification. At moment team is focusing on estimation & developing Flow meters from CR 'Sim.UI.Release.3.7.-Dynamic.Dec.Dash.and.Widgets' & dedicating sometime to troubleshoot issue on 'Team Setup' issue for '⁠lmoody@praxisanalytix.com' account.

**Comment by tejaspesquare** [comment]
FYI: @ljmoody @jamesmrollins @lijenn 
Couple of changes moved to test instance. Please verify if possible.
Note: Kindly ignore alignment of Directives, Drop down Ellipsis on Dynamic Decision Dashboard for all models.

**Comment by tejaspesquare** [comment]
@ljmoody @jamesmrollins @lijenn Point 5 is also completed & available in TEST-Slow environment.

**Comment by lijenn** [comment]
> * [ ]  9. Tutor button doesn't work with any of the additional features. @jamesmrollins will develop Tutor wireframel

@jamesmrollins Do we want the Tutor pop-ups to explain the Dynamic Dashboard? @ljmoody and Jenn think the Dashboard is self-explanatory enough. But we could revisit this if users are finding it difficult to use. Otherwise, let's close this issue!

**Comment by ljmoody** [comment]
Closing; tracking progress in #3029.
