### ISSUE TITLE
Comparator Variables

### ISSUE THREAD

**Issue by saveth** [lzim/teampsd#302]
@lzim @ericasimon @staceypark @holbrooa 

I'm starting a new issue per our DS meeting last week to track the discussion on the variables for the R21/R01.

@holbrooa When you're able to, please add the following information to the comparator dataset: program complexity at the different sites, and urban/rural location status.

@lzim When the R21 mentions patient panel size, are we discussing patient count or visitation count or both? Can you also clarify staffing configuration? Are we talking about the count of different staff (psychologist, psychiatrist, etc.) or are we talking about proportion of staffing in these categories for a site?

Thanks in advance for the help. 😃

**Comment by lzim** [comment]
@saveth @staceypark @holbrooa 

I'm going to close this issue - I believe that we have more nuanced details we wanted to discuss on OSF for this.   We can re-open (if needed) on GitHub down the road.
