### ISSUE TITLE
2023_wk2_nov_#story_b: As a facility leader, I need to know where opportunities to improve Veteran care exist in the care system

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#3022]
## Build the following wireframe in the Sim UI:

![image](https://github.com/lzim/teampsd/assets/30132017/a338316a-e62f-42c8-a93a-a274391bff8d)

## Acceptance Criteria:
[ ] The when team data is selected and the user clicks on "Run" all models are run, the date returned to the Sim UI and displayed accruately on the display.
[ ] All models are represented in the display.
[ ] The objects on the screen are aligned with each other and the page. 
[ ] The drop downs work correctly.
[ ] Individual models can be accessed from the main dashboard.

**Comment by lijenn** [comment]
Jenn and Laura decided to close this card since the wireframe for this work is already completed.
