### ISSUE TITLE
2024_wk5_jan_story_b: Draw Tutor prompts wireframe

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#3023]
Draw a Tutor prompts wireframe to instruct dev team where to place pointers on the screen.  Provide explanations for the prompt text field.

Acceptance Criteria

- [ ] The tutor prompts are pointing to all relevant objects and buttons on the screen.
- [ ] The explanations are clear and concise.

**Comment by jamesmrollins** [comment]
@ljmoody Let's schedule time so I can show you how to do this.

**Comment by lijenn** [comment]
@jamesmrollins This is a blocker for #3013, if we still need tutor prompts for the Dynamic Dashboard.
FYI @ljmoody

**Comment by ljmoody** [comment]
Hello @tejaspesquare - please see [this PDF](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0xXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--25b044f9d52a90e87db1c76add4c89ae939fb9f5/DDD%20tutor%20wireframe.pdf) for the Dynamic Decision Dashboard tutor prompt wireframe.

- [ ] 1. Please add new dropdown + table for DDD:
<img width="1457" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2ZXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--990eb2d289e6cd8ac0c3d826de1184da751b0f04/image.png" alt="image.png" />

- [ ] 2. Add prompts + messages as shown in PDF, 1-10.

FYI @jamesmrollins, @lijenn

**Comment by ljmoody** [comment]
Closing this card and tracking in 2 new cards:
#3066 - dynamic dashboard tutor prompt wireframe
#3067 - _MTL_ reports generator tutor prompt wireframe
