### ISSUE TITLE
wk3 2024_jan_epic #story_b: DEV Causal Loop Diagrams

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#3024]
# Develop and Test the Team Care Flow and Causal Loop Diagram. 

## Team Care Story Causal Loop Diagram Wireframe:

![image](https://github.com/lzim/teampsd/assets/30132017/f357fdab-10c9-4d5d-a937-46dfa4c3be75)

### Acceptance Criteria

- [ ] When the user navigates to the Causal Loop Diagram, a new tab opens, and the diagram is presented without reveals, which are controlled by the Causal Loop Dynamics selections.
- [ ] When the user clicks on the direction of increase or decrease arrows, then the other increase or decrease arrows respond in accordance with the polarity of the causal arrow.
- [ ] When the user clicks on Causal Loop Dynamics, such as Link Polarities, Loop Polarities and Increase or Decrease, the diagram builds as prescribed in the wireframe.
 
## Team Care Flow Diagram Wireframe

![image](https://github.com/lzim/teampsd/assets/30132017/c7bbf347-3fe7-4aad-8d05-b54e9a49bed6)

![image](https://github.com/lzim/teampsd/assets/30132017/cb5810f1-cce3-4492-92a9-bb5aeab54c15)

![image](https://github.com/lzim/teampsd/assets/30132017/b9c117f5-0935-4a95-a054-b1313f2d083b)

![image](https://github.com/lzim/teampsd/assets/30132017/b49e3b1a-14a1-4aea-8813-664e10470a8f)

### Acceptance Criteria

- [ ] When the user clicks on the "Flow" icon from the Dynamic Decision Dashboard, the user is presented with a new browser tab with the diagram depicted in the wireframe.
- [ ] The flows and stock variables are proportional to each other based on the instructions in the wireframe.
- [ ] Flows are labeled with actual values. 
- [ ] Stocks change color based on rules depicted in the wireframe.

**Comment by lijenn** [comment]
CLDs dev work is done, just review and feedback is left. Closing this card and adding details for Flow in #3085.
