### ISSUE TITLE
2024_feb_epic #story_b: QA DEV: Review Directives to Case History Matrix Wireframe

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#3025]
# Review Directive 1160.01 to Case History Table

<< Wireframe to be published by wk2_dec >>

## Acceptance Criteria

- [ ] When user clicks "Directives" from the Dynamic Decision Dashboard, the Table presents in a pop-up.
- [ ] The table presents columnar information regarding specific references within Directive 1160.01 that require actions by facilities that are supported by the Data UI and the Sim UI.
- [ ] These actions are then referenced to links to TT 3 Reports and easy-to-understand Case Histories that support how the directives were supported in application by other facilities. 

### Note:

- Consider formatting the TT 3 reports into the new report format that provides a summary findings to orient the viewer.
- May need to produce these formats outside the Reports Generator due to backwards compatibility issues.

**Comment by lijenn** [comment]
Discussed Praxis Meeting 3/22/24:
Work for this has been done. Next step is for Dev to develop the _MTL_ Directives Video table for 3.7.
