### ISSUE TITLE
wk3 2024_apr_epic #story_l Bug: teampsd repo render-book errors

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3036]
**Receiving "R 4.3.2" error, preventing gh-pages renderbook action's successful completion** 
fyi: @tejaspesquare see highlighted portion of screenshot below:

![image](https://github.com/lzim/teampsd/assets/124643236/d494e987-1ed3-4162-82c4-bcd86e3f6400)

1. Discovered 11/20/2023 when merging a feature-gh-pages branch to gh-pages branch within **teampsd repo**. 
2. Error message: "Failed to get R 4.3.2: Failed to get R 4.3.2: Failed to download version 4.3.2: Error: Unexpected HTTP response: 404"

**Comment by lijenn** [comment]
@ljmoody Where are we with this bug? Can you please update the ZenHub details or bring this the 2024_feb_roadmap? Thanks!

**Comment by ljmoody** [comment]
@lijenn, the _MTL_ repo was prioritized (with the same two bugs), so the render-book issue and Node 12 deprecation error (#3037) for TeamPSD repo haven't been addressed as of yet.

@tejaspesquare - is there an update or estimate for when #3036 and #3037 may be addressed by your team?

**Comment by lzim** [comment]
@ljmoody  & @lijenn 

Moving this from **New Issues** Pipeline to **In Progress** Pipeline in ZenHub.

**Comment by ljmoody** [comment]
@tejaspesquare - today I merged a pull request into the main gh-pages branch and received the render-book errors shown below:
![image](https://github.com/lzim/teampsd/assets/124643236/4f2b7311-5a5f-463a-8970-36f55ba869d0)

**Error messages:**
- Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v2, r-lib/actions/setup-r@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
- The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2, r-lib/actions/setup-r@v1. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

**Comment by tejaspesquare** [comment]
@ljmoody - (as mentioned in #3037) We have applied changes for following 2 branches (v2 replaced with v3, actions/checkout@v3). Can you please check it should work.
![image](https://github.com/lzim/teampsd/assets/144898781/28e4f2a6-99a5-410f-83c9-8c6785c1dd4d)

**Comment by ljmoody** [comment]
Hi there, @tejaspesquare - I made several small changes to the feature-gh-pages_3.0_updates branch and pulled into gh-pages. While it is merging the updated information into the gh-pages branch, the gh-pages website (manual) is still not updating. I'm pasting in below screen captures:

![image](https://github.com/lzim/teampsd/assets/124643236/fc5b22dc-430e-4682-b3f4-604b9040d0cd)

![image](https://github.com/lzim/teampsd/assets/124643236/b233acb4-cf44-476c-86b4-67a8c9859f69)
