### ISSUE TITLE
wk3 apr_epic #story_l Bug: deprecation errors, teampsd repo

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3037]
**Receiving deprecation errors upon render-book actions firing** 
fyi @tejaspesquare 
1. Discovered 11/20/2023 when merging a feature-gh-pages branch to gh-pages wtihin **teampsd repo**.
2. Error message: see highlighted portions of screenshot below.

![image](https://github.com/lzim/teampsd/assets/124643236/0324b2e9-0585-4b30-ab89-825e695cd75c)

**Comment by lijenn** [comment]
@ljmoody Where are we with this bug? Can you please update the ZenHub details or bring this the 2024_feb_roadmap? Thanks!

**Comment by ljmoody** [comment]
@lijenn, the MTL repo was prioritized (with the same two bugs), so the render-book issue and Node 12 deprecation error (https://github.com/lzim/teampsd/issues/3037) for TeamPSD repo haven't been addressed as of yet.

@tejaspesquare - is there an update or estimate for when https://github.com/lzim/teampsd/issues/3036 and https://github.com/lzim/teampsd/issues/3037 may be addressed by your team?

**Comment by ljmoody** [comment]
@tejaspesquare - FYI: I updated a feature branch and submitted a pull request today. Below is a screenshot of the action checker deprecation errors: Node.js 16, node12, set-output.

![image](https://github.com/lzim/teampsd/assets/124643236/d89cf943-88d7-49ff-97bb-c2d18495880f)

**Comment by ljmoody** [comment]
Hi @tejaspesquare, today I merged the above pull request into the main gh-pages branch and received the deprecation error shown below; I'll add the render-book errors to that separate card (#3036). It was unsuccessful. 

Additionally, I looked back several months, and it looks like the following pull requests were not successful and did not update information as they should have: #3007, #3035, #3077.

![image](https://github.com/lzim/teampsd/assets/124643236/8efeee5f-e67d-4610-9a62-282025952b05)

**Comment by tejaspesquare** [comment]
@ljmoody - We have applied changes for following 2 branches (v2 replaced with v3, actions/checkout@v3). Can you please check it should work.
![image](https://github.com/lzim/teampsd/assets/144898781/739b0993-80aa-40f3-8d81-660313951182)

**Comment by ljmoody** [comment]
Hi @tejaspesquare - the v1 deprecation error is now solved. 🎉 
This deprecation error still remains, but I'm unsure of if it's technically a deprecation error or a render-book error, so am including a screenshot here, as well as in #3036:

![image](https://github.com/lzim/teampsd/assets/124643236/19e35bb6-48f5-48dd-861c-6a8ac8ea9e34)

**Comment by lijenn** [comment]
Discussed Team Praxis Meeting: 
@jamesmrollins resolved deprecation bugs.
