### ISSUE TITLE
wk3 2024_mar_epic #story_l: deprecation errors, mtl repo

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3038]
**Receiving deprecation errors in mtl repo when render-book actions fire in mtl repo** 
FYI @tejaspesquare, Jenn and I would like to use the gh-pages rendering of the _MTL_ manual in our training session with users on November 29. If there is something I need to do or can do to help, please let me know. 

Discovered 11/20/2023 when merging a feature-gh-pages branch to gh-pages branch within **mtl repo**.
Error messages: see highlighted portions of screenshot below.

![image](https://github.com/lzim/teampsd/assets/124643236/24dce0cb-9779-45a6-92ae-4d11a0133afc)

**Comment by tejaspesquare** [comment]
@ljmoody We are not sure for what reason it is occurring. It will require thorough investigation on the issue & will take time. 

At moment we are focusing on tasks mentioned here https://github.com/lzim/teampsd/issues/3029  (see at bottom 24th Nov comments)

**Comment by lijenn** [comment]
@tejaspesquare In case this helps, I wonder if [our renderbook.yml](https://github.com/lzim/teampsd/blob/gh-pages/.github/workflows/renderbook.yml) needs to be updated with the new version? 

I found this from the README.md of the owner/github action's repo: 
https://github.com/JamesIves/github-pages-deploy-action#using-an-ssh-deploy-key-

- The action is now on version 4. Our .yml is version 3.
- We may just a new GitHub token (maybe our token expired?) or use an SSH key.

**Comment by tejaspesquare** [comment]
@ljmoody @lijenn  We have found one solution but not certain it will work or not. Could you please apply change on renderbook.yml by adding following variable & see if it works. 

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
     
![image](https://github.com/lzim/teampsd/assets/144898781/bed076f1-7b70-4597-9bb5-1df4b375a01c)

We can setup a call to do trial run. Please let us know your suitable time in case it is required.

**Comment by lijenn** [comment]
@tejaspesquare We tried adding the code below in the .yml file, but it didn't work. Any updates on the deprecation errors?

> env:
ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

**Comment by tejaspesquare** [comment]
@lijenn - We will update you soon about this error. Actually, we are waiting for meeting with James to verify solution we found. Thanks!

**Comment by jamesmrollins** [comment]
@tejaspesquare you can coordinate directly with @ljmoody and @lijenn for issues regarding actions and testing.

**Comment by ljmoody** [comment]
@tejaspesquare - Adding a new (to me) deprecation Action Checker message to this thread. Discovered 1/29/24 when committing changes to a .md file in the _MTL_ repo:

![image](https://github.com/lzim/teampsd/assets/124643236/7c51af1c-0e8f-4e14-af27-42b7d48b5cd2)

FYI @lijenn @jamesmrollins

**Comment by lijenn** [comment]
Discussed Team Praxis Meeting: 
@jamesmrollins resolved deprecation bugs.
