### ISSUE TITLE
Bug: wk3 2023_nov_epic #story_l: mtl repo render-book errors

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3039]
**Receiving "R 4.3.2" error that prevents gh-pages render-book actions from successfully completing** 
FYI @tejaspesquare, @lijenn  and I would like to use the gh-pages rendering of the _MTL_ manual in our training session with users on November 29. If there is something I need to do or can do to help, please let me know. 

Discovered 11/20/2023 when merging a feature-gh-pages branch to gh-pages branch within the **mtl repo**.
Error message: see highlighted portion of screenshot below:
![image](https://github.com/lzim/teampsd/assets/124643236/cfd56316-3cca-4358-9f75-a55e4023e9ad)

**Comment by lijenn** [comment]
@tejaspesquare When could the errors regarding render-book be addressed? Any chance fixing the deprecation errors in #3038 could fix render-book? Thanks!

**Comment by tejaspesquare** [comment]
@lijenn - Issue has been fixed on local branch & want to verify same with James before applying solution on main branch. We will let you know once it is done.

**Comment by lzim** [comment]
Nice work on this @lijenn  & @tejaspesquare 

_Is this issue ready to close?_ 

I see the epic is still labeled 2023_nov_epic but we close out 2024_jan_epic next week. 

Thanks again!

**Comment by tejaspesquare** [comment]
@lzim - Thank You!   Issue has been resolved & I believe it can be closed.

**Comment by lijenn** [comment]
Jenn and Laura decided this is done. The remaining MTL Manual errors are tracked in #3038.

**Comment by hnorthcraft** [comment]
#adjudicate_memo based on comments above i think this is probably more than 1sp? maybe 3? @lijenn

**Comment by lijenn** [comment]
@hnorthcraft 2 SP since the error was reported, fixed, and tested relatively quickly once it got prioritized.
