### ISSUE TITLE
2024_feb_epic #story_b: DEV Tutor Prompts

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3050]

**Comment by lzim** [comment]
@ljmoody 
@lijenn 
@jamesmrollins 

I may have closed this in error earlier in the week when I was trying to discern **sim_ui_workflow** priorities from the board.

_Is this card re: Sim UI Tutor captured elsewhere?_ 
_Should the card be in 2024_feb_epic for roadmpapping?_ 

Thanks for clarifying!

**Comment by ljmoody** [comment]
Good catch @lzim - I would recommend we keep this open, since the Tutor Prompt draw/dev/test cycle isn't complete yet. Added it to 2023_feb_epic to roadmap.

**Comment by ljmoody** [comment]
Closing this card; tutor prompts are being developed and tracked in their own cards and posted to DEV team via TEST cards for dashboard features.
