### ISSUE TITLE
2024_feb_epic #story_l Bug: Outdated Mapped Teams in Sim TEST

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#3051]
Tested at systems_sme_workflow w/ Debbie, David, Lindsey:

Why do Lindsey, Debbie, and David mapped to these teams?  They also see different teams.
![image](https://github.com/lzim/teampsd/assets/59668647/befef162-ad9e-481d-b943-3250e3ed1535)

**Comment by tejaspesquare** [comment]
@lijenn - Outdated you mean shared team which we have removed in login. We do require more details to debug this issue. As of need Login details.

**Comment by tejaspesquare** [comment]
@lijenn - In order to troubleshoot this issue can we have login details. Or if you like to have a discussion in our next meeting.

**Comment by lijenn** [comment]
Hi @tejaspesquare, The outdated teams are just old Test Slow teams that we'd like to remove since we have so many of them and we do not use them. Lindsey must have gotten mapped to it during auto-set up.

@ljmoody and @lijenn will delete the old Test Slow teams to clean up list of all teams/team set up.

**Comment by ljmoody** [comment]
@ljmoody removed test-slow teams created prior to Feb 28, 2024.

**Comment by lijenn** [comment]
Jenn confirmed outdated/unused Test teams are gone. Closing!
