### ISSUE TITLE
2024_mar_epic #story_l: Archive MTL 3.0 releases and associated information

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3055]
Reference: sim_ui_workflow meeting on January 10, 2024
*Need all the archives, TEST environments, and manuals/documentation discussed.

**Definition of Done:**

- [x] Archive SEE guides.
- [x] Archive SAY guides.
- [x] Include an underscore between mtl and the version number:
    - [x] mtl_1.7, mtl_2.0, mtl_3.0, mtl_3.7
- [x] Inventory and ensure there is an archive of each release:
    - [ ] mtl_1.0
    - [ ] mtl_1.7
    - [ ] mtl_2.0
    - [ ] mtl_3.0
    - [ ] mtl_3.7
---
**DECISIONS - Archives we need for each release:** (from sim_ui mtg 1/10/24)
- [x] Archive all release version files at https://mtl.how 
    - [x] ADD: release_3.0
- [x] Within the blue branch of https://mtl.how 
    - [ ] ADD: mtl_3.7_models
- [x] Archive full guide branches for each release mtl_1.7 mtl_2.0, mtl_3.0, mtl_3.7 that were hosted at https://mtl.how 
    - [x] e.g., release_1.7 
- [x] Archive each _MTL_ Manual  https://mtl.how/manual
- [x] Archive each set of _MTL_ Videos.
- [ ] Archive each set of Power BI Data UI files for each release. 

_Done:_
**gh-pages_mtl_2.0_archive** (archive of our _MTL 2.0_ manual) 
 
_Now:_
**gh-pages_mtl_3.7_test** (our _MTL 3.7_ TEST manual)
 
**gh-pages_mtl_3.0_archive** (archive of our _MTL 3.0_ manual)
 
**gh-pages_mtl_3.7_test_archive** (archive of our _MTL 3.7_ TEST manual)
 
_February 2024:_
**gh-pages_mtl_3.7** (our _MTL 3.7_ PROD manual)
 
**gh-pages_mtl_3.7_archive** (archive of our _MTL 3.7_ PROD manual)
 
**Do not worry about walking back work to archive an MTL 3.0 version of the manual.**
Likely provisional conclusion  - we will be only work in **PROD with these 12 NIH sites wrapping up in Jan/Feb.**
**Documentation:**
- [x] Self-registration
- [x] MTL Reports
And yes, we need all the archives, TEST environments and manuals/documentation we discussed.

**Comment by hnorthcraft** [comment]
#adjudicate_memo if I'm reading this correctly, the effort here seems to be tracked on other cards? is there any SP effort that should be attached to this one? @lijenn

**Comment by lijenn** [comment]
@hnorthcraft I think the effort is tracked in this card and the work lives in the associated gh-pages branches. 8 SP for this task.
