### ISSUE TITLE
2024_06: Finish Reviewing ILEAD MTL Enduring Videos & Provide all Graphics

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#3057]
**Discussed at wk3 #systems_sme_workflow**
@dlounsbu 
@lzim 
@dlkibbe 

@dlkibbe review the video and indicate the graphics needed for that video on the issue task card on GitHub. 
 
[x] video 1 - @lzim to try to create high res 
[x] video 2
[x] video 3
[x] video 4
[x] video 5 
[x] video 6
[x] video 7 
[x] video 8 - @lzim to try to create high res

**Comment by lzim** [comment]
**wk1 2024_06 #ilead_workflow update for June Roadmap Event https://mtl.how/2024_roadmap** 
- [x] @lzim approved the last of the first 8 videos wk5 2024_05
- [ ] Greg H (our #ilead_workflow video editor) released the next 8 and Lindsey will review wk1 2024_06
- [ ] Anticipate review and approval of batch 2 and batch 3 in 2024_06

**FYI: #support_workflow**
@ljmoody for the _Why/how use case_ documentation for the README.md at https://mtl.how

**Comment by lzim** [comment]
**wk5 2024_07 #ilead_workflow**
**Gallery Page - https://site-97998392.bcvp0rtal.com/**
1 - How Might Modeling to Learn help? - https://bcove.video/465KOIt .
2 - What gets in the way of meeting patient's needs? - https://bcove.video/4d4TmRZ
3 - How can we get more patients better without more hours in the day? - https://bcove.video/4bIhtF6
4 - How can a Modeling to Learn consultation help? - https://bcove.video/3WuJ7kI
5 - Why is Modeling to Learn useful when we have critical staffing and hiring needs? - https://bcove.video/4f7OfSL
6- How does Modeling to Learn benefit Substance Use Disorder or SUD programs? - https://bcove.video/46dSKHt
7 - How does Modeling to Learn benefit PTSD Clinical Teams or PCTs? - https://bcove.video/3zNR6An
8 - Can Modeling to Learn benefit Behavioral Health Integration Program or BHIP teams? - https://bcove.video/4bQfDSH
9 - How does Modeling to Learn support stepped care? https://bcove.video/4d6F2Ja
10 - How does measurement based care detect patient improvement or risk? https://bcove.video/3yl8FqY
11 - What are key drivers of higher care quality to improve recovery and prevent suicide? https://bcove.video/4c1YgOQ
12 - How can we improve SAIL with Modeling to Learn? https://bcove.video/4dmPVX5
13 - Why is the Modeling to Learn Red Data User Interface useful? https://bcove.video/3A6i7Py
14 - How do five key variables drive care quality over time? https://bcove.video/3A3sBiG
15 - Why is the Modeling to Learn Blue Simulation User Interface useful? https://bcove.video/4fnG5Gb
16 - Why is applied systems thinking more likely to help us avoid costly mistakes? https://bcove.video/3AelyUg
23 - How can we better balance needs of new and existing patients? https://bcove.video/3yaXy41
24 - How can we leverage the feedback, rates, and volume of our local care system? https://bcove.video/4fonk5v

**Comment by matthewtomo** [comment]
@lzim

- This issue is still slated for the 2024_06 Epic
- Can you please update the card so that we can close the Epic?

**Comment by ljmoody** [comment]
Remaining videos received. BrightCove links to those are:

17 - Why is Modeling to Learn able to provide new insights? - https://bcove.video/3XEKDAY
18 - Why does Modeling to Learn emphasize flows through care? - https://bcove.video/3ME6cvm
19 - How does Modeling to Learn improve medication management? - https://bcove.video/3To3mP4
20 - How does Modeling to Learn help improve psychotherapy? - https://bcove.video/4gjSdbG
21 - If we keep making the same care decisions, will things get better or worse? - https://bcove.video/4cZpLJk
22 - How does an appointment backlog extend the weeks between visits? - https://bcove.video/4d3jVGG

Video links are updated in 3.7 readme. Chaps 1&2 video links also updated; will be live upon next gh-pages build (likely today). Moving this card to done; suggest closing upon gh-pages update.

fyi @lzim
