### ISSUE TITLE
wk? 2024_jan_epic: BUG MTL Menu Page Broken - 502 Bad Gateway

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#3058]
@ljmoody @lijenn Found that the https://mtl.how/menu page is no longer working. 

There have been no development work on this feature and page so we are unsure why this page is no longer working:
<img width="1705" alt="image" src="https://github.com/lzim/teampsd/assets/59668647/ed472e9c-4265-4abb-90eb-be46dd1fcb80">

@lzim @dlkibbe @dlounsbu _I don't think anyone is using _MTL_ Menu for any consultations either?_

**Comment by lzim** [comment]
_Update:_ 

@dlounsbu & @lzim Both were able to see and download PDFs for teams.
- @lzim created a card on research repo to track the exporting and saving of the reports for R21 findings & fidelity manuscripts.

**Comment by lzim** [comment]
But is squashed! 🐛 💪🏽

**Comment by lzim** [comment]
#adjudicate_memo

Decided this bug required a 2 pt and 3 pt amount of DEV value_stream effort:

<img width="1532" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd09hQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--781d6783966d6847bd990eccc98ac4f1f7a8b79b/image.png" alt="image.png" />
