### ISSUE TITLE
ASAP Sim UI TEST: Could add team members to create a team for NIH Site (see research/595)

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#3059]
**#sim_ui_workflow**
@jamesmrollins 
@ljmoody 
@lijenn 

**#systems_sme_workflow met today for our 3 hours of prep for two _MTL 3.5 PROD_ or _MTL 3.7 TEST_ sites** 
- See [research #595](https://app.zenhub.com/workspaces/team-psd-workspace-5e4ac9bd8d388dfba6d9aef5/issues/gh/lzim/research/595)

**Here is the screenshot of the error observed from my VA Desktop using Chrome:**

![image](https://github.com/lzim/teampsd/assets/7454688/f62a07ce-5cfe-4e42-ac85-cafc03380864)

**Comment by ljmoody** [comment]
Team Praxis says this card is CLOSED! :)
