### ISSUE TITLE
1.7.4  CC Module Update

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#306]
@lzim @branscombj @dlkibbe @dlounsbu 

**1.7.4  CC Modifications**

@TomRust indicated changes to the CC module below:

**Features added:**

- Data switch now selects for the model to either have the new patient start rate OR the RVI = team data (as it can’t be both).  Feedback loop is intact for both options.  Currently, the switch is set to 0 = Use data on RVI, and the team could slide it over to 1 = Use data on New Patient Starts. 
- Model starts at week -13, in equilibrium (no need for hundreds of weeks’ to “get settled”).
- When experimenting with “additional appointment supply for new CC patients,” these slots now come at the expense of slots for existing patients – we’re not letting them make the pie bigger by pulling slots from outside the model boundary.

So, I changed itext for 

- “Additional Appointment Supply for New CC Patients”: Manually increase the clinical hours allocated specifically to new patients, where these "carve-out" appointments come directly from reducing appointment hours available for existing patients.
- Data Switch (now called “Use Team Data for Starting Rate or Return Visit Interval”): Control what data are used in the simulation - Select "RVI" to prioritize existing patients, where the team first sees all existing patients at the RVI estimated from the data, and only starts as many new patients as there are remaining open slots (based on RVI, supply, and missed appointment data).  Select "New Patient Starts" to prioritize new patients, where the team first sees all new patients at the rate estimated from the data, and only sees existing patients at the RVI possible given the remaining open slots (based on start rate, supply, and missed appointment data).

**To that end, I have modified the Sim UI and Experiments as shown:**

![image](https://user-images.githubusercontent.com/30132017/52077897-eca9cc00-2546-11e9-804c-e050e048fcbc.png)

**Here is another switch with alternative wording (this switch seems clearer to me).**

![image](https://user-images.githubusercontent.com/30132017/52078574-5d051d00-2548-11e9-8dc3-9521d45b8192.png)

With blessings, I will move this into development. ~James

_Originally posted by @jamesmrollins in https://github.com/lzim/teampsd/issues/298#issuecomment-459464579_

**Comment by lzim** [comment]
Hello @jamesmrollins @TomRust @staceypark @dlkibbe @branscombj @dlounsbu 

I apologize for being slow on this feedback. :turtle: Overall, I'm sprinting right along 🐰  
We do need this final and to DEV ASAP. Let's make sure we are ready for that by the end of the MTL Launch call today.

I believe the new switch could simply be this, no need to re-reference "team data" when that is already shown as an exogenous "Team Data" input below, and the slider is Red, which learners will know is from team data by convention. I believe this also means we will not need to include the word "use." 

I am not convinced that calling this switch "Prioritize Patients" will be well-received by providers. We will further explain the operational definition (as above) in the "i" information text, what about just using "Prioritize" alone as the header, then showing where the data comes from as below:

**"Prioritize"**
**left = "New Patient Starting Rate"
right = "Existing Patient Return Visit Interval"**

**Comment by jamesmrollins** [comment]
**Below are a summary of requested changes in MM:**

1.  Change team data switch into "Prioritize" switch as shown.  Change "Median Engagement in CC" to "Engagement Duration (median)(weeks)" in the Team Data Table.  Base case variable will be mapped to “fRVI," Vensim variable.
 
![image](https://user-images.githubusercontent.com/30132017/52438734-ccda5100-2ace-11e9-8c7e-1e1954c46238.png)

2. Provide following "i" text for the switch:

“Control what data are used in the simulation - Select 0 for "RVI" to prioritize existing patients, where the team first sees all existing patients at the RVI estimated from the data, and only starts as many new patients as there are remaining open slots (based on RVI, supply, and missed appointment data).  Select 1 for "New Patient Starts" to prioritize new patients, where the team first sees all new patients at the rate estimated from the data, and only sees existing patients at the RVI possible given the remaining open slots (based on start rate, supply, and missed appointment data).”

3.  Add "Engagement Duration" slider in Experiments Section. Range minimum is 1 week to 4 years (208 wks).  Zero "0" will signal base case value. 

![image](https://user-images.githubusercontent.com/30132017/52438784-e8ddf280-2ace-11e9-8135-b3d64c27fd56.png)

4.  Provide following "i" text for the slider:

 “Manually adjust the median number of weeks that patients receive care coordination visits with the team. (wks)”

5.  Modify the Sim UI switch icon as shown below.  

![image](https://user-images.githubusercontent.com/30132017/52439018-702b6600-2acf-11e9-9137-d0224abe93c6.png)

6.  Add "Engagement Duration" chart to the Expanded Ouputs Section and to the Save drop down menu.

**Comment by dlkibbe** [comment]
@jamesmrollins minor thing, ignore if you like: Can the text for the "Additional Appointment Supply for New CC Patients” be shortened even more?, e.g. "Increasing the clinical hours allocated specifically to new patients will directly reduce the appointment hours available for existing patients."

**Comment by jamesmrollins** [comment]
**Version 1.7.4 CC Modifications is in TEST**: Please review checklist below to and indicate your "Go, No-Go" response. I have truncated the checklist to only cover things that are applicable for this sprint. **

**Design Summary:**
CC was converted to use gaming variables and can now time step. In the CC module, the "Use Team Data" switch was modified to enable the user to either use the "New Patient Start Rate" or the "Existing Patient Return Visit Interval." Under the Engagement Pattern header in the Experiments Section, a new "Engagement Duration" slider was added, with a range of 1 to 208 wks.  The default is to use the base case value shown in the Team Data Table.  The Team Data Table was also edited from "Median Engagement (wks)" to "Engagement Duration (median)(wks)."  The main SIM UI was modified to change the "Use Team Data" slider icon to "Prioritize" slider icon. 

**Simulation Run** (James and Tom)

* [ ]    1. Widgets return same values as the client version of Vensim.
* [ ]    2. Charts are complete and consistent with values from the client version of Vensim.
* [ ]    3. (If new experiments are added) New experiments function properly.
* [ ]    4. (If new functions are added) New functions operate as specified.

**Outputs** (if variables or charts are added) (James, Stacey and Savet)

* [ ]    1. The save-experiment naming function properly encodes any new variable in a manner that is functional and understandable.

**Training and Documentation** (Debbie, Jane, and Stacey)

* [ ]    1. Changes in simulation are noted in training documents, or are in process.
* [ ]    2. Changes are consistent with dialogue and instruction in current video training.
* [ ]    3. Help descriptions are up-to-date and include explanations of new functions or variables.
* [ ]    4. "i" Information is up-to-date, correct and complete.

**Comment by jamesmrollins** [comment]
@TomRust, the BC button on the Prioritize slider is returning the value from the "RVI used when Booking" variable.  Is this correct?
![image](https://user-images.githubusercontent.com/30132017/52961413-bb573b80-334f-11e9-91b5-bfc7944916dc.png)

**Comment by jamesmrollins** [comment]
This decision would apply to CC, MM and AGG modules.

Below is a suggested modification to the "Add Appointments for New Patients" slider (current MM version shown below - 1).  According to @TomRust this title is misleading, as it implies the experimenter can add appointments to the total number of appointments available in the system.  On the contrary, the experimenter is really reapportioning a fixed number of appointment slots to a different purpose.  Ergo, the suggested new title should be "Appointment Slots Reserved for New Patients" (Proposed MM version shown below - 2).

1. a. Current Slider Design

![image](https://user-images.githubusercontent.com/30132017/53103138-e2457700-34e1-11e9-8577-3e8b7d524d4f.png)

1. b. Current Slider Icon Design

![image](https://user-images.githubusercontent.com/30132017/53103188-fa1cfb00-34e1-11e9-9493-5c158ae86d5f.png)

2. a. Proposed Slider Design  
![image](https://user-images.githubusercontent.com/30132017/53102830-559ab900-34e1-11e9-812e-bff755430d02.png)

2. b. Proposed Slider Icon Design

![image](https://user-images.githubusercontent.com/30132017/53103244-191b8d00-34e2-11e9-8d9a-9011fe3a9c9c.png)


Thanks,
James

**Comment by lzim** [comment]
@jamesmrollins this "appointment slots reserved for new patients" was approved last week.

Thanks! I will be testing CC and MM this week.

**Comment by saveth** [comment]
@jamesmrollins I've finished reviewing the CC Team Data Table and updating the code for the tt report to reflect the changes discussed in this thread. If other people don't have comments, then we can close this issue. 😄

**Comment by lzim** [comment]
Thanks @saveth Several folks still are working on this issue. We aren’t ready to close it yet. 😜

**Comment by jamesmrollins** [comment]
Hi @saveth , I updated the checklist with your contributions to the release effort and checked them off accordingly.  Thank you for getting this done! ~ James

**Comment by lzim** [comment]
**All** @jamesmrollins @saveth @dlkibbe @branscombj @staceypark @dlounsbu 

I believe this MTL 1.8 issue is ready to be closed 👏 

These tasks were completed and moved to mtl.how (#1 & #3) or to OSF (#2 MTL Video table & "i" information).
1. Changes in simulation are noted in training documents, or are in process.
2. Changes are consistent with dialogue and instruction in current video training.
3. Help descriptions are up-to-date and include explanations of new functions or variables.
4. "i" Information is up-to-date, correct and complete.

Great work 🍾

**Comment by lzim** [comment]
Re-opening to address priority mode in CC

@jamesrollins @tomrust @staceypark

**Comment by jamesmrollins** [comment]
@lzim @TomRust the changes as defined in MM are in.  However, we need to update the "i" information.  That's easy enough.

**Comment by lzim** [comment]
@jamesmrollins and @TomRust 

We do need the pop-up table to be VA Primary Bright RED, but I'm seeing this still in TEST:

![image](https://user-images.githubusercontent.com/7454688/57046204-92db9f80-6c24-11e9-879f-ac149aa62020.png)

**Comment by lzim** [comment]
from MM thread @jamesmrollins and @TomRust 

**Here's my recommended "i" information from last night (above for CC and MM):**

These base case values estimated from the team's data corresponds with the learning mode selected when opening the simulation.

Selecting the Existing Patient Return-to-clinic Visit Interval (RVI) mode prioritizes the existing patients Return-to-Clinic Visit Interval (RVI) estimated from team data, and only starts new patients in remaining open slots after the existing patient RVI, appointment supply, and missed appointments are all taken into account.
Selecting the New Patient Start Rate mode prioritizes seeing all new patients at the start rate estimated from team data, and only sees existing patients in remaining open slots after the new patient start rate, appointment supply, and missed appointments are all taken into account.

**Comment by lzim** [comment]
@jamesmrollins Can this issue be closed?

I'm looking at all the issues under the 1.8 Sprint Milestone and hoping that they can be closed.
Thanks!
🏃‍♀ 

FYI: @staceypark
