### ISSUE TITLE
Need wk3 #2024_apr_epic MTL 3.7 Release: Sim UI TEST Bug - Reorder Name field & Email Field Team Setup in Sim UI TEST

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3060]
**1. "Name" field should display first and last name, not email.** 

![image](https://github.com/lzim/teampsd/assets/124643236/0c3bd29a-8d08-48a8-bf56-b8c63ee035a4)

1. Discovered January 24, 2024, morning, while testing with Jenn Li - within TEST environment.

**2. In order for Team PSD to track this issue you must assign
- [x] issues/bugs -  Select **bug_tracker** under project, on the right to initiate tracking a Bug.
- [ ] features 
- [ ] manuscript

**Comment by lijenn** [comment]
Dev team will work to address/troubleshoot this issue this week.

**Comment by tejaspesquare** [comment]
@ljmoody , @lijenn - Could you please check while configured a member in a team having First Name as email Id or actual name. 

![image](https://github.com/lzim/teampsd/assets/144898781/cfca5b4b-2820-488f-b50e-b8b731c22385)

![image](https://github.com/lzim/teampsd/assets/144898781/178abd92-5ec2-480b-8abe-f28cf72dc421)

in case actual Name:
![image](https://github.com/lzim/teampsd/assets/144898781/830e5056-d8da-4b9f-8155-e0e501e38d96)

**Comment by ljmoody** [comment]
@tejaspesquare, I am responding here, but am sending you 2 testing videos via Praxis team chat because the videos show information we do not want to share publicly. **_Please review the videos and respond here_** with any suggestions, questions, or further testing ideas and requests. Thank you.

**Comment by tejaspesquare** [comment]
@ljmoody - We have gone through videos attached on Praxis team chat; we will be working into it. Thanks!

**Comment by tejaspesquare** [comment]
@ljmoody - This is handled & moved to TEST-Slow. Kindly check from your end.

![image](https://github.com/lzim/teampsd/assets/144898781/5bd5bcc3-3856-4700-857b-4b9b7f620a77)

**Comment by ljmoody** [comment]
@tejaspesquare, this is still not functioning properly from my testing in TEST-Slow this morning. Please see videos on Praxis team chat for testing examples which indicate:

- Not all team member names are added and displayed with success. This seems to be specific people/email accounts such as James & Debbie, and also Jenn's non-VA email account.
- The newly created team is saved; however, I cannot see the newly created team in the Facility Team Setup team list.

**Comment by tejaspesquare** [comment]
@ljmoody - Now adding members should work.

From My testing on  TEST-Slow

Adding members-  
![image](https://github.com/lzim/teampsd/assets/144898781/c083f583-d164-4caf-be75-cfaa2d517cbb)

The newly created team is saved; however, I cannot see the newly created team in the Facility Team Setup team list.  -> We shall track this in #3061

**Comment by ljmoody** [comment]
Hi @tejaspesquare, Jenn and I tested adding new users to a team and that is functioning. 👍  
_However,_ we would like to change the behavior of the **auto-added individuals** so their **first and last names populate the name field** and **email is only under the email column**. See this screenshot for a sample of how the auto-added people to teams are currently showing:
![image](https://github.com/lzim/teampsd/assets/124643236/fd6a1b88-a723-49d9-b130-0391522d12c3)

**Comment by jamesmrollins** [comment]
## 3/17 Sim UI Standup

- Attempted to clarify the use of 'family-Name' and how it is sometimes entered as a full name in Epicenter. 
- The DEV team may need to parse last name fields into 'familyName' and 'givenName'

See Forio's explanation below:

![image](https://github.com/lzim/teampsd/assets/30132017/28b3a09d-f611-4991-99f6-d4211588cfa1)

**Comment by tejaspesquare** [comment]
@jamesmrollins , @ljmoody , @lijenn  - We have fixed this & available on SIM Dev environment. Once you are ok with result will promote code to TEST-Slow.
![image](https://github.com/lzim/teampsd/assets/144898781/e8900561-6564-44ae-af59-1528599617ad)

**Comment by ljmoody** [comment]
@tejaspesquare I tested in DEV today and no auto-added users are showing:
![image](https://github.com/lzim/teampsd/assets/124643236/0896c59e-d659-462a-952e-9974d2a54f21)
![image](https://github.com/lzim/teampsd/assets/124643236/a3430a3a-5d2c-4f21-8af8-bdb7e50cba50)
![image](https://github.com/lzim/teampsd/assets/124643236/e1257e30-7d02-40cd-8350-c4bafa5eb177)

**Comment by ljmoody** [comment]
Hi @tejaspesquare - is it possible to promote this to TEST-Slow? 
(And please respond to my question in italics above. I know it's a different issue, but want to be clear on the expected behavior in both DEV and TEST-Slow instances so I know for validation and testing purposes.)

**Comment by tejaspesquare** [comment]
@ljmoody - Code is promoted to TEST-Slow.
On Dev instance there are only 2 users default added while team setup performing- i. devuser7 & ii. devusershared. I missed to respond yesterday itself. I'm so sorry.

**Comment by ljmoody** [comment]
Thanks for your clarification, @tejaspesquare! It's informative.

I validated in TEST-Slow today that:
✅ name column is populating correctly with both first and last names
✅ emails are only showing in the email column
✅ BONUS: that all 6 auto-added people are being added to the teams as well! 🕺 

Screenshots of _ind, _team, and _shared world teams after initial setup:
![image](https://github.com/lzim/teampsd/assets/124643236/a9de06f0-080f-46d6-8ea1-2020d197a047)

![image](https://github.com/lzim/teampsd/assets/124643236/8632db58-763a-45cc-aad4-25fe7eab26b8)

![image](https://github.com/lzim/teampsd/assets/124643236/49a14fd6-b054-4daf-bac3-c32a5695e1c3)

Closing this issue as completed. 
fyi: @jamesmrollins @lijenn
