### ISSUE TITLE
Need for wk3 #2024_apr_epic MTL 3.7 Release Sim UI TEST Bug: Team setup world issues ind, shared, team worlds.

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3061]
**1. When setting up a team, only shared world is being added - not ind or team:** 

![image](https://github.com/lzim/teampsd/assets/124643236/6e41e0d3-978b-4eac-80b9-e7f4f596e7e2)

1. Bug discovered January 24, 2023 while testing with Jenn Li in support_workflow. **Discovered in TEST environment.**

**Comment by jamesmrollins** [comment]
@ljmoody  This is in Test-Slow?

**Comment by ljmoody** [comment]
@jamesmrollins, yes, my apologies for not including that in the card. I've updated it above.

**Comment by tejaspesquare** [comment]
@ljmoody - just FYI 
In order to debug issue, it will be required to add new teams (through code) using your login. We will remove it when not in use.

**Comment by ljmoody** [comment]
Hi @tejaspesquare - if you mean use my login info to do this, you have my permission. Do you still have that information? And if not, what is a secure way to share that with you again (not here!).

**Comment by tejaspesquare** [comment]
@ljmoody - Thank You for your permission. I see your credentials shared earlier on Praxis Teams. No need to share it again.

**Comment by ljmoody** [comment]
**3/1/24 update from Tejas:**
>  - Team setup world issues (When setting up a team, only shared world is being added - not ind or team: account Laura M )
> -  Based on discussion with David, we are yet to find alternative solution as Pseudonym key not going to match with User key.

**Comment by tejaspesquare** [comment]
@ljmoody - This is verified from our side. Could you please check now. It should work on TEST-Slow.

**Comment by ljmoody** [comment]
Hi @tejaspesquare, when I tested (test-slow, using VA login) today, no teams I created today were showing (not _ind, _team, or _shared). 

This screenshot shows the multiple teams I created:
![image](https://github.com/lzim/teampsd/assets/124643236/8cc2d596-22bd-496b-8c40-bc85ed51260d)

...but these teams are not see in my team list:
![image](https://github.com/lzim/teampsd/assets/124643236/5987fb63-77cb-4dc4-a0c7-84fe50cc6c04)

Please troubleshoot and let me know when we can test again. Thank you.

**Comment by jamesmrollins** [comment]
@tejaspesquare  please provide an update tonight when we meet.

**Comment by ljmoody** [comment]
@tejaspesquare, please confirm that Jenn and Laura are **auto-added as facilitators** when setting up a team. Please be sure our **VA emails** are used for this.

**Comment by jamesmrollins** [comment]
3/13 Demo Meeting

- Adding @lijenn and @ljmoody to the automatic addition of facilitator when teams are set up will hopefully resolve this issue.
- @tejaspesquare will update the code and we will test again tomorrow.

**Comment by tejaspesquare** [comment]
@ljmoody , @lijenn  - This got fixed & all worlds are populated _team, _ind & _shared. Kindly test again with hard refresh after login.

![image](https://github.com/lzim/teampsd/assets/144898781/b4963104-b7b3-4cfa-a7ee-b088cc9ba209)

![image](https://github.com/lzim/teampsd/assets/144898781/79135a86-da44-4148-8b2d-2a4dcbb1b4cc)

**Comment by ljmoody** [comment]
Tested in Test-Slow using 2 different accounts. 
fyi: @lijenn, @tejaspesquare 
- Verified that Jenn and Laura are being auto-added as facilitators. 
- Verified that _ind, _team, and _shared worlds are created and seen by the user who created the team. 

Screenshots of testing below:
![image](https://github.com/lzim/teampsd/assets/124643236/f19958dc-a90d-4804-bcab-8a181e8d05a8)
![image](https://github.com/lzim/teampsd/assets/124643236/c5bab516-a81f-4a1f-bbc6-def2676239bf)


Moving to Done; @jamesmrollins I recommend closing this issue.

**Comment by hnorthcraft** [comment]
bug addressed was reported, fixed, and tested once it got prioritized 3sp
updating value streams

 #adjudicate_memo
