### ISSUE TITLE
wk4 2024_jan_epic: ANDON ASAP SIM PROD - Missing 2 teams and saved experiments created on 1/23/24 and 1/24/24

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#3065]
@tejaspesquare @jamesmrollins We found an ANDON/urgent issue today 1/24/24 where we are missing two teams in SIM Prod.

Please message me for the two team names. 
Team 1 was created on 1/23/24 with saved experiments by @lzim, @dlkibbe, @dlounsbu. 
@lijenn and @ljmoody created team 2 on 1/24/24 and noticed team 1 and team 2 are both missing in Sim Prod as of 1/24/24.

@lijenn Was unable to find both the team's groups in Epicenter. 
_Is there anyway we can restore these teams?_
_Are any development work being done in Test impacting the functionality in Prod somehow?_

**Comment by tejaspesquare** [comment]
@lijenn - There is a possibility that groups have been deleted by someone accidently & hence it's not there. By any chance if any flag maintained in database can track recent activities on those particular groups. On lower instances works fine. 

Is there anyway we can restore these teams? - Answer to this, if we have any mechanism wherein deleted items are able to restore as record into database & so it can be populated in epicenter.

**Comment by lzim** [comment]
Thanks @lijenn & @tejaspesquare 

@tejaspesquare Please keep me posted on the progress determining: 
- [ ] Whether any of the work completed on Tuesday in PROD can be regained. 
- [ ] We are particularly concerned about regaining the Q/H/F/D text entered for the experiments run as this was time-consuming to produce.

Then, we'll want to ensure we understand
- [ ] How/why the work would have been deleted to prevent any loss of work in the future.

FYI: @jamesmrollins @dlkibbe @dlounsbu

**Comment by lijenn** [comment]
@lzim After discussing with the Forio team, they **are not** able to recover the experiments. 
The Forio team spend the weekend to recover the shared, ind, and team worlds.
You, @dlkibbe, and @dlounsbu should see this at https://mtl.how/sim now.

Forio confirmed that the worlds were deleted by request in Epicenter, but the code is unable to show who. 
They plan to update the Epicenter code to track who deletes groups and how to recover experiments over the next year. 

One possibility is that my cat deleted the groups by walking on my keyboard when I was away. 
I found footage of my cat walking on my keyboard a few days after reporting the ANDON. 

Still, let's review the users who have access to Epicenter and determine if we need to remove anyone. 
I will also close my laptop lid when not in use...

Talk more at 2024_8am_workflow!

FYI @jamesmrollins @ljmoody @tejaspesquare

**Comment by lzim** [comment]
Thanks for the hard work on this, everyone!
I believe we can close this.

**Comment by hnorthcraft** [comment]
#Adjudicate_memo
updated with operations and dev value streams

@lijenn can you help on a SP estimate? it looks like there was some efforts for recovery but no mention of that tracked on another card

**Comment by lijenn** [comment]
@hnorthcraft #adjudicate_memo

3 SP since this issue addresses a dependency impacting progress across users and this documentation helps us realize that deleted experiments, at the time, were non-retrievable, so these experiments were not recovered. I believe this is also related to and tracked in https://github.com/lzim/research/issues/856.
