### ISSUE TITLE
wk5 2024_jan_epic #story_b: Draw Dynamic Dashboard Tutor prompts wireframe

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3066]
Draw a Tutor prompts wireframe to instruct dev team where to place pointers on the screen. Provide explanations for the prompt text field.

Acceptance Criteria

 - [x] The tutor prompts are pointing to all relevant objects and buttons on the screen.
 - [x] The explanations are clear and concise.

**Comment by ljmoody** [comment]
Hello @tejaspesquare - please see the [DDD tutor wireframe.pdf](https://github.com/lzim/teampsd/files/13969444/DDD.tutor.wireframe.pdf) for the Dynamic Decision Dashboard tutor prompt wireframe.

- [ ] 1. Please add new dropdown + table for DDD:
![image](https://github.com/lzim/teampsd/assets/124643236/f3eb31da-7e75-472e-9cb1-ebd722e28f23)

- [ ] 2. Add prompts + messages as shown in PDF, 1-10.

FYI @jamesmrollins, @lijenn

**Comment by tejaspesquare** [comment]
@ljmoody - Just a clarification items present in #3023 & #3066 are same.

**Comment by ljmoody** [comment]
Hi @tejaspesquare - you're right! Card #3023 had tutor prompts for two different modules; yesterday Jenn and I split that card into two distinct cards to track them separately. We will be tracking the tutor wireframe progress/development on this card now.

**Comment by ljmoody** [comment]
Closing this card; wireframes are developed. Moving wireframe tracking + validation to #3029 (testing card).

**Comment by tejaspesquare** [comment]
@ljmoody - I'm unable to download file "wireframe_DDD tutor.pdf". Can you please provide permission.

**Comment by hnorthcraft** [comment]
@lijenn #adjudicate_memo looks like this card is a dev and 3029 is a test card. test card is assigned 21, but is there any SP for the dev here?

**Comment by lijenn** [comment]
@hnorthcraft 3 SP since this was a quick wireframe development and instructs Dev team on where to place the tutor prompts in the interface.
