### ISSUE TITLE
2024_feb_roadmap: Draw _MTL_ Reports generator tutor prompt wireframe

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3067]
Draw a Tutor prompts wireframe to instruct dev team where to place pointers on the screen. Provide explanations for the prompt text field.

Acceptance Criteria
- [x] The tutor prompts are pointing to all relevant objects and buttons on the screen.
- [x]  The explanations are clear and concise.

**Comment by ljmoody** [comment]
Hello, @tejaspesquare - please see the [wireframe_MTL Reports tutor.pdf](https://github.com/lzim/teampsd/files/13996001/wireframe_MTL.Reports.tutor.pdf) for the _MTL_ Reports tutor prompt wireframe.

- [ ] Add new: 
![image](https://github.com/lzim/teampsd/assets/124643236/46f528ce-b7c1-4284-95e8-04c434257656)

fyi @jamesmrollins, @lijenn

**Comment by ljmoody** [comment]
Closing this card; wireframes are developed. Moving wireframe tracking + validation to #3028 (testing card).

**Comment by hnorthcraft** [comment]
3 SP since this was a quick wireframe development and instructs Dev team on where to place the tutor prompts in the interface #adjudicate_memo
