### ISSUE TITLE
2024_feb_roadmap #story_l: Sim UI Team Setup issues

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3068]
**Team setup issues:** 

~- [ ] 1. Remove Emily M. from being automatically added to teams when they're set up.~ This is tracked in #3009 
- [x] 2. People we added (in TEST) to the team are not showing up on the team member list (it did work for us in PROD environment).

<img width="840" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDc4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3bc2e4b5b4bfffbd3ef997c71840c0fab181a79b/image.png" alt="image.png" />

**Comment by lijenn** [comment]
Removing Emily M. is already tracked in the previous issue card #3009, so I will remove that from this card. Members not showing up in the team member list is a bug that needs to be fixed so I'm moving this card back into Priority Epic.

**Comment by lzim** [comment]
@ljmoody - _Can we close this card?_
LMK
thanks!

**Comment by ljmoody** [comment]
Tested functionality of adding team members in TEST-slow environment. 
Verified all team members added do show in the _team member list.
Closing this card as complete.

**Comment by hnorthcraft** [comment]
2 SP since the issue was reported, fixed, and tested relatively quickly once it got prioritized 
adding dev value stream
#adjudicate_memo
