### ISSUE TITLE
2024_09: TEST Causal Loop Diagrams (aka Feedback Loops, CLDs)

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3069]
## AC:
- [x] Test Feedback Loops:
  - [x] CC
  - [x] MM
  - [x] Psychotherapy
  - [x] Team Flow
  - [x] Team Care
- [x] all feedback to DEV is addressed and/or incorporated
- [x] validate Tutor wireframes
- [x] validate position of Team Care and Team Flow checkbox prompt arrows
- [x] Double caret is removed from Team Care pop-up
- [x] Double caret is removed from Team Flow pop-up

### When testing with users:
- [ ] Does current font size work for them?

**Comment by ljmoody** [comment]
Hello @tejaspesquare,

>on 2/7/24, from Tejas:
>@ljmoody & @lijenn: Point 20 & 21 (Casual Loop without Scroll) - This is fixed for remaining models & it is available to test in TEST-Slow. You can continue testing on this environment too.

I tested further using test environment, VA laptop, Edge browser. The causal loop diagram windows are functioning much better  for enlarging; however, I wonder about the ability to make the CLD window larger than the browser window. Some **users might find it tricky to resize** and expose the DDD underneath again. FYI: @lijenn:
![image](https://github.com/lzim/teampsd/assets/124643236/0f0419d2-a8fd-4a66-a9be-7cbda9737038)

I do have some requested changes to make - see screenshots below, please:

## Care Coordination Story:
- [ ] 2 edits to CLD
![image](https://github.com/lzim/teampsd/assets/124643236/84a25dc1-ddf2-4b51-9098-bd09c3cf7101)

## Team Care Story:
- [ ] 1 edit in header
- [ ] 5 edits to CLD
![image](https://github.com/lzim/teampsd/assets/124643236/ff219a3b-d293-4508-8a4f-6bbcc7159b98)

## Medication Management Story:
- [ ] 1 edit in header
- [ ] 2 edits to CLD
![image](https://github.com/lzim/teampsd/assets/124643236/d852b87b-c17c-4f3a-9ef9-f7265de22be2)

## Psychotherapy Story:
- [ ] 2 edits in CLD
![image](https://github.com/lzim/teampsd/assets/124643236/f2838a1a-d295-492e-82a3-f554320652d9)

## Team Flow:
- [ ] 1 edit to header
- [ ] 5 edits to CLD
![image](https://github.com/lzim/teampsd/assets/124643236/f8af7ad4-ddfe-4188-88a6-bf83dcbdd916)

**Comment by ljmoody** [comment]
Hi @tejaspesquare - please see the [wireframe_Feedback Loops tutor.pdf](https://github.com/lzim/teampsd/files/14103221/wireframe_Feedback.Loops.tutor.pdf) for the Feedback Loop tutor prompt wireframes - 6 pages.

Please check as completed to help with tracking progress:
- [ ] Tutor Administrative Dashboard updated
  - [ ] CC Story header + prompts added
  - [ ] MM Story header + prompts added
  - [ ] PSY Story header + prompts added
  - [ ] AGG Story header + prompts added
  - [ ] SP Story header + prompts added
- [ ] Update Team Care feedback loop blue header to include "Story"
- [ ] Update MM feedback loop tutor to include tutor icon in blue header
- [ ] Update Team Flow feedback loop blue header to include "Story"

**Comment by tejaspesquare** [comment]
@ljmoody, @lijenn:  Changes (edit in header & edits in CLD) are incorporated & available in TEST-Slow.    
Pending: Team Care Story - RVI legends on bottom left of window. Will be available in next publish.

**Comment by ljmoody** [comment]
Hi @tejaspesquare, 
I verified the changes you made - thank you!

In the screenshots + requested changes post above, it's possible Jenn added her feedback after you saw the post. Please revisit the following and update with this global correction: 

#### **_should be_ "Return-to-Clinic Visit Interval", _not_ "Return-to-Clinic-Visit-Interval"**

**Care Coordination:**
- [ ] correct 1 instance

**Team Care:**
- [ ] correct 1 instance
- [ ] RVI legend, when created, should also be "Return-to-Clinic Visit Interval"

**Medication Management:**
- [ ] correct 1 instance

**Psychotherapy:**
- [ ] correct 1 instance

**Comment by tejaspesquare** [comment]
@ljmoody - Changes (CLD) done & available in TEST-Slow.

**Comment by ljmoody** [comment]
Hi @tejaspesquare, Jenn and I verified the edits you've made - thank you! Could you please:
- [ ] 1. Provide an estimate date for when the Tutor will be developed. Or, if unknown, if you know an estimate start date for work on this.
- [ ] 2. The default opening size for some CLDs is too small (Team Care, Psych, Team Flow). Our users will find it difficult to read and may be frustrated at having to resize each time they're opened. Is it possible to make the pop-up CLD windows for these open up larger so objects & text appear the same as CC and MM CLDs?
 **For example**, the difficult-to-read CLDs currently open up like this:
![image](https://github.com/lzim/teampsd/assets/124643236/6cdcc96d-8e35-4e95-8b3b-8f1fa6ffd8b7)
![image](https://github.com/lzim/teampsd/assets/124643236/9b410ebd-135e-420f-b2ab-80d96f90d6a3)
![image](https://github.com/lzim/teampsd/assets/124643236/2a7ed6cc-6b8e-44c8-8777-9af8fcbf4323)

 And we would like to know if the default opening view could be more like the scale/size of this one:
![image](https://github.com/lzim/teampsd/assets/124643236/3aa4dafc-2b36-4d1d-8aa5-06129d6a3eeb)

**Comment by ljmoody** [comment]
@tejaspesquare - I've updated the "wireframe_Feedback Loops tutor.pdf" linked in a comment above. You should also now have permissions to view the file.

**Comment by ljmoody** [comment]
**3/1/24 update from Tejas:**
>  TEST Causal Loop Diagrams (aka Feedback Loops, CLDs) :- Default Opening size for some CLDs is too small, **not started yet.**

**Comment by ljmoody** [comment]
@tejaspesquare - good question (see below). I confirmed with Jenn that the tutor prompts we've made for the system stories do _not_ need links associated with them. 

> ![image](https://github.com/lzim/teampsd/assets/124643236/0aa7b27a-20fd-472c-bc28-f5ac44bf7137)

**Comment by ljmoody** [comment]
@tejaspesquare, is it possible for the fonts to be resized permanently, find a good average size, or dynamically size them? 
The window resizing is working well; the readability will be an issue for users. 
We hope to discuss options with you at our Sunday meeting.

**Comment by tejaspesquare** [comment]
@ljmoody , @lijenn :- wireframe_Feedback Loops tutor_#3069 This is developed & available to test on TEST-Slow. Also, we are doing parallel testing from our side.

**Comment by ljmoody** [comment]
@tejaspesquare - I validated the Feedback Loop (CLD) tutor prompts today. They are all as they should be according to the wireframes. Your placement for the prompt near the checkboxes is in a better position than what I had on the wireframe. For consistency, please update Team Flow Story and Team Care Story Tutor prompt arrow location to be the same the others (showing MM Story as the example to follow below):

## Change from:
![image](https://github.com/lzim/teampsd/assets/124643236/6ce9ca26-6fca-45da-a926-8c90713ed7a6)

## To: 
![image](https://github.com/lzim/teampsd/assets/124643236/2d97ac95-5223-4816-9f70-abde9907d58e)

**Comment by ljmoody** [comment]
Looks great, @tejaspesquare! Thank you. 
FYI: Jenn and I plan on testing CLDs together this week.

**Comment by ljmoody** [comment]
Hi @tejaspesquare, Jenn and I tested causal loops today. 
They are all legible upon opening--EXCEPT Team Care Story. The screenshot below is at 100% zoom. 
Is it possible to make the window larger - horizontally - to try to accommodate larger text? 
Is there something that can be done to improve the initial opening size and ability to read?
And, if something can or could be done, what level of effort or time would be involved for this to happen?

![image](https://github.com/lzim/teampsd/assets/124643236/52bff9d1-2e18-43cc-a474-e8cfc92ac61d)

**Comment by ljmoody** [comment]
Hi @tejaspesquare, I wanted to check in with you on a few things:
- [ ] Is there anything that can be done with the Team Care Story (see comment directly above)? If so, what can be improved and what level of effort or time would be involved?

- [ ] When the Feedback Loop pop-up window is closed with the Tutor still showing/in progress, the tutor message does not disappear. Is it possible to close the opened tutor prompts when users close the window? For example, I was clicking through Team Care tutor prompts, and exited the pop-up, but this message remained over the DDD:
![image](https://github.com/lzim/teampsd/assets/124643236/ac158338-78b3-4992-b789-81d37edaf281)

- [ ] Please remove double caret found in Team Care story:
* I have a feeling this is because when first opening this window, it is scrollable in the up/down direction. Is it possible to open without that? The scrolling amount is negligible, so doesn't seem necessary.
![image](https://github.com/lzim/teampsd/assets/124643236/48ba86d3-5546-4c74-a331-27dd5a765a48)

- [ ] Same as above for Team Flow story:
![image](https://github.com/lzim/teampsd/assets/124643236/64825c3e-6f73-41e1-abf9-e780a28ce5a7)

**Comment by lijenn** [comment]
Discussed 4/7 Sim UI Standup:
- @tejaspesquare Dev is working on the issues reported above.

**Comment by ljmoody** [comment]
@tejaspesquare - #3148 includes requests for additional CLD changes; I'm adding them + clarifying info/visuals here. Please check off as they're developed.

- [ ] 3. ALL feedback loops need to open as shown below - with **no features selected** in the dropdown:
![image](https://github.com/lzim/teampsd/assets/124643236/d48524b2-d9ef-4759-a08a-034bd211e088)

- [ ] 4. Change the order of dropdown checkboxes to be:
![image](https://github.com/lzim/teampsd/assets/124643236/153c82ee-871e-474d-a5e6-d4b9007f30a9)

- [ ] 5. Font needs to be scaled in sync better and without overlap ideally (shown here at 150% which was the best view):
![image](https://github.com/lzim/teampsd/assets/124643236/1d9eddbe-a285-471f-b9bc-fd7984b01093)

- [x]  6. changes already made

- [ ] 7. Add to the legend: "Click any arrow to see the impact of change."
![image](https://github.com/lzim/teampsd/assets/124643236/1b17e8b5-afdf-4ae8-a9bb-aa2efb2338cc)

**Comment by tejaspesquare** [comment]
@ljmoody - Following points are completed & can be verified at Test-Slow instance:
3. ALL feedback loops need to open as shown below - with no features selected in the dropdown:
4. Change the order of dropdown checkboxes to be:
7. Add to the legend: "Click any arrow to see the impact of change."

**Comment by tejaspesquare** [comment]
@ljmoody:  Research is required to tackle the font scaling issue. The team is currently seeking a solution and is expected to propose some suggestions.

 5. Font needs to be scaled in sync better and without overlap ideally (shown here at 150% which was the best view)
![image](https://github.com/lzim/teampsd/assets/144898781/685befe6-a72a-4f4a-867e-1f7f50612745)


Current view on Test-Slow:
![image](https://github.com/lzim/teampsd/assets/144898781/c3979825-2f34-425e-a7ff-2d9606791630)

Thank You!

**Comment by ljmoody** [comment]
✅ Validated all the following points are incorporated into all module CLDs.

> @ljmoody - Following points are completed & can be verified at Test-Slow instance: 3. ALL feedback loops need to open as shown below - with no features selected in the dropdown: 4. Change the order of dropdown checkboxes to be: 7. Add to the legend: "Click any arrow to see the impact of change."

**Comment by ljmoody** [comment]
Moved card #3148 to done and recommend closing; migrating comments related to CLD sizing here for continued tracking.

## 4/28 Sim UI Standup

- [ ] Dynamic sizing on pop-up is set vertically at 600 DPI.  They cannot reduce any further.
- [ ] If the diagram is partially off screen, then a slider will appear to move over to the hidden part of the diagram.
- [ ] The DEV team is going to evaluate the Causal Loop Diagrams and determine if we can modify the design slightly so we can accommodate larger text during zoom AND pull the window in a vertical direction.  

## Target Screen Resolutions for Dynamic Sizing

**Desktop Screen Resolutions:**
1. 1920x1080 (22.7%)
2. 1366x768 (14.47%)
3. 1536x864 (10.41%)
4. 1440x900 (6.61%)
5. 1600x900 (3.8%)¹

**Mobile Screen Resolutions:**
1. 360x800 (11.65%)
2. 390x844 (7.26%)
3. 414x896 (5.66%)
4. 393x873 (5.16%)
5. 328x926 (3.84%)¹

**Tablet Screen Resolutions:**
1. 768x1024 (26.96%)
2. 810x1080 (9.68%)
3. 800x1180 (5.04%)
4. 962x601 (2.99%)

fyi: @tejaspesquare, @lijenn, @jamesmrollins

**Comment by tejaspesquare** [comment]
@jamesmrollins, @ljmoody - The font scaling problem has been resolved and is now available on Test-slow. Please verify and provide your feedback.

Default view
![image](https://github.com/lzim/teampsd/assets/144898781/b61386b5-1e75-419d-8656-9ee6ccb6acb3)

Float (left) & Expand it
![image](https://github.com/lzim/teampsd/assets/144898781/6d5bec0b-55d2-40f5-ba4f-6b9916bdbe0e)

When do resize, font size is reduced
![image](https://github.com/lzim/teampsd/assets/144898781/1d161dab-d596-4fc5-b21c-b7e350e53ae7)

**Comment by ljmoody** [comment]
@tejaspesquare, the scaling is much improved and I appreciate how **the diagrams open automatically with the last user-selected window size and loop dynamics choices**. Feedback I have to offer:

- [ ] Change the scaling behavior of the highlighted loop polarities in Team Care so they scale/size the same as the others. They appear noticeably smaller at any pop-up zoom level than the others, but should be consistent in size. Is this possible?:
![image](https://github.com/lzim/teampsd/assets/124643236/406fc298-9198-4893-a8f3-a6eca16e5869)

- [ ] The Community icon and "Back to top" are at times located where users need to resize the pop-up. These both seem to be floating above the pop-up window. Is it possible for their behavior to rest behind the pop-up, so users can easily resize the pop-up with the corner toggle?:
![image](https://github.com/lzim/teampsd/assets/124643236/835ff8a3-7a92-4495-b26a-657d9abddc0e)

fyi: @lijenn, @jamesmrollins

**Comment by jamesmrollins** [comment]
@ljmoody - Did the popup size automatically over the community button, or did you drag it over the community button?  The community button is always on top as a business rule.  But I want to understand the use case better. Lets discuss at 5/3 meeting.

**Comment by tejaspesquare** [comment]
@ljmoody - Loop priorities issue is fixed & now it should appear consistent at any zoom level.

![image](https://github.com/lzim/teampsd/assets/144898781/ccb02582-80e4-49f1-82fd-e6fcf86f2f37)

**Comment by tejaspesquare** [comment]
Hello @jamesmrollins , @ljmoody , @lijenn - The wireframe development for Decision Meter has been finished and is now accessible on Test-Slow for validation.

![image](https://github.com/lzim/teampsd/assets/144898781/8500b510-eba9-4eb5-9dd3-5a751e7f6274)

![image](https://github.com/lzim/teampsd/assets/144898781/d4b256e7-a988-4838-92af-5a437d766fe7)

**Comment by ljmoody** [comment]
Thanks, @tejaspesquare, for the update on Decision Meter tutor prompts. I'll track that+validation in #3029.

**Comment by ljmoody** [comment]
@tejaspesquare, I now there are higher level tasks for you to work on currently. Still, I wanted to let you know that today Jenn and I looked at PROD version of causal loops and they're misbehaving. For example:

1. Jenn's view when opening up causal loops (VA laptop, 90% zoom, Chrome browser) is cutoff at the top:
![image](https://github.com/lzim/teampsd/assets/124643236/534f6bf2-4663-4343-9e4e-830e4898cf06)

2. Laura's view when opening and resizing causal loops (VA laptop, 100% zoom, Edge browser):
**Team Care:**
![image](https://github.com/lzim/teampsd/assets/124643236/e8c8e2fe-db2b-4edc-aeb7-7a060ffc325b)
![image](https://github.com/lzim/teampsd/assets/124643236/f121d212-b8bc-487f-a9a2-fc3c4df9f08b)
![image](https://github.com/lzim/teampsd/assets/124643236/c4b5453c-792e-4988-ba9e-8b9c8bcf780d)
![image](https://github.com/lzim/teampsd/assets/124643236/ccc32c3f-ba53-49f7-938e-64313343919d)

**MM:**
![image](https://github.com/lzim/teampsd/assets/124643236/8bd35b9d-4894-4b2f-bd10-33a9dd36b87c)
![image](https://github.com/lzim/teampsd/assets/124643236/865f296c-2903-4c25-b781-e87d8c875909)
![image](https://github.com/lzim/teampsd/assets/124643236/42a11753-f461-4d44-b4e8-ba048a09f0cd)
![image](https://github.com/lzim/teampsd/assets/124643236/6259dbc8-63b8-45f6-8716-a578af7da81f)

fyi: @lijenn, @jamesmrollins, @lzim

**Comment by tejaspesquare** [comment]
Hello @ljmoody - Please find my response below:

1. We will try to attend to Point #1 as soon as possible. In the meantime, if it has not been done already, could you please ask Jennifer to clear the cache and perform a hard refresh to see if that resolves the issue?
2.  Text re-size on popup: Behavior is like when the popup is initially opened, it requires a click within its area for the font size to adjust.  (Note: We put our efforts to fix this issue however not succeeded. Nevertheless, we would like to address this matter later point of time considering other high priority items) 
Subsequently, the font will automatically adjust according to any changes in screen size. Font resizing is not related to floating the screen.

Thank You!

**Comment by lijenn** [comment]
Thanks @tejaspesquare, clearing the cache and doing a hard refresh resolved my issue for the Team Care pop-up.

The behavior for the font size is a bit awkward, but I agree that it's a low priority (we can come back to this later) and focus on the API and CI/CD bugs for now.

**Comment by tejaspesquare** [comment]
Hello @ljmoody, @lijenn,
Casual Loop Diagrams - Text re-size on popup: This behavior is modified & now text scaling will happen only when user change popup size. It is moved to Test-slow for verification. 

FYI - @jamesmrollins

**Comment by ljmoody** [comment]
Hello @tejaspesquare,
I appreciate the resize cursor now available on each of the CLDs - makes resizing **much easier for users** when pop-up is large and when the community/top of page buttons are hovering over the resize triangle. 🚀 
![image](https://github.com/lzim/teampsd/assets/124643236/3750d432-5dbb-4fd6-80ad-27330a714fd3)

---

Tested CLDs for each module today in Test-slow, on VA laptop, Edge browser, zoom at 100%.
✅ Verified the font sizing behavior is now working as desired. 

## Care Coordination:
### when first opened:
![image](https://github.com/lzim/teampsd/assets/124643236/f00a932d-41a9-4d7c-8f63-4346706dfc32)

### when resized larger:
![image](https://github.com/lzim/teampsd/assets/124643236/3e0005de-65be-4410-b785-205567725201)

### when resized smaller: 
![image](https://github.com/lzim/teampsd/assets/124643236/0b09c70a-1529-4b83-9378-bfba72890f60)

## Team Care:
### when first opened:
![image](https://github.com/lzim/teampsd/assets/124643236/0d5a63f8-441c-4ffe-ad72-886e176a8814)

### when resized larger:
![image](https://github.com/lzim/teampsd/assets/124643236/d7af314e-3ef7-4364-97d9-fb9f9333fa64)

### when resized smaller: 
![image](https://github.com/lzim/teampsd/assets/124643236/7f1391f1-04e4-40e0-8812-64b16a4ed5c3)

## Medication Management:
### when first opened:
![image](https://github.com/lzim/teampsd/assets/124643236/cb315ced-e785-4ee7-9561-81b465027893)

### when resized larger:
![image](https://github.com/lzim/teampsd/assets/124643236/57d92665-e65c-40ff-9a2f-f2345320e7ea)

### when resized smaller: 
![image](https://github.com/lzim/teampsd/assets/124643236/b7366a07-4a7a-4b5a-9077-7b1bc51660e3)

## Psychotherapy:
### when first opened:
![image](https://github.com/lzim/teampsd/assets/124643236/4ffbc807-439a-4231-b3e1-c650af50c451)

### when resized larger:
![image](https://github.com/lzim/teampsd/assets/124643236/92af2433-c029-4ed4-bc3e-460167aadd9e)

### when resized smaller: 
![image](https://github.com/lzim/teampsd/assets/124643236/81f264e6-6fa9-48bc-aea2-37902104de0d)

## Team Flow:
### when first opened:
![image](https://github.com/lzim/teampsd/assets/124643236/7d540600-a4a6-4bba-b0e4-8a0e2e2a4fc0)

### when resized larger:
![image](https://github.com/lzim/teampsd/assets/124643236/98114657-8bd5-4941-8835-f92b67254d37)

### when resized smaller: 
![image](https://github.com/lzim/teampsd/assets/124643236/54a64f26-c4fa-4605-addc-d467b7fd03af)

fyi @jamesmrollins @lijenn

**Comment by ljmoody** [comment]
- Feedback loops are live in PROD for each module.
- Requested via #3207 possible refinement to pop-up, making it scalable and movable
- Feedback from DEV designer:
  > this is not currently possible due to the scaling font size (which would shrink too small if the graphic is allowed to be scaled further down
- Assigned points based on level of effort from Feb-June.
- Moving to done; suggest closing this card.

**Comment by lzim** [comment]
Thanks @ljmoody Closing the card
