### ISSUE TITLE
MTL Live Calendar Example

### ISSUE THREAD

**Issue by dlkibbe** [lzim/teampsd#307]
@lzim @staceypark Calendar Example for review
![calendar example](https://user-images.githubusercontent.com/31182258/52149983-8901ca80-263c-11e9-9728-150e1a59beba.png)

**Comment by lzim** [comment]
> @lzim @staceypark Calendar Example for review
> ![calendar example](https://user-images.githubusercontent.com/31182258/52149983-8901ca80-263c-11e9-9728-150e1a59beba.png)

Thanks @dlkibbe this was really helpful today! I'm going to upload to Lucid.
