### ISSUE TITLE
2024_feb_roadmap #story_l: Draw Causal Loop Diagrams (aka Feedback Loops, CLDs) tutor prompt wireframe

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3075]
Draw a Tutor prompts wireframe to instruct dev team where to place pointers on the screen. Provide explanations for the prompt text field.

Acceptance Criteria
- [x] The tutor prompts are pointing to all relevant objects and buttons on the screen.
- [x] The explanations are clear and concise.

**Comment by ljmoody** [comment]
Hi @tejaspesquare - please see the [wireframe_Feedback Loops tutor.pdf](https://github.com/lzim/teampsd/files/14103221/wireframe_Feedback.Loops.tutor.pdf) for the Feedback Loop tutor prompt wireframes - 6 pages.

Please check off as completed to help with tracking:
- [ ] Tutor Administrative Dashboard updated
  - [ ] CC Story header + prompts added
  - [ ] MM Story header + prompts added
  - [ ] PSY Story header + prompts added
  - [ ] AGG Story header + prompts added
  - [ ] SP Story header + prompts added
- [ ] Update Team Care feedback loop blue header to include "Story"
- [ ] Update MM feedback loop tutor to include tutor icon in blue header
- [ ] Update Team Flow feedback loop blue header to include "Story"

FYI: @jamesmrollins @lijenn

**Comment by ljmoody** [comment]
Closing this card; CLD wireframes are developed. Moving wireframe tracking + validation to #3069 (testing card).

**Comment by hnorthcraft** [comment]
3 SP since this was a quick wireframe development and instructs Dev team on where to place the tutor prompts in the interface #adjudicate_memo
