### ISSUE TITLE
Need for MTL 3.7 Release wk3 2024_apr_epic Bug in SIM UI TEST: User not showing up in shared world in Sim UI

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3080]
**Description:** 
@lijenn and @ljmoody are testing whether or not we can remove users from the facilitator_login and just let them use the administrator_login. Bug is that @ljmoody doesn't show up in shared world in sim_test. [**Please watch this video**](https://takouba-my.sharepoint.com/:v:/g/personal/lmoody_praxisanalytix_com/EQQF3abqT81Fq5To1fcxAa4BrDkYfxTRQd7Np_c0z2wCqQ?e=ubYi0q&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D) to see the bug - we were able to recreate it. We also have a question about the devusershared user we saw, too (at 3:48 in video).

![image](https://github.com/lzim/teampsd/assets/124643236/c99b37bb-f6da-4da6-9eb1-f44344b6da05)

1. When was the bug discovered? **2/7/2024, ~3:30p MST**. 
2. Is this an individual or shared world? n/a
3. What is the name of the experiment? n/a

**2. In order for Team PSD to track this issue you must assign**
- [x] issues/bugs -  Select **bug_tracker** under project, on the right to initiate tracking a Bug.
- [ ] features 
- [ ] manuscript 

**3. Support Workflow:**  
i. **Pipelines** - prioritize in priority pipeline  
ii. **Assignee** - assign to a workflow user  
iii. **Label**- label value stream and workflow 
iv. **Milestones & Epics** - select monthly sprint milestone (GitHub) & epic (ZenHub) within the workgroup   
v. **Estimate** - estimate task in complexity points   
vi. **Epics** - assign to team-wide epic and TeamPSD master plan project  

**3. If you anticipate that your **issue card** or **bug card** will have **dependencies** these can be added once the issue has been submitted.   
viii=. **Add dependencies** - assess for and add dependencies *blocking* & *blocked by* this issue

**Comment by lijenn** [comment]
Discussed at Sim UI Standup Call 03/11/24

The V2 pseudonym key is not matching to the V3 user key. Dev Team will see if there is a way to compare both keys. If that does not work, Dev will need to develop a new solution.

**Comment by tejaspesquare** [comment]
@ljmoody - Can you get me rights to watch attached video in the description.

**Comment by ljmoody** [comment]
Yes, my apologies @tejaspesquare about the video being inaccessible. I will share via Praxis teams (and make it obvious the video goes with this issue) because there is confidential information in the video.

**Comment by tejaspesquare** [comment]
@ljmoody - As per our detailed analysis, system is populating default users in a _shared team & Laura Moody is not in that list either of. For this reason, she is not able to see _shared team under Team setup.

![image](https://github.com/lzim/teampsd/assets/144898781/8121c84b-861e-4c1f-9766-14e70ee852ad)

![image](https://github.com/lzim/teampsd/assets/144898781/b23d5465-b51f-4a87-9e9a-18747ad20032)


Kindly suggest if this needs to be updated with Laura Moody email ID. If yes, then praxisanalytix or VA account?.

FYI - @jamesmrollins & @lijenn

**Comment by ljmoody** [comment]
@tejaspesquare,

- Jenn and Laura need to be auto-added to project - va-psd-test and va-psd-sim 
- Please use our VA emails.

We think this might solve this issue. :)

**Comment by jamesmrollins** [comment]
3/13 Demo Call
- This should be solved by adding @lijenn and @ljmoody as auto-added admins.
- Will test tomorrow.

**Comment by tejaspesquare** [comment]
@jamesmrollins , @ljmoody - This should work now.
![image](https://github.com/lzim/teampsd/assets/144898781/c21083ea-dec1-4287-a974-920b6946379d)

**Comment by ljmoody** [comment]
@tejaspesquare, I tested this today.

1. I created the team "3080_testing" using my VA login, as administrator. 
![image](https://github.com/lzim/teampsd/assets/124643236/b769c681-3959-40f2-893a-dabcb812ffbf)

2. I added myself to this team - using email: praxis, role: facilitator.
![image](https://github.com/lzim/teampsd/assets/124643236/c80bbf32-1b0e-43ef-bf77-4aeb74d892f0)

3. The praxis facilitator "me" shows up in _ind and _team, but not _shared:
![image](https://github.com/lzim/teampsd/assets/124643236/4e7416a8-3d6f-4f26-a705-f054594fc7a4)

4. I logged off and logged into Test-slow using praxis credentials, as facilitator. I do not see the _shared world here, either, but I should since I am on the team as a facilitator.
![image](https://github.com/lzim/teampsd/assets/124643236/20e58f17-a288-49de-8554-f8eee3c4a1d5)

Please let @lijenn and I know when we can test again. 
fyi @jamesmrollins

**Comment by jamesmrollins** [comment]
## 3/17 Sim Ui Standup

- [ ] Any individual user set up from the Team Setup, Add Team-Member pop-up, will be automatically added to their own _ind world and to the _team team.
- [ ] If an individual is to go into the _shared group, then they would be added by Admin Inputs to the Add Team-member pop up.
- [ ] @ljmoody indicated that a test a few days ago revealed the Admin login did not result in access to the _shared group.

**Comment by lijenn** [comment]
Hi @tejaspesquare, I tried to test this today Wed 3/20 in DEV instance but I do not have access to the Administrator Dashboard after singing in with the administrator_login.

I sign into DEV with administrator_login:
![image](https://github.com/lzim/teampsd/assets/59668647/f22eec87-c04f-46c9-9324-04befd2afdca)

I am automatically signed into the Dynamic Dashboard and do not see or have access to the Administrator Dashboard:
![image](https://github.com/lzim/teampsd/assets/59668647/b721e328-24a3-49a9-adab-8eaad534067b)

This is preventing me from creating a new team to test this bug.

**Comment by jamesmrollins** [comment]
3/20 Stand Up

- @tejaspesquare asked for a F5 reset to see if this was fixed.
- @lijenn attempted to sign in as administrator in DEV instance, but the problem persists.
- @tejaspesquare will attempt to recreate the error with @lijenn login details and fix tonight.

**Comment by tejaspesquare** [comment]
@jamesmrollins , @lijenn - We are still working on it.

**Comment by tejaspesquare** [comment]
@lijenn - Issue got fixed. It was permission issue at group level. You had non-facilitator role as per configuration in Epicenter.
![image](https://github.com/lzim/teampsd/assets/144898781/6db8dc09-aefc-4a67-b544-99d5a36bb228)



![image](https://github.com/lzim/teampsd/assets/144898781/730fd7f7-f358-44b1-918b-139e72bec3d1)

**Comment by jamesmrollins** [comment]
3/25 Stand up

- @lijenn will test this week.

**Comment by lijenn** [comment]
Hi @tejaspesquare I still do not see the _shared world team for teams that I set up in Test.
However, Laura is able to see all 3 worlds that I set up. And when Laura sets up a team, I am able to see all 3 worlds.
This issue seems specific to the teams I set up in Administrator dashboard.

Here is the team I set up, I do not see the _shared world:
![image](https://github.com/lzim/teampsd/assets/59668647/d80355ee-1d56-44a9-8c67-a5805d1d3910)

Both Laura and I are also unable to see all 3 worlds in the team dropdown here:
![image](https://github.com/lzim/teampsd/assets/59668647/491cf383-3ccf-4144-af66-d0cf65d2798d)

**Comment by tejaspesquare** [comment]
@lijenn - This is working fine & available to test on Test Slow.
I have logged in with your credentials.

Team Setup
![image](https://github.com/lzim/teampsd/assets/144898781/42654677-787a-47fb-942c-3297481bbc04)

Shared team
![image](https://github.com/lzim/teampsd/assets/144898781/f6ba3162-92b9-4ff4-a14a-10d72969b12b)

Dashboard
![image](https://github.com/lzim/teampsd/assets/144898781/735872ec-9f7d-4601-b4f4-ff0056b33960)

**Comment by lijenn** [comment]
@tejaspesquare Thanks! This worked for me in Sim Test. Closing this card.
