### ISSUE TITLE
2024_07 #story_b: DEV Psy Flow

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#3086]
All DEV Cards for Flow:
https://github.com/lzim/teampsd/issues/3049 - CC and MM Flow
https://github.com/lzim/teampsd/issues/3086 - Psy
https://github.com/lzim/teampsd/issues/3085 - Team Care and Team Flow

**Comment by jamesmrollins** [comment]
@lzim @ljmoody @lijenn 

## Sim UI 7/3

- [ ] @ljmoody will test by COB 7/8.

**Comment by ljmoody** [comment]
Began PSY Flow Diagram testing 7/5. Tracking the testing and feedback with Dev via #3072. 
Closing this card.
