### ISSUE TITLE
wk2 2024_mar_epic: TEST mtl.how/menu

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3087]
## AC:
- [ ] mtl.how/menu functions properly
- [ ] report output is as expected
  - [ ] **1** - Is the "team time" logo still to be used with 3.7 release?
  - [ ] **2** - mtl Blue / mtl Red logo should go here
![image](https://github.com/lzim/teampsd/assets/124643236/1a741650-554a-417a-90c2-3e00b3232be9)
- [ ] demo function works - 2/2024: _Laura tried to run the demo report and when she pressed "View Results" and it never loaded:_
![image](https://github.com/lzim/teampsd/assets/124643236/fefbd18e-35f6-4555-8d4f-c2f37123d7b1)

**Comment by lijenn** [comment]
Discussed Team Praxis Meeting 3/22/24.
Resolved and tested in #3058.
