### ISSUE TITLE
Preserve current Modeling to Learn 3.0 External Implementation Facilitation Manual

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3089]
## AC:
- [x] create/preserve manual: **_Modeling to Learn_ Facilitation Manual** (a preservation of the current manual as-is)
- [x] map to shortlink Lzim is creating: mtl.how/facilitation_manual
- [x] do not revise current manual to change to a consult manual (that will be its own separate manual.

**Comment by lzim** [comment]
Update: 

#ilead_workflow includes links to the _MTL 2.0_ videos associated with the External Implementation Faciltiation 12 session plan. These links need to be updated as part of the archiving.

**Comment by lzim** [comment]
**wk4 2024_mar_epic**
@lzim adding to this card observations about dependencies in documentation that need to be tracked carefully by: 
#support_workflow
#systems_sme_workflow
#sim_ui_workflow

- [ ] This figure needs to be updated.
- [ ] Decisions need to be made about mtl.how/red & mtl.how/blue guides for _MTL 3.0_ when we archive the _MTL 3.0 External Implementation Facilitation repo, README.md, SEE & SAY Guides, etc.
- [ ] 
<img width="888" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0ljQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6cc8c2f7ce3d7b56992380f01cdf1e75e21d225d/image.png" alt="image.png" />

**Comment by lijenn** [comment]
Discussed wk1 2024_07 sim_ui_workflow:
@ljmoody @jamesmrollins @lijenn confirmed that the roadmap above goes to the preserved MTL 3.0 Facilitation Manual.
