### ISSUE TITLE
wk1 2024_mar_epic SIM UI PROD Facilitator Dashboard Bug: Select Experiment dropdown does not show saved experiment(s)

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3090]
1. **Saved experiments are not showing in the Facilitator Dashboard.** When a user selects a team from the Select Team dropdown and then navigates to the "Select Experiment" dropdown, no saved experiments are shown.
2. Discovered 2/14/2024 in sim_ui_workflow, approx 3pm MST.
3. Found in PROD environment.

![image](https://github.com/lzim/teampsd/assets/124643236/f79840a5-e10a-48d7-93ef-0d904f648dc0)

**Comment by lzim** [comment]
@jamesmrollins 
@ljmoody 
@tejaspesquare 

**wk4 #2024_feb_epic**
-  We are are still seeing this Bug on 02/27 in #systems_sme_workflow prep.
FYI:
@dlkibbe 
@dlounsbu

**Comment by hnorthcraft** [comment]
#adjudicate_memo adding dup label
