### ISSUE TITLE
2024_08 #story_b: MTL 3.7 Consult Manual QA/QC content checks

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3093]
**FYI: Manual _CONTENT_ is being tracked in #3168**

### Leanest guide/manual updates we could do:
- [x] Find & replace _MTL 3.7_ "facilitator" to "consultant"
- [x] Remove any reference in 3.7 to "12 session plan"
- [x] Keep Red/Blue (continues until the NIH & VA trials wrap in 2024)

### Updates, changes, & checks:
- [x] Link to CPT Cheatsheet --> and check that MM and Psych Epi of Care "i" icons link to this correctly
- [ ] Update all Tutor manual links to 1) open a new browser window to 2) corresponding location of content in _MTL_ Manual (via Tutor Administrative Dashboard)
- [ ] ~Check for linked graphics that begin with "!" and replace with graphics (may need to recreate or move to gh-pages->images folder)~
- [x] Change "Facilitator Dashboard" heading to "Administrator Dashboard" (Decision made 2/28/24 in sim_ui_workflow)
- [x] 1st page of manual: "_Modeling to Learn_ 3.7 Consult Manual"
- [x] Direct link to manual will be: https://mtl.how/manual
- [ ] Remove the old 12 session plan and reflect the current process:
#systems_sme
  - [ ] Prep consult.
  - [ ] Schedule consult with site and #ilead_workflow for CME/CEUs

### Find & Replace:
- [x] facilitator->consultant
- [x] facilitate->consult
- [x] administrator->user
- [x] MTL->_MTL_
- [x] team time->site study
- [x] team time (tt) report, tt3, tt 3->_MTL_ Report
- [x] Facilitator Dashboard->Administrator Dashboard

**Comment by ljmoody** [comment]
@tejaspesquare - please change the name of this dashboard as shown in the screenshot:
![image](https://github.com/lzim/teampsd/assets/124643236/ff90a7fc-5922-4de4-8c2b-824c8452667e)

fyi: @lijenn, @lzim

**Comment by lzim** [comment]
**wk4 2024_mar_epic**

**The outline for the _MTL 3.7 Consult Manual_ needs to be finalized in wk1 2024_apr_epic**
@lzim is working on this to discuss at the **#support_workflow** 3rd hour of #consult_workflow prep 
Tues 04/02 at 10AM Pacific 

<img width="1653" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTRjQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dec9e9ca7522c455bb3106c606a1c7525d0d4e5e/image.png" alt="image.png" />

**Comment by ljmoody** [comment]
Hi @lzim, _how is the order of information for the consult manual coming along? Do you need any help Jenn or I can provide?_ I plan on joining the last hour of wk3 May #systems_sme_workflow tomorrow, so it's possible we can touch on this there. 

fyi @lijenn

**Comment by lzim** [comment]
**wk3 2024_06**
@ljmoody 
@lzim
@lijenn 

### Assets Required/Developed
- [ ] **Thumbnails** > Team PSD repo > resources > mtl_consult_thumbnails
- [ ] **_MTL_ Use Case Videos: _Why & How of Modeling to Learn_ Consults** in #ilead_workflow
- [ ] **Bookdown _MTL 3.7 Consult_

## Chapter 1 _Why_ use _Modeling to Learn_
## Chapter 2 _How_ to use _Modeling to Learn_
## Chapter 3 Technical Documentation 
- [ ] 03.01 _MTL 3.7 Red_ - This is for internal Veterans Health Administration staff.
- [ ] 03.02 _MTL 3.7 Blue_ - This is for internal Veterans Health Administration consults.
- [ ] 03.03 _MTL 3.7 Demo_ - This is for the public.

### Functional Requirements - Public-facing manual (not a lot of internal links on GitHub; link to within VA via Teams)
- [ ] 1. Create a README.md that links to the videos using the Thumbnails and links to the _MTL 3.7 Consult Manual_
- [ ] 2. Create the Markdown text of the Chap 1 & Chap 2 content from the associated videos 
- [ ] 3. Copied text #[Approved #ilead_workflows ](https://dvagov.sharepoint.com/:f:/r/sites/teampsd_vha/Shared%20Documents/ilead_workflow/ILEAD%20Approved%20Videos?csf=1&web=1&e=rK0O5Y)

## 1. Why place a _Modeling to Learn 3.7_ Consult? (10 chapters/videos)
- [ ] **01. How might _Modeling to Learn_ help?**
- [ ] **04. How can a _Modeling to Learn_ consult help?**
- [ ] **02. What gets in the way of meeting patients' needs?**
- [ ] **21. If we keep making the same care decisions, will things get better or worse?**
- [ ] **05. Why is _Modeling to Learn_ useful when we have critical staffing and hiring needs?** 
- [ ] **13. Why is the _MTL Red_ Data User Interface useful?**
- [ ] **15. Why is the _MTL Blue_ Simulation User Interface useful?**
- [ ] **16. Why is applied systems thinking more likely to help us avoid costly mistakes?**
- [ ] **17. Why is _Modeling to Learn_ able to provide new insights?**
- [ ] **18. Why does _Modeling to Learn_ emphasize flows through care over time?**

## 2. How can _Modeling to Learn_ help?
- [ ] **03. How can we get more patients better without more hours in the day?**
- [ ] **06. How does _Modeling to Learn_ benefit Substance Use Disorder or SUD programs?**
- [ ] **07. How does _Modeling to Learn_ benefit PTSD Clinical Teams or PCTs?**
- [ ] **08. How does _Modeling to Learn_ benefit Behavioral Health Integration Program or BHIP teams?**
- [ ] **09. How does _Modeling to Learn_ support stepped care?**
- [ ] **10. How does measurement based care detect patient improvement or risk?*
- [ ] **12. How can we improve SAIL with _Modeling to Learn_?**
- [ ] **14. How do five key variables drive care quality?**
- [ ] **19. How does _Modeling to Learn_ help improve medication management?**
- [ ] **20. How does _Modeling to Learn_ help improve psychotherapy?**
- [ ] **22. How does our appointment backlog extend the weeks between visits?**
- [ ] **23. How can we better balance needs of new and existing patients?**
- [ ] **24. How can we leverage the feedback, rates, and volume of our local care system?**
- [ ] **11. What key drivers of higher care quality improve recovery and prevent suicide?**

**Comment by lijenn** [comment]
Discussed 7/19 Team Praxis Call:
- [ ] @jamesmrollins dispositioned this to wk5 when @ljmoody is back.
- [ ] @ljmoody to assign estimates.

**Comment by ljmoody** [comment]
8/1/2024 update:
- [ ] plan to do leanest updates as mentioned in this card - COB tomorrow
- [ ] will perform find-&-replace on each chapter of new manual - estimate by COB tomorrow
- [ ] will work with @matthewtomo re: merge conflicts, consolidating updated information, & review before publishing
- [ ] further tasks that will need cards created to track/do later and when able include:
  - [ ] Update all Tutor manual links to 1) open a new browser window to 2) corresponding location of content in MTL Manual (via Tutor Administrative Dashboard)
  - [ ] Check for linked graphics that begin with "!" and replace with graphics (may need to recreate or move to gh-pages->images folder); #3231 is for fixing broken image links in Team PSD and MTL Manuals 

fyi: @jamesmrollins @lijenn @matthewtomo

**Comment by ljmoody** [comment]
Breaking remaining tasks in this card down into manageable chunks and closing this card with points revised reflect work effort.
- Created #3245 to track tutor links to manual (open in new window at corresponding location of content within manual)
- Tracking possible development of systems_sme current process in #3243
