### ISSUE TITLE
2024_06: Tom remove x-waiver in the Vensim DSS Model for MM module

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#3095]
@TomRust Remove x-waiver in the Vensim DSS Model for MM module

**Comment by lzim** [comment]
@TomRust I'll put this in #2024_apr_epic pending our work to establish you with PAVIR.

**Comment by jamesmrollins** [comment]
FYI @lzim 

- @TomRust completed changes to the model 4/12
- I will analyze variable mapping and update with Sim UI.
- I will test the model runs in both Vensim and the Epicenter API.
- I will make markups of the MM Model diagram to reflect removal of X-waiver related dynamics.
- I will review other support pages, such as _MTL_ More Information to ensure up-to-date screen shots.

**Comment by lzim** [comment]
@jamesmrollins 
@TomRust 

_Does this card cover the update of https://mtl.how/demo and GitHub to reflect our current MM Model with X-waiver removed?_
- [ ] @lzim needs the updated MM model details version and release date from the v22 model posted here: https://forio.com/app/va/va-psd-demo/mmsdmdoc.html for Progress Reports
LMK.

Thanks!

**Comment by lzim** [comment]
wk1 2024_06 - Discussed with @jamesmrollins last week.
Meeting with CDIAS team and NCQA team tomorrow. 

_What is the ETA on the two tasks above @tomrust_
Thanks! :rocket:
