### ISSUE TITLE
2024_apr_epic: James Remove the X-Waiver from the MM Module of MTL

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#3096]
Cross-Ref: 
https://app.zenhub.com/workspaces/team-psd-workspace-5e4ac9bd8d388dfba6d9aef5/issues/gh/lzim/teampsd/3095

**Comment by lzim** [comment]
**Discussed at wk4 2024_feb_epic sim_ui_workflow**
@lzim 
@lijenn 
@ljmoody 

Blocked by #3095 

### Requirements for removing X-Waiver from MM Module once Tom has updated Vensim DSS Model
- [ ] 1. Remove X-wavier from Main Model Diagram only 1 type of Appointment Supply
<img width="1225" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE9iQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--af52b7d0a4a97f9b16be2f6e9cddfad03a8b04db/image.png" alt="image.png" />

- [ ] 2. Remove from Experiments Section Team Data Table & Experiment Slider
<img width="832" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGViQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a83605197aa32104d5e25fa504bf6dfeaab86701/image.png" alt="image.png" />

<img width="1162" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGliQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1d56d4c80155d1b7957d76db98562cf4d1cd24da/image.png" alt="image.png" />

- [ ] 3. Remove all instances from Results Dashboard here is only one example:

<img width="1723" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNG1iQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b50488f817fd990b93d943d5c6a2366c2964d122/image.png" alt="image.png" />

**Comment by jamesmrollins** [comment]
This card replaced by #3150
