### ISSUE TITLE
2024_wk2_mar_epic Bug: Sim UI PROD Experiments and Facilitator Dashboard - Team Experiments do not show up in Experiments Blue Bar & Facilitator Dashboard

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3102]
**Team Experiments do not show up in Experiments Blue Bar & Facilitator Dashboard** 
1. Discovered 3/5/24.
2. In a _shared world.

In PROD instance, this is a _shared world. We see 3 shared experiments and 3 team experiments under the Select Experiment dropdown in the Experiments blue bar: 
![image](https://github.com/lzim/teampsd/assets/124643236/1cf3b64a-5ba3-4c82-851b-ae2c1f255fd5)

When we went to the associated _team world, the 3 team experiments we saw in the _shared world do not appear in neither the Select Experiment dropdown nor the Facilitator Dashboard:
![image](https://github.com/lzim/teampsd/assets/124643236/bcc5cbb1-5374-4541-8aec-973ba4a938d9)
![image](https://github.com/lzim/teampsd/assets/124643236/d2c52963-8dfd-40e7-915e-991480ee630a)

## Acceptance Criteria: 
- [ ] Saved team and shared experiments should show in Dynamic Dashboard's Experiment blue bar dropdown. 
- [ ] Please make them appear as they do on the Play page: list experiments in the current world first, then team/shared experiments listed under "Team Experiments" or "Shared Experiments".
- [ ] If users are logged into an _ind world, their individual experiments will not show.

**Comment by tejaspesquare** [comment]
@ljmoody - I have requested James for permission if we are allowed to perform end-to-end testing using sample model file.

**Comment by tejaspesquare** [comment]
@ljmoody - I tested in prod (Team -> laura_jenn_test_admin_login_shared) I could see newly added experiment populated under Select Experiment drop-down along with Team experiemnts

![image](https://github.com/lzim/teampsd/assets/144898781/3a030117-d8bc-4b29-ae3f-f4f138c642b1)

FYI - @jamesmrollins & @lijenn

**Comment by ljmoody** [comment]
@tejaspesquare, when Jenn and I tested today in PROD, experiments are not showing correctly.
For example, in the screenshot below, just 1 experiment is showing:
![image](https://github.com/lzim/teampsd/assets/124643236/5641b95f-de57-41da-a55d-e244ef123905)

... but these 3 experiments in _shared should show:
![image](https://github.com/lzim/teampsd/assets/124643236/5451870f-38ec-427d-94de-251d64bc09a1)

**Comment by tejaspesquare** [comment]
@ljmoody - Sure, we will revisit using my login by adding few more experiments.

**Comment by jamesmrollins** [comment]
## 3/17 Sim UI Standup

-[ ]  I the user navigates to the home page (dynamic dashboard), they will see a listing of all _team and _shared team's experiments.
-[ ] 's_*' Prefix for all shared experiment names.

![image](https://github.com/lzim/teampsd/assets/30132017/2a0720ce-b462-4788-a803-1b89bcb9871c)

**Comment by ljmoody** [comment]
@tejaspesquare FYI acceptance criteria as discussed on our call this evening: 
- [ ] Saved team and shared experiments should show in Dynamic Dashboard's Experiment blue bar dropdown. 
- [ ] Please make them appear as they do on the Play page: list experiments in the current world first, then team/shared experiments listed under "Team Experiments" or "Shared Experiments".
- [ ] If users are logged into an _ind world, their individual experiments will not show.

**Comment by tejaspesquare** [comment]
@jamesmrollins , @ljmoody :- We have applied latest changes. If this looks ok then we can promote to TEST-Slow.

1.Dashboard  screen -
![image](https://github.com/lzim/teampsd/assets/144898781/18720ba0-9b4e-46ab-bf22-e878594397fe)

2. Dynamic Decision Dashboard - 
![image](https://github.com/lzim/teampsd/assets/144898781/79312206-19a3-4c5d-a5b7-9b72bf2903bd)

3. Runner Screen - 
![image](https://github.com/lzim/teampsd/assets/144898781/9a5e85e6-f336-453f-ad38-8017cdc4e982)

Note: Currently, we have created shared world experiment with appending "S_*" at the time of creation & it is used across the same. If this requirement meant for only on DDD page & that too only display purpose then we will revert changes & process on only for DDD page.

**Comment by jamesmrollins** [comment]
3/21

- @ljmoody will test by 3/22

**Comment by ljmoody** [comment]
3/21/24: 
- Jenn and Laura tested in PROD the experiment dropdown lists in the Experiment blue header and validated it is working correctly.
- We also verified that the "S_" prefix is applied to _shared world experiments in TEST-Slow.
