### ISSUE TITLE
2024_wk2_mar: BUG: Sim_UI PROD Facilitator registration request results in a 401 error

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#3104]
## Findings

- When user clicks the "Facilitator Registration" link on the login dialogue, and follows registration process an approval notification is sent to the mtl.help inbox. 
- When the approver opens email and clicks the "Approve" link the user is redirected to a webpage 
- When the webpage attempts to load, the API returns an \"AUTHORIZATION_FAILURE\" .  See image below for details and Console error log.

![image](https://github.com/lzim/teampsd/assets/124643236/968f818c-8921-4a7e-b339-3cd1cd0b1c20)

- We need an error message similar to incorrect username or password, when a user attempts to login to an instance where they have not been setup. Something to the effect "You have not been setup in this application."

![image](https://github.com/lzim/teampsd/assets/30132017/268f337d-f492-47aa-bb63-e11ed6f72151)

**Comment by lzim** [comment]
@jamesmrollins - Let's discuss at wk2 #sim_ui_workflow

**Comment by jamesmrollins** [comment]
@tejaspesquare we have decided to remove the Facilitator Login feature from the login (see below).  We don't need this function in PROD any longer. Please route change through Break Fix.

![image](https://github.com/lzim/teampsd/assets/30132017/b1c33ff3-5f42-4641-b368-9341f5e8bc12)

**Comment by tejaspesquare** [comment]
@jamesmrollins  - Facilitator Registration link is hidden now on both Prod & Test Breakfix login screen.

![image](https://github.com/lzim/teampsd/assets/144898781/0853eed4-5635-4fdc-b339-1d613fc2c617)
