### ISSUE TITLE
1.7.5 Self-registration Portal

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#311]
@lzim @staceypark 

The Portal is just about ready to be released into test.  However, I need the following before I can do that:

1.  The GIFs below do not have adequate resolution.  Can we make them into a larger resolution, such as such as 1600x500, 1280x400?

* https://raw.githubusercontent.com/lzim/teampsd/master/resources/gifs/sim_ui_4.gif
* https://raw.githubusercontent.com/lzim/teampsd/master/resources/gifs/sim_ui_5.gif
* https://raw.githubusercontent.com/lzim/teampsd/master/resources/gifs/sim_ui_10.gif
* https://raw.githubusercontent.com/lzim/teampsd/master/resources/gifs/sim_ui_6.gif

2.  Please confirm that the email address we can send the registration information from is "mtl.info@va.gov"

**Comment by jamesmrollins** [comment]
@lzim we need to develop a convention for the course code.  It will be stored in coursecode.xlsx in the Dynamic Data folder of the Interface directory.  I will make up some for testing purposes, but we should make up a standard.

**Comment by lzim** [comment]
Thanks @jamesmrollins 

@staceypark and I will see if we can get higher res .gifs ASAP I do wish they were clearer.

@ericasimon Can we double-check at the HQ meeting today about, which email address would be sending the self-registration information from? 

@jamesmrollins We will have these email addresses that may be relevant for this
- mtl@va.gov - A distribution list for updates regarding new _MTL_ releases etc.
- mtl.info @va.gov - An inbox for reaching out to learn about _MTL_

**Comment by staceypark** [comment]
@jamesmrollins @lzim 
mtl@va.gov distribution list - currently working on recreating this with the correct email address (currently is vhamtl@va.gov)

mtl.info@va.gov - the email address exists and is live, but IT needs to finish up delegation of access to the email

@ericasimon expects both of the above to be resolved within the next two weeks

**Comment by lzim** [comment]
Hi @jamesmrollins 

It looks like the R01 link was released and can be added to the self-registration/demo site: 


1R01DA046651 (text shown for link below)
https://projectreporter.nih.gov/project_info_description.cfm?aid=9684317&icde=43169143&ddparam=&ddvalue=&ddsub=&cr=2&csb=default&cs=ASC&pball=

**Comment by jamesmrollins** [comment]
@lzim as discussed - the proposed language for the audience identifier on the page header.  The first sentence may be the only thing necessary.  The second sentence is more of a description of the program.

“The purpose of this website is to inform the wider mental health care community of vital research sponsored by the National Institute on Drug Abuse to improve mental health care delivery within the Veterans Administration. _Modeling to Learn_ teaches systems thinking and uses system dynamics modeling to streamline the implementation of improvements to mental health care services.”

**Comment by lzim** [comment]
@jamesmrollins Thanks for your work on this!

Here are my edits for the demo intro at the top:

Can we make the MTL logo even larger than the version I see today? More of a Banner.

Text for the top:
Funded by the National Institutes of Health, scientific study of _Modeling to Learn_ is underway to determine its effectiveness increasing delivery of evidence-based addiction and mental health care (NIDA R01DA046651; PI: Zimmerman). The _Modeling to Learn_ program supports multidisciplinary teams of frontline psychiatry, psychology, social work, nursing and certified peer support specialist providers in the Veterans Health Administration. This website supports the research effort by providing simulation demonstration to implementation science/quality improvement researchers, and to patient, provider and policy-maker stakeholders across the Veterans Health Administration, and other integrated addiction and mental health care systems.

**1. Let's not ask for location information - remove that prompt.**

**2. Let's use this order:**
a. First Name
b. Last Name
c. Email
d. Password
e. Password confirmation
f. Institution
g. Role
h. Discipline
i. How did you find us
j. Course code
k. Email updates

**3. Here are text edits:**
- Institution (choices in this order):
1. Veterans Health Administration
2. Non-VA Health Care System
3. Technology or Data Business
4. Federal Agency
5. State Agency
6. City or County Agency
7. Media or Press
8. Foundation
9. Other

- Role
1. Patient
2. Provider
3. Policy Maker
4. Researcher or Scientist
5. Student or Trainee
6. Health Care Administrator or Manager
7. Company Executive or Lead
8. Other

- Discipline
1. Psychiatry
2. Psychology
3. Social Work
4. Nursing
5. Peer Support Specialist
6. Counseling
7. Other Licensed Medical Provider
8. Public Health
9. Public Policy
10. Data Science and Statistics
11. Engineering and Operations
12. Other

- How did you find us?
1. VA Communications or Training
2. Scientific Manuscript
3. Scientific Conference
4. GitHub
5. Social Media 
6. Press
7. Other

- Course Code
You do not need a course code. However, some users may have course codes for specific trainings.

- Would you like email updates about  _Modeling to Learn_ quick tips and new releases?
yes/no

**Comment by jamesmrollins** [comment]
Thanks @lzim for the edits.  I will make them straight-away.  I do have a question - what size would you like the MTL Demo and target audience statement as a percentage of the total screen area.  I estimate it is currently at ~ 25%.

**Comment by jamesmrollins** [comment]
Hi @lzim,
Take a look below.  Which would you prefer?  

![image](https://user-images.githubusercontent.com/30132017/53388822-88113f80-3941-11e9-8dea-0dd79f7ab88a.png)

![image](https://user-images.githubusercontent.com/30132017/53388977-2b625480-3942-11e9-95cc-efc60d11d32b.png)

**Comment by lzim** [comment]
@jamesrollins I like this second one!

**Comment by lzim** [comment]
Thanks @jamesmrollins 

I checked it out this afternoon! It's looking really good.
- FYI: The R01 link doesn't go anywhere for some reason. The R21 link is working.

- I'm going to upload a fresh video to YouTube for an updated "Quick Start." I'll let you know when it's up.

- I think we to use this link for the "Cheatsheet" so it's easier for them to quickly get their hands on the right file:
https://github.com/lzim/mtl/blob/master/session05/s05_learner/mtl_how_sim_cheatsheet.pdf

- Can the slidedeck and manuscript icons be hyperlinks that take to the files?
I seem to want to click on them to get the information.

Thanks!

Lindsey

**Comment by jamesmrollins** [comment]
Thanks @lzim for the review.  I have updated the RO1 and Cheatsheet links in the DEMO Admin site, so they both should work.  When you upload the YouTube video, let me know and then I can walk @staceypark  through the admin screen link update process. 

I have changed the "Links" section in the Admin screen to "Resource Management."  The design intent for this section is to allow the webmaster the ability to modify any of the text from "Modeling to Learn" down to "Funding."  Additionally, I am investigating with DEV, the ability to make each section dynamic so you can add more content as it becomes available.  Kind of like SharePoint, only a lot easier.

**Comment by jamesmrollins** [comment]
The entry below documents edits requested by @lzim and @staceypark for mtl.how/DEMO.

1. Increase the white space on the left and right margins, top to bottom. Increase margins on left and right to 1.75 inches. Increase spacing between sections by 1.5.
2. Make landing page look as indicated in the sketch. Modeling to Learn logo takes up 1/4 of screen. Text takes next 1/4.  Shrink .gif files so they fit as a band in the slider along the bottom 1/2 of the screen.  @lzim to provide 4 updated .gif files. Ensure all 4 files are present. Put ½ inch of white space between each .gif in the slider.  
3. The .gif animations do not appear to be working properly in Safari. Please check functionality.
4. Replace the .gif files with the ones provided in separate attachments.
5. Mtl.demo is not the same size as other icons in the "Modeling to Learn" section. Make all icons the same size.
6. Insert “Other” as an option in the drop down menu of the login pop-up. Add a field directly below drop down menu, to gather “Other” information. Add data to API, display in Admin section and add to export.
7. Add italics functionality or coding to the Resource Management section so user can instruct page to display text in italics.  In the example, “Modeling to Learn” should be italicized since it is preceded and followed by a double-asterisk.
8. Presentation, Papers and Funding icons should execute associated hyperlinks when clicked. If a new entry into a section is added, it too should be able to execute the hyperlinks.

@jamesmrollins will circle back around with @staceypark to update text and links when full administrative functionality is completed. 

Sketch
![image](https://user-images.githubusercontent.com/30132017/54570487-e018f000-499b-11e9-9f29-c99b9a7c635a.png)

**Comment by jamesmrollins** [comment]
Hi @staceypark and @lzim - we need the .gif files to be a higher resolution - 1920 x 1080.  We had this issue the last time, and I believe you resolved the issue by recording on a larger screen.  Is it possible to get this done by COB 3/19?  COB can be like, really late, but please let me know an approximate time.  Thanks, James

**Comment by lzim** [comment]
@jamesmrollins I uploaded a new video for the "Quick Start Link" to the Admin page
https://youtu.be/sa1NsucEJrs

Thanks!

**Comment by lzim** [comment]
Thanks for all the work on this, I believe this is done/live 👍
