### ISSUE TITLE
MTL Live EES Review Edits

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#312]
- [ ] Language on SP module - certain scripts still refer to it as “coming”
- [ ] Basecase of “No new decisions” vs. “no changes”
- [ ] “Modeling to Learn” punctuated with italics, not quotes, bold, etc.
- [ ] Done and Do tables and header in correct order
- [ ] Need to add Individual vs. team world explanation 
- [ ] Use “section” instead of “tile”

**Comment by lzim** [comment]
Thanks @staceypark 

I've added @branscombj and @dlkibbe to the thread.
Jane and Debbie these are edits we've found working with the _MTL Live_ EES Committee 

@staceypark aren't these edits that you can make using a **pull request** but we can also be alerted to other places where they occur?

- [ ] We need to test and then describe the incremental sim

- [ ] I have open questions on Issue #298 for @TomRust related to what I found running a series of sims for the intensive outpatient program in 1.7.3 TEST  We need those answered and want to be ready for that test.

Thanks!

**Comment by branscombj** [comment]
@lzim @staceypark @dlkibbe Thank you for adding Debbie and me to this thread. Could you clarify what needs to happen?

**Comment by staceypark** [comment]
@branscombj @dlkibbe 
These changes are for the learner see scripts, which we are reviewing with the MTL Live EES Committee members. I made a pull request outlining all the notes above and more here:
https://github.com/lzim/teampsd/pull/313

Once the edits are made, we can do an official migration to the mtl.how repository with the changes.
thanks for you help!
