### ISSUE TITLE
2024_apr_epic: Sim UI PROD MM Learning Mode Save Dialogue names Learning Mode 0 and Learning Mode 1 as NPSR

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#3131]
## AC:
- [ ] Labels needed to indicate Learning Mode (NPSR = 1; EPRVI = 0):
  - [ ] Home landing page instruction for how to initiate a new session in a different learning mode - James
  - [x] Home Screen in Learning Mode dialogue itself need (0,1) label in the Learning Mode (NPSR = 1; EPRVI = 0)
  - [ ] Experiments Section "i" (see Lindsey's comment below) - James
  - [x] Experiments Section "bc" (see Lindsey's comment below) - Dev
  - [x] Results Dashboard in the "?" for each experiment (see Lindsey's comment below) - Dev
  - [x] Save Dialogue should indicate all the information (0,1) - Dev

---
As you can see in the check below.

Two Base Case Experiments were run one in Learning Mode 1 and one in Learning Mode 0, but both are saved as NPSR.

![image](https://github.com/lzim/teampsd/assets/7454688/931411c2-d03a-45f9-8172-b72316941e97)

![image](https://github.com/lzim/teampsd/assets/7454688/5019d6d9-6755-4053-9769-4891cfab2f7f)

- [ ] _Where do frontend Sim UI users check the alignment between?_ 
Learning Mode 1 and 
Learning Mode 0 
New Patient Start Rate (NPSR) mode and 
Existing Return-Visit-Interval (ERVI) mode

**Comment by lzim** [comment]
**Label Needed:  Learning Mode (NPSR = X; ERVI = X)**

- [ ] Home landing page instruction for how to initiate a new session in a different learning mode (Current State: Can do this with reselecting data to start a new session).
- [ ] Home Screen in Learning Mode Dialogue Itself
- [ ] Experiments Section "i" and "bc"
- [ ] Results Dashboard in the "?" for each experiment
- [ ] Save Dialogue

**Comment by lzim** [comment]
Need (0,1) Label in the Learning Mode (NPSR = X; ERVI = X) 

![image](https://github.com/lzim/teampsd/assets/7454688/0d94dc95-76e1-4dd4-bd08-0cc1f0649382)

**Comment by jamesmrollins** [comment]
3/20 Standup

- @jamesmrollins was not able to force the error with the system.  
- @tejaspesquare and Divyesh will fix the experiment maintenance issue so the files will list.
- @lijenn will delete test experiment and correctly rename the NPSR to EPRVI in the morning.

**Comment by tejaspesquare** [comment]
@jamesmrollins - 
Prod - now files are listed on Experiment Maintenance section.
![image](https://github.com/lzim/teampsd/assets/144898781/5a6bbe4a-58f7-4ec1-bd67-ae03001f7249)

 
It was restricted to render earlier just because some items having undefined name present, being handled now. 
![image](https://github.com/lzim/teampsd/assets/144898781/d7745cd4-5a9f-4907-b157-7df70fce58d5)

**Comment by lijenn** [comment]
@lijenn Deleted the Q8_EPRVI_bc_2024_3_20 experiment and renamed 

Q8_NPSR_bc_2024_3_20 to Q8_EPRVI_bc_2024_3_20 since the Learning Mode coded in the experiment was 0 and not 1.

**Comment by ljmoody** [comment]
@tejaspesquare Jenn and I tested in TEST-Slow, Care Coordination module.
Experiments using learning mode 0 are not being named correctly.
![image](https://github.com/lzim/teampsd/assets/124643236/c1d20074-3aa4-4359-9064-5cf8f0271c73)

![image](https://github.com/lzim/teampsd/assets/124643236/6b025017-a289-4375-97ac-398a98920a5f)

**Comment by tejaspesquare** [comment]
@ljmoody , @lijenn - Could you please check now on TEST-Slow .  Experiments using learning mode o showing correct value & named correctly

![image](https://github.com/lzim/teampsd/assets/144898781/ca8d75c1-2f37-4a64-afd5-1f56841ecf9f)

**Comment by lijenn** [comment]
@tejaspesquare Thanks for fixing this is TEST-SLOW. @ljmoody and I will test today. 

Can you push this code fix in Prod too?

**Comment by jamesmrollins** [comment]
@tejaspesquare - 

- [ ] Please add the following changes to ALL Learning Mode dialogue pop-ups in Test and PROD.

![image](https://github.com/lzim/teampsd/assets/30132017/0e8a6f50-7d9d-4041-94df-237d24f03a6e)

- [ ] Please confirm whether our GitHub CICD routine has been restored for model update. Note that we should have a CICD action that where updated model files will be moved to the respective projects, by merging a model file into a DEV branch, then merging DEV into TEST and then merging TEST into Master in LZIM/MTL.

**Comment by tejaspesquare** [comment]
@jamesmrollins - We have applied changes in in Learning mode pop-ups in Test & Prod.


Prod-
![image](https://github.com/lzim/teampsd/assets/144898781/86221dc1-c793-44d9-a160-2906fc1c0357)

Queries:

1. Could you please tell us shall we apply this change on Test Break-fix or not.
2. Do we need to change this code to 'ESRVI' from RVI (pink highlighted)
![image](https://github.com/lzim/teampsd/assets/144898781/2bd47266-65f0-40e6-be0a-423d3a986fcb)

Note: On Test-Slow instance this is in-progress. Design related changes is pending.

**Comment by lijenn** [comment]
Hi @lzim and @dlounsbu! Are you both running experiments in the Prod for team lzim/research [#595](https://github.com/lzim/research/issues/595). If so, please ignore the soft moss data file:


@tejaspesquare Did you add this file for this team in Prod? If not, this is a bug.

**Comment by ljmoody** [comment]
Hello @tejaspesquare, please make these edits to the Learning Mode popup:
![image](https://github.com/lzim/teampsd/assets/124643236/d064fb91-97cc-4c6c-ad0f-f42a6c8b9653)

- [ ] Yes, please push this to Break-fix as well.

**Comment by tejaspesquare** [comment]
@lijenn - Yes, we were using soft moss model file for troubleshoot the issue which James reported reg. API response data.
@ljmoody - Learning Mode changes will be updated in PROD & Break-fix.  On Test-Slow it is not available yet, code change done but some design changes need to apply.

**Comment by tejaspesquare** [comment]
@ljmoody & @lijenn - Please find updates below:

Prod Instance- 
![image](https://github.com/lzim/teampsd/assets/144898781/d48a903d-691e-48b8-b55a-482859362900)

Test Slow-
![image](https://github.com/lzim/teampsd/assets/144898781/4ea97355-4687-4cbc-9a38-10e1918119d9)

**Comment by lijenn** [comment]
> @lijenn - Yes, we were using soft moss model file for troubleshoot the issue which James reported reg. API response data. @ljmoody - Learning Mode changes will be updated in PROD & Break-fix. On Test-Slow it is not available yet, code change done but some design changes need to apply.

Thanks @tejaspesquare! Would it be alright for us to delete the soft moss data file in Prod?

**Comment by ljmoody** [comment]
Hi @tejaspesquare, please revise accordingly:

## In break-fix:
![image](https://github.com/lzim/teampsd/assets/124643236/d4a1de68-84d6-4c82-b1ec-31a0a522ac38)

## in Test-slow:
![image](https://github.com/lzim/teampsd/assets/124643236/3fd9b2a1-76bc-4727-8526-11883e9627c8)

**Comment by ljmoody** [comment]
Discussed at stand up 3/31/2024. 
@tejaspesquare will mirror Break Fix and Test Slow to have the same wording and formatting as Prod.

**Comment by tejaspesquare** [comment]
@ljmoody - Changes applied on Test-Slow. Break-Fix not updated yet as that will auto apply once code migration happen.

![image](https://github.com/lzim/teampsd/assets/144898781/974169c1-e087-419a-afad-499428ef1457)

**Comment by lzim** [comment]
Thanks @tejaspesquare & @ljmoody

**Comment by lzim** [comment]
Whoops...didn't mean to close it tho...it's early hear 🌞

**Comment by ljmoody** [comment]
@tejaspesquare, I noticed a misspelling in Test-Slow:
- [ ] Please correct spelling in Experiment > Rename popup:
![image](https://github.com/lzim/teampsd/assets/124643236/1275108c-e2d2-4885-8540-3e23a27cff04)

**Comment by tejaspesquare** [comment]
@ljmoody - Rename Experiment popup title spell is corrected & available in Test-Slow.

![image](https://github.com/lzim/teampsd/assets/144898781/2c38b84b-cc04-4965-8896-e28aaac2b468)

**Comment by ljmoody** [comment]
Tested Learning Mode saved experiments for both modes in Test-Slow using:
- 29march_laura_shared world
- Team Data file: sampledata_2024_03_29.xlsx
- CC experiment entered as EPRVI labeled and categorized correctly:
![image](https://github.com/lzim/teampsd/assets/124643236/6ac2e6d5-4001-458d-9f9b-ec81b62b323e)
- MM experiment entered as NPSR is labeled and categorized correctly:
![image](https://github.com/lzim/teampsd/assets/124643236/e05b0851-9cab-4083-9370-e03fd0c489f2)

@tejaspesquare, I believe this validates the fix and it can be pushed to PROD instance now.

**Comment by ljmoody** [comment]
✅ Validated spelling correction was made. 

> @ljmoody - Rename Experiment popup title spell is corrected & available in Test-Slow.
> 
> ![image](https://private-user-images.githubusercontent.com/144898781/319147942-2c38b84b-cc04-4965-8896-e28aaac2b468.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNjUyNDcsIm5iZiI6MTcxMjE2NDk0NywicGF0aCI6Ii8xNDQ4OTg3ODEvMzE5MTQ3OTQyLTJjMzhiODRiLWNjMDQtNDk2NS04ODk2LWUyOGFhYWMyYjQ2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwM1QxNzIyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYmM4Mjc0N2RmM2JkMjhkYmE1YWQ3ZWU2MDE3MmI5NTAyZmQ3YTJjZDFhMjNjMDRkOWMzMDAwOTc2ZmQyZTVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zSFZJ769KEMSGSb9b_izkWKU4ZkKMof7hS6Q3VzRdkA)

**Comment by ljmoody** [comment]
@tejaspesquare - I looked at the Learning Mode pop-ups in Test-Slow, PROD, and Break-Fix today. 
- [ ] Revisions are needed in PROD (see below)
- [ ] Same revisions are needed in Break-Fix, and I understand from your message above on 4/1 that will auto-apply once code migration happens
![image](https://github.com/lzim/teampsd/assets/124643236/bceb236c-2bff-4819-9371-2abbb0ee1706)

**Comment by lijenn** [comment]
Discussed Sim UI Stand Up 04/04/2024:
- @tejaspesquare will be able to make the revisions in Break Fix once the migration from Prod to Break Fix is completed. Will reach out to us next week for updates.

**Comment by lijenn** [comment]
Discussed 4/7 Sim UI Stand up:
- @tejaspesquare will start with the migration from TEST-SLOW to BREAK-FIX (will be a copy of PROD). Will fix the issue in Prod for CC module.

**Comment by tejaspesquare** [comment]
@lijenn - Revision for Learning mode is done on both Prod & Break-fix. Kindly check at your end.

Test Break-fix:
![image](https://github.com/lzim/teampsd/assets/144898781/a0be08c5-7e64-410e-abfd-4f5072363444)

Prod:
![image](https://github.com/lzim/teampsd/assets/144898781/bc8859c1-512e-481e-9f3a-3dcd876dc688)

**Comment by ljmoody** [comment]
## 3/14 standup:
@ljmoody will test this week.

**Comment by ljmoody** [comment]
fyi: @tejaspesquare @lijenn @jamesmrollins 
Tested and verified:
✅ Learning mode popup text is correct in PROD and Break-Fix.
✅ CC experiments are saved correctly with EPRVI and NPSR acronyms and learning mode codes (0, 1)
✅ MM experiments are saved correctly with EPRVI and NPSR acronyms and learning mode codes - screenshots below:
![image](https://github.com/lzim/teampsd/assets/124643236/c7b686c5-9193-4ea9-963d-f5d892faa83d)
![image](https://github.com/lzim/teampsd/assets/124643236/e287d289-5837-4c2c-b0dd-986f89e2f621)
![image](https://github.com/lzim/teampsd/assets/124643236/b4a8a810-31fc-4c8d-8825-746ad953224a)

**Comment by ljmoody** [comment]
@jamesmrollins, please incorporate the following modifications and check off as/when completed so Jenn and I can validate.

- [ ] **1. Home landing page instruction for how to initiate a new session in a different learning mode.** Per AC above.

- [ ] **2. Changes to Experiments Section "i":**
![image](https://github.com/lzim/teampsd/assets/124643236/3b893316-494d-424b-8061-5f08002f748c)

**Comment by ljmoody** [comment]
@tejaspesquare, please incorporate the following changes and check off as/when complete so Jenn and I can validate. 

- [ ] **1. Changes to Experiments Section "bc":**
![image](https://github.com/lzim/teampsd/assets/124643236/eb2b434d-658d-44cd-9b98-825846c71990)

- [ ] **2. Changes to Results Dashboard in the "?" for each experiment:** 
![image](https://github.com/lzim/teampsd/assets/124643236/f5311572-d500-4b89-8569-848ff9719941)

- [ ] **3. Changes to Experiment Slider Abbreviations blue bar in Save Experiment pop-up (Save Dialogue should indicate all the information (0,1)):** 
![image](https://github.com/lzim/teampsd/assets/124643236/a592281d-b361-4d81-83cb-ae9ddbff0dc0)

**Comment by jamesmrollins** [comment]
## 4/21 Sim UI

- Completed in DEV environment up for local testing.
- Will be available tomorrow 4/22 for end user testing.

**Comment by ljmoody** [comment]
Tested 4/22 in test-slow. 
✅ Verified changes to Experiments Section "bc":
**@tejaspesquare, there are two modifications needed in this Learning Mode pop-up:**
- [ ]  Please align the highlighted text to the left (versus justified).
- [ ] Looks like boldface was lost when the text update was made. Please see Point 1 above in my comment last week and re-apply boldface to the requested text.
![image](https://github.com/lzim/teampsd/assets/124643236/3302d6d8-e3a4-4213-9cd7-0f82c1453b3e)
 
✅ Verified changes to Results Dashboard in the "?" for each experiment:
![image](https://github.com/lzim/teampsd/assets/124643236/e17446e8-ddca-40a2-9038-dd1956faeb80)

✅ Verified changes to Experiment Slider Abbreviations blue bar in Save Experiment pop-up:
![image](https://github.com/lzim/teampsd/assets/124643236/c154cc84-fdf0-4b8d-bbc0-33b0af13d042)
![image](https://github.com/lzim/teampsd/assets/124643236/e47dfa06-d33e-4bc8-bb66-635192c8ab35)

**Comment by tejaspesquare** [comment]
@ljmoody - Text alignment & boldface is done. Kindly verify on Test Slow. Thank You!

![image](https://github.com/lzim/teampsd/assets/144898781/9ade3aa4-1f86-431d-b4c0-7a49001de0c5)

**Comment by lijenn** [comment]
Discussed Stand Up 04/24/24:
- @lijenn will test the above and then close the card if there are no issues.

**Comment by lijenn** [comment]
Jenn verified the left alignment is completed in CC and MM. 
Moving to Done column, @ljmoody feel free to close if the documentation is done for this.

**Comment by ljmoody** [comment]
Hi @lijenn, 
There are still two items James has yet to complete from Lindsey's checklist above, I think:
  - [ ] Home landing page instruction for how to initiate a new session in a different learning mode
    - Or is the above considered "done" by the red learning mode buttons and documentation in the _MTL_ manual?
  - [ ] Experiments Section "i" (needs to indicate learning mode #s)

Re: documentation, I've added "include info re: places indicating Learning Modes (NPSR = 1; EPRVI = 0) (ref #3131)" as a checklist item in #3030.

**Comment by ljmoody** [comment]
@lzim, to clarify re: labels needed and your note about "Home landing page instruction for how to initiate a new session in a different learning mode", do you want this information to be added to the end of the intro text at the top (highlighted in the graphic below)?
![image](https://github.com/lzim/teampsd/assets/124643236/6dcce118-1627-42c6-8276-98de64d0bd9b)
fyi: The Learning Mode pop-up does show up in two places of this page (see numbered pins) and the learning modes are specified there:
![image](https://github.com/lzim/teampsd/assets/124643236/c05c1d46-ab3b-4f4a-ae72-f8319cbc0147)
