### ISSUE TITLE
2024_apr_epic: BUG: Test_slow is not preformatting team data files into proper format for use by the model

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#3134]
## When the user uploads a team data file in the Test_slow project, the system is not changing the format of the file from the Power BI export (all variables in a single cell), to a Vensim standard format (all variables parsed into separate addressed cells).

- This appears to indicate the code that accomplishes the conversion is not incorporated in the 3.7 application.
- Testing shows that the code is working fine in the Sim UI PROD project.

## Results in nonsense values in the model.  Closer inspection reveals incorrect values in Team Data.

![image](https://github.com/lzim/teampsd/assets/30132017/9135c6b3-b0a3-4af5-a7e2-559e2661a63c)

## Power BI Export Format - This is the file that is in the directory, should be converted by the time in lands in the Epicenter Model Directory.

![image](https://github.com/lzim/teampsd/assets/30132017/3696ef83-6814-470a-b49f-01aee7a1a848)

## Sim UI Converted Format - This what the file should look like to be readable by the Sim UI.

![image](https://github.com/lzim/teampsd/assets/30132017/a6c9108b-76b3-4785-8bcc-6081a88c424d)

**Comment by tejaspesquare** [comment]
@jamesmrollins - This is in-progress. We will let you know in case more details required to troubleshoot the issue.

**Comment by lijenn** [comment]
Discussed at Stand Up 3/31/24:
@tejaspesquare will continue working with David from Forio to resolve this issue. The Dev team found inconsistencies in the data files in both Prod and Break Fix.

**Comment by ljmoody** [comment]
Discussed at 4/3/24:
@tejaspesquare says effort is halfway done.
When uploading to Sim UI, the raw file is not uploading correctly; but in production it is. Has to do with a file structure change which requires a different API. Conversion is being handled by Dev team in Test-Slow.

**Comment by lijenn** [comment]
Discussed 4/7 Sim UI Standup:
- @tejaspesquare 70% of the work for this has already been completed, remaining is expected to be done this week.

**Comment by ljmoody** [comment]
##4/14 standup:
@ljmoody will test this week.

**Comment by ljmoody** [comment]
@tejaspesquare, testing in Test-Slow verified that:
✅ data files uploaded are preformatted into proper format for use by the Sim. 

- Screenshot below is of testing. -- Created a new team, renamed data file (base files is "soft moss" file - the same file that was returning incorrect values), uploaded to team, and numbers showing are as expected.
- Moving this card to Done column within bug_tracker

![image](https://github.com/lzim/teampsd/assets/124643236/eb58b489-79c5-4790-b464-f71da89c1e2f)
fyi: @jamesmrollins @lijenn
