### ISSUE TITLE
2024: TEST dynamic decision dashboard wireframe & alt text for 508 compliance

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3137]
## AC:
- [ ] test screen reader prompts on DDD home page
- [ ] validate [508 wireframe](https://takouba-my.sharepoint.com/:b:/g/personal/lmoody_praxisanalytix_com/ETl7EzLM_bBFtfiengwXpOEB_Oyx2qq9xpvOicJsAr-eng?e=uxtTWg):
  - [ ] tag order is correct
  - [ ] screen reader narrative matches correct tag #s
- [ ] all feedback to DEV is addressed and/or incorporated

**Comment by ljmoody** [comment]
This appears to be a duplicate issue card. Issue is more fully developed and effort is tracked via #3198. Changed title, removed milestone, kept 0 points. 
Closing this card.

**Comment by ljmoody** [comment]
This appears to be a duplicate issue card. Issue is more fully developed and effort is tracked via #3198. Changed title, removed milestone, kept 0 points. 
Closing this card.

**Comment by hnorthcraft** [comment]
#adjudicate_memo adding dup label
