### ISSUE TITLE
2024_apr_epic Bug: Sim UI PROD discoveries during #systems_sme_prep

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#3138]
**wk4 2024_mar_epic #systems_sme_workflow**
@lzim 
@dlounsbu 

While prepping for [#595](https://github.com/lzim/research/issues/595) we noticed the following:

1. Need to ensure that the Administrator Dashboard in TEST and PROD indicates "**Team Care**" (Not Aggregate) and "**Team Flow**" 
![image](https://github.com/lzim/teampsd/assets/7454688/c80fc33a-8d0a-4e42-b65d-d57f48985eec)

**Comment by lzim** [comment]
We also observed these **odd "undefined" experiments** - _can these be deleted?_

![image](https://github.com/lzim/teampsd/assets/7454688/9eb84c5b-7ea6-4011-9235-98371f88c683)

**Comment by lzim** [comment]
_Updates:_
- [x] We deleted the experiments shown above.
- [x] We deleted data files we are not using with this team.
- [x] We retained the "moss" file.

**Comment by lijenn** [comment]
Discussed at Sim UI Stand Up on 3/31/24:
- [ ] @lijenn will delete the soft moss data file.
- [ ] @tejaspesquare will change "Aggregate" to "Team Care" and  "SP" to "Team Flow".

**Comment by tejaspesquare** [comment]
@lijenn - Model name changed "Aggregate" to "Team Care" and "SP" to "Team Flow". Available to test on Test-Slow.

![image](https://github.com/lzim/teampsd/assets/144898781/c1dbeee7-1027-4d39-8905-1b8d1cbd948d)

**Comment by ljmoody** [comment]
@lijenn, FYI I deleted the soft moss data file from Prod instance.

@tejaspesquare:
- [ ] Do you know why "2033" is at the end of this time/date stamp (per Lindsey's question above):
> _Do you see the 2033 in the screenshot below? Does that need to be displayed or can it be removed?_
![image](https://github.com/lzim/teampsd/assets/124643236/f1755e28-fe29-4850-a11b-606a8e79da2a)


- [ ] ✅ Verified that "Aggregate" displays as "Team Care" and "SP" displays as "Team Flow" in Test-Slow. Please promote to Prod. Once that is verified, we should be able to close this card.

**Comment by tejaspesquare** [comment]
@ljmoody - Answer to Lindsey's query about '2033' on Date/Time column, it does render time of specific day. Per logic followed format "yyyy_mm_dd_hhmm". Thank You!

If this clarified, then can we promote code to Prod?

**Comment by tejaspesquare** [comment]
@ljmoody - Code is promoted to Prod. environment.

Result on Test Break fix-
![image](https://github.com/lzim/teampsd/assets/144898781/d89085fd-a4fc-4d4d-ab96-7756386e0c8d)

**Comment by lzim** [comment]
Thank you! 🥇

**Comment by ljmoody** [comment]
✅ Validated today by testing experiments in PROD environment. Checked for "Team Care" (vs Aggregate) and "Team Flow" (vs SP). Works as expected. 

Closing this card as complete.

**Comment by hnorthcraft** [comment]
@lijenn SP esimate? #adjudicate_memo

**Comment by lijenn** [comment]
@hnorthcraft 3 SP following Operations standard scale since this was prep work that had to be resolved from a live site meeting to "advance a major milestone/dependence impacting progress across users".
