### ISSUE TITLE
wk4 2024_mar_epic Bug: Sim UI TEST data not uploading via Settings popup

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3139]
- Bug discovered 3/27/24 when Laura and Jenn were testing for #3091. Approx 1pm MST. 
- Trying to upload a data file to _team, _ind, and _shared worlds of newly created team (j&l_testing_2024_03_27). 

In TEST-Slow instance, data files uploaded via the Settings popup are not being uploaded:
![image](https://github.com/lzim/teampsd/assets/124643236/71e1c091-1d14-4519-a353-a60d4b4bd07a)

An additional screenshot with the inspect/console information:
![image](https://github.com/lzim/teampsd/assets/124643236/ec12a7d0-a6a5-4173-a0c3-359dd150a392)

**Comment by tejaspesquare** [comment]
@ljmoody - This is working fine now & code moved to Test-Slow.

![image](https://github.com/lzim/teampsd/assets/144898781/f794342c-a2f0-4396-974e-3a9a50bcf19e)

![image](https://github.com/lzim/teampsd/assets/144898781/e3f26c09-7671-48bf-9134-0ca7ff5e4c7f)

**Comment by ljmoody** [comment]
I tested this morning @tejaspesquare, and the issue is still ongoing for me. Please [watch this video](https://takouba-my.sharepoint.com/:v:/g/personal/lmoody_praxisanalytix_com/Edw7bxKZaudLkdZk-brLSqMB4udEg9y9qNjIwduOQE0bEw?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=lVSnRn) to see my test + inspect/console.

**Comment by lijenn** [comment]
Discussed at Stand Up 3/31/24:
- [ ] @ljmoody will do a hard refresh to retest this issue and report back.

**Comment by tejaspesquare** [comment]
@lijenn & @ljmoody - Upload file through Data section (Settings ->Add) works fine now. 
In V3.0 we don't have sub-folder concept & in 3.7 it has.
We have to think of business rule to perform Delete action as because in current scenario file will be associated with individual group & possibly 2 or more groups will upload same name file but will have different locations. So, on delete which file supposed to be removed will cause for others. Could you please suggest.

![image](https://github.com/lzim/teampsd/assets/144898781/d06a039a-7a27-4b29-9e53-6a4d58fa0db3)

Note: On this section we bring up (as per our conversation) all listed files from Epicenter. Alos, we have filtered duplicate file if any.

**Comment by ljmoody** [comment]
@tejaspesquare - Good question. We will bring this up at our sim_ui workgroup meeting and get back to you on this. In the meantime, since this issue will be closed today, I'm moving your question into #2997 for tracking purposes, FYI. 


> @lijenn & @ljmoody - Upload file through Data section (Settings ->Add) works fine now. In V3.0 we don't have sub-folder concept & in 3.7 it has. We have to think of business rule to perform Delete action as because in current scenario file will be associated with individual group & possibly 2 or more groups will upload same name file but will have different locations. So, on delete which file supposed to be removed will cause for others. Could you please suggest.
> 
> ![image](https://private-user-images.githubusercontent.com/144898781/318455386-d06a039a-7a27-4b29-9e53-6a4d58fa0db3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5OTk5MzksIm5iZiI6MTcxMTk5OTYzOSwicGF0aCI6Ii8xNDQ4OTg3ODEvMzE4NDU1Mzg2LWQwNmEwMzlhLTdhMjctNGIyOS05ZTUzLTZhNGQ1OGZhMGRiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQxOTI3MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YTg4NWVmOGFkYWUwYzU3NTZkZTNiM2UxOGRkZGU5Nzg5YWFjYjZhNTg3ZGNiMWQ2ZWYwZjVlZDMyODU5NzQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2LSYA5gHZ3rp-iZvtn6Z_eczm7Bklaf5xy4Ne3uGj6k)
> 
> Note: On this section we bring up (as per our conversation) all listed files from Epicenter. Alos, we have filtered duplicate file if any.

**Comment by ljmoody** [comment]
✅ validated that the Settings popup team data upload is working (screenshot of successful upload below). Closing this issue as completed.

![image](https://github.com/lzim/teampsd/assets/124643236/cbc64842-3b6f-4581-a092-be5baec108ae)

**Comment by hnorthcraft** [comment]
@lijenn #adjudicate_memo sp estimate:?

**Comment by lijenn** [comment]
@hnorthcraft 2 SP since this card is about a specific bug that was troubleshot, fixed, and tested. No user documentation needed.
