### ISSUE TITLE
wk2 2024_apr_epic #story_b: Rename all "Guide" Tutor references in Sim UI

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3140]
## AC:
- [x] Rename **ALL** Sim UI Tutor prompt "GUIDE" icons to "MANUAL".
- [x] Need by week 1 May for the _MTL_ 3.7 release to PROD. 

![image](https://github.com/lzim/teampsd/assets/124643236/cccb9245-72b3-4149-84a9-6bd033d559a1)

**Comment by tejaspesquare** [comment]
@ljmoody - This is done & code moved to Test-Slow.

Dynamic Decision Dashboard -
![image](https://github.com/lzim/teampsd/assets/144898781/b11552ad-b1e8-419e-9a0e-7a3f9fff7665)

Episodes of Care -
![image](https://github.com/lzim/teampsd/assets/144898781/cfaeabe6-20f0-42f8-bab8-bcecc10cd883)

Feedback Loops -
![image](https://github.com/lzim/teampsd/assets/144898781/4f8889fa-ca13-4214-854f-a7eaba7cc821)

![image](https://github.com/lzim/teampsd/assets/144898781/9846df38-ea66-4cbb-bce8-f33cb26c622e)

**Comment by ljmoody** [comment]
✅ Validated today that all "GUIDE" Tutor prompt icons are updated to read "MANUAL."
ℹ️ Noticed that many of the web links to the manual are not functional. Once the manual is updated, these web links will need to be populated (example shown in screenshot below). I've added this "to do" item to #3093.

![image](https://github.com/lzim/teampsd/assets/124643236/16010292-1462-413f-bf45-d9e3877c00df)

fyi:  @lzim
