### ISSUE TITLE
2024_apr_epic #story_b: BUG: Test-Slow Team Data upload does not upload to all chosen team worlds

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3141]
When a user uploads a Team Data file via the Administrator Dashboard Settings popup, that data file is not showing up in all worlds it was uploaded to.

Discovered 4/1/24 when testing for #3139.

Here is the breadcrumb trail of what I did in Test-Slow instance, logged in with VA account, as admin:

### 1. Used Settings popup to upload data file:
![image](https://github.com/lzim/teampsd/assets/124643236/734b112f-6a39-4fe2-b788-d08633df68c9)

### 2. Uploaded data file to 3 worlds:
![image](https://github.com/lzim/teampsd/assets/124643236/535fd4b7-13d3-4deb-bef4-a36ff9ec9024)

### 3. Successful upload:
![image](https://github.com/lzim/teampsd/assets/124643236/b841da39-b1fe-43ad-818d-c70fea6d49a3)

### 4. Then checked, with each team selected, to see what teams the data file was associated with:
- **It _was_ in _team:**
![image](https://github.com/lzim/teampsd/assets/124643236/3057f487-5564-4a33-bb40-db6b79895f42)

- **It _was not_ in _shared:**
![image](https://github.com/lzim/teampsd/assets/124643236/5de0f0ba-4e61-4fa9-b6e0-578e080ed449)

- **It _was not_ in _ind (but I think the _ind world it should show in is under my Praxis login, and it didn't show there either):**
![image](https://github.com/lzim/teampsd/assets/124643236/d94ce38d-5da6-4d46-95ea-fd73d962e71c)

**Comment by tejaspesquare** [comment]
@ljmoody - This is fixed & available to test on Test-Slow Instance.

I have uploaded file for following groups:

![image](https://github.com/lzim/teampsd/assets/144898781/3abeba81-a157-40d2-a0b1-9771724ebc2a)

File is accessible on _Shared world/Team
![image](https://github.com/lzim/teampsd/assets/144898781/e90a0313-158d-4425-a2dc-ffb46be4e42a)

_Team world/Team
![image](https://github.com/lzim/teampsd/assets/144898781/4dc98eee-fd87-4168-9d26-6f3dc5893f6b)

_ind world
![image](https://github.com/lzim/teampsd/assets/144898781/ccf21e2b-e870-423b-b1b2-37c354c50758)

**Comment by ljmoody** [comment]
✅ Validated today by :
- uploading a data file to all three worlds
- uploading a data file to just team and ind worlds
- uploading a data file to shared world only

All unique team data files were uploaded into worlds selected. 
Closing this card as complete.

**Comment by hnorthcraft** [comment]
@lijenn #adjudicate_memo sp estimate:?

**Comment by lijenn** [comment]
@hnorthcraft 2 SP since this is a specific bug that was resolved and fix was tested and implemented. No additional user documentation needed.
