### ISSUE TITLE
wk2 2024_apr_epic BUG: Test-Slow, Settings > Delete Team Data file does not delete team data file

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3142]
Discovered 4/3/2024 when testing in Test-Slow (using VA login, administrator). 

User attempted to delete a Team Data file via the Administrator Dashboard > Settings > Data > Delete. The action never completed and the file is still located in Data menu after closing the pop-up and refreshing. 

1. Selected team data file to delete and selected "yes":
![image](https://github.com/lzim/teampsd/assets/124643236/1c98552e-26f4-429f-a020-d69678bab9ac)

2. Waited for file deletion:
![image](https://github.com/lzim/teampsd/assets/124643236/3ba96a7d-e6bb-4d4e-9ba6-30aafa4e63af)

3. Screenshot of inspect console:
![image](https://github.com/lzim/teampsd/assets/124643236/ca2301a8-ee75-4274-a07d-66dd02a9bfa1)

**Comment by ljmoody** [comment]
Discussed at 4/3/24 Sim UI Standup: 
- [ ] @tejaspesquare will test and fix; he thinks that this fix will be quick and simple.

**Comment by tejaspesquare** [comment]
@ljmoody - This will automatically resolve once #2997 is fixed 
Ref. note from #2997: Team Data files listed in Team Set Up in Admin Dashboard encounter problems with deletion,

**Comment by lijenn** [comment]
Discussed 4/7 standup:
- @tejaspesquare is still working on the vensim conversion. ~70% of the work is already done and hope to complete the rest this week.

**Comment by tejaspesquare** [comment]
@ljmoody -The code has been moved to the Test Slow environment and should now function properly. Kindly re-evaluate the issue. Thank You!

**Comment by lijenn** [comment]
@lijenn verified that this is now working in Test-Slow. Thanks!

**Comment by hnorthcraft** [comment]
@lijenn #adjudicate_memo sp estimate:?

**Comment by lijenn** [comment]
@hnorthcraft 2 SP since this is a specific bug focused on deleting team data files in Test-Slow instance. Fix was implemented and tested. No additional user documentation was needed.
