### ISSUE TITLE
2024_04 Sim UI TEST: Administrative Dashboard Erratic at finding Teams - Sometimes returns none. 

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#3146]
@lijenn 
@ljmoody 
@jamesmrollins 
@tejaspesquare 

Upon using my **Administrator Login to Sim UI TEST** I've experienced erratic behavior finding Teams: 
- [ ] Sometimes returns no teams.
- [ ] Sometimes returns many teams.

**See the two screenshots and inspector consoles below.**
Both were observed on the same day, across the last two days, from the same VA laptop in Chrome.
Thx!

_**Inspector when dialogue finds no teams - Issues included**_
![image](https://github.com/lzim/teampsd/assets/7454688/498e20ca-f342-4718-a21d-2f23beab8a9b)

_**Inspector when dialogue finds no teams - I cannot display the full drop down menu in the screenshot**_

![image](https://github.com/lzim/teampsd/assets/7454688/33c92b72-dade-46da-b1fd-06fd940278ea)

**Comment by tejaspesquare** [comment]
Hello @lzim - I find no issue when trying to load teams on Administrator dashboard using my login. Every time it is listing correct teams.

![image](https://github.com/lzim/teampsd/assets/144898781/3f045c7a-c9d1-4e6b-ac86-11e15b4d2e13)

I guess there might be a lag in your case. I would request you to clear cache, delete history & do hard refresh (ctrl+R or ctrl+F5) once & check. If you still encounter issue, then we will need your login credentials to troubleshoot problem.
Thank You!

**Comment by lijenn** [comment]
Discussed 4/7 Sim UI Stand up:
- @tejaspesquare has fixed majority of the console log bugs, except for two.
- @lzim you should see the worlds you are assigned to in your Administrator dashboard now. Please post a screenshot, if you can. Thanks!

**Comment by lijenn** [comment]
@lzim Please let us know if you're still getting this erratic issue for the Admin Dashboard and having trouble finding your teams in your dropdown list in Test-Slow?

**Comment by ljmoody** [comment]
Hi @lzim, please try and test this again in Test-Slow. You should see worlds you're assigned to in your Admin dashboard. Jenn and I have tested and find no issues when searching for teams. Thank you!

If you still experience problems, please:
- take a screenshot of your search results, along with the team you searched for and didn't see. 
- try clearing your cache, delete history & do hard refresh (ctrl+R or ctrl+F5) once & check again.

**Comment by lzim** [comment]
Thanks @ljmoody & @tejaspesquare 
I don't seem to be having the same issue.
Closing this one. Thanks!

**Comment by hnorthcraft** [comment]
2 SP since the error was reported, fixed, and tested relatively quickly once it got prioritized #adjudicate_memo
