### ISSUE TITLE
wk2 2024_04: Bugs in Sim UI TEST discovered during #systems_sme_workflow

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#3148]
**wk2 2024_04 #systems_sme_workflow**
@lzim 
@dlkibbe 

- [x] 1. **The X's in Episode of care for PSY should only be for 3 months not 6 months of weekly psychotherapy.**
![image](https://github.com/lzim/teampsd/assets/7454688/e9c23355-4846-40fa-82e1-3984ac26785c)

- [x] 2. **Replace Team Care in the drop down; not Team (Agg) Care**
![image](https://github.com/lzim/teampsd/assets/7454688/6c1f66a8-011c-484f-b759-0012ba9c6344)

- [x] 3. **Start the Feedback loops like this with no features selected in the drop down.**
![image](https://github.com/lzim/teampsd/assets/7454688/c93ba80d-13e0-4bf1-9950-115b9864556f)

- [x] 4. **Order of the drop down should start with Loop polarities, then Increase and decrease, then Link polarities.** 
![image](https://github.com/lzim/teampsd/assets/7454688/f829727b-8301-4880-a233-3281b9bd68ba)
 
 - [x] 5. **Font needs to be scaled in sync better and without overlap ideally (shown here at 150% which was the best view)**
![image](https://github.com/lzim/teampsd/assets/7454688/deb4c1c0-b119-407f-8a29-5154932a8586)

- [x] 6. **EDIT: "Click any arrow to see the impact of an increase or decrease in that variable on the system dynamics."**
![image](https://github.com/lzim/teampsd/assets/7454688/870802f6-3027-46fe-9404-116e88939d8e)

- [x] 7. **Need to move out of the tutor to the legend: "Click any arrow to see the impact of change."**

**Comment by lijenn** [comment]
Discussed 4/10 Sim UI Stand Up:
- @tejaspesquare work provide Dev effort on the font and scaling issue for system stories. A potential way to address this issue could be to make the system story wider horizontally due to vertical limitations.

**Comment by ljmoody** [comment]
Tracking progress of above items in this card _and_ in:

1. #3029 

2. completed already

3., 4., & 5. #3069 

6. Tutor prompt changes made to all 5 feedback loops via the Tutor Admin dashboard; they now present as:
![image](https://github.com/lzim/teampsd/assets/124643236/246c7f74-ba00-4a11-9e6c-f90645190768)

7. #3069

**Comment by jamesmrollins** [comment]
## 4/21 Sim Ui Update

- System Story window resizing and scale, enlarging text to make more readable still in progress.
- Should be delivered by 4/22 for user testing.

**Comment by tejaspesquare** [comment]
@ljmoody, @lijenn - Can you please verify resize issue that got fixed & available in Test Slow. 

![image](https://github.com/lzim/teampsd/assets/144898781/c9f8a30a-ddd3-4ea5-bbdb-55b080aba9c2)

**Comment by ljmoody** [comment]
Hi @tejaspesquare - I tested the revised CLD today and made [this recording](https://takouba-my.sharepoint.com/:v:/g/personal/lmoody_praxisanalytix_com/EUGahzD_5WdAkjkNc9V7JZIBLoEoikKtj_CxzVZv1xWoJw?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=4fEion) for you to watch. Points I noticed:

- "S" letter on one loop label is hidden under the key.
- Some loop lines are overlapping letters/parts of words.
- It is difficult to get the pop-up window to resize down again once a user enlarges it. 

fyi: @lijenn

**Comment by lijenn** [comment]
Discussed Stand Up 04/24/24:
- @tejaspesquare discussed with Dev team and is working to see if the points noted above are improved as Dev team tests various resolutions.

**Comment by jamesmrollins** [comment]
## 4/28 Sim UI Standup

- [ ] Dynamic sizing on pop-up is set vertically at 600 DPI.  They cannot reduce any further.
- [ ] If the diagram is partially off screen, then a slider will appear to move over to the hidden part of the diagram.
- [ ] The DEV team is going to evaluate the Causal Loop Diagrams and determine if we can modify the design slightly so we can accommodate larger text during zoom AND pull the window in a vertical direction.

**Comment by ljmoody** [comment]
✅ Validated all 7 of Lindsey's reported bugs have been addressed. 
ℹ️ I'm capturing these last two comments on this card and adding to #3069, as finalized sizing of windows and text for CLDs is still being worked on by the Dev team. 

Moving to done column in ZenHub + GitHub bug_tracker. Recommend closing.

**Comment by ljmoody** [comment]
Double checked status of items listed by Lindsey at top of this card. All are complete.
Sizing of text is tracked via #3069. 
Closing this card as complete.

fyi @jamesmrollins
