### ISSUE TITLE
VAPOR Video Coding & Mapping

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#315]
@branscombj and @dlkibbe, 
Thanks for helping code and map the VAPOR stories. 

@lzim will send you the examples of the stories that have already been coded. As you're reviewing the content, keep in mind that we are aiming for the videos to be 2min or less.

- [x] Color code VAPOR stories for 1st, Patient best/worst, Provider best/worst (coding scheme image below)
- [x] VAPOR review and approval
- [ ] Erin will edit videos
- [ ] Map to **Modeling to Learn** 12 session plan pre-post emails

![vapor_coding](https://user-images.githubusercontent.com/31089501/52826798-2e726080-3077-11e9-83c0-bab9ab103349.jpg)

**Comment by lzim** [comment]
@staceypark @dlkibbe @branscombj @erinash

Following our meeting last week, four of five VAPOR board members/alumni have identified or reviewed their preferred "i statement" quotes/clips. We'll have the last bit of feedback on Monday.

I've added (new to GitHub and OSF) @erinash :boom: as a TeamPSD collaborator here. 
And at the **vapor_video_interviews** project on [OSF](https://osf.io/5utya/)

_We'll try to do these in parallel if we can:
- [ ] Erin will edit videos
- [ ] Jane and Debbie, please help map the clips to the _Modeling to Learn_ 12 session plan pre-post emails

**GOAL: Have a final clip -> MTL map for review at the next VAPOR meeting on 5/28.**

**Comment by dlkibbe** [comment]
@lzim Will work on mapping the clips to 12 session plan pre-post emails.

**Comment by staceypark** [comment]
cross-ref #870

**Comment by dlkibbe** [comment]
@lzim @staceypark @branscombj - Adding to this thread based on discussion yesterday:
Identify new content for session 2 VAPOR video - editing required - 3 suggestions below. Full text sent in an email for consideratoin:

02:36-'2:59 | D.C. - Take 2 |

0:4:53-'05:43 | D.C. - Take 1 | 

10:04-'10:45 | D.C. - Take 1 |
