### ISSUE TITLE
2024_06: Remove X-Waiver from Models and Sim UI

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#3150]
## User Story
The DEA X-Waiver requirement has been removed from providers who need to manage opioid use disorder (OUD); therefore, it does not need to be represented in the model.  As a user, I no longer need to allocate appointments to providers who held an X-Waiver.  These can be removed from the model and Sim UI model diagram.  To reduce confusion, any references containing pictures of the model with the X-Waiver dynamics must be removed.

## Acceptance Criteria

- [x] X-Waiver Dynamics are removed from the Vensim Model.
- [x] The Vensim Model continues to provide stable runs.
- [x] The X-Waiver Dynamics are removed from the Model Diagram.
- [x] The X-Waiver entries in the Team Data Table are removed.
- [x] The X-Waiver experimental sliders are removed.
- [x] The X-Waiver reports are removed from the reports dropdown. 
- [x] The X-Waiver variables in the Results Dashboard Control panel are removed.
- [x] The Appointment Slots Allocation sliders are renamed and "OUD" is added to the allocation list.
- [ ] The X-Waiver references in the More Info Modules description are removed.
- [x] The Play Screen and Model Diagram drop down sections under the "MTL Sections" blue bar are updated without X-Waiver Dynamics.

**Comment by jamesmrollins** [comment]
@tejaspesquare 

## MM Model Diagram Changes

### Current State

![image](https://github.com/lzim/teampsd/assets/30132017/2f76696d-20ef-4bf7-a402-680409637c35)

### Future State

- [ ] 1. Add new widget as shown.
- [ ] 2. Revise table as shown.
- [ ] 3. Revise Experiment Slider as shown.

![image](https://github.com/lzim/teampsd/assets/30132017/e1b48b03-ec2e-4425-95f6-f23021b76e35)

**Comment by jamesmrollins** [comment]
Tasks for @ljmoody and/or me

## More Info Changes

- [ ] 1. Remove the highlighted below.

![image](https://github.com/lzim/teampsd/assets/30132017/9d42f65e-fc38-4e38-9926-16d84f7f8863)

- [ ] 2. Rename the following to "Team Care" and "Team Flow" respectively.

![image](https://github.com/lzim/teampsd/assets/30132017/f9b4321e-9098-461b-9037-a95515875045)

- [ ] 3. When the dev team has completed updates to model diagram, update the following illustrations.

![image](https://github.com/lzim/teampsd/assets/30132017/94628c79-34f3-4213-bae3-bb1aeb3db356)

![image](https://github.com/lzim/teampsd/assets/30132017/07a782d0-02c5-4f56-a798-c67ce747eafd)

- [ ] 4. Update model information file on Demo website.

![image](https://github.com/lzim/teampsd/assets/30132017/0665aa6f-630b-44c7-81b3-1d8236ddafe7)

## Issues Related to 3.7 Deployment but Not Decided

- [ ] @lzim will we be updating the mtl.how/demo website to reflect the 3.7 user interface, or the 3.0 interface?
  - [ ] Use 3.0
  - [ ] Use 3.7   
- [ ] If 3.7 then,
  - [ ] Update GIF sliders to illustrate the new functionality (All model view, System Stories, Decision Meters)
  - [ ] Deploy 3.7 to DEMO website to enable user demo with 3.7 interface.
- [ ] If 3.0 then, 
  - [ ] Update GIF sliders to illustrate Team Care without the "(AGG)" in the label.

**Comment by lijenn** [comment]
Discussed Stand Up 04/24/24:
- @tejaspesquare is reviewing the requirements and preparing the queries and looking into based on API response based on current outputs from current developed. Will update @jamesmrollins once that is ready.

**Comment by jamesmrollins** [comment]
## 4/28 Sim UI Standup

- [ ] DEV Team is 50-60% complete with page updates.
- [ ] James will complete testing and variable mapping instructions by COB 4/29.
- [ ] James will push new model to lzim/mtl/dev branch and test in DEV Sim UI project. Then push DEV to Test Slow and test again.

**Comment by jamesmrollins** [comment]
@tejaspesquare  
FYI @lijenn @ljmoody 

- I have uploaded the model file package to lzim/mtl/tree/dev/blue/mtl3.0_models. 
- Let me know when user interface changes are complete and I will test.

**Comment by jamesmrollins** [comment]
@tejaspesquare 

## New Variable Mapping

![image](https://github.com/lzim/teampsd/assets/30132017/cec55a25-ef46-4e30-beb9-c00545c33ae1)

**Comment by tejaspesquare** [comment]
@jamesmrollins - Following amendment has been applied on MM model & available for your verification on SIM UI - Dev instance.
1. Add new widget as shown.
2. Revise table as shown.
3. Revise Experiment Slider as shown.

![image](https://github.com/lzim/teampsd/assets/144898781/ab378801-443e-4310-b3eb-3aef845ea15d)

![image](https://github.com/lzim/teampsd/assets/144898781/7254082b-c788-46eb-b87c-bf8d974f436c)

![image](https://github.com/lzim/teampsd/assets/144898781/68d114b5-03ec-4097-87b9-8e3104f2aaa3)

**Control Panel Current Experiment Values Window and Chart Drop Down Selections**
![image](https://github.com/lzim/teampsd/assets/144898781/deeae28a-07fc-467c-abd1-9b5d43c912fa)

**Comment by jamesmrollins** [comment]
@tejaspesquare 

Please change the following in **CC and MM Models**.

- [ ] This Learning Model is not correct as shown (see highlight below).  Should be "Learning Mode (0 = EPRVI; 1 = NPSR)"

![image](https://github.com/lzim/teampsd/assets/30132017/38ca14e3-2c04-4a4a-8f88-fbcfcf3ba686)

- [ ] Please move the Appointment Slots Allocation a little closer to "Appointments for Existing Patients" and more level with "Appointment Slots Reserved for New Patients" widget.

![image](https://github.com/lzim/teampsd/assets/30132017/0dc66f82-2814-4f94-ac8d-d9fc4a9353d2)
