### ISSUE TITLE
2024_wk1_may: BUG: CI/CD actions between lzim/mtl, jamesmrollins/sim_ui and Epicenter not working

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#3156]
## What Should Happen

When the user pushes a new model files (.vmfx, mdl, .xmile) to lzim/mtl and CI/CD action fires that creates an SD-Doc file, updates in lzim/mtl directory and moves the model files through the jamesmrollins/sim_ui and jamesmrollins/mtl_demo repositories to Epicenter. 

## What happens 

The action fires, with deprecation errors, and creates the SD-Doic file; however, the files do not migrate all the way to Epicenter and have to be downloaded and pushed manually. 

## Hypothesis

The action to Forio API that loads the files into Epicenter may be malfunctioning.

**Comment by hnorthcraft** [comment]
@lijenn I don't see any other work beside the initial comment? do you have thoughts on SP estimate?

**Comment by lijenn** [comment]
@hnorthcraft 1 SP since it looks like this was for documentation purposes. 
We also made the DECISION to have all Forio Epicenter files and CI/CD workflows flow directly to lzim repos only, so no work remains on this card.

#adjudicate_memo
