### ISSUE TITLE
2024_05 mtl.how/facilitation README.md - Update the BrightCove Links for the MTL 1.7 Release Videos

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#3157]
**Discussed wk1 2024_05 at #support_workflow (on #systems_sme_workflow) channel**

- [x] @ljmoody to update the _MTL 1.7_ release Brightcove video links on the _MTL 3.0 External Implementation Facilitation_ repository to reflect the links in this [mtl_1.7_external_implementation_facilitation_brightcover.xlsx](https://dvagov.sharepoint.com/:x:/r/sites/modeling_to_learn/Shared%20Documents/General/mtl_1.7_videos/mtl_1.7_external_implementation_facilitation_brightcove.xlsx?d=we788cf4b2590490b85bc777f8be55ffc&csf=1&web=1&e=pSQDha) file on Teams - README.md at https://mtl.how/facilitation 

- [x] Remove the TMS links - they are no longer valid.

Thank you! 🚀

**Comment by ljmoody** [comment]
@lzim, tasks for this card are complete and I verified all updated video links map to the correct session and module. I'm moving to the Done column; recommend closing this card. 

A screenshot of the updated Readme file:
![image](https://github.com/lzim/teampsd/assets/124643236/2b85194b-bb7d-4863-b074-c15463193023)

**Comment by lzim** [comment]
Great @ljmoody - Let's close it then. Thanks!
