### ISSUE TITLE
2024_06_epic: Bug: Run IDs are not preserved 

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#3159]
## What happens

1. When user navigates to Dynamic Dashboard, selects a Team Data File and clicks "Go" the models all run and return base case values.
2. When the user navigates to the model and runs the model, values are returned to the individual model.
3. When the user navigates back to the Dynamic Dashboard, the Run IDs are lost and the models are reset to zero.
4. IF the user logs out from the Dynamic Dashboard (DD) after the Team Data is loaded and models set to time zero, then the models are reset.

## What should happen

1. When the user performs steps above, the Run ID should be preserved for all models.
2. With number 2 above, where an individual model is run, and the user returns to the DD, then the stock values should be reflected in the DD.
3. An individual model can be reset and rerun from the model level, with the current Team Data, without disrupting the remaining models.
4. If the user reloads a Team Data file, then all models are reset and run to zero.

## Next Steps

1. Need verify what commands are being issued to the back end when user navigates between models.
2. Check Play button associated code that may be issuing a re-run or reset command.
3. Modify play button functionality to not reset if the model has been mounted or run.
4. Reset only when Reset button is clicked.
5. Runs can be restored using, POST .../api/v3/va/va-psd-dev/run/world/<worldkey>

**Comment by jamesmrollins** [comment]
@lzim @lijenn @ljmoody @dlkibbe @dlounsbu 

## 5/29 Demo Call

- These reset issues are resolved in Test Slow.

**Comment by lzim** [comment]
**wk2 2024_06 - #sim_ui_workflow**
@jamesmrollins 
@ljmoody 
@lijenn 
- _Is this all set in PROD now too?_ - We need to prep https://github.com/lzim/research/issues/572 this week.
Let me know. Thanks!

**Comment by ljmoody** [comment]
@lzim, my understanding is that yes, this issue is resolved and the fix was migrated to PROD. 
As such, I'm closing this card.
