### ISSUE TITLE
2024_wk4_may: BUG: Teams created in the Admin DB - settings is not showing in the Teams dropdown

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#3161]
## What Happened

1. When user navigates to the Settings Menu and creates a new team in the Facility Team Setup, the team is not reflected in the Team dropdown in the Admin DB.
2. The query is not operating correctly.

## What Should Happen

The teams listed in the Facility Team Setup, should be listed in the "Select Team" dropdown.

## Next Steps

@tejaspesquare will investigate the API call and answer: 
- What is the call with parameters for the Facility Team Setup
- What is the call with parameters for the Select Team dropdown. 
- Use the working call in both cases.

## Resolve Estimate: 5/25 (Revision 1)

**Comment by jamesmrollins** [comment]
@dberkman :  We are still not able to resolve why these calls do not return the same values for team listings for legacy groups. When the tester creates a new group from the Team Setup dialogue, it lists in the Select Team dropdown with no problems.  For example, the groups below worked when setup in the Team Setup dialogue:

_On the Dev Project_
local_04_feb_14

_On the Test-slow Project_
qa_test_29march_0240

## API Call from Settings dialogue in Admin Dashboard

![image](https://github.com/lzim/teampsd/assets/30132017/4fc2562f-eb9a-43e4-9cde-3db661456663)

Method: GET
API:
http://localhost:8000/V2ForioAPI/member/local/?userId=000001703a728146b8528a5995911198ff5b
Body:
userId: 000001703a728146b8528a5995911198ff5b
Response:
[
    {
        "type": "local",
        "created": "2024-03-12T14:49:35Z",
        "lastModified": "2024-03-12T14:49:35Z",
        "startDate": "2024-03-12T00:00:00Z",
        "id": "0000018e3322b1ad0ad0ad253b3500659675",
        "name": "mar_12_team_names_test_team",
        "account": "va",
        "project": "va-psd-test",
        "organization": "mar_12_team_names_test_team",
        "event": "Team",
        "price": 0,
        "runCount": 0,
        "userCount": 9,
        "members": [
            {
                "added": "2024-03-12T14:49:35Z",
                "memberType": "group",
                "role": "standard",
                "groupId": "0000018e3322b1ad0ad0ad253b3500659675",
                "userId": "000001703a728146b8528a5995911198ff5b",
                "userName": "jrollins@praxisanalytix.com",
                "firstName": "James",
                "lastName": "Rollins",
                "active": true,
                "id": 3901982,
                "userRow": 568229
            }
        ],
        "groupId": "0000018e3322b1ad0ad0ad253b3500659675"
    },
    {
        "type": "local",
        "created": "2024-03-14T20:17:31Z",
        "lastModified": "2024-03-14T20:17:31Z",
        "startDate": "2024-03-14T00:00:00Z",
        "id": "0000018e3e92e0358218328e70bf0065bba6",
        "name": "3080_testing_team",
        "account": "va",
        "project": "va-psd-test",
        "organization": "3080_testing_team",
        "event": "Team",
        "price": 0,
        "runCount": 40,
        "userCount": 10,
        "members": [
            {
                "added": "2024-03-14T20:17:32Z",
                "memberType": "group",
                "role": "facilitator",
                "groupId": "0000018e3e92e0358218328e70bf0065bba6",
                "userId": "000001703a728146b8528a5995911198ff5b",
                "userName": "jrollins@praxisanalytix.com",
                "firstName": "James",
                "lastName": "Rollins",
                "active": true,
                "id": 3911567,
                "userRow": 568229
            }
        ],
        "groupId": "0000018e3e92e0358218328e70bf0065bba6"
    },

## API Call from Select Team dropdown in Admin Dashboard

![image](https://github.com/lzim/teampsd/assets/30132017/9da2a102-a428-40db-ae1c-27a148401163)

**1. First part of call**

API :https://forio.com/v2/member/local/0000018e37c775c58218328e70bf006544d5
Method: Get
Authorization : Bearer + Token
Response:
{
    "type": "local",
    "created": "2024-03-13T12:53:36Z",
    "lastModified": "2024-03-13T12:53:36Z",
    "startDate": "2024-03-13T00:00:00Z",
    "id": "0000018e37c775c58218328e70bf006544d5",
    "name": "test_13march_0623_team",
    "account": "va",
    "project": "va-psd-dev",
    "organization": "test_13March_0623_team",
    "event": "Team",
    "price": 0,
    "runCount": 0,
    "userCount": 5,
    "members": [
        {
            "added": "2024-04-29T09:16:32Z",
            "memberType": "group",
            "role": "facilitator",
            "groupId": "0000018e37c775c58218328e70bf006544d5",
            "userId": "0000018b3d4d3c0766e8f40e19340060632d",
            "userName": "devrinkeshp@outlook.com",
            "firstName": "dev r",
            "active": true,
            "id": 4029051,
            "userRow": 2155218
        },
        {
            "added": "2024-03-13T12:53:37Z",
            "memberType": "group",
            "role": "facilitator",
            "groupId": "0000018e37c775c58218328e70bf006544d5",
            "userId": "0000016395d53f73d8e441bb18df05f76c52",
            "userName": "devuser7",
            "lastName": "Dev User7",
            "active": true,
            "id": 3906023,
            "userRow": 29427
        },
        {
            "added": "2024-03-13T12:53:37Z",
            "memberType": "group",
            "role": "standard",
            "groupId": "0000018e37c775c58218328e70bf006544d5",
            "userId": "0000017543409bce86d83cd1dc236288531f",
            "userName": "debra.kibbe@va.gov",
            "firstName": "",
            "lastName": "Debra Kibbe",
            "active": true,
            "id": 3906017,
            "userRow": 767693
        },
        {
            "added": "2024-03-13T12:53:37Z",
            "memberType": "group",
            "role": "facilitator",
            "groupId": "0000018e37c775c58218328e70bf006544d5",
            "userId": "000001703a728146b8528a5995911198ff5b",
            "userName": "jrollins@praxisanalytix.com",
            "firstName": "James",
            "lastName": "Rollins",
            "active": true,
            "id": 3906020,
            "userRow": 568229
        },
        {
            "added": "2024-04-26T09:03:53Z",
            "memberType": "group",
            "role": "facilitator",
            "groupId": "0000018e37c775c58218328e70bf006544d5",
            "userId": "000001685f87d358b7cd3676ca9e35eb25ed",
            "userName": "hirenp",
            "lastName": "Hiren Patel",
            "active": true,
            "id": 4024193,
            "userRow": 326522
        }
    ],
    "groupId": "0000018e37c775c58218328e70bf006544d5"
}
**2. Second part of the call**

Method: Get
API:http://localhost:8000/V3ForioAPI/world/test_13march_0658_team/episode-cc
Response:
[
    {
        "personae": [
            {
                "role": "Team Lead",
                "minimum": 0
            },
            {
                "role": "Player",
                "minimum": 0
            }
        ],
        "assignments": [
            {
                "user": {
                    "detail": {
                        "lastUpdated": "2024-04-23T17:22:38Z",
                        "lastLogin": "2024-04-23T17:22:38Z",
                        "modality": "none",
                        "created": "2020-10-19T23:52:14Z",
                        "givenName": "",
                        "familyName": "Debra Kibbe",
                        "countdown": {
                            "last": "2024-04-23T17:22:38Z",
                            "count": 0
                        },
                        "active": true,
                        "handle": "debra.kibbe@va.gov",
                        "email": "debra.kibbe@va.gov",
                        "mfaDetail": {
                            "mfaMethodology": "NONE"
                        },
                        "objectType": "native"
                    },
                    "lastUpdated": "2024-03-13T06:14:16Z",
                    "userKey": "0000017543409bce86d83cd1dc236288534c",
                    "created": "2020-10-19T23:52:14Z",
                    "displayName": " ",
                    "userId": 767693
                },
                "role": "Team Lead"
            }
        ],
        "orbitKey": "0000018e37ea0d718218328e70bf0065f4d9",
        "lastUpdated": "2024-03-13T13:28:08Z",
        "worldKey": "0000018e37d8bf0ce6feda995af700657792",
        "created": "2024-03-13T13:28:08Z",
        "orbitType": "episode",
        "name": "World001",
        "allowChannel": false
    }
]

**Comment by jamesmrollins** [comment]
@tejaspesquare  the below is from David B.

## Observations from code

1. The first call is v2 for all groups for a user, across Epicenter.
2. The second call is v2 for the users in a single group.
3. They do very different things, which is unsurprising as they are two different URLs. The last call is v3 for all worlds within an episode.

## Recommendation

If you want the data from the first call to also appear where the second call is being used, I would say use the first call in both places.

**Comment by jamesmrollins** [comment]
@davidberkman

## The Problem
- The second API for the Select Team drops down must return an "episode" because it is required for Home screen. I'm not positive, but "episode" is required for continuity?
- When the API requests the "episode" it returns a 404 (not found) error.
- The teams are set up in the Team Setup dialogue, the episode is created.  However, with legacy groups, the episode was not created.  The reason is unknown (is episode a feature of v3 that was not a part of v2?).

## The Solution
- Force create an episode with all legacy groups.

**Comment by jamesmrollins** [comment]
## 5/27 Stand Up

- Forio has made code recommendations to restructure the query to pull domain IDs.
- Need to test and ensure functionality is consistent is all places team drop down is used.
- Estimate 5 hours troubleshooting/coding time.
- Not available until tomorrow 5/26

**Comment by lzim** [comment]
Thanks for the estimate of availability on 05/28 @jamesmrollins 💯 
**_Ready for #systems_sme_workflow or someone else?_**

**Comment by ljmoody** [comment]
fyi @jamesmrollins & @lzim:
Tested 6/3/24 in PROD instance and verified ✅ teams created in Settings>Facility Team Setup _are_ showing in the Aministrator Dashboard Select Team dropdown menu - screenshots below. Closing this card as complete.

![image](https://github.com/lzim/teampsd/assets/124643236/8e6f5a09-c16b-4b1a-9db4-f8fc4705e231)

![image](https://github.com/lzim/teampsd/assets/124643236/b8cfeedb-3c02-430f-beb5-c4edc9e1b6be)

**Comment by hnorthcraft** [comment]
2 SP since the error was reported, fixed, and tested relatively quickly once it got prioritized
