### ISSUE TITLE
2024_06: BUG:  Resolve DEV instance 400 and 404 errors for bad request and assets not found in Administrator Dashboard page

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#3162]
## Resovle the following errors

![image](https://github.com/lzim/teampsd/assets/30132017/63a149b1-f987-447d-a470-fe170b7d5787)

**Comment by lzim** [comment]
**wk5 2024_05 #systems_sme_workflow**
@lzim
@dlkibbe 

@jamesmrollins - Please advise on estimated timeline for resolution for **#systems_sme_workflow**
Thanks! 

FYI: @dlounsbu
