### ISSUE TITLE
2024_06: BUG: Resolve authorization failures

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#3163]
Resolve the following authorization failure.  The current auth token is not valid for the desired group.  Use the authentication PATCH from the encyclopedia:

- PATCH .../api/v3/va/va-psd-dev/authentication {"objectType":"user", "groupKey":"<group key>"}
- Store the auth token using local storage or a cookie.
- David B. will try to arrange John (Forio DEV) to discuss the local storage of authorization token on Monday night.

![image](https://github.com/lzim/teampsd/assets/30132017/3b57d1a1-f1d9-40ee-a759-2c28fc470ee4)

##

**Comment by jamesmrollins** [comment]
5/25 Standup

- Current list of 400 series errors below.
- Authorization error caused by the code looking for a Team Data file that is not identified by the user at this stage of the workflow.  
- Continuing to work on resolving these issues:

![image](https://github.com/lzim/teampsd/assets/30132017/77a24073-ecc6-4b8b-8f8c-49474afdda80)

**Comment by lzim** [comment]
**wk5 2024_05 #systems_sme_workflow**
@lzim 
@dlkibbe 

@jamesmrollins - Unclear how this impacts our prep this AM. 
Please advise **#systems_sme_workflow** on the card. Thanks!

FYI: @dlounsbu

**Comment by jamesmrollins** [comment]
@tejaspesquare 

## Persistent 400 Error, Please Resolve

![image](https://github.com/lzim/teampsd/assets/30132017/b28d20ad-e928-4245-b1b3-5b3b0ae5d9a2)

**Comment by jamesmrollins** [comment]
FYI
@lzim @dlkibbe @lijenn @dlounsbu @ljmoody 

## 5/29 Demo Call
- **(SME Key Information)** These errors are not having an impact on functionality.
- We suspect these are issues with the API call to the backend, but it is unclear what assets the API is trying to return (they are not human readable API returns).
- Issue is returned to Forio for investigation

**Comment by lzim** [comment]
@tejaspesquare & **#systems_sme_workflow**

I'm trying to run down whether these have been resolved as we need to move on to prepping our _MTL 3.7 Blue_ consults in PROD. Please provide an update. Thanks!

FYI: @jamesmrollins @lijenn @ljmoody

**Comment by tejaspesquare** [comment]
Hello @lzim,

yes, the matter has been successfully resolved. It pertains to the specific user and concerns the user's profile picture. Each user must upload a profile picture using an Avatar link.

Before Avtar
![image](https://github.com/lzim/teampsd/assets/144898781/240fef4e-368d-410c-9f66-c6c14da0b361)

After Avtar
![image](https://github.com/lzim/teampsd/assets/144898781/01730c03-9eb0-4a41-90f3-2338cf157d28)

FYI- @jamesmrollins , @ljmoody , @lijenn
