### ISSUE TITLE
2024_06_epic: BUG: PSY Model Error Code 500 Message

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#3164]
When the PSY model is run, we receive the following error:

[6:01 AM] Tejas Patel (Unverified)
PSY Model retrieveFromWorld, Error Code: 500 Message: The timeout(10) seconds was exceeded while waiting for a response from command(com.forio.epicenter.grid.transformer.worker.uplink.v1.command.StateCommand@20cb3984)

![image](https://github.com/lzim/teampsd/assets/30132017/af5f1689-11fc-4dc7-8ab2-85a22ebdee48)

**Comment by jamesmrollins** [comment]
## 5/27 Stand Up

- The url and body of the call that errored, which are very very useful, and were available in the dev tools when this error cropped up, and could have been copied in text from there, are missing. 
- @tejaspesquare indicated when the error occurs the next time, he will ensure to capture the above information.

**Comment by lzim** [comment]
**wk5 2025_05 #systems_sme_workflow**
@lzim 
@dlkibbe 

@jamesmrollins - Your post from last night is not clear to us in #sytstems_sme_workflow
Please update card for #systems_sme_workflow user interpretation. Thanks!

FYI: @dlounsbu
