### ISSUE TITLE
2024_06_epic #story_b: create MTL 3.7 training agenda / outline

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3167]
## AC:
- [ ] objectives
- [ ] training outline

**Ex.** 
- I need to set up (get data, export, import to Sim UI) and prep for a consult.
- I need to...

### Desired content (solicited from Debbie & David):
- [ ] Overview of the new release - information flow from data UI to dashboard -- outline all new features
- [ ] ~Review of getting data from data UI to sim UI (need the repetition and practice for this)~ -> **DECISION** at 5/30/24 support_workflow meeting: "We will NOT be further documenting the Data UI in the [https://mtl.how/2024_roadmap](https://mtl.how/2024_roadmap) until after all the consults are closed for the **#r01_2018 #iir_2020**"
- [ ] What we have to fill in vs. what will be automatically populated
- [ ] Steps to / process for filling in the numbers that we have to fill in (what do we have to do to ensure the numbers we populate are correct)
- [ ] If there are typical ranges or patterns we should see in the dashboard or numbers what would be considered "abnormal"

**Comment by lzim** [comment]
@ljmoody 
- I'm not sure that I understand what this card covers. _Should we close it?_
- However, this Slidell Card, which we completed last month shows the checklist of the activities for completing a consult https://github.com/lzim/research/issues/602

This is also what is covered in the _MTL 3.7 Consult Workflow Issue Template_
available here: https://github.com/lzim/research/issues/new/choose

![image](https://github.com/lzim/teampsd/assets/7454688/d97475ab-2330-4ceb-b590-6fa8645737a6)

**Comment by ljmoody** [comment]
Hi @lzim, this card is meant for the _MTL_ 3.7 training we were to give Debbie/David (vs consult completion). The checkboxes above of "Desired content (solicited from Debbie & David)" capture what they've asked to have reviewed via training. Jenn and I have wondered if this card or official training is necessary - _do you believe it is?_

**Comment by lzim** [comment]
Thanks for clarifying. No. David and Debbie are learning by doing. 

We can close this card.
