### ISSUE TITLE
2024_08: develop content for MTL Consult Manual 

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3168]
**FYI: _QA/QC CHECKS_ are being tracked in #3093**

## AC:
- [ ] Create readme that links to videos using thumbnails and links to MTL 3.7 Consult Manual & update to reflect 3.7 release - see 5/22/24 [support_workgroup meeting recording](https://dvagov.sharepoint.com/sites/teampsd_vha/_layouts/15/stream.aspx?id=%2Fsites%2Fteampsd%5Fvha%2FShared%20Documents%2Fsupport%5Fworkgroup%2FRecordings%2FSupport%20Workgroup%20Meeting%2D20240522%5F120208%2DMeeting%20Recording%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2Eae38637d%2D552f%2D4a27%2D86b3%2D678f717080aa):
![image](https://github.com/lzim/teampsd/assets/124643236/ff01c11b-ded4-4aa3-a8dd-4b1f5e207664) 
- [x] Review other past chapters & content and determine if content is: relevant, needed, should be updated, remove, etc.
- [ ] Update to reflect data (red) or modeling (blue) consultation
- [ ] Include information found in #2851 re: binning of encounters
- [ ] ~?Update see/say guides~
- [x] Update Sim UI cheatsheet (Laura)
  - [x] add new ref/link to cheatsheet in Technical Documentation section
- [x] Update Data UI cheatsheet (Jenn)
  - [x] add new ref/link to cheatsheet in Technical Documentation section
- [ ] requested by Debbie & David: 
  - [ ] Red site prep checklist
  - [ ] Blue site prep checklist  

### Assets Required/Developed
- [x] **Thumbnails** > Team PSD repo > resources > mtl_consult_thumbnails
- [ ] **_MTL_ Use Case Videos: _Why & How of Modeling to Learn_ Consults** in #ilead_workflow
- [ ] **Bookdown _MTL 3.7 Consult_

## Chapter 3 Technical Documentation 
- [ ] 03.01 _MTL 3.7 Red_ - This is for internal Veterans Health Administration staff.
- [ ] 03.02 _MTL 3.7 Blue_ - This is for internal Veterans Health Administration consults.
- [ ] 03.03 _MTL 3.7 Demo_ - This is for the public.

### Functional Requirements - Public-facing manual (not a lot of internal links on GitHub; link to within VA via Teams)
- [x] 1. Create a README.md that links to the videos using the Thumbnails and links to the _MTL 3.7 Consult Manual_
- [x] 2. Create the Markdown text of the Chap 1 & Chap 2 content from the associated videos 
- [x] 3. Copied text #[Approved #ilead_workflows ](https://dvagov.sharepoint.com/:f:/r/sites/teampsd_vha/Shared%20Documents/ilead_workflow/ILEAD%20Approved%20Videos?csf=1&web=1&e=rK0O5Y)

## 1. Why place a _Modeling to Learn 3.7_ Consult? (10 chapters/videos)
- [x] **01. How might _Modeling to Learn_ help?**
  - [x] Brightcove video linked, opens in new window
- [x] **04. How can a _Modeling to Learn_ consult help?**
  - [x] Brightcove video linked, opens in new window
- [x] **02. What gets in the way of meeting patients' needs?**
  - [x] Brightcove video linked, opens in new window
- [x] **21. If we keep making the same care decisions, will things get better or worse?**
  - [ ] Brightcove video linked, opens in new window
- [x] **05. Why is _Modeling to Learn_ useful when we have critical staffing and hiring needs?** 
  - [x] Brightcove video linked, opens in new window
- [x] **13. Why is the _MTL Red_ Data User Interface useful?**
  - [x] Brightcove video linked, opens in new window
- [x] **15. Why is the _MTL Blue_ Simulation User Interface useful?**
  - [x] Brightcove video linked, opens in new window
- [x] **16. Why is applied systems thinking more likely to help us avoid costly mistakes?**
  - [x] Brightcove video linked, opens in new window
- [x] **17. Why is _Modeling to Learn_ able to provide new insights?**
  - [ ] Brightcove video linked, opens in new window
- [x] **18. Why does _Modeling to Learn_ emphasize flows through care over time?**
  - [ ] Brightcove video linked, opens in new window

## 2. How can _Modeling to Learn_ help?
- [x] **03. How can we get more patients better without more hours in the day?**
  - [x] Brightcove video linked, opens in new window
- [x] **06. How does _Modeling to Learn_ benefit Substance Use Disorder or SUD programs?**
  - [x] Brightcove video linked, opens in new window
- [x] **07. How does _Modeling to Learn_ benefit PTSD Clinical Teams or PCTs?**
  - [x] Brightcove video linked, opens in new window
- [x] **08. How does _Modeling to Learn_ benefit Behavioral Health Integration Program or BHIP teams?**
  - [x] Brightcove video linked, opens in new window
- [x] **09. How does _Modeling to Learn_ support stepped care?**
  - [x] Brightcove video linked, opens in new window
- [x] **10. How does measurement based care detect patient improvement or risk?*
  - [x] Brightcove video linked, opens in new window
- [x] **12. How can we improve SAIL with _Modeling to Learn_?**
  - [x] Brightcove video linked, opens in new window
- [x] **14. How do five key variables drive care quality?**
  - [x] Brightcove video linked, opens in new window
- [x] **19. How does _Modeling to Learn_ help improve medication management?**
  - [ ] Brightcove video linked, opens in new window
- [x] **20. How does _Modeling to Learn_ help improve psychotherapy?**
  - [ ] Brightcove video linked, opens in new window
- [x] **22. How does our appointment backlog extend the weeks between visits?**
  - [ ] Brightcove video linked, opens in new window
- [x] **23. How can we better balance needs of new and existing patients?**
  - [x] Brightcove video linked, opens in new window
- [x] **24. How can we leverage the feedback, rates, and volume of our local care system?**
  - [x] Brightcove video linked, opens in new window
- [x] **11. What key drivers of higher care quality improve recovery and prevent suicide?**
  - [x] Brightcove video linked, opens in new window

**Comment by ljmoody** [comment]
@lzim and @AnnHier, please let me know when evergreen video links (direct to Brightcove) are in place for the _MTL 3.7_ why and how videos. Once I have those, I can make direct links from the Readme thumbnails. Thanks!

**Comment by AnnHier** [comment]
Thank you and will do - they're still being reviewed and tweaked right now!

Ann Hier Brown
Executive Video Producer
VHA Institute for Learning, Education and Development
Phone:   314-894-6498
Personal Cell: 314-691-3372

To learn more about ILEAD, click here<https://dvagov.sharepoint.com/sites/VHAILEAD/>
For customer assistance, visit the ILEAD Help Center<https://dvagov.sharepoint.com/sites/VHAEESAPPS1/Help%20Center/Ticket.aspx#/>
***@***.***

From: Laura M ***@***.***>
Sent: Friday, May 31, 2024 4:39 PM
To: lzim/teampsd ***@***.***>
Cc: Brown (Hier), Ann B. ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [lzim/teampsd] wk3 2024_jun_epic #story_b: content finalization for MTL Consult Manual (Issue #3168)


@lzim<https://github.com/lzim> and @AnnHier<https://github.com/AnnHier>, please let me know when evergreen video links (direct to Brightcove) are in place for the MTL 3.7 why and how videos. Once I have those, I can make direct links from the Readme thumbnails. Thanks!

-

**Comment by ljmoody** [comment]
@lzim, I've added the 8 approved video transcriptions to Chap 1 & 2 drafts (each on separate feature branches). 
- Chap 1 is in feature-gh-pages_mtl_3.7_index_updates, see index.Rmd 
- Chap 2 is in feature-gh-pages_mtl_3.7_2.0_updates, see 2.0_how_to_use_mtl.md 

While you mentioned only wanting the time stamps removed and simple copy/paste, a bit of proofing was needed to keep consistency and reduce confusion (for example, changing "be hip" to "BHIP"). I made the following changes (not a comprehensive list, but the most common) and plan to do the same with the remaining video transcriptions once I have access--unless I hear differently from you.

- proof transcription by replaying video and checking transcription accuracy
- veteran > Veteran
- Lindsay > Lindsey
- Modeling to Learn / modeling to Learn / model to learn > _Modeling to Learn_
- mtl / MTL > _MTL_
- be hip > BHIP

**Comment by lzim** [comment]
This is great @ljmoody! 

_Will you please add story point estimates for this work and cross off the tasks on the task list that are completed vs. those that still remain?_

Thanks again!

**Comment by ljmoody** [comment]
@lzim, how would you like the graphic below to be revised to reflect the pivot to consult? 
- [ ] My team had a site consult.
- [ ] My teams is working with a consultant.
- [ ] another option...

![image](https://github.com/lzim/teampsd/assets/124643236/45006850-165c-4f11-8ea0-334761a69717)

**Comment by lzim** [comment]
**wk3 2024_07 #support_workflow**
@ljmoody 

**There are no text edits to the second batch of videos.**
- [x] I moved six of the videos to the APPROVED folder.
- [x] The two videos "MTL Red" and MTL Blue" are in EDIT and need pop-up messages for the URLs, but there will be no change for using the transcriptions for the Why/How use cases in the manual at https://mtl.how/manual ⁠

The transcripts for batch two can be added to the manual. Thanks!

**Comment by AnnHier** [comment]
Thanks, Lindsey!

That is helpful – I have a couple clarification questions but those can wait until our call tomorrow – hope you’re having a great week!

Ann Hier Brown
Executive Video Producer
VHA Institute for Learning, Education and Development
Phone:   314-894-6498
Personal Cell: 314-691-3372

To learn more about ILEAD, click here<https://dvagov.sharepoint.com/sites/VHAILEAD/>
For customer assistance, visit the ILEAD Help Center<https://dvagov.sharepoint.com/sites/VHAEESAPPS1/Help%20Center/Ticket.aspx#/>
***@***.***

From: Lindsey Zimmerman ***@***.***>
Sent: Friday, July 12, 2024 5:03 PM
To: lzim/teampsd ***@***.***>
Cc: Brown (Hier), Ann B. ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [lzim/teampsd] 2024_07_epic #story_b: develop content for MTL Consult Manual (Issue #3168)


wk3 2024_07 #support_workflow
@ljmoody<https://github.com/ljmoody>

There are no text edits to the second batch of videos.

  *   [X] I moved six of the videos to the APPROVED folder.
  *   [X] The two videos "MTL Red" and MTL Blue" are in EDIT and need pop-up messages for the URLs, but there will be no change for using the transcriptions for the Why/How use cases in the manual at https://mtl.how/manual ⁠

The transcripts for batch two can be added to the manual. Thanks!

**Comment by ljmoody** [comment]
## 7/17 Support_workgroup meeting:

**DECISIONs:** Since https://mtl.how/facilitate **is archived**
https://mtl.how/facilitate_workflow
**and** 
**#ilead_workflow** will have 16 Brightcove links available **wk4 2024_07** 

- Should have all 24 videos by **wk1 2024_08**

**__MTL 3.7_ Consult_** - Release the documentation! :)
 
01. _MTL 3.7_ Consult README.md at https://mtl.how
 
02. _MTL 3.7_ Consult Manual https://mtl.how/manual to reflect 16  consult use cases.

- Text only for now is okay.

**Comment by lijenn** [comment]
Discussed 7/19 Team Praxis Call:
- [ ] @jamesmrollins dispositioned this to wk5 when @ljmoody is back.
- [ ] @ljmoody to assign estimates.

**Comment by lzim** [comment]
**wk4 2024_07 #support_workflow & #ilead_workflow**
@lijenn 
@ljmoody 
@lzim
- See email with Ann & Greg in mtl.help@va.gov 

- [x] 1. 24 videos are complete without text changes and can be transcribed as the _MTL 3.7 Consult Manual Why/how (& What if)_ use cases.
- [ ] 2. 17 videos are APPROVED and Greg & Ann are posting them to Brightcove with enduring public-accessible links and the thumbnails.
- [ ] 3. 5 videos in the EDITED folder require that Greg add the pop-up graphics
- [ ] 4. 1 "new insights" video needs graphics that reflect our **pending Sankey/Scaled Flows in TEST**

_**#sim_ui_workflow** when do we have an example Team Care Flow, Medication Management, or PSY Flows that can be included as a graphic in #4._

0:23 Stock Rectangle
0:33 Flow In/Out
0:39 Rate Dial
[Why is Modeling to Learn able to provide new insights about where Veterans get stuck or drop out of care__17.mp4 (sharepoint.com)](https://dvagov.sharepoint.com/sites/teampsd_vha/_layouts/15/stream.aspx?id=%2fsites%2fteampsd_vha%2fShared+Documents%2filead_workflow%2fILEAD+Edit+Review%2fWhy+is+Modeling+to+Learn+able+to+provide+new+insights+about+where+Veterans+get+stuck+or+drop+out+of+care__17.mp4&referrer=StreamWebApp.Web&referrerScenario=AddressBarCopied.view.7afdac00-afe2-4893-b9cd-432aaf8771de&xsdata=MDV8MDJ8fGRjMWVmMTZjMTBiMjQ4MTUwNjZmMDhkY2FjMTI0OGJkfGU5NWYxYjIzYWJhZjQ1ZWU4MjFkYjdhYjI1MWFiM2JmfDB8MHw2Mzg1NzQ0NDE3ODYzNzM2NDF8VW5rbm93bnxUV0ZwYkdac2IzZDhleUpXSWpvaU1DNHdMakF3TURBaUxDSlFJam9pVjJsdU16SWlMQ0pCVGlJNklrMWhhV3dpTENKWFZDSTZNbjA9fDB8fHw%3d&sdata=VnVTMG5RUXpQWjFzd2UwN3NocFZKMGUzNmlQYzZHV011YXJEbmFSbVYyST0%3d)

**Comment by ljmoody** [comment]
Breaking what's left to do in this card down into manageable chunks.
- Created #3242 to track videos yet received and their inclusion into the manual.
  - Added to #sim_ui_workflow agenda for 8/9 to discuss ETA for Team Care Flow, Medication Management, and PSY flows that can be included as a graphic in video #17.
- Created #3241 to track adding alt text to images in this manual
- Created #3243 to track refining organization of information in Technical Documentation chapter to be specific to user type
- Created #3244 to track binning encounter documentation + adding to manual

**Comment by ljmoody** [comment]
@lzim re: your question below, the Dev team is working on this with @matthewtomo consistent with the approved wireframes. 
Some suggestions you've made in this card and others will require continued design development and discussions between you and sim_ui. 

---
**#sim_ui_workflow** when do we have an example Team Care Flow, Medication Management, or PSY Flows that can be included as a graphic in #4._

0:23 Stock Rectangle
0:33 Flow In/Out
0:39 Rate Dial
[Why is Modeling to Learn able to provide new insights about where Veterans get stuck or drop out of care__17.mp4 (sharepoint.com)](https://dvagov.sharepoint.com/sites/teampsd_vha/_layouts/15/stream.aspx?id=%2fsites%2fteampsd_vha%2fShared+Documents%2filead_workflow%2fILEAD+Edit+Review%2fWhy+is+Modeling+to+Learn+able+to+provide+new+insights+about+where+Veterans+get+stuck+or+drop+out+of+care__17.mp4&referrer=StreamWebApp.Web&referrerScenario=AddressBarCopied.view.7afdac00-afe2-4893-b9cd-432aaf8771de&xsdata=MDV8MDJ8fGRjMWVmMTZjMTBiMjQ4MTUwNjZmMDhkY2FjMTI0OGJkfGU5NWYxYjIzYWJhZjQ1ZWU4MjFkYjdhYjI1MWFiM2JmfDB8MHw2Mzg1NzQ0NDE3ODYzNzM2NDF8VW5rbm93bnxUV0ZwYkdac2IzZDhleUpXSWpvaU1DNHdMakF3TURBaUxDSlFJam9pVjJsdU16SWlMQ0pCVGlJNklrMWhhV3dpTENKWFZDSTZNbjA9fDB8fHw%3d&sdata=VnVTMG5RUXpQWjFzd2UwN3NocFZKMGUzNmlQYzZHV011YXJEbmFSbVYyST0%3d)
---
### Graphical improvements
- [ ] 1. The flows "bend" to/from the flows, creating unnecessary visual complexity AND challenges when zooming in to read the small text values. Recommend that there are no turns in the flows, just parallel left to right viewing to/from the stocks.
- [ ] 2. The stocks require a scale indicator on the tick marks.

![image](https://github.com/user-attachments/assets/c45d472a-fd94-4037-b030-32d723fa15e6)

**Comment by ljmoody** [comment]
- _Modeling to Learn_ 3.7 Consult Manual is now live. 
- Remaining work is broken down into cards made in above comment. 
- Graphical improvement suggestions to flow diagrams added to #3085 for tracking purposes. 
- Moving this card to done; suggest closing.
