### ISSUE TITLE
2024_wk5_may: BUG: Experiments not reloading into session

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#3170]
FYI:
@lijenn @ljmoody @dlkibbe @dlounsbu @lzim

Note:  This is only a problem in MM.

## What happens

- When user selects "Go" from the experiment dropdown in the experiment section of a model, the experiment values and associated text do not reload into the appropriate locations of the Text Pop Up.

## What should happen

- When the user selects an experiment from the experiment dropdown in the experiment section and clicks "Go" the model should reload the text (if available) into the Text Pop Up and set the experiment sliders to appropriate values.

![image](https://github.com/lzim/teampsd/assets/30132017/0f4a1a98-93b3-41df-b397-a8a5926d0d8d)

**Comment by tejaspesquare** [comment]
Hi @jamesmrollins - This is fixed & available to test on Test-slow.

![image](https://github.com/lzim/teampsd/assets/144898781/f3ae9fdb-f491-4e23-894c-661d2f981554)

![image](https://github.com/lzim/teampsd/assets/144898781/4d1de0aa-3f71-4acf-8d63-2eade35d38d0)

![image](https://github.com/lzim/teampsd/assets/144898781/b8480d21-b156-4545-8c29-695005216f1d)

**Comment by ljmoody** [comment]
✅ Verified this functionality is working correctly now in TEST-slow. Closing this issue card. 
fyi @tejaspesquare @jamesmrollins 

Tested by:
- Creating a team (laura_june_testing_team). 
- Used previously used data file. 
- Ran MM experiment and saved (using EPRVI mode as shown in James' screenshots above). 
- Returned to Admin Dashboard
- Re-entered sim, selected experiment, and observed all input text and sliders returned to saved experiment values. 
![image](https://github.com/lzim/teampsd/assets/124643236/b8ef7426-13c4-4139-bd91-a8f606e7f20a)

**Comment by hnorthcraft** [comment]
2 SP since the error was reported, fixed, and tested relatively quickly once it got prioritized
