### ISSUE TITLE
2024_07_epic #story_b: scope Sim 4.0 Flow

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3171]
## AC:
- [ ] Scope 4.0 Flow -> Location -> "Overlay" for #health_equity_contract and #health_equity_grant

**Comment by lzim** [comment]
I believe this was cleared up on our our **wk4 2024_06** call Fri 06/28.
There is no location "overlay" that comes from the Sim UI side on the current FY24 roadmap.

_Should we close this?_
@jamesmrollins 
@lijenn 
@ljmoody
