### ISSUE TITLE
2024_06 - Research, Development, Operations - validate MM model w/X-wavier removal

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3172]
## AC:
- [x] Vensim model upload/demo update, then
- [x] Sim UI for consults

**Comment by lzim** [comment]
Cross-ref: https://github.com/lzim/research/issues/824 assigned to @jamesmrollins & @tomrust

#adjudicate_memo for #aim_3 - Budget Impact Analyses
Not sure how the different cards are tracking each piece of this, but we need to get story point estimates on appropriate cards.

**Comment by lijenn** [comment]
Discussed 7/19:
- [x] - vensim upload
- [x] - sd docs
- [x] - sim ui
- [x] updated estimate to 5pts
