### ISSUE TITLE
wk2 2024_07 #story_b: rebuild r21 experiments

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3173]
## AC: 

- [ ] review OSF
- [ ] rebuild experiments

**Comment by lzim** [comment]
**wk2 2024_06 #sim_ui_workflow**
@lijenn 
@ljmoody 
@jamesmrollins 

We are aiming to submit the [R21 Findings manuscript](https://github.com/lzim/research/issues/768)  **wk3 2024_07**
_Who is working on this?_ 
_How does this manuscript submission deadline align with this work?_

Thanks!

**Comment by jamesmrollins** [comment]
@lzim

I am closing this card since it is now being tracked #3160.

- [ ] Roger on the deadline.  We re-noted it #3165.
- [ ] @lijenn is working on this.
- [ ] We can hit the wk2_jul deadline.
