### ISSUE TITLE
2024_06 #story_b: Resolve Directives pop-up sizing behavior

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3183]
Directives feature is currently live in PROD. However, function of Directives pop-up needs to be refined:

## AC:
- [x] Develop sizing capability on Directives pop-ups
- [ ] What happens now: pop-up window resizes based on mouse movement 
- [x] What needs to happen: pop-up window resizes based on user click and drag only
![image](https://github.com/lzim/teampsd/assets/124643236/027e9179-9a84-4e1f-b5e6-e00dc089f18c)

per Tejas: 
> If you perform a resize popup from right to left, you will observe that the size automatically adjusts according to the movement of the cursor. However, you can disable this behavior by clicking on the blue bar of the popup. We have made efforts to resolve this issue, but further investigation is needed as it is a third-party feature (text editor).

DEV team began investigating this issue June 10.

**Comment by tejaspesquare** [comment]
@ljmoody - This refinement is done & available to test on Prod environment. 

![image](https://github.com/lzim/teampsd/assets/144898781/58a326cc-e59b-41a6-9ccd-cff48462802f)

![image](https://github.com/lzim/teampsd/assets/144898781/5ff255cc-9b43-4d15-a4e4-8a5a86a8c1e0)

Pop-up resize & Float
![image](https://github.com/lzim/teampsd/assets/144898781/0bdad605-8755-4608-9495-1d51697ae67d)

![image](https://github.com/lzim/teampsd/assets/144898781/4f933bc5-f93c-4541-ad0e-746bb294ef20)


![image](https://github.com/lzim/teampsd/assets/144898781/b49e0edf-73a1-40bb-9e74-6620f86c2adb)



Note: I have configured sample directive for Psy & deleted after verification.

**Comment by ljmoody** [comment]
Hi @tejaspesquare,
✅ I am able to float the window and resize horizontally. 
❓: Is it possible to add vertical sizing capability, too, so the floating window can use the last ~1-2 inches of space on the screen? 
Screenshots taken on VA laptop, Edge browser, zoom 100%:

When Directives icon first opens:
![image](https://github.com/lzim/teampsd/assets/124643236/e53a9855-4548-4a04-8cec-58dd3a01e32f)

When Directives pop-up first opens:
![image](https://github.com/lzim/teampsd/assets/124643236/f7db8add-6754-4689-8e75-7f9d9b8f7008)

Maximum scaling capability currently: 
![image](https://github.com/lzim/teampsd/assets/124643236/a860ab32-5e99-49b9-b938-c26602afb827)

fyi @jamesmrollins

**Comment by tejaspesquare** [comment]
> Hi @ljmoody, 

❓: Is it possible to add vertical sizing capability, too, so the floating window can use the last ~1-2 inches of space on the screen? Screenshots taken on VA laptop, Edge browser, zoom 100%:

We attempted to meet your requirement, but unfortunately, we were unable to achieve the desired result. While this feature enables dynamic resizing, it does impact vertical scrolling for the content, as evident from the image below. 
Thank You! 

![image](https://github.com/lzim/teampsd/assets/144898781/9def4900-4087-4570-aede-48b143dbcfd0)

**Comment by ljmoody** [comment]
@jamesmrollins, given what @tejaspesquare said above, the Directives pop-up is sizing to the best of its ability and the vertical sizing is already at its maximum. As such, I'm closing this card.
