### ISSUE TITLE
2024_07 #story_b: Populate Directives Maintenance table in PROD

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3184]
## AC:

- [ ] use the Directives matrix developed by Jenn to populate MTL Dynamic Decision Dashboard Directives Maintenance table with:
   - Module Name
   - Video Topics
   - Video Link
   - MH 1161 Directive (directive text)
   - Resource Links
- [ ] Parallel the MTL 3.7 Consult Manual
- [ ] Omit rows of the table without a link

**Comment by lzim** [comment]
#sim_ui_workflow 
- Please estimate story points. Thx!

**Comment by lijenn** [comment]
Hi @tejaspesquare, I am unable to populate all the directive texts due to the word limit.

_Can we have unlimited word count?_ 

<img width="1104" alt="image" src="https://github.com/lzim/teampsd/assets/59668647/1c6b150e-49db-4d4e-a0f1-fc8142605af1">

**Comment by tejaspesquare** [comment]
> Hi @tejaspesquare, I am unable to populate the directive texts due to the word limit.

> _Can we have unlimited word count?_

Directives Maintenance - This is modified & now it should allow to add words without limit. Kindly verify on Test & provide your inputs.

![image](https://github.com/lzim/teampsd/assets/144898781/bf2b78a4-5a2f-40c4-936a-e593b350267e)

![image](https://github.com/lzim/teampsd/assets/144898781/a9a698bb-f849-45a9-be59-d1be96db1ff4)

**Comment by lijenn** [comment]
@tejaspesquare I'm still getting the maximum limit of words allowed in TEST:
<img width="1367" alt="image" src="https://github.com/lzim/teampsd/assets/59668647/fed16409-6334-44ca-b0bb-4cd50068e3dd">

**Comment by jamesmrollins** [comment]
## Sim UI Stand Up

- [ ] @tejaspesquare will investigate and resolve by 7/1.

**Comment by tejaspesquare** [comment]
Hello @jamesmrollins , @lijenn,
 
Verified on TEST.

1. This is allowed to enter words beyond 1lac.
![image](https://github.com/lzim/teampsd/assets/144898781/85d74a72-e0b9-491b-bef2-d079ef40c7d5)

Note: On a result window this might take more than usual time to display.

2. Keeping 24000 words

![image](https://github.com/lzim/teampsd/assets/144898781/115292e0-e8fb-43e7-99a0-a935934bebf8)

![image](https://github.com/lzim/teampsd/assets/144898781/ea3450cc-894c-4169-bab7-e67fba4e18f4)

![image](https://github.com/lzim/teampsd/assets/144898781/e07433fc-8160-4a74-b86a-0ed7c00482c2)

**Comment by jamesmrollins** [comment]
@lzim @dlkibbe @dlounsbu 

## Sim UI Workflow 7/3 Update

- [ ] Should be complete in PROD by COB 7/3.
