### ISSUE TITLE
wk2 2024_06 ANDON Sim UI PROD Set up - Episodes did not create message; Unclear 'Power BI' Format Message; Duplicate upload

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#3185]
**#sim_ui_workflow**
@jamesmrollins 
@lijenn 
@ljmoody 

- [x] 01. **ANDON:** I am trying to prepare an _MTL 3.7 Blue Consult_ for [#572](https://github.com/lzim/research/issues/572) and I got this error about not creating Episodes and I cannot move this forward.

![image](https://github.com/lzim/teampsd/assets/7454688/31a85c7d-e0a3-46c4-8901-19fb16c30ed6)

- [x] 02, **Clarify** this message about the necessary 'Power BI' format.

See below. This message has changed from prior versions and I am not sure that it is as clear as it was in the past. 
For example, it used to include the file extension .xlsx

_Do we need to include a screenshot?_ Or something so they can evaluate that they have the right format ??

> Please ensure the team data file must be in Power BI format before uploading. Are you sure the team data file is in Power BI format?
![image](https://github.com/lzim/teampsd/assets/7454688/d0763d0d-2b58-4269-bbe9-b3d1f290af74)

- [ ] 03. In addition, **I just uploaded a data file once and it looks like it uploaded it twice:**
![image](https://github.com/lzim/teampsd/assets/7454688/933f31ae-2fa0-4121-99df-567d74efec05)

**Comment by lzim** [comment]
- [ ] In addition, I just uploaded a data file once and it looks like it uploaded it twice:
![image](https://github.com/lzim/teampsd/assets/7454688/933f31ae-2fa0-4121-99df-567d74efec05)

**Comment by jamesmrollins** [comment]
@lzim 
@dlkibbe 
@dlounsbu 

FYI @lijenn @ljmoody 

1. We understand the bugs and have been able to replicate. We should be able to resolve by **Monday morning, 6/17 PST.**
2. We will workshop a better error message and have in place Monday as well.

**Comment by ljmoody** [comment]
@lzim, re:

>- [ ] 03. In addition, **I just uploaded a data file once and it looks like it uploaded it twice:**
![image](https://github.com/lzim/teampsd/assets/7454688/933f31ae-2fa0-4121-99df-567d74efec05)

This behavior is expected within the Settings > Data upload window. When a data file is uploaded, you will see the data file display like this. The top highlighted data file is associated with _team and _shared worlds; the lower highlighted file (with the added _ind identifier found in the Group column) is associated with that team's _ind world. This behavior is documented in card #2997, in [Tejas' April 8 comment](https://github.com/lzim/teampsd/issues/2997#issuecomment-2042829499). 

fyi @jamesmrollins @lijenn

**Comment by ljmoody** [comment]
@jamesmrollins, some notification messages brainstorms for Point 2 above:
- Team data is in Power BI format if multiple values are contained in a single cell.
- If you exported data (.xlsx) from the Data UI (Power BI) and are uploading for the first time, your team data is in the correct format. If you downloaded your team data file from the Sim UI, it will not work.
- Please upload .xlsx files that come directly from the Data UI (Power BI) or upload team data files found in your MS Teams General channel > Files folder.
- Do not attempt to upload data that was previously downloaded from the Sim UI. It will not work.
- When a Team Data file is downloaded from the Data UI, it is in a specific format that the Sim UI reformats during upload. This means that if a Team Data file is downloaded from the Sim UI and then re-uploaded to the Sim UI it will not work!

**Comment by jamesmrollins** [comment]
@ljmoody 

The notification message above looks good, as it adds needed details.  However, I would omit the first bullet as that would require someone to both open the .xlsx file and understand what they are looking at. 

@tejaspesquare 

We need to resolve the episode not created issue.  Please acknowledge receipt by clicking "thumbs up" in the reaction button below.

**Comment by lzim** [comment]
@ljmoody &
@jamesmrollins 

_Those bullets above are partially redundant options, are they not?_

Recommend this simplified text:
- Excel data files(.xlsx) exported from the _MTL_ Data UI (Power BI), or uploaded from your _MTL_ MS Teams, are in the correct format. 
- Downloading and re-uploading data files from the _MTL_ Simulation UI will not work.

**Comment by ljmoody** [comment]
@lzim, my bullet list of options was not finalized and meant to choose from. I appreciate you boiling it down and combining to make a robust message. Thank you. Teamwork=🌟!

@tejaspesquare, please incorporate Lindsey's bulleted items in the above comment as a replacement for the current "Please ensure the team data file must be in Power BI format before uploading. Are you sure the team data file is in Power BI format?" message and let me know when ready for verification. Thanks!

fyi @jamesmrollins

**Comment by lzim** [comment]
@jamesmrollins 
@matomasz 
@lijenn 
@ljmoody 

Given that Data files downloaded from the Sim UI no longer render properly, **_should we prevent the ability to download them to avoid confusion?_**

**Comment by tejaspesquare** [comment]
@ljmoody - We have replaced message & it appears like this. Shall we move to test for verification at your end.

![image](https://github.com/lzim/teampsd/assets/144898781/03e25b82-b4ef-4365-ab88-3b208b944f7a)

**Comment by ljmoody** [comment]
@tejaspesquare, is it possible to first change all 3 instances "MTL" to be iitalicized? If so, please do that and migrate to test for verification. Thank you.

> ![image](https://private-user-images.githubusercontent.com/144898781/341271297-03e25b82-b4ef-4365-ab88-3b208b944f7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5MDEwODcsIm5iZiI6MTcxODkwMDc4NywicGF0aCI6Ii8xNDQ4OTg3ODEvMzQxMjcxMjk3LTAzZTI1YjgyLWI0ZWYtNDM2NS1hYjg4LTNiMjA4Yjk0NGY3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMFQxNjI2MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNzIwNTA4ZGJiOWE5Y2U4Njg2ZmNmZGRmYjZiOTg5MDZiNDFkMDhhNDI4ZDYyOWQzODMxYTIyM2JiNjQ3MzkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.o5I01zbBfZxwK0aOb6jMGwFG1GWH3nlKxhEz1lFVmc4)

fyi @jamesmrollins @lijenn

**Comment by ljmoody** [comment]
✅ verified that point #2 above (data upload format message) is updated and live in PROD:
<img width="564" alt="image" src="https://github.com/lzim/teampsd/assets/124643236/3a15140a-ed71-4811-8887-4d0cee628274">

FYI @lzim @jamesmrollins

**Comment by lzim** [comment]
Great attention to detail and thanks @ljmoody and @tejaspesquare 
-  [ ] Note one final correction to the top bullet, which is clearer with the file extension after "Excel" and without the missing space in the screenshot above.
"Excel (.xlsx) data files exported from the MTL Data UI (Power BI), or uploaded from your MTL MS Teams, are in the correct format."

Thanks again!

**Comment by lzim** [comment]
#sim_ui_workflow - Please add story point estimates.
Thx!

**Comment by ljmoody** [comment]
✅ Verified correction was made and is live in PROD:
![image](https://github.com/lzim/teampsd/assets/124643236/15d07fe1-3c1b-456c-bf6d-437029eb4f38)

> Great attention to detail and thanks @ljmoody and @tejaspesquare
> 
> * [x]  Note one final correction to the top bullet, which is clearer with the file extension after "Excel" and without the missing space in the screenshot above.
>   "Excel (.xlsx) data files exported from the MTL Data UI (Power BI), or uploaded from your MTL MS Teams, are in the correct format."

**Comment by ljmoody** [comment]
Because 2 of the 3 tasks on this card are compete and the third is being tracked in another card (#3186), I'm closing this issue card.
