### ISSUE TITLE
2024_10 #story_b: DEV Enhance Sim UI Data Group column display to reduce confusion about "duplicate" data files

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3186]
## Current State:
Users open Administrator Dashboard > Settings > and see on the left-hand Data side of the window: 
![image](https://github.com/lzim/teampsd/assets/124643236/a448f568-fedf-4080-bcc6-3f65bd8bc3df)
This confuses users because they've uploaded **one** team data file, but it looks like there are now two. 

ℹ️: The top highlighted data file is associated with _team and _shared worlds; the lower highlighted file (with the added _ind identifier found in the Group column) is associated with that team's _ind world. This behavior is documented in card https://github.com/lzim/teampsd/issues/2997, in https://github.com/lzim/teampsd/issues/2997#issuecomment-2042829499.

## Desired State:
- [ ] Workshop an improved way to show what worlds the file(s) are associated with. What follows are suggestions, but by no means directions. More heads are needed to come up with the best solution.
- One suggestion: remove the team name from Group column and only show worlds the file is associated with (team, shared, ind).
- Another suggestion: have the file listed three times, with Group column showing _ind for one, _team for another, and _shared for the third.

## AC:
- [ ] Data files listed within the Data window are more easily understood.

**Comment by lzim** [comment]
@jamesmrollins 
@ljmoody 

Please note re: the ANDON: while two data files were created only one _shared world was created.

**Comment by ljmoody** [comment]
Noted, @lzim. Some of the behavior you observed on [#3185](https://github.com/lzim/teampsd/issues/3185) is expected and working correctly. Please refer to that card for our responses and explanations. 
We hope to improve the user experience in the future which is why I created this card 😀 

fyi @jamesmrollins

**Comment by lzim** [comment]
Right. Thanks @ljmoody 

I did read the card, but unfortunately it is still unclear (to me) how/why the behavior described as “expected” would be that way given the inconsistencies observed. Perhaps the word “some” reflects why this is.  

But if the use of the dialog and the GitHub explanation for its behavior is unclear to me. We definitely need this card to make it more user-friendly for all our _MTL_ users who are no longer expected to have to log in to Forio Epicenter backend and for whom self-explanatory self-registration is the user acceptance criteria.

> Some of the behavior you observed on https://github.com/lzim/teampsd/issues/3185 is expected and working correctly. Please refer to that card for our responses and explanations.
We hope to improve the user experience in the future which is why I created this card 😀

**Comment by ljmoody** [comment]
Tejas offered the following feedback on this issue; I'm sharing here to keep track of suggestions and feedback received:

- The DEV team developed based on the following comments found in #2997:
> -  If someone deletes a Team Data File in the shared or team world they are deleting it from shared and team worlds for all users of the shared and team worlds. This should not impact what is in individual worlds.

> - If someone uploads a Team Data File into a shared or team world, it should be available in team and shared worlds for all users of the shared and team worlds. This could be available in individual worlds too to save folks time. But, when someone uploads a Team Data file to an individual world, it should only be available to themselves and all MTL administrators who may need to provide support.
---
Tejas' responses to suggestions posed above: 
1.  One suggestion: remove the team name from Group column and only show worlds the file is associated with (team, shared, ind). &mdash; Tejas: _It is **not recommended** to display only the world that the file is associated with. This could lead to confusion among users, as it may be unclear which group the file belongs to when it is being deleted._
2. Another suggestion: have the file listed three times, with Group column showing _ind for one, _team for another, and _shared for the third. &mdash; Tejas: _Having 3 different entries for each world is possible however It is required to evaluate the effort that is needed._

fyi @jamesmrollins @lijenn @lzim

**Comment by lijenn** [comment]
Discussed 7/19 Team Praxis Call:
@jamesmrollins @matomasz @lijenn dispositioned to 2024_08. Reminder to add the sim_ui_dev label next epic.

**Comment by matthewtomo** [comment]
**Discussed Dev Standup wk4 2024_08**
@matthewtomo @tejaspesquare 

- @matthewtomo will connect with @jamesmrollins and @ljmoody to confirm the the behavior in this card still needs to be addressed, as the behavior in the sim UI differs from the screenshots.

**Comment by matthewtomo** [comment]
**Discussed Dev Standup wk_1 2024_9**
@matthewtomo @tejaspesquare 

- @matthewtomo will check in on this issue with @jamesmrollins later today to see if the AC has already been met.

**Comment by matthewtomo** [comment]
DECISION
@matthewtomo @jamesmrollins 

- AC is met.
- Marking issue as closed.
