### ISSUE TITLE
2024_07: Redesign Settings > Data > Add experience when associating data files with teams vs uploading data files to teams

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3187]
## Current State:
From the Administrator Dashboard > Settings pop-up, left-hand side "Data" of popup, users select Add:
![image](https://github.com/lzim/teampsd/assets/124643236/3f533d10-c2a9-4280-83f0-7f8fb1376780)

This is the best way to add data file(s) to the Sim UI _for the first time_ and associate to a team or multiple teams. 

Users are confused by the next pop-up, because it presents "Add" and "Upload" buttons:
![image](https://github.com/lzim/teampsd/assets/124643236/62e60c59-e2ad-46fc-99e7-c9253a281f7e)

- If users click "Add" to do this, they see an error message. 
![image](https://github.com/lzim/teampsd/assets/124643236/d8fb0929-5153-4ed5-aa0d-634e7b780584)
- The Add button only performs its intended function if, on the prior screen (Settings), the user selected one or more team data files. Then they must select Add to associate the file(s) with a team(s). This assigns a previously uploaded data file to a team.

- The Upload button is what users need to select to add data files to the Sim UI for the first time. - Users tend to select Add instead.

## Desired State:
Unsure, but something more intuitive or straightforward.
- Idea: rename the buttons? Because when you select Add on the Settings page, it makes sense to users to select Add on the Please select a world pop-up, because they want to add a file to a team and its worlds.

## AC:
- [x] Data file uploading for the first time vs adding/associating existing data files to teams is more easily understood.

**Comment by lijenn** [comment]
Discussed 7/19 Team Praxis Call:
- [ ] @matomasz will create the redesign wireframe ~ 2pts
- [ ] then we will let Dev know when it's ready ~ 3 pts
