### ISSUE TITLE
ANDON: No AUD, OUD, DEP data showing in Dynamic Decision Dashboard

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3188]
## What happens:
- FYI: Lindsey was using her VA DESKTOP and on Chrome browser. 
- [x] On 6/18/24, when Lindsey was working with a team data file, data values for AUD, OUD, and DEP did not populate - see screenshots below:
![image](https://github.com/lzim/teampsd/assets/124643236/1ff1a070-6afc-4f98-9098-8b93ad44ffd3)
![image](https://github.com/lzim/teampsd/assets/124643236/2cd7009b-ed5f-412b-a08c-78e118d4a26c)
![image](https://github.com/lzim/teampsd/assets/124643236/63752815-b83f-45ff-ba52-93134bf2c36f)

- [x] It was only when "Other" was selected that values showed. Screenshot below:
![image](https://github.com/lzim/teampsd/assets/124643236/6e1f87d9-56b0-4c8e-b0d8-e50140ce7423)

## What should happen:
 - [x] When a user selects a data file and clicks GO! within the DDD, AUD, OUD, and DEP stocks within Medication Management module should populate with relevant values.

**Comment by jamesmrollins** [comment]
For action: @tejaspesquare 
FYI: @lijenn @ljmoody @lzim @dlkibbe @dlounsbu @matomasz 

## Update 6/18

- Met with @TomRust and found that the MM model being used in the Sim UI was not correct.  The Sim UI team has been supplied with the appropriate model. The model in the Sim UI was not pulling and summing the data from both the w/x-waiver and wo/x-waiver % slots allocated -> aud, % slots allocated -> dep, % slots allocated -> oud, % slots allocated -> other. Therefore, zero values were being communicated because the model was only pulling from wo/x-waiver cells. 
- @tejaspesquare will update the MM model in all projects and branches in lzim/mtl, jamesmrollins/sim_ui and jamesmrollins/mtl-demo. I will provide updated model files in .vmfx, xmile, mdl formats and also include the HTML for the SD Doc. 
- @tejaspesquare will verify the team data table reflects the value from the following variables:
  - Slots Allocation % - > AUD, 
  - Slots Allocation % - > DEP, 
  - Slots Allocation % - > OUD, 
  - Slots Allocation % - > Other

**Comment by lzim** [comment]
Updated to **ANDON** to reflect that this is the only Bug or feature request that is creating a work stoppage. So, it's our #1 priority. 
As soon as resolved tomorrow we will be prepping our consults for next week.
Thanks!

**Comment by jamesmrollins** [comment]
## ANDON Update

- This is still working and is our number 1 priority
- We are attempting to resolve a variable mapping issue that is preventing the model from loading. 
- **Anticipate resolution by 6/21.**

FYI: @lijenn @lzim @tejaspesquare @TomRust @dlkibbe @matomasz @dlounsbu

**Comment by jamesmrollins** [comment]
## Andon Update 6/21

- We have resolved the AUD, DEP, OUD, Other model value returns. So the model is lined up with the Sim UI and Team Data correctly.
- Residual problems with reliable code migration is hampering deployment of code.  So Sim UI is still down.
- Will continue working on this until we get it right . . . more to follow Monday at 8am Workflow.

FYI: @lijenn @ljmoody @lzim @tejaspesquare @dlkibbe @matomasz @dlounsbu

**Comment by lzim** [comment]
@jamesmrollins - Just to make sure I understand your message and schedule and communicate effectively with partners and sites: **You’re saying we cannot prep anything in Sim UI PROd until Monday at the _earliest_?**

**Comment by jamesmrollins** [comment]
FYI @lzim @dlkibbe @dlounsbu 

## Andon Update 6/21.1

- **The Sim UI Prod is back up for _team and _shared.**_The _ind session problem still exists, but will be resolved Monday.
- MM Model is properly aligned, showing results for AUD, DEP, OUD, Other.
- Drill down to models is working. 
- Chrome and Edge validated.
- Clear cache is needed to ensure proper loading. 

## SME Impact

- SME's can continue prep work right away, but must use a _team or _shared session.
- The drill down to a model diagram should work.

## Clear Cache Instructions Are below for Edge

- [ ] Press "ctrl-H"
- [ ] Click on the Trash Can in upper right

![image](https://github.com/lzim/teampsd/assets/30132017/bbc1898a-a040-418b-b04f-1c6d1c5c0809)

- [ ] Select "From all Time" from the drop down
- [ ] Click all boxes
- [ ] Click "Clear now" blue button

![image](https://github.com/lzim/teampsd/assets/30132017/9de92cbe-1457-4eb6-83eb-b2a3ea68e1f3)

## Clear Cache Instructions Are below for Chrome

- [ ] Click on elipses ( . . .) in upper right of browser.  Then click "Settings"

![image](https://github.com/lzim/teampsd/assets/30132017/1a3a2055-bb08-495a-a76e-fa43924a5d27)

- [ ] Click on "Privacy and security" then "Delete browsing data"

![image](https://github.com/lzim/teampsd/assets/30132017/0ab5c577-8b6d-4967-8b80-2f34c2dffa06)

- [ ] Select "All time" from the drop down and select all check boxes.

![image](https://github.com/lzim/teampsd/assets/30132017/2db3927c-4e87-4ed1-925d-e96ae1a3e537)

- [ ] Select "Delete data"

**Comment by lzim** [comment]
FYI @dlkibbe & @dlounsbu

**Comment by lijenn** [comment]
Hi @tejaspesquare @jamesmrollins, _is the individual world ready for users tomorrow at 9AM Pacific or are there other pending issues?_

@lijenn was able to access the individual world for tomorrow's site meeting, upload and run a data file, and go into the model (MM) and run experiments. 
@ljmoody was also able to access the individual world.

**Comment by tejaspesquare** [comment]
Hello @lijenn, 

> Hi @tejaspesquare @jamesmrollins, _is the individual world ready for users tomorrow at 9AM Pacific or are there other pending issues?_

Please find updates regarding updates on individual world.

1.For now, individual work only if one Team lead present in a group.
2.If we are permitted to include multiple leads within a single team, it will result in an authentication issue when attempting to execute a model. For this case we had a problem & details sent to Forio(David).

**Comment by jamesmrollins** [comment]
@lzim @dlkibbe @dlounsbu 

## Some fundamental understandings

- [ ] In order to have an individual **world** you must be assigned a world ID and login directly to that world. 
- [ ] Our current algorithm assigns non-facilitators (non-Admin) as team leads in their own world, and
- [ ] It does not assign facilitators (Admin), because it would mean the login dropdown would have the Administrator Login, and the _ind login.  This could be a potentially long list.

## Recommendations for SMEs

- [ ] Use the _shared world as the SME workspace.  **OR**
- [ ] Use the_ind world ID **AND** tolerate a potentially log list of _ind worlds as your client base grows. 
- [ ] We can ensure that the "Administrator" login is always at the top of the login.
 
## Double checking my logic with D. Berkman at Forio to ensure I haven't missed something in the Business Rules.  Will advise if the above is incorrect.

**Comment by lzim** [comment]
@jamesmrollins 

- [ ] please provide an update a **#9am_workflow** on Monday.
- [x] @lzim added to the agenda.

**Comment by jamesmrollins** [comment]
## Decision 7/15

- [ ] Admins will prep in Shared world.
- [ ] Admins need a sandbox.  
- [ ] Admin sandbox would need access to all Team Data files. 
- [ ] Naming convention "lindsey.zimmerman@va.gov_ind"

**Comment by lzim** [comment]
**Discussed 9am_workflow leads wk3 2024_07**
@lzim
@jamesmrollins 
@lijenn 
@ljmoody 
@matomasz 

**DECISION:** 
Re:  Single Administrative World 
 _ind
 
Forio Epicenter Login Email
[lindsey.zimmerman@va.gov](mailto:lindsey.zimmerman@va.gov) 
 _ind

**Comment by lijenn** [comment]
@lzim Epicenter doesn't allow special characters except for underscores and hyphens for world names. 
<img width="730" alt="image" src="https://github.com/user-attachments/assets/2f9f5c81-5843-4a6d-af32-262a5592ceac">

_Want me to add underscores in place of the period and @ symbol or just use first and last name?_
<img width="706" alt="image" src="https://github.com/user-attachments/assets/b9aadcd2-7f1e-450a-bd0a-47374aeac172">

FYI
@jamesmrollins
@lijenn
@ljmoody
@matomasz
@ljmoody

**Comment by lzim** [comment]
Thanks @lijenn - good question! _Can we use periods?_ 
> Want me to add underscores in place of the period and @ symbol or just use first and last name?

**I recommend we keep it simple and aligned to va email standard: firstname.lastname**
lindsey.zimmerman
jennifer.li
matthew.tomaszewski 

**Back-up if no periods - firstname_lastname**
lindsey_zimmerman
jennifer_li
matthew_tomaszewski etc.

FYI:
@ljmoody 
@jamesmrollins 
@matomasz

**Comment by matthewtomo** [comment]
**Discussed wk4 2024_07 #sim_ui_workflow**
@matthewtomo @lijenn 
Does this mean we will now have individual worlds for admins/SMEs **AND** the _IND worlds associated with each team?

@lzim @jamesmrollins

**Comment by lzim** [comment]
Good question @matomasz @lijenn 

> Does this mean we will now have individual worlds for admins/SMEs AND the _IND worlds associated with each team?

I would think that having one single _ind world for admin would be sufficient, as long as it is easy to pull in to this _ind world the a) data, and b) experiments run and saved including text.

**Comment by matomasz** [comment]
**Discussed DEV Standup 7/29/2024**
@matthewtomo @tejaspesquare 

- Dev team needs clarification on the following items:
  - Do we only require a single _IND world for admin/facilitator users irrespective of their number of teams?
  - Will we no longer create _IND worlds for each admin on team creation, but still make _IND worlds for each Team Lead/Member?
- After clarification, Dev team will need to check the affected functionality to estimate how much work this change will take.

fyi: @lzim @jamesmrollins @lijenn @ljmoody

**Comment by matthewtomo** [comment]
**Discussed DEV Standup 7/29/2024**
@matthewtomo @tejaspesquare 

- Dev team needs clarification on the following items:
  - Do we only require a single _IND world for admin/facilitator users irrespective of their number of teams?
  - Will we no longer create _IND worlds for each admin on team creation, but still make _IND worlds for each Team Lead/Member?
- After clarification, Dev team will need to check the affected functionality to estimate how much work this change will take.

fyi: @lzim @jamesmrollins @lijenn @ljmoody

**Comment by lzim** [comment]
@matthewtomo @tejaspesquare 

Unfortunately, I'm having a hard time tracking the resolution on this. _Perhaps there is a separate card where I already answered these questions?)_ I'm not sure, but we need to make sure we can prep these sites ASAP.

FYI: @ljmoody @lijenn 

> Do we only require a single _IND world for admin/facilitator users irrespective of their number of teams?
- If it is easy to access any team world's a) **data** and b) **experiments & Q/H/F/D text,** then **YES** it is fine to have a single _ind world for admin users.

> Will we no longer create _IND worlds for each admin on team creation, but still make _IND worlds for each Team Lead/Member?
> **Yes.** Each team lead will need an individual world.

**Comment by matthewtomo** [comment]
@lzim I believe that the Original ANDON of this Issue has been resolved. I will pull this remaining task into a new issue (see: https://github.com/lzim/teampsd/issues/3237)
