### ISSUE TITLE
1.7.2 PSY Module Update

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#319]
This thread is being started to isolate and disposition PSY Model updates.

**Comment by jamesmrollins** [comment]
**Version 1.7.2 is in TEST**: Please consult the design summary and review checklist below to and indicate your "Go, No-Go" response. I will add all participants to a test group named "version_1_7_to_1_8_test" and assign individual worlds. I have truncated the checklist to only cover things that are applicable for this sprint. 

**Design Summary:** The PSY Module was:
1. Updated with gaming variables to allow for time stepping.
2. "Appointments Available for New Patients" switch and Icon was changed to "Appointment Slots Reserved for New Patients." (pending 2/25)
3. "Implement Intensive Outpatient Program" switch and icon was added.
4. In SIM UI, Changed "Median Engagement Time after 3 Months" icon to "Engagement Duration after 3 Months" and in Experiments Section, changed red slider icon text from "Change in Engagement Time of Patient's Past 3 Months" to "Change in Engagement Duration after 3 Months."
5. In Team Data Table, changed "Median Engagement Duration (wks)" to "Engagement Duration (median)(wks)" and change "Engagement Time after 3 Months (wks)" to "Engagement Duration after 3 Months (wks)"

**Simulation Run** (James and Tom)

* [x]    1. Widgets return same values as the client version of Vensim.
* [x]    2. Charts are consistent with values from the client version of Vensim.
* [x]    3. (If new experiments are added) New experiments function properly.
* [x]    4. (If new functions are added) New functions operate as specified.

**Outputs** (if variables or charts are added) (James, Stacey and Savet)

* [x]    1. The save-experiment naming function properly encodes any new variable in a manner that is understandable.

**Training and Documentation** (Debbie, Jane, and Stacey)

* [ ]    1. Changes in simulation are noted in training documents, or are in process.
* [ ]    2. Changes are consistent with dialogue and instruction in current video training.
* [ ]    3. Help descriptions are up-to-date and include explanations of new functions or variables.
* [ ]    4. "i" Information is up-to-date, correct and complete.

**Comment by jamesmrollins** [comment]
Reference issue #298, PSY Model label changes in the Main SIM UI started by @staceypark , @lzim and @TomRust .  Below is latest design interation:

Approve?  

- [ ] YES

- [ ] NO

![image](https://user-images.githubusercontent.com/30132017/53365241-9e91a980-38f5-11e9-8cb7-5f1b5a61b0c7.png)

**Comment by jamesmrollins** [comment]
Hi @lzim , here is another version for you to consider:

![image](https://user-images.githubusercontent.com/30132017/53615418-9f933700-3b92-11e9-8da8-35c830beff1b.png)

**Comment by lzim** [comment]
@jamesmrollins thanks I like the revised version you updated yesterday.

I really like the labeling of the stocks with a bigger font and Starters, Initiators and Completers first.
- I'd like to remove the parentheses for both the stocks and rates. So for the stocks, just keep the text "Patients in First Visit" with no parentheses.
- Let's make the rates parallel (lead with "Starters," remove parentheses, no need to re-state the number of visits, it is right above with the stocks), e.g. "Starters continue treatment Rate after 3 months."

Seem okay?  Let me know if you have any questions and thanks!
:trophy:

**Comment by jamesmrollins** [comment]
@lzim Here is how I interpreted your feedback:

![image](https://user-images.githubusercontent.com/30132017/53902302-c53a9900-3ff5-11e9-93d1-cb179af120d3.png)

**Comment by lzim** [comment]
@jamesrollins looks great. Thanks!👍🏾

**Comment by saveth** [comment]
@jamesmrollins I'm good with Psy unless we make further changes to the ModelParameter or master crosswalk. 😃

**Comment by jamesmrollins** [comment]
@saveth @TomRust @lzim @staceypark 

Tom, Savet and I met to discuss modifications to the xlsx export file to support R markdown Sankey needs.  We identified the appropriate variables that need to be added:

Exp-A through Exp-H
Bar-C through Bar-H

James will add these variables in the next pull to DEV.

**Comment by saveth** [comment]
@jamesmrollins @TomRust Is there a cap on the values for Bar-C through Bar-H? I'm seeing some extremely large negative values in my export and makes the Appointment Usage graph wacky.

**Comment by TomRust** [comment]
@saveth @jamesmrollins @holbrooa -- That's not good.  There are no negatives in the formulas that calculate those values, so the negatives must be coming from the data.  Negative frequencies or engagement times are hard to explain to the end user.  :)  

Could you attach the data file you used when you got those negative results?

**Comment by jamesmrollins** [comment]
@TomRust @holbrooa @saveth  The only negative number is saw was very, very small on Exp-G-Bar.  So small, that I just thought is was noise.  Otherwise, the other values are positive.  One thing I noticed and must verify are the Experiment Tile values. I see negative numbers there that are base case signal values,  not the actual base case values.  I will need to dig into that.  Could this be a part of the issue?

![image](https://user-images.githubusercontent.com/30132017/56300247-6c791880-60ea-11e9-882b-b4335d756550.png)

![image](https://user-images.githubusercontent.com/30132017/56300410-c5e14780-60ea-11e9-91b8-624784da137d.png)

**Comment by TomRust** [comment]
YES, @jamesmrollins !!!! Good sleuthing!  If we've accidentally mapped to the signal values, not the actual data values, then this is probably the cause of our renegade negative Exp-G-Bars result.

**Comment by jamesmrollins** [comment]
@TomRust those values are just what is reported in the export- not what is mapped to run in the sim.  In other words, even if I run a base case in Vensim, I still get the micro-small negative G bar value. So i don't suspect a negative base case signal value is the culprit here, UNLESS @saveth is using those values in an concomitant calculations in the R code.

**Comment by TomRust** [comment]
@saveth @jamesmrollins @holbrooa...Wow.  I have literally no idea what is going on.  Vensim is saying that 1+3+8 = -2e^33, instead of 12.  

I think I fixed it, though.  Emailing new Vensim file now.

**Comment by jamesmrollins** [comment]
@saveth @TomRust @holbrooa i recieved the file and ran it.  I have one question though, why are some of the bar variables returning a single value, and some return time arrayed values? Anyways, I will load this new file in TEST and see what it does there.

**Comment by TomRust** [comment]
I can set them to report only one value (pulled at whatever time I choose), or they can calculate continuously.  Something about mixing these two types of variables led to the bad arithmetic.

**Comment by jamesmrollins** [comment]
@saveth @jamesmrollins @holbrooa  new PSY runs in test without the funky negative value.  I will migrate to PROD. @saveth, we didn't include team data table in the export because it would be redundant with the model parameters file.  And we also needed a record of the BC switch settings for the experiment recall function.  What would work best for you??

![image](https://user-images.githubusercontent.com/30132017/56307884-c2ee5300-60fa-11e9-92f9-6388cb77bd6f.png)

**Comment by saveth** [comment]
@jamesmrollins @TomRust thank you for sussing out the issue with the negative number. The table you @jamesmrollins posted above is exactly what I needed to produce both the Sankey and Appointment Usage graphs. Thanks for the fix, I'll pull some new output to test my R code. Much appreciated. 👍 😄

**Comment by lzim** [comment]
**All** @jamesmrollins @saveth @dlkibbe @branscombj @staceypark @dlounsbu 

I believe this MTL 1.8 issue is ready to be closed 👏 

These tasks were completed and moved to mtl.how (#1 & #3) or to OSF (#2 MTL Video table & "i" information).
1. Changes in simulation are noted in training documents, or are in process.
2. Changes are consistent with dialogue and instruction in current video training.
3. Help descriptions are up-to-date and include explanations of new functions or variables.
4. "i" Information is up-to-date, correct and complete.

Great work 🍾
