### ISSUE TITLE
2024_06: BUG: Admin dashboard hanging up when Lindsey logs in

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3192]
For Action: @tejaspesquare 
FYI: @matomasz 

- Lindsey was using a VA laptop, Chrome browser. 
- Lindsey cleared her cache (because of behavior of Sim UI-clearing cache recommended by James & Laura to see if that would help with issues), then logged back into PROD instance. 
- She successfully logged in, but the Admin Dashboard started to hang up. Screenshot of inspector console below;
![image (2)](https://github.com/lzim/teampsd/assets/124643236/a56b6cdf-8e53-4404-99a3-931c382c4a30)

**Comment by tejaspesquare** [comment]
@ljmoody - I have logged in using my @lzim VA credentials & it is redirected to Dashboard page without any issue.

![image](https://github.com/lzim/teampsd/assets/144898781/9f449bd7-70fe-4118-9e8f-0fcea1cf0cb4)

![image](https://github.com/lzim/teampsd/assets/144898781/261d63b3-cbfc-4687-b61b-f140924ac5ef)

**Comment by ljmoody** [comment]
@tejaspesquare and @lzim, I tested logging in to PROD using lzim credentials on both Edge and Chrome browsers and the Admin Dashboard successfully loaded. Please try again, Lindsey.

fyi: @jamesmrollins @lijenn

**Comment by lzim** [comment]
It sees to be working for me too 👍🏽
