### ISSUE TITLE
2024_06 #story_b: BUG: Team Data files associated with worlds not showing on team Home page (Edge browser only)

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3194]
## What happens now:

After adding a team data file to 3 worlds via the Admin Dashboard:
![image](https://github.com/lzim/teampsd/assets/124643236/a60b299e-21c2-4ac4-b7f8-f7da97729f48)

Then selecting one of those team worlds and navigating to its Home page, the data file does not show in:
1. Please Select Team Data dropdown
2. Team Data blue bar dropdown
![image](https://github.com/lzim/teampsd/assets/124643236/226329c9-ce82-49c7-bf1d-16684c7e00dc)

Here's a screenshot of the console log:
![image](https://github.com/lzim/teampsd/assets/124643236/30c10607-d374-40eb-8a35-9724a9b7f9e3)

**Additional info:**
- I cleared my cache for both browsers on Monday morning following instruction in #3188.
- Jenn tested this as well and experienced the same results in both browsers.
- This happens in Edge browser only. Tested using Chrome and it behaves as expected:
![image](https://github.com/lzim/teampsd/assets/124643236/c1b0ba14-2754-4c91-8cd2-2668a773320d)

## What should happen:
When a team data file is uploaded to 1 or more worlds, that data file association should pre-populate in both the Please Select Team Data dropdown and the Team Data blue bar dropdown in that world's Home page.

fyi: @dlkibbe @dlounsbu @lzim

**Comment by tejaspesquare** [comment]
@ljmoody , @lijenn ,

We have not been able to replicate this problem on our side. It is possible that there is a delay in the API response. Please attempt the action again after clearing your cache and deleting your browsing history, as this may resolve the issue.

Team worlds created

![image](https://github.com/lzim/teampsd/assets/144898781/b9bbc7ad-c32a-400d-8153-8f3a03c05abe)

Widgets - Team Data & Session populated without an issue
![image](https://github.com/lzim/teampsd/assets/144898781/86fcc043-f460-4725-829b-8fd407e5c0df)

Edge Browser
![image](https://github.com/lzim/teampsd/assets/144898781/2539d882-c290-4d95-b5a1-ecd98b3893ee)

Edge - Team Lead Role user (Just to check behavior after bypass Dashboard)
![image](https://github.com/lzim/teampsd/assets/144898781/b7de0f46-6c0b-417f-b7de-b4897f2fb891)

@ljmoody  - I have logged in with your credentials & observed this is loading smoothly (Edge Browser)
![image](https://github.com/lzim/teampsd/assets/144898781/972c3250-8c62-4001-9bc5-93f4a92b9cd0)

**Comment by ljmoody** [comment]
Hi @tejaspesquare, 
I'm unable to clear browsing or download history (it's locked by the VA), but cleared everything else that's checked below . . . and it worked correctly just now! 🥳 
![image](https://github.com/lzim/teampsd/assets/124643236/226e4bf4-7416-4c44-9c74-37becaf296f1)

Screenshot of expected team data file associated with _team (also observed team data file populated for _ind and _shared worlds):
![image](https://github.com/lzim/teampsd/assets/124643236/0c652ba6-708e-46fe-9f5d-50c318551977)

I've asked @lijenn to test and verify before closing this card.

**Comment by ljmoody** [comment]
@tejaspesquare, Jenn also tested on Edge browser—first without clearing cache or cookies—and it's working for her as well. 
Closing this issue card.

**Comment by ljmoody** [comment]
@tejaspesquare, Jenn also tested on Edge browser—first without clearing cache or cookies—and it's working for her as well. 
Closing this issue card.
