### ISSUE TITLE
2024_07 #story_b: update Sim UI Cheatsheet to reflect 3.7 release

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3195]
## AC:
- [x] recreate Sim UI cheat sheet
- [x] update to reflect v3.7 and relevant date
- [x] include 2 new sections:
    - [x] Self Registration 
    - [x] Dynamic Decision Dashboard
- [x] update highlighted areas on existing sheet:
![image](https://github.com/lzim/teampsd/assets/124643236/1ab6b0c0-571d-4157-acde-eda2c332960b)
- [x] peer review by Jenn

**Comment by jamesmrollins** [comment]
@lzim 

## Sim UI 7/3

- [ ] Last two sections need to be developed.
- [ ] @lijenn will QA the document.
- [ ] Final done NLT COB 7/5.

**Comment by ljmoody** [comment]
ℹ️: Last two sections developed and cheatsheet shared via Lucidchart with @lijenn for review at COB 7/3.

**Comment by lijenn** [comment]
@ljmoody Please see my comments and responses to your questions on the document. Lmk if you have questions. Thanks!

**Comment by ljmoody** [comment]
Sim UI cheatsheet updated, peer reviewed, and saved to Lucidchart > lzim/mtl > cheatsheets. 
Closing this card.
