### ISSUE TITLE
BUGS in Sim UI PROD: SAIL link doesn't go to SAIL metrics

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#3197]
**wk4 2024_06 - #systems_sme_workflow**
@lzim **to add to this card as issues are identified during prep on Thu 06/27**
@dlkibbe 

### DDD PSY
- [x] 01. SAIL Metric Links not going to SAIL from PSY DDD
- [x] 02. MH Directives 1160.01
![image](https://github.com/lzim/teampsd/assets/7454688/b203b4c7-15a9-4fa5-af29-56628efdfac9)

### PSY module
- [x] 03. Results Dashboard isn't using our standard unites of pts for patients (see pnts)
![image](https://github.com/lzim/teampsd/assets/7454688/0276b7cb-1226-4f6c-940a-721f6d4b3500)

**Comment by dlounsbu** [comment]
![image](https://github.com/lzim/teampsd/assets/20574023/e462f9a5-2ee2-4e72-a50d-89aa03c31335)

**Comment by jamesmrollins** [comment]
**#systems_sme_workflow**
@lzim
@dlounsbu  
@dlkibbe 

- [ ] Completion Rate and Completing Rate are both features of the Psy module. 
- [ ] The difference is one is patients (Completion) and one is appointments (Completing). 
- [ ] When we designed this year ago, there was some concern about the similarities between the two.
- [ ] We may need to investigate calling it something else, but something tells me we have already exhausted other possibilities.

**Comment by jamesmrollins** [comment]
@lijenn @ljmoody 

- [ ] Please investigate the issues above regarding the directives pop up and admin page.
- [ ] Incorrect links and Coming Soon seem like things we can adjust from the admin page.

@tejaspesquare - See the error in the report in #3 above, Psy module Results Dashboard, unit of measure should be "pts" not "pnts." I checked the model and the units are correct for these.  Please scan the other reports to ensure there are no other typos.

**Comment by tejaspesquare** [comment]
@jamesmrollins , @lijenn ,
Reg. SAIL metrics link - Based on our investigation, this is being maintained as static code. i.e. mtl.how/sail
However, we are uncertain on click why this is redirecting to "https://github.com/lzim/mtl". 

FYI: in a code
![image](https://github.com/lzim/teampsd/assets/144898781/cf21a940-116d-42eb-8f58-3376388975b1)

**Comment by jamesmrollins** [comment]
@lijenn I checked the mtl.how/sail redirect from inside the domain and it directs the user to the lzim/mtl repo.  I think the redirect page link is incorrect.  Can you check it out please?

**Comment by ljmoody** [comment]
01. DDD PSY > SAIL Metric Links not going to SAIL from PSY DDD
    **update:** 
    - SAIL metric links (all 5 modules > More menu > SAIL Data icon) all route to github.com/lzim/mtl
    - @jamesmrollins when I manually typed "mtl.how/sail" into my browser (within VA and outside of VA), both tries led me to github.com/lzim/mtl
02. DDD PSY > MH Directives 1160.01
    **update:** I believe these weren't populated when Lindsey opened this card because of a word/character limit (tracked in #3184) reached when Jenn was attempting to populate the fields. As of today, this is solved and working in PROD. 
03. PSY Module >  Results Dashboard isn't using our standard units of pts for patients
  **update:** Verified units are corrected in TEST:
![image](https://github.com/lzim/teampsd/assets/124643236/fa35fcc5-601b-441a-9f38-0bee35156218)

04. Duplicate value for completing rate in the PSY module drop-downs
    **update:** See James' comment above re: Completion Rate vs Completing Rate.
    
![image](https://github.com/lzim/teampsd/assets/124643236/8a1ec176-794a-4ffe-8843-f6885a5da3eb)

**Comment by lijenn** [comment]
@ljmoody @jamesmrollins I updated https://mtl.how/sail to redirect to SAIL's Sharepoint site. The link is working in Prod now.

**Comment by ljmoody** [comment]
✅ Verified SAIL links (all 5 modules > More menu > SAIL Data icons) now direct to the Sharepoint site in PROD instance:
![image](https://github.com/lzim/teampsd/assets/124643236/76857a9e-2ecc-453f-b5da-b3f213a74ddc)

All tasks are complete; closing this card.
