### ISSUE TITLE
2024_07: develop HE wireframe

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3200]
##AC: 
- [ ]  Wireframe reviewed and validated against user design intent
- [ ] Feedback and corrections incorporated into final wireframe
- [ ] ? - Laura reviews wireframe for editing purposes

**Comment by lzim** [comment]
@ljmoody 
@matomasz 
@jamesmrollins 
@lijenn 

**Per our 06/26 Friday call and our https://mtl.how/2024_roadmap revisions.**
_What HE wireframe is needed?_

**Comment by lzim** [comment]
#adjudicate_memo - Card not needed.
**wk3 2024_07 #sim_ui_workflow**
@lzim
@jamesmrollins 
@matomasz 
@ljmoody 
@lijenn
