### ISSUE TITLE
2024_07 #story_b: BUG: newly created teams in PROD not created or seen as expected

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3203]
Discovered 7/3/2024 when creating a team live with James. VA laptop. Edge browser. Using my VA email login to and create teams within Sim UI, PROD instance.

# What happens now:
## Test 1, PROD: 
After creating a new team and adding:
- myself, **Praxis email**, Administrator role
- James, **Praxis email**, Team Lead role
the only team world I see listed is _shared:
![image](https://github.com/lzim/teampsd/assets/124643236/9d47ad7b-d627-41f4-94b2-1616560d18d3)

The _shared world includes:
![image](https://github.com/lzim/teampsd/assets/124643236/99d36188-1fba-4600-bc34-b4ac4feb5407)

I then logged off, and logged in using Praxis credentials:
1. I see these teams listed:
![image](https://github.com/lzim/teampsd/assets/124643236/e261526b-4528-4c5f-a291-78bf80bbe1b4)
2. The _teams world only has me listed & does not include 6 automatically added individuals
![image](https://github.com/lzim/teampsd/assets/124643236/7fa9dbc5-12c3-4aa2-a2e5-47428859d50b)
3. The _ind world only has me listed & does not include 6 automatically added individuals
![image](https://github.com/lzim/teampsd/assets/124643236/a899daac-7868-431c-a719-1c8d4a838c2c)

## Test 2, PROD: 
After creating a new team and adding:
- myself, **VA email**, Administrator role
- James, **VA email**, Team Lead role
the team worlds I see are:
![image](https://github.com/lzim/teampsd/assets/124643236/9ec1adf9-65a8-409d-a72a-438767594833)

1. The _team world includes:
> [!NOTE]  
> Jennifer is missing.

![image](https://github.com/lzim/teampsd/assets/124643236/cbf69878-06b8-409c-af91-895f822155ef)

2. The _shared world includes:
![image](https://github.com/lzim/teampsd/assets/124643236/0ae8fae6-89a5-40a6-a8e0-abdafd7a28ff)

3. The _ind world includes: 
> [!NOTE]  
> Jennifer is missing.

![image](https://github.com/lzim/teampsd/assets/124643236/5de38b9d-34fd-42f9-83f5-9f23bcb11f79)

# What should happen:
The behavior of PROD new team creation should be the same as found in TEST:
- Administrators, when using their administrator associated email to login, should see 1) all teams they've joined an 2) ones in which they have an 'Administrator' role. 
- All 6 automatically added individuals should be added to all team creations + worlds.
- FYI @tejaspesquare, PROD instance is particularly suspect; behavior seems normal in TEST instance (see screenshots below). _Could this issue be related to code migration?_

## Test 3, TEST:
When live testing with James (Edge, VA laptop, VA login), I created a new team adding:
- myself, **VA email**, Administrator role
- James, **VA email**, Team Lead role
I see all team worlds: 
![image](https://github.com/lzim/teampsd/assets/124643236/d93b13fb-12b6-4418-91c4-5bc197f11869)

1. The _team world includes:
![image](https://github.com/lzim/teampsd/assets/124643236/5aee8966-de4a-401c-8776-bcd1fc797000)

2. The _shared world includes:
_? - Should James also be listed here as Team Lead/VA email_
![image](https://github.com/lzim/teampsd/assets/124643236/5817b9db-2da4-4c5b-8406-b009729ab925)

3. The _ind world includes:
![image](https://github.com/lzim/teampsd/assets/124643236/ec9e7def-cff7-4ca7-add1-e1dd5d97fcc2)

**Comment by tejaspesquare** [comment]
@jamesmrollins , @ljmoody ,

Prod Instance, using 'tejas.p' login

New Team got created
![image](https://github.com/lzim/teampsd/assets/144898781/4cd2a6c7-7a6c-49cf-9b87-c7b1d0202566)

All 3 worlds got configured with expected default members: 

ex. _ind world
![image](https://github.com/lzim/teampsd/assets/144898781/c78d612d-6fa0-47d2-aa4a-02e4f37f0851)

![image](https://github.com/lzim/teampsd/assets/144898781/fcfd9573-4d4c-429b-a937-73430e498bd4)

Added - Laura Moddy, Praxis email, Administrator role
Edited James, Praxis email, Team Lead role from Administrator
under _shared world:
![image](https://github.com/lzim/teampsd/assets/144898781/bb003717-5f20-4694-b27b-846770ec3314)

Logged in using Laura Moody's Praxis account, only permission granted world is being added which is expected
![image](https://github.com/lzim/teampsd/assets/144898781/bce8f96c-fb90-493c-ba14-df33bc669c1c)

all 6 automatically added individually are present
![image](https://github.com/lzim/teampsd/assets/144898781/3594477a-f879-425a-b64d-e377ebc86273)

![image](https://github.com/lzim/teampsd/assets/144898781/dd9d9ba8-64a6-425f-b459-47ab0ac855c9)

This looks working fine as expected.

**Comment by ljmoody** [comment]
@tejaspesquare, I tested as you did and, using your same scenarios I got matching results. Which is good. However, the Sim UI PROD instance is acting strangely for me.

I think something odd could be going on with team creation in PROD. Can you please check?
fyi: tested using VA login, PROD instance, Edge browser, VA laptop.

## Create a team from Admin Dashboard > Settings > Add, & did not add any members as I created the team:
![image](https://github.com/lzim/teampsd/assets/124643236/322cd89d-7ec3-43d0-835f-30dcbf456a96)

- I only see the _shared world was created. _Am I supposed to see ind and team worlds, too?_
![image](https://github.com/lzim/teampsd/assets/124643236/a8b29656-d4e5-4f2b-a8e9-3c1b3a846fe6)

## Create team from Admin Dashboard > Settings > Add, & added 2 members myself as I created the team:
- I only see the _shared world was created. _Shouldn't I also see ind and team worlds, too?_
![image](https://github.com/lzim/teampsd/assets/124643236/5f9e6d35-2293-424f-ae5b-0c41b520f66b)

## Create a team from Admin Dashboard > Settings > Add. 
- I only see the _shared world was created:
![image](https://github.com/lzim/teampsd/assets/124643236/4d0526af-f15d-4f68-a2bd-29dc8b0507c0)
- It does contain the 6 auto-added people:
![image](https://github.com/lzim/teampsd/assets/124643236/83a9bb7b-ccb9-476f-b003-ecf00f6f2962)
### After creating the base team, used Settings > select team > Edit to add members:
- I manually added 2 more:
![image](https://github.com/lzim/teampsd/assets/124643236/065cbe6b-4bcc-4f52-92e2-be8e28d1aea9)
- Only 1 of the 2 people I added show on the _shared team list. _Shouldn't I see James' VA email/member listed here now?_
![image](https://github.com/lzim/teampsd/assets/124643236/4b01572b-9496-4442-8396-57f751aaf7d5)

## Checking against Epicenter:
It looks as though all worlds were made for all 3 teams I created, but that's not what appears in the Sim UI:
![image](https://github.com/lzim/teampsd/assets/124643236/32eec543-b243-4b18-b71d-cc219b4f4297)
- I think there could be issues with 1) seeing created worlds & 2) auto-added people and worlds they are added to. 

fyi: @jamesmrollins @lijenn

**Comment by ljmoody** [comment]
**7/9/24 response from Tejas:**
It appears that there is a conflict during team setup calls, as both of yours VA and Praxis have Administrator login access. We will need to investigate further to determine the root cause, and we will provide you with an update once we have more information.

Note: When we used James's credentials, the setup worked well. Not certain but his VA login Id having non-admin access.

**Comment by jamesmrollins** [comment]
@tejaspesquare please provide a weekending update.  Thank you.

**Comment by tejaspesquare** [comment]
Hello @jamesmrollins
The work is still ongoing. The developer is in the process of troubleshooting the code.

**Comment by tejaspesquare** [comment]
Hello @jamesmrollins , @ljmoody ,

This is got fixed & can be tested on TEST.

Using Laura's VA credentials, Team setup done & all worlds (_Team,_shared & _ind) got created 

![image](https://github.com/user-attachments/assets/d223ed78-11ca-4fb4-8eaf-efdc07f78dba)

Checking Respective Worlds with default Members
1. _team World
![image](https://github.com/user-attachments/assets/d8c83fb1-1e67-48b3-93ed-c095534c79fb)
![image](https://github.com/user-attachments/assets/6de43049-c089-42e2-a511-19dbb814f7ad)

2._shared world
![image](https://github.com/user-attachments/assets/6e4f9271-d183-4fc3-885f-35259f4d87f9)
![image](https://github.com/user-attachments/assets/5eb0cd08-14c2-4659-bc7c-2d4cdcfe09c1)

3._ind world
![image](https://github.com/user-attachments/assets/ace66441-62f6-4d64-ba37-b1eeeeffd009)
![image](https://github.com/user-attachments/assets/0ab4bcfc-2796-471e-b7a2-802957f7c3ed)


**When login with Laura's Praxis credentials, I see _team & _ind worlds accessible**
![image](https://github.com/user-attachments/assets/800a4ea1-5dd9-4099-b77a-b324c7217128)


**When establishing a team without including any team members or appointing a Team Lead**
![image](https://github.com/user-attachments/assets/6207b229-0819-4303-be4c-7249c35d3c45)

![image](https://github.com/user-attachments/assets/be817af0-65b4-4f18-9041-d16a793fb454)


Alos, did team setup using Laura's Praxis credentials, worlds got created as expected
![image](https://github.com/user-attachments/assets/06f47ecb-b50c-4ccb-a069-7f0dd1d812da)



Kindly confirm and inform us if you have noticed any discrepancies. If there are any aspects related to the business requirements that we may have overlooked, please share those details with us too.

**Comment by ljmoody** [comment]
Hi @tejaspesquare - I'll test as you did and outline my experience below. Tested in TEST, Edge browser.
fyi: @jamesmrollins @lijenn @matomasz 

## Test 1: Edge browser, VA login
### Created a team. 
- Created a team via Settings>Facility Team Setup
- Did not add any members/leads/admin - just kept with the default
- I only see _team and _ind worlds were created (via the Sim UI); however, Epicenter shows that all 3 were created
![image](https://github.com/user-attachments/assets/3e2c81fb-33f3-4bc5-a561-acd95eda0890)

### Checked all worlds for default members.
- _IND world:
![image](https://github.com/user-attachments/assets/f1db9928-54be-496f-a559-a7965c236c5b)

- _TEAM world:
![image](https://github.com/user-attachments/assets/a34269ce-2c76-404a-8992-3c640f85e3d6)

- _SHARED world (as shown in Epicenter since not showing in Sim UI):
**I am not listed as a member**
![image](https://github.com/user-attachments/assets/7497972b-edc1-4208-a7e3-a59515059bd4)

### Added myself (Praxis email) as Administrator in _ind and _team worlds.
- Logged in with Praxis credentials
- I also see _shared world - this is correct, since rule is that "Adding a member to _team will automatically add them to _shared and _ind. For this reason, _ind also listed in drop-down."
![image](https://github.com/user-attachments/assets/0b790cd3-e14d-4a8d-9c92-3848834ddcda)

## Test 2: Chrome browser, VA login
### Created a team. 
- Created a team via Settings>Facility Team Setup
- Did not add any members/leads/admin - just kept with the default
- I only see _team and _ind worlds were created (via the Sim UI); however, Epicenter shows that all 3 were created
![image](https://github.com/user-attachments/assets/78f07003-e95e-42f6-b552-3b6c431860bd)

### Checked all worlds for default members.
- _IND world:
![image](https://github.com/user-attachments/assets/90bcd546-93ea-4d57-836e-aff4aff6cfae)

- _TEAM world:
![image](https://github.com/user-attachments/assets/8a382081-d75c-40d8-96c1-122147cdd47e)

- _SHARED world (as shown in Epicenter since not showing in Sim UI):
**I am not listed as a member**
![image](https://github.com/user-attachments/assets/288d7980-a59f-42d7-94cd-6e757eb2f54b)

### Didn't have to add myself (Praxis email) to _ind as it was already populated. 
- **This was not the same user experience as in Edge.**
- Logged in with Praxis credentials
- I also see all 3 worlds; this is correct according to permission rules
![image](https://github.com/user-attachments/assets/164214ca-867b-474f-97a5-2c1f5a546f51)

_I believe I should see the _shared world upon team creation since I am an Administrator and am listed in all 3 worlds in Epicenter, correct?_

## Test 3: Chrome browser, Praxis login
### Created a team. 
-default members only; did not add any
![image](https://github.com/user-attachments/assets/aa16dd9d-b84f-464c-a65a-888044f07456)

### Checked all worlds for default members.
- _IND world:
![image](https://github.com/user-attachments/assets/5c263412-8221-410d-9946-943788c4f6d7)

- _TEAM world:
![image](https://github.com/user-attachments/assets/570c4482-9a51-4719-84b9-39326854aa3e)

- _SHARED world (as shown in Epicenter since not showing in Sim UI):
![image](https://github.com/user-attachments/assets/96207512-b16e-4a20-8f94-1a14ea8cac06)

**Note:** It is odd to me that under my Praxis login, I am auto added twice (once with VA email, once with Praxis email) onto all teams. Versus under my VA login, where I am auto added once to _ind and _team, but not to _shared.

**Comment by ljmoody** [comment]
@tejaspesquare -Jenn and I tested this together in PROD instance today - I used Edge, she used Chrome. We both experienced the same issues outlined below:

![image](https://github.com/user-attachments/assets/8c6162fc-76b7-423f-8eab-b171709068ab)

- When we each created a team and did not specify a team lead, the only team worlds created that we could see were _ind and _team. (But we could each see all 3 worlds that the other had created.)
- When we created a team and DID specify a team lead, we could see all 3 worlds were created. 
- Interestingly, the default_team_lead@mail.com user was ONLY added to worlds in which we added a specified team lead. Leads me to think the default user is not being added to all teams, but to teams with leads. Please check into this.
- Also, we both could not see _shared worlds in which we did not specify leads. So there is some type of connection between specifying a lead and not

fyi: @jamesmrollins

**Comment by ljmoody** [comment]
8/2/24 update from Tejas:
- Code migrated from DEV to TEST environment. Ready to test.
fyi: @lijenn @matthewtomo

**Comment by lijenn** [comment]
@lijenn verified in TEST on Chrome that the Team Lead default account is added to all 3 worlds and adding field user Team Leads are behaving as expected (has access to _team and _ind, not _shared).

To Do:
- [ ] Test in Edge browser

**Comment by ljmoody** [comment]
@ljmoody verified in TEST on Edge that:
- all 3 worlds are created
- default team lead account is added to all 3 worlds
- Team Lead (field user) sees _team and _ind worlds available to select when logging in (not shared)

@matthewtomo - I think this is ready to migrate. 🚀

**Comment by matthewtomo** [comment]
Discussed sim_ui_workflow wk_3_08
@matthewtomo @lzim @jamesmrollins @lijenn 

- The fix for this bug has been verified in TEST and pushed to PROD.
- Marking this issue as closed.
