### ISSUE TITLE
2024_07: Migrate TeamPSD repo's bug & feature status tracker

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3206]
- Team PSD repo's Projects (classic) will be **sunset on August 23, 2024.** Migration should happen before; projects must be enabled to migrate. 
- GitHub article re: [Sunset Notice - Projects (classic)](https://github.blog/changelog/2024-05-23-sunset-notice-projects-classic/)

## AC:
- [x] features migrated
- [x] bugs migrated - bug tracker, status view

**Comment by lijenn** [comment]
Discussed 7/19 Team Praxis Call:
@matomasz @jamesmrollins @lijenn migrated the bug and feature tracker!
