### ISSUE TITLE
2024_10: DEV Sim UI pop-up windows to either floating windows and/or open in a new browser tab

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3207]
## What happens now:
- DDD content is "hidden" by static pop-up windows.
- When users click on icons within the DDD, the associated pop-up windows behave as shown: 
  - Directives: not scalable or movable
  - Feedback Loops: scalable and movable (possibly refine?)
  - Decision Meters: not movable (no need for scalability)
  - Episodes of Care: not movable or scalable; requires scrolling to see the entire window contents

## What is desired to happen:
- When users click on icons within the DDD, they are able to scale (dynamically) the size and content within the pop-up _and_ and move the window to the desired position.

## AC:
- [ ] decide re: behavior of windows (floating or new browser tab?)
- [ ] windows meet design intent

**Comment by lijenn** [comment]
Needs to be discussed and whether or not we can triage given current Prod bugs at wk1 2024_08.

**Comment by lijenn** [comment]
Discussed sim_ui_workflow 8/7:
@matthewtomo @jamesmrollins @ljmoody @lijenn
- [ ] After PROD bugs and CI/CD instancing is fixed, @matthewtomo will get an estimate from Dev on this feature and/or work on the development work

**Comment by matthewtomo** [comment]
**Discussed DEV standup 8/9/2024**
@matthewtomo @tejaspesquare 

- @tejaspesquare will talk to the designer to help get a better estimate on the hours required for this task, and will report back here.

**Comment by tejaspesquare** [comment]
Hi @matomasz 

> * @tejaspesquare will talk to the designer to help get a better estimate on the hours required for this task, and will report back here.

1.Directives-not scalable or movable:  We are currently facing several technical challenges related to Iframe management. The table and data are being set dynamically, and the data presentation is also subject to change. Furthermore, the content varies in appearance across different screen resolutions. 
2.Feedback Loops-scalable and movable (possibly refine?): It appears that there is no room for further enhancement.
3.Decision Meters- not movable (no need for scalability): Floating possible 32hrs (Area covered:DDD & Simulator)
4.Episodes of Care- not movable or scalable; requires scrolling to see the entire window contents: 
   i. scrolling very mich possible for each month box , 
   ii. If we have to handle static data-3hrs 
   iii. If it involves dynamic data - An estimation cannot be made until the known sources of data & the method of access is available

**Comment by matthewtomo** [comment]
**Discussed DEV Standup 8/12/24**
@matthewtomo @tejaspesquare 

- For Directives, dev team is unable to provide an estimate due to the Iframe issues they are facing. This requires more work before an estimate can be made (potentially including exploring alternatives to Iframes)
- For Feedback Loops, the popup can be scaled up, but not scaled down due to support for different screen resolutions.
- For Decision Meters see above.
- For Episodes of Care, does this popup only handle static data, or does it involve dynamic data?

- Looking for guidance on the question for Episodes of Care. @lijenn @ljmoody 

fyi: @lzim @jamesmrollins

**Comment by matthewtomo** [comment]
**Discussed #DEV_Standup**
@matthewtomo @tejaspesquare 

- Time estimates for each task:
  - Directives: not scalable or movable: 
    - Dev team believes this is currently not possible to make scalable or moveable with our current implementation of iframes
  - Feedback Loops: scalable and movable (possibly refine?):
    -  Designer believes this is not currently possible due to the scaling font size (which would shrink too small if the graphic is allowed to be scaled further down)
  - Decision Meters: not movable (no need for scalability):
    - Floating possible (**Estimate 32hrs**)
  - Episodes of Care: not movable or scalable; requires scrolling to see the entire window contents:
    - Possible. Only handles static data (**Estimate 3 hours**)

**Comment by ljmoody** [comment]
This is essentially a duplicate card of #3190. Since that card is tracking the underlying feature development, it makes sense to close this card so communication and syncing is occurring in just one place.

- Kept points as-is for effort given so far on this card.
- Made the following notation twice in 3190 to be sure everyone is aware.

> ℹ️ - similar efforts were being tracked in a duplicate card #3207 (closed today). For historical communication regarding efforts towards this feature, it may be relevant to look at that card. Especially for August 2024 comments/communications.

Closing this card.
