### ISSUE TITLE
2024_07 BUG: Sim UI PROD & TEST Admin Dashboard Select Module dropdown not working correctly

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3209]
## What happens now:
- Discovered 7/12/24.
- Laura tested on Edge browser, TEST instance, VA laptop, using 12july_laura_team world, experiment: Q8_EPRVI_as_12_rfr_3.5_srwt_0.8
- Jenn tested in PROD (using a BC experiment in the MM module for her 123_a0_aqua_jenn_team) and experienced the same.

1. I created an experiment in the CC module: 
![image](https://github.com/user-attachments/assets/1679c907-94fe-44d0-aa18-2d0ddb27f566)

2. When I return to the Admin Dashboard, the "Go to Current Session" is grayed out:
![image](https://github.com/user-attachments/assets/072e3ead-e658-4536-b957-f0861e06ce58)

## Expected behavior:
- After a user saves an experiment in the Sim, when they return to the Admin Dashboard and make a selection from the Select Module dropdown, the Go to Current Session button should activate, allowing the user to go back into that module.

**Comment by lijenn** [comment]
Discussed 7/19 Team Praxis Meeting:
- [ ] Since all modules are run/initialized in the DDD, @tejaspesquare please remove the Go to Current Session button in the Admin Dashboard
<img width="909" alt="image" src="https://github.com/user-attachments/assets/a55f8cce-a7ca-41f8-b005-e6afe417ab6f">

**Comment by matomasz** [comment]
Discussed 7/22 Dev Standup Call:

- Button has been removed locally
- Change is under review and will be ready for the test environment by tomorrow

**Comment by tejaspesquare** [comment]
@lijenn , @matomasz,

This has been fixed & can be verified on TEST.
![image](https://github.com/user-attachments/assets/237b3fd8-5992-44d3-b8e6-93d8d5445c70)

**Comment by lijenn** [comment]
Thanks @tejaspesquare! I believe we can remove the "Select Module" button too, right?
![image](https://github.com/user-attachments/assets/aa6c735c-3386-4eb0-8119-269cdb6ef4fb)

If I recall correctly, there is no relationship between this button and what experiments are showing in the Admin Dashboard because all experiments for a group, regardless of the module the experiment was created in, will show.
![image](https://github.com/user-attachments/assets/4fb3b5be-bac0-4ce9-aba3-98e8af146d8b)

@matthewtomo 
@jamesmrollins 
@ljmoody

**Comment by tejaspesquare** [comment]
Hello @lijenn,
 
> Thanks @tejaspesquare! I believe we can remove the "Select Module" button too, right? 

Yes, now it's of no use. We will remove it.

> If I recall correctly, there is no relationship between this button and what experiments are showing in the Admin Dashboard because all experiments for a group, regardless of the module the experiment was created in, will show. 

You are correct!

**Comment by matthewtomo** [comment]
**Tested on 8/5/2024**

## Chrome:
![image](https://github.com/user-attachments/assets/c653683e-6382-40ed-bc10-b9e82d4a0285)
## Edge:
![image](https://github.com/user-attachments/assets/da5da98a-f058-4208-ba7f-6e200ba590ab)

Button and Dropdown are removed in TEST

fyi: @lijenn @ljmoody

**Comment by ljmoody** [comment]
**8/14/24:** ✅ verified that these changes were pushed to PROD.
Closing this because what wasn't functioning is no longer part of the Sim UI with work done on this card.
