### ISSUE TITLE
2024_08 ANDON Sim UI PROD: Lindsey Adm login - MTL 3.7 Blue Live consult at 8AM today (data no longer available)

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#3211]
**#systems_sme_workflow - wk3 2024_07**
@dlkibbe 
@lzim

### MTL Blue Live consult Tue 07/16
- [x] Previously prepared a use case for [research/572](https://github.com/lzim/research/issues/572)
- [x] Logged in using administrator
- [x] Navigated from Admin Dashboard to home button for this site.
- [x] Dynamic Decision Dashboard cannot find the data file used to prep this consult on 06/24/24.
**Cannot find the data file in either location by search or sort.** 
   - **_Screenshot 1:_ Note that the DDD indicates that experiments were run and saved.** 
   ![image](https://github.com/user-attachments/assets/a411141d-63e3-4ba5-8c96-141177b3b9fb)
   - **_Screenshot 2:_ Note that sorting the  data in the Data Section all have the same date of May 6.**
   ![image](https://github.com/user-attachments/assets/5206519a-d9e0-4a44-89ed-532c5fbd7e42)

**Comment by jamesmrollins** [comment]
@lijenn @dlkibbe @lzim 

Is this the file you are looking for??

![image](https://github.com/user-attachments/assets/24c400d2-afba-41a0-b4fe-d1ad72fc1ca6)

**Comment by dlkibbe** [comment]
![Palo Alto sim ui screenshot 2024_07_16](https://github.com/user-attachments/assets/2785a3a8-edb8-4adc-aa83-489345d70049)

**Comment by lzim** [comment]
- [ ] Need option for new user join a team world in progress
- [ ] Need intuitive **Upload** to Add distinctions.

v21_640by_sj

![image](https://github.com/user-attachments/assets/5268ff89-593f-4654-86bb-6d629f209530)

**Comment by lzim** [comment]
Thanks for joining us today @jamesmrollins

**Comment by jamesmrollins** [comment]
@lzim @ljmoody 

The user-registration issue is interesting, since we have a dropdown for existing teams for the user to select from.  Yet it doesn't show above.  Thanks @lzim for the screen capture.  We'll look into it.

**Comment by ljmoody** [comment]
@lzim @jamesmrollins 

Self registering users **do have the ability** to join existing teams. The screen _before_ the one pictured above is where users join an existing team, via the "Select or Create a Facility Team" dropdown:
![image](https://github.com/user-attachments/assets/7aa3df68-9543-4837-ad4a-8ede47e29e49)

I created #3213 today, which includes both items identified by Lindsey above. I think a refinement to the dropdown will help with this specific one.

**Comment by tejaspesquare** [comment]
Hello @lzim , @jamesmrollins,

just FYI-
Logged in with @lzim credentials, I could locate desired file in both sections "Team Data" & "Session start" 

![image](https://github.com/user-attachments/assets/c554f7ca-f61a-4df4-a3fb-8887abe46b02)

Go to simulation page for a Model (MM) 
![image](https://github.com/user-attachments/assets/30fb1825-9411-42ca-9db6-09cbe6911801)

Came back to Home Screen (without Model Run) 
![image](https://github.com/user-attachments/assets/483a4700-1d2f-4a47-a8c3-bf36dbfdadd3)

It is possible that the model binding was delayed and therefore could not be found in the Section 'Session start' .

**Comment by lzim** [comment]
@tejaspesquare - Not sure what specifically is meant by 'model binding' in this context. But, you're rate, it was a delay/latency issue of the files becoming available. I would say approximately 15 minutes worth of walking it through and taking screenshots before the data files became available. 

> It is possible that the model binding was delayed and therefore could not be found in the Section 'Session start' .

FYI: @jamesmrollins

**Comment by lijenn** [comment]
Discussed 7/19 Team Praxis Call:
- [ ] @matomasz will ask for follow-ups on this latency issue with @tejaspesquare, might be related to the console errors in #3220

**Comment by matomasz** [comment]
Discussed 7/22 Standup with Dev:

-  This bug is hard to reproduce, which is making it harder to address
- @matomasz will attempt to produce the bug today, and provide screenshots of any errors in the console

**Comment by matthewtomo** [comment]
**Discussed support_workflow**
@ljmoody @lijenn @matthewtomo 

- We noticed that some images in this issue history contain team names that might need to be censored.
- Pictures are currently being edited by @ljmoody and comments will be updated shortly.

**Comment by lijenn** [comment]
Discussed 8/2 @ljmoody @lijenn:
Keeping this is 2024_08 since the issue still occurs, but we have not been able to reproduce it or capture the console log.

**Comment by lzim** [comment]
Yes. Thanks!

> Would it be worthwhile to create a log of when files are uploaded/deleted so that we can track when changes like this occur?

**Comment by matthewtomo** [comment]
**Discussed Dev Standup8/14/2024**
@matthewtomo @tejaspesquare 

- [X] Dev team would require a GitHub token to handle the logging information in the GitHub Repo
- Hours estimate for this task: 16 hours

**Comment by lzim** [comment]
**wk3 2024_08 ** #9am_workflow leads*
@lzim
@lijenn 
@matthewtomo 
@dlounsbu 

**Discussed that this is a "Nice" to have, not "need" to have.**
**DECISION:**
- [x] @dlkibbe & @dlounsbu & @matthewtomo & @ljmoody - Yes, there are known data file latency issues. But, if we know that we can proceed because it hasn't replicable enough to capture a console or anything.


**This is an example of a vulnerability that creates rework and overwork - Cross-ref: #3160 .**
> It would allow us to identify if the file disappeared randomly or if it was deleted by a user.
