### ISSUE TITLE
2024_07: BUGS: Self registration only creates _ind & _team worlds + "looks" like new users are forced to create a new facility team

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3213]
Discovered 7/16/2024. 

### 1. When users self register, only _ind and _team worlds are created. They need _shared as well.
- Used my personal email to self register and created my own team:
![image](https://github.com/user-attachments/assets/1bdc2107-a8d4-4a78-9432-099b6c682008)

- Upon approval and logging in with those credentials, I only see _ind and _team:
![image](https://github.com/user-attachments/assets/59dc2e6e-4914-4953-9b50-0846c244e063)

### 2. When a person self registers, appears as if they "should" or are "forced" to create a new team because of dropdown choice order. User experience should be easier to check for and join existing teams. 
- When self registering, users see "Create New Facility Team" at top of dropdown. If they're in a hurry, don't take time to read instructions, or don't realize this is a dropdown with choices, they will inadvertently create a new team.
- The wireframe stipulates that pre-existing teams will be available to select from the narrowed-down VISN & Facility choices:
![image](https://github.com/user-attachments/assets/b364c171-4c5f-41ba-aa4b-e5bd8b13b5dd)
- In the wireframe, the "Create New Facility Team" option is at the bottom of the dropdown list of available teams (see above). Right now, it is the top option on the list. 
![image](https://github.com/user-attachments/assets/a1dafbec-4916-4e4a-864a-52c2b047df82)

### 1. Field users need access to the _shared world as well.
- @tejaspesquare - *action item:* create _shared world (in addition to _ind and _team) when a self-registering user creates a new Facility Team.
### 2. Self registration supports registering a new user with an existing group with ease.
- @tejaspesquare  - *action item:* Bump "Create New Facility Team" option to the end of the filtered list so users are less likely to create a new team.

**Comment by lzim** [comment]
Thanks @ljmoody 💪🏽

**Comment by tejaspesquare** [comment]
@ljmoody,

We have introduced a popup indicating user that either use existing team or select choice to establish new team.  This is moved to Prod as we had to move feature for adding default member while doing Team Setup.

Self Registration- 
1.User is filling up the registration form
![image](https://github.com/user-attachments/assets/b4135634-29a5-4362-b717-dba84063ecb0)

2.In the event that the user does not click on the Select Facility Team Dropdown but clicks on Submit, a message will be displayed to offer guidance.
![image](https://github.com/user-attachments/assets/7470d2e5-295c-4e98-b26f-bea208ad9709)

**Comment by lzim** [comment]
Thanks @tejaspesquare and @ljmoody 😸 !

In the last screenshot of the menu above, we need to make the **Select Facility or Create New Team** the top top chunk of this **Team and Account** menu. 

Recommended Reworded Menu Title: "Team and Account" 

Order of menu should be Team Sections first, then Account:
01. "Select Facility or Create New Team" (note this rewording)
02. VISN Facility Clinic
03. Select VHA Primary Role
04. First Name (etc. through Account creation)

**Comment by lzim** [comment]
### To approve access, we need to get the menu information included in the approval email sent to mtl.help@va.gov 
@jamesmrollins 
@lijenn
@ljmoody 
@matomasz 
@tejaspesquare 

#### Current State: This email does not provide enough information to approve:
![image](https://github.com/user-attachments/assets/e24b5b7d-9be8-4440-a7b4-3ecc970fa9e9)

#### Desired State: The information from the menu is in the email for review and approval.

We'll need all of the information from the menu in order to know whether to approve the access:
Existing team or New
VISN Facility Team
Role
Name
Email etc.

**Comment by lzim** [comment]
Edit: "If one exists, please use your facility team. Or, start a new team."

**Comment by tejaspesquare** [comment]
Hello @ljmoody, @ljmoody, 

We have incorporated the suggested changes, and they are available for verification on the test environment.

![image](https://github.com/user-attachments/assets/7d67e5c9-4f99-448c-9df8-583e99d70a01)
![image](https://github.com/user-attachments/assets/5825a4ad-5d6a-411d-9e7c-18a51e5b757a)

**Comment by ljmoody** [comment]
@tejaspesquare - excellent work incorporating all of those changes. 👏 

- [ ] Please reorder the first two fields as shown based on the rationale below:
![image](https://github.com/user-attachments/assets/b959b181-9695-40c5-981f-87b25c798a59)

@lzim: While testing, I discovered that the Select Facility Team dropdown and the Create New Team pop-up depends upon the VISN & Facility dropdown choices made by the user. Users would not see any dropdown choices of existing teams if they have not already selected a VISN + Facility. Same with the Create New Team pop-up - the pre-populated information would not exist nor be correct without having made selections in the dropdowns first.

**Comment by tejaspesquare** [comment]
Hello @ljmoody ,

> * [ ]  Please reorder the first two fields as shown based on the rationale below:

Changes implemented.
![image](https://github.com/user-attachments/assets/4bea35e0-1c96-4ca4-acf1-6993e8250897)

**Comment by lijenn** [comment]
Discussed 7/19 Team Praxis mtg:
- [ ] @matomasz verified that the VISN, Facility, Clinic columns are first followed by Select Facility and Create New Team
- [ ] @lijenn will check if the MTL Help Approval email contains the details for a new registered user

**Comment by matomasz** [comment]
The order of the fields now looks correct in the test environment. Additionally, if the user presses the submit button before selecting a facility or creating a new team, the pop-up uses @lzim's revised language.
![image](https://github.com/user-attachments/assets/e9d808c1-8ac6-4718-a05f-f2fd41f22d3a)

**Comment by lzim** [comment]
Great work @tejaspesquare & @matomasz and All - thank you!

Would be great to have in production **wk1 2024_08** - if possible. 
FYI: 
@ljmoody 
@jamesmrollins 
@lijenn

**Comment by ljmoody** [comment]
@matthewtomo & @tejaspesquare,

_What do you think about possibly adding a "Select" field to VISN and Facility fields (like Clinic)?_  The current design defaults VISN as V1 and Facility at 402, leading to a list of possible v1_402 team name if someone clicks Create New Team:
![Image](https://github.com/user-attachments/assets/c8b305d1-66be-441e-b28e-ecb6a87d363a)

---
### Tested for whether email contains the details for a new registered user (TEST instance of registration):
- in Tejas' comment above, screenshot shows registration email with details sent to mtl.info
- [ ] @tejaspesquare, please ensure registration request emails are sent to **mtl.help@va.gov** (not mtl.info@va.gov)

1. New user, registered with an existing team
   - received green "sent to MTL for approval" screen message
   - no email confirmation was sent (checked both .help and .info inboxes)
![Image](https://github.com/user-attachments/assets/bfa05d59-916a-44a4-8630-4677a16c9c50)

2. New user, first to register from my Facility Team 
   - received green "sent to MTL for approval" screen message
   - no email confirmation was sent (checked both .help and .info boxes)
   - **Observation:** when registering under condition 2 above, when the "looks like you are the first person to register" pop-up shows and a user completes the facility's team name and clicks Submit, there is no feedback given, nor does the Select Facility or Create New Team dropdown populate with the newly created team's name. _Could / Will this confuse registering users?_ 
![Image](https://github.com/user-attachments/assets/a09553b7-cdf0-42f8-9d66-e6e39c13e992)

**Comment by tejaspesquare** [comment]
Hello @ljmoody, @matthewtomo,

Changes are incorporated & can be verified on Dev instance. 

> _What do you think about possibly adding a "Select" field to VISN and Facility fields (like Clinic)?_ The current design defaults VISN as V1 and Facility at 402, leading to a list of possible v1_402 team name if someone clicks Create New Team: 

![image](https://github.com/user-attachments/assets/e97a512c-6a7b-4f2e-9c87-e56efbaa076b)
![image](https://github.com/user-attachments/assets/4857067f-cabc-4b0e-a5d0-38d2cf538055)
![image](https://github.com/user-attachments/assets/fb8688d6-d490-4884-8fb8-bb54fb48c497)


> * [ ]  @tejaspesquare, please ensure registration request emails are sent to **[mtl.help@va.gov](mailto:mtl.help@va.gov)** (not [mtl.info@va.gov](mailto:mtl.info@va.gov))

![image](https://github.com/user-attachments/assets/cbe4c5bd-d998-4607-94fb-d27ab1df1733)


> 1. New user, registered with an existing team
>    * email was sent to personal email used to register saying user has been registered and contained team name, VISN/facility/clinic, role, name, and email -- _who approved the request?_

For Approval notification you will have different ID 
![image](https://github.com/user-attachments/assets/13ea1e9a-c929-4009-8834-d61e8636c1f9)

After Approval Registered user get notification-
![image](https://github.com/user-attachments/assets/565d5936-d08d-45b9-9d5f-32e60ebd99d4)


> 2. New user, first to register from my Facility Team

>    * **Observation:** when registering under condition 2 above, when the "looks like you are the first person to register" pop-up shows and a user completes the facility's team name and clicks Submit, there is no feedback given, nor does the Select Facility or Create New Team dropdown populate with the newly created team's name. _Could / Will this confuse registering users?_

![image](https://github.com/user-attachments/assets/889a43c4-7b1c-4b36-9de1-933d3e8f9a9c)

Thanks!

**Comment by matthewtomo** [comment]
**Discussed DEV Standup 7/29/2024**
@matthewtomo @tejaspesquare 

- Dev is currently ensuring registration request emails are sent to [mtl.help@va.gov](mailto:mtl.help@va.gov) (not [mtl.info@va.gov](mailto:mtl.info@va.gov))
- Currently, Dev instance sends Acceptance/Rejection emails after registration is approved/denied. Is this the correct behavior?
  - Acceptance Email: ![image](https://github.com/user-attachments/assets/802829df-986b-4c4f-88c0-438f38a2433a)
  - Rejection Email: ![image](https://github.com/user-attachments/assets/3917d5c3-7341-40c3-9e94-b9d2d7bc66b7)

fyi: @jamesmrollins @lijenn @ljmoody

**Comment by matthewtomo** [comment]
Discussed in DEV Standup 8/1/2024
@matthewtomo @tejaspesquare

- The dev team needed to create a Forio account for the mtl.help@va.gov before they could use it as the email for registration approval.
- An invite has been sent to the mtl.help@va.gov email that needs to be accepted.
- After the invite is accepted they should be able to use the mtl.help@va.gov email for registration approval.

fyi: @jamesmrollins @lijenn @ljmoody

**Comment by lijenn** [comment]
@tejaspesquare @matthewtomo I accepted the invite from mtl.help@va.gov. Thanks!

**Comment by matthewtomo** [comment]
@lijenn Thank you!

- Could you put "Modeling to Learn" as the first name.
- Is there a standard password for the mtl.help account you can use?

**Comment by ljmoody** [comment]
8/2/24 update from Tejas:
- Code migrated from DEV to TEST environment. Ready to test.
fyi: @lijenn @matthewtomo

**Comment by matthewtomo** [comment]
**Tested 8/5/2024** in TEST on Chrome on Non VA Machine.

- When registering through self registration portal, the approval email is incorrectly being sent to the self registration user's email.
- The approval email should be sent to the mtl.help@va.gov email address.

![image](https://github.com/user-attachments/assets/0b56b60b-feef-494b-ae39-13bab1e31bf4)

fyi: @tejaspesquare @lijenn @ljmoody

**Comment by tejaspesquare** [comment]
Hello @matomasz,
 
> * When registering through self registration portal, the approval email is incorrectly being sent to the self registration user's email.
> * The approval email should be sent to the [mtl.help@va.gov](mailto:mtl.help@va.gov) email address.

This configuration has been intentionally retained as it relates to a live address, and David has requested to use of the internal ID, as otherwise notification being sent to his team. However, this issue will not arise in the production environment. If you still wish to conduct a round of testing with the live ID, we can arrange the setup. Kindly let me know. 

![image](https://github.com/user-attachments/assets/e104b152-7ba0-4aaa-9c87-a71bcf9006c6)

**Comment by tejaspesquare** [comment]
> Hello @matomasz,
> 
> > * When registering through self registration portal, the approval email is incorrectly being sent to the self registration user's email.
> > * The approval email should be sent to the [mtl.help@va.gov](mailto:mtl.help@va.gov) email address.
> 
> This configuration has been intentionally retained as it relates to a live address, and David has requested to use of the internal ID, as otherwise notification being sent to his team. However, this situation will not arise in the production environment. If you still wish to conduct a round of testing with the live ID, we can arrange the setup. Kindly let me know.
> 
> ![image](https://private-user-images.githubusercontent.com/144898781/355329663-e104b152-7ba0-4aaa-9c87-a71bcf9006c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MjQ0NjAsIm5iZiI6MTcyMjkyNDE2MCwicGF0aCI6Ii8xNDQ4OTg3ODEvMzU1MzI5NjYzLWUxMDRiMTUyLTdiYTAtNGFhYS05Yzg3LWE3MWJjZjkwMDZjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQwNjAyNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZWEzYjQ1NzY2ZjM0NTY0NWQxOWFhNmJhNTI1Yjk4MTA0YjU2YjMzMWI4M2IwODRmYTgzZDRjNDZmOGNmYzkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.w1HDNpaqAgaXLdi9OJSdAougVz4Qz7B9sfAlCnEcu94)

**Comment by matthewtomo** [comment]
**Tested 8/8/2024 & 8/9/2024** in TEST on Chrome on VA Virtual Desktop.

- When registering through self registration portal, the approval email is now correctly being sent to the mtl.help@va.gov email address.

![image](https://github.com/user-attachments/assets/e06a73dc-9aa9-40f5-be44-87db4ecdb495)

fyi: @tejaspesquare @lijenn @ljmoody

**Comment by matthewtomo** [comment]
**Discussed 8/20/24**
@matthewtomo @jamesmrollins 

- Issue has been addressed in code and pushed to PROD
