### ISSUE TITLE
2024_07: BUG: PROD instance doesn't allow DDD access from Admin Dashboard for newly created teams

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3214]
Discovered 7/16/24 in PROD instance
Tested with both Chrome and Edge; both the exact same behavior. 
fyi: @dlkibbe @dlounsbu @lzim: SME impact is minimal; this can interrupt your ability to create a new team and access the DDD. It should not impacts accessing the DDD for existing teams.
 
## Current behavior:
Upon creating a team-today-within the Admin Dashboard, I select it from the Select Team dropdown menu, then click Home. I am unable to access the DDD and receive this message:
![image](https://github.com/user-attachments/assets/8d21d856-1c22-4992-aa74-83fbba1ad59a)

## Desired behavior:
Once a team is created in the Admin Dashboard, if that team is selected via the Select Team dropdown menu, and the user clicks Home, they should be directed to the DDD. 
**This behavior is observed in the current TEST instance, both browsers.**
@tejaspesquare - please update ASAP with timeline to push TEST behavior to PROD.
![image](https://github.com/user-attachments/assets/41e381c4-6da3-4499-91ad-3c912ab2ac0c)

**Comment by tejaspesquare** [comment]
@ljmoody 

This is working now.
![image](https://github.com/user-attachments/assets/0a35a304-5336-4395-8874-b4953958995a)

Thanks!

**Comment by ljmoody** [comment]
✅ verified via testing in PROD today and yesterday, with several teams, that the Admin Dashboard allows access to DDD for newly created teams.
Closing this card!
