### ISSUE TITLE
2024_09: FEATURE Sim UI PROD: User is unable to log into Sim UI if they have enabled two factor authentication for their enduser account

### ISSUE THREAD

**Issue by matomasz** [lzim/teampsd#3217]
Discovered 7/17/2024

## Current behavior:
- When setting up an enduser account for the Sim UI, users are given the option to turn on two factor authentication.

![image](https://github.com/user-attachments/assets/54e9d6df-b178-4a3d-bbfb-a436492aaceb)

- If they enable two factor authentication and attempt to login to the Sim UI, the login will fail and the following error can be found in the console.

![image](https://github.com/user-attachments/assets/6b085421-35c8-4bd7-a84b-e66b781ddfaf)

## Desired behavior: 
- [ ] Provide users who set up two factor authentication for their enduser account a way to log in using their two factor credentials. **OR**
- [ ] Users should not have the option to enable two factor authentication when setting up their enduser account.

This issue will probably need to be discussed between @jamesmrollins, Dev team, and David Berkman from Forio.

**Comment by lijenn** [comment]
Discussed 7/19 Team Praxis Call:
- [ ] @matomasz will continue to investigate this with @tejaspesquare and will assign an estimate

**Comment by matomasz** [comment]
Discussed 7/22 DEV Standup Call:

- Clarified that the first screenshot is what end user sees after accepting email invite from Epicenter
- @matomasz will email David from Forio about finding documentation for multifactor auth feature

**Comment by matthewtomo** [comment]
@tejaspesquare I believe that I found the missing documentation that I was looking for here: https://forio.com/epicenter/docs/public/api_adapters/generated/auth/auth-manager/

**Comment by lijenn** [comment]
@ljmoody @lijenn thinks we could de-prioritize this bug given other more urgent Prod bugs. We'll bring it up in wk1 2024_08 meetings, thanks!

**Comment by matthewtomo** [comment]
**Discussed DEV Standup 8/5/24**
@matthewtomo @tejaspesquare 

- Documentation is unclear for how to use two factor authentication tokens: https://forio.com/epicenter/docs/public/api_adapters/generated/auth/auth-manager/
- DEV needs clarification on how two factor authentication tokens with the v2 or v3 versions of the Forio API.
- @matthewtomo will reach out to David from Forio to clarify on the best documentation for this feature.

**Comment by lijenn** [comment]
Discussed sim_ui_workflow 8/7:
@lijenn @jamesmrollins @ljmoody @matthewtomo 
- This is a feature that needs to be added and is triaged to 2024_09

**Comment by matthewtomo** [comment]
#Decision 8/21/2024
@matthewtomo 

- Users never encounter the "Complete your Registration" screen with our current user workflow and are never given the option to enable 2-fa (two factor authentication)
- This screen was only encountered due to manually adding an account for a DEV team member directly in epicenter.
- It may be worthwhile to add 2-fa as a feature in the future, but this bug currently can not affect any real users.

- Suggest moving this issue to the ICEBOX or Closing.
