### ISSUE TITLE
1.7.9 Team PSD Web Page

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#324]
Here are some ideas regarding the team web page.  Thank you @dlkibbe for the paragraph describing Team PSD.  All other words are just placeholders.  Same with pictures.  Like _MTL_, the idea is to make it easy to update for the webmaster using an admin page.  So it is a relatively uncomplicated layout consistent style-wise with _MTL_.  The map is problematic with respect to future edits, but perhaps a google maps solution might work. Certainly, I will need a listing of everyone who is going to have a bio, the bio, and portraits other than the ones you see on the page. 

![image](https://user-images.githubusercontent.com/30132017/55259416-ce004280-5222-11e9-843b-3163a86816df.png)
![image](https://user-images.githubusercontent.com/30132017/55259446-e7a18a00-5222-11e9-94e3-d8127a315f47.png)
![image](https://user-images.githubusercontent.com/30132017/55259476-fbe58700-5222-11e9-9c04-b008072fba83.png)
![image](https://user-images.githubusercontent.com/30132017/55259496-0a33a300-5223-11e9-9c1d-031f0ed962e0.png)

**Comment by lzim** [comment]
Thanks @jamesmrollins !!

@staceypark Can you provide the full list of Team PSD partners 😄 Thanks!

**Comment by staceypark** [comment]
@jamesmrollins here's the initial list of teampsd members.
I'll be checking them off as I get their headshot + bio

- [ ] Azevedo, Kathryn J.  
- [ ] Barlow, Donald L.  
- [ ] Bowling, Elizabeth D.  
- [ ] Branscomb, Jane M.   
- [ ] Collie, Claire  
- [ ] Dismuke, Clara E. 
- [ ] Dolin, Lara K. 
- [ ] Hier, Ann B.  
- [ ] Hong, Savet  
- [ ] Hunt, Marcia 
- [ ] Iwamasa, Gayle Y. 
- [ ] Kibbe, Debra L.  
- [ ] Kimerling, Rachel E. 
- [ ] Klocek, John W.  
- [ ] Kramer, Reynold  
- [ ] Lindley, Steven  
- [ ] Lounsbury, David W.  
- [ ] Mathews, Correy 
- [ ] McGovern, Mark P.
- [ ] Moore, Matt 
- [ ]  Mushiana, Swapandeep  
- [ ] Ontiveros, Erik 
- [ ] Park, Stacey D.  
- [ ] Powell, Fawn M.  
- [ ] Rollins, James
- [ ] Rosen, Craig 
- [ ] Rust, Tom 
- [ ] Schmitz, Theresa M.  
- [ ] Trafton, Jodie A 
- [ ] Wiechers, Ilse 
- [ ] Wiltsey-Stirman, Shannon  
- [ ] Yu, Wei 
- [ ] Zimmerman, Lindsey E.

**Comment by lzim** [comment]
Thanks @staceypark!

I’m organizing into workgroups and roles for @jamesrollins

I removed Wei since he just retired :smile:

So we have 40 total

**Comment by jamesmrollins** [comment]
A full PDF can be found at https://github.com/lzim/teampsd/tree/master/sim_ui_workgroup/mtl_1.8

![image](https://user-images.githubusercontent.com/30132017/55764535-cc076200-5a20-11e9-9432-9271638f9836.png)

**Comment by staceypark** [comment]
@jamesmrollins We decided to go with 4 separate maps. I reordered the list to reflect the new groupings and headings

**Comment by jamesmrollins** [comment]
We have completed the infrastructure for the TeamPSD website.  

1. Team page is now accessible in DEMO/TEST 
https://forio.com/app/va/va-psd-test-demo/teampsd.html

2.  Admin Dashboard Page URL: 
https://forio.com/app/va/va-psd-test-demo/login.html
            
3.  Regarding image files for slider and team member portraits - they must be placed into folders on:
https://forio.com/epicenter/va/va-psd-test-demo/static/files/DynamicData/Admin/Team%20PSD

Once in the folder, their filenames are entered into the Admin panel in the appropriate field.

4.  Regarding the What We Do Section, icon images must be placed into the What We Do folder at:
https://forio.com/epicenter/va/va-psd-test-demo/static/files/DynamicData/Admin

Once in the folder, their filenames are entered into the Admin panel in the appropriate field.

I will begin provisioning the team page using the bios and portraits we have received.

**Comment by lzim** [comment]
Awesome work @jamesmrollins 

Catching up on GitHub tasks now. Checking these out will be on my short list :apple

**Comment by lzim** [comment]
Hi @jamesmrollins 

@staceypark and I reviewed this today: https://forio.com/app/va/va-psd-test-demo/teampsd.html 
The Facilitators map with photos is looking good 😃 

1. Request to separate MTL Demo from Team PSD projects at the Epicenter Level. Recommend act we have DEV, TEST, PROD for the Sim, the Demo page and the Team Page separately.
Preferred:
DEMO: https://forio.com/app/va/va-psd-demo/mtl_demo.html
TEAM: https://forio.com/app/va/va-psd-team/teampsd.html

2. Attempts to review Epicenter Admin dashboards here: https://forio.com/app/va/va-psd-test-demo/login.html
![demo_admin](https://user-images.githubusercontent.com/7454688/56447995-a56ae600-62c0-11e9-97d8-7213e09f124c.png)

Is prompting a "world"  dialogue that doesn't advance for us to review the backend for provisioning
![world_dialogue](https://user-images.githubusercontent.com/7454688/56448004-bae01000-62c0-11e9-8250-1155b87f61c4.png)

3. Related to URL change:  get this to indicate "Team" or "Team PSD" rather than MTL Demo (see right "MTL Demo" tab screenshot): 
![team](https://user-images.githubusercontent.com/7454688/56447661-8408fa80-62be-11e9-8740-666e2de9f869.png)

4. Need smaller maps in the sliders, so that there is more white space/margins on the side. We do know you want to fit lots of images on the maps, but without the white space it feels crowded.

5. Narrow down to the four maps and four colors indicated above by @staceypark 
The border on the images below "Team PSD" need to match their maps above. For example, I should have a blue circular border for "Facilitators")

> @jamesmrollins here's the initial list of teampsd members.
> I'll be checking them off as I get their headshot + bio
> 
> **Facilitators** (blue)
> 
> * [x]  Branscomb, Jane M.  - Atlanta, GA
> * [ ]  Collie, Claire - Durham, NC
> * [ ]  Hunt, Marcia - New Haven, CT
> * [ ]  Klocek, John W. - Waco, TX
> * [ ]  Iwamasa, Gayle Y. - Lafayette, IN
> * [x]  Kibbe, Debra L. - Atlanta, GA
> * [x]  Lounsbury, David W. - Bronx, NY
> * [ ]  Moore, Matt - Oakland, CA
> * [ ]  Park, Stacey D. - Menlo Park, CA
> * [x]  Rust, Tom - Boston, MA
> * [ ]  Schmitz, Theresa M. - Philadelphia, PA
> * [ ]  Zimmerman, Lindsey E. - Menlo Park, CA
> 
> **Workgroup Leads** (green)
> 
> * [x]  Azevedo, Kathryn J. - Menlo Park, CA
> * [ ]  Holbrook, Andrew - Boston, MA
> * [x]  Hong, Savet - Menlo Park, CA
> * [x]   Mushiana, Swapandeep - Menlo Park, CA
> * [ ]  Rollins, James - Seattle, Washington
> 
> **Key Partners** (red)
> 
> * [x]  Bowling, Elizabeth D. - St. Louis, MO
> * [ ]  Mathews, Correy - St. Louis, MO
> * [x]  Hier, Ann B. - St. Louis, MO
> * [ ]  Powell, Fawn M. - St. Louis, MO
> * [ ]  Dolin, Lara K. - St. Louis, MO
> * [ ]  Barlow, Donald L. - Menlo Park, CA
> * [ ]  Kramer, Reynold - Menlo Park, CA
> * [x]  Edwards, Leroy - Menlo Park, CA
> * [ ]  Ontiveros, Erik - Menlo Park, CA
> * [x]  Thompson, Tammy - Menlo Park, CA
> * [x]  Dismuke, Libby - Menlo Park, CA
> * [x]  Trafton, Jodie A - Menlo Park, CA
> * [x]  Wiechers, Ilse - Menlo Park, CA
> 
> **Co-Investigators** (purple)
> 
> * [ ]  Kimerling, Rachel E. - Menlo Park, CA
> * [x]  McGovern, Mark P. - Stanford, CA
> * [ ]  Rosen, Craig - Menlo Park, CA
> * [x]  Lindley, Steven - Menlo Park, CA
> * [x]  Wiltsey-Stirman, Shannon - Menlo Park, CA

Thanks!

**Comment by lzim** [comment]
**Facilitators** (blue)

1. * [ ]  Zimmerman, Lindsey E. - Menlo Park, CA
2. * [x]  Lounsbury, David W. - Bronx, NY
3. * [x]  Rust, Tom - Boston, MA
4. * [x]  Branscomb, Jane M.  - Atlanta, GA
5. * [x]  Kibbe, Debra L. - Atlanta, GA
6. * [ ]  Collie, Claire - Durham, NC
7. * [ ]  Hunt, Marcia - New Haven, CT
8. * [ ]  Klocek, John W. - Waco, TX
9. * [ ]  Iwamasa, Gayle Y. - Lafayette, IN
10. * [ ]  Moore, Matt - Oakland, CA
11. * [ ]  Schmitz, Theresa M. - Philadelphia, PA
12. * [ ]  Park, Stacey D. - Menlo Park, CA

**Workgroup Leads** (green)

1. * [x]  Azevedo, Kathryn J. - Menlo Park, CA
2. * [ ]  Holbrook, Andrew - Boston, MA
3. * [x]  Hong, Savet - Menlo Park, CA
4. * [x]  Mushiana, Swapandeep - Menlo Park, CA
5. * [ ]  Rollins, James - Seattle, Washington

**Key Partners** (red)
 
1. * [x]  Bowling, Elizabeth D. - St. Louis, MO
2. * [ ]  Mathews, Correy - St. Louis, MO
3. * [x]  Hier, Ann B. - St. Louis, MO
4. * [ ]  Powell, Fawn M. - St. Louis, MO
5. * [ ]  Dolin, Lara K. - St. Louis, MO
6. * [ ]  Barlow, Donald L. - Menlo Park, CA
7. * [ ]  Kramer, Reynold - Menlo Park, CA
8. * [x]  Edwards, Leroy - Menlo Park, CA
9. * [ ]  Ontiveros, Erik - Menlo Park, CA
10. * [x]  Thompson, Tammy - Menlo Park, CA
11. * [x]  Trafton, Jodie A - Menlo Park, CA
12. * [x]  Wiechers, Ilse - Menlo Park, CA
13. * [x]  Dismuke, Libby - Menlo Park, CA

**Co-Investigators** (purple)

1. * [ ]  Kimerling, Rachel E. - Menlo Park, CA
2. * [x]  Lindley, Steven - Menlo Park, CA
3. * [x]  McGovern, Mark P. - Stanford, CA
4. * [ ]  Rosen, Craig - Menlo Park, CA
5. * [x]  Wiltsey-Stirman, Shannon - Menlo Park, CA

**Comment by lzim** [comment]
@jamesmrollins the ordered list for each map is above. Thanks!

**Comment by staceypark** [comment]
@jamesmrollins added 4 more bio/headshots.
Just need 

- [ ] Lara Dolin: 508 Compliance Specialist
- [ ] Reynold Kramer: member of Veterans Advisory Partnership for Operations and Research (VAPOR)
- [ ] Erik Ontiveros: member of Veterans Advisory Partnership for Operations and Research (VAPOR)
- [ ] Correy Mathews: Employee Education Services partner

@lzim and I decided to move forward with a placeholder for the headshot and for the bio can we put for now - "[Insert name]'s role on TeamPSD is [insert role here - refer above]. Bio coming soon"

Thanks!

**Comment by lzim** [comment]
@jamesmrollins and @staceypark 

I will see if Erin can help me extract a headshot for Ren and Erik from the VAPOR videos like we did once for Andrew. Then, we'll only be short two photos.

**Comment by lzim** [comment]
@jamesmrollins and @staceypark 

I will see if I can update the recently received HSRD grant to the DEMO site through epicenter on my own...stay tuned 📺

**Comment by lzim** [comment]
@jamesmrollins 

Per our call, let's draft instructions to add to this error message that tells the user what to do when they receive this error message.

I'm thinking it would be: "**Email already exists. Email mtl.info@va.gov to re-register this email address.**"

![image](https://user-images.githubusercontent.com/7454688/57048311-514cf380-6c28-11e9-97c1-36293b884c49.png)

**Comment by lzim** [comment]
@jamesmrollins **DEMO REGISTRATION & ISSUES**

_**Decisions**_
- Shorter term: Default course code length - **set it to a 45 days for the cybersem course code.**
- Longer term: Need a way to delete a registered email that has expired.
- What about about people who watch this webinar in the future
- The cybersem course code always be good for 45 days from registration.

**_Future_**
- More customization for this.

**DEMO SITE URL:**
https://forio.com/app/va/va-psd-demo/mtl_demo.html

**LOG IN AFTER REGISTRATION:**
https://forio.com/app/va/va-psd-demo/login.html

**Comment by TomRust** [comment]
@jamesmrollins --

Signing into the sim on the DEMO site was a little tricky with my short laptop monitor.  The list of required fields is so long that it didn't fit on my screen, but when I went to the scroll bar, the whole list disappeared!  I had to tab down to get to the Run button.  Is there a way to make the scroll bar accessible, or to automatically scroll down after someone fills in the Your Discipline field?

![image](https://user-images.githubusercontent.com/32961420/57090309-87e04800-6cd4-11e9-978c-7d71d66ac85c.png)

**Comment by TomRust** [comment]
@jamesmrollins --

Also, apparently the VA doesn't trust our team site:
![image](https://user-images.githubusercontent.com/32961420/57090427-c118b800-6cd4-11e9-84c9-623e4dad3e3b.png)

**Comment by dlkibbe** [comment]
Well that's a problem @TomRust !!!!

**Comment by jamesmrollins** [comment]
@TomRust @dlkibbe Yes, not being trusted is not good.  However, I am not familiar with that url in the screen capture.  We are not using that URL at this point.

Regarding the laptop issue, we haven't had any time to develop responsive design at this point.  What would be helpful for that effort, though, is a screen capture of your screen resolution.

**Comment by jamesmrollins** [comment]
Does anyone want to edit this?  Now would be the time.  I have spotted a few corrections.  But I was wondering if this may require some smithing.

![image](https://user-images.githubusercontent.com/30132017/57104566-87987a80-6cdd-11e9-9ddb-879509c19066.png)

**Comment by dlounsbu** [comment]
> A full PDF can be found at https://github.com/lzim/teampsd/tree/master/sim_ui_workgroup/mtl_1.8

This looks great, but all the other bios use names. My bio says "Dr. Lounsbury . . . ." Sounds pretentious. @AnnHier or @jamesmrollins, can you replace "Dr. Lounsbury" with "David Lounsbury"?? THANKS

**Comment by jamesmrollins** [comment]
@dlounsbu no worries Doc.  Taken care of! :-)

**Comment by lzim** [comment]
@TomRust @dlounsbu @jamesmrollins @staceypark @dlkibbe 

@TomRust 
1. Try https://mtl.how/team again. I updated the shortcut, but it's true it took a few tries to get it to work. I was able to get to it on my VA machine, and VA has never liked the domain teampsd.org.

@jamesmrollins 
2. I'll pot my recommended text here shortly for the hard coded portion.

@dlounsbu and All
3. I'd like us to consistently included our title and credentials, but then informal from there.
- Ideally we'd all convey as much personality as @holbrooa 💯

**Comment by lzim** [comment]
@jamesmrollins 

Below is my recommended, team site hard-coded introduction text.

Will you please included the same links for the R01 and R21...
We don't have an IIR link yet, but I added the details anyway.

**TEXT**
Funded by the National Institutes of Health and the Veterans Health Administration, scientific study of _Modeling to Learn_ is underway to determine its effectiveness increasing delivery of evidence-based addiction and mental health care (NIDA R01DA046651 and R21DA042198; HSRD I01HX002521; PI: Zimmerman). The _Modeling to Learn_ program supports multidisciplinary teams of frontline psychiatry, psychology, social work, nursing and certified peer support specialist providers in the Veterans Health Administration. 

This website supports the _Modeling to Learn_ effort by introducing the facilitators, workgroup leads, key partners and co-investigators who learn with frontline staff from MTL data and simulation resources. Our team, “Team PSD,” is distributed across the United States. Read below to learn more about who we are and what we do.

**Comment by lzim** [comment]
Last Question:

In addition to listing folks according to the order of the maps (colors:
- Facilitators (blue)
- Workgroup Leads (green)
- Key Partners (red)
- Co-investigators (purple)

**Remind me, is there no way to put the name by the photo on the map?

**Comment by jamesmrollins** [comment]
@lzim I have links for R01 and R21. Let me know when you get HSRD.  

May I recommend that titles and credentials follow immediately after the name:

For example:
Lindsey Zimmerman, PhD,
David Lounsbury, PhD,
or Ilse Wiechers, MD, MPP, MHS

**There certainly is a way to put names on the photo.  However, could be challenging with limited room, which is why we discarded them.  I tried again last night, but quickly ran out of room - especially on the Facilitator map.

**Comment by dlkibbe** [comment]
@Bowlied do you have a high resolution picture?

**Comment by jamesmrollins** [comment]
@lzim People are now in order by group as specified above.

**Comment by lzim** [comment]
Thanks @jamesmrollins 👍 

**Within BIOS**
- Yes, I agree that titles and **credentials follow the name**, then **first names** after that.

**MAPS**
- Okay to omit names from the maps. 
- Are the maps tied to the same number of seconds as at DEMO? If NOT, then **we need the maps to move at more like 4 seconds/map**. It's too long at present.

**BIO ORDER**
Ordering by workgroup is a lot clearer.\!
- But, we need **color-coded sub-headers under Team PSD** to scroll/navigate with ease to those sections:
  - Facilitators (blue)
  - Workgroup Leads (green)
  - Key Partners (red)
  - Co-investigators (purple)

**LIST OF PHOTOS THAT NEED TWEAKS**
_Problems with resolution_
- [ ] Claire
- [ ] Gayle
- [ ] Stacey
- [ ] Andrew
- [ ] Elizabeth
- [ ] Rachel

_Improve crop/placement_
- [ ] Theresa
- [ ] Tammy
- [ ] Craig

_Consider another image_
- [ ] John
- [ ] Swap
- [ ] Fawn
- [ ] Mark

**WHAT WE DO SECTIONS THAT NEED TO BE DRAFTED**
- [ ] Facilitators

- [ ] Workgroup Leads (Bullets for: Qual, Quant, Sim, HQ, Model)

- [ ] Key Partners (Bullets for: OMHSP, VAPOR, EES)

- [ ] Co-investigators

**Comment by staceypark** [comment]
@jamesmrollins Just got Erik Ontiveros's bio and headshot. They've been added to GH.
https://github.com/lzim/teampsd/blob/master/resources/bios/ontiveros_bio.md
https://github.com/lzim/teampsd/blob/master/resources/headshots/ontiveros_headshot.jpg.

Is there anything I can do to help with photo tweaks @lzim has indicated? I believe there are probably bios tweaks needed as well for people that went >150?

**Comment by jamesmrollins** [comment]
@lzim @staceypark   Just a few notes:

1.  Subsections under bios may not be possible - I will check.
2.  Slider delay, no worries, easy to change.
3.  If there are issues with photo placement, it is because the photo provided does not support better placement.  Therefore, a different photo with the subject more centered in the photo space is necessary.
So the 13 above may just need to re-shoot.  Recommend a bland background, slight look to the left or right, head centered in frame. Go with full resolution JPEG.  
4.  I am not comfortable editing other's bios, other than a format, typo or something.

**Comment by AnnHier** [comment]
Hi team - please glance at the attachment examples and see if those are placed a bit more like you envisioned.  Thanks!
![mtl Lower Banner Ex1](https://user-images.githubusercontent.com/41759126/57305253-5dacd280-70a6-11e9-8889-b4ce33d40d8c.jpg)
![mtl Lower Banner Ex2](https://user-images.githubusercontent.com/41759126/57305270-62718680-70a6-11e9-892d-4c39e8f36d15.jpg)

**Comment by lzim** [comment]
@annhier

Looks good to me!

**Comment by AnnHier** [comment]
@lzim excellent! We're cranking them out! :)

**Comment by lzim** [comment]
Hi @jamesmrollins I believe my recommended text for the team site was missed last week, can it be updated? I quote myself below:

> Below is my recommended, team site hard-coded introduction text.
> 
> Will you please included the same links for the R01 and R21...
> We don't have an IIR link yet, but I added the details anyway.
> 
> **TEXT**
> Funded by the National Institutes of Health and the Veterans Health Administration, scientific study of _Modeling to Learn_ is underway to determine its effectiveness increasing delivery of evidence-based addiction and mental health care (NIDA R01DA046651 and R21DA042198; HSRD I01HX002521; PI: Zimmerman). The _Modeling to Learn_ program supports multidisciplinary teams of frontline psychiatry, psychology, social work, nursing and certified peer support specialist providers in the Veterans Health Administration.
> 
> This website supports the _Modeling to Learn_ effort by introducing the facilitators, workgroup leads, key partners and co-investigators who learn with frontline staff from MTL data and simulation resources. Our team, “Team PSD,” is distributed across the United States. Read below to learn more about who we are and what we do.

**Comment by jamesmrollins** [comment]
@lzim Done!  This is now an update-able field in the new Team PSD Admin Page.

Now in test:

Webpage:  https://forio.com/app/va/va-psd-test-team/teampsd.html

Admin: https://forio.com/app/va/va-psd-test-team/admin.html

I plan to change the browser tab to say "Team PSD", it currently says MTL Demo.  I also plan to decrease the slider, slide time to 4 seconds. 

I will also add Eric Ontiveros to the mix.

**Comment by jamesmrollins** [comment]
Hi @lzim , I am proposing that we use the following format (subgroup name after hyphen) for breaking Team Members into their respective sub-groups under Team PSD. 

![image](https://user-images.githubusercontent.com/30132017/57540640-01de8580-7302-11e9-9caf-afcfd447d3cb.png)

**Comment by jamesmrollins** [comment]
@lzim  Here is a new Map Concept for your consideration:

![facilitators_map](https://user-images.githubusercontent.com/30132017/57546322-5dfcd600-7311-11e9-854a-b4d7cd1fc9c2.jpg)

**Comment by lzim** [comment]
@jamesmrollins 

I like it, except the dash, and the repetition of "Team PSD"

Would rather just:
- Facilitators
- Workgroup Leads
- Key Partners
- Co-investigators

> Hi @lzim , I am proposing that we use the following format (subgroup name after hyphen) for breaking Team Members into their respective sub-groups under Team PSD.
> 
> ![image](https://user-images.githubusercontent.com/30132017/57540640-01de8580-7302-11e9-9caf-afcfd447d3cb.png)

**Comment by lzim** [comment]
@jamesmrollins 

DRAFT MAP - I REALLY like being able to see who folks are by name, title, and location at a glance.

**Comment by lzim** [comment]
@jamesmrollins 

DRAFT MAP - I do NOT like the stars. I'd rather just have the photo and name, title, location.
The stars are what Edward Tufte would call "chart junk" doesn't add value and creates unnecessary visual complexity.

**Comment by jamesmrollins** [comment]
Consider a Dot or something to relate to location on map since photo is not close in some cases. I don’t agree with chart junk observation. It does have meaning with respect to location of participant.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by dlkibbe** [comment]
I think they should be @branscombj

**Comment by jamesmrollins** [comment]
Sans stars.

![image](https://user-images.githubusercontent.com/30132017/57634810-e5895580-755a-11e9-9bd3-30e330cdb67a.png)

**Comment by branscombj** [comment]
> I think they should be @branscombj

You are welcome to tag me in those pop-ups. I believe I was thinking that the ones we saw as "tips" were not going to be associated with one of us; only the ones that were corrections or pause instructions. Given how few corrections there are, it seems to me a little weird for the many numerous popups to be associated with the co-facilitator (ie the not-Lindsey presenter).

@lzim @TomRust @dlounsbu @dlkibbe @AnnHier  - I don't know if anyone has other thoughts. From a viewer's perspective, I fear it may feel like, "So-and-so didn't say much on the video, so they came back with all these afterthoughts in pop-up messages."

**Comment by lzim** [comment]
@jamesmrollins 

I think the updated map sans starts looks great!

**Comment by lzim** [comment]
@lzim @TomRust @dlounsbu @dlkibbe @AnnHier 

from @branscombj 
> I don't know if anyone has other thoughts. From a viewer's perspective, I fear it may feel like, "So-and-so didn't say much on the video, so they came back with all these afterthoughts in pop-up messages."

I'm not sure whether it seems that way, are there some examples we can review, @AnnHier ??

I'm sure we need to make sure it is working well as intended ASAP as we do not want re-work 😬

**Comment by lzim** [comment]
NOTE THAT THIS GOES WITH _MTL Video_ ISSUE - recommend we move our conversation to that issue.
@staceypark @TomRust @dlounsbu @dlkibbe @AnnHier
> 
> from @branscombj
> 
> > I don't know if anyone has other thoughts. From a viewer's perspective, I fear it may feel like, "So-and-so didn't say much on the video, so they came back with all these afterthoughts in pop-up messages."
> 
> I'm not sure whether it seems that way, are there some examples we can review, @AnnHier ??
> 
> I'm sure we need to make sure it is working well as intended ASAP as we do not want re-work 😬

**Comment by AnnHier** [comment]
> NOTE THAT THIS GOES WITH _MTL Video_ ISSUE - recommend we move our conversation to that issue.
> @staceypark @TomRust @dlounsbu @dlkibbe @AnnHier
> 
> > from @branscombj
> > > I don't know if anyone has other thoughts. From a viewer's perspective, I fear it may feel like, "So-and-so didn't say much on the video, so they came back with all these afterthoughts in pop-up messages."
> > 
> > 
> > I'm not sure whether it seems that way, are there some examples we can review, @AnnHier ??
> > I'm sure we need to make sure it is working well as intended ASAP as we do not want re-work grimacing

Hi @lzim, I can check - currently we're still mostly in the process of creating the popups before we edit them into the video, with the exceptions of the "placement" examples.  I don't necessarily feel it will read that way if the "un-attributed" tips come from @branscombj or you, but that's just me! :) If you do want to see an example, I can coordinate with our editor and graphic designer to test in module 6 agg.

**Comment by lzim** [comment]
@staceypark will you work with me to:

1. Complete the photo edits from the list above (posted by me 12 days ago).
2. Coordinate with either me or the workgroup leads to draft **What we Do** text for the following workgroups and key partners?

- [ ] hq	
- [ ] facilitate
- [ ] model
- [ ] sim_ui
- [ ] qual
- [ ] quant
- [ ] cois
- [ ] vapor
- [ ] ees

**Comment by branscombj** [comment]
> 2. Coordinate with either me or the workgroup leads to draft **What we Do** text for the following workgroups and key partners?
> * [ ]  ees

Coordinates with VA’s Employee Education System (EES) office to secure accreditation for continuing education units for staff members who complete *MTL Live*, *MTL Video*, or *MTL Facilitate*.

**Comment by staceypark** [comment]
@lzim 
@jamesmrollins and I are working on updating the photos. Looks like I'll probably need to grab some folks in person and snap pictures for better headshots.

> @staceypark will you work with me to:
> 
> 1. Complete the photo edits from the list above (posted by me 12 days ago).
> 2. Coordinate with either me or the workgroup leads to draft **What we Do** text for the following workgroups and key partners?
> 
> * [ ]  hq
> * [ ]  facilitate @branscombj thanks for taking a stab at the ees one! can you draft one for this as well?
> * [ ]  model @TomRust can you draft one before the launch meeting tomorrow?
> * [ ]  sim_ui @jamesmrollins can you draft one before the launch meeting tomorrow?
> * [ ]  qual @teampsdkathryn can you draft one to review at the qual meeting next Tues?
> * [ ]  quant @saveth @holbrooa let's spend 5min on this at the quant meeting tomorrow
> * [ ]  cois
> * [ ]  vapor
> * [ ]  ees

**Comment by jamesmrollins** [comment]
@lzim I will do my best.

**Comment by branscombj** [comment]
facilitate workgroup develops, tests and refines the approach, scripts and supporting materials for conducting *MTL* with learners; also develops, tests and refines the approach, scripts and supporting materials for conducting *MTL Facilitate* training for new co-facilitators

> Is it others' understanding that this workgroup does both? I wasn't sure.

**Comment by TomRust** [comment]
@jamesmrollins 
The modeling work group logo:
![Modelng Worgroup Logo](https://user-images.githubusercontent.com/32961420/57867441-2b4e5400-77cf-11e9-97e7-b82045e9b402.png)

**Comment by branscombj** [comment]
facilitate workgroup logo:
![image](https://user-images.githubusercontent.com/29778290/57868858-c5170080-77d1-11e9-95d6-948af3cef944.png)

**Comment by teampsdkathryn** [comment]
Draft Qualitative Workgroup What We Do Text: Kathryn Version 1


The qualitative workgroup strives to understand what clinical providers are experiencing in the clinic and how Modeling to Learn (MTL) can create transformative change. We use a participatory epistemology by engaging with partners and stakeholders to gain a new awareness of the dynamics related to the delivery of evidence-based practices (EBP). We have a theory of change and well as a model to explain the mechanism of change. These models offer unique qualitative categories and verbal construct mapping. Our team analyzes narrative text to grasp how MTL might work to create change. We analyze causal feedbacks, time, rates, and states of accumulation using RQDA, an R package for computer assisted qualitative data analysis. We strive to develop seminal practices from group modeling to understand determinants (facilitators, barriers) for improved EBP reach.
Should I embed this in the Lucid agenda as well for further discussion at the next qual  workgroup meeting?  Best Regards, Kathryn

**Comment by branscombj** [comment]
@staceypark Some guidance on level of detail and tone/audience for the workgroup descriptions? I see that my approach and Kathryn's are very different. Let me know if you want me to write more. Thanks!

**Comment by lzim** [comment]
@branscombj 

I think we are going for it being okay to have diversity right now, and are open to not being overly directive about tone/detail. But, I do think the participatory principles should be emphasized more in our facilitate workgroup, as that is key! Do you want to take a crack at it?

**Comment by lzim** [comment]
@jamesmrollins @TomRust @staceypark 

I didn't have time to say this yesterday, but I don't think we will have logos for each Team PSD **workgroup** and it would be weird if we did...case in point @TomRust  😆 

But, our **key partners** do have logos.

RECOMMEND:

1. Separate Workgroups from Key Partners.

**WORKGROUPS**
- [ ] hq	
- [ ] facilitate
- [ ] model
- [ ] sim_ui
- [ ] qual
- [ ] quant
- [ ] cois

**KEY PARTNERS**
- [ ] vapor
- [ ] ees

2. Omit an image on the left for Workgroups, but retain it for Key Partners.

Thanks!

**Comment by TomRust** [comment]
@jamesmrollins  -- Here is the Modeling Workgroup blurb:

The Modeling Workgroup builds virtual worlds. These worlds allow provider teams to quickly, easily, and safely experiment with their wildest improvement ideas. In seconds, they can see outcomes and unintended consequences that would otherwise remain hidden for months or years.  Unlike in their actual clinics, they have complete freedom to make as many mistakes as they need to learn, allowing them to develop intuition about how to optimize trade-offs specific to their own combination of patients, partners, and resources.  We are perpetually learning from teams to improve these virtual worlds, to find the right balance between realism and usefulness.

**Comment by lzim** [comment]
Thanks @TomRust

**Comment by branscombj** [comment]
@lzim 
> **KEY PARTNERS**
> 
> * [ ]  vapor
> * [ ]  ees
> 
Just wondering if TAS = key partner

**Comment by lzim** [comment]
@branscombj 

I think the TAS see themselves as Facilitators and members of Team PSD.  They do not have their own logo and we (myself and the TAS) are all part of Office of Mental Health and Suicide Prevention (OMHSP) 

However, we do list Drs. Wiechers and Trafton as key partners on the maps above, and they are also OMHSP.

For these resasons, we could list OMHSP as a key partner, if we did that we would also want to list @TomRust's office: Office of Healthcare Transformation (OHT).

**WORKGROUPS**
- [ ] hq	
- [ ] facilitate
- [ ] model
- [ ] sim_ui
- [ ] qual
- [ ] quant
- [ ] co_is

**KEY PARTNERS**
- [ ] vapor
- [ ] ees
- [ ] omhsp
- [ ] oht

**Comment by TomRust** [comment]
Hey @staceypark and @jamesmrollins -- The links to the SEE files from the demo site (https://github.com/lzim/teampsd/tree/master/mtl_facilitate_workgroup/mtl_live_guide) don't work.

**Comment by lzim** [comment]
Great catch 🎣 @TomRust 

But I didn't notice this before: It should NOT go to the Team PSD repo. It should definitely to to https://mtl.how where the "BEST" "CURRENT" SEE guides (and soon SAY guides) live.

FYI: @jamesmrollins and @staceypark

**Comment by saveth** [comment]
@jamesmrollins  says this is done and needs to be close. Any new issues or request requires a new ticket.
