### ISSUE TITLE
2024_09: MTL Manual, fix broken image links & correct image syntax

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3246]
- We need to use syntax that includes raw image info for bookdown/manual markdown files
- Possibly use FnR function to aid in this task - @matthewtomo may be able to help with this?

## AC:
- [x] Scrub all MTL Manual bookdown/manual markdown files 
- [x] No broken images
- [x] No images with "![image](image path)" syntax exist anymore
- [x] All image syntax is consistent

**Comment by matthewtomo** [comment]
**Discussed 8/20/24**

- Bookdown currently does not properly render all images (issue appears intermittently).
  - Appears that this can be resolved by deleting and re-adding the source of an image to trick bookdown into re-rendering it
- For images make sure to use following format to include alt text properly:
`<img alt="Alt Text" src="Path/URL to Image">`
  - Make sure to include "?raw=true" at the end of the url to just get the image and not the link to the image in GitHub
  - Example:
`<img alt="An image of our registration page" src="https://github.com/lzim/mtl/blob/gh-pages/images/self_registration_popup_team_name.png?raw=true">`

**Comment by matthewtomo** [comment]
**week 3 2024_08 Praxis Meeting**
@matthewtomo @jamesmrollins @ljmoody 

- @ljmoody has updated all images to the new format (with alt text), but some are still not rendering.
- [ ] @matthewtomo @ljmoody Go to bookdown repo and investigate existing tickets / create a new ticket

**Comment by ljmoody** [comment]
**8/29/24 ad hoc meeting with @matthewtomo & @ljmoody:**
- Tested hypothesis: are redirects causing image display & 403 issues? 
- When too many redirects happen, the images display (or not) inconsistently. 
- The decided-upon syntax (?raw=true") was the cause of redirects.

## NEW SYNTAX TO USE FOR IMAGES:
- in simplest form: 
`<img alt="Alt Text" src="Path/URL to Image">`

- **with more detail: 
`<img alt="Image of IMAGE DESCRIPTION." src="https://raw.githubusercontent.com/OWNER/REPO/gh-pages/images/IMAGE_FILE_NAME.png`**

For example, an actual image is displayed using this code in the _MTL_ Manual using this syntax:
 `<img alt="Image of the registration page." src="https://raw.githubusercontent.com/lzim/mtl/gh-pages/images/self_registration_login_screen.png">`

**Comment by ljmoody** [comment]
Issue solution has been tested and image issues are now resolved! 🎉 
Closing this card.

**Comment by hnorthcraft** [comment]
@ljmoody @matthewtomo 

Hi Laura and Matt! Can you please add story point estimates?

Thanks!
Heather



#adjudicate_memo
