### ISSUE TITLE
2024_09: DEV explanation message for modules with service choices

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3249]
**fyi:** original suggestion and related comments found in #3210

Users may be confused about what default numbers and services they're viewing. 

## AC:
- [x] develop messages for modules with radio button choices to help reduce confusion about what users are viewing (setting and numbers)
- [x] text to use for message/button:
  - [x] **Team Care:** "Default display is Intake evaluations; toggle to view other services."
  - [x] **Medication Management:** "Display is AUD; toggle to view other medication-specific services."
  - [x] **Team Flow:** "Display is GMH; toggle to view other setting-specific services."

Lindsey's preferred mockup thus far is below.
- @lijenn pointed out that the red does look similar to the Learning Mode buttons. 
- Tejas said he'd use different color codes. 
- Lindsey isn't sure another color is needed. But if so, draw from the VHA graphics and style requirements for approved colors. 
![image](https://github.com/user-attachments/assets/80bd1920-2ca5-407d-9486-fe3886df0fd6)

---
FYI: Original ask from Lindsey:
>_Do we have a card for developing a **RED explanation in Team Care** that you can either review Intake Evaluations OR the rest of the services in the new Dynamic Decision Dashboard?_
>   - **Text to use:** "Default display is Intake evaluations, toggle to view other services."
>![image](https://github.com/user-attachments/assets/5d8e29ef-13d3-48c7-ad32-81d2bdbf6ff9)
>
>![image](https://github.com/user-attachments/assets/89b265fe-458c-4034-9ffd-ad2aabf7240d)

**Comment by matthewtomo** [comment]
**Discussed DEV Standup 8/12/24**
@matthewtomo @tejaspesquare 

- @matthewtomo will start working on the development of this feature and provide updates here.

fyi: @jamesmrollins @ljmoody @lijenn

**Comment by matthewtomo** [comment]
**Discussed Dev Standup wk_1 2024_9**
@matthewtomo @tejaspesquare 

- This work will now be handled by DEV.
- Due to the dynamic design of the page, Dev does not currently have a time estimate for this task.
- @tejaspesquare will be able to provide an estimate here after discussion with the designer.

fyi: @jamesmrollins @ljmoody

**Comment by tejaspesquare** [comment]
Hi Matthew,

> * Due to the dynamic design of the page, Dev does not currently have a time estimate for this task.
> * @tejaspesquare will be able to provide an estimate here after discussion with the designer.

Following the conversation with the Designer, it has been determined that this task can be accomplished within 4 to 5 hours, assuming there are no significant design revisions. However, if major adjustments are necessary, the time required may extend to 8 to 10 hours due to the need for compatibility across multiple resolutions along with Zoom behavior. We target to finalize this by the end of the day on Friday, September 6th, or at the latest, by Monday, September 9th.

**Comment by matthewtomo** [comment]
- Dev team is requesting confirmation that the following "explanation" implementation looks good for the Medication Management module before continuing with the other modules
- To me, this current implementation raises @lijenn's original concern that the explanations (labelled 2) look like the learning mode buttons (labelled 1).
- @lzim and @ljmoody, do we need to come up with a new design for the explanations, or does the current implementation look good?
![image](https://github.com/user-attachments/assets/1d17213e-da1b-4088-9ed2-deee1f68e4ec)

**Comment by ljmoody** [comment]
I have the same trepidation that @lijenn mentioned. If Sim UI users (new or not) get used to red = learning mode, this could cause confusion. And more.

I went poking around and found the VA Graphics Guide! Here are [what I think are] the most relevant pages of that PDF to consider for this issue:
![image](https://github.com/user-attachments/assets/8409cfd1-2c18-4e44-b1e8-d85d81a76823)
![image](https://github.com/user-attachments/assets/e6c7aaa8-139f-4134-a556-0f19e28a41cc)

@lzim and @matthewtomo, I suggest we use "light blue"' for the buttons themselves, with white font. Yea or nay?
![image](https://github.com/user-attachments/assets/65c0bd46-e0ec-46c6-b544-123c3b4a0f09)

**Comment by matthewtomo** [comment]
**Discussed Dev Standup wk_1 2024_9**
@matthewtomo @tejaspesquare 

- Dev is also able to implement the explaination messages like shown above in @ljmoody's comment.
- They are waiting on confirmation from @lzim, before making that change.

**Comment by matthewtomo** [comment]
**Discussed Dev Standup wk_2 2024_9**
@matthewtomo @tejaspesquare 

- @matthewtomo will bring this up at the workflows meeting later today.

**Comment by ljmoody** [comment]
Discussed at wk2 2024_09 support, systems_sme, & sim_ui workflows sync

- @lzim suggests using black text for the explanation messages. 
- Develop to look like main Sim UI page (experiments/radio buttons/etc)

**Comment by matthewtomo** [comment]
@tejaspesquare
- Keep the same style of text as current DEV implementation, but change the color to black.
- Do this for Team Care, MM, and Team Flow, and make sure to use the exact wording from the acceptance criteria (quoted below)

> [ ] text to use for message/button:
> * [ ]  **Team Care:** "Default display is Intake evaluations; toggle to view other services."
> * [ ]  **Medication Management:** "Display is AUD; toggle to view other medication-specific services."
> * [ ]  **Team Flow:** "Display is GMH; toggle to view other setting-specific services."

**Comment by matthewtomo** [comment]
**Discussed Friday Dev Standup wk_2 2024_9**
@matthewtomo @tejaspesquare 

> @tejaspesquare
> 
> * Keep the same style of text as current DEV implementation, but change the color to black.
> * Do this for Team Care, MM, and Team Flow, and make sure to use the exact wording from the acceptance criteria (quoted below)

- This has been implemented and is available in the DEV environment.
![image](https://github.com/user-attachments/assets/c09f7616-a6d1-484e-be73-ab6e2581d430)
- [ ] @ljmoody does this look like it meets all of your Acceptance Criteria?

**Comment by ljmoody** [comment]
@matthewtomo, everything looks good with one minor change to be made. Please: uncap "D":
![image](https://github.com/user-attachments/assets/c78a5f5f-b41a-433a-8adc-cfbbbed7cf89)
Then all AC is met and ready to go!

**Comment by matthewtomo** [comment]
**Discussed Dev Standup wk_3 2024_9**
@matthewtomo @tejaspesquare 

- @ljmoody, the capitalization and alignment bugs have been corrected locally and will be deployed to the DEV environment soon.

**Comment by tejaspesquare** [comment]
Hello @ljmoody , @matomasz 
> Please: uncap "D": 

 This is moved to Dev environment.
![image](https://github.com/user-attachments/assets/e41534a4-21f7-4371-941f-19e727a00838)

**Comment by ljmoody** [comment]
✅ verified change in DEV environment
fyi @matthewtomo @tejaspesquare 
> > Please: uncap "D":
> 
> This is moved to Dev environment. ![image](https://private-user-images.githubusercontent.com/144898781/368450075-e41534a4-21f7-4371-941f-19e727a00838.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2Nzk1MjksIm5iZiI6MTcyNjY3OTIyOSwicGF0aCI6Ii8xNDQ4OTg3ODEvMzY4NDUwMDc1LWU0MTUzNGE0LTIxZjctNDM3MS05NDFmLTE5ZTcyN2EwMDgzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQxNzA3MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YjllYTQwMzJlYmFhZjc3NTYzNGI4YWNiZTAzMTQ0MDZiNTg3ZDZiYTg3MGIxMTc4MjMyMTI4MTJjMzNlYjRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IVDHuoPiBR6tkb5ivnMH6U5YWpBDallEkYFLilT-Ep0)

**Comment by matthewtomo** [comment]
**Tested for PROD in Google Chrome on non-VA machine 11/19/2024**
![image](https://github.com/user-attachments/assets/de003e2c-6b88-4bd5-9ec0-836e54213165)
- Closing this card as all acceptance criteria is met and the change is available in PROD
