### ISSUE TITLE
Brainstorming to Improve Session 4 

### ISSUE THREAD

**Issue by TomRust** [lzim/teampsd#325]
#### Issues:
1.	Difficult to know what the right questions are to ask to hone in on the team’s most important need, relative to the strengths of each model
2.	Need more time to prep for upcoming sessions
3.	Team list in sim is full of old teams, which isn’t what a normal user will see

#### Proposed solutions (addressing individual issues above):
1.	After getting the team to explain why they answered how they did and what their big take-aways are, then run the narrowing as a process of elimination.  Develop list of “no-go” responses to look for to know when to cross a model off the list for consideration.
2.	Add time to the end of session 5-8 debrief, to plan out the interaction with the sim for sessions 6-9.
3.	Add this process to remove teams from the dropdown list to the prep for session 5:
Sign into Epicenter
- _Go to PROD_
- _Click Groups_
- _Look for the world you'd like to remove from list of worlds_
- _Click on that world_
- _Go to Multiplayer Assignment_
- _Click the radio on the left and select “Make Inactive”_

**Possible Go/No-go list:**
 No-go signs:
- CC – ?
 - MM – Team doesn’t mention EBPharm
 - PSY – Team doesn’t mention EBPsy
 - AGG – Team is focused on one service/patient cohort.
 - SP – Team says they have no communication with other settings / aren’t allowed to talk with providers in other services / don’t adhere to the service agreements currently in place.  Team is very interested in getting existing patients into the right follow-up appointments (i.e., RVI).

Go signs:
- CC – Team is *only* struggling with providing care coordination appointments.
- MM – Team is primarily psychiatrists.
- PSY – Team is primarily psychologists. 
- AGG – Team says they are concerned with “service mix;” burnout, overtime, and overbooking; or that they have too many clinics/grids (which indicates that they don’t know why they are spending x hours on each service).
- SP – Team says they have good relationship with PC and specialty MH, or includes members from those settings. Team is primarily concerned with suicide prevention/care of high risk patients.

**Comment by lzim** [comment]
@staceypark 

This is the kind of information that would be really helpful to add to the *MTL Facilitate Guide.*

Lindsey

**Comment by dlkibbe** [comment]
@branscombj let's talk about @TomRust comments for the say files

**Comment by TomRust** [comment]
I've added the notes from out experience running this with the TAS to the pull request for the Session 4 Say file.  This doesn't need to be an issue on it's own.

--TOM
