### ISSUE TITLE
2024_wk1_sep: BUG: Inconsistent Team Data File Uploads from Admin Dashboard

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#3251]
## What Happens
- When user attempts to upload from the Admin Dashboard it works ok.
- When user attempts to upload another file, the file loads to the previously selected teams.

## What Should Happen

- When user uploads a file and selects teams the file applies to, it should load to those teams.

Cross Reference: #3220

**Comment by matthewtomo** [comment]
**Discussed Dev Standup wk4 2024_08**
@matthewtomo @tejaspesquare 

- This issue is not high priority as of this week.
-  @matthewtomo will provide detailed explanation of incorrect behavior after testing current behavior.

**Comment by matthewtomo** [comment]
After testing out the Admin Dashboard with @ljmoody for #3186, we noticed some inconsistencies that might be better tracked here. We have documented these inconsistencies to identify them and ask for clarification on proper behavior.

## Adding a file

### Adding to only the _ind world

#### From Home page for that world
- File is only added to the _ind world

#### From Admin Dashboard
- File is only added to the _ind world

### ⚠️Adding to only the _shared world

#### From Home page for that world
- ⚠️ File is only added to the _shared world

#### From Admin Dashboard
- ⚠️ File is added to the _ind, _shared, and _teams worlds for the _shared world's group

### ⚠️ Adding to only the _team world

#### From Home page for that world
- ⚠️ File is only added to the _team world

#### From Admin Dashboard
- ⚠️ File is added to the _ind, _shared, and _teams worlds for the _team world's group

## Deleting a file (When the file is included in all three worlds)

### Deleting from only the _ind world

#### From Home page for that world
- File is only removed from the _ind world

#### From Admin Dashboard
- File is only removed from the _ind world

### ⚠️ Deleting from only the _shared world

#### From Home page for that world
- ⚠️ File is only removed from the _shared world

#### From Admin Dashboard
- ⚠️ File is removed from the _shared and _team world for the _shared world's group

### ⚠️ Deleting from only the _team world

#### From Home page for that world
- ⚠️ File is only removed from the _team world

#### From Admin Dashboard
- ⚠️ File is removed from the _shared and _team world for the _team world's group

fyi: @jamesmrollins @ljmoody

**Comment by tejaspesquare** [comment]
Hi Matthew,

> After testing out the Admin Dashboard with @ljmoody for #3186, we noticed some inconsistencies that might be better tracked here. We have documented these inconsistencies to identify them and ask for clarification on proper behavior.

Just wanted to highlight that above mentioned behavior is anticipated.  We have distinct business rules applied for Admin Dashboard & Dynamic Decision Dashboard. 

1. DDD 
      - Uploaded file belongs to that specific world only
      - Delete file from individual world
       
2. Admin Dashboard

    2.1 Upload file -
      - When a file is uploaded to _team or shared, it will be available in all worlds. i.e. _team, _shared & _ind
      - When a file is uploaded to _ind, it will be accessible exclusively to the _ind world only.
  
    2.2 Delete file -
      - If a file is deleted from the _ind world, it will become disassociated from that world exclusively.
      - Deleting a file from either the _team or _shared will result in its removal from both worlds.

**Comment by matthewtomo** [comment]
**Discussed sim_ui_workflow wk_1 2024_9**
@matthewtomo @ljmoody @lzim @dlounsbu 

**Decision**
- When file is uploaded through Home/DDD, it should be uploaded to all worlds for that group (_team, _shared, and _ind)

**Comment by matthewtomo** [comment]
**Discussed Dev Standup wk_1 2024_9**
@matthewtomo @tejaspesquare 

- Allowing non admin users to upload files to worlds they can not access, might create issues where different worlds appear to have the same data file, but different files have been uploaded. This could cause a lot of rework for Admin users.
- In general, this business rule was set in place following the principle that users should only be able to affect worlds to which they were given access.
- Dev will look into this as a potential feature to see if they can find a solution to the above problems, and will report back.

**Comment by matthewtomo** [comment]
Suggest closing because requires decent amount of work for minimal if any benefit.

**Comment by matthewtomo** [comment]
Marking as closed for now due to above reasoning

**Comment by hnorthcraft** [comment]
assigning 2 sp for effort applied although card was closed as not planned.
