### ISSUE TITLE
2024_10 Develop wireframes and alt text for 508 compliance

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3262]
This is a placeholder card for those future efforts.  💪 - **This is a HEAVY lift!**
👉The card may need to be broken into individual cards for each of those features, depending on the level of effort and communication for all.👈 

The DDD has alt text for 508 compliance but development did not include yet-to-exist features, including:
- [ ] Feedback Loops
  - [ ] CC
  - [ ] Team Care
  - [ ] MM
  - [ ] Psy
  - [ ] Team Flow
- [ ] Decision Meters
  - [ ] CC
  - [ ] Team Care
  - [ ] MM
  - [ ] Psy
  - [ ] Team Flow
- [ ] Episodes of Care
  - [ ] Team Care, MM, Psy (one wireframe would work for all)
- [ ] Flow
  - [ ] CC
  - [ ] Team Care
  - [ ] MM
  - [ ] Psy
  - [ ] Team Flow

## AC:
- [ ] Create document with screenshots of the features listed above and:
  - [ ] Tags numbered according to screen reading order
  - [ ] Alt text for each tag
- [ ] Peer review of wireframe document
- [ ] Create DEV/TEST combo card and share wireframe with Dev team

**Comment by ljmoody** [comment]
**Discussed at wk4 2024_09 #sim_ui_workflow**
@matthewtomo @ljmoody @jamesmrollins 

- This must be developed.
- @ljmoody will work with @matthewtomo to bring in Dev team for help with this effort 
  - **idea:** could Dev team/designer identify all elements on screen capture with sequential pins, then Laura can make 508 alt text callouts for each?

**Comment by lzim** [comment]
@ljmoody 
@matthewtomo 

- This is a federal requirement for all of us. 
- I'm unclear about how this would be lower priority than the Tutor, which is more of a "nice to have" ??

**Comment by ljmoody** [comment]
**Discussed at 10/11/24 roadmapping workshop**
@matthewtomo @ljmoody 

- While roadmapping, we discussed that card is indeed too big (in effort and points) to track creation of all included wireframes and all text.
- We think the best approach is to break this card down into smaller "chunks", with those each being a sub-menu within the DDD:
- We created the following cards to track efforts:
  - #3302 
  - #3303 
  - #3304 
  - #3305
- Creation of these wireframes is higher priority than linking Tutor prompts to _MTL 3.7 Consult Manual_

**#adjudicate_memo**: 
- sprint/milestone/epic updated to October
- points reduced from 21 to 3 to reflect this and the other cards created, work approach discussed

Closing this card.
