### ISSUE TITLE
BUG: When new teams are created in the admin dashboard, they are not automatically added to the dropdown options

### ISSUE THREAD

**Issue by matthewtomo** [lzim/teampsd#3269]
**Current Behavior:**
- When an admin adds a new team in the admin dashboard, the team is not automatically added to the dropdown list of teams (see photos)
- The admin user is required to refresh the page before the new team is included as an option
![image](https://github.com/user-attachments/assets/6bebdb96-e91c-45d3-aebd-526d8b93e883)
- Before refresh:
![image](https://github.com/user-attachments/assets/5bad89fb-1a84-47cd-acb2-93439a34ea3b)
- After refresh:
![image](https://github.com/user-attachments/assets/bcab6f7d-6b99-47d8-8ac2-9e3011a73087)

**Desired behavior:**
- [ ] Admin user does not have to refresh the page for the newly created team to show up in the dropdown.

**Comment by lzim** [comment]
@matthewtomo 

If new teams are not visible, then this is a high priority.
I'm unclear about how **admin users** will understand how to find the new team they've created.

If we're low on scope, then we need at least a low dev message to be added.

**Comment by matthewtomo** [comment]
**Discussed Monday Dev Standup wk_2 2024_10**
@matthewtomo @tejaspesquare 

- This issue has been addressed and is available for testing in TEST

**Comment by lzim** [comment]
@matthewtomo - Please add to agenda for review with 

#support_workflow @ljmoody 
#systems_sme_workflow @lzim @dlkibbe @dlounsbu 

 at #9am_leads today on https://mtl.how/2025_roadmap to make sure we see the scope of timeline for impacted users

**Comment by matthewtomo** [comment]
TESTED in TEST Environment on Chrome on Non-VA Machine

- Team "NO_REFRESH_TEST" does not exist
![image](https://github.com/user-attachments/assets/913aa442-388f-4293-9daa-b6926939e64a)
- Team "NO_REFRESH_TEST" is created
![image](https://github.com/user-attachments/assets/d9325957-0798-42e3-aa01-d22d8d85ce8a)
![image](https://github.com/user-attachments/assets/b92f867e-161a-4f71-a9b1-ac4404014ba9)
- Team "NO_REFRESH_TEST" is available in the dropdown without refreshing the page
![image](https://github.com/user-attachments/assets/03e83086-9313-4dcc-8122-bbd7bbd4ca22)

Behavior has been corrected, ready for PROD 🚀

**Comment by ljmoody** [comment]
Tested today in PROD, using both Edge and Chrome.
✅ verified that newly created teams are automatically added to the dropdown options

![image](https://github.com/user-attachments/assets/8df5683b-9e3f-4bef-bdd9-87723169dc49)
![image](https://github.com/user-attachments/assets/6af5578b-9823-4dcb-a995-7eb9a66856b5)

Closing this card as complete. 
fyi @matthewtomo @lzim
