### ISSUE TITLE
2024_10 BUG: mtl.how/demo group name bug

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3288]
Discovered 10/3/2024 when testing mtl.how/demo with @matthewtomo.

## What happens:
When a user attempts to start a session on the Home page of the DEMO site, the sim gets stuck on the loading screen. 
- **Laura experienced this issue in Chrome**. In the terminal, the following error message is available:
![image](https://github.com/user-attachments/assets/821ebd3a-da28-4280-befe-853c94a695fb)
- **This issue is crisscrossed with #3287**
  - **Matthew encountered this issue in the Edge browser**
- This issue appears to be related to group names being saved in local storage. 
- The account Matthew used had the credentials - email: `test4@gmail.com`, pw: `1a12345678`

## What should happen:
The user should be able to start a session without getting stuck on the loading screen.

**Comment by matthewtomo** [comment]
**Discussed Friday Dev Standup wk_1 2024_10**
@matthewtomo @tejaspesquare 

- This issue has been addressed in the DEV-DEMO environment.
- [ ] @matthewtomo will promote the changes into the TEST-DEMO and DEMO environments later today

fyi: @ljmoody

**Comment by lzim** [comment]
@matthewtomo 

Stay in close communication with @lzim about this for inclusion of https://mtl.how/demo in the AHSR presentation slide deek wk3 2024_10 in SF. Thx!

**Comment by matthewtomo** [comment]
- This bug has been tested in the PROD environment for the Demo Site.
- Behavior is now resolved and the session runs to completion
- Marking card as closed

fyi: @lzim
