### ISSUE TITLE
2024_10: two content changes needed to sim_ui_3.7_cheatsheet

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3292]
- MTL logo icon behavior is [not consistent across users and pages](https://github.com/lzim/teampsd/issues/3198#issuecomment-2357169548) within the Sim UI. The highlighted square below should be removed and replaced. (MTL logo behavior tracked via #3198.)
- Team button on top navbar is being removed per[ this decision](https://github.com/lzim/teampsd/issues/3210#issuecomment-2403699019) in #3210. The highlighted square below should be removed and replaced.
![image](https://github.com/user-attachments/assets/3b5ac49f-7bb1-4fbc-b538-9a7212fb0c63)

- [x] workshop what to replace these with, if anything, with @lzim & @matthewtomo at wk2 2024_10 #support_workflow/sim_ui_workflow
  - section of cheatsheet is for "Navigation Bar" and includes all other elements of the navbar; are there two others we want to make bigger/highlight?

**Suggestion:** make Name section larger and show all examples of team name extensions (_ind, _shared, _team, & Administrator)?
![image](https://github.com/user-attachments/assets/cca10863-c883-466d-a4e4-e248858196e1)
![image](https://github.com/user-attachments/assets/aa462ae4-4210-46df-b04f-1c7649704c24)

## AC:
- [x] Cheatsheet updated in Lucid.app
- [x] Cheatsheet .pdf uploaded to mtl>gh-pages>images
- [x] Cheatsheet .png uploaded to mtl>gh-pages>images

**Comment by ljmoody** [comment]
**Discussed at wk2 2024_10 #sim_ui_workflow**
@matthewtomo @ljmoody @lzim @jamesmrollins 

**DECISIONS:**
- [ ] Home icon: Click to return to the Dynamic Decision Dashboard.
- [ ] mtl logo: Click to return to the Dynamic Decision Dashboard.
- [ ] delete chat & slide to right: KISS!

**Comment by ljmoody** [comment]
- Cheatsheet is updated.
- Closing this card as complete!

**Comment by lzim** [comment]
@ljmoody 

The cheatsheet looks great! 
- I see it's updated in mtl.how/manual
- _Can we please also add a link to the Data UI and Sim UI cheatsheets to the README.md at https://mtl.how?_

**Comment by ljmoody** [comment]
@lzim the Readme is updated with cheatsheet links:
![image](https://github.com/user-attachments/assets/db66e912-d021-4d15-bfb8-4cc6ce7a6022)

**Comment by lzim** [comment]
Excellent, thank you! I must have scrolled right by it.

**Comment by ljmoody** [comment]
@lzim - not the first time you didn't! I just updated it after you asked. ✔️
