### ISSUE TITLE
wk3 2024_11: Team PSD manual, add information about ActionChecker

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3296]
Possible need to include this information found in [10/10/2024 #sim_ui_workflow meeting](https://dvagov.sharepoint.com/sites/teampsd_vha/_layouts/15/stream.aspx?id=%2Fsites%2Fteampsd%5Fvha%2FShared%20Documents%2Fsim%5Fui%5Fworkflow%5F9am%5Fleads%2FRecordings%2Fsim%5Fui%5Fworkgroup%2D20241010%5F141352%2DMeeting%20Recording%2Emp4&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2Ecb5bbadf%2Dea4e%2D46b6%2Dbecb%2D9ff5925c1250). 

## Current State:
![image](https://github.com/user-attachments/assets/11830e79-8a98-4a21-bfa0-dd939faa9525)
- GitHub ActionChecker returns "All checks have failed" error with any failed action.
- Users may think their pull request isn't valid, is incorrect, or they don't know what they're doing - which is incorrect. 
- Failing ActionChecker _does not prevent one from deploying updates_ to the manual. Although "all checks have failed", users can still select to Merge pull request.
- Users can always revert their change/pull request.

## Existing documentation in Team PSD manual:
![image](https://github.com/user-attachments/assets/07a7feac-fc4d-4c64-b2c1-ad9d2c37b058)

## Desired documentation + state:
- [x] Team PSD Manual updated to include information about ActionChecker Editors

List below transferred to #3323.

<del>

- [ ] **Spell Checker** - checks for spelling errors (dictionary can be added to). 
    - [ ] future state desired: Change the settings on it because it's requesting another input: paths.
- [ ] **Markdown Link Checker** - checks to be sure links are valid. This will fail if any links inside VA domain (any links users cannot access outside the VA domain). 
  - [ ] future state desired: Fix the configuration of this to 
- [ ] **Markdown Linter for Directory Level Scan** - _more information needed here; not covered in our meeting_

</del>

**Comment by matthewtomo** [comment]
**Ad Hoc wk2 2024_10**
@matthewtomo @ljmoody 

- Things to include in documentation
  - The error does not prevent changes (we can still merge)
  - Fact: Action checker only does some automated verification (linting)
  - Explanations on what each step is checking for and how to view the failed output to check manually
- Roadmap for after flow diagrams in November?

**Comment by ljmoody** [comment]
**wk2 2024_11 update:**
fyi @lzim @matthewtomo 
- Published progress so far and it's live in the manual.
- Removed contributing to manual section from Chapter 1 (index.Rmd file) because it was duplicate of information in Chapter 2. 
- Updated Ch. 2 information about pull requests, including updated screenshots.
- Added information about linter Actions and ActionChecker.

**Left to do:**
Adding further information + graphics about the editors, how to fix errors, what's okay to ignore, etc.
- [ ] Spell Checker
- [ ] Markdown Link Checker
- [ ] Markdown Linter for Directory Level Scan
- [ ] fix purposeful spelling error in last sentence of chapter (so I could capture as an example of how to fix)

**Comment by ljmoody** [comment]
@matthewtomo, 
- Could you review the Linter Actions documentation for accuracy and understanding? If a review/qa card is needed for this (and to program in the roadmap), let me know and I'll do that.
- Today's updates to the Team PSD Manual weren't successful. 😞  I'm pasting in the action errors; I'm unfamiliar with the r-lib/actions/setup error; could you possibly help with this next week -or-in the near-term future?
![image](https://github.com/user-attachments/assets/3b14a158-ef02-4329-b4a4-43ff25f18550)
![image](https://github.com/user-attachments/assets/ea6de87b-9fb2-4427-8cd0-a5c5e8ae8197)

**Comment by matthewtomo** [comment]
> * Today's updates to the Team PSD Manual weren't successful. 😞  I'm pasting in the action errors; I'm unfamiliar with the r-lib/actions/setup error; could you possibly help with this next week -or-in the near-term future?

- @ljmoody, I was unfamiliar with the error message provided, so I decided to re-run all jobs and see if it was a one time error:
![image](https://github.com/user-attachments/assets/0ba1182d-79ec-4d0c-b2da-600753b2127a)
- It looks like that works and now the action completed successfully.
- Unfortunately, it looks like the `Re-run all jobs` button also replaces the failed attempt of the GitHub action, so I am no longer able to look at the original issue in any further depth.
![image](https://github.com/user-attachments/assets/14338ade-8f8a-4e3c-8c1b-abe1d6252e91)
- If a similar issue is encountered again in the future, please let me know, so that I can investigate further before we attempt re-running the action

**Comment by matthewtomo** [comment]
- The issue with renderbook appears to be related to a recent issue with Homebrew or the runner image used by GitHub, which many others are facing as well: https://forum.posit.co/t/r-cmd-check-fails-on-macos-latest-release-r-lib-actions-setup-r-v2/195084

- It looks like we might just need to wait a little and see if it gets resolved by higher powers, at the very least we can try re-running any actions that fail

**Comment by lzim** [comment]
Thanks for running this done @matthewtomo !

@ljmoody _Can we update the Team PSD manual to reflect the info on this card & close?_
It would be great to make folks from **#quant_workflow** who may be contributing to the Team PSD manual aware too.

**FYI #quant_workflow:** @hnorthcraft @kmacia @dkngenda @lijenn

**Comment by ljmoody** [comment]
fyi @lzim @hnorthcraft @kmacia @dkngenda @lijenn: the Team PSD Manual is being updated with information about Actions and the ActionChecker in chunks as I make progress on this card.

ℹ️ - Please refer to [2.3.6. Check the File Against GitHub Actions](https://lzim.github.io/teampsd/2-use-and-contribute-to-this-manual.html#check-the-file-against-github-actions).

I have one more Editor to document and then I'll close this card as complete.

**Comment by ljmoody** [comment]
All updates are now live in the manual.
Closing this card as complete!
