### ISSUE TITLE
2024_10: BUG: correct behavior of Team PSD map & sliders

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3306]
❗ **If possible, have maps on slide decks and slide decks on demo by Wednesday COB, October 16. Before AHSR talks on Thursday.**

## Current State:
- Bug identified during 10/9/24 #sim_ui_workflow meeting. 
- Team PSD map / sliders are not functioning properly at mtl.how/teampsd. Examples:
  - console is giving "failed to load resource" errors when generating the map "Edit Slider" page (v2 API)
![image](https://github.com/user-attachments/assets/056faf91-c0af-4098-bfaa-870db2bb622e)
  - 3 of 5 map sliders work now

## AC:
- Team members are able to add themselves to specific maps.
- Team members are able to locate their pictures in a specific geographic location on their relevant workflow.

**Comment by matthewtomo** [comment]
- Bug has been addressed and maps are available in PROD.
- Future development on the maps feature is being tracked on #3292

**Comment by lzim** [comment]
Thx! @matthewtomo
