### ISSUE TITLE
2024_11: remove introduction sentence from how/why use case video transcripts

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3313]
**From wk1 2024_11 training_workflow:** Lindsey would like to remove "Hi I'm ..." from transcripts of how/why videos. Example:

![image](https://github.com/user-attachments/assets/c540da7f-165c-466d-b77b-8ae6337e3766)

## AC: 
- [x] all "Hi, I'm . . ." sentences removed from feature branch of _MTL_ Manual
- [x] edits are live in published _MTL_ manual

**Comment by ljmoody** [comment]
✅ verified changes are live in _MTL_ manual.
**#adjudicate_memo:** changed points estimate from 2 to 1, based on effort needed to complete task.

**Comment by lzim** [comment]
You're amazing thanks @ljmoody
