### ISSUE TITLE
Sankey for tt report

### ISSUE THREAD

**Issue by saveth** [lzim/teampsd#335]
@staceypark @lzim Based on the meeting we had during lunch time. Here are the decisions we made:

@TomRust will determine which variables are used for the Sankey that should be pulled out.

@jamesmrollins will add the variables under the header Sankey in the psy extract.

@saveth will update the tt report to include the Sankey graph for psy.

**Comment by jamesmrollins** [comment]
I have also put the details for this under PSY Module Update

**Comment by lzim** [comment]
Thanks 🙏🏾 @jamesrolllins and @saveth!!

**Comment by TomRust** [comment]
I emailed this to everyone, but wanted to close the loop here, too.  The variables needed for the Sankey and associated bar charts are:
For Base Case Sankey: 
 - A, B, C, D, E, F, G
For Base Case Bar Chart:
 - C-Bars, D-Bars, E-Bars, G-Bars, H-Bars
For Experiment Sankey: 
 - Exp-A, Exp-B, Exp-C, Exp-D, Exp-E, Exp-F, Exp-G
For Experiment Bar Chart:
 - Exp-C-Bars, Exp-D-Bars, Exp-E-Bars, Exp-G-Bars, Exp-H-Bars

**Comment by lzim** [comment]
Great, @saveth is this issue ready to be closed then? 
I believe the updated tt code is posted and we just need to test it with R21 teams that worked in PSY

**Comment by saveth** [comment]
This issue is ready to be  closed. The next step is for @staceypark to test the conversion from html to pdf or outlook for the mail out to the various psy team.
