### ISSUE TITLE
Session 12 Done Do

### ISSUE THREAD

**Issue by dlkibbe** [lzim/teampsd#345]
@staceypark @lzim I was reviewing Session 12 see files and noted the Done Do language is repetitive. Is this correct? Can you take a look?

**Comment by lzim** [comment]
@dlkibbe 

I'm not sure if @staceypark made edits based on this comment before moving to mtl.how for the MTL 1.8 release to PROD, but I don't see redundancy here (i.e., looks okay to me):

https://github.com/lzim/mtl/blob/master/session12/s12_learner/mtl_session12_see.md

I'll close, but we can re-open this issue if I'm missing something. Thanks!
