### ISSUE TITLE
Browser Guidance Messages 

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#350]
Hi Team,

We received a recommendation last week to try to provide an omnipresent browser recommendation message for both the Data UI (Explorer preferred) and Sim UI (Chrome preferred within VA). I agree that this can be hard to remember and frustrating if you get it wrong.

I've seen a couple of these lately from other folks:

Example 1 - Basecamp:
![browser warning 1](https://user-images.githubusercontent.com/7454688/56967209-a3e9bb00-6b15-11e9-8b89-f5c012aa06b5.png)

Example 2 - GitHub:
![browser_warning2](https://user-images.githubusercontent.com/7454688/56967272-ba901200-6b15-11e9-947f-1a415c5fe483.png)

Is there any good way to add something like this?  

@jamesmrollins @holbrooa @saveth 

FYI: @TomRust @dlounsbu @branscombj @dlkibbe @staceypark

**Comment by branscombj** [comment]
From the examples above, it looks like the target application would have to offer that popup. If it's a matter of "better" instead of "required", then maybe we put a "recommended browser" message on our UI?
![image](https://user-images.githubusercontent.com/29778290/56968606-7a3e8d00-6b31-11e9-9266-bb27be1f56b6.png)

**Comment by jamesmrollins** [comment]
The issue is the nobody, including Microsoft, wants anyone to use Internet Explorer.  It is a very patched up browser that is not very secure.  I think the message should focus on that, similar to what GitHub says. It shouldn't matter, performance wise, which browser you use among the top three (Chrome, Edge, Firefox).

I think @branscombj location suggestion for the message would be ideal.

**Comment by staceypark** [comment]
Or maybe could it be between the MTL logo and the Username box?

**Comment by lzim** [comment]
Thanks @branscombj @jamesmrollins 

I agree with Jane and James regarding the location. And, I agree with James that it would be ideal to indicate all the browsers that work fine. Recommend:

- Recommended browsers: **Chrome, Edge, Firefox, Safari**
- Please make it VA primary bright red: #C4262E

_This is what we implemented for the Data UI_
![image](https://user-images.githubusercontent.com/7454688/57002337-7c294000-6b73-11e9-8a0b-e40a2001c771.png)

**Comment by jamesmrollins** [comment]
@lzim  Mock up:


![image](https://user-images.githubusercontent.com/30132017/57006372-18b00a00-6b95-11e9-8e72-ea351602fa64.png)

**Comment by lzim** [comment]
@jamesmrollins looks good!

**Comment by jamesmrollins** [comment]
@lzim we didn't get the guidance changes in last night, but definitely by tomorrow morning.

**Comment by staceypark** [comment]
@lzim In light of what we saw in IE this morning - should we revise the warning message to "Not supported in IE. Compatible only with Chrome, Edge, Firefox, or Safari" or something to that extent?

**Comment by lzim** [comment]
@jamesmrollins and @staceypark 

Yes, I think so, Stacey. James, this morning we saw a team lead log in to the sim in Explorer and it was missing functionality, _not just clunky_. We'll have to follow these other vendors and say NO to Explorer, I think.

Recommended edit:
**Not supported in Explorer. Compatible with Chrome, Edge, Firefox, or Safari.**

**Comment by lzim** [comment]
Great work to get this implemented on the **Data UI** and **Sim UI**

Thanks @jamesmrollins and @holbrooa @saveth !! 👏 

Closing this issue.

**Comment by lzim** [comment]
@jamesmrollins 

- See typos: no space after "For best results,please..."
- Edit to "Internet Explorer is not supported by the Simulation User Interface"
- The two sentences need periods.

![image](https://user-images.githubusercontent.com/7454688/57798551-d42e7d80-7701-11e9-8f94-3d50c5b0ae07.png)

**Comment by jamesmrollins** [comment]
Check - corrected by tomorrow.

**Comment by branscombj** [comment]
> @jamesmrollins
> 
> * See typos: no space after "For best results,please..."
> * Edit to "Internet Explorer is not supported by the Simulation User Interface"
> * The two sentences need periods.
> 
> ![image](https://user-images.githubusercontent.com/7454688/57798551-d42e7d80-7701-11e9-8f94-3d50c5b0ae07.png)

Really picky, but is it the UI that doesn't support IE, or IE that doesn't support the UI? I thought the correct wording would be Internet Explorer does not support the *MTL* simulation user interface. In which case I'd put the 2nd sentence first.

**Comment by jamesmrollins** [comment]
Actually, it is “Internet Explorer is not supported by Forio,” which means they do not design or implement any code structures that enable usage of Explorer.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by branscombj** [comment]
> Actually, it is “Internet Explorer is not supported by Forio,” which means they do not design or implement any code structures that enable usage of Explorer. Get Outlook for iOS<https://aka.ms/o0ukef>

Got it! Thanks.

**Comment by jamesmrollins** [comment]
We could just say, “MTL doesn’t work on Explorer, please use Edge, Firefox, Chrome or Safari for best results.”

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by branscombj** [comment]
Fine with me - I like plain language! Only please say "the *MTL* simulation user interface" or "the *MTL* sim UI" just so we don't send the wrong message about other *MTL* resources, some of which are agnostic or work best on IE.

**Comment by jamesmrollins** [comment]
Good point. Will do!

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by lzim** [comment]
@jamesmrollins and @branscombj

Please be sure to go to GitHub when you respond, not directly via email. I just edited the string of comments to remove email details.

I agree with Jane. Not only because we need learners to use Explorer for the Data UI, but we always have to use care not to conflate the Sim UI with _Modeling to Learn_. _Modeling to Learn_ is a multi-component change strategy that includes 1) virtual facilitation, 2) transparent local team data, and 3) participatory learning from simulation.

Recommended text:
**The _Modeling to Learn_ simulation user interface does not work on Explorer.
Please use Edge, Firefox, Chrome or Safari via desktop or mobile.**

**Comment by lzim** [comment]
@jamesmrollins okay closing this again :sweat_smile:
