### ISSUE TITLE
Lucid Issues to Troubleshoot

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#353]
Starting an issue for any Lucid issues occuring

**Comment by lzim** [comment]
@theresaschmitz 

Can you please take a screenshot of what you're seeing on Lucid and add it here?

**Comment by lzim** [comment]
@theresaschmitz 

Here is what you should be seeing:

![image](https://user-images.githubusercontent.com/7454688/57798022-954bf800-7700-11e9-93dc-f871d9cc1a6a.png)

**Comment by theresaschmitz** [comment]
![image](https://user-images.githubusercontent.com/49293536/57798251-5a56be00-771a-11e9-9913-e5fd7bdb3979.png)

**Comment by staceypark** [comment]
@theresaschmitz Based on your screenshot above, it actually looks like you were not joined in the meeting. There should have been a "Join Meeting" red button above this, where all the features Lindsey was mentioning in meeting should have showed up.
