### ISSUE TITLE
R and RStudio not knitting properly to html

### ISSUE THREAD

**Issue by saveth** [lzim/teampsd#358]
@staceypark @lzim 

With our version upgrades for RStudio and R, this has really impact on some of our code (how it's currently written) and how we render. For now, the tt reports will only be rendered in html file format. I can't get one of the packages that generate the tables to render into Word. It'll require additional time to figure out how to trouble this.

**Comment by saveth** [comment]
1. Had IT re-install R on remote Desktop;
2. Rebuilt the R library from scratch instead of using the one on the shared server;
3. Interactive plots are now rendering in html, which suggest that issue may be caused by a conflicting packages/versions  in the same library

Need to test the new library on other machines to validate if the solution will work across the board or if this is a corner case.

**Comment by saveth** [comment]
Using the newly built library on another machine did not resolve the problem. The machine where the issues was resolved was on a machine with R 3.5.6, whereas the machine that is still having issues have R3.5.3. Submitting another IT install ticket to determine if the R version is the culprit.

**Comment by lzim** [comment]
Thanks @saveth

@staceypark it would be good to orient @jessfroe to how to create help tickets, track them in the TeamPSD folder, and show her the list of TeamPSD workstations

**Comment by saveth** [comment]
IT finished installing 3.6.0 on the second machine and the new library packages work. No issues with creating the graphics for the tt report. 

@staceypark @jessfroe Should we request IT to install 3.6.0 on all TeamPSD machines?

**Comment by staceypark** [comment]
@saveth Yes please!

In general, if we are updating one machine, it's good practice to submit an IT ticket for all TeamPSD machines. In this case, looks like you wanted to see if the R version would solve our issues before propagating.

**Comment by saveth** [comment]
@lzim @staceypark @jessfroe @swapmush  I just submitted a HelpDesk ticket to have R updated on all the team machine in the center. Ticket is in our team folder. :smile

**Comment by lzim** [comment]
Thanks @saveth!

I re-opened the issue.

**Comment by lzim** [comment]
@saveth Is there an update on this HelpDesk ticket?  

Should all the qualitative workgroup members check to make sure everything is working on their machine?
Also, should this instruction file "Rlibrary_setup" be updated? 
Thanks 🚀 

FYI: @teampsdkathryn @dlounsbu @swapmush @jessfroe @staceypark

**Comment by saveth** [comment]
@teampsdkathryn @dlounsbu @swapmush @jessfroe @staceypark

I followed up with HelpDesk last week, they say the ticket has been assigned to our local IT. We're just waiting for Mike to do the installation.

**Comment by lzim** [comment]
> @teampsdkathryn @dlounsbu @swapmush @jessfroe @staceypark
> 
> I followed up with HelpDesk last week, they say the ticket has been assigned to our local IT. We're just waiting for Mike to do the installation.

Savet, will you please ping Mike about this? We really need to make sure everyone is current ASAP this week. 

Also, I don't think you answered this question: **Should this instruction file "Rlibrary_setup" be updated?**

Thanks!

Lindsey

**Comment by saveth** [comment]
@lzim The Rlibrary setup is the same as it has been. The only difference is that people have to click on "User Accounts" twice instead of once with Windows 10 update. Sadly, the original instructional document (word format) was lost when they updated my machine to Windows 10.

**Comment by saveth** [comment]
Per local IT request, the request for R update was resubmitted  as 7  separate tickets.

**Comment by saveth** [comment]
@lzim @staceypark @jessfroe @swapmush @teampsdkathryn 

Hi all! IT just pinged me that they just finished installing R 3.6.1 on our machines. Please check to make sure it's installed on your computer. Thanks, Savet

**Comment by saveth** [comment]
@lzim @staceypark @jessfroe @swapmush @teampsdkathryn 
IT  had installed R 3.6.1 on everyone's local machine a couple weeks ago and no one has posted any issues on this, so I'm closing this issue.

**Comment by lzim** [comment]
Thanks @saveth!

It was all working on my personal machine and in the conference room, I believe.

FYI @staceypark @jessfroe @swapmush @teampsdkathryn 
> IT  had installed R 3.6.1 on everyone's local machine a couple weeks ago and no one has posted any issues on this, so I'm closing this issue.

Please make sure everyone is fully operational!
