### ISSUE TITLE
1.8 CC Output File 

### ISSUE THREAD

**Issue by saveth** [lzim/teampsd#362]
Hi @jamesmrollins! As I'm updating tt report, I'm noticing that all my graphs matches the ones in the Result Dashboard, but not Referral Rate. This is what it shows in the Output and Text Result Dashboard:

![image](https://user-images.githubusercontent.com/12439059/58837927-e1100400-8611-11e9-87d3-1b3cb9f80134.png)

However, when I read in the export file to produce the same graph, I'm getting this:
![image](https://user-images.githubusercontent.com/12439059/58837970-07ce3a80-8612-11e9-8d50-145195b31735.png)

It looks like the Export File produces two rows for "Referral Rate". Line 30 and 47. Should I ignored line 47?

**Comment by lzim** [comment]
HI Everyone,

I'm going to loop @TomRust in on this, as he may be able to help with tracking this.
In general, I'd encourage liberal mentions of team members to make sure it catches the right team members' eyes. 👀 Thanks!

@saveth @jamesmrollins @staceypark

**Comment by saveth** [comment]
Tracking the duplicate variable labels were needed in the R code to identify which one were used in the sim graph, and which one was an icon label.
