### ISSUE TITLE
Data UI updates, polish, and validation in preparation for propagation.

### ISSUE THREAD

**Issue by holbrooa** [lzim/teampsd#371]
Issue articulation and task enumeration for bug annihilation, feature request accommodation, and levels 1 and 2 documentation (for Andrew's frustration moderation, not necessarily for team coordination) in preparation for propagation:

- [x] Verification that none of the existing level 2 documentation for CC, MM, Psy, Agg are misrepresentations, make necessary modifications and team notifications. 
- [x] Integration  and translation of splash pages' data model conceptualization for count aggregation differentiation (e.g. the distinct summation computation), visualization standardization, and propagation automation.
- [x] Self-affirmation recitation.
- [x] Ideation and implementation SP's gap threshold user communication.
- [x] Validation of SP gap threshold application to parameter calculation based on corner case permutation examinations.
- [ ] SP level 2 documentation and verification (reevaluation and final recommendation based on care episode perforation from gap threshold supplementation, if necessary).
- [ ] DataNotes documentation.
- [ ] Self-congratulation. Intoxication.

**Comment by lzim** [comment]
@holbrooa

Thanks, this is very clarifying 🤓
And the wit, very welcome! 😂

@staceypark
Let’s incorporate into the thinking we’re doing in parallel with @jamesmrollins on issue #373

**Comment by lzim** [comment]
hey @holbrooa Are you going to check a few things off your list above 😃 ?

FYI @staceypark
