### ISSUE TITLE
Intersession > SAY > SEE

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#375]
Morning @TomRust!

I'm putting the tables from the revised intersession guide into the SAY file, but it's taking some time to make the alignment work so that it's not confusing, and I see several missed opportunities for clinical language clinicians will understand, and framing that fits the _TOC_ principles.

### Intersession
- I continue to feel that the Intersession guide has to come first. 
- I found the IKEA example competing about, but don't think it's an analogous task, and it's putting details before the larger causal dynamics that are our goals and emphases based on our _MTL_ theory of change (TOC).
- In terms of the key thought process, the SAY guide actually doesn't efficiently come first.
- Instead, the identifying team-tailoring priorities based on the TOC comes first, then you fill in the session SAY guide, triaging to narrow down what you've prioritized and practiced.

### Recommended Steps:
1. Use the Intersession guide to identify the team priorities you will practice.
2. Fill in the SAY guide for that session based on the priorities you identify.
3. Practice the team-tailored script within the timestamps.

#### Things I'm working on:
- *There are some questions in the SEE guide that were absent from the SAY guide...*
- *I am cleaning up some of the reconciliation in the level of detail too. 

For example, the details for data, HF, Enc and Meas were too vague, which is likely why Jane and David couldn't answer some fate TAS questions a view weeks back.

#### Things I'm seeing:
1. I believe it's clearest to reinforce in the SAY guide whatever numbers the learner SEEs.
So that the facilitators script helps the learner to track where they are in in the guide.

2. I think the questions need to be reinforced by design much more - perhaps with an icon.
We talked about a pencil icon for tailoring with @staceypark, but we may even want a ? icon.

3. In general, the formatting of the SAY files is a mess of bullets and formatting that needs to be cleaned up/clearer.

4. The clock icons and time stamps from the intersession checklist have to be better aligned.

5. We likely need more standard offset information - like to denote a troubleshooting recommendation, like for error messages.

6. There are not enough mousework instructions in the SAY file, I'm adding some.

#### For Session 2 - I'm working with these links, numbers and questions below

**Intersession**
https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/checklists/inter_session_checklist.md

**SAY** 
https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/facilitator_say/mtl_session02_say.md

**SEE**
https://github.com/lzim/mtl/blob/master/session02/s02_learner/mtl_session02_see.md

**The SEE and SAY guides for session 2 have 7 numbered items with the following questions.
**I see 10 total questions** in the guides, that I believe would need to be "team tailored" during the "prioritize and practice" process.

I'll continue to update this post with the places that I'm tailoring that currently are not.

1.
ADDED: **This splashpage is designed so see trends relevant to your team vision of **__________________________** for the last two years.** 

2. ADDED: Tables and Clinical Detail
- There are three types View options on the upper right menu. __________________ [Team Lead's name] Will you please click through them, so we can see what they each display?
- Last meeting **________________________ [team members' names] mentioned concers with **__________________________ [themes from session 1 team vision].** 
- What View options are there and what do they mean?
- What filtering options are available?

3.

4.

5.

6.
- What stands out to you?
- What is most important to you to check out first?
- What is most surprising?

7.
- What data tab would you use to find out how many current patients on the team are engaged in a specific evidence-based psychotherapy? 
- What column shows you the session number (EBP template) that the patient is on?
- What viz tab would you use to see what the most common service encounters or visits are?
- Are there services that have been increasing over time? 
- Are there services that have been descreasing over time?

**Comment by lzim** [comment]
@TomRust and @staceypark 

Okay, I'm done futzing with the Intersession Guide for this morning, but I'm still editing the session 2 SAY guide. 

@TomRust will you take a look at the Intersession Guide first?

**Comment by dlounsbu** [comment]
@lzim @staceypark : I noticed that the formatting for the Readme.md files for mtl/session 11 and session 12 are old or not updated. Or, at least, they do not include the name of the Session.

**Comment by staceypark** [comment]
Clarification on new SEE/SAY/1pager decisions can be found on Issue #577 .
Further changes to guides should be identified and made through the document_tracker.
