### ISSUE TITLE
Create Team Data Table - run time error, login failed for user

### ISSUE THREAD

**Issue by dlkibbe** [lzim/teampsd#391]
Go to mtl.how/data
Using 640a0_mpd_team2 file
Trying to create a team data table for sim ui
Error message received
![image](https://user-images.githubusercontent.com/31182258/59469602-28ed1300-8dea-11e9-808e-30eeb65e1bb2.png)

**Comment by holbrooa** [comment]
Duplicate. See issue 392 https://github.com/lzim/teampsd/issues/392

Closing.
