### ISSUE TITLE
Data UI Run time error 52 when generating 

### ISSUE THREAD

**Issue by dlounsbu** [lzim/teampsd#393]
---
**Describe the bug**

In the Data UI, the create Team Data button gives "run time error 52." 

**To Reproduce**
1. Go to 640 Data UI Splash page.
2. Select clinics for team's data. 
3. Click on Create Team Data.
4. See error window that pops up. 

**Desktop (please complete the following information):**
 - Browser: Explorer

**Comment by holbrooa** [comment]
Duplicate issue. See https://github.com/lzim/teampsd/issues/392

Closing.
