### ISSUE TITLE
Y-axis label isn't quite right...It should be "Visits per month" or "Unique Patients per Month"

### ISSUE THREAD

**Issue by TomRust** [lzim/teampsd#394]
---
Step 1: Click raw to copy the code text below. 
Step 2: Click the link to create a new issue for the data splashpage and data user interface https://github.com/lzim/teampsd/issues/new.
Step 3: Edit the details to create a report that will help us improve mtl.how/data and the data UI.
labels: bug
assignees: holbrooa
---

**Describe the bug**

**To Reproduce**

**Expected behavior**
Chart y-axis labels are showing "Visits," as if the charts were bar charts or pie charts. But the x-axis is time, so the units are actually a rate of visits per month.  The y-axis labels should all be "... per month."

**Screenshots**
![image](https://user-images.githubusercontent.com/32961420/59470064-74ec8780-8deb-11e9-89c9-258e7ff1b10c.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by holbrooa** [comment]
Well, I see what you mean, but I would prefer not to label it that way. Two reasons: I think it's totally normal for a line graph to label the y axis with just the value and not the x-axis "per" part. So you just read it as y thing per x thing. I've seen that a lot, so I think it's normal - maybe it's technically wrong I guess. Anyway, the bigger second reason is that the time chunks are dynamic. You can click around to change these kinds of charts to be in weeks or years, but then the y axis label wouldn't change.

**Comment by lzim** [comment]
@tomrust and @holbrooa

I’m with Andrew on this one 😸

**Comment by holbrooa** [comment]
Talked to Tom. Closing issue.
