### ISSUE TITLE
Edge login failure for simUI

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#395]
@jamesmrollins 
I tried to log in to the sim using Edge on this MPD Windows desktop and got this after I entered my password and tried to select a world. This error came up instead of the expanded drop-down menu of worlds to choose from. I unblocked popup blocker
![image](https://user-images.githubusercontent.com/29778290/59473829-eda61080-8df8-11e9-97de-3d78f26123d4.png)

**Comment by lzim** [comment]
@jamesmrollins I just had the same issue on another VAPAHCS computer lab desktop (Windows). After seeing it, I checked the browser settings and popups were blocked. I unchecked to allow popups, closed the browser, reopened it, and had this again.

![image](https://user-images.githubusercontent.com/7454688/59557519-8de26d80-8f90-11e9-8a71-da2b774bfbe5.png)

**Comment by jamesmrollins** [comment]
I am not able to recreate this error on systems outside the VA.   I therefore am going to wait until I have established Citrix access and can run through the test together with the DEV team.

**Comment by jamesmrollins** [comment]
This error only occurs when using Edge within the VA domain.  There must be an issue within the settings.  DEV - please investigate which settings may cause the above error and offer suggestions.

**Comment by jamesmrollins** [comment]
@TomRust @branscombj @lzim @holbrooa @staceypark @saveth @jessfroe 

I am going to open a ticket with OIT regarding this issue.  We have attempted to recreate this issue by manipulating various settings in Edge with no luck.  This appears to be only an issue when using Edge on the VA domain.  Will likely require discussion with the entity that is responsible for browser policy within the VA.

**Comment by jamesmrollins** [comment]
@staceypark @jessfroe  Can you provide me with the browser version that is on the VA computers there in Menlo Park.  It can be found in Settings all the way on the bottom of the tile.  A screen capture would be grand!! Thanks, James

**Comment by jessfroe** [comment]
![image](https://user-images.githubusercontent.com/52052518/60824799-223e8b00-a15f-11e9-9178-53e94deef040.png)

**Comment by jamesmrollins** [comment]
@TomRust @branscombj @lzim @holbrooa @staceypark @saveth @jessfroe . I thought I would be able to go a little further with this issue.  Unfortunately, the desktop version of my Citrix portal is Windows 7, therefore does not have Edge.  Has anyone just put in a ticket to the Help Desk to see if it can be resolved?  I know we have not been able to reproduce this issue outside the VA.

Let me know how you wish to proceed.  Thanks, James

**Comment by branscombj** [comment]
> 
> Let me know how you wish to proceed. Thanks, James

@jamesmrollins I just logged in on my work desktop (not from Citrix) in Edge and had no problem. In fact the SimUI looked good and seemed at quick glance to be fine in Edge.

I don't know if the problem is something that's been resolved or had to do with being inside the Citrix desktop; but I'd say let's drop this issue unless/until we see it being a problem. We've been emphasizing using Chrome anyway.

Thank you for your trouble!

**Comment by jamesmrollins** [comment]
Thank you @branscombj for checking.  However, there is a remaining possibility - @staceypark @saveth @jessfroe can one of you try logging in from Menlo Park, to remove the possibility this may have been a local issue?

**Comment by lzim** [comment]
@staceypark Will you please test this tomorrow/Thursday and update James?

**Comment by jamesmrollins** [comment]
Hi @lzim. @staceypark and I already tested this using a Menlo Park computer.  Whatever was preventing Edge from working must have been resolved, as the Edge browser worked fine. This issue can be closed.

**Comment by lzim** [comment]
Thanks James, then I will close this Issue.
