### ISSUE TITLE
9/10 Facilitator Dashboard Feature Requests

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#397]
Hi @jamesmrollins 

We noticed two things today we wanted to inquire about in the Facilitator Dashboard:

1. The ability to see what world/group you are reviewing.
2. We also noticed that it doesn't always indicate what module it is, but I believe it may only *Suicide Prevention.*

![image](https://user-images.githubusercontent.com/7454688/59475135-c9e5c900-8dfe-11e9-9b36-66afa6422731.png)

Thanks!

FYI: @staceypark

**Comment by jamesmrollins** [comment]
@lzim this will take 8-10 hours to complete the changes above.  Do we have permission to proceed?

**Comment by lzim** [comment]
Yes @jamesmrollins!

**Comment by jamesmrollins** [comment]
@hirenp-waferwire you are cleared to begin development of the changes described above. thanks, James

**Comment by jamesmrollins** [comment]
@saveth @TomRust @staceypark Fellow Leads 😁

I am trying to test the Facilitator Dashboard in TEST.  Would y'all do me a big favor?  

1.	1.  Login to the TEST environment, and choose the facilitator_test_ind world.
2.	2.  Open a module and Run an experiment.  Any experiment is fine.  
3.	3.  Save the experiment.  Any name is fine.

This should only take about 10 minutes, tops. I promise! 🤞

**Comment by jamesmrollins** [comment]
Thank you @saveth and @TomRust for your help testing.  The facilitator dashboard appears to be working correctly with its new features.  DEV is done, unless something comes up.

**Comment by lzim** [comment]
@jamesmrollins @saveth @TomRust Thanks!!!!!

@staceypark and @ritahitching 
This needs to be in the **document_tracker** and documented for training. 
- Does it go in the **detail_facilitate** _and_ **team_document** columns?

**Comment by staceypark** [comment]
updated on #601 and #602 for documentation
