### ISSUE TITLE
Improve Team Data Table in PSY

### ISSUE THREAD

**Issue by dlkibbe** [lzim/teampsd#399]
![image](https://user-images.githubusercontent.com/31182258/59527831-88522e00-8e91-11e9-8b18-a341a2a3057f.png)

We found the table super confusing today! Our instinct is to read across the rows, but there are actually 3 different tables in the main table (the supply info, the patient diagnostic cohort info, and the patient flow info).  Could you change the format (add some dividing lines?) It would be great to add the New Patient Start Rate, too!

**Comment by saveth** [comment]
@lzim I double-checked the Psy “New Patient Start Rate” variable today. It exists  in the ModelParameter file, but does not exist in the master_crosswalk. Either that variable is not used or it is called something different.

**Comment by lzim** [comment]
Thank you, @saveth

FYI: @jamesrollins we are trying to track this down in the documentation to clear up this issue.

**Comment by jamesmrollins** [comment]
@lzimom @saveth @TomRust @holbrooa @staceypark 

My research found the following:

**Facts bearing on the problem:**
1.  The variable name "New Patient Start Rate" is contained in the Model Parameters file.  However, when the name changed is not clear. Perhaps @holbrooa can illuminate when the name changed.
2.  There is no "New Patient Start Rate" or any of its similar names in the master_crosswalk_table.xlsx.
3. There is no record of a design request to add this variable to the Team Data Table, see issue #298 1.7 to 1.8 Agile Development and issue #319. This table went through multiple design reviews, and redesigns. See also below, which is from version 1.5 of the design of the PSY Team Data Table, which does not contain the "New Patient Start Rate" variable:
![image](https://user-images.githubusercontent.com/30132017/59929554-e46b0400-93f5-11e9-9d51-bbf588d0f134.png)

4. There is no "New Patient Start Rate" model variable in the latest Vensim model file. However, there is a model variable called " Team Data on New Patient Starts," which uses the "New Patient Start Rate" in the ModelParameters.xlsx file (see picture below).

![image](https://user-images.githubusercontent.com/30132017/59928808-64906a00-93f4-11e9-86f0-cad0ba02b266.png)

5.   When the PSY model and its associated ModelParameter.xlsx file was first created in 11/17, there was not a "New Patient Start Rate;" however, there was a "NewPatsPerWeek" variable that fed the model. Similarly, the psy_ver8_11_17 model had a "Team Data on New Patients Referred to Psychotherapy," (see below under spreadsheet).

![image](https://user-images.githubusercontent.com/30132017/59930483-d1593380-93f7-11e9-998c-ec2bc40f1341.png)

![image](https://user-images.githubusercontent.com/30132017/59930274-74f61400-93f7-11e9-985c-1de4c2dde1a0.png)

6. PSY model updates for the 1.8 development efforts where tracked using a checklist; however, the checklist did not contain a check for ModelParameters inter-dependencies.
7. @holbrooa was gone for several months.  It is unclear to the investigator who, if anyone, was assigned to cover his duties while he was away.

**Analysis**
1. The inclusion of the "New Patient Start Rate" into the model was never designed into the Team Data Table; therefore, not included in any of the original master_crosswalk_table.xlsx files. 
2. "New Patient Start Rate" is not a conventional name used between the ModelParameters file and the vensim PSY model.
3. Although checklists for design review where included in the PSY sprint, it did not include a ModelParameters file dependency in the checklist. Furthermore, in the opinion of the investigator, the absence of a critical team-member exacerbated the issue.

**Recommendations**
1. While the cross-functional checklist is a good start, it should be enhanced and expanded to include all areas that should be checked before a change is allowed to go-live. As the audit-trail shows, the team missed multiple opportunities to find and correct this error. Based on the maturity of the project, the identification of habitual inter-work group dependencies should be possible, and consistent with the use of the new kanban tracking system.
2. The ModelParameters, associated Vensim model and the SIM UI  **must** follow conventions for variable naming using prefixes to make audits such as these possible.  The current conventions are:
a. For data variables - "_data_ variable name"
b. For User inputs - "_user_ variable name"
3. Owners of given resources, such as SIM UI, ModelParameters, or Model should check to ensure the model_crosswalk_table is accurate.

**Comment by lzim** [comment]
Thank you @jamesmrollins for your review the relevant team documentation and processes.

I believe this issue was generated under as close to "real world" training conditions as we could create during the F2F.  Is that correct @TomRust?

In other words, even though the variable was in ModelParameters.xlsx, I believe our modeler, and the team, did not see this as an essential variable (feature) until requested by learners during a training drill. Then, when the issue was reported (by @dlkibbe when working with Tom) it appeared to be an error.

Based on the fact-finding above, this could have been identified as a potential error/omission had the team been following recommendations like those James made above. But, it is also possible, it still may not have been identified, until learners (or roleplaying learners) worked through a "real" problem.

Our summer training schedule, will create many other opportunities for this type of discovery. And, our methods for review of master_crosswalk by each workgroup clarified. 

@saveth @TomRust @holbrooa @staceypark Do you concur with James' recommendations above?

**Comment by jamesmrollins** [comment]
@lzim @TomRust @dlkibbe 

@TomRust and I discussed the design of the table, for which I will provide a mockup:

1.  We will use the collapsible table design used in SP.
2.  We will stack information elements, vice show them side-by-side for clarity.
3.  The order of the stack will be:

**First collapsible section**
- Appointment Supply
- AUD within 3 Months %
- DEP within 3 Months %
- OUD within 3 Months %
- Other within 3 Months %
- New Patient Start Rate
- Patient Flow | Return Visit Interval | Engagement Duration

**Second collapsible section**
All that is currently below the heavy red line above the Return Visit Interval and Engagement Duration Popups.

**Comment by jamesmrollins** [comment]
@lzim @TomRust @dlkibbe

Here is a mock-up for a collapsible table:

![image](https://user-images.githubusercontent.com/30132017/60630406-ccf52900-9dae-11e9-9970-ea89e72d8267.png)

**Comment by dlkibbe** [comment]
Thanks @jamesmrollins - has the New Patient Start Rate description been added to the "i" information in the Team Data table or does text need to be developed? @TomRust

**Comment by jamesmrollins** [comment]
Hi @dlkibbe, @TomRust and @holbrooa , here is what is published in the ModelParameters file.  Unless anyone objects, I will add this to the team data table "i" information:

 "An estimate of the number of new patients starting with the team per week, calculated from the number of patients seen for psychotherapy in one year who have never had a psychotherapy visit with this team before. (pts/wk)"

**Also, I failed to mention above that I intend to collapse the entire table, versus half.**

Upon further investigation, I also found that the "New Patient Start Rate" is not a variable in the Psy model.  So I will add it to the model and update the Master Crosswalk Table as well.

**Comment by jamesmrollins** [comment]
@dlkibbe @saveth @lzim @staceypark @jessfroe @holbrooa @TomRust , Debbie's comment above about the "i" information reminded me that we should go through the Dependencies Table in our next Workgroup Leads Meeting.  I have updated it with what I know below, but encourage more input:

///////////////////////////////////////////////////////////////////////////////////////////////////////////////

**Executive Summary**

*Estimated person-hours to complete:*

*Estimated date for completion:*

*Lead team for effort:*

*Key people (use @ assignment for people whose input will be necessary):*



**Step 1 - Complete the Interdependencies Table**

Workgroup Leads review information provided by originator and collaborate to identify interdependencies. Then they describe modifications that are needed in the appropriate column and estimate hours needed to make changes:
 
● *Workgroup Products* - This column identifies the workgroups and the products for which they are responsible. This column can be
  modified by a workgroup lead on an ad-hoc basis to add one-time products or can be modified to include new and enduring products.
  
● *Dependency?* - This column is used by the workgroup leads during collaboration to identify the existence of an interdependency.

● *Description of Change or Action Needed* - Workgroup leads briefly describe the change required.

● *Hours* - Workgroup leads estimate the person-hours required to complete the task.


Workgroup Products        | Dependency?  | Description of Change Needed               |  Hours Estimate
------------------------- | -------------|--------------------------------------------|-----------------
**Documentation**            
Brochures                 |              |                                            |
MTL See Guide             |              |                                            |
MTL Say Guide             |              |                                            |
MTL Videos                |              |                                            |
Post Test                 |              |                                            |
**Investigators**         |              |                                            |
Presentation              |              |                                            |
Quarterly Report          |              |                                            |
Annual Report             |              |                                            |
**Qualitative**           |              |                                            |
MTL Fidelity Checklists   |              |                                            |
Systems Thinking Codebook |              |                                            |
CFIR Codebooks            |              |                                            | 
**Quantitative**          |              |                                            |
Data UI                   |     Y         |                                                   |
Data Queries              |              |                                            |
SharePoint                |              |                                            |
Excel Outputs             |              |                                            |
ModelParameters           |       Y       |"i" information may need to be revised, add units of measure |
tt Reports                |              |                                            |
**Model**
CC                        |              |                                            |
MM                        |              |                                            |
PSY                       |     Y         |   Need "New Patient Start Rate" variable added, Update Github, update binary in Epicenter    | 2
AGG                       |              |                                            |
SP                        |              |                                            |
**Sim User Interface**    |              |                                            |
Model Diagram             |              |                                            |
"i"Information            |    Y          |  Add "i" information to table   | 2
Experiments               |    Y          |   Re-draw table, make collapsible (see concept)      | 8
Outputs/Charts            |     ?         |                                            |2
Exports                   |      ?        |                                            |2
Master Crosswalk Table    |    Y        | Add variable to table       | 1

**Step 2 - Identify Constraints that may affect the team’s ability to complete the necessary actions.** 

Describe the constraint in terms of capability, capacity or affect on grant research goals. If there are no constraints identified, then leave the table blank.

●  Type - The type of constraint identifies one or more resource areas that are affected.  

●  Workgroup - this is the workgroup responsible for developing a new or modifying an existing product.

●  Discussion/recommendation - A brief narrative that expands the information regardingthe constraint and ideally a recommendation for
   overcoming the constraint.

**Type Constraint (check all that apply) / Workgroup(s) Affected / Discussion/Recommendation**

- [ ] Capacity      
- [ ] Cost         
- [ ] Schedule     
- [ ] Interference 
- [ ] Capability   
- [ ] Other (describe)

**Step 3 - Identify supported milestones.** *Affix the milestone at the issue level using available GitHub milestones.*

**Step 4 - Indicate the due date for completing the actions identified above, assuming constraints are removed.**


**Step 5 - Identify the lead workgroup for the action (check one):**

- [ ] Documentation
- [ ] Investigators
- [ ] Quantitative
- [ ] Qualitative
- [ ] Model
- [ ] Sim UI

**Step 6 - Go to the top of this section and complete Executive Summary information**

Note to Workgroups:  Use the issue thread to document further discussion, alternatives development and estimates.  However, be sure to update this form if dates, team responsibility or other information changes.

**Comment by TomRust** [comment]
@jamesmrollins The new patient start rate is in the model. It's "Team Data on New Patients Starts"
About the Team Data Table: Why do the Engagement Durations for Starters says "Always"?

My formatting suggestions for the Team Data table are to:
1) not vertically align numbers in different units
2) group the "Starters," "Initiators," and "Completers" data more clearly
3) clarify that "Patient Flow" is the label for all the percentages, RVI, and engagement duration data.

One way to do this is below:
![image](https://user-images.githubusercontent.com/32961420/60741411-46b81e80-9f37-11e9-9a61-3853f417859c.png)

**Comment by jamesmrollins** [comment]
@TomRust @saveth @staceypark @jessfroe @holbrooa  Here is an updated mock-up of the changes asked for by @dlkibbe and @TomRust .  Please note the addition of an "i" information dependency and update.  Also should have review by facilitators and education document custodians.

![image](https://user-images.githubusercontent.com/30132017/60927620-6a44d700-a25f-11e9-97a1-77e17d923a27.png)

**Comment by jamesmrollins** [comment]
This issue closed and merged with #451.  Transferred labor estimates over to #451.
