### ISSUE TITLE
AGG: No BC button for Review Rate!

### ISSUE THREAD

**Issue by dlkibbe** [lzim/teampsd#400]
---
Step 1: Click raw to copy the code text below. 
Step 2: Click the link to create a new issue for the simulation user interface https://github.com/lzim/teampsd/issues/new.
Step 3: Edit the details to create a report that will help us improve the sim UI.
labels: bug
assignees: jamesmrollins

---

**Describe the bug**
Need to be able to see the base case review rate! The BC icon is missing from the Review Rate slider.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/31182258/59532853-b427e080-8e9e-11e9-8c73-1eb212fe12df.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jamesmrollins** [comment]
@TomRust @lzim @dlkibbe @branscombj @saveth @staceypark @holbrooa @dlounsbu 

1.  Will add "Review Rate" variable to sim.
2.  Will add "BC" button to experiment slider.

**Comment by jamesmrollins** [comment]
@TomRust during testing, it the BC button, which is mapped to "Review Rate" is showing a negative value (-25.12).  This is consistent with the desktop version of the sim.  Is it possible to have a **negative** review rate?  It seems to me that it should be limited to zero.

**Comment by TomRust** [comment]
Hi James,

Yes, we can have a negative Review Rate.  That means they do some intake appointments that don’t result in patients starting new services.  I think the itext explains this…or it should, anyway.  :)

--TOM

**Comment by lzim** [comment]
@TomRust Will you please open a pull request to add to the SAY guide, an explanation of how we can have a negative review rate?

Thanks!

FYI: @staceypark and original poster @dlkibbe
