### ISSUE TITLE
AGG: BC button for Intake not showing the actual BC value, but "-1" instead

### ISSUE THREAD

**Issue by TomRust** [lzim/teampsd#402]
---
Step 1: Click raw to copy the code text below. 
Step 2: Click the link to create a new issue for the simulation user interface https://github.com/lzim/teampsd/issues/new.
Step 3: Edit the details to create a report that will help us improve the sim UI.
labels: bug
assignees: jamesmrollins

---

**Describe the bug**
BC pop-up should show the actual rate at time 0, not -1

**Screenshots**
![image](https://user-images.githubusercontent.com/32961420/59536165-d4a86880-8ea7-11e9-8a39-2315e3ef7073.png)

**Comment by jamesmrollins** [comment]
This variable BC value is mapped incorrectly to "User Intake Evaluation Rate."  Should be mapped to "Intake Evaluation Rate."

![image](https://user-images.githubusercontent.com/30132017/59569356-31895780-903d-11e9-8a6c-84399656e966.png)

**Comment by TomRust** [comment]
@jamesmrollins -- Just checked AGG Model in PROD -- Looks like this issue is squashed!  The "BC" button for Intake Evaluation Rate now shows the actual value, not "-1."

Thanks!
