### ISSUE TITLE
Missing i information in PSY

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#404]
FYI: @lzim @branscombj @dlkibbe @dlounsbu @TomRust 

**Describe the bug**
Missing 'i' information in Experiments Section for 1) Reserve Appointments for New Patients and 2) Implement Intensive Outpatient Program.

Typo in 'i' information in Model Diagram Section for "Starting Rate."  The units in the parentheses should say (pts/wk) not (pts)

**To Reproduce**
1. In Chrome
2. In World: 640a0_mpd_team2_ind in Psychotherapy module

**Screenshots**
![image](https://user-images.githubusercontent.com/31089501/59541732-88652480-8eb7-11e9-890b-02d35bead6c9.png)

![image](https://user-images.githubusercontent.com/31089501/59541750-961aaa00-8eb7-11e9-8f5d-641d51876b14.png)

![image](https://user-images.githubusercontent.com/31089501/59541847-09242080-8eb8-11e9-9250-e7f0a850ea7f.png)

**Comment by jamesmrollins** [comment]
@TomRust I am going to need language for the above variables.  i will then update the model-popup-information file. Please put the variable descriptions in this thread.  Thanks James

**Comment by jamesmrollins** [comment]
@staceypark @TomRust I was able to find definitions for these variables in the model and updated the model-popup-information.xlsx file in all project instances (PROD, TEST and DEV and MTL/DEMO/PROD, TEST and DEV).  I have also updated the master file in OSF.  

For some reason, the Reserve Appointments for New Patients doesn't want to read.  I have elevated this to DEV for correction.  I will let you know when it is resolved.  Thanks - James

**Comment by jamesmrollins** [comment]
Below is a screen capture of the problem:

![image](https://user-images.githubusercontent.com/30132017/60054093-6f662b80-968e-11e9-93ce-955698bd2399.png)

**Comment by jamesmrollins** [comment]
@staceypark this has been corrected.  Will you indicate your satisfaction, if so, and close this issue?

**Comment by TomRust** [comment]
@jamesmrollins --  i text looks good now.  Thanks!
