### ISSUE TITLE
AGG: Model Diagram - All services are showing Intake rates, when they should be 0

### ISSUE THREAD

**Issue by TomRust** [lzim/teampsd#405]
---
Step 1: Click raw to copy the code text below. 
Step 2: Click the link to create a new issue for the simulation user interface https://github.com/lzim/teampsd/issues/new.
Step 3: Edit the details to create a report that will help us improve the sim UI.
labels: bug
assignees: jamesmrollins

---

**Describe the bug**
In the rate widgets in the model diagram, all services are showing Intake rates, when they should be 0.  The intake rates should only show up when the user has clicked on the "Intake" radio button.  The rates are showing up anyway, no matter what radio button is clicked.

**To Reproduce**
1. Go to the AGG model diagram.
2. Click on any service's radio button.
3. Scroll down to see the intake flows
4. See error -- even when a user is focused the diagram on CC/PSY/etc., we can still see the intake start and completion rates (even though the stock is zero! as it should be, because there are no CC/PSY/etc. patients in intake).

**Expected behavior**
When any radio button but Intake is selected, the Intake inflow and outflow rates should be zero

**Screenshots**
![image](https://user-images.githubusercontent.com/32961420/59554216-679edc80-8f54-11e9-8c11-83c63dbfa10d.png)
![image](https://user-images.githubusercontent.com/32961420/59554221-7be2d980-8f54-11e9-9fa4-6559be20bd38.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jamesmrollins** [comment]
@TomRust i need the data file that you used for this issue.  The model and the SIM UI are returning the same values. I used 640a0_mpd_team1_2019_06_13.xlsx to test and they are behaving consistent with each other.

**Comment by TomRust** [comment]
@jamesmrollins -- I just checked out the AGG model in PROD -- it looks like this issue has been squashed!  Both Intake Rates and the one Intake stock are all showing zero patients/week (or patients) when any other service is selected.  

Thanks!
