### ISSUE TITLE
Visual fixes in Agg

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#406]
**Describe the bug**
1. Intake Evaluation rate green tile and the rate dial right below it are overlapping. Can we separate them?
2. Can the small "i" circle for "Treatment Decision Rate" be located closer to the rate circle instead of the stock rectangle? I know that it refers to the rate circle and yet looking at it I got confused because it looked anchored to the stock rectangle.

**To Reproduce**
In AGG in Model Diagram right under the "Patients" header.
Shouldn't be a world specific issue, but I was in my individual world in 640a0_mpd_team3

**Screenshots**
![image](https://user-images.githubusercontent.com/31089501/59554634-b9e2fc00-8f5a-11e9-820d-1ec1746b4a3e.png)

![image](https://user-images.githubusercontent.com/31089501/59554661-370e7100-8f5b-11e9-8b20-c72a8206c679.png)

**Comment by jamesmrollins** [comment]
@staceypark there are 4 resolutions that are supported.  When there is an in-between resolution, you can get performance like you are showing above.  Thus, to determine root cause, i would need to know your screen resolution when you saw that issue. Thanks James

**Comment by jamesmrollins** [comment]
Hi @staceypark , did you see my response above?  if possible I would like to close this issue.  Thanks, James

**Comment by staceypark** [comment]
@jamesmrollins I've checked it on several machines and I see what you're saying about the varying resolutions. I'm going to close this issue as I agree this is cost-prohibitive and we have the best arrangement we can.
