### ISSUE TITLE
"Delay to Starting Service" label in AGG diagram

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#411]
**BEFORE FILLING OUT THIS TEMPLATE, PLEASE ASSIGN THIS ISSUE TO THE BUG KANBAN UNDER PROJECTS (YES, EVEN IF IT IS A FEATURE. ALL ISSUES START IN THE BUG KANBAN FOR TRIAGE). --------------------->**

**Describe the opportunity**
A clear and concise description of the opportunity for improvement.

**READ THIS FIRST**
- _A bug is a developed feature that has been working, that is no longer working._
- _A feature is a function, product or characteristic that requires research, design and development._

**If This Is a Bug, start with number 1 below, if a Feature, skip to number 7.**

**1. Please describe the steps to reproduce the behavior.**
a. Go to '...' Agg module
b. Click on '....' Model diagram
c. Scroll down to '....' Patients flow
d. See error What's really "wait time" is labeled "Delay to Starting a Service" in the diagram.

**2. Please describe the expected behavior.**

**3. Please provide a(n) screenshot(s) of the bug.**
If applicable, add screenshots to help explain your problem. You can use the Snip tool available in Microsoft Windows 10.
![image](https://user-images.githubusercontent.com/7454688/59557407-32af7b80-8f8e-11e9-99a7-81465a36ba0d.png)

**4. Please identify your operating system and browser version.** n/a
 a. Operating System: [e.g. iOS] 
 b. Browser [e.g. chrome, safari]
 c. Version [e.g. 22][You can find version by clicking on "help" then "about Chrome/edge/firefox" to get version information.]

**5. If you are using a smartphone, please complete the following information, otherwise skip to number 6.**

**6. Additional context**
 - Which function, model or team data where you trying to use?
 - Provide any other relevant information that may affect this issue.

**FEATURE**

**7. How would you like this feature to work?**
Describe your expectations in terms of outcomes/products/behaviors.

**8. How urgent is this request? (Urgent/Not Urgent)**

**9. Why is this feature important to you?**

**10. Is your feature request related to a problem? Please describe.**

**11. Is there a deadline or other scheduled constraint driving your request?"**

**12. Additional context**

**STOP HERE. INFORMATION BELOW IS TO BE FILLED OUT BY WORKGROUPS AS PART OF TRIAGE AND WORK BREAKDOWN PROCESS**

**Estimated person hours to complete:**

**Key people (use @ assignment for people whose input will be necessary):**

**Key dependencies:**
Are there other tasks that need to be completed first?

**Constraints:**
Is there a resource constraint that may affect the development of the feature?

**Gantt chart needed? Attach link and/or screenshot.**

**Comment by jamesmrollins** [comment]
@lzim we need to you state your expectations more clearly:

1.  Do you want the "i" information to use the word "delay" instead of "wait time?" - or
2.  Do you want the variables to be renamed to "wait time" versus "Delay to Starting a Service?" -and
3.  Rename balancing loop "Start Delays Affect Treatment Decisions" to "Wait Time affects Treatment Decisions?"

**Comment by lzim** [comment]
@TomRust @jamesmrollins 

Tom, can you help with this issue? I cannot remember what led to this issue, and unfortunately the documentation is not clear enough.

Would use of wait-time instead of delay make it more parallel to the available data?

Thanks!

Lindsey

**Comment by jamesmrollins** [comment]
Hi @lzim , @TomRust and I discussed this issue and have summarized our findings below:

**Discussion:**
- "Wait time" (within the VA) has a specific meaning that applies only to new patients. 
- In the AGG model we don't have New Patients, rather we have patients starting new services.
- Delay is a more neutral word that indicates a patient starting a service; therefore, it will not conflict with the meaning of "wait time."

**Recommendation**
In the AGG model we should use the word "Delay" instead of "Wait Time."

**Please indicate your concurrence/non-concurrence with comment (if necessary)**

**Comment by lzim** [comment]
@TomRust and @jamesmrollins 

Let's use "delay" throughout, rather than "wait time." Yes, make sure it is updated in the "i" information depicted in the screenshot above.

**Comment by jamesmrollins** [comment]
@lzim @TomRust  I put the following in the "i" Information spreadsheet and updated all repositories (DEV/TEST/PROD, all three in DEMO environment and in OSF).  

"The average delay time for the team's patients to start in a service after either an intake appointment or review.  It is calculated from the number of patients delayed and the rate at which they start each service.   Delay time is capped at 52 weeks (wks)"

**Comment by lzim** [comment]
@TomRust

Will you review to make sure the negative polarity is there? @jamesmrollins confirmed that it should be in TEST.

@jamesmrollins please close once this changes moves to PROD.

Thanks!

**Comment by TomRust** [comment]
@lzim @jamesmrollins -- We need to flip two signs: The arrows pointing at the Treatment Decision Rate should be negative!  As the wait time goes up, the treatment decision rate goes down.

![image](https://user-images.githubusercontent.com/32961420/61545979-a114ad00-aa16-11e9-88ba-bce3812af324.png)

see Vensim:

![image](https://user-images.githubusercontent.com/32961420/61545949-90fccd80-aa16-11e9-96fd-e2036cf5aa39.png)

**Comment by jamesmrollins** [comment]
@hirenp-waferwire  Please see polarity changes above and change in TEST and promote to PROD.  Thank you, James

FYI @lzim @TomRust

**Comment by staceypark** [comment]
@jamesmrollins @TomRust @lzim 
Double checking - the above conversation makes it seem like we shouldn't have "wait" at all in AGG, and yet there's this entire loop about wait times...?? (and the reveal complexity is called "RVI & Wait Times). 

Perhaps that loop is fine, but the "Patients Waiting to Start Service" stock is part of the "Start Delays Affect Treatment Decisions" loop and is the only variable in that loop using "waiting". Seems inconsistent to me...

![image](https://user-images.githubusercontent.com/31089501/62181819-69a4db00-b309-11e9-868f-372a83c36ea4.png)

**Comment by jamesmrollins** [comment]
@staceypark .  "Wait time" and "Delay time" have very specific meanings and should not be intertwined.  Below is the summary explanation from above in the thread:

"Wait time" (within the VA) has a specific meaning that applies only to new patients.
In the AGG model we don't have New Patients, rather we have patients starting new services.
Delay is a more neutral word that indicates a patient starting a service; therefore, it will not conflict with the meaning of "wait time.

**Comment by jamesmrollins** [comment]
@staceypark if you don't have any further questions or feedback, I would like to promote this to PROD tonight.  Thanks, James
