### ISSUE TITLE
Discrepancy - Chart model diagram titles and dropdown titles in results dashboard in Psy Model

### ISSUE THREAD

**Issue by dlkibbe** [lzim/teampsd#412]
**BEFORE FILLING OUT THIS TEMPLATE, PLEASE ASSIGN THIS ISSUE TO THE BUG KANBAN UNDER PROJECTS (YES, EVEN IF IT IS A FEATURE. ALL ISSUES START IN THE BUG KANBAN FOR TRIAGE). --------------------->**

**Describe the opportunity**
A clear and concise description of the opportunity for improvement.

**READ THIS FIRST**
- _A bug is a developed feature that has been working, that is no longer working._
- _A feature is a function, product or characteristic that requires research, design and development._

**If This Is a Bug, start with number 1 below, if a Feature, skip to number 7.**

**1. Please describe the steps to reproduce the behavior.**
a. Go to '...'Psy Model, Results Dashboard, 
b. Click on '....' Chart dropdown titles
c. Scroll down to '....' Patients in first visit, patients in 2 to 7, patients in over 7 visits
d. See error - **The chart dropdown titles do not match the titles on the main model diagram image pasted below.**

**2. Please describe the expected behavior.**
The chart titles should have the name of the variable, which is shown in the SIM UI.

**3. Please provide a(n) screenshot(s) of the bug.**

![image](https://user-images.githubusercontent.com/31182258/59557427-d862ea80-8f8e-11e9-8c0e-4b2f4dcf48ad.png)

**4. Please identify your operating system and browser version.**
 a. Operating System: Windows 10
 b. Browser - Chrome
 c. Version  - Version 73.0.3683.103

**5. If you are using a smartphone, please complete the following information, otherwise skip to number 6.**

**6. Additional context**
 - Which function, model or team data where you trying to use? - Team 3, Psy model, Patients in their first 3 months of psychotherapy section of the main model diagram.
 - Provide any other relevant information that may affect this issue.

**FEATURE**

**7. How would you like this feature to work?**
Describe your expectations in terms of outcomes/products/behaviors.

**8. How urgent is this request? (Urgent/Not Urgent)**

**9. Why is this feature important to you?**

**10. Is your feature request related to a problem? Please describe.**

**11. Is there a deadline or other scheduled constraint driving your request?"**

**12. Additional context**

**STOP HERE. INFORMATION BELOW IS TO BE FILLED OUT BY WORKGROUPS AS PART OF TRIAGE AND WORK BREAKDOWN PROCESS**

**Estimated person hours to complete:**

**Key people (use @ assignment for people whose input will be necessary):**

**Key dependencies:**
Are there other tasks that need to be completed first?

**Constraints:**
Is there a resource constraint that may affect the development of the feature?

**Gantt chart needed? Attach link and/or screenshot.**

**Comment by jamesmrollins** [comment]
Hi @dlkibbe @TomRust @lzim  !  I got to the bottom of this issue.  We only added "Starters," Initiators," and "Completers" to the labels of the main diagram.  The variable names did not change. Since the drop downs take the name directly from the variable list, we need would need to change the model variables to make the labels all consistent.  I could go either way, but if we change, it would affect the model, the master_crosswalk table and the Sim UI.  What do you guys want to do?

**Comment by jamesmrollins** [comment]
@dlkibbe @TomRust @lzim 
Disregard the above - DEV was able to update the chart labels in the code.  So a model change is not necessary at this point.  Please close if you are satisfied with change.  Thanks, James

**Comment by TomRust** [comment]
@jamesmrollins -- Just check this out in PSY PROD.  It is easier to find those patient stocks in the chart drop down list now that you added the "Starters," "Initiators," and "Completers" prefixes.  Thanks!
