### ISSUE TITLE
Labels in PSY team data table vs diagram

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#413]
**BEFORE FILLING OUT THIS TEMPLATE, PLEASE ASSIGN THIS ISSUE TO THE BUG KANBAN UNDER PROJECTS (YES, EVEN IF IT IS A FEATURE. ALL ISSUES START IN THE BUG KANBAN FOR TRIAGE). --------------------->**

**Describe the opportunity**
A clear and concise description of the opportunity for improvement.

**READ THIS FIRST**
- _A bug is a developed feature that has been working, that is no longer working._
- _A feature is a function, product or characteristic that requires research, design and development._

**If This Is a Bug, start with number 1 below, if a Feature, skip to number 7.**

**1. Please describe the steps to reproduce the behavior.**
a. Go to '...' sim UI -PSY module main section
b. Click on '....' Experiments section, Team Data Table + model diagram
c. Scroll down to '....' _Patient flow_ variable names in the team data table are not the same as the stock labels in the diagram. This lack of parallelism is confusing. 
d. See error

**2. Please describe the expected behavior.**

**3. Please provide a(n) screenshot(s) of the bug.**
If applicable, add screenshots to help explain your problem. You can use the Snip tool available in Microsoft Windows 10.
![image](https://user-images.githubusercontent.com/7454688/59557475-7c4c9600-8f8f-11e9-870a-6aca7ed7bae7.png)

**4. Please identify your operating system and browser version.**
 a. Operating System: [e.g. iOS]
 b. Browser [e.g. chrome, safari]
 c. Version [e.g. 22][You can find version by clicking on "help" then "about Chrome/edge/firefox" to get version information.]

**5. If you are using a smartphone, please complete the following information, otherwise skip to number 6.**

**6. Additional context**
 - Which function, model or team data where you trying to use?
 - Provide any other relevant information that may affect this issue.

**FEATURE**

**7. How would you like this feature to work?**
Describe your expectations in terms of outcomes/products/behaviors.

**8. How urgent is this request? (Urgent/Not Urgent)**

**9. Why is this feature important to you?**

**10. Is your feature request related to a problem? Please describe.**

**11. Is there a deadline or other scheduled constraint driving your request?"**

**12. Additional context**

**STOP HERE. INFORMATION BELOW IS TO BE FILLED OUT BY WORKGROUPS AS PART OF TRIAGE AND WORK BREAKDOWN PROCESS**

**Estimated person hours to complete:**

**Key people (use @ assignment for people whose input will be necessary):**

**Key dependencies:**
Are there other tasks that need to be completed first?

**Constraints:**
Is there a resource constraint that may affect the development of the feature?

**Gantt chart needed? Attach link and/or screenshot.**

**Comment by jamesmrollins** [comment]
Hi @lzim I think that @dlkibbe has already reported this problem.  In either case, some discussion is necessary to understand the desired end state.

**Comment by lzim** [comment]
FYI: @dlkibbe @tomrust @dlounsbu @branscombj @staceypark

@jamesmrollins 

Yes, #399 is the same. 

I think we need to be able to find the text shown by the stocks in the diagram.

“Starters”
