### ISSUE TITLE
AGG Model Section Reveal Complexity - 'fix open loop'

### ISSUE THREAD

**Issue by dlounsbu** [lzim/teampsd#414]
**BEFORE FILLING OUT THIS TEMPLATE, PLEASE ASSIGN THIS ISSUE TO THE BUG KANBAN UNDER PROJECTS (YES, EVEN IF IT IS A FEATURE. ALL ISSUES START IN THE BUG KANBAN FOR TRIAGE). --------------------->**

**Describe the opportunity**
A clear and concise description of the opportunity for improvement.

**READ THIS FIRST**
- _A bug is a developed feature that has been working, that is no longer working._
- _A feature is a function, product or characteristic that requires research, design and development._

**If This Is a Bug, start with number 1 below, if a Feature, skip to number 7.**

**1. Please describe the steps to reproduce the behavior.**
a. Go to '...'
b. Click on '....'
c. Scroll down to '....'
d. See error

**2. Please describe the expected behavior.**

**3. Please provide a(n) screenshot(s) of the bug.**
If applicable, add screenshots to help explain your problem. You can use the Snip tool available in Microsoft Windows 10.

**4. Please identify your operating system and browser version.**
 a. Operating System: [e.g. iOS]
 b. Browser [e.g. chrome, safari]
 c. Version [e.g. 22][You can find version by clicking on "help" then "about Chrome/edge/firefox" to get version information.]

**5. If you are using a smartphone, please complete the following information, otherwise skip to number 6.**

**6. Additional context**
 - Which function, model or team data where you trying to use?
 - Provide any other relevant information that may affect this issue.

**FEATURE**

**7. How would you like this feature to work?**
Describe your expectations in terms of outcomes/products/behaviors.

@branscombj and @dlounsbu would like to close the loop for "RVI Delays Affects Treatment Decisions" Balancing Loop. See 'open' loop in screenshot shown below.

![image](https://user-images.githubusercontent.com/20574023/59557526-cda95500-8f90-11e9-8d97-24245190e284.png)

**8. How urgent is this request? (Urgent/Not Urgent)**

**9. Why is this feature important to you?**

**10. Is your feature request related to a problem? Please describe.**

**11. Is there a deadline or other scheduled constraint driving your request?"**

**12. Additional context**

**STOP HERE. INFORMATION BELOW IS TO BE FILLED OUT BY WORKGROUPS AS PART OF TRIAGE AND WORK BREAKDOWN PROCESS**

**Estimated person hours to complete:**

**Key people (use @ assignment for people whose input will be necessary):**

**Key dependencies:**
Are there other tasks that need to be completed first?

**Constraints:**
Is there a resource constraint that may affect the development of the feature?

**Gantt chart needed? Attach link and/or screenshot.**

**Comment by jamesmrollins** [comment]
@dlounsbu @dlkibbe @lzim @staceypark @saveth @holbrooa @TomRust 

**Findings:**
1.  There are two variables that would close this loop, Appointments and Completing Rate.
2.  They are located at the top of the diagram and make direct causal arrows impossible.


**Alternatives:**
1.  Leave the model diagram as-is.  The facilitators would need to point out the relationship verbally.
2.  Add shadow variables (see picture below - please ignore colors).  There is white space available to do this.  Notwithstanding, the facilitators would need to add the shadow variables to their understanding.  This would incur cost to change model diagram picture.
3.  Add more details in "i" information that explains causal relationships.  This would be the minimal amount of change required and incur additional cost.

![image](https://user-images.githubusercontent.com/30132017/60201861-3351d880-97fe-11e9-96de-84a731066427.png)

**Comment by staceypark** [comment]
@jamesmrollins I believe this issue has been resolved and can be closed. If so, please close it.
