### ISSUE TITLE
Matching base case values from team data table and RVI numbers in Learning Mode Pop-up Box

### ISSUE THREAD

**Issue by dlkibbe** [lzim/teampsd#415]
**BEFORE FILLING OUT THIS TEMPLATE, PLEASE ASSIGN THIS ISSUE TO THE BUG KANBAN UNDER PROJECTS (YES, EVEN IF IT IS A FEATURE. ALL ISSUES START IN THE BUG KANBAN FOR TRIAGE). --------------------->**

**Describe the opportunity**
We tested in Medication Management module. The Start Rate (mean) (pts/wk) in the team data table are matching exactly the numbers in the pop up box for Base Case Values - if New Patient Start Rate is selected, then RVI = ... We saw this in this data set: 640a0_mpd_team1_2019_06_13.xlsx
640a0_mpd_team3_2019_06_13.xlsx 
 

**READ THIS FIRST**
- _A bug is a developed feature that has been working, that is no longer working._
- _A feature is a function, product or characteristic that requires research, design and development._

**If This Is a Bug, start with number 1 below, if a Feature, skip to number 7.**

**1. Please describe the steps to reproduce the behavior.**
a. Go to '...' Medication Management Module
b. Click on '....' Click on Team Data table and open Base Case Values pop-up box
c. See error: 

**2. Please describe the expected behavior.**
The Start Rate (mean) (pts/wk) in the team data table are matching exactly the numbers in the pop up box for Base Case Values for the New Patient start rates - in both data sets - is that normal??

**3. Please provide a(n) screenshot(s) of the bug.**
If applicable, add screenshots to help explain your problem. You can use the Snip tool available in Microsoft Windows 10.
![image](https://user-images.githubusercontent.com/31182258/59557544-3f819e80-8f91-11e9-9bad-f2170d5b6b1f.png)

**4. Please identify your operating system and browser version.**
 a. Operating System: Windows
 b. Browser Chrome
 c. Version [e.g. 22][You can find version by clicking on "help" then "about Chrome/edge/firefox" to get version information.]

**5. If you are using a smartphone, please complete the following information, otherwise skip to number 6.**

**6. Additional context**
 - Which function, model or team data where you trying to use?
 - Provide any other relevant information that may affect this issue.

**FEATURE**

**7. How would you like this feature to work?**
Describe your expectations in terms of outcomes/products/behaviors.

**8. How urgent is this request? (Urgent/Not Urgent)**

**9. Why is this feature important to you?**

**10. Is your feature request related to a problem? Please describe.**

**11. Is there a deadline or other scheduled constraint driving your request?"**

**12. Additional context**

**STOP HERE. INFORMATION BELOW IS TO BE FILLED OUT BY WORKGROUPS AS PART OF TRIAGE AND WORK BREAKDOWN PROCESS**

**Estimated person hours to complete:**

**Key people (use @ assignment for people whose input will be necessary):**

**Key dependencies:**
Are there other tasks that need to be completed first?

**Constraints:**
Is there a resource constraint that may affect the development of the feature?

**Gantt chart needed? Attach link and/or screenshot.**

**Comment by jamesmrollins** [comment]
@TomRust @dlkibbe 
I ran some tests this morning and determined the SIM UI is running consistent with the client version Vensim AGG model, according to the  mapping instructions below:

![image](https://user-images.githubusercontent.com/30132017/59568121-380ed380-902b-11e9-909e-e65ce5cc2268.png)


When I ran my test model parameters file, I did not see the phenomenon we see with the 640a0 file that @dlkibbe identified in the bug report. So we may be back to the coincidence hypothesis again.

**Comment by jamesmrollins** [comment]
@TomRust we found the following:

1.  Base Case Value mapping is reversed. 
2.  Exact matching of BC values to values contained in the Team Data table under same categories is impossible.  This may indicate improper mapping of variables to the Team Data table.

**Comment by jamesmrollins** [comment]
@TomRust @dlkibbe below is the corrective action.  I found this mismatch also in CC.

@hirenp-waferwire 
Please provide an estimate of time required to swap the labels in the BC popup for Learning Mode as shown below:

![image](https://user-images.githubusercontent.com/30132017/60548876-0f980200-9cd8-11e9-9e76-5f04a2922772.png)


![image](https://user-images.githubusercontent.com/30132017/60549012-73222f80-9cd8-11e9-9fd1-cfb1f6502d10.png)

**Comment by jamesmrollins** [comment]
@TomRust and @dlkibbe  I tested this against the client version of the Vensim model, and it now matches the spec above. With respect to the coincidence of matching numbers, I ran the file 640a0_mpd_team1_2019_06_13.xlsx in the MM model and it no longer matches like it did in Debbie's original observation.  I believe this issue is resolved.  If you agree, please indicate so in this thread and I will promote this change into PROD.

**Comment by TomRust** [comment]
I’ll check on Monday. Thanks, @jamesmrollins

**Comment by lzim** [comment]
@TomRust is this looking okay in TEST?

If so, then @jamesmrollins please do promote to PROD and close the issue.

**Comment by TomRust** [comment]
@jamesmrollins -- The BC pop-up table still looks screwed up to me.

In TEST, it looks like the pop-up table is pulling the data values for the New Patient Start Rate. There should be no team data in the pop-up table! 

![image](https://user-images.githubusercontent.com/32961420/61548311-6f521500-aa1b-11e9-910d-52aaa08a212f.png)


After looking into this in Vensim, though, there wasn't a variable in the model that shows the New Patient Start Rate if the use selects the "Existing RVI" learning mode, regardless of which learning mode they actually select.  

So, I added two new variables to MM and CC that should make it clear which variables to reference in the Base Case Values pop-up table:
"xxx If Existing Patient RVI is selected, then New Pt. Starts ="
"xxx If New Patient Start Rate is selected, then RVI ="

I'm going to drop the new .mdl files [here](https://github.com/lzim/teampsd/tree/master/model_workgroup/models/mtl_1.8_models).

**Comment by jamesmrollins** [comment]
@TomRust so I was trapped in a "Do loop" because the mapping is correct and it checked out against the model, but all along it was not structurally sound.  Meaning we needed new variables to map, which you have provided?

**Comment by jamesmrollins** [comment]
@hirenp-waferwire I will email the updated CC_PROD.vmf and MM_PROD.vmf files separately.  The new mapping is shown below:

for CC:
![image](https://user-images.githubusercontent.com/30132017/61571458-81967800-aa48-11e9-8c18-4b95ff503ba1.png)


for MM:
![image](https://user-images.githubusercontent.com/30132017/61571369-eef5d900-aa47-11e9-89b9-b41d6b8d4a12.png)

Thank you,
James

**Comment by jamesmrollins** [comment]
@TomRust it looks like we are also having some internal error problems associated with variable naming.  In CC and MM model, we get an error while running simulation with mapped new variables.  The reasons are a comma "," in the variable name string and the variable name length is out of range.  

I will rename these variables and provide a new binary file for CC, MM model and upload same to GitHub. 

See below variables  and errors.
>> CC Model Variables
"If Existing Patient RVI is selected, then New Pt. Starts ="
"If New Patient Start Rate is selected, then RVI ="

 >> MM Model Variables
"xxx If New Patient Start Rate is selected, then RVI ="
"xxx If Existing Patient RVI is selected, then New Pt. Starts ="

![1](https://user-images.githubusercontent.com/30132017/62710832-df194700-b9ac-11e9-9eb7-8447f2a333dc.png)

![2](https://user-images.githubusercontent.com/30132017/62710856-e6405500-b9ac-11e9-80bd-7ad431ab824e.png)

**Comment by jamesmrollins** [comment]
@TomRust this issue was resolved in code, so no updates to the model were made.

**Comment by staceypark** [comment]
checked PROD & looks fixed.
