### ISSUE TITLE
Save clinic list at runtime for parameter generation

### ISSUE THREAD

**Issue by holbrooa** [lzim/teampsd#419]
**BEFORE FILLING OUT THIS TEMPLATE, PLEASE ASSIGN THIS ISSUE TO THE BUG KANBAN UNDER PROJECTS (YES, EVEN IF IT IS A FEATURE. ALL ISSUES START IN THE BUG KANBAN FOR TRIAGE). --------------------->**

**Describe the opportunity**
Keep track of clinic list when parameters are generated.

**READ THIS FIRST**
- _A bug is a developed feature that has been working, that is no longer working._
- _A feature is a function, product or characteristic that requires research, design and development._

**If This Is a Bug, start with number 1 below, if a Feature, skip to number 7.**

**1. Please describe the steps to reproduce the behavior.**
a. Go to '...'
b. Click on '....'
c. Scroll down to '....'
d. See error

**2. Please describe the expected behavior.**

**3. Please provide a(n) screenshot(s) of the bug.**
If applicable, add screenshots to help explain your problem. You can use the Snip tool available in Microsoft Windows 10.

**4. Please identify your operating system and browser version.**
 a. Operating System: [e.g. iOS]
 b. Browser [e.g. chrome, safari]
 c. Version [e.g. 22][You can find version by clicking on "help" then "about Chrome/edge/firefox" to get version information.]

**5. If you are using a smartphone, please complete the following information, otherwise skip to number 6.**

**6. Additional context**
 - Which function, model or team data where you trying to use?
 - Provide any other relevant information that may affect this issue.

**FEATURE**

**7. How would you like this feature to work?**
When the data UI generates model parameters for a team, save the clinic list that defines that team so that it can be brought back into clinic selection (somehow).

**8. How urgent is this request? (Urgent/Not Urgent)**
Not Urgent

**9. Why is this feature important to you?**
It will be both easier for users who want to generate another file for the same team, and easier for the developer for debugging when a problem is reported with a parameter file.

**10. Is your feature request related to a problem? Please describe.**
Additional communication is required for debugging, because the developer needs the clinic list for the team to reproduce the error. There's also an extra (repeated) step for users to generate a new file for the same team. This use case isn't a good thing anyway, but it does happen.

**11. Is there a deadline or other scheduled constraint driving your request?"**
No.

**12. Additional context**

**STOP HERE. INFORMATION BELOW IS TO BE FILLED OUT BY WORKGROUPS AS PART OF TRIAGE AND WORK BREAKDOWN PROCESS**

**Estimated person hours to complete:**
4

**Key people (use @ assignment for people whose input will be necessary):**
@holbrooa for development, but the new functionality will need to be rolled into guides **if** it requires action on the user's part (e.g. a button to bring in the previously used team). Even if it doesn't require new user actions, it will at least change how the clinic selection screen looks and works in certain situations.

@lzim @staceypark 

**Key dependencies:**
Data UI guides, data UI propagation.

**Constraints:**

**Gantt chart needed? Attach link and/or screenshot.**
Not needed for development (too quick).

**Comment by staceypark** [comment]
@holbrooa has already implemented the save clinic list function.
I linked it to all of the documentation columns that it may affect & as such will close the issue.
