### ISSUE TITLE
Rmarkdown knit issues

### ISSUE THREAD

**Issue by joycepyang** [lzim/teampsd#42]
Hi Lindsey,

I saw a few things I want to try out tomorrow in terms of knitting Rmd files.  One solution that seems promising is the following chunk:

```{r setup, cache = F}
knitr::opts_chunk$set(error = TRUE)
```

It appears that lots of people have had the same issue where running individual chunks results in output but the knitting arrests at particular lines due to specific issues.  Apparently inserting error=TRUE will allow for the whole document to knit anyway.

Will update you with the results of this.

Joyce

**Comment by lzim** [comment]
I also found this as a longer range solution: https://cran.r-project.org/web/packages/checkpoint/index.html

The goal of checkpoint is to solve the problem of package reproducibility in R. Specifically, checkpoint allows you to install packages as they existed on CRAN on a specific snapshot date as if you had a CRAN time machine.

This may help us keep the packages that once worked, working for the team longer and more efficiently.

Thanks for your work on this Joyce!

Lindsey

**Comment by saveth** [comment]
@joycepyang is this still an issue? If not, can we close this ticket?

**Comment by joycepyang** [comment]
Yes I'm closing it now, thanks.
