### ISSUE TITLE
MM: Learning Mode Pop-up

### ISSUE THREAD

**Issue by TomRust** [lzim/teampsd#420]
Hi again James,

The synthetic data in the Learning Mode pop-up table is confusing users trying to make that choice (i.e., "So, for my team of two providers, if I click "Existing RVI," then I'll be starting over 500 new patients? That doesn't seem possible.")

Could we either get the real values in that data-set or remove the table completely?

--TOM

**Comment by jamesmrollins** [comment]
@TomRust this table cannot have any calculated values, since the simulation has not run at this point.  So the choice is either modify the table or remove it.

**Comment by lzim** [comment]
@jamesmrollins and @tomrust

It cannot have calculated values, but if a dataset is selected, then could it have the current team data values for New Patient Start Rates and Existing Patient RVI?

**Comment by jamesmrollins** [comment]
@lzim and @tomrust the data cannot be dynamic on the home page because the user is in the process of selecting the data file to use.  Once the user selects "play," the sim goes out to find and execute the contents of the data file.

**Comment by jamesmrollins** [comment]
@TomRust @lzim @dlkibbe @branscombj @dlounsbu @holbrooa @saveth 

As per discussion with Tom

**Findings:**
1.  There is no way for the SIM UI to provide data to the red data table in the Learning Mode dialogue box.  Since the sim does not read information directly from the model parameters file, there no way to read the data in prior to running the model.
2.  The red table shown in the dialogue is confusing, as it does not indicate it is an example and its helpfulness to improving the learners understanding is suspect, since it is not relevant to their team's data.

**Recommendation:**
1.  Delete the table.

**Comment by lzim** [comment]
@jamesmrollins and @TomRust 

Agreed. We must delete the table. 

Can it include instructions on where the learner needs to go to check the base case values in the Data UI or Team Data Table?

**Comment by jamesmrollins** [comment]
@tomrust @lzim sure, we can add more text - can you give me a gist Tom?

**Comment by jamesmrollins** [comment]
@lzim  Here is what we came up with:

"Refer to the Data User Interface, Medication Management tab of the MMParams.xlsx file for data regarding the team's New Patient Start Rates and Return to Clinic Visit Intervals."

**Comment by jamesmrollins** [comment]
**Executive Summary**

*Estimated person-hours to complete:*

*Estimated date for completion:*

*Lead team for effort:*

*Key people (use @ assignment for people whose input will be necessary):*



**Step 1 - Complete the Interdependencies Table**

Workgroup Leads review information provided by originator and collaborate to identify interdependencies. Then they describe modifications that are needed in the appropriate column and estimate hours needed to make changes:
 
● *Workgroup Products* - This column identifies the workgroups and the products for which they are responsible. This column can be
  modified by a workgroup lead on an ad-hoc basis to add one-time products or can be modified to include new and enduring products.
  
● *Dependency?* - This column is used by the workgroup leads during collaboration to identify the existence of an interdependency.

● *Description of Change or Action Needed* - Workgroup leads briefly describe the change required.

● *Hours* - Workgroup leads estimate the person-hours required to complete the task.


Workgroup Products        | Dependency?  | Description of Change Needed               |  Hours Estimate
------------------------- | -------------|--------------------------------------------|-----------------
**Documentation**            
Brochures                 |              |                                            |
MTL See Guide             |              |                                            |
MTL Say Guide             |              |                                            |
MTL Videos                |              |                                            |
Post Test                 |              |                                            |
**Investigators**         |              |                                            |
Presentation              |              |                                            |
Quarterly Report          |              |                                            |
Annual Report             |              |                                            |
**Qualitative**           |              |                                            |
MTL Fidelity Checklists   |              |                                            |
Systems Thinking Codebook |              |                                            |
CFIR Codebooks            |              |                                            | 
**Quantitative**          |              |                                            |
Data UI                   |              |                                            |
Data Queries              |              |                                            |
SharePoint                |              |                                            |
Excel Outputs             |              |                                            |
ModelParameters           |              |                                            |
tt Reports                |              |                                            |
**Model**
CC                        |              |                                            |
MM                        |              |                                            |
PSY                       |              |                                            |
AGG                       |              |                                            |
SP                        |              |                                            |
**Sim User Interface**    |              |                                            |
Model Diagram             |              |                                            |
"i"Information            |              |                                            |
Experiments               |              |                                            |
Outputs/Charts            |              |                                            |
Exports                   |              |                                            |
Master Crosswalk Table    |              |                                            |

**Step 2 - Identify Constraints that may affect the team’s ability to complete the necessary actions.** 

Describe the constraint in terms of capability, capacity or affect on grant research goals. If there are no constraints identified, then leave the table blank.

●  Type - The type of constraint identifies one or more resource areas that are affected.  

●  Workgroup - this is the workgroup responsible for developing a new or modifying an existing product.

●  Discussion/recommendation - A brief narrative that expands the information regardingthe constraint and ideally a recommendation for
   overcoming the constraint.

**Type Constraint (check all that apply) / Workgroup(s) Affected / Discussion/Recommendation**

- [ ] Capacity      
- [ ] Cost         
- [ ] Schedule     
- [ ] Interference 
- [ ] Capability   
- [ ] Other (describe)

**Step 3 - Identify supported milestones.** *Affix the milestone at the issue level using available GitHub milestones.*

**Step 4 - Indicate the due date for completing the actions identified above, assuming constraints are removed.**


**Step 5 - Identify the lead workgroup for the action (check one):**

- [ ] Documentation
- [ ] Investigators
- [ ] Quantitative
- [ ] Qualitative
- [ ] Model
- [ ] Sim UI

**Step 6 - Go to the top of this section and complete Executive Summary information**

Note to Workgroups:  Use the issue thread to document further discussion, alternatives development and estimates.  However, be sure to update this form if dates, team responsibility or other information changes.

**Comment by jamesmrollins** [comment]
@TomRust @lzim @staceypark @jessfroe @holbrooa @saveth 

Updated concept sketch.

![image](https://user-images.githubusercontent.com/30132017/60737069-36d81480-9f0e-11e9-90f5-564d48ba5029.png)

**Comment by lzim** [comment]
@TomRust @lzim @staceypark @jessfroe @holbrooa @saveth @branscombj @dlkibbe @dlounsbu 

Hello All,

Ann Hier and Elizabeth Bowling from EES are awaiting our review of the MTL Videos in issue #294 (bottom of the thread, list of 10 edited videos). Jessilyn is taking the lead on the review for basic issues, but she is not as oriented for what may have changed since we submitted the pop-ups a few months ago.

Stacey realized that the Learning Mode pop-up is not addressed is MTL Video.

1. We need to make sure updates/improvements made since we submitted pop-ups to EES, are caught and pop-ups provided to EES.
2. Please note that any design changes will always have an MTL Video dependency.
💥 

_NOTE: The videos have the following remaining phases_:
1. Review the 10 videos in issue #294 to make sure EES is on the right track.
2. Provide Ann with any feedback on these 10.
3. Ann will release the other 26 videos.
4. The 26 videos need to be reviewed. 
**POINT OF NO RETURN - VIDEOS ARE FINAL** 
5. Then EES sends the videos for closed captioning.
6. Then we pilot test them.

**Comment by lzim** [comment]
> @TomRust @lzim @staceypark @jessfroe @holbrooa @saveth
> 
**Thanks James, this looks good, with the following recommended edits.**
Stacey and I made these together, do they look okay to you, Tom?

1. Keep the **Learning Mode** level 1 header.
2. Remove the "i" for information. Add a level 2 header **Instructions** at the top instead.
3. Move that **Instructions** information to the top above the **New Patient Start Rate** and **Existing Patient Return-to-clinic Visit Interval** details, so that it can function more like instructions.
4. Recommend **bold font** for **Medication Management (MMParams)** and **Care Coordination (CCParams)** respectively in the body of the paragraph.
5. Recommend **bold font** for  **New Patient Start Rate** and **Existing Patient Return-to-clinic Visit Interval** respectively in the body of the paragraph.
6. Edit the body of **Existing Patient Return-to-clinic Visit Interval** to say "Choose this learning mode to prioritize the Existing Patient Return-to-clinic Visit Interval estimated from team data...
7. Edit the body of **New Patient Start Rate** to say "Choose this learning mode to prioritize the New Patient Start Rate estimated from team data...



> Updated concept sketch.
> 
> ![image](https://user-images.githubusercontent.com/30132017/60737069-36d81480-9f0e-11e9-90f5-564d48ba5029.png)

**Comment by jamesmrollins** [comment]
@TomRust @lzim @staceypark @jessfroe @holbrooa @saveth @branscombj @dlkibbe @dlounsbu

Hi Everyone,
Here is an update _(I assumed with item 5 you wanted boldface on the variable names in the paragraph under the each of radio button titles)_:

![image](https://user-images.githubusercontent.com/30132017/61163846-b42ef680-a4c5-11e9-96eb-f17caf5329e3.png)

With a thumbs up from HQ, I will release for production and update the due date.

**Comment by jamesmrollins** [comment]
@TomRust @lzim @staceypark @jessfroe @holbrooa @saveth @branscombj @dlkibbe @dlounsbu

With respect to design changes and videos, **did you pin the rose on  @jessfroe** to act as a workgroup lead and look out for dependencies, find where in the video(s) the change is necessary and coordinate with Ann for an estimate of hours and due date?  We have some major SimUI design changes coming up in #444 and #451.  I have also discovered that the "Prioritize" switch in the main MM and CC diagram has not yet been removed in PROD.  I am going to enter a bug to track this change.

**Comment by TomRust** [comment]
@lzim , @jessfroe -- How about this text for the pop-ups for CC & MM Session 5 video, first time we click Play:

_Your experience might be a bit different: We've simplified how users prioritize their data.  Now, you choose which data you believe more accurately reflect your current state (the estimate for New Patient Wait Time, or the estimate for the Return-to-Clinic Visit Interval) **before** running simulations._

**Comment by jessfroe** [comment]
@TomRust @lzim I agree we need to include some sort of pop-up to inform learners of these changes, but worry that the previously used pop-up format may not be conducive to this type of information. I wonder what the logistics would be of including a completely separate screen with this info on it? Instead of a popup? Sort of blurring out the background and drawing attention to a larger message. Am I making sense?

**Comment by branscombj** [comment]
Shorter alternative-

SimUI update: Now you prioritize which estimate better reflects your team’s current state - New Patient Wait Time or Return-to-Clinic Visit Interval - before running any simulations.

On Jul 15, 2019, at 1:36 PM, TomRust <notifications@github.com<mailto:notifications@github.com>> wrote:


@lzim<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flzim&data=02%7C01%7Cjane%40gsu.edu%7Cc465ea168c42486df0b808d7094af313%7C515ad73d8d5e4169895c9789dc742a70%7C0%7C0%7C636988089821971714&sdata=FiWX5mTGBDOOpsXSuVHhFmRNkD%2BSqHv2Ng6PF%2BM21dA%3D&reserved=0> , @jessfroe<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjessfroe&data=02%7C01%7Cjane%40gsu.edu%7Cc465ea168c42486df0b808d7094af313%7C515ad73d8d5e4169895c9789dc742a70%7C0%7C0%7C636988089821981707&sdata=UQkJCrwqVeVoBlhFbrZ2NemLHlqXEVyVCKqBwxhIJ4o%3D&reserved=0> -- How about this text for the pop-ups for CC & MM Session 5 video, first time we click Play:

Your experience might be a bit different: We've simplified how users prioritize their data. Now, you choose which data you believe more accurately reflect your current state (the estimate for New Patient Wait Time, or the estimate for the Return-to-Clinic Visit Interval) before running simulations.

**Comment by jamesmrollins** [comment]
@hirenp-waferwire  The illustration below is released for development in CC and MM Learning Mode popup.  I will send an EPS graphic in a separate email.  Thanks, James.

![image](https://user-images.githubusercontent.com/30132017/61242055-a497f380-a6f9-11e9-863b-0ca0be690474.png)

**Comment by jessfroe** [comment]
@branscombj I like your suggestion. I think using a combo of both yours and @TomRust 's ideas would work. I still wonder about the use of a simple pop-up to communicate that change, though. I will make sure to keep this edit in mind when I'm watching those videos next week.

**Comment by lzim** [comment]
@jamesmrollins good question!
Per our meeting this AM, @jessfroe is a first pass, but we will need other more familiar Team PSD folks on deck after her.

FYI: @TomRust and @staceypark

**Comment by TomRust** [comment]
@jessfroe -- I'd love to be able to put more than our usual pop-up on screen to support our video watchers through this big change.  Happy to help with more text, if we get the space.

**Comment by jessfroe** [comment]
@TomRust agreed, it seems significant enough that a thorough explanation would be useful for the learners. I'll try to think about some ways we could do that. Maybe insert a large graphic that pauses and blurs out the video in the background to draw attention to the information? Not sure the implications of doing something like that. I'll bring this to attention in issue #294. Let me know if you have any ideas.

**Comment by dlkibbe** [comment]
It would be great @jessfroe and @TomRust if the large graphic is agreed upon that the language is positive... "brand new update" or "clinician-requested update" or "new feature" or something that bespokes a positive change...

**Comment by jessfroe** [comment]
@dlkibbe I definitely agree with you. It seems like @TomRust 's initial idea would work and is overall positive, but we could change some of the verbiage to make it exciting and positive for the learners. Or create a header that includes something along the lines of "New Clinician-Requested Update". I wonder if we should have a general format or general header for updates to be utilized as we need these specific types of graphics.

**Comment by TomRust** [comment]
@dlkibbe @jessfroe -- A standard graphic and more positive/customer responsive language would be great!  But, we should show it and change the wording of the pop-ups in every instance where there is a change like this in the Sim UI ...which means basically all the videos of sessions 5-10.  It's going to be a lot of work!

**Comment by lzim** [comment]
@dlkibbe @jessfroe @staceypark

@tomrust

Agreed! We like need to draft something with a screenshot of the Learning Mode and post it for Ann to try to make it better. 

Tom, do you have any bandwidth to take the first stab and the positivity, while staying clear/correct?

>  -- A standard graphic and more positive/customer responsive language would be great! But, we should show it and change the wording of the pop-ups in every instance where there is a change like this in the Sim UI ...which means basically all the videos of sessions 5-10. It's going to be a lot of work!

**Comment by TomRust** [comment]
@dlkibbe @jessfroe @staceypark @lzim -- How about this language?

_We've made some improvements since recording this video! We've simplified how the team's data are read into the model.  Now you prioritize which estimate better reflects your team’s current state - New Patient Wait Time or Return-to-Clinic Visit Interval - **before** running any simulations._

**Comment by TomRust** [comment]
@jamesmrollins @lzim -- I think the pop-up looks good in TEST.

**Comment by staceypark** [comment]
I took a stab a trimming Tom's blurb. I think we want to keep it as short as possible so the learner's won't glaze over it and I imagine we also have limited real estate on the screen? Does this still capture everything accurately while keeping it positive?
@TomRust @dlkibbe @jessfroe @lzim 

We improved how team data is prioritized in the simulation! Prioritize "New Patient Wait Time" or "Return-to-Clinic Visit Interval" to reflect your team's current state,

> @dlkibbe @jessfroe @staceypark @lzim -- How about this language?
> 
> _We've made some improvements since recording this video! We've simplified how the team's data are read into the model. Now you prioritize which estimate better reflects your team’s current state - New Patient Wait Time or Return-to-Clinic Visit Interval - **before** running any simulations._

**Comment by staceypark** [comment]
@lzim @dlkibbe @dlounsbu @TomRust @branscombj @jessfroe 
Can we get further opinions on this so @jamesmrollins can move it to PROD?

In terms of supporting materials, there is no dependency on this except videos in terms of inconsistency. However, is this something we want to add an explanation of in the SEE/SAY guides?

**Comment by dlkibbe** [comment]
@staceypark one concern about the statement "We improved how team data is prioritized in the simulation! Prioritize "New Patient Wait Time" or "Return-to-Clinic Visit Interval" to reflect your team's current state." Will the learner know what the phrase "how team data is prioritized in the simulation" or "reflect your team's current state" even means? Agreed, there is limited space on the screen, but I think some variation on Tom's language may be easier to understand. e.g.,

**MTL Model Improvement**: how the team's data is read into the model has been simplified. You are asked to prioritize which estimate better reflects your team’s current state - New Patient Wait Time or Return-to-Clinic Visit Interval - **before** running any simulations.

**Comment by dlkibbe** [comment]
@staceypark I like @branscombj suggestion from earlier better than the one I posted above:
MTL SimUI update: Now you prioritize which estimate better reflects your team’s current state - New Patient Wait Time or Return-to-Clinic Visit Interval - before running any simulations.

**Comment by jessfroe** [comment]
@staceypark I think the pop-up itself looks great in the Sim, so now we just need to figure out how to address this pop up in the MM/CC vids when the learners are first entering the SimUI. 
@TomRust I wanted to double check the need for a graphic with you - you mentioned addressing this in all S05 - S10 videos, but wouldn't it only be in videos for S05 MM/CC? After the learner chooses the mode, it does not prompt you again. And it is not applicable for the other modules. Please correct me if I'm wrong!

@dlkibbe that's a great point, the learners may not quite understand the question that is being asked of them. Regarding limited real estate, we might have more room than we think. Especially because this is significant enough that we should use as much space as possible. I am partial to the way Tom phrased it.

Are we thinking that we would put a copy of the graphic itself into the video pop-up? Or just an explanation when it would be occurring?

**Comment by staceypark** [comment]
@jessfroe Maybe I misunderstood? I thought the pop-up language we're editing right now is for the one in the video not the sim?

**Comment by jessfroe** [comment]
@staceypark correct, but you mentioned James wanting to move something to PROD, so I assumed you meant he wanted to move the SimUI pop-up to PROD?

**Comment by lzim** [comment]
@holbrooa Just double checking on the recent updates to the Data UI buttons, and wondering if we should we refer them to the Data User Interface or the "Team Data Table for Sim UI" My instinct is that if we point them to the Data UI before we get the Team Data Table, then we risk having them check an MMParams tab that will be wrong/not updated.
- When you produce the Team Data Table for the Sim UI, does it always both produce the file and update the Params tabs in the Data UI?

@staceypark @dlkibbe @branscombj @dlounsbu @TomRust Note that we should probably update the SEE/SAY guide to encourage the learners to save their Data UI file back to mtl.how/data at the end of session 3.

@jamesmrollins 
> "Refer to the Data User Interface, Medication Management tab (MMParams) of the Team Data spreadsheet, for data regarding the team's New Patient Start Rates and Return to Clinic Visit Intervals."

Looks like we have a typo for Existing Patient Return-to-Clinic Visit Interval -
It should read: "...and only start new patients in..."
![mm_learning_mode](https://user-images.githubusercontent.com/7454688/62845654-a9ab7c80-bc7e-11e9-856a-6e6c3737337d.png)

FYI: @jessfroe

**Comment by lzim** [comment]
@jessfroe for videos. When you get back from camping! ⛺️ 

This strikes me as pretty good with one mod replacing "estimate" with "team data"
 "Now you prioritize which team data better reflects your team’s current state - New Patient Wait Time or Return-to-Clinic Visit Interval - before running any simulations."

I think any pop-up images likely will want to address this Learning Mode pop-up, but also - possibly - the part about where they get the data in the Data UI or Sim UI (TBD, see my question to Andrew above).

**Comment by dlkibbe** [comment]
@staceypark @lzim  @branscombj @dlounsbu @TomRust I've added updating the SEE/SAY guide "to encourage the learners to save their Data UI file back to mtl.how/data at the end of session 3" to my list of edits.

**Comment by jamesmrollins** [comment]
@hirenp-waferwire please make the modifications shown below.

![image](https://user-images.githubusercontent.com/30132017/62892327-e027dc80-bcfc-11e9-9f8a-62679dbb95de.png)

**Comment by lzim** [comment]
@jamesmrollins 

In addition to these typos sent to @@hirenp-waferwire yesterday, per yesterday's _Workgroup Leads_ meeting, we realized that due to new features in the Data UI, we should NOT be sending the learners to the Data UI, rather we should be sending them to the "**Team Data Table for Sim UI**"

So, it would be worded like this (with the bolded format):

Refer to the **Medication Management (MM)** tab of the **Team Data Table for Sim UI** at **mtl.how/data**, for data regarding the team's **New Patient Start Rates** and **Return-to-Clinic Visit Intervals**.

FYI: @staceypark @jessfroe

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire, please see instructions below.  Modify CC Learning Mode pop-up similarly, substituting "Medication Management (MM)" with "Care Coordination (CC)"  Thank you, James


![image](https://user-images.githubusercontent.com/30132017/62965449-f182ee80-bdb9-11e9-8e28-538a8888afd5.png)
