### ISSUE TITLE
EBP Reach SQL Query

### ISSUE THREAD

**Issue by saveth** [lzim/teampsd#421]
**BEFORE FILLING OUT THIS TEMPLATE, PLEASE ASSIGN THIS ISSUE TO THE BUG KANBAN UNDER PROJECTS (YES, EVEN IF IT IS A FEATURE. ALL ISSUES START IN THE BUG KANBAN FOR TRIAGE). --------------------->**

**Describe the opportunity**
 A new EBP Reach SQL data pull where we have 2 types of denominators/numerators to consider for study.

**READ THIS FIRST**
- _A bug is a developed feature that has been working, that is no longer working._
- _A feature is a function, product or characteristic that requires research, design and development._

**If This Is a Bug, start with number 1 below, if a Feature, skip to number 7.**

**FEATURE**

**7. How would you like this feature to work?**
Describe your expectations in terms of outcomes/products/behaviors.

The new data pull should include updated EBP numerators and denominators that matches:
- Denominator:
- [ ] include all unique patients who have any diagnosis and dis-aggregated by diagnosis
- [ ] include all EBPharm patients who are able to get prescription without a visit

Numerator:
- [] include all unique patients (from original denominator) who received any EBP treatment, by treatment category
-[] the two types of EBP treatment: initiation vs. dose/course 

**8. How urgent is this request? (Urgent/Not Urgent)**
Urgent

**9. Why is this feature important to you?**
Required to generate Baseline EBP  needed to determine balancing of arms for clinic selections.

**10. Is your feature request related to a problem? Please describe.**

**11. Is there a deadline or other scheduled constraint driving your request?"**
This is necessary to calculate  the balancing of arms in clinic selection.

**12. Additional context**

**STOP HERE. INFORMATION BELOW IS TO BE FILLED OUT BY WORKGROUPS AS PART OF TRIAGE AND WORK BREAKDOWN PROCESS**

**Estimated person hours to complete:**

**Key people (use @ assignment for people whose input will be necessary):**
@saveth @holbrooa @lzim 

**Key dependencies:**
Are there other tasks that need to be completed first?

**Constraints:**
Is there a resource constraint that may affect the development of the feature?

**Gantt chart needed? Attach link and/or screenshot.**

**Comment by holbrooa** [comment]
Should have mismatches with reasons and possible solutions by COB Monday. There are 19 locations with missing CDW baseline info (but they're on Jodie's list) and there are 68 locations where there is EBPharm information but no EBPsy information (this is probably correct, but we should spot-check some to make sure).

Spreadsheets with missing sta6a are in Analyses\R01_mtl\Sampling\ModData

**Comment by holbrooa** [comment]
At the first site selection meeting, we'll need to determine exactly which datapoints are necessary, because there is still some confusion. In meetings, LZ has indicated that we don't need full numerator data, i.e. course/dose, for site selection. So we need to double-check that this dataset, once the mismatches above are addressed, is sufficient. Course/dose data requires much more complicated queries, of course, so we'll have to work backwards gantt-style on the deadline for that analysis. However, the grant seems to indicate that we do need the course/dose data for site selection. So quant will have questions about that, once the mismatches are figured out (should be done before this first site selection meeting). Time permitting, quant will pull different versions of the data and/or estimate the work hours required for different versions to discuss in the meeting.

@lzim @saveth @staceypark

**Comment by saveth** [comment]
@lzim Based on the Site Selection meeting, we discussed EBP measures that would exclude AUD from the R01 and IIR. However, AUD is listed in both the R21 and R01, but not in the IIR. Should @holbrooa pull both sets of denominators for the Site Selection calculation? And should we calculate the sampling differently for both the IIR and R01 or proceed as we have done (treat them the same)?

**Comment by saveth** [comment]
@holbrooa For patients who had been flagged with ICD depression code that are considered as both EBPsy and EBPharm, did you count them under both columns in the excel file?

![image](https://user-images.githubusercontent.com/12439059/61663415-6b293000-ac85-11e9-88ec-e38fe4765a89.png)

The numbers for depressionPSY column looks the same from previous files where you said it only included those with exclusive ICD PSY depression. The numbers in the depressionPharm column are higher, and you said that's because we're pulling from filled table instead of prescribe table.

**Comment by holbrooa** [comment]
Yes, they're counted under both if their icd code is listed as both. And the all is really "either." so I think we have everything we need.

**Comment by staceypark** [comment]
@saveth @holbrooa can this be closed? it's been in functional testing for quite some time.
and if not, when do we expect this to be done?

**Comment by lzim** [comment]
> @saveth @holbrooa can this be closed? it's been in functional testing for quite some time.
and if not, when do we expect this to be done?

@staceypark this has dependency with **meta_disseminate_scientists_va**

**Comment by holbrooa** [comment]
Yeah, let's close it. @lzim @saveth @staceypark  

Same for https://github.com/lzim/teampsd/issues/423
