### ISSUE TITLE
mm tt report running into error

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#422]
**Describe the opportunity**
Running into error running tt2 for team

files:
[agg_bc.xlsx](https://github.com/lzim/teampsd/files/3298212/agg_bc.xlsx)
[agg_exp1.xlsx](https://github.com/lzim/teampsd/files/3298213/agg_exp1.xlsx)
[ModelParameters.xlsx](https://github.com/lzim/teampsd/files/3298215/ModelParameters.xlsx)

**3. Please provide a(n) screenshot(s) of the bug.**
![image](https://user-images.githubusercontent.com/31089501/59625092-49b8af80-90ed-11e9-9372-95c363f259ff.png)

**Comment by saveth** [comment]
Can you provide more details? Is it's an issue of cell placement in the export file? Or how the r script transform the file?

**Comment by staceypark** [comment]
Issue with cell placement in what the export is giving me vs. what your code is calling for.
@jamesmrollins sounds like the export cell placements are changing again. We should update the code once the export cells are frozen.

**Comment by staceypark** [comment]
@saveth in line with the issue of changing names and exports, if the variable names are changing then keep in mind the chart title about the variable name also needs to be changing. This is easy to lookover since it doesn't break the code, but just wanted to keep it on your radar.

**Comment by saveth** [comment]
Closing this issue since it's more clearly outlined in another issue #427
