### ISSUE TITLE
Baseline EBP Calculation

### ISSUE THREAD

**Issue by saveth** [lzim/teampsd#423]
**BEFORE FILLING OUT THIS TEMPLATE, PLEASE ASSIGN THIS ISSUE TO THE BUG KANBAN UNDER PROJECTS (YES, EVEN IF IT IS A FEATURE. ALL ISSUES START IN THE BUG KANBAN FOR TRIAGE). --------------------->**

**Describe the opportunity**
Calculating Baseline EBP is necessary for the balancing of arms in  the randomization of sites.

**FEATURE**

**7. How would you like this feature to work?**
Describe your expectations in terms of outcomes/products/behaviors.

**8. How urgent is this request? (Urgent/Not Urgent)**
Urgent

**9. Why is this feature important to you?**
Required to calculate the balancing of arms during randomization/selection of clinics in orderto launch the studies. 

**10. Is your feature request related to a problem? Please describe.**

**11. Is there a deadline or other scheduled constraint driving your request?"**
R01/IIR launch in October 2019

**12. Additional context**

**STOP HERE. INFORMATION BELOW IS TO BE FILLED OUT BY WORKGROUPS AS PART OF TRIAGE AND WORK BREAKDOWN PROCESS**

**Estimated person hours to complete:**

**Key people (use @ assignment for people whose input will be necessary):**
@saveth @lzim @holbrooa 

**Key dependencies:**
Are there other tasks that need to be completed first?
#421 

**Constraints:**
Is there a resource constraint that may affect the development of the feature?

**Gantt chart needed? Attach link and/or screenshot.**

**Comment by staceypark** [comment]
@saveth @holbrooa can this be closed? it's been in functional testing for quite some time.
and if not, when do we expect this to be done?

**Comment by holbrooa** [comment]
Yeah, let's close it. @lzim @saveth @staceypark

Same for https://github.com/lzim/teampsd/issues/421
