### ISSUE TITLE
tt report page break formatting

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#426]
**Describe the opportunity**
Add pagebreak code: <P style="page-break-before: always">
throughout tt report codes for all modules in places where it makes sense so that tables are not split when knitting.

@saveth just fyi I need to push this edit at some point. And once I do, please don't remove. thanks.

**Comment by staceypark** [comment]
Other formatting items to add:
1) header 1 for team vision
2) code snippet for adding the tt png; include in file instructions to download tt png
3) header 1 for tt report number

**Comment by saveth** [comment]
The report is in html format, so there's no page break (one long document). You can have pagebreak if it's render in a different format.

**Comment by staceypark** [comment]
@saveth That's only partially true. Yes HTML has no page break but it's being given to the teams as a PDF (converted from the HTML view, not knitted as a PDF - this creates slightly different end results) so I do in fact need a page break. 

Anyways, I'm not asking you to add any of these things. I just need to be alerted when you're done with updating the code so I can add the part I need.

**Comment by saveth** [comment]
@staceypark Please see issue #361 regarding pull request #432, which will trigger this issue. Thanks. :)

**Comment by staceypark** [comment]
@saveth can you address #4 in my previous comment about the ggtitle? I don't want to change it if there's a reason we use header level for instead of ggtitle.

**Comment by saveth** [comment]
@staceypark I believe the header level was used to help differentiate all the different graphs while coding and it was aesthetically cleaner looking than the ggtitle. The ggtitle can be used if it's more practical.
