### ISSUE TITLE
Sim Agg Output changed

### ISSUE THREAD

**Issue by saveth** [lzim/teampsd#427]
**BEFORE FILLING OUT THIS TEMPLATE, PLEASE ASSIGN THIS ISSUE TO THE BUG KANBAN UNDER PROJECTS (YES, EVEN IF IT IS A FEATURE. ALL ISSUES START IN THE BUG KANBAN FOR TRIAGE). --------------------->**

**Describe the opportunity**
A clear and concise description of the opportunity for improvement.
Sim agg export file should be consistent so that R code for tt report can be consist over time and does not require to change.

**READ THIS FIRST**
- _A bug is a developed feature that has been working, that is no longer working._
- _A feature is a function, product or characteristic that requires research, design and development._

**If This Is a Bug, start with number 1 below, if a Feature, skip to number 7.**

**1. Please describe the steps to reproduce the behavior.**

Go to Sim> Login > Experiment Maintenance > export

**2. Please describe the expected behavior.**
Please see the attached image. The excel file on the left is the original, which the R code is based on. This export was pulled from the Outputs and Text export function.  The right is the file the team pulled on 6/14/2019, was pulled from the Home page Experiments Maintenance tile.  It is missing a variable (Effect of Provider Fatigue on Patient's Engagement Time) and is missing a blank line 3.  There are R coded reports dependent on the specific file structure from the Outputs and Text export.  They should both export the same. 

<img width="1437" alt="Screen Shot 2019-06-17 at 4 26 41 PM" src="https://user-images.githubusercontent.com/12439059/59643552-f90d7a80-911d-11e9-9fda-d0b2f08d8b3e.png">

Furthermore, it's missing a blank line on line 3.
<img width="1184" alt="Screen Shot 2019-06-17 at 4 27 15 PM" src="https://user-images.githubusercontent.com/12439059/59643577-0c204a80-911e-11e9-8a88-ae35107b9b0d.png">

**4. Please identify your operating system and browser version.**
 a. Operating System: [e.g. iOS]
 b. Browser [e.g. chrome, safari]
 c. Version [e.g. 22][You can find version by clicking on "help" then "about Chrome/edge/firefox" to get version information.]

File was pulled using Chrome on a Mac.

**5. If you are using a smartphone, please complete the following information, otherwise skip to number 6.**

**6. Additional context**
 - Which function, model or team data where you trying to use?
 - Provide any other relevant information that may affect this issue.

**STOP HERE. INFORMATION BELOW IS TO BE FILLED OUT BY WORKGROUPS AS PART OF TRIAGE AND WORK BREAKDOWN PROCESS**

**Estimated person hours to complete:**

**Key people (use @ assignment for people whose input will be necessary):**
@staceypark @jamesmrollins @saveth 

**Key dependencies:**
Are there other tasks that need to be completed first?

**Constraints:**
Is there a resource constraint that may affect the development of the feature?

**Gantt chart needed? Attach link and/or screenshot.**

**Comment by jamesmrollins** [comment]
@saveth @staceypark  the exports should both be good now.  Will you check to ensure you can run your tt reports?  If you are satisfied, please close this issue.

**Comment by saveth** [comment]
@jamesmrollins I tested both export for agg. While its great that they added an extra line at the top, the model variables exported from the Home page is completely different from what is exported from the Output and Text window. @staceypark says it should be exactly the same file as long as a experiment was saved.

![image](https://user-images.githubusercontent.com/12439059/60551102-0a8a8100-9cdf-11e9-9fc7-2f2c47910895.png)

**Comment by jamesmrollins** [comment]
@saveth @hirenp-waferwire. Yes, @staceypark is correct, they should all be same, as long as you saved the experiment **AND** did not reset the simulation. I ran a test exporting a file from each export function available from the simulation.  The operating steps are as follows.

1. Loaded Agg model in Test.
2.  Used Model_parameters_test3.xlsx
3.  Ran simulation to end.
4. Save simulation run at Bal_bc_2_date
5. Exported from Outputs and Text saved as Test Export 1 - Outputs and Text
6. Exported from Expanded Outputs saved as Test Export 1 - Expanded Outputs
7. Returned to home screen
8. Exported from Experiments Maintenance panel Test Export 1 - Home
9. Loaded files side-by-side.

They appear to be the same.

![image](https://user-images.githubusercontent.com/30132017/60562969-98319500-9d0e-11e9-9d89-b3b601462222.png)

@saveth Try following the steps I outline above and see if you have better results.  Feel free to call me tomorrow, I will be around.

**Comment by saveth** [comment]
@jamesmrollins I just repeated your process for test and sim. I am getting the same output files from both the Home page Experiment Panel Export and Output and Text. I've also updated the tt report for agg (on Github) to reflect the added line in the export file. So we're good to go. Thanks for the support on this issue. 😄
