### ISSUE TITLE
added new user in sim but cannot login

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#431]
**1. Please describe the steps to reproduce the behavior.**
a. Go to mtl.how/facilitate
b. Added Jessilyn Froelich (jfroelich@pavir.org) to the qual_workgroup_team Group where everyone is assigned to World001 as a Team Lead
c. Assigned username as jfroelich@pavir.org and same password as everyone else
d. No error message pops up but when we try to login after we click the "Login" button it is "processing" in the sense that we can't click the "Login" anymore but it doesn't open up the sim. 
e. I know it's not an error with the sim in general because my login works just fine.

No screenshot to really attach because it's just the login screen.

**Comment by jamesmrollins** [comment]
@staceypark the whole team needs to be mapped in world-team mapping, otherwise the sim doesn't know which world to present in the drop down in the next step.  I just tested it and it works fine.

**Comment by staceypark** [comment]
@jamesmrollins Ah shoot. I didn't think to check the world team mapping because the rest of the group has existed for awhile and should be mapped.
I think we lost some mapping between previous TEST to PROD moves. Looks like I need to make sure all of our existing groups are still mapped in the worlds mapping xlsx.

Going to close this issue and create a new card for myself as a to-do item for that.
Thanks!
