### ISSUE TITLE
1/8 r21 pilot team followup

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#433]
1. archive all experiments from worlds/groups that will be deleted in teampsd folder
2. delete groups no longer needed
3. make sure all teams that are active are still mapped in the world mapping xlsx as some got lost in the TEST to PROD shift

**Comment by staceypark** [comment]
r21 pilot worlds have all been organized and experiments re-run and saved.
however, teams may not be able to pull up prior experiments & their data files will not run that the experiments were based on due to all of the model changes.

This needs to be revisited closer to launch when we will be frozen for national rollout.

**Comment by lzim** [comment]
@staceypark, I don’t know what you mean?

We need tt1-3 of what we did in the R21 a year ago (as complete as we have it).

and

We need working data files and worlds now in case they start to use it again when we meet with them.

As the **r21_nce milestone** indicates we need to f/u with these teams in Sept (this month) as it will be their 12-month f/u.

**Comment by staceypark** [comment]
at our f/u with the r21 teams we will give them:
1. Complete tt1-3 for each team
2. team and individual worlds
3. fresh data pull that will work with the updated models

**Comment by staceypark** [comment]
final meetings with remaining r21 teams on 1/8
