### ISSUE TITLE
Create demo course code "scra2019"

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#436]
@jamesmrollins 

Will you please create a course code for https://mtl.how/demo called "scra2019."

And/or will you remind me whether I can/should be able to do this myself?

Thanks!

FYI: @staceypark and @dlounsbu

**Comment by jamesmrollins** [comment]
Hi @lzim.  I have updated mtl.how/demo to include the course code "scra2019."  You can update this yourself by:

1. Sign into Epicenter
2. Navigate to the VA MTL DEMO - PROD/Interface/Dynamic Data folder
3. Select CourseCode.xlsx in the root directory
4. Click on View Raw
5. When file downloads, open with Excel and edit with course code. Save your file and close. 
6. Go back to Epicenter and navigate back to Dynamic Data folder
7. Select "Upload" and choose the file you just edited from your Downloads folder.
8. Epicenter should give you a warning "Do you want to replace existing file?"  Click on yes and file should upload.

Done . . .

**Comment by lzim** [comment]
Thanks @jamesrollins

@staceypark

Will you add these instructions to the OSF wiki for:
- SDS
- SIRC
- AHSR
- ISTSS

**Comment by staceypark** [comment]
@lzim instructions added, closing the issue.
