### ISSUE TITLE
Implement new SP structure from F2F

### ISSUE THREAD

**Issue by holbrooa** [lzim/teampsd#440]
**ASSIGN to PROJECT "issue_tracker"**  

**Describe the opportunity**
As described at the face to face, the data UI should generate 0s when only a certain parameter set is run, and the drop down has been changed, and the button on SP needs to be changed. Also, various UI features and upgrades.

**READ THIS FIRST**
- _A bug is a developed feature that has been working, that is no longer working._
- _A feature is a function, product or characteristic that requires research, design and development._

**If This Is a Bug, start with number 1 below, if a Feature, skip to number 7.**

**1. Please describe the steps to reproduce the behavior.**
a. Go to '...'
b. Click on '....'
c. Scroll down to '....'
d. See error

**2. Please describe the expected behavior.**

**3. Please provide a(n) screenshot(s) of the bug.**
If applicable, add screenshots to help explain your problem. You can use the Snip tool available in Microsoft Windows 10.

**4. Please identify your operating system and browser version.**
 a. Operating System: [e.g. iOS]
 b. Browser [e.g. chrome, safari]
 c. Version [e.g. 22][You can find version by clicking on "help" then "about Chrome/edge/firefox" to get version information.]

**5. If you are using a smartphone, please complete the following information, otherwise skip to number 6.**

**6. Additional context**
 - Which function, model or team data where you trying to use?
 - Provide any other relevant information that may affect this issue.

**FEATURE**

**7. How would you like this feature to work?**
See notes from F2F

**8. How urgent is this request? (Urgent/Not Urgent)**

**9. Why is this feature important to you?**

**10. Is your feature request related to a problem? Please describe.**

**11. Is there a deadline or other scheduled constraint driving your request?"**

**12. Additional context**

**STOP HERE. INFORMATION BELOW IS TO BE FILLED OUT BY WORKGROUPS AS PART OF TRIAGE AND WORK BREAKDOWN PROCESS**

**Estimated person hours to complete:**
20
**Key people (use @ assignment for people whose input will be necessary):**
@holbrooa 
**Key dependencies:**
Are there other tasks that need to be completed first?

**Constraints:**
Is there a resource constraint that may affect the development of the feature?

**Gantt chart needed? Attach link and/or screenshot.**

**Comment by lzim** [comment]
@holbrooa @staceypark @jessfroe 

Thanks Andrew!  As a reminder we need this done before you leave on 7/3 (if you're taking 7/5 off).

We'll be training the TAS in the Data UI on Monday morning 7/8 😄

**Comment by holbrooa** [comment]
This card is in functional testing right now, but I know you want to use it, so here's the current state:

Ok, the data UI version in final datafiles has almost all of this functionality working for you to use with the TAS. You'll notice a new button for getting the previous clinic list from https://github.com/lzim/teampsd/issues/419 and the correct drop down options that we worked on at the F2F. The only thing that failed in testing was the 0s for all the models you don't select. So I'm continuing to work on that, and for now, the version in final datafiles just outputs all the tabs as it used to.

**Comment by staceypark** [comment]
@lzim @TomRust @jessfroe @branscombj @dlkibbe @dlounsbu 
@holbrooa Will the fix for "0s for all the models you don't select" be ready by Wednesday? We needed this done by Mon 7/8 as @lzim mentioned above to train the TAS.

Our next meeting with the TAS is 7/10 and we need this done by then as a high priority issue.

**Comment by holbrooa** [comment]
Yeah, it'll be done by then. I think the fix I implemented today works, but it takes some time to test, so I won't know for sure until tomorrow.

**Comment by staceypark** [comment]
@holbrooa 
We need to know on the hour when this gets done as we need to update the below before we meet with the TAS @9:30am Pacific Wednesday morning: 

1. SAY documentation - Will you be able to create SAY level documentation for the related SP changes?
2. SEE documentation
3. data UI gifs
4. data UI cheatsheet

**Comment by holbrooa** [comment]
@staceypark @lzim 
Okay, but please bear in mind that these are front-end design changes being implemented; it's not just under the hood. So before we go off and update all the documentation and everything, I would really appreciate it if we could have a chance to look at it together and you can tell me if it looks and works the way that you want, so we don't have to redo these things.  Do you have any time tomorrow morning maybe?

**Comment by holbrooa** [comment]
@lzim @staceypark 
The functional changes are now done. The 0s are working correctly. I've put two different versions of the data UI in the final datafiles folder, because I want to show you what I've tried in response to some of our conversations about usability. It shouldn't take very long to look at that, so you can decide which version is better before we update guides and stuff.

**Comment by holbrooa** [comment]
Whoa. Apparently the shared drive is full. It wouldn't let me copy my 5 MB data UI over. When we meet, I'll show you the UI changes on the one on my drive then, and hopefully the space issue will be resolved by then.

**Comment by saveth** [comment]
@holbrooa The system is being funny today. It gave me issues for a 7 MB file earlier too, but after a few minutes it copied it over.  Try again.

**Comment by lzim** [comment]
@holbrooa @saveth @staceypark @jessfroe @branscombj @dlounsbu @TomRust @dlkibbe 

Hello Everyone,
Jessilyn and I are working on the 11 items below for tomorrow's meetings. These are the items we identified during yesterday's #manuscriptmonday meeting related to the Data UI, which wasn't available for us to discuss during our three-hour meeting yesterday as the facilitate_workgroup expected. Unfortunately, we just wrapped my back-to-back morning meetings and Stacey is unexpectedly out today. 

Andrew, the NCPTSD Shared Drive space issues should be resolved. We are working to understand the differences between "DataToolFRE8UIChanges.xlsx" and "DataToolFRE6.xlsx" Do you have documentation for orienting us?
_quoting @holbrooa_:
> Okay, but please bear in mind that these are front-end design changes being implemented; it's not just under the hood. So before we go off and update all the documentation and everything, I would really appreciate it if we could have a chance to look at it together and you can tell me if it looks and works the way that you want, so we don't have to redo these things. Do you have any time tomorrow morning maybe?

- Andrew, unfortunately, as you can see, we don't have any unscheduled slots on Tuesday mornings, which is why we needed the SP updates to the Data UI on 7/3 per the request in the thread, so that these things could be reviewed yesterday 7/8/2019. 

**_Updating the SAY file_**
- [ ] 1. include SP details (Stacey review the guides and look for where updates are needed; Andrew double-check; COB Tues 7/9/2019
- [ ] 2. update the format consistent with F2F learning to be more like a checklist for team tailoring consistent with the MTL theory of change (Lindsey will work on and run it by Tom; COB Monday 7/8/2019)
- [ ] 3. Updating the SEE files to include the SPTransfers tab instructions
- [ ] Script details, .gifs; Stacey & Jessilyn; COB Tues 7/9/2019
- [ ] 3. PSY F2F PCT data - DECISION
- [ ] 4. Facilitator SP team data - test and prep - Lindsey will test and set up; with Tom and Andrew as needed
- [ ] 5. Give all Co-Facilitators Operations access - (Lindsey)
- [ ] 6. Go over the F2F fidelity and intersession checklist edits - (Lindsey)
- [ ] 7. F2F Facilitators need to complete evaluation - (Tom)
- [ ] 8. Team session 1 details on GitHub - PSY available; double-check for SP
**_Orient TAS to the revised training schedule and fidelity checklists_**
- [ ] Group Supervision on Monday - Update today
- [ ] Update on checklists
**_F2F and timeline_**
- [ ] 10. Set up the Lucid agenda and phone lines for the summer training schedule
- [ ] 11. Orient outside of the meeting

We will be updating folks as we have them in real-time per folks requests yesterday.

Thanks, for your patience everyone. HQ has done some brainstorming about what aspects of the revised Team PSD workflow contributed to us not having the Data UI for yesterday's 7/8/2019 #manuscriptmondays meeting for session 2, as we planned.

**Comment by holbrooa** [comment]
If you're working to understand the difference between the two files right now, can you just call me? The difference is a few different feature implementations based on what we've talked about. I can show you what they are, and you can tell me if it's good or not for each one, and then I can collapse back down to one final version to document and proceed with.

**Comment by lzim** [comment]
@holbrooa 😅 Awesome, yes.

> If you're working to understand the difference between the two files right now, can you just call me? The difference is a few different feature implementations based on what we've talked about. I can show you what they are, and you can tell me if it's good or not for each one, and then I can collapse back down to one final version to document and proceed with.

Yes, calling your cell now.

**Comment by lzim** [comment]
**New Features**
1. Get previous clinic list
Edit: Get   previous clinic list from last click of Get Patient-level Data
--
Edit: Get   previous clinic list from Create Team Data Table for Sim UI file named   \640_CConlyWCCtest_2019_07_08

2. Add Selection, not just "Add All" (Andrew will fix the retained selection issue when your prior selections are not displayed and you switch back to using filter-based clinic selection).

3. For "Module Selection" choosing "All with SP" from the drop-down is the longest query with no values zeroed out. However, the other selections with return zeros for any parameter set not selected by the learner. For example, the narrower query selection "All without SP" will still produce the SP tab, but it will have all zero values to show that the values were not included in the selection/query. The file you generate will have all five module tabs and labels, but will produce zeros if those parameters were not selected.

4. If you get fuzzy clinics in column A, then click on another tab and click back.

5. If you select "SP" (only) or "All with SP" then the SP module pop-ups will appear.
- click the "Get..." button for Sim parameters 
- EDIT pop-up text to say "module" and "...you must select clinics that your team refers to/from." "The SPReferrals tab allows to to select the clinics that your team steps patients up to (if your team is a GMH team) or steps patients down to (if your team is an SMH team)..."
- In SPReferrals tab edit: "The clinics selected below that my team refers to are:" (Andrew will reverse the logic of this in the query)
- Edit buttons to add "Cancel" which will keep the learner at the "ClinicSelection" tab, but selecting "OK" will take them to the SPReferrals tab.
- ADD to SP pop-up: "Once you have selected clinics in the "SPReferrals" tab return to the "ClinicSelection" tab and click "Create Team Data Table for Sim UI." 
- We added this language in SPReferrals A2 instructions: Use this tab to select clinics that your team refers to for the suicide prevention module. The data pull will track patients stepped up/down between your team's clinics and the ones you select below. Once you have selected referral clinics below, return to the "ClinicSelection" tab and select from the Module drop-down either "All with SP" or "SP," then click "Create Team Data Table for Sim UI." 

6. EDIT: SP Gap Threshold dialogue: "In general for the PC/PCMHI setting, how long of a gap in patient care is required for the subsequent visit to be considered a new care episode? Set the threshold below in weeks. The default threshold is 39 weeks (9 months)." (same edit for GMH and SM); Andrew will make the cancel button just cancel and close the dialogue.

7. Remaining issue: Finalize the decision about how to capture MH encounters/visits (by CPT code?) that occur in Primary Care; Right now we are using PCMHI 500-series (527, 534, 539), but is this too narrow? If so, how should this be operationalized? Lindsey will re-ping OMHSP partners about this.

_**DECISIONS MADE**
- We will adjust the schedule to do session 2 this week (PSY) and next week (SP)
- We will focus on the revised training schedule and fidelity checklists tomorrow.
- We will do intersessions prep for PSY and demo PSY on Friday
- We will ask the OMHSP TAS questions about the SP features tomorrow
- We will produce the documentation for SP for #manuscriptmonday on 7/15.

_**Triage for TAS training tomorrow Wed**_
- Team vision discussion that we will use for PSY and SP is here: https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/checklists/f2f_session1_debrief.md
- For SP it is Team #4 (at the link above) a GMH team struggling to refer to SMH...(specifically BHIP Blue/Green referring to PCT).

**Comment by holbrooa** [comment]
1. Get previous clinic buttons. Both? Neither? Layout? **Both and Lindsey changed the labels.**
2. Add all vs add selection dynamic whiz-bang button reuse. **Keep, but we need to handle case where user makes a selection and then changes the filter**
3. Edit SP transfers popup to be ok-cancel, where ok takes them to sptransfers
4. Button on SPTransfers? No. Let's add the instructions to the pop-up for blank SPTransfer clinics and to A2 on SPTransfers.
5. Also, rename SPTransfer tab to SPReferrals. :|
6. I'm not taking notes on Lindsey's wording, because she is. I'll refer to her notes for popups, and she's changing language in the spreadsheet directly in version 8 on the shared drive.
8. Care episode gap threshold language: Lindsey notes.
9. SP drop down of SMH/GMH needs to be reversed to be consistent with the new label.

**Comment by holbrooa** [comment]
Oh, one more thing @lzim 
Is there a configuration you want me to run tomorrow morning? Like, after the changes above are made, should I go ahead and run the queries for some clinics of your choosing?

**Comment by holbrooa** [comment]
@lzim 
I'm experiencing a terrible error this morning in which I can't open any macro-enabled workbook without destroying all the code therein. It seems to have been introduced by an OS update last night, I think. This is quite scary, as it makes all my code seem corrupted and potentially unrecoverable. But the fact that I get this error with **any** macro-enabled workbook means the problem is not with the workbooks themselves, so hopefully they haven't somehow all become corrupted. @saveth when you get in, please get in touch. I'd like to have you open the files and see if you can get to the code.

Obviously I'm not able to work on the above changes while this is happening. I'm trying to get more information about what's going on.

**Comment by holbrooa** [comment]
Seems similar to: https://social.technet.microsoft.com/Forums/ie/en-US/74ba5cad-8e46-4dd0-97ea-e6738bb23cd1/we-found-a-problem-with-some-content-in-workbooknamexlsm-do-you-want-us-to-try-to-recover-as?forum=excel

I'm going to go in to the VA and see if I can get anything done there.

**Comment by TomRust** [comment]
@lzim @branscombj @dlkibbe @dlounsbu @staceypark -- With these hiccups, what are we going to do to day with the TAS?  Prep for Session 2 PSY only?

**Comment by branscombj** [comment]
> @lzim @branscombj @dlkibbe @dlounsbu @staceypark -- With these hiccups, what are we going to do today with the TAS? Prep for Session 2 PSY only?

Yes. See the bottom of @lzim message above headed "new features" - Decisions Made and Triage - for changes to plan.

**Comment by TomRust** [comment]
@branscombj -- Thanks, Jane!  I didn't see it there.

**Comment by holbrooa** [comment]
@lzim

On a physical machine at the va, I can work on the files. So I have very quickly and hopefully without any typos made all the above changes except squashing the bug where the user has a selection but filters it away. It's version 9 in the folder.

**Comment by jessfroe** [comment]
@lzim @branscombj @TomRust @dlkibbe @dlounsbu @staceypark 
looking at our to-do list, one item we haven't made a decision about is who will orient the TAS to the new training schedule, as well as go over the revised fidelity checklists. Should we decide on that before the meeting starts?

**Comment by holbrooa** [comment]
Ok. Bug squashed. Everything from the above list is now implemented. I will be testing and looking for typos today, but you can use version 9 in final datafiles if you want.

**Comment by holbrooa** [comment]
Reviewing new data UI version in a meeting Friday 7/12 at 9:30 pacific and at manuscript Monday meeting on 7/15. Andrew will join Friday meeting at 10:30.

**Comment by staceypark** [comment]
cross-ref linked on all related documentation issues (session 2 & 3 detail, describe, document, & depend)
