### ISSUE TITLE
9/3 AGG Model Section Reveal Complexity - 'fix open loop'

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#444]
**ORIGINATOR**
*Please follow the steps below to open an issue for the MTL Workgroups to address. Be sure to provide a descriptive title for the issue when saving.*

**Step 1** - Please assign this issue to the issue_tracker, under the “Projects” menu on the right side of your GitHub page.

**Step 2** - Please answer the questions below by placing a lowercase "x" between the applicable brackets below and providing brief narratives where appropriate:

1. Is this issue a problem, such as a malfunction in the simulation, an error in documentation or similar concern, or is this a new idea
   we should consider?
   
   - [x] Problem *(continue to number 2 below)*
   - [ ] New idea *(continue to number 7 below)*

2. What team are you on (exg., Menlo Park, Team Blue)?
Facilitator Work Group

3. How urgent is this problem?

   - [ ] Urgent - *should be fixed right away!*
   - [x] Non-urgent - *can be prioritized within normal workstreams.*

4. In the space provided below, please describe the behavior you expected from the simulation or otherwise describe what you expected to see or hear. 

Facilitators would like to close the loop for "RVI Delays Affects Treatment Decisions" Balancing Loop.  

5. Please provide a screenshot of the bug, if possible.  Make as many screenshots as you like that would be helpful to illustrate the  
   issue.

   *<< Paste screenshots here>>*
![image](https://user-images.githubusercontent.com/30132017/60399668-fbf46c00-9b1c-11e9-893f-bdc3eb758346.png)

6.  Within which product did you notice the problem? *Check all that apply*

   - [ ] SharePoint
   - [ ] Data/Queries
   - [ ] Team Data
   - [ ] R-reports
   - [ ] See Guide
   - [ ] Say Guide
   - [ ] Videos
   - [ ] Post tests
   - [ ] Fidelity Checklist
   - [ ] Other?  Please describe here >>
   
   Care Coordination Simulation
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Medication Management
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Psychotherapy
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Aggregate 
   - [x] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Suicide Prevention
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
  
7. What kind of device are you using?
   - [ ] Tablet
   - [ ] Smartphone
   - [x] PC

8. What browser were you using?
   - [x] Chrome  *What version?*
   - [ ] Edge    *What version?*
   - [ ] Safari  *What version?*

9. Please describe your idea below.  Feel free to provide a scan or screen capture of a sketch of your idea.

10. Why is this idea important, in terms of your work?

11. How is this idea related to a problem you face in your daily practice?

12. Is there a deadline or other scheduled constraint driving your request that we should be aware of? *This will help us to prioritize
    this request.*

     **THANK YOU!!**

---------------------------------------------------------------------------------------------------------------------------------------
**STOP HERE. INFORMATION BELOW IS TO BE FILLED OUT BY WORKGROUPS AS PART OF TRIAGE AND WORK BREAKDOWN PROCESS**
---------------------------------------------------------------------------------------------------------------------------------------

**Executive Summary**

*Estimated person-hours to complete:* 8 hrs

*Estimated date for completion:* 16 July, 2019

*Lead team for effort:* @jamesmrollins 

*Key people (use @ assignment for people whose input will be necessary):*

**Note:**This issue was originally #414 and has been moved to this thread to incorporate use of new form.

**Step 1 - Complete the Interdependencies Table**

Workgroup Leads review information provided by originator and collaborate to identify interdependencies. Then they describe modifications that are needed in the appropriate column and estimate hours needed to make changes:
 
● *Workgroup Products* - This column identifies the workgroups and the products for which they are responsible. This column can be
  modified by a workgroup lead on an ad-hoc basis to add one-time products or can be modified to include new and enduring products.
  
● *Dependency?* - This column is used by the workgroup leads during collaboration to identify the existence of an interdependency.

● *Description of Change or Action Needed* - Workgroup leads briefly describe the change required.

● *Hours* - Workgroup leads estimate the person-hours required to complete the task.

Workgroup Products        | Dependency?  | Description of Change Needed               |  Hours Estimate
------------------------- | -------------|--------------------------------------------|-----------------
**Documentation**            
Brochures                 |              |                                            |
MTL See Guide             |              |                                            |
MTL Say Guide             |              |                                            |
MTL Videos                |              |                                            |
Post Test                 |              |                                            |
**Investigators**         |              |                                            |
Presentation              |              |                                            |
Quarterly Report          |              |                                            |
Annual Report             |              |                                            |
**Qualitative**           |              |                                            |
MTL Fidelity Checklists   |              |                                            |
Systems Thinking Codebook |              |                                            |
CFIR Codebooks            |              |                                            | 
**Quantitative**          |              |                                            |
Data UI                   |              |                                            |
Data Queries              |              |                                            |
SharePoint                |              |                                            |
Excel Outputs             |              |                                            |
ModelParameters           |              |                                            |
tt Reports                |              |                                            |
**Model**
CC                        |              |                                            |
MM                        |              |                                            |
PSY                       |              |                                            |
AGG                       |              |                                            |
SP                        |              |                                            |
**Sim User Interface**    |              |                                            |
Model Diagram             |       Y       |                Add shadow variables to diagram                            | 8
"i"Information            |              |                                            |
Experiments               |              |                                            |
Outputs/Charts            |              |                                            |
Exports                   |              |                                            |
Master Crosswalk Table    |              |                                            |

**Step 2 - Identify Constraints that may affect the team’s ability to complete the necessary actions.** 

Describe the constraint in terms of capability, capacity or affect on grant research goals. If there are no constraints identified, then leave the table blank.

●  Type - The type of constraint identifies one or more resource areas that are affected.  

●  Workgroup - this is the workgroup responsible for developing a new or modifying an existing product.

●  Discussion/recommendation - A brief narrative that expands the information regarding the constraint and ideally a recommendation for
   overcoming the constraint.

**Type Constraint (check all that apply) / Workgroup(s) Affected / Discussion/Recommendation**

- [ ] Capacity      
- [ ] Cost         
- [ ] Schedule     
- [ ] Interference 
- [ ] Capability   
- [ ] Other (describe)

**Step 3 - Identify supported milestones.** *Affix the milestone at the issue level using available GitHub milestones.*

**Step 4 - Indicate the due date for completing the actions identified above, assuming constraints are removed.**

**Step 5 - Identify the lead workgroup for the action (check one):**

- [ ] Documentation
- [ ] Investigators
- [ ] Quantitative
- [ ] Qualitative
- [ ] Model
- [ ] Sim UI

**Step 6 - Go to the top of this section and complete Executive Summary information**

**Comment by jamesmrollins** [comment]
@saveth @staceypark @jessfroe @TomRust @holbrooa @lzim 

Updated concept sketch.  Labor hours updated in work break down

![image](https://user-images.githubusercontent.com/30132017/60736492-068f7680-9f0c-11e9-8a80-b5d496881b18.png)

**Comment by jamesmrollins** [comment]
@TomRust @lzim @saveth @holbrooa @branscombj @dlounsbu @staceypark @jessfroe 

Date has been push back due to 508 workload.  New date 16 July, 2019.

**Comment by jamesmrollins** [comment]
@hirenp-waferwire  here are the 508 instructions for the balancing loop "RVI Delays Affects Treatment Decisions" tab order. 

![image](https://user-images.githubusercontent.com/30132017/61137564-912b2500-a47a-11e9-90fe-f8a06880b3d2.png)

**Comment by TomRust** [comment]
@jamesmrollins -- so sorry, James!  I should have looked last week.  The polarities on the two new arrows are flipped.  See Vensim model diagram below:

![image](https://user-images.githubusercontent.com/32961420/61544756-12069580-aa14-11e9-9f3c-ec1a1edf4f08.png)

**Comment by jamesmrollins** [comment]
@hirenp-waferwire see comment above.  Looks like the polarities of the arrows in the diagram are backwards (see Tom Rust comment above).  Please change.

![image](https://user-images.githubusercontent.com/30132017/62018866-670f7d80-b171-11e9-8077-9ab886448f88.png)

**Comment by jamesmrollins** [comment]
@hirenp-waferwire I verify that the above changes have been made - thank you.

**Comment by lzim** [comment]
@TomRust and @jamesmrollins 

Looks like the appointments and completing rate has been added with polarities correct.
Therefore, I think we're ready for PROD on the substantive design/development work.

However, it looks like we have an "i" information for Actual RVI: Typo at "increasing  extending"
![increasing_extending](https://user-images.githubusercontent.com/7454688/62845497-5f75cb80-bc7d-11e9-94c4-d4cbec5efac6.png)

Also, I'm not sure I'm getting this language:
Appointments are never cancelled due to high wait times, but actual RVI is capped at 12 months (52 weeks) for ease of display. (wks)

**Comment by TomRust** [comment]
@jamesmrollins @lzim -- How about this language, then:

_"The actual average return-to-clinic visit interval that patients experience.  This is either the same as the RVI used when appointments are scheduled, or potentially longer, if the team reacts to work pressure by extending existing patients' RVI.  Longer than desired RVIs do not cause patients or providers to cancel appointments.  In theory, the actual RVI could be pushed to more than one year, but we've capped it at 52 weeks."_

**Comment by staceypark** [comment]
@jamesmrollins this is in done but the "i" information error (refer to @lzim & @TomRust's last two comments) is still incorrect in PROD: 

![image](https://user-images.githubusercontent.com/31089501/64056856-53c64800-cb4b-11e9-96e4-c32e70908c20.png)

**Comment by jamesmrollins** [comment]
@staceypark the "i" information is now correct.
