### ISSUE TITLE
AGG: No BC Button for Review Rate  --Due: Aug 31--

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#445]
**ORIGINATOR**
*Please follow the steps below to open an issue for the MTL Workgroups to address. Be sure to provide a descriptive title for the issue when saving.*

**Step 1** - Please assign this issue to the issue_tracker, under the “Projects” menu on the right side of your GitHub page.

**Step 2** - Please answer the questions below by placing a lowercase "x" between the applicable brackets below and providing brief narratives and screenshots where appropriate:

1. Is this issue a problem, such as a malfunction in the simulation, an error in documentation or similar concern, or is this a new idea
   we should consider?
   
   - [x] Problem 
   - [ ] New idea
   
2. What team are you on (exg., Menlo Park, Team Blue)?
Facilitator Workgroup
3. How urgent is this issue?

   - [x] Urgent - *should be addressed right away!*
   - [ ] Non-urgent - *can be prioritized within normal workstreams.*

4. In the space provided below, please describe the information or behavior you expected from the product or otherwise describe what you expected to see or hear. 

The Experimental Slider "Review Rate" should have a "BC" button so teams can review their basecase values to aid in decision-making.

5. Please provide a screenshot of the bug, if possible.  Make as many screenshots as you like that would be helpful to illustrate the issue.

   *<< Paste screenshots here>>*
![image](https://user-images.githubusercontent.com/30132017/60399908-5bed1180-9b21-11e9-8980-cd05d2d67d1b.png)

6.  Within which product did you notice the problem? *Check all that apply*

**Data Products**

   - [ ] SharePoint
   - [ ] Data/Queries
   - [ ] Team Data
   - [ ] R-reports
   
**Instructional Products**
  
   - [ ] See Guide
   - [ ] Say Guide
   - [ ] Videos
   - [ ] Post tests
   - [ ] Fidelity Checklist
   - [ ] Other?  Please describe here >>
   
**Simulations**
   
   Care Coordination
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Medication Management
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Psychotherapy
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Aggregate 
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [x] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Suicide Prevention
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
7. What kind of device are you using?
   - [ ] Tablet
   - [ ] Smartphone
   - [x] PC

8. What browser were you using?
   - [x] Chrome  *What version?*
   - [ ] Edge    *What version?*
   - [ ] Safari  *What version?*

**<< If you are highlighting a new idea, please continue >>**

9. Please describe your idea below.  Feel free to provide a scan or screen capture of a sketch of your idea.

10. Why is this idea important, in terms of your work?

11. How is this idea related to a problem you face in your daily practice?

12. Is there a deadline or other scheduled constraint driving your request that we should be aware of? *This will help us to prioritize
    this request.*

**THANK YOU!!**

---------------------------------------------------------------------------------------------------------------------------------------
**STOP HERE. INFORMATION BELOW IS TO BE FILLED OUT BY WORKGROUPS AS PART OF TRIAGE AND WORK BREAKDOWN PROCESS**
---------------------------------------------------------------------------------------------------------------------------------------

**Executive Summary**

*Estimated person-hours to complete:* 

*Estimated date for completion:* July 8, 2019

*Lead team for effort:* Sim UI

*Key people (use @ assignment for people whose input will be necessary):*
@jamesmrollins 
@saveth 
@TomRust 

**Step 1 - Complete the Interdependencies Table**

Workgroup Leads review information provided by originator and collaborate to identify interdependencies. Then they describe modifications that are needed in the appropriate column and estimate hours needed to make changes:
 
● *Workgroup Products* - This column identifies the workgroups and the products for which they are responsible. This column can be
  modified by a workgroup lead on an ad-hoc basis to add one-time products or can be modified to include new and enduring products.
  
● *Dependency?* - This column is used by the workgroup leads during collaboration to identify the existence of an interdependency.

● *Description of Change or Action Needed* - Workgroup leads briefly describe the change required.

● *Hours* - Workgroup leads estimate the person-hours required to complete the task.

Workgroup Products        | Dependency?  | Description of Change Needed               |  Hours Estimate
------------------------- | -------------|--------------------------------------------|-----------------
**Documentation**            
Brochures                 |              |                                            |
MTL See Guide             |              |                                            |
MTL Say Guide             |              |                                            |
MTL Videos                |              |                                            |
Post Test                 |              |                                            |
**Investigators**         |              |                                            |
Presentation              |              |                                            |
Quarterly Report          |              |                                            |
Annual Report             |              |                                            |
**Qualitative**           |              |                                            |
MTL Fidelity Checklists   |              |                                            |
Systems Thinking Codebook |              |                                            |
CFIR Codebooks            |              |                                            | 
**Quantitative**          |              |                                            |
Data UI                   |              |                                            |
Data Queries              |              |                                            |
SharePoint                |              |                                            |
Excel Outputs             |              |                                            |
ModelParameters           |              |                                            |
tt Reports                |      Yes        |          Will change data structure of export.                                  | 1
**Model**
CC                        |              |                                            |
MM                        |              |                                            |
PSY                       |              |                                            |
AGG                       |              |                                            | 
SP                        |              |                                            |
**Sim User Interface**    |              |                                            |
Model Diagram             |              |                                            |
"i"Information            |              |                                            |
Experiments               |     Y         |   Add "BC" Button, map to "Review Rate" variable   |  2 hrs.
Outputs/Charts            |     N         |        Not Needed as per follow up from @TomRust                              |
Exports                   |       Y       |        Will add extra line to export                                    |  1 hrs.
Master Crosswalk Table    |     Y         |      Review Rate is missing from Master Crosswalk     | 1 hrs.
**Step 2 - Identify Constraints that may affect the team’s ability to complete the necessary actions.** 

Describe the constraint in terms of capability, capacity or affect on grant research goals. If there are no constraints identified, then leave the table blank.

●  Type - The type of constraint identifies one or more resource areas that are affected.  

●  Workgroup - this is the workgroup responsible for developing a new or modifying an existing product.

●  Discussion/recommendation - A brief narrative that expands the information regarding the constraint and ideally a recommendation for
   overcoming the constraint.

**Type Constraint (check all that apply) / Workgroup(s) Affected / Discussion/Recommendation**

- [ ] Capacity      
- [ ] Cost         
- [ ] Schedule     
- [ ] Interference 
- [ ] Capability   
- [ ] Other (describe)

**Step 3 - Identify supported milestones.** *Affix the milestone at the issue level using available GitHub milestones.*

**Step 4 - Indicate the due date for completing the actions identified above, assuming constraints are removed.**
July 8, 2019

**Step 5 - Identify the lead workgroup for the action (check one):**

- [ ] Documentation
- [ ] Investigators
- [ ] Quantitative
- [ ] Qualitative
- [ ] Model
- [x] Sim UI

**Step 6 - Go to the top of this section and complete Executive Summary information**

Note to Workgroups:  Use the issue thread to document further discussion, alternatives development and estimates.  However, be sure to update this form if dates, team responsibility or other information changes.

**Comment by jamesmrollins** [comment]
As per conversation with @TomRust, since the Review Rate is only necessary for a initial calculation, and then changes if the user adjusts the slider, it doesn't seem that there is an apparent need to report this in a chart, as it is not a dynamic variable - its just an input.

**Comment by jamesmrollins** [comment]
This issue is cross-referenced to #400 entered by @dlkibbe .

**Comment by jamesmrollins** [comment]
@hirenp-waferwire please move this to PROD and DEMO.  Thanks, James

**Comment by staceypark** [comment]
@jamesmrollins Looks good in Test. Doesn't have any changes in guides or cheatsheets.
Btw, we specifically have to be mindful of gif changes with changes to AGG, because all of our sim gifs are in Agg. #445 & #411 changes don't seem to have affected gifs however.

@saveth will have a dependency with tt report. Contrary to discussion this morning, since we doing PSY & SP with the TAS, the push to PROD for this can wait until her materials are ready as well, instead of needing to be ahead of the TAS schedule.

**Comment by jamesmrollins** [comment]
Thanks @staceypark .  However, this was already promoted to PROD.  Sorry, I moved this prematurely!

**Comment by saveth** [comment]
@jamesmrollins @staceypark  I exported the experiment files out of the sim from both prod and test for AGG, but there's no change. The last row in the file is still 244, which is the same as when I last exported for the July tt update.

**Comment by jamesmrollins** [comment]
@saveth @staceypark I investigated the Base Case value issue.  There are currently no exported base case values.  The experiment variables do export to show either their default (base case) as a negative value, or the user provided value based on the slider position.  See below for more information.  Ergo, I do not believe that @saveth has any dependencies in this case.

![image](https://user-images.githubusercontent.com/30132017/62339983-c7b0fa00-b492-11e9-9a26-4aad54d1eaf5.png)

**Comment by saveth** [comment]
Thanks @jamesmrollins! I guess this means this issue can now be closed. 😄
