### ISSUE TITLE
Provide a Link on Login Tile for User to Reset Their Password

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#446]
**ORIGINATOR**
*Please follow the steps below to open an issue for the MTL Workgroups to address. Be sure to provide a descriptive title for the issue when saving.*

**Step 1** - Please assign this issue to the issue_tracker, under the “Projects” menu on the right side of your GitHub page.

**Step 2** - Please answer the questions below by placing a lowercase "x" between the applicable brackets below and providing brief narratives and screenshots where appropriate:

1. Is this issue a problem, such as a malfunction in the simulation, an error in documentation or similar concern, or is this a new idea
   we should consider?
   
   - [ ] Problem 
   - [x] New idea
   
2. What team are you on (exg., Menlo Park, Team Blue)?
SIM UI Workgroup
3. How urgent is this issue?

   - [ ] Urgent - *should be addressed right away!*
   - [x] Non-urgent - *can be prioritized within normal workstreams.*

4. In the space provided below, please describe the information or behavior you expected from the product or otherwise describe what you expected to see or hear. 

5. Please provide a screenshot of the bug, if possible.  Make as many screenshots as you like that would be helpful to illustrate the issue.

   *<< Paste screenshots here>>*

6.  Within which product did you notice the problem? *Check all that apply*

**Data Products**

   - [ ] SharePoint
   - [ ] Data/Queries
   - [ ] Team Data
   - [ ] R-reports
   
**Instructional Products**
  
   - [ ] See Guide
   - [ ] Say Guide
   - [ ] Videos
   - [ ] Post tests
   - [ ] Fidelity Checklist
   - [ ] Other?  Please describe here >>
   
**Simulations**
- [x] Login
Home Screen
- [ ] Session 
- [ ] Experiment Maintenance
- [ ] Team Data Menu Maintenance
- [ ] Chat
- [ ] Help
   Care Coordination
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Medication Management
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Psychotherapy
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Aggregate 
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Suicide Prevention
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
7. What kind of device are you using?
   - [ ] Tablet
   - [ ] Smartphone
   - [ ] PC

8. What browser were you using?
   - [ ] Chrome  *What version?*
   - [ ] Edge    *What version?*
   - [ ] Safari  *What version?*

**<< If you are highlighting a new idea, please continue >>**

9. Please describe your idea below.  Feel free to provide a scan or screen capture of a sketch of your idea.
Provide the use with a link on the login tile, so they can request a password reset.
![image](https://user-images.githubusercontent.com/30132017/60400098-2dbd0100-9b24-11e9-81f0-561fdc4a8414.png)

10. Why is this idea important, in terms of your work?
This will relieve pressure from facilitators and HQ to administer user accounts by allowing user to self-help.

11. How is this idea related to a problem you face in your daily practice?

12. Is there a deadline or other scheduled constraint driving your request that we should be aware of? *This will help us to prioritize
    this request.*

No

**THANK YOU!!**

---------------------------------------------------------------------------------------------------------------------------------------
**STOP HERE. INFORMATION BELOW IS TO BE FILLED OUT BY WORKGROUPS AS PART OF TRIAGE AND WORK BREAKDOWN PROCESS**
---------------------------------------------------------------------------------------------------------------------------------------

**Executive Summary**

*Estimated person-hours to complete:* 10

*Estimated date for completion:* July 19, 2019

*Lead team for effort:* @jamesmrollins 

*Key people (use @ assignment for people whose input will be necessary):*

**Step 1 - Complete the Interdependencies Table**

Workgroup Leads review information provided by originator and collaborate to identify interdependencies. Then they describe modifications that are needed in the appropriate column and estimate hours needed to make changes:
 
● *Workgroup Products* - This column identifies the workgroups and the products for which they are responsible. This column can be
  modified by a workgroup lead on an ad-hoc basis to add one-time products or can be modified to include new and enduring products.
  
● *Dependency?* - This column is used by the workgroup leads during collaboration to identify the existence of an interdependency.

● *Description of Change or Action Needed* - Workgroup leads briefly describe the change required.

● *Hours* - Workgroup leads estimate the person-hours required to complete the task.

Workgroup Products        | Dependency?  | Description of Change Needed               |  Hours Estimate
------------------------- | -------------|--------------------------------------------|-----------------
**Documentation**            
Brochures                 |              |                                            |
MTL See Guide             |              |                                            |
MTL Say Guide             |              |                                            |
MTL Videos                |              |                                            |
Post Test                 |              |                                            |
**Investigators**         |              |                                            |
Presentation              |              |                                            |
Quarterly Report          |              |                                            |
Annual Report             |              |                                            |
**Qualitative**           |              |                                            |
MTL Fidelity Checklists   |              |                                            |
Systems Thinking Codebook |              |                                            |
CFIR Codebooks            |              |                                            | 
**Quantitative**          |              |                                            |
Data UI                   |              |                                            |
Data Queries              |              |                                            |
SharePoint                |              |                                            |
Excel Outputs             |              |                                            |
ModelParameters           |              |                                            |
tt Reports                |              |                                            |
**Model**
CC                        |              |                                            |
MM                        |              |                                            |
PSY                       |              |                                            |
AGG                       |              |                                            |
SP                        |              |                                            |
**Sim User Interface**    |              |                                            |
Model Diagram             |              |                                            |
"i"Information            |              |                                            |
Experiments               |              |                                            |
Outputs/Charts            |              |                                            |
Exports                   |              |                                            |
Master Crosswalk Table    |              |                                            |
Login Page       |     Y    |  Add link that gives a user the option to reset their password.  Must have email address Username.  |   10

**Step 2 - Identify Constraints that may affect the team’s ability to complete the necessary actions.** 

Describe the constraint in terms of capability, capacity or affect on grant research goals. If there are no constraints identified, then leave the table blank.

●  Type - The type of constraint identifies one or more resource areas that are affected.  

●  Workgroup - this is the workgroup responsible for developing a new or modifying an existing product.

●  Discussion/recommendation - A brief narrative that expands the information regarding the constraint and ideally a recommendation for
   overcoming the constraint.

**Type Constraint (check all that apply) / Workgroup(s) Affected / Discussion/Recommendation**

- [ ] Capacity      
- [ ] Cost         
- [ ] Schedule     
- [ ] Interference 
- [ ] Capability   
- [ ] Other (describe)

**Step 3 - Identify supported milestones.** *Affix the milestone at the issue level using available GitHub milestones.*

**Step 4 - Indicate the due date for completing the actions identified above, assuming constraints are removed.**

**Step 5 - Identify the lead workgroup for the action (check one):**

- [ ] Documentation
- [ ] Investigators
- [ ] Quantitative
- [ ] Qualitative
- [ ] Model
- [x] Sim UI

**Step 6 - Go to the top of this section and complete Executive Summary information**

Note to Workgroups:  Use the issue thread to document further discussion, alternatives development and estimates.  However, be sure to update this form if dates, team responsibility or other information changes.

**Comment by jamesmrollins** [comment]
@hirenp-waferwire this is released for development.  Thanks, James

**Comment by staceypark** [comment]
@jamesmrollins I'm going to update the sim_ui cheatsheet with this information before we move this to PROD.

FYI: @dlounsbu @branscombj @lzim @TomRust @dlkibbe
The implication for facilitators with the reset password option is that when we first setup the sim, we will be giving users a standard password. However, if they choose to reset their password, we will not know what it is.

**Comment by staceypark** [comment]
@jamesmrollins let's move this PROD, but keep it open until I update the cheatsheet.

**Comment by staceypark** [comment]
- added this to the meta_depend column since it will show up in all videos for session 5-12.
- gifs have already been updated so does not need to go in describe.
- adding to only s05 for detail since facilitators don't need to explain it every time & only adding to s05 for document where they first see the sim cheatsheet since the cheatsheet doesn't change per session.
