### ISSUE TITLE
Export Chat Dialogue Function

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#447]
**ORIGINATOR**
*Please follow the steps below to open an issue for the MTL Workgroups to address. Be sure to provide a descriptive title for the issue when saving.*

**Step 1** - Please assign this issue to the issue_tracker, under the “Projects” menu on the right side of your GitHub page.

**Step 2** - Please answer the questions below by placing a lowercase "x" between the applicable brackets below and providing brief narratives and screenshots where appropriate:

1. Is this issue a problem, such as a malfunction in the simulation, an error in documentation or similar concern, or is this a new idea
   we should consider?
   
   - [ ] Problem 
   - [x] New idea
   
2. What team are you on (exg., Menlo Park, Team Blue)?
Headquarters Workgroup
3. How urgent is this issue?

   - [ ] Urgent - *should be addressed right away!*
   - [x] Non-urgent - *can be prioritized within normal workstreams.*

4. In the space provided below, please describe the information or behavior you expected from the product or otherwise describe what you expected to see or hear. 

There is currently no way to export chat dialogue for qualitative analysis.  

5. Please provide a screenshot of the bug, if possible.  Make as many screenshots as you like that would be helpful to illustrate the issue.

   *<< Paste screenshots here>>*

6.  Within which product did you notice the problem? *Check all that apply*

**Data Products**

   - [ ] SharePoint
   - [ ] Data/Queries
   - [ ] Team Data
   - [ ] R-reports
   
**Instructional Products**
  
   - [ ] See Guide
   - [ ] Say Guide
   - [ ] Videos
   - [ ] Post tests
   - [ ] Fidelity Checklist
   - [ ] Other?  Please describe here >>
   
**Simulations**
   
   Home
   - [ ] Login 
   - [ ] Session
   - [ ] Experiment Maintenance Tile
   - [ ] Team Data Menu Maintenance
   - [x] Chat
   - [ ] Help
   - [ ] Facilitator Dashboard
   
   Care Coordination
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Medication Management
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Psychotherapy
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Aggregate 
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Suicide Prevention
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
7. What kind of device are you using?
   - [ ] Tablet
   - [ ] Smartphone
   - [ ] PC

8. What browser were you using?
   - [ ] Chrome  *What version?*
   - [ ] Edge    *What version?*
   - [ ] Safari  *What version?*

**<< If you are highlighting a new idea, please continue >>**

9. Please describe your idea below.  Feel free to provide a scan or screen capture of a sketch of your idea.

Develop an export function so chat dialogue can be exported as an Excel spreadsheet.  The spreadsheet should have columns to indicate the time stamp of the chat, the user ID and the chat narrative. Each row would capture a chat instance.

10. Why is this idea important, in terms of your work?

This function would aid qualitative analysis by enabling the scientist to use the keyword search, sort, and query function of the Excel software.

11. How is this idea related to a problem you face in your daily practice?

This function would streamline the assignment of codes.

12. Is there a deadline or other scheduled constraint driving your request that we should be aware of? *This will help us to prioritize this request.*
No.

**THANK YOU!!**

---------------------------------------------------------------------------------------------------------------------------------------
**STOP HERE. INFORMATION BELOW IS TO BE FILLED OUT BY WORKGROUPS AS PART OF TRIAGE AND WORK BREAKDOWN PROCESS**
---------------------------------------------------------------------------------------------------------------------------------------

**Executive Summary**

*Estimated person-hours to complete:*

*Estimated date for completion:*

*Lead team for effort:*

*Key people (use @ assignment for people whose input will be necessary):*

**Note -** This item was created for an assigned action in Lucid for tracking in new Kanban system. This feature should be validated with originator.  

**Step 1 - Complete the Interdependencies Table**

Workgroup Leads review information provided by originator and collaborate to identify interdependencies. Then they describe modifications that are needed in the appropriate column and estimate hours needed to make changes:
 
● *Workgroup Products* - This column identifies the workgroups and the products for which they are responsible. This column can be
  modified by a workgroup lead on an ad-hoc basis to add one-time products or can be modified to include new and enduring products.
  
● *Dependency?* - This column is used by the workgroup leads during collaboration to identify the existence of an interdependency.

● *Description of Change or Action Needed* - Workgroup leads briefly describe the change required.

● *Hours* - Workgroup leads estimate the person-hours required to complete the task.

Workgroup Products        | Dependency?  | Description of Change Needed               |  Hours Estimate
------------------------- | -------------|--------------------------------------------|-----------------
**Documentation**            
Brochures                 |              |                                            |
MTL See Guide             |              |                                            |
MTL Say Guide             |              |                                            |
MTL Videos                |              |                                            |
Post Test                 |              |                                            |
**Investigators**         |              |                                            |
Presentation              |              |                                            |
Quarterly Report          |              |                                            |
Annual Report             |              |                                            |
**Qualitative**           |              |                                            |
MTL Fidelity Checklists   |              |                                            |
Systems Thinking Codebook |              |                                            |
CFIR Codebooks            |              |                                            | 
**Quantitative**          |              |                                            |
Data UI                   |              |                                            |
Data Queries              |              |                                            |
SharePoint                |              |                                            |
Excel Outputs             |              |                                            |
ModelParameters           |              |                                            |
tt Reports                |              |                                            |
**Model**
CC                        |              |                                            |
MM                        |              |                                            |
PSY                       |              |                                            |
AGG                       |              |                                            |
SP                        |              |                                            |
**Sim User Interface**    |              |                                            |
Model Diagram             |              |                                            |
"i"Information            |              |                                            |
Experiments               |              |                                            |
Outputs/Charts            |              |                                            |
Exports                   |              |                                            |
Master Crosswalk Table    |              |                                            |

**Step 2 - Identify Constraints that may affect the team’s ability to complete the necessary actions.** 

Describe the constraint in terms of capability, capacity or affect on grant research goals. If there are no constraints identified, then leave the table blank.

●  Type - The type of constraint identifies one or more resource areas that are affected.  

●  Workgroup - this is the workgroup responsible for developing a new or modifying an existing product.

●  Discussion/recommendation - A brief narrative that expands the information regardingthe constraint and ideally a recommendation for
   overcoming the constraint.

**Type Constraint (check all that apply) / Workgroup(s) Affected / Discussion/Recommendation**

- [ ] Capacity      
- [ ] Cost         
- [ ] Schedule     
- [ ] Interference 
- [ ] Capability   
- [ ] Other (describe)

**Step 3 - Identify supported milestones.** *Affix the milestone at the issue level using available GitHub milestones.*

**Step 4 - Indicate the due date for completing the actions identified above, assuming constraints are removed.**

**Step 5 - Identify the lead workgroup for the action (check one):**

- [ ] Documentation
- [ ] Investigators
- [ ] Quantitative
- [ ] Qualitative
- [ ] Model
- [ ] Sim UI

**Step 6 - Go to the top of this section and complete Executive Summary information**

Note to Workgroups:  Use the issue thread to document further discussion, alternatives development and estimates.  However, be sure to update this form if dates, team responsibility or other information changes.

**Comment by staceypark** [comment]
@jamesmrollins I see the originator_followup_needed tag. What questions did you have?

**Comment by jamesmrollins** [comment]
@lzim and @staceypark I found this in the action list from Lucid.  Is about a year old.  The team wanted to validate that this is still a requirement, in case another work-around was developed.  Thanks, James

**Comment by lzim** [comment]
@staceypark and @jamesmrollins 

I don't know that this adds value. I recommend we close this issue.

**Comment by jamesmrollins** [comment]
@lzim as the originator, you would close the issue, which indicates your satisfaction regarding this issue. - James

@staceypark FYI

**Comment by lzim** [comment]
Closed thanks @jamesmrollins
