### ISSUE TITLE
PSY: Lower Portion of Psy Team Data Table Is not Accurate    --Now Due: AUG 19--

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#451]
**ORIGINATOR**
*Please follow the steps below to open an issue for the MTL Workgroups to address. Be sure to provide a descriptive title for the issue when saving.*

**Step 1** - Please assign this issue to the issue_tracker, under the “Projects” menu on the right side of your GitHub page.

**Step 2** - Please answer the questions below by placing a lowercase "x" between the applicable brackets below and providing brief narratives and screenshots where appropriate:

1. Is this issue a problem, such as a malfunction in the simulation, an error in documentation or similar concern, or is this a new idea
   we should consider?
   
   - [x] Problem 
   - [ ] New idea
   
2. What team are you on (exg., Menlo Park, Team Blue)?
N/A
3. How urgent is this issue?

   - [x] Urgent - *should be addressed right away!*
   - [ ] Non-urgent - *can be prioritized within normal workstreams.*

4. In the space provided below, please describe the information or behavior you expected from the product or otherwise describe what you expected to see or hear. 

Return Visit Interval after 3 Months (wks) is not actually divided into First Quartile, Mean or 4th Quartile groups.  In actuality, the numbers reflect median RVI for the Low, Medium and High patient groups. Low, Medium and High refers to their engagement duration.  

5. Please provide a screenshot of the bug, if possible.  Make as many screenshots as you like that would be helpful to illustrate the issue.

   *<< Paste screenshots here>>*
![image](https://user-images.githubusercontent.com/30132017/60927007-2355e200-a25d-11e9-9597-04fee60dc5b5.png)

6.  Within which product did you notice the problem? *Check all that apply*

**Data Products**

   - [ ] SharePoint
   - [ ] Data/Queries
   - [ ] Team Data
   - [ ] R-reports
   
**Instructional Products**
  
   - [ ] See Guide
   - [ ] Say Guide
   - [ ] Videos
   - [ ] Post tests
   - [ ] Fidelity Checklist
   - [ ] Cheatsheets
   - [ ] Other?  Please describe here >>
   
**Simulations**
   
   Home
   - [ ] Login 
   - [ ] Session
   - [ ] Experiment Maintenance Tile
   - [ ] Team Data Menu Maintenance
   - [ ] Chat
   - [ ] Help
   - [ ] Facilitator Dashboard
   
   Care Coordination
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Medication Management
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Psychotherapy
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [x] Team Data Table
   
   Aggregate 
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Suicide Prevention
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
7. What kind of device are you using?
   - [ ] Tablet
   - [ ] Smartphone
   - [x] PC

8. What browser were you using?
   - [x] Chrome  *What version?*
   - [ ] Edge    *What version?*
   - [ ] Safari  *What version?*

**<< If you are highlighting a new idea, please continue >>**

9. Please describe your idea below.  Feel free to provide a scan or screen capture of a sketch of your idea.

- From 1 visit there are low, medium and high groups as measured by engagement duration.
- "From X Visit" refers to what they did before the three month threshold.
- Engagement duration refers to post 3 months.
- "From X Visit" label should be using Starting, Initiators and Completers labels for consistency with upper part of table and UI diagram.
- First Quartile, and Mean and 4th Quartile are really medians of Low, Medium and High groups.
- Places that indicate "See table below" have a patient flow label that should be used in the table below.
- Engagement Time after 3 Months (wks) is correct, except the Mean should be Median.
- Grouping the data by Patient Flow for RVI and Engagement Time after 3 months may be a preferable alternative.
- Pop up charts need to be changed to refect the new order shown in the alternatives.
- This feature should be broken into its own feature and tracked/approved seperately.

Here is a sketch:

![image](https://user-images.githubusercontent.com/30132017/60927208-eb02d380-a25d-11e9-98d6-62bd66916122.png)

10. Why is this idea important, in terms of your work?

11. How is this idea related to a problem you face in your daily practice?

12. Is there a deadline or other scheduled constraint driving your request that we should be aware of? *This will help us to prioritize
    this request.*

**THANK YOU!!**

---------------------------------------------------------------------------------------------------------------------------------------
**STOP HERE. INFORMATION BELOW IS TO BE FILLED OUT BY WORKGROUPS AS PART OF TRIAGE AND WORK BREAKDOWN PROCESS**
---------------------------------------------------------------------------------------------------------------------------------------

**Executive Summary**

*Estimated person-hours to complete:* 19 hrs not including video/documentation in estimate.

*Estimated date for completion:*

*Lead team for effort:* @jamesmrollins 

*Key people (use @ assignment for people whose input will be necessary):*
@holbrooa 
@staceypark 
@saveth 
@TomRust 

**Please Note:** This issue is cross-referenced to #399 Improve Psy Team Data Table. 

**Step 1 - Complete the Interdependencies Table**

Workgroup Leads review information provided by originator and collaborate to identify interdependencies. Then they describe modifications that are needed in the appropriate column and estimate hours needed to make changes:
 
● *Workgroup Products* - This column identifies the workgroups and the products for which they are responsible. This column can be
  modified by a workgroup lead on an ad-hoc basis to add one-time products or can be modified to include new and enduring products.
  
● *Dependency?* - This column is used by the workgroup leads during collaboration to identify the existence of an interdependency.

● *Description of Change or Action Needed* - Workgroup leads briefly describe the change required.

● *Hours* - Workgroup leads estimate the person-hours required to complete the task.

Workgroup Products        | Dependency?  | Description of Change Needed               |  Hours Estimate
------------------------- | -------------|--------------------------------------------|-----------------
**Documentation**            
Brochures                 |              |                                            |
MTL See Guide             |              |                                            |
MTL Say Guide             |              |                                            |
MTL Videos                |    Y          |    Need to review for potential popup addition     |
Post Test                 |              |                                            |
**Investigators**         |              |                                            |
Presentation              |              |                                            |
Quarterly Report          |              |                                            |
Annual Report             |              |                                            |
**Qualitative**           |              |                                            |
MTL Fidelity Checklists   |              |                                            |
Systems Thinking Codebook |              |                                            |
CFIR Codebooks            |              |                                            | 
**Quantitative**          |              |                                            |
Data UI                   |              |                                            |
Data Queries              |              |                                            |
SharePoint                |              |                                            |
Excel Outputs             |              |                                            |
ModelParameters           |    Y          | Revise "i" Information in ModelParameters to include (pts/wk) |
tt Reports                |             Y | Update to include New Patient Start Rate to Team Data Table    | 4
**Model**
CC                        |              |                                            |
MM                        |              |                                            |
PSY                       |              |                                            |
AGG                       |              |                                            |
SP                        |              |                                            |
**Sim User Interface**    |              |                                            |
Model Diagram             |              |                                            |
"i"Information            |     Y         |      Team Data Table added information     |2
Experiments               |   Y           |        Team Data Table re-design                  | 10
Outputs/Charts            |       Y       |    Charts embedded into TD table            | 2
Exports                   |       Y       |       Addition of Low, Medium and High groups    | 2
Master Crosswalk Table    |     Y         |    New variable mapping                        |1

**Step 2 - Identify Constraints that may affect the team’s ability to complete the necessary actions.** 

Describe the constraint in terms of capability, capacity or affect on grant research goals. If there are no constraints identified, then leave the table blank.

●  Type - The type of constraint identifies one or more resource areas that are affected.  

●  Workgroup - this is the workgroup responsible for developing a new or modifying an existing product.

●  Discussion/recommendation - A brief narrative that expands the information regardingthe constraint and ideally a recommendation for
   overcoming the constraint.

**Type Constraint (check all that apply) / Workgroup(s) Affected / Discussion/Recommendation**

- [ ] Capacity      
- [ ] Cost         
- [ ] Schedule     
- [ ] Interference 
- [ ] Capability   
- [ ] Other (describe)

**Step 3 - Identify supported milestones.** *Affix the milestone at the issue level using available GitHub milestones.*

**Step 4 - Indicate the due date for completing the actions identified above, assuming constraints are removed.**

**Step 5 - Identify the lead workgroup for the action (check one):**

- [ ] Documentation
- [ ] Investigators
- [ ] Quantitative
- [ ] Qualitative
- [ ] Model
- [ ] Sim UI

**Step 6 - Go to the top of this section and complete Executive Summary information**

Note to Workgroups:  Use the issue thread to document further discussion, alternatives development and estimates.  However, be sure to update this form if dates, team responsibility or other information changes.

**Comment by jamesmrollins** [comment]
@saveth @staceypark @TomRust @jessfroe @holbrooa  This issue requires additional work breakdown from other workgroup leads and final team approval before cost estimation and decision by PI.

**Comment by TomRust** [comment]
@jamesmrollins -- In your mock-up, you are showing way more data than we have.  It's still only 9 RVIs and 9 Engagement Durations.

In our meeting on Tuesday, I though we brainstormed something more like this example:


**Starters who Return Later** |   |   |  
-- | -- | -- | --
  |   | Engagement Time after 3 Months     (wks) | RVI     (wks)
  | Low duration group | 13 | 9
  | Medium duration   group | 18 | 15
  | High duration   group | 37 | 5

**Comment by jamesmrollins** [comment]
@TomRust @holbrooa  I checked the meeting notes, and we had the three groups for each type of patients (i.e., Starters, Initiators and Completers).  The table below is what we are after, right?  The issue is that we don't have first quartile, median and fourth quartile data sets, we only have one number.  Is this the median number of appointments per week @holbrooa ?

![image](https://user-images.githubusercontent.com/30132017/61087565-d0aa3080-a3ea-11e9-8b89-d1d9f9750c4f.png)

When you guys confirm, I will revise the table.  Thanks, James

**Comment by holbrooa** [comment]
@TomRust @jamesmrollins 

Tom has it right. We're not adding any new data here, we're just trying to change the layout of the table to make it clearer what's going on. Specifically, there's a transposition going on above: what we had originally as **columns** - first quartile, median, and fourth quartile - are becoming **rows** - low duration group, medium duration group, and high duration group. Each of the three initial patient types (starters who return later, initiators who return later, completers who return) is being further divided into those three duration groups, and then each of those combinations (3x3 yielding 9 groups) has two data points: engagement and RVI. So that's the same 18 numbers we had before, just reorganized into a table that has only two columns of numbers, but nested rows.

The RVI numbers are indeed all medians. The engagement durations are technically not medians, but for the purpose of the communication that this table is supposed to accomplish, I think it's much more important to focus on how to present these numbers as estimates for each of the 9 groups. So each of the nine groups, e.g. Initiators who return later with low duration, has an engagement and an RVI. It's less important exactly how those two things are estimated, because they can go elsewhere for more information about that, but I just want to prevent the confusion that comes when it's not clear that the numbers refer to the above nested groups.

James, your screenshot doesn't have the lingo I copied into our meeting, just because it's in the next column over to the right.  That's where I talk about the nested group method I'm talking about here.

**Comment by jamesmrollins** [comment]
@holbrooa @TomRust  Let's start with the Master Crosswalk.  Please see below and indicate whether I have evolved from the neanderthal!  Once confirmed by one of you, I will redraw the art.  Thanks, James. 

![image](https://user-images.githubusercontent.com/30132017/61159293-6956b400-a4b0-11e9-8829-512b31071890.png)

**Comment by holbrooa** [comment]
@TomRust @jamesmrollins 

Yeah, that's the ticket! The labels need to be changed and stuff of course, but we are on the same page now with the layout.

**Comment by jamesmrollins** [comment]
@TomRust @holbrooa  Thanks Andrew.  I will provide two alternatives, with respect to the orientation of the columns and the rows.

**Comment by jamesmrollins** [comment]
@TomRust @holbrooa Here are the alternatives:

A.  Column format
![image](https://user-images.githubusercontent.com/30132017/61161372-58aa3c00-a4b8-11e9-925e-ad7c443fab07.png)

B.  Row format
![image](https://user-images.githubusercontent.com/30132017/61161402-6e1f6600-a4b8-11e9-92fe-8c669ffd4881.png)

A to me is more attractive, compact and easy to find numbers than B.  However, B has the room for more complete labels (i.e., "Low Duration Group", versus just "Low.")

**Comment by holbrooa** [comment]
Meh. Both are good for me. @lzim weigh in?

**Comment by jamesmrollins** [comment]
@TomRust @holbrooa here is the changes that I think need to be made to the charts.

**For RVI**
![image](https://user-images.githubusercontent.com/30132017/61161495-d0786680-a4b8-11e9-88cd-1f6cac22f76f.png)

**For Engagement Duration**

![image](https://user-images.githubusercontent.com/30132017/61161560-25b47800-a4b9-11e9-9e91-fd12a0e7a194.png)

**Comment by TomRust** [comment]
![image](https://user-images.githubusercontent.com/32961420/61229082-8203db80-a6f5-11e9-9fa3-0d7876f2fdbc.png)
 How about this?

**Comment by lzim** [comment]
> ![image](https://user-images.githubusercontent.com/32961420/61229082-8203db80-a6f5-11e9-9fa3-0d7876f2fdbc.png)
> How about this?

@jamesmrollins @TomRust thanks, Tom's edit to column option A above is great!

**Comment by TomRust** [comment]
@jamesmrollins -- the variable crosswalk looks good, too!

**Comment by TomRust** [comment]
@lzim , @jessfroe -- How about this for the pop-up in PSY Session 6 (right?) video, first time we reveal the team data table: 
_Your Team Data Table might look a bit different: We've re-organized the table to clarify which data apply to patients first 3 months in care and all their time after their first 3 months._

**Comment by jamesmrollins** [comment]
@hirenp-waferwire  Please review the design guidance below and provide me an updated estimate.  I will email an EPS artboard for reference.

**Update Team Data Table**.  I will email an updated master_crosswalk_table.xlsx that contains updated variable mapping for the table as illustrated below.

![image](https://user-images.githubusercontent.com/30132017/61240312-c4c5b380-a6f5-11e9-83d9-1e90ae219a30.png)

**Update Team Data Table "i" Information**

![image](https://user-images.githubusercontent.com/30132017/61240463-20903c80-a6f6-11e9-87b3-565ed0371074.png)

**Update Popup Charts**

![image](https://user-images.githubusercontent.com/30132017/61240750-cb085f80-a6f6-11e9-899d-a60784e5aad1.png)

![image](https://user-images.githubusercontent.com/30132017/61240699-add39100-a6f6-11e9-9cd4-5a5a6eb8bd72.png)

**Comment by jamesmrollins** [comment]
@hirenp-waferwire  Please see pick-list items below:

1.  Pop-up charts do not float outside Team Data Table
![image](https://user-images.githubusercontent.com/30132017/61386595-6883a080-a869-11e9-8d72-2a6439f9dacc.png)

2.  Format improvements.

![image](https://user-images.githubusercontent.com/30132017/61387252-a1704500-a86a-11e9-9c18-c5e763fd23a8.png)

3.  The table should use tab focus as per 508 guidelines. I know you know this; however, I made this entry as a note for me, so I don't forget to check it.

**Comment by staceypark** [comment]
1. @jamesmrollins I think the label "Team Data" at the top should be in Red in accordance with our "red = read in from team data" conventions yes?

![image](https://user-images.githubusercontent.com/31089501/62176669-3c4f3180-b2f7-11e9-8ff5-3c68bbf80ec1.png)

2. @TomRust @lzim  I think it's more consistent to keep RVI first and Median Engagement Duration second for both the First 3 Months & After 3 Months sections. Also, should the "After 3 Months Engagement Duration" say "Median Engagement Duration" as well or is this not a Median? In the event that it's not a Median, we need to explain the two engagement durations in the "i" information.
![image](https://user-images.githubusercontent.com/31089501/62177281-34908c80-b2f9-11e9-8ad4-22357ff3b2c8.png)

Along those lines, if it should indeed read "Median Engagement Duration" for After 3 Months, then the below two labels as well as the level in the Experiment section will need to change.
![image](https://user-images.githubusercontent.com/31089501/62177325-5a1d9600-b2f9-11e9-9402-e61e543d50bf.png)


3. @lzim @TomRust We don't have the "xyz who Return" language anywhere else but in the Team Data table. Are these the stock of patients coming out of the rates "xyz continue Treatment"? (below). I think the language needs to be kept consistent across, or maybe this is something that is obvious to clinicians that isn't to me?

Along those lines, why does the slider and rate dial use different language for Starters Who Return Later/Continue Treatment? Isn't this just "Starters Who Return" (without the "Later" from the table)?
![image](https://user-images.githubusercontent.com/31089501/62177003-36a61b80-b2f8-11e9-9895-4a6b2e156a8e.png)

FYI: @holbrooa @saveth above changes may require changes in ModelParams and tt reports.

**Comment by jessfroe** [comment]
> @lzim , @jessfroe -- How about this for the pop-up in PSY Session 6 (right?) video, first time we reveal the team data table:
> _Your Team Data Table might look a bit different: We've re-organized the table to clarify which data apply to patients first 3 months in care and all their time after their first 3 months._

@TomRust I do like this option to draw their attention to the different table. Maybe we can make it a bit more positive as we did for the MM/CC pop-up?

"We've upgraded the Team Data Table" instead of "it might look different"?

**Comment by lzim** [comment]
@jamesmrollins 

I'm getting some interesting formatting in Chrome with the new column format.
It isn't responsive when I adjust my windows...It's fixed like that.
![formatting_chrome](https://user-images.githubusercontent.com/7454688/62846377-bcc14b00-bc84-11e9-9ab4-28f3d585e506.png)

@staceypark Are you able to just very briefly run through your recommendations above that have not yet been addressed during the workgroup leads meeting tomorrow AM? ☕️

**Comment by jamesmrollins** [comment]
@lzim was able to replicate the screen you show above. It is an "in-between" resolution.  So, to get it to format a little better, you can try a few things.  First you can reduce the percentage of zoom in your browser, or continue to shrink your window if you have it in less-than-full-screen mode.

**Comment by jamesmrollins** [comment]
@lzim, @TomRust @branscombj @staceypark @holbrooa @saveth 

Below are the resolutions we support.  @lzim if you could tell me your VA laptop screen resolution, it will confirm if we are within any of the tiers below.  
    3200 X nnnn
    1920 X nnnn
    1680 X nnnn
    1440 X nnnn
    1360 X nnnn
    1280 X nnnn
    1024 (tablets) X nnnn
    768 (tablets) X nnnn
    Mobiles

Here is a concept that will hopefully support our various resolutions:

![image](https://user-images.githubusercontent.com/30132017/63113809-3472cc80-bf48-11e9-931e-b562c7ea4394.png)

**Comment by staceypark** [comment]
@jamesmrollins 
1. RVI should be spelled out as Return-to-clinic Visit Interval
2. Increase the font size of the chart titles

**Comment by jamesmrollins** [comment]
@hirenp-waferwire the responsive design, unfortunately, was not robust enough to maintain the alignment of row headers with associated data (see item 1 below).  We determined it is likely because the aspect ratio is not optimum for DEV.  Therefore, we have changed the aspect ratio to support a stacked listing of tables that should size better (see item 2 below). I will send an updated EPS file of the art board in a separate email.

Also note the label changes in Median Engagement Duration, now Engagement Duration and Return to Clinic Visit Interval, now hyphenated, Return-to-clinic Visit Interval.  This hyphenation will occur in all cases where the label or term is presented in the SIM UI.  See item 3 for other locations.

**1.** 
![image](https://user-images.githubusercontent.com/30132017/63130891-c262ad80-bf70-11e9-82a5-9f0bb652e078.png)

**2.**
![image](https://user-images.githubusercontent.com/30132017/63130954-eb833e00-bf70-11e9-8308-9bdec89bd3e5.png)

**3.**
Team Data Table "i" Information
![image](https://user-images.githubusercontent.com/30132017/63131286-fdb1ac00-bf71-11e9-9707-fb826aec9056.png)

Change in RVI of Patient's Past 3 Months Slider "i" Information
![image](https://user-images.githubusercontent.com/30132017/63131419-89c3d380-bf72-11e9-86a6-700b7b7bb3ed.png)

**Comment by lzim** [comment]
@staceypark @jamesmrollins @jessfroe 

Do we leave this issue in done until the documentation is complete?  Will that be the workflow?
Very soon, of course, we want to produce the documentation while new features are in TEST, so that everything is released at once the 1) documentation for training, and 2) release to PROD.

Just want to make sure the workflow is clear. Let me know if this needs **Workgroup Leads** meeting time to clarify. Or, is it covered in the revised SOP?

**Comment by saveth** [comment]
Per our Support Workgroup meeting this morning, @jamesmrollins do you want to close this issue since it's now cross-referenced in the document tracker and I've created issue #595 to track my dependencies on this issue?
