### ISSUE TITLE
MM/CC: Remove Priority Switch Icon from Sim UI Model Diagram

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#456]
**ORIGINATOR**
*Please follow the steps below to open an issue for the MTL Workgroups to address. Be sure to provide a descriptive title for the issue when saving.*

**Step 1** - Please assign this issue to the issue_tracker, under the “Projects” menu on the right side of your GitHub page.

**Step 2** - Please answer the questions below by placing a lowercase "x" between the applicable brackets below and providing brief narratives and screenshots where appropriate:

1. Is this issue a problem, such as a malfunction in the simulation, an error in documentation or similar concern, or is this a new idea
   we should consider?
   
   - [x] Problem 
   - [ ] New idea
   
2. What team are you on (exg., Menlo Park, Team Blue)?

3. How urgent is this issue?

   - [ ] Urgent - *should be addressed right away!*
   - [x] Non-urgent - *can be prioritized within normal workstreams.*

4. In the space provided below, please describe the information or behavior you expected from the product or otherwise describe what you expected to see or hear. 

The "Priority" switch and causal arrow from Team Data to Start Rate should be removed, since Learning Mode happens before sim runs to equilibrium.

5. Please provide a screenshot of the bug, if possible.  Make as many screenshots as you like that would be helpful to illustrate the issue.

   *<< Paste screenshots here>>*

![image](https://user-images.githubusercontent.com/30132017/61193452-48d55800-a670-11e9-888b-b868b1e35d7b.png)

6.  Within which product did you notice the problem? *Check all that apply*

**Data Products**

   - [ ] SharePoint
   - [ ] Data/Queries
   - [ ] Team Data
   - [ ] R-reports
   
**Instructional Products**
  
   - [ ] See Guide
   - [ ] Say Guide
   - [ ] Videos
   - [ ] Post tests
   - [ ] Fidelity Checklist
   - [ ] Cheatsheets
   - [ ] Other?  Please describe here >>
   
**Simulations**
   
   Home
   - [ ] Login 
   - [ ] Session
   - [ ] Experiment Maintenance Tile
   - [ ] Team Data Menu Maintenance
   - [ ] Chat
   - [ ] Help
   - [ ] Facilitator Dashboard
   
   Care Coordination
   - [x] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Medication Management
   - [x] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Psychotherapy
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Aggregate 
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Suicide Prevention
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
7. What kind of device are you using?
   - [ ] Tablet
   - [ ] Smartphone
   - [ ] PC

8. What browser were you using?
   - [ ] Chrome  *What version?*
   - [ ] Edge    *What version?*
   - [ ] Safari  *What version?*

**<< If you are highlighting a new idea, please continue >>**

9. Please describe your idea below.  Feel free to provide a scan or screen capture of a sketch of your idea.

10. Why is this idea important, in terms of your work?

11. How is this idea related to a problem you face in your daily practice?

12. Is there a deadline or other scheduled constraint driving your request that we should be aware of? *This will help us to prioritize this request.*

**THANK YOU!!**

---------------------------------------------------------------------------------------------------------------------------------------
**STOP HERE. INFORMATION BELOW IS TO BE FILLED OUT BY WORKGROUPS AS PART OF TRIAGE AND WORK BREAKDOWN PROCESS**
---------------------------------------------------------------------------------------------------------------------------------------

**Executive Summary**

*Estimated person-hours to complete:*

*Estimated date for completion:*

*Lead team for effort:* 

*Key people (use @ assignment for people whose input will be necessary):*
@jamesmrollins 
@TomRust (Co-i)
@jessfroe (video)

**Step 1 - Complete the Interdependencies Table**

Workgroup Leads review information provided by originator and collaborate to identify interdependencies. Then they describe modifications that are needed in the appropriate column and estimate hours needed to make changes:
 
● *Workgroup Products* - This column identifies the workgroups and the products for which they are responsible. This column can be
  modified by a workgroup lead on an ad-hoc basis to add one-time products or can be modified to include new and enduring products.
  
● *Dependency?* - This column is used by the workgroup leads during collaboration to identify the existence of an interdependency.

● *Description of Change or Action Needed* - Workgroup leads briefly describe the change required.

● *Hours* - Workgroup leads estimate the person-hours required to complete the task.

Workgroup Products        | Dependency?  | Description of Change Needed               |  Hours Estimate
------------------------- | -------------|--------------------------------------------|-----------------
**Documentation**            
Brochures                 |              |                                            |
MTL See Guide             |    Y          |      <<please describe and estimate>>                                      |
MTL Say Guide             |      Y        |   <<please describe and estimate>>                                         |
MTL Videos                |      Y        |                                            |
Post Test                 |              |                                            |
**Investigators**         |              |                                            |
Presentation              |              |                                            |
Quarterly Report          |              |                                            |
Annual Report             |              |                                            |
**Qualitative**           |              |                                            |
MTL Fidelity Checklists   |              |                                            |
Systems Thinking Codebook |              |                                            |
CFIR Codebooks            |              |                                            | 
**Quantitative**          |              |                                            |
Data UI                   |              |                                            |
Data Queries              |              |                                            |
SharePoint                |              |                                            |
Excel Outputs             |              |                                            |
ModelParameters           |              |                                            |
tt Reports                |              |                                            |
**Model**
CC                        |              |                                            |
MM                        |              |                                            |
PSY                       |              |                                            |
AGG                       |              |                                            |
SP                        |              |                                            |
**Sim User Interface**    |              |                                            |
Model Diagram             |       Y       |               Remove graphical features     |  4
"i"Information            |              |                                            |
Experiments               |              |                                            |
Outputs/Charts            |              |                                            |
Exports                   |              |                                            |
Master Crosswalk Table    |              |                                            |

**Step 2 - Identify Constraints that may affect the team’s ability to complete the necessary actions.** 

Describe the constraint in terms of capability, capacity or affect on grant research goals. If there are no constraints identified, then leave the table blank.

●  Type - The type of constraint identifies one or more resource areas that are affected.  

●  Workgroup - this is the workgroup responsible for developing a new or modifying an existing product.

●  Discussion/recommendation - A brief narrative that expands the information regardingthe constraint and ideally a recommendation for
   overcoming the constraint.

**Type Constraint (check all that apply) / Workgroup(s) Affected / Discussion/Recommendation**

- [ ] Capacity      
- [ ] Cost         
- [ ] Schedule     
- [ ] Interference 
- [ ] Capability   
- [ ] Other (describe)

**Step 3 - Identify supported milestones.** *Affix the milestone at the issue level using available GitHub milestones.*

**Step 4 - Indicate the due date for completing the actions identified above, assuming constraints are removed.**

**Step 5 - Identify the lead workgroup for the action (check one):**

- [x] Documentation
- [ ] Investigators
- [ ] Quantitative
- [ ] Qualitative
- [ ] Model
- [ ] Sim UI

**Step 6 - Go to the top of this section and complete Executive Summary information**

Note to Workgroups:  Use the issue thread to document further discussion, alternatives development and estimates.  However, be sure to update this form if dates, team responsibility or other information changes.

**Comment by jamesmrollins** [comment]
@jessfroe @TomRust there are likely dependencies with video and see-say guides. These changes may be way more substantial than what I have to do.  I am going to put this into development, but we need to estimate your portions of this.  I also recommend that one of you be the lead for this, my part is relatively minor.  I will report when this is ready to move to PROD.  Thanks, James

**Comment by jamesmrollins** [comment]
@hirenp-waferwire  please modify the model diagrams in CC and MM to remove the graphics as shown. Leave this card in the development queue, but notify me via this thread that this change is available for review in TEST.  Thanks, James

![image](https://user-images.githubusercontent.com/30132017/61243382-ae6f2600-a6fc-11e9-8eba-b6538f2c1d89.png)

**Comment by jessfroe** [comment]
@jamesmrollins Hi James, I'm happy to attempt to run point on this, though I'll likely still need guidance from @TomRust. 
I am continuing work on the videos so I will look out for any major dependencies/needs.

**Comment by TomRust** [comment]
![image](https://user-images.githubusercontent.com/32961420/61545468-8d1c7b80-aa15-11e9-8383-71fc068c3725.png)
looks great!

**Comment by staceypark** [comment]
@jamesmrollins there's no guide, gif or cheatsheet dependency on this. 
@jessfroe this may affect videos.
I believe it can be moved to PROD. 

FYI: @dlounsbu @branscombj @lzim @TomRust @dlkibbe

**Comment by jamesmrollins** [comment]
Thanks @staceypark .  

@hirenp-waferwire, please promote to PROD.
