### ISSUE TITLE
authorship_app: add calendar to shiny app

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#458]
Savet,

We are interested in managing the timeline of Team PSD manuscripts through a calendar function in our Team PSD Shiny authorship app. Like this, but linked to the authorship app functions: http://www.roymfrancis.com/calendar-plot-shiny-app-and-dynamic-ui/

1. Is this issue a problem, such as a malfunction in the simulation, an error in documentation or similar concern, or is this a new idea
   we should consider?
   
   - [ ] Problem 
   - [x] New idea
   
2. What team are you on (exg., Menlo Park, Team Blue)?
n/a

3. How urgent is this issue?

   - [ ] Urgent - *should be addressed right away!*
   - [x] Non-urgent - *can be prioritized within normal workstreams.*
*Ideally would be incorporated in the authorship app work that we are prioritizing now.

4. In the space provided below, please describe the information or behavior you expected from the product or otherwise describe what you expected to see or hear. 

Features for the authorship app:
It would be great to be able to assign and track progress across manuscripts, not just to decide up front who will be the authors. But, once assigned to use dates to track who is doing what, when the next hand off to another co-authors will occur, etc.

- This would include some sort of calendar function: https://meet.lucidmeetings.com/meeting/221026/send_followup

- This may also include some sort of GANTT chart, not sure...

5. Please provide a screenshot of the bug, if possible.  Make as many screenshots as you like that would be helpful to illustrate the issue.

Not a bug :bug:

6.  Within which product did you notice the problem? *Check all that apply*

**Data Products**

- Not a product, this is our "sciencing" 🔬 

   - [ ] SharePoint
   - [ ] Data/Queries
   - [ ] Team Data
   - [ ] R-reports
   
**Instructional Products**
  
   - [ ] See Guide
   - [ ] Say Guide
   - [ ] Videos
   - [ ] Post tests
   - [ ] Fidelity Checklist
   - [ ] Cheatsheets
   - [ ] Other?  Please describe here >>
   
**Simulations**
   
   Home
   - [ ] Login 
   - [ ] Session
   - [ ] Experiment Maintenance Tile
   - [ ] Team Data Menu Maintenance
   - [ ] Chat
   - [ ] Help
   - [ ] Facilitator Dashboard
   
   Care Coordination
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Medication Management
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Psychotherapy
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Aggregate 
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Suicide Prevention
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
7. What kind of device are you using?
   - [ ] Tablet
   - [ ] Smartphone
   - [ ] PC

8. What browser were you using?
   - [ ] Chrome  *What version?*
   - [ ] Edge    *What version?*
   - [ ] Safari  *What version?*

**<< If you are highlighting a new idea, please continue >>**

9. Please describe your idea below.  Feel free to provide a scan or screen capture of a sketch of your idea.

Please read the details above about tracking the "when" of who is doing what when on manuscripts.

10. Why is this idea important, in terms of your work?

We are trying to get the Team PSD Authorship App up and running ASAP, but we'd like to be able to track progress over time, and to assign to do dates. 

- We can use other platforms, but it DOES make a lot of sense to have it be integrated with the authorship app.

11. How is this idea related to a problem you face in your daily practice?

See above.

12. Is there a deadline or other scheduled constraint driving your request that we should be aware of? *This will help us to prioritize
    this request.*

- It would be great to include this update (e.g., a prototype) at the Tuesday 8/13 Manuscript meeting.

**THANK YOU!!**

---------------------------------------------------------------------------------------------------------------------------------------
**STOP HERE. INFORMATION BELOW IS TO BE FILLED OUT BY WORKGROUPS AS PART OF TRIAGE AND WORK BREAKDOWN PROCESS**
---------------------------------------------------------------------------------------------------------------------------------------

**Executive Summary**

*Estimated person-hours to complete:*

*Estimated date for completion:*

*Lead team for effort:*

*Key people (use @ assignment for people whose input will be necessary):*

**Step 1 - Complete the Interdependencies Table**

Workgroup Leads review information provided by originator and collaborate to identify interdependencies. Then they describe modifications that are needed in the appropriate column and estimate hours needed to make changes:
 
● *Workgroup Products* - This column identifies the workgroups and the products for which they are responsible. This column can be
  modified by a workgroup lead on an ad-hoc basis to add one-time products or can be modified to include new and enduring products.
  
● *Dependency?* - This column is used by the workgroup leads during collaboration to identify the existence of an interdependency.

● *Description of Change or Action Needed* - Workgroup leads briefly describe the change required.

● *Hours* - Workgroup leads estimate the person-hours required to complete the task.

Workgroup Products        | Dependency?  | Description of Change Needed               |  Hours Estimate
------------------------- | -------------|--------------------------------------------|-----------------
**Documentation**            
Brochures                 |              |                                            |
MTL See Guide             |              |                                            |
MTL Say Guide             |              |                                            |
MTL Videos                |              |                                            |
Post Test                 |              |                                            |
**Investigators**         |              |                                            |
Presentation              |              |                                            |
Quarterly Report          |              |                                            |
Annual Report             |              |                                            |
**Qualitative**           |              |                                            |
MTL Fidelity Checklists   |              |                                            |
Systems Thinking Codebook |              |                                            |
CFIR Codebooks            |              |                                            | 
**Quantitative**          |              |                                            |
Data UI                   |              |                                            |
Data Queries              |              |                                            |
SharePoint                |              |                                            |
Excel Outputs             |              |                                            |
ModelParameters           |              |                                            |
tt Reports                |              |                                            |
**Model**
CC                        |              |                                            |
MM                        |              |                                            |
PSY                       |              |                                            |
AGG                       |              |                                            |
SP                        |              |                                            |
**Sim User Interface**    |              |                                            |
Model Diagram             |              |                                            |
"i"Information            |              |                                            |
Experiments               |              |                                            |
Outputs/Charts            |              |                                            |
Exports                   |              |                                            |
Master Crosswalk Table    |              |                                            |

**Step 2 - Identify Constraints that may affect the team’s ability to complete the necessary actions.** 

Describe the constraint in terms of capability, capacity or affect on grant research goals. If there are no constraints identified, then leave the table blank.

●  Type - The type of constraint identifies one or more resource areas that are affected.  

●  Workgroup - this is the workgroup responsible for developing a new or modifying an existing product.

●  Discussion/recommendation - A brief narrative that expands the information regardingthe constraint and ideally a recommendation for
   overcoming the constraint.

**Type Constraint (check all that apply) / Workgroup(s) Affected / Discussion/Recommendation**

- [ ] Capacity      
- [ ] Cost         
- [ ] Schedule     
- [ ] Interference 
- [ ] Capability   
- [ ] Other (describe)

**Step 3 - Identify supported milestones.** *Affix the milestone at the issue level using available GitHub milestones.*

**Step 4 - Indicate the due date for completing the actions identified above, assuming constraints are removed.**

**Step 5 - Identify the lead workgroup for the action (check one):**

- [ ] Documentation
- [ ] Investigators
- [ ] Quantitative
- [ ] Qualitative
- [ ] Model
- [ ] Sim UI

**Step 6 - Go to the top of this section and complete Executive Summary information**

Note to Workgroups:  Use the issue thread to document further discussion, alternatives development and estimates.  However, be sure to update this form if dates, team responsibility or other information changes.

**Comment by saveth** [comment]
@jessfroe @staceypark @lzim After reviewing the resources provided and considering the intent outlined in item 4 above, I do not think adding a calendar to the Authorship app would address the intent stated in item 4.

I can integrate a calendar that would allow users to add the different sections of the manuscript into the calendar for that session and the selected manuscript. However, the current app only allows user to select contributors, eligibility, and allocation of points for each manuscript in a given session for each user. It does not allow users to enter information for multiple manuscripts at once and store the information on the back end. That is why any information a user enters has to be exported in a session to save and track their work.

If we're looking for a way to track who is working on what part of each manuscript and when across all the manuscripts, then I would recommend MS Project. You can create:
1) a project for each manuscript with all of the tasks/subtasks, and
2) a master project that pulls all the manuscript projects into one document to see overlap, etc.

**Comment by jessfroe** [comment]
@saveth just wanted to touch base regarding this issue and what we had discussed in person to document all our discussion.
I agree that perhaps the calendar function in the authorship app may not address all of the functions we need it to address. Right now, here are the functions I think we need/want:
1. Which manuscript it is
2. The corresponding authors assigned to the manuscript
3. The percent the manuscript is completed
4. All sections or tasks associated with the manuscript
5. Who is currently working on it/who is working on it next
6. Approximate date to complete and finalize the manuscript

I'm not sure if @lzim and @staceypark agree with these points. I understand that the shiny authorship app only allows us to view one manuscript at a time which doesn't quite work for what we would want to utilize the manuscript tracker for. 
Thoughts?

**Comment by jessfroe** [comment]
@saveth just another point, it seems like it would be best to use an existing platform to manage the manuscripts.

**Comment by staceypark** [comment]
@jessfroe Thanks for writing up those points. I think those are a good start for what we want.

@saveth To underscore at @jessfroe point below and per our conversation about this, as a reminder we don't want to use MS Project for this. The learning curve and management is too high to use just to manage the manuscripts. We definitely want to use an existing platform, which may or may not be the authorship app depending on Shiny's capabilities. 

> @saveth just another point, it seems like it would be best to use an existing platform to manage the manuscripts.

We welcome any other ideas and expertise you have about on managing this with our existing platforms! 😃 
FYI: @lzim

**Comment by saveth** [comment]
@jessfroe @staceypark Thank you for outlining the points of what you're looking for.  I'm happy to continue to look into ways to developing another ShinyApp that would enable us to upload exports from #425 to centralize all the data entered by the team.

@lzim expressed that HQ is primarily looking for a way to manage all the different manuscripts, tasks, and people, not necessarily having everyone on the team putting their hands into the pot on this. In which case, of all the tools we have at our current disposal, MS Project is the program that we have that meets all the requirements outlined by @jessfroe above. I'm concerned that it would not be an efficient use of time, resources, and money for me to essentially figure out how to build a free version of something like MS Project. (By the way, I'm not a software programmer, so the learning curve and time to develop something of the sort will probably be longer than you expect). 

I'll continue to develop some sort of gantt to be embedded into #425 for @lzim review and approval for the manuscript meetings. Then return to this issue of developing another app to help HQ manage all the manuscripts.

**Comment by staceypark** [comment]
@saveth As we discussed before with @jessfroe, yes HQ will be primarily responsible for the management but everyone needs to be able to contribute/view/understand whichever solution we use. The team won't be able to use MS Project to even view the document without downloading it at the very basic level.
> @lzim expressed that HQ is primarily looking for a way to manage all the different manuscripts, tasks, and people, not necessarily having everyone on the team putting their hands into the pot on this.

**Comment by jessfroe** [comment]
@lzim can we close this issue now, because we created the manuscript_tracker kanban?

**Comment by staceypark** [comment]
@jessfroe let’s just go ahead and close issues when we think they are done. We can always reopen them later if needed.
