### ISSUE TITLE
authorship_app 

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#459]
Bug related to timeout server connection is preventing testing of authorship app: Related to issue https://github.com/lzim/teampsd/issues/425

1. Is this issue a problem, such as a malfunction in the simulation, an error in documentation or similar concern, or is this a new idea
   we should consider?
   
   - [x] Problem 
   - [ ] New idea
   
2. What team are you on (exg., Menlo Park, Team Blue)?

3. How urgent is this issue?

   - [] Urgent - *should be addressed right away!*
   - [x] Non-urgent - *can be prioritized within normal workstreams.*
*Somewhat urgent as this is necessary to complete testing.

4. In the space provided below, please describe the information or behavior you expected from the product or otherwise describe what you expected to see or hear. 

Server connection issue - see screenshot below

5. Please provide a screenshot of the bug, if possible.  Make as many screenshots as you like that would be helpful to illustrate the issue.

![image](https://user-images.githubusercontent.com/7454688/61254699-44657980-a71a-11e9-83b2-f95c6aba33e2.png)

6.  Within which product did you notice the problem? *Check all that apply*

**Data Products**

   - [ ] SharePoint
   - [ ] Data/Queries
   - [ ] Team Data
   - [ ] R-reports
   
**Instructional Products**
  
   - [ ] See Guide
   - [ ] Say Guide
   - [ ] Videos
   - [ ] Post tests
   - [ ] Fidelity Checklist
   - [ ] Cheatsheets
   - [ ] Other?  Please describe here >>
   
**Simulations**
   
   Home
   - [ ] Login 
   - [ ] Session
   - [ ] Experiment Maintenance Tile
   - [ ] Team Data Menu Maintenance
   - [ ] Chat
   - [ ] Help
   - [ ] Facilitator Dashboard
   
   Care Coordination
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Medication Management
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Psychotherapy
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Aggregate 
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Suicide Prevention
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
7. What kind of device are you using?
   - [ ] Tablet
   - [ ] Smartphone
   - [X] PC

8. What browser were you using?
   - [X] Chrome  *What version?*
   - [ ] Edge    *What version?*
   - [ ] Safari  *What version?*

**<< If you are highlighting a new idea, please continue >>**

9. Please describe your idea below.  Feel free to provide a scan or screen capture of a sketch of your idea.

10. Why is this idea important, in terms of your work?

11. How is this idea related to a problem you face in your daily practice?

12. Is there a deadline or other scheduled constraint driving your request that we should be aware of? *This will help us to prioritize
    this request.*

**THANK YOU!!**

---------------------------------------------------------------------------------------------------------------------------------------
**STOP HERE. INFORMATION BELOW IS TO BE FILLED OUT BY WORKGROUPS AS PART OF TRIAGE AND WORK BREAKDOWN PROCESS**
---------------------------------------------------------------------------------------------------------------------------------------

**Executive Summary**

*Estimated person-hours to complete:*

*Estimated date for completion:*

*Lead team for effort:*

*Key people (use @ assignment for people whose input will be necessary):*

**Step 1 - Complete the Interdependencies Table**

Workgroup Leads review information provided by originator and collaborate to identify interdependencies. Then they describe modifications that are needed in the appropriate column and estimate hours needed to make changes:
 
● *Workgroup Products* - This column identifies the workgroups and the products for which they are responsible. This column can be
  modified by a workgroup lead on an ad-hoc basis to add one-time products or can be modified to include new and enduring products.
  
● *Dependency?* - This column is used by the workgroup leads during collaboration to identify the existence of an interdependency.

● *Description of Change or Action Needed* - Workgroup leads briefly describe the change required.

● *Hours* - Workgroup leads estimate the person-hours required to complete the task.

Workgroup Products        | Dependency?  | Description of Change Needed               |  Hours Estimate
------------------------- | -------------|--------------------------------------------|-----------------
**Documentation**            
Brochures                 |              |                                            |
MTL See Guide             |              |                                            |
MTL Say Guide             |              |                                            |
MTL Videos                |              |                                            |
Post Test                 |              |                                            |
**Investigators**         |              |                                            |
Presentation              |              |                                            |
Quarterly Report          |              |                                            |
Annual Report             |              |                                            |
**Qualitative**           |              |                                            |
MTL Fidelity Checklists   |              |                                            |
Systems Thinking Codebook |              |                                            |
CFIR Codebooks            |              |                                            | 
**Quantitative**          |              |                                            |
Data UI                   |              |                                            |
Data Queries              |              |                                            |
SharePoint                |              |                                            |
Excel Outputs             |              |                                            |
ModelParameters           |              |                                            |
tt Reports                |              |                                            |
**Model**
CC                        |              |                                            |
MM                        |              |                                            |
PSY                       |              |                                            |
AGG                       |              |                                            |
SP                        |              |                                            |
**Sim User Interface**    |              |                                            |
Model Diagram             |              |                                            |
"i"Information            |              |                                            |
Experiments               |              |                                            |
Outputs/Charts            |              |                                            |
Exports                   |              |                                            |
Master Crosswalk Table    |              |                                            |

**Step 2 - Identify Constraints that may affect the team’s ability to complete the necessary actions.** 

Describe the constraint in terms of capability, capacity or affect on grant research goals. If there are no constraints identified, then leave the table blank.

●  Type - The type of constraint identifies one or more resource areas that are affected.  

●  Workgroup - this is the workgroup responsible for developing a new or modifying an existing product.

●  Discussion/recommendation - A brief narrative that expands the information regardingthe constraint and ideally a recommendation for
   overcoming the constraint.

**Type Constraint (check all that apply) / Workgroup(s) Affected / Discussion/Recommendation**

- [ ] Capacity      
- [ ] Cost         
- [ ] Schedule     
- [ ] Interference 
- [ ] Capability   
- [ ] Other (describe)

**Step 3 - Identify supported milestones.** *Affix the milestone at the issue level using available GitHub milestones.*

**Step 4 - Indicate the due date for completing the actions identified above, assuming constraints are removed.**

**Step 5 - Identify the lead workgroup for the action (check one):**

- [ ] Documentation
- [ ] Investigators
- [ ] Quantitative
- [ ] Qualitative
- [ ] Model
- [ ] Sim UI

**Step 6 - Go to the top of this section and complete Executive Summary information**

Note to Workgroups:  Use the issue thread to document further discussion, alternatives development and estimates.  However, be sure to update this form if dates, team responsibility or other information changes.

**Comment by lzim** [comment]
@saveth 

Note: this is happening when we try to advance to the score tab.

**Comment by saveth** [comment]
I pushed an updated version of Authorship Scorecard and it seems to solved the problem.
