### ISSUE TITLE
DUI generating team data

### ISSUE THREAD

**Issue by dlounsbu** [lzim/teampsd#468]
**ORIGINATOR**
*Please follow the steps below to open an issue for the MTL Workgroups to address. Be sure to provide a descriptive title for the issue when saving.*

**Step 1** - Please assign this issue to the issue_tracker, under the “Projects” menu on the right side of your GitHub page.

**Step 2** - Please answer the questions below by placing a lowercase "x" between the applicable brackets below and providing brief narratives and screenshots where appropriate:

1. Is this issue a problem, such as a malfunction in the simulation, an error in documentation or similar concern, or is this a new idea
   we should consider?
   
   - [x] Problem 
   - [ ] New idea
   
2. What team are you on (exg., Menlo Park, Team Blue)?
Team 2 Co-Facilitation Practice

3. How urgent is this issue?

   - [ ] Urgent - *should be addressed right away!* 
   - [x] Non-urgent - *can be prioritized within normal workstreams.*

4. In the space provided below, please describe the information or behavior you expected from the product or otherwise describe what you expected to see or hear. 

Today after my intersession prep with Dr. Theresa M. Schmitz, I tried to generate team data. As expected the hour glass came up and then, after a few minutes, I got a Basic run time error. 

I was trying to see if I could successfully generate new parameters for ALL modules, including SP (Stepped Care). 

I would like to know, also, when you do this, the new parameter estimates will be stored in the SUI Excel file and SUI folder AND, also, that they would update the zero values in the DUE Excel file. 

5. Please provide a screenshot of the bug, if possible.  Make as many screenshots as you like that would be helpful to illustrate the issue.

   *<< Paste screenshots here>>*
![image](https://user-images.githubusercontent.com/20574023/62252789-d24f8e80-b3c1-11e9-9c9a-5007493189ac.png)

6.  Within which product did you notice the problem? *Check all that apply*

**Data Products**

   - [ ] SharePoint
   - [ ] Data/Queries
   - [x] Team Data
   - [ ] R-reports
   
**Instructional Products**
  
   - [ ] See Guide
   - [ ] Say Guide
   - [ ] Videos
   - [ ] Post tests
   - [ ] Fidelity Checklist
   - [ ] Cheatsheets
   - [ ] Other?  Please describe here >>
   
**Simulations**
   
   Home
   - [ ] Login 
   - [ ] Session
   - [ ] Experiment Maintenance Tile
   - [x] Team Data Menu Maintenance
   - [ ] Chat
   - [ ] Help
   - [ ] Facilitator Dashboard
   
   Care Coordination
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Medication Management
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Psychotherapy
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Aggregate 
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Suicide Prevention
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
7. What kind of device are you using?
   - [ ] Tablet
   - [ ] Smartphone
   - [x] PC my laptop

8. What browser were you using?
   - [ ] Chrome  *What version?*
   - [x] Explorer 11  *What version?*
   - [ ] Safari  *What version?*

**<< If you are highlighting a new idea, please continue >>**

9. Please describe your idea below.  Feel free to provide a scan or screen capture of a sketch of your idea.

10. Why is this idea important, in terms of your work?

I am concerned that this will happen during a session.

11. How is this idea related to a problem you face in your daily practice?

I need to feel confident that the DUI works well and will not stop when I run team data.

12. Is there a deadline or other scheduled constraint driving your request that we should be aware of? *This will help us to prioritize
    this request.*

I would like to have some reply by Friday, prior to our practice co-facilitation session. 

**THANK YOU!!**

---------------------------------------------------------------------------------------------------------------------------------------
**STOP HERE. INFORMATION BELOW IS TO BE FILLED OUT BY WORKGROUPS AS PART OF TRIAGE AND WORK BREAKDOWN PROCESS**
---------------------------------------------------------------------------------------------------------------------------------------

**Executive Summary**

*Estimated person-hours to complete:*

*Estimated date for completion:*

*Lead team for effort:*

*Key people (use @ assignment for people whose input will be necessary):*

**Step 1 - Complete the Interdependencies Table**

Workgroup Leads review information provided by originator and collaborate to identify interdependencies. Then they describe modifications that are needed in the appropriate column and estimate hours needed to make changes:
 
● *Workgroup Products* - This column identifies the workgroups and the products for which they are responsible. This column can be
  modified by a workgroup lead on an ad-hoc basis to add one-time products or can be modified to include new and enduring products.
  
● *Dependency?* - This column is used by the workgroup leads during collaboration to identify the existence of an interdependency.

● *Description of Change or Action Needed* - Workgroup leads briefly describe the change required.

● *Hours* - Workgroup leads estimate the person-hours required to complete the task.

Workgroup Products        | Dependency?  | Description of Change Needed               |  Hours Estimate
------------------------- | -------------|--------------------------------------------|-----------------
**Documentation**            
Brochures                 |              |                                            |
MTL See Guide             |              |                                            |
MTL Say Guide             |              |                                            |
MTL Videos                |              |                                            |
Post Test                 |              |                                            |
**Investigators**         |              |                                            |
Presentation              |              |                                            |
Quarterly Report          |              |                                            |
Annual Report             |              |                                            |
**Qualitative**           |              |                                            |
MTL Fidelity Checklists   |              |                                            |
Systems Thinking Codebook |              |                                            |
CFIR Codebooks            |              |                                            | 
**Quantitative**          |              |                                            |
Data UI                   |              |                                            |
Data Queries              |              |                                            |
SharePoint                |              |                                            |
Excel Outputs             |              |                                            |
ModelParameters           |              |                                            |
tt Reports                |              |                                            |
**Model**
CC                        |              |                                            |
MM                        |              |                                            |
PSY                       |              |                                            |
AGG                       |              |                                            |
SP                        |              |                                            |
**Sim User Interface**    |              |                                            |
Model Diagram             |              |                                            |
"i"Information            |              |                                            |
Experiments               |              |                                            |
Outputs/Charts            |              |                                            |
Exports                   |              |                                            |
Master Crosswalk Table    |              |                                            |

**Step 2 - Identify Constraints that may affect the team’s ability to complete the necessary actions.** 

Describe the constraint in terms of capability, capacity or affect on grant research goals. If there are no constraints identified, then leave the table blank.

●  Type - The type of constraint identifies one or more resource areas that are affected.  

●  Workgroup - this is the workgroup responsible for developing a new or modifying an existing product.

●  Discussion/recommendation - A brief narrative that expands the information regardingthe constraint and ideally a recommendation for
   overcoming the constraint.

**Type Constraint (check all that apply) / Workgroup(s) Affected / Discussion/Recommendation**

- [ ] Capacity      
- [ ] Cost         
- [ ] Schedule     
- [ ] Interference 
- [ ] Capability   
- [ ] Other (describe)

**Step 3 - Identify supported milestones.** *Affix the milestone at the issue level using available GitHub milestones.*

**Step 4 - Indicate the due date for completing the actions identified above, assuming constraints are removed.**

**Step 5 - Identify the lead workgroup for the action (check one):**

- [ ] Documentation
- [ ] Investigators
- [ ] Quantitative
- [ ] Qualitative
- [ ] Model
- [ ] Sim UI

**Step 6 - Go to the top of this section and complete Executive Summary information**

Note to Workgroups:  Use the issue thread to document further discussion, alternatives development and estimates.  However, be sure to update this form if dates, team responsibility or other information changes.

**Comment by dlounsbu** [comment]
@theresaschmitz 

I noticed that there were parms estimates in the Sim UI data folder! So, maybe we need to call up that file for our practice session on Friday. 

As I noted in the issue, I tried to generate new team data, but a bug in the Excel process appeared to abort my request. 

@holbrooa , when one 'Gets Team Data for the Sim Models,' will the Parms Tabs in the current DUI workbook be updated? Or will this just create a the SUI folder file?

**Comment by holbrooa** [comment]
Yeah, it gets updated in both places. I'm trying to recreate the error you got. If I can't, I'll ask you to help by doing what you just did again, but this time hitting that debug button.

**Comment by dlounsbu** [comment]
Thanks for this information. Okay, I will try to recreate now. And I will push debug button this time.

**Comment by holbrooa** [comment]
Thanks David! After you hit debug, you should see a screen with code on it, and a line highlighted. Take a screenshot of that, and then you can go ahead and close the whole thing.

**Comment by dlounsbu** [comment]
@holbrooa @theresaschmitz 

As soon as I tried to open the Excel file for editing, I got the bug report.

![image](https://user-images.githubusercontent.com/20574023/62311166-3c674280-b459-11e9-8765-c6a196e1e07b.png)

**Comment by theresaschmitz** [comment]
Thanks David. Hopefully that will work!

**Comment by dlounsbu** [comment]
Just tried to Get Team Data again, for my Team 2 practice, and got a bug.

![image](https://user-images.githubusercontent.com/20574023/62392546-b53bcc80-b535-11e9-82b0-b6da91f55321.png)

**Comment by holbrooa** [comment]
@dlounsbu 
Ah, I see. That's the same issue I worked through yesterday afternoon with Stacey. So either, open up the latest data UI where the bug is fixed (in teamPSD > quant_workgroup > final_datafiles) or if you just close the file for a second, I can fix the bug in the version you're working with.

**Comment by dlounsbu** [comment]
I see. So, I as using an old version of the DUI. I did not know that. When will your new improved version be moved to the mtl.how?

David

**Comment by holbrooa** [comment]
I moved this to done on the issue tracker, because the bug has been squashed in the latest version of the data UI. But I will also create a folder on mtl.how/data for a copy of the latest version to live, for those who can't get to our final_datafiles folder.
