### ISSUE TITLE
8/8 Documentation for the two data UI buttons

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#469]
**ORIGINATOR**
*Please follow the steps below to open an issue for the MTL Workgroups to address. Be sure to provide a descriptive title for the issue when saving.*

**Step 1** - Please assign this issue to the issue_tracker, under the “Projects” menu on the right side of your GitHub page.

**Step 2** - Please answer the questions below by placing a lowercase "x" between the applicable brackets below and providing brief narratives and screenshots where appropriate:

1. Is this issue a problem, such as a malfunction in the simulation, an error in documentation or similar concern, or is this a new idea
   we should consider?
   
   - [x] Problem 
   - [ ] New idea  

3. How urgent is this issue?

   - [x] Urgent - *should be addressed right away!*
   - [ ] Non-urgent - *can be prioritized within normal workstreams.*

4. In the space provided below, please describe the information or behavior you expected from the product or otherwise describe what you expected to see or hear. 

We need updated documentation on the actions leading up to (i.e. filtering and selecting clinics, choosing the GMH/SMH team in SP Transfers, etc., ability to 1, all, or all w/o SP params) and the actions that result from (i.e. 0's in the parameters files, how clinic selection tab doesn't show you which clinics were selected but rather the last filtered clinic, how hitting the Team Data Table Sim UI button updates both the data UI params tabs & creates a new params file) using the "Get Patient Level Data" and "Team Data Table Sim UI" buttons.

6.  Within which product did you notice the problem? *Check all that apply*
**Data Products**
   - [ ] SharePoint
   - [x] Data/Queries
   - [x] Team Data
   - [ ] R-reports
   
**Instructional Products**
  
   - [x] See Guide @branscombj @dlkibbe 
   - [x] Say Guide @branscombj @dlkibbe 
   - [x] Videos @jessfroe 
   - [ ] Post tests
   - [ ] Fidelity Checklist
   - [x] Cheatsheets - data UI cheatsheet & sim UI cheatsheet updates by @staceypark afterwards 
   - [ ] Other?  Please describe here >>

12. Is there a deadline or other scheduled constraint driving your request that we should be aware of? *This will help us to prioritize this request.*
The facilitators missed learning this for Session 3 last week and we want to orient & update them when we next meet. Most folks are out this week so I believe we want all of our materials, including cheatsheets, session guides, etc. ready for facilitators by Monday 8/12.

**THANK YOU!!**

---------------------------------------------------------------------------------------------------------------------------------------
**STOP HERE. INFORMATION BELOW IS TO BE FILLED OUT BY WORKGROUPS AS PART OF TRIAGE AND WORK BREAKDOWN PROCESS**
---------------------------------------------------------------------------------------------------------------------------------------

**Executive Summary**

*Estimated person-hours to complete:*

*Estimated date for completion:*

*Lead team for effort:*

*Key people (use @ assignment for people whose input will be necessary):*

**Step 1 - Complete the Interdependencies Table**

Workgroup Leads review information provided by originator and collaborate to identify interdependencies. Then they describe modifications that are needed in the appropriate column and estimate hours needed to make changes:
 
● *Workgroup Products* - This column identifies the workgroups and the products for which they are responsible. This column can be
  modified by a workgroup lead on an ad-hoc basis to add one-time products or can be modified to include new and enduring products.
  
● *Dependency?* - This column is used by the workgroup leads during collaboration to identify the existence of an interdependency.

● *Description of Change or Action Needed* - Workgroup leads briefly describe the change required.

● *Hours* - Workgroup leads estimate the person-hours required to complete the task.

Workgroup Products        | Dependency?  | Description of Change Needed               |  Hours Estimate
------------------------- | -------------|--------------------------------------------|-----------------
**Documentation**            
Brochures                 |              |                                            |
MTL See Guide             |              |                                            |
MTL Say Guide             |              |                                            |
MTL Videos                |              |                                            |
Post Test                 |              |                                            |
**Investigators**         |              |                                            |
Presentation              |              |                                            |
Quarterly Report          |              |                                            |
Annual Report             |              |                                            |
**Qualitative**           |              |                                            |
MTL Fidelity Checklists   |              |                                            |
Systems Thinking Codebook |              |                                            |
CFIR Codebooks            |              |                                            | 
**Quantitative**          |              |                                            |
Data UI                   |              |                                            |
Data Queries              |              |                                            |
SharePoint                |              |                                            |
Excel Outputs             |              |                                            |
ModelParameters           |              |                                            |
tt Reports                |              |                                            |
**Model**
CC                        |              |                                            |
MM                        |              |                                            |
PSY                       |              |                                            |
AGG                       |              |                                            |
SP                        |              |                                            |
**Sim User Interface**    |              |                                            |
Model Diagram             |              |                                            |
"i"Information            |              |                                            |
Experiments               |              |                                            |
Outputs/Charts            |              |                                            |
Exports                   |              |                                            |
Master Crosswalk Table    |              |                                            |

**Step 2 - Identify Constraints that may affect the team’s ability to complete the necessary actions.** 

Describe the constraint in terms of capability, capacity or affect on grant research goals. If there are no constraints identified, then leave the table blank.

●  Type - The type of constraint identifies one or more resource areas that are affected.  

●  Workgroup - this is the workgroup responsible for developing a new or modifying an existing product.

●  Discussion/recommendation - A brief narrative that expands the information regardingthe constraint and ideally a recommendation for
   overcoming the constraint.

**Type Constraint (check all that apply) / Workgroup(s) Affected / Discussion/Recommendation**

- [ ] Capacity      
- [ ] Cost         
- [ ] Schedule     
- [ ] Interference 
- [ ] Capability   
- [ ] Other (describe)

**Step 3 - Identify supported milestones.** *Affix the milestone at the issue level using available GitHub milestones.*

**Step 4 - Indicate the due date for completing the actions identified above, assuming constraints are removed.**

**Step 5 - Identify the lead workgroup for the action (check one):**

- [ ] Documentation
- [ ] Investigators
- [ ] Quantitative
- [ ] Qualitative
- [ ] Model
- [ ] Sim UI

**Step 6 - Go to the top of this section and complete Executive Summary information**

Note to Workgroups:  Use the issue thread to document further discussion, alternatives development and estimates.  However, be sure to update this form if dates, team responsibility or other information changes.

**Comment by holbrooa** [comment]
This is the existing instruction box for how to use the Clinic Selection tab: 
"Add clinics to the box below to define the data pull for your team. To add a clinic, double click a clinic name from column C of the spreadsheet or use the add all button on the right to add all clinics from the filtered list. Double click clinics from the list below to remove them. If you select multiple clinics from column C, the Add All button will change to an Add Selection button which will add the selected clinics."

Seems okay to me, and it's had a few rounds of Lindsey's wordsmithing at this point. But there's no mention there of the two new buttons. They're pretty self-explanatory, I thought. They say:
"Get previous clinic list from last click of Get Patient-level Data" and "Get previous clinic list from Create Team Data Table for Sim UI file named [file name here]" and they do exactly what they say: they fetch the clinic list that was last used for each button.

So that's the two new buttons.  For the drop down, the meaning seems clear - you're either picking an individual module or all with or without SP. The problem there is that we have to always output every tab, even if you've only generated parameters for one module. And when you generate parameters, they stay in the data UI you're using (and then the parameter tabs just get copied out with the file name you chose) so there's a danger of giving you parameters from a different set of clinics.  And if you upload that file, there is then no way to know that those parameters are for a different set.  So, we decided the tool should output 0s for any module you don't have selected.  That way, you get 0s and it's clear that you didn't run that module's parameter pull instead of mystery numbers and a moment of "wait, did I run this, or are these old parameters?"

**Comment by branscombj** [comment]
> 
> So, we decided the tool should output 0s for any module you don't have selected. That way, you get 0s and it's clear that you didn't run that module's parameter pull instead of mystery numbers and a moment of "wait, did I run this, or are these old parameters?"

Could we have a note under the new buttons that says, "Choosing only the module parameters you think you'll use will shorten the time it takes to generate the output file. In that file, you will still see parameters tabs for all modules; but parameter values for modules not selected will all read as zeros."

**Comment by holbrooa** [comment]
The master data UI will have 0s for all parameter sheets. When a team grabs a copy of the file and uses it for their team, the "Create Team Data Table" button will both populate the parameter sheets in that Data UI file and create the copy of those sheets that can be uploaded to run simulations. That means it is a good idea to save the Data UI file after running the queries - that will maintain the new  parameter sheets in the Data UI itself, as well as the list in the "Get previous clinic list..." button.

Also, we're going to add the drop-down selection to the filename, e.g. "640_ATS_MM_2019_08_12" The "ATS" is the user-supplied team name, and the rest is automatically populated by the tool - so it's [automatic sta3n]_[whatever the user types]_[automatic drop-down selection]_[automatic date].

**Comment by holbrooa** [comment]
Note when I say master data UI, I mean the blank one that will be propagated to each facility that I refer to in https://github.com/lzim/teampsd/issues/474  so I'll try to maintain any decisions here that are relevant to that idea on that thread.

**Comment by staceypark** [comment]
@staceypark @branscombj @dlkibbe add documentation on how on issue in data UI where the data is blacked out

**Comment by lzim** [comment]
@staceypark 

Need instructions on how to toggle to fix this issue:

![image](https://user-images.githubusercontent.com/7454688/62881145-ecec0680-bce3-11e9-99ae-7797db39c98b.png)

**Comment by holbrooa** [comment]
In order to fix the black grid list, just select a different tab and then come back. That should fix it.

**Comment by staceypark** [comment]
how about:
 "Choosing only single modules will shorten the time it takes to generate the team data sim UI file. Parameter values for modules not selected will all read as zeroes."

**Comment by branscombj** [comment]
> "Choosing only single modules will shorten the time it takes to generate the team data sim

That is very clear to me!

**Comment by lzim** [comment]
@staceypark

Yes it’s clear, although I prefer “reduce” to “shorten.”
