### ISSUE TITLE
Need Psy and Pharm omnibus tweener denominators due Monday morning 8/12

### ISSUE THREAD

**Issue by holbrooa** [lzim/teampsd#470]
New research feature. Need to accommodate for site selection (copied from site selection meeting https://meet.lucidmeetings.com/lucid/meeting/221416):
What we need: 

1. Omnibus EBP Reach (with and without AUD) - we have this now

2. Omnibus EBPsy Reach (with and without AUD)

3. Omnibus EBPharm Reach (with and without AUD)

4. PTSD EBP Reach - we have this now

5. Depression EBP Reach - we have this now

6. AUD EBP Reach - we have this now

7. OUD EBP Reach - we have this now

EBP Denominators (Omnibus: All of them; Disaggregated to EBPsy and EBPharm; Disaggregated for each Diagnostic Cohort)

1. PTSD EBP Reach Initiate Denominator**(has only EBPsy)

2. Dep EBP Reach Initiate Denominator **(has both EBPsy and EBPharm)

3. OUD EBP Reach Initiate Denominator**(has only EBPharm)

4. AUD EBP Reach Initiate Denominator**(has  both EBPsy and EBPharm)

We have 1 from the first list and 4-7. 2 and 3 are what we still need. Will need 4 new columns for comparator: 

1. Psy omnibus with AUD
2. Psy omnibus without AUD
3. Pharm omnibus with AUD
4. Pharm omnibus without AUD.

**Executive Summary**

*Estimated person-hours to complete:*
8 combined person- and server-hours.
*Estimated date for completion:*
8/15 site selection meeting
*Lead team for effort:*
Quant
*Key people (use @ assignment for people whose input will be necessary):*
@holbrooa @saveth 

**Step 1 - Complete the Interdependencies Table**

Workgroup Leads review information provided by originator and collaborate to identify interdependencies. Then they describe modifications that are needed in the appropriate column and estimate hours needed to make changes:
 
● *Workgroup Products* - This column identifies the workgroups and the products for which they are responsible. This column can be
  modified by a workgroup lead on an ad-hoc basis to add one-time products or can be modified to include new and enduring products.
  
● *Dependency?* - This column is used by the workgroup leads during collaboration to identify the existence of an interdependency.

● *Description of Change or Action Needed* - Workgroup leads briefly describe the change required.

● *Hours* - Workgroup leads estimate the person-hours required to complete the task.

Workgroup Products        | Dependency?  | Description of Change Needed               |  Hours Estimate
------------------------- | -------------|--------------------------------------------|-----------------
**Documentation**            
Brochures                 |              |                                            |
MTL See Guide             |              |                                            |
MTL Say Guide             |              |                                            |
MTL Videos                |              |                                            |
Post Test                 |              |                                            |
**Investigators**         |              |                                            |
Presentation              |              |                                            |
Quarterly Report          |              |                                            |
Annual Report             |              |                                            |
**Qualitative**           |              |                                            |
MTL Fidelity Checklists   |              |                                            |
Systems Thinking Codebook |              |                                            |
CFIR Codebooks            |              |                                            | 
**Quantitative**          |              |                                            |
Data UI                   |              |                                            |
Data Queries              |              |                                            |
SharePoint                |              |                                            |
Excel Outputs             |              |                                            |
ModelParameters           |              |                                            |
tt Reports                |              |                                            |
**Model**
CC                        |              |                                            |
MM                        |              |                                            |
PSY                       |              |                                            |
AGG                       |              |                                            |
SP                        |              |                                            |
**Sim User Interface**    |              |                                            |
Model Diagram             |              |                                            |
"i"Information            |              |                                            |
Experiments               |              |                                            |
Outputs/Charts            |              |                                            |
Exports                   |              |                                            |
Master Crosswalk Table    |              |                                            |

**Step 2 - Identify Constraints that may affect the team’s ability to complete the necessary actions.** 

Describe the constraint in terms of capability, capacity or affect on grant research goals. If there are no constraints identified, then leave the table blank.

●  Type - The type of constraint identifies one or more resource areas that are affected.  

●  Workgroup - this is the workgroup responsible for developing a new or modifying an existing product.

●  Discussion/recommendation - A brief narrative that expands the information regardingthe constraint and ideally a recommendation for
   overcoming the constraint.

**Type Constraint (check all that apply) / Workgroup(s) Affected / Discussion/Recommendation**

- [ ] Capacity      
- [ ] Cost         
- [ ] Schedule     
- [ ] Interference 
- [ ] Capability   
- [ ] Other (describe)

**Step 3 - Identify supported milestones.** *Affix the milestone at the issue level using available GitHub milestones.*

**Step 4 - Indicate the due date for completing the actions identified above, assuming constraints are removed.**

**Step 5 - Identify the lead workgroup for the action (check one):**

- [ ] Documentation
- [ ] Investigators
- [ ] Quantitative
- [ ] Qualitative
- [ ] Model
- [ ] Sim UI

**Step 6 - Go to the top of this section and complete Executive Summary information**

Note to Workgroups:  Use the issue thread to document further discussion, alternatives development and estimates.  However, be sure to update this form if dates, team responsibility or other information changes.

**Comment by holbrooa** [comment]
@saveth I generated a new file with the 4 new columns. Will you please go check it out?

**Comment by saveth** [comment]
@holbrooa Thanks!

**Comment by saveth** [comment]
@holbrooa @lzim Andrew, we discussed in the meeting yesterday of validating AUD and OUD to see if it had the same issue of depression and if we need to do a similar data pull to SAIL for our AUD and OUD initiate. We definitely need a similar definition for OUD. Right now our OUD reach is at 100% for some clinic, which does not seem right.

**Comment by holbrooa** [comment]
I went and checked the code this morning, and I am doing the same logic for all the patients who get a prescription. Which is to say, each diagnostic cohort includes patients who get a visit or a relevant prescription, just like depression.

**Comment by saveth** [comment]
@holbrooa Thanks for double checking. @lzim thinks it's correct that some of these clinics will get 100% reach for OUD as that's a priority for many sites.

**Comment by holbrooa** [comment]
Okay, that is what I thought. Whew.

Now I can get the word "omnitweenominators" out of my head.
