### ISSUE TITLE
MTL.how video review schedule!

### ISSUE THREAD

**Issue by jessfroe** [lzim/teampsd#471]
Hi all!

I'm starting this thread to get the ball rolling on the final review of the MTL.how videos. There are 36 videos total, and they all need a set of trained eyes to ensure we aren't missing any new pop-ups, changes to the DataUI and SimUI information, etc. I have done a first pass on quite a few, but the bulk of them still need additional review. 
S01 - S04: 1 video each, 4 videos total

S05 - S10: 5 videos each (Agg, Psy, MM, CC, SP), 30 videos total

S11 & S12: 1 video each, 2 videos total

- I'd like to get a basic understanding of the kind of time each team member has to dedicate to reviewing the videos. Each video takes roughly 40 minutes for me (probably because I am pausing multiple times) so that is a safe bet for the allotment of time needed for each video. 

- I'd also like to know what module or session you feel most comfortable reviewing, or which you are most intimately familiar with. 

**If you could please give me an estimate of hours/week you can dedicate to video review, as well as modules and sessions you can review, that would greatly help me with creating a review schedule for everyone.**

Thank you!

**Comment by dlkibbe** [comment]
@jessfroe I will look at 1-4 before next Wednesday. Sorry, I know we talked about a "review method" or checklist while reviewing, are you using a formal video review tool?

**Comment by jessfroe** [comment]
@dlkibbe I wasn't using a specific checklist, though that would be greatly beneficial to have. I can try to come up with something in the next few days. 
Would it be useful to use the same OSF project to help track the schedule and any changes that need to be made?

**Comment by jessfroe** [comment]
**Working checklist for video review:**
[ ] Check for typos in current pop-up graphics 
[ ] Intro and outro chime/MTL animation and "Test. Don't Guess.", module and session information at the beginning of each video
[ ] Dependencies with changes in the Data UI/Sim UI --> what is necessary to resolve this inconsistency? What sort of explanation is necessary to help minimize confusion for learners? (example of this is the Learning Mode pop-up for CC/MM when users first log in to their world, variable name changes)
[ ] Missing pop-ups - for example, should a pause graphic be included for consistency across a video, does the web address need to be provided, should keyboard shortcuts be explicitly mentioned etc. 

- We should decide if we want certain pop-ups to be included consistently across videos. For example, most videos have a pop-up at the very beginning with "mtl.how" and information on where to access the learner SEE guide, but not all do. Same thing with "Ctrl + C" or other keyboard shortcuts. Should we make sure each video has these types of pop-ups where relevant?    

- Please add to this checklist as you see fit. This is based on my minimal understanding of what could potentially be found in the videos. 😃

**Comment by dlkibbe** [comment]
you're the best @jessfroe - thank you for this. I agree with bullet number 1 above - the mtl.how pop up  reinforces the brand and the keystrokes and other reminders help the learner remain engaged. One other item that might be added to the checklist is if there are errors in the words said by a facilitator that require an "oops, we meant to say..." pop-up

**Comment by lzim** [comment]
@jessfroe @dlkibbe @branscombj @staceypark 

Jessilyn, let me know if you need any time on this checklist at our meeting tomorrow.
I believe that it is generally good, but may also want to integrate some elements of the other **document_tracker** columns, such as the links to relevant issues. Only this case, it should refer perhaps to the relevant SEE card in the **detail_learner** column.

Does that make sense?

**Comment by jessfroe** [comment]
@lzim yes, I'll close this issue and reference video review in the respective document_tracker cards. 

FYI @branscombj @dlkibbe @TomRust
