### ISSUE TITLE
8/14 GH labels proposal

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#477]
Current list of labels on GH:
1. bug
2. code_review
3. decision_made
4. dev
5. documentation
6. facilitate_workgroup
7. for_fun
8. guide
9. help_resource
10. help_wanted
11. model
12. need_decision
13. new_feature
14. new_release
15. non_urgent
16. originator_followup_needed
17. qual
18. quant
19. question
20. research
21. sim_ui
22. tt_report
23. urgent

Proposed set of labels & rules governing label creation:
a. Short: No more than 3-5 chars (including underscores) so that the label name doesn't get cut off.
b. Unique: No subproducts of larger workgroups (i.e. no tt_report label, just quant label).
c. Necessary: Make sure the label serves a purpose for alerting a workgroup or for sorting priorities (i.e. all the items in the issue tracker are bugs so no need for bug label). 

1. dev
2. doc
3. fac
4. grant
5. guide
6. hq
7. model
8. pi (to alert @lzim that PI action is necessary; potential to replace PIR)
9. pubs
10. qual
11. quant
12. sim
13. urgent
14. wl (workgroup leads)

**Comment by branscombj** [comment]
@staceypark Looks good to me!

**Comment by jamesmrollins** [comment]
@staceypark This looks good to me.  However, I have a few questions/comments:

1.  Originator follow up needed - is this replaced with "wl?"  If not, what is the usage policy for the "wl" label?
2.  Has the usage policy for "grant" changed?
3.  Agree with dropping the PIR kanban. 

_And not on topic, but related - recommend the following changes for the Kanban Issue Management System section:_

1. issue_tracker - Add a usage policy for the "closed" queue.
2. feature_tracker - Add a usage policy for the "closed" queue

**Comment by staceypark** [comment]
@jamesmrollins 
originator followup
 - No, this is not replaced by WL. I took this out because in my experience, the label itself doesn't do anything since the issue responder still needs to write out their specific questions to the originator. And they would know that it needs a response since they would get pingged.
- The "wl" tag would be used to signal an issue to workgroup leads only - i.e. this very issue on GH labels, I would have used a wl tag.

grant label
- I'm not sure what you mean this question? The label didn't exist, and I think we should have one to signal grant related items.

pir kanban
- Ok great. @lzim can you/we go ahead and close the pir kanban? also @lzim can we go ahead and close the other kanbans that aren't the issue, feature, manuscript, and team? It has been creating some confusion amongst the team.

**_related:_**
"closed" queue policy - I've been updating the policy document to reflect our new policy that - 
done = issue responder is done working on the task.
closed = issue originator officially closes the GH issue b/c they feel that their needs have been fully addressed.
proposal: why don't we call the kanban columns "done by responder" and "closed by originator"?

**Comment by staceypark** [comment]
@saveth @dlounsbu @holbrooa @lzim @TomRust please weigh in before end of day 8/14

**Comment by jessfroe** [comment]
@staceypark these look great! No comments/questions from me.

**Comment by saveth** [comment]
I agree that we should reduce the number of labels and close down all the projects that aren't in use. I'm fine with the proposed new labels.

**Comment by staceypark** [comment]
Collapsed into #478 - Revised GH Issue template. Refer there for latest info.
