### ISSUE TITLE
8/20 master rqda project

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#482]
include:
1. 3 codebooks - fidelity rqda, systems_thinking, cfir
2. attributes
3. cases
4. 80% clean testing data set

fidelity rqda codes w/ likert scale:
1. - clear_engagement
2. - partner_for_change 
3. - transparency 
4. - local_control 
5. - shared_understanding 
6. - team_priority 
7. - build_capacities_strengths 
8. - consensus_building 
9. - shared_decisionmaking 
10. - local_synergy 
11. - workable_solutions

once finished, send qual team path in TeamPSD folder to find these items. Post to 8/20 qual lucid meeting agenda.

**Comment by dlounsbu** [comment]
@jessfroe @swapmush @teampsdkathryn 

I know the Jesslyn is setting up the updated RQDA code books, data sets, etc. 

Is the plan to set these up a master copy in the qual workgroup folder on TeamPSD? 

I would like to start (or restart) my coding work on TeamPSD. Currently, I have a working version of RQDA on my local drive, with de-identified data for analyses. It seems that it may be more convenient to work a dedicated subfolder on TeamPSD. I think there  were some connectivity issues prior, which is way I was working with my locally installed version of RQDA.

**Comment by staceypark** [comment]
@dlounsbu @jessfroe @swapmush @teampsdkathryn 
Yes, there's a master copy for the training and testing data set in the qual workgroup folder in TeamPSD.
I've also uploaded them here: https://github.com/lzim/teampsd/tree/master/qual_workgroup/projects

The projects have their respective deidentified files with all the codes set up (systems thinking, fidelity, cfir, qhfd, team/facilitator) as well as the attributes (session number), cases (deidentified team number), and files categories (code initials).
