### ISSUE TITLE
 Migrate MTL Menu to VA RedCap

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#483]
We are currently using Stanford REDCap for the mtl.how/menu.
However, not all of our facilitators have SUNET ID's so this poses and access issue.
VA also has a REDCap but we need to investigate it's functionalities.

In the VA REDCap, we also need to see how to have the menu results disaggregate by team, as currently each team needs a separate project in REDCap.

**Comment by staceypark** [comment]
*tt report code for mtl.how/menu may need to change with this change.

**Comment by jessfroe** [comment]
Here is info I've found so far according to various presentations found on the VA website:
- VA REDcap reached full functionality in 2018
- Use of VA REDcap is free to all VA employees, even WOC appointments 
- Survey respondents must be logged into an active VA network to complete a VA REDcap survey 

Preliminary understanding is that switching to VA REDcap should not pose any particular difficulties. Seems fairly straightforward.

**Comment by lzim** [comment]
Great! Thanks @jessfroe

So, let’s migrate at least one instance of mtl.how/menu to VA RedCap now. I can update the MTL branded link once this is done. And, we can make sure everyone can access the results.

But, let’s also set up the  first question to prompt a “version” of the menu, by which I mean they select their team, and the results are aggregated to include that single team. 

Of course, it will be the SAME menu for everyone, but I’m confident RedCap will have Logic where you can answer a promp question and it will keep that data together on the backend.

Notes: We also have other RedCap programming needs:

1. Partner, Build and Apply Fidelity ratings for each session
2. The R21 pre-, mid- and final evaluation. 

We’ll want both of these in the next 12 weeks. 1 for ro1_iir_launch and the other for R21 wrap-up

**Comment by jessfroe** [comment]
@lzim To loop you in to the conversation I had with Team 2 during co-facilitation practice today, the fidelity rating items are still quite unclear for folks. 
I was hoping that, when we orient the team to the VA REDCap link for the fidelity ratings next week, we can further discuss the questions in the way you have done before in qual, clearly linking the questions to mechanism of change across the projects. 
What do you think about that plan? 
FYI @staceypark

**Comment by lzim** [comment]
> @lzim To loop you in to the conversation I had with Team 2 during co-facilitation practice today, the fidelity rating items are still quite unclear for folks.
> I was hoping that, when we orient the team to the VA REDCap link for the fidelity ratings next week, we can further discuss the questions in the way you have done before in qual, clearly linking the questions to mechanism of change across the projects.
> What do you think about that plan?
> FYI @staceypark

Yes, @jessfroe we definitely can! Thanks for the heads up and tracking this.
- Perhaps you could let me know the nature of the questions?
- And, this is probably a **meta_detail** #601 part of the guide that @TomRust and I can produce.

**Comment by staceypark** [comment]
@jessfroe I think the remaining issue on this is to migrate the MTL menu from Stanford to VA Redcap. Would you be able to work on that? We would need to format it in the same way the Facilitator Fidelity ratings worked - everyone goes to same link and series of surveys that lead them to their team's specific MTL menu survey.

lmk if you have any questions.

**Comment by jessfroe** [comment]
@staceypark I'm happy to work on this starting next week. I won't be working from the office much today and tomorrow, and I can't access VA RedCap from my computer. Shouldn't take long, though.

**Comment by ritahitching** [comment]
@lijenn  I assigned myself to this task. thanks

**Comment by ritahitching** [comment]
@staceypark I just checked my Stanford RedCap, and I no longer have access to MTL project. Any ideas? thanks

**Comment by lzim** [comment]
#hq @staceypark @lijenn @ritahitching 
Please cross-ref #1162 Thanks!

**Comment by ritahitching** [comment]
@lijenn 
I already have VA RedCap and Stanford RedCap accounts.

@staceypark 
Please add me as a user to the MTL projects on Stanford's RedCap (no need to be in Citrix to access Stanford'd RedCap thankfully!) so that  I can migrate MTL.how/menu to the VA RedCap.  My Stanford SUNetID is **hitching**. 

From what I understand @lzim is wanting to wrap up  all the RedCap stuff by COB today.

#1162

**Comment by ritahitching** [comment]
1. Move instrument in **Modeling to Learn** Project in Stanford RedCap to VA RedCap.
2. Created new project in VA RedCap called **Modeling to Learn Menu**
3. Grant access to project to TeamPSD core team

**Comment by ritahitching** [comment]
@staceypark @lzim @lijenn good morning 😄 

1. The projects and instruments previously in Stanford RedCap are not in VA Redcap ready for review.
2. They appear exactly as they were in Stanford RedCap - I uploaded the Data Dictionary - no manual coding to avoid errors. 
3.  have not made any modification or imported any data. 
4. Please confirm we do not want to keep any of the prior data in Stanford's RedCap.
5. You should all have received invitations to both projects. 
6. Please let me know if you didn't receive the invite.

**Remaining Issues**

1. Please let me know if any modifications to the instruments are needed., and I can update accordingly
2. Only the core HQ members have access to the projects.  Should @anthonycpichardo @anazariz be added?
3. The QIICs do not have access to the VA RedCap projects as yet.  
4. Any guidance on my question above about moving the new projects to production?
5. The MTL.how/menu short-link takes users to Stanford RedCap and needs updating to reflect the changes.
6. I mentioned in issue #886 - that the MTL.how/menu does not specify that users will need to be within the VA intranet to access VA RedCap.  Should this be adde to the instructions page?

**Comment by staceypark** [comment]
@ritahitching 
Per our conversation Friday:
1. There is only one MTL project we need to move, which is called Modeling to Learn Menu (TAS MTL Live) 
2. This isn't the final form. We are just using this instrument for the initial move as it has the correct set of questions for the Menu.
3. Any language tailored toward the "TAS" should be removed as this is for our MTL Learners.

Thanks for trying to track the requirements in the issue. Let's open up the issue card together next time, to make sure we're all on the same page 😄 

@lijenn can you make these edits, since I believe you are doing the review concurrent with the redcap check.

Re: Dev to Prod mode question.
We'll move to production once these are finalized. We haven't added any of the teams yet, so we can't add these to prod.

**Comment by staceypark** [comment]
For REDCap documentation:
1.  I know we are working on a map on how to create REDCap project
2. Makes sense that we would want a REDCap review process checklist
3. @ritahitching @lijenn Can someone clarify what the purpose of this third markdown cheatsheet is?

> @lijenn start draft check list of how to review a RedCap process (use MTL.how/menu as example) and @ritahitching will review and create a markdown cheatsheet.

**Comment by ritahitching** [comment]
@staceypark @lijenn 

- [ ] Please review the RedCap map on how to create a project, I created it's in LucidChart. 

from @staceypark 
I know we are working on a map on how to create REDCap project

- [ ] The 'cheatsheet' is the check list  on how to review a RedCap project

from @staceypark 
Makes sense that we would want a REDCap review process checklist
@ritahitching @lijenn Can someone clarify what the purpose of this third markdown cheatsheet is?

**Comment by lijenn** [comment]
@ritahitching @staceypark I am making the edits needed on MTL Menu. 
- [ ] Removed TAS in the project name
- [ ] Enabled as survey to add TeamPSD Style (i.e logo)

 #1286 is the issue card for the Checklist task. I will post my draft there by noon. 
I think we should stick to using the term "Checklist" instead of "Cheatsheet" since a cheatsheet would include more visuals like screenshots and not have any check boxes like a checklist would.

**Comment by staceypark** [comment]
@ritahitching @lijenn 
It sounds like the "cheatsheet" and "checklist" are the same piece of work? and not two different things?

> I think we should stick to using the term "Checklist" instead of "Cheatsheet" since a cheatsheet would include more visuals like screenshots and not have any check boxes like a checklist would.

Yes, a cheatsheet and checklist are two different things. It sounds like in this case, we are making a checklist (a list of items with checkboxes to review when double checking a REDCap project) not a cheatsheet (a guide with screenshots and steps on the REDCap platform).

It's important to stick to language consistent with our SOP so we're all on the same page! 😄

**Comment by ritahitching** [comment]
I am closing this issue as MTL Menu (MTL Live) is in VA RedCap and the instrument has been check by @lijenn
