### ISSUE TITLE
9/4 Ensure diagnosis information on splash pages is using primary diagnosis only. (august update)

### ISSUE THREAD

**Issue by holbrooa** [lzim/teampsd#486]
Executive summary:

On the next splash page update, ensure the diagnosis data is using primary diagnosis only, as discussed at https://meet.lucidmeetings.com/meeting/223386

After reviewing the new diagnosis combinations on the data UI, we decided to change the splash pages' diagnosis charts to being primary only (apparently users thought this is how it already was). This will require a new update and refresh - doesn't make any sense to do it in the middle of the month.

Person hours ~ 6 @holbrooa 
server hours ~ a whole bunch

**Comment by staceypark** [comment]
@holbrooa can you add updates on estimate of time left for your issues to help prioritize your work for the week?

**Comment by holbrooa** [comment]
This requires some long-running queries, so I am planning on working on it mostly at the end of my days, then letting it run into the evening. I would estimate at least a couple evenings of that. Should be good by Thursday.

**Comment by holbrooa** [comment]
Back-end upgrade is done. Propagation started last night and should finish sometime this morning. Once it's done, I'll spot check a few to make sure there's nothing glaringly wrong, and then close this issue.

**Comment by staceypark** [comment]
discussed during workgroup leads meeting and issue is ready to be closed.
