### ISSUE TITLE
Add patient cohort idea to documentation. 

### ISSUE THREAD

**Issue by holbrooa** [lzim/teampsd#487]
The patient cohort idea that is the first step in every model's data pull and is documented at the top of the DataNotes tab in the data ui needs to be highlighted somewhere, either duplicating the documentation in DataNotes or at least pointing users/facilitators to it. The idea is especially relevant for SP, because the model's data is still the user team's cohort, so any patients who take a pathway through the model that doesn't hit the user team isn't actually included in the parameter calculations. This has significant ramifications on the interpretation of model results - ask Tom.

@lzim @staceypark @TomRust @jessfroe 
Not sure about the in-flux template or project for this, so it's pretty barebones.  At least there's already a documentation tag. I'm adding it to issues for now.

**Comment by lzim** [comment]
@holbrooa @TomRust @staceypark @jessfroe 

So, this would go in the **session 2 cards** of the **document_tracker.**
One for the **detail_facilitate** column and one in the **dissemiante_scientists_va** column.
I'll link to this issue in each of those places.
