### ISSUE TITLE
EBP Reach Initiate & Dose definitions documentation: https://osf.io/z7y8m/wiki/home/

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#571]
@saveth @holbrooa 
We have a lot of operational definitions of EBP reach that need to be tracked in preparation for the 8/27 co-I meeting. Please add them here.

**Comment by saveth** [comment]
EBP Reach Initiate formula used for sampling can be found in the slide deck presented to the co-Is ( https://meet.lucidmeetings.com/meeting/224872). Additional details of the different EBP measures and covariates can be found in the OSF: https://osf.io/z7y8m/wiki/home/

That's where all the updates on the variables, definition and procedure is occurring as we iterate and clarify things.

**Comment by lzim** [comment]
@saveth @holbrooa @staceypark 

I've added the CONSORT reporting requirements that came up on Tuesday to the OSF project. We can talk about this during the quant_workgroup meeting.

https://osf.io/z7y8m/wiki/consort/

**Comment by saveth** [comment]
Here are the open dependencies:

- [ ] #462 
- [ ] #615

**Comment by lzim** [comment]
This issue cross-references seven other issues. It should have been documented on OSF adequate for use in manuscritp #559 **r01_protocol_impsci**
So, I'm closing it.
