### ISSUE TITLE
question about pull requests

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#577]
What is the difference between Reviewers and Assignees?

**Comment by staceypark** [comment]
@branscombj here's some guidance I found online that I agree with: 
For "**reviewer**": someone you want to review the code. Not necessarily the person responsible for that area or responsible for merging the commit. Can be someone who worked on that chunk of code before, as GitHub auto-suggests. **For our team, a use case could be found in updating session guides. When @branscombj creates a pull request for changes to a Session 03 guide, you may want both @dlkibbe and @holbrooa 's eyes on it, but not for them to be the final approval.**

For "**assignee**": up to the project's team/maintainer what it means and there's no strict definition. It can be the PR opener, or someone responsible for that area (who is going to accept the PR after the review is done or just close it). It's not up to GitHub to define what it is leaving it open for project maintainers what fits best for their project. **I propose we use assignee to indicate who should do the final approval, merge, & closing of the pull request.**

FYI: Workgroup leads - @lzim @dlounsbu @saveth @holbrooa @jamesmrollins @TomRust @jessfroe

**Comment by lzim** [comment]
Very helpful, thanks @branscombj!

**Comment by branscombj** [comment]
@staceypark Works for me. To summarize: 
**Reviewers** should look at the proposed changes and weigh in if they have objections or amendments. 

- It would be helpful if they left evidence that they'd reviewed if they don't have objections or amendments. 

**Assignees** should make a final call, push changes to Master, and close the pull request. 

- Should the Assignee ping everyone after they've reviewed but before they've merged changes as a "last call"?

My concern is that sometimes I know that others might have a different thought about changes I propose, and I worry that they won't see them before they get either dismissed or enacted.
