### ISSUE TITLE
Cost estimate for changing SP module name?

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#580]
**1. Add description:** 
@branscombj suggested changing the SP module full name to "Measurement Based Stepped Care **and** Suicide Prevention" instead of "Measurement Based Stepped Care **for** Suicide Prevention".

@jamesmrollins could you give us a cost estimate for this 3 letter change?

<< Paste screenshots here>>
 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by lzim** [comment]
**Morning Y'all 3 Things:**
@TomRust @dlkibbe @jessfroe @staceypark 
**1. Working with Team 2 tomorrow, please do note for the TAS that we made this language change to "AND" based on TAS feedback, and this is now in PROD**

![and_sp](https://user-images.githubusercontent.com/7454688/63947795-757cdd80-ca2c-11e9-9e5e-2acdd5fa50bc.jpg)

@branscombj @dlkibbe @tomrust @staceypark and @jessfroe 

**2. We ALL need to track this issue #580 in all our **document_tracker** cards (Describe, Detail, Document, Disseminate, Depend) from s05 through s10.** 
- Each point person for each of these columns, should add this issue to the issue checklist on their **document_tracker** session cards for their column:
- Jane & Debbie for **describe_learner**
- Lindsey & Tom for **detail_facilitator**
- Stacey for **document_team**
- Lindsey (in this case) for **disseminate_scientists_va**
- Jessilyn for **depend_products** - Check the EES brochures, however, too @branscombj and @dlkibbe 

**3. @TomRust please cross-ref issue #587 to make sure that there are no bugs in SP that have not yet been caught** 🐛

**Comment by lzim** [comment]
@staceypark @jessfroe 

This issue can be closed, when linked in each column of the **document_tracker.**

**Comment by staceypark** [comment]
linked #490 in the document_tracker which details the same issue.
