### ISSUE TITLE
Session 06 suggestions

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#581]
**HQ said they'd do the Session 6 updates for this week's demo. I have these suggestions:**
1. Delete the Purpose section - Most sessions don't have that, and the LOs should be enough about the purpose.
2. Change "Part I" and "Part II" to step level: ##1. and ##2.
3. Word step 1: Find the answers to these questions in the model diagram.
4. Delete the bullets and change 1-4 to a.-d.
5. Word step 2: Tell a systems story about the team's highest priority need
6. Delete the bullets and tip; write instructions about telling a system story in a few generic steps.

**Comment by staceypark** [comment]
@branscombj I believe these concerns & edits should all be addressed with the most recent change to the S06 guide and will close the issue.

**Comment by branscombj** [comment]
@staceypark Yep, I believe they were all considered (and overridden), so it's fine to close! 😜
