### ISSUE TITLE
8/28: SP: Control Panel Details Say "TEST" instead of Variable Details

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#583]
@jamesmrollins As the screenshot shows below today in the SP module working with data for Team 4, the expanded outputs section **Control Panel** said only TEST XXXX instead of specific team data values.

<< Paste screenshots here>>
![image](https://user-images.githubusercontent.com/7454688/63727369-f2ce0580-c814-11e9-9c6a-f46bfa7a97d0.png)

 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by staceypark** [comment]
@lzim @jessfroe Is this clear to add in the template
"For sim bugs, also include inspect console screenshots. You can navigate to the console by: Right-click in any browser > select Inspect Element > select Console."

**Comment by lzim** [comment]
> @lzim @jessfroe Is this clear to add in the template

Here are my recommended edits:

“Include Screenshot If browser inspector code by: Right-clicking in any browser > select Inspect Element > select Console."

**Comment by staceypark** [comment]
@lzim sure sounds good! I think you have to edit the template.

**Comment by lzim** [comment]
@staceypark 

Right! I meant to do that this week but, ran out of time. 

Let’s keep this open until I finish it!

**Comment by lzim** [comment]
Done. Closes #583
