### ISSUE TITLE
9/6 Sim_ui: Investigate world-team-mapping alternatives

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#588]
**1. Add description:** 
Currently, administrators must manage a world-team-mapping.xlsx spreadsheet in order to inform the team label in the sim_ui header AND the team listing in the Facilitator Dashboard drop down menu.  

**World-team-mapping**

![image](https://user-images.githubusercontent.com/30132017/63781597-d9719b80-c89e-11e9-9db3-5766a1b529ad.png)

**Facilitator Dashboard, "Select Team" drop down menu**

![image](https://user-images.githubusercontent.com/30132017/63781716-06be4980-c89f-11e9-8518-d70661080d63.png)

**Sim_ui header**

![image](https://user-images.githubusercontent.com/30132017/63781792-2a818f80-c89f-11e9-9628-499f21e7ea7c.png)

**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by jamesmrollins** [comment]
@lzim @staceypark We have figured out a way to do away with the world-team mapping.  Since we now only have one team per group/world then we can use the "events" field for the team common name, reflected in the Sim UI header.  

For the Facilitator drop down, critical for navigating through the individual group/world, we will build the drop down menu directly from the user assignment table.  

This will take 10 development hours.

Do I have your permission to proceed?

Thank you.
James

**Comment by lzim** [comment]
@jamesmrollins and @staceypark

I’m sorry, but I’m not sure I am track the experience for the 
1. **learner** 
- what Stacey and I last discussed, after selecting the world at log-in, seeing  “individual” for any individual world and “team name” for team world. Am, I right about how that world work?

and 

2. **facilitator**
- sounds like part of a drop down selection in Epicenter, but no downloading, updating, uploading world-team mapping file, is that right?

**Comment by staceypark** [comment]
@lzim from my understanding, yes to both

since we control the "event name" we can make the learner see whatever we want. 
In line with what you and I discussed I believe the decisions were to use:
1. "specific team name i.e. 640a0_mpd_team2" in the team world 
2. "Individual World" for all of the individual worlds regardless of the team.

**Comment by jamesmrollins** [comment]
@lzim and @staceypark 

Regarding 1 - Yes, the learner would see two worlds possibly, the team/world and the individual group/world.  The login drop down is created by the code scanning the user listing in Epicenter for that group.
Regarding 2 - Correct, there will no further use for the world-team-mapping for neither the label nor the Facilitator Dashboard drop down.  The Facilitator Dashboard drop down will be created by reviewing the list of assigned worlds in the x_ind group/worlds

**Comment by lzim** [comment]
> Regarding 1 - Yes, the learner would see two worlds possibly, the team group/world and the individual group/world. The login drop down is created by the code scanning the user listing in Epicenter for that group.

> Regarding 2 - Correct, there will no further use for the world-team-mapping for neither the label nor the Facilitator Dashboard drop down. The Facilitator Dashboard drop down will be created by the code reviewing the list of assigned worlds in the x_ind group/worlds

Let’s hold off until next week @staceypark, until I am clearer than this:  “Yes, the learner would see two worlds possibly, the team group/world and the individual group/world.”

My hesitation on implementation is related to the training we provide in the **depend_products** videos, and my understanding of what @staceypark described about the dependency. 

Glad there is an improvement option to address corruption, and ease on the facilitator end, however.

**Comment by lzim** [comment]
Note: I would add the **documentation** label if I could, but I don’t seem to be able to from my phone 📱

**Comment by jamesmrollins** [comment]
@lzim @staceypark Just to be clear in communication - this will simplify management of what appears in the drop down.  Currently, the Sim already presents the learner with all drop down group/worlds where they are listed as a End User.  So no change there.  What is changed, is the way we are putting the label up in the header of the Sim UI.  Instead of referring to the world-team-mapping, we are now referring to the Event Name field in the Group Edit page.

The only change will be to remove the last dependency on the world-team-mapping, which is the drop down listing in the Facilitator Dashboard.  If approved, we will now be building the drop down list from the group instances ending in _ind, from the user assignment listing.  That way the facilitator can navigate to and monitor all individuals in the _ind group/world.

This does not, necessarily, solve the world corruption problem.  It only makes it easier and faster to correct the problem.  If we have a corruption issue, I need to be notified immediately so Forio and I can freeze the server instance and investigate.

**Comment by lzim** [comment]
Thanks @jamesmrollins

> What is changed, is the way we are putting the label up in the header of the Sim UI. Instead of referring to the world-team-mapping, we are now referring to the Event Name field in the Group Edit page.

- Right, drop-down at log-in same for learner. My question is the convention for the Sim UI Nav Bar, now that it’s event name instead of team-world mapping.
- I proposed to @staceypark “Individual World” across the board for all learners in **Ind** world, and team name, as always for **Team** world.
- We emphasize the old way where individual world lists the learner’s name there in _nearly all videos_ as most instruct learner to do something in their individual world.

> building drop-down in Epicenter...
- this seems fine

> doesn’t solve, merely reduces potential for corruption
- roger

**Comment by jamesmrollins** [comment]
@lzim yes, I believe we can put the individual's name in the NAV bar with the new concept; thus, keep with what is in the training video.  Let me verify with @hirenp-waferwire.

**Comment by jamesmrollins** [comment]
@lzim I have verified with DEV that we can use pull the user's name from the multiplayer assignments listing and display it in the user's Sim UI Nav bar.  Do you want me to proceed with development?  Thank you, James

@staceypark FYSA

**Comment by lzim** [comment]
@jamesmrollins and @staceypark

Yes, if this under the hood improvement creates no learner-facing changes. Then, yes, please proceed. 🤗

**Comment by jamesmrollins** [comment]
@hirenp-waferwire we are approved to implement this change in TEST.  Thank you, James

**Comment by staceypark** [comment]
@jamesmrollins @lzim 
great that nothing changes for the learner but I will need to update the facilitate cheatsheet to **remove** the instructions on world team mapping. I've already linked this issue to the meta document card #602 to address that.

**Comment by jamesmrollins** [comment]
@staceypark since you have a card started on this, I will move this to the "done' pile.  When documentation is GTG, then we can promote to PROD.

**Comment by staceypark** [comment]
We can promote to PROD and close.
tracked in #602 for documentation.
