### ISSUE TITLE
9/5 CBOC and VAMC proportion

### ISSUE THREAD

**Issue by saveth** [lzim/teampsd#591]
**1. Add description:** 
From co-I meeting(https://meet.lucidmeetings.com/meeting/224872):

Analyze the total population of CBOC to see what proportional eligible (aka "underperforming") and also calculate from the total population of Medical Centers what proportion are eligible/underperforming.

**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by lzim** [comment]
Cross-ref #438 I'd like to add this to the Site Selection slide deck.

FYI: @saveth @holbrooa @staceypark @jessfroe

**Comment by staceypark** [comment]
@lzim @saveth I've added this to the quant meeting tomorrow. It sounded like we needed more discussion time on this.

**Comment by lzim** [comment]
> @lzim @saveth I've added this to the quant meeting tomorrow. It sounded like we needed more discussion time on this.
> 
> @saveth I moved this to under_development. It shouldn't be in work_breakdown anymore right? Please make sure to move your kanban cards along the tracker

Thanks @staceypark  This really needs to be during the site selection meeting with @saveth 
We have much to discuss, and likely won’t have enough **quant_workgroup** time on it. But, if we do have time, we can try to cover some of this ⏲

**Comment by saveth** [comment]
@lzim This information is in the current slide deck (Eligibility_pres_2019Sept_initiate_noAUD.html) as of Sept. 6, 2019 on slide 60-63.
