### ISSUE TITLE
Update tt report for Team Data Table  (tt1) - 9/6

### ISSUE THREAD

**Issue by saveth** [lzim/teampsd#595]
**1. Add description:** 
Check TeamData Tables in sim and update tt-report that are related to the following issues:

- [x] #445 
- [x] #451 
- [x] #457 

<< Paste screenshots here>>
 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by saveth** [comment]
@holbrooa @jamesmrollins I'm updating the tt report for Psy Team Data Table and I noticed a mismatch that I hope one of you could explain. I believe the sim is pulling the wrong value (it's pulling from the cell above):
![image](https://user-images.githubusercontent.com/12439059/63968838-5e9eb100-ca55-11e9-8794-f06bceed01d1.png) ![image](https://user-images.githubusercontent.com/12439059/63968897-80983380-ca55-11e9-99ed-b3592192cf9c.png)

Or should it be pulling the Median Appointment Supply, but t keep the 75th percentile label?

**Comment by saveth** [comment]
@jamesmrollins the crosswalk shows that we're using the correct label across the different platforms. @TomRust, perhaps the Vensim model is pulling the incorrect cell for the Appointment Supply (75th percentile)? It should be C36 instead of C35?

**Comment by jamesmrollins** [comment]
@TomRust @saveth @holbrooa  Yes, that is the problem.  I checked the current version of the model, Appointment Supply (75th Percentile) and it is currently mapped to C35.

**Comment by saveth** [comment]
Awesome! Thanks for checking @jamesmrollins! @TomRust can you update the Vensim for Psy to pull in Appointment Supply (75th Percentile) from the correct cell, D36? Thanks!

**Comment by jamesmrollins** [comment]
@TomRust @saveth I remapped the variable to cell c36 and uploaded an updated file to PROD.
