### ISSUE TITLE
10/4 Splashpage: For the September update, propagate a list of sta6a codes with plain English division names

### ISSUE THREAD

**Issue by holbrooa** [lzim/teampsd#597]
**1. Add description:** 

Need to be able to point people to some kind of sta6a lookup. Either in the data UI itself (unlikely because of the dependency on other documentation) or as a separate list in a folder on the splash pages. 

<< Paste screenshots here>>
 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_
8
**Edit the due date (if necessary)**

**Comment by staceypark** [comment]
@holbrooa is working on this and the updated Splashpages should be live by tomorrow morning

**Comment by staceypark** [comment]
all of the splashpages were updated. @holbrooa is going to double check no the sta6a codes list.

**Comment by staceypark** [comment]
@holbrooa will populate the sta6a codes excel spreadsheet in the master data_ui folder in everyone's splashpages with the data ui

**Comment by ritahitching** [comment]
@holbrooa were you able to update the spreadsheet with the sta6a code?

**Comment by holbrooa** [comment]
It's done! I don't have permissions to go look anymore, but if you go look in the master data UI folder in any splash page, you should see the sta6a codes there in a spreadsheet.

**Comment by staceypark** [comment]
confirmed done with spot checks to different station folders.
