### ISSUE TITLE
meta_describe

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#600]
# Meta Describe Checklist

## 1. Link to the document, add relevant team members to the card, and add workflow decisions.
- [x] Add the link the current draft of the documentation for the issue
- [x] Add all related workflow decisions here:
1. SEE guide decisions:
- Numbering and main content on the SEE guides cannot change as these are already shown in the videos.
- Only edits that address errors, typos, or content that make the learning incorrect for the learner should be made.
2.
3. 

## 2. Link to issues that must be edited in the document in the **issue_tracker** and **feature_tracker.** _(use the # for the link to the issue)_
- [x] Issue #451 
- [x] Issue #490  
- [x] Issue #577 
- [x] previously Outputs section and Expanded Outputs Section is now called **Outputs & Text Section**

## 3. Team Review
- [x] Fidelity - check with Lindsey
- [x] Data UI - check quant_workgroup
- [x] Sim UI - check with model_workgroup and/or sim_workgroup

## 4. Review and Open Pull Requests _(use the # for the link to the pull request)_
- [x] Check the draft for typos
- [x] Check or open a pull request for the document edits

## 5. Review and/or Update Graphics
- [x] Screenshots
- [x] Gifs
- [x] Logos/Icons
- [x] Links

## 6. Dependencies
- [x] Make sure that any edits you make that need to be added to **depend_product** are tracked (e.g., _MTL Video_)

## 7. Close Pull Requests
- [x] Request review and/or close open pull requests for the document

**Comment by jessfroe** [comment]
**Describe Documentation Review Schedule - SEE Guides**

|   Date   |  Session |
| - | - |
| 9/6 | S07, S05 
| 9/13 | S08, S04
| 9/20 | S09, S03
| 9/27 | S10, S02
| 10/4 | S11, S01
| 10/11 | S12

**Comment by jessfroe** [comment]
@lzim I updated the schedule table for describe, detail and depend, and populated the meta cards for each column with the same schedule. I also added the due dates to each card. 

Let me know if you were envisioning something different!

**Comment by lzim** [comment]
Thanks @jessfroe FYI: @staceypark

1. I’ve added the left hand column **training schedule** and added the weekly **disseminate** milestone tasks.

2. I’ve also edited the schedule above to reflect that we need all documentation point persons to wrap up documentation (i.e., close all cards) for all columns in the tracker to meet our **r01_iir_launch** milestone.

3. The only lag is the **depend** column, otherwise, we need all other documentation done *^_before_** training.

@jessfroe Will you please populate across the **meta** cards?

**Comment by jessfroe** [comment]
@lzim thanks! That makes perfect sense to have all that information in one place. 
@staceypark it looks like you updated all of the schedules, correct? Thank you!

**Comment by branscombj** [comment]
@staceypark Could you remind me here (in the schedule above) when on the end date these are supposed to be completed by - COB Fridays? Thanks!

**Comment by lzim** [comment]
Right @branscombj 

- COB Friday is the target for everything in the row for that date.

**Comment by staceypark** [comment]
@branscombj @dlkibbe 
Based on the timeline we sketched out at the top, we should be done with documentation for the meta_describe column (SEE guides) as of tomorrow, but we're a bit behind.

Looks like we still need to do:
S1-4 and S11-12. 

Since the MTL Facilitate training is still rolling, **please start with Session 11, then 12, followed by 1-4**.

I know there's quite a lot of video review (#604) that also needs to be done. Please let me know what the plan is for getting all of the documentation done or let me know if you need help.

**Comment by dlkibbe** [comment]
I'll get with @branscombj about see guide reviews.

**Comment by staceypark** [comment]
@branscombj Thanks for getting Session 11 & 12 SEE ready for this week!
As you are working through Sessions 1-4, just a reminder to please add your **initials & date** in the "date" section of the YAML header where we keep track of who last edited the doc.

**Comment by branscombj** [comment]
- [ ] In reviewing the see/say files, cheat sheets, etc., @dlkibbe realized there is no point at which the facilitators explain in session 2 or 3 about the 3 folders in succession to help the learner understand how they are linked and what they contain. (This goes to the COP question "What is the difference between the folders:..."). Could we add something about this to Learner SEE (red/blue) &/or Facilitator SAY (red/blue) &/or the data UI cheat sheet?

**Comment by staceypark** [comment]
@branscombj @dlkibbe @lijenn see my answer on #747
