### ISSUE TITLE
meta_detail

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#601]
# Meta Detail Checklist

## 1. Link to the document, add relevant team members to the card, and add workflow decisions.
- [ ] Add the link the current draft of the documentation for the issue
- [ ] Add all related workflow decisions here:
1.  SAY guide decisions:
- SAY guides are not meant to be read during the intersession prep or live co-facilitation session. They should be read as a "how to" guide outside of the session. These are part of the larger MTL Manual where facilitators can go for more detail.
- We will not use "lettering" for subtext (i.e. 2a, 5c, etc.) as this will make it harder to stay in sync. Instead, we will only be using bullets.

2. 1 pager decisions:
- 1 pagers will not have any numbers at all as this will make it harder to keep everything in sync.
- 1 pagers (instead of the original SAY guides) should be used during the intersession prep to write down team details and conceptualization.

## 2. Link to issues that must be edited in the document in the **issue_tracker** and **feature_tracker.** _(use the # for the link to the issue)_
- [ ] Issue #396
- [ ] Issue #451 
- [x] Issue #410 
- [x] Issue #490  
- [x] Issue #577 
- [ ] Issue #397 Facilitator dashboard training
- [ ] Theresa's recommendation for SAY guides: Add note for facilitators to bring out the "bright spot" of team's data
- [x] Issue #580 
- [x] Issue #830 - Red and Blue Icons & Links; "Episode of Care" units for SP.

## 3. Team Review
- [ ] Fidelity - check with Lindsey
- [ ] Data UI - check quant_workgroup
- [ ] Sim UI - check with model_workgroup and/or sim_workgroup

## 4. Review and Open Pull Requests _(use the # for the link to the pull request)_
- [ ] Check the draft for typos
- [ ] Check or open a pull request for the document edits

## 5. Review and/or Update Graphics
- [ ] Screenshots
- [ ] Gifs
- [ ] Logos/Icons
- [ ] Links

## 6. Dependencies
- [ ] Make sure that any edits you make that need to be added to **depend_product** are tracked (e.g., _MTL Video_)

## 7. Close Pull Requests
- [ ] Request review and/or close open pull requests for the document

**Comment by jessfroe** [comment]
**Detail Documentation Review Schedule - SAY Guides**


|   Date   |  Videos   |
| - | - |
| 9/6 | S07, S05 
| 9/13 | S08, S04
| 9/20 | S09, S03
| 9/27 | S10, S02
| 10/4 | S11, S01
| 10/11 | S12

**Comment by lzim** [comment]
@jessfroe and @staceypark

Please cross-ref issue #600 **meta_describe** and populate the combined schedule in each column.
It will be easier across the team to keep track of all the relevant weekly documentation deadlines across columns/point persons according to the Master training schedule. Thanks!

**Comment by branscombj** [comment]
@lzim @staceypark #2 of Meta Detail Checklist - since all the issues except the last one listed are now closed, can I assume that the Detail documents have all been reviewed for those?

**Comment by lzim** [comment]
@branscombj and @dlkibbe 

Jane, just becaused the issues referenced are closed, if the checkbox is not checked, then no. I would not have checked for something but forgotten to check the box on the **meta_detail** card.

But, I am concerned about a question I wanted to check on with you and alert @staceypark to before the fire alarm went off today... 🙄 

Namely, when I check the YAML headers in the SAY files at https://mtl.how/ I see that some are VERY old (i.e., from 2018). And, while I may have missed one here or there, I was definitely making a serious point of updating the SAY guide YAML headers to say "Edited by lz" with the date like you see here for **session 9** SAY: https://github.com/lzim/mtl/blob/master/blue/session09/s09_facilitator/mtl_session09_say.md
which says, "September 30, 2019 - edited by LZ"

And, I see a number of discrepancies between the **MTL** repo and the **TeamPSD** repo. For example:
- session 8 at mtl.how: https://github.com/lzim/mtl/blob/master/blue/session08/s08_facilitator/mtl_session08_say.md
which says, "September 2018"

- session 8 at TeamPSD: https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/facilitator_say/mtl_session08_say.md

I am concerned that I was editing things at **Team PSD** repo that never made it to https://mtl.how, somehow. For example, my guess would be that of the two **session 8** guides listed above, the one by Rita is the most current, and probably updated my work after I did. But, anything that still says 2018 at the header. 

- Unfortunately, we've also realized that when Stacey re-mapped the SAY guides to be nested within the **Blue** folder that is all of the **history** that we can track at https://mtl.how
- However, you can check the history to see if the edits were mine (before Rita's, for example) at the **History** button.

- In sum, I am most confident that I have reviewed guides that say I have reviewed them in the YAML header.

✅ **DECISION** We concluded that we should **_keep_** the full editing history in the YAML header to further help track these sorts of things.


FYI: @ritahitching and @lijenn

**Comment by ritahitching** [comment]
Meeting Monday Jan 27 - #ManuscriptMonday 
YAML header - You should document when you make edits, but please retain the record of prior edits.
Lucid meeting: https://meet.lucidmeetings.com/lucid/meeting/239235

**Comment by branscombj** [comment]
Facilitator Manual Table of Contents

@lzim This is a kind of meta question - I wonder if we should revisit, flesh out, and implement [this](https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/facilitation_guide/manual_toc.md):

It's a table of contents for an eventual facilitator manual that I started drafting a couple of years ago with the idea of ID'ing what I'd expect to see in a full manual if I were an MTL facilitator trainee. I feel like the QIICs could be really helpful for us getting that outline really filled out, from their fresh training experience. The purpose is twofold:

a) Be an outline of all the content we'd want, in case there's any that's not yet developed; and

b) Be a visually familiar style of outline that folks use to link to the content, so an actual facilitator manual.

**Comment by branscombj** [comment]
@staceypark @lzim Do we want to use an MTL BLUE logo instead of MTL LIVE in the guides? We are using MTL RED logo in the Red guides.
