### ISSUE TITLE
09/20: R21 RedCap Pre, Mid Post Evaluation 

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#605]
**1. **R21 RedCap Post-evaluation (Sept 2019) hq** goes with 
- R21 Booster Wrap Meetings w/tt reports (Sept 2019) facilitate_workgroup

- Described in #hqhuddle 08/31/2019 regarding **new r21_project_nce milestone**
 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by jessfroe** [comment]
@lzim just to be extra clear. I am adding the pre, mid, and post evaluations as surveys on REDCap. Are we continuing with use of VA REDCap for all REDCap projects? 
And, are these evaluations the learner completes, or the facilitators? I'm not sure I know exactly what is being referenced.

**Comment by lzim** [comment]
> @lzim just to be extra clear. I am adding the pre, mid, and post evaluations as surveys on REDCap. Are we continuing with use of VA REDCap for all REDCap projects?
> And, are these evaluations the learner completes, or the facilitators? I'm not sure I know exactly what is being referenced.

Thanks @jessfroe Right, I believe we can move over to VA RedCap for everything, unless I'm missing some reason that we shouldn't?? 
- I think it's easier to migrate and do all our work in one place, and _these are NOT research data, they are formative evaluation/QI data._

**Learners complete these evaluation forms:**
- The pre and made evaluation forms were originally completed with paper-and-pencil...we've come a long way... 🤣 
- But, we'll want to do the post-evaluation via **VA Red Cap.**

Great clarifying questions!

**Comment by ritahitching** [comment]
@jessfroe have you had a chance to put this up yet?

**Comment by jessfroe** [comment]
@ritahitching yes I believe this was all done quite a while ago. Closing the issue.

**Comment by jessfroe** [comment]
@lzim @ritahitching @staceypark 
Sorry for the confusion! I was thinking about the fidelity rating checklists I had completed on RedCAP...D'oh. Will work on this to be completed by COB Friday. 
My bad 🙈

**Comment by staceypark** [comment]
@jessfroe no worries, thanks for your help!

**Comment by lzim** [comment]
Hi Everyone!

Actually this is another need. The R21 evaluation measures. Pre/Mid/Post

I was talking about the R01 & IIR measures, which also need RedCap programming. 

Perhaps we need separate issues?

@ritahitching @staceypark @jessfroe

**Comment by jessfroe** [comment]
Ah, okay. @staceypark and I clarified the other measures that need to be digitized this morning. I'll create two new issues for each separate grant (R01 & IIR).
I did finish the Pre, Mid and Post for the R21, yesterday, so I will close this issue now. 
Thanks!
@lzim @ritahitching
