### ISSUE TITLE
IIR ART (Clinical Trials) registration

### ISSUE THREAD

**Issue by jessfroe** [lzim/teampsd#606]
ART documentation checklist

## 1. Link to the document and add relevant team members to the card.
- [x] Add the link the current draft of the documentation for the issue:

**To edit the registration:** http://art.puget-sound.med.va.gov/ChooseProject.cfm (internal to VA server).

**To view the posted registration on CT:** https://clinicaltrials.gov/ct2/show/NCT04208217?term=NCT04208217&rank=1

## 2. Link to issues that must be edited in the document in the **issue_tracker** and **feature_tracker.** _(use the # for the link to the issue)_
- [x] N/A

## 3. Team Review
- [x] Fidelity - check with Lindsey
- [x] Data UI - check quant_workgroup
- [x] Sim UI - check with model_workgroup and/or sim_workgroup

## 4. Review and Open Pull Requests _(use the # for the link to the pull request)_
- [x] Check the draft for typos
- [x] Check or open a pull request for the document edits

## 5. Review and/or Update Graphics
- [x] Screenshots
- [x] Gifs
- [x] Logos/Icons
- [x] Links

## 6. Dependencies
- [x] Make sure that any edits you make that need to be added to **depend_product** are tracked (e.g., _MTL Video_)

## 7. Close Pull Requests
- [x] Request review and/or close open pull requests for the document

**Comment by staceypark** [comment]
Successfully registered 12/20

**Comment by staceypark** [comment]
**DECISION Re: #608 CT.GOV - hq_workgroup on 4/16/2020

@staceypark will adjust enrolling dates for IIR to reflect delay with COVID, but still keep end date within expected timeline.
