### ISSUE TITLE
R01 Clinical Trials registration

### ISSUE THREAD

**Issue by jessfroe** [lzim/teampsd#607]
CT documentation checklist

## 1. Link to the document and add relevant team members to the card.
- [x] Add the link the current draft of the documentation for the issue:

**To edit the registration:** https://register.clinicaltrials.gov/

**To view the posted registration on CT**:

## 2. Link to issues that must be edited in the document in the **issue_tracker** and **feature_tracker.** _(use the # for the link to the issue)_
- [x] N/A

## 3. Team Review
- [x] Fidelity - check with Lindsey
- [x] Data UI - check quant_workgroup
- [x] Sim UI - check with model_workgroup and/or sim_workgroup

## 4. Review and Open Pull Requests _(use the # for the link to the pull request)_
- [x] Check the draft for typos
- [x] Check or open a pull request for the document edits

## 5. Review and/or Update Graphics
- [x] Screenshots
- [x] Gifs
- [x] Logos/Icons
- [x] Links

## 6. Dependencies
- [x] Make sure that any edits you make that need to be added to **depend_product** are tracked (e.g., _MTL Video_)

## 7. Close Pull Requests
- [x] Request review and/or close open pull requests for the document

**Comment by staceypark** [comment]
@lzim There unfortunately isn't any specific guidance on how to manage the Study Status on ct.gov. Here is guidance about project extensions:

As outlined in the NIH Grants Policy Statement 8.1.1.3, recipients may extend the final budget period of the approved project on active grants **one time for up to 12 months without requesting prior approval from NIH.**

To support participant health and safety, and continuity of research during this public health emergency, NIH will allow for additional extensions, including mid-project period extensions, for awards supporting NIH-funded clinical trials and human subjects research. Recipients should contact the awarding Institute or Center (IC) to provide details on the effects of COVID-19, and the need for an extension. NIH is committed to working with its recipients during this public health emergency.
Typically, project periods for NIH awards supporting clinical trials and other human subjects research are limited to seven years. NIH will allow project periods to extend beyond the 7-year timeframe for extensions related to COVID-19.

_How to extend final budget period:_
Recipients must use the eRA Commons No-Cost Extension feature to electronically notify NIH that they are exercising their one-time authority to extend without funds the completion date of an award. This extension feature becomes available to the recipient 90 days before the project period end date. Extensions may be up to 12 months beyond the final budget period end date. In the eRA Commons, this notification can be made up to the last day of the current project end date. An e-mail notification is automatically sent to the GMO. No further action by the recipient is required.

**Comment by lzim** [comment]
**DECISION Re: #607 CT.GOV - **hq_workgroup** on 4/16/2020

@staceypark will adjust enrolling dates for both the R01 and the IIR to reflect 10/1 (post MTL COVID-19 module development)
