### ISSUE TITLE
Stockton Pre 2018.07.24

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#61]
Please review pre email for Stockton 2018.07.24 and provide feedback by Friday 7/20:

https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/pre_post_emails/stockton/stockton_pre_2018.07.24.docx

**Comment by TomRust** [comment]
looks good to me!

**Comment by branscombj** [comment]
Done list: "Build" to "Built"
We Decided and Do list: "to see desired impact" --> "to see if we can achieve our desired impact" ?

**Comment by dlounsbu** [comment]
In the We Decided section, it would be useful to mention the name of the model they are currently working with. Also, I would mention units with the variables -- 'Supply of appts' and '% referral of patients (per week)'.

**Comment by staceypark** [comment]
Made edits based on @branscombj and @dlounsbu comments in v2 below and sent.
https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/pre_post_emails/stockton/stockton_pre_2018.07.24_v2.docx
