### ISSUE TITLE
Document R21 DART

### ISSUE THREAD

**Issue by jessfroe** [lzim/teampsd#610]
DART documentation checklist

## 1. Link to the document and add relevant team members to the card.
- [ ] Add the link the current draft of the documentation for the issue:
**Work for this being tracked on** lzim/mtl_code#7

## 2. Link to issues that must be edited in the document in the **issue_tracker** and **feature_tracker.** _(use the # for the link to the issue)_
- [ ] Issue #451 
- [ ] Issue #392 
- [ ] Issue # 

# Dart Request - 5 Page Submission Guide

### All of the information below can be found with a combination of 4 documents/platforms:
*- complete grant application PDF in TeamPSD > Grants*
*- Clinical Trials registration at clinialtrials.gov*
*- IRB protocol application & approval letters in TeamPSD > IRB*
*- RDIS (Research & Development Information System) at rdispaloalto.net*

## Page 1 Information
- [ ] Short Name for Study : 
  ***- Grant application (use own discretion to shorten)***
- [ ] Does our project have an IRB or other project number? 
***Each of our projects has 3 numbers:***
  ***- federal Identifier # from the funding agency: under Grants in TeamPSD***
  ***- clinicaltrials.gov identifier #: search for project on the clinical trials website***
  ***- IRB protocol #: under protocol application in IRB in TeamPSD***
- [ ] Approval Expiration Date?
  ***- IRB Approval letter***
- [ ] Study Start Date : 
  ***- Clinicaltrials.gov registration; note: don't use the dates in the Grants application as they may have updated***
- [ ] Anticipated Study Close Date : 
  ***- Clinicaltrials.gov registration; don't use the dates in the Grants application as they may have updated***
- [ ] Has our study been determined to be an exempt human subjects study? 
  ***- IRB protocol application***
- [ ] If no, informed consent required orally or in writing? HIPPA authorization in writing? IRB Approval for waiver of informed consent?
  ***- IRB protocol application***
- [ ] Does the study have IRB or Privacy Board approval for a waiver of HIPPA authorization? If not, is the waiver only for recruiting/eligibility or for the entire study?
  ***- IRB protocol application***

## Page 2 Participant List
- [ ] List of team members and their requirement needs (Notifications, Data Access or CAPRI/JLV Access)

## Page 3 Data Sources
- [ ] Determine Data Storage Location (VINCI or On Premise Server [Need Location Details])
***Keep consistent to what was specified on RDIS. Tap an HQ member for RDIS info if needed.***
- [ ] Data Access Systems: Would we like to use the SAS Grid in VINCI?
- [ ] Are we sending any data external to VHA? Need location details if so. Company/Agency Name and address and we will need to fill out a DUA 
***Keep consistent to what was specified on RDIS. Tap an HQ member for RDIS info if needed.***
- [ ] What identification level do we need? Real SSN, Scrambled SSN, or Identifiable data but no real/scrambled SSN
***Keep consistent to what was specified on RDIS. Tap an HQ member for RDIS info if needed.***
- [ ] Required Data Sources : Do we need anything other than CDW Production?
- [ ] NDS Approval for CDW access

## Page 4 Documents
- [ ] Required Documents to be uploaded - vary based on our selections made above.

## Page 5 Submission
- [ ] Submit request - missing documents or items will be displayed here.

### Research Request Memo
-  Blank form found [here](http://vaww.vhadataportal.med.va.gov/DataAccess/DARTRequestProcess.aspx#DocumentsAndForms)

### Research Study Institutional Review Board (IRB) Approval Letter
- Located in TeamPSD > IRB, but originally downloaded from Stanford IRB website eprotocol.stanford.edu under Actions >  Download Approval Letter
- From CIRB, local VAMC, or University Affiliate
- IRB letters are needed from each site
- Key Items needed:
  - PI Name
  - Study Name 
  - Approval Date
  - Expiration Date
  - Signed by the Chair of the IRB

### Research and Development RD Committee Approval Letter
- Located in TeamPSD > rdis, but originally downloaded from RDIS website at rdispaloalto.net under Initial Approval Letter

### IRB Approval of Waiver of HIPAA-Compliant Authorization
- Should include
  - VA Facility Name
  - Title of Study
  - PI Name
  - Brief description of PHI used for IRB
  - Must have Chair of IRB Signature

### Research Protocol
- Should include:
  - Introductory paragraph
  - Statement of the Problem
  - Purpose
  - Significance of the Study
  - Research Questions and/or Hypotheses and/or Null Hypotheses
  - Background
  - Methodology
  - Procedure and time frame
  - Analysis plan 
  - Scope and limitations
  - Use the most up to date Protocol

### CDW-Domain Checklist
-  Blank form found [here](http://vaww.vhadataportal.med.va.gov/DataAccess/DARTRequestProcess.aspx#DocumentsAndForms)

**Comment by anthonycpichardo** [comment]
Work for this being tracked on https://github.com/lzim/mtl_code/issues/7

**Comment by lzim** [comment]
Thanks @anthonycpichardo 

I had to head out from #hqhuddle to talk COVID-19 grant with Tom, but I wanted to make sure we keep this review moving.

Note, this key link from your comment goes in the top of the **master document card.** 
This is consistent with the feedback you had when you joined, that we folks deviate from keep the key information at the top, things get kinda hectic. 🌪️  I've added it above.

> Work for this being tracked on lzim/mtl_code#7 

FYI: @staceypark

**Comment by lzim** [comment]
I believe this is done, right? 
Now we're just waiting on VINCI to finalize the ORD_R21 build?

@anthonycpichardo @staceypark

**Comment by staceypark** [comment]
@lzim @anthonycpichardo is the build finished? Or is that the thing we're having the date issues with...

**Comment by anthonycpichardo** [comment]
@lzim @staceypark This is done now. 

Closing
