### ISSUE TITLE
Fidelity Coding Operational Definitions

### ISSUE THREAD

**Issue by jessfroe** [lzim/teampsd#614]
**Hi Qual Workgroup!**

Per our conversation during our 9/03 qual workgroup meeting, here are the **Fidelity Codes** we are utilizing.

Our responsibilities for the next week are to nail down the operational definitions of the following codes using Oetzel et al., (2013 & 2018) as guides, and subsequently utilize these codes with the master_r21_train RQDA project.

Let's hash these out in the comments and work to define these codes as soon as possible!

😄 

1. clear_engagement 

2. partner_for_change 

3. transparency 

4. local_control

5. shared_understanding 

6. team_priority 

7. build_capacities_strengths 

8. consensus_building 

9. shared_decisionmaking 

10. local_synergy 

11. workable_solutions

**Comment by jessfroe** [comment]
Here is the operational definition for #7 which we discussed during our qual_workgroup meeting: 

**7. build_capacities_strengths**

-  Team has the resources it needs to meet its aims. (What does it mean to have capacity?)

-  Facilitators are helping the team to maximize their existing local resources in this statement (sentence). (A capacity building quality to the process.)

-  Facilitators are working to build capacity for participatory learning for simulation (BUILD); make improved decisions under complexity. (This is specific to building capacities for modeling or systems thinking or additional components of MTL.)

**Comment by jessfroe** [comment]
@dlounsbu @swapmush @lzim @teampsdkathryn 
I'm going to start brainstorming some additional definitions. I'll continue to use the same format as above, including the information from Oetzel et al. (2013 and 2018) and expanding with additional MTL specific definitions:
 
**4. local_control**
- Alignment with CBPR principles, with a partner focus. Develops individual partner capacity and equitable partnerships in all phases of the research. 
(would this be more applicable to 2. partner_for_change?
- Teams have access and control over the use of their VA specific data while using MTL, and feel efficacious utilizing this data. 
- Facilitators tailor MTL to the localized data provided by each team, and increase feelings of control over team data. 

**5. shared_understanding**
- Partner values, and a shared understanding of the project mission, priorities and strategies. 
- Team members engage in collaboration across their team to prioritize their team need, as well as running their base case, and experiments 1, 2, and 3. 
- Facilitators ensure MTL is used for priorities that are relevant to the team. 

Please iterate upon this as much as you can! This is a very rough first pass.

**Comment by lzim** [comment]
@jessfroe

FYI: @staceypark 
This is @jessfroe’s, but she is out (for Team PSD) today. 

Yes, we need to go back to the **qual_workgroup** Lucid Meeting where we pulled out each fidelity item from the revised **fidelity_training** checklist in *mtl_facilitate_workgroup** and add the operational definitions. Cross-ref #613

**Comment by swapmush** [comment]
**1. clear_engagement** 
-  Team has the resources it needs to meet its aims. (What does it mean to have capacity?)
-  Facilitators are helping the team to maximize their existing local resources in this statement (sentence). (A capacity building quality to the process.)
-  Facilitators are working to build capacity for participatory learning for simulation (BUILD); make improved decisions under complexity. (This is specific to building capacities for modeling or systems thinking or additional components of MTL.) 

**9. -shared_decision making** 
-Team members’ opinions are considered by the team, and they are comfortable in supporting team decision process. 
-Facilitators are developing shared decision making skills of the team in this statement (sentence). 
Facilitators are eliciting feedback from providers and building consensus in order to make shared decisions (BUILD); stakeholders are iteratively making decisions in MTL about their local system (i.e. Q/H/F/D). 

**10.  local_synergy** 
-Team demonstrates the capacity to work together effectively and accounting for the complexities of their system.  
- Facilitators are helping the team maximize their efficiency within the context of their local system in this statement. (sentence)
- Facilitators are working to build capacity for developing team goals, recognize challenges, and work together effectively through modeling and simulation (BUILD). 

Please iterate and edit as you all see fit.

**Comment by jessfroe** [comment]
Hi @lzim, could you let me know if I'm on the right track and have accurately interpreted what we discussed earlier? 
I put a question mark after the ones I was _really_ not sure about. 

**clear_engagement** 
Facilitators established relationships, built trust, and created processes for action. 
(?)

**partner_for_change** 
We recognized the need to partner to create change and improvement. 

**transparency** 
We were clear about the purposes or goals of this improvement effort.

**local_control**
We made VHA data resources in this effort transparent. 
We facilitated greater understanding and local team control over use of VHA data. 
(?)

**shared_understanding** 
Our (this) team has a clear and shared understanding of the problems we are trying to address. 

**team_priority** 
This project emphasizes what is important to our (this) team. 

**build_capacities_strengths** 
We sought to support our existing capabilities to best use local team resources and make local decisions. 
(?)

**consensus_building** 
Even though we did not have total agreement, we did reach a kind of consensus that our (this) team all accepts. 

**shared_decisionmaking** 
We are supporting shared team decision-making in this project. 

**local_synergy** 
We recognized local challenges for our (this) team and came up with good solutions. 

**workable_solutions**
We developed strategies that are likely to work for our (this) team.

**Comment by lzim** [comment]
> Hi @lzim, could you let me know if I'm on the right track and have accurately interpreted what we discussed earlier?
> I put a question mark after the ones I was _really_ not sure about.
> 
> **clear_engagement**
> Facilitators established relationships, built trust, and created processes for action.
> (?)
> 
> **partner_for_change**
> We recognized the need to partner to create change and improvement.
> 
> **transparency**
> We were clear about the purposes or goals of this improvement effort.
> 
> **local_control**
> We made VHA data resources in this effort transparent.
> We facilitated greater understanding and local team control over use of VHA data.
> (?)
> 
> **shared_understanding**
> Our (this) team has a clear and shared understanding of the problems we are trying to address.
> 
> **team_priority**
> This project emphasizes what is important to our (this) team.
> 
> **build_capacities_strengths**
> We sought to support our existing capabilities to best use local team resources and make local decisions.
> (?)
> 
> **consensus_building**
> Even though we did not have total agreement, we did reach a kind of consensus that our (this) team all accepts.
> 
> **shared_decisionmaking**
> We are supporting shared team decision-making in this project.
> 
> **local_synergy**
> We recognized local challenges for our (this) team and came up with good solutions.
> 
> **workable_solutions**
> We developed strategies that are likely to work for our (this) team.

**Fo Sho** @jessfroe!  
💣

This is what I meant to start from our **facilitator fidelity ratings** and our **CBPR theory of change** survey items. 

We’ll work on this tomorrow starting at 8AM Pacific - see you there @teampsdkathryn @dlounsbu @swapmush

**Comment by jessfroe** [comment]
**Per qual meeting 9/10/2019:**
- Overlapping coding is okay: these codes are **not mutually exclusive**
- Code by **speaker**
- To what extent is the **facilitator** engaging in the **theory of change**
- Probably won't have much coding of the teams - we are interested in the _extent_ to which the _facilitator_ engages in the participatory principles

- Potential to look at the whole session as a measurement of time for coding - did the facilitator address the above participatory principles **in session**

- Absent = the facilitators did not engage in the participatory principle for that session
- Present = the facilitators did engage in participatory principles during the session

- Need to have an **example** of where the **specific principle** is present within the session to show where it occurs

**Possible points for each stage of MTL**
Partner - 0 - 5 
Build - 0 - 4
Apply - 0 - 2

Out of 11 - Use **total** of **yes/no** to determine total score

We will not be separating out the different phases currently - at the train level, we did not  have these phases flushed out, so we are interested in determining to what extent the facilitators engaged in all of these principles in all sessions.

**Comment by jessfroe** [comment]
@lzim before I populate the table of PARTNER/BUILD/APPLY with the codes within each phase, can you confirm that my codes are corresponding to the correct statements? Otherwise I am not sure that I will put them underneath the correct phase. 
Thanks! 😸

**Comment by jessfroe** [comment]
Phase | Code | Fidelity Rating
| - | - | -
| **PARTNER** |  | 
|  | clear_engagement | Facilitators established relationships, built trust, and created processes for action. |
| | partner_for_change | We recognized the need to partner to create change and improvement.|
| | transparency |We were clear about the purposes or goals of this improvement effort. We made VHA data resources in this effort transparent. |
| | local_control | We facilitated greater understanding and local team control over use of VHA data.|
| | shared_understanding | Our (this) team has a clear and shared understanding of the problems we are trying to address.|
| **BUILD** | | |
| | team_priority | This project emphasizes what is important to our (this) team.|
| | build_capacities_strengths | We sought to support our existing capabilities to best use local team resources and make local decisions.|
| | consensus_building | Even though we did not have total agreement, we did reach a kind of consensus that our (this) team all accepts. | 
| | shared_decisionmaking | We are supporting shared team decision-making in this project.|
| **APPLY** | | | 
| | local_synergy | We recognized local challenges for our (this) team and came up with good solutions.|
| | workable_solutions | We developed strategies that are likely to work for our (this) team.|

**Comment by jessfroe** [comment]
FYI @lzim I populated the table with my current understanding of the code and their corresponding Fidelity Q. Please let me know if I need to adjust it at all.

**Comment by lzim** [comment]
Yes @jessfroe - the table looks great!

NOTE: I edited above one thing, which is that we are coding by **TEAM MEETING NOTE** 
- We made the change during the meeting.

Thanks!

FYI: @swapmush @dlounsbu @teampsdkathryn

**Comment by lzim** [comment]
Cross-ref #692
