### ISSUE TITLE
Due TBD: EBP Reach Dose calculation 

### ISSUE THREAD

**Issue by saveth** [lzim/teampsd#615]
**1. Add description:** 
Once Andrew is done with #462 and hands over the data, then the data needs to be validated, setup for analysis and EBP Reach Dose needs to be calculated.

<< Paste screenshots here>>
 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [x]   Capacity
- [ ]   Cost
- [x]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_ 1month
Once @saveth receives the data, the following process needs to occur in order: 
a) Data needs to be setup and validated throughout the various EBP measures calculation to ensure appropriate data definition, data pull, and calculation (depending on issues discovered during the data cleaning/validation process, this may take any where from a week or month--hoping it's just a week)
b) Andrew has provided new data using the updated EBPharm data definition (#462 on 10/2) and  per the meeting (https://meet.lucidmeetings.com/meeting/228771) on 10/3, the follow set of validation/analysis needs to be performed:
- [x] 2-3 days: rerun the current EBP Reach Initiate code for each of the 12 EBP Reach conditions (#476) (this requires individual script files for each analysis)
- [ ] 1 week: setup code, validate and run analysis for Option B average calculation as discussed in OSF (https://osf.io/z7y8m/wiki/Data%20Definition/) and on 10/1 (https://meet.lucidmeetings.com/meeting/228871)
- [ ] 2 weeks: write code to generate EBP Reach Dose using current average of proportions (Option A) and general average (Option B) for 12 EBP measures and validate the data 
- [ ] 1 week: need to update slide deck in #476 with all 48 EBP Reach calculations (section b) for co-I meeting and validation of EBP definition for R01/IIR protocol manuscripts (#559 #561) :
- [ ] TBD: will also need to collaborate with @lzim to determine what and how much materials go into the slide deck for co-Is; @saveth will work with @staceypark to schedule extra meetings to review new slidedeck prior to co-I meeting, once we've determined which month the materials will be presented 

**Edit the due date (if necessary)**

**Comment by staceypark** [comment]
@saveth please add the deadline at the beginning of the issue instead of the end, as the template instructs you to do. this helps us immediately see prioritization across the tracker

**Comment by staceypark** [comment]
@saveth Like we discussed at the Workgroup Leads meeting yesterday, #462, #615, and #424 are our top priority as we need them done to submit our protocols for the grants prior to launch.

You & @saveth will be at the AI conference starting 9/18 so we need these done by latest next Monday 9/16 as our top priority.

**Comment by saveth** [comment]
@staceypark @lzim I noticed that you've changed the due date to be next week. This is NOT feasible. @holbrooa hasn't even provided me with the data and I need at least a month to validate and code the analysis. We spent over 4 months validating and coding the EBP Initiate data, so I can't do this in a week assuming I get the data now.

**Comment by saveth** [comment]
@staceypark @lzim Glad we were able to talk this afternoon to clarify things. I've updated the template above to include the time line and details on what I anticipate will need to happen to accomplish this task.

**Comment by saveth** [comment]
@holbrooa promised that he will provide the data by COB 9/11.

**Comment by lzim** [comment]
Thanks @saveth @holbrooa and @staceypark for staying on top of this.

- For @holbrooa’s piece of this: I would rank #615 for the _R01 protocol_ and trial registration - **EBP Reach Dose/Course** higher than #424 p-chart update for the _R21 preliminary findings_

- We do need @saveth to be able to going on this ASAP, esp. if this something she is worried may take an additional month...

**Comment by saveth** [comment]
@lzim @staceypark @ritahitching @holbrooa I've updated the cost estimates above to include all the new calculations and validation necessary for EBP Reach Initiate and Dose to ensure that we're  using the appropriate data definitions/calcualtions for the protocols. We will need to discuss changing the Due date to reflect the updated time estimate.

**Comment by staceypark** [comment]
We've updated the due date to 11/1 in the Support Workgroups meeting to reflect the updated timeline since the data was just handed off to @saveth

**Comment by staceypark** [comment]
@saveth is working on validating data and creating code for Dose calculations this week

**Comment by lzim** [comment]
> @saveth is working on validating data and creating code for Dose calculations this week.

That sounds great @staceypark 

- We'll want to keep an eye on this along with the p-charts/xmr-charts for the R21.
- And, the tt3 reports.

**Comment by ritahitching** [comment]
@lzim @saveth @staceypark @ritahitching 

- Final issues will be updated on site selection is finalized

**Comment by saveth** [comment]
@lzim @staceypark @ritahitching This is done. Showed @staceypark  and @anthonycpichardo  where the code is housed in the team folder.

**Comment by lzim** [comment]
This was open for #559 **r01_protocol_impsci**
- Closing to review manuscript and then determine whether this needs further work.
