### ISSUE TITLE
9/30 Unable to upload new users to Epicenter

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#616]
**1. Add description:** 
@jamesmrollins we are trying to create a sim login for @ritahitching (our new HQ member) on Epicenter. I tried to add her to 640a0_mpd_team4_ind and got the error "Username may only contain [a-z], [0-9], hyphen (-), or underscore (_)" (sorry GitHub is not letting me attach screenshots for some reason). Has there been a new Epicenter update that changed requirements for usernames?

 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_**14 hrs.**

**Edit the due date (if necessary)**

**Comment by jamesmrollins** [comment]
@staceypark I sent @ritahitching a team 4 invite as an individual invite.  Let's see if that works.  The special character prohibition has always been there as far as I remember.

**Comment by staceypark** [comment]
we are getting an error message:
"there is a problem with your session. please sign out from epicenter and try again"

**Comment by jamesmrollins** [comment]
@staceypark I just ran the experiment below and it worked ok, even with the special character.  I assigned the user to the worlds and was able to login with both.

![image](https://user-images.githubusercontent.com/30132017/64202667-8cfe0100-ce46-11e9-9c96-3495feeaf1e8.png)

Regarding the error message in last thread, there may have been a server communication error, which can come from a multitude of reasons including internet traffic.

**Comment by staceypark** [comment]
@jamesmrollins she's still experiencing the same error

**Comment by jamesmrollins** [comment]
@staceypark I think we have identified the problem - We cannot use the same user name for Epicenter Member and End User.  I think if we use a different email, we should be ok.  Please have @rhitching call me soonest, and I will see if we can correct the problem.  Cheers! James

**Comment by lzim** [comment]
@jamesmrollins @staceypark

This is a constraint that Forio creates since the Team PSD Co-Facilitators were trained. 

It is likely to be a big headache for the TAS who, I believe, never created Faciliator/Epicenter Admin accounts. Right, Stacey?

**Comment by staceypark** [comment]
@jamesmrollins we resolved it for @ritahitching (by the way her handle is first and last name)
and I've linked it to #602 in the document tracker for me to update in the facilitate cheatsheet, but @lzim  is right in that this will pose an issue for all of the IC (Implementation Consultants / formerly TAS).

**Comment by jamesmrollins** [comment]
@lzim @staceypark based on your comments above, this issue does not seem resolved to me.  I need to understand why this will cause a problem for the TAS facilitators, especially if we haven't registered their membership in Epicenter.  Can we talk a little more on this please?  Thanks,
James

**Comment by lzim** [comment]
> @lzim @staceypark based on your comments above, this issue does not seem resolved to me. I need to understand why this will cause a problem for the TAS facilitators, especially if we haven't registered their membership in Epicenter. Can we talk a little more on this please? Thanks,
> James

Agreed @jamesmrollins I don’t think it is resolved.
Will you add #616 to tomorrow’s Support Workgroup Leads meeting, please?

First, the TAS are now calling themselves the “ICs” per @staceypark’s comment above.

The Team PSD Co-Facilitators were grandfathered in to retaining the same username for the Sim UI and MTL Facilitate (Epicenter). 

The ICs have already had to develop several username/password combinations across Lucid, GitHub, Sim UI, etc. It would be great if they did not have to be different, and if they could use their VA email. 

If they absolutely cannot, it would be good @staceypark to set up something standard for them.

**Comment by staceypark** [comment]
@jamesmrollins will reach out to Forio to see if we can get an exception for the entire VA project for users using same email for the backend Epicenter and the front end Sim UI

**Comment by jamesmrollins** [comment]
@lzim @staceypark @jessfroe @ritahitching 
I spoke with Forio today.  They indicated that it would be possible to flag our session so we can have a single log-in for both MTL group/world and Epicenter level interactions.  However, they would need to push it in conjunction with a server update scheduled for later this month.  I will advise when this is in place.  Thanks, James

**Comment by lzim** [comment]
> @lzim @staceypark @jessfroe @ritahitching
> I spoke with Forio today. They indicated that it would be possible to flag our session so we can have a single log-in for both MTL group/world and Epicenter level interactions 🎇🎈🎉. However, they would need to push it in conjunction with a server update scheduled for later this month. I will advise when this is in place. Thanks, James

Great news! Thanks @jamesmrollins 💥

**Comment by jamesmrollins** [comment]
@hirenp-waferwire this looks good! Please see minor edits below.

1.  MTL Demo Registration eMail (this applies to both 2 week and 90 day versions).

![image](https://user-images.githubusercontent.com/30132017/64976024-342a6180-d865-11e9-9e92-4b6cc79c0f05.png)

2.  Since a course code was offered, the expiration should be 90 days.  The email should also reflect this period of expiration.  Is it possible to give an actual expiration date as a column in the Admin screen and in the email to the end user?

![image](https://user-images.githubusercontent.com/30132017/64976693-cd0dac80-d866-11e9-8f0d-df736f76e60b.png)

3.  The type in the Registration Pop Up should be normal.  _Modeling to Learn_ should be italics.

![image](https://user-images.githubusercontent.com/30132017/64977150-b61b8a00-d867-11e9-9309-ffc2c0ffa8d1.png)

**Comment by jamesmrollins** [comment]
@staceypark @ritahitching can you try registering Rita using the same email for both the member and the End User level in Epicenter and report your findings please?  Thank you, James.  

P.S. The result should be that Rita is able to use the same email based username for both her membership to the project level and as an end user.

**Comment by ritahitching** [comment]
@jamesmrollins do you have time to walk me through the process of adding me to the website today or tomorrow?

**Comment by staceypark** [comment]
@ritahitching @jamesmrollins tested out using the same email for Forio & Sim registration and looks like it works. No documentation needs to be updated.
