### ISSUE TITLE
PCT Post 2018.07.18

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#62]
Please review PCT post 2018.07.18 email and provide feedback by Friday 7/20:

https://github.com/lzim/teampsd/blob/10392804056426848bb9f19d74554d74153cc8f3/mtl_facilitate_workgroup/pre_post_emails/pct/pct_post_2018.07.18.docx

**Comment by TomRust** [comment]
all important items covered

**Comment by branscombj** [comment]
care for ~25 visits  - should it just say "commonalities among patients who are in care the longest"?
On the done list, Reviewed how to use Data UI to validate Sim UI data - Do they have to "validate" the Sim UI data? Is this more about just being able to go back and forth so they understand what's showing and why? Or "Reviewed how to check the dataset selected in the Data UI to clarify any questions about data showing in Sim UI" .. ?

**Comment by branscombj** [comment]
woops didn't mean to close it.

**Comment by staceypark** [comment]
@branscombj - I agree that "validate" may not be the most appropriate nor clinician friendly word.  I changed it to "reviewed how to use Data UI to understand and clarify Sim UI data questions."  The "~25 visits" phrasing was a decision made with the team so I left as is and sent.

v2 here:
https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/pre_post_emails/pct/pct_post_2018.07.18_v2.docx
