### ISSUE TITLE
redcap_qa_roles_definitions wk2 QA PROD support from James

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#622]
**Andon Policy for Immediate TEAM ACTIONs (pre-launch)**

1. Contact HQ (Lindsey & Stacey; Stacey can make a call if Lindsey is unavailable)

2. Call an immediate meeting to identify and implement the fix.

3. Team PSD will conduct a post-mortem to manage specific learner impacts team-by-team.

**Comment by ritahitching** [comment]
@staceypark @lijenn @ritahitching 
Please clarify the task - not sure what it refers to.

Once the specs are clear either @ritahitching or @lijenn will be assigned the task.

**Comment by staceypark** [comment]
@ritahitching @lijenn 
This was a two part task for:
1. redcap training guide -- already done. I've updated the estimate on this task to reflect this piece being done.
2. creating a map on how to use and create projects in REDCap -- If you go to the team's LucidChart account, I started one, but haven't finished it yet. I can orient whoever takes up this task to what needs to be done.

**Comment by ritahitching** [comment]
@staceypark and @lijenn 
I'll do the map on creating new projects on RedCap.  I assigned myself. 
I'll use the LucidChart document entitled **va_redcap_map**
thanks,

**Comment by ritahitching** [comment]
@lijenn please review the Lucidchart diagram entitled **va_redcap_map**  on how to make a new RedCap project. thanks

**Comment by lijenn** [comment]
@ritahitching
Hi Rita, I think the 'Click "Create Project"' square should come before the square that explains how to enable the survey, right? 
- [ ] Move 'Click "Create Project"' to correct location

I also did not get or see the 'Agree to REDCap Notice' after enabling the project to be a survey? 

@staceypark Could you also explain how much more in depth the map should go into?

**Comment by staceypark** [comment]
@ritahitching please do not edit other people's comments, consistent with our SOP (unless someone has responded to GitHub by email and everyone's email information is displayed to the public). Please just make a new comment! 

For example, it makes it confusing to future readers - like myself! 😅 

@lijenn I think you were asking how in-depth the map should go? Not sure what the "removed" part is about. The map should be in-depth enough, that someone can create a project from start to finish alone.
> * [x]  I removed it
>   @staceypark Could you also explain how much more in depth the map should go into?

**Comment by ritahitching** [comment]
@staceypark 
- [ ] The Lucidchart map on how to create a new RedCap project is ready for review.  
- [ ] Please let me know if there are any edits.
- [ ] I will then close this issue.
thanks

I'm not sure I understand your comment below.  Which comment did I edit? Apologies if it caused you confusion. 🙏 
from @staceypark 
@ritahitching please do not edit other people's comments, consistent with our SOP (unless someone has responded to GitHub by email and everyone's email information is displayed to the public). Please just make a new comment!

For example, it makes it confusing to future readers - like myself! 😅

**Comment by staceypark** [comment]
> @staceypark
> 
> * [ ]  The Lucidchart map on how to create a new RedCap project is ready for review.
> * [ ]  Please let me know if there are any edits.
> * [ ]  I will then close this issue.
>   thanks
> 

Thanks @ritahitching. I'll take a look.


> I'm not sure I understand your comment below. Which comment did I edit? Apologies if it caused you confusion. 🙏
> from @staceypark
> @ritahitching please do not edit other people's comments, consistent with our SOP (unless someone has responded to GitHub by email and everyone's email information is displayed to the public). Please just make a new comment!
> 
> For example, it makes it confusing to future readers - like myself! 😅

I'm referring to the edits you made to Jenn's comments in this thread.
![image](https://user-images.githubusercontent.com/31089501/78812219-ec456600-797f-11ea-82bd-950fedab4132.png)

**Comment by ritahitching** [comment]
@staceypark thanks for clarifying. 
@lijenn and I did this together while we were triaging the issue and discussing the task over a MS Teams call.  
I'll make edits on a new comment in future.

> > @staceypark
> > 
> > * [ ]   The Lucidchart map on how to create a new RedCap project is ready for review.
> > * [ ]   Please let me know if there are any edits.
> > * [ ]   I will then close this issue.
> >   thanks
> 
> Thanks @ritahitching. I'll take a look.
> 
> > I'm not sure I understand your comment below. Which comment did I edit? Apologies if it caused you confusion. 🙏
> > from @staceypark
> > @ritahitching please do not edit other people's comments, consistent with our SOP (unless someone has responded to GitHub by email and everyone's email information is displayed to the public). Please just make a new comment!
> > For example, it makes it confusing to future readers - like myself! 😅
> 
> I'm referring to the edits you made to Jenn's comments in this thread.
> ![image](https://user-images.githubusercontent.com/31089501/78812219-ec456600-797f-11ea-82bd-950fedab4132.png)

**Comment by ritahitching** [comment]
from @staceypark comments mentioned in #1286 

**RedCap map:**
- [ ] Review the shapes and colors. Dark red is used to connect to a new map.
- [ ] End of the flowchart should be a pill shape instead of a rectangle.
- [ ] Map flow order needs to be reviewed (e.g. can't create a VA RedCap account without already being at the VA RedCap website).

**Please Clarify Regarding Comment**
- [ ] Add instruction on how to create a full project - including instruments and user roles. Instead of leading up to the "project button". This map should allow someone to create a full survey on their own.

1. I was under the impression this map was to provide guidance on how to log-in to RedCap and start/create a new project with out details about building instruments. 
2. If we want to create a map on how to build/create/design a project and create instruments that's a different ask.  
3. In my opinion these asks should be separate maps, otherwise they become very long and complicated. 
4. The process for creating different instruments is very detailed and easy to get wrong without any RedCap training.  
5. There are many several types of instruments, self-build per question options, copy existing instruments, data dictionaries etc.
6. Should we have maps for different types of instruments and process of creating them.

thanks,

**Comment by staceypark** [comment]
@ritahitching great question - 
Logging in is the first step to accessing any platform so that makes sense to include.
I don't think I actually creating a project vs. creating a new instrument as two different things. 
Meaning it doesn't make sense to me that someone would create a project without creating an instrument.

I would liken it to:
Teaching someone how to open up a new PowerPoint file but not explaining how to add new slides and text. Knowing how to open a new PowerPoint file itself, doesn't get you anywhere or let you do anything.

**Comment by ritahitching** [comment]
@staceypark thanks for comment. 
- My reasoning  was that you cannot start an instrument without creating a **Project** first, but you can add/ edit /delete different types of instruments once a project is created. 

- [ ] Please confirm you are asking for a LucidChart map that has instruction to create/edit/delete etc. instruments within (i) surveys and within (ii) longitudinal in the same or in two separate LucidChart maps?
thanks

**Comment by staceypark** [comment]
@ritahitching 
> * [ ]  Please confirm you are asking for a LucidChart map that has instruction to create/edit/delete etc. instruments within (i) surveys and within (ii) longitudinal in the same or in two separate LucidChart maps?

Thanks for "active reading" 😄 Yes, create one LucidChart that includes instructions on how to create/edit/delete instruments, meaning, extend your current map a bit more.
I'm not sure what you mean by instruments within surveys. Instruments = surveys right?

> * [ ]  Should we disregards longitudinal with arms for now?

Sure, let's go ahead and disregard longitudinal for now as we do not have a use case for those with our team.

**Comment by ritahitching** [comment]
@staceypark thanks for clarifying. Please review the additions on LucidChart. I'm just focusing on surveys.
thanks.

**Comment by ritahitching** [comment]
@staceypark not sure if you've had a chance to review the revised Lucidchart map, when you get a chance please send me your comments. Thanks

**Comment by staceypark** [comment]
@ritahitching 
Rita this map still does not follow the flow chart template shapes and colors.
Quick check on shapes and colors - Can you tell me when the bright red pill is used? When is the dark red pentagon used?

FYI @lijenn

**Comment by ritahitching** [comment]
@staceypark thanks for feedback on colors. 

## Answers:
I used your [prior map](https://www.lucidchart.com/documents/edit/e9f7a037-9b5a-491d-a2c2-644168377d5a/0_0) for guidance, from what I understand you used: 
- [ ] bright red pill for creating / starting and ending a map
![image](https://user-images.githubusercontent.com/54862187/79598254-76847d00-8098-11ea-8599-17165c97cb54.png)
![image](https://user-images.githubusercontent.com/54862187/79598321-99af2c80-8098-11ea-84c0-a0ecab782e2e.png)

- [ ] dark red pentagon for ending a section 

![image](https://user-images.githubusercontent.com/54862187/79598114-4210c100-8098-11ea-8763-fd4322c18709.png)

## Questions:

- [ ] I choose the bright red pill at the end of each stage of the RedCap creation process to help with the visual flow/breakup of the information. Do  you recommend another icon/color?

![image](https://user-images.githubusercontent.com/54862187/79598574-12ae8400-8099-11ea-9d85-454b0f4a9704.png)
![image](https://user-images.githubusercontent.com/54862187/79598857-7a64cf00-8099-11ea-8e20-5e201fd97d60.png)

-  [ ] I choose the dark red pentagon to indicate the end of the process to request a RedCap account - my reasoning was that the user has to wait until the account is available.  The pentagon then links back to the log in flow.  Do you recommend another icon/color? 

![image](https://user-images.githubusercontent.com/54862187/79598465-d7ac5080-8098-11ea-9fbb-c5f3d9dba0e5.png)

- [ ] D you have any changes to the content / steps in the map?
thanks

**Comment by staceypark** [comment]
@ritahitching before we turn to content changes on the map:

You confirm here that the bright red pill was used for the start/end of a map...
> bright red pill for creating / starting and ending a map

But then contradict this in your next statement that you used it to breakup the information. You *cannot* change the standardization of the template/legend to your own needs - **That defeats having a template and makes it confusing for everyone else. Please do not do that on this map or anywhere else.** Does that make sense?
> I choose the bright red pill at the end of each stage of the RedCap creation process to help with the visual flow/breakup of the information. Do you recommend another icon/color?

No, the dark red pentagon is not for ending a section. It sounds like you were not clear going into this map on how the shapes and colors are used. **In the future, please clarify beforehand these types of requirements if you are not sure.**
> dark red pentagon for ending a section

As your next step, can you:
- [ ] Update the map template. Currently it includes a legend of the colors but does not indicate which shapes they are for or what the shapes mean. Can you add the below info into that legend (note: keep the hex code for the colors that are already there)

Shape: Pill
Color: Bright Red
Meaning: Start/End

Shape: Rectangle
Color: Light Blue
Meaning: Process or Task

Shape: Diamond
Color: Dark Blue
Meaning: Decision

Shape: Pentagon
Color: Dark Red
Meaning: Connect to another map

Shape: Arrow
Color: Black
Meaning: Sequence

- [ ] Edit your current map to match this template.

**Comment by ritahitching** [comment]
@staceypark thanks for edits.  I updated the map to reflect the feedback. thanks

**Comment by staceypark** [comment]
@ritahitching I'm not seeing the update on the map template aka "template_teampsd"? 

Remember, you created the template a while back as our standard template for all maps. The legend on this template already included the colors, which I mentioned above in number 1, and we want to add a fuller description of the shapes and meanings to make sure this standardized template is meaningful.

Can you make sure to update this?

> Update the map template. Currently it includes a legend of the colors but does not indicate which shapes they are for or what the shapes mean. Can you add the below info into that legend (note: keep the hex code for the colors that are already there)

**Comment by ritahitching** [comment]
@staceypark I updated the [teampsd template](https://www.lucidchart.com/documents#/templates?folder_id=home&browser=icon) with full color list and definition of shapes and their uses on Lucidchart.

**Comment by ritahitching** [comment]
@ritahitching update make to include
VHA user name and VA email to log in to RedCap

**Comment by staceypark** [comment]
@ritahitching I'm still not seeing where the template is. Can you link me directly to the document where you think the updated template is?

Also, please create a task card assigned to me for reviewing your work consistent with what we have been discussing at HQ huddles and reviewed again at the HQ workgroup meeting on 4/23.

**Comment by ritahitching** [comment]
@staceypark good morning 
- [ ] Lucidchart templates located [here](https://www.lucidchart.com/documents#/templates?folder_id=home) under **Presonal** section.
- [ ] MTL.how map template [here](https://www.lucidchart.com/invitations/accept/def64d0c-2bda-4124-a7a4-c465ba3cb006)
- [ ] TeamPSD Bug & Feature template [here](https://www.lucidchart.com/invitations/accept/b8afc818-1a38-46c6-b985-04fea3081656) 
- [ ] ZenHub template [here](https://www.lucidchart.com/invitations/accept/777a8ae3-8992-4965-bd41-0d212a9ac038)
- [ ] VA RedCap diagram [here](https://www.lucidchart.com/invitations/accept/baaa449c-2e9f-4ec5-af46-83ca80c4882f)
- [ ] Issue card to review RedCap diagram #1374

**Comment by ritahitching** [comment]
@lzim please confirm I can move this issue to the May milestone &  Epic?
thanks

**Comment by lzim** [comment]
> @lzim please confirm I can move this issue to the May milestone & Epic?
> thanks

@ritahitching Yes, consistent with #1 from the **hq_workgroup** meeting and the **all_hands** meeting:  closing the open **document_tracker** cards and finishing the **Team PSD Manual** are our top cross-cutting **may_epic** priorities.

**Comment by lzim** [comment]
@staceypark and @lijenn 

I'm not sure what needs to be done to close this?
We will need the baseline RedCap working in **oct_epic.**

**Comment by lijenn** [comment]
- Remaining task is to reformat/edit the RedCap guide for MTL Manual, will close this document card once done by today/tmrw.
- All RedCap projects should be ready to go, will do a final review before we move it from development to production in #1290 in wk 3, but I can get probably get this done sooner depending on bandwidth.
- Same for setting up Facilitators RedCap accounts in #1277, will need to give the QIICS a notice in advance before setting up accounts to expect the email.

**Comment by lzim** [comment]
@lijenn 
@staceypark 

Note that any _research_ use of RedCap would be a Team PSD task for the Team PSD manual.

The only _operations_ use of RedCap is for the MTL Menu in session 4. Does that make sense?

**Comment by lzim** [comment]
Discussed at hq_workgroup on 2/4/2021

Jenn believe the documentation of RedCap QA is ready:
- [ ] QA DEV
- [ ] QA TEST
- [ ] QA PROD

Need to create an issue task card for @jamesmrollins to test the surveys in wk2
- [ ] QA PROD most urgent - Ideal release is 2/8, but due to EES delays and IRB mod may not release until later

- [ ] QA TEST to add to manual
