### ISSUE TITLE
sim_ui_qa_roles_definitions

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#624]
**Andon Policy for Immediate TEAM ACTIONs (pre-launch)**

1. Contact HQ (Lindsey & Stacey; Stacey can make a call if Lindsey is unavailable)

2. Call an immediate meeting to identify and implement the fix.

3. Team PSD will conduct a post-mortem to manage specific learner impacts team-by-team.

**Comment by lzim** [comment]
Hi @jamesmrollins 

We discussed these open document cards as the place to outline the qa roles and definitions for the Sim UI.
- [ ] DEV QA
- [ ] TEST QA
- [ ] PROD QA
