### ISSUE TITLE
wk1 sep_epic Update facility_data_qa testing procedures and documentation

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#626]
**Andon Policy for Immediate TEAM ACTIONs (pre-launch)**

1. Contact HQ (Lindsey & Stacey; Stacey can make a call if Lindsey is unavailable)

2. Call an immediate meeting to identify and implement the fix.

3. Team PSD will conduct a post-mortem to manage specific learner impacts team-by-team.

**Comment by ritahitching** [comment]
@holbrooa Any documentation on the andon policy in splashpage check?

**Comment by anthonycpichardo** [comment]
Splash Page documentation- how to run the process and things to be aware of. Document solutions to any issues that may arise. 

@staceypark verify if this is accurate.

**Comment by anthonycpichardo** [comment]
@staceypark can you verify what this issue card is for?

**Comment by anthonycpichardo** [comment]
Write a document that outlines the splashpage update process and how to catch any issues with the update

**Comment by anthonycpichardo** [comment]
The document needs to include the following knowledge: "we can update the splashpage to show the Data refresh button, but it needs to be done individually per SplashChart, it is also being set from the SplashMothership,  we will need to modify the code for the future or it will be reintroduced

Also we need to be monitoring sites that are too large. Sharepoint has 50 mb limit for worksheets, if a site is too large that has been propagated we need to allow for them to opened in excel via the pop up. This is done in the WebApp properties."

**Comment by lzim** [comment]
@anthonycpichardo let’s track this with the post kickoff email from HCS 644

**Comment by lzim** [comment]
@anthonycpichardo 

We talked about #626 at Monday's Workgroup Leads meeting. 
Want to make sure it's considered along with #1218 & #1192.

This is a piece of documentation/SOP checklist that makes sense to develop and consider along with our "March propagation."
_- Note: We should call the splashpage propagation but the month's worth of data that we're adding. Hence, we're doing the March propagation._

FYI: @staceypark and @anazariz

**Comment by staceypark** [comment]
@anthonycpichardo can you update the due date on this and when you want my review?

**Comment by anthonycpichardo** [comment]
Update splashpage guide to reflect style guide changes

**Comment by lzim** [comment]
@anthonycpichardo 

Are there still open tasks on this **document_card**?

**Comment by anthonycpichardo** [comment]
The outstanding items for this are on #1733 which will be closed today.

**Comment by lzim** [comment]
@anthonycpichardo 
@anazariz 

Let’s be sure to consider the active **ANDON** identified in the Data UI & tracked in VA GitHub applies to facility QA too. 

We have missing clinics & need to make sure any ways of catching errors like that are captured across DEV QA, TEST QA, PROD QA.

**Comment by staceypark** [comment]
Documentation can be found TeamPSD > quant_workgroup > splash_pages

**Comment by lzim** [comment]
**Discussed at team_time 8/10** 
Cross-ref #627 (But, may be a closed card soon, if there is no longer a facility and data distinction in Power BI).

@staceypark 
@lijenn 
@dkngenda 

**We want to follow our QA approach for Research like this:** 
https://lzim.github.io/teampsd/11-track-issues-features.html#contribute-to-an-r-notebook

**- VA GitHub - Recommends Enterprise GitHub if you're working directly with the EHR data**
https://department-of-veterans-affairs.github.io/github-handbook/guides

**Our VA Enterprise GitHub Repos**
https://github.ec.va.gov/

**Comment by lzim** [comment]
@staceypark  What is there to do on this as we orient Jeff?

**Comment by staceypark** [comment]
I'm going to close this as we are not/have not been updating the facility files in awhile. Our current documentation last reviewed as part of the data UI monthly update is sufficient for the PBI work.
