### ISSUE TITLE
Green Post 2018.07.18

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#63]
Please review Green post 2018.07.18 email and provide feedback by Friday 7/20:

https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/pre_post_emails/green/green_post_2018.07.18.docx

**Comment by TomRust** [comment]
love it.  I hope they follow through, and actually run their own experiments in the interim.

**Comment by branscombj** [comment]
looks great!

**Comment by staceypark** [comment]
thanks for the review! sent to team
