### ISSUE TITLE
9/9 R01/IIR Patient Panel and Provider type

### ISSUE THREAD

**Issue by saveth** [lzim/teampsd#630]
**1. Add description:** 
From the Quant meeting today (https://meet.lucidmeetings.com/meeting/225810), create new graphs/analysis:

1) Examine the number of patients by CBOC/VAMC
2) Type of Provides by CBOC/VAMC

<< Paste screenshots here>>
 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by saveth** [comment]
@lzim This information is in the current slide deck (Eligibility_pres_2019Sept_initiate_noAUD.html) as of Sept. 6, 2019 on slide 17-19. The CBOC are substantially smaller than the VAMC with an average patient size of ~300. If just barely have enough clinics in our study design to capture a 5% difference.

**Comment by lzim** [comment]
@saveth 

Thank you!  This is a very important finding that we did not have before.
I’m very glad Craig mentioned this, and that you were able to evaluate it.

My understanding of the SOP is that we won’t close issues until they have been reviewed by the requester.  

I’ll take a look at slides 17-19, see if I have more questions, and then run it by the Craig and the co-Is, ideally next week before we meet again!

Thanks, and have a great weekend 🍹

**Comment by ritahitching** [comment]
Done - need @lzim to confirm if the issue can be closed. 
Cluster size in the slide deck - site list is complete

**Comment by lzim** [comment]
Yes, this seems done 😄
