### ISSUE TITLE
Evaluating REDCap survey results for MTL Facilitator Fidelity

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#633]
**1. Add description:** 
In relation to the solution for #483, when using REDCap for both the MTL menu and Facilitator fidelity ratings, we use a specific survey queue logic to enable the survey completers to be able to look at the results live for their specific needs.

For example, for the MTL menu, this allows the clinic team to look at their own survey menu results for their team and no other teams.

For the facilitators, this allows them to look at the aggregated results of the fidelity ratings for their specific team for the specific session.

However in order to support this queueing logic, we have to create a distinct survey for each instance across all of the combinations (@saveth I can also show you in person what I mean by this through REDCap).

For example, for the facilitator fidelity survey:
1. in survey 1, they choose team name (team 2 or 4)
2. in survey 2, they are directed to either team2 or team4's survey to choose the session number based on how they answered survey 1.
3. in survey 3, they do the actual fidelity ratings for the specific session depending on what they answered in survey 2. Meaning by this third level, there is a specific survey for team2_session01, team2_session2, team2_session3...

So, for just doing the summer MTL facilitator training session for 2 teams, this queue logic needs 27 distinct surveys.

*Ultimately, to assess fidelity across the trial we would want to aggregate & evaluate results across all of these distinct surveys. @saveth we need a backend code/system for doing this*
 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by lzim** [comment]
@staceypark and @jessfroe 

Stacey, Rita and I discussed this at the end of day #hqhuddle. 

Please cross-ref #613 and #631 and we’ll talk about this first this AM Friday 9/6/2019 **BEFORE** propagating.

Thanks!

**Comment by staceypark** [comment]
@saveth our first test of evaluating results will come when the facilitation training ends in the beginning of November. We can likely start scoping toward end of October.

**Comment by ritahitching** [comment]
Already have the data but need to download data and then provide to @saveth

**Comment by ritahitching** [comment]
@lzim @saveth @staceypark @ritahitching 

- Final issues will be updated on site selection is finalized

**Comment by staceypark** [comment]
@dlounsbu @jessfroe @lzim @staceypark will have a meeting to do CFA with these results.
@lzim should we try to meet before the new year?

**Comment by lzim** [comment]
> @dlounsbu @jessfroe @lzim @staceypark will have a meeting to do CFA with these results.
> @lzim should we try to meet before the new year?

- Let's try to meet the week of Jan. 6th

**Comment by anthonycpichardo** [comment]
Did the above meeting take place? Is quant analysis still needed on this?

**Comment by staceypark** [comment]
I believe the analyses / evaluation needed for these results are all being done by @dlounsbu and we are tracking it as part of the r01 protocol manuscript analyses #559. As such I'll cross-ref it there and close this here.
