### ISSUE TITLE
9/6: New Team PSD project > psych_tracker

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#634]
1. Issue Workflow for **psych_tracker** project 
- [ ] propose to use the same issue
- [ ] create a label & 
- [ ] have James triage **psych_tracker** issues from the **issue_tracker** to the **psych_tracker**

@jamesmrollins this was #3 in “New Business” for today’s Support Workgroup Leads meeting. However, we didn’t get to due to the Andon discussion (prevention & policy).

- Basically, I talked this through with @staceypark and I can create a new project tomorrow. But, wanted to check out the issue, label, and SOP outlined above.

Thanks!
 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by jamesmrollins** [comment]
@lzim thank you.  I am a little unclear about the first three items on the checklist in the issue template.  Let me confirm your meaning:

1.  We will use the same issue disposition determination process currently in use for issues.  All new issues will go into the issue_tracker triage section.
2.  James will be the point person for determining priorities of items in the issue_tracker triage section and then move them to the psych_tracker.  BTW, why not ptool_tracker? 
3. We will use the same SOP for entering title information, deadlines and such as MTL.

Regarding the sections of the psych_tracker, may I recommend the following sections:

1. work_break_down - determine the impacts of the "ask" in terms of cost, time, etc . . . 
2. validated_actions - queue to sort the importance of actions underway.
3. in_progress - queue of activities under way.
4. completed - as read
5. closed - as read

Regarding labels, I would hold off on this for a while and let the situation develop.

I will ask Jeanne Gabriele and Chris Crowe to establish GitHub accounts and train them in on the use of this method to govern interaction between the MTL and Ptool teams. I will also look at how we should be using OSF to share documentation.  Right now, I will take the lead on making sure that documents find their way to the repository. The only thing still up in the air is note-taking and meeting recording.  I am happy to see that this is done, but we lack a common format (such as Lucid). I think we agreed that during our next "all together" meeting, we would put this on the agenda for discussion.

**Comment by lzim** [comment]
Hi James,

Sorry about the lag, it’s been a full day!
This is my first volley of thinking through the SOP, so we can get it set up.

> @lzim thank you. I am a little unclear about the first three items on the checklist in the issue template. Let me confirm your meaning:
> 
> 1. We will use the same issue disposition determination process currently in use for issues.  All new issues will go into the issue_tracker triage section.
- Right, that is what I am proposing

> 2. James will be the point person for determining priorities of items in the issue_tracker triage section and then move them to the psych_tracker.  BTW, why not ptool_tracker?
- Specifically, all Team PSD work group leads are still responsible for triage & priorities overall.
- But, you would pull any psych_tracker issues into that tracker.
- While “ptool” was our working name for this for a while, I worry that “ptool_tracker” is not descriptive enough, potentially even sounds “bad” and the “psych_tracker” may be preferred, esp. as online resources start to get developed around it. I can answer more questions if you have them, on our Monday call.

> 3. We will use the same SOP for entering title information, deadlines and such as MTL.
- Right.

> Regarding the sections of the psych_tracker, may I recommend the following sections:
> 
> 1. work_break_down - determine the impacts of the "ask" in terms of cost, time, etc . . .
> 2. validated_actions - queue to sort the importance of actions underway.
> 3. in_progress - queue of activities under way.
> 4. completed - as read
> 5. closed - as read
- This sounds fine to me, to be revised with Chris’ input as needed. 
- Whereas Team PSD HQ helps to review the other Team PSD trackers, my hope is that you would manage **psych_tracker** and/or get additional project management help from Chris’ team.


> Regarding labels, I would hold off on this for a while and let the situation develop.
- @staceypark and I believe that it will be very helpful to have a specific label for issues associated with this project. I would prefer to start using a label right away to clearly denote what falls under this part of the NCPTSD contract with Takouba/Praxisanalytix for filtering and tracking.

> I will ask Jeanne Gabriele and Chris Crowe to establish GitHub accounts and train them in on the use of this method to govern interaction between the MTL and Ptool teams. I will also look at how we should be using OSF to share documentation. Right now, I will take the lead on making sure that documents find their way to the repository. The only thing still up in the air is note-taking and meeting recording. I am happy to see that this is done, but we lack a common format (such as Lucid). I think we agreed that during our next "all together" meeting, we would put this on the agenda for discussion.
- This all sounds good. I would propose to change the OSF project from “Ptool” to “psych_tracker” too. These are recommendations, we can discuss, however.

Thanks!
Happy Friday 🌿

**Comment by lzim** [comment]
Are we ready to close this particular issue, @jamesmrollins ?
