### ISSUE TITLE
PSY Model Diagram "i" information

### ISSUE THREAD

**Issue by dlkibbe** [lzim/teampsd#638]
**1. Add description:** 
Psy Model - I'm logged in to my individual world and Gayle was logged into her individual world and noticed this issue with the "i" information. 
It appears the descriptive text in the "i" information at the very bottom of the screen for the "Continuing Treatment Rate (After 3 Months) from Visit 2 to 7 is from the "i" box should be switched with the "i" information to the right - it says "The number of patients who continue treatment after completing eight or more psythotherapy visit within their first three months. (pts/wk)" when it should say "The number of patients who continue treatment after completing two to seven psythotherapy visits within their first three months. (pts/wk)" (again this text is in the box to the right and it should be in the box to the left). I'm logged in remotely through the VA and I don't think my screen shots will paste.
 

**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by jamesmrollins** [comment]
Hi @dlkibbe , it should be fixed now.  I was backwards in the model-popup-information.xlsx file.  Thanks, James

**Comment by dlkibbe** [comment]
Thanks @jamesmrollins

**Comment by staceypark** [comment]
@dlkibbe can you check if this is fixed correctly in the sim and click "close" below if the issue has resolved?

**Comment by staceypark** [comment]
May have video dependency depending on which 'i' information we show in the videos for PSY.

**Comment by lzim** [comment]
> May have video dependency depending on which 'i' information we show in the videos for PSY.

@staceypark @jamesmrollins 

Since the “i” information is meant to be able to by dynamically updated, 
- [ ] @staceypark please make a card to create team instructions for updating “i” information text to the **document_team**

Cross-ref #705

**Comment by staceypark** [comment]
tracked in #475 and #604
