### ISSUE TITLE
9/17 Cannot upload screenshots using snipping tool onto GitHub Issue 

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#640]
1. We have been using the Snipping Tool to capture screenshots for pasting GitHub issues. Recently we noticed that this no longer works.

Also, Issue #357  relies on VA clinicians being able to use this screenshot function.

 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by staceypark** [comment]
@holbrooa can you check this issue from Boston and @saveth can you test from virtual login?

**Comment by saveth** [comment]
@staceypark just tested, the snipping image won't paste

**Comment by holbrooa** [comment]
Nope. Doesn't work for me either.

**Comment by lzim** [comment]
UPDATE **TeamPSD Workgroup Leads** (and Team PSD members documenters)

@staceypark @ritahitching @jamesmrollins @TomRust @jessfroe @saveth @holbrooa @branscombj @dlkibbe 

FYI: We are not currently able to use any file uploads on GitHub, this includes upload of model files (.mdl) @TomRust or anything else, including snips. _That means in issues, or in pull requests._

NEXT STEPS:
1. We captured images of the browser inspector for both Issues and Pull Requests
2. @staceypark will be alerting GitHub to see if there is a fix on their end, if not, we will pursue a fix on our end within VA.

Cross-ref: #642 **#hqhuddle Week of 9/9**

**Comment by jamesmrollins** [comment]
@lzim @staceypark  I called the help desk on this one to see if it is a security policy.  It is not - in fact the help desk uses it for troubleshooting too.  I can paste and upload into GitHub just fine, so I don't believe it is a Github issue.  A working hypothesis is a security policy that is preventing the use of these functions. The other theory, according to Microsoft, is a corrupt registry.  However, I think the first is much more likely.

**Comment by lzim** [comment]
Thanks @jamesmrollins

@staceypark please keep us posted on your progress with this one 1) via GH, then 2) VA. We all use this several times each day.

- Very promising that it can/will be resolved quickly if VA NSD uses GH for this same purpose.

**Comment by staceypark** [comment]
Issue seems to have self-resolved. 
@jamesrollins please close your helpdesk ticket asap. I cannot close it for you.

**Comment by jamesmrollins** [comment]
@staceypark Need NHD number please 😁

**Comment by jamesmrollins** [comment]
@lzim @staceypark Ticket is now closed. 👍
