### ISSUE TITLE
9/17: Demo Site Not Allowing Login

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#644]
**1. Add description:** 
I was trying to access the MTL demo but kept running into the error when trying to play the simulation: “The expiration date for group(account=va, project=va-psd-demo, group=team_mtl_demo-jan-2019) has passed”

<< Paste screenshots here>>
 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_  **16 hrs.**

**Edit the due date (if necessary)**

**Comment by jamesmrollins** [comment]
@lzim @staceypark @jessfroe I THINK, but am not sure, this may be a duplicate record issue.  If a user registers for a demo session, and the days expire, you cannot force more days in the Admin screen.  The user has to be deleted from the Admin screen AND Epicenter End Users.  Then they can register again.  I have made these correction and have asked Dexter to try again.  I will inform you of the results.  Thanks, James

**Comment by lzim** [comment]
@jamesmrollins and @staceypark (removing Jessilyn)

- Dexter and I just went through this again, and I mistakenly did not catch him before he re-registered under the 3 day testing window.

I propose we do this:

1. Prompt people to alert them that they want to enter a course code if they have one, and/or
2. Prompt to alert them that it will time-out after 3 days if they do not have a course code, and/or
3. Prompt about how to access their **demo account** later*
-_Note_: I did set up a branded link for this: https://forio.com/app/va/va-psd-demo/login.html already at mtl.how/demo_login.

*In addition, Dexter learned about this outside of course, so he did not have the guidance about how to log-back in after registering. So, he logically registered again.

Context: 
- When we did the national Cyberseminar series in May, we provided guidance on how to navigate to the course log-in, without re-registering, but this could possibly be in the prompt too?
- Many folks may check this out outside of a course...

Summary of possible recommendations
- We could also extend the 3 day demo window if we think it's too short.
- We could use pop-up alerts.
- We send a registration email the user, so that they are instructed that way instead of a pop-up.

**Comment by lzim** [comment]
NOTE @jamesmrollins 

It is a bummer that we're having a GitHub screenshot problem...:cry:

But, I also note that Dexter doesn't have the warning that he's having a user time-out error until he's well into the Sim UI.

- Also fun...
- We found that when I logged into PROD at the same time, as myself, it switched Dexter's instance in a separate browser window of Chrome, over to me in my Individual world.

- Screenshots will be forthcoming...

**Comment by jamesmrollins** [comment]
@lzim can you verify the captions for what is going on in these captures please?  My guesses are below.  We can also discuss in Thursday's meeting. I agree, I think we need better prompts for the user so they can understand what is going on with respect to seminar codes and having links to log back in.  I think that a pop up and an email would probably work best.

This is what happened when you logged in.  But I see in the admin panel that you do not have a demo account set up. Did you delete it?
![image](https://user-images.githubusercontent.com/30132017/64665614-0ded6780-d408-11e9-9606-27b3aa9e17e3.png)

This is what Dexter saw when he tried to login after re-registering today.
![image](https://user-images.githubusercontent.com/30132017/64665636-1d6cb080-d408-11e9-84e4-3948dd5f6346.png)

This is the inspect window for Dexter's session.
![image](https://user-images.githubusercontent.com/30132017/64665744-7c322a00-d408-11e9-99ea-93176a4fca37.png)

We will check it out.

**Comment by lzim** [comment]
@jamesmrollins

You are correct re: screenshot 2 and screenshot 3.

The first shot is related to my comment that
1. Dexter logged in to DEMO in Chrome on my VA machine
2. We ran into errors on DEMO, and did not log out.
3. On the same VA machine, in a separate Chrome window, I logged into PROD Team 4 Individual World as myself.
4. When we toggled back to the DEMO page, it had adjusted Dexter’s DEMO login instance to user Lindsey Zimmerman _in DEMO_ (as you can see in the URL), even though I didn’t login there and don’t have a current DEMO login.

https://user-images.githubusercontent.com/30132017/64665614-0ded6780-d408-11e9-9606-27b3aa9e17e3.png

**Comment by lzim** [comment]
@jamesmrollins and @staceypark

- **Are there any fixes to the DEMO confusion that could be implemented _before_ we present at SIRC on Saturday?**

**Comment by jamesmrollins** [comment]
@lzim **Yes**.  The site should be working properly now.  The Group, to which everyone is assigned, had expired in July (see below).  We reset it to never expire.  I tested it this morning and it works ok.  We also updated it to the latest sim version, and have added these sites to our update checklist - so that should never happen again either.

![image](https://user-images.githubusercontent.com/30132017/64709850-cd273a00-d46b-11e9-994a-03991442ed05.png)


**Still Outstanding:**
1. Lindsey cross-page login issue - may I use your login password for the team4_ind group/world to see if I can recreate this issue?
2. Increase demo expiration time. How much time do you want to give them? As a temporary workaround, we could do this by hand as they register. 
3. A link on main page, a pop up and email with instructions on how to return to the mtl demo sim page.  In the meantime, we can give folks at the SIRC conference these instructions manually, as you did before at the Cyberseminar Series in May.

Also please note that you and Stacey are registered in the Demo project groups as facilitators using your va.gov emails.  This means anytime you navigate to mtl.demo, you will get the admin page. If you want to get into the DEMO simulation, you will need to register with a different email address.  Then I would go in and set my expiration date to 180 or something like that.

**Comment by lzim** [comment]
@jamesmrollins & @staceypark

> Lindsey cross-page login issue - may I use your login password for the team4_ind group/world to see if I can recreate this issue?
- yes

> Increase demo expiration time. How much time do you want to give them? As a temporary workaround, we could do this by hand as they register.
- what if we start with two weeks for now?

> A link on main page, a pop up and email with instructions on how to return to the mtl demo sim page. 
- great 👍🏾 

> In the meantime, we can give folks at the SIRC conference these instructions manually, as you did before at the Cyberseminar Series in May.
- Right, I will.

**Comment by lzim** [comment]
@jamesmrollins

- I was rethinking the issue of _not_ asking for names. Given some of the registration confusion we’ve had, I started to wonder if having a name that we can associate with active/registered emails may sometimes be key to helping people who get stuck in some way. 
- Maybe I can ask you about that in person today!

![image](https://user-images.githubusercontent.com/30132017/64828129-fdf69480-d57b-11e9-8b7d-bee1aab15e99.png)

**Comment by jamesmrollins** [comment]
Hi @lzim .  Sorry for the confusion. The drawing above is actually missing the name fields.  We currently collect names, so no worries.  I will update the drawing.  See you in a little while.

**Comment by lzim** [comment]
@jamesmrollins

Okay! So they were just missing. I noticed that, but had approved the design, so I wanted to update that I’d like to keep the name fields.

**Comment by jamesmrollins** [comment]
@lzim  and @hirenp-waferwire FYI - The issue I reported above where the web pages were not loading correctly was resolved.  If you ever have an issue where the web pages are cross-loading, you can resolve it by clearing your cache of cookies.  Sometimes the cookies get corrupted and cause abnormal browser behavior.

**Comment by jamesmrollins** [comment]
@hirenp-waferwire please see below for MTL DEMO site changes:

1.  Changes to the MTL DEMO Website:

![image](https://user-images.githubusercontent.com/30132017/64930836-18817580-d7e9-11e9-888e-41041b20190d.png)


2. Changes to the Registration Pop Up.  Please change the default time for access to 14 days for a registration, and 90 days for a coded registration.  When user clicks "Run" please send an email appropriate for the type of registration.  Please edit the text as shown in the highlights below:

![image](https://user-images.githubusercontent.com/30132017/64930662-c4c25c80-d7e7-11e9-8e95-8e41df98ce12.png)

3.  Regarding emails for 2 week and 90 day registrations - please send email as shown below:

![image](https://user-images.githubusercontent.com/30132017/64930752-72357000-d7e8-11e9-869b-0bf8532262fe.png)

4.  Regarding DEMO Sim UI landing page Pop Up - Please amend as shown below:

![image](https://user-images.githubusercontent.com/30132017/64930784-a4df6880-d7e8-11e9-844e-0e27ced62b61.png)

**Comment by jamesmrollins** [comment]
@hirenp-waferwire this looks good! Please see minor edits below.

1.  MTL Demo Registration eMail (this applies to both 2 week and 90 day versions).

![image](https://user-images.githubusercontent.com/30132017/64976024-342a6180-d865-11e9-9e92-4b6cc79c0f05.png)

2.  Since a course code was offered, the expiration should be 90 days.  The email should also reflect this period of expiration.  Is it possible to give an actual expiration date as a column in the Admin screen and in the email to the end user?

![image](https://user-images.githubusercontent.com/30132017/64976693-cd0dac80-d866-11e9-8f0d-df736f76e60b.png)

3.  The type in the Registration Pop Up should be normal.  _Modeling to Learn_ should be italics.

![image](https://user-images.githubusercontent.com/30132017/64977150-b61b8a00-d867-11e9-9309-ffc2c0ffa8d1.png)

**Comment by lzim** [comment]
@jamesmrollins & @staceypark 

I was just reviewing the Google Analytics traffic and session data for mtl.how/sim (aka PROD).

All of these moves here are a step in the right direction for DEMO, but I’m wondering if we would also benefit from gaining data-based insights about how interacting with mtl.how/demo is working for users.

**Comment by jamesmrollins** [comment]
@lzim I am not sure what you mean by mtl.how/DEMO.  You mean the information website, or the SIM UI?  I thought we had the DEMO SIM UI covered. So I may be answering my own question. . . 🤔

**Comment by lzim** [comment]
> @lzim I am not sure what you mean by mtl.how/DEMO. You mean the information website, or the SIM UI? I thought we had the DEMO SIM UI covered. So I may be answering my own question. . . 🤔

@jamesmrollins When I check the Google Analytics dashboard I only see if for mtl.how/sim (PROD) right? Not mtl.how/demo (DEMO)?

FYI: @staceypark

**Comment by jamesmrollins** [comment]
@staceypark  @lzim Ok, I see, you want to track stuff on the DEMO Sim UI webpage.  Got it, I will get it done.

**Comment by jamesmrollins** [comment]
@hirenp-waferwire please see below for final adjustments before promotion to PROD.  Also, will you investigate and give me an estimate to add google analytics to the DEMO Prod website and SIM UI? ~Thanks, James

![image](https://user-images.githubusercontent.com/30132017/65193206-2e807780-da2f-11e9-9b88-add24df8eea2.png)

**Comment by jamesmrollins** [comment]
@lzim I added this website to the Google Analytics page last night.  

@staceypark .  The modifications for this issue have been tested and are now in PROD. Recommend we open a document card to update the cheatsheet instructions for this page to add in the new link functions and describe the expiration date.

**Comment by lzim** [comment]
> @lzim I added this website to the Google Analytics page last night.

@jamesmrollins Great, thanks!

> @staceypark . The modifications for this issue have been tested and are now in PROD. Recommend we open a document card to update the cheatsheet instructions for this page to add in the new link functions and describe the expiration date.

- [ ] Yes, we need a “how to”  **document_team** card. Cross-ref #705

**Comment by staceypark** [comment]
@lzim to clarify, before I add cards:
Do you mean an "epicenter how to" card, or a card that tracks all of our "how to" needs?

The team/demo backend management information doesn't exist in any cheatsheet so far.
I would add this documentation need to the category of HQ training (#475). I don't think we want anyone else potentially making changes to our public team websites.

**Comment by lzim** [comment]
@staceypark

Hopefully the **document_team** metacard is tracking all the stuff that needs “how to information.”

Agreed, that we don’t need it to be public how to update DEMO or TEAM, but do need a guide. There are more changes that we/I could make, if I had the instructions.

**Comment by staceypark** [comment]
@lzim ok tracked! We can close this issue now.

**Comment by lzim** [comment]
@staceypark 

What about for Dexter’s user?

**Comment by lzim** [comment]
> @staceypark
> 
> What about for Dexter’s user?

@jamesmrollins confirmed this is resolved 👏🏼
