### ISSUE TITLE
Master brochure for MTL-Live sessions 4-12

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#65]
This is our "generic" content to cover all of the MTL Live sessions that involve running experiments with the Sim UI. https://github.com/lzim/teampsd/blob/master/ees_workgroup/mtl_live/master_brochure.rmd

**Comment by lzim** [comment]
@branscombj @dlkibbe @justinspears1 

I committed the changes we discussed in today's meeting in pull request: https://github.com/lzim/teampsd/pull/67/commits/e5caf817a8cf3b0453dbe1253247d6074bd27db4

Thanks!

**Comment by lzim** [comment]
Hi @branscombj @dlkibbe and @justinspears1 I'm going to close this here, and start a fresh issue for tasks related to EES accreditation. Thanks!
