### ISSUE TITLE
ASAP MTL Demo: Learning Mode not updated at mtl.how/demo

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#663]
**1. Add description:** 
@jamesmrollins Dexter and I were in **demo** and noticed that the **MM** module had the old **Learning Mode.**
- Haven't tested CC

**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by jamesmrollins** [comment]
@lzim @saveth @staceypark @TomRust @jessfroe @branscombj @ritahitching the versions of the app for the DEMO site are behind. I plan to get this updated as my first order of business tonight.  I apologize for any inconvenience.

**Comment by jamesmrollins** [comment]
@lzim @saveth @staceypark @TomRust @jessfroe @branscombj @ritahitching the CC and MM models are now updated in the DEMO site.

**Comment by staceypark** [comment]
@lzim I believe this can be closed now. Did you have any other questions?

**Comment by lzim** [comment]
> @lzim I believe this can be closed now. Did you have any other questions?

@staceypark Yes, the questions that remain are:
- [ ] What documentation is needed for this - track in the **document_tracker**
- [ ] Who has tested this in DEMO mode?  I have not.

**Comment by jamesmrollins** [comment]
@lzim I tested these and they are in place - that is why I moved to "done" column.  Nevertheless, always appreciate a second set of eyes 👀

**Comment by staceypark** [comment]
@lzim @jamesmrollins 

No documentation needed because we don't have any documentation specific only to the demo site. The Learning Mode pop-up update in general has already been tracked in our products.
> What documentation is needed for this - track in the document_tracker

Just tested in Demo and matches most recent Learning Mode pop up. But...
The instructions on both direct the learner to look at a tab of the Team Data Table at mtl.how/data which makes no sense for people signing up for a Demo account. Are we framing this as "you're playing with something temporarily without full context so there will be questions and limited resources/functions" or should the instructions actually tailor to Demo?

> Who has tested this in DEMO mode? I have not.

**Comment by staceypark** [comment]
@lzim thoughts on my comment above / can we close this?

**Comment by lzim** [comment]
@staceypark 

I think we need a cheatsheet that helps folks navigate the DEMO

**Comment by jamesmrollins** [comment]
@lzim FYSA
@jamesmrollins will investigate a way to tutor users that are entering into the DEMO site for the first time.  The tutor will appear each time at login, until dismissed.

**Comment by staceypark** [comment]
@jamesmrollins any updates on the tutor function?
And should we either start a new feature card for that or update the title on this card and move it to the feature_tracker?

**Comment by staceypark** [comment]
@jamesmrollins created a fresh feature card for the tutor function
#775 cross-ref
