### ISSUE TITLE
RQDA r21_master projects code changes (DUE 9/12)

### ISSUE THREAD

**Issue by jessfroe** [lzim/teampsd#664]
@dlounsbu @swapmush @teampsdkathryn @lzim 

Hi Qual workgroup, 

Per our conversation in our meeting Tuesday 09/10, we need to update the fidelity codes within the **master_r21_train** and **master_r21_test** RQDA projects. 

Instead of using the likert scale (1 - 5) codes, we are instead utilizing a **yes/no** dichotomous rating scale. 
I (@jessfroe) will work on updating the projects by **COB today** and will let the workgroup know when I have finished, so that we are all able to code with the new rating scale.

Thanks everyone!! 😸

**Comment by staceypark** [comment]
Looks like this was finished, closing issue.
