### ISSUE TITLE
Due TBD: Data UI adaptation to CCI - rollout unknown in FRE

### ISSUE THREAD

**Issue by holbrooa** [lzim/teampsd#667]
We don't know exactly when yet, but CDW is changing the way data are stored in a significant way. Without getting into technical details, all existing queries will work, but there might be major performance hits.  They don't have a date for the rollout on the FRE that we're using, but it will be within the next couple months, I think. They are rolling it out onto the first server this Saturday 9/14, with other servers (FRE included) some time later.

I believe this change will make far-reaching queries like the ones we've been doing for research data more efficient but specific operational queries like the ones the data UI uses will be less efficient. No way to know for sure until it happens. I will likely need to change the queries in the data UI somehow to mitigate this performance decrease.

**Comment by staceypark** [comment]
First rollout did occur on 9/14. No other updates have come for other servers yet.

**Comment by ritahitching** [comment]
@holbrooa Followed the link above and do not see any additional information as to when changes to the servers might occur.  Is that your view too?

**Comment by holbrooa** [comment]
Yeah, but I can't actually follow the link right now, because I'm back in permissions purgatory. But to my knowledge, this rollout is still TBD.

**Comment by anthonycpichardo** [comment]
@holbrooa Hi Andrew, was this completed? Is this related to the sql server partitions.

**Comment by anazariz** [comment]
This is a non-issue. This ticket has to do with the date partitions in CDW.  Andrew has already implemented dates in the scripts that take advantage of the partitions.  

@anthonycpichardo  I recommend that we close this ticket. I will include the date formatting that will take advantage of the partition in my code documentation (front/back-end).

**Comment by anthonycpichardo** [comment]
Closing this ticket as it has already been resolved per @anazariz's research
