### ISSUE TITLE
wk3 R21 Tests of Specific Aims xbar charts and pcharts

### ISSUE THREAD

**Issue by saveth** [lzim/teampsd#674]
4/3/20 Update: Need to generate the xbar charts for the dataset Andrew provided that was used for the p charts. Barring any result from #1248 that would lead to a change in data, then both the xbar and pcharts would need to be remade

________________________________________
In order to help to help clarify the request in #424, this issue is broken out into a number of tickets to differentiate the various "asks" and "due date".

Once @holbrooa provides the data #672, p-charts for the R21 clinics need to be produce with the following specs:

1. EBP Reach for Initiate and Dose as defined in #571  with the following:

|Condition | Reach |
|-- | -- |
|with AUD | Omnibus EBP Reach |
| | Omnibus EBPsy Reach |
| | Omnibus EBPharm Reach |

2. With generic clinic labels for the following clinics:
-  Clinic 1, 
- Clinic 2, and
- "other" VAPAHCS

3. Baseline time period for the clinics:
Clinic 1
- Pre: April 2014-March 2015 (@lzim while this is the true precondition, we have been using the mixed condition Nov 2014 - Oct 2015 since data didn't exist until Nov. 2014)
- Post: Oct -Sept 2019
Clinic 2
- Pre: Oct 2016-Sept 2017
- Post: Oct-2018-Sept 2019

<< Paste screenshots here>>
 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [x ]   Other (describe)

_Add estimated person-hours to complete:_ 1 week for p-chart
To accomplish this task: #672 must be closed prior to starting this task. This ticket will require: two sets of code:
1) 2-3 days: code to generate the overall dataset, and
2) 2-4 days:  create new code for graphs similar but different from previous p-charts to to be used in the grant/ R21 tt report

**Edit the due date (if necessary)**

**Comment by saveth** [comment]
@lzim Can you please clarify the pre/post -conditions for the R21 sites? In #424, you listed:

Clinic 1
- Pre: April 2014-March 2015
- Post: Sept-Aug 2019

Clinic 2
- Pre: Oct 2016-Sept 2017
- Post: Oct-2018-Sept 2019

_Do you mean?_
**Clinic 1**
- **Pre: April 2014-March 2015** (we have been using the mixed condition Nov 2014 - Oct 2015 since data didn't exist until Nov. 2014)
- **Post: Sept 2018-Aug 2019?** (Did the training with this site take more than 3 years?)

**Clinic 2**
- **Pre: Oct 2016-Sept 2017**
- **Post: Oct-2018-Sept 2019**

**Comment by saveth** [comment]
In the support workgroup meeting today we decided we to change the date to 11/1 to indicate when we need the preliminary p-chart graphs with the new data definitions for the NIH R21 progress report.

**Comment by staceypark** [comment]
@holbrooa is going to create a button for pulling fresh pchart data in a new excel workbook.
For our sites for R21, we should have all the data we need to create pcharts from the 2014 and beyond monster pull he did.

@holbrooa I missed the xmr update during the morning call. Do you have an update on that piece?

**Comment by staceypark** [comment]
@staceypark 
- [ ] schedule AH, TR, & LZ for floors
- [ ] schedule LZ & TR for ISTSS prep

**Comment by holbrooa** [comment]
The button I'm going to add is just for new data. We'll still need @saveth code for creation of the actual charts. So whichever kind of chart you want, it's the same data pull. Also, for the purpose of that data pull, I think I'll need a meeting with @saveth or something to identify exactly which columns I need to update. If it's all of them, I guess that's doable but sort of a pain.

**Comment by saveth** [comment]
@holbrooa are you available to look at the data to get your questions answered?

**Comment by saveth** [comment]
@holbrooa We haven't used columns G-S (PatCount-Adjunct) nor does it seem relevant to the EBP calculations for AIMS 1.  Does this help you with rewriting the code for the p-chart?

With regards to @staceypark question, will the xmr data be in the same file or a separate file?

FYI: @saveth @ritahitching @lzim

**Comment by holbrooa** [comment]
@saveth Yeah, any time today or tomorrow is fine for me. Tomorrow works slightly better, if you have no preference. 

I believe the plan is to have a separate file, because they want me to build the data pull so that it can automatically update with current data.

**Comment by holbrooa** [comment]
@lzim @staceypark @ritahitching 
I will write some code to pull intake -> first ebpsy template by patient and put that on a separate tab when I make the updateable comparator dataset I described to Stacey and Rita. XmR doesn't make any sense in this context - I think you mean X bar R. But I don't really have time to worry about the chart part of this, because the data pull doesn't even exist.

@saveth 
We've had some discussions about transitioning data from excel files to server tables. I can go ahead and put a copy of the comparator dataset up there, though I don't think I'll have time to make it updateable. Should be easy enough for someone to figure out from our other code, though. Ultimately, it'd be better to have patient-level information up there and do all the data processing in R, as we've talked about a few times. If you end up going that route, the code that generates the comparator file itself should be adaptable to that purpose. And that would definitely be my recommendation, though it'd take a lot of effort/time to implement (which is why we haven't done it).

**Comment by staceypark** [comment]
For r21, going back to beginning of 2014, we will look for unique patients in sta6a with CPT code for first intake on diagnoses of interest (AUD, Dep, OUD, PTSD) followed by the first instance of an EBP (first initiation template for EBPsy or first script for EBPharm) and calculate number of days in between. 
- Other intakes and templates that are not the first ones will be ignored.
- More than likely this will be number of days to first EBPharm since we are using OR logic to EBPharm or EBPsy.
- Ignore patients who have 2 year gap between intake and template, because they would be treated like a new patient by then.

**Comment by saveth** [comment]
@holbrooa Do you have any updates on the data?

FYI: @saveth @staceypark @ritahitching @lzim

**Comment by holbrooa** [comment]
Yeah the sql query is written to pull this. It's in quant -> sql_queries. Called "intakeToEBP" It doesn't go as far as aggregating by month, because I feel like there are a couple ways you might want to do that, so instead it leaves it at the patient level. Should be pretty self-explanatory once you see the output.

**Comment by staceypark** [comment]
@saveth is almost done updating p chart codes based on new EBP reach definitions.
She will follow up with @holbrooa after to get the xbar chart data in xlsx form and then discuss with @lzim to scope that work.

**Comment by ritahitching** [comment]
@lzim @saveth @staceypark @ritahitching 

- Final issues will be updated on site selection is finalized

**Comment by staceypark** [comment]
@saveth 
Once you are done reviewing the protocols for R01 & IIR, can you turn to producing EBPharm & EBPsy pcharts for the r21 sites for @lzim to present at NIDA on 1/22 (Lindsey OOO 1/21-1/24)

**Comment by anthonycpichardo** [comment]
@staceypark Just want to verify that the ask here is still to generate xbar charts using the existing data

**Comment by anthonycpichardo** [comment]
Currently validating data then xbar charts can be generated.

**Comment by anthonycpichardo** [comment]
@dkngenda  @lzim Action items:
 
- [ ] Examine the numerator and denominators for the pchart values

- [ ] Double check UCL and LCL

- [ ] Add the grey bar for the post sections

**Comment by anthonycpichardo** [comment]
@lzim @dkngenda 

For the EBP Cohort question, those 3 charts are currently depicting the ratio of folks who completed a dose vs how many initiated one including AUD for EBPsy, EBPharm, and the Total Cohort:
```
 m_ebpsy_agg_prop_comp = nebpsy_AUD_num_dose / nebpsy_AUD_num_init,
    m_ebpharm_agg_prop_comp = nebpharm_AUD_num_dose / nebpharm_AUD_num_init,
    m_ebp_cohort_prop_comp = ebp_num_dose / ebp_num_init,
```
Do we want to keep these and improve the verbiage on the notebook or remove them?

**Comment by lzim** [comment]
> @lzim @dkngenda
> 
> For the EBP Cohort question, those 3 charts are currently depicting the ratio of folks who completed a dose vs how many initiated one including AUD for EBPsy, EBPharm, and the Total Cohort:
...
> Do we want to keep these and improve the verbiage on the notebook or remove them?

@anthonycpichardo  Can you help me understand how the ratio is being calculated in terms of months and unique patients? On conceptual level a numerator of EBP completers over a denominator of EBP initiators does make sense to me with exception of how it's handing the time frame??

**Comment by dkngenda** [comment]
@lzim  Pros and Cons for Fishers Exact Test vs Chi Squared Test
Fisher's exact test 
- Pros:  More accurate when the samples size is small (total sample size less than 1000)
- Cons:  Used for small samples and works for only 2 by 2 cross tabs in R
Chi-square
- Pros: Recommended  for large sample sizes where expected frequencies are >5.
- Cons: For small sample size, not as accurate as Fisher's exact test.

Refs:
1. [Biostats handbook by McDonald](http://www.biostathandbook.com/fishers.html)
2. [Statistical notes for clinical researchers: Chi-squared test and Fisher's exact test](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5426219/)

Since we made a decision to compare the overall 12 month initiation in the pre and post period instead of month by month change, we can stick to Fisher's exact test, as that means we will have one  2 by 2 table. Also, regardless of which test we use, the results don't change

**Comment by anthonycpichardo** [comment]
> > @lzim @dkngenda
> > For the EBP Cohort question, those 3 charts are currently depicting the ratio of folks who completed a dose vs how many initiated one including AUD for EBPsy, EBPharm, and the Total Cohort:
> > ...
> > Do we want to keep these and improve the verbiage on the notebook or remove them?
> 
> @anthonycpichardo Can you help me understand how the ratio is being calculated in terms of months and unique patients? On conceptual level a numerator of EBP completers over a denominator of EBP initiators does make sense to me with exception of how it's handing the time frame??

Sure, the duration is the total time period looking at month by month intervals.

If i remember correctly, we are only counting ebp template completion once per patient per template. I will need to double check this but I believe that to be the case.

**Comment by lzim** [comment]
@dkngenda 

Thanks for this. 

Right, the Fisher’s exact test for 12 month pre and 12 month post is what we proposed in the R21 and went through NIH peer review, so we must stick to our original plan. 

Do you have thought about how you planning to display the results?

**Comment by lzim** [comment]
@anthony and @staceypark 

Thanks Anthony, I believe we considered rules for how to handle this with Andrew, like once you’re a completer, do you continue to be counted as a completer over time? Or are completers removed at some point?

Anthony, please let us know what you find about implementation.

**Comment by anthonycpichardo** [comment]
> @anthony and @staceypark
> 
> Thanks Anthony, I believe we considered rules for how to handle this with Andrew, like once you’re a completer, do you continue to be counted as a completer over time? Or are completers removed at some point?
> 
> Anthony, please let us know what you find about implementation.

Sorry just to clarify, are you asking if completers are removed from the cohort?

**Comment by lzim** [comment]
@anthonycpichardo 

Well, not really just that. 

Based on review of the SQL used to create data used for this, I'm asking for a complete operational definition of the "cohort" over the cohort definitional time span. This is necessary for understanding cohort analysis and interpreting the calculation and relationship of numerators and denominators over time.

For this particular proportion, which is designed to understand a cohort of unique patients served by this sta6a over a specific time frame:
- What is the time frame that defines the cohort? And, given this answer, how are observations during a) prior periods of time addressed. Or b) subsequent periods?
- How are the a) numerator and b) denominator estimated? 
In other words, under what rules/conditions do unique patients enter/exit the denominator over time? Or, in any given month? Same thing for the numerator. Under what rules/conditions do they enter/exit?

Cases can help to illustrate how patient characteristics are being considered in the cohort analyses, and help readers/reviewers to understand how we're measuring whether patients progress to EBP completer status over the time period for the sta6a. But, basically, we need the details of what the code is doing. 

Tables can also help in which the rows define the cohorts and the column define the time and the proportion is calculated in each cell

cohort | time 1 | time 2
cohort 1 | % | %
cohort 2 | % | %

One case would be the patient who met a completer definition at some point over the time observation period, given the time observation how are they handled in any subsequent observations?

**Comment by lzim** [comment]
@anthonycpichardo It may also help to review the PSY cohort definition in the Data Notes tab of the Data UI.  

Let me know if this is making sense to you or if you could use more cohort analysis help from 
@dkngenda and I?

Here's another attempt to explain how we could display and understand the cumulative metric values for EBP cohorts depending on what you see is happening in the code:

All sta6a Omnibus EBP Initiators  | Time 0  |  Time 1  | ...  | Time n  |
EBPsy Initiate Cohort 1  (n = ??) | % complete |  % complete  | ...  |  % complete  |

EBPPharm Initiate Cohort 2  (n = ??) | % complete |  % complete  | ...  |  % complete  |

We need to define both the time and characteristics by which patients enter the "EBP Initiate Cohort" denominator. We should have their characteristics for EBP initiate, what we need is it's relationship to time. In other words, on the first observation of this cohort (Time 0) patients enter EBP initiate if they initiate EBP at that sta6a within one year prior to Time 0? Or, within two years prior to Time 0? Or, what? 

The cohort size (number of unique EBP initiators) for Time 0 should be provided in the row. 

The columns reflect the time increments - probably by month - by which we track the cohorts and each cell contains the proportion (%) of EBP initiators in that cohort who progress to EBP completer status over that month or time increment.

Using both cases and tables to illustrate.

We should also consider how this proportion works for segments based on their diagnosis (depression, PTSD, AUD and OUD). For example, if a unique patient for a sta6a is included in Cohort 1 below at time 0 are they, or are they not included in the time 0 column for cohort 2?

An EBPsy scenario:
All sta6a Omnibus EBPsy Initiators  | Time 0  |  Time 1  | ...  | Time n  |
Depression EBPsy Initiate Cohort 1  (n = ??) | % complete |  % complete  | ...  |  % complete  |

PTSD EBPsy Initiate Cohort 2  (n = ??) | % complete |  % complete  | ...  |  % complete  |


All sta6a Depression EBP Initiators  | Time 0  |  Time 1  | ...  | Time n  |
Depression EBPsy Initiate Cohort 1  (n = ??) | % complete |  % complete  | ...  |  % complete  |

Depression EBPharm Initiate Cohort 2  (n = ??) | % complete |  % complete  | ...  |  % complete  |

Subsequent Observations

We need to identify and explain anything filters in our coding rules that exclude patients from any of the cohorts at time 0, but then would include those same patients for subsequent observations (e.g. a patient who initiates and completes an EBPsy at that sta6a for PTSD, but over the course of a year also begins EBPharm for depression at the same sta6a). 

_Logic related to subsequent observations can exceed 100%, which is what prompted @dkngenda's question._

I'm hoping this is enough to go on. 🤓

**Comment by dkngenda** [comment]
> @dkngenda
> 
> Thanks for this.
> 
> Right, the Fisher’s exact test for 12 month pre and 12 month post is what we proposed in the R21 and went through NIH peer review, so we must stick to our original plan.
> 
> Do you have thought about how you planning to display the results?

For all tests of difference in proportion, I am thinking of using tables with a format like the one below. 

| Initiated   | pre-MTL| post-MTL| p value  |
| --------- | -------   | --------   | -------   |
| Yes          | 391         | 436          |   0.02     |
| No           | 7193       | 6623        |                |
|                                                                       |

For the cross tabs cells, I could also use proportions instead of actual counts

**Comment by lzim** [comment]
@anthonycpichardo @dkngenda @staceypark 
Add this here too:

sta6a | Location | pre_start | pre_end | post_start | post_end | intervention_start | intervention_end
-- | -- | -- | -- | -- | -- | -- | --
640HA | Stockton | 2016-10-01 | 2017-09-30 | 2018-09-01 | 2019-08-31 | 2017-10-04 | 2018-08-31
640A0 | Menlo Park | 2014-11-01 | 2015-10-31 | 2018-10-01 | 2019-09-30 | 2015-04-29 | 2018-09-30

**Comment by anthonycpichardo** [comment]
Are we ready to close this issue @dkngenda

**Comment by anthonycpichardo** [comment]
This is ready to close =). Great job team!
