### ISSUE TITLE
WAVE1 Updates for the R01_IIR tt3 

### ISSUE THREAD

**Issue by saveth** [lzim/teampsd#675]
**1. Add description:** 
In order to help to help clarify the request in #424, this issue is broken out into a number of tickets to differentiate the various "asks" and "due date".

Once @holbrooa provides the data #672 and  p-charts for the R21 is done #674, then we need p-charts for clinics in the R01_IIR to be used in the tt-report with the following specs:

1. EBP Reach for Initiate and Dose as defined in #571  with the following:

|Condition | Reach |
|-- | -- |
|with AUD | Omnibus EBP Reach |
| | Omnibus EBPsy Reach |
| | Omnibus EBPharm Reach |
|without AUD | Omnibus EBP Reach |
| | Omnibus EBPsy Reach |
| | Omnibus EBPharm Reach |

2. Use 2 Baseline time period reference:
    i.  R01 refers to the 12months prior to training and 12months post training
    ii. IIR refers to the 6 months before and 6months after training

3. Generate individual reports for each of the 48 clinics identified for the study

<< Paste screenshots here>>
 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_2days
Tickets for #672  and #674  should be closed prior to starting this issue. Will need to consider if additional dataset needs to be created to account for different time reference and study period.

**Edit the due date (if necessary)**

**Comment by lzim** [comment]
@saveth @staceypark @holbrooa @ritahitching 

- Please note the policy from yesterday’s **Support Workgroup Leads** meeting: **_We do NOT want to assign due dates outside of meetings._**
- We can briefly discuss this on Monday, but as I mentioned in the prior issue on this (Cross-ref #424) this will not be due until much farther in the future than this. _Likely not until 4/01/2020 at the earliest._

**Comment by staceypark** [comment]
I took the due date off of this for now.

**Comment by saveth** [comment]
@lzim @staceypark @ritahitching @anthonycpichardo The code for this is done. Only two changes are needed. I've told @anthonycpichardo what changes need to be and where in the script file so that these quick changes can be made by the new person.

**Comment by anthonycpichardo** [comment]
This changes refer to the data changes needed when prepping data for R01_IIR. Moving to epic backlog until we resolve r21.

**Comment by lzim** [comment]
@anthonycpichardo 
@dkngenda 
@anazariz 
@staceypark 

FYI: Helpful to keep this in mind with research#29 etc.

**Comment by staceypark** [comment]
@lijenn @anthonycpichardo @staceypark 
To check in grants: what is going into the email reports for Red arms?

**Comment by staceypark** [comment]
closed at 8/12 hq workgroup meeting
