### ISSUE TITLE
SP-MBC Module - Order of Team Data Table Variables

### ISSUE THREAD

**Issue by dlkibbe** [lzim/teampsd#704]
**1. Add description:** 
Minor thing - Suicide Prevention & Measurement-based Care Module 
I believe the order of the variables in the team data table does not match the order of the variables descriptions in the "i" descriptive table. For a learner it might be easier if the "i" information is listed in the order that the variable appears in the MBC team data table and the Stepped Care data table. Engagement Time Before Ending, Symptom Proportions % and Time to Improve would move up. Engagement Time before Step up/down, Time from Flag to Step up/down and Wait times move down to be the bottom 3.

<< Paste screenshots here>>
![image](https://user-images.githubusercontent.com/31182258/64963873-f549db00-d867-11e9-89ef-52dbeda357a8.png)

 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members. @jamesmrollins @staceypark 
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_ 1 hour.

**Edit the due date (if necessary)**

**Comment by jamesmrollins** [comment]
@dlkibbe see below for the appropriate order. Please indicated your approval/disapproval.  

@lzim this is a minor change that will only take 1 hour (see labor estimate in issue template).  

![image](https://user-images.githubusercontent.com/30132017/64975321-97b38f80-d863-11e9-845e-116122d879e1.png)

**Comment by dlkibbe** [comment]
Yes, @jamesmrollins - this is what makes sense to my learning brain. Thank you.

**Comment by jamesmrollins** [comment]
@lzim I would like to put this into tonight's pull with DEV.  Thanks, James

**Comment by staceypark** [comment]
@lzim Looks like there will be some documentation dependencies with this change to video especially.
It'll only take Dev, one night to change. Can @jamesmrollins go ahead and do this?

**Comment by lzim** [comment]
> @lzim Looks like there will be some documentation dependencies with this change to video especially.
> It'll only take Dev, one night to change. Can @jamesmrollins go ahead and do this?

@jamesmrollins and @staceypark 

Yes, approved

**Comment by jamesmrollins** [comment]
@dlkibbe this has been changed in TEST (see below).  @staceypark this may need documentation changes, not sure, perhaps you can check it out.  Once you give me the thumbs up, I will promote to production.

![image](https://user-images.githubusercontent.com/30132017/65339041-474c7280-db80-11e9-9c77-a76061a63d6d.png)

**Comment by dlkibbe** [comment]
Thanks @jamesmrollins

**Comment by staceypark** [comment]
Tracked on #604 for documentation
