### ISSUE TITLE
Spelling correction - Suicide Prevention & Measurement-based Care

### ISSUE THREAD

**Issue by dlkibbe** [lzim/teampsd#707]
**1. Add description:** 
Model diagram, "i" information for GMH Effect of Patient Load on Care Quality:
Detremental should be spelled "detrimental"
In the phrase "There is no limit to the detremental effect..."

![image](https://user-images.githubusercontent.com/31182258/64989290-34455400-d89b-11e9-9fd9-fd4b212a60b5.png)

<< Paste screenshots here>>
 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by jamesmrollins** [comment]
@dlkibbe Did search and replace on misspelling in the "i" information spreadsheet.  Found 10 others.  Corrected and uploaded new file in OSF, DEV, TEST and PROD.  Thanks, James.

**Comment by staceypark** [comment]
Checked PROD & looks good. 
By the way, how would one update information in the "i" information for the Team Data Table pop-up? Is that hard coded instead of being updatable by the excel spreadsheet?

**Comment by jamesmrollins** [comment]
@staceypark - Yes, it is hard coded.  I have a proposed feature in the future_release kanban to provide an on-line means to manage all "i" information and get away from these darn spreadsheets!
