### ISSUE TITLE
 9/20 Links in pre/post checklist are not up-to-date with new prep workflow

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#708]
**1. Add description:** 
In pre/post checklist for prep, the links that point to see/say/facilitation notes, etc. are not reflective of most recent decisions on where resources are located (i.e. see & say guides are always on mtl.how, team_tracker, etc.)

<< Paste screenshots here>>
 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by lzim** [comment]
Thanks @staceypark 

I believe I also mentioned getting the pre/post emails in the **document_tracker** somewhere 🙋🏻‍♀️

They strike me as **document_team** information

**Comment by staceypark** [comment]
@lzim stuck them in the document_team session cards!

**Comment by staceypark** [comment]
edited links in checklist PR #714
