### ISSUE TITLE
mtl_facilitate_pilot planning 4-7 Sept 2018

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#71]
Starting our planning for the MTL Facilitate Pilot: 

Straw Agenda: teampsd/mtl_facilitate_workgroup/facilitation_guide/MTL Facilitate Training Facilitators_agenda_draft2.docx

Not just this one-time event:
1. What do they have to do in advance to be prepared?
2. What do they have to be able to do at the end?
3. What will we follow up on with them afterward?

Debbie presented a design philosophy that focuses on experiential learning and fun.

We need to triage what we want to cover.

@branscombj @staceypark @dlkibbe

**Comment by lzim** [comment]
Hello Everyone,

Following up on the work we did to merge Debbie's draft schedule with the recently revised 12-session *MTL Live* plan, the Revised Schedule for the MTL Facilitate Pilot is available here:
https://github.com/lzim/teampsd/tree/master/mtl_facilitate_workgroup/mtl_facilitate_pilot

To finalize our preparations we need to get our *MTL Live* In-session exercise guides together for 
- sessions 2 (data UI) & 3 (team data table for sim UI) [Lindsey & Stacey working on this]
- sessions 5 & 6 (sim UI using CC), and sessions 7, 8, 9 & 10 (using sim UI AGG) [Jane & Debbie to start, with help once session 2 & 3 are done]

The daily schedules (day 1, day 2, day 3 & day 4) include the *MTL Facilitate Pilot* Schedule-at-a-Glance for that day, and the experiential learning activities are listed below the schedule.
- day 1 - 3 exercises
- day 2 - 6 exercises
- day 3 - 6 exercises
- day 4 - 3 exercises

These exercises are of two types: The actual *MTL Live* in-session exercise for the first hour. Then, a "mutual learning" exercise designed to assess and reinforce learning. These mutual learning exercises are to be drawn from Debbie's draft 2 agenda, and should move from learning the *MTL Live* exercise from the 12-sesion plan, to practice with more "train-the-trainer" learning experiences.

Thanks!

 @branscombj @staceypark @dlkibbe @TomRust @dlounsbu

**Comment by branscombj** [comment]
Lindsey went over the below (on GitHub) with me for “90 seconds” at the end of the debrief call (~25 minutes). She drilled in that we have to do both “in-session guides” that are essentially the MTL Live session plans for Sessions 5-9 – in addition to the “mutual learning” activities to reinforce them.

Jane Branscomb, MPH
Senior Research Associate
Georgia Health Policy Center
Andrew Young School of Policy Studies
Georgia State University
55 Park Place 8th Floor, Atlanta, GA 30303
404.413.0317 (direct), 404.413.0316 (fax)
jane@gsu.edu
www.ghpc.gsu.edu<http://www.ghpc.gsu.edu/>

[/Users/lorisolomon/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_1054234362]<https://www.facebook.com/GeorgiaHealthPolicyCenter/>[cid:image011.png@01D4033A.B2EF22F0][/Users/lorisolomon/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_747647809]<https://twitter.com/GSUGHPC>[/Users/lorisolomon/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_224188472]<https://vimeo.com/gahealthpolicycenter>

[cid:image006.png@01D43EED.641A1830]

**Comment by lzim** [comment]
@lzim @staceypark @TomRust @dlounsbu @branscombj @kibbe

We discussed this yesterday. **Please see the Lucid notes from our meeting, which breaks down the next steps for these guides by the four days of the *MTL Facilitate Pilot*.**

Team members will:
1) **sync their own branch with Master before they do any work.** Make sure you have the latest copy of that file : )**
2) work on guides on their own branch in this folder location: TeamPSD/mtl_facilitate_workgroup/mtl_facilitate_pilot/ then the day folder for whatever *MTL Facilitate Pilot* day that in-session guide or mutual learning activity will be covered 
3) when done with your work, commit to your own branch, and open a pull request to request team review. Please use project workflow/tracking options on the right menu to call out someone/all of us. For example, please mention @lzim and I’ll take a look, be sure to add the request to the TeamPSD project
4) **always sync your branch to Master** to stay current with others’ work and make sure you’re working on the latest copy of a file, including edits, formatting or comments from others.

Thanks!

Lindsey
Closing this issue.
