### ISSUE TITLE
Date-Time Group Format

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#72]
@lzim @dlkibbe @TomRust 
I am not sure we agreed on this yet.  Our current date-time stamp is DDhhmmMMYYYY.   I am going to change it to MM/DD/YY hh:mm  .

Let me know if this isn't the case.

Thank you,
James

**Comment by lzim** [comment]
Hi @jamesmrollins, 

Thanks for checking. I think you missed our discuss of this at the top of today's MTL Launch call.

We are looking for this format (lower case and underscores): **yyyy_mm_dd_hhmm** 

I've cc'd @saveth from the quantitative workgroup who proposed this approach, which enables sorting by date/time (ascending or descending).

@dlkibbe @TomRust @staceypark 

Thanks!

Lindsey

**Comment by jamesmrollins** [comment]
@TomRust @lzim 
I am not sure how to align these feedback loops in AGG.  There also appear to be two feedback loops in Vensim than in the SIMUI.

![image](https://user-images.githubusercontent.com/30132017/43611094-ebe3173c-965c-11e8-9078-f10e2cc12e0c.png)
