### ISSUE TITLE
Multi-variable Experiment Sliders Should Sum BC Values

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#726]
**1. Add description:** 
The Multi-Variable Experiment Sliders in the models should return BC values at equilibrium and sum them.  Dmnl variables should sum to 100%.

![image](https://user-images.githubusercontent.com/30132017/65624885-99760500-df7f-11e9-92cd-40809eee9847.png)

 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by jamesmrollins** [comment]
@hirenp-waferwire please review the Reference at this link >> https://github.com/lzim/teampsd/issues/314#issuecomment-480098380 

I believe this idea was completed at least for PSY and AGG in the April timeframe. Please investigate the discrepancy - thought we completed this already.

Thanks,
James

**Comment by staceypark** [comment]
@jamesmrollins @lzim @TomRust 
I'm looking at AGG Appointment Supply and it does not show the values for the BC. It just shows "BC", similar to your current SP diagram.

If I understand your comment/diagram, are you saying that instead of "BC" it should show a number in each box? I thought it only shows the value if the slider is moved?

My reading of #314 is to add a function where the sim throws a warning if the total > supply, not for the "BC" to show specific values instead before moving the sliders. @lzim @TomRust perhaps you guys can shed some light

**Comment by jamesmrollins** [comment]
Hi @staceypark .  Please hang on a bit until I investigate.  I will update hopefully by tomorrow's meeting, else on Monday.

**Comment by TomRust** [comment]
Hi @jamesmrollins & @lzim ,

I thought this summing feature was supposed to work like this **in all instances**:
- If all sliders are BC, then the boxes associated with each slider should say BC, and the sum box should show the sum as a number (summing all the BC values, which, in the example above, should be 100%).
- If any one slider is moved away from BC, then that box should show the number the slider was moved to, the other slider boxes should still say BC, and the sum box should show the sum as a number (summing the BC values and the new slider input).
- If all the sliders are moved away from BC, then all the slider boxes should show the numbers they were moved to, and the sum box should show the sum as a number (summing the slider inputs).
 - If the sum is dimensionless, and it is greater than 100%, then a warning should appear.
 - If the sum is an appointment supply total, and it is greater than the base case total, then a warning should appear.

**Comment by jamesmrollins** [comment]
Hi @TomRust , you are partially correct.  Last April, according to my documentation, in the SP model we made it so the sliders are automatically set to the BC values when the user starts the sim (see below).  We didn't propagate the feature to all models, because we didn't have enough funds. 

Somehow, the feature was removed during our various upgrades.  However, it is now returned and view-able in SP.

@lzim 
The next question is, "Do we want to change the rest of the sliders to do this and remove the "BC" from all sliders?"  I suspect there are many documentation dependencies, so this may be something for a future release.  If you want to proceed, then I can get cost information. Otherwise, perhaps we should put in the "Future Release" column.

![image](https://user-images.githubusercontent.com/30132017/65704527-8aed2380-e03b-11e9-9a86-6efdceb40976.png)

**Comment by TomRust** [comment]
@jamesmrollins & @lzim -- 

Sorry I wasn't clear, James.  My description is what I thought would be the most helpful to the users.  I don't remember what we put together back in April.  

After reading your reply though, now I have a different idea.  I still think leaving everything labeled BC when the slider position is on BC is very helpful, as it allows the users to do a quick scan to see which sliders they have manipulated.  AND, I see how starting the slider in the position that corresponds to the BC value is also useful.  **Could we have both somehow?** Where the sliders starts in the position corresponding to the BC value, and the box shows "BC" when the slider is on the BC value? That seems like the best of both.

@lzim -- What do you think?  Should we ask the other facilitators to weigh in with their experience?  Or is this a discussion to put off til we're working on MTL2.0?  :)

**Comment by jamesmrollins** [comment]
Hi @TomRust @lzim 
Yeah, I didn't remember either, then bam! I did. Unfortunately, we have to do one or the other.  Meaning, the slider and the number in the box are dependent.  If we want to stick to the "BC" scheme, I can see the advantages, especially with respect to all the documentation that explains "BC."

I remember early on in the design effort we wanted the auto-set sliders. But perhaps it would be better to put this feature into Ver 2.0 +

**Comment by lzim** [comment]
@jamesmrollins @TomRust @staceypark 

Thanks for thinking this through!

I think we may need to:
1. Make sure how these work is clear in our existing **document_tracker** In other words, how it works now.
2. File the description @TomRust provides in the **new_release** column for now.

What you describe, Tom, sounds great though!

@jamesmrollins It would be helpful to cost out these in advance/as we go to help us prepare for _MTL 2.0_ requests.

> I thought this summing feature was supposed to work like this **in all instances**:
> 
> * If all sliders are BC, then the boxes associated with each slider should say BC, and the sum box should show the sum as a number (summing all the BC values, which, in the example above, should be 100%).
> * If any one slider is moved away from BC, then that box should show the number the slider was moved to, the other slider boxes should still say BC, and the sum box should show the sum as a number (summing the BC values and the new slider input).
> * If all the sliders are moved away from BC, then all the slider boxes should show the numbers they were moved to, and the sum box should show the sum as a number (summing the slider inputs).
> * If the sum is dimensionless, and it is greater than 100%, then a warning should appear.
> * If the sum is an appointment supply total, and it is greater than the base case total, then a warning should appear.

**Comment by jamesmrollins** [comment]
@lzim @TomRust 
The way the sliders work in all instances, except the one shown in the graphic above, just as @TomRust has described. No worries there.  We did change the SP sliders to the alternative method, meaning auto setting the BC value. This upgrade was made in April (I think).  I thought I made it at Tom's request, but he doesn't recall that.  That being the case, I can return the SP sliders back to the original algorithm.  

If we decide to incorporate the auto-functionality in version 2.0, then keep these facts in mind.  First, the slider either shows "BC" or a number.  Second, we can keep the BC popup button there, to reiterate the BC value, as I have shown above. Third, the slider and the number box are dependent. I cannot separate the values they show. Fourth, we wouldn't need default negative values anymore, because the sliders would start out on their base case value.

**Comment by staceypark** [comment]
@jamesmrollins @lzim @TomRust 
If we are going to move all models  toward the "alt method" that SP is currently using, why don't we just keep SP the way it is to reduce documentation issues that will come with reverting it back.

Or, will that be too confusing for learners because it's inconsistent between models.

**Comment by jamesmrollins** [comment]
@jamesmrollins @lzim @TomRust Lets discuss in the Monday Meeting.  Your documentation for SP likely illustrates the "BC" method, vice the auto-set method.  Thus, we may be better just changing it back and pushing the decision to Ver 2.0

**Comment by staceypark** [comment]
@lzim @jamesmrollins @TomRust 
At the Workgroup Leads meeting 2019/09/30, we decided to keep this feature (showing values instead of the word "BC" for multi-variable experiment sliders) for SP, but not for the other four models. We are putting this card to be tracked for future_release in MTL 2.0 for the other four models.

**Comment by jamesmrollins** [comment]
@lzim @dlkibbe @TomRust @staceypark @holbrooa @saveth @dlounsbu @ritahitching @jessfroe 

**Andon Alert**

@dlkibbe discovered an issue with the SP model, where we have the "XXX Openings for New Episodes of Care %" slider preset, are returning lines on the charts that are NOT flat, as we would expect in the base case setting.  

**Facts:**
1.  If the sliders are set to "BC" (with BC showing in the number window), then the charts all show a flat line.  (see below)

![image](https://user-images.githubusercontent.com/30132017/66225606-ac7a8a80-e68d-11e9-94a7-c692b2d443aa.png)

2. If the sliders are set to the whole number, as the are NOW after simulation startup, then the lines change slightly.  The line changes are amplified due to the auto-adjusting scale feature.

![image](https://user-images.githubusercontent.com/30132017/66225362-1e060900-e68d-11e9-9991-7c9c26a7f01f.png)

**Analysis**
If the sliders are set to "BC", then the simulation refers to "XXX EQ Initial Openings for New Patients %," then the number is not rounded up and is actually a 16 place decimal.  This precision results in a flat line. In the screen shot below, the values in the sliders are rounded up, and the actual value in the EQ variable is more precise.

![image](https://user-images.githubusercontent.com/30132017/66225295-f747d280-e68c-11e9-8184-ea6c5ca8ecf6.png)

**Recommendations**

For an **interim fix**, facilitators should be instructed to manually adjust the sliders back to "BC" prior to making any run. @dlkibbe was advised to do this for her immediate session needs on 10/4. 

For a **final fix**, we should reset the sim code, so the variables start with the "BC" setting, versus the slider setting.

**Comment by staceypark** [comment]
@lzim 
@jamesmrollins would like a decision on this and @staceypark thinks we should address this with facilitators today during group supervision regarding the interim solution

**Comment by lzim** [comment]
@jamesmrollins 

So, there is no known fix other than a return to including the "bc" in the slider?
There is no way to round in the slider, but keep the full value "under the hood?"

Lindsey

**Comment by jamesmrollins** [comment]
@lzim I don't believe so.  

When the slider is set to "BC," it actually feeds a [-1] to the variable. In the example of "GMH Openings for New Episodes of Care %," the [-1] tells it to refer to the "EQ GMH Openings for New Episodes of Care %" variable return value, which is a 16 place decimal fraction. 

With the slider pre-set logic, the code reads the same EQ variable, but has to round it up or down to fit on the slider scale, whose resolution is in increments of 1. 

However, I will ask DEV as they often surprise me with what they can do.

**Comment by jamesmrollins** [comment]
@lzim I was correct about the slider resolution.  It is not possible to have both the 16 place decimal and the slider preset.  The value resolution is constrained by the increment on the scale.

**Comment by lzim** [comment]
Okay, thanks @jamesmrollins 

It sounds like will:
1. Have “bc” shown as the value, and 
2. Retina the “bc” button to check the bc value

FYI: @staceypark and @TomRust

**Comment by jamesmrollins** [comment]
@hirenp-waferwire , please return the "XXX Openings for New Episodes of Care %, XXX Opening for New Episodes of Care from PC/PCMHI %, and XXX Openings for New Episodes of Care from SMH % and related sliders on SMH and PC/PCMHI panel" to "BC" setting.  Thank you.

![image](https://user-images.githubusercontent.com/30132017/66491083-0cdf4280-ea67-11e9-9025-be2a8bec87d6.png)

**Comment by staceypark** [comment]
@jamesmrollins in PROD

**Comment by staceypark** [comment]
@jamesmrollins 
I want to double check, should this function (of showing "BC" as the value next to the sliders with a "BC" button for checking the value) only be in SP? 

For example, this is what I see in PSY. Would I need to look at the team data table in PSY to find the BC values?

![image](https://user-images.githubusercontent.com/31089501/71537093-e42f5200-28cb-11ea-950d-a75dd6423925.png)

**Comment by jamesmrollins** [comment]
@staceypark  If I understand you correctly, the showing of "BC" should be standard across all the simulations.  The reason is the actual "BC" value is a very exact number, like 1.0000000000001, so it is necessary for the model to achieve equilibrium. If we round to just two or three decimals, it throws the model out of wack. Yes, you would need to refer to the TDT for the rounded BC values.

![image](https://user-images.githubusercontent.com/30132017/71593622-b32c6880-2ae9-11ea-8d8e-30b0bf2a083f.png)
