### ISSUE TITLE
Patient Load unit should be pct not pts

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#727]
1. @TomRust says that the Patient Load variable unit should be "pct" (percentage) and not "pts" as this a ratio.

![image](https://user-images.githubusercontent.com/30132017/65626114-e064fa00-df81-11e9-8897-5eded4bb0584.png)

 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by jamesmrollins** [comment]
@TomRust @staceypark @lzim @dlounsbu @branscombj  

According to the Master Crosswalk Table, this should be "Pts/wk"  The Vensim model indicates "Dmnl" that is consistent with @TomRust reported comments above.  I will update the table too.

**Comment by jamesmrollins** [comment]
@hirenp-waferwire please change the units for GMH/SMH/PC-PCMHI Patient Load units to %.

**Comment by staceypark** [comment]
@jamesmrollins when do we expect this to be in PROD? I noticed it wasn't there this morning

**Comment by jamesmrollins** [comment]
@staceypark I will put it in Sunday's workstream. Should be fixed by Monday.

**Comment by staceypark** [comment]
looks good in PROD and tracked in meta_depend column
