### ISSUE TITLE
SP: Add Text to Grey Box in Stepped Care View

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#739]
**1. Add description:** 
When zoomed out in GMH/SMH/PC Stepped Care View, then the grey box "XXX Effect of Measurement Based Care on Patients' Symptoms and Risk needs an additional phrase added the clarifies the units.
Add: (pts) to clarify the units like this (see red box in screenshot):
"GMH Effect of Measurement Based Care on Patients' Symptoms and Risk (pts)"

- This helps to "close the loop" for the dominant reinforcing feedback: "Higher Care Quality Improves Recovery" 

![patients_in_GMH](https://user-images.githubusercontent.com/7454688/65910473-9f088c00-e37f-11e9-98c4-5c19bd359179.png)

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_1 hr.

**Edit the due date (if necessary)**

**Comment by jamesmrollins** [comment]
@lzim got it.

**Comment by staceypark** [comment]
@lzim @jamesmrollins this is done in PROD.
I tracked it in the depend column (although I doubt we need to make a pop up its so tiny)
I think it's ready to be closed

**Comment by lzim** [comment]
Agreed

**Comment by lzim** [comment]
**wk2 2024_09 - #fidelity_manuscript**
@lzim 
@kmacia 

- [ ] @kmacia - Add "facilitator" to the Title.

![image](https://github.com/user-attachments/assets/4b47f299-47d0-4745-b27e-338db174f817)
