### ISSUE TITLE
ASAP CDW Health Factors: Request for MTL HF Data for Cerner EHRM Transition

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#742]
Consistent with the email received from the CERNER EHRM transition team.
We need to provide the list of all the health factors data that we use in _Modeling to Learn_ in order to ensure that we will retain that data in the Cerner era moving forward.

@holbrooa Can you provide this list ASAP today?
- Please let me know if you have questions about this.

@staceypark FYI

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by holbrooa** [comment]
Not totally sure what shape of answer they're looking for for "a list of HF's being used" but I can give them this code snippet (from OMHSP):

`SELECT  
	 HealthFactorTypeSID
	,HealthFactorCategory
	,HealthFactorType
	,MH_PEI_Template	                =CASE WHEN healthfactorcategory LIKE '%MH PEI %'                            THEN 1 ELSE 0 END
	,MH_CPT_Template	                =CASE WHEN healthfactorcategory LIKE 'MH CPT TEMPLATES (COGNITIVE PROCESSING)%' THEN 1 ELSE 0 END
	,MH_CBT_D_Template	                =CASE WHEN healthfactorcategory LIKE '%MH CBT-D TEMPLATES%'                  THEN 1 ELSE 0 END
	,MH_ACT_Template                    =CASE WHEN healthfactorcategory LIKE '%MH ACT %'							 THEN 1 ELSE 0 END
	,MH_BFT_Template                    =CASE WHEN healthfactorcategory LIKE '%MH BFT TEMPLATES%'	                 THEN 1 ELSE 0 END 
	,MH_CBT_I_Template                  =CASE WHEN healthfactorcategory LIKE '%MH CBT-I TEMPLATES%'                  THEN 1 ELSE 0 END 
	,MH_IBCT_Template                   =CASE WHEN healthfactorcategory LIKE '%MH IBCT TEMPLATES%'                   THEN 1 ELSE 0 END 
	,MH_IPT_For_Depression              =CASE WHEN healthfactorcategory LIKE '%MH IPT FOR DEPRESSION%'               THEN 1 ELSE 0 END 
	,MH_SST_Template                    =CASE WHEN healthfactorcategory LIKE '%MH SST TEMPLATES%'                    THEN 1 ELSE 0 END 
	,MH_PHQ9_Decrease                   =CASE WHEN HealthFactorType     LIKE '%MH EBP PROG PHQ9 DECREASE%'           THEN 1 ELSE 0 END
	,MH_Other_Rpt_Decrease              =CASE WHEN HealthFactorType     LIKE '%MH EBP PROG OTHER RPT DECREASE%'      THEN 1 ELSE 0 END
	,MH_Decrease_Depression             =CASE WHEN HealthFactorType     LIKE '%MH EBP PROG RPT DECREASE DEPRESSION%' THEN 1 ELSE 0 END
	,MH_Closing_Phase                   =CASE WHEN HealthFactorType     LIKE '%MH ACT 3 CLOSING PHASE%'              THEN 1 ELSE 0 END
	,MH_Early_Term                      =CASE WHEN HealthFactorType     LIKE '%MH EBP EARLY TERM SYMPTOMS REMIT%'    THEN 1 ELSE 0 END
    ,MH_EBP_EARLY_TERM_AGREE            =CASE WHEN HealthFactorType     LIKE '%MH EBP EARLY TERM AGREE%'             THEN 1 ELSE 0 END
    ,MH_CBT_I_4_FINAL_SESSION           =CASE WHEN HealthFactorType     LIKE '%MH CBT-I 4 FINAL SESSION%'            THEN 1 ELSE 0 END
	,MH_CBT_I_GOAL_PARTIAL_ACHIEVE      =CASE WHEN HealthFactorType     LIKE '%MH CBT I GOAL PARTIAL ACHIEVE%'       THEN 1 ELSE 0 END
	,MH_CBT_I_GOAL_ACHIEVE              =CASE WHEN HealthFactorType     LIKE '%MH CBT I GOAL ACHIEVE%'               THEN 1 ELSE 0 END
	,MH_CBT_I_CONTINUING_SELF_CARE_PLAN =CASE WHEN HealthFactorType     LIKE '%MH CBT I CONTINUING SELF CARE PLAN%'  THEN 1 ELSE 0 END
	,MH_IBCT_4_FEEDBACK					=CASE WHEN HealthFactorType     LIKE '%MH_IBCT 4 FEEDBACK%'				     THEN 1 ELSE 0 END
	,MH_IBCT_FEEDBACK_OVERVIEW			=CASE WHEN HealthFactorType     LIKE '%MH IBCT FEEDBACK OVERVIEW%'			 THEN 1 ELSE 0 END
	,MH_IBCT_5_Therapy                  =CASE WHEN HealthFactorType     LIKE '%MH IBCT 5 Therapy%'				     THEN 1 ELSE 0 END
	,MH_BFT_2_EDUCATION_SESSION			=CASE WHEN HealthFactorType     LIKE '%MH BFT 2 EDUCATION SESSION%'		     THEN 1 ELSE 0 END
	,MH_BFT_3_COMMUNICATION_SESSION		=CASE WHEN HealthFactorType     LIKE '%MH BFT 3 COMMUNICATION SESSION%'	     THEN 1 ELSE 0 END
	,MH_BFT_4_PROBLEM_SOLVING_SESSION	=CASE WHEN HealthFactorType     LIKE '%MH BFT 4 PROBLEM SOLVING SESSIO%'	 THEN 1 ELSE 0 END
	,MH_BFT_5_FINAL_SESSION				=CASE WHEN HealthFactorType     LIKE '%MH BFT 5 FINAL SESSION%'			     THEN 1 ELSE 0 END
	,MH_CBT_D_3_COGNITIVE_BEHAVIORAL_FINAL=CASE WHEN HealthFactorType   LIKE '%MH CBT-D 3 COGNITIVE BEHAVIORAL FINAL%' THEN 1 ELSE 0 END
	,MH_IPT_3_TERMINATION_SESSION	   =CASE WHEN HealthFactorType      LIKE '%MH IPT 3 TERMINATION SESSION%'        THEN 1 ELSE 0 END
    ,MH_SST_3_FINAL                    =CASE WHEN healthfactorcategory  LIKE '%MH SST 3 FINAL%'                      THEN 1 ELSE 0 END 

FROM [cdwwork].[Dim].[HealthFactorType]`

**Comment by holbrooa** [comment]
@lzim @staceypark  If that's an acceptable answer, do you want me to reply to the email? Or you can just copy/paste that code block.

**Comment by staceypark** [comment]
@lzim is this fine?

**Comment by staceypark** [comment]
@lzim can you confirm on this so we can send?

**Comment by lzim** [comment]
I had a clarifying email bounce, and just re-read the email more carefully request we email a specific cc line. 

I added to the thread of my original response, andpasted the code snip directly in the message to clarify with those two folks.

I've kept @staceypark and @holbrooa on the thread, and added @jamesmrollins 
And, I asked if any further action was need.

Thanks again!

**Comment by staceypark** [comment]
resolved and can be closed.
