### ISSUE TITLE
5/29:  Always Include Text from Previous Exp - Remove Selection Option

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#743]
**1. Add description:** 
It seems that more often than not, we want to include the text from any prior experiment that we're pulling up in the Experiments section. I wonder if that should be the default (vs not-checked box) or even maybe always include it.

<< Paste screenshots here>>
 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by lzim** [comment]
@branscombj 
 Please be sure to add this to the **issue_tracker** project, if you would like it to be considered by Workgroup Leads.

- I’ve added @jamesmrollins and @staceypark 

- This is an interesting idea to put in **future_release** column

**Comment by jamesmrollins** [comment]
@branscombj @lzim this is technically feasible.

**Comment by staceypark** [comment]
Great! I'm putting this in the future_release column

> @branscombj @lzim this is technically feasible.

**Comment by jamesmrollins** [comment]
@branscombj @lzim and James discussed this issue during 4/14 WG Leads meeting:

1.  Lindsey proposed the migration of "Decision" text from a prior experiment to the "Question" text of a current experiment.  Jane responded that she thought it sometimes better to see the full dialectic (i.e., QHFD).
2.  There was also discussion of formatting the text to italics or boldface to help differentiate prior experiment text, versus current experiment text.  
3.  James noted that text boxes requiring the use of different fonts, may need to have those controls built in.  Didn't believe that formatting text is currently an option.
4.  Group decided that they needed more time to think on it.  
5.  This issue moved to May sprint.

**Comment by jamesmrollins** [comment]
### Check off requirements to verify progress through feature_tracker.
- [ ] 1. It seems that more often than not, we want to include the text from any prior experiment that we're pulling up in the Experiments section. Should the inclusion of text from a prior experiment be the default (vs not-checked box).
  - [ ] a. Change the default of the "Include text" check box from unchecked to checked.
  - [ ] b. Consider including only text from previous experiment "Decisions" text box to the current experiment "Our Question" text box.
  - [ ] c.  Decision to proceed reached in team meeting - - - - TBD
  
  Task Cards:
  #
---
- [ ] 2. **DESIGN** in **operations_to_do** and **research_to_do**
  - [ ] a. **what & why** - **_MVP_ of design** of requirements in a **algorithm map, wireframes or design** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** design **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 3. **DEVELOP** in **under_development** - "frozen"

  Task Cards:
  #
---
- [ ] 4. **TEST in functional_test**
  - [ ] a. **what & why** - **TEST requirements** using **testing_checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** via TEST **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 5. **PROD in done**
  - [ ] a. **what & why** - **_DOCUMENT_ feature** using **document_tracker** for the **5 D's.** 
  - [ ] b. **date & who** -  **DELEGATE**
    - [ ] **describe_learners** [Jenn & Rita]
    - [ ] **detail_facilitators** [Jane & Debbie]
    - [ ] **document_team** [Anthony]
    - [ ] **disseminate_scientists_va** [Anthony]
    - [ ] **depend_products** [hq & ees]
  
  Task Cards:
  #
---
- [ ] 6. **closed** - fully documented, trained and ready for the next release.
