### ISSUE TITLE
session09_say_checklist typo

### ISSUE THREAD

**Issue by dlounsbu** [lzim/teampsd#745]
**1. Add description:** 

Learning Objectives timestamp label says Session 8, not Session 9

<< Paste screenshots here>>
 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by dlounsbu** [comment]
This is just a small, but annoying typo.

**Comment by staceypark** [comment]
great catch @dlounsbu!
fixed it in PR #755  and going to close this
