### ISSUE TITLE
DUE 2/21: MM & CC Learning Mode video_edits

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#748]
## Pop-ups needed for major changes 
- [ ] s5-10 for CC & MM Learning Mode Popup when selecting module and elimination of "From Team Data" switch in the Experiment Section

**Comment by staceypark** [comment]
## Session 05

### S05 AGG
Time | Correction Type | Description
-- | -- | --
2:46 | Add pop-up | Add pop-up at 2:46 -   "Reminder: mtl.how/data contains protected health information (PHI)
14:45 | Add pop-up | Add pop-up at 14:45 -   "Starting a new session in the team world will impact other team members   using MTL"
20:13 | Add pop-up | Add pop-up at 20:13 - "Tip:   To zoom in, press 'shift, Ctrl, +' simultaneously"
23:18 | Add pop-up | Add pop-up at 23:18: "   Remember: Log off the simulation UI!"

### S05 CC
Time | Correction Type | Description
-- | -- | --
3:38 | Add pop-up | Add pop-up at 3:38 -   "Reminder: mtl.how/data contains protected health information (PHI)
8:11 | Add pop-up | Add pop-up at 8:11 - "Tip:   Zoom in = press "shift, Ctrl, +" simultaneously"
14:00 | Add pop-up | Add pop-up at 14:00 - "   Starting a new session in the team world will impact other team members using   MTL"
18:10 | Add pop-up | Add pop-up at 18:10 -   "Oops! Go into Outputs to see text boxes and results"
19:10 | Add pop-up | Add pop-up at 19:10"Review   "i" for variable and team data descriptions"
23:38 | Add pop-up | Add pop-up at 23:38 - "MTL   simulations help a team look forward 2 years"
24:45s | Add pop-up | Add pop-up at 24:45 -   "Remember: Log off the simulation UI!"

### S05 MM
Time | Correction Type | Description
-- | -- | --
14:48 | Add pop-up | Add pop-up at 14:48 - "   Starting a new session in the team world will impact other team members using   MTL"
19:27 | Add pop-up | Add pop-up at 19:27 - "Tip:   Zoom in = press "shift, Ctrl, +" simultaneously"
21:52 | Add pop-up | Add pop-up at 21:52 -   "Review "i" for team data and variable descriptions
26:35:00 | Add pop-up | Add pop-up at 26:35 - "MTL   simulations help a team look forward 2 years"
29:52:00 | Add pop-up | Add pop-up at 29:52 -   "Remember: Log off the simulation UI!"

### S05 PSY
Time | Correction Type | Description
-- | -- | --
4:31 | Add pop-up | Add pop-up at 4:31 - "Tip:   Zoom in = press "shift, Ctrl, +" simultaneously"
5:00 | Add pop-up | Add pop-up at 5:00 - "Tip:   Zoom out = press "shift, Ctrl, -" simultaneously"
8:08 | Add pop-up | Add pop-up at 8:08 -   "Measurement-Based Care for Suicide Prevention"
14:48 | Add pop-up | Add pop-up at 14:48 -   "Starting a new session in the team world will impact other team members   using MTL"
26:47:00 | Add pop-up | Add pop-up at 26:47 - "MTL   helps a team look forward 2 years"
31:05:00 | Add pop-up | Add pop-up at 31:05 -   "Remember: Log off the simulation UI!"


### S05 SP
Time | Correction Type | Description
-- | -- | --
3:25 | Add pop-up | Add pop-up at 3:25 - "Enter  email and PIV passcode"
6:45 | Add pop-up | Add pop-up at 6:45 -   "Navigate to the sim UI team data folder"
9:30 | Add pop-up | Add pop-up at 9:30 -   "Starting a new session in the team world will impact other team members   using MTL"
13:00 | Add pop-up | Add pop-up at 13:00 - "Tip:   Zoom in = press "shift, Ctrl, +" simultaneously"
13:40 | Add pop-up | Add pop-up at 13:40 - "Tip:   Zoom out = press "shift, Ctrl, -" simultaneously"
15:28 | Add pop-up | Add pop-up at 15:28 - "Make   sure the file name ends in .xlsx"
18:35 | Add pop-up | Add pop-up at 18:35 - "Red   = read in from team data"
26:50:00 | Add pop-up | Add pop-up at 26:50 -  "Remember: Log off the simulation   UI!"

**Comment by staceypark** [comment]
## Session 06

### S06 AGG
Time | Correction Type | Description
-- | -- | --
9:00 | Add pop-up | Add pop-up at 9:00 "The AGG   model can simulate the mix of services unique to your team"

### S06 MM
Time | Correction Type | Description
-- | -- | --
13:32 | Add pop-up | Add pop-up at 13:32  - "Red stacked boxes mean there is   more than 1 variable you can adjust."

### S06 PSY
Time | Correction Type | Description
-- | -- | --
6:09 | Add pop-up | Add pop-up at 6:09 - "Every   MTL model examines Patients & Appointments"
11:38 | Add pop-up | Add pop-up at 11:38 -   "Click any "i" for information about a variable"
11:55 | Add pop-up | Add pop-up at 11:55 -   "Gauge = rate (patients or appointments per week")

### S06 SP
Time | Correction Type | Description
-- | -- | --
10:00 | Add pop-up | SP Model diagrams have been   updated! (or whatever the agreen upon language
33:59:00 | Add pop-up | Add pop-up "Reminder: Log   off MTL module"

**Comment by staceypark** [comment]
## Session 07

### S07 AGG
Time | Correction Type | Description
-- | -- | --
6:51 | Add pop-up | Add pop-up at 6:51 - "Enter a hypothesis" and please leave up for 10s
29:00:00 | Add pop-up | Add pop-up at 29:00 -   "Lindsey is using the Psychotherapy module as an example"
31:10:00 | Add pop-up | Add pop-up at 31:10 -  "Remember: Log off the simulation   UI!"

### S07 CC
Time | Correction Type | Description
-- | -- | --
3:07 | Add pop-up | Add pop-up at 3:07 - "bc =   Base Case of no new decisions in your team"
9:45 | Add pop-up | Add pop-up from 9:45 - 9:55   -  “Study the diagram to develop your   Hypothesis”
29:20s | Add pop-up | Add pop-up at 29:20 -   "Remember: Log off the simulation UI!"

### S07 MM
Time | Correction Type | Description
-- | -- | --
17:00 | Add pop-up | Add pop-up at 17:00 - “Before   hitting BC Run, make sure your slider values are at BC, 0 or 1 in Experiments   section”
17:34 | Add pop-up | Add pop-up at 17:34 - "bc =   Base Case of no new decisions in your team.”
25:04:00 | Add pop-up | Add pop-up at 25:04 - “MM allows   2 comparisons: compare different runs (“Compare Experiments”) or different   patient groups (“Compare Patient Cohorts”)”
29:05:00 | Add pop-up | Add pop-up at 29:05 - “Study the   model diagram to see how decisions interact.”
31:25:00 | Add pop-up | Add pop-up at 31:25 -  "Remember: Log off the simulation   UI!"

### S07 PSY
Time | Correction Type | Description
-- | -- | --
22:06 - 22:17 | Add pop-up | Add pop-up at 22:06 - 22:17   -  “Check out Results Dashboard   dropdown menus to see how MTL links to SAIL measures.”
29:00:00 | Add pop-up | Add pop-up at 29:00 -  "Remember: Log off the simulation   UI!"

### S07 SP
Time | Correction Type | Description
-- | -- | --
13:40 | Add pop-up | Add pop-up at 13:40 - “Before   hitting BC Run, make sure your slider values are at BC, 0 or 1 in Experiments   section”
26:34:00 | Add pop-up | Add pop-up at 26:34 -   "Remember: Log off the simulation UI!"

**Comment by jessfroe** [comment]
##Session 08

###S08 AGG
No added pop-ups suggested 

###S08 CC
No added pop-ups suggested

###S08 MM
Time | Correction Type | Description
-- | -- | -- 
11:40 | Add pop-up | “Stake a claim = if our team does X, then Y will happen over 2 years” 


###S08 PSY
Time | Correction Type | Description
-- | -- | -- 
12:43 | Add pop-up | “Stake a claim = if our team does X, then Y will happen over 2 years” 

###S09 SP
Time | Correction Type | Description
20:00 | Add pop-up | “Dynamic Hypothesis: Look back 2 years to stake a claim about trends over the next 2 years.”

@staceypark I'm having trouble with the table format for this comment. I even copy and pasted from your comment to try and make the formatting correct. Is it not going to make a table because it's just one line? Help please 🐱

**Comment by jessfroe** [comment]
## Session 09

### S09 AGG
Time | Correction Type | Description
-- | -- | -- 
1:40 | Add pop-up | "What is your team's overarching question/need?"
5:33 | Add pop-up | "Select Previous Experiment, include Text and Go"
17:29 | Add pop-up | "Test realistic, feasible scenarios to answer concrete questions in your team"
21:11 | Add pop-up | "Enter your Hypothesis in the text box"
36:58 | Add pop-up | "Don't forget to save and log off the sim UI"

### S09 CC
Time | Correction Type | Description
-- | -- | --
8:00 | Add pop-up | "Select Previous Experiment, Include Text and Go"
11:02 | Add pop-up | "Select Previous Experiment, Include Text and Go"
15:00 | Add pop-up | "Review results from your previous experiments"
33:15 | Add pop-up | "Don't forget to save and log off the sim UI"

### S09 MM
Time | Correction Type | Description
-- | -- | --
0:00 | Add pop-up | Add graphic about the learning mode pop-up
5:06 | Add pop-up | "Select Previous Experiment, Include Text and Go"
40:56 | Add pop-up | Don't forget to save and log off the sim UI"

### S09 PSY
Time | Correction Type | Description
-- | -- | --
3:10 | Add pop-up | Describe what the Sankey diagram is/does for the learner
9:38 | Add pop-up | Indicate that the Experiments section has a new look/has been updated
12:29 | Add pop-up | Remind the learner that the team data table looks different.
17:58 | Add pop-up | Discuss variable name change - "Variable has changed: Change in Engagement Duration after Three Months"
27:10 | Add pop-up | "Don't forget to save and log off the sim UI"

### S09 SP
Time | Correction Type | Description
-- | -- | --
2:25 | Add pop-up | “Test. Don’t guess.”
2:50 | Add pop-up | “Select Previous Experiment, Include Text and Go"
32:35 | Add pop-up | “Don’t forget to log off the sim UI”

**Comment by jessfroe** [comment]
## Session 04 

Time | Correction Type | Description
-- | -- | -- 
2:50 | Add pop-up |  MTL.how/menu: staff survey to prioritize team needs
1:02 | Add pop-up | MTL Modules: Aggregate Services, Care Coordination, Medication Management, Psychotherapy, and Measurement Based Stepped Care and Suicide Prevention
10:12 | Add pop-up | MTL Module: Care Coordination (CC)
10:55 | Add pop-up | MTL Module: Medication Management (MM)
11:55 | Add pop-up | MTL Module: Psychotherapy (PSY)
12:50 | Add pop-up | MTL Module: Aggregate mix of services (AGG)
13:45 | Add pop-up | MTL Module: Measurement Based Stepped Care for Suicide Prevention (SP)
16:29 | Add pop-up | Over 12 sessions, MTL participants get 4 “team time” progress reports

**Comment by jessfroe** [comment]
## Session 03

Time | Correction Type | Description
-- | -- | -- 
2:36 | Add pop-up | MTL Data User Interface (UI) = mtl.how/data
2:55 | Add pop-up | MTL Data UI - use Internet Explorer
3:45 | Add pop-up | “Create Team Data Table for Sim UI” generates file with a tab for each MTL module
7:35 | Add pop-up | Data UI has 1 folder with team data and 1 folder for Sim UI
7:50 | Add pop-up | CC = Care Coordination Module
10:50 | Add pop-up | Red Text populates the Team Data Table in Sim UI
11:20 | Add pop-up | MM = Medication Management Module
13:45 | Add pop-up | PSY = Psychotherapy Module
16:10 | Add pop-up | DataNotes – last tab in data UI file has good info for new MTL users!
19:22 | Add pop-up | AGG = Aggregate Mix of Services Module
21:03 | Add pop-up | SP = Suicide Prevention Module
23:31 | Add pop-up | Pause & Review Info in Parameters Tabs
25:59 | Add pop-up | Column E in the Params tabs provides add’l variable details

**Comment by jessfroe** [comment]
## Session 01

Time | Correction Type | Description
-- | -- | -- 
1:20 | Add Pop-up | Go to mtl.how for all Modeling to Learn (MTL) resources
3:25 | Add Pop-up | MTL Session 1 Goal: Integrate “Your Vision” with the “Team Vision”
10:35 | Add Pop-up | The beginning and end of every MTL session has a “Done” and “Do” review
11:45 | Add pop-up | Go to mtl.how for help (Jane is saying this exact thing at this point in the video)
13:00 | Add pop-up | MTL participants receive Pre- and Post-session emails with Done/Do reminders

**Comment by jessfroe** [comment]
## Session 02

Time | Correction Type | Description
-- | -- | -- 
0:22 | Add Pop up | Add “Open the learner see guide at mtl.how”
0:36 | Add Pop-up | “Done” = What we did last or in between sessions
0:49 | Add Pop-up | “Do” = What we will do today
0:56 | Add pop-up | “mtl.how/data is Data User Interface or Data UI”
1:44 | Add pop-up | “Log in to mtl.how/data in Explorer”
2:01 | Add pop-up | “BISL = Business Intelligence Service Line” (LZ is saying this)
2:15 | Add pop-up | Go to mtl.how data; enter email & PIV pass code”
2"32 | Add pop-up | “mtl.how/data contains protected health information (PHI)”
4:25 | Add pop-up | Explore MTL Data UI using vertical & horizontal scroll bars
5:29 | Add pop-up | At the moment LZ is moving her cursor up to refresh the data, the camera goes to her and TR on screen vs. showing the computer screen. She is saying at “navigate up here and choose data...” and then the camera goes back to screen but the learner didn’t see her initial click. So may want to add a pop-up at 5:29 that says “Click “DATA” above chart, Click “Refresh All Connections”
6:35 | Add pop-up | “Tabs with VIZ = visualization”
7:57 | Add pop-up | ”Viz Tabs = Diagnoses, Health Factors, Encounters, Measures”
8:45 | Add pop-up | “Data Tabs = feature patient-level data”
10:48 | Add pop-up | “MTL Data UI has “hyperlocal data” – by patient, by provider, by clinic”
12:40 | Add pop-up | “Click Edit Workbook, Edit in Excel” to open your team data file”
14:50 | Add pop-up | “Use MTL Data UI to create a personalized team data file”
17:15 | Add pop-up | “Once clinics are selected, click “Get Patient Level Data.” Generating a data file may take up to 15 minutes!”
18:29 | Add pop-up | “Review team trends on viz tabs”
20:00 | Add pop-up | “Pause, Use learner see guide to walk through MTL Data UI tabs”
22:47 | Add pop-up | “Review patient data on data tabs”
23:55 | Add pop-up | “Patients engaged in specific service = Health Factors tab”
26:45 | Add pop-up | “MTL Data UI = mtl.how/data”
28:15 | Add pop-up | “For MTL Help - email mtl.help@va.gov”

**Comment by jessfroe** [comment]
## Session 11

Time | Correction Type | Description
-- | -- | -- 
1:04 | Add pop-up | “Log in to mtl.how/sim to review the team experiments and decisions or learnings”
3:38 | Add pop-up | “Team Time 1 Report: Vision, Team Data, Team Trends, Team Priority Need”
4:30 | Add pop-up | “Final Team Time report will summarize all your work!”
6:10 | Add pop-up | “Consider new decisions you can make today in your clinic.”
8:30 | Add pop-up | “Pause. Examine key insights, decisions, actions, targets & resources.”
11:27 | Add pop-up | "Need help? Email mtl.help@va.gov"

**Comment by jessfroe** [comment]
## Session 12

Time | Correction Type | Description
-- | -- | -- 
1:00 | Add pop-up | “SEE guides for all 12 MTL sessions are at mtl.how”
3:15 | Add pop-up | “MTL can be completed on any web-connected device”
6:30 | Add pop-up | “Data User Interface = mtl.how/data” (it will have been 8 sessions since the user last looked at the data UI, a reminder is helpful)
8:55 | Add pop-up | “Review DataNotes tab for detailed info about team data”
13:22 | Add pop-up  | “Explore any MTL module via video and get licensure credit.”
17:30 | Add pop-up | “Sim UI questions? Review HELP section of mtl.how/sim”

**Comment by staceypark** [comment]
@branscombj @dlkibbe Did we get the CC & MM Learning Modes covered in the pop-ups? I wasn't sure if this got tracked???

**Comment by branscombj** [comment]
> @branscombj @dlkibbe Did we get the CC & MM Learning Modes covered in the pop-ups? I wasn't sure if this got tracked???

I think @jessfroe sent over all of our popups/corrections to Ann in Excel? Could we search there?

**Comment by branscombj** [comment]
@staceypark I am checking here https://osf.io/wzf7k/

**Comment by branscombj** [comment]
OK @staceypark I think that Excel file in OSF was only some final edits - not all of them. Probably the easiest way to answer your question would be to look at the videos!

**Comment by branscombj** [comment]
@staceypark I just looked at the final video for Session 05 CC and it does not have a popup about the popup you get when you click Start a New Session in CC. 😦

**Comment by staceypark** [comment]
> @staceypark I just looked at the final video for Session 05 CC and it does not have a popup about the popup you get when you click Start a New Session in CC. 😦

Same I just looked through the video too

**Comment by branscombj** [comment]
> Same I just looked through the video too 😨

If up to me, I'd put that in the issue tracker for a desired fix in MTL Video 2.0.

**Comment by staceypark** [comment]
> > Same I just looked through the video too 😨
> 
> If up to me, I'd put that in the issue tracker for a desired fix in MTL Video 2.0.

We also have other pop-ups that are going to be needed like all the PLDR changes...

**Comment by branscombj** [comment]
Yes. A list of them might help our future selves figure out at what point to invest in edits - whether additional pop-ups, spliced video or audio, or whole new recording(s).

**Comment by branscombj** [comment]
OK to put this here, right?

mtl Session 12 Final1 – https://bcove.video/38xrxBz 
mtl Session 11 Final1 – https://bcove.video/2EhzInn 
mtl Session 10 Suicide Prevention Module Final1_1 – https://bcove.video/2PEAFLU 
mtl Session 10 Psy Module Final1_1 – https://bcove.video/2thMmRh 
mtl Session 10 Med Management Module Final1_1 – https://bcove.video/2EbU0ii 
mtl Session 10 Care Coordination Module Final1_1 – https://bcove.video/2YIcHUe 
mtl Session 10 Aggregate Module Final1_1 – https://bcove.video/2RVMiB3 
mtl Session 9 Suicide Prevention Module Final1_1 – https://bcove.video/34oXQiQ 
mtl Session 9 Psy Module Final1_1 – https://bcove.video/2PgADLb 
mtl Session 9 Med Management Module Final1_1 – https://bcove.video/36AoaaS 
mtl Session 9 Care Coordination Module Final1_1 – https://bcove.video/38B9Pgw 
mtl Session 9 Aggregate Module Final1_1 – https://bcove.video/2t8cRs7 
mtl Session 8 Suicide Prevention Module Final1_1 – https://bcove.video/2RQGDMk 
mtl Session 8 Psy Module Final1_1 – https://bcove.video/2smgSJc 
mtl Session 8 Med Management Module Final1_1 – https://bcove.video/35kBzUy 
mtl Session 8 Care Coordination Module Final1_1 – https://bcove.video/2RMmCql 
mtl Session 8 Aggregate Module Final1_1 – https://bcove.video/35ks9bC 
mtl Session 7 Suicide Prevention Module Final1_1 – https://bcove.video/2RVNQuu 
mtl Session 7 Psy Module Final1_1 – https://bcove.video/2YN5nH2 
mtl Session 7 Med Management Module REDO Final1_1 – https://bcove.video/2qNGRsw 
mtl Session 7 Care Coordination Module Final1_1 – https://bcove.video/2PJxPVP 
mtl Session 7 Aggregate Module Final1_1 – https://bcove.video/2PGqKWd 
mtl Session 6 Suicide Prevention Module Final1_1 – https://bcove.video/2PGWGKa 
mtl Session 6 Psy Module Final1_1 – https://bcove.video/2YMyOsC 
mtl Session 6 Med Management Module Final1_1 – https://bcove.video/2YNtPYt 
mtl Session 6 Care Coordination Module Final1_1 – https://bcove.video/2POCoP0 
mtl Session 6 Aggregate Module Final1_1 – https://bcove.video/35lRbaf 
mtl Session 5 Suicide Prevention Module Final1_1 – https://bcove.video/2PgYXN5 
mtl Session 5 Psy Module Final1_1 – https://bcove.video/34gfrJG 
mtl Session 5 Med Management Module Final1_1 – https://bcove.video/2snBuko 
mtl Session 5 Care Coordination Module Final1_1 – https://bcove.video/34fw7AR 
mtl Session 5 Aggregate Module Final1_1 – https://bcove.video/36xbi5t 
mtl Session 4 Final1_1 – https://bcove.video/36E0XF7 
mtl Session 3 Final1_1 – https://bcove.video/38Buyk2 
mtl Session 2 Final1_1 – https://bcove.video/2PGS6vo 
mtl Session 1 Final1_1 – https://bcove.video/2PBJxli

**Comment by staceypark** [comment]
@branscombj 
I just spoke with Lindsey, and we are thinking that we only want to present edits to Elizabeth of critical changes (like the learning modes in CC & MM) that will make it confusing for frontline staff rather than all changes. For example, features like the Community/PLDR button should be clear enough that they don't need a pop up to explain them.

Could you think through other major dependencies like that that would be confusing for our learners? Either they would already be tracked in our document_tracker workflow or any remaining ones would be in the issue_tracker or feature_tracker following our SOP.

FYI: @dlkibbe @lijenn

**Comment by lzim** [comment]
> @branscombj
> I just spoke with Lindsey, and we are thinking that we only want to present edits to Elizabeth of critical changes (like the learning modes in CC & MM) that will make it confusing for frontline staff rather than all changes. For example, features like the Community/PLDR button should be clear enough that they don't need a pop up to explain them.
> 
> Could you think through other major dependencies like that that would be confusing for our learners? Either they would already be tracked in our document_tracker workflow or any remaining ones would be in the issue_tracker or feature_tracker following our SOP.
> 
> FYI: @dlkibbe @lijenn

Thanks, bit, that's not entirely what I meant @staceypark. We likely do need a list of MTL 2.0 edits like @branscombj proposed.

But, I'm VERY concerned that of our list CC & MM learning mode wasn't included, as I believe that may is likely the most confusing to handle, whereas the others are "upgrades" or "new features."

In fact, we're highly likely to hear about this very soon when our pilot reviewers get going 😸 

Note: @staceypark I realize that some _MTL Video_ pilot reviewers will not have a world set up in the Sim UI. Who can help with that? It would be great to include in the training of @ritahitching and @lijenn but we also need to keep in mind that reviewers are supposed to complete their review in 2 weeks!

**Comment by lzim** [comment]
Note: This needs to be triaged to one pop-up for CC & one for MM as for the 2/21 due date.
Since there is no Learning Mode in AGG and MTL Video Pilot Reviewers are reviewing that module, we should be okay there.
I've assigned @staceypark

**Comment by staceypark** [comment]
@lzim How's this?
Not sure where the line is of detail vs. length

**New! Learning Modes:**
Choose a Learning Mode to prioritize **Existing Patients Return-to-Clinic Visit Interval** or **New Patient Start Rate** for all your experiments through Session 12.

**Comment by branscombj** [comment]
> OK to put this here, right?
> 
> mtl Session 12 Final1 – https://bcove.video/38xrxBz
> mtl Session 11 Final1 – https://bcove.video/2EhzInn
> mtl Session 10 Suicide Prevention Module Final1_1 – https://bcove.video/2PEAFLU
> mtl Session 10 Psy Module Final1_1 – https://bcove.video/2thMmRh
> mtl Session 10 Med Management Module Final1_1 – https://bcove.video/2EbU0ii
> mtl Session 10 Care Coordination Module Final1_1 – https://bcove.video/2YIcHUe
> mtl Session 10 Aggregate Module Final1_1 – https://bcove.video/2RVMiB3
> mtl Session 9 Suicide Prevention Module Final1_1 – https://bcove.video/34oXQiQ
> mtl Session 9 Psy Module Final1_1 – https://bcove.video/2PgADLb
> mtl Session 9 Med Management Module Final1_1 – https://bcove.video/36AoaaS
> mtl Session 9 Care Coordination Module Final1_1 – https://bcove.video/38B9Pgw
> mtl Session 9 Aggregate Module Final1_1 – https://bcove.video/2t8cRs7
> mtl Session 8 Suicide Prevention Module Final1_1 – https://bcove.video/2RQGDMk
> mtl Session 8 Psy Module Final1_1 – https://bcove.video/2smgSJc
> mtl Session 8 Med Management Module Final1_1 – https://bcove.video/35kBzUy
> mtl Session 8 Care Coordination Module Final1_1 – https://bcove.video/2RMmCql
> mtl Session 8 Aggregate Module Final1_1 – https://bcove.video/35ks9bC
> mtl Session 7 Suicide Prevention Module Final1_1 – https://bcove.video/2RVNQuu
> mtl Session 7 Psy Module Final1_1 – https://bcove.video/2YN5nH2
> mtl Session 7 Med Management Module REDO Final1_1 – https://bcove.video/2qNGRsw
> mtl Session 7 Care Coordination Module Final1_1 – https://bcove.video/2PJxPVP
> mtl Session 7 Aggregate Module Final1_1 – https://bcove.video/2PGqKWd
> mtl Session 6 Suicide Prevention Module Final1_1 – https://bcove.video/2PGWGKa
> mtl Session 6 Psy Module Final1_1 – https://bcove.video/2YMyOsC
> mtl Session 6 Med Management Module Final1_1 – https://bcove.video/2YNtPYt
> mtl Session 6 Care Coordination Module Final1_1 – https://bcove.video/2POCoP0
> mtl Session 6 Aggregate Module Final1_1 – https://bcove.video/35lRbaf
> mtl Session 5 Suicide Prevention Module Final1_1 – https://bcove.video/2PgYXN5
> mtl Session 5 Psy Module Final1_1 – https://bcove.video/34gfrJG
> mtl Session 5 Med Management Module Final1_1 – https://bcove.video/2snBuko
> mtl Session 5 Care Coordination Module Final1_1 – https://bcove.video/34fw7AR
> mtl Session 5 Aggregate Module Final1_1 – https://bcove.video/36xbi5t
> mtl Session 4 Final1_1 – https://bcove.video/36E0XF7
> mtl Session 3 Final1_1 – https://bcove.video/38Buyk2
> mtl Session 2 Final1_1 – https://bcove.video/2PGS6vo
> mtl Session 1 Final1_1 – https://bcove.video/2PBJxli

@dlkibbe the current video links

**Comment by staceypark** [comment]
I've updated the documentation for Session 05 as part of #1043.
Jenn created gifs for this as part of #1060
