### ISSUE TITLE
Units correction needed for output chart

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#753]
**1. Add description:** 
In PSY we have Completing Rate and Completion Rate. In the Results Dashboard, they both show units as appts/wk. **CompleTION Rate should be pts/wk**.

<< Paste screenshots here>>
 
![image](https://user-images.githubusercontent.com/29778290/66335281-b3f99800-e908-11e9-8e06-8d8d3cb9bcea.png)

**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by jamesmrollins** [comment]
@branscombj I have verified this in the Vensim model, updated the master_crosswalk_table and will refer to @hirenp-waferwire for correction.  Thanks, James

**Comment by jamesmrollins** [comment]
@branscombj This is done and in PROD.

**Comment by lzim** [comment]
Can we close this issue? @branscombj and @jamesmrollins

**Comment by jamesmrollins** [comment]
@lzim @branscombj  OK with me.

**Comment by branscombj** [comment]
Me too!
