### ISSUE TITLE
type in function for "Number" dropdown in Save Experiment dialogue

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#757]
1. In every other dropdown, we are able to start typing in the variable name and select it from a shortened list to prevent scrolling through the dropdown. Wondering if it is possible to have this function for the "Number" dropdown in the Save Experiment dialogue because the range is -8000 to 8000,

@lzim Do you think this a useful add?

**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_ 44 hrs.

**Edit the due date (if necessary)**

**Comment by jamesmrollins** [comment]
@staceypark  @lzim  Probably can do this.  I will check it out.  I agree, scrolling through 16,000 numbers in increments of one is not very user friendly.

**Comment by lzim** [comment]
> @staceypark @lzim Probably can do this. I will check it out. I agree, scrolling through 16,000 numbers in increments of one is not very user friendly.

- Makes sense. Let us know and we can decide if it should happen now or in a future release.

**Comment by jamesmrollins** [comment]
@lzim @staceypark  I have updated the hours required to complete this in the template at beginning of thread.

**Comment by staceypark** [comment]
@lzim - @jamesmrollins updated the hours required to complete (5 hours) and recommends we do this as part of this version of MTL instead of as a future release

**Comment by lzim** [comment]
Thanks @jamesmrollins and @staceypark 

- So, it will be 5 hours to do this in the SAVE dialogue, with recommendation to do this now.
- I approve developing this improved functionality.

Two Related Questions:
1. Is there any way to undo only the last step of a SAVE dialogue name, like a "backspace?" Rather than just "x" out of the whole dialogue? I often have carefully crafted a complex run, only to make a mistake and have to start over completely. I've seen learners make the same mistake during our _MTL Facilitator_ training.
![image](https://user-images.githubusercontent.com/7454688/67253616-cfe75880-f435-11e9-85b1-fde191d86c6d.png)

2. _Experiment Section_: Is there any way to be able to type in the boxes on the sliders?

**Comment by jamesmrollins** [comment]
@lzim for some reason GitHub isn't allowing picture uploads.  Regarding number 1 and 2 above.  I believe we can, but it will add to the estimated hours.  I will continue as if I have permission to develop those, and will update total hours when we complete.

**Comment by jamesmrollins** [comment]
hi @lzim adding in the backspace functionality will add an additional 3-4 hours.  We are taking a look at the Experiment Slider, should be able to give you an estimate soon.  Keep in mind there are bucket-load of experiment sliders. 🗑

**Comment by lzim** [comment]
> hi @lzim adding in the backspace functionality will add an additional 3-4 hours. We are taking a look at the Experiment Slider, should be able to give you an estimate soon. Keep in mind there are bucket-load of experiment sliders. 🗑

- Okay great, the backspace will be really helpful.

- You’re right about the many sliders, keep me posted.

**Comment by jamesmrollins** [comment]
@lzim it will take 35 hours to change the slider functionality to allow direct user type-in input. Below is the breakdown:

   -> There are approx 132 number experiment sliders in all 5 (CC, MM, AGG, PSY, SP) models.
   -> Field input changes impact existing code, so need to change code to convert read only field to input field and allow user input.
   -> Create a field input validation code, so user is constrained to the number increment and decimal value.
   -> Designing changes and verify to following screen resolution  
        3200 X nnnn
        1920 X nnnn
        1680 X nnnn
        1440 X nnnn
        1360 X nnnn
        1280 X nnnn
        1024 (tablets) X nnnn
        768 (tablets) X nnnn
        Mobiles   
  -> Functional testing.

**Comment by lzim** [comment]
@jamesmrollins 

- Thanks, the 35 hours to type in values for all sliders sounds like a future release. 

FYI: @staceypark

**Comment by jamesmrollins** [comment]
@lzim @staceypark 
Thanks Lindsey, I will break this feature out into its' own number and move to the future project.  I will reference back to this issue.  Thanks James.

**Comment by staceypark** [comment]
tested and works great!
