### ISSUE TITLE
SP: Error Message following Experiment Run

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#758]
**1. Add description:** 
Ran an experiment in the SP module, my individual world. I got an error message at the end of the run but I didn't think to take a screen shot quick enough. All the sliders within the red, green and purple boxes disappeared.

FYI: @jamesmrollins 
@dlkibbe sent us both a screenshot of the issue as she was not able to post it to GitHub since she was on VPN.

@dlkibbe Note: Issues need to go on mtl.how/teampsd not the mtl.how repository. I moved it for you.

<< Paste screenshots here>>
 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by dlkibbe** [comment]
@staceypark that's what I was trying to ask on the phone but not intelligently! Thanks for moving the issue.

**Comment by staceypark** [comment]
@jamesmrollins says that sometimes the sim does not load properly, due to slow communications on the Internet, exacerbated with use of VPN. If this happens again, he recommends you logout & log back in. He has experience the issue outside of the VPN as well. There is not much else we can do, especially without the error message.
