### ISSUE TITLE
Deadline + Product: Short description (ex. 8/12 AGG: Missing feedback loop)

### ISSUE THREAD

**Issue by dlounsbu** [lzim/teampsd#759]
**1. Add description:** 

#294 Videos do not load.  I get a black screen. Video is not found.

<< Paste screenshots here>>
 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [x]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by lzim** [comment]
Duplicate with closed issue #760 

> @dlounsbu

> These links are outdated & not working by design.

 > Go to the appropriate session card in mtl.how/documents

> The current video links are there.

> I also updated our ahsr_2019 OSF project with the current MM video links

**Comment by dlounsbu** [comment]
Thanks

**Comment by dlounsbu** [comment]
@lzim : The links are working! I will watch them over the weekend. Don't think we need to talk this evening (10/11).
