### ISSUE TITLE
comparator_cpt merge MERGE with issue #205

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#76]
Hi @saveth and @joycepyang!

I started an issue for this, so we can track our progress easily.

**Joyce's questions from her pull request**
https://github.com/lzim/teampsd/pull/74
Thank you for reviewing this code for me. I used most of the same code that you already cleaned and reviewed for me for the anti_join code. In order to make sure that the CDW_minus_merge data we are looking at is only the data with dates that match the CPT dataset, I entered the following based on the timeframe, so the new code starts at Line 80: filter(year_q == 2012Q2:2016Q3) %>%

For the second issue of making sure that we are looking at number of clinics and not number of observations, I believe I should be doing the analyses based on unique number of sta6a and sta3n combinations versus observations. To do this, I'm trying to generate a concatenated variable sta6asta3n. When I examine the frequencies of this I can tell the unique number of combinations. Is that the right way to think about this?

Additionally however, I'm not very clear on how to run subsequent descriptors of other variables (e.g., total encounters) that is not a mean of each observation of total encounters, but instead is a mean of total encounters based on unique combinations of sta6a & sta3ns (i.e., clinics). i.e., I believe I still cannot do describe(cdw_minus_merge.df$totalencounters) for example, because that will still give me descriptive statistics on totalencounters based on observations and not unique sta6asta3n combinations. Can you please help me with this code?

**Next steps from Lucid quant_workgroup notes:**

 Next Steps: #1 Need to clarify in the column headings (ideally) what the measure is below (proportion, count, etc.)

- Next Steps #2: Do not need a mean and SD for complexity as that is a nominal/factor variable.

2. Feedback on labels and understanding the data structure for each dataset:

- Next Steps #3: Need to describe the # of unique sta6a in each dataset (CPT and CDW) and describe the number of observations of each unique sta6a (clinic).

3. Notable findings in the table:

- Although the means are similar, the SD for Total Encounters varies significantly between the CPT and CDW dataset.

-Next Steps #4: It would be helpful to produce graphs of the distributions of the variables for the CPT and CDW datasets as part of the data exploration

4. Due to the longitudinal/observational focus of our primary analyses, we do need to understand whether these measures of central tendency in each data set are obscuring secular trends. Specifically, it is very likely that overall demand for services (as measured by encounters), and adoption of EBPsy (as measured by CPT and PE templates) is increasing 

- Next steps #5: To explore and report on this, we would need graphs over time that show the measure of central tendency for each quarter observed in the dataset, with "error bars" that show the standard deviation.

**Comment by saveth** [comment]
Copying comments from pull #74 

@joycepyang Regarding year range, it's fine to use filter(year_q == 2012Q2:2016Q3) %>% if it's giving you the same year range in both dataset.

As for facilities, sta6a is already the unique identify for each location. You can derive sta3n from the sta6a code, therefore concatenating the two variables would be unnecessary. You'll want to do tab(sta6a), length(tab(sta6a)) or unique(sta6a) to identify how many clinics is in your dataset.

With regards to the encounters, you'll want to examine the mean of the totalencouter variable, and the mean for each clinic: group_by (sta6a) %>% summarize( mean = mean(totalencounter), sd = sd(totalencounter)). This will give you the mean and sd for each facility across all their year_quarter data. Then you might want to graph it to see if there are differences across facilities. Another way to consider it is group_by(year_quarter) %>% summarize(mean = mean(totalencounter), sd = sd(totalencounter)) which will then create mean and sd across all facilities for each year. Then graph this, to see if there are variation across the years that can explain the variation in your grand mean and sd.

Is this enough to help you move your coding/analysis along? If you need clarification, we can talk tomorrow night.

**Comment by lzim** [comment]
Thanks @saveth!

**Comment by lzim** [comment]
Hello @joycepyang and @saveth - we need to merge this outstanding issue #76 with issue #205 Joyce created yesterday. 

Specifically, we don't want to lose track of the time-based displays Next Steps #4, 4 and 5, which are still outstanding on this issue.

Thanks,

Lindsey

**Comment by lzim** [comment]
I’m going to pull item 4 and 5 our and post with the other most recent duplicate issue #205
