### ISSUE TITLE
10/14 MM: Video Links Not Working 

### ISSUE THREAD

**Issue by dlounsbu** [lzim/teampsd#760]
**1. Add description:** 

#294 Links here do not work. I cannot get any videos to play. 

![image](https://user-images.githubusercontent.com/20574023/66687512-cd744a00-ec50-11e9-8f29-d60c6faf9996.png)

**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [x]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by lzim** [comment]
@dlounsbu 

These links are outdated & not working by design. 

Go to the appropriate session card in mtl.how/documents

The current video links are there. 

I also updated our ahsr_2019 OSF project with the current MM video links
