### ISSUE TITLE
wk1_mar: User Type-in Functionality for Experiment Sliders

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#779]
@lzim it will take 35 hours to change the slider functionality to allow direct user type-in input. Below is the breakdown:

   -> There are approx 132 number experiment sliders in all 5 (CC, MM, AGG, PSY, SP) models.
   -> Field input changes impact existing code, so need to change code to convert read only field to input field and allow user input.
   -> Create a field input validation code, so user is constrained to the number increment and decimal value.
   -> Designing changes and verify to following screen resolution  
        3200 X nnnn
        1920 X nnnn
        1680 X nnnn
        1440 X nnnn
        1360 X nnnn
        1280 X nnnn
        1024 (tablets) X nnnn
        768 (tablets) X nnnn
        Mobiles   
  -> Functional testing.

_Originally posted by @jamesmrollins in https://github.com/lzim/teampsd/issues/757#issuecomment-545964054_

![image](https://user-images.githubusercontent.com/30132017/67586022-8b91dc00-f705-11e9-95d3-9d6c8b7c0911.png)

**Comment by lzim** [comment]
Thanks @jamesmrollins

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire 

- The type-in functionality looks good and is working! 
- We need to change the tab order to make best use of this feature. 
- Can we associate the name of the data-input box with the variable name in order to maintain 508 compliance? 
- If we can somehow do that, then new tab order would be, data box - "i" information - next data box. and so on. We would skip the units of measure tab-stop since the units of measure are also indicated in the "i" information.
