### ISSUE TITLE
Team PSD Webpage: Install a photo upload capability to the admin page.

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#782]
**1. Add description:** 
This issue is referenced to #620, which is quoted below. Items 1 and 2 are complete.  Complete item 3, install upload photo utility for the Team PSD admin web page. 

> **Estimate:** 20 Hrs for Items 1 and 2. Item 3 estimate 15 hrs
> **Design Objectives:**
> 
> 1. Install a button or link in the header of the Sim UI page header that will enable users to upload a picture.
> 2. Install a utility that guides users through uploading a photo, centering the photo in a frame and then putting photo in the Sim Ui page header.
> 3. Install same upload utility in the Team PSD website admin page. (let me know if this was not a part of original estimate – I don’t recall if we discussed this or not).
> 
> ![image](https://user-images.githubusercontent.com/30132017/67448599-559d0c80-f5cc-11e9-81ca-da118b06ba0f.png)
> 
> ![image](https://user-images.githubusercontent.com/30132017/67448695-9f85f280-f5cc-11e9-9431-e5ce22bdde25.png)
> 
> ![image](https://user-images.githubusercontent.com/30132017/67448703-a9a7f100-f5cc-11e9-9c81-309714f02ac9.png)

**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_15 hrs.

**Edit the due date (if necessary)**

**Comment by anthonycpichardo** [comment]
accidentally turned this into an epic. Created new issue 1246 to replicate its contents.

Sorry. theres no undo button =(

**Comment by epearman** [comment]
#ajudicate_memo
