### ISSUE TITLE
Task: Link "i" Information Directly to Comments Field in Vensim Models 

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#784]
**1. Add description:** Create an admin page to manage "i" information and Team Data Table information entries. This will reduce errors and version control issues, as there will be only one record. 

<< Paste screenshots here>>
 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by lzim** [comment]
@lzim and @jamesmrollins reviewed this at 4/9/2020 Sim UI meeting:

**#784 Admin Page for "i" information.**
 a. The "boon" here is that there won't need to be a admin panel, rather the Sim UI will sync with variables in the Vensim models.

b. The advantage of 1**00% sync is the scientific models and the UI are 100% consistent at all times, this would correspond to #1220 requirement 3, which is replicate the SDM-DOC as a "Model Documentation" or "Technical Specs" section of mtl.how/demo.**

c. The task then would be to take the MTL 2.0 Vensim models that we know are out-of-sync with the Sim UI and make sure that they all align.


**Cross-ref Requirements 1-3 of #1220 -**

GOAL: _Building a solution for auto-checking and correcting inconsistencies in any model component (i.e., variable name, "i" information, etc) anywhere across MTL resources (data, Vensim models, UI, tt reports, guides)_

- ...First phase of implementation would be data, Vensim, UI... (but should keep in mind a standardization goal across all our resources.

**To Be Determined:** Could the database management solution proposed for the master crosswalk: in requirement 1 & 2 to check for exceptions, could automate checking for inconsistencies among models, Data UI, Sim UI, etc.?

- This would be great to focus on first to fix all current inconsistenceis to make all of our resources consistent with one another.

- Use case, MTL COP identifies a new name for a variable - corrects all instances automatically.

**Comment by jamesmrollins** [comment]
@lzim @staceypark we decided in the 4/13 WG Leads meeting to move this to the May sprint because we are being blocked by Forio. 

This may also have a dependency on #1220 as the parsing-comparison function may be useful in updating model comments, versus having to do it by hand.

**Comment by jamesmrollins** [comment]
@lzim @staceypark @branscombj @dlkibbe  

### Request
**I need your permission to change the title of the "i" information box for user-defined variables.**

### Recommendation
Allow the "user-defined" prefix to be used in the title of experiment variables and ensure this convention is consistent across all models. 

### Facts Bearing on the Problem
1.  I am hooking up the title of the "i" information dialogue directly to the model-variable name field and pulling the explanation text directly from the model-variable comment field (see code in first picture).  This removes the need for the .xlsx "i" information files.  However, since we are now referencing the variable directly for title and "i" information, we have issues like the below, where the slider is named "user-defined" (see pictures below).  
2.  The variable name is technically accurate, as it is a user-defined variable, and the explanation is also correct.  However, this is the case where the "Referral Rate" does not have a slider widget separate from the rate dial, but is instead integrated in the main diagram (see last picture).  
3.  It would be very easy to copy the Referral Rate explanation to the user-defined variable comments section to keep it consistent.  

![image](https://user-images.githubusercontent.com/30132017/101289635-91843880-37b2-11eb-996c-ef0dcc3e76d0.png)

![image](https://user-images.githubusercontent.com/30132017/101289615-6ef21f80-37b2-11eb-84ca-9ebb7070c11d.png)

![image](https://user-images.githubusercontent.com/30132017/101289623-7fa29580-37b2-11eb-9b21-dd32feea64b6.png)

**Comment by jamesmrollins** [comment]
@lzim would prefer to screen-out "user-defined" or "user" from the name of the variable and only show the core variable name.

**Comment by jamesmrollins** [comment]
This coding is complete and testing is managed under issue #1637
