### ISSUE TITLE
30 Nov:  Conduct On-board Brief w/MH Leaders and Program Leads

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#786]
**1. Add description:** 
Contact and brief program leads, gather advice and support.  Publish call reports:
Kelly Maeiritsch, Claire Collie, Shannon Wiltsey-Stirman.
Contact Cerner: David Kirksey
Contact and elicit support from VISN:
Dr. Indest
Contact and Elicit Support from American Lake:
Dr. Jesse Markman, Chief/ Greg Reger, dpty
Contact and coordinate with Communities of Practice:
Peggy Henderson - Psychosocial Therapy
Pearl McGee - Dissemination Branch , Center for PTSD

<< Paste screenshots here>>
 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by lzim** [comment]
@jamesmrollins 

These four folks I know very well. The first two are part of *MTL,* the second two NCPTSD. 

Claire Collie
Shannon Wiltsey-Stirman
Kelly Maeiritsch
Pearl McGee Vincent

Let me know if/when/how I can help.

**Comment by jamesmrollins** [comment]
Thanks @lzim .  So far no issues getting meetings with them.  All very supportive of effort.  One thing we need to discuss when we get with Chris, is how we set up communications and discussion.  Can we stay within policy by using extra-domain resources?
