### ISSUE TITLE
Manage Psychotherapy Tool Project Meetings

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#789]
**1. Add description:** 

- Manage psychotherapy tool meetings.  
- Provide notes and manage action items.  
- Schedule meetings and notify participants. 

<< Paste screenshots here>>
 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by jamesmrollins** [comment]
10/29/2019 Project Meeting Notes
[psychotherapy_tool_project_mtg_october_29_2019.docx](https://github.com/lzim/teampsd/files/3786263/psychotherapy_tool_project_mtg_october_29_2019.docx)

**Comment by jamesmrollins** [comment]
September 2019 Meeting Notes
[teampt_meeting_3_sep .docx](https://github.com/lzim/teampsd/files/3795299/teampt_meeting_3_sep.docx)
[teampt_meeting_24_sep.docx](https://github.com/lzim/teampsd/files/3795300/teampt_meeting_24_sep.docx)
[Psychotherapy_Tool__Outgoing_Message__Leadership_September_10_2019.pdf](https://github.com/lzim/teampsd/files/3795301/Psychotherapy_Tool__Outgoing_Message__Leadership_September_10_2019.pdf)
[Psychotherapy_Tool__Outgoing_Message__Leadership_September_24_2019.pdf](https://github.com/lzim/teampsd/files/3795302/Psychotherapy_Tool__Outgoing_Message__Leadership_September_24_2019.pdf)
[teampt_meeting_3_sep .docx](https://github.com/lzim/teampsd/files/3795303/teampt_meeting_3_sep.docx)
[teampt_meeting_24_sep.docx](https://github.com/lzim/teampsd/files/3795304/teampt_meeting_24_sep.docx)

**Comment by jamesmrollins** [comment]
October Meeting Notes
[Psychotherapy_Tool__Outgoing_Message__Leadership_October_1_2019.pdf](https://github.com/lzim/teampsd/files/3795306/Psychotherapy_Tool__Outgoing_Message__Leadership_October_1_2019.pdf)
[Psychotherapy_Tool__Outgoing_Message__Leadership_October_8_2019.pdf](https://github.com/lzim/teampsd/files/3795307/Psychotherapy_Tool__Outgoing_Message__Leadership_October_8_2019.pdf)
[Psychotherapy_Tool__Outgoing_Message__Leadership_October_17_2019 (2).pdf](https://github.com/lzim/teampsd/files/3795308/Psychotherapy_Tool__Outgoing_Message__Leadership_October_17_2019.2.pdf)
[psychotherapy_tool_project_mtg_october_29_2019.docx](https://github.com/lzim/teampsd/files/3795309/psychotherapy_tool_project_mtg_october_29_2019.docx)
[psychotherapy_tool_project_mtg_october_31_2019.docx](https://github.com/lzim/teampsd/files/3795310/psychotherapy_tool_project_mtg_october_31_2019.docx)
[Psychotherapy_Tool_Weekly_Meeting_October_22_2019.pdf](https://github.com/lzim/teampsd/files/3795311/Psychotherapy_Tool_Weekly_Meeting_October_22_2019.pdf)

**Comment by jamesmrollins** [comment]
@psychcrowe and @Mohmer99 I will post meeting notes in GitHub.  If you have any comments, or agenda items to add before next meetings, you can put them in this discussion thread.  Thanks James

**Comment by jamesmrollins** [comment]
@psychcrowe @Mohmer99  I changed the meetings to 1 PM EST and moved next Tuesday's meeting to Wednesday at 1 PM EST.

**Comment by jamesmrollins** [comment]
@psychcrowe and @Mohmer99 Meeting minutes for 11/5 meeting.
[psychotherapy_tool_project_mtg_nov_5_2019.docx](https://github.com/lzim/teampsd/files/3810689/psychotherapy_tool_project_mtg_nov_5_2019.docx)

**Comment by Mohmer99** [comment]
@jamesmrollins are the minutes above from today?  Date on them states October 31.  I just wanted to review and see what I can offer to the plans and schedule.  Thanks!

**Comment by jamesmrollins** [comment]
@psychcrowe and @Mohmer99 Meeting minutes for 11/12 meeting;

[psychotherapy_tool_project_mtg_nov_12_2019.docx](https://github.com/lzim/teampsd/files/3837725/psychotherapy_tool_project_mtg_nov_12_2019.docx)

**Comment by jamesmrollins** [comment]
@psychcrowe and @Mohmer99 Meeting minutes for 11/26 meeting:
[psychotherapy_tool_project_mtg_nov_26_2019.docx](https://github.com/lzim/teampsd/files/3893612/psychotherapy_tool_project_mtg_nov_26_2019.docx)

**Comment by jamesmrollins** [comment]
meeting minutes for 11/21 meeting:

[psychotherapy_tool_project_mtg_nov_21_2019.docx](https://github.com/lzim/teampsd/files/3912649/psychotherapy_tool_project_mtg_nov_21_2019.docx)

**Comment by jamesmrollins** [comment]
Meeting minutes for 12/03 meeting:
[psychotherapy_tool_project_mtg_dec_03_2019.docx](https://github.com/lzim/teampsd/files/3941239/psychotherapy_tool_project_mtg_dec_03_2019.docx)

**Comment by jamesmrollins** [comment]
Meeting minutes for 12/10 meeting:
[psychotherapy_tool_project_mtg_dec_10_2019.docx](https://github.com/lzim/teampsd/files/3946730/psychotherapy_tool_project_mtg_dec_10_2019.docx)

**Comment by jamesmrollins** [comment]
Meeting minutes for 12.16 meeting:
[psychotherapy_tool_project_mtg_dec_16_2019.docx](https://github.com/lzim/teampsd/files/3975193/psychotherapy_tool_project_mtg_dec_16_2019.docx)

**Comment by jamesmrollins** [comment]
12.24 Meeting was a non-conduct.  However, meeting updates attached.
[psychotherapy_tool_project_mtg_dec_24_2019.docx](https://github.com/lzim/teampsd/files/3998851/psychotherapy_tool_project_mtg_dec_24_2019.docx)

**Comment by jamesmrollins** [comment]
Meeting for 1.7 attached
[psychotherapy_tool_project_mtg_jan_07_20.docx](https://github.com/lzim/teampsd/files/4093124/psychotherapy_tool_project_mtg_jan_07_20.docx)

**Comment by jamesmrollins** [comment]
Notes for meeting for 1.21 attached:

[psychotherapy_tool_project_mtg_jan_21_20.docx](https://github.com/lzim/teampsd/files/4093128/psychotherapy_tool_project_mtg_jan_21_20.docx)

**Comment by jamesmrollins** [comment]
Notes for meetings 2/3. 2/18. and 2/25
[psychotherapy_tool_project_mtg_feb_3_20.docx](https://github.com/lzim/teampsd/files/4252117/psychotherapy_tool_project_mtg_feb_3_20.docx)
[psychotherapy_tool_project_mtg_feb_18_20.docx](https://github.com/lzim/teampsd/files/4252118/psychotherapy_tool_project_mtg_feb_18_20.docx)
[psychotherapy_tool_project_mtg_feb_25_20A.docx](https://github.com/lzim/teampsd/files/4252119/psychotherapy_tool_project_mtg_feb_25_20A.docx)
