### ISSUE TITLE
mtl_how_readme_edits

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#790]
**1. Add description:** 

A few suggestions for the ReadMe page at mtl.how:

1. Top line: mtl 1.7 and 1.8 **<--- Does this have to be here? The versions are repeated below.**

2. Modeling to Learn by Team PSD - Release 1.7 and 1.8 **<--- Could this be moved below the logo? The sooner the eye can find that friendly signpost, the better. As it is, the view of the GitHub header and file directory is a pretty intimidating place to land, for anyone unfamiliar with GH.** 

3. **It might even be worth putting another "click" layer in - all the Session folders behind one main folder - so that the MTL Logo and the information below it are immediately in view.**

4. Modeling to Learn Links **<--- The URLs are all shown with "www." - It would be nicer without, since it isn't necessary to type it.**

5. MTL Facilitate - coming in FY2019!* **<--- This asterisk does not have a referend.**

6. SP module "for" to "and" corrections needed.

<< Paste screenshots here>>
 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by branscombj** [comment]
@staceypark These are some suggestions about the (current) mtl.how page to try to make it easier for learners or visitors to grasp and use. Of course, this page might change based on today's discussion about the Red and Blue versions of MTL.

**Comment by staceypark** [comment]
these edits have already been addressed at the current mtl.how
