### ISSUE TITLE
November Splashpage update

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#794]
**1. Add description:** 
To run the Splashpage update at the beginning of each month, we need a computer that has the SQL Management Studio software on it. @ritahitching and I asked IT to download it for TeamPSD machines, but they have not yet. We were going to try running the Splashpage update ourselves as a test to see if we understood Andrew's instructions, but without the software we cannot run it.

@saveth I believe you have it on your machine you work on from home? We may need you to do the November update. 

<< Paste screenshots here>>
 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by saveth** [comment]
@staceypark I would be happy to help run the Splashpage for the month. Where are the instructions that Andrew left with you on how to run it? 

FYI: @saveth @ritahitching

**Comment by saveth** [comment]
@staceypark @ritahitching I found the instruction and am running the update now.
