### ISSUE TITLE
12/4 R21 RedCap: Post Evaluation

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#820]
@jessfroe 

I didn't see this in the R01 and IIR measures, which you plan to program by next Monday. But, are you able to just program the R21 Post Evaluations? We are updating Stockton and Menlo Park and it would be great if we could point them directly to the link to provide us feedback. 

- It is only 10 items. Please let us know. We are heading to Stockton this morning 😸 

Thanks!

FYI: @staceypark and @ritahitching 
-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by jessfroe** [comment]
@lzim 
The R21 pre, mid and post evals are all in RedCAP, just missing some finishing touches. Unless I am mixing up the questionnaires - @staceypark can you clarify for me? This is what I already completed, right? 
I can definitely finish this tomorrow before noon. I see the due date is tomorrow, but you are heading to a site today. Did you need it today?

**Comment by staceypark** [comment]
@jessfroe yes this is what you finished, but Lindsey and I need to be added to the VA RedCAP Project that you've put these under, or else we will not be able to access them.

**Comment by jessfroe** [comment]
@staceypark @lzim 
Great, I'll add you both tomorrow as well as complete the surveys so you can distribute.

**Comment by lzim** [comment]
Awesome, thanks so much @jessfroe 💯 

We'll circulate the links to the Stockton CBOC tomorrow. And, we'll circulate to the other clinics over the next few weeks as we update all of them too.

Thanks again !

**Comment by jessfroe** [comment]
@lzim @staceypark 
I added you both to the REDCap project
Post-evaluation is ready to go! Just a few more things to edit for the pre and mid, and then those will be completed as well

**Comment by jessfroe** [comment]
All are now completed, closing this issue.

**Comment by staceypark** [comment]
@jessfroe 
1.	We are going to need a survey specific to each team.
Can you pipe the backend so there’s a survey that asks which team they’re on and then based on their answer, leads them to their team specific survey? (similar to how we did the backend for the fidelity survey where we ask which team & session they’re on to lead them to the specific survey for that teams’ session) --- Please see my email for the team names

2.	Can you make sure to add a section for the tt report and update the survey title to say “Please provide feedback and ideas to improve Modeling to Learn” for the additional surveys you’re creating based on instruction #1? (I’ve already done the one for the PCT as you saw in the link below, so it just needs to look the same)

**Comment by jessfroe** [comment]
@staceypark got it
So, the survey is the same, they are just separate surveys for each individual team? Underneath the same project, right?

**Comment by staceypark** [comment]
yep you got it! :)

**Comment by jessfroe** [comment]
Okay, @staceypark and @lzim, project is updated. Stacey, the correct tt_report for each team needs to be uploaded. 
Let me know if there is anything else I can do for this today.

**Comment by staceypark** [comment]
@jessfroe @lzim 
Two interesting things:
1. If they don't all have a PDF attached to that tt report item, then the PDF shows for none of them.
2. Somehow, I can't make a different PDF show for the different choices. They all seem to show the one for the first instrument?!

Conclusion: I think we may need to either:
1. Disaggregate the surveys into separate projects each (currently they are all under one project or "link" in a similar manner as the mtl fidelity survey was for facilitators) or 
2. When we send the link to the survey, attach the tt3 report in the same email.

I like Option 2, for scalability in the future as well. I don't think we want to have a large proliferation of REDCap projects?

**Comment by lzim** [comment]
> When we send the link to the survey, attach the tt3 report in the same email.

This sounds fine to me. Thanks!
@staceypark & @jessfroe

**Comment by staceypark** [comment]
@jessfroe  Looks great thanks! One thing I would keep in mind as you're creating the other ones, we do not folks to be able to see the aggregated results as this our research data. I turned the function "off" in the survey settings. Let me know if you need me to show you where it is.

**Comment by lzim** [comment]
Hi @staceypark 

I'm still looking for these links/tt3 reports and emails 👍 

Thanks!

**Comment by staceypark** [comment]
I just reforwarded to you. Lmk if you don't get it

**Comment by jessfroe** [comment]
Hi, is this all good to go now? I noticed it was re-opened in December, not sure if the kinks were ironed out or not.

**Comment by staceypark** [comment]
Links sent to r21 teams. We can close this issue now.
