### ISSUE TITLE
SEE & SAY Guides and Master Brochure Comparisons

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#825]
**SEE & SAY Guides and Master Brochure Comparisons:**

**Comment by ritahitching** [comment]
Sessions | SEE Guide | SAY Guide | Master | Notes
-- | -- | -- | -- | --
1 |   |   |   |  
2 |   |   |   |  
3 |   |   |   |  
4 |   |   |   |  
5 |   |   |   |  
6 |   |   |   |  
7 |   |   |   |  
8 |   |   |   |  
9 |   |   |   |  
10 |   |   |   |  
11 |   |   |   |  
12 |   |   |   |

**Comment by ritahitching** [comment]
@staceypark table noting the discrepancies in the SEE / SAY and EES guides for Elizabeth.

**Comment by staceypark** [comment]
Thanks @ritahitching for producing this table! I made some edits above.
@lzim we are trying to setup a meeting with Elizabeth, Julie, Jane, and us. We can present these as well as the MTL Blue / MTL Red during that time. Should we give only the edits or a full set of objectives 1-12 that incorporates all the edits?

**Comment by staceypark** [comment]
@ritahitching as your next step on this could you:
1. Create a new branch
2. update the SEE guides and Master Brochures to match the Learning Objectives in the SAY guides.
3. Create a pull request to me.

Let's walk through 1-2 examples together, before you do the entire batch. Thanks!

**Comment by ritahitching** [comment]
> @ritahitching as your next step on this could you:
> 
> 1. Create a new branch
> 2. update the SEE guides and Master Brochures to match the Learning Objectives in the SAY guides.
> 3. Create a pull request to me.
> 
> Let's walk through 1-2 examples together, before you do the entire batch. Thanks!

@staceypark sure, no problem.  I'll get started and check in with you when you arrive.

**Comment by ritahitching** [comment]
@staceypark 

**Learning Objectives from Master Brochure by Session** 

**Session** | **Learning Objectives**
-- | --
**1** | 1. Describe your own vision for what you would like your team   to get from Modeling to Learn.
  | 2. Test out your thinking with your team about what your   shared vision is for becoming a "dream team."
  | 3. Identify a shared team vision for learning from Modeling to   Learn.
  |  
**2** | 1. Describe the decisions your   team made in producing your team data table.
  | 2. Test out whether your   expectations about team historical trends are displayed in the   "viz" tabs.
  | 3. Apply your clinical expertise   to identify new information about a team patient in the "data"   tabs.
  |  
**3** | 1. Describe your team trends   over the last two years based on the estimates in the team data table.
  | 2. Test out whether your   understanding of how the team data is estimated through review of the   descriptions and definitions.
  | 3. Apply your clinical expertise   to consider the team trends in the data UI and team data table to identify   team priorities for learning.
  |  
**4** | 1. Describe the high priority   needs reported across the team.
  | 2. Test out how these needs are   experienced across the team through team dialogue.
  | 3. Consider the team vision and   apply team decision-making to select a high-priority module of MTL.
  |  
**5** | 1. Describe the team data in the   experiments tile.
  | 2. Test out the simulation user   interface for more information about team data.
  | 3. Apply clinical expertise to   consider the decisions the team makes that affect these variables.
  |  
**6** | 1. Describe the systems story of   your team's highest priority.
  | 2. Test out your thinking about   causes of team challenges using the model diagram.
  | 3. Apply clinical expertise to   develop a question for team learning using simulation.
  |  
**7** | 1. Describe the base case of no   changes in your team.
  | 2. Test out your thinking about   what is likely to cause oscillation in team treands.
  | 3. Apply systems thinking to   develop a hypothesis about your team's clinical priority.
  |  
**8** | 1. Describe the systems story   your team believes will cause the outcomes you expect to observe in your   experiment.
  | 2. Test your dynamic hypothesis   about your team's clinical priority.
  | 3. Apply systems thinking to   describe your team's findings, insights, and conclusions from your   experiment.
  |  
**9** | 1. Describe the systems story   your team believes will cause the outcomes you expect to observe in your   experiment.
  | 2. Test your dynamic hypothesis   about your team's clinical priority
  | 3. Apply systems thinking to   describe your team's findings, insights ad conclusions from your experiment.
  |  
**10** | 1. Describe the decisions you   experimented with and how they are intertwined with other decisions and   clinic outcomes.
  | 2. Test your understanding of   the system story by describing what is happening when the model produces a   runaway increase or decrease in some ouput.
  | 3. Apply your thinking to   anticipate the long-term trend in your clinic's EBP reach under two different   decision scenarios.
  |  
**11** | 1. Describe what your team has   prioritized as decisions to implement in your clinic.
  | 2. Test your team's plan against   your individual and shared, team vision.
  | 3. Apply your team's plan in   clinical decisions.
  |  
**12** | 1. Describe what your team has   learned and prioritized throughout the MTL 12 session program.
  | 2. Test how your team's plan   aligns with your team's shared vision.
  | 3. Apply decisions that your   team has prioritized to implement in the clinic.

**Comment by ritahitching** [comment]
@staceypark 

**Comparison between SEE and SAY guides**
**Yes** = match between guides
Please review the SAY guides with the extra information (Sessions: 1, 2, 7, 8, 9, 10, 11)

Session | SEE Guide | SAY Guide | Links
-- | -- | -- | --
1 |   |   |  
Do | Yes | Yes | Yes
Done | Yes, extra detail | Yes | Yes
  |   |   |  
2 |   |   |  
Do | Yes, extra detail | Yes | Yes
Done | Yes | Yes | Yes
  |   |   |  
3 |   |   |  
Do | Yes | Yes | Yes
Done | Yes | Yes | Yes
  |   |   |  
4 |   |   |  
Do | Yes | Yes | Yes
Done | Yes | Yes | Yes
  |   |   |  
5 |   |   |  
Do | Yes | Yes | Yes
Done | Yes | Yes | Yes
  |   |   |  
6 |   |   |  
Do | Yes | Yes | Yes
Done | Yes | Yes | Yes
  |   |   |  
7 |   |   |  
Do | Yes, extra detail | Yes | Yes
Done | Yes | Yes | Yes
  |   |   |  
8 |   |   |  
Do | Yes, extra detail | Yes | Yes
Done | Yes | Yes | Yes
  |   |   |  
9 |   |   |  
Do | Yes, extra detail | Yes | Yes
Done | Yes | Yes | Yes
  |   |   |  
10 |   |   |  
Do | Yes, extra detail | Yes | Yes
Done | Yes | Yes | Yes
  |   |   |  
11 |   |   |  
Do | Yes, extra detail | Yes | Yes
Done | Yes, extra detail | Yes | Yes
  |   |   |  
12 |   |   |  
Do | Yes | Yes | Yes
Done | Yes | Yes | Yes

**Comment by ritahitching** [comment]
- Send any updated learning objective in the SEE and SAY guides.
- Note discrepancies with to the Master Brochures
- Elizabeth back 1/15

**Comment by ritahitching** [comment]
## **Updated table of EES Learning Objectives Sessions 1 -12**

@staceypark @lzim 
- Please clarify for **Session 5** in **Learning Objective 1** if you want to use the word **section** or **tile**  in the sentence.  
- Some minor typo discrepancies which I will update.

**As soon as I have clarification I will:**
1. Update the Learning Objectives document in our shared drive.
1. Email Elizabeth the updated table of Learning Objectives.
2. Create a pull request to update the in GitHub repo (https://github.com/lzim/teampsd/tree/master/ees_workgroup/master_brochures)

thanks!
Rita


  |   | Stacey Word Doc | Match |   | Rita GitHub Table | Match |   | GitHub Repo Master Brochures |   | Pull Request Changes Needed |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | Session | Learning Objectives |   | Session | Learning Objectives |   | Session |   |   |   |   |  
  | 1 | 1. Describe your own vision for   what you would like your team to get from Modeling to Learn. | Yes | 1 | 1. Describe your own vision for what you   would like your team to get from Modeling to Learn. | Yes | 1 | 1. Describe your own vision for   what you would like your team to get from Modeling to Learn. |   |   |   |  
  |   | 2. Test out your thinking with   your team about what your shared vision is for becoming a "dream   team." | Yes |   | 2. Test out your thinking with your team   about what your shared vision is for becoming a "dream team." | Yes |   | 2. Test out your thinking with   your team about what your shared vision is for becoming a "dream   team." |   |   |   |  
  |   | 3. Identify a shared team vision   for learning from Modeling to Learn. | Yes |   | 3. Identify a shared team vision for   learning from Modeling to Learn. | Yes |   | 3. Identify a shared team vision   for learning from Modeling to Learn. |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |  
  | 2 | 1. Describe the decisions your   team made in producing your team data table. | Yes | 2 | 1. Describe the decisions your team made   in producing your team data table. | Yes | 2 | 1. Describe the decisions your   team made in producing your team data table. |   |   |   |  
  |   | 2. Test out whether your   expectations about team historical trends are displayed in the   "viz" tabs. | Yes |   | 2. Test out whether your expectations   about team historical trends are displayed in the "viz" tabs. | Yes |   | 2. Test out whether your   expectations about team historical trends are displayed in the   "viz" tabs. |   |   |   |  
  |   | 3. Apply your clinical expertise   to identify new information about a team patient in the "data"   tabs. | Yes |   | 3. Apply your clinical expertise to   identify new information about a team patient in the "data" tabs. | Yes |   | 3. Apply your clinical expertise   to identify new information about a team patient in the "data"   tabs. |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |  
  | 3 | 1. Describe your team trends   over the last two years based on the estimates in the team data table. | Yes | 3 | 1. Describe your team trends over the   last two years based on the estimates in the team data table. | Yes | 3 | 1. Describe your team trends   over the last two years based on the estimates in the team data table. |   |   |   |  
  |   | 2. Test out your understanding   of how the team data is estimated through review of the descriptions and   definitions. (remove the word “whether) | No |   | 2. Test out whether your understanding of   how the team data is estimated through review of the descriptions and   definitions. | Yes |   | 2. Test out whether your   understanding of how the team data is estimated through review of the   descriptions and definitions. |   | Remove word "whether" |   |  
  |   | 3. Apply your clinical expertise   to consider the team trends in the data UI and team data table to identify   team priorities for learning. | Yes |   | 3. Apply your clinical expertise to   consider the team trends in the data UI and team data table to identify team   priorities for learning. | Yes |   | 3. Apply your clinical expertise   to consider the team trends in the data UI and team data table to identify   team priorities for learning. |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |  
  | 4 | 1. Describe the high priority   needs reported across the team. | Yes | 4 | 1. Describe the high priority needs   reported across the team. | Yes | 4 | 1. Describe the high priority   needs reported across the team. |   |   |   |  
  |   | 2. Test out how these needs are   experienced across the team through team dialogue. | Yes |   | 2. Test out how these needs are   experienced across the team through team dialogue. | Yes |   | 2. Test out how these needs are   experienced across the team through team dialogue. |   |   |   |  
  |   | 3. Consider the team vision and   apply team decision-making to select a high-priority module of MTL. | Yes |   | 3. Consider the team vision and apply   team decision-making to select a high-priority module of MTL. | Yes |   | 3. Consider the team vision and   apply team decision-making to select a high-priority module of MTL. |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |  
  | 5 | 1. Describe the team data in the   experiments section. (change from “tile” to “section”). | No | 5 | 1. Describe the team data in the   experiments tile. | Yes | 5 | 1. Describe the team data in the   experiments tile. |   | Decide which "Section"   or "Tile" and update |   |  
  |   | 2. Test out the simulation user   interface for more information about team data. | Yes |   | 2. Test out the simulation user interface   for more information about team data. | Yes |   | 2. Test out the simulation user   interface for more information about team data. |   |   |   |  
  |   | 3. Apply clinical expertise to   consider the decisions the team makes that affect these variables. | Yes |   | 3. Apply clinical expertise to consider   the decisions the team makes that affect these variables. | Yes |   | 3. Apply clinical expertise to   consider the decisions the team makes that affect these variables. |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |  
  | 6 | 1. Describe the systems story of   your team's highest priority. | Yes | 6 | 1. Describe the systems story of your   team's highest priority. | Yes | 6 | 1. Describe the systems story of   your team's highest priority. |   |   |   |  
  |   | 2. Test out your thinking about   causes of team challenges using the model diagram. | Yes |   | 2. Test out your thinking about causes of   team challenges using the model diagram. | Yes |   | 2. Test out your thinking about   causes of team challenges using the model diagram. |   |   |   |  
  |   | 3. Apply clinical expertise to   develop a question for team learning using simulation. | Yes |   | 3. Apply clinical expertise to develop a   question for team learning using simulation. | Yes |   | 3. Apply clinical expertise to   develop a question for team learning using simulation. |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |  
  | 7 | 1. Describe the base case of no new decisions in your team. (change from “no changes” to “no new decisions”) | NO | 7 | 1. Describe the base case of no changes   in your team. | Yes | 7 | 1. Describe the base case of no   changes in your team. |   | Chanhe "No changes" to   "No new decisions" |   |  
  |   | 2. Test out your thinking about   what is likely to cause oscillation in team trends. | Yes |   | 2. Test out your thinking about what is   likely to cause oscillation in team treands. | Yes |   | 2. Test out your thinking about   what is likely to cause oscillation in team treands. |   |   |   |  
  |   | 3. Apply systems thinking to   develop a hypothesis about your team's clinical priority. | Yes |   | 3. Apply systems thinking to develop a   hypothesis about your team's clinical priority. | Yes |   | 3. Apply systems thinking to   develop a hypothesis about your team's clinical priority. |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |  
  | 8 | 1. Describe the systems story   your team believes will cause the outcomes you expect to observe in your   experiment. | Yes | 8 | 1. Describe the systems story your team   believes will cause the outcomes you expect to observe in your experiment. | Yes | 8 | 1. Describe the systems story   your team believes will cause the outcomes you expect to observe in your   experiment. |   |   |   |  
  |   | 2. Test your dynamic hypothesis   about your team's clinical priority. | Yes |   | 2. Test your dynamic hypothesis about   your team's clinical priority. | Yes |   | 2. Test your dynamic hypothesis   about your team's clinical priority. |   |   |   |  
  |   | 3. Apply systems thinking to   describe your team's findings, insights, and conclusions from your   experiment. | Yes |   | 3. Apply systems thinking to describe   your team's findings, insights, and conclusions from your experiment. | Yes |   | 3. Apply systems thinking to   describe your team's findings, insights, and conclusions from your   experiment. |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |  
  | 9 | 1. Describe the systems story   your team believes will cause the outcomes you expect to observe in your   experiment. | Yes | 9 | 1. Describe the systems story your team   believes will cause the outcomes you expect to observe in your experiment. | Yes | 9 | 1. Describe the systems story   your team believes will cause the outcomes you expect to observe in your   experiment. |   |   |   |  
  |   | 2. Test your dynamic hypothesis   about your team's clinical priority | Yes |   | 2. Test your dynamic hypothesis about   your team's clinical priority | Yes |   | 2. Test your dynamic hypothesis   about your team's clinical priority |   | period missing |   |  
  |   | 3. Apply systems thinking to   describe your team's findings, insights and conclusions from your experiment. (typo   in the word and) | No |   | 3. Apply systems thinking to describe   your team's findings, insights ad conclusions from your experiment. | Yes |   | 3. Apply systems thinking to   describe your team's findings, insights ad conclusions from your experiment. |   | and |   |  
  |   |   |   |   |   |   |   |   |   |   |   |  
  | 10 | 1. Describe the decisions you   experimented with and how they are intertwined with other decisions and   clinic outcomes. | Yes | 10 | 1. Describe the decisions you   experimented with and how they are intertwined with other decisions and   clinic outcomes. | Yes | 10 | 1. Describe the decisions you   experimented with and how they are intertwined with other decisions and   clinic outcomes. |   |   |   |  
  |   | 2. Test your understanding of   the system story by describing what is happening when the model produces a   runaway increase or decrease in some output. | Yes |   | 2. Test your understanding of the system   story by describing what is happening when the model produces a runaway   increase or decrease in some ouput. | Yes |   | 2. Test your understanding of   the system story by describing what is happening when the model produces a   runaway increase or decrease in some ouput. |   |   |   |  
  |   | 3. Apply your thinking to   anticipate the long-term trend in your clinic's EBP reach under two different   decision scenarios. | Yes |   | 3. Apply your thinking to anticipate the   long-term trend in your clinic's EBP reach under two different decision   scenarios. | Yes |   | 3. Apply your thinking to   anticipate the long-term trend in your clinic's EBP reach under two different   decision scenarios. |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |  
  | 11 | 1. Describe what your team has   prioritized as decisions to implement in your clinic. | Yes | 11 | 1. Describe what your team has   prioritized as decisions to implement in your clinic. | Yes | 11 | 1. Describe what your team has   prioritized as decisions to implement in your clinic. |   |   |   |  
  |   | 2. Test your team's plan against   your individual and shared team vision. (removed extra   comma) | Yes |   | 2. Test your team's plan against your   individual and shared, team vision. | Yes |   | 2. Test your team's plan against   your individual and shared, team vision. |   | remove extra comma after word   "shared" |   |  
  |   | 3. Apply your team's plan in   clinical decisions. | Yes |   | 3. Apply your team's plan in clinical   decisions. | Yes |   | 3. Apply your team's plan in   clinical decisions. |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |  
  | 12 | 1. Describe what your team has   learned and prioritized throughout the MTL 12 session program. | Yes | 12 | 1. Describe what your team has learned   and prioritized throughout the MTL 12 session program. | Yes | 12 | 1. Describe what your team has   learned and prioritized throughout the MTL 12 session program. |   |   |   |  
  |   | 2. Test how your team's plan   aligns with your team's shared vision. | Yes |   | 2. Test how your team's plan aligns with   your team's shared vision. | Yes |   | 2. Test how your team's plan   aligns with your team's shared vision. |   |   |   |  
  |   | 3. Apply decisions that your   team has prioritized to implement in the clinic. | Yes |   | 3. Apply decisions that your team has   prioritized to implement in the clinic. | Yes |   | 3. Apply decisions that your   team has prioritized to implement in the clinic. |   |   |   |  
  |   |   |   |   |   |   |   |   |   |   |   |

**Comment by staceypark** [comment]
@ritahitching have word document ready to send to Elizabeth and confirm with Stacey then generate a pull request for the changes. End of day 1/23.

**Comment by ritahitching** [comment]
@staceypark  
I created a new branch for the edits to the Learning Objectives and made a pull request/ The email for Elizabeth is ready for review. thanks
