### ISSUE TITLE
GitHub Wiki FAQ

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#829]
**1. Add description:** 
@staceypark will draft GitHub Wiki FAQ quesitons into this issue for asynchronous review by team

<< Paste screenshots here>>
 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by staceypark** [comment]
Categories:
1) Data UI
2) Sim UI
- Where can I find the Vensim Models?
- How do I get a tutorial of the Sim UI?
3) Demo
- How can I sign up for a quick demo of the sim UI?
4) Facilitation
- Where can I find the Learner SEE guides?
- Where can I find the Facilitator SAY guides?

5) Research
- Where can I find the research grants supporting this project?
- Where can I find

**Comment by lzim** [comment]
@staceypark 

These are nice first steps, but I think they focus a bit too much on the public audiences and not enough on the types of question that a learner will have when actively participating in _Modeling to Learn_

Can you work to build the FAQs of a typical clinician in the field going through _MTL_?
Does that make sense?

**Comment by staceypark** [comment]
merging with #747 which we already had open for this issue. 
comments have been moved there.
