### ISSUE TITLE
Stockton Pre 2018.08.14

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#83]
Please review the Stockton pre email and provide feedback before Monday 8/13:

https://github.com/lzim/teampsd/tree/master/mtl_facilitate_workgroup/pre_post_emails/stockton

**Comment by dlounsbu** [comment]
I am not sure where the pre-email text can be found. I click the link, but that does not pull it up. Files are blank or not readable ... at least via my phone.

**Comment by lzim** [comment]
You bring up a good point @dlounsbu 

@staceypark can these be uploaded as .Rmd or .html so we can review online without a download?
