### ISSUE TITLE
Qualitative Workgroup - Fidelity Rating Groups

### ISSUE THREAD

**Issue by jessfroe** [lzim/teampsd#831]
Hi qual workgroup, 
I'm creating a issue thread for us to track the key decisions made on Tuesday, as well as continue to think through next steps for the fidelity coding. 

**Fidelity Rating Pairs**
- Swap and Andrea
- Kathryn and Jessilyn 

**Next steps discussed:** 
- Pairs will touch base to schedule a meeting together
- Both pairs will discuss coding as a group at an upcoming qual meeting 

Please add on to this thread with thoughts, ideas, or anything I missed.

**Comment by jessfroe** [comment]
Also - was Andrea never added to our team_psd repository @lzim ? I don't see her on our list of potential assignees.

**Comment by lzim** [comment]
> Also - was Andrea never added to our team_psd repository @lzim ? I don't see her on our list of potential assignees.

@jessfroe and @staceypark 

It looks like she hasn’t been added. Would one of you help her get her free account set up and give me her username? I will add her.

**Comment by staceypark** [comment]
Closing this issue as I believe everyone has finished their fidelity coding
