### ISSUE TITLE
August Task: Training Video SOP

### ISSUE THREAD

**Issue by saveth** [lzim/teampsd#833]
**1. Add description:** 
Based on the meeting,  https://meet.lucidmeetings.com/lucid/meeting/236602, we need to develop an SOP that would enable team members to identify resources and simply storage and time for training.

Comments from meeting:
1. We need a central library with all training resources and videos.

2. We will also need an indicator of the video resource nested within the folder/document itself. This could be via a link, or putting a copy of the resource in that folder. - Savet will think this through further and present ideas to HQ.

<< Paste screenshots here>>
 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by anthonycpichardo** [comment]
@staceypark Were these recordings done prior to Savet leaving?

**Comment by staceypark** [comment]
@anthonycpichardo the recordings weren't ever done. this is an SOP we need to develop.

**Comment by staceypark** [comment]
@lzim @anthonycpichardo @lijenn 
I feel like we developed different recording processes via the TeamPSD 2.0 process for user feedback as well as Zoom meeting recordings for quant videos all on YT. I think this can be closed.
