### ISSUE TITLE
Green Pre 2018.08.15

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#84]
Please review the Green pre email and provide feedback before Monday 8/13:

https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/pre_post_emails/green/green_pre_2018.08.15.docx

**Comment by branscombj** [comment]
Looks good. Same question about possible typos.

**Comment by staceypark** [comment]
@lzim @dlounsbu @branscombj @dlkibbe @TomRust 

In HTML form:

https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/pre_post_emails/green/green_pre_2018.08.15_v2.html
