### ISSUE TITLE
wk4 - Setup team_tracker in GitHub private repository

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#841]
**1. Add description:** 
1. Setup resource cards for each session (mirroring the ones from the MTL Facilitate training mtl.how/team_tracker) with links to both MTL Blue & MTL Red resources
2. Setup team specific cards in the tracker with session fidelity details

<< Paste screenshots here>>
 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by jessfroe** [comment]
@staceypark 
Just wanted to check in about content for the private repo team_tracker - I am populating this tracker with the same information from the other team_tracker? 
I'll be working on this today and tomorrow.

**Comment by staceypark** [comment]
@jessfroe Actually let's hold off onto this we have the MTL Blue & MTL Red finalized on mtl.how

**Comment by jessfroe** [comment]
@staceypark any update about the private repo?

**Comment by staceypark** [comment]
@lijenn please add an estimate

**Comment by lijenn** [comment]
@staceypark Hi Stacey, I'm not too sure of what the task is so I am unable to estimate this. 

More specifically:
- what is the private GH repo?
- resource cards?
- session fidelity details?

Also note the team_tracker short link does not seem to be working.

**Comment by staceypark** [comment]
@lzim 
@lijenn and I want to make sure the right checklists are being populated for the team tracker.

We seem to have several going on though:
- there's pre/post checklists and partner/build/apply checklists here: https://github.com/lzim/teampsd/tree/master/mtl_facilitate_workgroup/checklists
- we also have the say checklists here: https://github.com/lzim/teampsd/tree/master/mtl_facilitate_workgroup/facilitator_say
- the checklists populated in the team cards here don't exactly seem to match either of those:
https://github.com/lzim/teampsd/issues/582
- I believe you're working on updating the facilitator fidelity items related to #1074 and the *MTL* fidelity manual as well.

**Comment by lzim** [comment]
Thanks for waking through these today @staceypark and @lijenn 

Note: The pre/post checklists are separate from the ones that reflect coverage of SAY guide material. And, we will still want to prompt them with pre/post checklists, but we should assess whether or how there may be any platform changes that should be updated in these lists. 

I will look through the team2 and team4 lists as compared to the ones in the facilitator_say folder and update you. Thanks!

**Comment by staceypark** [comment]
@lzim can you take a look at the above when you get a chance so @lijenn and I can populate the tracker.

**Comment by lzim** [comment]
@lijenn @staceypark 

Jenn & I discussed this, this morning at Workgroup Leads. The checklists used for Team 2 & Team 4 are correct for the early sessions. We want to populate these starting only with session 1 tram meetings likely to take place mid-to-late January.

Question for @lijenn & @anthonycpichardo Has this function been covered in the CRM MVP flow map (cross-ref #1329 & #1585)? The facilitators would rather not use GitHub for this if they could do all team management in the single 365D platform.

**Comment by anthonycpichardo** [comment]
It has not, we will add it to the list--it is documented on the user stories MVP though. 

I would consider this likely to be outside the scope of the initial email flow MVP for Wednesday

**Comment by lijenn** [comment]
costing as we're working on CRM #1684
