### ISSUE TITLE
PCT Pre 2018.08.15

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#85]
Please review the PCT pre email and provide feedback before Monday 8/13:

https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/pre_post_emails/pct/pct_pre_2018.08.15.docx

**Comment by branscombj** [comment]
Yep!

**Comment by dlkibbe** [comment]
The comments made on the first draft for the team email apply to these as well. Take or leave as you see fit. Thanks @staceypark

**Comment by staceypark** [comment]
@lzim @dlkibbe @branscombj @dlounsbu @TomRust 

In HTML format here: 
https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/pre_post_emails/pct/pct_pre_2018.08.15_v8.html

@dlounsbu Brought up an excellent point!  We want to be posting reproducible code on GitHub, which is a great reminder to myself and everyone else, that we do **not** want to use formats that require downloading i.e. Word.  I will be using RMD in the future for full rendering of images and formatting, which html currently does not do.
