### ISSUE TITLE
Updates to MTL Team website

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#853]
**Updates to MTL Team Website:** 
Hi James,
Best wishes for 2020.
I need a couple of updates to the MTL website in the Team section.  Namely:

1. Adding a headshot for **Jennifer Li** - who will be joining us shortly as a HQ team members and should be in the **Facilitator** section of the map. Her photo is located here: https://github.com/lzim/teampsd/blob/master/resources/headshots/li_headshot.jpg

2. Changes to **John Klocek** in the map to say **VA - Office of Mental Health and Suicide Prevention, Waco, TX** - to match the other QIICS on the team.  
Thanks!
Rita

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by jamesmrollins** [comment]
Done!

**Comment by staceypark** [comment]
@ritahitching please check mtl.how/team and close this issue if your request has been met

**Comment by ritahitching** [comment]
@jamesmrollins @staceypark 
Thanks James. 
I just looked over the map and see that you updated John Klocek's description to say **"Office of Mental Health and Suicide Prevention, Waco, TX"** but is missing the **"VA"** portion from my original request **" VA - Office of Mental Health and Suicide Prevention, Waco, TX"**. 
Will you please add the word **"VA"** and we can then close this issue? thanks!

**Comment by ritahitching** [comment]
> @jamesmrollins @staceypark
@jamesmrollins 
Good morning, I'm checking in to ask if you were able to update the mtl.how/team map for John Klocek?

> Thanks James.
> I just looked over the map and see that you updated John Klocek's description to say **"Office of Mental Health and Suicide Prevention, Waco, TX"** but is missing the **"VA"** portion from my original request **" VA - Office of Mental Health and Suicide Prevention, Waco, TX"**.
> Will you please add the word **"VA"** and we can then close this issue? thanks!

**Comment by jamesmrollins** [comment]
@ritahitching this is complete.  I also updated Mr. Pichardo's headshot.

**Comment by lzim** [comment]
@ritahitching 

Will you please upload Ash's photo to GitHub so that James can add to the mtl.how/team website?

Thanks!

FYI: @jamesmrollins

**Comment by ritahitching** [comment]
@jamesmrollins @staceypark @lzim 
Hi James, Good morning. Will you please update mtl.how/team with details of our latest team member:

1. **Ash Nazarizadeh SQL Programmer Data Analyst** You can find his headshot (pending pull request approval from Stacey) at **https://github.com/lzim/teampsd/tree/master/resources/headshots**.
2. Ash's information on the mtl.how/team map should match everyone's at HQ.
**Ash Nazarizadeh VA - Office of Mental Health and Suicide Prevention Menlo Park, CA**
3. I uploaded Ash's **bio** to the forio/epicenter platform.

thanks! Rita
