### ISSUE TITLE
GitHub - mtl.how homepage visuals

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#858]
**1. Add description:** 
Suggestions for possible visual simplifications to the (new) mtl.how landing page. 

<< Paste screenshots here>>
 ![image](https://user-images.githubusercontent.com/29778290/71840202-ce1f4f80-308a-11ea-8add-918ba1218461.png)

**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by branscombj** [comment]
I mocked this up in a pull request at mtl.how (branch red_readme)

![image](https://user-images.githubusercontent.com/29778290/71921801-8dd9d300-3157-11ea-8d08-cd2bd4ad0b12.png)

**Comment by branscombj** [comment]
This links to #830

**Comment by lzim** [comment]
@branscombj 

I implemented what we discussed during the meeting today.
Please take a look at https://mtl.how/ https://mtl.how/blue https://mtl.how/red and let me know how they look .

Thanks!

FYI: @staceypark @ritahitching @lijenn @dlkibbe

**Comment by branscombj** [comment]
> I implemented what we discussed during the meeting today.
> Please take a look at https://mtl.how/ https://mtl.how/blue https://mtl.how/red and let me know how they look .
 
> FYI: @staceypark @ritahitching @lijenn @dlkibbe

Looks great! I removed a few words from the top line of text in the Red readme so it matches the Blue one.
