### ISSUE TITLE
Suggested Changes to Short-term and Long-term Hours Variables in AGG

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#86]
@lzim @dlkibbe @branscombj @holbrooa @staceypark @TomRust 

In the current Sim/UI, "Long-term Hours Worked" and "Short-term Hours Worked" are mapped to "Effect of Fatigue on Actual Hours Available" and "Effect of Fatigue on Appointment Completion Rate" respectively. The "i" information associated with these variables explain the short-term and long-term effect that working overtime has on staff productivity and burn-out.  Therefore, we recommend to the team that the labels change as is shown below. Please note that the sensitivity sliders' descriptions will be changed from "Effect of . . . " to "Sensitivity of . . . " 

![image](https://user-images.githubusercontent.com/30132017/44050242-43213e20-9eeb-11e8-9006-5f0c779835c5.png)

We will begin working AGG development soon - need your comments or suggestions soon?
Thanks,
James

**Comment by jamesmrollins** [comment]
@lzim @dlkibbe @branscombj @holbrooa @staceypark @TomRust
Hey Everybody!  Any comments on this thread?

**Comment by TomRust** [comment]
you just snuck this issue right under everyone's radar, James!  :)

It seems like we already have "effect" in the next variable in the loop for each case, but I really like clarifying that it's "overtime."

How about we just call them "Short-term Overtime" and "Long-term Overtime"? 

They could be either in units of "hrs" or a % of the official hours.  Whatever is clearer to the user.  Example: if the team works 10 hrs / wk in CC, and then started working 15 hrs / wk for a few weeks, then the "Short-term Overtime" would climb to ~5 hrs (indicating that over the past few weeks they have worked ~5 hours over their official hours in CC), or 50% (indicating that they have been recently working 50% more than their official hours in CC).  I can build it either way.

--TOM

**Comment by dlkibbe** [comment]
@jamesmrollins @TomRust - I think this is a good change, my only question is what is the definition of short- vs. long-term if asked?

**Comment by jamesmrollins** [comment]
@dlkibbe 
Well!  I'm glad you asked :-)

If the user clicks the "i" icon (not shown in the diagram above, but in the future version), they would get the following definitions respectively:

Long Term Hours - Persistently working long workweeks relative to normal eventually increases provider quit rate, and thus reduces actual team hours available. It is constrained from going above 1 (as lower than official work hours do not create new staff or attract other staff to work on this team).

Short Term Hours - Long workweeks relative to normal team hours reduce employee productivity. Restricted from going below 1, as lower than official work hours do not influence providers or patients to come more regularly to their appointments.

**Comment by TomRust** [comment]
D'oh! I just double checked, and the short term hours are the average hours worked over the last *3* weeks.

**Comment by jamesmrollins** [comment]
@TomRust @branscombj @dlkibbe @lzim @staceypark @holbrooa 
Hey Everyone!
Good Morning.  Please take a look at this issue and weigh in.  Even if you agree, it would be good if you concurred with Tom and I.  If you disagree, please indicate so and also offer another course.  Once I have my answer, then I can get AGG and CC standardization finished. I forgot to note above that the issue also affects CC and will affect MM as well.

Thanks!
James

**Comment by dlkibbe** [comment]
@jamesmrollins @TomRust 
First, I think it would be really helpful for the clinicians if the specific hours were in the "i" definitions, i.e. Short-term hours are the average hours over the past 3 weeks, and Long-term hours are the average hours over the past year.
Second, a question (my ignorance is showing), would the "effect" sliders still have ranges from 0 to 2 or would the range on the "effect" sliders be different? If it's the same range, I would think it's OK.

**Comment by jamesmrollins** [comment]
@dlkibbe 
Hi Debbie,
Yes, we will provide specific definitions for Short Term Overtime and Long Term Overtime.  

The "Effect" sliders are labels on the Sim/UI main diagram. The are not directly adjustable. They show as slider icons, because they are adjustable as "Sensitivities."  Therefore, the 0 to 2 scale only applies to the "Sensitivity" slider. 
Thank you,
James

**Comment by staceypark** [comment]
@jamesmrollins @TomRust 

Looking at the two "Effect" sliders in the diagram I see that - 
"Effect of Work Pressure on Overtime" maps directly onto "Sensitivity of Overtime to Work Pressure", but I'm not sure what "Effect of Burnout on Actual Hours Available" would map onto in the sensitivity experiment sliders?  

Wouldn't the language for the "effect" sliders and "sensitivities" be the same? Perhaps I'm missing something here.

**Comment by lzim** [comment]
@TomRust @jamesmrollins @dlkibbe @staceypark @branscombj 

I apologize for the delay on my response. James talked with me about this on Friday. 

In addition, to making the changes to the "short-term overtime" and "long-term overtime" variables in the second image - and separate from the edited, "i" information.

I find the difference in language between the experiment sliders and the main diagram hard to track, I think because the construction of each table reverses the order of the relationship.

For example, in the second example James posted on Friday - the main diagram says, "Effect of Work Pressure on Overtime." So, then do I adjust that with "Sensitivity of Overtime to Work Pressure?" This one isn't too bad, even though the order reads work press are 

Even more confusing is this: "Effect of Burnout on Actual Hours Available" (main sim UI diagram/tile), then, a slider in the experiment tile, "Sensitivity of Burnout to Long-term Hours Worked." Is Burnout effecting the hours available, or is hours worked effecting burnout?

I could be fine going with either "effect" or "sensitivity" but we should work to make them parallel so folks can easily track the direction of the sensitivity effect. Right?

Lindsey

**Comment by jamesmrollins** [comment]
@lzim @dlkibbe @TomRust @holbrooa @branscombj 
Team,
I apologize for the sketchy explanation of the issue.  I have prepared a table below, which I hope does a better job of explaining what we are trying to accomplish.  I hope it clarifies some of the wording issues that Lindsey and Debbie have brought up.  


Vensim | SIM/UI Main Icon | Exp Tile Slider | "Effect of" "i" information | "Sensitivity to"  "i"information | Notes
-- | -- | -- | -- | -- | --
Effect of Long-Term Hours Worked on Burnout | Effect of Long-Term Hours Worked on Burnout | Sensitivity of Burnout to Long-Term Hours Worked | Persistently working long workweeks relative to normal eventually increases provider quit rate, and thus reduces actual team hours available. It is constrained from going above 1 (as lower than official work hours do not create new staff or attract other staff to work on this team). | Exponent controlling the effect of long-term use of overtime on burnout, where an increase in long-term overtime causes an increase in the staff quit rate and thus the hours available declines. A value of "1" implies the assumption that doubling the hours worked over the official hours will eventually cause enough quits to cut the official hours offered in half.  For the same situation, a value of "0.5" would eventually reduce the official team hours to 71% of its original value, and a value of 1.5 would reduce the official hours to 35% of the original. | Currently Worded in SIm/UI Diagram as: Effect of Burnout on Actual Hours Available
Effect of Short-Term Hours Worked on Cancellations | Effect of Short-Term Hours Worked on Cancellations | Sensitivity of Cancellations to Short-term Hours Worked | Long workweeks relative to normal team hours reduce employee productivity. Restricted from going below 1, as lower than official work hours do not influence providers or patients to come more regularly to their appointments. | The effect size of overtime work hours on missed appointments, where extended workweeks lead to reduced productivity via increased missed appointments by clinicians and patients (as clinicians have less time to devote to non-patient facing tasks -- like appointment reminder calls).  A value of "1" implies the assumption that there is a direct relationship between relative increases in work hours and the percent of appointments missed (e.g., doubling the work hours will also double the % of appointments missed).  For the same situation, a value of "0.5" would only increase the number missed appointments to 41% over the original value, and a value of 1.5 would increase the missed appointments by 182%. |  
Effect of Wait Times on Intake Evaluation Rate | Effect of Wait Times on Intake Evaluation Rate | Sensitivity of New Patient Starts to New Patient Delays | Other clinicians' perception of care delays for starting patients in this team reduces their new patient referrals.  This effects is controlled by an exponent that reflects how sensitive providers' referral decisions are to these care delays for new patients.  It is constrained from going above 1 (as lower than clinically new patient wait times do not make a team more attractive). | The effect size of new patient wait times on team attractiveness and referrals, where the referrals for intake drop as new patient wait times increase (relative to the team's new patient wait time goal).  A value of "1" implies the assumption that doubling the wait time will reduce the new patient referral rate by half.  For the same situation, a value of "0.5" would reduce the referral rate to 71% of the original rate, and a value of 1.5 would reduce the referral rate to only 35% of the original rate. | Currently Worded in SIm/UI Diagram as: Effect of Care Delays on Intake Evaluation Rate
Effect of Work Pressure on Overtime | Effect of Work Pressure on Overtime | Sensitivity of Overtime to Work Pressure | High schedule pressure leads to overtime; low pressure does not lead to a reduction in hours worked (i.e., the effect is restricted from going below 1). | The effect size of work pressure on overtime, where an increase in appointment backlog causes the team to work more "unofficial" hours . A value of "1" implies the assumption that there is a direct relationship between work pressure and the amount of overtime used (e.g., doubling the work pressure will also double the hours worked per week).  For the same situation, a value of "0.5" would only increase the hours worked to 41% over the original value, and a value of 1.5 would increase the hours worked to 182% over the original value. |  
Effect of Work Pressure on Scheduled Return Visit Interval | Effect of Work Pressure on Scheduled Return Visit Interval | Sensitivity of RVI to Work Pressure | High schedule pressure increases the time between appointments. Restricted from going below 1, as lower work pressure does not influence providers to bring in their patients more often than is clinically recommended. | The effect size of work pressure on delays in care, where an increase in appointment backlog causes the team to extend the scheduled Return Visit Interval for current patients. A value of "1" implies the assumption that there is a direct relationship between work pressure and RVI (e.g., doubling the work pressure will also double the RVI).  For the same situation, a value of "0.5" would only increase the RVI by 41% over its original value, and a value of 1.5 would increase the RVI by 182% over the original value. |  
Effect of Fatigue on Patient's Engagement Time | Effect of Fatigue on Patient's Engagement Time | Sensitivity of Service Duration to Provider Fatigue | Clinician fatigue reduces patient engagement, reducing the patients' percieved quality of care, and thus the average patient duration in a service.  It is constrained from going above 1 (as lower than official work hours do not increase a patient's time in a service). | The effect size of provider fatigue on patients' duration in a service, where the total time in a service drops as fatigue increases.  A value of "1" implies the assumption that doubling provider fatigue (e.g., short-term increases in work hours) will reduce the patients percieved quality of service, and thus their willingness to remain in that service by half.  For the same situation, a value of "0.5" would reduce the average duration in that service to 71% of the original time in service, and a value of 1.5 would reduce the duration to only 35% of the original duration. |  
Effect of RVI Delays on Treatment Decisions | Effect of RVI Delays on Treatment Decisions | Sensitivity of Within Team Referrals to Existing Patient Care Delays | Clinicians' perception of care delays for services reduces their new patient referrals to those services.  This effects is controlled by an exponent that reflects how sensitive providers' triage decisions are to these care delays for existing patients.  It is constrained from going above 1 (as lower than clinically necessary return visit intervals do not make a service more attractive). | The effect size of existing patient care delays on service attractiveness and referrals, where within-team referrals to a service drop as actual return visit interval increases (relative to desired RVI).  A value of "1" implies the assumption that doubling the time between appointments for existing patients (e.g., delaying their care) will reduce the new patient referral rate for that service by half.  For the same situation, a value of "0.5" would reduce the referral rate for that service, or its attractiveness, to 71% of the original rate, and a value of "1.5" would reduce the attractiveness to only 35% of the original rate. | Currently Worded in SIm/UI Diagram as: Effect of Care Delays on Within-Team Referrals
Effect of Start Delays on Treatment Decisions | Effect of Start Delays on Treatment Decisions | Sensitivity of Within Team Referrals to Existing Patient Care Delays | Clinicians' perception of care delays for services reduces their new patient referrals to those services.  This effects is controlled by an exponent that reflects how sensitive providers' triage decisions are to these care delays for existing patients.  It is constrained from going above 1 (as lower than clinically necessary return visit intervals do not make a service more attractive). | The effect size of existing patient care delays on service attractiveness and referrals, where within-team referrals to a service drop as actual return visit interval increases (relative to desired RVI).  A value of "1" implies the assumption that doubling the time between appointments for existing patients (e.g., delaying their care) will reduce the new patient referral rate for that service by half.  For the same situation, a value of "0.5" would reduce the referral rate for that service, or its attractiveness, to 71% of the original rate, and a value of "1.5" would reduce the attractiveness to only 35% of the original rate. | This is a new variable that is affected by the sensitivity setting and is not shown in the Sim?UI main diagram.
