### ISSUE TITLE
Schedule meetings for teamPSD

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#868]
**TeamPSD Meetings:** 

Schedule meetings for teamPSD

1.  4th Tuesday / 9 am all hands (HQ, Quant, QIICS, Co-Is - virtual) 9am Pacific to 10am Pacific
2. 4th Friday all HQ working afternoon 12pm - inventory/work updates for the following month - onsite 12:30pm Pacific to 4pm Pacific.

@staceypark would appreciate if you could review my first draft on these meetings - they are already in Lucidchart.

**Comment by staceypark** [comment]
We decided for the all hands meeting, all workgroups will come to this meeting to celebrate their success of milestone completions for the month.

Invite: HQ, Quant, Qual, Sim, Facilitate (only Jane, Debbie, David), VAPOR (Ren, DC, Erik, Leroy)
Do NOT invite: Co-I's (Kimerling, Rosen, SWS, Trafton, Wiechers, McGovern, Lindley), QIICs, EES, Rust

**Comment by ritahitching** [comment]
Email invitation sent.
