### ISSUE TITLE
Individual vs. Team World Management

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#87]

**Comment by staceypark** [comment]
Hi Team,

I spoke to James earlier on how the different changes we requested were implemented.  In regards to the individual vs. team world management, we will be managing it at the **Group** level now.  Meaning, each user will be added to two different groups.  One for their individual world and one for their team world.  We decided before that we wanted folks to be able to upload their pictures to the Sim UI, so it makes sense to stick to the convention of emails as username (login convention for team world previously), for the new single sign-on experience. 

Once folks login, they will see the choice to choose a world like below: 
![image](https://user-images.githubusercontent.com/31089501/44067676-83a185dc-9f2b-11e8-9a2e-cd7c3ac46765.png)

@jamesmrollins 
1) I was not able to change the "640a0_mpd-user-training-may-2018" group name to "640_team_world".  I used the "Edit" function and was given a message that changes were saved successfully, but when I refreshed, the changes were not made?
2) Can we change the pop up to say "Please select a **world**" instead of **team**? We've been facilitating clinicians with the language "world" and "team" has a different meaning to them.

The logic for mapping teams and individuals to their different worlds will still be the same as before (Interface > Dynamic Data > world-team-mapping.xlsx).

@dlkibbe @TomRust I've already done the mapping for Stockton tomorrow since we will be meeting with them.  During the meeting, we will need to introduce this single-sign on change to the team.

**Comment by jamesmrollins** [comment]
Hi All,
Regarding number 1 - I will report this to Forio.
Regarding number 2 - The correct term would actually be "Group" as the user is first selecting the group.  When they select the group, then they will land in whatever World they are assigned to.  

Regarding this statement below:
"We do not want to have one individual world group and one team world group for the entire country. This will create problems with the UI, like the world corruption issue we previously experienced. I've chosen to divide it by facility level at the moment i.e. 640_team_world and 640_individual_world. We can change that later if we decide otherwise."

May I recommend the following change:
Put teams that are geographically or functionally related under the same group.  For example, the 640a0_mpd code would be the group code, and wcc, blue or green would be the team.  So it would look like this:
Group               World     Team
640a0_mpd       001        Menlo Park, wcc
                          002        Menlo Park green
640a0_mpd_i     001        Individual 1
                          002        Individiual 2

Thanks,
James

**Comment by jamesmrollins** [comment]
@lzim @dlounsbu @branscombj @dlkibbe @TomRust @staceypark 

Hi All,
First off, I'm sorry Stacey.  I reread the thread this morning and realized that your explanation was clear enough.  For some reason I thought it unclear last night, and needed another explanation.  It didn't. My explanation simply repeated what you just said <<chagrin emoji>>. 

The image below is another recommended change.  Although by choosing a group, the user will automatically land in a world, it is probably better to refer to the list as groups, versus teams or worlds. It may be particularly helpful if someone, say a subject-matter-expert, needs to be in multiple groups across the enterprise.

![image](https://user-images.githubusercontent.com/30132017/44103057-0e4003e8-9fa0-11e8-9515-cbd48071c466.png)

Thank you,
James

**Comment by staceypark** [comment]
@jamesmrollins No worries!

@lzim @dlounsbu @branscombj @dlkibbe @TomRust 
It's true that "group" is technically the correct term.  Perhaps we should stick with that instead.  Either way, we need to decide on a naming convention and stick with it as we will be rapidly creating many groups soon.  (Also because if we were to move people around from one group to another to rename the group name, it would not carry their saved experiments with them for any play world experiments they may have run)

If folks were in multiple groups, they would be seeing:
"640_individual_world" or "640_individual_group"
"640_team_world" or ...
"480_individual_world" or ... 
"480_team_world" or ....

**Comment by staceypark** [comment]
@lzim @dlounsbu @branscombj @dlkibbe @TomRust @jamesmrollins 
James and I further discussed this morning and landed back on using the term "world" as that makes the most sense for the user.  
1. No user would ever be in more than one "world" inside an Epicenter "group".  
2. It makes sense to play in a "world" as opposed to a "group"
3. "Group" can become confusing with "team"
4. We've already facilitated using the term "world" so it makes sense to stick to that.

The distinction between "group" and "world" is something that only facilitators would need to understand.

If no one has any other objections, I would like to close this issue and move forward with getting all the teams uploaded through this new individual vs. team world management structure.

**Comment by dlkibbe** [comment]
Agreed @staceypark  - especially number 4.

**Comment by dlkibbe** [comment]
@jamesmrollins it might helpful to ensure the 640a0_mpd-user-training-may-2018 file or any file that is used for a team has the words "teamworld" in the name so that it is easy for the user to discern which world to choose. Just a thought but I don't know if it's possible.

**Comment by dlkibbe** [comment]
@jamesmrollins so will the place where you click on the drop down arrow also say "Please select a world"?

**Comment by jamesmrollins** [comment]
@dlkibbe 
Ah!  Good Catch.  
![image](https://user-images.githubusercontent.com/30132017/44282935-8687f180-a211-11e8-8db0-edab2952eb2a.png)
