### ISSUE TITLE
VAPOR videos in pre/post emails

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#870]
**VAPOR videos in pre/post emails**

@staceypark lets discuss the process for this task please.

1. View VAPOR videos 
2. Align pre and post emails
3. Generate table of discrepancies and update accordingly.

**Comment by ritahitching** [comment]
@lzim 
Please add me to the OSF project **vapor_videos_interviews**
thanks!

**Comment by ritahitching** [comment]
VAPOR Videos
VAPOR Clips & Emails
OSF -VAPOR videos
OSF  vapor_videos_interviews
VAPOR videos folder "CLIPS" already mapped to their session 
Total 12 sessions

**Task**
Separate into pre and post emails in mtl/faciliate workgroup 
html code link - in markdown code 
Videos currently on OSF - scope out with Lindsey's new location for videos (e.g. private video in our existing YouTube account).

[<img src = "Insert link to image here" height = "45" width = "75">](Insert link that you want to go to when you click on the image) 

https://github.com/lzim/teampsd/tree/master/mtl_facilitate_workgroup/pre_post_emails

**Comment by staceypark** [comment]
Cross-ref issue #315 where we have the diagram of how the interviews were coded and mapped.

**Comment by lijenn** [comment]
@lzim Any updates/progress with Erin on uploading the VAPOR videos from OSF onto YouTube?

**Comment by lzim** [comment]
All these videos are posted at https://mtl.how/videos

Thanks @erinash 🥇

**Comment by lzim** [comment]
@lijenn what's the difference between #870 and #987 are they duplicates?

I think so, so I'm closing this one.

**Comment by staceypark** [comment]
@lijenn I believe #987 is the document_card in the document tracker and #870 tracks a specific chunk to be done (specifically the VAPOR addition) for that right?

**Comment by lijenn** [comment]
From HQ Huddle 3/13:
Close this issue as VAPOR videos are already on Youtube. Make new issue card to reflect #987 needing a template.
