### ISSUE TITLE
Inventory of possible TeamPSD missing files

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#872]
**Audit Possible Missing teamPSD folders:** 

- Review missing/deleted teamPSD folder and reinstating by IT.
- Work with Steve Woodward for the inventory of possible missing folders.
- Discuss how best to complete this task - discuss with Stacey.
- Discussed at HQ meeting Feb 6 - pin placed.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [x]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_ estimate 3 hours - not sure need to discuss with Steve & HQ

**Edit the due date (if necessary)** May be moved to March 2020

**Comment by ritahitching** [comment]
@staceypark can we discuss before I reach out to Steve Woodward? thanks

**Comment by ritahitching** [comment]
@staceypark did you hear anything back from Steve on this issue? thanks Rita

**Comment by ritahitching** [comment]
@lijenn just FYI main contact is Steve Woodward - details will be on relationship list.

**Comment by lzim** [comment]
I think we can close this issue.
