### ISSUE TITLE
TAS 2018.08.18

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#88]
TAS Week 1 Email for MTL Facilitate Prep:
https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/pre_post_emails/tas/tas_2018.08.13.html

I added a "tas" subfolder under the pre_post_emails" folder for the emails we will be sending leading up to the September Chicago training.

@dlkibbe The first one you drafted for us has been uploaded at the link as an html.  Thanks!!

**Comment by lzim** [comment]
@staceypark 

Are you able to upload .Rmd files for these emails?  It would be great to be able to edit and comment on them directly on GitHub.

Note: These emails should use the de-idenfified team names!

Lindsey

**Comment by staceypark** [comment]
@lzim 
https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/pre_post_emails/email_template.rmd

Here's my best working copy of the rmd version so far.  There's still a lot of missing parts though, including:
1. Changing text color
2. Hyperlinking images (Haven't found a solution that let's me both resize and hyperlink images. Surely, this doesn't need to be a tradeoff...)
3. Hyperlinking emails
4. Center aligning some text and images 

I will keep working on this, but I think we should send out this week's emails as this won't be resolved today.

**Comment by staceypark** [comment]
https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/pre_post_emails/tas/tas_2018.08.17.rmd

**Comment by lzim** [comment]
@staceypark following up on our work yesterday:

Let’s close this issue. We won’t have TAS emails or R21 Pilot team emails here. Instead, we’ll use this space to draft out the templates in .Rmd for pre/post emails for the 12-session plan according to the fidelity checklist.

Thanks!

Lindsey
