### ISSUE TITLE
PLDR Screen Capture - Need More Information

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#883]
here is my screenshot<br></br></br></br></br></br>![image](https://s3.amazonaws.com/epicenter-asset/production/va/va-psd-test/1578682649927549220_img0.jpeg) <br/>

**Comment by jamesmrollins** [comment]
@lzim   Need a problem statement please.

**Comment by lzim** [comment]
@jamesmrollins 

This was simply an attempt to upload an image from within the VA domain.
