### ISSUE TITLE
Due Date 2/21 Pavir - Create list /calendar dates of manual requisitions for subscriptions

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#885]
**PAVIR  manual requisitions:** 

Create an internal TeamPSD schedule for each vendor that will need manual requisition submissions each year and with due dates for the subscriptions. Perhaps we could create a yearly Outlook reminder that will ping us a few weeks before the deadline as well.

@Stacey will generate draft and review with you.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [x]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_  less than 1 hour

**Edit the due date (if necessary)**

**Comment by ritahitching** [comment]
@staceypark 

Lindsey asked me to put together a list of vendors that TeamPSD uses that require a manual requisition, so that we can set up a calendar reminders a week prior to subscriptions needing to be renewed. I found the following on our shared drive.  Can we please discuss where I can find the remaining information and if some are already on ReqLogic?

  | Purpose | Last Purchased
-- | -- | --
Adobe Connect | Project Management |  
BaseCamp | Project Management |  
Forio | Website & Facilitation|  
GotoMeetings | Project Management |  
LucidMeetings | Project Management |  
MS Dynamics CRM | Project Management |  
Rebrandly | Shortlinks for TeamPSD |  
TeamPSD Website | Project & Facilitation |  
Vensim | Project & Facilitation |  
Abode Creative Cloud | Documents & Graphics | 12/25/2019
Zotero | Reference Management | 7/29/2018
Apple Scribe | Transcription Service |  
GitHub Private | Project management |  
Shiny | Manuscripts & Data Analysis |

**Comment by staceypark** [comment]
@ritahitching update column to reflect 

**vendor / purpose / cost  - break down by month and year / last purchase date**

**Comment by staceypark** [comment]
@ritahitching I think there was a misunderstanding here - it would be helpful to note which ones we are paying for annually and which monthly so that we know how to setup our system for updating them.
For example, Zotero is a yearly subscription while Rebrandly is a monthly one.

**Comment by ritahitching** [comment]
@staceypark @lijenn 
Please confirm that I can close this issue, pending a costing update on the Vensim.
I  created calendar reminders for all the vendors above on the outlook calendar and invited you both.
thanks!
Rita

**Comment by ritahitching** [comment]
@lzim 

Will you please clarify how the **purchase** of the **Vensim** is made? 
There are no details on ReqLogic or on our shared drive. 
I was able to find details for the purchase of the Vensim in 2016 for $175 using the login in details for the Vensim in the shared drive . 
thanks,
Rita

**Comment by staceypark** [comment]
@ritahitching thanks for creating the outlook reminders. you can close this issue once the Vensim piece is resolved

**Comment by ritahitching** [comment]
> **urchase** of the **Vensim** is made?

@lzim will you please
