### ISSUE TITLE
PLDR Screenshot Capture for Issue or Idea Button

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#887]
When I try to drag a screenshot into the screenshot dialogue it takes up the whole screen and I can't get around it or see what to do next. I only no how to escape.<br><br>That does not happen when I use the file upload option. It only happens when I try to drag my image file over.<br><br>Thanks!<br><br>Lindsey</br></br></br></br></br>

**Comment by jamesmrollins** [comment]
@lzim I may need to witness this as I am not able to reproduce.
