### ISSUE TITLE
1/29 : Devise and produce MTL and Epicenter Training

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#888]
**1. Add description:** 
Produce training documentation and tracking system to develop Epicenter and MTL administration competencies.  Documentation will use markdown formats and wireframes available in Github.

**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_ ~ 20 hrs.

**Edit the due date (if necessary)**

**Comment by jamesmrollins** [comment]
Hi @staceypark and @ritahitching !  Please take a look below and comment.  This is the outline of training directions I hope to develop between now and next week so we can train up some more admins such as @lrollins33 and all of your new hires...Pending any feedback from you, I plan to get started developing these right away.  Thanks, James

**Training Outline for Epicenter Admin User** 
1. Introduction to Epicenter
- How to register an End User
- Overview of VA Epicenter Projects and rules for use
2. Group Setup, Facilitator Role Assignment, and Impersonate User Function.
- Group naming convention
- How to manage End Users
- How to manage Team Data files
3. Dynamic Data "i" Information Maintenance Procedure
- How to update "i" information in Epicenter
- When and how to update "i" information in OSF
4. How to update and test Vensim models in the Epicenter
- How models are named, version controlled and stored in the GitHub repository
- How to test and release a model
- How to upload team data into epicenter.
 
**Training Outline for TEAM PSD and MTL Demo Admin User**

1. Team PSD - Dynamic Data and Administration Folder Updates
- Administration Page Overview
- How to update a team member record
- How to add a team member bio and photograph
- How to update a slider 
- How to update web page resources
2. MTL Demo - Dynamic Data and Administration Folder Updates
- Administration Page Overview
- How to update the Demo team data file.
- How to add a course code
- How to add/update/export the demo user list
- How to update or add MTL Demo web page resources
- How to create/update and sequence MTL sliders

**Comment by staceypark** [comment]
@jamesmrollins 
1. I moved the issue to the feature tracker, since this is really a feature.
2. Let me know if you have any major edits to the template I drafted since I'm also working on training docs.
3. Lindsey gave us the greenlight on doing a training_tracker - Could you start one based on the ideas you had from our last chat?
4. Comments on your list above
 - Add overview of facilitate dashboard and how it works (what data you can see, what the percentages mean, etc.)
- Add section on the Sim itself about the mtl.how/sim not the Epicenter (i.e. export runs, chat, upload data, etc).
- Not sure what "how to test and release a model" means. Do you mean in the general sense of all the things to click through/run when new model updates come through? What do you mean by release?

**Comment by jamesmrollins** [comment]
Hi @staceypark ,

Below is a training outline that I recommend we use for our standard markdown.  The sentences in parenthesis are explanations, and not included with the template.

TRAINING OUTLINE
1. Title: (should be structured to contain first element as target area of software. Such as TEAM PSD WEBSITE: How to update a biography)
2. External links needed: (self-explanatory)
3. Training Objectives: (what are we accomplishing with this training?)
4. Full Instructions: (Procedural steps with pictures)
5. Exercise: (The trainee would use this to do their practice runs.  Perhaps divide into beginning, intermediate and hard, depending on the complexity of the task)
6. Knowledge Check:  (A checklist form of the steps)

Note: Since the training record is going to be included in the Project Kanban, then we don’t need it in the docs.

TRAINING RECORD KEEPING

ISSUE Cards
An individual who is going to train, will create a new issue and indicate the title of the training module they intend to complete. They will assign the issue to the “train” silo of the “training_tracker” Kanban. This issue card will contain the person's handle (example, @jamesmrollins ) and the training module title (example, TEAM PSD WEBSITE: Administration Page Overview).

TRAINING_TRACKER
Users will track completion of their training modules by progressing their issue cards from “train” to exercise_2.  Only trainers can progress the cards through “supervised_1” to “complete” indicating the training was evaluated and the skills are performed to standard. If a trainee, in the opinion of the trainer is competent in a given skill, they may skip a supervised evaluation step and go directly to “complete.”  

Recommend the following silos. :

train 	exercise_1	exercise_2	supervised_1	supervised_2	complete 

I recommend we use a “training complete” flag when the person lands in the “complete” silo.

**Comment by staceypark** [comment]
@jamesmrollins I updated the training guide template a bit here based on your feedback above: https://github.com/lzim/teampsd/blob/master/resources/training_guides/training_guide_template.md

And started the training tracker here (the "complete" column is automated so that when cards are closed in this tracker, they are automatically stuck in that column):
https://github.com/lzim/teampsd/projects/13

**Comment by staceypark** [comment]
@jamesmrollins team naming convention for Epicenter groups is broken down into 4 parts: 
1. 3 digit numeric health care system + 2 digit alphanumeric location (i.e. 640a0)
2. 3 digit alpha location code (i.e. mpd)
3. local team name (i.e. pct)
4. "team" for team world and "ind" for individual world

Put together, it looks like: 640a0_mpd_pct_team

**Comment by staceypark** [comment]
thanks @lrollins33 and @jamesmrollins for working on this!
I accepted the pull request updating the documents and will close this issue.
