### ISSUE TITLE
Discuss Due 2/28 Send cameras & monitors & hardcopy materials & swag to facilitators

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#890]
**Send below materials to facilitators** 
- Inventory of need for webcams & second monitors 

| QIIC | Webcam | Monitors * | Address Provided | 
|---|---|---|---|
| Claire | yes | 0 | yes |
| David | no  | 1 |yes |
| Debbie |travelling until 2/21 | travelling until 2/21 |
| Gayle | yes | 0 | yes | 
| Jane | no | 1 | yes | 
| Jay | no | 1 | yes| 
| John |yes | 0 | yes |
| Matt |no | 0 |  - | 
| Marcia | no | 0 |  - | 
| Theresa | yes | 0 | yes 

- MTL lanyards, magnets, and waterbottles
- MTL resources hardcopy 

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [x]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_ estimate 5 hours to place Reqlogic orders and arrange shipping to all Facilitators

**Edit the due date (if necessary)** Ideally end of Feb

**Comment by ritahitching** [comment]
@ritahitching contact QIICS confirming their needs for webcams & monitors


QIIC | Webcam (yes/no) | Monitor (0,1,2)
-- | -- | --
Theresa | 1 |  
Marcia |   |  
Gayle | 1 |  
John |   |  
Jay |   |  
Matt |   |  
David |   | confirm if 1 or 2 are needed
Jane |   |  
Debbie |   |

**Comment by ritahitching** [comment]
- **Done**
Email Claire, David, Gayle and Theresa asking for shipping address for their respective equipment needs.  
- **Do** 
Will email Debbie and Jay again, once they return from travel after 2/14 asking

**Comment by ritahitching** [comment]
Resend David an email asking for shipping address.

**Comment by ritahitching** [comment]
Emailed Debbie and Jay asking to confirm their equipment needs and shipping information.

**Comment by ritahitching** [comment]
Sent Debbie another email asking for confirmation of equipment needs and shipping address.
All other Facilitators have updated their equipment needs and shipping details.
Order to be placed as soon as Debbie responds if not sooner.

**Comment by ritahitching** [comment]
Ready to close this issue and move to # 1021
