### ISSUE TITLE
Add new team member to MTL.how/team

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#897]
## **Add Anthony Pichardo to mtl.how/team and changes to Kathryn and John** 

@jamesmrollins will you please make the following updates to the mtl.how/team website 

1. New team member **Anthony Pichardo:**

- Upload Anthony Pichardo's headshot and bio to the mtl.how/team.
He will be joining us shortly as a Data Analyst / Technical Writer and should appear next to Savet's bio.
- Anthony's headshot is at: 
https://github.com/lzim/teampsd/blob/master/resources/headshots/pichardo_headshot.jpg
-  I have added Anthony's details to forio. 
- Anthony's details for the map are :  **Anthony Pichardo VA - Office of Mental Health and Suicide Prevention, Menlo Park, CA**

2. Update issue **#853** for **John Klocek** it should say on the map **VA - Office of Mental Health and Suicide Prevention, Waco, TX**

3. Update in the map **Kathryn Azevedo Mendoza**  name is incorrect it currently says: **Katherin Azevedo-Mendoza** 

thank you!,
Rita

**Comment by ritahitching** [comment]
@jamesmrollins 
Hi James, will you please finish up these final updates to the mtl.how/team website:

**Map:**
1: Update in the map Kathryn Azevedo Mendoza name is incorrect it currently says: Katherin Azevedo-Mendoza
2: Extra floating head of Stacey in West Coast section of the map
3. Add Anthony Pichardo and Ash Nazarizadeh
4. Andrea L. Nevedal photo is located in the East Coast section of the map but the description says Palo Alto.  Please move her photo. 

**Main Team Page**
1. Ash Nazarizadeh photo missing

thanks!
Rita

**Comment by jamesmrollins** [comment]
@ritahitching please get Stacey to merge Ash's photo so I can process.  Thanks

**Comment by ritahitching** [comment]
@jamesmrollins we need the following changes please:

**Map:**
1:  **Kathryn Azevedo Mendoza** name is incorrect it currently says: Katherin Azevedo-Mendoza
2: Extra floating head of Stacey
3. Add Anthony Pichardo and Ash Nazarizadeh photo and title - to match others in Menlo Park.
**Anthony Pichardo Office of Mental Health and Suicide Prevention, Menlo Park, CA**
**Ash  Nazarizadeh Office of Mental Health and Suicide Prevention, Menlo Park, CA**
4. **Andrea Nevedal's** photo and location is on the East Coast, but the address says Palo Alto.  Please move her to the West Coast.

**Webpage**
1. **Ash Nazarizadeh's** photo is  missing

**Comment by jamesmrollins** [comment]
Hi @ritahitching - sorry don't mean to drag this on.  Perhaps I have it right this time . . . 

- [x] 1: Kathryn Azevedo Mendoza name is incorrect it currently says: Katherin Azevedo-Mendoza
- [x] 2: Extra floating head of Stacey
- [x] 3. Add Anthony Pichardo and Ash Nazarizadeh photo and title - to match others in Menlo Park.
   - Anthony Pichardo **VA -** Office of Mental Health and Suicide Prevention, Menlo Park, CA
   - Ash Nazarizadeh **VA -** Office of Mental Health and Suicide Prevention, Menlo Park, CA
- [x] 4. Andrea Nevedal's photo and location is on the East Coast, but the address says Palo Alto. Please move her to the West Coast.

Webpage
- [x] Ash Nazarizadeh's photo is missing

_NOTES_
_1. Ash's photo does not have adequate resolution and aspect ratio.  Please retake and I can update his photos._
_2. Everyone's title has, "VA -" in front of, "Office of Mental Health and Suicide Prevention, Menlo Park, CA" so I took the liberty to add that in._

**Comment by ritahitching** [comment]
@jamesmrollins 
This looks great. thanks!
