### ISSUE TITLE
MTL Sim UI Cookies Typo

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#898]
**1. Add description:** 

Not sure where to find and how to edit the Cookies Pop-Up typos on the mtl.how/test log-in page.

<< Paste screenshots here>>
<img width="771" alt="Screen Shot 2020-01-21 at 9 56 37 AM" src="https://user-images.githubusercontent.com/59668647/72829840-68a79300-3c34-11ea-9f73-828e1320c932.png">

 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by jamesmrollins** [comment]
Hi @lijenn 
These items are edited by my DEV team, so there is no place for you to edit.  If you find anything like this in the future, screen capture it, and highlight the error using the highlighter in the Snip Tool. What is the typo you are concerned about above?  Is it the "t" in "to?"  If so, I will address it.  It is supposed to be a single sentence - didn't quite come out right.

**Comment by lijenn** [comment]
Closing this issue and merging it to #864 for continuation over there.
