### ISSUE TITLE
Syllabus: Administrator Training

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#918]
### Introduction

The table below outlines key concepts and activities we will be cover each week, to prepare you to be a competent administrator of the enterprise platforms we use to manage Team PSD.  Team PSD uses Forio Epicenter (https://forio.com/products/epicenter/) to develop and distribute the simulation user interface (Sim UI), and GitHub  (https://github.com/lzim/teampsd/) manage changes to _Modeling to Learn_products and provide training and support to users (http://mtl.how/). Learners are expected to review any readings and ensure they can access listed url's prior to scheduled training. While these are not "graded" modules, per say, we will require practical exercises, knowledge checks and proctored evaluations of each desired skill. 

### Weekly Topics
| *Week* | *Topic Covered* | *Links to Learning Materials* |
|--------|-------|----------|
| 1 - 1/31 | **Team PSD Policies and Procedures** <br> - Governing Principles <br> - Responsibilities <br> - Workgroups, definitions and labels <br> - Kanban Management System <br> - Monthly Sprint Management / Workgroup Leads Meeting Management <br> **Markdown** | - [SOP on mtl.how/teampsd Wiki](https://github.com/lzim/teampsd/wiki/TeamPSD-Policy-&-Procedure-SOP) <br> - [GitHub Repositories](https://github.com/lzim/teampsd/blob/master/resources/training_guides/github/repositories.md)<br> - [Markdown Language](https://github.com/lzim/teampsd/blob/master/resources/training_guides/r/markdown.md)   |
| 2 - 2/7 | **TeamPSD Principles** <br> **Issues & Pull Requests** <br> - Creating new issues for each type of tracker <br> - Understanding how issues move forward/backward within trackers <br> - Create & edit files and file pathways <br> - Create a pull request   | - [TeamPSD principles on mtl.how/teampsd Wiki](https://github.com/lzim/teampsd/wiki/TeamPSD-Policy-%26-Procedure-SOP#governing-principles) <br> - [Issues & Trackers](https://github.com/lzim/teampsd/blob/master/resources/training_guides/github/issues_and_trackers_management.md) <br> - [New File](https://github.com/lzim/teampsd/blob/master/resources/training_guides/github/new_file.md) <br> - [Pull Requests & Branches](https://github.com/lzim/teampsd/blob/master/resources/training_guides/github/pull_requests_and_branches_management.md) <br> - [Adobe Connect; mtl.how/live](https://github.com/lzim/teampsd/blob/master/resources/training_guides/mtl_how_live/host_login.md) |
| 3 - 2/14 Review Existing Resources & Develop Maps | **mtl.how** <br> - Overview of mtl.how Resources <br> - Community of Practice Support <br> - Wiki Management |  Stacey will provide "scavenger hunt" questions |
| 4 - 2/21 Review Existing Resources & Develop Maps | **Team PSD Website Administration** <br> - Logging into Admin Website  <br> - Website Overview, Familiarization and Epicenter Dependencies <br> - Resource Management <br> - Biographies and Photo Management <br> - Using Special Characters (md text) <br> - Updating the Slider   | Ash & Anthony focus on mapping; Rita & Jenn focus on Dashboard |
| 5 - 2/28 Review Existing Resources & Develop Maps | **MTL Demo Website Administration** <br> - Logging into Admin Website  <br> - Website Overview, Familiarization and Epicenter Dependencies <br> - Managing Demo User Records <br> - Updating Conference Code <br> - Resource Management (adding and populating new sections) <br> - Using Special Characters (md text)  <br> - Updating the Slider (gif constraints) | Ash & Anthony focus on mapping; Rita & Jenn focus on Dashboard |
| 6 - 3/12  Set up Wave Teams w/Stacey |  **RedCap** & **Team Tracker** & **Pre/Post Emails** | Rita & Jenn  |
| 7 - 3/20 Set-up Wave 1 Teams w/Stacey Part 1 | **Splashpage Folder Set-up & Permissions** <br> - Create Team Folders <br> - Permissions <br> - Data UI <br> - Sim UI | Rita & Jenn; **Create directory of teams, emails/disciplines, passwords, session dates/schedule, team leads etc.**  |
| 8 - 3/27 Set-up Wave 1 Teams w/Stacey Part 2 | **Splashpage Folder Set-up & Permissions** <br> - Create Team Folders <br> - Permissions <br> - Data UI <br> - Sim UI | Rita & Jenn; **Create directory of teams, emails/disciplines, passwords, session dates/schedule, team leads etc.**  Cross-ref #978  |
| 9- 4/3 Set-up Wave 1 Teams w/James part 1 | **Epicenter Administration 1** <br> - Navigation and functions <br> - End User Management <br> - File upload procedure <br> - Dynamic data management | Rita & Jenn; **Create directory of teams, emails/disciplines, passwords, session dates/schedule, team leads etc.**   |
| 10 - 4/10  Set Part 1 Set-up Wave 1 Teams w/James| **Epicenter Administration 2** <br> - Group Management <br> - Name and Create Groups <br> - Populate Groups <br> - Add or Delete End Users from Groups <br> - Facilitator Assignment  | Rita & Jenn; **Create directory of teams, emails/disciplines, passwords, session dates/schedule, team leads etc.**   |
| 11 - 4/21 | **Open Science Framework** | Rita & Jenn  |

**Group HW - Try this during an internal team meeting** 
**Meeting Management via Lucid and mtl.how/live** <br> **Adobe Connect; mtl.how/live** <br> - How to Login as Host <br> - Managing Attendees / Guests <br> - Recording Audio & Screen Sessions Sharing Screens <br> - Backup Recording in TeamPSD folder<br> **Lucid** <br> - Lucid Overview (logging in, navigation and resources) <br> - Calendar Management (deleting, cancelling and moving meetings) <br> - Setting up a New Meeting (meeting templates, invites, notices) <br> - Setting up a Call and Recording Meetings <br> - Recording and Tracking Decisions <br> - Document Management (moving docs between Lucid and repositories) <br> - Transferring and Distributing Notes to GitHub and Basecamp. <br> - Common Troubleshooting Issues  |  |

## Links to Resources
**SOP:** https://github.com/lzim/teampsd/wiki/TeamPSD-Policy-&-Procedure-SOP
**TeamPSD - Repositories:** https://github.com/lzim/teampsd/blob/master/resources/training_guides/github/repositories.md
**Markdown Reference Guide:** https://github.com/lzim/teampsd/blob/master/resources/training_guides/r/markdown.md
**How to Use and Manage Labels in GitHub:** https://github.com/lzim/teampsd/blob/master/resources/training_guides/github/labels_management.md
**How to Manage Issues and Use Project Trackers - mtl.how/live:** https://github.com/lzim/teampsd/blob/master/resources/training_guides/mtl_how_live/host_login.md
**How to Make a Pull Request and Make Your Own Branch:** https://github.com/lzim/teampsd/blob/master/resources/training_guides/github/pull_requests_and_branches_management.md
**How to Login and Use Adobe Connect at mtl.how/live:** https://github.com/lzim/teampsd/blob/master/resources/training_guides/mtl_how_live/host_login.md
**Adobe Connect Link:** https://mtl.how/live

**Comment by jamesmrollins** [comment]
https://mtl.how/live

SOP: https://github.com/lzim/teampsd/wiki/TeamPSD-Policy-&-Procedure-SOP
TeamPSD -repositories: https://github.com/lzim/teampsd/blob/master/resources/training_guides/github/repositories.md
Markdown - https://github.com/lzim/teampsd/blob/master/resources/training_guides/r/markdown.md
Labels Management - https://github.com/lzim/teampsd/blob/master/resources/training_guides/github/labels_management.md
Issues and Trackers Management - mtl.how/live: https://github.com/lzim/teampsd/blob/master/resources/training_guides/mtl_how_live/host_login.md
Pull Requests and Branch - https://github.com/lzim/teampsd/blob/master/resources/training_guides/github/pull_requests_and_branches_management.md
mtl.how/live: https://github.com/lzim/teampsd/blob/master/resources/training_guides/mtl_how_live/host_login.md

**Comment by staceypark** [comment]
**Next Steps**
- [ ] @staceypark will update the syllabus to make sure all facilitate-related critical tasks are trained on by end of February
- [ ] On Friday 2/28, @branscombj @dlkibbe will join the training from 1-2pm Pacific / 4-5pm Eastern
- [ ] @staceypark will send the Lucid invitation for joining this meeting
