### ISSUE TITLE
Due Discuss 2/14 Purchase WiFi Hotspot 

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#931]
**1. Purchase WiFi team PSD** 

Use the ATT 2TE model (https://www.att.com/buy/connected-devices-and-more/att-unite-express-2-black.html).
Purchased through ReqLogic an unlimited data plan with ATT - estimated cost of $100 monthly which included the WiFi hardware.
Data plan offers a main and guest plan. Main plans has a fixed password login that can support 8 devices simultaneously. The guest plan has a daily changing password and can support 3 devices concurrently.
Benefits: Hotspot does not block websites the VA typical does, can be moved to improve bandwidth and is relatively reliable for general web access.
Drawbacks: Hotspot coverage poor when downloading and uploading files.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by ritahitching** [comment]
@lzim good morning 😄 

**Purchase WiFi hotspot for teamPSD Update**
1. A summary of the various data plans can be found in our shared drive: folder **pavir expenses** then **wifi_hotspot**
2. Spoke with Luanne regarding the requisition I put in through ReqLogic for the WiFi hotspot (REQ#83973) and she provided the following recommendations: options are $40, $70 or $100
- ReqLogic does not provide requisition support for phone data plans. The recommendation is that you purchase a line directly from a carrier (e.g. AT&T), and be reimbursed monthly through your paycheck up to the value of $50. I confirmed this was possible for you as a non-Pavir employee.  I added the form needed for reimbursement to the same "wifi_hotspot** folder.
- Leanne recommended getting a WiFi hotspot device from Mary Thorton  rather than making a ReqLogic requisition - I emailed Mary asking for guidance on the process.  
3. Shannon's team purchased their devise outright through ReqLogic and are on the monthly $37.00 data plan which provides unlimited data for up to 10 devices.  They get a non-profit discount as Shannon is VA/Stanford through Pavir - team is not sure how the data plan is purchased.

**Comment by ritahitching** [comment]
> **1. Purchase WiFi team PSD**
> 
> Use the ATT 2TE model (https://www.att.com/buy/connected-devices-and-more/att-unite-express-2-black.html).
> Purchased through ReqLogic an unlimited data plan with ATT - estimated cost of $100 monthly which included the WiFi hardware.
> Data plan offers a main and guest plan. Main plans has a fixed password login that can support 8 devices simultaneously. The guest plan has a daily changing password and can support 3 devices concurrently.
> Benefits: Hotspot does not block websites the VA typical does, can be moved to improve bandwidth and is relatively reliable for general web access.
> Drawbacks: Hotspot coverage poor when downloading and uploading files.
> 
> **Workgroups leads**
> **Identify Constraints (check all that apply):**
> 
> * [ ]    Capacity
> * [ ]    Cost
> * [ ]    Schedule
> * [ ]    Interference
> * [ ]    Capability
> * [ ]    Other (describe)
> 
> _Add estimated person-hours to complete:_
> 
> **Edit the due date (if necessary)**

**Update**
Purchase WiFi hotspot for teamPSD
PAVIR does not provide support for phone line requisitions.  The recommendation is the PI purchase a line directly from a carrier (e.g. AT&T).  The PI is then reimbursed monthly through their paycheck up to the value of $50.  I have the form for the paycheck reimbursement and added it to the HQ meeting agenda for review.

**Comment by ritahitching** [comment]
@lzim 
I spoke with Mary Thornton at PAVIR and I can pick up a **no cost WiFi hotspot (hardware with unlimited data plan)**  for our team on  **Wednesday Feb 12**.  
I am happy to go and pick up the WiFi when I go to work at the VA Palo Alto.  
Please let me know if you are OK with this no cost solution.  
thanks
Rita

**Comment by staceypark** [comment]
@ritahitching I'm not sure why this is in the issue column (as well as some other issues) if this is not a product that exists that is "broken"

**Comment by ritahitching** [comment]
I'm closing this issue as we have a WiFi hotspot from Pavir.
