### ISSUE TITLE
Move data_script to quant_workgroup

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#94]
@saveth Are we ready to next data_script within quant_workgroup?

I didn't want to move it if it would be disruptive.
But, if it's ready to be moved, please move it to within the workgroup.

Thanks!

Lindsey

**Comment by saveth** [comment]
@lzim @joycepyang 
My code has fully merged with the Master data_script folder. I believe all of Joyce's code has not merged with the Master's data_script folder. If she's ready, then we're ready to move the folder.
