### ISSUE TITLE
Sim UI Meeting Management

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#943]
This issue is created to track meeting management tasks that include:

1.  Preparing SIM UI agenda items for Workgroup Leads Meeting.
2.  Preparing reports and budgets for Praxis Monthly Meeting.
3.  Preparing documents and related items not directly associated with another issue number.

**Comment by lzim** [comment]
@jamesmrollins 

Can this be closed?

**Comment by jamesmrollins** [comment]
@lzim.  I set up a process to relate issues in GitHub to my hours tracking log. That way I can audit back to an approved original request or activity.  Certainly, open on-going administrative issues like this can nag us, but can we keep this one for me?  Thanks, James

**Comment by lzim** [comment]
@jamesmrollins 

Sounds like you’re saying #943 will just sit here?
Yes. We can keep it, if you need it. 
I’ve taken it off **go_live.**
