### ISSUE TITLE
Sim UI - Set up a TEST - Break/Fix Instance

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#949]
**1. Add description:** 
Set up a TEST-Fast instance that will be used to make small changes ( 8 hours or less) to the Sim UI.  Rename current TEST instance TEST-Slow and use for larger changes that require development hours over 8 hours. 

**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_8 hours.

**Edit the due date (if necessary)**

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire.  Please configure a **MTL TEST-Break/Fix** project in Epicenter.  

1. Leave Issue #339 https://github.com/lzim/teampsd/projects/7#card-26088770 Participatory Learning, Design and Research on MTL TEST. **This will be re-spec'd and redeveloped.** However, rest assured we will be using much of the current functionality. 

2.  Leave Issue #775  https://github.com/lzim/teampsd/projects/7#card-29555133 on MTL DEV until further notice. 

_Migrate the following features to this instance for evaluation, test and release:_

1. #620 - https://github.com/lzim/teampsd/projects/7#card-28149999 Gravatar.  This cleared for PROD.
2. #886 - https://github.com/lzim/teampsd/issues/886#issue-548335731 Screen Captures not Crisp (this has not been documented yet). However, all .svg icons that we updated to make more crisp at all resolutions.
3.  #797 - https://github.com/lzim/teampsd/issues/797#issuecomment-569777662 Psy Model: Sankey Diagram not Portraying Data Correctly.  This is @jamesmrollins and @TomRust action - I have listed it here so we don't forget to migrate to PROD.

**Comment by jamesmrollins** [comment]
UPDATE:

1.  #620 Gravatar Issue can be closed - is now on PROD.
2.  Break-fix loop is set up:  https://forio.com/app/va/va-psd-test-breakfix/login.html

![image](https://user-images.githubusercontent.com/30132017/74362701-0565d800-4d7e-11ea-8a02-74533f26ccea.png)

**Comment by staceypark** [comment]
Completed per 2/24 workgroup leads meeting
