### ISSUE TITLE
Photos in the Sim UI via Gravatar

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#95]
Hi @jamesmrollins,

Can you clarify how we all get our photos in the sim UI?

I believe we just need to upload a photo at Gravatar and use the same email at Gravatar that we use to log-in to the sim. Is that correct? And, is that what other users would need to do too?

Thanks!

Lindsey
@dlounsbu @jamesmrollins @TomRust @dlkibbe @branscombj

**Comment by jamesmrollins** [comment]
Yes, that is all one would need to do.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
