### ISSUE TITLE
mtl_red_part_1

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#950]
# mtl_red_part_1 CHECKLIST

## 1. Link to the document and add relevant team members to the card.
- [x] Add the link the current draft of the documentation for the issue:
https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/facilitator_say/mtl_red_part_1_say.md

## 2. Link to issues that must be edited in the document in the **issue_tracker** and **feature_tracker.** _(use the # for the link to the issue)_
- [x] Issue #451 
- [x] Issue #487
- [x] Issue #430  
- [x] Issue #419 
- [x] Issue #440  

## 3. Team Review
- [x] Fidelity - check with Lindsey
- [x] Data UI - check quant_workgroup
- [x] Sim UI - check with model_workgroup and/or sim_workgroup

## 4. Review and Open Pull Requests _(use the # for the link to the pull request)_
- [x] Check the draft for typos
- [x] Check or open a pull request for the document edits

## 5. Review and/or Update Graphics
- [x] Screenshots
- [x] Gifs
- [x] Logos/Icons
- [x] Links

## 6. Dependencies
- [x] Make sure that any edits you make that need to be added to **depend_product** are tracked (e.g., _MTL Video_)

## 7. Close Pull Requests
- [x] Request review and/or close open pull requests for the document

**Comment by anazariz** [comment]
Should "s02 CHECKLIST" be changed to "mtl_red_part_1_Facilitator_Say"?

**Comment by branscombj** [comment]
@staceypark @anazariz I'm not clear about his question, but the MTL Red Part 1 Facilitator SAY guide is [here ](https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/facilitator_say/mtl_red_part_1_say.md); the s02-05 Checklists for MTL Blue need to be created. As well as checklists for MTL Red Part 1&2.

**Comment by lzim** [comment]
Hi @branscombj 🤣 

This is the same issue as a couple of others, which is that @anazariz reviewed this himself, but did not check off all the boxes for a complete document_tracker review.

Assigning back to you & let me know if you have any questions. Thanks!
FYI: @staceypark
