### ISSUE TITLE
F/up IT 3* per week (last date f/up 2/14)  to Installation Request R, R Studio, and Microsoft SQL Server Management Studio

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#966]
**1. Software Installation** 

Rita submit IT helpdesk ticket for Savet's old machine in Lindsey's office for R, R Studio, and Microsoft SQL Server Management Studio

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost 
- [x]   Schedule - 3 times weekly - call  IT
- [x]   Interference - preventing Qual team from doing their work
- [ ]   Capability 
- [ ]   Other (describe)

_Add estimated person-hours to complete:_ Allocating emergent issue time during the week to follow up 

**Edit the due date (if necessary)** Estimated end of Feb - request placed in Jan

**Comment by ritahitching** [comment]
Update
I followed up again with IT helpdesk on the ticket we submitted Jan 24 to install R, R Studio, and Microsoft SQL Server Management Studio - ticket remains open and without a triage a date. Sent Mary an email asking if she can request to have the ticket expedited.

**Comment by ritahitching** [comment]
Re-submitted an IT helpdesk ticket and expedited the process with Mary to to install R, R Studio, and Microsoft SQL Server Management Studio.

**Comment by ritahitching** [comment]
Continue to ask IT to triage ticket - ideal due date end of Feb 2020

**Comment by lzim** [comment]
Hi @ritahitching 

I think that this could make more progress with greater detail on the issue ticket. I've approved the request, and I see it's been closed 3 times now, which is a good sign that that OIT doesn't have what they need to follow through on it.

**Comment by ritahitching** [comment]
@lzim 
I checked Ash's machine in your office and R Studio and SQL have been installed.
I will close this issue.
thanks!
