### ISSUE TITLE
3/20 MTL Facilitate and EES Support Needs

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#978]
@staceypark Here are some tasks and functions that the Facilitate &/or EES work group will need HQ's support on or will divvy up with HQ (@lijenn @ritahitching ) - for your consideration for training and prep prior to launch:

Apps administrative tasks and trouble-shooting:
- [x] data UI
- [x] sim UI (user and facilitator)
- [x] mtl.how/live (web conferencing)
- [x] audio conferencing
- [x] Lucid meetings or MS Teams
- [x] mtl.how
- [x] mtl.how/menu

Communications tasks and trouble-shooting:
- [x] Maintain for internal use only: directory of team name, MTL arm, start date, co-facilitators, meeting times, team members, credentials and disciplines, VA email addresses, sim UI passwords, TMS links, team lead(s).
- [x] Create a subset of directory (first 5 items) to send to EES for accreditation and TMS posting.
- [x] Pre- and post-session mailings
- [x] Forward email incoming to appropriate facilitators/TeamPSD members

**Comment by staceypark** [comment]
@branscombj Thanks for this list! 😄 
These are all items that @jamesmrollins and I plan to train on during our weekly Friday training sessions. We have been meeting at 3pm Pacific / 6pm Eastern to review the training for each week, but perhaps we can meet earlier and you can join that planning/review meeting, even if you don't join the training, to make sure we are on track?

**Comment by branscombj** [comment]
@staceypark Sure, I could join y'all to review topics & progress on Friday afternoons. Unfortunately this Friday I'm booked until 4pm my time (and loathe to stay past 5 ❤️); the next three Fridays I'm free at 3:00, 2:30, and all day, respectively.

**Comment by staceypark** [comment]
@branscombj whoops my bad I left out the day of the week.
We review the plan on Wednesday (@6pm Eastern - but can be earlier) and do the actual training on Friday (@4-7pm Eastern)

**Comment by branscombj** [comment]
@staceypark Ah! On Wednesdays I don't any have standing conflicts after MTL Facilitate Launch. So good this Wednesday and next. Then not available the following 2 Wednesday afternoons, then OK again.

**Comment by ritahitching** [comment]
@staceypark @lijenn 

I updated the agenda for **Friday's 2/14 Training** session to  include details of Jane joining to make sure the training is focused on meeting the **Facilitate Workgroup's** needs in time for the launch.
Please let me know if there anything else I should add/do.
thanks,
Rita

**Comment by staceypark** [comment]
@ritahitching No, that is not what Jane and I have agreed on yet. Please DO NOT update the training agenda (unless you have training-related questions you need addressed) as James/I (and now Jane) are running point for that to train *you* (and others) and determining what we will do.

Also, if you read Jane's message above, she specifically says she is NOT available this Friday during our training time. Please read other folks messages carefully before making changes, and think through how the point persons / workflow are outlined in the SOP.

**Comment by ritahitching** [comment]
> @ritahitching No, that is not what Jane and I have agreed on yet. Please DO NOT update the training agenda (unless you have training-related questions you need addressed) as James/I (and now Jane) are running point for that to train _you_ (and others) and determining what we will do.
> 
> Also, if you read Jane's message above, she specifically says she is NOT available this Friday during our training time. Please read other folks messages carefully before making changes, and think through how the point persons / workflow are outlined in the SOP.

Got, I'm sorry. I did not read this before changing the title.

**Comment by staceypark** [comment]
cross-ref in #918 and closing
