### ISSUE TITLE
session 6 in-session activity for review

### ISSUE THREAD

**Issue by dlkibbe** [lzim/teampsd#98]
Please review this session 6 in-session activity @lzim @staceypark @TomRust @dlounsbu @branscombj 
teampsd/mtl_facilitate_workgroup/mtl_live_guide/session6_in_session_activity.rmd

**Comment by lzim** [comment]
@lzim @staceypark @TomRust @dlounsbu @branscombj @kibbe

We discussed this yesterday. **Please see the Lucid notes from our meeting, which breaks down the next steps for these guides by the four days of the *MTL Facilitate Pilot*.**

Team members will:
1) **sync their own branch with Master before they do any work.** Make sure you have the latest copy of that file : )**
2) work on guides on their own branch in this folder location: TeamPSD/mtl_facilitate_workgroup/mtl_facilitate_pilot/ then the day folder for whatever *MTL Facilitate Pilot* day that in-session guide or mutual learning activity will be covered 
3) when done with your work, commit to your own branch, and open a pull request to request team review. Please use project workflow/tracking options on the right menu to call out someone/all of us. For example, please mention @lzim and I’ll take a look, be sure to add the request to the TeamPSD project
4) **always sync your branch to Master** to stay current with others’ work and make sure you’re working on the latest copy of a file, including edits, formatting or comments from others.

Thanks!

Lindsey
Closing this issue.
