### ISSUE TITLE
2020_02_17-Splash Page Button Triage

### ISSUE THREAD

**Issue by anazariz** [lzim/teampsd#980]
**1. Add description:** 

We need to triage the splash page to better understand the problem and come up with a fix.
<< Paste screenshots here>>
 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [x]   Cost: 8
- [x]   Schedule: 2/17
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_8

**Edit the due date (if necessary)**

**Comment by staceypark** [comment]
1. Refresh Data connections on Splashpage do not work. Have narrowed the issue down to the SharePoint level, as it works in the SplashMothership.

**Comment by anazariz** [comment]
Triage was performed on 2/26 with @anazariz , @anthonycpichardo  and @staceypark as follows:
1-SplashMothership was copied to prevent unintentional code change  
2-A SQL Code walk-through was performed to understand the logic
3-Server segments of the SQL code was run on CDW to compare results with the results in various sheets of the workbook
A walk-through was conducted with Andrew to validate understanding. 

 @anthonycpichardo I recommend that we close this ticket and continue with the fix.
