### ISSUE TITLE
2020_02_27 + Splash Page Fix

### ISSUE THREAD

**Issue by anazariz** [lzim/teampsd#981]
**1. Add description:** 

Fixing the Splash Page based on triage from #980
<< Paste screenshots here>>
 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by anthonycpichardo** [comment]
vizMeas vizDiag and vizEnc are missing buttons, need to go through the video and find them

**Comment by anthonycpichardo** [comment]
Notes:
ScaleOfAction filter missing from vizMeas

**Comment by anthonycpichardo** [comment]
Should be able to see data value when you hover over the dots

**Comment by anthonycpichardo** [comment]
Look at Session 02 video's filter functions and take an inventory of which ones are missing:

- vizEncounter - missing Division

**Comment by anthonycpichardo** [comment]
#980  Triage was performed on 2/26 with @anazariz , @anthonycpichardo and @staceypark as follows:
1-SplashMothership was copied to prevent unintentional code change
2-A SQL Code walk-through was performed to understand the logic
3-Server segments of the SQL code was run on CDW to compare results with the results in various sheets of the workbook
A walk-through was conducted with Andrew to validate understanding.

**Comment by anthonycpichardo** [comment]
Documentation being completed as part of #626
