### ISSUE TITLE
Deadline 2/21  LucidMeeting - calendar invitation and link are not working 

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#982]
**LucidMeeting Broken Links:** 

Follow up with LucidMeeting - that calendar invitation and link are not working - experiencing problems. Lindsey will send additional information.
-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)** Ideally before next MTL Launch meeting 2/19

**Comment by staceypark** [comment]
@lijenn can this be closed?

**Comment by lijenn** [comment]
@staceypark Am still in communication with Lucid. Will most likely be resolved today or no later by tomorrow. I can update the deadline right now.
