### ISSUE TITLE
wk4 feb_epic: MTL Red Pre/Post emails: Add specific dates/time & co-facilitators & meeting links

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#983]
Add specific dates/time & co-facilitators & meeting links, & TMS course code.

**Comment by lijenn** [comment]
at jane & debby:
Jane, I really love the guide you made that was sent in the email.

How about this as the body template?
- Program description: a small blurb for each of the 12 sessions 
   - i.e Session 1: Team Vision - Teams will develop individual goals into a shared Team vision
- Registration: Pre-registration is only necessary if users want to receive credit. Must go through specific team link
-

**Comment by ritahitching** [comment]
@lijenn I will work on the email template while you finish your Epicenter homework.

**Comment by lzim** [comment]
@lijenn I've edited the title to "wave1" for due date to reflect that this is for **wave1_teams**

**Comment by lijenn** [comment]
Jenn to ping Joe and see if we can get the course codes for Fresno. And, make sure he's got clarity about yesterday, and add to pre/post emails

**Comment by lijenn** [comment]
In progress of getting dates confirmed by EES and confirmed dates are already done/in progress for pre/post emails for sites that we are about to begin with. Issue cards for this have been broken down by team and cards that require team-tailoring now tracked in the lzim/mtl_team_tracker to ensure privacy. Closing this card.
