### ISSUE TITLE
Sim UI-More Info section content cut off

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#989]
**1. Add description:** 

The content in the section describing the AGG module is cut off at the bottom of the section by the next blue bar.

![image](https://user-images.githubusercontent.com/29778290/74499722-9f2ea180-4eb2-11ea-8f74-d2ef05008427.png)
 
**2. Click on the right:**  
a. **Projects** - assign to **issue_tracker.**  
b. **Assignee** - assign relevant team members.  
c. **Labels**- review and select labels to indicate the responsible workgroup and all potential dependencies 
d. **Milestones** - select the dependent milestone.  

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by jamesmrollins** [comment]
@branscombj I recommend we close this issue as we will be redesigning this page.

**Comment by jamesmrollins** [comment]
This will be cross referenced in the MTL More Information redesign.
