### ISSUE TITLE
Wording of AGG description in sim UI More Info page

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#991]
**1. Add description:** 
The short blurb describing the AGG module in S04 Say was identical to that of CC. I modified slightly. We may want to modify the description used in other places. The one I know of is in the sim UI More Info page.
Here is what I proposed in #990 :
AGG shows how a variety of team decisions interact to affect your overall mix of services. You can explore trade-offs between decisions such as desired new patient wait times, current patient return visit intervals, and overbooking, and how they affect team outcomes like total missed appointments, number of patients in care, and number of patients completing care. You can compare the effects of different decisions on outcomes in one service, or you can compare the effects of one decision on different services.

**2. Click on the right:**  
a. **Projects** - assign to **issue_tracker.**  
b. **Assignee** - assign relevant team members.  
c. **Labels**- review and select labels to indicate the responsible workgroup and all potential dependencies 
d. **Milestones** - select the dependent milestone.  

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by staceypark** [comment]
@jamesmrollins alert for More Info

**Comment by jamesmrollins** [comment]
@branscombj  - Did you intend for your AGG description written above, to update the one provided in the Sim UI Expanded Outputs?  See below.  **If not** . . . I intended to use the description below in the MTL More Info pages.  They were supposed to be consistent with each other in the first place . . . **If so**, then I will change both.

![image](https://user-images.githubusercontent.com/30132017/77487383-9608ec80-6def-11ea-9b84-333ba7769b19.png)

**Comment by branscombj** [comment]
@jamesmrollins No, you can use that in both of those places. Except please use this slightly edited version, thanks!

This model shows interactions among all the services offered by your team. It allows you to experiment with how you allocate time across services and how you manage within-team referrals after patient review. It also lets you explore your team’s willingness to use overtime as a solution to a large backlog of appointments and how sensitive your team’s care quality, morale, and burnout are to working long hours.

**Comment by branscombj** [comment]
Complete.
